import type { CodenamesSeed } from './types';

export const popcultureWords: CodenamesSeed[] = [
  { de: 'Batman', en: 'Batman' },
  { de: 'Superman', en: 'Superman' },
  { de: 'Spider-Man', en: 'Spider-Man' },
  { de: 'Hulk', en: 'Hulk' },
  { de: 'Thor', en: 'Thor' },
  { de: 'Iron Man', en: 'Iron Man' },
  { de: 'Joker', en: 'Joker' },
  { de: 'Wonder Woman', en: 'Wonder Woman' },
  { de: 'Captain America', en: 'Captain America' },
  { de: 'Deadpool', en: 'Deadpool' },
  { de: 'Marvel', en: 'Marvel' },
  { de: 'Darth Vader', en: 'Darth Vader' },
  { de: 'Yoda', en: 'Yoda' },
  { de: 'Luke Skywalker', en: 'Luke Skywalker' },
  { de: 'Chewbacca', en: 'Chewbacca' },
  { de: 'R2-D2', en: 'R2-D2' },
  { de: 'Jedi', en: 'Jedi' },
  { de: 'Lichtschwert', en: 'Lightsaber' },
  { de: 'Stormtrooper', en: 'Stormtrooper' },
  { de: 'Star Wars', en: 'Star Wars' },
  { de: 'Harry Potter', en: 'Harry Potter' },
  { de: 'Hermine', en: 'Hermione' },
  { de: 'Voldemort', en: 'Voldemort' },
  { de: 'Dumbledore', en: 'Dumbledore' },
  { de: 'Hogwarts', en: 'Hogwarts' },
  { de: 'Gandalf', en: 'Gandalf' },
  { de: 'Frodo', en: 'Frodo' },
  { de: 'Gollum', en: 'Gollum' },
  { de: 'Herr der Ringe', en: 'Lord of the Rings' },
  { de: 'Shrek', en: 'Shrek' },
  { de: 'Mario', en: 'Mario' },
  { de: 'Luigi', en: 'Luigi' },
  { de: 'Yoshi', en: 'Yoshi' },
  { de: 'Pikachu', en: 'Pikachu' },
  { de: 'Pokémon', en: 'Pokémon' },
  { de: 'Sonic', en: 'Sonic' },
  { de: 'Zelda', en: 'Zelda' },
  { de: 'Tetris', en: 'Tetris' },
  { de: 'Minecraft', en: 'Minecraft' },
  { de: 'Fortnite', en: 'Fortnite' },
  { de: 'Pac-Man', en: 'Pac-Man' },
  { de: 'Lara Croft', en: 'Lara Croft' },
  { de: 'GTA', en: 'GTA' },
  { de: 'FIFA', en: 'FIFA' },
  { de: 'Die Sims', en: 'The Sims' },
  { de: 'Candy Crush', en: 'Candy Crush' },
  { de: 'Among Us', en: 'Among Us' },
  { de: 'Roblox', en: 'Roblox' },
  { de: 'Tamagotchi', en: 'Tamagotchi' },
  { de: 'Gameboy', en: 'Game Boy' },
  { de: 'PlayStation', en: 'PlayStation' },
  { de: 'Xbox', en: 'Xbox' },
  { de: 'Nintendo', en: 'Nintendo' },
  { de: 'Zauberwürfel', en: "Rubik's Cube" },
  { de: 'Monopoly', en: 'Monopoly' },
  { de: 'Uno', en: 'Uno' },
  { de: 'Scrabble', en: 'Scrabble' },
  { de: 'Jenga', en: 'Jenga' },
  { de: 'Twister', en: 'Twister' },
  { de: 'Barbie', en: 'Barbie' },
  { de: 'Lego', en: 'Lego' },
  { de: 'Playmobil', en: 'Playmobil' },
  { de: 'Titanic', en: 'Titanic' },
  { de: 'Avatar', en: 'Avatar' },
  { de: 'Matrix', en: 'Matrix' },
  { de: 'Rocky', en: 'Rocky' },
  { de: 'Rambo', en: 'Rambo' },
  { de: 'Terminator', en: 'Terminator' },
  { de: 'Godzilla', en: 'Godzilla' },
  { de: 'King Kong', en: 'King Kong' },
  { de: 'Dracula', en: 'Dracula' },
  { de: 'Frankenstein', en: 'Frankenstein' },
  { de: 'James Bond', en: 'James Bond' },
  { de: 'Indiana Jones', en: 'Indiana Jones' },
  { de: 'Sherlock', en: 'Sherlock' },
  { de: 'Jack Sparrow', en: 'Jack Sparrow' },
  { de: 'Tarzan', en: 'Tarzan' },
  { de: 'Pinocchio', en: 'Pinocchio' },
  { de: 'Aschenputtel', en: 'Cinderella' },
  { de: 'Schneewittchen', en: 'Snow White' },
  { de: 'Rapunzel', en: 'Rapunzel' },
  { de: 'Arielle', en: 'Ariel' },
  { de: 'Elsa', en: 'Elsa' },
  { de: 'Simba', en: 'Simba' },
  { de: 'Aladdin', en: 'Aladdin' },
  { de: 'Mulan', en: 'Mulan' },
  { de: 'Peter Pan', en: 'Peter Pan' },
  { de: 'Mary Poppins', en: 'Mary Poppins' },
  { de: 'Willy Wonka', en: 'Willy Wonka' },
  { de: 'Micky Maus', en: 'Mickey Mouse' },
  { de: 'Donald Duck', en: 'Donald Duck' },
  { de: 'Goofy', en: 'Goofy' },
  { de: 'Garfield', en: 'Garfield' },
  { de: 'Snoopy', en: 'Snoopy' },
  { de: 'Homer', en: 'Homer' },
  { de: 'Simpsons', en: 'Simpsons' },
  { de: 'SpongeBob', en: 'SpongeBob' },
  { de: 'Asterix', en: 'Asterix' },
  { de: 'Obelix', en: 'Obelix' },
  { de: 'Tim und Struppi', en: 'Tintin' },
  { de: 'Schlümpfe', en: 'Smurfs' },
  { de: 'Popeye', en: 'Popeye' },
  { de: 'Bugs Bunny', en: 'Bugs Bunny' },
  { de: 'Scooby-Doo', en: 'Scooby-Doo' },
  { de: 'Tom und Jerry', en: 'Tom and Jerry' },
  { de: 'Winnie Puuh', en: 'Winnie the Pooh' },
  { de: 'Grinch', en: 'Grinch' },
  { de: 'Minions', en: 'Minions' },
  { de: 'Pippi Langstrumpf', en: 'Pippi Longstocking' },
  { de: 'Heidi', en: 'Heidi' },
  { de: 'Krümelmonster', en: 'Cookie Monster' },
  { de: 'Kermit', en: 'Kermit' },
  { de: 'Teletubbies', en: 'Teletubbies' },
  { de: 'Sesamstraße', en: 'Sesame Street' },
  { de: 'Mr. Bean', en: 'Mr. Bean' },
  { de: 'Naruto', en: 'Naruto' },
  { de: 'Dragon Ball', en: 'Dragon Ball' },
  { de: 'Sailor Moon', en: 'Sailor Moon' },
  { de: 'Totoro', en: 'Totoro' },
  { de: 'Jurassic Park', en: 'Jurassic Park' },
  { de: 'Toy Story', en: 'Toy Story' },
  { de: 'Findet Nemo', en: 'Finding Nemo' },
  { de: 'König der Löwen', en: 'The Lion King' },
  { de: 'Die Eiskönigin', en: 'Frozen' },
  { de: 'Ghostbusters', en: 'Ghostbusters' },
  { de: 'Der Pate', en: 'The Godfather' },
  { de: 'Top Gun', en: 'Top Gun' },
  { de: 'Transformers', en: 'Transformers' },
  { de: 'Game of Thrones', en: 'Game of Thrones' },
  { de: 'Friends', en: 'Friends' },
  { de: 'Stranger Things', en: 'Stranger Things' },
  { de: 'Squid Game', en: 'Squid Game' },
  { de: 'Breaking Bad', en: 'Breaking Bad' },
  { de: 'Wednesday', en: 'Wednesday' },
  { de: 'Shakira', en: 'Shakira' },
  { de: 'Madonna', en: 'Madonna' },
  { de: 'Beyoncé', en: 'Beyoncé' },
  { de: 'Rihanna', en: 'Rihanna' },
  { de: 'Adele', en: 'Adele' },
  { de: 'Eminem', en: 'Eminem' },
  { de: 'Elvis', en: 'Elvis' },
  { de: 'Michael Jackson', en: 'Michael Jackson' },
  { de: 'Taylor Swift', en: 'Taylor Swift' },
  { de: 'Lady Gaga', en: 'Lady Gaga' },
  { de: 'Ed Sheeran', en: 'Ed Sheeran' },
  { de: 'Billie Eilish', en: 'Billie Eilish' },
  { de: 'Justin Bieber', en: 'Justin Bieber' },
  { de: 'Beatles', en: 'Beatles' },
  { de: 'ABBA', en: 'ABBA' },
  { de: 'Rolling Stones', en: 'Rolling Stones' },
  { de: 'Nirvana', en: 'Nirvana' },
  { de: 'Metallica', en: 'Metallica' },
  { de: 'Rammstein', en: 'Rammstein' },
  { de: 'Coldplay', en: 'Coldplay' },
  { de: 'AC/DC', en: 'AC/DC' },
  { de: 'Daft Punk', en: 'Daft Punk' },
  { de: 'Spice Girls', en: 'Spice Girls' },
  { de: 'Mozart', en: 'Mozart' },
  { de: 'Beethoven', en: 'Beethoven' },
  { de: 'Einstein', en: 'Einstein' },
  { de: 'Picasso', en: 'Picasso' },
  { de: 'Mona Lisa', en: 'Mona Lisa' },
  { de: 'Shakespeare', en: 'Shakespeare' },
  { de: 'Napoleon', en: 'Napoleon' },
  { de: 'Kleopatra', en: 'Cleopatra' },
  { de: 'Chaplin', en: 'Chaplin' },
  { de: 'Marilyn Monroe', en: 'Marilyn Monroe' },
  { de: 'Messi', en: 'Messi' },
  { de: 'Ronaldo', en: 'Ronaldo' },
  { de: 'Tom Cruise', en: 'Tom Cruise' },
  { de: 'Schwarzenegger', en: 'Schwarzenegger' },
  { de: 'Elon Musk', en: 'Elon Musk' },
  { de: 'Netflix', en: 'Netflix' },
  { de: 'YouTube', en: 'YouTube' },
  { de: 'Google', en: 'Google' },
  { de: 'Facebook', en: 'Facebook' },
  { de: 'Instagram', en: 'Instagram' },
  { de: 'TikTok', en: 'TikTok' },
  { de: 'WhatsApp', en: 'WhatsApp' },
  { de: 'Spotify', en: 'Spotify' },
  { de: 'Wikipedia', en: 'Wikipedia' },
  { de: 'iPhone', en: 'iPhone' },
  { de: 'ChatGPT', en: 'ChatGPT' },
  { de: 'Disney', en: 'Disney' },
  { de: 'Tesla', en: 'Tesla' },
  { de: 'Ferrari', en: 'Ferrari' },
  { de: 'Porsche', en: 'Porsche' },
  { de: 'Coca-Cola', en: 'Coca-Cola' },
  { de: "McDonald's", en: "McDonald's" },
  { de: 'Nutella', en: 'Nutella' },
  { de: 'Ikea', en: 'Ikea' },
  { de: 'Nike', en: 'Nike' },
  { de: 'Adidas', en: 'Adidas' },
  { de: 'Oscar', en: 'Oscar' },
  { de: 'Meme', en: 'Meme' },
  { de: 'Selfie', en: 'Selfie' },
  { de: 'Hashtag', en: 'Hashtag' },
  { de: 'Influencer', en: 'Influencer' },
  { de: 'Podcast', en: 'Podcast' },
  { de: 'Bitcoin', en: 'Bitcoin' },
];
