import type { MostLikelyToSeed } from './types';

export const futureQuestions: MostLikelyToSeed[] = [
  { de: 'eine eigene Sekte gründen', en: 'start their own cult' },
  { de: 'zehn Kinder bekommen', en: 'end up with ten kids' },
  {
    de: 'nach Neuseeland auswandern und nie zurückkommen',
    en: 'move to New Zealand and never come back',
  },
  { de: 'mit 30 Millionär sein', en: 'be a millionaire by 30' },
  { de: 'mit 40 noch bei den Eltern wohnen', en: 'still live with their parents at 40' },
  { de: 'Bürgermeister einer Kleinstadt werden', en: 'become mayor of a small town' },
  { de: 'ein Buch schreiben, das niemand liest', en: 'write a book that nobody reads' },
  { de: 'auf einem Bauernhof mit Ziegen enden', en: 'end up on a farm with goats' },
  { de: 'in einer Netflix-Doku auftauchen', en: 'show up in a Netflix documentary' },
  { de: 'Bundeskanzler werden', en: 'become chancellor' },
  {
    de: 'ein Restaurant eröffnen, das nach einem Jahr pleitegeht',
    en: 'open a restaurant that goes bust after a year',
  },
  { de: 'den Job kündigen und Influencer werden', en: 'quit their job to become an influencer' },
  { de: 'mit 60 noch auf Festivals gehen', en: 'still go to festivals at 60' },
  {
    de: 'im Lotto gewinnen und alles in einem Jahr verprassen',
    en: 'win the lottery and blow it all in a year',
  },
  { de: 'mit 25 heiraten und mit 26 geschieden sein', en: 'get married at 25 and divorced at 26' },
  {
    de: 'auf einem Segelboot um die Welt leben',
    en: 'live on a sailboat sailing around the world',
  },
  { de: 'ein Start-up gründen, das niemand versteht', en: 'found a startup nobody understands' },
  { de: 'im Reality-TV landen', en: 'end up on reality TV' },
  { de: 'einen Nobelpreis gewinnen', en: 'win a Nobel Prize' },
  { de: 'als Erstes von uns Großeltern werden', en: 'be the first of us to become a grandparent' },
  { de: 'nie heiraten und damit glücklich sein', en: 'never marry and be totally happy about it' },
  { de: 'eine Wohnung voller Katzen haben', en: 'have an apartment full of cats' },
  { de: 'als Aussteiger im Wald leben', en: 'drop out and live in the woods' },
  {
    de: 'mit Krypto reich werden und alles wieder verlieren',
    en: 'get rich on crypto and lose it all again',
  },
  { de: 'einen Weltrekord aufstellen', en: 'set a world record' },
  { de: 'eine Bar auf Mallorca eröffnen', en: 'open a bar in Mallorca' },
  { de: 'in einem Tiny House leben', en: 'live in a tiny house' },
  { de: 'Professor an einer Uni werden', en: 'become a university professor' },
  { de: 'das eigene Hochzeitsdatum vergessen', en: 'forget their own wedding anniversary' },
  { de: 'Foodblogger werden', en: 'become a food blogger' },
  { de: 'irgendwann ins Kloster gehen', en: 'eventually join a monastery' },
  { de: 'die eigene Firma an Google verkaufen', en: 'sell their company to Google' },
  { de: 'mit 50 noch WG-Partys feiern', en: 'still throw shared flat parties at 50' },
  { de: 'einen Promi heiraten', en: 'marry a celebrity' },
  { de: 'als Erstes von uns in Rente gehen', en: 'be the first of us to retire' },
  {
    de: 'bis 80 arbeiten, weil es ohne langweilig ist',
    en: 'work until 80 because retirement is boring',
  },
  {
    de: 'in die Politik gehen und einen Skandal auslösen',
    en: 'go into politics and cause a scandal',
  },
  { de: 'einen Weinberg erben', en: 'inherit a vineyard' },
  { de: 'auf dem Mars leben wollen', en: 'volunteer to live on Mars' },
  { de: 'Zwillinge bekommen', en: 'have twins' },
  {
    de: 'einen Podcast starten, den nur die eigene Mutter hört',
    en: 'start a podcast only their mom listens to',
  },
  { de: 'Schlagersänger werden', en: 'become a schlager singer' },
  { de: 'ein Hotel in den Bergen führen', en: 'run a hotel in the mountains' },
  {
    de: 'in zehn Jahren in zehn Ländern gewohnt haben',
    en: 'have lived in ten countries within ten years',
  },
  { de: 'die Elternabende an der Schule leiten', en: 'end up running the school parent meetings' },
  { de: 'den Familienbetrieb übernehmen', en: 'take over the family business' },
  { de: 'einen eigenen Wikipedia-Artikel bekommen', en: 'get their own Wikipedia article' },
  { de: 'eine Million Follower haben', en: 'have a million followers' },
  { de: 'Pilot werden', en: 'become a pilot' },
  { de: 'mit 70 noch Skateboard fahren', en: 'still skateboard at 70' },
  { de: 'einen Bestseller schreiben', en: 'write a bestseller' },
  { de: 'in einer Villa mit Pool enden', en: 'end up in a villa with a pool' },
  {
    de: 'alles verkaufen und nur noch mit einem Rucksack leben',
    en: 'sell everything and live out of a backpack',
  },
  {
    de: 'einen Hund haben, der auf Instagram berühmter ist als sie selbst',
    en: 'own a dog that’s more famous on Instagram than they are',
  },
  {
    de: 'Hausmeister der eigenen alten Schule werden',
    en: 'become the caretaker at their old school',
  },
  { de: 'Kinderbuchautor werden', en: 'become a children’s book author' },
  {
    de: 'den Rest des Lebens in Thailand verbringen',
    en: 'spend the rest of their life in Thailand',
  },
  { de: 'Schauspieler in einer Daily Soap werden', en: 'act in a daily soap opera' },
  { de: 'einen Michelin-Stern bekommen', en: 'earn a Michelin star' },
  {
    de: 'als Rentner jeden Tag im Baumarkt sein',
    en: 'spend every day at the hardware store once retired',
  },
  {
    de: 'Vereinsvorsitzender im Kleingartenverein werden',
    en: 'chair the local allotment garden club',
  },
  { de: 'einen Escape-Room eröffnen', en: 'open an escape room' },
  { de: 'ihre Kinder nach Pokémon benennen', en: 'name their kids after Pokémon' },
  {
    de: 'eine Fernbeziehung über drei Kontinente führen',
    en: 'have a long distance relationship across three continents',
  },
  {
    de: 'von heute auf morgen Yogalehrer auf Bali werden',
    en: 'suddenly become a yoga teacher in Bali',
  },
  { de: 'einen Oscar gewinnen', en: 'win an Oscar' },
  {
    de: 'mit 35 eine Midlife-Crisis haben und einen Porsche kaufen',
    en: 'have a midlife crisis at 35 and buy a Porsche',
  },
  { de: 'einen Bauernhof mit Alpakas betreiben', en: 'run an alpaca farm' },
  { de: 'als Hacker im Darknet verschwinden', en: 'disappear into the dark web as a hacker' },
  { de: 'eine Rede vor den Vereinten Nationen halten', en: 'give a speech at the United Nations' },
  { de: 'als Letztes von uns heiraten', en: 'be the last of us to get married' },
  { de: 'als Erstes von uns heiraten', en: 'be the first of us to get married' },
  { de: 'ein eigenes Getränk auf den Markt bringen', en: 'launch their own drink brand' },
  { de: 'Fußballtrainer der Jugendmannschaft werden', en: 'coach a youth football team' },
  { de: 'eine eigene Modelinie rausbringen', en: 'launch their own fashion line' },
  { de: 'mit 45 noch studieren', en: 'still be at university at 45' },
  { de: 'im Fernsehen bei einer Quizshow gewinnen', en: 'win big on a TV quiz show' },
  { de: 'die eigene Insel kaufen', en: 'buy their own island' },
  { de: 'in die Antarktis auswandern', en: 'move to Antarctica' },
  { de: 'einen eigenen Feiertag einführen wollen', en: 'try to create their own public holiday' },
  { de: 'ein Leben lang in der eigenen Heimatstadt bleiben', en: 'never leave their hometown' },
  { de: 'Astronaut werden', en: 'become an astronaut' },
  {
    de: 'jeden Sommer auf demselben Campingplatz verbringen',
    en: 'spend every summer at the same campsite',
  },
  {
    de: 'einen YouTube-Kanal über Modelleisenbahnen betreiben',
    en: 'run a YouTube channel about model trains',
  },
  {
    de: 'die Bürgerinitiative gegen den neuen Kreisverkehr anführen',
    en: 'lead the protest against the new roundabout',
  },
  { de: 'mit 90 noch Tinder benutzen', en: 'still use Tinder at 90' },
  {
    de: 'eine Weltreise machen und als anderer Mensch zurückkommen',
    en: 'go on a world trip and come back a different person',
  },
  { de: 'einen Foodtruck aufmachen', en: 'open a food truck' },
  { de: 'Präsident eines Fanclubs werden', en: 'become president of a fan club' },
  {
    de: 'als Erstes von uns auf einer Briefmarke landen',
    en: 'be the first of us to appear on a stamp',
  },
  { de: 'in einem Science-Fiction-Film mitspielen', en: 'star in a sci-fi movie' },
  { de: 'einen eigenen Whisky brennen', en: 'distill their own whisky' },
  { de: 'ein Haus komplett selbst bauen', en: 'build a house entirely by themselves' },
  { de: 'Tierarzt für Exoten werden', en: 'become a vet for exotic animals' },
  {
    de: 'in zehn Jahren genau dasselbe machen wie heute',
    en: 'be doing exactly the same thing in ten years',
  },
  { de: 'bei einer Castingshow weinend rausfliegen', en: 'get voted off a talent show in tears' },
  {
    de: 'einen Bürojob kündigen und Tischler werden',
    en: 'quit an office job to become a carpenter',
  },
  { de: 'die eigene Biografie mit 30 schreiben', en: 'write their autobiography at 30' },
  { de: 'auf einem Kreuzfahrtschiff arbeiten', en: 'work on a cruise ship' },
  { de: 'Pfarrer werden', en: 'become a priest' },
  { de: 'im Alter eine Rockband gründen', en: 'start a rock band in their old age' },
  {
    de: 'den Rest des Lebens im Wohnmobil verbringen',
    en: 'spend the rest of their life in a camper van',
  },
  { de: 'einen Roboter heiraten', en: 'marry a robot' },
  { de: 'eine Firma mit 500 Mitarbeitern führen', en: 'run a company with 500 employees' },
  { de: 'ein Leben lang Single bleiben', en: 'stay single forever' },
  {
    de: 'im Alter plötzlich zum Heavy-Metal-Fan werden',
    en: 'suddenly become a heavy metal fan in old age',
  },
  {
    de: 'Patenonkel oder Patentante für alle unsere Kinder werden',
    en: 'become godparent to all our kids',
  },
  { de: 'mit 50 einen Marathon laufen', en: 'run a marathon at 50' },
  { de: 'mit der eigenen Oma eine Weltreise machen', en: 'go on a world trip with their grandma' },
  { de: 'Präsident eines Schützenvereins werden', en: 'become president of a shooting club' },
  {
    de: 'nach Japan auswandern und perfekt Japanisch lernen',
    en: 'move to Japan and become fluent in Japanese',
  },
  { de: 'die Welt mit einer Erfindung verändern', en: 'change the world with an invention' },
  { de: 'eine Erfindung machen, die niemand braucht', en: 'invent something nobody needs' },
  {
    de: 'als Erstes von uns in einen Skandal verwickelt sein',
    en: 'be the first of us caught up in a scandal',
  },
  { de: 'in einer Kommune leben', en: 'live in a commune' },
  {
    de: 'einen Bauernhof erben und keine Ahnung haben',
    en: 'inherit a farm and have no clue what to do',
  },
  {
    de: 'im Alter Golf spielen und nichts anderes mehr',
    en: 'play golf in retirement and nothing else',
  },
  { de: 'im Gemeinderat sitzen', en: 'sit on the town council' },
  { de: 'eine Kaffeerösterei eröffnen', en: 'open a coffee roastery' },
  { de: 'ein Tattoostudio eröffnen', en: 'open a tattoo studio' },
  { de: 'ein Leben lang Schulden haben', en: 'be in debt forever' },
  {
    de: 'früh in Rente gehen und dann nur noch reisen',
    en: 'retire early and do nothing but travel',
  },
  { de: 'die eigenen Kinder zu Hause unterrichten', en: 'homeschool their kids' },
  { de: 'ein Museum über sich selbst eröffnen', en: 'open a museum about themselves' },
  { de: 'Gründer einer neuen Partei werden', en: 'found a new political party' },
  {
    de: 'jedes Jahr ein Familientreffen mit 200 Gästen ausrichten',
    en: 'host a family reunion with 200 guests every year',
  },
  {
    de: 'eine Weltmeisterschaft in einer obskuren Sportart gewinnen',
    en: 'win a world championship in an obscure sport',
  },
  { de: 'irgendwann im Guinness-Buch stehen', en: 'make it into the Guinness Book' },
  { de: 'Zahnarzt mit eigener Praxis werden', en: 'become a dentist with their own practice' },
  { de: 'Bestatter werden', en: 'become an undertaker' },
  { de: 'in Las Vegas spontan heiraten', en: 'get married on a whim in Las Vegas' },
  {
    de: 'ein Selbsthilfebuch schreiben, ohne sich selbst zu helfen',
    en: 'write a self help book without helping themselves',
  },
  {
    de: 'die Hochzeit so groß feiern, dass sie im Fernsehen kommt',
    en: 'throw a wedding so big it makes the news',
  },
  {
    de: 'Trauzeuge bei allen unseren Hochzeiten sein',
    en: 'be best man or maid of honor at all our weddings',
  },
  {
    de: 'die Nachbarn mit Weihnachtsdeko in den Wahnsinn treiben',
    en: 'drive the neighbors mad with Christmas lights',
  },
  { de: 'irgendwann mit uns allen ein Haus teilen', en: 'end up sharing a house with all of us' },
  { de: 'eine eigene Religion erfinden', en: 'invent their own religion' },
  { de: 'zum Prepper werden und einen Bunker bauen', en: 'become a prepper and build a bunker' },
  {
    de: 'ein Sternerestaurant als Stammlokal haben',
    en: 'have a Michelin star restaurant as their regular spot',
  },
  { de: 'mehr Haustiere als Freunde haben', en: 'have more pets than friends' },
  {
    de: 'einen Stand auf dem Weihnachtsmarkt betreiben',
    en: 'run a stall at the Christmas market',
  },
  { de: 'mit 30 in einem Schloss wohnen', en: 'live in a castle by 30' },
  { de: 'als Hellseher Geld verdienen', en: 'make money as a psychic' },
  { de: 'in einer Boyband oder Girlband landen', en: 'end up in a boy band or girl group' },
  { de: 'die eigene Hochzeit absagen', en: 'call off their own wedding' },
  { de: 'die Welt mit dem Fahrrad umrunden', en: 'cycle around the world' },
  { de: 'den Mount Everest besteigen', en: 'climb Mount Everest' },
  { de: 'Sterneköchin oder Sternekoch werden', en: 'become a star chef' },
  {
    de: 'eine Kneipe übernehmen und selbst der beste Gast sein',
    en: 'take over a pub and be its best customer',
  },
  { de: 'in einer Rentnergang auf Motorrädern fahren', en: 'ride in a pensioner motorcycle gang' },
  { de: 'einen Bauernhof in Kanada kaufen', en: 'buy a ranch in Canada' },
  { de: 'den nächsten großen Tanztrend erfinden', en: 'invent the next big dance trend' },
  { de: 'Lehrer an unserer alten Schule werden', en: 'end up teaching at our old school' },
  {
    de: 'in einem Werbespot für Hämorrhoidensalbe auftreten',
    en: 'appear in a commercial for hemorrhoid cream',
  },
  {
    de: 'im Knast landen, aber aus einem lustigen Grund',
    en: 'end up in jail for something hilarious',
  },
  { de: 'einen Brettspielverlag gründen', en: 'start a board game company' },
  { de: 'ein Comeback als Teeniestar feiern', en: 'have a comeback as a former teen star' },
  { de: 'als Influencer für Rentner bekannt werden', en: 'become a famous senior influencer' },
  { de: 'einen Zoo eröffnen', en: 'open a zoo' },
  { de: 'beim Tatort eine Leiche spielen', en: 'play a corpse on a TV crime show' },
  { de: 'mit 40 nochmal komplett den Beruf wechseln', en: 'completely change careers at 40' },
  {
    de: 'eine Ferienwohnung an Touristen vermieten und reich werden',
    en: 'get rich renting out holiday flats',
  },
  { de: 'einen Bauernhof in Italien renovieren', en: 'restore an old farmhouse in Italy' },
  {
    de: 'das eigene Leben als Musical auf die Bühne bringen',
    en: 'turn their life story into a musical',
  },
  {
    de: 'in einer Stadt wohnen, die niemand von uns kennt',
    en: 'live in a town none of us has heard of',
  },
  { de: 'den oder die Ex nochmal heiraten', en: 'remarry their ex' },
  {
    de: 'selbstgemachte Marmelade auf dem Wochenmarkt verkaufen',
    en: 'sell homemade jam at the farmers market',
  },
  { de: 'irgendwann ein Weingut besitzen', en: 'own a winery someday' },
  {
    de: 'die Welt retten, aber niemandem davon erzählen',
    en: 'save the world and tell nobody about it',
  },
  { de: 'unter Wasser heiraten', en: 'get married underwater' },
  { de: 'vor Gericht gegen den Vermieter gewinnen', en: 'win a court case against their landlord' },
  {
    de: 'einen Gerichtsprozess wegen eines Gartenzwergs führen',
    en: 'go to court over a garden gnome',
  },
  { de: 'Stammgast im Frühstücksfernsehen werden', en: 'become a regular on breakfast TV' },
  {
    de: 'die ganze Familie mit Ahnenforschung nerven',
    en: 'annoy the family with a genealogy obsession',
  },
  {
    de: 'die eigene Firma an die Wand fahren und neu anfangen',
    en: 'crash their company and start all over',
  },
  { de: 'mit 100 noch Witze erzählen', en: 'still be telling jokes at 100' },
  {
    de: 'das älteste Mitglied unserer Gruppe werden, das noch feiert',
    en: 'be the oldest of us still partying',
  },
  {
    de: 'in einer Hütte in Norwegen ohne WLAN leben',
    en: 'live in a cabin in Norway without wifi',
  },
  {
    de: 'mit einem Hobby berühmt werden, das niemand ernst nimmt',
    en: 'get famous for a hobby nobody takes seriously',
  },
  { de: 'einen Reiterhof für Kinder führen', en: 'run a pony farm for kids' },
  { de: 'zehn Hunde gleichzeitig haben', en: 'own ten dogs at once' },
  { de: 'einen eigenen Song im Radio hören', en: 'hear their own song on the radio' },
  {
    de: 'sich in der Midlife-Crisis tätowieren lassen',
    en: 'get a big tattoo during their midlife crisis',
  },
  {
    de: 'die eigenen Eltern bei sich einziehen lassen',
    en: 'have their parents move in with them',
  },
  { de: 'als Diplomat im Ausland arbeiten', en: 'work abroad as a diplomat' },
  { de: 'eine Hundeschule eröffnen', en: 'open a dog training school' },
  { de: 'als Erstes von uns ein Haus kaufen', en: 'be the first of us to buy a house' },
  { de: 'einen eigenen Fußballverein kaufen', en: 'buy their own football club' },
  { de: 'die Schulden aller Freunde abbezahlen', en: 'pay off all their friends’ debts' },
  { de: 'jeden Winter in Spanien überwintern', en: 'spend every winter in Spain' },
  { de: 'mit einem Fernsehkoch eine Show machen', en: 'host a cooking show with a celebrity chef' },
  { de: 'eine Scheune als Hochzeitslocation vermieten', en: 'rent out a barn as a wedding venue' },
  {
    de: 'ein Comeback der eigenen Schulband organisieren',
    en: 'organize a reunion of their school band',
  },
  {
    de: 'ein Klassentreffen organisieren und als Einziges hingehen',
    en: 'organize a class reunion and be the only one there',
  },
  { de: 'in einem Leuchtturm wohnen', en: 'live in a lighthouse' },
  { de: 'eine eigene Kochbuchreihe rausbringen', en: 'publish a series of cookbooks' },
  { de: 'in einem Jahr fünf Mal umziehen', en: 'move house five times in one year' },
  {
    de: 'an einer Expedition in den Regenwald teilnehmen',
    en: 'join an expedition into the rainforest',
  },
  { de: 'mit einem Hund durch ganz Europa wandern', en: 'hike across Europe with their dog' },
  { de: 'irgendwann Bauer werden und es lieben', en: 'become a farmer and absolutely love it' },
];
