import type { MostLikelyToSeed } from './types';

export const sexualQuestions: MostLikelyToSeed[] = [
  { de: 'einen One-Night-Stand im Urlaub haben', en: 'have a one night stand on holiday' },
  { de: 'mit dem Ex wieder im Bett landen', en: 'end up in bed with their ex again' },
  {
    de: 'schon beim ersten Date die Nacht zusammen verbringen',
    en: 'spend the night together on the first date',
  },
  {
    de: 'heimlich Sexspielzeug im Handgepäck haben',
    en: 'have a sex toy hidden in their hand luggage',
  },
  { de: 'beim Sex plötzlich laut lachen müssen', en: 'suddenly burst out laughing during sex' },
  { de: 'einen Dreier vorschlagen', en: 'suggest a threesome' },
  { de: 'Sex an einem öffentlichen Ort haben', en: 'have sex in a public place' },
  { de: 'die Nachbarn mit lautem Sex wecken', en: 'wake the neighbours with loud sex' },
  { de: 'Handschellen im Nachttisch aufbewahren', en: 'keep handcuffs in their nightstand' },
  { de: 'eine Affäre mit dem Chef anfangen', en: 'start an affair with their boss' },
  { de: 'mit jemandem aus dieser Runde schlafen', en: 'sleep with someone in this group' },
  { de: 'auf einer Hochzeit jemanden abschleppen', en: 'hook up with someone at a wedding' },
  { de: 'freiwillig einen Stripclub besuchen', en: 'happily visit a strip club' },
  { de: 'beim Dirty Talk komplett versagen', en: 'completely fail at dirty talk' },
  {
    de: 'eine Dating-App nur für Bettgeschichten nutzen',
    en: 'use a dating app purely for hookups',
  },
  { de: 'im Flugzeug dem Mile High Club beitreten', en: 'join the mile high club' },
  { de: 'nachts nackt baden gehen', en: 'go skinny dipping at night' },
  { de: 'sich beim Sex filmen', en: 'film themselves having sex' },
  {
    de: 'Nacktfotos aus Versehen an die falsche Person schicken',
    en: 'accidentally send nudes to the wrong person',
  },
  { de: 'ein Rollenspiel im Schlafzimmer ausprobieren', en: 'try role play in the bedroom' },
  { de: 'beim Sex den falschen Namen sagen', en: 'say the wrong name during sex' },
  { de: 'einen Swingerclub besuchen', en: 'visit a swingers club' },
  { de: 'eine Freundschaft plus haben', en: 'have a friends with benefits arrangement' },
  { de: 'im Auto Sex haben', en: 'have sex in a car' },
  { de: 'morgens neben einer fremden Person aufwachen', en: 'wake up next to a stranger' },
  {
    de: 'den Walk of Shame mit erhobenem Kopf hinlegen',
    en: 'do the walk of shame with their head held high',
  },
  { de: 'eine Nacht mit Fesselspielen planen', en: 'plan a night of bondage' },
  { de: 'auf Augenbinden im Bett stehen', en: 'be into blindfolds in bed' },
  { de: 'in einer Umkleidekabine rummachen', en: 'make out in a changing room' },
  {
    de: 'mit dem Barkeeper flirten, um Drinks gratis zu bekommen',
    en: 'flirt with the bartender for free drinks',
  },
  {
    de: 'heimlich für den besten Freund des Partners schwärmen',
    en: 'have a secret crush on their partner’s best friend',
  },
  { de: 'an einem Abend mit drei Leuten knutschen', en: 'kiss three people in one night' },
  { de: 'einen Sexshop ohne jede Scham betreten', en: 'walk into a sex shop without any shame' },
  { de: 'Dessous nur für sich selbst kaufen', en: 'buy lingerie just for themselves' },
  { de: 'einen Quickie in der Mittagspause haben', en: 'have a quickie on their lunch break' },
  {
    de: 'alle Stellungen aus dem Kamasutra ausprobieren',
    en: 'try every position in the Kama Sutra',
  },
  { de: 'Sex auf dem Küchentisch haben', en: 'have sex on the kitchen table' },
  { de: 'für einen Pornostar schwärmen', en: 'have a crush on a porn star' },
  { de: 'beim Sex einschlafen', en: 'fall asleep during sex' },
  {
    de: 'auf der Weihnachtsfeier mit einem Kollegen rummachen',
    en: 'make out with a coworker at the office Christmas party',
  },
  {
    de: 'einen Liebesbrief voller schmutziger Details schreiben',
    en: 'write a love letter full of dirty details',
  },
  { de: 'ein Zimmer im Stundenhotel buchen', en: 'book a hotel room by the hour' },
  {
    de: 'beim Sex unbedingt das Licht anlassen wollen',
    en: 'insist on keeping the lights on during sex',
  },
  { de: 'beim Flirten völlig übertreiben', en: 'go way over the top when flirting' },
  { de: 'jemandem einen Lapdance geben', en: 'give someone a lap dance' },
  { de: 'beim Strip-Poker als Erstes nackt sein', en: 'be the first one naked at strip poker' },
  { de: 'auf einer Party Strip-Poker vorschlagen', en: 'suggest strip poker at a party' },
  { de: 'die ganze Nacht durch sexten', en: 'sext all night long' },
  { de: 'Sexspielzeug als Geschenk verschenken', en: 'give a sex toy as a gift' },
  { de: 'im Urlaub eine Sommeraffäre haben', en: 'have a summer fling on holiday' },
  { de: 'heimlich Erotikromane lesen', en: 'secretly read erotic novels' },
  { de: 'sich beim Sex verletzen', en: 'get injured during sex' },
  { de: 'beim Sex einen Krampf bekommen', en: 'get a cramp during sex' },
  { de: 'beim Sex das Bett kaputt machen', en: 'break the bed during sex' },
  {
    de: 'von der Polizei beim Rummachen erwischt werden',
    en: 'get caught making out by the police',
  },
  {
    de: 'von den eigenen Eltern beim Sex erwischt werden',
    en: 'get caught having sex by their parents',
  },
  {
    de: 'von den Mitbewohnern beim Sex gehört werden',
    en: 'get overheard having sex by their flatmates',
  },
  { de: 'Sex unter der Dusche haben', en: 'have sex in the shower' },
  { de: 'Sex am Strand haben', en: 'have sex on the beach' },
  { de: 'immer ein Kondom im Portemonnaie haben', en: 'always carry a condom in their wallet' },
  { de: 'im Bett gern die Kontrolle übernehmen', en: 'love taking control in bed' },
  { de: 'sich im Bett gern unterwerfen', en: 'enjoy being submissive in bed' },
  { de: 'ein Safeword mit dem Partner festlegen', en: 'agree on a safe word with their partner' },
  { de: 'eine Peitsche besitzen', en: 'own a whip' },
  { de: 'im Schlafzimmer Latex tragen', en: 'wear latex in the bedroom' },
  { de: 'ein ganzes Wochenende nur im Bett verbringen', en: 'spend a whole weekend in bed' },
  { de: 'auf Tinder mehr als hundert Matches haben', en: 'have over a hundred matches on Tinder' },
  {
    de: 'mit jemandem heimgehen, ohne den Namen zu kennen',
    en: 'go home with someone without knowing their name',
  },
  { de: 'sich in einen Stripper verlieben', en: 'fall for a stripper' },
  { de: 'mit einem Promi schlafen', en: 'sleep with a celebrity' },
  { de: 'dem Kellner heimlich die eigene Nummer zustecken', en: 'slip their number to the waiter' },
  { de: 'mit dem Personal Trainer flirten', en: 'flirt with their personal trainer' },
  { de: 'ein Boudoir-Fotoshooting machen', en: 'do a boudoir photo shoot' },
  { de: 'ein Sextagebuch führen', en: 'keep a sex diary' },
  { de: 'Geburtstagssex für Pflicht halten', en: 'treat birthday sex as mandatory' },
  { de: 'mit Essen im Bett experimentieren', en: 'experiment with food in bed' },
  { de: 'eine eigene Playlist für Sex haben', en: 'have a dedicated sex playlist' },
  { de: 'Schlagsahne mit ins Schlafzimmer nehmen', en: 'bring whipped cream into the bedroom' },
  { de: 'Massageöl immer griffbereit haben', en: 'always keep massage oil within reach' },
  { de: 'eine erotische Massage geben', en: 'give an erotic massage' },
  { de: 'ein Toy mit Fernbedienung besitzen', en: 'own a remote controlled toy' },
  {
    de: 'ein ferngesteuertes Toy in der Öffentlichkeit tragen',
    en: 'wear a remote controlled toy in public',
  },
  { de: 'einen Fußfetisch haben', en: 'have a foot fetish' },
  { de: 'auf Uniformen stehen', en: 'have a thing for uniforms' },
  { de: 'im Kostüm Sex haben', en: 'have sex in costume' },
  { de: 'nach einer Party mit dem Gastgeber schlafen', en: 'sleep with the host after a party' },
  { de: 'auf einem Festival im Zelt Sex haben', en: 'have sex in a tent at a festival' },
  {
    de: 'beim Klassentreffen mit dem alten Schwarm schlafen',
    en: 'sleep with their old crush at a class reunion',
  },
  { de: 'einen Seitensprung beichten', en: 'confess to cheating' },
  { de: 'eine offene Beziehung vorschlagen', en: 'suggest an open relationship' },
  { de: 'polyamor leben', en: 'live polyamorously' },
  { de: 'zwei Leute gleichzeitig daten', en: 'date two people at the same time' },
  { de: 'eine anzügliche Sprachnachricht schicken', en: 'send a flirty voice note' },
  { de: 'eine heiße Story nur für enge Freunde posten', en: 'post a spicy close friends story' },
  { de: 'einen OnlyFans-Account starten', en: 'start an OnlyFans account' },
  {
    de: 'heimlich jemanden auf OnlyFans abonnieren',
    en: 'secretly subscribe to someone’s OnlyFans',
  },
  {
    de: 'bei einem Porno wirklich auf die Handlung achten',
    en: 'actually follow the plot of a porn',
  },
  { de: 'den Browserverlauf ständig löschen', en: 'constantly clear their browser history' },
  { de: 'beim Pornoschauen erwischt werden', en: 'get caught watching porn' },
  {
    de: 'die eigene Lieblingskategorie bei Pornos verraten',
    en: 'reveal their favourite porn category',
  },
  { de: 'mit einer fremden Person im Zug flirten', en: 'flirt with a stranger on the train' },
  { de: 'Sex auf einer Zugtoilette haben', en: 'have sex in a train toilet' },
  { de: 'Sex im Büro haben', en: 'have sex at the office' },
  { de: 'nachts Sex im Hotelpool haben', en: 'have sex in a hotel pool at night' },
  { de: 'Sex in der Sauna haben', en: 'have sex in a sauna' },
  { de: 'mit dem Tanzlehrer flirten', en: 'flirt with their dance teacher' },
  { de: 'beim Speed-Dating mit allen flirten', en: 'flirt with everyone at speed dating' },
  {
    de: 'einen Vibrator bei der Sicherheitskontrolle erklären müssen',
    en: 'have to explain a vibrator at airport security',
  },
  { de: 'beim ersten Kuss zu viel Zunge benutzen', en: 'use too much tongue on a first kiss' },
  { de: 'einen Knutschfleck stolz herzeigen', en: 'proudly show off a hickey' },
  { de: 'einen Knutschfleck mit Make-up überdecken', en: 'cover up a hickey with makeup' },
  {
    de: 'mit Kratzspuren auf dem Rücken auftauchen',
    en: 'show up with scratch marks on their back',
  },
  { de: 'beim Flirten knallrot werden', en: 'turn bright red while flirting' },
  { de: 'eine Liste mit Sexfantasien führen', en: 'keep a list of sexual fantasies' },
  { de: 'die eigene wildeste Fantasie laut aussprechen', en: 'say their wildest fantasy out loud' },
  { de: 'jede Fantasie wirklich ausprobieren', en: 'actually act out every fantasy' },
  { de: 'Sex vor dem Spiegel haben', en: 'have sex in front of a mirror' },
  { de: 'einen Spiegel über dem Bett aufhängen', en: 'hang a mirror over the bed' },
  {
    de: 'Seidenbettwäsche nur für besondere Nächte aufheben',
    en: 'save silk sheets for special nights',
  },
  { de: 'Sex auf einer Dachterrasse haben', en: 'have sex on a rooftop' },
  { de: 'in der letzten Reihe im Kino rummachen', en: 'make out in the back row of a cinema' },
  { de: 'im Aufzug mit jemandem rummachen', en: 'make out with someone in a lift' },
  { de: 'schon beim ersten Date über Sex reden', en: 'talk about sex on the first date' },
  {
    de: 'auf einen Kaffee nach oben einladen, ohne Kaffee zu haben',
    en: 'invite someone up for coffee without owning any coffee',
  },
  {
    de: 'bei Netflix and Chill nie den Film zu Ende sehen',
    en: 'never finish the film during Netflix and chill',
  },
  { de: 'mit dem Reiseleiter flirten', en: 'flirt with the tour guide' },
  {
    de: 'im Skiurlaub mit dem Skilehrer etwas anfangen',
    en: 'hook up with the ski instructor on a ski trip',
  },
  { de: 'mit einem Rettungsschwimmer flirten', en: 'flirt with a lifeguard' },
  {
    de: 'einen Vierer mit einem befreundeten Paar haben',
    en: 'have a foursome with another couple',
  },
  { de: 'beim Sex aus dem Bett fallen', en: 'fall out of bed during sex' },
  { de: 'beim Sex auf der Fernbedienung liegen', en: 'end up lying on the TV remote during sex' },
  { de: 'beim Sex an die Steuererklärung denken', en: 'think about their tax return during sex' },
  { de: 'einen Orgasmus vortäuschen', en: 'fake an orgasm' },
  { de: 'direkt nach dem Sex einschlafen', en: 'fall asleep right after sex' },
  { de: 'nach dem Sex sofort Pizza bestellen', en: 'order pizza right after sex' },
  { de: 'direkt nach dem Sex aufs Handy schauen', en: 'check their phone right after sex' },
  { de: 'Sex dem Frühstück vorziehen', en: 'choose sex over breakfast' },
  {
    de: 'einen Streit nur für den Versöhnungssex anfangen',
    en: 'start a fight just for the makeup sex',
  },
  { de: 'morgens immer Lust haben', en: 'always be in the mood in the morning' },
  { de: 'den ganzen Tag an Sex denken', en: 'think about sex all day long' },
  { de: 'im Supermarkt jemanden anflirten', en: 'flirt with someone at the supermarket' },
  { de: 'im Fitnessstudio jemanden abschleppen', en: 'pick someone up at the gym' },
  { de: 'beim Yoga plötzlich Lust bekommen', en: 'suddenly get turned on during yoga' },
  { de: 'Sex als Cardio-Training zählen', en: 'count sex as their cardio' },
  { de: 'mit einem Tinder-Date in den Urlaub fahren', en: 'go on holiday with a Tinder date' },
  { de: 'für einen Hookup quer durch die Stadt fahren', en: 'cross the whole city for a hookup' },
  { de: 'für einen Hookup in ein anderes Land fliegen', en: 'fly to another country for a hookup' },
  {
    de: 'nachts um drei eine eindeutige Nachricht schicken',
    en: 'send a booty call text at three in the morning',
  },
  { de: 'einen Booty Call nie ablehnen', en: 'never turn down a booty call' },
  {
    de: 'die Nummer einer Affäre unter falschem Namen speichern',
    en: 'save a fling’s number under a fake name',
  },
  {
    de: 'eine geheime Dating-App auf dem Handy haben',
    en: 'have a secret dating app on their phone',
  },
  {
    de: 'den Ex nachts betrunken anschreiben',
    en: 'drunk text their ex in the middle of the night',
  },
  {
    de: 'auf einer Hausparty im Badezimmer rummachen',
    en: 'make out in the bathroom at a house party',
  },
  {
    de: 'beim Flaschendrehen schummeln, um jemanden zu küssen',
    en: 'cheat at spin the bottle to kiss someone',
  },
  {
    de: 'bei Wahrheit oder Pflicht freiwillig blankziehen',
    en: 'strip voluntarily at truth or dare',
  },
  {
    de: 'einen Stripper für den Junggesellenabschied buchen',
    en: 'book a stripper for a bachelor party',
  },
  {
    de: 'auf einem Junggesellenabschied eine fremde Person küssen',
    en: 'kiss a stranger at a bachelor party',
  },
  { de: 'eine Toy-Party mit Freunden veranstalten', en: 'host a sex toy party with friends' },
  { de: 'die größte Sammlung an Sexspielzeug besitzen', en: 'own the biggest sex toy collection' },
  {
    de: 'sich ein Tattoo an einer intimen Stelle stechen lassen',
    en: 'get a tattoo somewhere intimate',
  },
  { de: 'ein Intimpiercing haben', en: 'have an intimate piercing' },
  { de: 'grundsätzlich nackt schlafen', en: 'always sleep naked' },
  { de: 'nackt die Tür öffnen', en: 'answer the door naked' },
  { de: 'im FKK-Urlaub völlig entspannt sein', en: 'be completely relaxed on a nudist holiday' },
  { de: 'Sex im Wald haben', en: 'have sex in the woods' },
  { de: 'Sex auf der Waschmaschine haben', en: 'have sex on the washing machine' },
  { de: 'Sex im Treppenhaus haben', en: 'have sex in a stairwell' },
  { de: 'auf einer Party Sex im Gästezimmer haben', en: 'have sex in the guest room at a party' },
  { de: 'im Elternhaus Sex haben', en: 'have sex at their parents’ house' },
  { de: 'beim Sex lustige Geräusche machen', en: 'make funny noises during sex' },
  { de: 'beim Sex die Socken anbehalten', en: 'keep their socks on during sex' },
  { de: 'aus einer Kissenschlacht Sex machen', en: 'turn a pillow fight into sex' },
  {
    de: 'Dessous tragen, nur um sie direkt wieder auszuziehen',
    en: 'put on lingerie only to take it straight off',
  },
  { de: 'unter dem Mantel nichts tragen', en: 'wear nothing under their coat' },
  { de: 'ohne Unterwäsche zur Arbeit gehen', en: 'go to work without underwear' },
  {
    de: 'eine fremde Unterhose als Andenken behalten',
    en: 'keep someone’s underwear as a souvenir',
  },
  {
    de: 'einen versteckten Ordner mit heißen Fotos haben',
    en: 'have a hidden folder of naughty pics',
  },
  { de: 'eine Erotikmesse besuchen', en: 'go to an adult expo' },
  { de: 'einen Tantrakurs besuchen', en: 'take a tantra course' },
  { de: 'Sex im Kalender eintragen', en: 'schedule sex in their calendar' },
  { de: 'ein Jahr freiwillig enthaltsam leben', en: 'stay celibate for a year by choice' },
  { de: 'bei der Zahl der Sexpartner lügen', en: 'lie about their body count' },
  { de: 'die meisten Sexpartner haben', en: 'have the highest body count' },
  { de: 'sich nach einem One-Night-Stand verlieben', en: 'fall in love after a one night stand' },
  {
    de: 'aus einer Freundschaft plus eine Beziehung machen',
    en: 'turn friends with benefits into a relationship',
  },
  {
    de: 'jemanden mit einem einzigen Zwinkern ins Bett bekommen',
    en: 'get someone into bed with a single wink',
  },
  {
    de: 'mit einem furchtbaren Anmachspruch Erfolg haben',
    en: 'succeed with a terrible pickup line',
  },
  { de: 'jemanden mit Blicken ausziehen', en: 'undress someone with their eyes' },
  {
    de: 'im Hotel mit dem Zimmernachbarn anbandeln',
    en: 'hook up with the guest next door at a hotel',
  },
  { de: 'auf dem Rücksitz eines Taxis rummachen', en: 'make out in the back of a taxi' },
  { de: 'das Hotelbett mit Rosenblättern bestreuen', en: 'cover the hotel bed in rose petals' },
  { de: 'im Bett mit Kerzenwachs spielen', en: 'play with candle wax in bed' },
  { de: 'im Bett Spanking ausprobieren', en: 'try spanking in bed' },
  { de: 'im Schlafzimmer ein Halsband tragen', en: 'wear a collar in the bedroom' },
  { de: 'eine BDSM-Party besuchen', en: 'go to a BDSM party' },
  {
    de: 'sich versehentlich Sexspielzeug ins Büro liefern lassen',
    en: 'accidentally have a sex toy delivered to the office',
  },
  {
    de: 'die Nachbarn ein Paket voller Sexspielzeug annehmen lassen',
    en: 'have the neighbours accept a parcel full of sex toys',
  },
  {
    de: 'die Eltern mit einem versauten Witz schockieren',
    en: 'shock their parents with a dirty joke',
  },
  { de: 'die schmutzigsten Witze des Abends erzählen', en: 'tell the dirtiest jokes of the night' },
  {
    de: 'den Partner mit neuen Dessous überraschen',
    en: 'surprise their partner with new lingerie',
  },
];
