services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
    volumes:
      - nextjs_template_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  postgres_network:
    driver: bridge

volumes:
  nextjs_template_postgres_data:
    driver: local
