import type { WouldYouRatherSeed } from './types';

export const coworkersQuestions: WouldYouRatherSeed[] = [
  {
    a: 'in jedem Meeting die Kamera anhaben',
    b: 'in jedem Meeting das Protokoll schreiben',
    aEn: 'have your camera on in every meeting',
    bEn: 'take the minutes in every meeting',
  },
  {
    a: 'nie wieder ein Meeting haben, dafür alles per E-Mail klären',
    b: 'nie wieder eine E-Mail schreiben, dafür alles in Meetings klären',
    aEn: 'never have a meeting again and sort everything out by email',
    bEn: 'never write an email again and sort everything out in meetings',
  },
  {
    a: 'jeden Morgen ein Standup um 8 Uhr haben',
    b: 'jeden Freitag ein zweistündiges Teammeeting um 16 Uhr haben',
    aEn: 'have a standup at 8 a.m. every morning',
    bEn: 'have a two-hour team meeting at 4 p.m. every Friday',
  },
  {
    a: 'in jedem Meeting spontan etwas präsentieren müssen',
    b: 'in keinem Meeting mehr etwas sagen dürfen',
    aEn: 'have to present something on the spot in every meeting',
    bEn: 'not be allowed to say anything in meetings anymore',
  },
  {
    a: 'im Call aus Versehen deinen privaten Browser teilen',
    b: 'im Call vergessen, dass du nicht stummgeschaltet bist, während du singst',
    aEn: 'accidentally share your private browser on a call',
    bEn: 'forget you’re not muted on a call while you’re singing',
  },
  {
    a: 'alle Meetings im Stehen abhalten',
    b: 'alle Meetings beim Spazierengehen abhalten',
    aEn: 'hold every meeting standing up',
    bEn: 'hold every meeting on a walk',
  },
  {
    a: 'dass jedes Meeting ohne Agenda automatisch abgesagt wird',
    b: 'dass jedes Meeting nach 25 Minuten hart endet',
    aEn: 'have every meeting without an agenda cancelled automatically',
    bEn: 'have every meeting end abruptly after 25 minutes',
  },
  {
    a: 'alle Meetings der Woche gebündelt am Montag haben',
    b: 'jeden Tag genau ein Meeting haben',
    aEn: 'have all the week’s meetings bundled on Monday',
    bEn: 'have exactly one meeting every day',
  },
  {
    a: 'jedes Meeting moderieren müssen',
    b: 'jedes Meeting mit einem Witz eröffnen müssen',
    aEn: 'have to chair every meeting',
    bEn: 'have to open every meeting with a joke',
  },
  {
    a: 'in einem Meeting einschlafen und schnarchen',
    b: 'in einem Meeting deine Chefin aus Versehen Mama nennen',
    aEn: 'fall asleep and snore in a meeting',
    bEn: 'accidentally call your boss “Mom” in a meeting',
  },
  {
    a: 'für immer nur im Homeoffice arbeiten',
    b: 'für immer nur im Büro arbeiten',
    aEn: 'only ever work from home',
    bEn: 'only ever work at the office',
  },
  {
    a: 'im Homeoffice mit wackeligem Internet arbeiten',
    b: 'im Büro mit einer Stunde Pendelweg pro Strecke arbeiten',
    aEn: 'work from home with flaky internet',
    bEn: 'work at the office with an hour’s commute each way',
  },
  {
    a: 'von überall auf der Welt arbeiten, aber zu deutschen Bürozeiten',
    b: 'nur von zuhause arbeiten, aber wann immer du willst',
    aEn: 'work from anywhere in the world, but on German office hours',
    bEn: 'only work from home, but whenever you want',
  },
  {
    a: 'im Homeoffice immer Anzug oder Kostüm tragen müssen',
    b: 'im Büro immer Jogginghose tragen müssen',
    aEn: 'have to wear a suit at all times when working from home',
    bEn: 'have to wear sweatpants at all times at the office',
  },
  {
    a: 'einen Monat lang am Strand arbeiten',
    b: 'zwei Wochen zusätzlichen Urlaub bekommen',
    aEn: 'work from the beach for a month',
    bEn: 'get two extra weeks of vacation',
  },
  {
    a: 'eine Vier-Tage-Woche mit Zehn-Stunden-Tagen',
    b: 'eine Fünf-Tage-Woche mit Acht-Stunden-Tagen',
    aEn: 'have a four-day week with ten-hour days',
    bEn: 'have a five-day week with eight-hour days',
  },
  {
    a: 'im Homeoffice ständig vom Nachbarn mit der Bohrmaschine gestört werden',
    b: 'im Büro direkt neben der Kaffeemaschine sitzen',
    aEn: 'be constantly disturbed by your neighbor’s drill when working from home',
    bEn: 'sit right next to the coffee machine at the office',
  },
  {
    a: 'dass dein Haustier in jedem Call durchs Bild läuft',
    b: 'dass dein virtueller Hintergrund dauerhaft ein Kinderfoto von dir ist',
    aEn: 'have your pet walk through the frame on every call',
    bEn: 'have a childhood photo of you as your permanent virtual background',
  },
  {
    a: 'in einem Großraumbüro mit 100 Leuten arbeiten',
    b: 'ganz allein in einem fensterlosen Einzelbüro arbeiten',
    aEn: 'work in an open-plan office with 100 people',
    bEn: 'work all alone in a windowless private office',
  },
  {
    a: 'jeden Tag einen anderen Schreibtisch suchen müssen',
    b: 'für immer am selben Platz direkt neben der Toilette sitzen',
    aEn: 'have to find a different desk every day',
    bEn: 'sit at the same desk right next to the restroom forever',
  },
  {
    a: '20 Prozent mehr Gehalt ohne Homeoffice',
    b: '20 Prozent weniger Gehalt mit komplett freier Ortswahl',
    aEn: 'get a 20 percent raise but no remote work',
    bEn: 'take a 20 percent pay cut but work from anywhere',
  },
  {
    a: 'doppelt so viel verdienen, aber nur zehn Urlaubstage haben',
    b: 'dein jetziges Gehalt mit 50 Urlaubstagen haben',
    aEn: 'earn twice as much but only get ten days off',
    bEn: 'keep your current salary with 50 days off',
  },
  {
    a: 'dass alle Kollegen dein Gehalt kennen',
    b: 'das Gehalt aller Kollegen kennen und es niemandem sagen dürfen',
    aEn: 'have all your coworkers know your salary',
    bEn: 'know everyone’s salary and not be allowed to tell anyone',
  },
  {
    a: 'einmal im Jahr einen großen Bonus bekommen',
    b: 'jeden Monat etwas mehr Gehalt bekommen',
    aEn: 'get one big bonus a year',
    bEn: 'get a little more salary every month',
  },
  {
    a: 'einen Dienstwagen bekommen',
    b: 'eine BahnCard 100 erster Klasse bekommen',
    aEn: 'get a company car',
    bEn: 'get an unlimited first-class rail pass',
  },
  {
    a: 'ein sicheres Gehalt ohne jeden Bonus',
    b: 'ein kleineres Grundgehalt mit riesigem Bonuspotenzial',
    aEn: 'have a secure salary with no bonus at all',
    bEn: 'have a smaller base salary with huge bonus potential',
  },
  {
    a: 'dein Gehalt selbst festlegen, aber das ganze Team stimmt darüber ab',
    b: 'dass dein Chef es festlegt, ohne dass du verhandeln darfst',
    aEn: 'set your own salary, but the whole team votes on it',
    bEn: 'have your boss set it without being allowed to negotiate',
  },
  {
    a: 'jeden Tag kostenloses Mittagessen bekommen',
    b: 'jeden Monat 200 Euro mehr bekommen',
    aEn: 'get free lunch every day',
    bEn: 'get 200 euros more every month',
  },
  {
    a: 'Firmenanteile bekommen, die viel wert sein könnten',
    b: 'eine feste Prämie bekommen, die sicher ist',
    aEn: 'get company shares that could be worth a lot',
    bEn: 'get a fixed bonus that’s guaranteed',
  },
  {
    a: 'eine Gehaltserhöhung ohne neuen Titel',
    b: 'einen beeindruckenden Titel ohne Gehaltserhöhung',
    aEn: 'get a raise without a new title',
    bEn: 'get an impressive title without a raise',
  },
  {
    a: 'einen Chef, der dich ständig lobt, dich aber nie befördert',
    b: 'einen Chef, der nie lobt, dich aber gezielt fördert',
    aEn: 'have a boss who praises you constantly but never promotes you',
    bEn: 'have a boss who never praises you but actively develops you',
  },
  {
    a: 'einen Chef, der dir um 23 Uhr noch E-Mails schreibt',
    b: 'einen Chef, der jeden Tag um 7:30 Uhr Meetings ansetzt',
    aEn: 'have a boss who emails you at 11 p.m.',
    bEn: 'have a boss who schedules meetings at 7:30 a.m. every day',
  },
  {
    a: 'einen Chef, der dir bei allem über die Schulter schaut',
    b: 'einen Chef, der nie erreichbar ist',
    aEn: 'have a boss who looks over your shoulder on everything',
    bEn: 'have a boss who’s never reachable',
  },
  {
    a: 'dass deine Chefin deine alten Instagram-Posts likt',
    b: 'dass deine Chefin deine Spotify-Playlists sehen kann',
    aEn: 'have your boss like your old Instagram posts',
    bEn: 'have your boss be able to see your Spotify playlists',
  },
  {
    a: 'eine Woche lang den Job deiner Chefin machen',
    b: 'eine Woche lang den Job des Azubis machen',
    aEn: 'do your boss’s job for a week',
    bEn: 'do the apprentice’s job for a week',
  },
  {
    a: 'mit deiner Chefin zehn Stunden im Auto sitzen',
    b: 'mit deiner Chefin einen Abend lang Karaoke singen',
    aEn: 'spend ten hours in a car with your boss',
    bEn: 'spend an evening doing karaoke with your boss',
  },
  {
    a: 'für deinen besten Freund arbeiten',
    b: 'deinen besten Freund als Mitarbeiter haben',
    aEn: 'work for your best friend',
    bEn: 'have your best friend work for you',
  },
  {
    a: 'einen Chef, der jünger ist als du',
    b: 'einen Chef, der dich schon als Kind kannte',
    aEn: 'have a boss who’s younger than you',
    bEn: 'have a boss who knew you as a kid',
  },
  {
    a: 'dass dein Chef alle deine Chats mitliest',
    b: 'dass dein Chef deinen Bildschirm jederzeit live sehen kann',
    aEn: 'have your boss read all your chats',
    bEn: 'have your boss be able to see your screen live at any time',
  },
  {
    a: 'jedes Feedback-Gespräch vor dem ganzen Team führen',
    b: 'nie wieder irgendein Feedback bekommen',
    aEn: 'have every feedback talk in front of the whole team',
    bEn: 'never get any feedback again',
  },
  {
    a: 'neben jemandem sitzen, der laut kaut',
    b: 'neben jemandem sitzen, der ständig laut telefoniert',
    aEn: 'sit next to someone who chews loudly',
    bEn: 'sit next to someone who’s always on loud phone calls',
  },
  {
    a: 'einen Kollegen haben, der alles besser weiß',
    b: 'einen Kollegen haben, der bei allem nachfragt',
    aEn: 'have a coworker who knows everything better',
    bEn: 'have a coworker who asks about everything',
  },
  {
    a: 'einen Kollegen, der deine Ideen als seine verkauft',
    b: 'einen Kollegen, der seine Fehler auf dich schiebt',
    aEn: 'have a coworker who sells your ideas as his own',
    bEn: 'have a coworker who blames his mistakes on you',
  },
  {
    a: 'dass jemand regelmäßig dein Essen aus dem Kühlschrank nimmt',
    b: 'dass jemand jeden Tag deine Lieblingstasse benutzt',
    aEn: 'have someone regularly take your food from the fridge',
    bEn: 'have someone use your favorite mug every day',
  },
  {
    a: 'in einem Team voller Frühaufsteher arbeiten',
    b: 'in einem Team voller Nachteulen arbeiten',
    aEn: 'work in a team full of early birds',
    bEn: 'work in a team full of night owls',
  },
  {
    a: 'von allen Kollegen geduzt werden, auch vom Vorstand',
    b: 'von allen Kollegen gesiezt werden, auch vom Praktikanten',
    aEn: 'be on first-name terms with everyone, even the board',
    bEn: 'be addressed formally by everyone, even the intern',
  },
  {
    a: 'dass ein Kollege jeden Tag Fisch in der Mikrowelle aufwärmt',
    b: 'dass ein Kollege jeden Tag Zwiebeln am Schreibtisch schneidet',
    aEn: 'have a coworker reheat fish in the microwave every day',
    bEn: 'have a coworker chop onions at their desk every day',
  },
  {
    a: 'mit deinem Lieblingskollegen in einem langweiligen Projekt arbeiten',
    b: 'mit deinem schwierigsten Kollegen in einem spannenden Projekt',
    aEn: 'work with your favorite coworker on a boring project',
    bEn: 'work with your most difficult coworker on an exciting project',
  },
  {
    a: 'dass dein Kollege in jeder Nachricht fünf Ausrufezeichen setzt',
    b: 'dass dein Kollege nur mit „ok“ antwortet',
    aEn: 'have a coworker who puts five exclamation marks in every message',
    bEn: 'have a coworker who only replies with “ok”',
  },
  {
    a: 'einen spannenden Job mit wenig Gehalt',
    b: 'einen langweiligen Job mit viel Gehalt',
    aEn: 'have an exciting job with a low salary',
    bEn: 'have a boring job with a high salary',
  },
  {
    a: 'dein ganzes Berufsleben bei einer Firma bleiben',
    b: 'alle zwei Jahre den Job wechseln',
    aEn: 'stay at one company for your whole career',
    bEn: 'switch jobs every two years',
  },
  {
    a: 'in einem chaotischen Startup arbeiten',
    b: 'in einem bürokratischen Konzern arbeiten',
    aEn: 'work at a chaotic startup',
    bEn: 'work at a bureaucratic corporation',
  },
  {
    a: 'Chefin von 50 Leuten sein',
    b: 'die gefragteste Expertin ohne Personalverantwortung sein',
    aEn: 'be the boss of 50 people',
    bEn: 'be the most sought-after expert with no direct reports',
  },
  {
    a: 'einen Job haben, der die Welt verbessert, aber stressig ist',
    b: 'einen entspannten Job haben, der niemandem wirklich hilft',
    aEn: 'have a job that makes the world better but is stressful',
    bEn: 'have a relaxed job that doesn’t really help anyone',
  },
  {
    a: 'mit 55 in Rente gehen und bis dahin 55 Stunden die Woche arbeiten',
    b: 'bis 70 arbeiten, aber nur 25 Stunden die Woche',
    aEn: 'retire at 55 and work 55 hours a week until then',
    bEn: 'work until 70, but only 25 hours a week',
  },
  {
    a: 'dich selbstständig machen und alles riskieren',
    b: 'angestellt bleiben und sicher sein',
    aEn: 'go independent and risk everything',
    bEn: 'stay employed and be safe',
  },
  {
    a: 'in deinem Traumjob schlecht sein',
    b: 'in einem langweiligen Job der Beste sein',
    aEn: 'be bad at your dream job',
    bEn: 'be the best at a boring job',
  },
  {
    a: 'in fünf Jahren dreimal befördert werden, aber umziehen müssen',
    b: 'in fünf Jahren nie befördert werden, aber bleiben dürfen, wo du bist',
    aEn: 'get promoted three times in five years but have to move',
    bEn: 'never get promoted in five years but stay where you are',
  },
  {
    a: 'einen Job ohne Kundenkontakt haben',
    b: 'einen Job ohne Kollegen haben',
    aEn: 'have a job with no customer contact',
    bEn: 'have a job with no coworkers',
  },
  {
    a: 'beim Teamevent Karaoke singen',
    b: 'beim Teamevent eine spontane Rede halten',
    aEn: 'sing karaoke at the team event',
    bEn: 'give an impromptu speech at the team event',
  },
  {
    a: 'das nächste Teamevent im Escape Room machen',
    b: 'das nächste Teamevent im Kletterpark machen',
    aEn: 'have the next team event in an escape room',
    bEn: 'have the next team event at a ropes course',
  },
  {
    a: 'die Weihnachtsfeier organisieren müssen',
    b: 'auf der Weihnachtsfeier als Erstes tanzen müssen',
    aEn: 'have to organize the Christmas party',
    bEn: 'have to be the first one dancing at the Christmas party',
  },
  {
    a: 'ein Teamwochenende im Zelt verbringen',
    b: 'einen ganzen Tag Workshop mit Vertrauensübungen machen',
    aEn: 'spend a team weekend camping in tents',
    bEn: 'do a full-day workshop with trust exercises',
  },
  {
    a: 'beim Firmenlauf mitlaufen',
    b: 'beim Firmenlauf als Maskottchen am Rand anfeuern',
    aEn: 'run in the company race',
    bEn: 'cheer from the sidelines as the mascot at the company race',
  },
  {
    a: 'beim Teamkochen das Essen versalzen',
    b: 'beim Teamkochen das Essen anbrennen lassen',
    aEn: 'oversalt the food at the team cooking event',
    bEn: 'burn the food at the team cooking event',
  },
  {
    a: 'beim Sommerfest gegen den Chef im Tischkicker verlieren',
    b: 'beim Sommerfest den Chef im Tischkicker haushoch schlagen',
    aEn: 'lose to your boss at foosball at the summer party',
    bEn: 'crush your boss at foosball at the summer party',
  },
  {
    a: 'dass das Teamevent immer an einem Freitagabend stattfindet',
    b: 'dass das Teamevent immer an einem Montagmorgen stattfindet',
    aEn: 'have team events always on a Friday evening',
    bEn: 'have team events always on a Monday morning',
  },
  {
    a: 'auf der Weihnachtsfeier beim Wichteln eine Socke bekommen',
    b: 'auf der Weihnachtsfeier ein Geschenk bekommen, das du selbst mal verschenkt hast',
    aEn: 'get a single sock at the Secret Santa',
    bEn: 'get a gift at the Secret Santa that you once gave away yourself',
  },
  {
    a: 'das Teamfoto mit geschlossenen Augen auf der Firmenwebsite haben',
    b: 'das Teamfoto mit Spinat zwischen den Zähnen haben',
    aEn: 'have the team photo with your eyes closed on the company website',
    bEn: 'have the team photo with spinach in your teeth',
  },
  {
    a: 'jede E-Mail innerhalb von fünf Minuten beantworten müssen',
    b: 'E-Mails nur einmal pro Woche lesen dürfen',
    aEn: 'have to answer every email within five minutes',
    bEn: 'only be allowed to read emails once a week',
  },
  {
    a: 'eine E-Mail an die ganze Firma mit einem Tippfehler im Betreff schicken',
    b: 'eine E-Mail mit dem falschen Anhang an einen Kunden schicken',
    aEn: 'send an email to the whole company with a typo in the subject',
    bEn: 'send an email with the wrong attachment to a client',
  },
  {
    a: 'dass jede deiner Nachrichten mit „Liebe Grüße“ enden muss',
    b: 'dass jede deiner Nachrichten mit „Hochachtungsvoll“ enden muss',
    aEn: 'have every message you write end with “Lots of love”',
    bEn: 'have every message you write end with “Yours faithfully”',
  },
  {
    a: 'einen Posteingang mit 5.000 ungelesenen Mails haben',
    b: 'einen Posteingang, den jeder Kollege mitlesen kann',
    aEn: 'have an inbox with 5,000 unread emails',
    bEn: 'have an inbox that every coworker can read',
  },
  {
    a: 'dass im Firmenchat nur Sprachnachrichten erlaubt sind',
    b: 'dass im Firmenchat nur Emojis erlaubt sind',
    aEn: 'have only voice messages allowed in the company chat',
    bEn: 'have only emojis allowed in the company chat',
  },
  {
    a: 'dass dein Status im Chat immer „abwesend“ anzeigt',
    b: 'dass dein Status im Chat immer „verfügbar“ anzeigt',
    aEn: 'have your chat status always show “away”',
    bEn: 'have your chat status always show “available”',
  },
  {
    a: 'aus Versehen „Antwort an alle“ mit einem Lästerkommentar drücken',
    b: 'aus Versehen eine private Nachricht in den Teamkanal posten',
    aEn: 'accidentally hit “reply all” with a snarky comment',
    bEn: 'accidentally post a private message in the team channel',
  },
  {
    a: 'nach Feierabend komplett unerreichbar sein',
    b: 'immer erreichbar sein, dafür früher Schluss machen',
    aEn: 'be completely unreachable after work',
    bEn: 'always be reachable but finish earlier',
  },
  {
    a: 'nur noch handschriftliche Notizen statt Chat benutzen',
    b: 'nur noch per Telefon statt per Chat kommunizieren',
    aEn: 'only use handwritten notes instead of chat',
    bEn: 'only communicate by phone instead of chat',
  },
  {
    a: 'um 6 Uhr anfangen und um 14 Uhr Feierabend haben',
    b: 'um 11 Uhr anfangen und um 19 Uhr Feierabend haben',
    aEn: 'start at 6 a.m. and finish at 2 p.m.',
    bEn: 'start at 11 a.m. and finish at 7 p.m.',
  },
  {
    a: 'jeden Tag eine Stunde Mittagspause haben',
    b: 'jeden Tag eine Stunde früher gehen dürfen',
    aEn: 'have an hour-long lunch break every day',
    bEn: 'be allowed to leave an hour early every day',
  },
  {
    a: 'nie wieder Überstunden machen, aber nie Gleitzeit haben',
    b: 'flexibel arbeiten, aber gelegentlich am Wochenende',
    aEn: 'never work overtime again but have no flextime',
    bEn: 'work flexibly but occasionally on weekends',
  },
  {
    a: 'deinen Urlaub immer spontan nehmen dürfen',
    b: 'deinen Urlaub ein Jahr im Voraus planen müssen, dafür doppelt so viel',
    aEn: 'always be able to take vacation spontaneously',
    bEn: 'have to plan vacation a year in advance, but get twice as much',
  },
  {
    a: 'im Urlaub einmal am Tag deine Mails checken müssen',
    b: 'nach dem Urlaub einen ganzen Tag lang Mails abarbeiten',
    aEn: 'have to check your emails once a day on vacation',
    bEn: 'spend a whole day clearing emails after vacation',
  },
  {
    a: 'alle Urlaubstage im Sommer am Stück nehmen',
    b: 'alle Urlaubstage über das Jahr als lange Wochenenden verteilen',
    aEn: 'take all your vacation days in one block in summer',
    bEn: 'spread all your vacation days across the year as long weekends',
  },
  {
    a: 'dass dein Wecker an Arbeitstagen zufällig klingelt',
    b: 'dass du jeden Tag pünktlich auf die Minute einstempeln musst',
    aEn: 'have your alarm go off at a random time on workdays',
    bEn: 'have to clock in on the dot every single day',
  },
  {
    a: 'einen Job mit unbegrenztem Urlaub, den sich keiner traut zu nehmen',
    b: 'einen Job mit 30 festen Urlaubstagen, die alle nehmen',
    aEn: 'have unlimited vacation that nobody dares to take',
    bEn: 'have 30 fixed vacation days that everybody takes',
  },
  {
    a: 'am Brückentag arbeiten und dafür später frei haben',
    b: 'am Brückentag frei haben und dafür den Freitag danach arbeiten',
    aEn: 'work on the bridge day and get time off later',
    bEn: 'take the bridge day off and work the following Friday instead',
  },
  {
    a: 'am 24. Dezember arbeiten müssen',
    b: 'am 2. Januar um 7 Uhr eine Präsentation halten müssen',
    aEn: 'have to work on December 24',
    bEn: 'have to give a presentation at 7 a.m. on January 2',
  },
  {
    a: 'jeden Montag frei haben',
    b: 'jeden Freitag ab Mittag frei haben',
    aEn: 'have every Monday off',
    bEn: 'have every Friday afternoon off',
  },
  {
    a: 'einen Laptop haben, der jeden Tag ein Update macht',
    b: 'einen Laptop haben, der jede Stunde kurz einfriert',
    aEn: 'have a laptop that updates every day',
    bEn: 'have a laptop that freezes briefly every hour',
  },
  {
    a: 'dass der Drucker nie funktioniert',
    b: 'dass das WLAN jeden Tag zur Mittagszeit ausfällt',
    aEn: 'have a printer that never works',
    bEn: 'have the Wi-Fi go down every day at lunchtime',
  },
  {
    a: 'alle Passwörter alle zwei Wochen ändern müssen',
    b: 'dich bei jedem Programm mit drei Faktoren anmelden müssen',
    aEn: 'have to change all your passwords every two weeks',
    bEn: 'have to log into every program with three-factor authentication',
  },
  {
    a: 'nur noch mit einem winzigen Laptopbildschirm arbeiten',
    b: 'nur noch an einem Rechner von 2005 arbeiten',
    aEn: 'only work on a tiny laptop screen',
    bEn: 'only work on a computer from 2005',
  },
  {
    a: 'jede Präsentation in PowerPoint mit Übergangseffekten machen',
    b: 'jede Präsentation nur mit einem Flipchart machen',
    aEn: 'do every presentation in PowerPoint with transition effects',
    bEn: 'do every presentation with just a flip chart',
  },
  {
    a: 'ein Excel mit 80 Tabs pflegen',
    b: 'ein Wiki pflegen, das niemand liest',
    aEn: 'maintain a spreadsheet with 80 tabs',
    bEn: 'maintain a wiki that nobody reads',
  },
  {
    a: 'dass dein Bildschirmschoner ein Foto von dir im Urlaub zeigt',
    b: 'dass dein Desktophintergrund vom Team ausgesucht wird',
    aEn: 'have a vacation photo of you as your screensaver',
    bEn: 'have your desktop wallpaper chosen by the team',
  },
  {
    a: 'für die IT den Support für alle Kollegen übernehmen',
    b: 'die Reisekostenabrechnungen für alle Kollegen machen',
    aEn: 'handle IT support for all your coworkers',
    bEn: 'do the travel expense reports for all your coworkers',
  },
  {
    a: 'dass eine KI alle deine Mails schreibt, ohne dass du sie liest',
    b: 'alle deine Mails wieder per Hand auf Papier schreiben',
    aEn: 'have an AI write all your emails without you reading them',
    bEn: 'go back to writing all your emails by hand on paper',
  },
  {
    a: 'eine Tastatur benutzen, deren Tasten laut klackern',
    b: 'eine Maus benutzen, die alle paar Minuten die Verbindung verliert',
    aEn: 'use a keyboard with loud, clacky keys',
    bEn: 'use a mouse that loses connection every few minutes',
  },
  {
    a: 'jede Dienstreise mit dem Zug machen, auch nach Lissabon',
    b: 'jede Dienstreise als Tagesreise mit dem Flieger machen',
    aEn: 'take the train on every business trip, even to Lisbon',
    bEn: 'do every business trip as a day trip by plane',
  },
  {
    a: 'auf Dienstreise im Luxushotel allein übernachten',
    b: 'auf Dienstreise mit dem ganzen Team in einer Jugendherberge schlafen',
    aEn: 'stay alone in a luxury hotel on business trips',
    bEn: 'stay in a youth hostel with the whole team on business trips',
  },
  {
    a: 'einmal im Monat für eine Woche ins Ausland reisen',
    b: 'nie reisen, aber jeden Tag lange Calls mit anderen Zeitzonen haben',
    aEn: 'travel abroad for a week once a month',
    bEn: 'never travel but have long calls across time zones every day',
  },
  {
    a: 'auf einer Messe drei Tage am Stand stehen',
    b: 'drei Tage lang Schulungen für neue Kollegen geben',
    aEn: 'stand at a trade fair booth for three days',
    bEn: 'give training sessions to new colleagues for three days',
  },
  {
    a: 'mit dem Chef im Flugzeug nebeneinandersitzen',
    b: 'mit dem Chef im Hotel beim Frühstück am selben Tisch sitzen',
    aEn: 'sit next to your boss on the plane',
    bEn: 'sit at the same breakfast table as your boss in the hotel',
  },
  {
    a: 'deinen Koffer auf Dienstreise verlieren',
    b: 'deinen Laptop auf Dienstreise im Taxi vergessen',
    aEn: 'lose your suitcase on a business trip',
    bEn: 'leave your laptop in a taxi on a business trip',
  },
  {
    a: 'jeden Tag den gleichen Weg ins Büro nehmen, der 40 Minuten dauert',
    b: 'jeden Tag einen 15-minütigen Weg nehmen, aber mit dem Fahrrad im Regen',
    aEn: 'take the same 40-minute route to the office every day',
    bEn: 'take a 15-minute route every day, but by bike in the rain',
  },
  {
    a: 'im Zug pendeln und dort produktiv arbeiten',
    b: 'mit dem Auto pendeln und Podcasts hören',
    aEn: 'commute by train and get work done on the way',
    bEn: 'commute by car and listen to podcasts',
  },
  {
    a: 'dass dein Büro im 40. Stock ist und der Aufzug oft streikt',
    b: 'dass dein Büro im Keller ohne Tageslicht ist',
    aEn: 'have your office on the 40th floor with an elevator that often breaks',
    bEn: 'have your office in the basement with no daylight',
  },
  {
    a: 'ein Büro mit Rutsche und Tischtennisplatte haben',
    b: 'ein ruhiges Büro mit eigenem Fenster haben',
    aEn: 'have an office with a slide and a ping-pong table',
    bEn: 'have a quiet office with your own window',
  },
  {
    a: 'dass im Büro immer 18 Grad sind',
    b: 'dass im Büro immer 27 Grad sind',
    aEn: 'have the office always at 18 degrees',
    bEn: 'have the office always at 27 degrees',
  },
  {
    a: 'im Büro einen Bürohund haben, der dich ständig ablenkt',
    b: 'im Büro keine Pflanzen, keine Tiere und keine Musik haben',
    aEn: 'have an office dog that distracts you all the time',
    bEn: 'have an office with no plants, no pets and no music',
  },
  {
    a: 'dass im Büro den ganzen Tag Radio läuft',
    b: 'dass im Büro absolute Stille herrscht wie in einer Bibliothek',
    aEn: 'have the radio on in the office all day',
    bEn: 'have total library silence in the office',
  },
  {
    a: 'dass in der Firmenküche nie Kaffee da ist',
    b: 'dass in der Firmenküche nie saubere Tassen da sind',
    aEn: 'never have coffee in the office kitchen',
    bEn: 'never have clean mugs in the office kitchen',
  },
  {
    a: 'für die Spülmaschine in der Büroküche zuständig sein',
    b: 'für das Kaffeekochen im ganzen Team zuständig sein',
    aEn: 'be in charge of the dishwasher in the office kitchen',
    bEn: 'be in charge of making coffee for the whole team',
  },
  {
    a: 'dass dein Schreibtisch ein Stehtisch ist, den du nie runterfahren kannst',
    b: 'dass dein Bürostuhl leicht kippelt',
    aEn: 'have a standing desk you can never lower',
    bEn: 'have an office chair that wobbles slightly',
  },
  {
    a: 'jeden Tag in der Kantine essen',
    b: 'jeden Tag dein Essen selbst vorkochen',
    aEn: 'eat in the cafeteria every day',
    bEn: 'meal-prep your own lunch every day',
  },
  {
    a: 'jeden Mittag mit dem ganzen Team essen gehen',
    b: 'jeden Mittag allein am Schreibtisch essen',
    aEn: 'go to lunch with the whole team every day',
    bEn: 'eat alone at your desk every day',
  },
  {
    a: 'dass der Chef jeden Freitag Pizza ausgibt',
    b: 'dass jeden Freitag um 15 Uhr Schluss ist',
    aEn: 'have the boss buy pizza every Friday',
    bEn: 'have work end at 3 p.m. every Friday',
  },
  {
    a: 'für jeden Geburtstag im Team einen Kuchen backen müssen',
    b: 'für jeden Geburtstag im Team ein Gedicht vortragen müssen',
    aEn: 'have to bake a cake for every birthday on the team',
    bEn: 'have to recite a poem for every birthday on the team',
  },
  {
    a: 'dass an deinem Geburtstag die ganze Firma für dich singt',
    b: 'dass deinen Geburtstag niemand im Büro mitbekommt',
    aEn: 'have the whole company sing for you on your birthday',
    bEn: 'have nobody at the office notice your birthday',
  },
  {
    a: 'dass dein Kühlschrankfach im Büro für alle sichtbar beschriftet ist',
    b: 'dass deine Snackschublade jeden Tag von Kollegen geplündert wird',
    aEn: 'have your fridge shelf at the office labeled for all to see',
    bEn: 'have your snack drawer raided by coworkers every day',
  },
  {
    a: 'beim Bewerbungsgespräch über einen Stuhl stolpern',
    b: 'beim Bewerbungsgespräch den Namen der Firma falsch sagen',
    aEn: 'trip over a chair in a job interview',
    bEn: 'say the company name wrong in a job interview',
  },
  {
    a: 'ein Bewerbungsgespräch mit zehn Leuten auf einmal haben',
    b: 'sieben Bewerbungsrunden einzeln durchlaufen',
    aEn: 'have a job interview with ten people at once',
    bEn: 'go through seven separate interview rounds',
  },
  {
    a: 'beim ersten Arbeitstag zu spät kommen',
    b: 'beim ersten Arbeitstag am falschen Standort stehen',
    aEn: 'be late on your first day of work',
    bEn: 'show up at the wrong location on your first day',
  },
  {
    a: 'den Namen eines Kollegen nach einem Jahr immer noch nicht wissen',
    b: 'einen Kollegen seit einem Jahr mit dem falschen Namen ansprechen',
    aEn: 'still not know a coworker’s name after a year',
    bEn: 'have called a coworker by the wrong name for a year',
  },
  {
    a: 'in deiner ersten Woche alle 200 Kollegen persönlich kennenlernen',
    b: 'in deiner ersten Woche niemanden außer deinem Team sehen',
    aEn: 'meet all 200 coworkers personally in your first week',
    bEn: 'see nobody but your team in your first week',
  },
  {
    a: 'dein Onboarding von einem Roboter bekommen',
    b: 'dein Onboarding von dem Kollegen bekommen, der morgen kündigt',
    aEn: 'be onboarded by a robot',
    bEn: 'be onboarded by the coworker who’s quitting tomorrow',
  },
  {
    a: 'im Arbeitsvertrag eine Klausel haben, dass du jeden Tag lächeln musst',
    b: 'im Arbeitsvertrag eine Klausel haben, dass du nie über Arbeit klagen darfst',
    aEn: 'have a clause in your contract that you must smile every day',
    bEn: 'have a clause in your contract that you can never complain about work',
  },
  {
    a: 'kündigen und eine dramatische Abschiedsrede halten',
    b: 'kündigen und ganz still verschwinden',
    aEn: 'quit and give a dramatic farewell speech',
    bEn: 'quit and quietly disappear',
  },
  {
    a: 'eine Abschiedsmail an die ganze Firma schreiben müssen',
    b: 'zum Abschied einen Ausstand für alle organisieren müssen',
    aEn: 'have to write a farewell email to the whole company',
    bEn: 'have to throw a farewell party for everyone',
  },
  {
    a: 'dass dein Nachfolger alles besser macht als du',
    b: 'dass dein Nachfolger alles kaputt macht, was du aufgebaut hast',
    aEn: 'have your successor do everything better than you',
    bEn: 'have your successor wreck everything you built',
  },
  {
    a: 'einen Job bekommen, weil du jemanden kennst',
    b: 'einen Job nicht bekommen, obwohl du die Beste warst',
    aEn: 'get a job because you know someone',
    bEn: 'not get a job even though you were the best',
  },
  {
    a: 'eine Probezeit von einem Jahr haben',
    b: 'eine Kündigungsfrist von einem Jahr haben',
    aEn: 'have a one-year probation period',
    bEn: 'have a one-year notice period',
  },
  {
    a: 'vor 300 Leuten eine Präsentation halten',
    b: 'einem einzigen schwierigen Kunden eine schlechte Nachricht überbringen',
    aEn: 'give a presentation in front of 300 people',
    bEn: 'deliver bad news to one single difficult client',
  },
  {
    a: 'dass deine Präsentation abstürzt und du frei weiterreden musst',
    b: 'dass in deiner Präsentation ein peinlicher Tippfehler auf jeder Folie steht',
    aEn: 'have your presentation crash and keep talking off the cuff',
    bEn: 'have an embarrassing typo on every slide of your presentation',
  },
  {
    a: 'jeden Fehler, den du machst, im Teammeeting beichten',
    b: 'dass jeder Fehler von dir anonym im Firmennewsletter landet',
    aEn: 'confess every mistake you make in the team meeting',
    bEn: 'have every mistake you make appear anonymously in the company newsletter',
  },
  {
    a: 'einen Fehler machen, der die Firma viel Geld kostet, und es sofort zugeben',
    b: 'einen Fehler machen, der nie rauskommt, und es für immer wissen',
    aEn: 'make a costly mistake for the company and admit it immediately',
    bEn: 'make a mistake that never comes out and know it forever',
  },
  {
    a: 'dass dein Name auf jedem Projekt steht, egal wie es läuft',
    b: 'dass dein Name auf keinem Projekt steht, egal wie gut es läuft',
    aEn: 'have your name on every project, however it goes',
    bEn: 'have your name on no project, however well it goes',
  },
  {
    a: 'jedes Projekt eine Woche zu früh abgeben',
    b: 'jedes Projekt auf den letzten Drücker, aber perfekt abgeben',
    aEn: 'hand in every project a week early',
    bEn: 'hand in every project at the last minute, but perfect',
  },
  {
    a: 'immer an fünf Projekten gleichzeitig arbeiten',
    b: 'drei Jahre lang an einem einzigen Projekt arbeiten',
    aEn: 'always work on five projects at once',
    bEn: 'work on a single project for three years',
  },
  {
    a: 'eine Deadline haben, die viel zu knapp ist',
    b: 'gar keine Deadline haben und nie fertig werden',
    aEn: 'have a deadline that’s far too tight',
    bEn: 'have no deadline at all and never finish',
  },
  {
    a: 'ein Projekt übernehmen, das komplett im Chaos versinkt',
    b: 'ein Projekt von null starten mit null Budget',
    aEn: 'take over a project that’s in total chaos',
    bEn: 'start a project from scratch with zero budget',
  },
  {
    a: 'in einem Team arbeiten, in dem jeder mitentscheidet',
    b: 'in einem Team arbeiten, in dem eine Person alles entscheidet',
    aEn: 'work in a team where everyone has a say',
    bEn: 'work in a team where one person decides everything',
  },
  {
    a: 'die Aufgabe bekommen, die niemand machen will',
    b: 'die Aufgabe bekommen, die alle machen wollen, aber unter Beobachtung',
    aEn: 'get the task nobody wants to do',
    bEn: 'get the task everyone wants, but under scrutiny',
  },
  {
    a: 'für jedes erledigte To-do ein Häkchen vor dem ganzen Team setzen',
    b: 'deine To-do-Liste niemals abschließen können',
    aEn: 'tick off every to-do in front of the whole team',
    bEn: 'never be able to finish your to-do list',
  },
  {
    a: 'als Teamleitung einen Kollegen entlassen müssen',
    b: 'als Kollege erfahren, dass du entlassen wirst',
    aEn: 'have to let a coworker go as team lead',
    bEn: 'find out as a coworker that you’re being let go',
  },
  {
    a: 'dass dein Team jedes Jahr ein neues Logo und einen neuen Namen bekommt',
    b: 'dass deine Firma alle sechs Monate umstrukturiert',
    aEn: 'have your team get a new logo and name every year',
    bEn: 'have your company restructure every six months',
  },
  {
    a: 'jedes Quartal neue Ziele bekommen',
    b: 'fünf Jahre lang die gleichen Ziele haben',
    aEn: 'get new goals every quarter',
    bEn: 'have the same goals for five years',
  },
  {
    a: 'dass jede Entscheidung von drei Abteilungen abgesegnet werden muss',
    b: 'dass jede Entscheidung spontan per Münzwurf fällt',
    aEn: 'have every decision approved by three departments',
    bEn: 'have every decision made on the spot by a coin toss',
  },
  {
    a: 'einen Kollegen einarbeiten, der nie zuhört',
    b: 'von einem Kollegen eingearbeitet werden, der nie etwas erklärt',
    aEn: 'train a coworker who never listens',
    bEn: 'be trained by a coworker who never explains anything',
  },
  {
    a: 'dass dein Lieblingskollege kündigt',
    b: 'dass dein Lieblingskollege befördert wird und dein Chef wird',
    aEn: 'have your favorite coworker quit',
    bEn: 'have your favorite coworker get promoted and become your boss',
  },
  {
    a: 'ein Team leiten, das klüger ist als du',
    b: 'in einem Team arbeiten, in dem du der Klügste bist',
    aEn: 'lead a team that’s smarter than you',
    bEn: 'work in a team where you’re the smartest',
  },
  {
    a: 'mit einem Kollegen arbeiten, der immer zu spät kommt',
    b: 'mit einem Kollegen arbeiten, der immer viel zu früh da ist und dich weckt',
    aEn: 'work with a coworker who’s always late',
    bEn: 'work with a coworker who’s always way too early and wakes you up',
  },
  {
    a: 'einen Kollegen haben, der in jedem Satz Anglizismen benutzt',
    b: 'einen Kollegen haben, der jede Abkürzung erfindet',
    aEn: 'have a coworker who uses buzzwords in every sentence',
    bEn: 'have a coworker who invents an acronym for everything',
  },
  {
    a: 'dass ein Kollege jede Pause mit dir verbringen will',
    b: 'dass ein Kollege dir jede Pause aus dem Weg geht',
    aEn: 'have a coworker who wants to spend every break with you',
    bEn: 'have a coworker who avoids you every break',
  },
  {
    a: 'jeden Tag einen Kollegen loben müssen',
    b: 'jeden Tag von einem Kollegen ehrliches Feedback bekommen',
    aEn: 'have to praise a coworker every day',
    bEn: 'get honest feedback from a coworker every day',
  },
  {
    a: 'dass alle Kollegen deine Eltern kennenlernen',
    b: 'dass alle Kollegen deine Wohnung sehen',
    aEn: 'have all your coworkers meet your parents',
    bEn: 'have all your coworkers see your apartment',
  },
  {
    a: 'mit Kollegen privat in den Urlaub fahren',
    b: 'Kollegen nie außerhalb der Arbeit sehen',
    aEn: 'go on a private vacation with coworkers',
    bEn: 'never see coworkers outside of work',
  },
  {
    a: 'dass ein Kollege dein Nachbar ist',
    b: 'dass ein Kollege dein Mitbewohner ist',
    aEn: 'have a coworker as your neighbor',
    bEn: 'have a coworker as your roommate',
  },
  {
    a: 'jede Woche ein After-Work-Bier mit dem Team trinken',
    b: 'einmal im Jahr eine riesige Firmenparty feiern',
    aEn: 'have an after-work drink with the team every week',
    bEn: 'have one huge company party a year',
  },
  {
    a: 'beim Teamevent die Spiele moderieren',
    b: 'beim Teamevent bei jedem Spiel mitmachen müssen',
    aEn: 'host the games at the team event',
    bEn: 'have to take part in every game at the team event',
  },
  {
    a: 'auf der Firmenfeier zu viel erzählen',
    b: 'auf der Firmenfeier als Einziger nüchtern bleiben',
    aEn: 'say too much at the company party',
    bEn: 'be the only sober one at the company party',
  },
  {
    a: 'beim Teamausflug wandern gehen',
    b: 'beim Teamausflug ein Museum besuchen',
    aEn: 'go hiking on the team outing',
    bEn: 'visit a museum on the team outing',
  },
  {
    a: 'dass jedes Teamevent ein Kostümmotto hat',
    b: 'dass jedes Teamevent eine Präsentation zu Firmenwerten enthält',
    aEn: 'have a costume theme at every team event',
    bEn: 'have a presentation on company values at every team event',
  },
  {
    a: 'beim Teamquiz alle Fragen zur Firmengeschichte beantworten müssen',
    b: 'beim Teamquiz Fragen über deine Kollegen beantworten müssen',
    aEn: 'have to answer all the company history questions at the team quiz',
    bEn: 'have to answer questions about your coworkers at the team quiz',
  },
  {
    a: 'beim Teamevent mit dem Vorstand im Boot rudern',
    b: 'beim Teamevent mit dem Vorstand Bowling spielen',
    aEn: 'row a boat with the board at the team event',
    bEn: 'go bowling with the board at the team event',
  },
  {
    a: 'dass Fotos vom Teamevent auf LinkedIn landen',
    b: 'dass Videos vom Teamevent im Firmen-Intranet landen',
    aEn: 'have photos from the team event end up on LinkedIn',
    bEn: 'have videos from the team event end up on the company intranet',
  },
  {
    a: 'täglich einen LinkedIn-Post über deine Arbeit schreiben',
    b: 'nie wieder irgendwo über deine Arbeit sprechen dürfen',
    aEn: 'write a LinkedIn post about your work every day',
    bEn: 'never be allowed to talk about your work anywhere again',
  },
  {
    a: 'dass dein Jobtitel auf LinkedIn falsch übersetzt ist',
    b: 'dass dein Profilbild auf LinkedIn ein altes Passfoto ist',
    aEn: 'have your job title mistranslated on LinkedIn',
    bEn: 'have an old passport photo as your LinkedIn picture',
  },
  {
    a: 'für die Firmenwebsite ein Video über dich drehen',
    b: 'für den Firmen-Podcast eine Stunde lang interviewt werden',
    aEn: 'shoot a video about yourself for the company website',
    bEn: 'be interviewed for an hour on the company podcast',
  },
  {
    a: 'dass dein Chef dich vor allen lobt',
    b: 'dass dein Chef dir unter vier Augen eine Gehaltserhöhung gibt',
    aEn: 'have your boss praise you in front of everyone',
    bEn: 'have your boss give you a raise in private',
  },
  {
    a: 'ein Jahr Sabbatical ohne Gehalt',
    b: 'drei Monate bezahlte Auszeit, aber nur einmal im Leben',
    aEn: 'take a year’s sabbatical without pay',
    bEn: 'get three months of paid leave, but only once in your life',
  },
  {
    a: 'eine Weiterbildung bezahlt bekommen, die zwei Jahre dauert',
    b: 'jeden Monat einen Tag für eigene Projekte bekommen',
    aEn: 'get a two-year training course paid for',
    bEn: 'get one day a month for your own projects',
  },
  {
    a: 'jede Woche einen Pflichtkurs zu Excel besuchen',
    b: 'jede Woche einen Pflichtkurs zu Achtsamkeit besuchen',
    aEn: 'attend a mandatory Excel course every week',
    bEn: 'attend a mandatory mindfulness course every week',
  },
  {
    a: 'dass jeder Mitarbeiter ein Haustier mitbringen darf',
    b: 'dass jeder Mitarbeiter ein Nickerchen im Ruheraum machen darf',
    aEn: 'have every employee be allowed to bring a pet',
    bEn: 'have every employee be allowed to nap in a quiet room',
  },
  {
    a: 'bei der Arbeit nie Musik hören dürfen',
    b: 'bei der Arbeit nur die Musik deines Chefs hören dürfen',
    aEn: 'never be allowed to listen to music at work',
    bEn: 'only be allowed to listen to your boss’s music at work',
  },
  {
    a: 'dass deine Firma eine Kleiderordnung mit Krawatte hat',
    b: 'dass deine Firma Firmenshirts für alle vorschreibt',
    aEn: 'have your company enforce a dress code with ties',
    bEn: 'have your company require branded shirts for everyone',
  },
  {
    a: 'jeden Tag pünktlich gehen, auch wenn noch Arbeit liegt',
    b: 'immer alles erledigen, auch wenn es spät wird',
    aEn: 'leave on time every day even if work is left',
    bEn: 'always get everything done, even if it gets late',
  },
  {
    a: 'dass dein Arbeitstag nur aus Calls besteht',
    b: 'dass dein Arbeitstag nur aus E-Mails besteht',
    aEn: 'have a workday made up only of calls',
    bEn: 'have a workday made up only of emails',
  },
  {
    a: 'im Call die ganze Zeit dein eigenes Gesicht groß sehen',
    b: 'im Call nie sehen können, wer gerade spricht',
    aEn: 'see your own face big on screen during every call',
    bEn: 'never be able to see who’s speaking on a call',
  },
  {
    a: 'dass jeder Call fünf Minuten zu spät anfängt',
    b: 'dass jeder Call fünf Minuten zu lang dauert',
    aEn: 'have every call start five minutes late',
    bEn: 'have every call run five minutes over',
  },
  {
    a: 'einen Workshop mit Post-its und Klebepunkten machen',
    b: 'einen Workshop mit Rollenspielen machen',
    aEn: 'do a workshop with sticky notes and dot voting',
    bEn: 'do a workshop with role-playing',
  },
  {
    a: 'dass in jedem Meeting jemand „Lass uns das offline besprechen“ sagt',
    b: 'dass in jedem Meeting jemand „Kannst du mich hören?“ fragt',
    aEn: 'have someone say “let’s take this offline” in every meeting',
    bEn: 'have someone ask “can you hear me?” in every meeting',
  },
  {
    a: 'in einem Meeting sitzen, in dem du nichts zu tun hast',
    b: 'in einem Meeting sein, in dem alle Fragen an dich gehen',
    aEn: 'sit in a meeting where you have nothing to do',
    bEn: 'be in a meeting where every question is directed at you',
  },
  {
    a: 'ein Brainstorming mit 20 Leuten leiten',
    b: 'ein Brainstorming ganz allein machen und dann präsentieren',
    aEn: 'lead a brainstorm with 20 people',
    bEn: 'brainstorm all alone and then present it',
  },
  {
    a: 'in einer Firma arbeiten, in der jeder alles sagen darf',
    b: 'in einer Firma arbeiten, in der alles diplomatisch verpackt wird',
    aEn: 'work at a company where everyone can say anything',
    bEn: 'work at a company where everything is diplomatically wrapped up',
  },
  {
    a: 'in einer kleinen Firma, in der dich jeder kennt',
    b: 'in einer riesigen Firma, in der du anonym bist',
    aEn: 'work at a small company where everyone knows you',
    bEn: 'work at a huge company where you’re anonymous',
  },
  {
    a: 'für eine Firma arbeiten, deren Produkt du liebst',
    b: 'für eine Firma arbeiten, deren Kollegen du liebst',
    aEn: 'work for a company whose product you love',
    bEn: 'work for a company whose people you love',
  },
  {
    a: 'ein Jahr lang nur nachts arbeiten',
    b: 'ein Jahr lang jedes Wochenende arbeiten',
    aEn: 'only work nights for a year',
    bEn: 'work every weekend for a year',
  },
  {
    a: 'dass jede deiner Arbeitsstunden aufgezeichnet wird',
    b: 'dass niemand weiß, was du eigentlich machst',
    aEn: 'have every one of your working hours tracked',
    bEn: 'have nobody know what you actually do',
  },
  {
    a: 'dass deine Kollegen dich für faul halten, obwohl du viel arbeitest',
    b: 'dass deine Kollegen dich für fleißig halten, obwohl du wenig tust',
    aEn: 'have coworkers think you’re lazy even though you work a lot',
    bEn: 'have coworkers think you’re hardworking even though you do little',
  },
  {
    a: 'dich in Meetings immer zu Wort melden müssen',
    b: 'immer als Letzter in Meetings sprechen dürfen',
    aEn: 'always have to speak up in meetings',
    bEn: 'always only get to speak last in meetings',
  },
  {
    a: 'dass deine Mutter bei deinem Arbeitgeber anruft',
    b: 'dass dein Arbeitgeber bei deiner Mutter anruft',
    aEn: 'have your mom call your employer',
    bEn: 'have your employer call your mom',
  },
  {
    a: 'jede Woche Pläne für die Zukunft der Firma schmieden',
    b: 'nie wissen, wie es mit der Firma weitergeht',
    aEn: 'make plans for the company’s future every week',
    bEn: 'never know where the company is headed',
  },
  {
    a: 'Chef sein und von allen gemocht werden',
    b: 'Chef sein und von allen respektiert werden',
    aEn: 'be the boss and be liked by everyone',
    bEn: 'be the boss and be respected by everyone',
  },
  {
    a: 'dass deine Arbeit nie gesehen, aber immer gebraucht wird',
    b: 'dass deine Arbeit immer gesehen, aber selten gebraucht wird',
    aEn: 'have your work never seen but always needed',
    bEn: 'have your work always seen but rarely needed',
  },
  {
    a: 'einen Tag mit dem CEO tauschen',
    b: 'einen Tag mit der Person am Empfang tauschen',
    aEn: 'swap places with the CEO for a day',
    bEn: 'swap places with the receptionist for a day',
  },
  {
    a: 'nur noch Aufgaben machen, die du kannst',
    b: 'nur noch Aufgaben machen, bei denen du etwas lernst',
    aEn: 'only do tasks you already know how to do',
    bEn: 'only do tasks where you learn something',
  },
  {
    a: 'die Präsentation machen und vorne stehen',
    b: 'die ganze Arbeit hinter der Präsentation machen',
    aEn: 'give the presentation and stand up front',
    bEn: 'do all the work behind the presentation',
  },
  {
    a: 'in einer Firma arbeiten, die vier Wochen Betriebsferien im August macht',
    b: 'in einer Firma arbeiten, in der du Urlaub nehmen kannst, wann du willst',
    aEn: 'work at a company that closes for four weeks in August',
    bEn: 'work at a company where you can take time off whenever you want',
  },
];
