import type { WouldYouRatherSeed } from './types';

export const crazyQuestions: WouldYouRatherSeed[] = [
  {
    a: 'jeden Morgen in einem zufälligen Land aufwachen',
    b: 'nie wieder schlafen müssen, aber immer müde sein',
    aEn: 'wake up in a random country every morning',
    bEn: 'never need sleep again but always feel tired',
  },
  {
    a: 'mit Tieren sprechen können, aber sie sind alle unhöflich',
    b: 'jede Sprache der Welt sprechen, aber nur flüsternd',
    aEn: 'talk to animals but they’re all rude',
    bEn: 'speak every language in the world but only in a whisper',
  },
  {
    a: 'zehn Minuten in die Zukunft sehen können',
    b: 'einmal am Tag zehn Sekunden zurückspulen können',
    aEn: 'see ten minutes into the future',
    bEn: 'rewind ten seconds once a day',
  },
  {
    a: 'einen Drachen haben, der so groß ist wie eine Katze',
    b: 'eine Katze haben, die so groß ist wie ein Drache',
    aEn: 'have a dragon the size of a cat',
    bEn: 'have a cat the size of a dragon',
  },
  {
    a: 'durch Wände gehen können, aber deine Schuhe bleiben jedes Mal stecken',
    b: 'dich teleportieren können, aber immer 50 Meter daneben landen',
    aEn: 'walk through walls but your shoes get stuck every time',
    bEn: 'teleport but always land 50 meters off',
  },
  {
    a: 'mit einem Smartphone ins Mittelalter reisen, aber ohne Ladekabel',
    b: 'mit allem, was du heute weißt, nochmal als Kind anfangen',
    aEn: 'travel to the Middle Ages with a smartphone but no charger',
    bEn: 'start over as a child with everything you know now',
  },
  {
    a: 'dass jeder deiner Gedanken als Untertitel über deinem Kopf erscheint',
    b: 'dass dein Leben einen Soundtrack hat, den alle hören',
    aEn: 'have every thought appear as subtitles above your head',
    bEn: 'have a soundtrack to your life that everyone can hear',
  },
  {
    a: 'für immer 25 bleiben, während alle um dich herum altern',
    b: 'ganz normal altern, aber nie krank werden',
    aEn: 'stay 25 forever while everyone around you ages',
    bEn: 'age normally but never get sick',
  },
  {
    a: 'eine Zeitmaschine haben, die nur in die Vergangenheit fährt',
    b: 'eine Zeitmaschine haben, die nur in die Zukunft fährt',
    aEn: 'own a time machine that only goes to the past',
    bEn: 'own a time machine that only goes to the future',
  },
  {
    a: 'jedes Mal niesen, wenn in deiner Nähe jemand lügt',
    b: 'jedes Mal Schluckauf bekommen, wenn du selbst lügst',
    aEn: 'sneeze every time someone near you lies',
    bEn: 'get hiccups every time you lie yourself',
  },
  {
    a: 'Pflanzen mit einer Berührung wachsen lassen',
    b: 'jedes kaputte Gerät mit einer Berührung reparieren',
    aEn: 'make plants grow with a touch',
    bEn: 'fix any broken device with a touch',
  },
  {
    a: 'in einem Videospiel deiner Wahl leben',
    b: 'in einem Film deiner Wahl leben',
    aEn: 'live inside a video game of your choice',
    bEn: 'live inside a movie of your choice',
  },
  {
    a: 'dass deine Haare jeden Tag zufällig die Farbe wechseln',
    b: 'dass deine Stimme jeden Tag wie ein anderer Promi klingt',
    aEn: 'have your hair change color randomly every day',
    bEn: 'have your voice sound like a different celebrity every day',
  },
  {
    a: 'ein Jahr auf dem Mars leben',
    b: 'ein Jahr in einer Unterwasserstation leben',
    aEn: 'live on Mars for a year',
    bEn: 'live in an underwater station for a year',
  },
  {
    a: 'von einem Geist verfolgt werden, der nur schlechte Witze erzählt',
    b: 'von einem Geist verfolgt werden, der dich ständig korrigiert',
    aEn: 'be haunted by a ghost who only tells bad jokes',
    bEn: 'be haunted by a ghost who constantly corrects you',
  },
  {
    a: 'die Schwerkraft um dich herum halbieren können',
    b: 'die Zeit für alle außer dir auf halbe Geschwindigkeit bremsen',
    aEn: 'halve the gravity around you',
    bEn: 'slow time to half speed for everyone but you',
  },
  {
    a: 'jeden deiner Träume bewusst steuern können',
    b: 'jede Nacht die Träume eines anderen Menschen sehen',
    aEn: 'control every dream you have',
    bEn: 'see someone else’s dreams every night',
  },
  {
    a: 'einen Vampir als Mitbewohner haben, der nie abwäscht',
    b: 'einen Werwolf als Mitbewohner haben, der bei Vollmond alles zerlegt',
    aEn: 'have a vampire roommate who never does the dishes',
    bEn: 'have a werewolf roommate who trashes the place every full moon',
  },
  {
    a: 'jede Lüge erkennen, aber selbst nie lügen können',
    b: 'perfekt lügen können, aber nie eine Lüge erkennen',
    aEn: 'detect every lie but never be able to lie yourself',
    bEn: 'lie perfectly but never be able to spot a lie',
  },
  {
    a: 'einen Knopf haben, der jede Ampel auf Grün schaltet',
    b: 'einen Knopf haben, mit dem du jede Warteschlange überspringst',
    aEn: 'have a button that turns every traffic light green',
    bEn: 'have a button that lets you skip any queue',
  },
  {
    a: '100 Jahre in die Zukunft reisen, ohne zurückzukönnen',
    b: '100 Jahre in die Vergangenheit reisen, ohne zurückzukönnen',
    aEn: 'travel 100 years into the future with no way back',
    bEn: 'travel 100 years into the past with no way back',
  },
  {
    a: 'so stark sein wie zehn Menschen, aber nur montags',
    b: 'doppelt so schlau sein, aber nur sonntags',
    aEn: 'be as strong as ten people but only on Mondays',
    bEn: 'be twice as smart but only on Sundays',
  },
  {
    a: 'dass für dich jedes Essen nach Pizza schmeckt',
    b: 'nie wieder Hunger haben, aber auch nichts mehr schmecken',
    aEn: 'have every food taste like pizza to you',
    bEn: 'never be hungry again but never taste anything either',
  },
  {
    a: 'einen Erzähler haben, der dein Leben kommentiert und den nur du hörst',
    b: 'einen Erzähler haben, den alle außer dir hören',
    aEn: 'have a narrator commenting on your life that only you can hear',
    bEn: 'have a narrator that everyone except you can hear',
  },
  {
    a: 'dich in jedes Tier verwandeln können, aber feststecken, wenn du einschläfst',
    b: 'einmal im Jahr für einen Tag eine zufällige andere Person sein',
    aEn: 'shapeshift into any animal but get stuck if you fall asleep',
    bEn: 'become a random other person for one day each year',
  },
  {
    a: 'Superkräfte haben, aber nur in einem lächerlichen Kostüm',
    b: 'der Sidekick eines echten Superhelden sein',
    aEn: 'have superpowers but only in a ridiculous costume',
    bEn: 'be the sidekick of a real superhero',
  },
  {
    a: 'von Aliens entführt werden und zurückkommen, aber keiner glaubt dir',
    b: 'Beweise für Aliens finden, aber niemandem davon erzählen dürfen',
    aEn: 'get abducted by aliens and come back but nobody believes you',
    bEn: 'find proof of aliens but never be allowed to tell anyone',
  },
  {
    a: 'für immer nur rückwärts laufen können',
    b: 'für immer nur in Reimen sprechen können',
    aEn: 'only ever be able to walk backwards',
    bEn: 'only ever be able to speak in rhymes',
  },
  {
    a: 'drei Wünsche frei haben, aber dein ärgster Feind bekommt jeden doppelt',
    b: 'einen Wunsch frei haben, den ein fieser Dschinn wörtlich nimmt',
    aEn: 'get three wishes but your worst enemy gets each one twice',
    bEn: 'get one wish that an evil genie takes literally',
  },
  {
    a: 'ein Schloss auf einer schwebenden Insel ohne WLAN besitzen',
    b: 'eine winzige Wohnung, deren Fenster jeden Tag woanders hinzeigen',
    aEn: 'own a castle on a floating island with no Wi-Fi',
    bEn: 'own a tiny flat whose windows look out somewhere new every day',
  },
  {
    a: 'auf Mausgröße schrumpfen können, wann immer du willst',
    b: 'auf drei Meter wachsen können, wann immer du willst',
    aEn: 'shrink to the size of a mouse whenever you want',
    bEn: 'grow to three meters tall whenever you want',
  },
  {
    a: 'jedes Buch der Welt in einer Sekunde lesen können',
    b: 'jedes Instrument sofort meisterhaft spielen können',
    aEn: 'read any book in the world in one second',
    bEn: 'play any instrument masterfully right away',
  },
  {
    a: 'einen Tag als dein Haustier erleben',
    b: 'dein Haustier einen Tag lang dein Leben führen lassen',
    aEn: 'spend a day as your pet',
    bEn: 'let your pet live your life for a day',
  },
  {
    a: 'ewig leben, aber als sprechender Baum',
    b: 'nur noch 30 Jahre leben, aber jeden Tag wie ein Rockstar',
    aEn: 'live forever but as a talking tree',
    bEn: 'live only 30 more years but every day like a rock star',
  },
  {
    a: 'dass jeder Raum, den du betrittst, sofort aufgeräumt ist',
    b: 'dass jeder Mensch, den du triffst, sofort gute Laune bekommt',
    aEn: 'have every room you enter tidy itself instantly',
    bEn: 'have everyone you meet cheer up instantly',
  },
  {
    a: 'in einer Welt ohne Musik leben',
    b: 'in einer Welt ohne Farben leben',
    aEn: 'live in a world without music',
    bEn: 'live in a world without colors',
  },
  {
    a: 'einen Klon haben, der deine Arbeit erledigt, aber langsam dein Leben übernimmt',
    b: 'ein Roboterdouble haben, das alles kann, aber nie lächelt',
    aEn: 'have a clone that does your work but is slowly taking over your life',
    bEn: 'have a robot double that can do everything but never smiles',
  },
  {
    a: 'alles in Gold verwandeln, was du anfasst, aber nur einmal im Monat',
    b: 'jeden Gegenstand verdoppeln können, aber nur Dinge unter einem Euro',
    aEn: 'turn anything you touch into gold but only once a month',
    bEn: 'duplicate any object but only things worth under one euro',
  },
  {
    a: 'in einer Welt aufwachen, in der die Dinosaurier nie ausgestorben sind',
    b: 'in einer Welt aufwachen, in der nie Strom erfunden wurde',
    aEn: 'wake up in a world where dinosaurs never died out',
    bEn: 'wake up in a world where electricity was never discovered',
  },
  {
    a: 'Geräusche als Farben sehen',
    b: 'Farben als Geräusche hören',
    aEn: 'see sounds as colors',
    bEn: 'hear colors as sounds',
  },
  {
    a: 'jeden Tag einen Euro mehr finden als am Tag davor',
    b: 'jetzt sofort 100.000 Euro bekommen',
    aEn: 'find one euro more each day than the day before',
    bEn: 'get 100,000 euros right now',
  },
  {
    a: 'die Zeit anhalten können, aber immer nur fünf Sekunden lang',
    b: 'eine Person deiner Wahl eine Stunde lang einfrieren können',
    aEn: 'stop time but only ever for five seconds',
    bEn: 'freeze one person of your choice for an hour',
  },
  {
    a: 'als Riese unter Menschen leben',
    b: 'als Mensch unter Riesen leben',
    aEn: 'live as a giant among humans',
    bEn: 'live as a human among giants',
  },
  {
    a: 'deine Lieblingsserie aus dem Gedächtnis löschen, um sie neu zu sehen',
    b: 'deine Lieblingsserie jederzeit komplett im Kopf abspielen können',
    aEn: 'erase your favorite show from memory to watch it fresh',
    bEn: 'replay your favorite show fully in your head anytime',
  },
  {
    a: 'eine Stimme haben, die Glas zerspringen lässt',
    b: 'einen Blick haben, der Milch sauer werden lässt',
    aEn: 'have a voice that shatters glass',
    bEn: 'have a stare that makes milk go sour',
  },
  {
    a: 'ein eigenes Raumschiff haben, das nur bis zum Mond fliegt',
    b: 'ein U-Boot haben, das überall hintaucht, aber nur rückwärts fährt',
    aEn: 'own a spaceship that only flies as far as the moon',
    bEn: 'own a submarine that dives anywhere but only goes backwards',
  },
  {
    a: 'dass jeder Kühlschrank, den du öffnest, voll ist',
    b: 'dass dich einmal am Tag eine Tür an einen Ort deiner Wahl bringt',
    aEn: 'have every fridge you open be full',
    bEn: 'have one door a day take you anywhere you choose',
  },
  {
    a: 'dass es jedes Mal Konfetti regnet, wenn du lachst',
    b: 'dass es draußen regnet, wann immer du traurig bist',
    aEn: 'have confetti rain down every time you laugh',
    bEn: 'have it rain outside whenever you’re sad',
  },
  {
    a: 'dich an alles erinnern, was du je erlebt hast',
    b: 'alles vergessen können, was du vergessen willst',
    aEn: 'remember everything you’ve ever experienced',
    bEn: 'be able to forget anything you want to forget',
  },
  {
    a: 'ein Spiegelbild mit eigenem Willen haben',
    b: 'einen Schatten mit eigenem Willen haben',
    aEn: 'have a reflection with a mind of its own',
    bEn: 'have a shadow with a mind of its own',
  },
  {
    a: 'rückwärts altern wie Benjamin Button',
    b: 'normal altern, aber ab 60 körperlich nie mehr abbauen',
    aEn: 'age backwards like Benjamin Button',
    bEn: 'age normally but never decline physically after 60',
  },
  {
    a: 'eine Pizza haben, die sich immer wieder selbst auffüllt',
    b: 'ein Glas haben, das sich immer mit deinem Lieblingsgetränk füllt',
    aEn: 'have a pizza that keeps refilling itself',
    bEn: 'have a glass that always refills with your favorite drink',
  },
  {
    a: 'dass dir alle Katzen der Welt hinterherlaufen',
    b: 'dass dir alle Tauben der Welt gehorchen',
    aEn: 'have every cat in the world follow you around',
    bEn: 'have every pigeon in the world obey you',
  },
  {
    a: 'auf einem Planeten mit zwei Sonnen leben, auf dem es nie dunkel wird',
    b: 'auf einem Planeten leben, auf dem immer Nacht ist und Polarlichter leuchten',
    aEn: 'live on a planet with two suns where it never gets dark',
    bEn: 'live on a planet where it’s always night and the auroras glow',
  },
  {
    a: 'die Gedanken von Tieren hören',
    b: 'die Gedanken von Babys hören',
    aEn: 'hear animals’ thoughts',
    bEn: 'hear babies’ thoughts',
  },
  {
    a: 'jeden Morgen eine zufällige Superkraft für den Tag bekommen',
    b: 'eine feste, aber ziemlich schwache Superkraft haben',
    aEn: 'get a random superpower every morning for that day',
    bEn: 'have one permanent but pretty weak superpower',
  },
  {
    a: 'als Hauptfigur in einem Horrorfilm aufwachen',
    b: 'als Nebenfigur in einer endlosen Seifenoper aufwachen',
    aEn: 'wake up as the main character in a horror movie',
    bEn: 'wake up as a side character in an endless soap opera',
  },
  {
    a: 'dass jeden Tag eine zufällige Stunde lang alle deine Gedanken hören',
    b: 'einen Tag pro Monat nur die Wahrheit sagen können',
    aEn: 'have everyone hear your thoughts for one random hour a day',
    bEn: 'be unable to say anything but the truth one day a month',
  },
  {
    a: 'mit einem Fingerschnippen jede Mahlzeit herbeizaubern',
    b: 'mit einem Fingerschnippen jede Wohnung blitzblank putzen',
    aEn: 'conjure any meal with a snap of your fingers',
    bEn: 'make any home spotless with a snap of your fingers',
  },
  {
    a: 'auf Wolken laufen können, aber nur barfuß',
    b: 'unter Wasser atmen können, aber an Land ständig husten',
    aEn: 'walk on clouds but only barefoot',
    bEn: 'breathe underwater but cough constantly on land',
  },
  {
    a: 'einen Tag mit deinem zehnjährigen Ich verbringen',
    b: 'einen Tag mit deinem 80-jährigen Ich verbringen',
    aEn: 'spend a day with your ten-year-old self',
    bEn: 'spend a day with your 80-year-old self',
  },
  {
    a: 'in einer Welt leben, in der Gemüse beim Schneiden schreit',
    b: 'in einer Welt leben, in der Steine summen, wenn man sie berührt',
    aEn: 'live in a world where vegetables scream when you cut them',
    bEn: 'live in a world where stones hum when you touch them',
  },
  {
    a: 'ein Zentaur sein',
    b: 'eine Meerjungfrau oder ein Meermann sein',
    aEn: 'be a centaur',
    bEn: 'be a mermaid or merman',
  },
  {
    a: 'jedes Schloss öffnen können',
    b: 'jedes Passwort sofort kennen',
    aEn: 'be able to open any lock',
    bEn: 'instantly know any password',
  },
  {
    a: 'jeden Abend um 20 Uhr einschlafen, egal wo du bist',
    b: 'jeden Morgen um 4 Uhr hellwach sein, egal wie spät es wurde',
    aEn: 'fall asleep at 8 p.m. every night wherever you are',
    bEn: 'be wide awake at 4 a.m. every morning no matter how late it got',
  },
  {
    a: 'in einer riesigen Seifenblase um die Welt reisen',
    b: 'auf dem Rücken einer Riesenschildkröte um die Welt reisen',
    aEn: 'travel the world in a giant soap bubble',
    bEn: 'travel the world on the back of a giant turtle',
  },
  {
    a: 'deinen größten Fehler ungeschehen machen, aber eine schöne Erinnerung verlieren',
    b: 'deine schönste Erinnerung nochmal erleben und sie danach für immer vergessen',
    aEn: 'undo your biggest mistake but lose one happy memory',
    bEn: 'relive your happiest memory once and then forget it forever',
  },
  {
    a: 'dass dein Bett dich jede Nacht an einen neuen Ort teleportiert',
    b: 'dass dein Auto selbst entscheidet, wohin es fährt',
    aEn: 'have your bed teleport you somewhere new every night',
    bEn: 'have your car decide for itself where to go',
  },
  {
    a: 'einen Superschurken als besten Freund haben',
    b: 'einen Superhelden als Erzfeind haben',
    aEn: 'have a supervillain as your best friend',
    bEn: 'have a superhero as your archenemy',
  },
  {
    a: 'das Wetter steuern können, aber nur in deiner Straße',
    b: 'überall, wo du bist, immer Frühling haben',
    aEn: 'control the weather but only on your street',
    bEn: 'have it always be spring wherever you are',
  },
  {
    a: 'eine Stunde mit jeder historischen Person reden, aber sie kann dich nicht leiden',
    b: 'eine Stunde mit deinem Ururenkel aus der Zukunft reden',
    aEn: 'talk to any historical figure for an hour, but they can’t stand you',
    bEn: 'talk to your great-great-grandchild from the future for an hour',
  },
  {
    a: 'leuchtende Fußspuren hinterlassen',
    b: 'dass überall, wo du gehst, Blumen wachsen',
    aEn: 'leave glowing footprints',
    bEn: 'have flowers grow wherever you walk',
  },
  {
    a: 'jedes Essen in Schokolade verwandeln können',
    b: 'jede Flüssigkeit in Kaffee verwandeln können',
    aEn: 'turn any food into chocolate',
    bEn: 'turn any liquid into coffee',
  },
  {
    a: 'alle zehn Jahre einen neuen, zufälligen Körper bekommen',
    b: 'für immer deinen Körper behalten, aber er ist leicht durchsichtig',
    aEn: 'get a new random body every ten years',
    bEn: 'keep your body forever but it’s slightly see-through',
  },
  {
    a: 'in einer Welt ohne Spiegel leben',
    b: 'in einer Welt ohne Uhren leben',
    aEn: 'live in a world without mirrors',
    bEn: 'live in a world without clocks',
  },
  {
    a: 'einen Tag lang der Bösewicht in deinem Lieblingsfilm sein',
    b: 'einen Tag lang der Held in dem Film sein, den du am meisten hasst',
    aEn: 'be the villain in your favorite movie for a day',
    bEn: 'be the hero in the movie you hate most for a day',
  },
  {
    a: 'jeden Menschen zum Lachen bringen können',
    b: 'jeden Menschen sofort beruhigen können',
    aEn: 'be able to make anyone laugh',
    bEn: 'be able to calm anyone down instantly',
  },
  {
    a: 'dass alles, was du sagst, als Opernarie herauskommt',
    b: 'dass alles, was du sagst, als Echo zurückhallt',
    aEn: 'have everything you say come out as an opera aria',
    bEn: 'have everything you say echo back',
  },
  {
    a: 'auf einem Raumschiff geboren sein, das nie landet',
    b: 'auf einem Planeten geboren sein, den noch nie jemand verlassen hat',
    aEn: 'be born on a spaceship that never lands',
    bEn: 'be born on a planet nobody has ever left',
  },
  {
    a: 'schweben können, aber nur einen Meter über dem Boden',
    b: 'zehn Meter hoch springen können, aber jedes Mal hart landen',
    aEn: 'hover but only one meter above the ground',
    bEn: 'jump ten meters high but land hard every time',
  },
  {
    a: 'Haustiere haben, die sprechen können, aber nur über dich lästern',
    b: 'Zimmerpflanzen haben, die dich laut beschimpfen, wenn du sie vergisst',
    aEn: 'have pets that can talk but only gossip about you',
    bEn: 'have houseplants that yell at you when you forget them',
  },
  {
    a: 'einen Tag im Jahr 3000 verbringen',
    b: 'einen Tag im alten Rom verbringen',
    aEn: 'spend a day in the year 3000',
    bEn: 'spend a day in ancient Rome',
  },
  {
    a: 'dich nie wieder verlaufen können',
    b: 'nie wieder etwas verlieren können',
    aEn: 'never get lost again',
    bEn: 'never lose anything again',
  },
  {
    a: 'in einer Zeitschleife stecken, aus der nur ein perfekter Tag rausführt',
    b: 'jeden Tag am nächsten Morgen komplett vergessen',
    aEn: 'be stuck in a time loop that only a perfect day gets you out of',
    bEn: 'completely forget each day the next morning',
  },
  {
    a: 'dass die Welt zu einem Zeichentrickfilm wird',
    b: 'dass die Welt zu einem Musical wird',
    aEn: 'have the world turn into a cartoon',
    bEn: 'have the world turn into a musical',
  },
  {
    a: 'ein Telefon haben, mit dem du in die Vergangenheit anrufen kannst',
    b: 'ein Telefon haben, das Anrufe aus der Zukunft empfängt',
    aEn: 'have a phone that can call the past',
    bEn: 'have a phone that receives calls from the future',
  },
  {
    a: 'einen Tag lang den Körper mit der Person links von dir tauschen',
    b: 'einen Tag lang den Körper mit der Person rechts von dir tauschen',
    aEn: 'swap bodies for a day with the person on your left',
    bEn: 'swap bodies for a day with the person on your right',
  },
  {
    a: 'Feuer kontrollieren können, aber immer frieren',
    b: 'Eis kontrollieren können, aber immer schwitzen',
    aEn: 'control fire but always feel cold',
    bEn: 'control ice but always be sweating',
  },
  {
    a: 'dein Pech an andere weitergeben können',
    b: 'dir das Glück anderer kurz ausleihen können',
    aEn: 'pass your bad luck on to others',
    bEn: 'briefly borrow other people’s good luck',
  },
  {
    a: 'jeden Menschen mit einem Fingerschnippen verstummen lassen',
    b: 'jedem Menschen eine Frage stellen, die er ehrlich beantworten muss',
    aEn: 'silence anyone with a snap of your fingers',
    bEn: 'ask anyone one question they must answer honestly',
  },
  {
    a: 'mit einem Koch, der nie redet, auf einer einsamen Insel stranden',
    b: 'mit einem Entertainer, der nie aufhört zu reden, auf einer Insel stranden',
    aEn: 'be stranded on a desert island with a chef who never talks',
    bEn: 'be stranded on an island with an entertainer who never stops talking',
  },
  {
    a: 'in einem Haus wohnen, dessen Räume sich jede Nacht neu anordnen',
    b: 'in einem Haus wohnen, das jede Woche in eine andere Stadt umzieht',
    aEn: 'live in a house whose rooms rearrange every night',
    bEn: 'live in a house that moves to a new city every week',
  },
  {
    a: 'deine Gedanken als Bilder auf Papier drucken können',
    b: 'deine Träume als Film aufnehmen können',
    aEn: 'print your thoughts as pictures on paper',
    bEn: 'record your dreams as films',
  },
  {
    a: 'so verflucht sein, dass du quakst wie ein Frosch, wenn du lügst',
    b: 'so verflucht sein, dass deine Nase leuchtet, wenn du verliebt bist',
    aEn: 'be cursed to croak like a frog whenever you lie',
    bEn: 'be cursed with a nose that glows whenever you’re in love',
  },
  {
    a: 'in einer Welt leben, in der Geld auf Bäumen wächst und alles irre teuer ist',
    b: 'in einer Welt leben, in der alles gratis ist, du aber alles selbst baust',
    aEn: 'live where money grows on trees and everything is wildly expensive',
    bEn: 'live where everything is free but you have to build it all yourself',
  },
  {
    a: 'nie wieder Schmerzen spüren',
    b: 'die Gefühle aller Menschen im Raum spüren',
    aEn: 'never feel pain again',
    bEn: 'feel the emotions of everyone in the room',
  },
  {
    a: 'die Erde einmal aus dem Weltall sehen',
    b: 'einmal den tiefsten Punkt im Meer erkunden',
    aEn: 'see Earth from space once',
    bEn: 'explore the deepest point of the ocean once',
  },
  {
    a: 'ein Mammut als Haustier haben',
    b: 'einen Säbelzahntiger als Haustier haben',
    aEn: 'have a mammoth as a pet',
    bEn: 'have a saber-toothed tiger as a pet',
  },
  {
    a: 'dass deine Lügen nach faulen Eiern riechen',
    b: 'dass du bei jeder Wahrheit leicht glitzerst',
    aEn: 'have your lies smell like rotten eggs',
    bEn: 'sparkle slightly every time you tell the truth',
  },
  {
    a: 'eine Woche Urlaub auf dem Mond machen, aber der Rückflug dauert ein Jahr',
    b: 'einen Monat Urlaub in einem Paralleluniversum machen',
    aEn: 'vacation on the moon for a week but the flight home takes a year',
    bEn: 'vacation in a parallel universe for a month',
  },
  {
    a: 'dein Ich aus einem Paralleluniversum treffen, das alles besser hinkriegt',
    b: 'dein Ich aus einem Paralleluniversum treffen, das gescheitert ist und dir die Schuld gibt',
    aEn: 'meet your parallel-universe self who does everything better',
    bEn: 'meet your parallel-universe self who failed and blames you',
  },
  {
    a: 'wie ein Gecko Wände hochlaufen können',
    b: 'wie eine Eule den Kopf fast ganz umdrehen können',
    aEn: 'climb walls like a gecko',
    bEn: 'turn your head almost all the way around like an owl',
  },
  {
    a: 'eine Lampe mit einem Dschinn finden, der nur mittelmäßige Wünsche erfüllt',
    b: 'eine gute Fee haben, die nur dienstags arbeitet',
    aEn: 'find a lamp with a genie who only grants mediocre wishes',
    bEn: 'have a fairy godmother who only works on Tuesdays',
  },
  {
    a: 'einen Herzschlag haben, den alle laut hören',
    b: 'einen Magen haben, der beim Knurren Melodien spielt',
    aEn: 'have a heartbeat everyone can hear',
    bEn: 'have a stomach that growls little melodies',
  },
  {
    a: 'anderen Menschen Lebenszeit abkaufen können',
    b: 'deine eigene Lebenszeit für viel Geld verkaufen können',
    aEn: 'be able to buy lifetime from other people',
    bEn: 'be able to sell your own lifetime for a lot of money',
  },
  {
    a: 'allein auf einer Raumstation wohnen, an die nachts etwas klopft',
    b: 'allein in einem Leuchtturm wohnen, in dem nachts jemand singt',
    aEn: 'live alone on a space station where something knocks at night',
    bEn: 'live alone in a lighthouse where someone sings at night',
  },
  {
    a: 'dich überallhin beamen können, aber nur an Orte, an denen du schon warst',
    b: 'dich überallhin beamen können, aber nur an Orte, an denen du nie warst',
    aEn: 'teleport anywhere but only to places you’ve been',
    bEn: 'teleport anywhere but only to places you’ve never been',
  },
  {
    a: 'jedes Tier reiten können',
    b: 'jedes Fahrzeug fahren können',
    aEn: 'be able to ride any animal',
    bEn: 'be able to drive any vehicle',
  },
  {
    a: 'Flügel haben, die zu klein zum Fliegen sind',
    b: 'einen Schwanz haben, der all deine Gefühle verrät',
    aEn: 'have wings too small to fly with',
    bEn: 'have a tail that gives away all your feelings',
  },
  {
    a: 'dass jedes Lied, das du summst, sofort im Radio läuft',
    b: 'dass jeder Satz, den du sagst, zum Meme wird',
    aEn: 'have every song you hum play on the radio right away',
    bEn: 'have every sentence you say turn into a meme',
  },
  {
    a: 'mit einem Feuerzeug in der Steinzeit landen',
    b: 'mit einer Taschenlampe im Wilden Westen landen',
    aEn: 'land in the Stone Age with a lighter',
    bEn: 'land in the Wild West with a flashlight',
  },
  {
    a: 'ein Zauberer sein, der nur Löffel verbiegen kann',
    b: 'hellsehen können, aber nur das Wetter von morgen',
    aEn: 'be a wizard who can only bend spoons',
    bEn: 'be psychic but only about tomorrow’s weather',
  },
  {
    a: 'dass jede Pflanze verwelkt, die du ansiehst',
    b: 'dass jede Uhr in deiner Nähe stehen bleibt',
    aEn: 'wilt every plant you look at',
    bEn: 'stop every clock near you',
  },
  {
    a: 'die einzige Person sein, die sich an eine gelöschte Zeitlinie erinnert',
    b: 'die einzige Person sein, die Geister sehen kann',
    aEn: 'be the only person who remembers an erased timeline',
    bEn: 'be the only person who can see ghosts',
  },
  {
    a: 'Energie aus Sonnenlicht ziehen und nie mehr essen müssen',
    b: 'Energie aus Musik ziehen und nie mehr schlafen müssen',
    aEn: 'draw energy from sunlight and never need to eat',
    bEn: 'draw energy from music and never need to sleep',
  },
  {
    a: 'dass bei jedem Klatschen irgendwo auf der Welt ein Licht ausgeht',
    b: 'dass bei jedem Pfiff von dir ein fremder Hund angerannt kommt',
    aEn: 'make a light go out somewhere in the world every time you clap',
    bEn: 'have a stranger’s dog come running every time you whistle',
  },
  {
    a: 'einen Tag lang ein Dinosaurier sein',
    b: 'einen Tag lang ein Blauwal sein',
    aEn: 'be a dinosaur for a day',
    bEn: 'be a blue whale for a day',
  },
  {
    a: 'sieben Jahre am Stück schlafen und als Millionär aufwachen',
    b: 'sieben Jahre über ein Fantasyreich herrschen und dann ins normale Leben zurück',
    aEn: 'sleep for seven years straight and wake up a millionaire',
    bEn: 'rule a fantasy kingdom for seven years, then return to normal life',
  },
  {
    a: 'das nächste Kapitel deines Lebens vorab lesen können',
    b: 'das Tagebuch jedes Menschen einmal lesen dürfen',
    aEn: 'read the next chapter of your life in advance',
    bEn: 'read anyone’s diary once',
  },
  {
    a: 'einen Geist als Butler haben',
    b: 'einen sprechenden Raben als Assistenten haben',
    aEn: 'have a ghost as your butler',
    bEn: 'have a talking raven as your assistant',
  },
  {
    a: 'für immer auf den Mond ziehen, aber mit WLAN',
    b: 'auf der Erde bleiben, aber nie wieder verreisen',
    aEn: 'move to the moon forever, but with Wi-Fi',
    bEn: 'stay on Earth but never travel again',
  },
  {
    a: 'beim Gähnen kleine Feuerbälle spucken',
    b: 'beim Lachen Seifenblasen ausatmen',
    aEn: 'spit little fireballs when you yawn',
    bEn: 'breathe out soap bubbles when you laugh',
  },
  {
    a: 'Dinge mit Gedanken bewegen, aber nur bis 100 Gramm',
    b: 'Gegenstände zu dir rufen, aber nur aus dem Nachbarraum',
    aEn: 'move things with your mind but only up to 100 grams',
    bEn: 'summon objects to you but only from the next room',
  },
  {
    a: 'die Welt mit den Augen einer Fliege sehen',
    b: 'die Welt mit den Ohren einer Fledermaus hören',
    aEn: 'see the world through a fly’s eyes',
    bEn: 'hear the world with a bat’s ears',
  },
  {
    a: 'immer wissen, was andere über dich denken',
    b: 'dass nie jemand schlecht über dich denkt, du aber nie erfährst, was',
    aEn: 'always know what others think of you',
    bEn: 'have nobody ever think badly of you but never know what they think',
  },
  {
    a: 'in einem Dorf in einer Schneekugel leben',
    b: 'in einem Puppenhaus leben, in das ein Riesenkind hineinschaut',
    aEn: 'live in a village inside a snow globe',
    bEn: 'live in a dollhouse that a giant child peers into',
  },
  {
    a: 'das Ende jedes Films schon vorher kennen',
    b: 'nie wieder einen Film zu Ende sehen können',
    aEn: 'know the ending of every movie in advance',
    bEn: 'never be able to finish a movie again',
  },
  {
    a: 'dich zehnmal klonen können, aber nur einen Tag im Jahr',
    b: 'jedes Jahr einen Extratag bekommen, den nur du erlebst',
    aEn: 'clone yourself ten times but only one day a year',
    bEn: 'get one extra day every year that only you experience',
  },
  {
    a: 'Laseraugen haben, die nur funktionieren, wenn du weinst',
    b: 'Tränen haben, die Wunden heilen, aber nur wenn du vor Lachen weinst',
    aEn: 'have laser eyes that only work when you cry',
    bEn: 'have tears that heal wounds but only when you cry with laughter',
  },
  {
    a: 'eine Bibliothek mit allen Büchern besuchen, die nie geschrieben wurden',
    b: 'ein Museum mit allem besuchen, was je verloren ging',
    aEn: 'visit a library of every book never written',
    bEn: 'visit a museum of everything ever lost',
  },
  {
    a: 'in einer Welt mit Ameisen so groß wie Hunde leben',
    b: 'in einer Welt mit Pferden so groß wie Hamster leben',
    aEn: 'live in a world with ants the size of dogs',
    bEn: 'live in a world with horses the size of hamsters',
  },
  {
    a: 'einen eigenen Planeten besitzen, auf dem du allein lebst',
    b: 'auf der Erde bleiben, aber in einer Stadt mit 100 Millionen Menschen',
    aEn: 'own your own planet where you live alone',
    bEn: 'stay on Earth but in a city of 100 million people',
  },
  {
    a: 'eine Sanduhr haben, die einmal im Leben einen ganzen Tag zurückdreht',
    b: 'eine Sanduhr haben, die jede Woche eine Stunde zurückdreht',
    aEn: 'have an hourglass that turns back a whole day once in your life',
    bEn: 'have an hourglass that turns back one hour every week',
  },
  {
    a: 'Ritter in einer Fantasywelt sein',
    b: 'Hacker in einer Cyberpunkwelt sein',
    aEn: 'be a knight in a fantasy world',
    bEn: 'be a hacker in a cyberpunk world',
  },
  {
    a: 'einen Tag geschrumpft in einem Ameisenhaufen verbringen',
    b: 'einen Tag im Bauch eines Wals verbringen wie Pinocchio',
    aEn: 'spend a day shrunk down in an anthill',
    bEn: 'spend a day in the belly of a whale like Pinocchio',
  },
  {
    a: 'die Stimme jedes Menschen perfekt nachmachen können',
    b: 'das Gesicht jedes Menschen annehmen können',
    aEn: 'perfectly imitate anyone’s voice',
    bEn: 'take on anyone’s face',
  },
  {
    a: 'dass für dich die Schwerkraft jeden Tag die Richtung wechselt',
    b: 'dass dein Tag 30 Stunden hat, während alle anderen 24 haben',
    aEn: 'have gravity change direction for you every day',
    bEn: 'have 30-hour days while everyone else gets 24',
  },
  {
    a: 'in einer Welt leben, die von freundlichen Robotern regiert wird',
    b: 'in einer Welt leben, die von sehr klugen Katzen regiert wird',
    aEn: 'live in a world ruled by friendly robots',
    bEn: 'live in a world ruled by very smart cats',
  },
  {
    a: 'andere heilen können, aber ihre Schmerzen kurz selbst spüren',
    b: 'jede Krankheit sofort erkennen, aber keine heilen können',
    aEn: 'heal others but briefly feel their pain yourself',
    bEn: 'recognize any illness instantly but be unable to cure any',
  },
  {
    a: 'ein Schwert haben, das immer trifft, aber ununterbrochen redet',
    b: 'einen Schild haben, der alles abwehrt, aber nur, wenn du singst',
    aEn: 'have a sword that never misses but never stops talking',
    bEn: 'have a shield that blocks everything but only while you sing',
  },
  {
    a: 'dein Outfit per Gedanken wechseln können',
    b: 'deine Frisur per Gedanken ändern können',
    aEn: 'change your outfit with a thought',
    bEn: 'change your hairstyle with a thought',
  },
  {
    a: 'einen Kompass haben, der immer zu dem zeigt, was du am meisten willst',
    b: 'eine Karte haben, die zeigt, wo alle deine Bekannten gerade sind',
    aEn: 'have a compass that always points to what you want most',
    bEn: 'have a map showing where everyone you know is right now',
  },
  {
    a: 'ein Pinguin in der Wüste sein',
    b: 'ein Kamel in der Arktis sein',
    aEn: 'be a penguin in the desert',
    bEn: 'be a camel in the Arctic',
  },
  {
    a: 'dich bei jedem Vollmond in ein Huhn verwandeln',
    b: 'dich bei jedem Gewitter in einen Igel verwandeln',
    aEn: 'turn into a chicken every full moon',
    bEn: 'turn into a hedgehog during every thunderstorm',
  },
  {
    a: 'in einer Welt aus Lego leben',
    b: 'in einer Welt aus Zuckerwatte leben',
    aEn: 'live in a world made of Lego',
    bEn: 'live in a world made of cotton candy',
  },
  {
    a: 'einen Roboter haben, der dich perfekt versteht, aber alles ausplaudert',
    b: 'einen Roboter haben, der schweigt wie ein Grab, dich aber nie versteht',
    aEn: 'have a robot that understands you perfectly but blabs everything',
    bEn: 'have a robot that’s silent as the grave but never understands you',
  },
  {
    a: 'eine Minute lang 1000 Jahre in die Zukunft blicken',
    b: 'eine Stunde lang 1000 Jahre in die Vergangenheit blicken',
    aEn: 'look 1,000 years into the future for one minute',
    bEn: 'look 1,000 years into the past for one hour',
  },
  {
    a: 'das Gedächtnis eines Goldfischs haben, aber immer glücklich sein',
    b: 'ein perfektes Gedächtnis haben, aber oft ins Grübeln kommen',
    aEn: 'have a goldfish’s memory but always be happy',
    bEn: 'have a perfect memory but brood a lot',
  },
  {
    a: 'dass alle deine Befehle befolgen, aber nur drei Wörter pro Tag',
    b: 'dass dir alle vertrauen, egal was du sagst',
    aEn: 'have everyone obey your commands, but only three words a day',
    bEn: 'have everyone trust you no matter what you say',
  },
  {
    a: 'in einer Stadt in den Wolken leben',
    b: 'in einer Stadt tief unter der Erde leben',
    aEn: 'live in a city in the clouds',
    bEn: 'live in a city deep underground',
  },
  {
    a: 'einen Zauberspiegel haben, der immer brutal ehrlich ist',
    b: 'einen Zauberspiegel haben, der dir immer schmeichelt',
    aEn: 'have a magic mirror that’s always brutally honest',
    bEn: 'have a magic mirror that always flatters you',
  },
  {
    a: 'dass Leute bei jeder Umarmung eine Erinnerung von dir sehen',
    b: 'dass du bei jeder Umarmung eine Erinnerung der anderen siehst',
    aEn: 'have people see one of your memories every time you hug',
    bEn: 'see one of their memories every time you hug someone',
  },
  {
    a: 'eine Fernbedienung für dein Leben mit Vorspultaste haben',
    b: 'eine Fernbedienung für dein Leben mit Pausetaste haben',
    aEn: 'have a remote for your life with a fast-forward button',
    bEn: 'have a remote for your life with a pause button',
  },
  {
    a: 'der letzte Mensch auf der Erde sein, aber mit allem, was du willst',
    b: 'einer von zehn Menschen auf einem fremden Planeten sein',
    aEn: 'be the last person on Earth but with everything you want',
    bEn: 'be one of ten people on an alien planet',
  },
  {
    a: 'jeden Sport auf Profiniveau beherrschen, aber nur ohne Zuschauer',
    b: 'überall Durchschnitt sein, außer vor Publikum, da bist du genial',
    aEn: 'play any sport at a pro level but only with nobody watching',
    bEn: 'be average at everything except in front of a crowd, where you’re brilliant',
  },
  {
    a: 'ein Dinosaurierei ausbrüten und das Tier großziehen',
    b: 'ein Alienbaby großziehen, das vom Himmel gefallen ist',
    aEn: 'hatch a dinosaur egg and raise the creature',
    bEn: 'raise an alien baby that fell from the sky',
  },
  {
    a: 'dass alle Musik der Welt nach Blockflöte klingt',
    b: 'dass alle Stimmen der Welt nach Helium klingen',
    aEn: 'have all the music in the world sound like a recorder',
    bEn: 'have every voice in the world sound like helium',
  },
  {
    a: 'einen Kleiderschrank haben, der in eine Fantasywelt führt',
    b: 'ein Portal im Keller haben, das in eine Science-Fiction-Welt führt',
    aEn: 'have a wardrobe that leads to a fantasy world',
    bEn: 'have a portal in your basement that leads to a sci-fi world',
  },
  {
    a: 'jedes Geräusch um dich herum stummschalten können',
    b: 'jeden Geruch um dich herum ausblenden können',
    aEn: 'mute any sound around you',
    bEn: 'block out any smell around you',
  },
  {
    a: 'von einem freundlichen Monster unter deinem Bett beschützt werden',
    b: 'überall von einem mürrischen Schutzengel begleitet werden',
    aEn: 'be protected by a friendly monster under your bed',
    bEn: 'be followed everywhere by a grumpy guardian angel',
  },
  {
    a: 'dass jeder Morgen mit einer Achterbahnfahrt beginnt',
    b: 'dass jeder Abend mit einem Feuerwerk nur für dich endet',
    aEn: 'start every morning with a roller coaster ride',
    bEn: 'end every evening with fireworks just for you',
  },
  {
    a: 'auf einer flachen Erde direkt am Rand wohnen',
    b: 'im Inneren einer hohlen Erde wohnen',
    aEn: 'live on a flat Earth right at the edge',
    bEn: 'live inside a hollow Earth',
  },
  {
    a: 'nie länger als drei Tage am selben Ort bleiben dürfen',
    b: 'nie wieder die Stadt verlassen dürfen, in der du gerade bist',
    aEn: 'never stay anywhere longer than three days',
    bEn: 'never leave the city you’re in right now',
  },
  {
    a: 'die Gedanken von Fremden hören, aber nie die von Freunden',
    b: 'die Gedanken von Freunden hören, aber nie die von Fremden',
    aEn: 'hear strangers’ thoughts but never your friends’',
    bEn: 'hear your friends’ thoughts but never strangers’',
  },
  {
    a: 'Eis haben, das nie schmilzt',
    b: 'Kaffee haben, der nie kalt wird',
    aEn: 'have ice cream that never melts',
    bEn: 'have coffee that never gets cold',
  },
  {
    a: 'Pirat auf einem fliegenden Schiff sein',
    b: 'Kopfgeldjäger in einer fernen Galaxie sein',
    aEn: 'be a pirate on a flying ship',
    bEn: 'be a bounty hunter in a distant galaxy',
  },
  {
    a: 'nach deinem Tod als Geist in deinem Haus bleiben',
    b: 'als zufälliges Tier wiedergeboren werden',
    aEn: 'stay on as a ghost in your house after you die',
    bEn: 'be reborn as a random animal',
  },
  {
    a: 'ein Tattoo haben, das sich jeden Tag verändert',
    b: 'Augen haben, die je nach Laune die Farbe wechseln',
    aEn: 'have a tattoo that changes every day',
    bEn: 'have eyes that change color with your mood',
  },
  {
    a: 'wissen, wo jeder verlorene Schatz der Welt liegt',
    b: 'jedes verlorene Haustier der Welt finden können',
    aEn: 'know where every lost treasure in the world is',
    bEn: 'be able to find every lost pet in the world',
  },
  {
    a: 'Blitze aus deinen Fingern schießen, aber jedes Handy in der Nähe geht kaputt',
    b: 'Metall anziehen wie ein Magnet, ohne es abschalten zu können',
    aEn: 'shoot lightning from your fingers but fry every phone nearby',
    bEn: 'attract metal like a magnet with no way to switch it off',
  },
  {
    a: 'dein Leben lang von einem langsamen Zombie verfolgt werden, der nie aufgibt',
    b: 'jede Nacht vor einer sehr schnellen Mumie flüchten müssen',
    aEn: 'be followed your whole life by a slow zombie that never gives up',
    bEn: 'have to flee from a very fast mummy every night',
  },
  {
    a: 'die Menschheit bei den Aliens vertreten',
    b: 'die Aliens bei der Menschheit vertreten',
    aEn: 'represent humanity to the aliens',
    bEn: 'represent the aliens to humanity',
  },
  {
    a: 'riechen können wie ein Spürhund',
    b: 'sehen können wie ein Adler',
    aEn: 'smell like a sniffer dog',
    bEn: 'see like an eagle',
  },
  {
    a: 'für immer in einem Freizeitpark leben',
    b: 'für immer in einem Einkaufszentrum leben',
    aEn: 'live in an amusement park forever',
    bEn: 'live in a shopping mall forever',
  },
  {
    a: 'dass jeder Satz in deinem Tagebuch wahr wird, aber erst nach einem Jahr',
    b: 'dass jeder Wunsch, den du laut aussprichst, sofort wahr wird, aber nur halb',
    aEn: 'have every sentence in your diary come true, but only after a year',
    bEn: 'have every wish you say out loud come true instantly, but only halfway',
  },
  {
    a: 'auf einem Besen fliegen, der Höhenangst hat',
    b: 'auf einem fliegenden Teppich reisen, der seekrank wird',
    aEn: 'ride a broomstick that’s afraid of heights',
    bEn: 'travel on a flying carpet that gets seasick',
  },
  {
    a: 'einen Jetpack mit fünf Minuten Akku haben',
    b: 'Stiefel haben, mit denen du an der Decke laufen kannst',
    aEn: 'have a jetpack with a five-minute battery',
    bEn: 'have boots that let you walk on the ceiling',
  },
  {
    a: 'an jedem Geburtstag in ein zufälliges anderes Jahrzehnt springen',
    b: 'an jedem Geburtstag dein kommendes Jahr vorab sehen',
    aEn: 'jump to a random decade on every birthday',
    bEn: 'get a preview of your coming year on every birthday',
  },
  {
    a: 'einen Glücksbringer haben, der wirklich wirkt, aber furchtbar stinkt',
    b: 'einen Talisman haben, der dich vor jedem Unglück schützt, aber laut piept',
    aEn: 'have a lucky charm that really works but smells awful',
    bEn: 'have a talisman that protects you from all misfortune but beeps loudly',
  },
  {
    a: 'die Welt sehen wie ein Gemälde von van Gogh',
    b: 'die Welt sehen wie ein verpixeltes Videospiel',
    aEn: 'see the world like a Van Gogh painting',
    bEn: 'see the world like a pixelated video game',
  },
  {
    a: 'die Laune aller Menschen als Farbe über ihrem Kopf sehen',
    b: 'bei allen Menschen einen Akkubalken sehen, der zeigt, wie müde sie sind',
    aEn: 'see everyone’s mood as a color above their head',
    bEn: 'see a battery bar on everyone showing how tired they are',
  },
  {
    a: 'durch jeden Spiegel in einen anderen Spiegel steigen können',
    b: 'durch Pfützen in andere Pfützen auf der Welt springen können',
    aEn: 'step through any mirror into another mirror',
    bEn: 'jump through puddles into other puddles around the world',
  },
  {
    a: 'die Hauptfigur in einem Märchen sein, das nicht gut ausgeht',
    b: 'eine Nebenfigur in einem Märchen mit Happy End sein',
    aEn: 'be the main character in a fairy tale with a bad ending',
    bEn: 'be a minor character in a fairy tale with a happy ending',
  },
  {
    a: 'dass die ersten Aliens auf der Erde aussehen wie Kartoffeln',
    b: 'dass die ersten Aliens auf der Erde genauso aussehen wie deine Familie',
    aEn: 'have the first aliens on Earth look like potatoes',
    bEn: 'have the first aliens on Earth look exactly like your family',
  },
  {
    a: 'jede Woche eine neue Fähigkeit lernen, aber eine alte vergessen',
    b: 'nie wieder etwas Neues lernen, aber auch nie etwas vergessen',
    aEn: 'learn a new skill every week but forget an old one',
    bEn: 'never learn anything new again but never forget anything either',
  },
  {
    a: 'in einem Lebkuchenhaus wohnen, das ständig angeknabbert wird',
    b: 'in einem Glashaus mitten in der Stadt wohnen',
    aEn: 'live in a gingerbread house that keeps getting nibbled',
    bEn: 'live in a glass house in the middle of the city',
  },
  {
    a: 'einen Kühlschrank haben, der beleidigt ist, wenn du ungesund isst',
    b: 'ein Handy haben, das eifersüchtig wird, wenn du es weglegst',
    aEn: 'have a fridge that sulks when you eat junk',
    bEn: 'have a phone that gets jealous when you put it down',
  },
  {
    a: 'Sternschnuppen herbeirufen können, die aber keine Wünsche erfüllen',
    b: 'einmal im Jahr eine Sonnenfinsternis auslösen können',
    aEn: 'summon shooting stars that don’t grant any wishes',
    bEn: 'trigger a solar eclipse once a year',
  },
  {
    a: 'einen Tag lang die Naturgesetze für dich umschreiben dürfen',
    b: 'einen Tag lang über die ganze Welt bestimmen dürfen',
    aEn: 'rewrite the laws of nature for yourself for one day',
    bEn: 'rule the whole world for one day',
  },
  {
    a: 'ein Fahrrad haben, das bei Vollmond fliegen kann',
    b: 'einen Regenschirm haben, mit dem du durch die Luft gleiten kannst',
    aEn: 'have a bike that can fly under a full moon',
    bEn: 'have an umbrella you can glide through the air with',
  },
  {
    a: 'dein Bewusstsein in einen Roboter laden und ewig leben',
    b: 'als Mensch sterben, aber erst mit 150',
    aEn: 'upload your mind into a robot and live forever',
    bEn: 'die as a human, but not until 150',
  },
  {
    a: 'einen Tag lang mit den Erinnerungen eines Fremden leben',
    b: 'einen Tag lang all deine eigenen Erinnerungen verlieren',
    aEn: 'live for a day with a stranger’s memories',
    bEn: 'lose all your own memories for a day',
  },
  {
    a: 'hauptberuflich Monster jagen',
    b: 'hauptberuflich Spukfälle aufklären',
    aEn: 'hunt monsters for a living',
    bEn: 'solve hauntings for a living',
  },
  {
    a: 'einen Zettel mit zehn Wörtern an dein jüngeres Ich schicken',
    b: 'einen Zettel mit zehn Wörtern von deinem älteren Ich bekommen',
    aEn: 'send a ten-word note to your younger self',
    bEn: 'receive a ten-word note from your older self',
  },
  {
    a: 'einen Zoo voller Fabelwesen leiten',
    b: 'ein Aquarium voller Tiefseemonster leiten',
    aEn: 'run a zoo full of mythical creatures',
    bEn: 'run an aquarium full of deep-sea monsters',
  },
  {
    a: 'Schuhe haben, mit denen du nie müde wirst',
    b: 'eine Jacke haben, in der dir immer genau richtig warm ist',
    aEn: 'own shoes that never let you get tired',
    bEn: 'own a jacket that always keeps you at exactly the right temperature',
  },
  {
    a: 'nie wieder sprechen, aber Gedanken an andere senden können',
    b: 'laut sprechen können, aber nur mit der Stimme eines Fremden',
    aEn: 'never speak again but be able to send thoughts to others',
    bEn: 'speak out loud but only in a stranger’s voice',
  },
  {
    a: 'einen Tag lang die Entstehung der Erde beobachten',
    b: 'einen Tag lang beim Bau der Pyramiden zuschauen',
    aEn: 'watch the formation of the Earth for a day',
    bEn: 'watch the pyramids being built for a day',
  },
  {
    a: 'einen Kraken als Haustier haben, der heimlich Sachen klaut',
    b: 'ein Faultier als Haustier haben, das dich perfekt nachäfft',
    aEn: 'have a pet octopus that secretly steals things',
    bEn: 'have a pet sloth that imitates you perfectly',
  },
  {
    a: 'in einer Welt leben, in der alle Superkräfte haben außer dir',
    b: 'der einzige Mensch mit Superkräften sein, dem niemand vertraut',
    aEn: 'live in a world where everyone has superpowers except you',
    bEn: 'be the only person with superpowers and have nobody trust you',
  },
];
