import type { WouldYouRatherSeed } from './types';

export const deepQuestions: WouldYouRatherSeed[] = [
  {
    a: 'wissen, wann du stirbst',
    b: 'wissen, wie du stirbst',
    aEn: 'know when you will die',
    bEn: 'know how you will die',
  },
  {
    a: 'alle Erinnerungen an deine erste große Liebe verlieren',
    b: 'alle Erinnerungen an deine Kindheit verlieren',
    aEn: 'lose every memory of your first great love',
    bEn: 'lose every memory of your childhood',
  },
  {
    a: 'noch einmal 18 sein, mit deinem heutigen Wissen',
    b: 'für immer so alt bleiben, wie du jetzt bist',
    aEn: 'be 18 again with everything you know now',
    bEn: 'stay the age you are now forever',
  },
  {
    a: 'einen Tag aus deiner Vergangenheit noch einmal erleben',
    b: 'einen Tag aus deiner Zukunft vorab sehen',
    aEn: 'relive one day from your past',
    bEn: 'see one day from your future in advance',
  },
  {
    a: 'jede Erinnerung perfekt behalten',
    b: 'schlechte Erinnerungen gezielt löschen können',
    aEn: 'remember everything perfectly',
    bEn: 'be able to delete bad memories on purpose',
  },
  {
    a: 'die Vergangenheit ändern können',
    b: 'die Zukunft sehen können',
    aEn: 'be able to change the past',
    bEn: 'be able to see the future',
  },
  {
    a: 'ein langes, ruhiges Leben führen',
    b: 'ein kurzes, aufregendes Leben führen',
    aEn: 'live a long, quiet life',
    bEn: 'live a short, exciting life',
  },
  {
    a: 'einen verstorbenen Menschen noch einmal umarmen',
    b: 'einem verstorbenen Menschen noch eine Frage stellen',
    aEn: 'hug someone who has died one more time',
    bEn: 'ask someone who has died one more question',
  },
  {
    a: 'dein ganzes Leben als Film anschauen können',
    b: 'einen Tag lang im Kopf eines anderen Menschen leben',
    aEn: 'be able to watch your whole life as a movie',
    bEn: 'live inside another person’s head for a day',
  },
  {
    a: 'für immer 30 bleiben, während alle anderen altern',
    b: 'ganz normal mit allen anderen zusammen alt werden',
    aEn: 'stay 30 forever while everyone else ages',
    bEn: 'grow old normally alongside everyone else',
  },
  {
    a: 'die Zeit für alle anhalten können, nur nicht für dich',
    b: 'ein Jahr deines Lebens zurückspulen können',
    aEn: 'be able to stop time for everyone but you',
    bEn: 'be able to rewind one year of your life',
  },
  {
    a: 'jeden Morgen ohne Erinnerung an gestern aufwachen',
    b: 'jeden Tag denselben Tag noch einmal erleben',
    aEn: 'wake up every morning with no memory of yesterday',
    bEn: 'live the same day over and over again',
  },
  {
    a: 'ein Tagebuch über dein ganzes Leben lesen können',
    b: 'die Briefe lesen, die deine Großeltern sich geschrieben haben',
    aEn: 'be able to read a diary of your entire life',
    bEn: 'read the letters your grandparents wrote to each other',
  },
  {
    a: 'dich an jeden Traum erinnern',
    b: 'nie mehr träumen, aber immer tief schlafen',
    aEn: 'remember every dream you have',
    bEn: 'never dream again but always sleep deeply',
  },
  {
    a: 'zehn Jahre länger leben',
    b: 'deine letzten zehn Jahre bei bester Gesundheit verbringen',
    aEn: 'live ten years longer',
    bEn: 'spend your last ten years in perfect health',
  },
  {
    a: 'einen Moment deines Lebens für immer festhalten können',
    b: 'einen Moment deines Lebens ungeschehen machen können',
    aEn: 'be able to hold on to one moment of your life forever',
    bEn: 'be able to undo one moment of your life',
  },
  {
    a: 'das Ende deines Lebens kennen',
    b: 'das Ende der Menschheit kennen',
    aEn: 'know how your life ends',
    bEn: 'know how humanity ends',
  },
  {
    a: 'in der Vergangenheit leben, mit allem, was du heute weißt',
    b: 'in der Zukunft leben, ohne zu wissen, was dort normal ist',
    aEn: 'live in the past with everything you know today',
    bEn: 'live in the future without knowing what’s normal there',
  },
  {
    a: 'mit 40 alles verlieren und neu anfangen',
    b: 'mit 20 alles haben und nichts mehr erreichen müssen',
    aEn: 'lose everything at 40 and start over',
    bEn: 'have everything at 20 and never need to achieve anything again',
  },
  {
    a: 'wissen, an welchem Tag du am glücklichsten sein wirst',
    b: 'wissen, an welchem Tag du am traurigsten sein wirst',
    aEn: 'know the day you’ll be happiest',
    bEn: 'know the day you’ll be saddest',
  },
  {
    a: 'eine große Liebe haben, die irgendwann endet',
    b: 'viele schöne Beziehungen, aber nie die eine',
    aEn: 'have one great love that eventually ends',
    bEn: 'have many good relationships but never the one',
  },
  {
    a: 'geliebt werden, ohne selbst so zu lieben',
    b: 'lieben, ohne genauso zurückgeliebt zu werden',
    aEn: 'be loved without loving back as much',
    bEn: 'love without being loved back as much',
  },
  {
    a: 'genau wissen, was dein Partner wirklich für dich fühlt',
    b: 'nie nachfragen und einfach darauf vertrauen',
    aEn: 'know exactly what your partner really feels for you',
    bEn: 'never ask and simply trust it',
  },
  {
    a: 'einen besten Freund fürs ganze Leben haben',
    b: 'in jeder Lebensphase neue enge Freunde finden',
    aEn: 'have one best friend for your whole life',
    bEn: 'find new close friends in every phase of life',
  },
  {
    a: 'deine Familie aussuchen können',
    b: 'deine Freunde nie verlieren können',
    aEn: 'be able to choose your family',
    bEn: 'never be able to lose your friends',
  },
  {
    a: 'dass dein Partner deine Gedanken lesen kann',
    b: 'dass du die Gedanken deines Partners lesen kannst',
    aEn: 'have your partner be able to read your thoughts',
    bEn: 'be able to read your partner’s thoughts',
  },
  {
    a: 'mit deiner ersten Liebe für immer zusammenbleiben',
    b: 'die Liebe deines Lebens erst mit 50 treffen',
    aEn: 'stay with your first love forever',
    bEn: 'meet the love of your life at 50',
  },
  {
    a: 'einen Streit mit einem geliebten Menschen nie klären',
    b: 'einen Freund verlieren, ohne je zu erfahren, warum',
    aEn: 'never resolve a fight with someone you love',
    bEn: 'lose a friend without ever knowing why',
  },
  {
    a: 'eine Beziehung voller Leidenschaft, aber mit viel Streit',
    b: 'eine Beziehung voller Ruhe, aber ohne Kribbeln',
    aEn: 'have a relationship full of passion but lots of fighting',
    bEn: 'have a relationship full of calm but no butterflies',
  },
  {
    a: 'dass alle deine Exen ehrlich sagen, was sie über dich denken',
    b: 'dass deine engsten Freunde ehrlich sagen, was sie über dich denken',
    aEn: 'have all your exes honestly say what they think of you',
    bEn: 'have your closest friends honestly say what they think of you',
  },
  {
    a: 'allein und glücklich sein',
    b: 'in einer Beziehung zufrieden, aber nie wirklich glücklich sein',
    aEn: 'be single and happy',
    bEn: 'be content in a relationship but never truly happy',
  },
  {
    a: 'für die Liebe in ein fremdes Land ziehen',
    b: 'für die Liebe deinen Traumjob aufgeben',
    aEn: 'move to a foreign country for love',
    bEn: 'give up your dream job for love',
  },
  {
    a: 'einem Menschen verzeihen, der dich tief verletzt hat',
    b: 'Verzeihung von jemandem bekommen, den du tief verletzt hast',
    aEn: 'forgive someone who hurt you deeply',
    bEn: 'be forgiven by someone you hurt deeply',
  },
  {
    a: 'deinen Eltern alles erzählen können',
    b: 'von deinen Eltern alles erfahren, was sie dir verschwiegen haben',
    aEn: 'be able to tell your parents everything',
    bEn: 'learn everything your parents kept from you',
  },
  {
    a: 'dass deine Kinder dich als Freund sehen',
    b: 'dass deine Kinder dich als Vorbild sehen',
    aEn: 'have your kids see you as a friend',
    bEn: 'have your kids see you as a role model',
  },
  {
    a: 'einen Freund haben, der immer ehrlich ist',
    b: 'einen Freund haben, der immer zu dir hält',
    aEn: 'have a friend who is always honest',
    bEn: 'have a friend who always has your back',
  },
  {
    a: 'jemanden heiraten, den deine Familie liebt, du aber nur magst',
    b: 'jemanden heiraten, den du liebst, deine Familie aber ablehnt',
    aEn: 'marry someone your family loves but you only like',
    bEn: 'marry someone you love but your family rejects',
  },
  {
    a: 'nie wieder einsam sein',
    b: 'nie wieder enttäuscht werden',
    aEn: 'never feel lonely again',
    bEn: 'never be disappointed again',
  },
  {
    a: 'wissen, wer heimlich in dich verliebt war',
    b: 'wissen, wer heimlich schlecht über dich redet',
    aEn: 'know who was secretly in love with you',
    bEn: 'know who secretly talks badly about you',
  },
  {
    a: 'deinem Seelenverwandten nur einmal kurz begegnen',
    b: 'ihm nie begegnen und nie davon erfahren',
    aEn: 'meet your soulmate only once, briefly',
    bEn: 'never meet them and never know it',
  },
  {
    a: 'immer die Wahrheit sagen müssen',
    b: 'nie erkennen können, wenn jemand lügt',
    aEn: 'always have to tell the truth',
    bEn: 'never be able to tell when someone is lying',
  },
  {
    a: 'ein guter Mensch sein, den niemand mag',
    b: 'ein schlechter Mensch sein, den alle lieben',
    aEn: 'be a good person nobody likes',
    bEn: 'be a bad person everyone loves',
  },
  {
    a: 'reich sein, aber nie zufrieden',
    b: 'wenig haben, aber jeden Tag zufrieden sein',
    aEn: 'be rich but never satisfied',
    bEn: 'have little but be content every day',
  },
  {
    a: 'einem Fremden das Leben retten, ohne dass es je jemand erfährt',
    b: 'als Held gefeiert werden für etwas, das du nicht getan hast',
    aEn: 'save a stranger’s life without anyone ever knowing',
    bEn: 'be celebrated as a hero for something you didn’t do',
  },
  {
    a: 'deinen Werten treu bleiben und den Job verlieren',
    b: 'den Job behalten und gegen deine Werte handeln',
    aEn: 'stay true to your values and lose your job',
    bEn: 'keep your job and act against your values',
  },
  {
    a: 'die Welt ein bisschen besser machen und vergessen werden',
    b: 'berühmt werden, ohne irgendetwas zu bewirken',
    aEn: 'make the world a little better and be forgotten',
    bEn: 'become famous without changing anything',
  },
  {
    a: 'immer gerecht urteilen',
    b: 'immer barmherzig urteilen',
    aEn: 'always judge fairly',
    bEn: 'always judge mercifully',
  },
  {
    a: 'eine Lüge erzählen, die einen Freund schützt',
    b: 'die Wahrheit sagen, auch wenn sie ihn verletzt',
    aEn: 'tell a lie that protects a friend',
    bEn: 'tell the truth even if it hurts them',
  },
  {
    a: 'für das Richtige kämpfen und verlieren',
    b: 'dich anpassen und gewinnen',
    aEn: 'fight for what’s right and lose',
    bEn: 'go along with things and win',
  },
  {
    a: 'wissen, was andere wirklich von dir denken',
    b: 'dir nie wieder Gedanken darüber machen',
    aEn: 'know what others really think of you',
    bEn: 'never worry about it again',
  },
  {
    a: 'allen anderen alles vergeben können',
    b: 'dir selbst alles vergeben können',
    aEn: 'be able to forgive others for everything',
    bEn: 'be able to forgive yourself for everything',
  },
  {
    a: 'die Macht haben, Hunger auf der Welt zu beenden',
    b: 'die Macht haben, eine tödliche Krankheit auszurotten',
    aEn: 'have the power to end world hunger',
    bEn: 'have the power to wipe out a deadly disease',
  },
  {
    a: 'ein Versprechen brechen, um jemandem zu helfen',
    b: 'ein Versprechen halten, obwohl es jemandem schadet',
    aEn: 'break a promise to help someone',
    bEn: 'keep a promise even though it hurts someone',
  },
  {
    a: 'in einer Welt ohne Lügen leben',
    b: 'in einer Welt ohne Geheimnisse leben',
    aEn: 'live in a world without lies',
    bEn: 'live in a world without secrets',
  },
  {
    a: 'für deine Überzeugung ins Gefängnis gehen',
    b: 'deine Überzeugung öffentlich widerrufen und frei bleiben',
    aEn: 'go to prison for your beliefs',
    bEn: 'publicly renounce your beliefs and stay free',
  },
  {
    a: 'die Hälfte deines Vermögens spenden',
    b: 'ein Jahr deines Lebens ehrenamtlich arbeiten',
    aEn: 'donate half of everything you own',
    bEn: 'spend a year of your life volunteering',
  },
  {
    a: 'eine Entscheidung treffen, die vielen hilft und einem schwer schadet',
    b: 'eine, die einem hilft und vielen ein bisschen schadet',
    aEn: 'make a choice that helps many and badly hurts one',
    bEn: 'make one that helps one and hurts many a little',
  },
  {
    a: 'in einer perfekten Simulation glücklich sein',
    b: 'in der echten Welt kämpfen müssen',
    aEn: 'be happy in a perfect simulation',
    bEn: 'have to struggle in the real world',
  },
  {
    a: 'immer wissen, was richtig ist',
    b: 'immer die Kraft haben, das Richtige zu tun',
    aEn: 'always know what’s right',
    bEn: 'always have the strength to do what’s right',
  },
  {
    a: 'nie wieder neidisch sein',
    b: 'nie wieder wütend sein',
    aEn: 'never feel envy again',
    bEn: 'never feel anger again',
  },
  {
    a: 'einen Job lieben, der schlecht bezahlt ist',
    b: 'einen Job hassen, der dich reich macht',
    aEn: 'love a job that pays badly',
    bEn: 'hate a job that makes you rich',
  },
  {
    a: 'in einer Sache die Beste der Welt sein',
    b: 'in vielen Sachen ziemlich gut sein',
    aEn: 'be the best in the world at one thing',
    bEn: 'be pretty good at many things',
  },
  {
    a: 'selbstständig sein, mit ständiger Existenzangst',
    b: 'angestellt sein, mit voller Sicherheit',
    aEn: 'be your own boss with constant money worries',
    bEn: 'be an employee with complete security',
  },
  {
    a: 'mit 35 aufhören zu arbeiten und sparsam leben',
    b: 'bis 70 arbeiten, aber in deinem Traumberuf',
    aEn: 'stop working at 35 and live frugally',
    bEn: 'work until 70 but in your dream job',
  },
  {
    a: 'selbst einen Nobelpreis gewinnen',
    b: 'ein Kind großziehen, das einen gewinnt',
    aEn: 'win a Nobel Prize yourself',
    bEn: 'raise a child who wins one',
  },
  {
    a: 'vier Tage die Woche arbeiten und weniger verdienen',
    b: 'fünf Tage arbeiten und deutlich mehr verdienen',
    aEn: 'work four days a week and earn less',
    bEn: 'work five days and earn a lot more',
  },
  {
    a: 'den Traumberuf aus deiner Kindheit ausüben',
    b: 'einen Beruf finden, von dem du heute noch nichts weißt',
    aEn: 'do your childhood dream job',
    bEn: 'find a job you don’t even know exists yet',
  },
  {
    a: 'etwas erschaffen, das dich überlebt',
    b: 'dein eigenes Leben so glücklich wie möglich leben',
    aEn: 'create something that outlives you',
    bEn: 'live your own life as happily as possible',
  },
  {
    a: 'Talent ohne Ehrgeiz haben',
    b: 'Ehrgeiz ohne Talent haben',
    aEn: 'have talent without ambition',
    bEn: 'have ambition without talent',
  },
  {
    a: 'bei etwas scheitern, das dir wichtig ist',
    b: 'Erfolg haben bei etwas, das dir egal ist',
    aEn: 'fail at something that matters to you',
    bEn: 'succeed at something you don’t care about',
  },
  {
    a: 'dein ganzes Leben an einem Ort verbringen',
    b: 'alle zwei Jahre in eine neue Stadt ziehen',
    aEn: 'spend your whole life in one place',
    bEn: 'move to a new city every two years',
  },
  {
    a: 'deine Leidenschaft zum Beruf machen',
    b: 'sie als Hobby behalten, das dir niemand verdirbt',
    aEn: 'turn your passion into your job',
    bEn: 'keep it as a hobby nobody can ruin for you',
  },
  {
    a: 'ein Jahr Auszeit nehmen und danach neu anfangen',
    b: 'weiterarbeiten und in fünf Jahren sicher aufsteigen',
    aEn: 'take a year off and start fresh afterwards',
    bEn: 'keep working and get a sure promotion in five years',
  },
  {
    a: 'für eine Idee alles riskieren',
    b: 'ein sicheres Leben ohne große Wetten führen',
    aEn: 'risk everything for an idea',
    bEn: 'live a safe life without big bets',
  },
  {
    a: 'von deinen Kollegen respektiert werden',
    b: 'von deinen Kollegen gemocht werden',
    aEn: 'be respected by your coworkers',
    bEn: 'be liked by your coworkers',
  },
  {
    a: 'genau wissen, welcher Beruf dich glücklich macht',
    b: 'genug Geld haben, um nie arbeiten zu müssen',
    aEn: 'know exactly which job would make you happy',
    bEn: 'have enough money to never work',
  },
  {
    a: 'als Lehrkraft ein einzelnes Leben grundlegend verändern',
    b: 'als Gründer tausend Arbeitsplätze schaffen',
    aEn: 'change one life completely as a teacher',
    bEn: 'create a thousand jobs as a founder',
  },
  {
    a: 'ein Werk schaffen, das erst nach deinem Tod berühmt wird',
    b: 'eins, das jetzt gefeiert und dann vergessen wird',
    aEn: 'create a work that only becomes famous after you die',
    bEn: 'create one that’s celebrated now and forgotten later',
  },
  {
    a: 'für deine Arbeit gelobt, aber unterbezahlt werden',
    b: 'gut bezahlt, aber nie wahrgenommen werden',
    aEn: 'be praised for your work but underpaid',
    bEn: 'be well paid but never noticed',
  },
  {
    a: 'im Beruf große Kompromisse machen',
    b: 'in der Liebe große Kompromisse machen',
    aEn: 'make big compromises in your career',
    bEn: 'make big compromises in love',
  },
  {
    a: 'so gesehen werden, wie du wirklich bist',
    b: 'so gesehen werden, wie du gern wärst',
    aEn: 'be seen as you really are',
    bEn: 'be seen as you wish you were',
  },
  {
    a: 'in einem anderen Land geboren sein',
    b: 'in einer anderen Zeit geboren sein',
    aEn: 'have been born in another country',
    bEn: 'have been born in another era',
  },
  {
    a: 'deine größte Angst überwinden',
    b: 'dir deinen größten Traum erfüllen',
    aEn: 'overcome your biggest fear',
    bEn: 'fulfill your biggest dream',
  },
  {
    a: 'eine Eigenschaft an dir ändern können',
    b: 'eine Entscheidung in deinem Leben ändern können',
    aEn: 'be able to change one trait about yourself',
    bEn: 'be able to change one decision in your life',
  },
  {
    a: 'deine Muttersprache für immer verlieren',
    b: 'deine Heimatstadt nie wieder sehen',
    aEn: 'lose your native language forever',
    bEn: 'never see your hometown again',
  },
  {
    a: 'eine Woche als anderes Geschlecht leben',
    b: 'eine Woche in einer völlig fremden Kultur leben',
    aEn: 'live as another gender for a week',
    bEn: 'live in a completely foreign culture for a week',
  },
  {
    a: 'hören, was bei deiner Beerdigung über dich gesagt wird',
    b: 'lesen, was deine Eltern damals über dich ins Tagebuch geschrieben haben',
    aEn: 'hear what people say about you at your funeral',
    bEn: 'read what your parents once wrote about you in their diary',
  },
  {
    a: 'sehr intelligent, aber oft traurig sein',
    b: 'durchschnittlich klug und meistens glücklich sein',
    aEn: 'be very intelligent but often sad',
    bEn: 'be average and mostly happy',
  },
  {
    a: 'dich nie wieder schämen',
    b: 'dich nie wieder schuldig fühlen',
    aEn: 'never feel ashamed again',
    bEn: 'never feel guilty again',
  },
  {
    a: 'dich selbst als besten Freund haben',
    b: 'dich selbst als Elternteil haben',
    aEn: 'have yourself as your best friend',
    bEn: 'have yourself as your parent',
  },
  {
    a: 'immer wissen, was du willst',
    b: 'immer bekommen, was du brauchst',
    aEn: 'always know what you want',
    bEn: 'always get what you need',
  },
  {
    a: 'die Person werden, die deine Eltern sich gewünscht haben',
    b: 'die Person werden, die du mit 15 sein wolltest',
    aEn: 'become the person your parents hoped for',
    bEn: 'become the person you wanted to be at 15',
  },
  {
    a: 'von allen ein bisschen verstanden werden',
    b: 'von einem einzigen Menschen komplett verstanden werden',
    aEn: 'be understood a little by everyone',
    bEn: 'be completely understood by one single person',
  },
  {
    a: 'deine Persönlichkeit behalten, aber einen anderen Körper haben',
    b: 'deinen Körper behalten, aber eine andere Persönlichkeit haben',
    aEn: 'keep your personality but have a different body',
    bEn: 'keep your body but have a different personality',
  },
  {
    a: 'viel mutiger sein',
    b: 'viel gelassener sein',
    aEn: 'be much braver',
    bEn: 'be much calmer',
  },
  {
    a: 'ein Leben ohne Zweifel führen',
    b: 'ein Leben ohne Angst führen',
    aEn: 'live a life without doubt',
    bEn: 'live a life without fear',
  },
  {
    a: 'dich an keinen deiner Fehler mehr erinnern',
    b: 'aus jedem Fehler doppelt so viel lernen',
    aEn: 'never remember any of your mistakes',
    bEn: 'learn twice as much from every mistake',
  },
  {
    a: 'für etwas bekannt sein, das du bereust',
    b: 'für gar nichts bekannt sein',
    aEn: 'be known for something you regret',
    bEn: 'be known for nothing at all',
  },
  {
    a: 'in deinem Leben alles selbst entscheiden',
    b: 'alle großen Entscheidungen einem Menschen überlassen, dem du vertraust',
    aEn: 'make every decision in your life yourself',
    bEn: 'leave all big decisions to someone you trust',
  },
  {
    a: 'so bleiben, wie du bist',
    b: 'jemand ganz anderes werden, der glücklicher ist',
    aEn: 'stay exactly who you are',
    bEn: 'become someone completely different who is happier',
  },
  {
    a: 'bereuen, etwas getan zu haben',
    b: 'bereuen, etwas nicht getan zu haben',
    aEn: 'regret something you did',
    bEn: 'regret something you didn’t do',
  },
  {
    a: 'an eine Abzweigung deines Lebens zurückgehen',
    b: 'nur sehen, was aus dem anderen Weg geworden wäre',
    aEn: 'go back to one crossroads in your life',
    bEn: 'only see what the other path would have become',
  },
  {
    a: 'alle Chancen sehen, die du je verpasst hast',
    b: 'nie davon erfahren',
    aEn: 'see every chance you ever missed',
    bEn: 'never find out about them',
  },
  {
    a: 'dein Leben ohne Erinnerung noch einmal von vorne leben',
    b: 'einfach so weiterleben wie bisher',
    aEn: 'live your life again from the start with no memory',
    bEn: 'just keep living the way you are',
  },
  {
    a: 'einen großen Fehler wiedergutmachen',
    b: 'einen großen Erfolg noch einmal erleben',
    aEn: 'make up for one big mistake',
    bEn: 'relive one big success',
  },
  {
    a: 'jemandem endlich sagen, dass du ihn liebst',
    b: 'jemandem endlich sagen, dass er dich verletzt hat',
    aEn: 'finally tell someone you love them',
    bEn: 'finally tell someone they hurt you',
  },
  {
    a: 'einen Brief an dein 16-jähriges Ich schicken',
    b: 'einen Brief von deinem 70-jährigen Ich bekommen',
    aEn: 'send a letter to your 16-year-old self',
    bEn: 'receive a letter from your 70-year-old self',
  },
  {
    a: 'eine sichere Entscheidung treffen, die du später bereust',
    b: 'eine mutige Entscheidung treffen, die schiefgeht',
    aEn: 'make a safe choice you later regret',
    bEn: 'make a bold choice that goes wrong',
  },
  {
    a: 'jeden Tag so leben, als wäre es dein letzter',
    b: 'jeden Tag so leben, als hättest du ewig Zeit',
    aEn: 'live every day as if it were your last',
    bEn: 'live every day as if you had forever',
  },
  {
    a: 'das Studium abbrechen und deinem Traum folgen',
    b: 'fertig studieren und auf Nummer sicher gehen',
    aEn: 'drop out of college to follow your dream',
    bEn: 'finish your degree and play it safe',
  },
  {
    a: 'wissen, ob es ein Leben nach dem Tod gibt',
    b: 'wissen, ob es irgendwo anders im Universum Leben gibt',
    aEn: 'know whether there is life after death',
    bEn: 'know whether there is life elsewhere in the universe',
  },
  {
    a: 'den Sinn des Lebens kennen',
    b: 'ohne ihn zu kennen glücklich sein',
    aEn: 'know the meaning of life',
    bEn: 'be happy without knowing it',
  },
  {
    a: 'an etwas Falsches glauben und Frieden finden',
    b: 'die Wahrheit kennen und daran verzweifeln',
    aEn: 'believe something false and find peace',
    bEn: 'know the truth and despair over it',
  },
  {
    a: 'in einer Welt ohne Musik leben',
    b: 'in einer Welt ohne Bücher und Filme leben',
    aEn: 'live in a world without music',
    bEn: 'live in a world without books and movies',
  },
  {
    a: 'jede Sprache sprechen, aber nie verreisen',
    b: 'überallhin reisen, aber nur deine Sprache sprechen',
    aEn: 'speak every language but never travel',
    bEn: 'travel everywhere but speak only your own language',
  },
  {
    a: 'kurz nach deinem Tod vergessen werden',
    b: 'für immer erinnert werden, aber völlig falsch',
    aEn: 'be forgotten soon after you die',
    bEn: 'be remembered forever, but completely wrong',
  },
  {
    a: 'die ganze Geschichte der Menschheit mit eigenen Augen sehen',
    b: 'die Welt in 1000 Jahren sehen',
    aEn: 'see all of human history with your own eyes',
    bEn: 'see the world 1,000 years from now',
  },
  {
    a: 'ein glückliches Leben ohne tieferen Sinn führen',
    b: 'ein sinnvolles Leben ohne viel Glück führen',
    aEn: 'live a happy life without deeper meaning',
    bEn: 'live a meaningful life without much happiness',
  },
  {
    a: 'einen Tag im Leben jedes Menschen auf der Welt verbringen',
    b: 'ein ganzes Leben im Kopf eines einzigen Menschen verbringen',
    aEn: 'spend one day in the life of every person on Earth',
    bEn: 'spend a whole lifetime inside one single person’s head',
  },
  {
    a: 'in einer Welt leben, in der niemand stirbt',
    b: 'in einer Welt leben, in der niemand leidet',
    aEn: 'live in a world where nobody dies',
    bEn: 'live in a world where nobody suffers',
  },
  {
    a: 'Kinder haben und kaum noch Zeit für dich',
    b: 'keine Kinder haben und alle Freiheit der Welt',
    aEn: 'have kids and barely any time for yourself',
    bEn: 'have no kids and all the freedom in the world',
  },
  {
    a: 'so werden wie deine Mutter',
    b: 'so werden wie dein Vater',
    aEn: 'turn out like your mother',
    bEn: 'turn out like your father',
  },
  {
    a: 'deinen Eltern ein sorgenfreies Alter schenken',
    b: 'deinen Kindern einen sorgenfreien Start ins Leben schenken',
    aEn: 'give your parents a worry-free old age',
    bEn: 'give your kids a worry-free start in life',
  },
  {
    a: 'als Einzelkind aufwachsen',
    b: 'als mittleres von fünf Kindern aufwachsen',
    aEn: 'grow up as an only child',
    bEn: 'grow up as the middle of five kids',
  },
  {
    a: 'in der Nähe deiner Familie wohnen',
    b: 'weit weg in deiner Traumstadt wohnen',
    aEn: 'live close to your family',
    bEn: 'live far away in your dream city',
  },
  {
    a: 'deinen Eltern endlich alles verzeihen',
    b: 'von deinen Eltern hören, dass sie stolz auf dich sind',
    aEn: 'finally forgive your parents for everything',
    bEn: 'hear your parents say they’re proud of you',
  },
  {
    a: 'deine Eltern einen Tag lang in deinem Alter erleben',
    b: 'deine Kinder einen Tag lang als Erwachsene erleben',
    aEn: 'spend a day with your parents at your age',
    bEn: 'spend a day with your kids as adults',
  },
  {
    a: 'Kinder großziehen, die erfolgreich, aber distanziert sind',
    b: 'Kinder, die durchschnittlich, aber eng mit dir verbunden sind',
    aEn: 'raise kids who are successful but distant',
    bEn: 'raise kids who are average but close to you',
  },
  {
    a: 'eine Familie, die offen über alles streitet',
    b: 'eine Familie, die harmonisch ist und vieles ruhen lässt',
    aEn: 'have a family that argues openly about everything',
    bEn: 'have a family that keeps the peace and lets things rest',
  },
  {
    a: 'ein Familiengeheimnis aufdecken',
    b: 'es für immer begraben lassen',
    aEn: 'uncover a family secret',
    bEn: 'let it stay buried forever',
  },
  {
    a: 'einen verlorenen alten Freund zurückgewinnen',
    b: 'einen neuen besten Freund finden',
    aEn: 'win back an old friend you lost',
    bEn: 'find a new best friend',
  },
  {
    a: 'dass deine Freunde ehrlich sagen, was sie von deinem Partner halten',
    b: 'dass sie schweigen und dich einfach unterstützen',
    aEn: 'have your friends say honestly what they think of your partner',
    bEn: 'have them stay quiet and just support you',
  },
  {
    a: 'Freunde haben, die dich herausfordern',
    b: 'Freunde haben, die dich nehmen, wie du bist',
    aEn: 'have friends who challenge you',
    bEn: 'have friends who take you as you are',
  },
  {
    a: 'der Freund sein, der immer hilft',
    b: 'der Freund sein, dem immer geholfen wird',
    aEn: 'be the friend who always helps',
    bEn: 'be the friend who always gets helped',
  },
  {
    a: 'einem Freund Geld leihen und es nie zurückbekommen',
    b: 'Nein sagen und die Freundschaft riskieren',
    aEn: 'lend a friend money and never get it back',
    bEn: 'say no and risk the friendship',
  },
  {
    a: 'einen Abend mit allen Menschen, die dir je wichtig waren',
    b: 'ein Jahr ganz allein in der Natur',
    aEn: 'spend one evening with everyone who ever mattered to you',
    bEn: 'spend a year completely alone in nature',
  },
  {
    a: 'in deiner Gruppe immer der Lustige sein',
    b: 'immer der sein, bei dem sich alle ausweinen',
    aEn: 'always be the funny one in your group',
    bEn: 'always be the one everyone cries to',
  },
  {
    a: 'wissen, welche Freundschaft für immer hält',
    b: 'wissen, welche bald zerbricht',
    aEn: 'know which friendship will last forever',
    bEn: 'know which one will soon fall apart',
  },
  {
    a: 'jetzt sofort eine Million Euro bekommen',
    b: 'für den Rest deines Lebens 4000 Euro im Monat bekommen',
    aEn: 'get a million euros right now',
    bEn: 'get 4,000 euros a month for the rest of your life',
  },
  {
    a: 'reich sein, aber ein einsames Leben führen',
    b: 'knapp bei Kasse sein, aber von Menschen umgeben',
    aEn: 'be rich but live a lonely life',
    bEn: 'be short on money but surrounded by people',
  },
  {
    a: 'ein eigenes Haus in einer langweiligen Stadt',
    b: 'zur Miete in deiner Lieblingsstadt',
    aEn: 'own a house in a boring town',
    bEn: 'rent in your favorite city',
  },
  {
    a: 'alles Geld der Welt, aber keine Zeit',
    b: 'alle Zeit der Welt, aber kein Geld',
    aEn: 'have all the money in the world but no time',
    bEn: 'have all the time in the world but no money',
  },
  {
    a: 'dein Geld nur noch für Erlebnisse ausgeben',
    b: 'dein Geld nur noch für Dinge ausgeben, die bleiben',
    aEn: 'spend your money only on experiences',
    bEn: 'spend your money only on things that last',
  },
  {
    a: 'ein Erbe annehmen, das deine Familie spaltet',
    b: 'darauf verzichten und den Frieden bewahren',
    aEn: 'accept an inheritance that splits your family',
    bEn: 'turn it down and keep the peace',
  },
  {
    a: 'bis 90 körperlich fit, aber vergesslich sein',
    b: 'bis 90 geistig klar, aber körperlich schwach sein',
    aEn: 'be physically fit until 90 but forgetful',
    bEn: 'be mentally sharp until 90 but physically weak',
  },
  {
    a: 'nie wieder Musik hören',
    b: 'nie wieder Farben sehen',
    aEn: 'never hear music again',
    bEn: 'never see colors again',
  },
  {
    a: 'im Alter von deinen Kindern gepflegt werden',
    b: 'im Alter von Fremden professionell gepflegt werden',
    aEn: 'be cared for by your kids when you’re old',
    bEn: 'be cared for professionally by strangers when you’re old',
  },
  {
    a: 'heute erfahren, welche Krankheit du einmal bekommst',
    b: 'es erst erfahren, wenn es so weit ist',
    aEn: 'find out today which illness you’ll get someday',
    bEn: 'only find out when it happens',
  },
  {
    a: 'nie wieder körperlichen Schmerz spüren',
    b: 'nie wieder Liebeskummer haben',
    aEn: 'never feel physical pain again',
    bEn: 'never be heartbroken again',
  },
  {
    a: 'jede Nacht acht Stunden schlafen und weniger schaffen',
    b: 'nur vier Stunden schlafen und viel mehr erleben',
    aEn: 'sleep eight hours every night and get less done',
    bEn: 'sleep only four hours and experience much more',
  },
  {
    a: 'für immer ohne Internet leben',
    b: 'für immer ohne Reisen leben',
    aEn: 'live without the internet forever',
    bEn: 'live without traveling forever',
  },
  {
    a: 'in einem Dorf leben, in dem jeder alles über dich weiß',
    b: 'anonym in einer Großstadt leben, in der dich niemand kennt',
    aEn: 'live in a village where everyone knows everything about you',
    bEn: 'live anonymously in a big city where nobody knows you',
  },
  {
    a: 'dass alle deine privaten Nachrichten öffentlich werden',
    b: 'dass dein kompletter Suchverlauf öffentlich wird',
    aEn: 'have all your private messages go public',
    bEn: 'have your entire search history go public',
  },
  {
    a: 'in einer Welt ohne Social Media leben',
    b: 'in einer Welt, in der alles für immer online bleibt',
    aEn: 'live in a world without social media',
    bEn: 'live in a world where everything stays online forever',
  },
  {
    a: 'eine KI als besten Freund, die dich perfekt versteht',
    b: 'einen Menschen als besten Freund, der dich oft missversteht',
    aEn: 'have an AI best friend who understands you perfectly',
    bEn: 'have a human best friend who often misunderstands you',
  },
  {
    a: 'in die Politik gehen und wirklich etwas verändern',
    b: 'dein Privatleben komplett für dich behalten',
    aEn: 'go into politics and really change something',
    bEn: 'keep your private life completely to yourself',
  },
  {
    a: 'ein Leben mit festen Ritualen führen',
    b: 'ein Leben voller Spontaneität führen',
    aEn: 'live a life of fixed routines',
    bEn: 'live a life full of spontaneity',
  },
  {
    a: 'dass alle Menschen gleich viel verdienen',
    b: 'dass jeder genau das bekommt, was er leistet',
    aEn: 'have everyone earn exactly the same',
    bEn: 'have everyone get exactly what they earn by their effort',
  },
  {
    a: 'im Rampenlicht stehen',
    b: 'hinter den Kulissen die Fäden ziehen',
    aEn: 'stand in the spotlight',
    bEn: 'pull the strings behind the scenes',
  },
  {
    a: 'alles intensiver fühlen, Gutes wie Schlechtes',
    b: 'alles gedämpfter fühlen, aber stabiler sein',
    aEn: 'feel everything more intensely, good and bad',
    bEn: 'feel everything more muted but be steadier',
  },
  {
    a: 'vor anderen nie weinen können',
    b: 'bei jeder Kleinigkeit weinen müssen',
    aEn: 'never be able to cry in front of others',
    bEn: 'have to cry over every little thing',
  },
  {
    a: 'deine Wut sofort rauslassen',
    b: 'sie runterschlucken und später in Ruhe reden',
    aEn: 'let your anger out right away',
    bEn: 'swallow it and talk calmly later',
  },
  {
    a: 'einmal im Leben überwältigend glücklich sein',
    b: 'ein Leben lang leise zufrieden sein',
    aEn: 'be overwhelmingly happy once in your life',
    bEn: 'be quietly content your whole life',
  },
  {
    a: 'Heimweh nach einem Ort haben, den es nicht mehr gibt',
    b: 'Fernweh nach einem Ort haben, den du nie erreichst',
    aEn: 'be homesick for a place that no longer exists',
    bEn: 'long for a faraway place you’ll never reach',
  },
  {
    a: 'dich nie wieder neu verlieben können',
    b: 'dich nie wieder entlieben können',
    aEn: 'never be able to fall in love again',
    bEn: 'never be able to fall out of love again',
  },
  {
    a: 'dich jeden Tag ein bisschen einsam fühlen',
    b: 'dich einmal im Jahr eine Woche lang sehr einsam fühlen',
    aEn: 'feel a little lonely every day',
    bEn: 'feel very lonely for one week every year',
  },
  {
    a: 'die Angst vor dem Scheitern verlieren',
    b: 'die Angst vor dem Urteil anderer verlieren',
    aEn: 'lose your fear of failure',
    bEn: 'lose your fear of other people’s judgment',
  },
  {
    a: 'immer aussprechen müssen, was du denkst',
    b: 'nie wieder deine Meinung sagen dürfen',
    aEn: 'always have to say what you think',
    bEn: 'never be allowed to share your opinion again',
  },
  {
    a: 'deine letzten Worte an einen geliebten Menschen frei wählen',
    b: 'seine letzten Worte an dich hören',
    aEn: 'choose your last words to someone you love',
    bEn: 'hear their last words to you',
  },
  {
    a: 'einen Brief bekommen, den dir jemand nie geschickt hat',
    b: 'einen Brief abschicken, den du nie losgeschickt hast',
    aEn: 'receive a letter someone never sent you',
    bEn: 'send a letter you never sent',
  },
  {
    a: 'zuhören können wie niemand sonst',
    b: 'reden können wie niemand sonst',
    aEn: 'be able to listen like nobody else',
    bEn: 'be able to speak like nobody else',
  },
  {
    a: 'die ganze Welt bereisen, aber allein',
    b: 'nur dein eigenes Land sehen, aber mit deinen Liebsten',
    aEn: 'travel the whole world, but alone',
    bEn: 'only see your own country, but with your loved ones',
  },
  {
    a: 'ein Jahr lang in einem Kloster schweigen',
    b: 'ein Jahr lang ohne Plan durch ein fremdes Land ziehen',
    aEn: 'spend a year in silence at a monastery',
    bEn: 'spend a year wandering a foreign country with no plan',
  },
  {
    a: 'einen Sonnenaufgang auf dem Mount Everest sehen',
    b: 'die Erde einmal aus dem All sehen',
    aEn: 'watch a sunrise from Mount Everest',
    bEn: 'see Earth from space once',
  },
  {
    a: 'einen Tag als dein Vater oder deine Mutter erleben',
    b: 'einen Tag als dein bester Freund erleben',
    aEn: 'live one day as your father or mother',
    bEn: 'live one day as your best friend',
  },
  {
    a: 'jedes Jahr einen perfekten Tag genau wiederholen',
    b: 'jedes Jahr einen ganz neuen Tag erleben, egal wie er wird',
    aEn: 'repeat one perfect day exactly every year',
    bEn: 'live a brand-new day every year, however it turns out',
  },
  {
    a: 'eine Fernbeziehung mit deiner großen Liebe führen',
    b: 'mit jemandem in deiner Nähe zusammen sein, der dich nur halb begeistert',
    aEn: 'be in a long-distance relationship with the love of your life',
    bEn: 'be with someone nearby who only half excites you',
  },
  {
    a: 'dass dein Partner dein bester Freund ist',
    b: 'dass dein Partner dein größtes Abenteuer ist',
    aEn: 'have your partner be your best friend',
    bEn: 'have your partner be your greatest adventure',
  },
  {
    a: 'deinen Partner jeden Tag neu kennenlernen',
    b: 'ihn so gut kennen, dass dich nichts mehr überrascht',
    aEn: 'get to know your partner anew every day',
    bEn: 'know them so well that nothing surprises you anymore',
  },
  {
    a: 'nach einer Trennung befreundet bleiben',
    b: 'nach einer Trennung komplett den Kontakt abbrechen',
    aEn: 'stay friends after a breakup',
    bEn: 'cut off all contact after a breakup',
  },
  {
    a: 'eine große Hochzeit mit 200 Gästen feiern',
    b: 'heimlich nur zu zweit heiraten',
    aEn: 'have a big wedding with 200 guests',
    bEn: 'secretly get married with just the two of you',
  },
  {
    a: 'dein Leben lang in derselben Beziehung bleiben',
    b: 'alle zehn Jahre mit jemand Neuem anfangen',
    aEn: 'stay in the same relationship your whole life',
    bEn: 'start over with someone new every ten years',
  },
  {
    a: 'eine Gabe haben, die nur dir selbst nützt',
    b: 'eine Gabe haben, die nur anderen nützt',
    aEn: 'have a gift that only benefits you',
    bEn: 'have a gift that only benefits others',
  },
  {
    a: 'Zeit mit Menschen vertrödeln, die du liebst',
    b: 'produktive Zeit mit Menschen verbringen, die dir egal sind',
    aEn: 'waste time with people you love',
    bEn: 'spend productive time with people you don’t care about',
  },
  {
    a: 'alle deine Fotos verlieren',
    b: 'alle deine Nachrichten und Briefe verlieren',
    aEn: 'lose all your photos',
    bEn: 'lose all your messages and letters',
  },
  {
    a: 'in einer Zeit leben, in der du gebraucht wirst',
    b: 'in einer Zeit leben, in der du einfach in Ruhe leben kannst',
    aEn: 'live in a time when you’re needed',
    bEn: 'live in a time when you can simply live in peace',
  },
  {
    a: 'dein Leben lang suchen und nie ganz ankommen',
    b: 'früh ankommen und danach nichts Neues mehr suchen',
    aEn: 'search your whole life and never quite arrive',
    bEn: 'arrive early and never search for anything new again',
  },
  {
    a: 'von allen respektiert, aber gefürchtet werden',
    b: 'von allen gemocht, aber nicht ernst genommen werden',
    aEn: 'be respected but feared by everyone',
    bEn: 'be liked but not taken seriously by everyone',
  },
  {
    a: 'nur noch Vertrautes erleben',
    b: 'nur noch Neues erleben',
    aEn: 'only experience familiar things from now on',
    bEn: 'only experience new things from now on',
  },
  { a: 'im Recht sein', b: 'deinen Frieden haben', aEn: 'be right', bEn: 'be at peace' },
  {
    a: 'Menschen sofort durchschauen können',
    b: 'in jedem Menschen immer das Beste sehen',
    aEn: 'be able to see through people instantly',
    bEn: 'always see the best in everyone',
  },
  {
    a: 'die Welt verändern und dafür deine Familie vernachlässigen',
    b: 'ein kleines Leben führen, ganz für deine Familie',
    aEn: 'change the world and neglect your family for it',
    bEn: 'live a small life devoted entirely to your family',
  },
  {
    a: 'dort alt werden, wo du aufgewachsen bist',
    b: 'an einem Ort alt werden, den du selbst gefunden hast',
    aEn: 'grow old where you grew up',
    bEn: 'grow old in a place you found yourself',
  },
  {
    a: 'deinen Kindern vor allem Mut beibringen',
    b: 'deinen Kindern vor allem Freundlichkeit beibringen',
    aEn: 'teach your kids courage above all',
    bEn: 'teach your kids kindness above all',
  },
  {
    a: 'dass die ganze Welt dein Lebenswerk kennt',
    b: 'dass deine Enkel noch deine Geschichte erzählen',
    aEn: 'have the whole world know your life’s work',
    bEn: 'have your grandchildren still tell your story',
  },
  {
    a: 'deinen Traum für deinen Partner aufgeben',
    b: 'deinen Partner seinen Traum für dich aufgeben lassen',
    aEn: 'give up your dream for your partner',
    bEn: 'let your partner give up their dream for you',
  },
  {
    a: 'einen Ort haben, an dem du dich völlig sicher fühlst',
    b: 'einen Menschen haben, bei dem du dich völlig sicher fühlst',
    aEn: 'have a place where you feel completely safe',
    bEn: 'have a person you feel completely safe with',
  },
  {
    a: 'mit 80 auf ein Leben voller Abenteuer zurückblicken',
    b: 'mit 80 auf ein Leben voller tiefer Beziehungen zurückblicken',
    aEn: 'look back at 80 on a life full of adventure',
    bEn: 'look back at 80 on a life full of deep relationships',
  },
  {
    a: 'für immer jung aussehen',
    b: 'dich für immer jung fühlen',
    aEn: 'look young forever',
    bEn: 'feel young forever',
  },
  {
    a: 'dem Universum eine einzige Frage stellen dürfen',
    b: 'eine einzige Sache in deinem Leben garantiert bekommen',
    aEn: 'get to ask the universe one single question',
    bEn: 'be guaranteed one single thing in your life',
  },
];
