import type { WouldYouRatherSeed } from './types';

export const dilemmaQuestions: WouldYouRatherSeed[] = [
  {
    a: 'deinen Traumjob in einer anderen Stadt annehmen',
    b: 'bei deiner Familie bleiben und im ungeliebten Job weitermachen',
    aEn: 'take your dream job in another city',
    bEn: 'stay near your family and keep the job you dislike',
  },
  {
    a: 'der Partnerin deines besten Freundes von seiner Affäre erzählen',
    b: 'schweigen und mit dem Geheimnis leben',
    aEn: 'tell your best friend’s partner about his affair',
    bEn: 'stay silent and live with the secret',
  },
  {
    a: 'zehn Jahre länger leben, aber nie wieder reisen',
    b: 'zehn Jahre früher sterben und die ganze Welt sehen',
    aEn: 'live ten years longer but never travel again',
    bEn: 'die ten years earlier and see the whole world',
  },
  {
    a: 'eine eigene Firma gründen und alles riskieren',
    b: 'im sicheren Job bleiben und dich immer fragen, was gewesen wäre',
    aEn: 'start your own company and risk everything',
    bEn: 'stay in your safe job and always wonder what could have been',
  },
  {
    a: 'alle Erinnerungen an deine Kindheit verlieren',
    b: 'alle Erinnerungen an die letzten fünf Jahre verlieren',
    aEn: 'lose all memories of your childhood',
    bEn: 'lose all memories of the last five years',
  },
  {
    a: 'bei einer Prüfung schummeln, die über deine Zukunft entscheidet',
    b: 'ehrlich bleiben und wahrscheinlich durchfallen',
    aEn: 'cheat on an exam that decides your future',
    bEn: 'stay honest and probably fail',
  },
  {
    a: 'deinem Bruder einen Job verschaffen, für den er nicht geeignet ist',
    b: 'ihm absagen und den Familienfrieden riskieren',
    aEn: 'get your brother a job he isn’t qualified for',
    bEn: 'turn him down and risk peace in the family',
  },
  {
    a: 'mit jemandem zusammen sein, den du liebst, der dich aber weniger liebt',
    b: 'mit jemandem zusammen sein, der dich vergöttert, den du aber nur magst',
    aEn: 'be with someone you love who loves you less',
    bEn: 'be with someone who adores you but whom you only like',
  },
  {
    a: 'einen Fehler gestehen, der einen Kollegen den Job gekostet hat',
    b: 'schweigen und befördert werden',
    aEn: 'confess a mistake that cost a coworker their job',
    bEn: 'stay quiet and get promoted',
  },
  {
    a: 'auf dein Erbe verzichten, um den Familienfrieden zu retten',
    b: 'das Erbe nehmen und mit deinen Geschwistern brechen',
    aEn: 'give up your inheritance to keep the peace in the family',
    bEn: 'take the inheritance and break with your siblings',
  },
  {
    a: 'wissen, dass dein Partner dich betrogen hat',
    b: 'es nie erfahren und glücklich bleiben',
    aEn: 'know your partner cheated on you',
    bEn: 'never find out and stay happy',
  },
  {
    a: 'deine Eltern im Alter selbst pflegen und die Karriere aufgeben',
    b: 'sie in ein Heim geben und weiterarbeiten',
    aEn: 'care for your aging parents yourself and give up your career',
    bEn: 'put them in a care home and keep working',
  },
  {
    a: 'im Lotto gewinnen und es niemandem erzählen dürfen',
    b: 'es allen erzählen und ständig um Geld gebeten werden',
    aEn: 'win the lottery and not be allowed to tell anyone',
    bEn: 'tell everyone and get constantly asked for money',
  },
  {
    a: 'einen Freund verraten, um deine Familie zu schützen',
    b: 'zu deinem Freund halten und deine Familie in Schwierigkeiten bringen',
    aEn: 'betray a friend to protect your family',
    bEn: 'stand by your friend and get your family into trouble',
  },
  {
    a: 'deine Mutter beim Ladendiebstahl erwischen und es melden',
    b: 'wegschauen und es nie ansprechen',
    aEn: 'catch your mom shoplifting and report it',
    bEn: 'look away and never bring it up',
  },
  {
    a: 'fünf Jahre deines Lebens hergeben, damit dein Hund zehn Jahre länger lebt',
    b: 'ihn ganz normal altern lassen',
    aEn: 'give up five years of your life so your dog lives ten years longer',
    bEn: 'let them age normally',
  },
  {
    a: 'berühmt sein und keine Privatsphäre mehr haben',
    b: 'unbekannt bleiben und dein Talent verschwenden',
    aEn: 'be famous and have no privacy left',
    bEn: 'stay unknown and waste your talent',
  },
  {
    a: 'deine Beziehung retten, indem du deinen Traum aufgibst',
    b: 'deinen Traum verfolgen und die Beziehung beenden',
    aEn: 'save your relationship by giving up your dream',
    bEn: 'chase your dream and end the relationship',
  },
  {
    a: 'deine Wohnung verkaufen, um einen Freund aus den Schulden zu holen',
    b: 'Nein sagen und zusehen, wie er alles verliert',
    aEn: 'sell your apartment to get a friend out of debt',
    bEn: 'say no and watch him lose everything',
  },
  {
    a: 'für immer 25 bleiben, während alle um dich herum altern',
    b: 'normal altern und mit 75 sterben',
    aEn: 'stay 25 forever while everyone around you ages',
    bEn: 'age normally and die at 75',
  },
  {
    a: 'als Zeuge aussagen, einen Unschuldigen retten und dich selbst gefährden',
    b: 'schweigen und sicher bleiben',
    aEn: 'testify, save an innocent person and put yourself in danger',
    bEn: 'stay silent and stay safe',
  },
  {
    a: 'deinem besten Freund sagen, dass seine Verlobte dich angebaggert hat',
    b: 'es für dich behalten und sein Trauzeuge sein',
    aEn: 'tell your best friend his fiancée hit on you',
    bEn: 'keep it to yourself and be his best man',
  },
  {
    a: 'an einem Ort mit perfektem Wetter, aber ohne Freunde leben',
    b: 'im grauen Heimatort bei all deinen Freunden bleiben',
    aEn: 'live somewhere with perfect weather but no friends',
    bEn: 'stay in your gray hometown with all your friends',
  },
  {
    a: 'die Hälfte verdienen und deine Arbeit lieben',
    b: 'doppelt so viel verdienen und deinen Job hassen',
    aEn: 'earn half as much and love your work',
    bEn: 'earn twice as much and hate your job',
  },
  {
    a: 'alle deine Fotos und Videos verlieren',
    b: 'alle deine Ersparnisse verlieren',
    aEn: 'lose all your photos and videos',
    bEn: 'lose all your savings',
  },
  {
    a: 'mit deiner großen Liebe leben, aber keine Kinder bekommen können',
    b: 'Kinder haben mit jemandem, den du weniger liebst',
    aEn: 'live with the love of your life but never be able to have kids',
    bEn: 'have kids with someone you love less',
  },
  {
    a: 'ein Geschäft führen, das dich reich macht, aber der Umwelt schadet',
    b: 'ein sauberes Geschäft führen, das kaum etwas abwirft',
    aEn: 'run a business that makes you rich but harms the environment',
    bEn: 'run a clean business that barely makes money',
  },
  {
    a: 'jeden Abend mit deinem Partner streiten, ihn aber tief lieben',
    b: 'nie streiten, euch aber nebeneinander langweilen',
    aEn: 'fight with your partner every night but love them deeply',
    bEn: 'never fight but be bored next to each other',
  },
  {
    a: 'ein Jahr ins Gefängnis gehen und dafür fünf Millionen Euro bekommen',
    b: 'nie mehr als gerade genug zum Leben haben',
    aEn: 'go to prison for a year and get five million euros for it',
    bEn: 'never have more than just enough to get by',
  },
  {
    a: 'erfahren, dass dein Partner dich vor Jahren betrogen hat, und gehen',
    b: 'es verzeihen und es nie ganz vergessen',
    aEn: 'find out your partner cheated years ago and leave',
    bEn: 'forgive it and never quite forget',
  },
  {
    a: 'deine Ersparnisse in die Idee eines Freundes stecken',
    b: 'ablehnen und riskieren, dass er ohne dich reich wird',
    aEn: 'put your savings into a friend’s idea',
    bEn: 'say no and risk him getting rich without you',
  },
  {
    a: 'dein Studium für ein sicheres Jobangebot abbrechen',
    b: 'weiterstudieren und das Angebot verpassen',
    aEn: 'drop out of college for a secure job offer',
    bEn: 'keep studying and miss the offer',
  },
  {
    a: 'öffentlich für deine Überzeugung einstehen und Freunde verlieren',
    b: 'den Mund halten und alle behalten',
    aEn: 'stand up for your beliefs in public and lose friends',
    bEn: 'keep your mouth shut and keep everyone',
  },
  {
    a: 'deinen Eltern sagen, dass du ihren Lebensplan für dich ablehnst',
    b: 'ihren Plan leben und sie glücklich machen',
    aEn: 'tell your parents you reject the life plan they have for you',
    bEn: 'live their plan and make them happy',
  },
  {
    a: 'deine beste Freundin im Bewerbungsverfahren für deinen Traumjob ausstechen',
    b: 'dich zurückziehen und ihr die Stelle lassen',
    aEn: 'beat your best friend for your dream job',
    bEn: 'withdraw and let her have the position',
  },
  {
    a: 'die OP deines Haustiers für 8.000 Euro zahlen und pleite sein',
    b: 'es gehen lassen und finanziell sicher bleiben',
    aEn: 'pay 8,000 euros for your pet’s surgery and be broke',
    bEn: 'let it go and stay financially safe',
  },
  {
    a: 'deinen Freunden ehrlich sagen, was du von ihrem Partner hältst',
    b: 'lächeln und schweigen, obwohl du ihn nicht ausstehen kannst',
    aEn: 'tell your friends honestly what you think of their partner',
    bEn: 'smile and stay quiet even though you can’t stand them',
  },
  {
    a: 'ein Erbe ablehnen, das aus unfairen Geschäften stammt',
    b: 'es annehmen und Gutes damit tun',
    aEn: 'turn down an inheritance that came from shady deals',
    bEn: 'accept it and do good with it',
  },
  {
    a: 'mit 40 in Rente gehen und sehr bescheiden leben',
    b: 'bis 70 arbeiten und dann reich sein',
    aEn: 'retire at 40 and live very modestly',
    bEn: 'work until 70 and be rich then',
  },
  {
    a: 'deine Heimat für immer verlassen und anderswo sicher leben',
    b: 'bleiben, obwohl dort alles immer schwieriger wird',
    aEn: 'leave your home country forever and live safely elsewhere',
    bEn: 'stay even though everything there keeps getting harder',
  },
  {
    a: 'deine Geschwister über die Krankheit deiner Eltern anlügen, wie sie es wollen',
    b: 'ihren Wunsch brechen und es erzählen',
    aEn: 'lie to your siblings about your parents’ illness, as they asked',
    bEn: 'break their wish and tell them',
  },
  {
    a: 'eine großartige Fernbeziehung führen',
    b: 'eine mittelmäßige Beziehung vor Ort führen',
    aEn: 'have a great long-distance relationship',
    bEn: 'have a mediocre relationship close by',
  },
  {
    a: 'deine Traumwohnung bekommen, weil du den Vermieter anlügst',
    b: 'ehrlich sein und weiter suchen',
    aEn: 'get your dream apartment by lying to the landlord',
    bEn: 'be honest and keep looking',
  },
  {
    a: 'jemanden heiraten, den deine Familie nicht ausstehen kann',
    b: 'dich trennen und deine Familie behalten',
    aEn: 'marry someone your family can’t stand',
    bEn: 'break up and keep your family',
  },
  {
    a: 'deinen Ex um Hilfe bitten, um aus einer Notlage zu kommen',
    b: 'stolz bleiben und es allein durchstehen',
    aEn: 'ask your ex for help to get out of a tough spot',
    bEn: 'stay proud and get through it alone',
  },
  {
    a: 'öffentlich machen, dass deine Firma Kunden betrügt, und keinen Job mehr finden',
    b: 'schweigen und gut bezahlt bleiben',
    aEn: 'expose that your company cheats customers and never find work again',
    bEn: 'stay quiet and stay well paid',
  },
  {
    a: 'dein Leben lang nur einen einzigen Freund haben, der immer bleibt',
    b: 'viele Freunde haben, aber keinen wirklich engen',
    aEn: 'have just one friend your whole life who always stays',
    bEn: 'have lots of friends but no truly close one',
  },
  {
    a: 'eine Woche vor der Hochzeit Zweifel bekommen und absagen',
    b: 'trotzdem heiraten und hoffen, dass es gut geht',
    aEn: 'get doubts a week before your wedding and call it off',
    bEn: 'get married anyway and hope it works out',
  },
  {
    a: 'deine Kinder in der Großstadt mit allen Chancen aufziehen',
    b: 'auf dem Land mit Ruhe, aber wenig Möglichkeiten',
    aEn: 'raise your kids in a big city with every opportunity',
    bEn: 'raise them in the countryside with peace but few options',
  },
  {
    a: 'mit deinem Partner ins Ausland ziehen und deinen Job kündigen',
    b: 'bleiben und eine Fernbeziehung riskieren',
    aEn: 'move abroad with your partner and quit your job',
    bEn: 'stay and risk a long-distance relationship',
  },
  {
    a: 'ein Geheimnis kennen, das deine Familie zerstören könnte',
    b: 'es als Einzige nicht kennen, während alle anderen es wissen',
    aEn: 'know a secret that could destroy your family',
    bEn: 'be the only one who doesn’t know while everyone else does',
  },
  {
    a: 'nie wieder ins Ausland reisen dürfen',
    b: 'nie wieder in deine Heimat zurückkehren dürfen',
    aEn: 'never be allowed to travel abroad again',
    bEn: 'never be allowed to return home again',
  },
  {
    a: 'für deinen Bruder bürgen, der schon zweimal pleite war',
    b: 'Nein sagen und euer Verhältnis riskieren',
    aEn: 'co-sign for your brother who has already gone broke twice',
    bEn: 'say no and risk your relationship',
  },
  {
    a: 'nie wieder Geld verdienen müssen, aber nichts mehr erschaffen dürfen',
    b: 'arbeiten bis zum Umfallen, aber etwas Bleibendes schaffen',
    aEn: 'never have to earn money again but never create anything again',
    bEn: 'work until you drop but build something lasting',
  },
  {
    a: 'eine Million Euro bekommen und nie wieder mit deinen Eltern sprechen',
    b: 'arm bleiben und den Kontakt behalten',
    aEn: 'get a million euros and never speak to your parents again',
    bEn: 'stay broke and keep in touch with them',
  },
  {
    a: 'deinem Freund ehrlich sagen, dass sein Start-up scheitern wird',
    b: 'ihn ermutigen und zusehen, wie er sein Erspartes verliert',
    aEn: 'tell your friend honestly that his startup will fail',
    bEn: 'encourage him and watch him lose his savings',
  },
  {
    a: 'deinem Kind Wohlstand bieten, aber kaum zu Hause sein',
    b: 'immer da sein, aber jeden Euro umdrehen müssen',
    aEn: 'give your kid a comfortable life but barely be home',
    bEn: 'always be there but have to count every euro',
  },
  {
    a: 'zugeben, dass dein Fehler die Firma 50.000 Euro gekostet hat',
    b: 'ihn vertuschen und hoffen, dass es keiner merkt',
    aEn: 'admit your mistake cost the company 50,000 euros',
    bEn: 'cover it up and hope nobody notices',
  },
  {
    a: 'eine Liebe erleben, die brennt, aber nur einen Sommer hält',
    b: 'eine ruhige Liebe, die ein Leben lang hält, aber nie brennt',
    aEn: 'have a love that burns bright but only lasts one summer',
    bEn: 'have a quiet love that lasts a lifetime but never burns',
  },
  {
    a: 'deine Lieblingsstadt verlassen, weil die Miete zu teuer wird',
    b: 'bleiben und dein halbes Gehalt für Miete zahlen',
    aEn: 'leave your favorite city because rent gets too expensive',
    bEn: 'stay and spend half your salary on rent',
  },
  {
    a: 'dein Haustier abgeben, weil dein Partner allergisch ist',
    b: 'das Tier behalten und die Beziehung riskieren',
    aEn: 'give up your pet because your partner is allergic',
    bEn: 'keep the pet and risk the relationship',
  },
  {
    a: 'einen Preis annehmen, den eigentlich dein Teamkollege verdient hat',
    b: 'ihn öffentlich ablehnen und deinen Chef blamieren',
    aEn: 'accept an award your teammate actually deserved',
    bEn: 'turn it down publicly and embarrass your boss',
  },
  {
    a: 'die Wahrheit über deine Herkunft erfahren und deine Familie verletzen',
    b: 'nie nachforschen und für immer rätseln',
    aEn: 'learn the truth about your origins and hurt your family',
    bEn: 'never dig and wonder forever',
  },
  {
    a: 'die große Weltreise machen und danach bei null anfangen',
    b: 'das Geld für eine eigene Wohnung sparen',
    aEn: 'take the big trip around the world and start from zero after',
    bEn: 'save the money for a place of your own',
  },
  {
    a: 'einem Freund ein Alibi geben, obwohl du nicht weißt, ob er schuldig ist',
    b: 'die Wahrheit sagen und ihn vielleicht ins Gefängnis bringen',
    aEn: 'give a friend an alibi without knowing if he’s guilty',
    bEn: 'tell the truth and maybe send him to prison',
  },
  {
    a: 'eine Freundschaft beenden, die dir nicht guttut',
    b: 'bleiben, weil ihr so viel zusammen erlebt habt',
    aEn: 'end a friendship that’s bad for you',
    bEn: 'stay because you’ve been through so much together',
  },
  {
    a: 'deinen Eltern ein Haus kaufen und selbst zur Miete wohnen',
    b: 'dir eins kaufen und sie in ihrer kleinen Wohnung lassen',
    aEn: 'buy your parents a house and keep renting yourself',
    bEn: 'buy one for yourself and leave them in their small apartment',
  },
  {
    a: 'zehn Jahre kürzer leben und nie krank sein',
    b: 'lange leben mit chronischen Schmerzen',
    aEn: 'live ten years less and never be sick',
    bEn: 'live a long life with chronic pain',
  },
  {
    a: 'eine Beförderung annehmen und plötzlich deine Freunde im Team führen',
    b: 'ablehnen und einfach Kollege bleiben',
    aEn: 'take a promotion and suddenly manage your friends on the team',
    bEn: 'turn it down and just stay a coworker',
  },
  {
    a: 'deinem Kind von deinem größten Fehler erzählen',
    b: 'ihn für immer verschweigen',
    aEn: 'tell your kid about your biggest mistake',
    bEn: 'keep it secret forever',
  },
  {
    a: 'bei deinem kranken Partner bleiben, obwohl die Liebe weg ist',
    b: 'gehen und mit der Schuld leben',
    aEn: 'stay with your sick partner even though the love is gone',
    bEn: 'leave and live with the guilt',
  },
  {
    a: 'Ruhm für ein Buch kassieren, das ein verstorbener Freund geschrieben hat',
    b: 'es unter seinem Namen veröffentlichen und leer ausgehen',
    aEn: 'take the fame for a book a late friend wrote',
    bEn: 'publish it under his name and get nothing',
  },
  {
    a: 'deine Gefühle für den Partner deines besten Freundes gestehen',
    b: 'sie für immer verschweigen',
    aEn: 'confess your feelings for your best friend’s partner',
    bEn: 'keep them hidden forever',
  },
  {
    a: 'nie wieder lügen können',
    b: 'nie wieder erkennen können, wenn jemand lügt',
    aEn: 'never be able to lie again',
    bEn: 'never be able to tell when someone is lying again',
  },
  {
    a: 'reich in einer Diktatur leben',
    b: 'arm in einer Demokratie leben',
    aEn: 'live rich in a dictatorship',
    bEn: 'live poor in a democracy',
  },
  {
    a: 'einem obdachlosen Freund auf unbestimmte Zeit dein Sofa anbieten',
    b: 'ihn abweisen und dich schuldig fühlen',
    aEn: 'offer a homeless friend your couch indefinitely',
    bEn: 'turn him away and feel guilty',
  },
  {
    a: 'gegen alle Ratschläge kündigen, weil dein Bauch es sagt',
    b: 'auf alle hören und deine innere Stimme ignorieren',
    aEn: 'quit against everyone’s advice because your gut says so',
    bEn: 'listen to everyone and ignore your inner voice',
  },
  {
    a: 'das Auslandsjahr deines Lebens machen und Omas letzten Geburtstag verpassen',
    b: 'zu Hause bleiben und die Chance verpassen',
    aEn: 'do the year abroad of your life and miss grandma’s last birthday',
    bEn: 'stay home and miss the chance',
  },
  {
    a: 'Geld von einem Elternteil annehmen, der dich damit kontrolliert',
    b: 'ablehnen und finanziell kämpfen',
    aEn: 'take money from a parent who uses it to control you',
    bEn: 'refuse and struggle financially',
  },
  {
    a: 'ein perfektes Leben in einer Simulation führen',
    b: 'ein schwieriges Leben in der echten Welt führen',
    aEn: 'live a perfect life in a simulation',
    bEn: 'live a hard life in the real world',
  },
  {
    a: 'deinem besten Freund 10.000 Euro Schulden erlassen',
    b: 'auf das Geld bestehen und die Freundschaft riskieren',
    aEn: 'forgive your best friend a 10,000 euro debt',
    bEn: 'insist on the money and risk the friendship',
  },
  {
    a: 'deinen Partner melden, weil er betrunken Auto gefahren ist',
    b: 'ihn decken und hoffen, dass nichts passiert ist',
    aEn: 'report your partner for driving drunk',
    bEn: 'cover for them and hope nothing happened',
  },
  {
    a: 'deine Firma teuer an einen Konzern verkaufen, der alle entlässt',
    b: 'nicht verkaufen und weiter ums Überleben kämpfen',
    aEn: 'sell your company for a fortune to a corporation that fires everyone',
    bEn: 'not sell and keep fighting to survive',
  },
  {
    a: 'dein Leben einem einzigen Ziel widmen und alles andere opfern',
    b: 'ein ausgeglichenes Leben ohne große Erfolge führen',
    aEn: 'dedicate your life to a single goal and sacrifice everything else',
    bEn: 'live a balanced life without big achievements',
  },
  {
    a: 'zu deinem Partner halten, als ihm alle etwas Schlimmes vorwerfen',
    b: 'auf Abstand gehen, bis die Wahrheit klar ist',
    aEn: 'stand by your partner when everyone accuses them of something awful',
    bEn: 'keep your distance until the truth comes out',
  },
  {
    a: 'deinem Kind den Traumberuf ausreden, weil er brotlos ist',
    b: 'es unterstützen und um seine Zukunft bangen',
    aEn: 'talk your kid out of their dream job because it doesn’t pay',
    bEn: 'support them and fear for their future',
  },
  {
    a: 'die Erinnerung an deine größte Liebe löschen, damit der Schmerz aufhört',
    b: 'sie behalten und weiter leiden',
    aEn: 'erase the memory of your greatest love so the pain stops',
    bEn: 'keep it and keep hurting',
  },
  {
    a: 'öffentlich für einen Fehler deines Chefs geradestehen',
    b: 'die Schuld zurückgeben und deinen Job riskieren',
    aEn: 'publicly take the blame for your boss’s mistake',
    bEn: 'hand the blame back and risk your job',
  },
  {
    a: 'einen gut bezahlten Job bei einem Rüstungskonzern annehmen',
    b: 'arbeitslos bleiben, bis etwas anderes kommt',
    aEn: 'take a well-paid job at an arms manufacturer',
    bEn: 'stay unemployed until something else comes along',
  },
  {
    a: 'dich entschuldigen, obwohl du im Recht bist',
    b: 'im Recht bleiben und die Freundschaft verlieren',
    aEn: 'apologize even though you’re right',
    bEn: 'stay right and lose the friendship',
  },
  {
    a: 'deinen Eltern verzeihen, die dich als Kind vernachlässigt haben',
    b: 'den Kontakt abbrechen und so deinen Frieden finden',
    aEn: 'forgive the parents who neglected you as a child',
    bEn: 'cut contact and find your peace that way',
  },
  {
    a: 'ein Kind bekommen, obwohl du dir unsicher bist',
    b: 'keins bekommen und es vielleicht später bereuen',
    aEn: 'have a child even though you’re unsure',
    bEn: 'not have one and maybe regret it later',
  },
  {
    a: 'deinem Partner Zugriff auf dein Handy geben, weil er es verlangt',
    b: 'die Beziehung deswegen beenden',
    aEn: 'give your partner access to your phone because they demand it',
    bEn: 'end the relationship over it',
  },
  {
    a: 'einen geliebten Menschen ziehen lassen, damit er glücklich wird',
    b: 'ihn festhalten, obwohl er woanders glücklicher wäre',
    aEn: 'let someone you love go so they can be happy',
    bEn: 'hold on even though they’d be happier elsewhere',
  },
  {
    a: 'ein Gerücht über dich stehen lassen, um einen Freund zu schützen',
    b: 'es richtigstellen und den Freund bloßstellen',
    aEn: 'let a rumor about you stand to protect a friend',
    bEn: 'set the record straight and expose your friend',
  },
  {
    a: 'jetzt verzichten und fürs Alter sparen',
    b: 'jetzt leben und im Alter knapp bei Kasse sein',
    aEn: 'go without now and save for old age',
    bEn: 'live it up now and be short on money when you’re old',
  },
  {
    a: 'deinen Job retten, indem du einen Kollegen beim Chef anschwärzt',
    b: 'fair bleiben und selbst gekündigt werden',
    aEn: 'save your job by badmouthing a coworker to the boss',
    bEn: 'play fair and get fired yourself',
  },
  {
    a: 'für viel Geld ein Jahr im Ausland arbeiten, fast ohne Kontakt nach Hause',
    b: 'zu Hause bleiben und die Chance ablehnen',
    aEn: 'work abroad for a year for big money with almost no contact home',
    bEn: 'stay home and turn down the chance',
  },
  {
    a: 'den Fehler eines Arztes melden, der dir sonst sehr geholfen hat',
    b: 'es auf sich beruhen lassen',
    aEn: 'report a mistake by a doctor who has otherwise helped you a lot',
    bEn: 'let it go',
  },
  {
    a: 'ein glückliches Leben führen und nach dem Tod vergessen werden',
    b: 'ein hartes Leben führen und Geschichte schreiben',
    aEn: 'live a happy life and be forgotten after you die',
    bEn: 'live a hard life and make history',
  },
  {
    a: 'deine Schwester vor einem Typen warnen, der dich früher schlecht behandelt hat',
    b: 'nichts sagen, weil sie so glücklich wirkt',
    aEn: 'warn your sister about a guy who treated you badly in the past',
    bEn: 'say nothing because she seems so happy',
  },
  {
    a: 'für viel Geld Werbung für ein Produkt machen, das du schlecht findest',
    b: 'ablehnen und knapp bei Kasse bleiben',
    aEn: 'advertise a product you think is bad for a lot of money',
    bEn: 'turn it down and stay short on cash',
  },
  {
    a: 'unendlich viel Zeit haben, aber kein Geld',
    b: 'unendlich viel Geld haben, aber keine freie Zeit',
    aEn: 'have unlimited time but no money',
    bEn: 'have unlimited money but no free time',
  },
  {
    a: 'einen Wettbewerb gewinnen, weil die Jury sich verrechnet hat',
    b: 'den Fehler melden und verlieren',
    aEn: 'win a contest because the judges miscounted',
    bEn: 'report the mistake and lose',
  },
  {
    a: 'deinem Vater sagen, dass du seinen Betrieb nicht übernehmen willst',
    b: 'ihn übernehmen und deinen eigenen Weg aufgeben',
    aEn: 'tell your dad you don’t want to take over his business',
    bEn: 'take it over and give up your own path',
  },
  {
    a: 'immer gewinnen, aber nie wissen, ob du es verdient hast',
    b: 'oft verlieren, aber jeder Sieg ist echt',
    aEn: 'always win but never know if you deserved it',
    bEn: 'lose often but every win is real',
  },
  {
    a: 'deine Freunde vor einem Fehler warnen und sie verärgern',
    b: 'sie den Fehler machen lassen und hinterher trösten',
    aEn: 'warn your friends about a mistake and annoy them',
    bEn: 'let them make the mistake and comfort them afterward',
  },
  {
    a: 'deinem Bruder eine Niere spenden, obwohl ihr euch kaum versteht',
    b: 'Nein sagen und mit der Entscheidung leben',
    aEn: 'donate a kidney to your brother even though you barely get along',
    bEn: 'say no and live with that decision',
  },
  {
    a: 'eine Familie gründen und deine Karriere auf Eis legen',
    b: 'Karriere machen und die Familie vielleicht zu lange verschieben',
    aEn: 'start a family and put your career on hold',
    bEn: 'build your career and maybe put off a family too long',
  },
  {
    a: 'all deine Freunde verlieren und deinen Seelenverwandten finden',
    b: 'alle Freunde behalten und ihn nie finden',
    aEn: 'lose all your friends and find your soulmate',
    bEn: 'keep all your friends and never find them',
  },
  {
    a: 'deine Eltern finanziell unterstützen und selbst nichts sparen',
    b: 'für dich sparen, während sie knapp leben',
    aEn: 'support your parents financially and save nothing yourself',
    bEn: 'save for yourself while they scrape by',
  },
  {
    a: 'eine gefundene Geldbörse mit 2.000 Euro behalten, während du pleite bist',
    b: 'sie abgeben und weiter kämpfen',
    aEn: 'keep a found wallet with 2,000 euros while you’re broke',
    bEn: 'hand it in and keep struggling',
  },
  {
    a: 'deinem Kind sagen, dass sein Hund gestorben ist',
    b: 'erzählen, er sei auf einen Bauernhof gezogen',
    aEn: 'tell your kid their dog died',
    bEn: 'say it moved to a farm',
  },
  {
    a: 'eine Delle an einem parkenden Auto melden und viel zahlen',
    b: 'wegfahren und nachts nicht schlafen können',
    aEn: 'report a dent you made in a parked car and pay a lot',
    bEn: 'drive away and lose sleep over it',
  },
  {
    a: 'deinem Partner einen großen Geldfehler beichten',
    b: 'ihn heimlich ausbügeln, auch wenn es Jahre dauert',
    aEn: 'confess a big money mistake to your partner',
    bEn: 'fix it in secret even if it takes years',
  },
  {
    a: 'die Firma deiner Familie retten, indem du Leute entlässt',
    b: 'alle behalten und riskieren, dass alles pleitegeht',
    aEn: 'save your family’s company by laying people off',
    bEn: 'keep everyone and risk it all going bankrupt',
  },
  {
    a: 'eine große Chance nur bekommen, weil dein Onkel der Chef ist',
    b: 'sie ablehnen und dich selbst hochkämpfen',
    aEn: 'get a big opportunity only because your uncle is the boss',
    bEn: 'turn it down and work your way up yourself',
  },
  {
    a: 'deine beste Freundin auf ihr Alkoholproblem ansprechen und sie verlieren können',
    b: 'schweigen und zusehen',
    aEn: 'confront your best friend about her drinking problem and risk losing her',
    bEn: 'stay silent and watch',
  },
  {
    a: 'einem Fremden helfen, der dich um Geld bittet und vielleicht lügt',
    b: 'ihn abweisen und vielleicht jemanden in echter Not übergehen',
    aEn: 'help a stranger who asks for money and might be lying',
    bEn: 'turn him away and maybe ignore someone truly in need',
  },
  {
    a: 'deinen größten Erfolg mit jemandem teilen, der wenig beigetragen hat',
    b: 'alles allein einstreichen und die Freundschaft verlieren',
    aEn: 'share your biggest success with someone who contributed little',
    bEn: 'take all the credit and lose the friendship',
  },
  {
    a: 'wegen eures gemeinsamen Kindes in der Beziehung bleiben',
    b: 'gehen und das Kind nur jedes zweite Wochenende sehen',
    aEn: 'stay in the relationship because of your child',
    bEn: 'leave and only see your kid every other weekend',
  },
  {
    a: 'für immer dein Wahlrecht verlieren',
    b: 'nie wieder öffentlich deine Meinung sagen dürfen',
    aEn: 'lose your right to vote forever',
    bEn: 'never be allowed to voice your opinion in public again',
  },
  {
    a: 'deiner Familie weiter jeden Monat Geld schicken, obwohl sie es verschwendet',
    b: 'aufhören und dich wie ein Verräter fühlen',
    aEn: 'keep sending your family money every month even though they waste it',
    bEn: 'stop and feel like a traitor',
  },
  {
    a: 'kündigen, weil dein Chef jemanden unfair behandelt',
    b: 'bleiben und versuchen, es von innen zu ändern',
    aEn: 'quit because your boss treats someone unfairly',
    bEn: 'stay and try to change things from inside',
  },
  {
    a: 'mit 30 alles erreicht haben und dich danach langweilen',
    b: 'erst mit 60 Erfolg haben und bis dahin kämpfen',
    aEn: 'achieve everything by 30 and be bored after that',
    bEn: 'only succeed at 60 and struggle until then',
  },
  {
    a: 'an die Elite-Uni gehen und deine Freunde zurücklassen',
    b: 'bei deinen Freunden bleiben und an die Uni vor Ort gehen',
    aEn: 'go to the elite university and leave your friends behind',
    bEn: 'stay with your friends and go to the local university',
  },
  {
    a: 'deinem Ex helfen, der in Not ist und dich damals verletzt hat',
    b: 'ihn abweisen und dich trotzdem schlecht fühlen',
    aEn: 'help your ex who’s in trouble and once hurt you',
    bEn: 'turn them away and still feel bad',
  },
  {
    a: 'ein Testament finden, das dich enterbt, und es verschwinden lassen',
    b: 'es abgeben und leer ausgehen',
    aEn: 'find a will that disinherits you and make it disappear',
    bEn: 'hand it over and get nothing',
  },
  {
    a: 'eine unheilbare Diagnose bis ins Detail kennen',
    b: 'nichts davon wissen und unbeschwert weiterleben',
    aEn: 'know every detail of an incurable diagnosis',
    bEn: 'know nothing about it and keep living carefree',
  },
  {
    a: 'das Lebenswerk deiner Eltern verkaufen, um Schulden zu tilgen',
    b: 'es behalten und weiter in Schulden versinken',
    aEn: 'sell your parents’ life’s work to pay off debts',
    bEn: 'keep it and sink further into debt',
  },
  {
    a: 'einen Freund vor allen verteidigen, obwohl er im Unrecht ist',
    b: 'ihm vor allen widersprechen',
    aEn: 'defend a friend in front of everyone even though he’s wrong',
    bEn: 'contradict him in front of everyone',
  },
  {
    a: 'deine Kinder auf eine Privatschule schicken und selbst auf alles verzichten',
    b: 'sie auf die normale Schule schicken und entspannt leben',
    aEn: 'send your kids to private school and go without everything yourself',
    bEn: 'send them to regular school and live relaxed',
  },
  {
    a: 'dein Erspartes auf eine riskante Chance setzen, die es verzehnfachen kann',
    b: 'es sicher liegen lassen und langsam schrumpfen sehen',
    aEn: 'bet your savings on a risky chance that could multiply it tenfold',
    bEn: 'leave it safe and watch it slowly shrink',
  },
  {
    a: 'eine Freundin decken, die bei einer Prüfung betrügt',
    b: 'es melden und eure Freundschaft beenden',
    aEn: 'cover for a friend who cheats on an exam',
    bEn: 'report it and end your friendship',
  },
  {
    a: 'die Krankheit eines geliebten Menschen auf dich nehmen',
    b: 'hilflos zusehen, wie er leidet',
    aEn: 'take a loved one’s illness on yourself',
    bEn: 'watch helplessly as they suffer',
  },
  {
    a: 'ein Leben voller Abenteuer ohne festes Zuhause führen',
    b: 'ein sicheres Zuhause ohne Abenteuer haben',
    aEn: 'live a life full of adventure with no fixed home',
    bEn: 'have a safe home with no adventure',
  },
  {
    a: 'deinem Mitbewohner kündigen, obwohl er nirgendwo hin kann',
    b: 'ihn bleiben lassen und selbst weiter leiden',
    aEn: 'kick out your roommate even though he has nowhere to go',
    bEn: 'let him stay and keep suffering yourself',
  },
  {
    a: 'zugeben, dass du das Familienerbstück zerbrochen hast',
    b: 'schweigen, während dein Bruder beschuldigt wird',
    aEn: 'admit you broke the family heirloom',
    bEn: 'stay quiet while your brother gets blamed',
  },
  {
    a: 'deine Kreativität verlieren und dafür reich werden',
    b: 'kreativ bleiben und nie Geld damit verdienen',
    aEn: 'lose your creativity and get rich for it',
    bEn: 'stay creative and never make money from it',
  },
  {
    a: 'deine Wählerstimme für 10.000 Euro verkaufen',
    b: 'ablehnen, obwohl deine Stimme kaum etwas ändert',
    aEn: 'sell your vote for 10,000 euros',
    bEn: 'refuse even though your vote barely changes anything',
  },
  {
    a: 'deine Jugendliebe heiraten und nie jemand anderen kennenlernen',
    b: 'viele Beziehungen haben und nie die eine finden',
    aEn: 'marry your teenage sweetheart and never get to know anyone else',
    bEn: 'have lots of relationships and never find the one',
  },
  {
    a: 'die Lüge deines Partners vor seinen Eltern mittragen',
    b: 'sie auffliegen lassen und einen Familienstreit auslösen',
    aEn: 'go along with your partner’s lie to their parents',
    bEn: 'blow it open and start a family fight',
  },
  {
    a: 'auf deinen Traum verzichten, damit dein Geschwister seinen leben kann',
    b: 'deinen Traum leben und ihm den Weg verbauen',
    aEn: 'give up your dream so your sibling can live theirs',
    bEn: 'live your dream and block their path',
  },
  {
    a: 'deinem Kind erlauben, die Schule für seinen Traum abzubrechen',
    b: 'es zwingen, die Schule durchzuziehen',
    aEn: 'let your kid drop out of school for their dream',
    bEn: 'force them to finish school',
  },
  {
    a: 'viel verdienen bei einem Chef, der dich kleinmacht',
    b: 'wenig verdienen bei einem Chef, der dich fördert',
    aEn: 'earn a lot under a boss who belittles you',
    bEn: 'earn little under a boss who supports you',
  },
  {
    a: 'den letzten Wunsch deines Opas erfüllen, obwohl du ihn falsch findest',
    b: 'ihn ablehnen und dich für immer fragen, ob das richtig war',
    aEn: 'fulfill your grandpa’s last wish even though you think it’s wrong',
    bEn: 'refuse it and always wonder if that was right',
  },
  {
    a: 'eine fremde Familie in Not monatelang bei dir wohnen lassen',
    b: 'Nein sagen und dich egoistisch fühlen',
    aEn: 'let a family in need you don’t know live with you for months',
    bEn: 'say no and feel selfish',
  },
  {
    a: 'deinen Glauben aufgeben, um mit deiner Liebe zusammen zu sein',
    b: 'an deinem Glauben festhalten und sie verlieren',
    aEn: 'give up your faith to be with the one you love',
    bEn: 'hold on to your faith and lose them',
  },
  {
    a: 'einen guten Freund heiraten, mit dem alles leicht ist',
    b: 'auf die große Liebe warten, die vielleicht nie kommt',
    aEn: 'marry a good friend with whom everything is easy',
    bEn: 'wait for the great love that may never come',
  },
  {
    a: 'eine geliebte Familientradition beenden, weil sie jemanden verletzt',
    b: 'sie weiterführen, obwohl du es weißt',
    aEn: 'end a beloved family tradition because it hurts someone',
    bEn: 'keep it going even though you know',
  },
  {
    a: 'erfolgreich werden und deine Freunde aus Neid verlieren',
    b: 'erfolglos bleiben und alle behalten',
    aEn: 'become successful and lose your friends to envy',
    bEn: 'stay unsuccessful and keep them all',
  },
  {
    a: 'als Einziger von einer Kündigungswelle verschont bleiben',
    b: 'zusammen mit allen Kollegen gehen müssen',
    aEn: 'be the only one spared in a wave of layoffs',
    bEn: 'have to leave along with all your coworkers',
  },
  {
    a: 'deinem Kind früh sagen, dass es adoptiert ist',
    b: 'es geheim halten, solange es geht',
    aEn: 'tell your child early that they’re adopted',
    bEn: 'keep it secret as long as you can',
  },
  {
    a: 'den letzten Platz im Evakuierungsflug nehmen und deinen Freund zurücklassen',
    b: 'ihm den Platz geben und selbst bleiben',
    aEn: 'take the last seat on the evacuation flight and leave your friend behind',
    bEn: 'give him the seat and stay yourself',
  },
  {
    a: 'einem Freund, der dich als Referenz angibt, ein ehrliches Zeugnis ausstellen',
    b: 'ihn loben, obwohl er nicht gut ist',
    aEn: 'give an honest reference for a friend who listed you',
    bEn: 'praise him even though he isn’t good',
  },
  {
    a: 'dem Arbeitgeber treu bleiben, der dich in der Krise gerettet hat',
    b: 'für viel mehr Geld zur Konkurrenz wechseln',
    aEn: 'stay loyal to the employer who saved you in a crisis',
    bEn: 'switch to a competitor for much more money',
  },
  {
    a: 'ein Jahr lang kaum Freunde sehen für einen großen Karrieresprung',
    b: 'deine Freunde sehen und beruflich auf der Stelle treten',
    aEn: 'barely see your friends for a year for a big career jump',
    bEn: 'see your friends and stay stuck at work',
  },
  {
    a: 'deinem Gewissen folgen und einen Großauftrag platzen lassen',
    b: 'den Auftrag erfüllen und dein ungutes Gefühl runterschlucken',
    aEn: 'follow your conscience and let a huge contract fall through',
    bEn: 'deliver the contract and swallow your unease',
  },
  {
    a: 'deinen Lebenstraum erst mit 70 erfüllen',
    b: 'ihn mit 25 erfüllen und danach wieder verlieren',
    aEn: 'only fulfill your life’s dream at 70',
    bEn: 'fulfill it at 25 and then lose it again',
  },
  {
    a: 'mit jemandem befreundet bleiben, dessen Ansichten du verachtest',
    b: 'eine lange Freundschaft wegen Politik beenden',
    aEn: 'stay friends with someone whose views you despise',
    bEn: 'end a long friendship over politics',
  },
  {
    a: 'deine Eltern zu dir ziehen lassen',
    b: 'sie allein lassen, obwohl sie einsam sind',
    aEn: 'let your parents move in with you',
    bEn: 'leave them alone even though they’re lonely',
  },
  {
    a: 'eine vernünftige Entscheidung treffen, die dir das Herz bricht',
    b: 'auf dein Herz hören, obwohl der Kopf weiß, dass es falsch ist',
    aEn: 'make a sensible decision that breaks your heart',
    bEn: 'follow your heart even though your head knows it’s wrong',
  },
  {
    a: 'einen Artikel veröffentlichen, der einen Mächtigen stürzt und deine Quelle gefährdet',
    b: 'ihn zurückhalten und die Quelle schützen',
    aEn: 'publish an article that topples someone powerful and endangers your source',
    bEn: 'hold it back and protect the source',
  },
  {
    a: 'eine alleinerziehende Kollegin melden, die im Lager klaut',
    b: 'wegschauen und zur Mitwisserin werden',
    aEn: 'report a single-mom coworker who steals from the stockroom',
    bEn: 'look away and become complicit',
  },
  {
    a: 'Schluss machen, obwohl dein Partner nichts falsch gemacht hat',
    b: 'bleiben, obwohl du nichts mehr fühlst',
    aEn: 'break up even though your partner did nothing wrong',
    bEn: 'stay even though you feel nothing anymore',
  },
  {
    a: 'die Abschlussprüfung schreiben und die Beerdigung deines Opas verpassen',
    b: 'zur Beerdigung gehen und ein Jahr verlieren',
    aEn: 'take your final exam and miss your grandpa’s funeral',
    bEn: 'go to the funeral and lose a year',
  },
  {
    a: 'nie wieder Weihnachten mit deiner Familie feiern',
    b: 'jedes Weihnachten mit deiner zerstrittenen Familie feiern',
    aEn: 'never spend Christmas with your family again',
    bEn: 'spend every Christmas with your feuding family',
  },
  {
    a: 'deinem Kind beibringen, immer ehrlich zu sein, auch wenn es schadet',
    b: 'ihm beibringen, dass kleine Lügen manchmal nötig sind',
    aEn: 'teach your kid to always be honest, even when it hurts them',
    bEn: 'teach them that small lies are sometimes necessary',
  },
  {
    a: 'beim Arzt übertreiben, um schneller behandelt zu werden',
    b: 'ehrlich sein und monatelang warten',
    aEn: 'exaggerate at the doctor’s to get treated sooner',
    bEn: 'be honest and wait for months',
  },
  {
    a: 'deinem Freund einen Job in deiner Firma besorgen, obwohl er nicht gut ist',
    b: 'ablehnen und ihn enttäuschen',
    aEn: 'get your friend a job at your company even though he isn’t good',
    bEn: 'refuse and let him down',
  },
  {
    a: 'den Geburtstag deines Kindes für einen Deal verpassen, der eure Zukunft sichert',
    b: 'den Deal platzen lassen und dabei sein',
    aEn: 'miss your kid’s birthday for a deal that secures your future',
    bEn: 'let the deal fall through and be there',
  },
  {
    a: 'jemanden anzeigen, der dein Fahrrad geklaut hat und es dringend braucht',
    b: 'es gut sein lassen und das Rad abschreiben',
    aEn: 'report someone who stole your bike and badly needs it',
    bEn: 'let it go and write off the bike',
  },
  {
    a: 'für 50.000 Euro in einer Werbung auftreten, die dich lächerlich macht',
    b: 'ablehnen, obwohl du das Geld dringend brauchst',
    aEn: 'appear in an ad that makes you look ridiculous for 50,000 euros',
    bEn: 'turn it down even though you badly need the money',
  },
  {
    a: 'einen Fehler in der Steuererklärung behalten, der euch viel Geld bringt',
    b: 'ihn korrigieren und kräftig nachzahlen',
    aEn: 'keep a mistake on your tax return that gets you a lot of money',
    bEn: 'correct it and pay a lot back',
  },
  {
    a: 'dein Leben lang Single bleiben',
    b: 'in einer unglücklichen Ehe leben',
    aEn: 'stay single your whole life',
    bEn: 'live in an unhappy marriage',
  },
  {
    a: 'das Handy deines Teenagers heimlich kontrollieren',
    b: 'ihm vertrauen und nichts wissen',
    aEn: 'secretly check your teenager’s phone',
    bEn: 'trust them and know nothing',
  },
  {
    a: 'den Ex deines besten Freundes daten',
    b: 'auf jemanden verzichten, der dich wirklich glücklich macht',
    aEn: 'date your best friend’s ex',
    bEn: 'give up someone who truly makes you happy',
  },
  {
    a: 'als Einziger vor einer Gefahr warnen und als Panikmacher gelten',
    b: 'schweigen und hoffen, dass du falschliegst',
    aEn: 'be the only one warning about a danger and be called a fearmonger',
    bEn: 'stay silent and hope you’re wrong',
  },
  {
    a: 'dein ganzes Erspartes einem Fremden in Not geben',
    b: 'es behalten und nie erfahren, was aus ihm wurde',
    aEn: 'give all your savings to a stranger in need',
    bEn: 'keep it and never find out what became of him',
  },
  {
    a: 'einen Job, der die Welt besser macht, aber schlecht bezahlt ist',
    b: 'einen gut bezahlten Job, der niemandem hilft',
    aEn: 'have a job that makes the world better but pays badly',
    bEn: 'have a well-paid job that helps nobody',
  },
  {
    a: 'mit deinem Ersparten das Studium deines Kindes zahlen',
    b: 'damit deine eigene Rente sichern',
    aEn: 'pay for your kid’s college with your savings',
    bEn: 'use them to secure your own retirement',
  },
  {
    a: 'deine Wohnung an einen netten, aber knappen Mieter vermieten',
    b: 'an einen unsympathischen, der deutlich mehr zahlt',
    aEn: 'rent your apartment to a nice tenant who’s short on money',
    bEn: 'rent it to an unpleasant one who pays a lot more',
  },
  {
    a: 'dein Kind einen Fehler machen lassen, den du kommen siehst',
    b: 'eingreifen und es bevormunden',
    aEn: 'let your kid make a mistake you see coming',
    bEn: 'step in and treat them like they can’t decide',
  },
  {
    a: 'den Lottogewinn mit deinen Kollegen teilen, obwohl du allein getippt hast',
    b: 'alles behalten und die Gruppe verlieren',
    aEn: 'share the lottery win with your coworkers even though you played alone',
    bEn: 'keep it all and lose the group',
  },
  {
    a: 'einen ehrlichen Lebenslauf schicken und den Job wohl nicht bekommen',
    b: 'ihn aufhübschen und den Job sicher bekommen',
    aEn: 'send an honest résumé and probably not get the job',
    bEn: 'pad it and definitely get the job',
  },
  {
    a: 'deine Gesundheit für den Job ruinieren und befördert werden',
    b: 'kürzertreten und beruflich stehen bleiben',
    aEn: 'wreck your health for your job and get promoted',
    bEn: 'slow down and stall in your career',
  },
  {
    a: 'im Streit zu deinem Partner halten und deine Mutter verletzen',
    b: 'zu deiner Mutter halten und deinen Partner verletzen',
    aEn: 'side with your partner in a fight and hurt your mom',
    bEn: 'side with your mom and hurt your partner',
  },
  {
    a: 'ein großzügiges Geschenk annehmen von jemandem, der dafür etwas erwartet',
    b: 'es ablehnen und ihn kränken',
    aEn: 'accept a generous gift from someone who expects something in return',
    bEn: 'turn it down and offend them',
  },
  {
    a: 'deinem Partner von deinem geheimen Notgroschen erzählen',
    b: 'ihn weiter verstecken, für alle Fälle',
    aEn: 'tell your partner about your secret emergency fund',
    bEn: 'keep hiding it, just in case',
  },
  {
    a: 'all deine Daten für 100.000 Euro an einen Konzern verkaufen',
    b: 'ablehnen und weiter jeden Cent umdrehen',
    aEn: 'sell all your data to a corporation for 100,000 euros',
    bEn: 'refuse and keep counting every cent',
  },
  {
    a: 'mit deinem heutigen Wissen wieder 18 sein, aber alles Erreichte verlieren',
    b: 'bleiben, wo du bist, mit all deinen Fehlern',
    aEn: 'be 18 again with what you know now but lose everything you’ve achieved',
    bEn: 'stay where you are with all your mistakes',
  },
  {
    a: 'deine Leidenschaft zum Beruf machen und sie vielleicht hassen lernen',
    b: 'sie als Hobby behalten und einen Job machen, der dich langweilt',
    aEn: 'turn your passion into your job and maybe learn to hate it',
    bEn: 'keep it as a hobby and do a job that bores you',
  },
  {
    a: 'mit deiner Familie brechen, um du selbst zu sein',
    b: 'dich verstellen, um dazuzugehören',
    aEn: 'break with your family to be yourself',
    bEn: 'pretend to be someone else to belong',
  },
  {
    a: 'eine Regel brechen, um jemandem zu helfen, und deinen Job verlieren',
    b: 'die Regel befolgen und dich ewig fragen, ob du hättest helfen können',
    aEn: 'break a rule to help someone and lose your job',
    bEn: 'follow the rule and forever wonder if you could have helped',
  },
  {
    a: 'einem Freund in der Krise Tag und Nacht zur Verfügung stehen',
    b: 'auf dich selbst achten und Grenzen setzen',
    aEn: 'be there for a friend in crisis day and night',
    bEn: 'look after yourself and set boundaries',
  },
  {
    a: 'einen Kredit für die Traumhochzeit aufnehmen',
    b: 'klein heiraten und die Familie enttäuschen',
    aEn: 'take out a loan for your dream wedding',
    bEn: 'have a small wedding and disappoint the family',
  },
  {
    a: 'deinen besten Freund als Geschäftspartner nehmen',
    b: 'einen Fremden nehmen, der fachlich besser passt',
    aEn: 'take your best friend as a business partner',
    bEn: 'pick a stranger who’s a better professional fit',
  },
  {
    a: 'ein Leben ohne Schmerz, aber auch ohne tiefe Freude',
    b: 'ein Leben, in dem du beides mit voller Wucht spürst',
    aEn: 'have a life without pain but also without deep joy',
    bEn: 'have a life where you feel both at full force',
  },
  {
    a: 'jemandem eine zweite Chance geben, der dich bestohlen hat',
    b: 'ihn abschreiben, obwohl er sich ändern will',
    aEn: 'give a second chance to someone who stole from you',
    bEn: 'write them off even though they want to change',
  },
  {
    a: 'dein hochbegabtes Kind auf ein Internat weit weg schicken',
    b: 'es zu Hause behalten und unterfordert sehen',
    aEn: 'send your gifted child to a boarding school far away',
    bEn: 'keep them at home and watch them be underchallenged',
  },
];
