import type { WouldYouRatherSeed } from './types';

export const funnyQuestions: WouldYouRatherSeed[] = [
  {
    a: 'bei jedem Räuspern laut muhen',
    b: 'bei jedem Gähnen wie ein Wolf heulen',
    aEn: 'moo loudly every time you clear your throat',
    bEn: 'howl like a wolf every time you yawn',
  },
  {
    a: 'für immer nur rückwärts gehen können',
    b: 'für immer nur seitwärts wie eine Krabbe laufen können',
    aEn: 'only ever be able to walk backwards',
    bEn: 'only ever be able to scuttle sideways like a crab',
  },
  {
    a: 'Finger aus Fischstäbchen haben',
    b: 'Zehen aus Gummibärchen haben',
    aEn: 'have fish sticks for fingers',
    bEn: 'have gummy bears for toes',
  },
  {
    a: 'jedes Mal laut pupsen, wenn du lügst',
    b: 'jedes Mal rülpsen, wenn du die Wahrheit sagst',
    aEn: 'fart loudly every time you lie',
    bEn: 'burp every time you tell the truth',
  },
  {
    a: 'einen Bauch haben, der bei Stille Opernarien singt',
    b: 'Knie haben, die bei jedem Schritt laut knacken',
    aEn: 'have a stomach that sings opera arias whenever it’s quiet',
    bEn: 'have knees that crack loudly with every step',
  },
  {
    a: 'auf jeder Beerdigung einen Lachanfall bekommen',
    b: 'bei jedem Heiratsantrag in der Nähe laut „Nein!“ rufen',
    aEn: 'get a laughing fit at every funeral',
    bEn: 'shout “No!” at every marriage proposal nearby',
  },
  {
    a: 'für immer eine Heliumstimme haben',
    b: 'für immer wie ein Seehund lachen',
    aEn: 'have a helium voice forever',
    bEn: 'laugh like a seal forever',
  },
  {
    a: 'immer leicht nach Zwiebeln riechen',
    b: 'immer leicht nach nassem Hund riechen',
    aEn: 'always smell faintly of onions',
    bEn: 'always smell faintly of wet dog',
  },
  {
    a: 'statt zu klatschen immer laut „Bravo, Kartoffel!“ rufen',
    b: 'statt zu winken immer einen Knicks machen',
    aEn: 'shout “Bravo, potato!” instead of clapping',
    bEn: 'curtsy instead of waving',
  },
  {
    a: 'dein eigenes Schreien für immer als Klingelton haben',
    b: 'deine Mutter, die deinen Namen ruft, für immer als Wecker haben',
    aEn: 'have your own scream as your ringtone forever',
    bEn: 'have your mom calling your name as your alarm forever',
  },
  {
    a: 'jeden Morgen mit einer zufälligen Frisur aufwachen',
    b: 'jeden Morgen in einem zufälligen Outfit aufwachen',
    aEn: 'wake up every morning with a random hairstyle',
    bEn: 'wake up every morning in a random outfit',
  },
  {
    a: 'deinem Chef aus Versehen ein Kussmund-Selfie schicken',
    b: 'deinen Ex aus Versehen in den Familienchat einladen',
    aEn: 'accidentally send your boss a kissy-face selfie',
    bEn: 'accidentally add your ex to the family group chat',
  },
  {
    a: 'beim Essen immer laut schmatzen müssen',
    b: 'beim Trinken immer laut gurgeln müssen',
    aEn: 'have to smack your lips loudly while eating',
    bEn: 'have to gurgle loudly while drinking',
  },
  {
    a: 'nur noch in Reimen sprechen können',
    b: 'nur noch singend sprechen können',
    aEn: 'only be able to speak in rhymes',
    bEn: 'only be able to speak by singing',
  },
  {
    a: 'ein Leben lang Socken in Sandalen tragen',
    b: 'ein Leben lang im Schlafanzug zur Arbeit gehen',
    aEn: 'wear socks with sandals for life',
    bEn: 'go to work in pajamas for life',
  },
  {
    a: 'einen Schnurrbart haben, der nie aufhört zu wachsen',
    b: 'Augenbrauen haben, die nie aufhören zu wachsen',
    aEn: 'have a mustache that never stops growing',
    bEn: 'have eyebrows that never stop growing',
  },
  {
    a: 'dass jeder deine Gedanken als Untertitel sieht',
    b: 'dass ein Sportkommentator dein Leben live kommentiert',
    aEn: 'have everyone see your thoughts as subtitles',
    bEn: 'have a sports commentator narrate your life live',
  },
  {
    a: 'dass beim Betreten jedes Raums eine Fanfare ertönt',
    b: 'dass beim Verlassen jedes Raums eine traurige Posaune erklingt',
    aEn: 'have a fanfare play whenever you enter a room',
    bEn: 'have a sad trombone play whenever you leave a room',
  },
  {
    a: 'jedes Getränk aus einem Gummistiefel trinken',
    b: 'jede Mahlzeit mit einem Schuhlöffel essen',
    aEn: 'drink every drink out of a rubber boot',
    bEn: 'eat every meal with a shoehorn',
  },
  {
    a: 'Hände so groß wie Bratpfannen haben',
    b: 'Füße so klein wie die einer Barbie haben',
    aEn: 'have hands as big as frying pans',
    bEn: 'have feet as tiny as a Barbie’s',
  },
  {
    a: 'Ohren haben, die rot leuchten, wenn du lügst',
    b: 'eine Nase haben, die pfeift, wenn du nervös bist',
    aEn: 'have ears that glow red when you lie',
    bEn: 'have a nose that whistles when you’re nervous',
  },
  {
    a: 'auf jedem ersten Date dein Getränk umkippen',
    b: 'auf jedem ersten Date den Namen deines Dates vergessen',
    aEn: 'knock over your drink on every first date',
    bEn: 'forget your date’s name on every first date',
  },
  {
    a: 'jeden Tag von einer wütenden Gans verfolgt werden',
    b: 'jeden Tag einmal von einem Lama angespuckt werden',
    aEn: 'be chased by an angry goose every day',
    bEn: 'get spat on by a llama once a day',
  },
  {
    a: 'nur noch mit Fäustlingen tippen können',
    b: 'nur noch mit der Nase tippen können',
    aEn: 'only be able to type wearing mittens',
    bEn: 'only be able to type with your nose',
  },
  {
    a: 'immer laut aussprechen, was du gerade googelst',
    b: 'dass dein Suchverlauf jeden Montag an deine Familie geht',
    aEn: 'always say out loud what you’re googling',
    bEn: 'have your search history sent to your family every Monday',
  },
  {
    a: 'in jedem Restaurant deine Bestellung rappen müssen',
    b: 'in jedem Restaurant dem Koch persönlich applaudieren müssen',
    aEn: 'have to rap your order in every restaurant',
    bEn: 'have to personally applaud the chef in every restaurant',
  },
  {
    a: 'jedes Mal stolpern, wenn dich jemand ansieht',
    b: 'jedes Mal winken, wenn dich jemand ansieht',
    aEn: 'trip every time someone looks at you',
    bEn: 'wave every time someone looks at you',
  },
  {
    a: 'einen Schwanz haben, der wedelt, wenn du dich freust',
    b: 'Ohren haben, die sich anlegen, wenn du sauer bist',
    aEn: 'have a tail that wags when you’re happy',
    bEn: 'have ears that flatten when you’re angry',
  },
  {
    a: 'jeden Satz mit „Wie schon die alten Ägypter sagten“ beginnen',
    b: 'jeden Satz mit „und das ist auch gut so“ beenden',
    aEn: 'start every sentence with “As the ancient Egyptians used to say”',
    bEn: 'end every sentence with “and that’s a good thing”',
  },
  {
    a: 'nur noch mit Schwimmflügeln ins Wasser dürfen',
    b: 'nur noch mit Fahrradhelm Auto fahren dürfen',
    aEn: 'only be allowed in the water wearing armbands',
    bEn: 'only be allowed to drive wearing a bike helmet',
  },
  {
    a: 'dass dein Gesicht auf allen Geldscheinen ist, aber mit Doppelkinn',
    b: 'dass deine Stimme jede Durchsage am Bahnhof spricht',
    aEn: 'have your face on every banknote, but with a double chin',
    bEn: 'have your voice make every announcement at the train station',
  },
  {
    a: 'jede Nacht im Schlaf laut deine Passwörter sagen',
    b: 'jede Nacht im Schlaf durch die Wohnung tanzen',
    aEn: 'say your passwords out loud in your sleep every night',
    bEn: 'dance around your apartment in your sleep every night',
  },
  {
    a: 'nur noch Kleidung in Neongelb tragen',
    b: 'nur noch Kleidung mit deinem eigenen Gesicht drauf tragen',
    aEn: 'only wear neon yellow clothes',
    bEn: 'only wear clothes printed with your own face',
  },
  {
    a: 'einen Tag lang die Katze deines Nachbarn sein',
    b: 'einen Tag lang das Handy deines besten Freundes sein',
    aEn: 'be your neighbor’s cat for a day',
    bEn: 'be your best friend’s phone for a day',
  },
  {
    a: 'beim Lachen grunzen wie ein Schwein',
    b: 'beim Weinen heulen wie eine Sirene',
    aEn: 'snort like a pig when you laugh',
    bEn: 'wail like a siren when you cry',
  },
  {
    a: 'immer Spinat zwischen den Zähnen haben',
    b: 'immer einen Streifen Klopapier am Schuh hinter dir herziehen',
    aEn: 'always have spinach between your teeth',
    bEn: 'always drag a strip of toilet paper stuck to your shoe',
  },
  {
    a: 'deine Eltern als Mitbewohner haben',
    b: 'deine Grundschullehrerin als Mitbewohnerin haben',
    aEn: 'have your parents as roommates',
    bEn: 'have your primary school teacher as a roommate',
  },
  {
    a: 'jeden Abend ein Gute-Nacht-Lied von deinem Chef bekommen',
    b: 'jeden Morgen einen Weckanruf von deinem Ex bekommen',
    aEn: 'get a lullaby from your boss every night',
    bEn: 'get a wake-up call from your ex every morning',
  },
  {
    a: 'auf jedem Foto die Augen geschlossen haben',
    b: 'auf jedem Foto unscharf sein',
    aEn: 'have your eyes closed in every photo',
    bEn: 'be blurry in every photo',
  },
  {
    a: 'immer viel zu nah an Leuten stehen',
    b: 'immer viel zu fest die Hand drücken',
    aEn: 'always stand way too close to people',
    bEn: 'always shake hands way too firmly',
  },
  {
    a: 'eine Woche lang in einer Hüpfburg wohnen',
    b: 'eine Woche lang in einem Bällebad wohnen',
    aEn: 'live in a bouncy castle for a week',
    bEn: 'live in a ball pit for a week',
  },
  {
    a: 'nur noch mit Piratenakzent sprechen',
    b: 'nur noch in der dritten Person über dich reden',
    aEn: 'only speak in a pirate accent',
    bEn: 'only talk about yourself in the third person',
  },
  {
    a: 'jedes Mal einen Purzelbaum machen, wenn du aufstehst',
    b: 'jedes Mal ein Furzkissen-Geräusch machen, wenn du dich setzt',
    aEn: 'do a somersault every time you stand up',
    bEn: 'make a whoopee cushion sound every time you sit down',
  },
  {
    a: 'bei jedem Handschlag einen Stromschlag verteilen',
    b: 'bei jeder Umarmung laut quietschen wie ein Gummitier',
    aEn: 'give an electric shock with every handshake',
    bEn: 'squeak loudly like a rubber toy with every hug',
  },
  {
    a: 'offiziell „Pupsi“ heißen',
    b: 'offiziell „Hoheit“ heißen, auch in jedem Brief vom Amt',
    aEn: 'officially be named “Fartsy”',
    bEn: 'officially be called “Your Highness”, even in every letter from the authorities',
  },
  {
    a: 'jedes Gespräch mit einer Verbeugung beenden',
    b: 'jedes Gespräch mit einem High five beginnen',
    aEn: 'end every conversation with a bow',
    bEn: 'start every conversation with a high five',
  },
  {
    a: 'für immer Glitzer im Gesicht haben, der nicht abgeht',
    b: 'für immer einen Fleck auf dem Shirt haben, egal welches',
    aEn: 'always have glitter on your face that won’t come off',
    bEn: 'always have a stain on your shirt, no matter which one',
  },
  {
    a: 'bei jedem Witz, den du nicht verstehst, laut lachen müssen',
    b: 'bei jedem Witz, den du verstehst, ernst bleiben müssen',
    aEn: 'have to laugh loudly at every joke you don’t get',
    bEn: 'have to keep a straight face at every joke you do get',
  },
  {
    a: 'einen Hamster so groß wie ein Pferd als Haustier haben',
    b: 'ein Pferd so klein wie ein Hamster als Haustier haben',
    aEn: 'have a hamster the size of a horse as a pet',
    bEn: 'have a horse the size of a hamster as a pet',
  },
  {
    a: 'dein Tagebuch beim Familienessen laut vorlesen',
    b: 'deine alten Chats auf einer Leinwand zeigen lassen',
    aEn: 'read your diary aloud at a family dinner',
    bEn: 'have your old chats shown on a big screen',
  },
  {
    a: 'dass jede Tür, die du öffnest, laut knarrt',
    b: 'dass jeder Stuhl, auf dem du sitzt, wackelt',
    aEn: 'have every door you open creak loudly',
    bEn: 'have every chair you sit on wobble',
  },
  {
    a: 'am Ende jedes Telefonats aus Versehen „Hab dich lieb“ sagen',
    b: 'bei jedem Abschied aus Versehen salutieren',
    aEn: 'accidentally say “love you” at the end of every phone call',
    bEn: 'accidentally salute every time you say goodbye',
  },
  {
    a: 'nur noch vom Kinderteller bestellen dürfen',
    b: 'nur noch vom Seniorenteller bestellen dürfen',
    aEn: 'only be allowed to order from the kids’ menu',
    bEn: 'only be allowed to order from the seniors’ menu',
  },
  {
    a: 'dass dein Spiegelbild immer eine Sekunde hinterherhinkt',
    b: 'dass dein Schatten manchmal etwas anderes macht als du',
    aEn: 'have your reflection always lag one second behind',
    bEn: 'have your shadow sometimes do something different than you',
  },
  {
    a: 'mit einem Fremden im Aufzug stecken bleiben, der Blockflöte spielt',
    b: 'mit deinem Chef im Aufzug stecken bleiben, der Karaoke singen will',
    aEn: 'get stuck in an elevator with a stranger playing the recorder',
    bEn: 'get stuck in an elevator with your boss who wants to do karaoke',
  },
  {
    a: 'dass dein Magen in jedem Meeting laut knurrt',
    b: 'dass dein Stuhl in jedem Meeting Furzgeräusche macht',
    aEn: 'have your stomach growl loudly in every meeting',
    bEn: 'have your chair make fart noises in every meeting',
  },
  {
    a: 'statt zu gehen für immer hüpfen',
    b: 'statt zu rennen für immer galoppieren',
    aEn: 'hop everywhere instead of walking, forever',
    bEn: 'gallop instead of running, forever',
  },
  {
    a: 'einmal pro Woche in der Öffentlichkeit einschlafen, egal wo',
    b: 'einmal pro Woche in der Öffentlichkeit spontan anfangen zu tanzen',
    aEn: 'fall asleep in public once a week, no matter where',
    bEn: 'spontaneously start dancing in public once a week',
  },
  {
    a: 'ein Tattoo von deinem Lieblingsgemüse auf der Stirn haben',
    b: 'den Namen deines Zahnarztes auf den Unterarm tätowiert haben',
    aEn: 'have a tattoo of your favorite vegetable on your forehead',
    bEn: 'have your dentist’s name tattooed on your forearm',
  },
  {
    a: 'einen Tag lang ein Goldfisch sein',
    b: 'einen Tag lang ein Saugroboter sein',
    aEn: 'be a goldfish for a day',
    bEn: 'be a robot vacuum for a day',
  },
  {
    a: 'in einer Welt leben, in der alle pfeifen statt sprechen',
    b: 'in einer Welt leben, in der sich alle nur pantomimisch verständigen',
    aEn: 'live in a world where everyone whistles instead of talking',
    bEn: 'live in a world where everyone only communicates in mime',
  },
  {
    a: 'auf jeder Party immer der DJ sein müssen',
    b: 'auf jeder Party immer die Garderobe bewachen müssen',
    aEn: 'always have to be the DJ at every party',
    bEn: 'always have to guard the coats at every party',
  },
  {
    a: 'nie wieder Schnürsenkel binden können',
    b: 'nie wieder einen Reißverschluss zubekommen',
    aEn: 'never be able to tie shoelaces again',
    bEn: 'never be able to close a zipper again',
  },
  {
    a: 'immer klebrige Hände haben',
    b: 'immer feuchte Socken anhaben',
    aEn: 'always have sticky hands',
    bEn: 'always be wearing damp socks',
  },
  {
    a: 'im Vorstellungsgespräch laut rülpsen',
    b: 'im Vorstellungsgespräch die Personalerin aus Versehen „Mama“ nennen',
    aEn: 'burp loudly in a job interview',
    bEn: 'accidentally call the interviewer “Mom” in a job interview',
  },
  {
    a: 'jeden Song im Radio mitsingen müssen, auch ohne den Text zu kennen',
    b: 'zu jedem Song im Radio tanzen müssen, egal wo du bist',
    aEn: 'have to sing along to every song on the radio, even without knowing the words',
    bEn: 'have to dance to every song on the radio, wherever you are',
  },
  {
    a: 'einen Pinguin als Mitbewohner haben, der nie putzt',
    b: 'einen Papagei haben, der all deine Geheimnisse ausplaudert',
    aEn: 'have a penguin roommate who never cleans',
    bEn: 'have a parrot that blabs all your secrets',
  },
  {
    a: 'dass dein Lieblingsessen für immer nach Zahnpasta schmeckt',
    b: 'dass jedes Getränk für immer leicht nach Gurke schmeckt',
    aEn: 'have your favorite food taste like toothpaste forever',
    bEn: 'have every drink taste slightly of cucumber forever',
  },
  {
    a: 'bei jedem Lachen Seifenblasen aus der Nase pusten',
    b: 'Konfetti statt Tränen weinen',
    aEn: 'blow soap bubbles out of your nose every time you laugh',
    bEn: 'cry confetti instead of tears',
  },
  {
    a: 'für immer die Frisur von deinem Grundschulfoto tragen',
    b: 'für immer die Brille deines Opas tragen',
    aEn: 'keep the haircut from your primary school photo forever',
    bEn: 'wear your grandpa’s glasses forever',
  },
  {
    a: 'jede Frage mit einer Gegenfrage beantworten müssen',
    b: 'jede Frage mit einem Sprichwort beantworten müssen',
    aEn: 'have to answer every question with a question',
    bEn: 'have to answer every question with a proverb',
  },
  {
    a: 'statt rot zu werden immer knallgrün anlaufen',
    b: 'bei Nervosität sichtbar Dampf aus den Ohren lassen',
    aEn: 'turn bright green instead of blushing',
    bEn: 'visibly steam from your ears when you’re nervous',
  },
  {
    a: 'nur noch Schuhe tragen, die bei jedem Schritt blinken',
    b: 'nur noch Schuhe tragen, die bei jedem Schritt quietschen',
    aEn: 'only wear shoes that light up with every step',
    bEn: 'only wear shoes that squeak with every step',
  },
  {
    a: 'einen Monat lang nur flüstern dürfen',
    b: 'einen Monat lang nur schreien dürfen',
    aEn: 'only be allowed to whisper for a month',
    bEn: 'only be allowed to shout for a month',
  },
  {
    a: 'auf dem Abiball vor allen der Länge nach hinfallen',
    b: 'auf dem Abiball den ganzen Abend mit offenem Hosenstall tanzen',
    aEn: 'fall flat on your face in front of everyone at your graduation ball',
    bEn: 'dance all night with your fly open at your graduation ball',
  },
  {
    a: 'dass deine Oma ein viraler Rap-Star wird',
    b: 'dass dein Opa ein Influencer für Bauchtanz wird',
    aEn: 'have your grandma become a viral rap star',
    bEn: 'have your grandpa become a belly dance influencer',
  },
  {
    a: 'immer eine Schwimmbrille tragen müssen',
    b: 'immer einen Bauarbeiterhelm tragen müssen',
    aEn: 'always have to wear swimming goggles',
    bEn: 'always have to wear a hard hat',
  },
  {
    a: 'jedes Mal aufstehen müssen, wenn jemand deinen Namen sagt',
    b: 'jedes Mal einen Tanzschritt machen müssen, wenn jemand „Hallo“ sagt',
    aEn: 'have to stand up whenever someone says your name',
    bEn: 'have to do a dance move whenever someone says “hello”',
  },
  {
    a: 'eine Woche lang als Weihnachtsbaum verkleidet herumlaufen',
    b: 'eine Woche lang als Hotdog verkleidet herumlaufen',
    aEn: 'walk around dressed as a Christmas tree for a week',
    bEn: 'walk around dressed as a hot dog for a week',
  },
  {
    a: 'Pupse haben, die nach Rosen riechen, aber wie eine Tuba klingen',
    b: 'lautlose Pupse haben, die grün leuchten',
    aEn: 'have farts that smell like roses but sound like a tuba',
    bEn: 'have silent farts that glow green',
  },
  {
    a: 'auf deinem Ausweisfoto Hasenohren tragen',
    b: 'auf deinem Führerscheinfoto schielen',
    aEn: 'wear bunny ears in your ID photo',
    bEn: 'be cross-eyed in your driver’s license photo',
  },
  {
    a: 'eine Katze haben, die jeden Morgen deinen Namen schreit',
    b: 'einen Hund haben, der bei jedem Besuch deine Unterwäsche anschleppt',
    aEn: 'have a cat that screams your name every morning',
    bEn: 'have a dog that drags out your underwear whenever guests come over',
  },
  {
    a: 'nur noch kalte Pizza essen dürfen',
    b: 'nur noch lauwarmes Eis essen dürfen',
    aEn: 'only be allowed to eat cold pizza',
    bEn: 'only be allowed to eat lukewarm ice cream',
  },
  {
    a: 'jeden vorbeifahrenden Bus laut grüßen müssen',
    b: 'bei jedem Auto, das du siehst, laut die Marke rufen müssen',
    aEn: 'have to greet every passing bus out loud',
    bEn: 'have to shout the brand of every car you see',
  },
  {
    a: 'in Zeitlupe laufen, wenn du es eilig hast',
    b: 'im Zeitraffer reden, wenn du nervös bist',
    aEn: 'move in slow motion whenever you’re in a hurry',
    bEn: 'talk in fast-forward whenever you’re nervous',
  },
  {
    a: 'nur noch mit einem Einrad zur Arbeit fahren',
    b: 'nur noch mit einem Bobbycar zur Arbeit fahren',
    aEn: 'only commute to work on a unicycle',
    bEn: 'only commute to work on a toddler’s ride-on car',
  },
  {
    a: 'dass deine Nachbarn jeden deiner Duschgesänge hören',
    b: 'dass deine Kollegen jedes deiner Selbstgespräche hören',
    aEn: 'have your neighbors hear every song you sing in the shower',
    bEn: 'have your coworkers hear every time you talk to yourself',
  },
  {
    a: 'nach jeder Mahlzeit eine Dankesrede halten',
    b: 'vor jeder Mahlzeit ein Gedicht über das Essen aufsagen',
    aEn: 'give a thank-you speech after every meal',
    bEn: 'recite a poem about your food before every meal',
  },
  {
    a: 'statt Handy ein Telefon mit Kabel überall mitschleppen',
    b: 'Nachrichten nur noch per Brieftaube verschicken',
    aEn: 'drag a corded phone everywhere instead of a cell phone',
    bEn: 'only send messages by carrier pigeon',
  },
  {
    a: 'eine Nacht heimlich im Möbelhaus übernachten',
    b: 'eine Nacht heimlich im Spaßbad übernachten',
    aEn: 'secretly spend a night in a furniture store',
    bEn: 'secretly spend a night in a water park',
  },
  {
    a: 'im Partnerlook mit deinem Chef zur Arbeit kommen',
    b: 'im Partnerlook mit deiner Mutter auf eine Party gehen',
    aEn: 'show up to work in a matching outfit with your boss',
    bEn: 'go to a party in a matching outfit with your mom',
  },
  {
    a: 'beim Sport immer stöhnen wie ein Tennisprofi',
    b: 'beim Sport dich selbst laut anfeuern müssen',
    aEn: 'always grunt like a tennis pro when you exercise',
    bEn: 'have to cheer yourself on loudly when you exercise',
  },
  {
    a: 'ein Bett haben, das jeden Morgen laut dein Gewicht ansagt',
    b: 'einen Kühlschrank haben, der alles kommentiert, was du rausnimmst',
    aEn: 'have a bed that announces your weight every morning',
    bEn: 'have a fridge that comments on everything you take out',
  },
  {
    a: 'dass deine Kleidung die Farbe deiner Stimmung annimmt',
    b: 'dass sich deine Haare je nach Laune kräuseln',
    aEn: 'have your clothes change color with your mood',
    bEn: 'have your hair curl up depending on your mood',
  },
  {
    a: 'bei jedem Geburtstag ein Ständchen solo singen müssen',
    b: 'bei jedem Geburtstag eine Torte ins Gesicht bekommen',
    aEn: 'have to sing a solo birthday song at every birthday',
    bEn: 'get a cake in the face at every birthday',
  },
  {
    a: 'eine Stunde in einer Badewanne voller Wackelpudding sitzen',
    b: 'eine Stunde in einem Pool voller Cornflakes schwimmen',
    aEn: 'sit in a bathtub full of jelly for an hour',
    bEn: 'swim in a pool full of cornflakes for an hour',
  },
  {
    a: 'einen Tag lang nur „Banane“ sagen können',
    b: 'einen Tag lang nur mit Emojis kommunizieren dürfen',
    aEn: 'only be able to say “banana” for a day',
    bEn: 'only be allowed to communicate in emojis for a day',
  },
  {
    a: 'der Einzige im Kostüm auf einer normalen Party sein',
    b: 'der Einzige ohne Kostüm auf einer Kostümparty sein',
    aEn: 'be the only one in costume at a regular party',
    bEn: 'be the only one not in costume at a costume party',
  },
  {
    a: 'aus Versehen auf einer fremden Hochzeit landen und eine Rede halten müssen',
    b: 'aus Versehen in einem Seniorensportkurs landen und nicht gehen dürfen',
    aEn: 'accidentally end up at a stranger’s wedding and have to give a speech',
    bEn: 'accidentally end up in a seniors’ fitness class and not be allowed to leave',
  },
  {
    a: 'ein Jahr lang einen Ohrwurm von einem Kinderlied haben',
    b: 'ein Jahr lang einen Ohrwurm von einer Warteschleifenmelodie haben',
    aEn: 'have a children’s song stuck in your head for a year',
    bEn: 'have a hold music melody stuck in your head for a year',
  },
  {
    a: 'dass jedes Foto von dir automatisch einen Clownfilter hat',
    b: 'dass jedes Video von dir automatisch in Zeitlupe läuft',
    aEn: 'have every photo of you automatically get a clown filter',
    bEn: 'have every video of you automatically play in slow motion',
  },
  {
    a: 'eine Woche lang nur über eine Handpuppe sprechen dürfen',
    b: 'eine Woche lang nur mit Megafon sprechen dürfen',
    aEn: 'only be allowed to talk through a hand puppet for a week',
    bEn: 'only be allowed to talk through a megaphone for a week',
  },
  {
    a: 'beim Schwimmen nur noch Hundepaddeln können',
    b: 'beim Tanzen nur noch den Roboter können',
    aEn: 'only be able to doggy paddle when swimming',
    bEn: 'only be able to do the robot when dancing',
  },
  {
    a: 'jeden Tag eine Stunde lang Schluckauf haben',
    b: 'jeden Tag eine Stunde lang eine juckende Nase haben',
    aEn: 'have hiccups for an hour every day',
    bEn: 'have an itchy nose for an hour every day',
  },
  {
    a: 'zu jeder Prüfung eine Clownsnase tragen',
    b: 'jede Prüfung mit Gummihandschuhen schreiben',
    aEn: 'wear a clown nose to every exam',
    bEn: 'write every exam wearing rubber gloves',
  },
  {
    a: 'beim ersten Treffen mit den Schwiegereltern laut pupsen',
    b: 'beim ersten Treffen mit den Schwiegereltern ihre Lieblingsvase umwerfen',
    aEn: 'fart loudly the first time you meet your in-laws',
    bEn: 'knock over your in-laws’ favorite vase the first time you meet them',
  },
  {
    a: 'immer eine Sekunde zu spät lachen',
    b: 'immer eine Sekunde zu früh klatschen',
    aEn: 'always laugh one second too late',
    bEn: 'always clap one second too early',
  },
  {
    a: 'jede Nacht vom selben peinlichen Moment träumen',
    b: 'jeden Morgen ein peinliches Foto von dir im Familienchat finden',
    aEn: 'dream about the same embarrassing moment every night',
    bEn: 'find an embarrassing photo of yourself in the family chat every morning',
  },
  {
    a: 'Arme haben, die einen halben Meter zu lang sind',
    b: 'Beine haben, die einen halben Meter zu kurz sind',
    aEn: 'have arms that are half a meter too long',
    bEn: 'have legs that are half a meter too short',
  },
  {
    a: 'im Zug immer neben jemandem sitzen, der Döner isst',
    b: 'im Zug immer neben jemandem sitzen, der laut telefoniert',
    aEn: 'always sit next to someone eating a kebab on the train',
    bEn: 'always sit next to someone on a loud phone call on the train',
  },
  {
    a: 'eine Sprache sprechen, die nur Tauben verstehen',
    b: 'eine Sprache sprechen, die nur Kühe verstehen',
    aEn: 'speak a language only pigeons understand',
    bEn: 'speak a language only cows understand',
  },
  {
    a: 'immer statisch abstehende Haare haben',
    b: 'immer Kissenabdrücke im Gesicht haben',
    aEn: 'always have staticky hair standing on end',
    bEn: 'always have pillow creases on your face',
  },
  {
    a: 'in jedem Videocall aus Versehen das Mikro anlassen',
    b: 'in jedem Videocall aus Versehen die Kamera anlassen',
    aEn: 'accidentally leave your mic on in every video call',
    bEn: 'accidentally leave your camera on in every video call',
  },
  {
    a: 'Federn statt Haare haben',
    b: 'kleine Muscheln statt Fingernägel haben',
    aEn: 'have feathers instead of hair',
    bEn: 'have tiny seashells instead of fingernails',
  },
  {
    a: 'auf jedem Flug neben einem schreienden Baby sitzen',
    b: 'auf jedem Flug neben jemandem sitzen, der die Schuhe auszieht',
    aEn: 'sit next to a screaming baby on every flight',
    bEn: 'sit next to someone who takes their shoes off on every flight',
  },
  {
    a: 'einen Monat lang eine Krone tragen müssen',
    b: 'einen Monat lang einen Umhang tragen müssen',
    aEn: 'have to wear a crown for a month',
    bEn: 'have to wear a cape for a month',
  },
  {
    a: 'immer wie ein Nachrichtensprecher reden',
    b: 'immer wie ein Märchenerzähler reden',
    aEn: 'always talk like a news anchor',
    bEn: 'always talk like a fairy tale narrator',
  },
  {
    a: 'von Fremden immer für den Kellner gehalten werden',
    b: 'von Fremden immer nach dem Weg gefragt werden, den du nie kennst',
    aEn: 'always be mistaken for the waiter by strangers',
    bEn: 'always be asked for directions by strangers, though you never know the way',
  },
  {
    a: 'immer „Gerda“ genannt werden, egal wie du heißt',
    b: 'immer „Chef“ genannt werden, auch von deinem Chef',
    aEn: 'always be called “Gerda”, whatever your name is',
    bEn: 'always be called “boss”, even by your boss',
  },
  {
    a: 'beim Nachdenken Geräusche wie ein altes Modem machen',
    b: 'bei Wut Geräusche wie ein Wasserkocher machen',
    aEn: 'make dial-up modem noises when you think',
    bEn: 'make kettle noises when you get angry',
  },
  {
    a: 'zum Elternabend mit Lockenwicklern auftauchen',
    b: 'zum Elternabend im Kostüm vom Vorabend auftauchen',
    aEn: 'show up to a parents’ evening in hair curlers',
    bEn: 'show up to a parents’ evening in last night’s costume',
  },
  {
    a: 'jeden deiner Schritte laut mitzählen müssen',
    b: 'beim Öffnen jeder Tür laut „Tadaa!“ rufen müssen',
    aEn: 'have to count every step out loud',
    bEn: 'have to shout “Ta-da!” every time you open a door',
  },
  {
    a: 'einen Bauch haben, der wie eine Glocke klingt, wenn man draufklopft',
    b: 'einen Kopf haben, der wie eine Kokosnuss klingt, wenn man anklopft',
    aEn: 'have a belly that rings like a bell when tapped',
    bEn: 'have a head that sounds like a coconut when knocked on',
  },
  {
    a: 'mit einem Ziegenbock als Trauzeugen heiraten',
    b: 'mit einem Alpaka als Blumenkind heiraten',
    aEn: 'get married with a goat as your best man',
    bEn: 'get married with an alpaca as your flower girl',
  },
  {
    a: 'jeden Morgen mit aufgemaltem Schnurrbart aufwachen',
    b: 'jeden Morgen mit einer Socke im Mund aufwachen',
    aEn: 'wake up with a drawn-on mustache every morning',
    bEn: 'wake up with a sock in your mouth every morning',
  },
  {
    a: 'dass dein Name bei jedem Supermarktbesuch durchgesagt wird',
    b: 'bei jedem Supermarktbesuch mit dem Einkaufswagen irgendwo dagegenfahren',
    aEn: 'have your name announced every time you go to the supermarket',
    bEn: 'crash your shopping cart into something on every supermarket trip',
  },
  {
    a: 'immer die Unterhose aus der Hose gucken haben',
    b: 'immer den Pulli verkehrt herum anhaben',
    aEn: 'always have your underwear peeking out of your pants',
    bEn: 'always wear your sweater inside out',
  },
  {
    a: 'mit Bäumen reden können, die aber nur lästern',
    b: 'mit Fischen reden können, die aber nur jammern',
    aEn: 'be able to talk to trees, but they only gossip',
    bEn: 'be able to talk to fish, but they only complain',
  },
  {
    a: 'nie wieder Spaghetti essen können, ohne dich vollzuspritzen',
    b: 'nie wieder ein Brötchen schneiden können, ohne dass es zerbröselt',
    aEn: 'never again eat spaghetti without splattering yourself',
    bEn: 'never again cut a bread roll without it crumbling to bits',
  },
  {
    a: 'eine Schnecke als Haustier haben, die überall mitkommt',
    b: 'eine Ente haben, die dir überall folgt und dich anschnattert',
    aEn: 'have a pet snail that comes everywhere with you',
    bEn: 'have a duck that follows you everywhere quacking at you',
  },
  {
    a: 'eine Zahnspange tragen, bis du 80 bist',
    b: 'eine Brille mit winzigen Scheibenwischern tragen',
    aEn: 'wear braces until you’re 80',
    bEn: 'wear glasses with tiny windshield wipers',
  },
  {
    a: 'dass dein peinlichstes Video vor jedem Kinofilm läuft',
    b: 'dass dein Tanzstil das nächste Internet-Meme wird',
    aEn: 'have your most embarrassing video play before every movie',
    bEn: 'have your dance moves become the next internet meme',
  },
  {
    a: 'für immer nur 1 % Akku auf dem Handy haben',
    b: 'für immer Internet haben, das so langsam lädt wie 2005',
    aEn: 'have your phone stuck at 1% battery forever',
    bEn: 'have internet that loads like it’s 2005 forever',
  },
  {
    a: 'jedes Mal miauen müssen, wenn du eine Katze siehst',
    b: 'jedes Mal bellen müssen, wenn du einen Hund siehst',
    aEn: 'have to meow whenever you see a cat',
    bEn: 'have to bark whenever you see a dog',
  },
  {
    a: 'beim Online-Dating ein Match mit deiner alten Mathelehrerin haben',
    b: 'beim Online-Dating ein Match mit deinem Chef haben',
    aEn: 'match with your old math teacher on a dating app',
    bEn: 'match with your boss on a dating app',
  },
  {
    a: 'jedes Wort mit „-chen“ verniedlichen müssen',
    b: 'vor jedes Wort „Mega“ setzen müssen',
    aEn: 'have to add “little” to every word',
    bEn: 'have to put “mega” in front of every word',
  },
  {
    a: 'im Fitnessstudio beim Posieren vor dem Spiegel erwischt werden',
    b: 'im Büro beim Nasebohren erwischt werden',
    aEn: 'get caught posing in front of the gym mirror',
    bEn: 'get caught picking your nose at the office',
  },
  {
    a: 'eine Woche lang Taucherflossen statt Schuhe tragen',
    b: 'eine Woche lang auf Stelzen statt in Schuhen laufen',
    aEn: 'wear swim fins instead of shoes for a week',
    bEn: 'walk on stilts instead of shoes for a week',
  },
  {
    a: 'dass jede deiner Nachrichten mit „Gesendet von meinem Toaster“ endet',
    b: 'dass deine Autokorrektur jedes „Hallo“ zu „Hallöchen Popöchen“ macht',
    aEn: 'have every message you send end with “Sent from my toaster”',
    bEn: 'have autocorrect turn every “hi” into “hello sweet cheeks”',
  },
  {
    a: 'beim Tanzen leuchten wie eine Discokugel',
    b: 'beim Singen immer von Tauben umringt werden',
    aEn: 'glow like a disco ball whenever you dance',
    bEn: 'get surrounded by pigeons whenever you sing',
  },
  {
    a: 'Pizza nur noch mit Gewürzgurken und Banane essen dürfen',
    b: 'Pommes nur noch mit Vanillepudding essen dürfen',
    aEn: 'only be allowed to eat pizza with pickles and banana',
    bEn: 'only be allowed to eat fries with vanilla pudding',
  },
  {
    a: 'deinen Lebenslauf von deiner Mutter schreiben lassen',
    b: 'dein Dating-Profil von deinem Opa schreiben lassen',
    aEn: 'have your mom write your CV',
    bEn: 'have your grandpa write your dating profile',
  },
  {
    a: 'nie wieder ein Schraubglas aufbekommen',
    b: 'nie wieder eine Chipstüte leise öffnen können',
    aEn: 'never be able to open a jar again',
    bEn: 'never be able to open a bag of chips quietly again',
  },
  {
    a: 'in einem Musical leben, in dem jeder Streit gesungen wird',
    b: 'in einer Sitcom leben, in der nach jedem Fehler Lacher eingespielt werden',
    aEn: 'live in a musical where every argument is sung',
    bEn: 'live in a sitcom with a laugh track after every mistake',
  },
  {
    a: 'ein Einhorn-Horn auf der Stirn haben',
    b: 'winzige Engelsflügel haben, mit denen du nicht fliegen kannst',
    aEn: 'have a unicorn horn on your forehead',
    bEn: 'have tiny angel wings you can’t fly with',
  },
  {
    a: 'jeden Vortrag aus Versehen mit deinen Urlaubsfotos beginnen',
    b: 'jeden Vortrag mit einer Stimme halten, die ständig bricht',
    aEn: 'accidentally start every presentation with your vacation photos',
    bEn: 'give every presentation with a voice that keeps cracking',
  },
  {
    a: 'nach jedem Witz „Verstehst du?“ fragen müssen',
    b: 'jeden Witz zweimal erzählen müssen',
    aEn: 'have to ask “Get it?” after every joke',
    bEn: 'have to tell every joke twice',
  },
  {
    a: 'eine Augenbraue haben, die für immer hochgezogen ist',
    b: 'ein Auge haben, das ständig zwinkert',
    aEn: 'have one eyebrow permanently raised',
    bEn: 'have one eye that keeps winking',
  },
  {
    a: 'vom Nachbarn beim Singen in die Haarbürste erwischt werden',
    b: 'vom Nachbarn beim Plaudern mit deinen Pflanzen erwischt werden',
    aEn: 'get caught by your neighbor singing into a hairbrush',
    bEn: 'get caught by your neighbor chatting with your plants',
  },
  {
    a: 'nur noch Wörter mit drei Buchstaben benutzen',
    b: 'nur noch Wörter benutzen, die mit B anfangen',
    aEn: 'only use words with three letters',
    bEn: 'only use words that start with B',
  },
  {
    a: 'immer im Skianzug ins Freibad gehen',
    b: 'immer in Badehose zum Skifahren gehen',
    aEn: 'always go to the outdoor pool in a ski suit',
    bEn: 'always go skiing in swimwear',
  },
  {
    a: 'eine Woche lang ohne Daumen auskommen',
    b: 'eine Woche lang die Knie nicht beugen können',
    aEn: 'go a week without using your thumbs',
    bEn: 'be unable to bend your knees for a week',
  },
  {
    a: 'Pflanzen haben, die schreien, wenn du das Gießen vergisst',
    b: 'Wäsche haben, die weint, wenn sie zu lange liegt',
    aEn: 'have plants that scream when you forget to water them',
    bEn: 'have laundry that cries when it’s left lying around too long',
  },
  {
    a: 'in jedem Urlaub aus Versehen den Koffer eines Fremden mitnehmen',
    b: 'in jedem Urlaub am falschen Flughafen landen',
    aEn: 'accidentally take a stranger’s suitcase on every vacation',
    bEn: 'land at the wrong airport on every vacation',
  },
  {
    a: 'vor dem Schlafengehen immer einen Kopfstand machen müssen',
    b: 'vor dem Verlassen des Hauses immer ein Rad schlagen müssen',
    aEn: 'have to do a headstand before going to bed',
    bEn: 'have to do a cartwheel before leaving the house',
  },
  {
    a: 'dass all deine Sprachnachrichten hallen wie in einer Kathedrale',
    b: 'dass all deine Sprachnachrichten in doppeltem Tempo abgespielt werden',
    aEn: 'have all your voice messages echo like in a cathedral',
    bEn: 'have all your voice messages play at double speed',
  },
  {
    a: 'dass deine Mutter jeden deiner Posts kommentiert',
    b: 'dass dein Vater jeden Tag ein Babyfoto von dir postet',
    aEn: 'have your mom comment on every post you make',
    bEn: 'have your dad post a baby photo of you every day',
  },
  {
    a: 'dass bei jedem Fluchen ein Kirchenchor „Halleluja“ singt',
    b: 'dass bei jedem Seufzen ein Saxofon-Solo einsetzt',
    aEn: 'have a church choir sing “Hallelujah” every time you swear',
    bEn: 'have a saxophone solo kick in every time you sigh',
  },
  {
    a: 'noch einmal eine Woche in die fünfte Klasse gehen',
    b: 'eine Woche lang im Altersheim mitwohnen',
    aEn: 'go back to fifth grade for a week',
    bEn: 'live in a retirement home for a week',
  },
  {
    a: 'jeden Morgen deine Schuhe auf dem Dach finden',
    b: 'jeden Morgen dein Auto voller Klebezettel finden',
    aEn: 'find your shoes on the roof every morning',
    bEn: 'find your car covered in sticky notes every morning',
  },
  {
    a: 'im Kino immer laut den Film nacherzählen müssen',
    b: 'im Kino bei jedem Kuss laut „Uuuh“ machen müssen',
    aEn: 'have to narrate the movie out loud at the cinema',
    bEn: 'have to go “ooooh” loudly at every kiss at the cinema',
  },
  {
    a: 'immer der Letzte sein, der einen Witz versteht',
    b: 'immer der Einzige sein, der über deine eigenen Witze lacht',
    aEn: 'always be the last one to get a joke',
    bEn: 'always be the only one laughing at your own jokes',
  },
  {
    a: 'einen Fanclub aus Rentnern haben, der dich überall bejubelt',
    b: 'einen Fanclub aus Kindergartenkindern haben, der dich überall nachmacht',
    aEn: 'have a fan club of pensioners cheering you on everywhere',
    bEn: 'have a fan club of preschoolers copying you everywhere',
  },
  {
    a: 'immer die Rolltreppe in die falsche Richtung nehmen',
    b: 'immer gegen Glastüren laufen',
    aEn: 'always take the escalator going the wrong way',
    bEn: 'always walk into glass doors',
  },
  {
    a: 'auf der Hochzeit deines besten Freundes in Ritterrüstung erscheinen',
    b: 'auf der Hochzeit deines besten Freundes im Neoprenanzug erscheinen',
    aEn: 'show up to your best friend’s wedding in a suit of armor',
    bEn: 'show up to your best friend’s wedding in a wetsuit',
  },
  {
    a: 'einen Bauchnabel haben, der bei Hunger blinkt',
    b: 'Ohren haben, die bei Müdigkeit herunterklappen',
    aEn: 'have a belly button that blinks when you’re hungry',
    bEn: 'have ears that flop down when you’re tired',
  },
  {
    a: 'einen Tag lang Bürgermeister sein, aber nur Quatschgesetze erlassen dürfen',
    b: 'einen Tag lang Polizist sein, aber nur Tauben Strafzettel geben dürfen',
    aEn: 'be mayor for a day, but only allowed to pass silly laws',
    bEn: 'be a police officer for a day, but only allowed to give tickets to pigeons',
  },
  {
    a: 'dass jeder Hund dich für sein Herrchen hält',
    b: 'dass jede Katze dich für ihren Diener hält',
    aEn: 'have every dog think you’re its owner',
    bEn: 'have every cat think you’re its servant',
  },
  {
    a: 'einen Zwilling haben, der allen deine peinlichsten Geschichten erzählt',
    b: 'einen Klon haben, der immer das Gegenteil von dir sagt',
    aEn: 'have a twin who tells everyone your most embarrassing stories',
    bEn: 'have a clone who always says the opposite of you',
  },
  {
    a: 'eine Zahnlücke haben, die bei jedem „s“ pfeift',
    b: 'eine Zunge haben, die bei jedem „t“ rausrutscht',
    aEn: 'have a tooth gap that whistles on every “s”',
    bEn: 'have a tongue that slips out on every “t”',
  },
  {
    a: 'auf Familienfeiern immer am Kindertisch sitzen',
    b: 'auf Familienfeiern immer neben dem Onkel mit den Verschwörungstheorien sitzen',
    aEn: 'always sit at the kids’ table at family parties',
    bEn: 'always sit next to the conspiracy theory uncle at family parties',
  },
  {
    a: 'ein Handy haben, das bei jedem Runterfallen laut „Aua“ schreit',
    b: 'einen Laptop haben, der bei jedem Fehler laut seufzt',
    aEn: 'have a phone that yells “ouch” every time you drop it',
    bEn: 'have a laptop that sighs loudly at every error',
  },
  {
    a: 'einen Monat lang jeden Tag Rosenkohl zum Frühstück essen',
    b: 'einen Monat lang jeden Tag einen Leberwurst-Smoothie trinken',
    aEn: 'eat Brussels sprouts for breakfast every day for a month',
    bEn: 'drink a liverwurst smoothie every day for a month',
  },
  {
    a: 'nach jeder Verabschiedung in dieselbe Richtung gehen müssen wie die anderen',
    b: 'bei jedem Abschied eine halbe Umarmung und einen halben Handschlag machen',
    aEn: 'always have to walk the same way as the others after saying goodbye',
    bEn: 'do half a hug and half a handshake every time you say goodbye',
  },
  {
    a: 'immer zurückwinken, obwohl gar nicht du gemeint warst',
    b: 'immer „Du auch“ sagen, wenn der Kellner „Guten Appetit“ wünscht',
    aEn: 'always wave back when someone wasn’t waving at you',
    bEn: 'always say “you too” when the waiter says “enjoy your meal”',
  },
  {
    a: 'eine Wohnung voller lebensgroßer Pappaufsteller von dir haben',
    b: 'eine Wohnung haben, die komplett im Leopardenmuster eingerichtet ist',
    aEn: 'have a home full of life-size cardboard cutouts of yourself',
    bEn: 'have a home decorated entirely in leopard print',
  },
  {
    a: 'bei jedem „Ja“ nicken wie ein Wackeldackel',
    b: 'bei jedem „Nein“ mit dem Fuß aufstampfen',
    aEn: 'nod like a bobblehead every time you say “yes”',
    bEn: 'stomp your foot every time you say “no”',
  },
  {
    a: 'unter einer Blaskapelle wohnen, die jeden Morgen probt',
    b: 'neben einem Hahn wohnen, der jede Stunde kräht',
    aEn: 'live below a brass band that rehearses every morning',
    bEn: 'live next to a rooster that crows every hour',
  },
  {
    a: 'eine Glatze mit einer tätowierten Landkarte haben',
    b: 'einen Vokuhila haben, den du nie ändern darfst',
    aEn: 'be bald with a map tattooed on your head',
    bEn: 'have a mullet you’re never allowed to change',
  },
  {
    a: 'ein Navi haben, das dich bei jedem Verfahren beleidigt',
    b: 'ein Navi haben, das bei jedem Abbiegen laut jubelt',
    aEn: 'have a GPS that insults you whenever you take a wrong turn',
    bEn: 'have a GPS that cheers loudly at every turn',
  },
  {
    a: 'auf jede Frage in schlechtem Französisch antworten',
    b: 'auf jede Frage mit Opernstimme antworten',
    aEn: 'answer every question in bad French',
    bEn: 'answer every question in an opera voice',
  },
  {
    a: 'jede Nacht schnarchen wie ein Rasenmäher',
    b: 'jede Nacht im Schlaf laut lachen',
    aEn: 'snore like a lawnmower every night',
    bEn: 'laugh out loud in your sleep every night',
  },
  {
    a: 'Kopfhörer haben, die sich immer mit dem Lautsprecher im Bus verbinden',
    b: 'einen Handywecker haben, der immer in Meetings klingelt',
    aEn: 'have headphones that always connect to the bus speakers',
    bEn: 'have a phone alarm that always goes off in meetings',
  },
  {
    a: 'bei jeder Begrüßung zwei Wangenküsschen zu viel geben',
    b: 'bei jeder Begrüßung einen Fistbump erwarten und ins Leere hauen',
    aEn: 'give two cheek kisses too many every time you greet someone',
    bEn: 'go for a fist bump and hit thin air every time you greet someone',
  },
  {
    a: 'vor Publikum gegen deine Oma im Armdrücken verlieren',
    b: 'vor Publikum gegen ein Kind im Schach verlieren',
    aEn: 'lose an arm wrestle to your grandma in front of a crowd',
    bEn: 'lose a game of chess to a child in front of a crowd',
  },
  {
    a: 'einen Tag lang mit deinem Haustier die Rollen tauschen',
    b: 'einen Tag lang mit deinem Chef die Rollen tauschen',
    aEn: 'swap roles with your pet for a day',
    bEn: 'swap roles with your boss for a day',
  },
  {
    a: 'jedes Mal anfangen zu jodeln, wenn du nervös bist',
    b: 'jedes Mal einen Stepptanz hinlegen, wenn du nervös bist',
    aEn: 'start yodeling whenever you’re nervous',
    bEn: 'break into a tap dance whenever you’re nervous',
  },
  {
    a: 'vor jedem Satz erst ein Kompliment machen müssen',
    b: 'vor jedem Satz erst „Entschuldigung“ sagen müssen',
    aEn: 'have to give a compliment before every sentence',
    bEn: 'have to say “sorry” before every sentence',
  },
  {
    a: 'bei jedem Niesen ein Popcorn aus der Nase schießen',
    b: 'bei jedem Husten eine kleine Feder ausspucken',
    aEn: 'shoot a piece of popcorn out of your nose with every sneeze',
    bEn: 'cough up a little feather every time you cough',
  },
  {
    a: 'dass der Bus immer auf dich wartet, aber alle beim Einsteigen klatschen',
    b: 'dass jeder Zug genau in dem Moment abfährt, in dem du ankommst',
    aEn: 'have the bus always wait for you, but everyone claps as you get on',
    bEn: 'have every train leave the exact moment you arrive',
  },
  {
    a: 'die Superkraft haben, Brot mit bloßen Händen zu toasten',
    b: 'die Superkraft haben, immer die passende zweite Socke zu finden',
    aEn: 'have the superpower to toast bread with your bare hands',
    bEn: 'have the superpower to always find the matching sock',
  },
  {
    a: 'fliegen können, aber nur in Schrittgeschwindigkeit',
    b: 'unsichtbar werden können, aber nur, solange du die Luft anhältst',
    aEn: 'be able to fly, but only at walking speed',
    bEn: 'be able to turn invisible, but only while holding your breath',
  },
  {
    a: 'mit deiner Mutter im selben Büro arbeiten',
    b: 'deinen Vater als Mitspieler in deiner Fußballmannschaft haben',
    aEn: 'share an office with your mom',
    bEn: 'have your dad as a teammate on your football team',
  },
  {
    a: 'ein Jahr lang jeden Tag einen Rentierpulli tragen',
    b: 'ein Jahr lang jeden Tag ein Hawaiihemd tragen',
    aEn: 'wear a reindeer sweater every day for a year',
    bEn: 'wear a Hawaiian shirt every day for a year',
  },
  {
    a: 'bei jedem Lachen das Gleichgewicht verlieren',
    b: 'bei jedem Lachen in Strömen weinen',
    aEn: 'lose your balance every time you laugh',
    bEn: 'cry floods of tears every time you laugh',
  },
  {
    a: 'eine Autohupe haben, die „La Cucaracha“ spielt',
    b: 'eine Fahrradklingel haben, die bei jedem Tritt bimmelt',
    aEn: 'have a car horn that plays “La Cucaracha”',
    bEn: 'have a bike bell that dings with every pedal stroke',
  },
  {
    a: 'immer Hosen haben, die zu kurz sind',
    b: 'immer Ärmel haben, die zu lang sind',
    aEn: 'always have pants that are too short',
    bEn: 'always have sleeves that are too long',
  },
  {
    a: 'beim Einparken immer Publikum haben, das Punkte vergibt',
    b: 'an der Kasse immer Kleingeld abzählen müssen, während die Schlange wächst',
    aEn: 'always have an audience scoring you when you park',
    bEn: 'always have to count out coins at the checkout while the line grows',
  },
  {
    a: 'dass nach jedem Gespräch ein Abspann mit deinem Namen läuft',
    b: 'dass vor jedem Gespräch ein „Was bisher geschah“ läuft',
    aEn: 'have end credits with your name roll after every conversation',
    bEn: 'have a “previously on” recap play before every conversation',
  },
  {
    a: 'Fußspuren hinterlassen, die wie eine Disco-Tanzfläche leuchten',
    b: 'überall, wo du gehst, Gänseblümchen sprießen lassen',
    aEn: 'leave footprints that light up like a disco floor',
    bEn: 'make daisies sprout everywhere you walk',
  },
];
