import type { WouldYouRatherSeed } from './types';

export const grossQuestions: WouldYouRatherSeed[] = [
  {
    a: 'eine Woche nicht duschen',
    b: 'eine Woche dieselben Socken tragen',
    aEn: 'not shower for a week',
    bEn: 'wear the same socks for a week',
  },
  {
    a: 'ein Glas warme Mayonnaise trinken',
    b: 'ein Glas warmes Gurkenwasser trinken',
    aEn: 'drink a glass of warm mayonnaise',
    bEn: 'drink a glass of warm pickle brine',
  },
  {
    a: 'die Zahnbürste eines Fremden benutzen',
    b: 'den Kaugummi eines Fremden weiterkauen',
    aEn: 'use a stranger’s toothbrush',
    bEn: 'keep chewing a stranger’s gum',
  },
  {
    a: 'in einem Bällebad voller Kakerlaken sitzen',
    b: 'in einer Badewanne voller Nacktschnecken liegen',
    aEn: 'sit in a ball pit full of cockroaches',
    bEn: 'lie in a bathtub full of slugs',
  },
  {
    a: 'nur noch Essen bekommen, in dem ein Haar liegt',
    b: 'nur noch Essen bekommen, auf das jemand geniest hat',
    aEn: 'only ever get food with a hair in it',
    bEn: 'only ever get food someone sneezed on',
  },
  {
    a: 'deinen Kopf eine Minute in eine alte Sporttasche stecken',
    b: 'einmal quer über eine Turnmatte lecken',
    aEn: 'stick your head in an old gym bag for a minute',
    bEn: 'lick all the way across a gym mat',
  },
  {
    a: 'den ganzen Tag nasse Socken tragen',
    b: 'den ganzen Tag Sand in der Unterhose haben',
    aEn: 'wear wet socks all day',
    bEn: 'have sand in your underwear all day',
  },
  {
    a: 'eine lebende Made essen',
    b: 'ein Getränk austrinken, in dem eine tote Fliege schwimmt',
    aEn: 'eat a live maggot',
    bEn: 'finish a drink with a dead fly floating in it',
  },
  {
    a: 'jeden Morgen mit einer Spinne auf dem Gesicht aufwachen',
    b: 'jeden Abend eine Kakerlake in deinem Bett finden',
    aEn: 'wake up with a spider on your face every morning',
    bEn: 'find a cockroach in your bed every night',
  },
  {
    a: 'Schweißfüße haben, die man im ganzen Haus riecht',
    b: 'Mundgeruch haben, und niemand sagt es dir',
    aEn: 'have sweaty feet the whole house can smell',
    bEn: 'have bad breath and nobody ever tells you',
  },
  {
    a: 'an einem benutzten Wattestäbchen eines Fremden lecken',
    b: 'auf einem abgeschnittenen Fußnagel eines Fremden kauen',
    aEn: 'lick a stranger’s used cotton swab',
    bEn: 'chew on a stranger’s toenail clipping',
  },
  {
    a: 'eine Nacht im Dixi-Klo am letzten Festivaltag schlafen',
    b: 'eine Woche lang die Dixi-Klos eines Festivals putzen',
    aEn: 'sleep one night in a porta-potty on the last day of a festival',
    bEn: 'clean a festival’s porta-potties for a week',
  },
  {
    a: 'ein Sandwich essen, das im Bus auf den Boden gefallen ist',
    b: 'ein Sandwich essen, das ein Hund abgeleckt hat',
    aEn: 'eat a sandwich that fell on the floor of a bus',
    bEn: 'eat a sandwich a dog licked',
  },
  {
    a: 'den Duschabfluss einer WG mit bloßen Händen reinigen',
    b: 'ein Waschbecken voller fremder Barthaare putzen',
    aEn: 'unclog a shared flat’s shower drain with your bare hands',
    bEn: 'clean a sink full of a stranger’s beard hairs',
  },
  {
    a: 'immer leicht nach Zwiebeln riechen',
    b: 'immer leicht nach Fisch riechen',
    aEn: 'always smell faintly of onions',
    bEn: 'always smell faintly of fish',
  },
  {
    a: 'dir von einem sabbernden Bernhardiner das Gesicht abschlecken lassen',
    b: 'dir von einer Kuh einmal übers Gesicht lecken lassen',
    aEn: 'let a drooling St. Bernard lick your face',
    bEn: 'let a cow lick your face once',
  },
  {
    a: 'Milch trinken, die seit einer Woche abgelaufen ist',
    b: 'Joghurt essen, von dem du den Schimmel abgekratzt hast',
    aEn: 'drink milk that expired a week ago',
    bEn: 'eat yogurt after scraping the mold off',
  },
  {
    a: 'ein Jahr lang keine Zähne putzen dürfen',
    b: 'ein Jahr lang kein Deo benutzen dürfen',
    aEn: 'not be allowed to brush your teeth for a year',
    bEn: 'not be allowed to use deodorant for a year',
  },
  {
    a: 'eine Handvoll lebender Mehlwürmer essen',
    b: 'ein rohes Ei samt Schale zerkauen',
    aEn: 'eat a handful of live mealworms',
    bEn: 'chew up a raw egg, shell and all',
  },
  {
    a: 'deine Zehennägel nur noch mit den Zähnen kürzen können',
    b: 'deine Fingernägel nie wieder schneiden können',
    aEn: 'only be able to trim your toenails with your teeth',
    bEn: 'never be able to cut your fingernails again',
  },
  {
    a: 'jedes Mal pupsen, wenn du laut lachst',
    b: 'jedes Mal laut rülpsen, wenn du jemanden begrüßt',
    aEn: 'fart every time you laugh out loud',
    bEn: 'burp loudly every time you greet someone',
  },
  {
    a: 'in einer Wohnung voller Fruchtfliegen leben',
    b: 'in einer Wohnung mit einem Mäusenest in der Wand leben',
    aEn: 'live in a flat full of fruit flies',
    bEn: 'live in a flat with a mouse nest in the wall',
  },
  {
    a: 'ein Glas Spülwasser nach dem Abwasch trinken',
    b: 'ein Glas Wasser aus einer alten Blumenvase trinken',
    aEn: 'drink a glass of dishwater after the washing up',
    bEn: 'drink a glass of water from an old flower vase',
  },
  {
    a: 'bei jedem Bissen ein langes Haar im Mund spüren',
    b: 'bei jedem Schluck Sand zwischen den Zähnen haben',
    aEn: 'feel a long hair in your mouth with every bite',
    bEn: 'get sand between your teeth with every sip',
  },
  {
    a: 'mit jemandem das Bett teilen, der schnarcht und sabbert',
    b: 'mit jemandem das Bett teilen, der nachts ständig pupst',
    aEn: 'share a bed with someone who snores and drools',
    bEn: 'share a bed with someone who farts all night',
  },
  {
    a: 'kalte Pizza essen, auf der jemand eingeschlafen ist',
    b: 'warme Pizza essen, die jemand angeleckt hat',
    aEn: 'eat cold pizza someone fell asleep on',
    bEn: 'eat warm pizza someone licked',
  },
  {
    a: 'in der vollen Bahn ausgiebig in der Nase bohren',
    b: 'in der vollen Bahn die Schuhe ausziehen und an deinen Füßen riechen',
    aEn: 'pick your nose thoroughly on a packed train',
    bEn: 'take off your shoes on a packed train and sniff your feet',
  },
  {
    a: 'eine Schüssel Haferbrei essen, der seit drei Tagen herumsteht',
    b: 'eine Schüssel Wackelpudding mit Haaren drin essen',
    aEn: 'eat a bowl of porridge that’s been sitting out for three days',
    bEn: 'eat a bowl of jelly with hairs in it',
  },
  {
    a: 'die verschwitzten Trikots einer ganzen Fußballmannschaft waschen',
    b: 'die Kühlschränke einer ganzen WG-Etage ausräumen',
    aEn: 'wash a whole football team’s sweaty jerseys',
    bEn: 'clear out the fridges of an entire shared-flat floor',
  },
  {
    a: 'sechs Wochen einen Gips tragen, unter dem es juckt und stinkt',
    b: 'sechs Wochen eine Zahnspange tragen, in der immer Essen hängt',
    aEn: 'wear an itchy, smelly cast for six weeks',
    bEn: 'wear braces that always have food stuck in them for six weeks',
  },
  {
    a: 'eine Fischsuppe essen, in der noch die Augen schwimmen',
    b: 'eine Hühnersuppe essen, in der noch die Füße liegen',
    aEn: 'eat fish soup with the eyes still floating in it',
    bEn: 'eat chicken soup with the feet still in it',
  },
  {
    a: 'barfuß durch eine Bahnhofstoilette laufen',
    b: 'barfuß durch einen Kuhstall laufen',
    aEn: 'walk barefoot through a train station toilet',
    bEn: 'walk barefoot through a cowshed',
  },
  {
    a: 'einen Schluck aus einem Aquarium trinken',
    b: 'einen Schluck aus einer Pfütze am Bahnhof trinken',
    aEn: 'take a sip from a fish tank',
    bEn: 'take a sip from a puddle at a train station',
  },
  {
    a: 'den Schweiß von einem Laufband im Fitnessstudio ablecken',
    b: 'die Tasten eines Geldautomaten ablecken',
    aEn: 'lick the sweat off a gym treadmill',
    bEn: 'lick the buttons of a cash machine',
  },
  {
    a: 'dein Leben lang sichtbare Schuppen haben',
    b: 'dein Leben lang feuchte, klebrige Hände haben',
    aEn: 'have visible dandruff for the rest of your life',
    bEn: 'have damp, sticky hands for the rest of your life',
  },
  {
    a: 'Tee trinken, der durch eine getragene Socke gefiltert wurde',
    b: 'Kaffee aus einem ungespülten Aschenbecher trinken',
    aEn: 'drink tea filtered through a worn sock',
    bEn: 'drink coffee out of an unwashed ashtray',
  },
  {
    a: 'eine Woche in einem Zimmer mit einem nassen Hund schlafen',
    b: 'eine Woche neben einem Katzenklo schlafen, das keiner sauber macht',
    aEn: 'sleep in a room with a wet dog for a week',
    bEn: 'sleep for a week next to a litter box nobody cleans',
  },
  {
    a: 'dir die Zähne mit Seife putzen',
    b: 'dir die Haare mit Bratfett waschen',
    aEn: 'brush your teeth with soap',
    bEn: 'wash your hair with cooking grease',
  },
  {
    a: 'dein Handy aus einer ungespülten Toilette fischen',
    b: 'deinen Schlüssel aus einem vollen Mülleimer im Park fischen',
    aEn: 'fish your phone out of an unflushed toilet',
    bEn: 'fish your keys out of a full bin in the park',
  },
  {
    a: 'nur noch Essen mit der Konsistenz von Schleim essen',
    b: 'nur noch Essen mit der Konsistenz von Sand essen',
    aEn: 'only eat food with the texture of slime',
    bEn: 'only eat food with the texture of sand',
  },
  {
    a: 'eine Gabel Surströmming essen',
    b: 'ein ganzes Stück Durian essen',
    aEn: 'eat a forkful of surströmming',
    bEn: 'eat a whole piece of durian',
  },
  {
    a: 'mit einem riesigen Pickel auf der Nase zum ersten Date gehen',
    b: 'mit Spinat zwischen den Zähnen zum Vorstellungsgespräch gehen',
    aEn: 'go on a first date with a huge pimple on your nose',
    bEn: 'go to a job interview with spinach in your teeth',
  },
  {
    a: 'in jedem Meeting einen laut knurrenden Magen haben',
    b: 'in jedem Meeting feuchte Aussprache haben',
    aEn: 'have a loudly growling stomach in every meeting',
    bEn: 'spit a little when you talk in every meeting',
  },
  {
    a: 'einen Tag in einem Kostüm stecken, das nach altem Schweiß riecht',
    b: 'einen Tag in Gummistiefeln voller Wasser herumlaufen',
    aEn: 'spend a day in a costume that smells of old sweat',
    bEn: 'spend a day walking around in wellies full of water',
  },
  {
    a: 'eine Spinne auf deiner Zahnbürste entdecken, nachdem du geputzt hast',
    b: 'eine Schnecke in deinem Salat entdecken, nachdem du gegessen hast',
    aEn: 'find a spider on your toothbrush after brushing',
    bEn: 'find a snail in your salad after eating',
  },
  {
    a: 'mit einem Ohrenkneifer im Ohr aufwachen',
    b: 'mit einem Tausendfüßler im Schuh loslaufen',
    aEn: 'wake up with an earwig in your ear',
    bEn: 'set off with a centipede in your shoe',
  },
  {
    a: 'aus einem Glas trinken, in dem über Nacht ein Gebiss lag',
    b: 'aus einer Flasche trinken, in die jemand zurückgespuckt hat',
    aEn: 'drink from a glass someone soaked their dentures in overnight',
    bEn: 'drink from a bottle someone spat back into',
  },
  {
    a: 'ein Eis essen, an dem eine Taube gepickt hat',
    b: 'ein Eis essen, an dem ein Kleinkind geschleckt hat',
    aEn: 'eat an ice cream a pigeon pecked at',
    bEn: 'eat an ice cream a toddler licked',
  },
  {
    a: 'den Kühlschrank nach einem Stromausfall im Sommerurlaub ausräumen',
    b: 'eine Brotdose öffnen, die seit den Sommerferien im Schulranzen liegt',
    aEn: 'clear out the fridge after a power cut during your summer holiday',
    bEn: 'open a lunchbox that’s been in a school bag since the summer holidays',
  },
  {
    a: 'einen Fingernagel in deinem Döner finden',
    b: 'ein Pflaster in deinem Salat finden',
    aEn: 'find a fingernail in your kebab',
    bEn: 'find a plaster in your salad',
  },
  {
    a: 'in einem Zelt schlafen, das nach Katzenpipi riecht',
    b: 'in einem Hotelbett schlafen, auf dessen Kissen fremde Haare liegen',
    aEn: 'sleep in a tent that smells of cat pee',
    bEn: 'sleep in a hotel bed with a stranger’s hairs on the pillow',
  },
  {
    a: 'einen Monat lang jeden Morgen kalten Kaffee mit Haut drauf trinken',
    b: 'einen Monat lang jeden Morgen Milch mit Klümpchen trinken',
    aEn: 'drink cold coffee with a skin on it every morning for a month',
    bEn: 'drink lumpy milk every morning for a month',
  },
  {
    a: 'deine Hand in einen Eimer voller Regenwürmer stecken',
    b: 'deine Hand in einen Eimer mit kaltem Bratfett stecken',
    aEn: 'put your hand in a bucket full of earthworms',
    bEn: 'put your hand in a bucket of cold cooking fat',
  },
  {
    a: 'in lauwarmem Haferschleim baden',
    b: 'in eiskalter Erbsensuppe baden',
    aEn: 'bathe in lukewarm oat gruel',
    bEn: 'bathe in ice-cold pea soup',
  },
  {
    a: 'den Atem von jemandem riechen, der gerade Thunfisch gegessen hat',
    b: 'an der Achsel von jemandem riechen, der gerade joggen war',
    aEn: 'smell the breath of someone who just ate tuna',
    bEn: 'sniff the armpit of someone who just went jogging',
  },
  {
    a: 'dir die Zähne mit der Zahnbürste deines Hundes putzen',
    b: 'dir das Gesicht mit einem Handtuch aus dem Fitnessstudio abtrocknen',
    aEn: 'brush your teeth with your dog’s toothbrush',
    bEn: 'dry your face with a towel from the gym',
  },
  {
    a: 'einen alten Kaugummi kauen, der unter einem Tisch klebte',
    b: 'ein Bonbon lutschen, das schon jemand anderes im Mund hatte',
    aEn: 'chew old gum that was stuck under a table',
    bEn: 'suck a sweet someone else already had in their mouth',
  },
  {
    a: 'deinen Bauchnabel nie wieder sauber machen können',
    b: 'deine Ohren nie wieder sauber machen können',
    aEn: 'never be able to clean your belly button again',
    bEn: 'never be able to clean your ears again',
  },
  {
    a: 'für 100 Euro eine lebende Kakerlake essen',
    b: 'für 100 Euro ein Glas Sardinenöl austrinken',
    aEn: 'eat a live cockroach for 100 euros',
    bEn: 'drink a whole glass of sardine oil for 100 euros',
  },
  {
    a: 'beim Essen immer laut schmatzen müssen',
    b: 'beim Essen immer neben jemandem sitzen, der laut schmatzt',
    aEn: 'always have to chew loudly with your mouth open',
    bEn: 'always have to sit next to someone who chews loudly',
  },
  {
    a: 'nach einem Marathon die Socken eines Läufers anziehen',
    b: 'nach einem Marathon das Stirnband eines Läufers tragen',
    aEn: 'put on a runner’s socks right after a marathon',
    bEn: 'wear a runner’s headband right after a marathon',
  },
  {
    a: 'eine Ratte über deinen nackten Fuß laufen lassen',
    b: 'eine Nacktschnecke über deinen Arm kriechen lassen',
    aEn: 'let a rat run over your bare foot',
    bEn: 'let a slug crawl along your arm',
  },
  {
    a: 'Spaghetti mit Ketchup und Vanillepudding essen',
    b: 'Pizza mit Banane und Thunfisch essen',
    aEn: 'eat spaghetti with ketchup and vanilla custard',
    bEn: 'eat pizza with banana and tuna',
  },
  {
    a: 'Cornflakes mit Orangensaft statt Milch essen',
    b: 'Pommes in heißen Kakao tunken',
    aEn: 'eat cornflakes with orange juice instead of milk',
    bEn: 'dip chips in hot chocolate',
  },
  {
    a: 'einen Smoothie aus Rosenkohl und Schokolade trinken',
    b: 'einen Milchshake mit Leberwurst trinken',
    aEn: 'drink a Brussels sprout and chocolate smoothie',
    bEn: 'drink a liver sausage milkshake',
  },
  {
    a: 'direkt nach dem Zähneputzen Orangensaft trinken',
    b: 'Kaffee mit Salz statt Zucker trinken',
    aEn: 'drink orange juice right after brushing your teeth',
    bEn: 'drink coffee with salt instead of sugar',
  },
  {
    a: 'einem Fremden direkt nach seinem Niesen die Hand geben',
    b: 'einem Fremden die Hand geben, der ungewaschen vom Klo kommt',
    aEn: 'shake a stranger’s hand right after they sneezed into it',
    bEn: 'shake hands with a stranger who just left the loo without washing',
  },
  {
    a: 'im Kino auf einem klebrigen Sitz sitzen',
    b: 'im Kino neben jemandem sitzen, der seine Schuhe auszieht',
    aEn: 'sit on a sticky seat at the cinema',
    bEn: 'sit next to someone at the cinema who takes their shoes off',
  },
  {
    a: 'im Flugzeug neben jemandem sitzen, der seine nackten Füße auf deine Armlehne legt',
    b: 'im Flugzeug neben jemandem sitzen, der dich ständig anhustet',
    aEn: 'sit next to someone on a plane who puts their bare feet on your armrest',
    bEn: 'sit next to someone on a plane who keeps coughing on you',
  },
  {
    a: 'eine Woche ohne Klopapier auskommen',
    b: 'eine Woche ohne Zahnpasta auskommen',
    aEn: 'go a week without toilet paper',
    bEn: 'go a week without toothpaste',
  },
  {
    a: 'immer fettige Haare haben, egal wie oft du sie wäschst',
    b: 'immer klebrige Haut haben, egal wie oft du duschst',
    aEn: 'always have greasy hair no matter how often you wash it',
    bEn: 'always have sticky skin no matter how often you shower',
  },
  {
    a: 'in einer Wanne voller abgeschnittener Haare vom Friseur baden',
    b: 'in einer Wanne voller gebrauchter Teebeutel baden',
    aEn: 'bathe in a tub full of hair clippings from a barber',
    bEn: 'bathe in a tub full of used teabags',
  },
  {
    a: 'einen Wurm in deinem Apfel halb durchbeißen',
    b: 'eine Larve in deiner Himbeere zerkauen',
    aEn: 'bite a worm in your apple in half',
    bEn: 'chew up a grub in your raspberry',
  },
  {
    a: 'deinen Schreibtisch direkt neben dem stinkenden Bürokühlschrank haben',
    b: 'deinen Schreibtisch neben dem Kollegen haben, der täglich Fisch in der Mikrowelle wärmt',
    aEn: 'have your desk right next to the smelly office fridge',
    bEn: 'sit next to the colleague who microwaves fish every day',
  },
  {
    a: 'den Fettabscheider einer Imbissbude sauber machen',
    b: 'die Biotonnen einer ganzen Straße auswaschen',
    aEn: 'clean out a takeaway’s grease trap',
    bEn: 'wash out the compost bins of an entire street',
  },
  {
    a: 'bei jedem Date riesige Schweißflecken unter den Armen haben',
    b: 'bei jedem Date Essensreste im Mundwinkel haben',
    aEn: 'have huge sweat patches under your arms on every date',
    bEn: 'have food stuck in the corner of your mouth on every date',
  },
  {
    a: 'eine Mahlzeit aus einem Hundenapf essen',
    b: 'eine Mahlzeit aus einem Schweinetrog essen',
    aEn: 'eat a meal out of a dog bowl',
    bEn: 'eat a meal out of a pig trough',
  },
  {
    a: 'Saft trinken, der in der Sonne angefangen hat zu gären',
    b: 'Wasser trinken, das drei Wochen in einer Flasche im heißen Auto lag',
    aEn: 'drink juice that started fermenting in the sun',
    bEn: 'drink water that sat in a bottle in a hot car for three weeks',
  },
  {
    a: 'an einem drei Monate alten Küchenschwamm riechen',
    b: 'an einem Handtuch riechen, das tagelang nass in der Waschmaschine lag',
    aEn: 'sniff a three-month-old kitchen sponge',
    bEn: 'sniff a towel that sat wet in the washing machine for days',
  },
  {
    a: 'einen Monat lang Läuse haben',
    b: 'einen Monat lang Fußpilz haben',
    aEn: 'have head lice for a month',
    bEn: 'have athlete’s foot for a month',
  },
  {
    a: 'jede Nacht von zehn Mücken gestochen werden',
    b: 'jede Nacht eine Spinne über dein Kissen laufen sehen',
    aEn: 'get bitten by ten mosquitoes every night',
    bEn: 'watch a spider walk across your pillow every night',
  },
  {
    a: 'eine Mahlzeit aus dem Müll eines Sternerestaurants essen',
    b: 'eine Mahlzeit in der dreckigsten Imbissbude der Stadt essen',
    aEn: 'eat a meal out of a Michelin-star restaurant’s bin',
    bEn: 'eat a meal at the filthiest takeaway in town',
  },
  {
    a: 'die Haut von gekochter Milch essen',
    b: 'die Fettschicht von kalter Bratensoße löffeln',
    aEn: 'eat the skin off boiled milk',
    bEn: 'spoon up the layer of fat from cold gravy',
  },
  {
    a: 'einen Teller Kutteln essen',
    b: 'einen Teller kalte Blutwurst essen',
    aEn: 'eat a plate of tripe',
    bEn: 'eat a plate of cold black pudding',
  },
  {
    a: 'ein Stück fermentierten Hai aus Island essen',
    b: 'ein schwarzes, tausendjähriges Ei essen',
    aEn: 'eat a piece of Icelandic fermented shark',
    bEn: 'eat a black century egg',
  },
  {
    a: 'dass dein Schweiß immer nach Knoblauch riecht',
    b: 'dass jeder deiner Pupse nach faulen Eiern riecht',
    aEn: 'have sweat that always smells of garlic',
    bEn: 'have every fart smell of rotten eggs',
  },
  {
    a: 'immer das abgeleckte Besteck eines Fremden benutzen müssen',
    b: 'immer aus dem halbvollen Glas eines Fremden trinken müssen',
    aEn: 'always have to use a stranger’s licked cutlery',
    bEn: 'always have to drink from a stranger’s half-full glass',
  },
  {
    a: 'eine Woche bei jemandem mit 30 Katzen wohnen',
    b: 'eine Woche in einem Hühnerstall wohnen',
    aEn: 'live for a week with someone who has 30 cats',
    bEn: 'live in a chicken coop for a week',
  },
  {
    a: 'einen Zahnarzt haben, der beim Bohren nach Zwiebeln riecht',
    b: 'einen Friseur haben, der dir die ganze Zeit in den Nacken schnauft',
    aEn: 'have a dentist whose breath smells of onions while drilling',
    bEn: 'have a hairdresser who keeps breathing heavily on your neck',
  },
  {
    a: 'barfuß auf eine Nacktschnecke treten',
    b: 'mit Flip-Flops in einen Hundehaufen treten',
    aEn: 'step on a slug barefoot',
    bEn: 'step in dog poo wearing flip-flops',
  },
  {
    a: 'Ketchup auf Vanilleeis essen',
    b: 'Senf auf Schokoladenkuchen essen',
    aEn: 'eat ketchup on vanilla ice cream',
    bEn: 'eat mustard on chocolate cake',
  },
  {
    a: 'eine ganze Knoblauchknolle roh essen',
    b: 'eine ganze Zwiebel wie einen Apfel essen',
    aEn: 'eat a whole bulb of raw garlic',
    bEn: 'eat a whole onion like an apple',
  },
  {
    a: 'einen Becher geschmolzene Butter trinken',
    b: 'einen Becher Olivenöl trinken',
    aEn: 'drink a cup of melted butter',
    bEn: 'drink a cup of olive oil',
  },
  {
    a: 'einen Löffel Katzenfutter essen',
    b: 'einen Löffel Fischfutter essen',
    aEn: 'eat a spoonful of cat food',
    bEn: 'eat a spoonful of fish food',
  },
  {
    a: 'einen Döner essen, der eine Nacht im Auto lag',
    b: 'Sushi essen, das einen Tag in der Sonne stand',
    aEn: 'eat a kebab that spent a night in the car',
    bEn: 'eat sushi that sat in the sun for a day',
  },
  {
    a: 'Gummibärchen essen, die in einer Hosentasche geschmolzen sind',
    b: 'Schokolade essen, die jemand im Mund angewärmt hat',
    aEn: 'eat gummy bears that melted in someone’s pocket',
    bEn: 'eat chocolate someone warmed up in their mouth',
  },
  {
    a: 'Pommes essen, die jemand angefasst und zurückgelegt hat',
    b: 'Chips aus einer Dip-Schüssel essen, in die jeder doppelt gedippt hat',
    aEn: 'eat fries someone touched and put back',
    bEn: 'eat chips from a dip everyone double-dipped in',
  },
  {
    a: 'Wackelpudding mit Fleischstückchen drin essen',
    b: 'Kartoffelbrei mit Rosinen und Gummibärchen essen',
    aEn: 'eat jelly with bits of meat in it',
    bEn: 'eat mashed potatoes with raisins and gummy bears',
  },
  {
    a: 'Salat essen, an dem noch Erde hängt',
    b: 'Muscheln essen, die beim Kauen knirschen',
    aEn: 'eat salad with soil still stuck to it',
    bEn: 'eat mussels that crunch when you chew',
  },
  {
    a: 'ein gebratenes Hirn probieren',
    b: 'eine gekochte Zunge probieren',
    aEn: 'try fried brain',
    bEn: 'try boiled tongue',
  },
  {
    a: 'Toast mit Erdnussbutter und Essiggurken essen',
    b: 'Toast mit Nutella und Thunfisch essen',
    aEn: 'eat toast with peanut butter and pickles',
    bEn: 'eat toast with Nutella and tuna',
  },
  {
    a: 'Fruchtgummis voller Fusseln aus einer Jackentasche essen',
    b: 'ein Pfefferminz essen, das wochenlang lose in einer Handtasche lag',
    aEn: 'eat fluff-covered gummies from a coat pocket',
    bEn: 'eat a mint that rolled around loose in a handbag for weeks',
  },
  {
    a: 'ein Osterei essen, das seit Ostern versteckt war',
    b: 'ein Weihnachtsplätzchen essen, das im Juli hinter dem Sofa lag',
    aEn: 'eat an Easter egg that’s been hidden since Easter',
    bEn: 'eat a Christmas cookie found behind the sofa in July',
  },
  {
    a: 'Bohnen aus einer Dose essen, die seit einer Woche offen im Kühlschrank steht',
    b: 'Reis essen, der seit drei Tagen auf dem Herd steht',
    aEn: 'eat beans from a tin that’s been open in the fridge for a week',
    bEn: 'eat rice that’s been sitting on the stove for three days',
  },
  {
    a: 'Popcorn vom Kinoboden essen',
    b: 'Pommes vom Boden eines Fast-Food-Ladens essen',
    aEn: 'eat popcorn off a cinema floor',
    bEn: 'eat fries off the floor of a fast food place',
  },
  {
    a: 'eine ganze Sardine mit Kopf essen',
    b: 'eine ganze Garnele mit Schale und Fühlern essen',
    aEn: 'eat a whole sardine, head and all',
    bEn: 'eat a whole prawn, shell and feelers and all',
  },
  {
    a: 'Bier aus einem getragenen Turnschuh trinken',
    b: 'Sekt aus einem alten Gummistiefel trinken',
    aEn: 'drink beer out of a worn trainer',
    bEn: 'drink sparkling wine out of an old welly',
  },
  {
    a: 'abgestandenes Bier vom Vorabend trinken, in dem eine Kippe schwimmt',
    b: 'einen Schluck aus dem Glas nehmen, in das alle auf der Party ihre Reste gekippt haben',
    aEn: 'drink last night’s flat beer with a cigarette butt in it',
    bEn: 'take a sip from the glass everyone at the party poured their leftovers into',
  },
  {
    a: 'einen Monat lang nicht die Haare waschen',
    b: 'ein halbes Jahr lang dieselbe Bettwäsche benutzen',
    aEn: 'not wash your hair for a month',
    bEn: 'use the same bedding for six months',
  },
  {
    a: 'immer ein Handtuch benutzen, das nie richtig trocknet',
    b: 'immer ein Handtuch benutzen, das schon jemand anderes benutzt hat',
    aEn: 'always use a towel that never fully dries',
    bEn: 'always use a towel someone else already used',
  },
  {
    a: 'nach dem Sport ungeduscht in einem vollen Bus stehen',
    b: 'im vollen Bus unter der Achsel eines verschwitzten Fremden stehen',
    aEn: 'stand on a packed bus unshowered after a workout',
    bEn: 'stand under a sweaty stranger’s armpit on a packed bus',
  },
  {
    a: 'die getragene Kontaktlinse eines Freundes einsetzen',
    b: 'den angefangenen Lippenpflegestift eines Fremden benutzen',
    aEn: 'put in a friend’s worn contact lens',
    bEn: 'use a stranger’s used lip balm',
  },
  {
    a: 'die ungeputzten In-Ear-Kopfhörer eines Fremden benutzen',
    b: 'auf der Mundharmonika eines Fremden spielen',
    aEn: 'use a stranger’s uncleaned earbuds',
    bEn: 'play a stranger’s harmonica',
  },
  {
    a: 'auf einer Autobahntoilette ohne Klopapier festsitzen',
    b: 'auf einer Autobahntoilette ohne funktionierende Spülung festsitzen',
    aEn: 'be stuck in a motorway toilet with no toilet paper',
    bEn: 'be stuck in a motorway toilet with a broken flush',
  },
  {
    a: 'einem Fremden die Brotkrümel aus dem Bart picken',
    b: 'einem Fremden die Schuppen von der Schulter wischen',
    aEn: 'pick the breadcrumbs out of a stranger’s beard',
    bEn: 'brush the dandruff off a stranger’s shoulder',
  },
  {
    a: 'dir von jemand anderem die Ohren putzen lassen',
    b: 'jemand anderem die Ohren putzen',
    aEn: 'let someone else clean your ears',
    bEn: 'clean someone else’s ears',
  },
  {
    a: 'die Hornhaut eines Fremden abraspeln',
    b: 'dir die Füße von hundert Knabberfischen abknabbern lassen',
    aEn: 'file off a stranger’s calluses',
    bEn: 'let a hundred fish nibble the skin off your feet',
  },
  {
    a: 'den Bauchnabel deines besten Freundes sauber machen',
    b: 'die Zehenzwischenräume deines besten Freundes sauber machen',
    aEn: 'clean your best friend’s belly button',
    bEn: 'clean between your best friend’s toes',
  },
  {
    a: 'die Pickel deines besten Freundes ausdrücken',
    b: 'deinen besten Freund deine Pickel ausdrücken lassen',
    aEn: 'squeeze your best friend’s pimples',
    bEn: 'let your best friend squeeze your pimples',
  },
  {
    a: 'eine Vogelspinne über dein Gesicht krabbeln lassen',
    b: 'eine Kakerlake über deinen Hals krabbeln lassen',
    aEn: 'let a tarantula crawl across your face',
    bEn: 'let a cockroach crawl across your neck',
  },
  {
    a: 'einen Blutegel eine Minute an deinem Arm saugen lassen',
    b: 'eine vollgesogene Zecke selbst aus deinem Bauch ziehen',
    aEn: 'let a leech suck on your arm for a minute',
    bEn: 'pull a fully bloated tick out of your own stomach',
  },
  {
    a: 'Ameisen in deinem Müsli entdecken, als du es schon halb gegessen hast',
    b: 'Mehlmotten im Mehl entdecken, als der Kuchen schon im Ofen ist',
    aEn: 'spot ants in your cereal when you’re halfway through',
    bEn: 'spot flour moths in the flour when the cake is already in the oven',
  },
  {
    a: 'einen Fisch mit bloßen Händen ausnehmen',
    b: 'ein rohes Hähnchen mit bloßen Händen ausnehmen',
    aEn: 'gut a fish with your bare hands',
    bEn: 'clean out a raw chicken with your bare hands',
  },
  {
    a: 'Taubenkacke auf den Kopf bekommen',
    b: 'Möwenkacke auf dein Brötchen bekommen',
    aEn: 'get pigeon poo on your head',
    bEn: 'get seagull poo on your sandwich',
  },
  {
    a: 'einen Hundehaufen mit einer löchrigen Tüte aufheben',
    b: 'ein Katzenklo mit einem Teelöffel sauber machen',
    aEn: 'pick up dog poo with a bag that has a hole in it',
    bEn: 'clean a litter box with a teaspoon',
  },
  {
    a: 'ein Auto fahren, in dem irgendwo ein Fisch verwest',
    b: 'in einem Zimmer schlafen, in dem hinter der Wand eine tote Maus liegt',
    aEn: 'drive a car with a fish rotting somewhere inside',
    bEn: 'sleep in a room with a dead mouse behind the wall',
  },
  {
    a: 'eine Gesichtsmaske aus Schneckenschleim tragen',
    b: 'eine Haarkur aus rohem Ei und Bier machen',
    aEn: 'wear a snail slime face mask',
    bEn: 'do a hair treatment with raw egg and beer',
  },
  {
    a: 'zehn Minuten mit jemandem im Aufzug feststecken, der gerade gepupst hat',
    b: 'zehn Minuten mit jemandem im Aufzug feststecken, der eine Dose Thunfisch isst',
    aEn: 'be stuck in a lift for ten minutes with someone who just farted',
    bEn: 'be stuck in a lift for ten minutes with someone eating a tin of tuna',
  },
  {
    a: 'eine Woche direkt neben einer Kläranlage wohnen',
    b: 'eine Woche direkt neben einer Schweinefarm wohnen',
    aEn: 'live right next to a sewage plant for a week',
    bEn: 'live right next to a pig farm for a week',
  },
  {
    a: 'eine Stunde in einer Umkleide nach dem Fußballspiel sitzen',
    b: 'eine Stunde in einem überfüllten Fanbus im Hochsommer sitzen',
    aEn: 'sit in a changing room after a football match for an hour',
    bEn: 'sit on a packed fan bus in midsummer for an hour',
  },
  {
    a: 'in einer Wohnung leben, die immer nach nassem Hund riecht',
    b: 'in einer Wohnung leben, die immer nach altem Frittierfett riecht',
    aEn: 'live in a flat that always smells of wet dog',
    bEn: 'live in a flat that always smells of old frying oil',
  },
  {
    a: 'beim ersten Date aus Versehen laut rülpsen',
    b: 'beim ersten Date aus Versehen hörbar pupsen',
    aEn: 'accidentally burp loudly on a first date',
    bEn: 'accidentally fart audibly on a first date',
  },
  {
    a: 'deinem Chef beim Reden aus Versehen ins Gesicht spucken',
    b: 'deinem Chef aus Versehen auf den Teller niesen',
    aEn: 'accidentally spit in your boss’s face while talking',
    bEn: 'accidentally sneeze on your boss’s plate',
  },
  {
    a: 'abends merken, dass du den ganzen Tag einen Popel an der Nase hattest',
    b: 'abends merken, dass dir den ganzen Tag Klopapier am Schuh hing',
    aEn: 'realise in the evening you had a bogey on your nose all day',
    bEn: 'realise in the evening you had toilet paper stuck to your shoe all day',
  },
  {
    a: 'bei den Schwiegereltern ein Haar in der Suppe finden und weiteressen',
    b: 'bei den Schwiegereltern das Klo verstopfen und es beichten',
    aEn: 'find a hair in your soup at your in-laws’ and keep eating',
    bEn: 'clog the toilet at your in-laws’ and confess it',
  },
  {
    a: 'barfuß durch einen Raum voller Wackelpudding laufen',
    b: 'barfuß durch einen Raum voller kalter, nasser Spaghetti laufen',
    aEn: 'walk barefoot through a room full of jelly',
    bEn: 'walk barefoot through a room full of cold, wet spaghetti',
  },
  {
    a: 'eine Schüssel schleimige Okra essen',
    b: 'eine Schüssel fadenziehendes Natto essen',
    aEn: 'eat a bowl of slimy okra',
    bEn: 'eat a bowl of stringy natto',
  },
  {
    a: 'zehn rohe Austern hintereinander schlürfen',
    b: 'ein Glas rohes Eiweiß in einem Zug trinken',
    aEn: 'slurp ten raw oysters in a row',
    bEn: 'down a glass of raw egg whites in one go',
  },
  {
    a: 'nur noch matschige, aufgeweichte Cornflakes essen',
    b: 'nur noch labbrige, kalte Pommes essen',
    aEn: 'only ever eat soggy cornflakes',
    bEn: 'only ever eat limp, cold fries',
  },
  {
    a: 'in nassen Klamotten schlafen',
    b: 'in einem Bett voller Sand und Krümel schlafen',
    aEn: 'sleep in wet clothes',
    bEn: 'sleep in a bed full of sand and crumbs',
  },
  {
    a: 'eine Stunde lang Kreide auf einer Tafel quietschen hören',
    b: 'eine Stunde lang jemandem beim Fingernägelkauen zuhören',
    aEn: 'listen to chalk squeaking on a blackboard for an hour',
    bEn: 'listen to someone biting their nails for an hour',
  },
  {
    a: 'im Zug neben jemandem sitzen, der seine Fußnägel schneidet',
    b: 'im Zug neben jemandem sitzen, der ein hartgekochtes Ei pellt und isst',
    aEn: 'sit next to someone on a train who’s clipping their toenails',
    bEn: 'sit next to someone on a train peeling and eating a boiled egg',
  },
  {
    a: 'ein Wochenende in einem Zimmer mit einem Schimmelfleck an der Decke schlafen',
    b: 'ein Wochenende in einem Zimmer mit tropfendem Kondenswasser an den Fenstern schlafen',
    aEn: 'sleep a weekend in a room with a mold patch on the ceiling',
    bEn: 'sleep a weekend in a room with condensation dripping off the windows',
  },
  {
    a: 'die Fusseln aus dem Trockner eines Fremden mit der Hand rausholen',
    b: 'die verstopfte Spülmaschine eines Fremden mit der Hand leeren',
    aEn: 'pull the lint out of a stranger’s dryer by hand',
    bEn: 'empty a stranger’s clogged dishwasher by hand',
  },
  {
    a: 'jeden Tag ein Haarknäuel aus deinem Essen ziehen',
    b: 'jeden Tag eine Wimper in deinem Auge haben, die nicht rausgeht',
    aEn: 'pull a hairball out of your food every day',
    bEn: 'have an eyelash stuck in your eye every day that won’t come out',
  },
  {
    a: 'einen Mund voll Meerwasser mit Algen schlucken',
    b: 'einen Mund voll Schwimmbadwasser aus dem Kinderbecken schlucken',
    aEn: 'swallow a mouthful of seawater with seaweed in it',
    bEn: 'swallow a mouthful of water from the kiddie pool',
  },
  {
    a: 'eine Woche lang Zahnbelag haben, den jeder sieht',
    b: 'eine Woche lang gelbe Fingernägel haben, die jeder sieht',
    aEn: 'have plaque on your teeth everyone can see for a week',
    bEn: 'have yellow fingernails everyone can see for a week',
  },
  {
    a: 'einen Tag lang die getragenen Socken deines Mitbewohners anziehen',
    b: 'einen Tag lang aus der ungespülten Tasse deines Mitbewohners trinken',
    aEn: 'wear your flatmate’s worn socks for a day',
    bEn: 'drink from your flatmate’s unwashed mug for a day',
  },
  {
    a: 'eine Rolle Klopapier aus einer Pfütze fischen und benutzen',
    b: 'Zeitungspapier als Klopapier benutzen',
    aEn: 'fish a roll of toilet paper out of a puddle and use it',
    bEn: 'use newspaper as toilet paper',
  },
  {
    a: 'Nacktschnecken aus deinem Gemüsebeet mit der Hand absammeln',
    b: 'Raupen von deinen Rosen mit der Hand absammeln',
    aEn: 'pick slugs off your vegetable patch by hand',
    bEn: 'pick caterpillars off your roses by hand',
  },
  {
    a: 'das Erbrochene eines anderen aufwischen',
    b: 'ein verstopftes Klo mit der Hand freimachen',
    aEn: 'mop up someone else’s sick',
    bEn: 'unclog a toilet with your hand',
  },
  {
    a: 'vor allen anderen eine Spinne aus deinem Kragen holen müssen',
    b: 'vor allen anderen eine Wespe aus deinem Ärmel schütteln müssen',
    aEn: 'have to fish a spider out of your collar in front of everyone',
    bEn: 'have to shake a wasp out of your sleeve in front of everyone',
  },
  {
    a: 'einen Teller Spaghetti essen, der aussieht wie Würmer',
    b: 'einen Teller Würmer essen, die aussehen wie Spaghetti',
    aEn: 'eat a plate of spaghetti that looks like worms',
    bEn: 'eat a plate of worms that look like spaghetti',
  },
  {
    a: 'eine Woche lang nur Essen aus dem Mülleimer der Kantine essen',
    b: 'eine Woche lang nur Essen vom Vortag aus dem Imbiss essen',
    aEn: 'only eat food from the canteen bin for a week',
    bEn: 'only eat yesterday’s leftovers from a takeaway for a week',
  },
  {
    a: 'die Fischabfälle auf einem Fischmarkt einsammeln',
    b: 'die Essensreste nach einem Kindergeburtstag aufräumen',
    aEn: 'collect the fish scraps at a fish market',
    bEn: 'clean up the food mess after a kids’ birthday party',
  },
  {
    a: 'immer eine Jacke tragen, die nach Raucherkneipe riecht',
    b: 'immer eine Jacke tragen, die nach Hallenbad-Umkleide riecht',
    aEn: 'always wear a jacket that smells like a smoky pub',
    bEn: 'always wear a jacket that smells like a pool changing room',
  },
  {
    a: 'nach dem Schwimmbad merken, dass jemand in deinen Schuh gespuckt hat',
    b: 'nach dem Schwimmbad merken, dass du fremde Badelatschen anhast',
    aEn: 'find out after swimming that someone spat in your shoe',
    bEn: 'find out after swimming that you’re wearing a stranger’s flip-flops',
  },
  {
    a: 'in einen Apfel beißen und eine halbe Raupe sehen',
    b: 'in ein Brötchen beißen und einen Schimmelfleck sehen',
    aEn: 'bite into an apple and see half a caterpillar',
    bEn: 'bite into a bread roll and see a patch of mold',
  },
  {
    a: 'einmal am Tag laut schniefen müssen, ohne dir die Nase putzen zu dürfen',
    b: 'einmal am Tag laut die Nase hochziehen und runterschlucken müssen',
    aEn: 'have to sniff loudly once a day without blowing your nose',
    bEn: 'have to snort loudly and swallow it once a day',
  },
  {
    a: 'ein Taschentuch benutzen, das schon jemand benutzt hat',
    b: 'dir die Nase mit deinem eigenen Ärmel putzen, vor allen Leuten',
    aEn: 'use a tissue someone already used',
    bEn: 'wipe your nose on your own sleeve in front of everyone',
  },
  {
    a: 'ein Jahr lang in einer Wohnung mit Silberfischen im Bad leben',
    b: 'ein Jahr lang in einer Wohnung mit Spinnen in jeder Ecke leben',
    aEn: 'live for a year in a flat with silverfish in the bathroom',
    bEn: 'live for a year in a flat with spiders in every corner',
  },
  {
    a: 'einen Gurkensaft-Shot mit rohem Eigelb trinken',
    b: 'einen Shot aus Fischsoße und Zitrone trinken',
    aEn: 'drink a pickle juice shot with a raw egg yolk',
    bEn: 'drink a shot of fish sauce and lemon',
  },
  {
    a: 'jeden Morgen mit Sabber auf dem Kissen aufwachen',
    b: 'jeden Morgen mit verklebten Augen aufwachen',
    aEn: 'wake up with drool on your pillow every morning',
    bEn: 'wake up with crusty eyes every morning',
  },
  {
    a: 'einen Monat lang jeden Tag dein Mittagessen mit einer Wespe teilen',
    b: 'einen Monat lang jeden Tag dein Frühstück mit einer Fliege teilen',
    aEn: 'share your lunch with a wasp every day for a month',
    bEn: 'share your breakfast with a fly every day for a month',
  },
  {
    a: 'eine verschimmelte Kaffeetasse aus dem Büro abwaschen',
    b: 'eine vergessene Thermoskanne mit Milchkaffee öffnen',
    aEn: 'wash up a moldy coffee mug from the office',
    bEn: 'open a forgotten thermos of milky coffee',
  },
  {
    a: 'in einem Restaurant essen, in dem du gerade eine Maus gesehen hast',
    b: 'in einem Restaurant essen, dessen Küche du gerade gesehen hast',
    aEn: 'eat at a restaurant where you just saw a mouse',
    bEn: 'eat at a restaurant whose kitchen you just saw',
  },
  {
    a: 'ein Glas Milch mit einem Klecks Senf trinken',
    b: 'ein Glas Cola mit einem Löffel Mayo trinken',
    aEn: 'drink a glass of milk with a dollop of mustard',
    bEn: 'drink a glass of cola with a spoonful of mayo',
  },
  {
    a: 'blind in eine Schüssel geschälter Weintrauben greifen',
    b: 'blind in eine Schüssel kalter, glibberiger Nudeln greifen',
    aEn: 'reach blindfolded into a bowl of peeled grapes',
    bEn: 'reach blindfolded into a bowl of cold, slimy noodles',
  },
  {
    a: 'nie wieder Nasenhaare schneiden dürfen',
    b: 'nie wieder Ohrenhaare schneiden dürfen',
    aEn: 'never be allowed to trim your nose hair again',
    bEn: 'never be allowed to trim your ear hair again',
  },
  {
    a: 'jeden Tag eine Stunde lang den Kaugummi von Gehwegen kratzen',
    b: 'jeden Tag eine Stunde lang Taubenkacke von Denkmälern schrubben',
    aEn: 'scrape gum off pavements for an hour every day',
    bEn: 'scrub pigeon poo off monuments for an hour every day',
  },
  {
    a: 'dein Lieblingskissen nie wieder waschen dürfen',
    b: 'deine Lieblingsjeans nie wieder waschen dürfen',
    aEn: 'never be allowed to wash your favourite pillow again',
    bEn: 'never be allowed to wash your favourite jeans again',
  },
  {
    a: 'in einem Hostel schlafen, in dem die Matratze Flecken hat',
    b: 'in einem Hostel schlafen, in dem das Bad keine Tür hat',
    aEn: 'sleep in a hostel with a stained mattress',
    bEn: 'sleep in a hostel where the bathroom has no door',
  },
  {
    a: 'einen Hering roh und im Ganzen herunterschlucken',
    b: 'einen Löffel rohe Leber kauen',
    aEn: 'swallow a whole raw herring',
    bEn: 'chew a spoonful of raw liver',
  },
  {
    a: 'beim Schuheausziehen bei Freunden merken, dass deine Füße stinken',
    b: 'beim Jackeausziehen bei Freunden merken, dass deine Achseln stinken',
    aEn: 'take your shoes off at a friend’s place and realise your feet stink',
    bEn: 'take your jacket off at a friend’s place and realise your armpits stink',
  },
  {
    a: 'beim Kuscheln mit deinem Hund seinen Mundgeruch abbekommen',
    b: 'beim Kuscheln mit deiner Katze ein Haarknäuel abbekommen',
    aEn: 'get a blast of your dog’s bad breath while cuddling',
    bEn: 'get a hairball from your cat while cuddling',
  },
  {
    a: 'eine Woche lang einen Schnupfen haben und keine Taschentücher',
    b: 'eine Woche lang Durchfall haben und nur eine Toilette für zehn Leute',
    aEn: 'have a cold for a week with no tissues',
    bEn: 'have diarrhoea for a week with one toilet for ten people',
  },
  {
    a: 'deine Haare mit einem Kamm aus dem Fundbüro kämmen',
    b: 'deine Ohren mit einem Wattestäbchen aus dem Fundbüro putzen',
    aEn: 'comb your hair with a comb from the lost and found',
    bEn: 'clean your ears with a cotton swab from the lost and found',
  },
  {
    a: 'einen Burger aus Mehlwürmern essen',
    b: 'eine Wurst aus Blut und Innereien essen',
    aEn: 'eat a mealworm burger',
    bEn: 'eat a sausage made of blood and offal',
  },
  {
    a: 'ein Fondue essen, in das alle ihre Gabeln abgeleckt zurückgesteckt haben',
    b: 'eine Bowle trinken, in die alle ihre Finger gesteckt haben',
    aEn: 'eat fondue where everyone dipped their licked forks back in',
    bEn: 'drink punch everyone has stuck their fingers into',
  },
  {
    a: 'die Wohnung eines Messies einen Tag lang aufräumen',
    b: 'die Toiletten einer Autobahnraststätte einen Tag lang putzen',
    aEn: 'clean a hoarder’s home for a day',
    bEn: 'clean the toilets at a motorway service station for a day',
  },
  {
    a: 'einen Schluck aus einer Flasche nehmen und merken, dass ein Zigarettenstummel drin ist',
    b: 'einen Schluck aus einer Dose nehmen und merken, dass eine Wespe drin ist',
    aEn: 'take a swig from a bottle and realise there’s a cigarette butt in it',
    bEn: 'take a swig from a can and realise there’s a wasp in it',
  },
  {
    a: 'beim Zahnarzt sabbernd einschlafen',
    b: 'beim Friseur schnarchend einschlafen',
    aEn: 'fall asleep drooling at the dentist',
    bEn: 'fall asleep snoring at the hairdresser’s',
  },
  {
    a: 'dass immer ein bisschen Rotz an deiner Oberlippe hängt',
    b: 'dass immer ein bisschen Schlaf in deinen Augenwinkeln klebt',
    aEn: 'always have a bit of snot on your upper lip',
    bEn: 'always have a bit of sleep crust in the corners of your eyes',
  },
  {
    a: 'eine Woche lang Zähneputzen mit Wasser aus der Regentonne',
    b: 'eine Woche lang Duschen mit Wasser aus dem Teich',
    aEn: 'brush your teeth with rain barrel water for a week',
    bEn: 'shower with pond water for a week',
  },
  {
    a: 'eine Schnecke mit Gehäuse schlucken',
    b: 'einen Grashüpfer lebend zerkauen',
    aEn: 'swallow a snail, shell and all',
    bEn: 'chew up a live grasshopper',
  },
  {
    a: 'einen Hund haben, der sich ständig in Aas wälzt',
    b: 'eine Katze haben, die dir tote Mäuse ins Bett legt',
    aEn: 'have a dog that keeps rolling in dead animals',
    bEn: 'have a cat that leaves dead mice in your bed',
  },
  {
    a: 'eine Tasse Tee trinken, in die jemand seinen Finger gesteckt hat',
    b: 'eine Tasse Kaffee trinken, in die jemand reingepustet hat',
    aEn: 'drink a cup of tea someone dipped their finger in',
    bEn: 'drink a cup of coffee someone blew into',
  },
  {
    a: 'den Müllschlucker eines Hochhauses von innen putzen',
    b: 'die Mülltonnen eines Sommerfestivals am letzten Tag leeren',
    aEn: 'clean the inside of a tower block’s rubbish chute',
    bEn: 'empty a summer festival’s bins on the last day',
  },
  {
    a: 'eine Woche mit einem eingewachsenen Zehennagel herumlaufen',
    b: 'eine Woche mit einer offenen Blase an der Ferse herumlaufen',
    aEn: 'walk around for a week with an ingrown toenail',
    bEn: 'walk around for a week with an open blister on your heel',
  },
  {
    a: 'einen Kuchen essen, bei dem der Bäcker in den Teig geniest hat',
    b: 'einen Kuchen essen, bei dem der Bäcker nach dem Klo keine Hände gewaschen hat',
    aEn: 'eat a cake the baker sneezed into the batter of',
    bEn: 'eat a cake made by a baker who didn’t wash after the loo',
  },
  {
    a: 'ein Wochenende bei Freunden schlafen, deren Hund ständig sabbert',
    b: 'ein Wochenende bei Freunden schlafen, deren Katze ständig aufs Bett springt',
    aEn: 'spend a weekend with friends whose dog drools constantly',
    bEn: 'spend a weekend with friends whose cat keeps jumping on the bed',
  },
  {
    a: 'in einem Raum voller Leute, die Zwiebelmett essen, eingesperrt sein',
    b: 'in einem Raum voller Leute, die Harzer Käse essen, eingesperrt sein',
    aEn: 'be locked in a room full of people eating raw onion mince',
    bEn: 'be locked in a room full of people eating stinky Harz cheese',
  },
  {
    a: 'eine Socke aus dem Wäschekorb einer Sporthalle über deine Hand ziehen',
    b: 'einen Handschuh aus dem Fundbüro eines Schwimmbads anziehen',
    aEn: 'pull a sock from a sports hall’s laundry basket over your hand',
    bEn: 'put on a glove from a swimming pool’s lost and found',
  },
  {
    a: 'Gummibärchen essen, die nach Fisch schmecken',
    b: 'Fischstäbchen essen, die nach Gummibärchen schmecken',
    aEn: 'eat gummy bears that taste of fish',
    bEn: 'eat fish fingers that taste of gummy bears',
  },
  {
    a: 'einen Saft trinken, in dem dicke Fruchtfleischklumpen schwimmen',
    b: 'einen Bubble Tea trinken, dessen Perlen sich wie Fischaugen anfühlen',
    aEn: 'drink juice with big lumps of pulp floating in it',
    bEn: 'drink bubble tea whose pearls feel like fish eyes',
  },
  {
    a: 'dein Gesicht in eine Schüssel kalten Grießbrei drücken',
    b: 'dein Gesicht in eine Schüssel warmen Hüttenkäse drücken',
    aEn: 'press your face into a bowl of cold semolina pudding',
    bEn: 'press your face into a bowl of warm cottage cheese',
  },
  {
    a: 'beim Grillen eine Wurst essen, die vorher in den Kohlen lag',
    b: 'beim Grillen eine Wurst essen, an der eine Wespe saß',
    aEn: 'eat a barbecue sausage that fell in the coals',
    bEn: 'eat a barbecue sausage a wasp was sitting on',
  },
  {
    a: 'jeden Abend mit Kindern Lausekontrolle machen',
    b: 'jeden Abend in einer Jugendherberge die Duschen kontrollieren',
    aEn: 'check kids for lice every evening',
    bEn: 'inspect the showers at a youth hostel every evening',
  },
  {
    a: 'eine Woche lang die Toilette nicht spülen können',
    b: 'eine Woche lang ohne warmes Wasser abwaschen müssen',
    aEn: 'be unable to flush the toilet for a week',
    bEn: 'have to do the washing up without hot water for a week',
  },
  {
    a: 'einen Mitbewohner haben, der nie abwäscht',
    b: 'einen Mitbewohner haben, der nie die Klotür zumacht',
    aEn: 'have a flatmate who never does the dishes',
    bEn: 'have a flatmate who never closes the toilet door',
  },
];
