import type { WouldYouRatherSeed } from './types';

export const normalQuestions: WouldYouRatherSeed[] = [
  {
    a: 'nur noch ungewürztes Essen essen',
    b: 'alles nur noch mit Ketchup essen müssen',
    aEn: 'only eat unseasoned food',
    bEn: 'have to eat everything with ketchup',
  },
  {
    a: 'für immer auf Pizza verzichten',
    b: 'für immer auf Pasta verzichten',
    aEn: 'give up pizza forever',
    bEn: 'give up pasta forever',
  },
  {
    a: 'jeden Tag dasselbe Frühstück essen',
    b: 'nie wieder frühstücken',
    aEn: 'eat the same breakfast every day',
    bEn: 'never eat breakfast again',
  },
  {
    a: 'nur noch mit Stäbchen essen',
    b: 'nur noch mit einem Löffel essen',
    aEn: 'only eat with chopsticks',
    bEn: 'only eat with a spoon',
  },
  {
    a: 'nie wieder Käse essen',
    b: 'nie wieder Brot essen',
    aEn: 'never eat cheese again',
    bEn: 'never eat bread again',
  },
  {
    a: 'jedes Getränk nur noch lauwarm trinken',
    b: 'jedes Getränk nur noch eiskalt trinken',
    aEn: 'drink everything lukewarm',
    bEn: 'drink everything ice cold',
  },
  {
    a: 'immer kochen, aber nie abwaschen müssen',
    b: 'nie kochen, aber immer abwaschen müssen',
    aEn: 'always cook but never have to do the dishes',
    bEn: 'never cook but always have to do the dishes',
  },
  {
    a: 'zum Frühstück nur noch Süßes essen',
    b: 'zum Frühstück nur noch Herzhaftes essen',
    aEn: 'only eat sweet things for breakfast',
    bEn: 'only eat savory things for breakfast',
  },
  {
    a: 'nie wieder ins Restaurant gehen',
    b: 'nie wieder selbst kochen',
    aEn: 'never go to a restaurant again',
    bEn: 'never cook for yourself again',
  },
  {
    a: 'eine Woche lang nur Suppe essen',
    b: 'eine Woche lang nur Salat essen',
    aEn: 'eat only soup for a week',
    bEn: 'eat only salad for a week',
  },
  {
    a: 'dein Lieblingsessen nie wieder essen',
    b: 'nur noch dein Lieblingsessen essen',
    aEn: 'never eat your favorite food again',
    bEn: 'only ever eat your favorite food',
  },
  {
    a: 'jeden Morgen frische Brötchen vor der Tür haben',
    b: 'jeden Abend ein fertig gekochtes Essen bekommen',
    aEn: 'find fresh bread rolls at your door every morning',
    bEn: 'get a home-cooked dinner every evening',
  },
  {
    a: 'nie wieder Eis essen',
    b: 'nie wieder Pommes essen',
    aEn: 'never eat ice cream again',
    bEn: 'never eat fries again',
  },
  {
    a: 'Popcorn nur noch salzig essen',
    b: 'Popcorn nur noch süß essen',
    aEn: 'only eat salty popcorn',
    bEn: 'only eat sweet popcorn',
  },
  {
    a: 'jede Mahlzeit allein essen',
    b: 'jede Mahlzeit mit Fremden teilen',
    aEn: 'eat every meal alone',
    bEn: 'share every meal with strangers',
  },
  {
    a: 'ein Jahr lang vegan leben',
    b: 'ein Jahr lang keinen Alkohol trinken',
    aEn: 'live vegan for a year',
    bEn: 'not drink alcohol for a year',
  },
  {
    a: 'als Wasser nur noch stilles trinken',
    b: 'als Wasser nur noch Sprudel trinken',
    aEn: 'only drink still water',
    bEn: 'only drink sparkling water',
  },
  {
    a: 'jeden Tag Reis essen',
    b: 'jeden Tag Kartoffeln essen',
    aEn: 'eat rice every day',
    bEn: 'eat potatoes every day',
  },
  {
    a: 'nie wieder Knoblauch essen',
    b: 'nie wieder Zwiebeln essen',
    aEn: 'never eat garlic again',
    bEn: 'never eat onions again',
  },
  {
    a: 'beim Lieferdienst immer zu viel bestellen',
    b: 'beim Lieferdienst immer zu wenig bestellen',
    aEn: 'always order too much food for delivery',
    bEn: 'always order too little food for delivery',
  },
  {
    a: 'nur noch mit dem Zug reisen',
    b: 'nur noch mit dem Auto reisen',
    aEn: 'only travel by train',
    bEn: 'only travel by car',
  },
  {
    a: 'einen Monat in einer Berghütte ohne Internet verbringen',
    b: 'einen Monat auf einem Kreuzfahrtschiff verbringen',
    aEn: 'spend a month in a mountain hut without internet',
    bEn: 'spend a month on a cruise ship',
  },
  {
    a: 'jedes Jahr an denselben Urlaubsort fahren',
    b: 'nie zweimal an denselben Ort reisen dürfen',
    aEn: 'go to the same vacation spot every year',
    bEn: 'never be allowed to visit the same place twice',
  },
  {
    a: 'nur noch Strandurlaub machen',
    b: 'nur noch Städtetrips machen',
    aEn: 'only take beach vacations',
    bEn: 'only take city trips',
  },
  {
    a: 'auf jedem Flug den Mittelsitz bekommen',
    b: 'auf jedem Flug neben einem schreienden Baby sitzen',
    aEn: 'get the middle seat on every flight',
    bEn: 'sit next to a screaming baby on every flight',
  },
  {
    a: 'eine Weltreise allein machen',
    b: 'eine Weltreise mit deinen Eltern machen',
    aEn: 'travel the world alone',
    bEn: 'travel the world with your parents',
  },
  {
    a: 'im Urlaub nur noch zelten',
    b: 'im Urlaub nur noch in Hostels schlafen',
    aEn: 'only go camping on vacation',
    bEn: 'only stay in hostels on vacation',
  },
  {
    a: 'jeden Urlaub bis ins Detail durchplanen müssen',
    b: 'jeden Urlaub komplett spontan antreten müssen',
    aEn: 'have to plan every vacation down to the last detail',
    bEn: 'have to go on every vacation completely unplanned',
  },
  {
    a: 'nie wieder ins Ausland reisen',
    b: 'nie wieder im eigenen Land verreisen',
    aEn: 'never travel abroad again',
    bEn: 'never travel within your own country again',
  },
  {
    a: 'bei jeder Reise dein Gepäck verlieren',
    b: 'bei jeder Reise fünf Stunden Verspätung haben',
    aEn: 'lose your luggage on every trip',
    bEn: 'be delayed five hours on every trip',
  },
  {
    a: 'nur noch im Winter Urlaub machen',
    b: 'nur noch im Sommer Urlaub machen',
    aEn: 'only go on vacation in winter',
    bEn: 'only go on vacation in summer',
  },
  {
    a: 'ein Jahr im Ausland leben, ohne die Sprache zu sprechen',
    b: 'ein Jahr lang deine Heimatstadt nicht verlassen',
    aEn: 'live abroad for a year without speaking the language',
    bEn: 'not leave your hometown for a year',
  },
  {
    a: 'mit dem Fahrrad durch Europa fahren',
    b: 'mit dem Wohnmobil durch Amerika fahren',
    aEn: 'cycle across Europe',
    bEn: 'drive across America in an RV',
  },
  {
    a: 'jede Reise im Nachtzug antreten',
    b: 'jede Reise mit einem Billigflieger um 6 Uhr morgens antreten',
    aEn: 'start every trip on a night train',
    bEn: 'start every trip on a 6 a.m. budget flight',
  },
  {
    a: 'im Urlaub keine Fotos machen dürfen',
    b: 'niemandem von deinem Urlaub erzählen dürfen',
    aEn: 'not be allowed to take photos on vacation',
    bEn: 'not be allowed to tell anyone about your vacation',
  },
  {
    a: 'jeden Urlaub mit 20 Leuten verbringen',
    b: 'jeden Urlaub ganz allein verbringen',
    aEn: 'spend every vacation with 20 people',
    bEn: 'spend every vacation completely alone',
  },
  {
    a: 'in einer riesigen Wohnung am Stadtrand wohnen',
    b: 'in einer winzigen Wohnung mitten in der Stadt wohnen',
    aEn: 'live in a huge apartment on the edge of town',
    bEn: 'live in a tiny apartment right in the city center',
  },
  {
    a: 'nie wieder umziehen dürfen',
    b: 'jedes Jahr umziehen müssen',
    aEn: 'never be allowed to move again',
    bEn: 'have to move every year',
  },
  {
    a: 'in einer WG mit fünf Leuten wohnen',
    b: 'allein auf einem abgelegenen Bauernhof wohnen',
    aEn: 'live in a shared flat with five people',
    bEn: 'live alone on a remote farm',
  },
  {
    a: 'eine Wohnung ohne Waschmaschine haben',
    b: 'eine Wohnung ohne Spülmaschine haben',
    aEn: 'have an apartment without a washing machine',
    bEn: 'have an apartment without a dishwasher',
  },
  {
    a: 'im fünften Stock ohne Aufzug wohnen',
    b: 'im Erdgeschoss direkt an einer Hauptstraße wohnen',
    aEn: 'live on the fifth floor with no elevator',
    bEn: 'live on the ground floor right on a busy road',
  },
  {
    a: 'Nachbarn haben, die jede Nacht Party machen',
    b: 'Nachbarn haben, die sich über jedes Geräusch beschweren',
    aEn: 'have neighbors who party every night',
    bEn: 'have neighbors who complain about every noise',
  },
  {
    a: 'ein Haus mit Garten haben und eine Stunde pendeln',
    b: 'in einer kleinen Wohnung fünf Minuten von der Arbeit wohnen',
    aEn: 'have a house with a garden and a one-hour commute',
    bEn: 'live in a small apartment five minutes from work',
  },
  {
    a: 'in einem Leuchtturm wohnen',
    b: 'auf einem Hausboot wohnen',
    aEn: 'live in a lighthouse',
    bEn: 'live on a houseboat',
  },
  {
    a: 'nie wieder putzen müssen',
    b: 'nie wieder Wäsche waschen müssen',
    aEn: 'never have to clean again',
    bEn: 'never have to do laundry again',
  },
  {
    a: 'eine Wohnung mit perfekter Aussicht haben',
    b: 'eine Wohnung in perfekter Lage haben',
    aEn: 'have an apartment with a perfect view',
    bEn: 'have an apartment in a perfect location',
  },
  {
    a: 'in einem Dorf wohnen, in dem dich jeder kennt',
    b: 'in einer Großstadt wohnen, in der dich niemand kennt',
    aEn: 'live in a village where everyone knows you',
    bEn: 'live in a big city where nobody knows you',
  },
  {
    a: 'in einer Wohnung leben, die immer zu warm ist',
    b: 'in einer Wohnung leben, die immer zu kalt ist',
    aEn: 'live in an apartment that’s always too warm',
    bEn: 'live in an apartment that’s always too cold',
  },
  {
    a: 'für immer ohne Kissen schlafen',
    b: 'für immer ohne Bettdecke schlafen',
    aEn: 'sleep without a pillow forever',
    bEn: 'sleep without a blanket forever',
  },
  {
    a: 'deine Wohnung komplett weiß einrichten',
    b: 'deine Wohnung komplett knallbunt einrichten',
    aEn: 'furnish your home entirely in white',
    bEn: 'furnish your home in loud, bright colors',
  },
  {
    a: 'jeden Tag um 5 Uhr aufstehen',
    b: 'jeden Tag erst um 2 Uhr nachts ins Bett gehen',
    aEn: 'get up at 5 a.m. every day',
    bEn: 'go to bed at 2 a.m. every night',
  },
  {
    a: 'nie wieder verschlafen',
    b: 'nie wieder deinen Schlüssel verlegen',
    aEn: 'never oversleep again',
    bEn: 'never misplace your keys again',
  },
  {
    a: 'jeden Tag 10.000 Schritte gehen müssen',
    b: 'jeden Tag 30 Minuten meditieren müssen',
    aEn: 'have to walk 10,000 steps every day',
    bEn: 'have to meditate for 30 minutes every day',
  },
  {
    a: 'immer zehn Minuten zu früh kommen',
    b: 'immer zehn Minuten zu spät kommen',
    aEn: 'always arrive ten minutes early',
    bEn: 'always arrive ten minutes late',
  },
  {
    a: 'nur noch kalt duschen',
    b: 'nur noch zwei Minuten lang duschen dürfen',
    aEn: 'only take cold showers',
    bEn: 'only be allowed two-minute showers',
  },
  {
    a: 'nie wieder einen Mittagsschlaf machen',
    b: 'nie wieder ausschlafen',
    aEn: 'never take a nap again',
    bEn: 'never sleep in again',
  },
  {
    a: 'jeden Abend Tagebuch schreiben müssen',
    b: 'jeden Morgen Sport machen müssen',
    aEn: 'have to write in a journal every evening',
    bEn: 'have to work out every morning',
  },
  {
    a: 'dein Handy nur noch eine Stunde am Tag benutzen dürfen',
    b: 'nur noch ein Handy ohne Internet haben',
    aEn: 'only be allowed to use your phone one hour a day',
    bEn: 'only have a phone without internet',
  },
  {
    a: 'immer alles sofort erledigen',
    b: 'immer alles auf den letzten Drücker machen',
    aEn: 'always get everything done right away',
    bEn: 'always do everything at the last minute',
  },
  {
    a: 'nie wieder Nachrichten lesen',
    b: 'nie wieder Social Media nutzen',
    aEn: 'never read the news again',
    bEn: 'never use social media again',
  },
  {
    a: 'nur noch Sprachnachrichten bekommen',
    b: 'nur noch Anrufe bekommen',
    aEn: 'only ever get voice messages',
    bEn: 'only ever get phone calls',
  },
  {
    a: 'nie wieder eine E-Mail schreiben',
    b: 'nie wieder telefonieren',
    aEn: 'never write an email again',
    bEn: 'never make a phone call again',
  },
  {
    a: 'jeden Tag dasselbe Outfit tragen',
    b: 'nie zweimal dasselbe Outfit tragen dürfen',
    aEn: 'wear the same outfit every day',
    bEn: 'never be allowed to wear the same outfit twice',
  },
  {
    a: 'immer Socken tragen müssen, auch im Bett',
    b: 'nie wieder Socken tragen dürfen',
    aEn: 'always have to wear socks, even in bed',
    bEn: 'never be allowed to wear socks again',
  },
  {
    a: 'nur noch mit Musik einschlafen können',
    b: 'nur noch in absoluter Stille einschlafen können',
    aEn: 'only be able to fall asleep with music',
    bEn: 'only be able to fall asleep in total silence',
  },
  {
    a: 'mit 4 Stunden Schlaf auskommen, aber immer leicht müde sein',
    b: 'jede Nacht 10 Stunden schlafen müssen, um fit zu sein',
    aEn: 'get by on 4 hours of sleep but always feel a bit tired',
    bEn: 'need 10 hours of sleep every night to feel rested',
  },
  {
    a: 'ein Handy haben, das immer bei 10 Prozent Akku ist',
    b: 'ein Handy mit gesprungenem Display haben',
    aEn: 'have a phone that’s always at 10 percent battery',
    bEn: 'have a phone with a cracked screen',
  },
  {
    a: 'nie wieder Musik über Kopfhörer hören',
    b: 'nie wieder Musik über Lautsprecher hören',
    aEn: 'never listen to music on headphones again',
    bEn: 'never listen to music on speakers again',
  },
  {
    a: 'jedes Mal fünfmal hintereinander niesen',
    b: 'jeden Tag eine Stunde Schluckauf haben',
    aEn: 'sneeze five times in a row every time',
    bEn: 'have hiccups for an hour every day',
  },
  {
    a: 'immer die langsamste Kasse im Supermarkt erwischen',
    b: 'immer den Einkaufswagen mit dem kaputten Rad erwischen',
    aEn: 'always end up in the slowest checkout line',
    bEn: 'always get the shopping cart with the wonky wheel',
  },
  {
    a: 'perfekt Gitarre spielen können',
    b: 'perfekt singen können',
    aEn: 'be able to play guitar perfectly',
    bEn: 'be able to sing perfectly',
  },
  {
    a: 'jede Sprache verstehen, aber nicht sprechen können',
    b: 'jede Sprache sprechen, aber nur mit starkem Akzent',
    aEn: 'understand every language but not speak them',
    bEn: 'speak every language, but only with a heavy accent',
  },
  {
    a: 'nie wieder ein Buch lesen',
    b: 'nie wieder einen Film schauen',
    aEn: 'never read a book again',
    bEn: 'never watch a movie again',
  },
  {
    a: 'jedes Wochenende wandern gehen',
    b: 'jedes Wochenende auf dem Sofa verbringen',
    aEn: 'go hiking every weekend',
    bEn: 'spend every weekend on the couch',
  },
  {
    a: 'ein Profi im Kochen sein',
    b: 'ein Profi im Tanzen sein',
    aEn: 'be a pro at cooking',
    bEn: 'be a pro at dancing',
  },
  {
    a: 'jede Serie nur ein einziges Mal sehen dürfen',
    b: 'nur noch Serien schauen dürfen, die du schon kennst',
    aEn: 'only be allowed to watch each show once',
    bEn: 'only be allowed to watch shows you’ve already seen',
  },
  {
    a: 'nie wieder auf ein Konzert gehen',
    b: 'nie wieder ins Kino gehen',
    aEn: 'never go to a concert again',
    bEn: 'never go to the movies again',
  },
  {
    a: 'Schach auf Weltklasseniveau spielen',
    b: 'Tischtennis auf Weltklasseniveau spielen',
    aEn: 'play chess at a world-class level',
    bEn: 'play table tennis at a world-class level',
  },
  {
    a: 'jedes Brettspiel gewinnen',
    b: 'jedes Quiz gewinnen',
    aEn: 'win every board game',
    bEn: 'win every quiz',
  },
  {
    a: 'malen können wie ein Profi',
    b: 'fotografieren können wie ein Profi',
    aEn: 'paint like a pro',
    bEn: 'take photos like a pro',
  },
  {
    a: 'nur noch Musik aus den 80ern hören',
    b: 'nur noch aktuelle Charts hören',
    aEn: 'only listen to music from the 80s',
    bEn: 'only listen to the current charts',
  },
  {
    a: 'beim Karaoke immer zuerst singen müssen',
    b: 'beim Karaoke nie selbst das Lied aussuchen dürfen',
    aEn: 'always have to sing first at karaoke',
    bEn: 'never get to pick your own song at karaoke',
  },
  {
    a: 'einen Marathon laufen',
    b: 'einen Viertausender besteigen',
    aEn: 'run a marathon',
    bEn: 'climb a 4,000-meter mountain',
  },
  {
    a: 'einen eigenen Gemüsegarten haben',
    b: 'einen eigenen Pool haben',
    aEn: 'have your own vegetable garden',
    bEn: 'have your own pool',
  },
  {
    a: 'nie wieder Videospiele spielen',
    b: 'nie wieder Brettspiele spielen',
    aEn: 'never play video games again',
    bEn: 'never play board games again',
  },
  {
    a: 'perfekt surfen können',
    b: 'perfekt Ski fahren können',
    aEn: 'be able to surf perfectly',
    bEn: 'be able to ski perfectly',
  },
  {
    a: 'ein Buch schreiben',
    b: 'ein Album aufnehmen',
    aEn: 'write a book',
    bEn: 'record an album',
  },
  {
    a: 'in einem Musical mitspielen',
    b: 'als Statist in einem Kinofilm auftauchen',
    aEn: 'perform in a musical',
    bEn: 'appear as an extra in a movie',
  },
  {
    a: 'deine Freizeit nur noch draußen verbringen',
    b: 'deine Freizeit nur noch drinnen verbringen',
    aEn: 'spend all your free time outdoors',
    bEn: 'spend all your free time indoors',
  },
  {
    a: 'jedes Spiel knapp verlieren',
    b: 'jedes Spiel haushoch gewinnen, aber alle sind genervt',
    aEn: 'narrowly lose every game',
    bEn: 'win every game by a landslide, but everyone’s annoyed',
  },
  {
    a: 'für immer nur Jogginghosen tragen',
    b: 'für immer nur schicke Kleidung tragen',
    aEn: 'only wear sweatpants forever',
    bEn: 'only wear fancy clothes forever',
  },
  {
    a: 'immer etwas zu warm angezogen sein',
    b: 'immer etwas zu dünn angezogen sein',
    aEn: 'always be dressed a little too warm',
    bEn: 'always be dressed a little too lightly',
  },
  {
    a: 'ein hässliches, aber super bequemes Sofa haben',
    b: 'ein wunderschönes, aber unbequemes Sofa haben',
    aEn: 'have an ugly but super comfy couch',
    bEn: 'have a gorgeous but uncomfortable couch',
  },
  {
    a: 'nie wieder Schuhe tragen müssen',
    b: 'nie wieder eine Jacke brauchen',
    aEn: 'never have to wear shoes again',
    bEn: 'never need a jacket again',
  },
  {
    a: 'jeden Tag Sonne und 35 Grad haben',
    b: 'jeden Tag 15 Grad und leichten Regen haben',
    aEn: 'have sunshine and 35 degrees every day',
    bEn: 'have 15 degrees and light rain every day',
  },
  {
    a: 'nur noch in einer Hängematte schlafen',
    b: 'nur noch auf einer Matratze auf dem Boden schlafen',
    aEn: 'only sleep in a hammock',
    bEn: 'only sleep on a mattress on the floor',
  },
  {
    a: 'jede Woche eine Massage bekommen',
    b: 'jede Woche eine Putzkraft bekommen',
    aEn: 'get a massage every week',
    bEn: 'get a cleaner every week',
  },
  {
    a: 'nie wieder frieren',
    b: 'nie wieder schwitzen',
    aEn: 'never feel cold again',
    bEn: 'never sweat again',
  },
  {
    a: 'immer einen Sitzplatz in Bus und Bahn bekommen',
    b: 'immer einen Parkplatz direkt vor der Tür finden',
    aEn: 'always get a seat on the bus and train',
    bEn: 'always find a parking spot right outside the door',
  },
  {
    a: 'ein Jahr ohne Sommer erleben',
    b: 'ein Jahr ohne Winter erleben',
    aEn: 'live through a year without summer',
    bEn: 'live through a year without winter',
  },
  {
    a: 'jeden Abend ein warmes Bad nehmen können',
    b: 'jeden Morgen einen perfekten Kaffee serviert bekommen',
    aEn: 'be able to take a warm bath every evening',
    bEn: 'be served a perfect coffee every morning',
  },
  {
    a: 'immer kratzige Pullis tragen',
    b: 'immer zu enge Schuhe tragen',
    aEn: 'always wear itchy sweaters',
    bEn: 'always wear shoes that are too tight',
  },
  {
    a: 'nie wieder Kopfschmerzen haben',
    b: 'nie wieder Muskelkater haben',
    aEn: 'never have a headache again',
    bEn: 'never have sore muscles again',
  },
  {
    a: 'nur noch auf dem Bauch schlafen können',
    b: 'nur noch auf dem Rücken schlafen können',
    aEn: 'only be able to sleep on your stomach',
    bEn: 'only be able to sleep on your back',
  },
  {
    a: 'immer genau wissen, wie spät es ist',
    b: 'immer genau wissen, wo Norden ist',
    aEn: 'always know exactly what time it is',
    bEn: 'always know exactly where north is',
  },
  {
    a: 'jede Diskussion gewinnen',
    b: 'jedem Streit aus dem Weg gehen können',
    aEn: 'win every argument',
    bEn: 'be able to avoid every fight',
  },
  {
    a: 'immer wissen, ob es in der nächsten Stunde regnet',
    b: 'immer wissen, ob dein Zug pünktlich kommt',
    aEn: 'always know whether it’ll rain in the next hour',
    bEn: 'always know whether your train will be on time',
  },
  {
    a: 'vier Tage die Woche je zehn Stunden arbeiten',
    b: 'fünf Tage die Woche je acht Stunden arbeiten',
    aEn: 'work ten hours a day, four days a week',
    bEn: 'work eight hours a day, five days a week',
  },
  {
    a: 'nur noch im Homeoffice arbeiten',
    b: 'jeden Tag ins Büro gehen',
    aEn: 'only work from home',
    bEn: 'go to the office every day',
  },
  {
    a: 'einen Job lieben, der schlecht bezahlt ist',
    b: 'einen Job hassen, der sehr gut bezahlt ist',
    aEn: 'love a job that pays badly',
    bEn: 'hate a job that pays really well',
  },
  {
    a: 'nie wieder Geburtstag feiern',
    b: 'nie wieder Weihnachten feiern',
    aEn: 'never celebrate your birthday again',
    bEn: 'never celebrate Christmas again',
  },
  {
    a: 'nur noch Geschenke von deiner Wunschliste bekommen',
    b: 'nur noch Überraschungsgeschenke bekommen',
    aEn: 'only get gifts from your wish list',
    bEn: 'only get surprise gifts',
  },
  {
    a: 'deinen Geburtstag mit 100 Leuten feiern',
    b: 'deinen Geburtstag mit deinen drei engsten Freunden feiern',
    aEn: 'celebrate your birthday with 100 people',
    bEn: 'celebrate your birthday with your three closest friends',
  },
  {
    a: 'heute 1.000 Euro bekommen',
    b: 'ab jetzt jeden Monat 20 Euro bekommen, für immer',
    aEn: 'get 1,000 euros today',
    bEn: 'get 20 euros every month from now on, forever',
  },
  {
    a: 'einen zusätzlichen freien Tag pro Woche haben',
    b: 'acht Wochen mehr Urlaub im Jahr haben',
    aEn: 'have one extra day off every week',
    bEn: 'have eight more weeks of vacation a year',
  },
  {
    a: 'nie wieder Schlange stehen',
    b: 'nie wieder im Stau stehen',
    aEn: 'never wait in line again',
    bEn: 'never sit in traffic again',
  },
  {
    a: 'immer einen perfekten ersten Eindruck machen',
    b: 'immer die perfekte Antwort parat haben',
    aEn: 'always make a perfect first impression',
    bEn: 'always have the perfect comeback ready',
  },
  {
    a: 'nie wieder Werbung sehen müssen',
    b: 'nie wieder ein Passwort vergessen',
    aEn: 'never have to see ads again',
    bEn: 'never forget a password again',
  },
  {
    a: 'nie wieder einen Geburtstag vergessen',
    b: 'nie wieder einen Namen vergessen',
    aEn: 'never forget a birthday again',
    bEn: 'never forget a name again',
  },
  {
    a: 'immer recht haben, aber niemand glaubt dir',
    b: 'immer falsch liegen, aber alle glauben dir',
    aEn: 'always be right, but nobody believes you',
    bEn: 'always be wrong, but everyone believes you',
  },
  {
    a: 'auf jeder Party der DJ sein',
    b: 'auf jeder Party für das Essen zuständig sein',
    aEn: 'be the DJ at every party',
    bEn: 'be in charge of the food at every party',
  },
  {
    a: 'bei jedem Ausflug fahren müssen',
    b: 'bei jedem Ausflug hinten in der Mitte sitzen',
    aEn: 'have to drive on every trip',
    bEn: 'sit in the back middle seat on every trip',
  },
  {
    a: 'eine Katze haben, die dich jede Nacht um 4 Uhr weckt',
    b: 'einen Hund haben, der überall Haare verliert',
    aEn: 'have a cat that wakes you up at 4 a.m. every night',
    bEn: 'have a dog that sheds everywhere',
  },
  {
    a: 'nie wieder erkältet sein',
    b: 'nie wieder zum Zahnarzt müssen',
    aEn: 'never catch a cold again',
    bEn: 'never have to go to the dentist again',
  },
  {
    a: 'jeden Montag frei haben',
    b: 'jeden Freitag frei haben',
    aEn: 'have every Monday off',
    bEn: 'have every Friday off',
  },
  {
    a: 'alle deine Nachbarn persönlich kennen',
    b: 'deine Nachbarn nie zu Gesicht bekommen',
    aEn: 'know all your neighbors personally',
    bEn: 'never see your neighbors at all',
  },
  {
    a: 'nie wieder eine Steuererklärung machen',
    b: 'nie wieder auf ein Amt gehen müssen',
    aEn: 'never do a tax return again',
    bEn: 'never have to go to a government office again',
  },
  {
    a: 'einen Monat ohne Handy leben',
    b: 'einen Monat ohne Auto und Öffis leben',
    aEn: 'live without your phone for a month',
    bEn: 'live without a car or public transit for a month',
  },
  {
    a: 'von jedem Film vorher das Ende kennen',
    b: 'jeden Film nach der Hälfte abbrechen müssen',
    aEn: 'know the ending of every movie beforehand',
    bEn: 'have to stop every movie halfway through',
  },
  {
    a: 'auf jedem Gruppenfoto die Augen zu haben',
    b: 'auf jedem Gruppenfoto unscharf sein',
    aEn: 'have your eyes closed in every group photo',
    bEn: 'be blurry in every group photo',
  },
  {
    a: 'nur noch per Brief kommunizieren',
    b: 'nur noch per Videoanruf kommunizieren',
    aEn: 'only communicate by letter',
    bEn: 'only communicate by video call',
  },
  {
    a: 'beim Lachen immer laut grunzen',
    b: 'bei jedem Lachen Tränen in den Augen haben',
    aEn: 'always snort loudly when you laugh',
    bEn: 'tear up every time you laugh',
  },
  {
    a: 'nie wieder Auto fahren',
    b: 'nie wieder Fahrrad fahren',
    aEn: 'never drive a car again',
    bEn: 'never ride a bike again',
  },
  {
    a: 'immer zu laut sprechen',
    b: 'immer zu leise sprechen',
    aEn: 'always talk too loudly',
    bEn: 'always talk too quietly',
  },
  {
    a: 'jeden Tag 30 Minuten auf den Bus warten',
    b: 'jeden Tag 30 Minuten zur Arbeit laufen',
    aEn: 'wait 30 minutes for the bus every day',
    bEn: 'walk 30 minutes to work every day',
  },
  {
    a: 'im Kino immer in der ersten Reihe sitzen',
    b: 'im Kino immer neben jemandem sitzen, der laut isst',
    aEn: 'always sit in the front row at the movies',
    bEn: 'always sit next to a loud eater at the movies',
  },
  {
    a: 'ohne Spiegel leben',
    b: 'ohne Uhr leben',
    aEn: 'live without mirrors',
    bEn: 'live without clocks',
  },
  {
    a: 'alle deine Handyfotos verlieren',
    b: 'alle deine Handykontakte verlieren',
    aEn: 'lose all the photos on your phone',
    bEn: 'lose all the contacts on your phone',
  },
  {
    a: 'jeden Tag im Garten frühstücken',
    b: 'jeden Tag im Bett frühstücken',
    aEn: 'have breakfast in the garden every day',
    bEn: 'have breakfast in bed every day',
  },
  {
    a: 'für immer dieselbe Frisur haben',
    b: 'jeden Monat eine zufällige Frisur bekommen',
    aEn: 'have the same haircut forever',
    bEn: 'get a random haircut every month',
  },
  {
    a: 'nur noch Hörbücher hören',
    b: 'nur noch Podcasts hören',
    aEn: 'only listen to audiobooks',
    bEn: 'only listen to podcasts',
  },
  {
    a: 'einen Tag im Freizeitpark verbringen',
    b: 'einen Tag in der Therme verbringen',
    aEn: 'spend a day at an amusement park',
    bEn: 'spend a day at a spa',
  },
  {
    a: 'auf einem Festival im Zelt schlafen',
    b: 'jeden Festivaltag aus dem Hotel anreisen',
    aEn: 'sleep in a tent at a festival',
    bEn: 'commute to the festival from a hotel every day',
  },
  {
    a: 'nur noch Filme mit Untertiteln schauen',
    b: 'nur noch synchronisierte Filme schauen',
    aEn: 'only watch movies with subtitles',
    bEn: 'only watch dubbed movies',
  },
  {
    a: 'immer viel zu viel Gepäck dabeihaben',
    b: 'immer etwas Wichtiges vergessen',
    aEn: 'always pack way too much',
    bEn: 'always forget something important',
  },
  {
    a: 'jedes Gespräch mit einem Witz beginnen müssen',
    b: 'jedes Gespräch mit einem Kompliment beenden müssen',
    aEn: 'have to start every conversation with a joke',
    bEn: 'have to end every conversation with a compliment',
  },
  {
    a: 'eine Spinne irgendwo im Schlafzimmer wissen',
    b: 'die ganze Nacht eine Mücke im Schlafzimmer hören',
    aEn: 'know there’s a spider somewhere in your bedroom',
    bEn: 'hear a mosquito in your bedroom all night',
  },
  {
    a: 'immer Sand in den Schuhen haben',
    b: 'immer einen offenen Schnürsenkel haben',
    aEn: 'always have sand in your shoes',
    bEn: 'always have an untied shoelace',
  },
  {
    a: 'beim Einkaufen immer etwas vergessen',
    b: 'beim Einkaufen immer doppelt so viel ausgeben wie geplant',
    aEn: 'always forget something when grocery shopping',
    bEn: 'always spend twice as much as planned when shopping',
  },
  {
    a: 'nie wieder online shoppen',
    b: 'nie wieder in einem Laden einkaufen',
    aEn: 'never shop online again',
    bEn: 'never shop in a store again',
  },
  {
    a: 'ein Jahr lang im Hotel leben',
    b: 'ein Jahr lang im Wohnmobil leben',
    aEn: 'live in a hotel for a year',
    bEn: 'live in an RV for a year',
  },
  {
    a: 'ein Smartphone ohne Kamera haben',
    b: 'ein Smartphone ohne Navigation haben',
    aEn: 'have a smartphone without a camera',
    bEn: 'have a smartphone without navigation',
  },
  {
    a: 'einen perfekten Orientierungssinn haben',
    b: 'ein perfektes Rhythmusgefühl haben',
    aEn: 'have a perfect sense of direction',
    bEn: 'have a perfect sense of rhythm',
  },
  {
    a: 'jeden Abend Besuch bekommen',
    b: 'nie wieder Besuch bekommen',
    aEn: 'have visitors every evening',
    bEn: 'never have visitors again',
  },
  {
    a: 'nur noch Vanilleeis essen',
    b: 'jedes Eis in einer zufälligen Sorte bekommen',
    aEn: 'only eat vanilla ice cream',
    bEn: 'get a random flavor every time you order ice cream',
  },
  {
    a: 'in einem Zimmer ohne Fenster schlafen',
    b: 'in einem Zimmer ohne Vorhänge schlafen',
    aEn: 'sleep in a room without windows',
    bEn: 'sleep in a room without curtains',
  },
  {
    a: 'auf jeder Hochzeit eine Rede halten müssen',
    b: 'auf jeder Hochzeit als Erstes tanzen müssen',
    aEn: 'have to give a speech at every wedding',
    bEn: 'have to be the first one dancing at every wedding',
  },
  {
    a: 'beim Grillen immer am Grill stehen müssen',
    b: 'beim Grillen nie mitbestimmen dürfen, was drauf kommt',
    aEn: 'always have to man the grill at barbecues',
    bEn: 'never get a say in what goes on the grill',
  },
  {
    a: 'mit 50 in Rente gehen und wenig Geld haben',
    b: 'mit 70 in Rente gehen und reich sein',
    aEn: 'retire at 50 with little money',
    bEn: 'retire at 70 and be rich',
  },
  {
    a: 'bei jedem Wetter mit dem Rad zur Arbeit fahren',
    b: 'jeden Tag eine Stunde Bahn zur Arbeit fahren',
    aEn: 'bike to work in any weather',
    bEn: 'take a one-hour train ride to work every day',
  },
  {
    a: 'nur noch Kleidung aus dem Secondhandladen kaufen',
    b: 'nur noch Kleidung tragen, die jemand anderes aussucht',
    aEn: 'only buy clothes from thrift stores',
    bEn: 'only wear clothes someone else picks for you',
  },
  {
    a: 'eine Woche ohne Strom auskommen',
    b: 'eine Woche ohne fließendes Wasser auskommen',
    aEn: 'go a week without electricity',
    bEn: 'go a week without running water',
  },
  {
    a: 'in jeder Gruppe alles organisieren müssen',
    b: 'in keiner Gruppe etwas mitentscheiden dürfen',
    aEn: 'have to organize everything in every group',
    bEn: 'never get a say in any group',
  },
  {
    a: 'noch einmal zur Schule gehen',
    b: 'noch einmal die Führerscheinprüfung machen',
    aEn: 'go back to school',
    bEn: 'retake your driving test',
  },
  {
    a: 'immer einen Ohrwurm haben',
    b: 'nie wieder ein Lied im Kopf haben',
    aEn: 'always have a song stuck in your head',
    bEn: 'never have a song in your head again',
  },
  {
    a: 'ständig die Fernbedienung verlieren',
    b: 'ständig das Ladekabel verlieren',
    aEn: 'constantly lose the remote',
    bEn: 'constantly lose your charging cable',
  },
  {
    a: 'jede Nacht träumen und dich an alles erinnern',
    b: 'nie wieder träumen, aber immer erholt aufwachen',
    aEn: 'dream every night and remember everything',
    bEn: 'never dream again but always wake up rested',
  },
  {
    a: 'einen Koch als besten Freund haben',
    b: 'einen Handwerker als besten Freund haben',
    aEn: 'have a chef as your best friend',
    bEn: 'have a handyman as your best friend',
  },
  {
    a: 'deine Lieblingsserie vergessen und neu schauen',
    b: 'dein Lieblingsbuch vergessen und neu lesen',
    aEn: 'forget your favorite show and watch it fresh',
    bEn: 'forget your favorite book and read it fresh',
  },
  {
    a: 'ein Jahr lang auf Zucker verzichten',
    b: 'ein Jahr lang auf Koffein verzichten',
    aEn: 'give up sugar for a year',
    bEn: 'give up caffeine for a year',
  },
  {
    a: 'im Restaurant immer das bestellen, was empfohlen wird',
    b: 'im Restaurant immer dasselbe bestellen',
    aEn: 'always order whatever the waiter recommends',
    bEn: 'always order the same dish at restaurants',
  },
  {
    a: 'nie wieder Fast Food essen',
    b: 'nie wieder Süßigkeiten essen',
    aEn: 'never eat fast food again',
    bEn: 'never eat candy again',
  },
  {
    a: 'jeden Abend frisch bezogene Bettwäsche haben',
    b: 'immer ein perfekt aufgeräumtes Zuhause haben',
    aEn: 'have fresh bed sheets every night',
    bEn: 'always have a perfectly tidy home',
  },
  {
    a: 'Gäste haben, die immer eine Stunde zu früh kommen',
    b: 'Gäste haben, die nie nach Hause gehen wollen',
    aEn: 'have guests who always arrive an hour early',
    bEn: 'have guests who never want to go home',
  },
  {
    a: 'eine eigene Bäckerei besitzen',
    b: 'eine eigene Bar besitzen',
    aEn: 'own your own bakery',
    bEn: 'own your own bar',
  },
  {
    a: 'einen Tag lang Bürgermeister deiner Stadt sein',
    b: 'einen Tag lang Chef deiner Firma sein',
    aEn: 'be mayor of your town for a day',
    bEn: 'be the boss of your company for a day',
  },
  {
    a: 'nur noch bar bezahlen',
    b: 'nur noch mit Karte bezahlen',
    aEn: 'only pay with cash',
    bEn: 'only pay by card',
  },
  {
    a: 'jeden Film von jemand anderem aussuchen lassen',
    b: 'jedes Urlaubsziel von jemand anderem aussuchen lassen',
    aEn: 'let someone else pick every movie you watch',
    bEn: 'let someone else pick every vacation destination',
  },
  {
    a: 'jeden Morgen von Vogelgezwitscher geweckt werden',
    b: 'jeden Morgen vom Duft frischen Kaffees geweckt werden',
    aEn: 'wake up to birdsong every morning',
    bEn: 'wake up to the smell of fresh coffee every morning',
  },
  {
    a: 'eine Woche bei deinen Schwiegereltern wohnen',
    b: 'eine Woche bei deinem Chef wohnen',
    aEn: 'stay with your in-laws for a week',
    bEn: 'stay with your boss for a week',
  },
  {
    a: 'einen Sommer lang als Eisverkäufer arbeiten',
    b: 'einen Winter lang als Skilehrer arbeiten',
    aEn: 'work as an ice cream seller for a summer',
    bEn: 'work as a ski instructor for a winter',
  },
  {
    a: 'als Heißgetränk nur noch Tee haben',
    b: 'als Heißgetränk nur noch Kakao haben',
    aEn: 'only have tea as a hot drink',
    bEn: 'only have hot chocolate as a hot drink',
  },
  {
    a: 'jeden Tag zehn Minuten aufräumen',
    b: 'einmal im Monat einen ganzen Tag aufräumen',
    aEn: 'tidy up for ten minutes every day',
    bEn: 'spend one whole day a month tidying up',
  },
  {
    a: 'bei jedem Spieleabend die Regeln erklären müssen',
    b: 'bei jedem Spieleabend ohne Regelerklärung mitspielen',
    aEn: 'have to explain the rules at every game night',
    bEn: 'play every game night without anyone explaining the rules',
  },
  {
    a: 'nie wieder Erdbeeren essen',
    b: 'nie wieder Äpfel essen',
    aEn: 'never eat strawberries again',
    bEn: 'never eat apples again',
  },
  {
    a: 'in einem Viertel ohne Bäckerei wohnen',
    b: 'in einem Viertel ohne Supermarkt wohnen',
    aEn: 'live in a neighborhood without a bakery',
    bEn: 'live in a neighborhood without a supermarket',
  },
  {
    a: 'jedes Paket zwei Wochen zu spät bekommen',
    b: 'jedes Paket beim Nachbarn abholen müssen',
    aEn: 'get every package two weeks late',
    bEn: 'have to pick up every package from a neighbor',
  },
  {
    a: 'nur noch Flip-Flops tragen',
    b: 'nur noch Gummistiefel tragen',
    aEn: 'only wear flip-flops',
    bEn: 'only wear rubber boots',
  },
  {
    a: 'beim Teamwählen immer als Letzter gewählt werden',
    b: 'in jeder Mannschaft der Kapitän sein müssen',
    aEn: 'always get picked last for teams',
    bEn: 'have to be captain of every team',
  },
  {
    a: 'jedes Telefonat auf Lautsprecher führen müssen',
    b: 'jedes Telefonat als Videoanruf führen müssen',
    aEn: 'have to take every call on speakerphone',
    bEn: 'have to take every call as a video call',
  },
  {
    a: 'in einem Baumhaus übernachten',
    b: 'in einem Iglu übernachten',
    aEn: 'spend the night in a treehouse',
    bEn: 'spend the night in an igloo',
  },
  {
    a: 'deine Wohnung jeden Monat umstellen',
    b: 'nie wieder ein Möbelstück verrücken',
    aEn: 'rearrange your home every month',
    bEn: 'never move a piece of furniture again',
  },
  {
    a: 'beim Essengehen immer die Rechnung übernehmen',
    b: 'beim Essengehen nie das Restaurant aussuchen dürfen',
    aEn: 'always pick up the bill when eating out',
    bEn: 'never get to choose the restaurant when eating out',
  },
  {
    a: 'jeden Tag eine Stunde mehr Freizeit haben',
    b: 'jede Nacht eine Stunde mehr Schlaf bekommen',
    aEn: 'have one more hour of free time every day',
    bEn: 'get one more hour of sleep every night',
  },
  {
    a: 'ein Talent fürs Backen haben',
    b: 'ein Talent fürs Grillen haben',
    aEn: 'have a talent for baking',
    bEn: 'have a talent for grilling',
  },
  {
    a: 'die ganze Nacht im Club tanzen',
    b: 'die ganze Nacht am Lagerfeuer reden',
    aEn: 'dance all night at a club',
    bEn: 'talk all night around a campfire',
  },
  {
    a: 'jede Nachricht sofort beantworten müssen',
    b: 'Nachrichten nur einmal am Tag lesen dürfen',
    aEn: 'have to answer every message immediately',
    bEn: 'only be allowed to read messages once a day',
  },
  {
    a: 'einen eigenen Koch haben',
    b: 'einen eigenen Chauffeur haben',
    aEn: 'have a personal chef',
    bEn: 'have a personal driver',
  },
  {
    a: 'auf jeder Party als Erster ankommen',
    b: 'auf jeder Party als Letzter gehen',
    aEn: 'be the first to arrive at every party',
    bEn: 'be the last to leave every party',
  },
  {
    a: 'eine Nacht in der Wüste verbringen',
    b: 'eine Nacht auf einem Gletscher verbringen',
    aEn: 'spend a night in the desert',
    bEn: 'spend a night on a glacier',
  },
];
