import type { WouldYouRatherSeed } from './types';

export const partyQuestions: WouldYouRatherSeed[] = [
  {
    a: 'an der Clubtür abgewiesen werden, während deine Freunde reinkommen',
    b: 'reinkommen, während deine Freunde draußen bleiben müssen',
    aEn: 'get turned away at the club door while your friends get in',
    bEn: 'get in while your friends are left outside',
  },
  {
    a: 'die ganze Nacht direkt neben der Box stehen müssen',
    b: 'die ganze Nacht direkt neben den Toiletten stehen müssen',
    aEn: 'have to stand right next to the speaker all night',
    bEn: 'have to stand right next to the toilets all night',
  },
  {
    a: 'eine Stunde in der Schlange vor dem Club warten',
    b: '30 Euro Eintritt für einen fast leeren Club zahlen',
    aEn: 'wait an hour in line outside the club',
    bEn: 'pay 30 euros entry for an almost empty club',
  },
  {
    a: 'dass der DJ die ganze Nacht nur Schlager spielt',
    b: 'dass der DJ die ganze Nacht Techno ohne Pause spielt',
    aEn: 'have the DJ play nothing but cheesy schlager all night',
    bEn: 'have the DJ play nonstop techno all night',
  },
  {
    a: 'deine Jacke an der Garderobe verlieren',
    b: 'dein Handy im Club verlieren',
    aEn: 'lose your jacket at the coat check',
    bEn: 'lose your phone in the club',
  },
  {
    a: 'vor allen auf der Tanzfläche hinfallen',
    b: 'beim Karaoke vor allen komplett den Text vergessen',
    aEn: 'fall over on the dance floor in front of everyone',
    bEn: 'completely forget the lyrics at karaoke in front of everyone',
  },
  {
    a: 'jedes Wochenende in denselben Club gehen',
    b: 'jedes Wochenende eine neue Bar ausprobieren, die meistens enttäuscht',
    aEn: 'go to the same club every weekend',
    bEn: 'try a new bar every weekend that usually disappoints',
  },
  {
    a: 'um 22 Uhr losgehen und um eins zu Hause sein',
    b: 'um eins losgehen und um sieben zu Hause sein',
    aEn: 'head out at 10 p.m. and be home by one',
    bEn: 'head out at one and get home at seven',
  },
  {
    a: 'einen Abend lang DJ sein, obwohl du keine Ahnung davon hast',
    b: 'einen Abend lang hinter der Bar stehen, ohne einen einzigen Cocktail zu kennen',
    aEn: 'be the DJ for a night with no clue what you’re doing',
    bEn: 'work the bar for a night without knowing a single cocktail',
  },
  {
    a: 'nur noch in Clubs mit Handyverbot feiern',
    b: 'nur noch in Clubs feiern, in denen alle ständig filmen',
    aEn: 'only party in clubs with a phone ban',
    bEn: 'only party in clubs where everyone films constantly',
  },
  {
    a: 'jeden Song im Club laut mitsingen müssen',
    b: 'keinen einzigen Song im Club kennen',
    aEn: 'have to sing along loudly to every song in the club',
    bEn: 'not know a single song in the club',
  },
  {
    a: 'die ganze Nacht in unbequemen Schuhen tanzen',
    b: 'barfuß über den klebrigen Clubboden laufen',
    aEn: 'dance all night in uncomfortable shoes',
    bEn: 'walk barefoot across the sticky club floor',
  },
  {
    a: 'dass die Party genau dann endet, wenn es am schönsten ist',
    b: 'dass die Party noch fünf Stunden weitergeht, nachdem du müde bist',
    aEn: 'have the party end exactly when it’s at its best',
    bEn: 'have the party go on for five more hours after you’re tired',
  },
  {
    a: 'im VIP-Bereich sitzen, wo niemand tanzt',
    b: 'mitten in der Menge tanzen, wo dir alle auf die Füße treten',
    aEn: 'sit in the VIP area where nobody dances',
    bEn: 'dance in the middle of the crowd where everyone steps on your feet',
  },
  {
    a: 'einen Tag lang den schlimmsten Song des Abends im Kopf haben',
    b: 'einen Tag lang ein Piepen im Ohr haben',
    aEn: 'have the worst song of the night stuck in your head for a day',
    bEn: 'have a ringing in your ears for a day',
  },
  {
    a: 'nur noch warmes Bier trinken',
    b: 'nur noch Wein aus dem Tetrapack trinken',
    aEn: 'only ever drink warm beer',
    bEn: 'only ever drink wine from a carton',
  },
  {
    a: 'bei jedem Trinkspiel verlieren',
    b: 'bei jedem Trinkspiel die Regeln erklären müssen',
    aEn: 'lose every drinking game',
    bEn: 'have to explain the rules of every drinking game',
  },
  {
    a: 'einen Abend lang nur Shots trinken',
    b: 'einen Abend lang nur süße Cocktails mit Schirmchen trinken',
    aEn: 'drink only shots for a night',
    bEn: 'drink only sweet cocktails with little umbrellas for a night',
  },
  {
    a: 'die Runde für alle bezahlen',
    b: 'den ganzen Abend für alle zur Bar laufen',
    aEn: 'pay for everyone’s round',
    bEn: 'run to the bar for everyone all night',
  },
  {
    a: 'nach jedem einzelnen Bier einen Kater haben',
    b: 'nie einen Kater haben, aber nach zwei Bier sofort einschlafen',
    aEn: 'get a hangover after every single beer',
    bEn: 'never get hungover but fall asleep right after two beers',
  },
  {
    a: 'den ganzen Abend Fahrer für alle sein',
    b: 'die Person sein, die alle nach Hause bringen müssen',
    aEn: 'be the designated driver for everyone all night',
    bEn: 'be the person everyone has to get home',
  },
  {
    a: 'Bierpong gegen deine Eltern spielen',
    b: 'ein Trinkspiel gegen deinen Chef spielen',
    aEn: 'play beer pong against your parents',
    bEn: 'play a drinking game against your boss',
  },
  {
    a: 'nur noch Getränke bestellen, die du nicht aussprechen kannst',
    b: 'immer das trinken, was der Barkeeper für dich aussucht',
    aEn: 'only order drinks you can’t pronounce',
    bEn: 'always drink whatever the bartender picks for you',
  },
  {
    a: 'dass dein Lieblingsdrink überall ausverkauft ist',
    b: 'dass dein Lieblingsdrink überall das Doppelte kostet',
    aEn: 'have your favorite drink sold out everywhere',
    bEn: 'have your favorite drink cost double everywhere',
  },
  {
    a: 'ein Glas Rotwein über dein weißes Shirt bekommen',
    b: 'ein Glas Rotwein über das weiße Sofa des Gastgebers kippen',
    aEn: 'get a glass of red wine spilled on your white shirt',
    bEn: 'spill a glass of red wine on the host’s white couch',
  },
  {
    a: 'Jägermeister pur trinken',
    b: 'Tequila ohne Salz und Zitrone trinken',
    aEn: 'drink Jägermeister neat',
    bEn: 'do tequila without salt and lime',
  },
  {
    a: 'den ganzen Abend alkoholfrei trinken und es allen erklären müssen',
    b: 'mittrinken, obwohl du morgen eine Prüfung hast',
    aEn: 'stay alcohol-free all night and have to explain it to everyone',
    bEn: 'drink along even though you have an exam tomorrow',
  },
  {
    a: 'für immer auf Bier verzichten',
    b: 'für immer auf Wein verzichten',
    aEn: 'give up beer forever',
    bEn: 'give up wine forever',
  },
  {
    a: 'dass jeder deiner Drinks viel zu stark gemischt ist',
    b: 'dass jeder deiner Drinks fast nur aus Eis besteht',
    aEn: 'have every drink mixed way too strong',
    bEn: 'have every drink be almost all ice',
  },
  {
    a: 'Kurze mit Leuten trinken, die du nicht kennst',
    b: 'Kurze mit deinen Großeltern trinken',
    aEn: 'take shots with people you don’t know',
    bEn: 'take shots with your grandparents',
  },
  {
    a: 'einen Cocktail für 18 Euro bestellen, der furchtbar schmeckt',
    b: 'den ganzen Abend den billigsten Fusel vom Späti trinken',
    aEn: 'order an 18-euro cocktail that tastes awful',
    bEn: 'drink the cheapest booze from the corner shop all night',
  },
  {
    a: 'einen Weinabend ausrichten, ohne Ahnung von Wein zu haben',
    b: 'bei einer Weinprobe neben einem Weinsnob sitzen',
    aEn: 'host a wine night without knowing anything about wine',
    bEn: 'sit next to a wine snob at a wine tasting',
  },
  {
    a: 'beim Öffnen den Sektkorken gegen die Lampe schießen',
    b: 'beim Öffnen dich selbst komplett mit Sekt vollschäumen',
    aEn: 'shoot the cork into the lamp when opening the bubbly',
    bEn: 'spray yourself head to toe with bubbly when opening it',
  },
  {
    a: 'nur noch auf Partys mit Open Bar, aber schlechter Musik gehen',
    b: 'nur noch auf Partys mit großartiger Musik, wo du jeden Drink selbst zahlst',
    aEn: 'only go to parties with an open bar but bad music',
    bEn: 'only go to parties with great music where you pay for every drink',
  },
  {
    a: 'vier Tage Festival ohne Dusche verbringen',
    b: 'vier Tage Festival mit leerem Handyakku verbringen',
    aEn: 'spend four days at a festival without a shower',
    bEn: 'spend four days at a festival with a dead phone',
  },
  {
    a: 'im Zelt bei Dauerregen schlafen',
    b: 'im Zelt bei 35 Grad aufwachen',
    aEn: 'sleep in a tent in nonstop rain',
    bEn: 'wake up in a tent at 35 degrees',
  },
  {
    a: 'dein Zelt nach der ersten Nacht nicht mehr finden',
    b: 'dein Zelt finden, aber es ist eingestürzt',
    aEn: 'not be able to find your tent after the first night',
    bEn: 'find your tent, but it has collapsed',
  },
  {
    a: 'deine Lieblingsband ganz vorne im Gedränge sehen',
    b: 'deine Lieblingsband entspannt von ganz hinten sehen, aber kaum etwas erkennen',
    aEn: 'see your favorite band right up front in the crush',
    bEn: 'watch your favorite band relaxed from way back but barely see a thing',
  },
  {
    a: 'das ganze Festival nur Dixi-Klos haben',
    b: 'saubere Toiletten haben, aber immer eine Stunde anstehen',
    aEn: 'have only portable toilets for the whole festival',
    bEn: 'have clean toilets but always wait an hour',
  },
  {
    a: 'auf ein Festival mit nur einer Band gehen, die du liebst',
    b: 'auf ein Festival mit zwanzig Bands gehen, die du ganz okay findest',
    aEn: 'go to a festival with just one band you love',
    bEn: 'go to a festival with twenty bands you think are okay',
  },
  {
    a: 'jede Nacht um vier vom Nachbarzelt mit Ballermann-Hits geweckt werden',
    b: 'die Leute sein, die das Nachbarzelt jede Nacht um vier wecken',
    aEn: 'get woken up by party anthems from the next tent at four every night',
    bEn: 'be the people who wake up the next tent at four every night',
  },
  {
    a: 'auf dem Festival nur kalte Dosenravioli essen',
    b: 'auf dem Festival für jedes Essen 15 Euro zahlen',
    aEn: 'eat only cold canned ravioli at the festival',
    bEn: 'pay 15 euros for every meal at the festival',
  },
  {
    a: 'gleich am ersten Festivaltag komplett im Schlamm landen',
    b: 'gleich am ersten Festivaltag einen Sonnenbrand im Gesicht bekommen',
    aEn: 'end up covered in mud on the first day of the festival',
    bEn: 'get a sunburned face on the first day of the festival',
  },
  {
    a: 'auf dem Festival direkt neben deinem Ex campen',
    b: 'auf dem Festival direkt neben deinen Eltern campen',
    aEn: 'camp right next to your ex at the festival',
    bEn: 'camp right next to your parents at the festival',
  },
  {
    a: 'drei Tage auf einem Rockfestival verbringen',
    b: 'drei Tage auf einem Technofestival verbringen',
    aEn: 'spend three days at a rock festival',
    bEn: 'spend three days at a techno festival',
  },
  {
    a: 'den Headliner verpassen, weil du eingeschlafen bist',
    b: 'den Headliner sehen, aber die ganze Zeit dringend aufs Klo müssen',
    aEn: 'miss the headliner because you fell asleep',
    bEn: 'see the headliner but desperately need the toilet the whole time',
  },
  {
    a: 'dir auf dem Festival das Zelt mit jemandem teilen, der schnarcht',
    b: 'im Auto schlafen, weil im Zelt kein Platz mehr ist',
    aEn: 'share your festival tent with someone who snores',
    bEn: 'sleep in the car because there’s no room left in the tent',
  },
  {
    a: 'einen Kater mit hämmernden Kopfschmerzen haben',
    b: 'einen Kater mit ständiger Übelkeit haben',
    aEn: 'have a hangover with a pounding headache',
    bEn: 'have a hangover with constant nausea',
  },
  {
    a: 'verkatert zu einem Familienessen müssen',
    b: 'verkatert beim Umzug helfen müssen',
    aEn: 'have to go to a family dinner hungover',
    bEn: 'have to help someone move house hungover',
  },
  {
    a: 'zwei Tage Kater nach einer legendären Nacht haben',
    b: 'gar keinen Kater nach einem langweiligen Abend haben',
    aEn: 'have a two-day hangover after a legendary night',
    bEn: 'have no hangover at all after a boring night',
  },
  {
    a: 'am Morgen danach jede Nachricht lesen, die du geschickt hast',
    b: 'nie erfahren, was du letzte Nacht alles geschrieben hast',
    aEn: 'read every message you sent the morning after',
    bEn: 'never find out what you texted last night',
  },
  {
    a: 'verkatert in einen Flieger steigen',
    b: 'verkatert eine Präsentation halten',
    aEn: 'get on a plane hungover',
    bEn: 'give a presentation hungover',
  },
  {
    a: 'verkatert aufwachen und es ist schon Sonntag, 16 Uhr',
    b: 'verkatert um sieben aufwachen und nicht mehr einschlafen können',
    aEn: 'wake up hungover and it’s already 4 p.m. on Sunday',
    bEn: 'wake up hungover at seven and not be able to fall back asleep',
  },
  {
    a: 'für alle das Katerfrühstück machen',
    b: 'allein das Chaos von der Party aufräumen',
    aEn: 'make hangover breakfast for everyone',
    bEn: 'clean up the mess from the party alone',
  },
  {
    a: 'dich an nichts vom Abend erinnern',
    b: 'dich an jedes peinliche Detail vom Abend erinnern',
    aEn: 'remember nothing from the night',
    bEn: 'remember every embarrassing detail from the night',
  },
  {
    a: 'jeden Kater erst einen Tag später bekommen',
    b: 'jeden Kater doppelt so stark, aber nur halb so lang haben',
    aEn: 'always get your hangover a day late',
    bEn: 'have every hangover twice as bad but half as long',
  },
  {
    a: 'deinen Kater bei deinen Eltern auskurieren',
    b: 'deinen Kater in einer WG mit fünf lauten Mitbewohnern auskurieren',
    aEn: 'nurse your hangover at your parents’ place',
    bEn: 'nurse your hangover in a flat with five loud roommates',
  },
  {
    a: 'die Party in deiner eigenen Wohnung schmeißen',
    b: 'auf eine Party gehen, auf der du nur den Gastgeber kennst',
    aEn: 'throw the party at your own place',
    bEn: 'go to a party where you only know the host',
  },
  {
    a: 'dass zu deiner Party viel zu wenige Leute kommen',
    b: 'dass doppelt so viele kommen, wie du eingeladen hast',
    aEn: 'have way too few people show up to your party',
    bEn: 'have twice as many people show up as you invited',
  },
  {
    a: 'dass die Nachbarn die Polizei rufen',
    b: 'dass die Nachbarn rüberkommen und bis zum Schluss bleiben',
    aEn: 'have the neighbors call the police',
    bEn: 'have the neighbors come over and stay until the very end',
  },
  {
    a: 'die ganze Party in der Küche verbringen',
    b: 'die ganze Party auf dem kalten Balkon verbringen',
    aEn: 'spend the whole party in the kitchen',
    bEn: 'spend the whole party on the cold balcony',
  },
  {
    a: 'dass sich jemand auf deiner Party in dein Bett übergibt',
    b: 'dass jemand auf deiner Party dein Klo verstopft',
    aEn: 'have someone throw up in your bed at your party',
    bEn: 'have someone clog your toilet at your party',
  },
  {
    a: 'die ganze Nacht die Musik aussuchen, während alle meckern',
    b: 'nie die Musik aussuchen dürfen',
    aEn: 'pick the music all night while everyone complains',
    bEn: 'never get to pick the music',
  },
  {
    a: 'auf einer Mottoparty als Einziger ohne Kostüm auftauchen',
    b: 'auf einer normalen Party als Einziger im Kostüm auftauchen',
    aEn: 'show up as the only one without a costume at a theme party',
    bEn: 'show up as the only one in costume at a normal party',
  },
  {
    a: 'dass deine Party bis sieben Uhr morgens geht',
    b: 'dass alle um Mitternacht schon gehen',
    aEn: 'have your party go until 7 a.m.',
    bEn: 'have everyone leave by midnight',
  },
  {
    a: 'nach der Party ganz allein aufräumen',
    b: 'Hilfe beim Aufräumen bekommen, bei der etwas Wertvolles zerbricht',
    aEn: 'clean up all alone after the party',
    bEn: 'get help cleaning up, but something valuable gets broken',
  },
  {
    a: 'auf einer Party nur Leute treffen, die über Krypto reden',
    b: 'auf einer Party nur Leute treffen, die über ihre Arbeit reden',
    aEn: 'only meet people talking about crypto at a party',
    bEn: 'only meet people talking about their jobs at a party',
  },
  {
    a: 'einen Partyraum mit großartiger Anlage, aber ohne Sitzplätze haben',
    b: 'einen gemütlichen Raum ohne richtige Musikanlage haben',
    aEn: 'have a party room with a great sound system but no seats',
    bEn: 'have a cozy room with no proper sound system',
  },
  {
    a: 'dass auf deiner Party um elf das Bier ausgeht',
    b: 'dass auf deiner Party um neun das Essen ausgeht',
    aEn: 'run out of beer at your party at eleven',
    bEn: 'run out of food at your party at nine',
  },
  {
    a: 'jede Geburtstagsfeier im Freundeskreis bei dir ausrichten müssen',
    b: 'nie wieder eine Party bei dir zu Hause feiern dürfen',
    aEn: 'have to host every birthday party in your friend group',
    bEn: 'never be allowed to throw a party at your place again',
  },
  {
    a: 'dass ein Gast deinen kompletten Kühlschrank leer isst',
    b: 'dass ein Gast deinen teuersten Whisky leer trinkt',
    aEn: 'have a guest eat everything in your fridge',
    bEn: 'have a guest finish your most expensive whisky',
  },
  {
    a: 'nur noch unter der Woche ausgehen, wenn alles leer ist',
    b: 'nur noch am Wochenende ausgehen, wenn alles überfüllt ist',
    aEn: 'only go out on weeknights when everything’s empty',
    bEn: 'only go out on weekends when everything’s packed',
  },
  {
    a: 'um drei Uhr nachts zwei Stunden auf den Nachtbus warten',
    b: 'um drei Uhr nachts 60 Euro für ein Taxi zahlen',
    aEn: 'wait two hours for the night bus at 3 a.m.',
    bEn: 'pay 60 euros for a cab at 3 a.m.',
  },
  {
    a: 'zwei Stunden für ein Outfit brauchen und dann doch zu Hause bleiben',
    b: 'spontan in Jogginghose losgehen und in einer schicken Bar landen',
    aEn: 'spend two hours on an outfit and then stay home anyway',
    bEn: 'head out on a whim in sweatpants and end up in a fancy bar',
  },
  {
    a: 'auf jeder Party immer als Erster ankommen',
    b: 'auf jeder Party immer als Letzter gehen',
    aEn: 'always be the first to arrive at every party',
    bEn: 'always be the last to leave every party',
  },
  {
    a: 'an einem Abend fünf verschiedene Bars abklappern',
    b: 'den ganzen Abend in einer einzigen Kneipe bleiben',
    aEn: 'hit five different bars in one night',
    bEn: 'stay in a single pub all night',
  },
  {
    a: 'für immer auf den Döner um vier Uhr morgens verzichten',
    b: 'nie wieder vorglühen',
    aEn: 'give up the 4 a.m. kebab forever',
    bEn: 'never pre-drink again',
  },
  {
    a: 'beim Vorglühen den besten Teil des Abends erleben',
    b: 'erst um zwei Uhr in Stimmung kommen, wenn alle müde sind',
    aEn: 'have the best part of the night during pre-drinks',
    bEn: 'only get in the mood at 2 a.m. when everyone’s tired',
  },
  {
    a: 'nur noch in Bars gehen, in denen du dein eigenes Wort nicht verstehst',
    b: 'nur noch in Bars gehen, in denen alle flüstern',
    aEn: 'only go to bars where you can’t hear yourself think',
    bEn: 'only go to bars where everyone whispers',
  },
  {
    a: 'spontan mit Fremden zum Feiern in eine andere Stadt fahren',
    b: 'den ganzen Abend allein zu Hause bleiben, während alle feiern',
    aEn: 'go partying in another city with strangers on a whim',
    bEn: 'stay home alone all night while everyone else parties',
  },
  {
    a: 'jedes Wochenende ausgehen, aber nie länger als bis Mitternacht',
    b: 'nur einmal im Monat ausgehen, dafür bis zum Morgen',
    aEn: 'go out every weekend but never past midnight',
    bEn: 'go out only once a month but until morning',
  },
  {
    a: 'beim Ausgehen dein Portemonnaie verlieren',
    b: 'beim Ausgehen deinen Haustürschlüssel verlieren',
    aEn: 'lose your wallet on a night out',
    bEn: 'lose your house key on a night out',
  },
  {
    a: 'für den Rest deines Lebens nur noch zu Karaoke-Abenden gehen',
    b: 'für den Rest deines Lebens nur noch zu Kneipenquiz-Abenden gehen',
    aEn: 'only go to karaoke nights for the rest of your life',
    bEn: 'only go to pub quiz nights for the rest of your life',
  },
  {
    a: 'die letzte Bahn nach Hause erwischen und die beste Stunde verpassen',
    b: 'bleiben und um fünf Uhr morgens am Bahnhof frieren',
    aEn: 'catch the last train home and miss the best hour',
    bEn: 'stay and freeze at the station at 5 a.m.',
  },
  {
    a: 'auf einer Party den Namen deines Gegenübers vergessen',
    b: 'jemanden den ganzen Abend mit dem falschen Namen ansprechen',
    aEn: 'forget the name of the person you’re talking to at a party',
    bEn: 'call someone by the wrong name all night',
  },
  {
    a: 'dass deine Eltern ein Video von dir betrunken sehen',
    b: 'dass dein Chef ein Video von dir betrunken sieht',
    aEn: 'have your parents see a video of you drunk',
    bEn: 'have your boss see a video of you drunk',
  },
  {
    a: 'betrunken deinem Ex schreiben',
    b: 'betrunken deinem Chef schreiben',
    aEn: 'drunk-text your ex',
    bEn: 'drunk-text your boss',
  },
  {
    a: 'betrunken eine peinliche Story posten, die 200 Leute sehen',
    b: 'betrunken eine peinliche Sprachnachricht in die Familiengruppe schicken',
    aEn: 'post an embarrassing story while drunk that 200 people see',
    bEn: 'send an embarrassing voice message to the family group chat while drunk',
  },
  {
    a: 'mitten in deiner Hochzeitsrede Schluckauf bekommen',
    b: 'mitten in deiner Hochzeitsrede in Tränen ausbrechen',
    aEn: 'get hiccups in the middle of your wedding speech',
    bEn: 'burst into tears in the middle of your wedding speech',
  },
  {
    a: 'mit Edding im Gesicht aufwachen',
    b: 'mit einer neuen Frisur aufwachen, die dir deine Freunde geschnitten haben',
    aEn: 'wake up with marker drawn all over your face',
    bEn: 'wake up with a new haircut your friends gave you',
  },
  {
    a: 'mit einem Tattoo aufwachen, an das du dich nicht erinnerst',
    b: 'mit einem Piercing aufwachen, an das du dich nicht erinnerst',
    aEn: 'wake up with a tattoo you don’t remember getting',
    bEn: 'wake up with a piercing you don’t remember getting',
  },
  {
    a: 'laut über jemanden lästern, der direkt hinter dir steht',
    b: 'vor allen eine Rede halten, über die niemand lacht',
    aEn: 'loudly gossip about someone standing right behind you',
    bEn: 'give a speech in front of everyone that nobody laughs at',
  },
  {
    a: 'den ganzen Abend mit Spinat zwischen den Zähnen herumlaufen',
    b: 'den ganzen Abend mit offenem Hosenstall herumlaufen',
    aEn: 'walk around all night with spinach in your teeth',
    bEn: 'walk around all night with your fly open',
  },
  {
    a: 'auf jedem Gruppenfoto die Augen zu haben',
    b: 'auf jedem Partyfoto mitten beim Kauen erwischt werden',
    aEn: 'have your eyes closed in every group photo',
    bEn: 'get caught mid-chew in every party photo',
  },
  {
    a: 'laut mitsingen und merken, dass die Musik längst aus ist',
    b: 'jemandem zurückwinken, der gar nicht dich gemeint hat',
    aEn: 'sing at the top of your lungs and realize the music stopped ages ago',
    bEn: 'wave back at someone who wasn’t waving at you',
  },
  {
    a: 'auf dem Heimweg in der Bahn einschlafen und an der Endstation aufwachen',
    b: 'mitten in der Nacht bei der falschen Wohnung in deinem Haus klingeln',
    aEn: 'fall asleep on the train home and wake up at the last stop',
    bEn: 'ring the wrong apartment in your building in the middle of the night',
  },
  {
    a: 'dass dein peinlichster Tanzmove viral geht',
    b: 'dass deine peinlichste Karaoke-Performance viral geht',
    aEn: 'have your most embarrassing dance move go viral',
    bEn: 'have your most embarrassing karaoke performance go viral',
  },
  {
    a: 'dich am nächsten Tag bei allen Gästen für dein Verhalten entschuldigen',
    b: 'nie erfahren, ob du dich daneben benommen hast',
    aEn: 'apologize to every guest for your behavior the next day',
    bEn: 'never find out whether you behaved badly',
  },
  {
    a: 'eine Party crashen und rausgeworfen werden',
    b: 'auf deiner eigenen Party als Erster einschlafen',
    aEn: 'crash a party and get thrown out',
    bEn: 'be the first to fall asleep at your own party',
  },
  {
    a: 'betrunken eine Online-Bestellung über 300 Euro aufgeben',
    b: 'betrunken einen Flug für nächste Woche buchen',
    aEn: 'place a 300-euro online order while drunk',
    bEn: 'book a flight for next week while drunk',
  },
  {
    a: 'den ganzen Abend auf deinen sehr betrunkenen besten Freund aufpassen',
    b: 'der sehr betrunkene Freund sein, auf den alle aufpassen müssen',
    aEn: 'look after your very drunk best friend all night',
    bEn: 'be the very drunk friend everyone has to look after',
  },
  {
    a: 'mit Freunden feiern, die ständig Fotos machen wollen',
    b: 'mit Freunden feiern, die um elf schon müde sind',
    aEn: 'party with friends who constantly want to take photos',
    bEn: 'party with friends who are tired by eleven',
  },
  {
    a: 'deinen Freund allein in der Bar lassen, um nach Hause zu gehen',
    b: 'bleiben, obwohl du todmüde bist',
    aEn: 'leave your friend alone at the bar so you can go home',
    bEn: 'stay even though you’re dead tired',
  },
  {
    a: 'eine Freundesgruppe haben, die immer feiern will',
    b: 'eine Freundesgruppe haben, die nie feiern will',
    aEn: 'have a friend group that always wants to party',
    bEn: 'have a friend group that never wants to party',
  },
  {
    a: 'der Freund sein, der immer den Abend planen muss',
    b: 'der Freund sein, der nie gefragt wird, ob er mitkommt',
    aEn: 'be the friend who always has to plan the night',
    bEn: 'be the friend who never gets asked to come along',
  },
  {
    a: 'dass dein bester Freund auf der Party mit deinem Schwarm flirtet',
    b: 'dass dein Schwarm dich den ganzen Abend über deinen besten Freund ausfragt',
    aEn: 'have your best friend flirt with your crush at the party',
    bEn: 'have your crush ask you about your best friend all night',
  },
  {
    a: '300 ungelesene Nachrichten in der Gruppe für den Abend haben',
    b: 'merken, dass dich keiner in die Gruppe für den Abend geholt hat',
    aEn: 'have 300 unread messages in the group chat for the night',
    bEn: 'realize nobody added you to the group chat for the night',
  },
  {
    a: 'auf Partys immer die Streits deiner Freunde schlichten müssen',
    b: 'auf Partys immer selbst mitten im Streit stecken',
    aEn: 'always have to settle your friends’ fights at parties',
    bEn: 'always be caught in the middle of the fight at parties',
  },
  {
    a: 'mit Freunden ausgehen, die nur in Clubs wollen',
    b: 'mit Freunden ausgehen, die nur in Kneipen wollen',
    aEn: 'go out with friends who only want clubs',
    bEn: 'go out with friends who only want pubs',
  },
  {
    a: 'deinem Freund ehrlich sagen, dass sein Date furchtbar ist',
    b: 'den ganzen Abend mit seinem furchtbaren Date verbringen und schweigen',
    aEn: 'tell your friend honestly that their date is awful',
    bEn: 'spend all night with their awful date and say nothing',
  },
  {
    a: 'jede Rechnung durch alle teilen, auch wenn du nur Wasser hattest',
    b: 'immer genau abrechnen und als geizig gelten',
    aEn: 'always split the bill evenly, even if you only had water',
    bEn: 'always pay exactly your share and be seen as stingy',
  },
  {
    a: 'die Person sein, die alle zum Ausgehen überredet',
    b: 'die Person sein, die immer überredet werden muss',
    aEn: 'be the one who talks everyone into going out',
    bEn: 'be the one who always needs to be talked into it',
  },
  {
    a: 'dass deine Freunde deinen Geburtstag vergessen',
    b: 'dass deine Freunde dir eine Überraschungsparty schmeißen, die du hasst',
    aEn: 'have your friends forget your birthday',
    bEn: 'have your friends throw you a surprise party you hate',
  },
  {
    a: 'mit Freunden ausgehen, die sich nie entscheiden können, wohin',
    b: 'mit Freunden ausgehen, die immer in dieselbe langweilige Bar wollen',
    aEn: 'go out with friends who can never decide where to go',
    bEn: 'go out with friends who always want the same boring bar',
  },
  {
    a: 'einen Junggesellenabschied mit Bauchladen in der Fußgängerzone feiern',
    b: 'einen Junggesellenabschied mit Wellness und Kräutertee feiern',
    aEn: 'have a bachelor party selling shots from a tray in the town center',
    bEn: 'have a bachelor party with spa treatments and herbal tea',
  },
  {
    a: 'am Ballermann auf Mallorca feiern',
    b: 'in einem sündhaft teuren Club auf Ibiza feiern',
    aEn: 'party at the Ballermann strip in Mallorca',
    bEn: 'party in a ridiculously expensive club in Ibiza',
  },
  {
    a: 'Silvester in einem überfüllten Club feiern',
    b: 'Silvester zu zweit auf dem Sofa verbringen',
    aEn: 'spend New Year’s Eve in a packed club',
    bEn: 'spend New Year’s Eve on the couch with one other person',
  },
  {
    a: 'eine ganze Karnevalswoche durchfeiern',
    b: 'die ganze Karnevalswoche komplett nüchtern arbeiten',
    aEn: 'party through a whole week of Carnival',
    bEn: 'work through the whole week of Carnival completely sober',
  },
  {
    a: 'auf dem Oktoberfest einen Tisch für zehn Leute bezahlen',
    b: 'auf dem Oktoberfest stundenlang ohne Platz herumstehen',
    aEn: 'pay for a table for ten at Oktoberfest',
    bEn: 'stand around for hours at Oktoberfest without a seat',
  },
  {
    a: 'auf eine Hochzeit mit Open Bar, aber ohne Tanzfläche gehen',
    b: 'auf eine Hochzeit mit Tanzfläche, aber ohne Alkohol gehen',
    aEn: 'go to a wedding with an open bar but no dance floor',
    bEn: 'go to a wedding with a dance floor but no alcohol',
  },
  {
    a: 'den Junggesellenabschied deines besten Freundes planen müssen',
    b: 'auf seiner Hochzeit die Rede halten müssen',
    aEn: 'have to plan your best friend’s bachelor party',
    bEn: 'have to give the speech at their wedding',
  },
  {
    a: 'einen Abend mit den Partyfreunden deiner Eltern verbringen',
    b: 'deine Eltern auf deine Party mitnehmen',
    aEn: 'spend an evening with your parents’ party friends',
    bEn: 'bring your parents to your party',
  },
  {
    a: 'auf der Firmenfeier zu viel trinken',
    b: 'auf der Firmenfeier als Einziger nüchtern bleiben',
    aEn: 'drink too much at the office party',
    bEn: 'be the only sober one at the office party',
  },
  {
    a: 'auf der Weihnachtsfeier den ganzen Abend neben dem Chef sitzen',
    b: 'auf der Weihnachtsfeier die Rede halten',
    aEn: 'sit next to the boss all night at the Christmas party',
    bEn: 'give the speech at the Christmas party',
  },
  {
    a: 'auf einer Bootsparty seekrank werden',
    b: 'auf einer Kellerparty ohne Handyempfang festsitzen',
    aEn: 'get seasick at a boat party',
    bEn: 'be stuck at a basement party with no phone signal',
  },
  {
    a: 'nur noch auf Silent Discos feiern',
    b: 'nur noch auf Partys feiern, auf denen eine Coverband spielt',
    aEn: 'only party at silent discos',
    bEn: 'only party where a cover band is playing',
  },
  {
    a: 'auf einer Party nur mit Fremden reden',
    b: 'auf einer Party nur mit deinem Ex reden',
    aEn: 'talk only to strangers at a party',
    bEn: 'talk only to your ex at a party',
  },
  {
    a: 'auf jeder Party deinem Ex begegnen',
    b: 'auf jeder Party deinem Chef begegnen',
    aEn: 'run into your ex at every party',
    bEn: 'run into your boss at every party',
  },
  {
    a: 'auf einer Party jemand Tolles kennenlernen und die Nummer nicht bekommen',
    b: 'die Nummer bekommen, aber den Namen vergessen haben',
    aEn: 'meet someone great at a party and not get their number',
    bEn: 'get their number but have forgotten their name',
  },
  {
    a: 'dein erstes Date auf einem Festival haben',
    b: 'dein erstes Date auf der Hochzeit von Fremden haben',
    aEn: 'have your first date at a festival',
    bEn: 'have your first date at a stranger’s wedding',
  },
  {
    a: 'an der Bar einen Korb bekommen, während deine Freunde zuschauen',
    b: 'einen Drink ausgegeben bekommen von jemandem, den du loswerden willst',
    aEn: 'get turned down at the bar while your friends watch',
    bEn: 'get bought a drink by someone you’re trying to get rid of',
  },
  {
    a: 'auf jeder Party der Fotograf sein müssen',
    b: 'auf keinem einzigen Foto der Party zu sehen sein',
    aEn: 'have to be the photographer at every party',
    bEn: 'not appear in a single photo from the party',
  },
  {
    a: 'eine Playlist machen, die alle hassen',
    b: 'die ganze Nacht die Playlist von jemand anderem ertragen',
    aEn: 'make a playlist everyone hates',
    bEn: 'put up with someone else’s playlist all night',
  },
  {
    a: 'im Trinkspiel die Wahrheit über deinen schlimmsten Abend erzählen',
    b: 'stattdessen drei Shots hintereinander trinken',
    aEn: 'tell the truth about your worst night in a drinking game',
    bEn: 'down three shots in a row instead',
  },
  {
    a: 'bei „Wahrheit oder Pflicht“ immer Wahrheit nehmen müssen',
    b: 'bei „Wahrheit oder Pflicht“ immer Pflicht nehmen müssen',
    aEn: 'always have to pick truth in truth or dare',
    bEn: 'always have to pick dare in truth or dare',
  },
  {
    a: 'bei „Ich hab noch nie“ in jeder Runde trinken müssen',
    b: 'bei „Ich hab noch nie“ nie trinken und als langweilig gelten',
    aEn: 'have to drink every round of never have I ever',
    bEn: 'never drink in never have I ever and be seen as boring',
  },
  {
    a: 'einen Spieleabend mit Leuten, die schummeln',
    b: 'einen Spieleabend mit Leuten, die alles viel zu ernst nehmen',
    aEn: 'have a game night with people who cheat',
    bEn: 'have a game night with people who take everything way too seriously',
  },
  {
    a: 'die Fotos vom Abend nie zu sehen bekommen',
    b: 'alle Fotos vom Abend sehen, auch die schlimmen',
    aEn: 'never get to see the photos from the night',
    bEn: 'see every photo from the night, even the bad ones',
  },
  {
    a: 'dein Lieblingslied auf jeder Party hören, bis du es hasst',
    b: 'dein Lieblingslied nie wieder auf einer Party hören',
    aEn: 'hear your favorite song at every party until you hate it',
    bEn: 'never hear your favorite song at a party again',
  },
  {
    a: 'auf eine Party mit lauter Musik gehen, auf der niemand redet',
    b: 'auf eine Party mit leiser Musik gehen, auf der alle über Politik streiten',
    aEn: 'go to a party with loud music where nobody talks',
    bEn: 'go to a party with quiet music where everyone argues about politics',
  },
  {
    a: 'dass auf deiner Party der Strom ausfällt',
    b: 'dass auf deiner Party die Toilette kaputtgeht',
    aEn: 'have the power go out at your party',
    bEn: 'have the toilet break at your party',
  },
  {
    a: 'auf einer Party hungrig bleiben',
    b: 'das selbst gekochte, furchtbare Essen des Gastgebers loben müssen',
    aEn: 'stay hungry at a party',
    bEn: 'have to praise the host’s awful home cooking',
  },
  {
    a: 'die einzige Person auf der Party sein, die tanzt',
    b: 'die einzige Person auf der Party sein, die nicht tanzt',
    aEn: 'be the only person dancing at the party',
    bEn: 'be the only person not dancing at the party',
  },
  {
    a: 'auf einer Party einen Promi treffen und es nicht merken',
    b: 'auf einer Party einen Promi treffen und dich komplett blamieren',
    aEn: 'meet a celebrity at a party and not realize it',
    bEn: 'meet a celebrity at a party and totally embarrass yourself',
  },
  {
    a: 'die Nacht durchfeiern und direkt zum Frühstück gehen',
    b: 'um Mitternacht ins Bett gehen und frisch in den Tag starten',
    aEn: 'party through the night and go straight to breakfast',
    bEn: 'go to bed at midnight and start the day fresh',
  },
  {
    a: 'jede Partynacht mit einem Deep Talk um vier Uhr morgens beenden',
    b: 'jede Partynacht mit einer Essensbestellung beenden, die du bereust',
    aEn: 'end every party night with a deep talk at 4 a.m.',
    bEn: 'end every party night with a food order you regret',
  },
  {
    a: 'auf einer Party fünf Stunden lang mit jemandem über Fußball reden',
    b: 'auf einer Party fünf Stunden lang mit jemandem über Sternzeichen reden',
    aEn: 'talk football with someone at a party for five hours',
    bEn: 'talk star signs with someone at a party for five hours',
  },
  {
    a: 'auf einer Party jemanden treffen, der genauso aussieht wie du',
    b: 'im selben Outfit wie der Gastgeber auftauchen',
    aEn: 'meet someone at a party who looks exactly like you',
    bEn: 'show up in the same outfit as the host',
  },
  {
    a: 'dass auf jeder Party jemand die Gitarre auspackt',
    b: 'dass auf jeder Party jemand die Musik leiser dreht',
    aEn: 'have someone pull out a guitar at every party',
    bEn: 'have someone turn the music down at every party',
  },
  {
    a: 'auf der Tanzfläche mit deinem alten Lehrer tanzen',
    b: 'auf der Tanzfläche direkt neben deinen Eltern tanzen',
    aEn: 'dance with your old teacher on the dance floor',
    bEn: 'dance right next to your parents on the dance floor',
  },
  {
    a: 'beim Karaoke immer ein Duett mit einem Fremden singen müssen',
    b: 'beim Karaoke immer allein eine Ballade singen müssen',
    aEn: 'always have to sing a duet with a stranger at karaoke',
    bEn: 'always have to sing a ballad solo at karaoke',
  },
  {
    a: 'die Afterparty bei dir zu Hause haben',
    b: 'die Afterparty verpassen, von der alle noch wochenlang reden',
    aEn: 'host the afterparty at your place',
    bEn: 'miss the afterparty everyone talks about for weeks',
  },
  {
    a: 'ohne Jacke losgehen und auf dem Heimweg frieren',
    b: 'mit Jacke losgehen und eine Stunde an der Garderobe anstehen',
    aEn: 'go out without a jacket and freeze on the way home',
    bEn: 'bring a jacket and queue for an hour at the coat check',
  },
  {
    a: 'in einer Stadt wohnen, in der alle Bars um Mitternacht schließen',
    b: 'in einer Stadt wohnen, in der Clubs nie schließen, aber alles teuer ist',
    aEn: 'live in a city where every bar closes at midnight',
    bEn: 'live in a city where clubs never close but everything is expensive',
  },
  {
    a: 'immer nüchtern bleiben, dich aber auf jeder Party super amüsieren',
    b: 'immer mittrinken, dich aber auf Partys oft langweilen',
    aEn: 'always stay sober but have a great time at every party',
    bEn: 'always drink but often be bored at parties',
  },
  {
    a: 'dass der DJ jeden deiner Musikwünsche ablehnt',
    b: 'dass der DJ jeden deiner Wünsche spielt und die Tanzfläche sich leert',
    aEn: 'have the DJ turn down every one of your requests',
    bEn: 'have the DJ play every request and watch the dance floor empty',
  },
  {
    a: 'dass deine Mitbewohner ohne Vorwarnung eine Party schmeißen',
    b: 'Mitbewohner haben, die nie eine Party erlauben',
    aEn: 'have your roommates throw a party without warning',
    bEn: 'have roommates who never allow parties',
  },
  {
    a: 'nach der Party mit vier Freunden in einem Doppelbett schlafen',
    b: 'nach der Party allein auf dem harten Boden schlafen',
    aEn: 'sleep in a double bed with four friends after the party',
    bEn: 'sleep alone on the hard floor after the party',
  },
  {
    a: 'nie wieder Schnaps trinken dürfen',
    b: 'nie wieder in einem Club tanzen dürfen',
    aEn: 'never be allowed to drink spirits again',
    bEn: 'never be allowed to dance in a club again',
  },
  {
    a: 'nur noch auf 80er-Partys gehen',
    b: 'nur noch auf 2000er-Partys gehen',
    aEn: 'only go to 80s parties',
    bEn: 'only go to 2000s parties',
  },
  {
    a: 'auf einer Party in einem Gespräch festhängen, aus dem du nicht rauskommst',
    b: 'die ganze Party allein am Snacktisch stehen',
    aEn: 'be stuck in a conversation you can’t escape at a party',
    bEn: 'stand alone by the snack table for the whole party',
  },
  {
    a: 'auf dem Weg zur Party im Aufzug steckenbleiben',
    b: 'auf dem Weg zur Party ohne Schirm in einen Wolkenbruch geraten',
    aEn: 'get stuck in the elevator on the way to the party',
    bEn: 'get caught in a downpour without an umbrella on the way to the party',
  },
  {
    a: 'den ganzen Abend ohne Handy feiern',
    b: 'mit Handy feiern, aber den ganzen Abend live streamen müssen',
    aEn: 'party all night without your phone',
    bEn: 'party with your phone but have to livestream the whole night',
  },
  {
    a: 'beim Tanzen jemandem einen Drink über das Outfit kippen',
    b: 'beim Tanzen einen Drink über dein eigenes Outfit gekippt bekommen',
    aEn: 'spill a drink on someone’s outfit while dancing',
    bEn: 'get a drink spilled on your own outfit while dancing',
  },
  {
    a: 'eine Woche Party auf einem Kreuzfahrtschiff machen',
    b: 'eine Woche Après-Ski in einer Skihütte machen',
    aEn: 'party for a week on a cruise ship',
    bEn: 'spend a week doing après-ski at a ski lodge',
  },
  {
    a: 'in einem Raum ohne Fenster bei 30 Grad tanzen',
    b: 'auf einer Gartenparty im Oktober frieren',
    aEn: 'dance in a windowless room at 30 degrees',
    bEn: 'freeze at a garden party in October',
  },
  {
    a: 'nie wieder einen Abend vor Mitternacht beenden dürfen',
    b: 'jeden Abend um Mitternacht zu Hause sein müssen',
    aEn: 'never be allowed to end a night before midnight',
    bEn: 'always have to be home by midnight',
  },
  {
    a: 'mit Freunden feiern, die immer zu viel trinken',
    b: 'mit Freunden feiern, die gar nicht trinken und früh gehen',
    aEn: 'party with friends who always drink too much',
    bEn: 'party with friends who don’t drink and leave early',
  },
  {
    a: 'dass deine Oma auf deiner Party alle unter den Tisch trinkt',
    b: 'dass dein kleiner Bruder auf deiner Party deine peinlichsten Kindheitsgeschichten erzählt',
    aEn: 'have your grandma drink everyone under the table at your party',
    bEn: 'have your little brother tell your most embarrassing childhood stories at your party',
  },
  {
    a: 'einen Sommer lang als Barkeeper an der Küste arbeiten',
    b: 'einen Sommer lang DJ in einem kleinen Dorfclub sein',
    aEn: 'work as a bartender on the coast for a summer',
    bEn: 'be the DJ in a small village club for a summer',
  },
  {
    a: 'in einer Dorfdisco feiern',
    b: 'auf einer Studentenparty feiern, auf der du der Älteste bist',
    aEn: 'party at a village disco',
    bEn: 'party at a student party where you’re the oldest',
  },
  {
    a: 'nach einer Party mit Muskelkater vom Tanzen aufwachen',
    b: 'nach einer Party heiser vom Mitsingen aufwachen',
    aEn: 'wake up after a party with sore muscles from dancing',
    bEn: 'wake up after a party hoarse from singing along',
  },
  {
    a: 'deine Partyoutfits nur noch von deiner Mutter aussuchen lassen',
    b: 'deine Partyoutfits nur noch von deinem besten Freund aussuchen lassen',
    aEn: 'let your mom pick all your party outfits',
    bEn: 'let your best friend pick all your party outfits',
  },
  {
    a: 'dass jeder Gast eine Flasche mitbringt, die keiner trinken will',
    b: 'dass kein einziger Gast etwas mitbringt',
    aEn: 'have every guest bring a bottle nobody wants to drink',
    bEn: 'have not a single guest bring anything',
  },
  {
    a: 'der einzige Single auf einer Pärchenparty sein',
    b: 'das einzige Paar auf einer Singleparty sein',
    aEn: 'be the only single person at a couples’ party',
    bEn: 'be the only couple at a singles party',
  },
  {
    a: 'dass deine Party im Netz legendär wird, du dich aber an nichts erinnerst',
    b: 'eine kleine Party feiern, an die sich nur du gern erinnerst',
    aEn: 'have your party become legendary online but remember none of it',
    bEn: 'have a small party that only you fondly remember',
  },
  {
    a: 'auf einer Party aus Versehen das Getränk eines Fremden austrinken',
    b: 'dein Getränk kurz abstellen und es nie wiederfinden',
    aEn: 'accidentally finish a stranger’s drink at a party',
    bEn: 'set your drink down for a second and never find it again',
  },
  {
    a: 'deinen Geburtstag in einem Club feiern, wo es niemand weiß',
    b: 'deinen Geburtstag in einem Club feiern, wo der DJ es ansagt und alle singen',
    aEn: 'celebrate your birthday in a club where nobody knows',
    bEn: 'celebrate your birthday in a club where the DJ announces it and everyone sings',
  },
  {
    a: 'mit deinen Kollegen feiern gehen',
    b: 'mit den Freunden deines Partners feiern gehen',
    aEn: 'go out partying with your coworkers',
    bEn: 'go out partying with your partner’s friends',
  },
  {
    a: 'in einem Bus voller Fremder zum Festival fahren',
    b: 'zehn Stunden mit deinen Freunden im engen Auto zum Festival fahren',
    aEn: 'ride to the festival on a bus full of strangers',
    bEn: 'drive ten hours to the festival in a cramped car with your friends',
  },
  {
    a: 'betrunken all deine eigenen Geheimnisse ausplaudern',
    b: 'betrunken die Geheimnisse deiner Freunde ausplaudern',
    aEn: 'spill all your own secrets while drunk',
    bEn: 'spill your friends’ secrets while drunk',
  },
  {
    a: 'jedes Mal mitten im besten Song aufs Klo müssen',
    b: 'beim besten Song jedes Mal an der Bar in der Schlange stehen',
    aEn: 'always need the toilet in the middle of the best song',
    bEn: 'always be stuck in line at the bar during the best song',
  },
  {
    a: 'mit einer Gruppe feiern, die du gerade erst kennengelernt hast',
    b: 'mit deinen ältesten Freunden feiern, die nur über früher reden',
    aEn: 'party with a group you only just met',
    bEn: 'party with your oldest friends who only talk about the old days',
  },
  {
    a: 'in einer Bar neben einem lauten Junggesellenabschied sitzen',
    b: 'in einer Bar neben einer Geburtstagsrunde sitzen, die alle fünf Minuten singt',
    aEn: 'sit in a bar next to a loud bachelor party',
    bEn: 'sit in a bar next to a birthday group that sings every five minutes',
  },
  {
    a: 'auf einer Hochzeit tanzen müssen, obwohl du es nicht kannst',
    b: 'den ganzen Abend am Tisch mit der redseligsten Tante sitzen',
    aEn: 'have to dance at a wedding even though you can’t',
    bEn: 'sit at the table all night with the chattiest aunt',
  },
  {
    a: 'einmal im Monat richtig eskalieren',
    b: 'jeden Abend ein entspanntes Feierabendbier trinken',
    aEn: 'go completely wild once a month',
    bEn: 'have a relaxed after-work beer every evening',
  },
  {
    a: 'den ganzen Abend Fragen zu deiner Beziehung beantworten',
    b: 'den ganzen Abend die Beziehungsprobleme eines Freundes anhören',
    aEn: 'answer questions about your relationship all night',
    bEn: 'listen to a friend’s relationship problems all night',
  },
  {
    a: 'dich nachts zu einem spontanen Bad im See überreden lassen',
    b: 'als Einziger am Ufer stehen und auf alle Sachen aufpassen',
    aEn: 'get talked into a spontaneous midnight swim in the lake',
    bEn: 'be the only one on the shore guarding everyone’s stuff',
  },
  {
    a: 'beim Grillfest den ganzen Abend für alle am Grill stehen',
    b: 'beim Grillfest als Letzter essen und nur Reste bekommen',
    aEn: 'man the grill for everyone all evening at the barbecue',
    bEn: 'eat last at the barbecue and only get leftovers',
  },
  {
    a: 'nach einer Party mit drei unbekannten Nummern im Handy aufwachen',
    b: 'nach einer Party mit der Nachricht „Wir müssen reden“ aufwachen',
    aEn: 'wake up after a party with three unknown numbers in your phone',
    bEn: 'wake up after a party to a text saying “We need to talk”',
  },
  {
    a: 'auf eine Dachterrassenparty im Regen gehen',
    b: 'bei schönstem Wetter auf eine Kellerparty gehen',
    aEn: 'go to a rooftop party in the rain',
    bEn: 'go to a basement party in perfect weather',
  },
  {
    a: 'versprechen, nur auf ein Bier mitzukommen, und bis fünf bleiben',
    b: 'wirklich nach einem Bier gehen und alles verpassen',
    aEn: 'promise you’re only coming for one beer and stay until five',
    bEn: 'actually leave after one beer and miss everything',
  },
  {
    a: 'einen Partner haben, der auf jeder Party im Mittelpunkt steht',
    b: 'einen Partner haben, der auf jeder Party in der Ecke steht und gehen will',
    aEn: 'have a partner who’s the center of attention at every party',
    bEn: 'have a partner who stands in the corner wanting to leave every party',
  },
  {
    a: 'auf eine Party gehen, ohne zu wissen, wessen Party es ist',
    b: 'auf eine Party gehen, auf der dich alle kennen, du aber niemanden',
    aEn: 'go to a party without knowing whose party it is',
    bEn: 'go to a party where everyone knows you but you know nobody',
  },
  {
    a: 'jede Woche auf ein Konzert gehen',
    b: 'jede Woche in einen Club gehen',
    aEn: 'go to a concert every week',
    bEn: 'go to a club every week',
  },
  {
    a: 'auf einem Konzert direkt hinter der größten Person stehen',
    b: 'auf einem Konzert direkt neben jemandem stehen, der schief mitsingt',
    aEn: 'stand right behind the tallest person at a concert',
    bEn: 'stand right next to someone singing off-key at a concert',
  },
  {
    a: 'nach einer legendären Nacht kein Geld mehr übrig haben',
    b: 'dein Geld noch haben, aber keinen einzigen schönen Moment erlebt haben',
    aEn: 'have no money left after a legendary night',
    bEn: 'still have your money but not a single good memory',
  },
  {
    a: 'für immer den Spitznamen behalten, den du an einem Partyabend bekommen hast',
    b: 'bei jedem Klassentreffen deinen peinlichsten Partymoment erzählt bekommen',
    aEn: 'keep the nickname you got on one party night forever',
    bEn: 'have your most embarrassing party moment retold at every reunion',
  },
  {
    a: 'auf eine Party in einer Scheune auf dem Land gehen',
    b: 'auf eine Party in einem schicken Penthouse gehen, wo du nichts anfassen darfst',
    aEn: 'go to a party in a barn in the countryside',
    bEn: 'go to a party in a fancy penthouse where you can’t touch anything',
  },
  {
    a: 'nie wieder auf eine Party eingeladen werden',
    b: 'zu jeder Party eingeladen werden und nie absagen dürfen',
    aEn: 'never get invited to a party again',
    bEn: 'get invited to every party and never be allowed to say no',
  },
];
