import type { WouldYouRatherSeed } from './types';

export const sexualQuestions: WouldYouRatherSeed[] = [
  {
    a: 'nie wieder küssen, aber weiter Sex haben dürfen',
    b: 'nie wieder Sex haben, aber weiter küssen dürfen',
    aEn: 'never kiss again but still have sex',
    bEn: 'never have sex again but still kiss',
  },
  {
    a: 'beim Rummachen von deinen Eltern erwischt werden',
    b: 'deine Eltern beim Rummachen erwischen',
    aEn: 'get caught making out by your parents',
    bEn: 'catch your parents making out',
  },
  {
    a: 'jemanden küssen, der gerade Döner mit extra Zwiebeln gegessen hat',
    b: 'jemanden küssen, der viel zu viel Zunge einsetzt',
    aEn: 'kiss someone who just ate a kebab with extra onions',
    bEn: 'kiss someone who uses way too much tongue',
  },
  {
    a: 'deinen allerersten Kuss noch einmal erleben',
    b: 'deinen schlechtesten Kuss vor allen nachspielen',
    aEn: 'relive your very first kiss',
    bEn: 'reenact your worst kiss in front of everyone',
  },
  {
    a: 'einen filmreifen Kuss im strömenden Regen bekommen',
    b: 'einen heimlichen Kuss in der Abstellkammer einer Party bekommen',
    aEn: 'get a movie-worthy kiss in the pouring rain',
    bEn: 'get a secret kiss in the storage room at a party',
  },
  {
    a: 'nur noch mit geschlossenen Augen küssen können',
    b: 'nur noch mit offenen Augen küssen können',
    aEn: 'only be able to kiss with your eyes closed',
    bEn: 'only be able to kiss with your eyes open',
  },
  {
    a: 'beim Knutschen niesen müssen',
    b: 'beim Knutschen Schluckauf bekommen',
    aEn: 'sneeze while making out',
    bEn: 'get the hiccups while making out',
  },
  {
    a: 'mit deinem Schwarm Flaschendrehen spielen',
    b: 'mit deinem Schwarm sieben Minuten im Schrank verbringen',
    aEn: 'play spin the bottle with your crush',
    bEn: 'spend seven minutes in the closet with your crush',
  },
  {
    a: 'jeden Kuss, den du gibst, bewertet bekommen',
    b: 'jeden Kuss, den du bekommst, laut bewerten müssen',
    aEn: 'have every kiss you give get rated',
    bEn: 'have to rate every kiss you get out loud',
  },
  {
    a: 'dass dein Date dein komplettes Tinder-Profil laut vorliest',
    b: 'dass dein Date deine letzten zehn Matches sieht',
    aEn: 'have your date read your entire Tinder profile out loud',
    bEn: 'have your date see your last ten matches',
  },
  {
    a: 'auf einem Date deinen Ex treffen',
    b: 'auf einem Date den Ex deines Dates treffen',
    aEn: 'run into your ex on a date',
    bEn: 'run into your date’s ex on a date',
  },
  {
    a: 'auf ein Blind Date gehen, das deine Mutter ausgesucht hat',
    b: 'auf ein Blind Date gehen, das deine besten Freunde ausgesucht haben',
    aEn: 'go on a blind date your mom picked',
    bEn: 'go on a blind date your best friends picked',
  },
  {
    a: 'schon beim ersten Date küssen',
    b: 'mit dem ersten Kuss bis zum fünften Date warten',
    aEn: 'kiss on the very first date',
    bEn: 'wait until the fifth date for the first kiss',
  },
  {
    a: 'jemanden daten, der perfekt küsst, aber im Bett langweilig ist',
    b: 'jemanden daten, der schlecht küsst, aber im Bett fantastisch ist',
    aEn: 'date someone who kisses perfectly but is boring in bed',
    bEn: 'date someone who kisses badly but is amazing in bed',
  },
  {
    a: 'Leute nur noch über Dating-Apps kennenlernen',
    b: 'Leute nur noch im echten Leben ansprechen dürfen',
    aEn: 'only meet people through dating apps',
    bEn: 'only be allowed to approach people in real life',
  },
  {
    a: 'deine Dating-Bio von deiner Oma schreiben lassen',
    b: 'deine Profilfotos von deinem Ex aussuchen lassen',
    aEn: 'have your dating bio written by your grandma',
    bEn: 'have your profile pictures picked by your ex',
  },
  {
    a: 'nach einem tollen Date geghostet werden',
    b: 'mitten im Date sitzen gelassen werden',
    aEn: 'get ghosted after a great date',
    bEn: 'get walked out on in the middle of a date',
  },
  {
    a: 'ein Date mit jemandem haben, der nur über den Ex redet',
    b: 'ein Date mit jemandem haben, der nur über Krypto redet',
    aEn: 'go on a date with someone who only talks about their ex',
    bEn: 'go on a date with someone who only talks about crypto',
  },
  {
    a: 'ein erstes Date haben, bei dem ihr nur knutscht und kaum redet',
    b: 'ein erstes Date haben, bei dem ihr stundenlang redet, aber euch nicht küsst',
    aEn: 'have a first date where you just make out and barely talk',
    bEn: 'have a first date where you talk for hours but never kiss',
  },
  {
    a: 'dein erstes Date in einer Sauna haben',
    b: 'dein erstes Date in einem Paartanzkurs haben',
    aEn: 'have your first date in a sauna',
    bEn: 'have your first date at a couples dance class',
  },
  {
    a: 'jemanden daten, der genau wie dein Ex aussieht',
    b: 'jemanden daten, der sich genau wie einer deiner Elternteile verhält',
    aEn: 'date someone who looks exactly like your ex',
    bEn: 'date someone who acts exactly like one of your parents',
  },
  {
    a: 'eine Nacht mit deinem Promi-Crush verbringen',
    b: 'eine Woche Urlaub mit deinem Promi-Crush machen, aber ohne Sex',
    aEn: 'spend one night with your celebrity crush',
    bEn: 'spend a week on vacation with your celebrity crush, but no sex',
  },
  {
    a: 'jedes Date mit einem Kuss beenden müssen',
    b: 'jedes Date mit einem Handschlag beenden müssen',
    aEn: 'have to end every date with a kiss',
    bEn: 'have to end every date with a handshake',
  },
  {
    a: 'nur noch per Sprachnachricht flirten',
    b: 'nur noch per handgeschriebenem Brief flirten',
    aEn: 'only flirt via voice messages',
    bEn: 'only flirt via handwritten letters',
  },
  {
    a: 'einen One-Night-Stand mit einer Kollegin oder einem Kollegen haben',
    b: 'einen One-Night-Stand mit der besten Freundin oder dem besten Freund deines Ex haben',
    aEn: 'have a one-night stand with a coworker',
    bEn: 'have a one-night stand with your ex’s best friend',
  },
  {
    a: 'dass dein Date heimlich deine Freunde über dich ausfragt',
    b: 'dass dein Date heimlich dein Instagram bis 2015 durchscrollt',
    aEn: 'have your date secretly quiz your friends about you',
    bEn: 'have your date secretly scroll your Instagram back to 2015',
  },
  {
    a: 'beim Speed-Dating jedem denselben Witz erzählen müssen',
    b: 'beim Speed-Dating nur in Reimen sprechen dürfen',
    aEn: 'have to tell everyone the same joke at speed dating',
    bEn: 'only be allowed to speak in rhymes at speed dating',
  },
  {
    a: 'einen Abend lang einen Flirt-Coach im Ohr haben',
    b: 'einen Abend lang jeden Anmachspruch deiner Freunde benutzen müssen',
    aEn: 'have a flirting coach in your earpiece for a night',
    bEn: 'have to use every pickup line your friends feed you for a night',
  },
  {
    a: 'jemanden mit einem furchtbaren Anmachspruch rumkriegen',
    b: 'dich mit einem furchtbaren Anmachspruch rumkriegen lassen',
    aEn: 'win someone over with a terrible pickup line',
    bEn: 'get won over by a terrible pickup line',
  },
  {
    a: 'nur noch mit Licht an Sex haben',
    b: 'nur noch im Stockdunkeln Sex haben',
    aEn: 'only have sex with the lights on',
    bEn: 'only have sex in pitch darkness',
  },
  {
    a: 'beim Sex einen Lachanfall bekommen',
    b: 'beim Sex aus Versehen den falschen Namen sagen',
    aEn: 'get a laughing fit during sex',
    bEn: 'accidentally say the wrong name during sex',
  },
  {
    a: 'ein Jahr lang keinen Sex haben',
    b: 'ein Jahr lang keinen Alkohol trinken',
    aEn: 'go a year without sex',
    bEn: 'go a year without alcohol',
  },
  {
    a: 'nur noch Quickies haben',
    b: 'nur noch stundenlangen Sex haben',
    aEn: 'only ever have quickies',
    bEn: 'only ever have hours-long sex',
  },
  {
    a: 'dass deine Nachbarn jedes Mal alles mithören',
    b: 'dass dein Bett bei jeder Bewegung laut quietscht',
    aEn: 'have your neighbors hear everything every time',
    bEn: 'have your bed squeak loudly with every move',
  },
  {
    a: 'Sex nur noch morgens direkt nach dem Aufwachen haben',
    b: 'Sex nur noch mitten in der Nacht haben',
    aEn: 'only have sex right after waking up',
    bEn: 'only have sex in the middle of the night',
  },
  {
    a: 'beim Sex einen Wadenkrampf bekommen',
    b: 'beim Sex aus dem Bett fallen',
    aEn: 'get a calf cramp during sex',
    bEn: 'fall out of bed during sex',
  },
  {
    a: 'dass dein Mitbewohner mitten beim Sex ins Zimmer platzt',
    b: 'dass mitten beim Sex deine Mutter anruft und es nicht aufhört zu klingeln',
    aEn: 'have your roommate burst in during sex',
    bEn: 'have your mom call during sex and the phone won’t stop ringing',
  },
  {
    a: 'Sex am Strand haben',
    b: 'Sex im Zelt auf einem Festival haben',
    aEn: 'have sex on a beach',
    bEn: 'have sex in a tent at a festival',
  },
  {
    a: 'einmal Sex in einem Schloss haben',
    b: 'einmal Sex in einem Baumhaus haben',
    aEn: 'have sex in a castle once',
    bEn: 'have sex in a treehouse once',
  },
  {
    a: 'nie wieder Oralsex bekommen',
    b: 'nie wieder Oralsex geben dürfen',
    aEn: 'never receive oral sex again',
    bEn: 'never be allowed to give oral sex again',
  },
  {
    a: 'jemanden im Bett haben, der ununterbrochen redet',
    b: 'jemanden im Bett haben, der komplett still ist',
    aEn: 'have a partner who talks nonstop in bed',
    bEn: 'have a partner who’s completely silent in bed',
  },
  {
    a: 'beim Dirty Talk komplett versagen',
    b: 'beim Strippen am Reißverschluss hängen bleiben',
    aEn: 'totally fail at dirty talk',
    bEn: 'get stuck on a zipper while stripping',
  },
  {
    a: 'einen Striptease für deinen Partner aufführen',
    b: 'von deinem Partner vor deinen Freunden einen Lapdance bekommen',
    aEn: 'perform a striptease for your partner',
    bEn: 'get a lap dance from your partner in front of your friends',
  },
  {
    a: 'allen deine Sex-Playlist vorspielen',
    b: 'allen deinen Kosenamen aus dem Schlafzimmer verraten',
    aEn: 'play your sex playlist for everyone',
    bEn: 'tell everyone your bedroom pet name',
  },
  {
    a: 'beim Sex immer Socken anbehalten müssen',
    b: 'beim Sex immer Schlager laufen haben',
    aEn: 'always have to keep your socks on during sex',
    bEn: 'always have cheesy German pop playing during sex',
  },
  {
    a: 'deinem Partner deine wildeste Fantasie beichten',
    b: 'die wildeste Fantasie deines Partners erfahren',
    aEn: 'confess your wildest fantasy to your partner',
    bEn: 'find out your partner’s wildest fantasy',
  },
  {
    a: 'für immer nur noch Missionarsstellung haben',
    b: 'nie wieder Missionarsstellung haben dürfen',
    aEn: 'only ever do missionary',
    bEn: 'never be allowed to do missionary again',
  },
  {
    a: 'Sex mit Schlagsahne ausprobieren',
    b: 'Sex mit Eiswürfeln ausprobieren',
    aEn: 'try sex with whipped cream',
    bEn: 'try sex with ice cubes',
  },
  {
    a: 'dass dein Partner beim Sex einschläft',
    b: 'beim Sex selbst einschlafen',
    aEn: 'have your partner fall asleep during sex',
    bEn: 'fall asleep during sex yourself',
  },
  {
    a: 'nach dem Sex kuscheln müssen, obwohl ihr beide schwitzt',
    b: 'nach dem Sex sofort aufstehen müssen',
    aEn: 'have to cuddle after sex even though you’re both sweaty',
    bEn: 'have to get up right after sex',
  },
  {
    a: 'deinem Partner deine komplette Sexgeschichte erzählen',
    b: 'die komplette Sexgeschichte deines Partners hören',
    aEn: 'tell your partner your entire sexual history',
    bEn: 'hear your partner’s entire sexual history',
  },
  {
    a: 'deinen Bodycount vor allen verraten',
    b: 'den Bodycount von allen hier erfahren, aber nichts sagen dürfen',
    aEn: 'reveal your body count to everyone',
    bEn: 'learn everyone’s body count here but not be allowed to say anything',
  },
  {
    a: 'dass dein Toy bei der Sicherheitskontrolle am Flughafen ausgepackt wird',
    b: 'dass dein Toy im Handgepäck plötzlich anfängt zu brummen',
    aEn: 'have your toy unpacked at airport security',
    bEn: 'have your toy suddenly start buzzing in your carry-on',
  },
  {
    a: 'im Bett gefesselt werden',
    b: 'im Bett die Augen verbunden bekommen',
    aEn: 'get tied up in bed',
    bEn: 'get blindfolded in bed',
  },
  {
    a: 'ein Safeword haben, bei dem du jedes Mal lachen musst',
    b: 'ein Safeword haben, das viel zu lang ist',
    aEn: 'have a safeword that makes you laugh every time',
    bEn: 'have a safeword that’s way too long',
  },
  {
    a: 'ein Rollenspiel als Fremde in einer Hotelbar spielen',
    b: 'ein Rollenspiel als Pizzabote und Kundschaft spielen',
    aEn: 'role-play as strangers in a hotel bar',
    bEn: 'role-play as the pizza delivery person and the customer',
  },
  {
    a: 'dass dein Partner auf ein Kostüm steht, das du albern findest',
    b: 'dass dein Partner deine Lieblingsfantasie albern findet',
    aEn: 'have your partner love a costume you think is silly',
    bEn: 'have your partner think your favorite fantasy is silly',
  },
  {
    a: 'eine Nacht in einem Hotelzimmer mit Spiegeldecke verbringen',
    b: 'eine Nacht in einem Iglu-Hotel verbringen',
    aEn: 'spend a night in a hotel room with a mirrored ceiling',
    bEn: 'spend a night in an igloo hotel',
  },
  {
    a: 'aus Versehen eine heiße Nachricht in den Familienchat schicken',
    b: 'aus Versehen eine heiße Nachricht an deinen Chef schicken',
    aEn: 'accidentally send a spicy text to the family group chat',
    bEn: 'accidentally send a spicy text to your boss',
  },
  {
    a: 'nur noch per Sprachnachricht sexten',
    b: 'nur noch mit Emojis sexten',
    aEn: 'only sext via voice messages',
    bEn: 'only sext using emojis',
  },
  {
    a: 'eine Woche lang keine Unterwäsche tragen',
    b: 'eine Woche lang nur sexy Dessous tragen, auch beim Sport',
    aEn: 'go a week without underwear',
    bEn: 'wear only sexy lingerie for a week, even at the gym',
  },
  {
    a: 'dass dein Date deine hässlichste Unterhose sieht',
    b: 'dass dein Date dein ungemachtes, chaotisches Zimmer sieht',
    aEn: 'have your date see your ugliest underwear',
    bEn: 'have your date see your messy, unmade room',
  },
  {
    a: 'mit jemandem schlafen, der viel zu laut ist',
    b: 'mit jemandem schlafen, der dabei komische Grimassen schneidet',
    aEn: 'sleep with someone who’s way too loud',
    bEn: 'sleep with someone who makes weird faces',
  },
  {
    a: 'dass dein Partner nach dem Sex sofort am Handy hängt',
    b: 'dass dein Partner nach dem Sex sofort schnarcht',
    aEn: 'have your partner grab their phone right after sex',
    bEn: 'have your partner start snoring right after sex',
  },
  {
    a: 'für eine Nacht einen Dreier ausprobieren',
    b: 'für eine Nacht einen Swingerclub besuchen',
    aEn: 'try a threesome for one night',
    bEn: 'visit a swingers club for one night',
  },
  {
    a: 'mit deinem Partner einen Tantra-Workshop besuchen',
    b: 'mit deinem Partner zusammen einen Erotikfilm schauen',
    aEn: 'attend a tantra workshop with your partner',
    bEn: 'watch an erotic movie together with your partner',
  },
  {
    a: 'mit deiner Mutter in einen Sexshop gehen',
    b: 'mit deinem Chef in einen Sexshop gehen',
    aEn: 'go to a sex shop with your mom',
    bEn: 'go to a sex shop with your boss',
  },
  {
    a: 'dass dein Erotik-Paket aus Versehen zu deinen Eltern geliefert wird',
    b: 'dass der Paketbote dein Erotik-Paket vor deinen Nachbarn öffnet',
    aEn: 'have your adult package accidentally delivered to your parents',
    bEn: 'have the delivery guy open your adult package in front of your neighbors',
  },
  {
    a: 'nie wieder Vorspiel haben',
    b: 'für immer nur noch Vorspiel haben',
    aEn: 'never have foreplay again',
    bEn: 'only ever have foreplay',
  },
  {
    a: 'dass dein Partner dein Handy durchsucht',
    b: 'dass dein Partner dein altes Tagebuch liest',
    aEn: 'have your partner go through your phone',
    bEn: 'have your partner read your old diary',
  },
  {
    a: 'mit deinem Ex befreundet bleiben',
    b: 'deinen Ex nie wiedersehen',
    aEn: 'stay friends with your ex',
    bEn: 'never see your ex again',
  },
  {
    a: 'mit einem Ex wieder zusammenkommen',
    b: 'den Ex deiner besten Freundin oder deines besten Freundes daten',
    aEn: 'get back together with an ex',
    bEn: 'date your best friend’s ex',
  },
  {
    a: 'eine offene Beziehung führen',
    b: 'eine Fernbeziehung führen',
    aEn: 'be in an open relationship',
    bEn: 'be in a long-distance relationship',
  },
  {
    a: 'deinem Partner jeden Crush beichten müssen',
    b: 'jeden Crush deines Partners erfahren',
    aEn: 'have to confess every crush to your partner',
    bEn: 'find out every crush your partner has',
  },
  {
    a: 'mit jemandem zusammen sein, der extrem eifersüchtig ist',
    b: 'mit jemandem zusammen sein, der nie eifersüchtig ist',
    aEn: 'be with someone who’s extremely jealous',
    bEn: 'be with someone who’s never jealous',
  },
  {
    a: 'jeden Tag einen Liebesbrief von deinem Partner bekommen',
    b: 'jeden Tag ein heißes Foto von deinem Partner bekommen',
    aEn: 'get a love letter from your partner every day',
    bEn: 'get a hot photo from your partner every day',
  },
  {
    a: 'beim Kennenlernen immer den ersten Schritt machen müssen',
    b: 'beim Kennenlernen nie den ersten Schritt machen dürfen',
    aEn: 'always have to make the first move when meeting someone',
    bEn: 'never be allowed to make the first move when meeting someone',
  },
  {
    a: 'dass deine Freunde deinen Partner nicht ausstehen können',
    b: 'dass deine Familie deinen Partner nicht ausstehen kann',
    aEn: 'have your friends not stand your partner',
    bEn: 'have your family not stand your partner',
  },
  {
    a: 'einen Heiratsantrag vor tausend Leuten bekommen',
    b: 'einen Heiratsantrag im Bett in Unterwäsche bekommen',
    aEn: 'get proposed to in front of a thousand people',
    bEn: 'get proposed to in bed in your underwear',
  },
  {
    a: 'mit deinem besten Freund schlafen und die Freundschaft riskieren',
    b: 'nie erfahren, wie es mit deinem besten Freund gewesen wäre',
    aEn: 'sleep with your best friend and risk the friendship',
    bEn: 'never find out what it would’ve been like with your best friend',
  },
  {
    a: 'eine Freundschaft Plus haben',
    b: 'eine feste Beziehung ganz ohne Sex haben',
    aEn: 'have a friends-with-benefits thing',
    bEn: 'have a committed relationship with no sex at all',
  },
  {
    a: 'deinem Partner gestehen, dass du schon mal etwas vorgespielt hast',
    b: 'erfahren, dass dein Partner dir schon mal etwas vorgespielt hat',
    aEn: 'confess to your partner that you’ve faked it before',
    bEn: 'find out your partner has faked it with you before',
  },
  {
    a: 'dass dein Partner mit all deinen Freunden flirtet',
    b: 'dass dein Partner mit niemandem flirtet, nicht mal mit dir',
    aEn: 'have a partner who flirts with all your friends',
    bEn: 'have a partner who flirts with no one, not even you',
  },
  {
    a: 'zehn Jahre lang nur mit derselben Person schlafen',
    b: 'zehn Jahre lang jeden Monat jemand Neues daten',
    aEn: 'sleep with only the same person for ten years',
    bEn: 'date someone new every month for ten years',
  },
  {
    a: 'deinen Seelenverwandten finden, aber der Sex ist mittelmäßig',
    b: 'den besten Sex deines Lebens haben, aber euch nichts zu sagen haben',
    aEn: 'find your soulmate but the sex is mediocre',
    bEn: 'have the best sex of your life but nothing to talk about',
  },
  {
    a: 'jede Woche etwas Neues im Bett ausprobieren müssen',
    b: 'für immer bei derselben perfekten Routine im Bett bleiben',
    aEn: 'have to try something new in bed every week',
    bEn: 'stick to the same perfect routine in bed forever',
  },
  {
    a: 'auf einer Hochzeit neben deinem Ex sitzen',
    b: 'auf einer Hochzeit neben dem neuen Partner deines Ex sitzen',
    aEn: 'sit next to your ex at a wedding',
    bEn: 'sit next to your ex’s new partner at a wedding',
  },
  {
    a: 'von deinem Ex betrunken angerufen werden',
    b: 'deinen Ex betrunken anrufen',
    aEn: 'get a drunk call from your ex',
    bEn: 'drunk-call your ex',
  },
  {
    a: 'deinem Ex eine öffentliche Bewertung als Liebhaber schreiben',
    b: 'von deinem Ex eine öffentliche Bewertung als Liebhaber bekommen',
    aEn: 'write your ex a public review as a lover',
    bEn: 'get a public review as a lover from your ex',
  },
  {
    a: 'dass dein Partner schon mit 50 Leuten geschlafen hat',
    b: 'dass dein Partner noch nie mit jemandem geschlafen hat',
    aEn: 'have a partner who’s slept with 50 people',
    bEn: 'have a partner who’s never slept with anyone',
  },
  {
    a: 'nach drei Wochen einen Heiratsantrag bekommen',
    b: 'nach drei Jahren immer noch kein „Ich liebe dich“ gehört haben',
    aEn: 'get proposed to after three weeks',
    bEn: 'still not have heard "I love you" after three years',
  },
  {
    a: 'mit jemandem zusammen sein, der mehrmals täglich Sex will',
    b: 'mit jemandem zusammen sein, der nur einmal im Monat Lust hat',
    aEn: 'be with someone who wants sex several times a day',
    bEn: 'be with someone who’s only in the mood once a month',
  },
  {
    a: 'deine Hochzeitsnacht mit den Schwiegereltern im Nebenzimmer verbringen',
    b: 'deine Hochzeitsnacht komplett verschlafen',
    aEn: 'spend your wedding night with your in-laws in the next room',
    bEn: 'sleep through your entire wedding night',
  },
  {
    a: 'dass dein Partner im Schlaf einen fremden Namen murmelt',
    b: 'im Schlaf den Namen deines Ex murmeln',
    aEn: 'have your partner mumble a stranger’s name in their sleep',
    bEn: 'mumble your ex’s name in your sleep',
  },
  {
    a: 'zusehen, wie dein Partner mit einer heißen fremden Person flirtet',
    b: 'mit einer heißen fremden Person flirten, während dein Partner zusieht',
    aEn: 'watch your partner flirt with a hot stranger',
    bEn: 'flirt with a hot stranger while your partner watches',
  },
  {
    a: 'dass dein Ex einen Hit über eure Beziehung schreibt',
    b: 'dass dein Ex ein Buch über eure Beziehung schreibt',
    aEn: 'have your ex write a hit song about your relationship',
    bEn: 'have your ex write a book about your relationship',
  },
  {
    a: 'dass dein Partner eine emotionale Affäre hat',
    b: 'dass dein Partner einen rein körperlichen Seitensprung hat',
    aEn: 'have your partner have an emotional affair',
    bEn: 'have your partner have a purely physical fling',
  },
  {
    a: 'dass euer Liebesleben eine Netflix-Doku wird',
    b: 'dass euer Liebesleben ein Podcast wird, den deine Familie hört',
    aEn: 'have your love life turned into a Netflix documentary',
    bEn: 'have your love life turned into a podcast your family listens to',
  },
  {
    a: 'nach einem One-Night-Stand den Namen nicht mehr wissen',
    b: 'nach einem One-Night-Stand zugeben müssen, dass du einen falschen Namen genannt hast',
    aEn: 'forget their name after a one-night stand',
    bEn: 'have to admit you gave a fake name after a one-night stand',
  },
  {
    a: 'den Walk of Shame im Partyoutfit vom Vorabend machen',
    b: 'den Walk of Shame in geliehenen Klamotten deines Dates machen',
    aEn: 'do the walk of shame in last night’s party outfit',
    bEn: 'do the walk of shame in clothes borrowed from your date',
  },
  {
    a: 'nach einem One-Night-Stand zum Frühstück bleiben',
    b: 'dich morgens heimlich rausschleichen',
    aEn: 'stay for breakfast after a one-night stand',
    bEn: 'sneak out quietly in the morning',
  },
  {
    a: 'mit jemandem aus deinem Fitnessstudio etwas anfangen',
    b: 'mit jemandem aus deinem Haus etwas anfangen',
    aEn: 'hook up with someone from your gym',
    bEn: 'hook up with someone from your building',
  },
  {
    a: 'auf einer Hochzeit mit einem Gast rummachen',
    b: 'auf der Firmenfeier mit jemandem aus dem Team rummachen',
    aEn: 'make out with a guest at a wedding',
    bEn: 'make out with someone from your team at the office party',
  },
  {
    a: 'eine heiße Urlaubsromanze haben, die nach einer Woche endet',
    b: 'eine lauwarme Romanze haben, die ein Jahr hält',
    aEn: 'have a hot vacation fling that ends after a week',
    bEn: 'have a lukewarm romance that lasts a year',
  },
  {
    a: 'jemanden in der Bahn ansprechen, der dir gefällt',
    b: 'jemandem an der Bar wortlos einen Drink ausgeben',
    aEn: 'talk to someone you like on the train',
    bEn: 'buy someone a drink at the bar without saying a word',
  },
  {
    a: 'um drei Uhr nachts eine Booty-Call-Nachricht bekommen',
    b: 'um drei Uhr nachts eine Booty-Call-Nachricht schicken',
    aEn: 'get a booty call text at 3 a.m.',
    bEn: 'send a booty call text at 3 a.m.',
  },
  {
    a: 'dass dein Hookup beim Frühstück deine Eltern kennenlernt',
    b: 'dass dein Hookup deinem Mitbewohner sein Herz ausschüttet',
    aEn: 'have your hookup meet your parents at breakfast',
    bEn: 'have your hookup pour their heart out to your roommate',
  },
  {
    a: 'dass dein One-Night-Stand am nächsten Tag dein neuer Kollege ist',
    b: 'dass dein One-Night-Stand am nächsten Tag dein neuer Vermieter ist',
    aEn: 'have your one-night stand turn out to be your new coworker',
    bEn: 'have your one-night stand turn out to be your new landlord',
  },
  {
    a: 'dass dir beim Sex ein Pups entwischt',
    b: 'dass dein Magen beim Sex laut knurrt',
    aEn: 'let one slip during sex',
    bEn: 'have your stomach growl loudly during sex',
  },
  {
    a: 'dass dein Haustier beim Sex zuschaut',
    b: 'dass dein Haustier beim Sex aufs Bett springt',
    aEn: 'have your pet watch you during sex',
    bEn: 'have your pet jump on the bed during sex',
  },
  {
    a: 'beim Ausziehen mit dem Kopf im Pulli stecken bleiben',
    b: 'beim Ausziehen über deine eigene Hose stolpern',
    aEn: 'get your head stuck in your sweater while undressing',
    bEn: 'trip over your own pants while undressing',
  },
  {
    a: 'dass das Bett unter euch zusammenbricht',
    b: 'dass der Rauchmelder wegen eurer Duftkerzen losgeht',
    aEn: 'have the bed collapse under you',
    bEn: 'have the smoke alarm go off because of your scented candles',
  },
  {
    a: 'beim ersten Mal mit jemandem das Kondom falsch herum aufsetzen',
    b: 'beim ersten Mal mit jemandem den BH nicht aufbekommen',
    aEn: 'put the condom on the wrong way your first time with someone',
    bEn: 'not be able to undo the bra your first time with someone',
  },
  {
    a: 'dass dein Partner deine Geräusche im Bett nachmacht',
    b: 'dass deine Freunde deine Geräusche im Bett durch die Wand hören',
    aEn: 'have your partner imitate your bedroom noises',
    bEn: 'have your friends hear your bedroom noises through the wall',
  },
  {
    a: 'dass beim Sex deine Sprachassistentin anspringt',
    b: 'dass dein Smart Speaker beim Sex plötzlich die Nachrichten vorliest',
    aEn: 'have your voice assistant activate during sex',
    bEn: 'have your smart speaker suddenly read the news during sex',
  },
  {
    a: 'nach dem Sex merken, dass das Fenster sperrangelweit offen war',
    b: 'nach dem Sex merken, dass ihr die ganze Zeit auf einer Pizza gelegen habt',
    aEn: 'realize after sex that the window was wide open',
    bEn: 'realize after sex that you were lying on a pizza the whole time',
  },
  {
    a: 'dass deine Schwiegermutter dein Toy in der Spülmaschine findet',
    b: 'dass deine Schwiegermutter Handschellen in deinem Nachttisch findet',
    aEn: 'have your mother-in-law find your toy in the dishwasher',
    bEn: 'have your mother-in-law find handcuffs in your nightstand',
  },
  {
    a: 'beim Sex dein Lieblingslied mitsingen müssen',
    b: 'beim Sex die Tetris-Melodie im Kopf haben',
    aEn: 'have to sing along to your favorite song during sex',
    bEn: 'have the Tetris theme stuck in your head during sex',
  },
  {
    a: 'dass dein Partner beim Sex wie ein Sportkommentator redet',
    b: 'dass dein Partner beim Sex ständig Filmzitate bringt',
    aEn: 'have your partner talk like a sports commentator during sex',
    bEn: 'have your partner keep quoting movies during sex',
  },
  {
    a: 'dass dir im Meeting sexy Unterwäsche aus der Tasche fällt',
    b: 'dass deine sexy Unterwäsche bei deinen Eltern auf dem Wäscheständer hängt',
    aEn: 'have sexy underwear fall out of your bag in a meeting',
    bEn: 'have your sexy underwear hanging on your parents’ drying rack',
  },
  {
    a: 'mit einem riesigen Knutschfleck zur Familienfeier gehen',
    b: 'mit einem riesigen Knutschfleck zum Vorstellungsgespräch gehen',
    aEn: 'go to a family party with a huge hickey',
    bEn: 'go to a job interview with a huge hickey',
  },
  {
    a: 'im Bett etwas Neues ausprobieren und dir dabei einen Muskel zerren',
    b: 'im Bett etwas Neues ausprobieren und es megapeinlich finden',
    aEn: 'try something new in bed and pull a muscle',
    bEn: 'try something new in bed and find it super cringe',
  },
  {
    a: 'bei deinen Eltern mit deinem Partner Wand an Wand zu ihrem Schlafzimmer schlafen',
    b: 'bei deinen Eltern in getrennten Zimmern schlafen müssen',
    aEn: 'stay at your parents’ with your partner, right next to their bedroom',
    bEn: 'stay at your parents’ and have to sleep in separate rooms',
  },
  {
    a: 'dass beim Flirten deine Gedanken laut ausgesprochen werden',
    b: 'beim Flirten immer knallrot werden',
    aEn: 'have your thoughts spoken out loud while flirting',
    bEn: 'always turn bright red when flirting',
  },
  {
    a: 'nur noch Leute attraktiv finden, die schlecht für dich sind',
    b: 'nur noch Leute attraktiv finden, die total langweilig sind',
    aEn: 'only be attracted to people who are bad for you',
    bEn: 'only be attracted to people who are totally boring',
  },
  {
    a: 'dass dein Crush dich nur als guten Freund sieht',
    b: 'dass dein Crush dich heiß, aber ziemlich dumm findet',
    aEn: 'have your crush only see you as a good friend',
    bEn: 'have your crush think you’re hot but pretty dumb',
  },
  {
    a: 'deinem Crush deine Gefühle in einem Brief gestehen',
    b: 'deinem Crush deine Gefühle betrunken gestehen',
    aEn: 'confess your feelings to your crush in a letter',
    bEn: 'confess your feelings to your crush while drunk',
  },
  {
    a: 'immer wissen, wer heimlich auf dich steht',
    b: 'auf alle unwiderstehlich wirken, aber nie wissen, ob es echt ist',
    aEn: 'always know who secretly has a thing for you',
    bEn: 'seem irresistible to everyone but never know if it’s real',
  },
  {
    a: 'eine unglaublich sexy Stimme haben',
    b: 'einen unglaublich sexy Körper haben',
    aEn: 'have an incredibly sexy voice',
    bEn: 'have an incredibly sexy body',
  },
  {
    a: 'den perfekten Hintern haben',
    b: 'das perfekte Lächeln haben',
    aEn: 'have the perfect butt',
    bEn: 'have the perfect smile',
  },
  {
    a: 'mit Blicken flirten können wie ein Profi',
    b: 'mit Worten flirten können wie ein Profi',
    aEn: 'flirt with your eyes like a pro',
    bEn: 'flirt with words like a pro',
  },
  {
    a: 'jemanden daten, dessen Akzent dich schwach macht',
    b: 'jemanden daten, dessen Hände dich schwach machen',
    aEn: 'date someone whose accent makes you weak',
    bEn: 'date someone whose hands make you weak',
  },
  {
    a: 'dass dir beim Flirten Spinat zwischen den Zähnen hängt',
    b: 'dass beim Flirten dein Hosenstall offen steht',
    aEn: 'have spinach in your teeth while flirting',
    bEn: 'have your fly down while flirting',
  },
  {
    a: 'nur noch mit Augenkontakt flirten dürfen',
    b: 'nur noch über Reaktionen auf Instagram-Storys flirten dürfen',
    aEn: 'only be allowed to flirt with eye contact',
    bEn: 'only be allowed to flirt by reacting to Instagram stories',
  },
  {
    a: 'dass dein Crush sieht, dass du seine alten Fotos geliked hast',
    b: 'dass dein Crush sieht, wie oft du sein Profil anschaust',
    aEn: 'have your crush see you liked their old photos',
    bEn: 'have your crush see how often you check their profile',
  },
  {
    a: 'dass dein Crush dich verkatert im Jogginganzug sieht',
    b: 'dass dein Crush dich beim Singen unter der Dusche hört',
    aEn: 'have your crush see you hungover in sweatpants',
    bEn: 'have your crush hear you singing in the shower',
  },
  {
    a: 'dich in jemanden verlieben, der vergeben ist',
    b: 'jemanden lieben, der dich nur körperlich will',
    aEn: 'fall for someone who’s taken',
    bEn: 'love someone who only wants you physically',
  },
  {
    a: 'dass alle deine Freunde deinen Partner heiß finden',
    b: 'dass außer dir niemand deinen Partner heiß findet',
    aEn: 'have all your friends find your partner hot',
    bEn: 'have nobody but you find your partner hot',
  },
  {
    a: 'sofort Funken spüren, die nach einem Monat verpuffen',
    b: 'erst nach Monaten Gefühle entwickeln, die dann ewig halten',
    aEn: 'feel instant sparks that fizzle out after a month',
    bEn: 'develop feelings only after months, but they last forever',
  },
  {
    a: 'einen Partner haben, der umwerfend sexy, aber humorlos ist',
    b: 'einen Partner haben, der urkomisch, aber kein bisschen sexy ist',
    aEn: 'have a partner who’s stunningly sexy but humorless',
    bEn: 'have a partner who’s hilarious but not sexy at all',
  },
  {
    a: 'dass dein Promi-Crush deinen durstigen Kommentar liest',
    b: 'dass dein Promi-Crush deine Fanfiction über sich liest',
    aEn: 'have your celebrity crush read your thirsty comment',
    bEn: 'have your celebrity crush read your fan fiction about them',
  },
  {
    a: 'dich nur noch zu Leuten hingezogen fühlen, die Socken in Sandalen tragen',
    b: 'dich nur noch zu Leuten hingezogen fühlen, die laut schmatzen',
    aEn: 'only be attracted to people who wear socks with sandals',
    bEn: 'only be attracted to people who chew loudly',
  },
  {
    a: 'bei jedem Flirt ein Zitat aus einem Liebesfilm benutzen müssen',
    b: 'bei jedem Flirt einen Flachwitz erzählen müssen',
    aEn: 'have to use a romance movie quote every time you flirt',
    bEn: 'have to tell a dad joke every time you flirt',
  },
  {
    a: 'dass dein Date dein Lieblingsparfum hasst',
    b: 'dass dein Date nach etwas riecht, das du hasst',
    aEn: 'have your date hate your favorite perfume',
    bEn: 'have your date smell like something you hate',
  },
  {
    a: 'jemanden daten, der jede Nacht eng kuscheln will',
    b: 'jemanden daten, der beim Schlafen keine Berührung erträgt',
    aEn: 'date someone who wants to cuddle close every night',
    bEn: 'date someone who can’t stand being touched while sleeping',
  },
  {
    a: 'beim Sex von deinem Partner Anweisungen bekommen',
    b: 'beim Sex deinem Partner Anweisungen geben',
    aEn: 'take orders from your partner during sex',
    bEn: 'give your partner orders during sex',
  },
  {
    a: 'einen Fußfetisch haben',
    b: 'einen Achselfetisch haben',
    aEn: 'have a foot fetish',
    bEn: 'have an armpit fetish',
  },
  {
    a: 'einen Abend lang einen sexy Superheldenanzug tragen',
    b: 'einen Abend lang ein sexy Dinosaurierkostüm tragen',
    aEn: 'wear a sexy superhero suit for an evening',
    bEn: 'wear a sexy dinosaur costume for an evening',
  },
  {
    a: 'eine Vorliebe fürs Zuschauen haben',
    b: 'eine Vorliebe fürs Beobachtetwerden haben',
    aEn: 'have a thing for watching',
    bEn: 'have a thing for being watched',
  },
  {
    a: 'Spanking ausprobieren',
    b: 'Spiele mit heißem Kerzenwachs ausprobieren',
    aEn: 'try spanking',
    bEn: 'try playing with hot candle wax',
  },
  {
    a: 'Dirty Talk nur noch im tiefsten Bayerisch machen',
    b: 'Dirty Talk nur noch im Englisch von Shakespeare machen',
    aEn: 'only do dirty talk in the thickest Bavarian dialect',
    bEn: 'only do dirty talk in Shakespearean English',
  },
  {
    a: 'einen ganzen Tag auf einer Erotikmesse arbeiten',
    b: 'einen ganzen Tag in einem Sexshop an der Kasse sitzen',
    aEn: 'work a full day at an erotic fair',
    bEn: 'work a full day at a sex shop checkout',
  },
  {
    a: 'alle deine Kinks offen im Dating-Profil stehen haben',
    b: 'nie über deine Kinks reden dürfen',
    aEn: 'have all your kinks listed openly on your dating profile',
    bEn: 'never be allowed to talk about your kinks',
  },
  {
    a: 'Sex an einem Ort haben, an dem man erwischt werden könnte',
    b: 'Sex nur noch im eigenen Bett mit abgeschlossener Tür haben',
    aEn: 'have sex somewhere you might get caught',
    bEn: 'only have sex in your own bed with the door locked',
  },
  {
    a: 'beim Sex gekitzelt werden',
    b: 'beim Sex gebissen werden',
    aEn: 'get tickled during sex',
    bEn: 'get bitten during sex',
  },
  {
    a: 'deinen Partner mit einer Feder verwöhnen',
    b: 'deinen Partner mit warmem Massageöl verwöhnen',
    aEn: 'pamper your partner with a feather',
    bEn: 'pamper your partner with warm massage oil',
  },
  {
    a: 'jemanden daten, der im Bett Rollenspiele liebt',
    b: 'jemanden daten, der im Bett strikt Vanilla ist',
    aEn: 'date someone who loves role-play in bed',
    bEn: 'date someone who’s strictly vanilla in bed',
  },
  {
    a: 'eine einzige Kamasutra-Stellung perfekt beherrschen',
    b: 'zehn Kamasutra-Stellungen mittelmäßig beherrschen',
    aEn: 'master one Kama Sutra position perfectly',
    bEn: 'be mediocre at ten Kama Sutra positions',
  },
  {
    a: 'deine Sex-Bucketlist vor allen vorlesen',
    b: 'die Sex-Bucketlist deines Partners vor allen vorlesen',
    aEn: 'read your sex bucket list out to everyone',
    bEn: 'read your partner’s sex bucket list out to everyone',
  },
  {
    a: 'dass deine Freunde wissen, wie oft du Sex hast',
    b: 'dass deine Freunde wissen, mit wem du zuletzt geschlafen hast',
    aEn: 'have your friends know how often you have sex',
    bEn: 'have your friends know who you last slept with',
  },
  {
    a: 'bei Wahrheit oder Pflicht immer Wahrheit nehmen müssen',
    b: 'bei Wahrheit oder Pflicht immer Pflicht nehmen müssen',
    aEn: 'always have to pick truth in truth or dare',
    bEn: 'always have to pick dare in truth or dare',
  },
  {
    a: 'mit deinem Partner bei Temptation Island landen',
    b: 'mit deinem Ex bei Ex on the Beach landen',
    aEn: 'end up on Temptation Island with your partner',
    bEn: 'end up on Ex on the Beach with your ex',
  },
  {
    a: 'ein Jahr lang flirten, aber nie weitergehen dürfen',
    b: 'ein Jahr lang Sex haben, aber nie flirten dürfen',
    aEn: 'flirt for a year but never be allowed to go further',
    bEn: 'have sex for a year but never be allowed to flirt',
  },
  {
    a: 'nachts mit Freunden nacktbaden gehen',
    b: 'mit deinen Kollegen in eine gemischte Sauna gehen',
    aEn: 'go skinny-dipping with friends at night',
    bEn: 'go to a mixed sauna with your coworkers',
  },
  {
    a: 'nackt für einen Aktzeichenkurs Modell stehen',
    b: 'für einen Wohltätigkeitskalender in Unterwäsche posieren',
    aEn: 'pose nude for a life drawing class',
    bEn: 'pose in your underwear for a charity calendar',
  },
  {
    a: 'für dein Date nackt kochen',
    b: 'für dein Date nackt die Wohnung putzen',
    aEn: 'cook naked for your date',
    bEn: 'clean the apartment naked for your date',
  },
  {
    a: 'eine Woche lang nur nackt schlafen',
    b: 'eine Woche lang nur im Ganzkörper-Einteiler schlafen',
    aEn: 'sleep only naked for a week',
    bEn: 'sleep only in a full-body onesie for a week',
  },
  {
    a: 'dass dein Chef dich auf Tinder findet',
    b: 'dass dein Ex dich auf Tinder findet',
    aEn: 'have your boss find you on Tinder',
    bEn: 'have your ex find you on Tinder',
  },
  {
    a: 'jemanden nur durch Tanzen verführen dürfen',
    b: 'jemanden nur durch Kochen verführen dürfen',
    aEn: 'only be allowed to seduce someone by dancing',
    bEn: 'only be allowed to seduce someone by cooking',
  },
  {
    a: 'dein Liebesleben von einer KI bewerten lassen',
    b: 'dein Liebesleben von deiner Oma bewerten lassen',
    aEn: 'have your love life rated by an AI',
    bEn: 'have your love life rated by your grandma',
  },
  {
    a: 'ein Thirst-Trap-Foto posten, das nur deine Familie liked',
    b: 'ein Thirst-Trap-Foto posten, das nur dein Ex liked',
    aEn: 'post a thirst trap that only your family likes',
    bEn: 'post a thirst trap that only your ex likes',
  },
  {
    a: 'Sex in einer Hängematte ausprobieren',
    b: 'Sex in der Badewanne ausprobieren',
    aEn: 'try sex in a hammock',
    bEn: 'try sex in the bathtub',
  },
  {
    a: 'dass dein Partner im Bett immer zärtlich ist',
    b: 'dass dein Partner im Bett immer wild ist',
    aEn: 'have a partner who’s always tender in bed',
    bEn: 'have a partner who’s always wild in bed',
  },
  {
    a: 'von deinem Partner ein Aktgemälde von dir geschenkt bekommen',
    b: 'deinem Partner ein Aktgemälde von dir schenken',
    aEn: 'get a nude painting of yourself as a gift from your partner',
    bEn: 'give your partner a nude painting of yourself',
  },
  {
    a: 'den Valentinstag komplett im Bett verbringen',
    b: 'den Valentinstag mit einer verrückten Schnitzeljagd verbringen',
    aEn: 'spend all of Valentine’s Day in bed',
    bEn: 'spend Valentine’s Day on a wild scavenger hunt',
  },
  {
    a: 'mit jemandem schlafen, der sehr schüchtern ist',
    b: 'mit jemandem schlafen, der extrem selbstbewusst ist',
    aEn: 'sleep with someone who’s very shy',
    bEn: 'sleep with someone who’s extremely confident',
  },
  {
    a: 'beim Sex an deine Steuererklärung denken müssen',
    b: 'beim Sex an deinen Ex denken müssen',
    aEn: 'have to think about your taxes during sex',
    bEn: 'have to think about your ex during sex',
  },
  {
    a: 'ein Tattoo mit dem Namen deines Ex tragen',
    b: 'ein Tattoo mit dem Namen deines aktuellen Partners tragen',
    aEn: 'have a tattoo of your ex’s name',
    bEn: 'have a tattoo of your current partner’s name',
  },
  {
    a: 'allen den Inhalt deiner Nachttischschublade zeigen',
    b: 'allen zeigen, wem du heimlich auf Instagram folgst',
    aEn: 'show everyone what’s in your nightstand drawer',
    bEn: 'show everyone who you secretly follow on Instagram',
  },
  {
    a: 'deinen Partner mit einem sexy Outfit überraschen und ausgelacht werden',
    b: 'deinem Partner eine heiße Nachricht schicken, die erst am nächsten Tag gelesen wird',
    aEn: 'surprise your partner with a sexy outfit and get laughed at',
    bEn: 'send your partner a spicy text that doesn’t get read until the next day',
  },
  {
    a: 'beim Flirten Rotwein über dein Gegenüber kippen',
    b: 'beim Flirten dein Gegenüber aus Versehen anspucken',
    aEn: 'spill red wine on the person you’re flirting with',
    bEn: 'accidentally spit on the person you’re flirting with',
  },
  {
    a: 'dass dein Partner noch Fotos vom Ex aufhebt',
    b: 'dass dein Partner noch regelmäßig mit dem Ex schreibt',
    aEn: 'have your partner still keep photos of their ex',
    bEn: 'have your partner still text their ex regularly',
  },
  {
    a: 'heimlich in deinen Mitbewohner verknallt sein',
    b: 'heimlich in den Partner deines besten Freundes verknallt sein',
    aEn: 'secretly have a crush on your roommate',
    bEn: 'secretly have a crush on your best friend’s partner',
  },
  {
    a: 'mit jemandem zusammen sein, der umwerfend tanzt',
    b: 'mit jemandem zusammen sein, der umwerfend kocht',
    aEn: 'be with someone who dances amazingly',
    bEn: 'be with someone who cooks amazingly',
  },
  {
    a: 'beim Bildschirmteilen aus Versehen einen Erotik-Tab zeigen',
    b: 'beim Bildschirmteilen aus Versehen deinen Dating-Chat zeigen',
    aEn: 'accidentally show a spicy tab while screen sharing',
    bEn: 'accidentally show your dating chat while screen sharing',
  },
  {
    a: 'deine erste große Liebe heiraten',
    b: 'jemanden heiraten, den du erst mit 40 triffst',
    aEn: 'marry your first great love',
    bEn: 'marry someone you only meet at 40',
  },
  {
    a: 'nach dem Sex Komplimente für deine Technik bekommen',
    b: 'nach dem Sex Komplimente für dein Aussehen bekommen',
    aEn: 'get complimented on your technique after sex',
    bEn: 'get complimented on your looks after sex',
  },
  {
    a: 'jeden Morgen mit Küssen geweckt werden',
    b: 'jeden Abend mit einer Massage ins Bett gebracht werden',
    aEn: 'be woken up with kisses every morning',
    bEn: 'be put to bed with a massage every night',
  },
  {
    a: 'beim Pärchenabend erfahren, dass das andere Paar swingt',
    b: 'beim Pärchenabend aus Versehen euer Sexleben zum Thema machen',
    aEn: 'find out at couples’ night that the other couple are swingers',
    bEn: 'accidentally make your sex life the topic at couples’ night',
  },
  {
    a: 'dass dein Partner dir beim Sex starr in die Augen schaut',
    b: 'dass dein Partner beim Sex immer die Augen zu hat',
    aEn: 'have your partner stare into your eyes during sex',
    bEn: 'have your partner always keep their eyes closed during sex',
  },
  {
    a: 'ein Date mit Augenbinde haben',
    b: 'ein Date mit Ohrstöpseln haben',
    aEn: 'go on a date blindfolded',
    bEn: 'go on a date with earplugs in',
  },
  {
    a: 'Telefonsex mit miserablem Empfang haben',
    b: 'Videosex haben, bei dem das Bild ständig einfriert',
    aEn: 'have phone sex with terrible reception',
    bEn: 'have video sex where the picture keeps freezing',
  },
  {
    a: 'Sex unter der Dusche ausprobieren und ausrutschen',
    b: 'Sex auf dem Küchentisch ausprobieren und Geschirr zerbrechen',
    aEn: 'try sex in the shower and slip',
    bEn: 'try sex on the kitchen table and break the dishes',
  },
  {
    a: 'deinen alten Uni-Schwarm wiedertreffen und sofort Funken spüren',
    b: 'deinen alten Uni-Schwarm wiedertreffen und gar nichts mehr fühlen',
    aEn: 'run into your old college crush and feel instant sparks',
    bEn: 'run into your old college crush and feel nothing at all',
  },
  {
    a: 'heiße Sprachnachrichten bekommen, während du bei deinen Eltern am Tisch sitzt',
    b: 'heiße Sprachnachrichten bekommen, während du in einem wichtigen Meeting bist',
    aEn: 'get spicy voice messages while sitting at the table with your parents',
    bEn: 'get spicy voice messages while you’re in an important meeting',
  },
  {
    a: 'die beste Nacht deines Lebens komplett vergessen',
    b: 'deine peinlichste Nacht nie vergessen können',
    aEn: 'completely forget the best night of your life',
    bEn: 'never be able to forget your most embarrassing night',
  },
  {
    a: 'eine Nacht mit deinem Crush verbringen, aber nur kuscheln',
    b: 'eine fantastische Nacht mit einer fremden Person verbringen',
    aEn: 'spend a night with your crush but only cuddle',
    bEn: 'spend an amazing night with a stranger',
  },
  {
    a: 'dass dein Partner dir im Bett sagt, was du besser machen kannst',
    b: 'nie Feedback bekommen und nie wissen, wie gut du bist',
    aEn: 'have your partner tell you what you could do better in bed',
    bEn: 'never get feedback and never know how good you are',
  },
  {
    a: 'beim Pfänderspiel bis auf die Unterwäsche verlieren',
    b: 'beim Pfänderspiel jemanden aus der Runde küssen müssen',
    aEn: 'lose a forfeit game down to your underwear',
    bEn: 'have to kiss someone in the group as a forfeit',
  },
  {
    a: 'die letzte Person in dieser Runde sein, die noch Single ist',
    b: 'die erste Person in dieser Runde sein, die heiratet',
    aEn: 'be the last person in this group who’s still single',
    bEn: 'be the first person in this group to get married',
  },
];
