import type { HotPotatoSeed } from './types';

export const animalsPrompts: HotPotatoSeed[] = [
  { de: 'Säugetiere', en: 'Mammals' },
  { de: 'Wildtiere', en: 'Wild animals' },
  { de: 'Fische', en: 'Fish' },
  { de: 'Reptilien', en: 'Reptiles' },
  { de: 'Nagetiere', en: 'Rodents' },
  { de: 'Beuteltiere', en: 'Marsupials' },
  { de: 'Raubtiere', en: 'Predators' },
  { de: 'Raubkatzen und Wildkatzen', en: 'Big cats and wild cats' },
  { de: 'Affen und Menschenaffen', en: 'Monkeys and apes' },
  { de: 'Schlangen', en: 'Snakes' },
  { de: 'Greifvögel und Eulen', en: 'Birds of prey and owls' },
  { de: 'Singvögel', en: 'Songbirds' },
  { de: 'Wasservögel', en: 'Water birds' },
  { de: 'Exotische Vögel', en: 'Exotic birds' },
  { de: 'Papageien und Sittiche', en: 'Parrots and parakeets' },
  { de: 'Haiarten', en: 'Types of sharks' },
  { de: 'Wale und Delfine', en: 'Whales and dolphins' },
  { de: 'Meeressäuger', en: 'Marine mammals' },
  { de: 'Fische, die im Meer leben', en: 'Saltwater fish' },
  { de: 'Fische aus Flüssen und Seen', en: 'Freshwater fish' },
  { de: 'Fische, die man angeln kann', en: 'Fish you can catch with a rod' },
  { de: 'Aquarienfische', en: 'Aquarium fish' },
  { de: 'Muscheln, Krebse und Tintenfische', en: 'Shellfish, crustaceans and squid' },
  { de: 'Käferarten', en: 'Types of beetles' },
  { de: 'Spinnenarten', en: 'Types of spiders' },
  { de: 'Fliegende Insekten', en: 'Flying insects' },
  { de: 'Katzenrassen', en: 'Cat breeds' },
  { de: 'Pferderassen', en: 'Horse breeds' },
  { de: 'Kleine Hunderassen', en: 'Small dog breeds' },
  { de: 'Große Hunderassen', en: 'Large dog breeds' },
  { de: 'Hirsche und Antilopen', en: 'Deer and antelopes' },
  { de: 'Huftiere', en: 'Hoofed animals' },
  { de: 'Haustiere, die im Käfig leben', en: 'Pets that live in a cage' },
  { de: 'Ungewöhnliche Haustiere', en: 'Unusual pets' },
  { de: 'Tiere im Terrarium', en: 'Terrarium animals' },
  { de: 'Tiere im Streichelzoo', en: 'Petting zoo animals' },
  { de: 'Tiere, die der Mensch gezähmt hat', en: 'Domesticated animals' },
  { de: 'Arbeitstiere', en: 'Working animals' },
  { de: 'Tiere, die man essen kann', en: 'Animals people eat' },
  { de: 'Wildtiere, die gejagt werden', en: 'Game animals that people hunt' },
  { de: 'Tiere in Afrika', en: 'Animals in Africa' },
  { de: 'Tiere in Australien', en: 'Animals in Australia' },
  { de: 'Tiere in Asien', en: 'Animals in Asia' },
  { de: 'Tiere in Südamerika', en: 'Animals in South America' },
  { de: 'Tiere in Nordamerika', en: 'Animals in North America' },
  { de: 'Wildtiere in Europa', en: 'Wild animals in Europe' },
  { de: 'Tiere in Indien', en: 'Animals in India' },
  { de: 'Tiere in der Savanne', en: 'Savanna animals' },
  { de: 'Tiere im Regenwald', en: 'Rainforest animals' },
  { de: 'Tiere in der Wüste', en: 'Desert animals' },
  { de: 'Tiere im Wald', en: 'Forest animals' },
  { de: 'Tiere in den Bergen', en: 'Mountain animals' },
  { de: 'Tiere in der Arktis und Antarktis', en: 'Polar animals' },
  { de: 'Tiere im Korallenriff', en: 'Coral reef animals' },
  { de: 'Tiere am Strand', en: 'Animals at the beach' },
  { de: 'Tiere im Teich', en: 'Pond animals' },
  { de: 'Tiere im Fluss', en: 'River animals' },
  { de: 'Tiere im Sumpf', en: 'Swamp animals' },
  { de: 'Tiere auf der Wiese', en: 'Meadow animals' },
  { de: 'Tiere im Garten', en: 'Garden animals' },
  { de: 'Tiere in der Stadt', en: 'Animals in the city' },
  { de: 'Ungeziefer und Schädlinge', en: 'Pests and vermin' },
  { de: 'Tiere, die auf Bäumen leben', en: 'Animals that live in trees' },
  { de: 'Tiere, die unter der Erde leben', en: 'Animals that live underground' },
  { de: 'Tiere, die im Wasser und an Land leben', en: 'Animals that live in water and on land' },
  { de: 'Nachtaktive Tiere', en: 'Nocturnal animals' },
  { de: 'Tiere, die Winterschlaf halten', en: 'Animals that hibernate' },
  { de: 'Tiere, die weite Strecken wandern', en: 'Animals that migrate' },
  { de: 'Tiere, die in Herden leben', en: 'Herd animals' },
  {
    de: 'Tiere, die in Schwärmen oder Kolonien leben',
    en: 'Animals that live in swarms or colonies',
  },
  { de: 'Tiere, die Eier legen', en: 'Animals that lay eggs' },
  { de: 'Tiere, die Nester bauen', en: 'Animals that build nests' },
  { de: 'Tiere, die fliegen können', en: 'Animals that can fly' },
  { de: 'Tiere, die schwimmen können', en: 'Animals that can swim' },
  { de: 'Tiere, die klettern können', en: 'Animals that can climb' },
  { de: 'Tiere, die springen können', en: 'Animals that can jump' },
  { de: 'Tiere, die graben', en: 'Animals that dig' },
  { de: 'Tiere, die sich tarnen', en: 'Animals that use camouflage' },
  { de: 'Schnelle Tiere', en: 'Fast animals' },
  { de: 'Starke Tiere', en: 'Strong animals' },
  { de: 'Kluge Tiere', en: 'Smart animals' },
  { de: 'Süße Tiere', en: 'Cute animals' },
  { de: 'Flauschige Tiere', en: 'Fluffy animals' },
  { de: 'Glitschige Tiere', en: 'Slimy animals' },
  { de: 'Laute Tiere', en: 'Loud animals' },
  { de: 'Tiere, die viel schlafen', en: 'Animals that sleep a lot' },
  { de: 'Gefährliche Tiere', en: 'Dangerous animals' },
  { de: 'Giftige Tiere', en: 'Venomous animals' },
  { de: 'Tiere, die stechen können', en: 'Animals that can sting' },
  { de: 'Tiere, vor denen Menschen Angst haben', en: 'Animals people are afraid of' },
  { de: 'Bedrohte Tierarten', en: 'Endangered animals' },
  { de: 'Ausgestorbene Tiere', en: 'Extinct animals' },
  { de: 'Tiere, die kriechen', en: 'Animals that crawl' },
  { de: 'Fleischfresser', en: 'Carnivores' },
  { de: 'Pflanzenfresser', en: 'Herbivores' },
  { de: 'Allesfresser', en: 'Omnivores' },
  { de: 'Tiere, die Insekten fressen', en: 'Animals that eat insects' },
  { de: 'Tiere, die Fisch fressen', en: 'Animals that eat fish' },
  { de: 'Tiere, die Gras fressen', en: 'Animals that eat grass' },
  { de: 'Tiere mit Hörnern oder Geweih', en: 'Animals with horns or antlers' },
  { de: 'Tiere mit Fell', en: 'Animals with fur' },
  { de: 'Tiere mit Schuppen', en: 'Animals with scales' },
  { de: 'Tiere mit Flügeln', en: 'Animals with wings' },
  { de: 'Tiere mit Flossen', en: 'Animals with fins' },
  { de: 'Tiere mit Krallen', en: 'Animals with claws' },
  { de: 'Tiere mit Stacheln', en: 'Animals with spines or quills' },
  { de: 'Tiere mit Panzer oder Schale', en: 'Animals with a shell' },
  { de: 'Tiere mit langem Schwanz', en: 'Animals with a long tail' },
  { de: 'Tiere mit großen Ohren', en: 'Animals with big ears' },
  { de: 'Tiere mit langen Beinen', en: 'Animals with long legs' },
  { de: 'Tiere mit Streifen', en: 'Animals with stripes' },
  { de: 'Tiere mit Flecken', en: 'Animals with spots' },
  { de: 'Tiere mit Schnabel', en: 'Animals with a beak' },
  { de: 'Tiere mit Fühlern', en: 'Animals with antennae' },
  { de: 'Tiere mit Schnurrhaaren', en: 'Animals with whiskers' },
  { de: 'Tiere mit Schwimmhäuten', en: 'Animals with webbed feet' },
  { de: 'Tiere mit mehr als sechs Beinen', en: 'Animals with more than six legs' },
  { de: 'Tiere ohne Beine', en: 'Animals without legs' },
  { de: 'Tiere ohne Knochen', en: 'Animals without bones' },
  { de: 'Tiere, die größer sind als ein Mensch', en: 'Animals bigger than a human' },
  { de: 'Tiere, die in einen Schuhkarton passen', en: 'Animals that fit in a shoebox' },
  { de: 'Schwarz-weiße Tiere', en: 'Black and white animals' },
  { de: 'Rote Tiere', en: 'Red animals' },
  { de: 'Grüne Tiere', en: 'Green animals' },
  { de: 'Gelbe oder orangefarbene Tiere', en: 'Yellow or orange animals' },
  { de: 'Weiße Tiere', en: 'White animals' },
  { de: 'Schwarze Tiere', en: 'Black animals' },
  { de: 'Blaue Tiere', en: 'Blue animals' },
  { de: 'Braune Tiere', en: 'Brown animals' },
  { de: 'Graue Tiere', en: 'Gray animals' },
  { de: 'Bunte Tiere', en: 'Colorful animals' },
  { de: 'Tiere in Märchen und Fabeln', en: 'Animals in fairy tales and fables' },
  { de: 'Tiere in Firmenlogos', en: 'Animals in company logos' },
  { de: 'Tiere in Wappen und Flaggen', en: 'Animals on coats of arms and flags' },
  {
    de: 'Tiere in Namen von Superhelden und Schurken',
    en: 'Animals in superhero and villain names',
  },
  { de: 'Tiere in Namen von Sportvereinen', en: 'Animals in sports team names' },
  { de: 'Yoga-Übungen mit Tiernamen', en: 'Yoga poses named after animals' },
  { de: 'Tiere, die es als Kuscheltier gibt', en: 'Animals you can get as a stuffed toy' },
  { de: 'Tiere, die man früher im Zirkus sah', en: 'Animals you used to see in the circus' },
  { de: 'Tiere, die Kinder lieben', en: 'Animals kids love' },
  { de: 'Tiere, die man streicheln kann', en: 'Animals you can pet' },
  { de: 'Echsen', en: 'Lizards' },
  { de: 'Tiere, die in Videospielen die Hauptrolle spielen', en: 'Animals that star in video games' },
  { de: 'Tiere in Filmtiteln', en: 'Animals in movie titles' },
  { de: 'Tiere in der Bibel', en: 'Animals in the Bible' },
  { de: 'Tiere mit Pfoten', en: 'Animals with paws' },
  { de: 'Tiere mit kurzen Beinen', en: 'Animals with short legs' },
  { de: 'Tiere mit langem Hals', en: 'Animals with a long neck' },
  { de: 'Tiere mit großen Zähnen', en: 'Animals with big teeth' },
  { de: 'Tiere mit langer Nase oder Rüssel', en: 'Animals with a long nose or trunk' },
  { de: 'Langsame Tiere', en: 'Slow animals' },
  { de: 'Tiere, die sehr alt werden', en: 'Animals that live very long' },
  { de: 'Tiere, die stinken', en: 'Smelly animals' },
  { de: 'Tiere, die Kunststücke lernen können', en: 'Animals that can learn tricks' },
  { de: 'Tiere, die lustig aussehen', en: 'Funny-looking animals' },
  { de: 'Beliebte Hundenamen', en: 'Popular dog names' },
  { de: 'Beliebte Katzennamen', en: 'Popular cat names' },
  { de: 'Tricks, die man einem Hund beibringen kann', en: 'Tricks you can teach a dog' },
  { de: 'Dinge, die man für ein Haustier braucht', en: 'Things you need for a pet' },
  { de: 'Berufe, die mit Tieren zu tun haben', en: 'Jobs that involve animals' },
  { de: 'Dinge, die von Tieren stammen', en: 'Things that come from animals' },
  { de: 'Körperteile von Tieren, die Menschen nicht haben', en: 'Animal body parts humans don’t have' },
  { de: 'Gefährliche Tiere im Meer', en: 'Dangerous sea creatures' },
  { de: 'Tiere, die man besser nicht als Haustier hält', en: 'Animals you shouldn’t keep as a pet' },
  { de: 'Tiere, die man gerne einen Tag lang wäre', en: 'Animals you’d like to be for a day' },
  { de: 'Tierkostüme für Fasching', en: 'Animal costumes for a costume party' },
  { de: 'Tiere, die man gut pantomimisch darstellen kann', en: 'Animals that are easy to act out' },
  { de: 'Tiere, deren Geräusch man nachmachen kann', en: 'Animals whose sound you can imitate' },
  { de: 'Nationaltiere von Ländern', en: 'National animals of countries' },
  { de: 'Dinge, die Hunde gerne tun', en: 'Things dogs love to do' },
  { de: 'Dinge, die Katzen gerne tun', en: 'Things cats love to do' },
  { de: 'Dinge, die Haustiere kaputt machen', en: 'Things pets destroy' },
  { de: 'Dinge, die man im Pferdestall findet', en: 'Things you find in a horse stable' },
  { de: 'Futter, das Tiere fressen', en: 'Foods animals eat' },
  { de: 'Tierrassen, die nach Orten benannt sind', en: 'Animal breeds named after places' },
  { de: 'Tiere, die Blut saugen', en: 'Animals that suck blood' },
  { de: 'Tiere, die kleiner als ein Fingernagel sind', en: 'Animals smaller than a fingernail' },
  { de: 'Dinge, die man zum Angeln braucht', en: 'Things you need for fishing' },
  { de: 'Dinge in einem Aquarium', en: 'Things in an aquarium' },
  { de: 'Tiere, gegen die man im Kampf verlieren würde', en: 'Animals you would lose a fight to' },
  { de: 'Tiere, die man im Kampf besiegen könnte', en: 'Animals you could beat in a fight' },
  { de: 'Tiere, auf denen man reiten kann', en: 'Animals you can ride' },
  { de: 'Begriffe für Tiergruppen wie Herde oder Rudel', en: 'Words for groups of animals like herd or pack' },
  { de: 'Wohnorte von Tieren wie Nest oder Bau', en: 'Animal homes like nest or burrow' },
  { de: 'Arten, wie sich Tiere fortbewegen', en: 'Ways animals move' },
  { de: 'Geräusche, die Tiere machen', en: 'Sounds animals make' },
  { de: 'Beliebte Tiermotive für Tattoos', en: 'Popular animal tattoos' },
  { de: 'Tiere, die man als Kind gefangen hat', en: 'Animals you caught as a kid' },
  { de: 'Tiere, die einem beim Autofahren über die Straße laufen', en: 'Animals that cross the road in front of your car' },
  { de: 'Tiere, die man beim Camping trifft', en: 'Animals you meet while camping' },
  { de: 'Tiere, die Nüsse fressen', en: 'Animals that eat nuts' },
  { de: 'Tiere, die gerne in der Sonne liegen', en: 'Animals that like to bask in the sun' },
  { de: 'Tiere, die Obst fressen', en: 'Animals that eat fruit' },
  { de: 'Tiere, die man nachts hört', en: 'Animals you hear at night' },
  { de: 'Tiere, die man gerne als Haustier hätte', en: 'Animals you’d love to have as a pet' },
  { de: 'Tiere, die Hunde gerne jagen', en: 'Animals dogs love to chase' },
  { de: 'Tiere, die zu Halloween passen', en: 'Animals that fit Halloween' },
  { de: 'Tiere, die man im Winter draußen sieht', en: 'Animals you see outside in winter' },
  { de: 'Tiere, die Katzen gerne jagen', en: 'Animals cats love to hunt' },
  { de: 'Tiere, die zu Weihnachten passen', en: 'Animals that fit Christmas' },
];
