import type { HotPotatoSeed } from './types';

export const brandsPrompts: HotPotatoSeed[] = [
  { de: 'Luxus- und Sportwagenmarken', en: 'Luxury and sports car brands' },
  { de: 'Modelle von Elektroautos', en: 'Electric car models' },
  { de: 'Motorradmarken', en: 'Motorcycle brands' },
  { de: 'Fahrradmarken', en: 'Bicycle brands' },
  { de: 'Reifenhersteller', en: 'Tyre brands' },
  { de: 'Tankstellenketten', en: 'Petrol station brands' },
  { de: 'Smartphone-Hersteller', en: 'Smartphone brands' },
  { de: 'Handymodelle', en: 'Mobile phone models' },
  { de: 'Laptop-Hersteller', en: 'Laptop brands' },
  { de: 'Fernseher-Hersteller', en: 'TV brands' },
  { de: 'Kamerahersteller', en: 'Camera brands' },
  { de: 'Kopfhörermarken', en: 'Headphone brands' },
  { de: 'Smartwatches und Fitness-Tracker', en: 'Smartwatches and fitness trackers' },
  { de: 'Hersteller von PC-Hardware und Zubehör', en: 'PC hardware and accessory brands' },
  { de: 'Webbrowser', en: 'Web browsers' },
  { de: 'Betriebssysteme', en: 'Operating systems' },
  { de: 'Suchmaschinen', en: 'Search engines' },
  { de: 'E-Mail-Anbieter', en: 'Email providers' },
  { de: 'Messenger-Apps', en: 'Messaging apps' },
  { de: 'Programme und Dienste von Microsoft', en: 'Microsoft products and services' },
  { de: 'Produkte und Dienste von Google', en: 'Google products and services' },
  { de: 'Produkte von Apple', en: 'Apple products' },
  { de: 'Produkte und Dienste von Amazon', en: 'Amazon products and services' },
  { de: 'Produkte von Sony', en: 'Sony products' },
  { de: 'Produkte und Konsolen von Nintendo', en: 'Nintendo products and consoles' },
  { de: 'KI-Tools und Chatbots', en: 'AI tools and chatbots' },
  { de: 'Große Tech-Konzerne', en: 'Big tech companies' },
  { de: 'Apps für Fitness und Sport', en: 'Fitness and workout apps' },
  { de: 'Apps fürs Büro und zum Organisieren', en: 'Productivity and work apps' },
  { de: 'Lern-Apps', en: 'Learning apps' },
  { de: 'Apps zum Bearbeiten von Fotos und Videos', en: 'Photo and video editing apps' },
  { de: 'Musik-Apps und Musikdienste', en: 'Music apps and services' },
  { de: 'Lieferdienste und Liefer-Apps', en: 'Food and grocery delivery apps' },
  { de: 'Fahrdienste und Sharing-Apps', en: 'Ride-hailing and sharing apps' },
  { de: 'Reiseportale und Buchungsseiten', en: 'Travel booking sites' },
  { de: 'Apps und Seiten für Gebrauchtes', en: 'Apps and sites for buying second-hand' },
  { de: 'Apps zum Investieren und Traden', en: 'Investing and trading apps' },
  { de: 'Bezahldienste und Kreditkarten', en: 'Payment services and credit cards' },
  { de: 'Kryptowährungen', en: 'Cryptocurrencies' },
  { de: 'Plattformen und Shops für Videospiele', en: 'Video game stores and platforms' },
  { de: 'Online-Shops', en: 'Online shops' },
  { de: 'Banken', en: 'Banks' },
  { de: 'Versicherungen', en: 'Insurance companies' },
  { de: 'Mobilfunkanbieter', en: 'Mobile network providers' },
  { de: 'Paket- und Kurierdienste', en: 'Parcel and courier companies' },
  { de: 'Hotelketten', en: 'Hotel chains' },
  { de: 'Kreuzfahrtreedereien', en: 'Cruise lines' },
  { de: 'Bahn- und Fernbusunternehmen', en: 'Train and coach companies' },
  { de: 'Supermarktketten', en: 'Supermarket chains' },
  { de: 'Kaufhäuser', en: 'Department stores' },
  { de: 'Elektronikmärkte und Technikhändler', en: 'Electronics retailers' },
  { de: 'Modeketten', en: 'High street fashion chains' },
  { de: 'Luxusmodemarken', en: 'Luxury fashion brands' },
  { de: 'Jeansmarken', en: 'Denim brands' },
  { de: 'Outdoor-Marken', en: 'Outdoor clothing brands' },
  { de: 'Streetwear-Marken', en: 'Streetwear brands' },
  { de: 'Surf- und Skatemarken', en: 'Surf and skate brands' },
  { de: 'Unterwäschemarken', en: 'Underwear and lingerie brands' },
  { de: 'Schuhmarken, die keine Sportmarken sind', en: 'Shoe brands that aren’t sportswear brands' },
  { de: 'Sneaker-Modelle', en: 'Sneaker models' },
  { de: 'Brillen- und Sonnenbrillenmarken', en: 'Glasses and sunglasses brands' },
  { de: 'Schmuckmarken', en: 'Jewellery brands' },
  { de: 'Uhrenmarken', en: 'Watch brands' },
  { de: 'Bekannte Parfums', en: 'Famous perfumes' },
  { de: 'Kosmetik- und Make-up-Marken', en: 'Cosmetics and make-up brands' },
  { de: 'Kosmetik- und Drogerieketten', en: 'Beauty and drugstore chains' },
  { de: 'Shampoo- und Haarpflegemarken', en: 'Shampoo and hair care brands' },
  { de: 'Zahnpflegemarken', en: 'Toothpaste and dental care brands' },
  { de: 'Putz- und Waschmittelmarken', en: 'Cleaning and laundry brands' },
  { de: 'Taschen- und Kofferhersteller', en: 'Bag and luggage brands' },
  { de: 'Hersteller von Haushaltsgeräten', en: 'Home appliance brands' },
  { de: 'Marken für Küchengeräte und Kochgeschirr', en: 'Kitchen appliance and cookware brands' },
  { de: 'Hersteller von Kaffeemaschinen', en: 'Coffee machine brands' },
  { de: 'Werkzeugmarken', en: 'Tool brands' },
  { de: 'Schreibwarenmarken', en: 'Stationery brands' },
  { de: 'Produkte von IKEA', en: 'IKEA products' },
  { de: 'Tiernahrungsmarken', en: 'Pet food brands' },
  { de: 'Marken für Babyprodukte', en: 'Baby product brands' },
  { de: 'Medikamentenmarken aus der Apotheke', en: 'Over-the-counter medicine brands' },
  { de: 'Musikinstrumentenmarken', en: 'Musical instrument brands' },
  { de: 'Marken für Bälle und Sportgeräte', en: 'Sports equipment brands' },
  { de: 'Spielzeugmarken', en: 'Toy brands' },
  { de: 'Technik-Klassiker von früher', en: 'Retro tech products' },
  { de: 'Fernsehsender', en: 'TV channels' },
  { de: 'Zeitungen', en: 'Newspapers' },
  { de: 'Zeitschriften und Magazine', en: 'Magazines' },
  { de: 'Firmen und Marken, die zu Disney gehören', en: 'Companies and brands owned by Disney' },
  { de: 'Restaurantketten mit Bedienung', en: 'Sit-down restaurant chains' },
  { de: 'Kaffeehausketten', en: 'Coffee shop chains' },
  { de: 'Getränke, die man bei Starbucks bestellen kann', en: 'Drinks you can order at Starbucks' },
  { de: 'Frühstücksflocken', en: 'Breakfast cereals' },
  { de: 'Keks- und Gebäckmarken', en: 'Biscuit and cookie brands' },
  { de: 'Schokoladenmarken', en: 'Chocolate brands' },
  { de: 'Süßigkeitenmarken ohne Schokolade', en: 'Candy brands that aren’t chocolate' },
  { de: 'Chips- und Snackmarken', en: 'Crisps and snack brands' },
  { de: 'Eismarken', en: 'Ice cream brands' },
  { de: 'Produkte von Ferrero', en: 'Ferrero products' },
  { de: 'Marken für Saucen, Ketchup und Gewürze', en: 'Sauce, ketchup and seasoning brands' },
  { de: 'Kaffeemarken', en: 'Coffee brands' },
  { de: 'Teemarken', en: 'Tea brands' },
  { de: 'Limonadenmarken', en: 'Soft drink brands' },
  { de: 'Energydrink-Marken', en: 'Energy drink brands' },
  { de: 'Mineralwassermarken', en: 'Bottled water brands' },
  { de: 'Getränke von Coca-Cola', en: 'Drinks made by Coca-Cola' },
  { de: 'Marken, die nach einer echten Person benannt sind', en: 'Brands named after a real person' },
  { de: 'Marken, die nach einem Ort benannt sind', en: 'Brands named after a place' },
  { de: 'Marken, deren Name eine Abkürzung ist', en: 'Brands whose name is an abbreviation' },
  { de: 'Marken mit einer Zahl im Namen', en: 'Brands with a number in their name' },
  { de: 'Marken mit einer Farbe im Namen', en: 'Brands with a colour in their name' },
  { de: 'Marken mit einem roten Logo', en: 'Brands with a red logo' },
  { de: 'Logos, die man auch ohne Namen erkennt', en: 'Logos you recognise without the name' },
  { de: 'Markennamen, die man für das Produkt selbst sagt', en: 'Brand names people use for the product itself' },
  { de: 'Marken mit einem Und-Zeichen im Namen', en: 'Brands with an ampersand in their name' },
  { de: 'Werbemaskottchen', en: 'Brand mascots' },
  { de: 'Marken und Firmen, die es nicht mehr gibt', en: 'Brands and companies that no longer exist' },
  { de: 'Firmengründer', en: 'Company founders' },
  { de: 'Firmen aus Deutschland', en: 'German companies' },
  { de: 'Firmen aus Japan', en: 'Japanese companies' },
  { de: 'Firmen aus den USA', en: 'American companies' },
  { de: 'Firmen aus Italien', en: 'Italian companies' },
  { de: 'Firmen aus Frankreich', en: 'French companies' },
  { de: 'Firmen aus Skandinavien', en: 'Scandinavian companies' },
  { de: 'Firmen aus der Schweiz', en: 'Swiss companies' },
  { de: 'Firmen aus Großbritannien', en: 'British companies' },
  { de: 'Firmen aus China', en: 'Chinese companies' },
  { de: 'Firmen aus Spanien', en: 'Spanish companies' },
  { de: 'Asiatische Automarken', en: 'Asian car brands' },
  { de: 'Europäische Automarken', en: 'European car brands' },
  { de: 'Amerikanische Automarken', en: 'American car brands' },
  { de: 'Sportwagenmodelle', en: 'Sports car models' },
  { de: 'Modelle von Volkswagen', en: 'Volkswagen models' },
  { de: 'Modelle von Ford', en: 'Ford models' },
  { de: 'Modelle von Mercedes-Benz', en: 'Mercedes-Benz models' },
  { de: 'Modelle von Toyota', en: 'Toyota models' },
  { de: 'Modelle von BMW', en: 'BMW models' },
  { de: 'Autovermietungen', en: 'Car rental companies' },
  { de: 'Reiseveranstalter', en: 'Tour operators and package holiday companies' },
  { de: 'Raumfahrtfirmen und Raumfahrtagenturen', en: 'Space companies and agencies' },
  { de: 'Produkte von Samsung', en: 'Samsung products' },
  { de: 'Computerprogramme', en: 'Computer software programs' },
  { de: 'Antivirenprogramme', en: 'Antivirus programs' },
  { de: 'Cloud-Speicherdienste', en: 'Cloud storage services' },
  { de: 'Druckerhersteller', en: 'Printer brands' },
  { de: 'Lautsprecher- und Hi-Fi-Marken', en: 'Speaker and hi-fi brands' },
  { de: 'Marken für Handyzubehör', en: 'Phone accessory brands' },
  { de: 'Soziale Netzwerke von früher', en: 'Social networks from back in the day' },
  { de: 'Produkte von Hasbro und Mattel', en: 'Hasbro and Mattel products' },
  { de: 'Sammelfiguren und Sammelkarten', en: 'Collectible figures and cards' },
  { de: 'Läden, die man in jedem Einkaufszentrum findet', en: 'Shops you find in every shopping mall' },
  { de: 'Billigläden und Restpostenketten', en: 'Discount and pound shops' },
  { de: 'Möbel- und Einrichtungsketten', en: 'Furniture and home decor chains' },
  { de: 'Baumärkte', en: 'DIY and hardware stores' },
  { de: 'Sportgeschäfte', en: 'Sporting goods stores' },
  { de: 'Fitnessstudioketten', en: 'Gym chains' },
  { de: 'Marken für Anzüge und Hemden', en: 'Suit and shirt brands' },
  { de: 'Marken für Winterjacken', en: 'Winter jacket brands' },
  { de: 'Marken für Trinkflaschen und Thermobecher', en: 'Water bottle and travel mug brands' },
  { de: 'Marken für Matratzen und Betten', en: 'Mattress and bed brands' },
  { de: 'Marken für Grills', en: 'Barbecue grill brands' },
  { de: 'Marken für Rasierer und Bartpflege', en: 'Razor and beard care brands' },
  { de: 'Deo- und Duschgelmarken', en: 'Deodorant and shower gel brands' },
  { de: 'Hautpflegemarken', en: 'Skincare brands' },
  { de: 'Sonnencrememarken', en: 'Sunscreen brands' },
  { de: 'Marken für Taschentücher und Toilettenpapier', en: 'Tissue and toilet paper brands' },
  { de: 'Zigarettenmarken', en: 'Cigarette brands' },
  { de: 'Pharmakonzerne', en: 'Pharmaceutical companies' },
  { de: 'Marken von Nestlé', en: 'Nestlé brands' },
  { de: 'Marken von Mars', en: 'Brands owned by Mars' },
  { de: 'Marken von Procter & Gamble', en: 'Procter & Gamble brands' },
  { de: 'Marken von Unilever', en: 'Unilever brands' },
  { de: 'Pizzaketten', en: 'Pizza chains' },
  { de: 'Bäckerei- und Donutketten', en: 'Bakery and doughnut chains' },
  { de: 'Joghurt- und Milchmarken', en: 'Yoghurt and dairy brands' },
  { de: 'Käsemarken', en: 'Cheese brands' },
  { de: 'Marken für Brotaufstriche', en: 'Spread brands' },
  { de: 'Marken für Fertiggerichte und Tiefkühlkost', en: 'Ready meal and frozen food brands' },
  { de: 'Nudel- und Reismarken', en: 'Pasta and rice brands' },
  { de: 'Müsliriegel- und Proteinriegelmarken', en: 'Cereal bar and protein bar brands' },
  { de: 'Marken für Sportnahrung und Proteinpulver', en: 'Sports nutrition and protein powder brands' },
  { de: 'Saft- und Smoothiemarken', en: 'Juice and smoothie brands' },
  { de: 'Modelle von Audi', en: 'Audi models' },
  { de: 'Hersteller von Lkw und Bussen', en: 'Truck and bus manufacturers' },
  { de: 'Marken für Instantnudeln', en: 'Instant noodle brands' },
  { de: 'Apps für Videoanrufe und Videokonferenzen', en: 'Video call and video conferencing apps' },
  { de: 'Marken für Pflanzenmilch', en: 'Plant-based milk brands' },
  { de: 'Marken für Kerzen und Raumdüfte', en: 'Candle and home fragrance brands' },
  { de: 'Marken für Alkopops, Cider und Hard Seltzer', en: 'Alcopop, cider and hard seltzer brands' },
  { de: 'Drinks mit einem Markennamen in der Bestellung', en: 'Bar orders that include a brand name' },
  { de: 'Werbeslogans', en: 'Advertising slogans' },
  { de: 'Marken von Prominenten', en: 'Celebrity brands' },
  { de: 'Marken, die in Rapsongs vorkommen', en: 'Brands that get name-dropped in rap songs' },
  { de: 'Marken mit einem Apostroph im Namen', en: 'Brands with an apostrophe in their name' },
  { de: 'Marken mit einem Tier im Namen', en: 'Brands with an animal in their name' },
  { de: 'Marken mit einem Weltraum-Begriff im Namen', en: 'Brands with a space-related word in their name' },
  { de: 'Marken, die nach Figuren aus Mythen und Sagen benannt sind', en: 'Brands named after mythological figures' },
  { de: 'Firmen, die über 100 Jahre alt sind', en: 'Companies that are over 100 years old' },
  { de: 'Firmen, die nach dem Jahr 2000 gegründet wurden', en: 'Companies founded after the year 2000' },
  { de: 'Firmen aus Kalifornien', en: 'Companies from California' },
  { de: 'Firmen aus den Niederlanden', en: 'Dutch companies' },
  { de: 'Firmen aus Südkorea', en: 'South Korean companies' },
];
