import type { HotPotatoSeed } from './types';

export const foodPrompts: HotPotatoSeed[] = [
  { de: 'Dinge, die man im Wok zubereitet', en: 'Things you cook in a wok' },
  { de: 'Asiatische Nudelgerichte', en: 'Asian noodle dishes' },
  { de: 'Dinge, die man auf einem Kuchen findet', en: 'Things you find on top of a cake' },
  { de: 'Pizzasorten', en: 'Types of pizza' },
  { de: 'Biersorten', en: 'Types of beer' },
  { de: 'Gerichte, die mit Alkohol zubereitet werden', en: 'Dishes made with alcohol' },
  { de: 'Rebsorten', en: 'Grape varieties for wine' },
  { de: 'Exotische Früchte', en: 'Exotic fruits' },
  { de: 'Beeren', en: 'Berries' },
  { de: 'Gemüse, das unter der Erde wächst', en: 'Vegetables that grow underground' },
  { de: 'Gerichte, die man zu einer Party mitbringt', en: 'Dishes people bring to a potluck' },
  { de: 'Getreidesorten', en: 'Types of grain' },
  { de: 'Speiseöle', en: 'Cooking oils' },
  { de: 'Einfache Gerichte für Kochanfänger', en: 'Easy dishes for beginner cooks' },
  { de: 'Wurstsorten', en: 'Types of sausage' },
  { de: 'Steak-Zuschnitte', en: 'Cuts of steak' },
  { de: 'Lebensmittel, die im Garten wachsen', en: 'Food you can grow in a garden' },
  { de: 'Suppen', en: 'Soups' },
  { de: 'Salate', en: 'Salads' },
  { de: 'Salatzutaten', en: 'Salad ingredients' },
  { de: 'Nudelgerichte', en: 'Pasta dishes' },
  { de: 'Gerichte mit Reis', en: 'Rice dishes' },
  { de: 'Gerichte mit Hackfleisch', en: 'Dishes made with ground meat' },
  { de: 'Gerichte mit Hähnchen', en: 'Chicken dishes' },
  { de: 'Gerichte mit Fisch', en: 'Fish dishes' },
  { de: 'Gerichte mit Käse', en: 'Cheesy dishes' },
  { de: 'Gerichte mit Tomaten', en: 'Dishes made with tomatoes' },
  { de: 'Gerichte mit Speck', en: 'Dishes with bacon' },
  { de: 'Gerichte mit Knoblauch', en: 'Dishes with garlic' },
  { de: 'Lebensmittel mit Zimt', en: 'Foods with cinnamon' },
  { de: 'Lebensmittel mit Schokolade', en: 'Foods with chocolate' },
  { de: 'Vegetarische Gerichte', en: 'Vegetarian dishes' },
  { de: 'Eintöpfe und Schmorgerichte', en: 'Stews and braised dishes' },
  { de: 'Gerichte aus dem Ofen', en: 'Dishes you make in the oven' },
  { de: 'Gerichte aus der Pfanne', en: 'Dishes you make in a frying pan' },
  { de: 'Gerichte aus Frankreich', en: 'French dishes' },
  { de: 'Gerichte aus Spanien', en: 'Spanish dishes' },
  { de: 'Gerichte aus Deutschland', en: 'German dishes' },
  { de: 'Gerichte aus Griechenland', en: 'Greek dishes' },
  { de: 'Gerichte aus Japan', en: 'Japanese dishes' },
  { de: 'Gerichte aus China', en: 'Chinese dishes' },
  { de: 'Gerichte aus Indien', en: 'Indian dishes' },
  { de: 'Gerichte aus der Türkei', en: 'Turkish dishes' },
  { de: 'Gerichte aus den USA', en: 'American dishes' },
  { de: 'Gerichte aus Mexiko', en: 'Mexican dishes' },
  { de: 'Gerichte aus Thailand', en: 'Thai dishes' },
  { de: 'Gerichte aus Großbritannien', en: 'British dishes' },
  { de: 'Gerichte aus dem Nahen Osten', en: 'Middle Eastern dishes' },
  { de: 'Gerichte aus Osteuropa', en: 'Eastern European dishes' },
  { de: 'Gerichte aus Korea', en: 'Korean dishes' },
  { de: 'Nationalgerichte verschiedener Länder', en: 'National dishes of different countries' },
  { de: 'Streetfood aus aller Welt', en: 'Street food from around the world' },
  { de: 'Typische Zutaten der italienischen Küche', en: 'Typical ingredients in Italian cooking' },
  { de: 'Typische Zutaten der asiatischen Küche', en: 'Typical ingredients in Asian cooking' },
  { de: 'Fingerfood', en: 'Finger food' },
  { de: 'Dinge, die man am Buffet findet', en: 'Things you find at a buffet' },
  { de: 'Fast-Food-Gerichte', en: 'Fast food items' },
  { de: 'Dinge, die man bei McDonald’s bestellen kann', en: 'Things you can order at McDonald’s' },
  { de: 'Tiefkühlprodukte', en: 'Frozen foods' },
  { de: 'Lebensmittel aus der Dose', en: 'Canned foods' },
  { de: 'Lebensmittel, die man im Glas kauft', en: 'Foods that come in a jar' },
  { de: 'Dinge im Vorratsschrank', en: 'Things in a pantry' },
  { de: 'Lebensmittel, die man mit Schale isst', en: 'Foods you eat with the skin on' },
  { de: 'Zubereitungsarten beim Kochen', en: 'Cooking methods' },
  { de: 'Zutaten zum Backen', en: 'Baking ingredients' },
  { de: 'Chipssorten', en: 'Potato chip flavors' },
  { de: 'Marmeladensorten', en: 'Jam flavors' },
  { de: 'Saftsorten', en: 'Juice flavors' },
  { de: 'Kekssorten', en: 'Types of cookies' },
  {
    de: 'Lebensmittel, die nicht in den Kühlschrank gehören',
    en: 'Foods you shouldn’t keep in the fridge',
  },
  { de: 'Dinge, die man ins Müsli tun kann', en: 'Things you can put in muesli' },
  { de: 'Zutaten für einen Smoothie', en: 'Smoothie ingredients' },
  { de: 'Zutaten für einen Burger', en: 'Burger ingredients' },
  { de: 'Zutaten für Sushi', en: 'Sushi ingredients' },
  { de: 'Zutaten für ein Curry', en: 'Curry ingredients' },
  { de: 'Zutaten für Cocktails', en: 'Cocktail ingredients' },
  { de: 'Füllungen für Tacos und Burritos', en: 'Fillings for tacos and burritos' },
  { de: 'Dinge, die man in eine Suppe tun kann', en: 'Things you can put in a soup' },
  { de: 'Dinge, die man in den Kaffee tun kann', en: 'Things you can put in coffee' },
  { de: 'Dinge, die man auf Pommes tun kann', en: 'Toppings for fries' },
  { de: 'Toppings für Eis', en: 'Ice cream toppings' },
  { de: 'Gerichte für ein romantisches Dinner', en: 'Dishes for a romantic dinner' },
  { de: 'Dinge, die man auf einen Spieß stecken kann', en: 'Things you can put on a skewer' },
  { de: 'Dinge, die man in einen Dip tunken kann', en: 'Things you can dip into a dip' },
  { de: 'Dinge, die man mit Ketchup isst', en: 'Things you eat with ketchup' },
  { de: 'Getränke ohne Alkohol', en: 'Non-alcoholic drinks' },
  { de: 'Heiße Getränke', en: 'Hot drinks' },
  { de: 'Getränke mit Koffein', en: 'Drinks with caffeine' },
  { de: 'Getränke mit Milch', en: 'Drinks made with milk' },
  { de: 'Getränke mit Kohlensäure', en: 'Fizzy drinks' },
  { de: 'Gerichte, die man aus Resten machen kann', en: 'Dishes you can make from leftovers' },
  { de: 'Vegane Ersatzprodukte', en: 'Vegan alternatives to animal products' },
  { de: 'Dinge, die Veganer nicht essen', en: 'Things vegans don’t eat' },
  { de: 'Fermentierte Lebensmittel', en: 'Fermented foods' },
  { de: 'Geräucherte Lebensmittel', en: 'Smoked foods' },
  { de: 'Getrocknete Lebensmittel', en: 'Dried foods' },
  { de: 'Frittierte Lebensmittel', en: 'Deep-fried foods' },
  { de: 'Rote Lebensmittel', en: 'Red foods' },
  { de: 'Grüne Lebensmittel', en: 'Green foods' },
  { de: 'Gelbe Lebensmittel', en: 'Yellow foods' },
  { de: 'Orangefarbene Lebensmittel', en: 'Orange foods' },
  { de: 'Weiße Lebensmittel', en: 'White foods' },
  { de: 'Braune Lebensmittel', en: 'Brown foods' },
  { de: 'Runde Lebensmittel', en: 'Round foods' },
  { de: 'Knusprige Lebensmittel', en: 'Crunchy foods' },
  { de: 'Klebrige Lebensmittel', en: 'Sticky foods' },
  { de: 'Scharfe Lebensmittel', en: 'Spicy foods' },
  { de: 'Saure Lebensmittel', en: 'Sour foods' },
  { de: 'Bittere Lebensmittel', en: 'Bitter foods' },
  { de: 'Salzige Snacks', en: 'Salty snacks' },
  { de: 'Gesunde Snacks', en: 'Healthy snacks' },
  { de: 'Ungesundes Essen', en: 'Junk food' },
  { de: 'Lebensmittel mit viel Eiweiß', en: 'High-protein foods' },
  { de: 'Lebensmittel mit viel Zucker', en: 'Foods with lots of sugar' },
  { de: 'Lebensmittel, die stinken', en: 'Smelly foods' },
  { de: 'Lebensmittel, die Kinder nicht mögen', en: 'Foods kids don’t like' },
  { de: 'Lieblingsessen von Kindern', en: 'Kids’ favorite foods' },
  { de: 'Gerichte, die Oma kocht', en: 'Dishes grandma makes' },
  { de: 'Lebensmittel, die man schälen muss', en: 'Foods you have to peel' },
  { de: 'Obst mit Kernen oder Steinen', en: 'Fruits with seeds or pits' },
  { de: 'Lebensmittel, die an Bäumen wachsen', en: 'Foods that grow on trees' },
  { de: 'Lebensmittel, die man roh essen kann', en: 'Foods you can eat raw' },
  { de: 'Lebensmittel, die man nicht roh essen sollte', en: 'Foods you shouldn’t eat raw' },
  { de: 'Lebensmittel, die schnell schlecht werden', en: 'Foods that go bad quickly' },
  { de: 'Lebensmittel, die lange haltbar sind', en: 'Foods that last a long time' },
  { de: 'Lebensmittel, die man in Scheiben schneidet', en: 'Foods you cut into slices' },
  { de: 'Lebensmittel, die man ohne Zähne essen kann', en: 'Foods you can eat without teeth' },
  { de: 'Gerichte, die man mit Stäbchen isst', en: 'Foods you eat with chopsticks' },
  { de: 'Gerichte, die man mit den Händen isst', en: 'Foods you eat with your hands' },
  { de: 'Gerichte, die man mit dem Löffel isst', en: 'Foods you eat with a spoon' },
  { de: 'Gerichte, die man mit Messer und Gabel isst', en: 'Foods you eat with a knife and fork' },
  { de: 'Gerichte, die in einer Schüssel serviert werden', en: 'Foods served in a bowl' },
  { de: 'Gerichte, die man kalt isst', en: 'Dishes you eat cold' },
  { de: 'Dinge, die in Teig eingewickelt sind', en: 'Things wrapped in dough' },
  { de: 'Dinge aus Kartoffeln', en: 'Things made from potatoes' },
  { de: 'Dinge aus Mais', en: 'Things made from corn' },
  { de: 'Dinge aus Äpfeln', en: 'Things made from apples' },
  { de: 'Dinge aus Mehl', en: 'Things made from flour' },
  { de: 'Dinge, die man in der Bäckerei kauft', en: 'Things you buy at a bakery' },
  { de: 'Dinge, die man in der Metzgerei kauft', en: 'Things you buy at a butcher shop' },
  { de: 'Dinge, die man im Café bestellt', en: 'Things you order at a café' },
  { de: 'Dinge, die man auf dem Wochenmarkt kauft', en: 'Things you buy at a farmers market' },
  {
    de: 'Dinge, die man an der Tankstelle zu essen kauft',
    en: 'Food and drinks you buy at a gas station',
  },
  { de: 'Dinge aus dem Snackautomaten', en: 'Things from a vending machine' },
  { de: 'Essen auf dem Jahrmarkt', en: 'Food at a fair' },
  { de: 'Essen und Trinken auf dem Oktoberfest', en: 'Food and drinks at Oktoberfest' },
  { de: 'Weihnachtliches Essen und Trinken', en: 'Christmas food and drinks' },
  { de: 'Essen auf einem Kindergeburtstag', en: 'Food at a kid’s birthday party' },
  { de: 'Dinge für ein Picknick', en: 'Things to bring to a picnic' },
  { de: 'Dinge in einer Brotdose', en: 'Things in a lunchbox' },
  { de: 'Knabbereien für einen Filmabend', en: 'Snacks for a movie night' },
  { de: 'Essen für einen Kater', en: 'Hangover food' },
  { de: 'Essen, wenn man krank ist', en: 'Food when you’re sick' },
  { de: 'Mitternachtssnacks', en: 'Midnight snacks' },
  { de: 'Essen und Trinken im Sommer', en: 'Summer food and drinks' },
  { de: 'Gerichte für kalte Wintertage', en: 'Dishes for cold winter days' },
  { de: 'Dinge, die man in der Mikrowelle macht', en: 'Things you make in a microwave' },
  { de: 'Essen in der Kantine oder Mensa', en: 'Food you get in a cafeteria' },
  { de: 'Apfelsorten', en: 'Apple varieties' },
  { de: 'Gerichte mit Kokosmilch', en: 'Dishes with coconut milk' },
  { de: 'Gerichte mit Pilzen', en: 'Dishes with mushrooms' },
  { de: 'Gerichte mit Spinat', en: 'Dishes with spinach' },
  { de: 'Gerichte mit Bohnen und Linsen', en: 'Dishes with beans and lentils' },
  { de: 'Gerichte mit Zwiebeln', en: 'Dishes with onions' },
  { de: 'Gerichte mit Sahne', en: 'Dishes with cream' },
  { de: 'Gerichte mit Erdnüssen', en: 'Dishes with peanuts' },
  { de: 'Gerichte mit Lachs', en: 'Dishes with salmon' },
  { de: 'Gerichte mit Garnelen', en: 'Dishes with shrimp' },
  { de: 'Gerichte mit Rindfleisch', en: 'Beef dishes' },
  { de: 'Gerichte mit Schweinefleisch', en: 'Pork dishes' },
  { de: 'Gerichte mit Tofu', en: 'Dishes with tofu' },
  { de: 'Gerichte mit Avocado', en: 'Dishes with avocado' },
  { de: 'Gerichte mit Zucchini oder Aubergine', en: 'Dishes with zucchini or eggplant' },
  { de: 'Dinge, die man beim Lieferdienst bestellt', en: 'Things you order for delivery' },
  { de: 'Desserts mit Obst', en: 'Desserts with fruit' },
  { de: 'Desserts aus dem Kühlschrank', en: 'No-bake desserts' },
  { de: 'Gebäck mit Füllung', en: 'Filled pastries' },
  { de: 'Dinge, die man mit Puderzucker bestreut', en: 'Things you dust with powdered sugar' },
  { de: 'Dinge mit Vanillegeschmack', en: 'Vanilla-flavored things' },
  { de: 'Dinge mit Erdbeergeschmack', en: 'Strawberry-flavored things' },
  { de: 'Dinge mit Karamell', en: 'Things with caramel' },
  { de: 'Dinge, die man mit Honig süßen kann', en: 'Things you can sweeten with honey' },
  { de: 'Dinge, die man mit Zitrone verfeinert', en: 'Things you add lemon to' },
  { de: 'Dinge, die man zu Wein essen kann', en: 'Foods that go well with wine' },
  { de: 'Dinge, die man zu Bier essen kann', en: 'Foods that go well with beer' },
  { de: 'Beilagen', en: 'Side dishes' },
  { de: 'Vorspeisen', en: 'Appetizers' },
  { de: 'Gerichte mit Brot', en: 'Dishes made with bread' },
  { de: 'Dinge, die man im Kino kaufen kann', en: 'Things you can buy at a movie theater' },
  { de: 'Kräuter', en: 'Herbs' },
  { de: 'Zitrusfrüchte und Steinobst', en: 'Citrus fruits and stone fruits' },
  { de: 'Kohl und Blattgemüse', en: 'Cabbages and leafy greens' },
  { de: 'Hülsenfrüchte und Bohnen', en: 'Beans and legumes' },
  { de: 'Pilzsorten', en: 'Types of mushrooms' },
  { de: 'Sorten von Pommes und Kartoffelbeilagen', en: 'Kinds of fries and potato sides' },
  {
    de: 'Pfannkuchen und Waffeln aus aller Welt',
    en: 'Pancakes and waffles from around the world',
  },
  { de: 'Weinsorten und Schaumweine', en: 'Types of wine and sparkling wine' },
  { de: 'Longdrinks', en: 'Mixed drinks' },
  { de: 'Getränke aus aller Welt', en: 'Drinks from around the world' },
  { de: 'Lebensmittel, die man einfrieren kann', en: 'Foods you can freeze' },
];
