import type { HotPotatoSeed } from './types';

export const musicPrompts: HotPotatoSeed[] = [
  { de: 'Musikinstrumente', en: 'Musical instruments' },
  { de: 'Blasinstrumente', en: 'Wind instruments' },
  { de: 'Saiteninstrumente', en: 'String instruments' },
  { de: 'Schlaginstrumente', en: 'Percussion instruments' },
  { de: 'Instrumente in einem Orchester', en: 'Instruments in an orchestra' },
  { de: 'Musikgenres', en: 'Music genres' },
  { de: 'Unterarten von Rockmusik', en: 'Types of rock music' },
  { de: 'Unterarten von elektronischer Musik', en: 'Types of electronic music' },
  { de: 'Tanzstile', en: 'Dance styles' },
  { de: 'Lateinamerikanische Tänze und Musikstile', en: 'Latin American dances and music styles' },
  { de: 'Songs von Queen', en: 'Songs by Queen' },
  { de: 'Songs von ABBA', en: 'Songs by ABBA' },
  { de: 'Songs von den Beatles', en: 'Songs by the Beatles' },
  { de: 'Songs von Michael Jackson', en: 'Songs by Michael Jackson' },
  { de: 'Songs von Madonna', en: 'Songs by Madonna' },
  { de: 'Songs von den Rolling Stones', en: 'Songs by the Rolling Stones' },
  { de: 'Songs von Elvis Presley', en: 'Songs by Elvis Presley' },
  { de: 'Songs von Taylor Swift', en: 'Songs by Taylor Swift' },
  { de: 'Songs von Ed Sheeran', en: 'Songs by Ed Sheeran' },
  { de: 'Songs von Rihanna', en: 'Songs by Rihanna' },
  { de: 'Songs von Beyoncé', en: 'Songs by Beyoncé' },
  { de: 'Songs von Eminem', en: 'Songs by Eminem' },
  { de: 'Songs von Coldplay', en: 'Songs by Coldplay' },
  { de: 'Songs von Britney Spears', en: 'Songs by Britney Spears' },
  { de: 'Songs von Lady Gaga', en: 'Songs by Lady Gaga' },
  { de: 'Songs von Elton John', en: 'Songs by Elton John' },
  { de: 'Songs von David Bowie', en: 'Songs by David Bowie' },
  { de: 'Songs von Bon Jovi', en: 'Songs by Bon Jovi' },
  { de: 'Songs von AC/DC', en: 'Songs by AC/DC' },
  { de: 'Songs von Metallica', en: 'Songs by Metallica' },
  { de: 'Songs von den Red Hot Chili Peppers', en: 'Songs by the Red Hot Chili Peppers' },
  { de: 'Songs von U2', en: 'Songs by U2' },
  { de: 'Songs von Bruno Mars', en: 'Songs by Bruno Mars' },
  { de: 'Songs von Katy Perry', en: 'Songs by Katy Perry' },
  { de: 'Songs von Justin Bieber', en: 'Songs by Justin Bieber' },
  { de: 'Songs von Robbie Williams', en: 'Songs by Robbie Williams' },
  { de: 'Songs von Rammstein', en: 'Songs by Rammstein' },
  { de: 'Songs von Die Toten Hosen', en: 'Songs by Die Toten Hosen' },
  { de: 'Songs von Die Ärzte', en: 'Songs by Die Ärzte' },
  { de: 'Songs von Herbert Grönemeyer', en: 'Songs by Herbert Grönemeyer' },
  { de: 'Songs von Helene Fischer', en: 'Songs by Helene Fischer' },
  { de: 'Songs von Udo Jürgens', en: 'Songs by Udo Jürgens' },
  { de: 'Songs von Shakira', en: 'Songs by Shakira' },
  { de: 'Songs von Whitney Houston', en: 'Songs by Whitney Houston' },
  { de: 'Songs von Phil Collins und Genesis', en: 'Songs by Phil Collins and Genesis' },
  { de: 'Songs von den Bee Gees', en: 'Songs by the Bee Gees' },
  { de: 'Songs von Prince', en: 'Songs by Prince' },
  { de: 'Songs von Bob Marley', en: 'Songs by Bob Marley' },
  { de: 'Songs von Linkin Park', en: 'Songs by Linkin Park' },
  { de: 'Songs von Green Day', en: 'Songs by Green Day' },
  { de: 'Songs von den Backstreet Boys', en: 'Songs by the Backstreet Boys' },
  { de: 'Songs von Oasis', en: 'Songs by Oasis' },
  { de: 'Songs von Dua Lipa', en: 'Songs by Dua Lipa' },
  { de: 'Songs von The Weeknd', en: 'Songs by The Weeknd' },
  { de: 'Songs von Drake', en: 'Songs by Drake' },
  { de: 'Songs von Pink', en: 'Songs by Pink' },
  { de: 'Songs von Kylie Minogue', en: 'Songs by Kylie Minogue' },
  { de: 'Songs von Tina Turner', en: 'Songs by Tina Turner' },
  { de: 'Songs von Stevie Wonder', en: 'Songs by Stevie Wonder' },
  { de: 'Songs von Bruce Springsteen', en: 'Songs by Bruce Springsteen' },
  { de: 'Songs von Billy Joel', en: 'Songs by Billy Joel' },
  { de: 'Songs von Johnny Cash', en: 'Songs by Johnny Cash' },
  { de: 'Songs von Frank Sinatra', en: 'Songs by Frank Sinatra' },
  { de: 'Songs von Mariah Carey', en: 'Songs by Mariah Carey' },
  { de: 'Songs von Céline Dion', en: 'Songs by Céline Dion' },
  { de: 'Songs von George Michael und Wham!', en: 'Songs by George Michael and Wham!' },
  { de: 'Songs von Depeche Mode', en: 'Songs by Depeche Mode' },
  { de: 'Songs von Guns N’ Roses', en: 'Songs by Guns N’ Roses' },
  { de: 'Songs von Aerosmith', en: 'Songs by Aerosmith' },
  { de: 'Songs von Ariana Grande', en: 'Songs by Ariana Grande' },
  { de: 'Songs von Billie Eilish', en: 'Songs by Billie Eilish' },
  { de: 'Songs von One Direction und Harry Styles', en: 'Songs by One Direction and Harry Styles' },
  { de: 'Songs von Udo Lindenberg', en: 'Songs by Udo Lindenberg' },
  { de: 'Songs von Nena', en: 'Songs by Nena' },
  { de: 'Songs von Fleetwood Mac', en: 'Songs by Fleetwood Mac' },
  { de: 'Songs von Pink Floyd', en: 'Songs by Pink Floyd' },
  { de: 'Songs von Nirvana und den Foo Fighters', en: 'Songs by Nirvana and the Foo Fighters' },
  { de: 'Songs von Lana Del Rey', en: 'Songs by Lana Del Rey' },
  { de: 'Songs von Imagine Dragons', en: 'Songs by Imagine Dragons' },
  { de: 'Songs von den Scorpions', en: 'Songs by the Scorpions' },
  { de: 'Songs von Avicii und David Guetta', en: 'Songs by Avicii and David Guetta' },
  { de: 'Songs von Kanye West', en: 'Songs by Kanye West' },
  { de: 'Songs von Miley Cyrus', en: 'Songs by Miley Cyrus' },
  { de: 'Songs von Cher', en: 'Songs by Cher' },
  {
    de: 'Songs von Lionel Richie und den Commodores',
    en: 'Songs by Lionel Richie and the Commodores',
  },
  { de: 'Rockbands', en: 'Rock bands' },
  { de: 'Metal-Bands', en: 'Metal bands' },
  { de: 'Punkbands', en: 'Punk bands' },
  { de: 'Boybands', en: 'Boy bands' },
  { de: 'Girlgroups', en: 'Girl groups' },
  { de: 'Rapper', en: 'Rappers' },
  { de: 'Rapperinnen', en: 'Female rappers' },
  { de: 'Deutsche Rapper', en: 'German rappers' },
  { de: 'Sängerinnen', en: 'Female singers' },
  { de: 'Sänger', en: 'Male singers' },
  { de: 'DJs', en: 'DJs' },
  { de: 'Popstars', en: 'Pop stars' },
  { de: 'Country-Musiker', en: 'Country musicians' },
  { de: 'Jazzmusiker', en: 'Jazz musicians' },
  { de: 'Schlagersänger', en: 'Schlager singers' },
  { de: 'Komponisten klassischer Musik', en: 'Classical composers' },
  { de: 'Berühmte klassische Musikstücke', en: 'Famous pieces of classical music' },
  { de: 'Opern', en: 'Operas' },
  { de: 'Musicals', en: 'Musicals' },
  { de: 'Songs aus Musicals', en: 'Songs from musicals' },
  { de: 'Disney-Filme mit Songs', en: 'Disney films with songs' },
  { de: 'Songs aus Disney-Filmen', en: 'Songs from Disney films' },
  { de: 'Songs aus Filmen', en: 'Songs from films' },
  { de: 'James-Bond-Songs', en: 'James Bond theme songs' },
  { de: 'Weihnachtslieder', en: 'Christmas songs' },
  { de: 'Kinderlieder', en: 'Children’s songs' },
  { de: 'Eurovision-Gewinner', en: 'Eurovision winners' },
  { de: 'Länder beim Eurovision Song Contest', en: 'Countries in the Eurovision Song Contest' },
  { de: 'Musikfestivals', en: 'Music festivals' },
  { de: 'Musiker mit nur einem Namen', en: 'Musicians known by one name' },
  { de: 'Musiker mit Künstlernamen', en: 'Musicians with stage names' },
  { de: 'Verstorbene Musiklegenden', en: 'Music legends who have died' },
  { de: 'Musiker, die auch Schauspieler sind', en: 'Musicians who are also actors' },
  { de: 'Berühmte Gitarristen', en: 'Famous guitarists' },
  { de: 'Berühmte Schlagzeuger', en: 'Famous drummers' },
  { de: 'Musiker, die Klavier spielen', en: 'Musicians who play the piano' },
  { de: 'Berühmte Frontmänner von Bands', en: 'Famous band frontmen' },
  { de: 'Berühmte Frontfrauen von Bands', en: 'Famous band frontwomen' },
  { de: 'Bands mit Tieren im Namen', en: 'Bands with animals in their name' },
  { de: 'Songs mit einem Frauennamen im Titel', en: 'Songs with a woman’s name in the title' },
  { de: 'Songs mit einem Männernamen im Titel', en: 'Songs with a man’s name in the title' },
  { de: 'Songs mit einer Stadt im Titel', en: 'Songs with a city in the title' },
  { de: 'Songs über Autos und Straßen', en: 'Songs about cars and roads' },
  { de: 'Songs über Liebe', en: 'Love songs' },
  { de: 'Trennungssongs', en: 'Breakup songs' },
  { de: 'Partysongs', en: 'Party songs' },
  { de: 'Sommerhits', en: 'Summer hits' },
  { de: 'Karaoke-Klassiker', en: 'Karaoke classics' },
  { de: 'Songs zum Mitgrölen', en: 'Songs everyone sings along to' },
  { de: 'Songs, die man auf Hochzeiten hört', en: 'Songs played at weddings' },
  { de: 'Songs, die man im Stadion hört', en: 'Songs you hear at stadiums' },
  { de: 'Songs mit eigenem Tanz', en: 'Songs with their own dance' },
  { de: 'One-Hit-Wonder', en: 'One-hit wonders' },
  { de: 'Hits aus den 60ern', en: 'Hits from the 60s' },
  { de: 'Hits aus den 70ern', en: 'Hits from the 70s' },
  { de: 'Hits aus den 80ern', en: 'Hits from the 80s' },
  { de: 'Hits aus den 90ern', en: 'Hits from the 90s' },
  { de: 'Hits aus den 2000ern', en: 'Hits from the 2000s' },
  { de: 'Hits aus den 2010ern', en: 'Hits from the 2010s' },
  { de: 'Disco-Hits', en: 'Disco hits' },
  { de: 'Rap-Songs', en: 'Rap songs' },
  { de: 'Rockklassiker', en: 'Rock classics' },
  { de: 'Balladen', en: 'Ballads' },
  { de: 'Duette', en: 'Duets' },
  {
    de: 'Coversongs, die bekannter sind als das Original',
    en: 'Covers more famous than the original',
  },
  { de: 'Songs, die in der Werbung liefen', en: 'Songs used in commercials' },
  { de: 'Titelsongs von Serien', en: 'TV series theme songs' },
  { de: 'Songs, die man zum Sport hört', en: 'Workout songs' },
  { de: 'Songs zum Einschlafen', en: 'Songs to fall asleep to' },
  { de: 'Songs über Geld', en: 'Songs about money' },
  { de: 'Songs über das Wetter', en: 'Songs about the weather' },
  { de: 'Songs über die Nacht', en: 'Songs about the night' },
  { de: 'Bands aus Großbritannien', en: 'Bands from the UK' },
  { de: 'Bands aus den USA', en: 'Bands from the USA' },
  { de: 'Deutsche Bands', en: 'German bands' },
  { de: 'Deutsche Sängerinnen und Sänger', en: 'German singers' },
  { de: 'Musiker aus Kanada', en: 'Musicians from Canada' },
  { de: 'Musiker aus Australien', en: 'Musicians from Australia' },
  { de: 'Musiker aus Schweden', en: 'Musicians from Sweden' },
  { de: 'Musiker aus Frankreich', en: 'Musicians from France' },
  { de: 'Musiker aus Italien', en: 'Musicians from Italy' },
  { de: 'Musiker aus Österreich', en: 'Musicians from Austria' },
  { de: 'Musiker aus Lateinamerika', en: 'Latin American musicians' },
  { de: 'Musiker aus Irland', en: 'Musicians from Ireland' },
  { de: 'K-Pop-Gruppen und -Stars', en: 'K-pop groups and stars' },
  { de: 'Reggae- und Dancehall-Künstler', en: 'Reggae and dancehall artists' },
  { de: 'Hip-Hop-Künstler aus den 90ern', en: 'Hip-hop artists from the 90s' },
  { de: 'Popstars aus den 80ern', en: 'Pop stars from the 80s' },
  { de: 'Musiker aus Castingshows', en: 'Musicians from talent shows' },
  { de: 'Bands mit Geschwistern', en: 'Bands with siblings in them' },
  { de: 'Musiker, die Solokarriere gemacht haben', en: 'Musicians who went solo from a band' },
  { de: 'Musikbegriffe', en: 'Music terms' },
  { de: 'Tempo- und Lautstärkebezeichnungen', en: 'Tempo and dynamics markings' },
  { de: 'Stimmlagen und Gesangstechniken', en: 'Voice types and singing techniques' },
  { de: 'Dinge auf einer Konzertbühne', en: 'Things on a concert stage' },
  { de: 'Dinge in einem Tonstudio', en: 'Things in a recording studio' },
  { de: 'Dinge, die man auf ein Festival mitnimmt', en: 'Things you take to a festival' },
  { de: 'Dinge, die man auf einem Konzert macht', en: 'Things people do at a concert' },
  { de: 'Berufe in der Musikbranche', en: 'Jobs in the music industry' },
  { de: 'Geräte, mit denen man Musik hört', en: 'Devices for listening to music' },
  { de: 'Dinge, die eine Band braucht', en: 'Things a band needs' },
  { de: 'Gründe, warum ein Konzert ausfällt', en: 'Reasons a concert gets cancelled' },
  { de: 'Berühmte Konzerthallen und Arenen', en: 'Famous concert halls and arenas' },
  { de: 'Berühmte Musikalben', en: 'Famous albums' },
  { de: 'Musikvideos, die man kennt', en: 'Famous music videos' },
  { de: 'Songs, die viral gegangen sind', en: 'Songs that went viral' },
  { de: 'Songs mit berühmtem Gitarrenriff', en: 'Songs with a famous guitar riff' },
  { de: 'Instrumentalstücke ohne Gesang', en: 'Instrumental tracks without vocals' },
  { de: 'Musiker mit auffälligem Look', en: 'Musicians with an iconic look' },
  { de: 'Musiker, die Grammys gewonnen haben', en: 'Grammy-winning musicians' },
  { de: 'Rocklegenden', en: 'Rock legends' },
  { de: 'Divas der Popmusik', en: 'Pop divas' },
  { de: 'Lieder, die man am Lagerfeuer singt', en: 'Songs you sing around a campfire' },
  { de: 'Songs über Tiere', en: 'Songs about animals' },
  { de: 'Songs über Essen und Trinken', en: 'Songs about food and drink' },
];
