import type { HotPotatoSeed } from './types';

export const normalPrompts: HotPotatoSeed[] = [
  { de: 'Automarken', en: 'Car brands' },
  { de: 'Dinge, die man im Kühlschrank findet', en: 'Things you find in a fridge' },
  { de: 'Obstsorten', en: 'Types of fruit' },
  { de: 'Gemüsesorten', en: 'Vegetables' },
  { de: 'Haustiere', en: 'Pets' },
  { de: 'Tiere auf dem Bauernhof', en: 'Farm animals' },
  { de: 'Länder in Europa', en: 'Countries in Europe' },
  { de: 'Hauptstädte', en: 'Capital cities' },
  { de: 'Sportarten', en: 'Sports' },
  { de: 'Sportarten mit Ball', en: 'Sports played with a ball' },
  { de: 'Dinge, die man im Supermarkt kauft', en: 'Things you buy at the supermarket' },
  { de: 'Berufe', en: 'Jobs' },
  { de: 'Kleidungsstücke', en: 'Items of clothing' },
  { de: 'Dinge im Badezimmer', en: 'Things in a bathroom' },
  { de: 'Dinge in der Küche', en: 'Things in a kitchen' },
  { de: 'Möbelstücke', en: 'Pieces of furniture' },
  { de: 'Farben', en: 'Colors' },
  { de: 'Körperteile', en: 'Body parts' },
  { de: 'Getränke', en: 'Drinks' },
  { de: 'Cocktails', en: 'Cocktails' },
  { de: 'Biermarken', en: 'Beer brands' },
  { de: 'Pizzabeläge', en: 'Pizza toppings' },
  { de: 'Gewürze und Kräuter', en: 'Spices and herbs' },
  { de: 'Süßigkeiten', en: 'Sweets and candy' },
  { de: 'Schokoriegel', en: 'Chocolate bars' },
  { de: 'Käsesorten', en: 'Types of cheese' },
  { de: 'Brotsorten', en: 'Types of bread' },
  { de: 'Nudelsorten', en: 'Pasta shapes' },
  { de: 'Dinge, die man zum Frühstück isst', en: 'Things you eat for breakfast' },
  { de: 'Fast-Food-Ketten', en: 'Fast food chains' },
  { de: 'Modemarken', en: 'Fashion brands' },
  { de: 'Sportmarken', en: 'Sportswear brands' },
  { de: 'Elektronikmarken', en: 'Electronics brands' },
  { de: 'Social-Media-Apps', en: 'Social media apps' },
  { de: 'Apps auf dem Handy', en: 'Apps on your phone' },
  { de: 'Videospiele', en: 'Video games' },
  { de: 'Brettspiele', en: 'Board games' },
  { de: 'Kartenspiele', en: 'Card games' },
  { de: 'Disney-Filme', en: 'Disney movies' },
  { de: 'Pixar-Filme', en: 'Pixar movies' },
  { de: 'Harry-Potter-Figuren', en: 'Harry Potter characters' },
  { de: 'Superhelden', en: 'Superheroes' },
  { de: 'Bösewichte aus Filmen', en: 'Movie villains' },
  { de: 'Zeichentrickfiguren', en: 'Cartoon characters' },
  { de: 'Simpsons-Figuren', en: 'Simpsons characters' },
  { de: 'Märchen', en: 'Fairy tales' },
  { de: 'Märchenfiguren', en: 'Fairy tale characters' },
  { de: 'Fernsehserien', en: 'TV series' },
  { de: 'Dinge, die blau sind', en: 'Things that are blue' },
  { de: 'Dinge aus Papier', en: 'Things made of paper' },
  { de: 'Songs der Beatles', en: 'Songs by the Beatles' },
  { de: 'Dinge mit Knöpfen', en: 'Things with buttons' },
  { de: 'Musikrichtungen', en: 'Music genres' },
  { de: 'Dinge, die kleben', en: 'Things that are sticky' },
  { de: 'Dinge auf dem Flohmarkt', en: 'Things at a flea market' },
  { de: 'Vornamen für Mädchen', en: 'Girls’ names' },
  { de: 'Schauspieler aus Hollywood', en: 'Hollywood actors' },
  { de: 'Fußballvereine', en: 'Football clubs' },
  { de: 'Fußballspieler', en: 'Football players' },
  { de: 'Olympische Sportarten', en: 'Olympic sports' },
  { de: 'Wintersportarten', en: 'Winter sports' },
  { de: 'Dinge am Strand', en: 'Things at the beach' },
  { de: 'Dinge, die man in den Koffer packt', en: 'Things you pack in a suitcase' },
  { de: 'Dinge im Klassenzimmer', en: 'Things in a classroom' },
  { de: 'Dinge im Büro', en: 'Things in an office' },
  { de: 'Dinge im Auto', en: 'Things in a car' },
  { de: 'Dinge in einer Handtasche', en: 'Things in a handbag' },
  { de: 'Dinge im Garten', en: 'Things in a garden' },
  { de: 'Werkzeuge', en: 'Tools' },
  { de: 'Küchengeräte', en: 'Kitchen appliances' },
  { de: 'Dinge mit Stecker', en: 'Things that plug into a socket' },
  { de: 'Schulfächer', en: 'School subjects' },
  { de: 'Sprachen', en: 'Languages' },
  { de: 'Tiere im Zoo', en: 'Zoo animals' },
  { de: 'Meerestiere', en: 'Sea creatures' },
  { de: 'Vögel', en: 'Birds' },
  { de: 'Insekten und Krabbeltiere', en: 'Insects and creepy crawlies' },
  { de: 'Hunderassen', en: 'Dog breeds' },
  { de: 'Dinosaurier', en: 'Dinosaurs' },
  { de: 'Blumen', en: 'Flowers' },
  { de: 'Baumarten', en: 'Types of trees' },
  { de: 'Dinge im Weltall', en: 'Things in space' },
  { de: 'Wetterlagen und Wetterphänomene', en: 'Types of weather' },
  { de: 'Naturkatastrophen', en: 'Natural disasters' },
  { de: 'Berühmte Berge', en: 'Famous mountains' },
  { de: 'Flüsse', en: 'Rivers' },
  { de: 'Inseln', en: 'Islands' },
  { de: 'Städte in Deutschland', en: 'Cities in Germany' },
  { de: 'Städte in den USA', en: 'Cities in the USA' },
  { de: 'Länder in Afrika', en: 'Countries in Africa' },
  { de: 'Länder in Asien', en: 'Countries in Asia' },
  { de: 'Berühmte Sehenswürdigkeiten', en: 'Famous landmarks' },
  { de: 'Urlaubsziele', en: 'Holiday destinations' },
  { de: 'Verkehrsmittel', en: 'Means of transport' },
  { de: 'Fluggesellschaften', en: 'Airlines' },
  { de: 'Dinge mit Rädern', en: 'Things with wheels' },
  { de: 'Dinge, die fliegen', en: 'Things that fly' },
  { de: 'Dinge, die man aufladen muss', en: 'Things you need to charge' },
  { de: 'Dinge, die rund sind', en: 'Things that are round' },
  { de: 'Dinge, die rot sind', en: 'Things that are red' },
  { de: 'Dinge, die grün sind', en: 'Things that are green' },
  { de: 'Dinge, die gelb sind', en: 'Things that are yellow' },
  { de: 'Dinge, die stinken', en: 'Things that smell bad' },
  { de: 'Dinge, die gut riechen', en: 'Things that smell good' },
  { de: 'Dinge, die heiß werden', en: 'Things that get hot' },
  { de: 'Dinge, die kalt sind', en: 'Things that are cold' },
  { de: 'Dinge, die man in der Apotheke kauft', en: 'Things you buy at a pharmacy' },
  { de: 'Dinge, die Lärm machen', en: 'Things that make noise' },
  { de: 'Dinge aus Holz', en: 'Things made of wood' },
  { de: 'Dinge aus Glas', en: 'Things made of glass' },
  { de: 'Dinge aus Plastik', en: 'Things made of plastic' },
  { de: 'Dinge aus Metall', en: 'Things made of metal' },
  { de: 'Dinge, die man auf dem Kopf trägt', en: 'Things you wear on your head' },
  { de: 'Schuharten', en: 'Types of shoes' },
  { de: 'Schmuckstücke', en: 'Types of jewelry' },
  { de: 'Dinge im Schlafzimmer', en: 'Things in a bedroom' },
  { de: 'Dinge im Wohnzimmer', en: 'Things in a living room' },
  { de: 'Dinge im Kinderzimmer', en: 'Things in a kid’s room' },
  { de: 'Spielzeug', en: 'Toys' },
  { de: 'Spiele für draußen', en: 'Outdoor games' },
  { de: 'Partyspiele', en: 'Party games' },
  { de: 'Trinkspiele', en: 'Drinking games' },
  { de: 'Dinge auf einer Party', en: 'Things at a party' },
  { de: 'Dinge, die zu Weihnachten gehören', en: 'Things that go with Christmas' },
  { de: 'Feiertage', en: 'Holidays' },
  { de: 'Halloween-Kostüme', en: 'Halloween costumes' },
  { de: 'Dinge auf einer Hochzeit', en: 'Things at a wedding' },
  { de: 'Dinge im Krankenhaus', en: 'Things in a hospital' },
  { de: 'Krankheiten', en: 'Illnesses' },
  { de: 'Übungen im Fitnessstudio', en: 'Exercises at the gym' },
  { de: 'Dinge auf einer Baustelle', en: 'Things on a construction site' },
  { de: 'Kampfsportarten', en: 'Martial arts' },
  { de: 'Italienische Gerichte', en: 'Italian dishes' },
  { de: 'Asiatische Gerichte', en: 'Asian dishes' },
  { de: 'Desserts', en: 'Desserts' },
  { de: 'Kuchen und Torten', en: 'Cakes' },
  { de: 'Eissorten', en: 'Ice cream flavors' },
  { de: 'Saucen und Dips', en: 'Sauces and dips' },
  { de: 'Dinge, die man grillt', en: 'Things you put on the grill' },
  { de: 'Brotbeläge', en: 'Things you put on a sandwich' },
  { de: 'Nüsse und Kerne', en: 'Nuts and seeds' },
  { de: 'Speisefische und Meeresfrüchte', en: 'Fish and seafood you can eat' },
  { de: 'Kaffeespezialitäten', en: 'Coffee drinks' },
  { de: 'Teesorten', en: 'Types of tea' },
  { de: 'Spirituosen', en: 'Spirits and liquors' },
  { de: 'Softdrinks', en: 'Soft drinks' },
  { de: 'Milchprodukte', en: 'Dairy products' },
  { de: 'Gerichte mit Kartoffeln', en: 'Potato dishes' },
  { de: 'Gerichte mit Eiern', en: 'Dishes made with eggs' },
  { de: 'Automodelle', en: 'Car models' },
  { de: 'Teile eines Autos', en: 'Parts of a car' },
  { de: 'Teile eines Fahrrads', en: 'Parts of a bike' },
  { de: 'Teile eines Hauses', en: 'Parts of a house' },
  { de: 'Räume in einem Haus', en: 'Rooms in a house' },
  { de: 'Gebäude in einer Stadt', en: 'Buildings in a town' },
  { de: 'Arten von Geschäften', en: 'Types of shops' },
  { de: 'Dinge auf einem Spielplatz', en: 'Things on a playground' },
  { de: 'Dinge im Wald', en: 'Things in a forest' },
  { de: 'Dinge am Himmel', en: 'Things in the sky' },
  { de: 'Dinge im Zirkus', en: 'Things at a circus' },
  { de: 'Fahrgeschäfte im Freizeitpark', en: 'Theme park rides' },
  { de: 'Dinge im Kino', en: 'Things at the cinema' },
  { de: 'Dinge, die man im Urlaub macht', en: 'Things you do on vacation' },
  { de: 'Hobbys', en: 'Hobbies' },
  { de: 'Aufgaben im Haushalt', en: 'Household chores' },
  { de: 'Gefühle', en: 'Emotions' },
  { de: 'Charaktereigenschaften', en: 'Personality traits' },
  { de: 'Ausreden fürs Zuspätkommen', en: 'Excuses for being late' },
  { de: 'Dinge, die man zum Camping mitnimmt', en: 'Things you take camping' },
  { de: 'Dinge in einem Hotelzimmer', en: 'Things in a hotel room' },
  { de: 'Dinge im Flugzeug', en: 'Things on a plane' },
  { de: 'Dinge am Bahnhof', en: 'Things at a train station' },
  { de: 'Dinge am Flughafen', en: 'Things at an airport' },
  { de: 'Superkräfte', en: 'Superpowers' },
  { de: 'Fabelwesen', en: 'Mythical creatures' },
  { de: 'Götter aus der Mythologie', en: 'Gods from mythology' },
  { de: 'Berühmte Maler', en: 'Famous painters' },
  { de: 'Berühmte Wissenschaftler', en: 'Famous scientists' },
  { de: 'US-Präsidenten', en: 'US presidents' },
  { de: 'Dinge in einer Bibliothek', en: 'Things in a library' },
  { de: 'Berühmte Personen aus der Geschichte', en: 'Famous historical figures' },
  { de: 'Währungen', en: 'Currencies' },
  { de: 'Star-Wars-Figuren', en: 'Star Wars characters' },
  { de: 'Pokémon', en: 'Pokémon' },
  { de: 'Figuren aus Super Mario', en: 'Super Mario characters' },
  { de: 'Zeichentrickserien', en: 'Animated series' },
  { de: 'Filme mit Tom Hanks', en: 'Movies with Tom Hanks' },
  { de: 'Filmreihen', en: 'Film franchises' },
  { de: 'Horrorfilme', en: 'Horror movies' },
  { de: 'Dinge mit Löchern', en: 'Things with holes' },
  { de: 'Wassersportarten', en: 'Water sports' },
  { de: 'Dinge im Schwimmbad', en: 'Things at a swimming pool' },
  { de: 'Dinge, die man in der Hosentasche hat', en: 'Things you keep in your pocket' },
  { de: 'Dinge, die man oft verliert', en: 'Things people often lose' },
  { de: 'Beliebte Geschenke', en: 'Popular gifts' },
  { de: 'Stoffe', en: 'Fabrics' },
  { de: 'Frisuren', en: 'Hairstyles' },
  { de: 'Kosmetikprodukte', en: 'Beauty products' },
  { de: 'Dinge aus dem Baumarkt', en: 'Things from a hardware store' },
  { de: 'Dinge in einem Restaurant', en: 'Things in a restaurant' },
];
