import type { HotPotatoSeed } from './types';

export const partyPrompts: HotPotatoSeed[] = [
  { de: 'Whiskymarken', en: 'Whisky brands' },
  { de: 'Wodkamarken', en: 'Vodka brands' },
  { de: 'Rummarken', en: 'Rum brands' },
  { de: 'Ginmarken', en: 'Gin brands' },
  { de: 'Champagnermarken', en: 'Champagne brands' },
  { de: 'Likörsorten', en: 'Types of liqueur' },
  { de: 'Cocktails mit Wodka', en: 'Cocktails made with vodka' },
  { de: 'Cocktails mit Rum', en: 'Cocktails made with rum' },
  { de: 'Cocktails mit Gin', en: 'Cocktails made with gin' },
  { de: 'Cocktails mit Tequila', en: 'Cocktails made with tequila' },
  { de: 'Cocktails mit Whisky', en: 'Cocktails made with whisky' },
  { de: 'Shots und Kurze', en: 'Shots and shooters' },
  { de: 'Getränke mit Cola', en: 'Drinks made with cola' },
  { de: 'Getränke mit Orangensaft', en: 'Drinks made with orange juice' },
  { de: 'Zutaten für eine Bowle', en: 'Ingredients for a party punch' },
  { de: 'Rote Getränke', en: 'Red drinks' },
  { de: 'Getränke, die man mit Strohhalm trinkt', en: 'Drinks you sip through a straw' },
  { de: 'Getränke aus Italien', en: 'Drinks from Italy' },
  { de: 'Getränke aus Frankreich', en: 'Drinks from France' },
  { de: 'Getränke aus Deutschland', en: 'Drinks from Germany' },
  { de: 'Getränke aus Großbritannien und Irland', en: 'Drinks from the UK and Ireland' },
  { de: 'Getränke aus den USA', en: 'Drinks from the USA' },
  { de: 'Getränke aus Spanien und Portugal', en: 'Drinks from Spain and Portugal' },
  { de: 'Getränke aus Lateinamerika', en: 'Drinks from Latin America' },
  { de: 'Getränke aus der Karibik', en: 'Drinks from the Caribbean' },
  { de: 'Getränke aus Asien', en: 'Drinks from Asia' },
  { de: 'Getränke aus Osteuropa', en: 'Drinks from Eastern Europe' },
  { de: 'Getränke aus Griechenland, der Türkei und dem Balkan', en: 'Drinks from Greece, Turkey and the Balkans' },
  { de: 'Prost in anderen Sprachen', en: 'Ways to say cheers in other languages' },
  { de: 'Trinksprüche', en: 'Drinking toasts and sayings' },
  { de: 'Spitznamen für Getränke', en: 'Nicknames for drinks' },
  { de: 'Deko und Garnitur für Drinks', en: 'Drink garnishes and decorations' },
  { de: 'Barzubehör', en: 'Bar tools' },
  { de: 'Glasarten', en: 'Types of glasses' },
  { de: 'Dinge, aus denen man trinken kann', en: 'Things you can drink out of' },
  { de: 'Dinge, mit denen man eine Flasche öffnen kann', en: 'Things you can open a bottle with' },
  { de: 'Begriffe, die man an der Bar hört', en: 'Phrases you hear at a bar' },
  { de: 'Weinregionen', en: 'Wine regions' },
  { de: 'Begriffe rund um Wein', en: 'Wine words' },
  { de: 'Dinge bei einer Weinprobe', en: 'Things at a wine tasting' },
  { de: 'Dinge in einer Brauerei', en: 'Things in a brewery' },
  { de: 'Dinge im Biergarten', en: 'Things in a beer garden' },
  { de: 'Dinge im Bierzelt', en: 'Things in a beer tent' },
  { de: 'Dinge in einem Irish Pub', en: 'Things in an Irish pub' },
  { de: 'Arten von Bars', en: 'Types of bars' },
  { de: 'Dinge in einer Karaokebar', en: 'Things in a karaoke bar' },
  { de: 'Dinge in einer Bowlingbahn', en: 'Things at a bowling alley' },
  { de: 'Dinge in einem Casino', en: 'Things in a casino' },
  { de: 'Begriffe beim Poker', en: 'Poker terms' },
  { de: 'Begriffe beim Billard', en: 'Pool and billiards terms' },
  { de: 'Begriffe beim Darts', en: 'Darts terms' },
  { de: 'Themen bei einem Kneipenquiz', en: 'Pub quiz categories' },
  { de: 'Lustige Teamnamen für ein Kneipenquiz', en: 'Funny pub quiz team names' },
  { de: 'Sätze bei „Ich hab noch nie“', en: 'Never Have I Ever statements' },
  { de: 'Fragen bei Wahrheit oder Pflicht', en: 'Questions for Truth or Dare' },
  { de: 'Begriffe zum Vorspielen bei Scharade', en: 'Things to act out in charades' },
  { de: 'Strafen für den Verlierer eines Spiels', en: 'Forfeits for the loser of a game' },
  { de: 'Gründe, beim Trinkspiel einen Schluck zu nehmen', en: 'Reasons to take a sip in a drinking game' },
  { de: 'Ausreden, wenn man ein Spiel verliert', en: 'Excuses for losing a game' },
  { de: 'Partyspiele mit Musik', en: 'Party games with music' },
  { de: 'Spiele, für die man nichts braucht', en: 'Games you can play with nothing at all' },
  { de: 'Spiele mit Stift und Papier', en: 'Pen-and-paper games' },
  { de: 'Kategorien bei Stadt, Land, Fluss', en: 'Categories for Scattergories' },
  { de: 'Rollen bei Werwolf oder Mafia', en: 'Roles in Werewolf or Mafia' },
  { de: 'Spiele auf Kindergeburtstagen', en: 'Games at kids’ birthday parties' },
  { de: 'Videospiele für Partys', en: 'Video games for parties' },
  { de: 'Dinge, die man für einen Spieleabend braucht', en: 'Things you need for a game night' },
  { de: 'Dinge, die man beim Junggesellinnenabschied trägt', en: 'Things people wear at a bachelorette party' },
  { de: 'Aktivitäten für einen Gruppenausflug', en: 'Activities for a group outing' },
  { de: 'Anlässe für eine Party', en: 'Occasions to throw a party' },
  { de: 'Arten von Partys', en: 'Types of parties' },
  { de: 'Wörter für Party', en: 'Words for a party' },
  { de: 'Mottopartys', en: 'Party themes' },
  { de: 'Pärchenkostüme', en: 'Couple costumes' },
  { de: 'Gruppenkostüme', en: 'Group costumes' },
  { de: 'Kostüme, die man in fünf Minuten bastelt', en: 'Last-minute costumes' },
  { de: 'Partydeko', en: 'Party decorations' },
  { de: 'Dinge, die man aufblasen kann', en: 'Inflatable party things' },
  { de: 'Dinge, die auf einer Party leuchten', en: 'Things that light up at a party' },
  { de: 'Dinge, die man auf einer Feier anzündet', en: 'Things you light at a party' },
  { de: 'Dinge, die auf einer Party knallen', en: 'Things that pop or bang at a party' },
  { de: 'Dinge, die man auf einer Feier wirft', en: 'Things people throw at celebrations' },
  { de: 'Requisiten für die Fotobox', en: 'Photo booth props' },
  { de: 'Fotoposen', en: 'Photo poses' },
  { de: 'Was in eine Partyeinladung gehört', en: 'Things you put on a party invitation' },
  { de: 'Dinge, die man zu einer Party mitbringt', en: 'Things you bring to a party' },
  { de: 'Dinge, die man nicht zu einer Party mitbringen sollte', en: 'Things you should not bring to a party' },
  { de: 'Dinge, die man vor einer Hausparty versteckt', en: 'Things you hide before a house party' },
  { de: 'Regeln für eine Hausparty', en: 'House party rules' },
  { de: 'Dinge, die man zum Vorglühen braucht', en: 'Things you need for pregaming' },
  { de: 'Rituale vor dem Ausgehen', en: 'Getting-ready rituals before a night out' },
  { de: 'Fragen, die Eltern vor dem Ausgehen stellen', en: 'Questions parents ask before you go out' },
  { de: 'Dinge, die man beim Ausgehen dabeihat', en: 'Things you carry on a night out' },
  { de: 'Dinge, die eine gute Party ausmachen', en: 'Things that make a great party' },
  { de: 'Dinge, die ein guter Gastgeber tut', en: 'Things a good host does' },
  { de: 'Dinge, die ein schlechter Gast tut', en: 'Things a bad guest does' },
  { de: 'Gründe, warum eine Party langweilig ist', en: 'Reasons a party is boring' },
  { de: 'Dinge, die auf einer Party ausgehen', en: 'Things that run out at a party' },
  { de: 'Dinge, die man auf einer Party sucht', en: 'Things people look for at a party' },
  { de: 'Orte, an denen man auf einer Party herumsteht', en: 'Spots where people hang out at a party' },
  { de: 'Sätze, die man auf jeder Party hört', en: 'Things you hear at every party' },
  { de: 'Geräusche auf einer Party', en: 'Sounds at a party' },
  { de: 'Gerüche auf einer Party', en: 'Smells at a party' },
  { de: 'Typen auf jeder Party', en: 'Types of people at every party' },
  { de: 'Smalltalk-Themen auf einer Party', en: 'Small talk topics at a party' },
  { de: 'Themen, die man auf einer Party meiden sollte', en: 'Topics to avoid at a party' },
  { de: 'Fragen zum Kennenlernen', en: 'Getting-to-know-you questions' },
  { de: 'Flirtsprüche', en: 'Pickup lines' },
  { de: 'Promis, die man gern auf seiner Party hätte', en: 'Celebrities you’d invite to your party' },
  { de: 'Gründe, noch ein bisschen zu bleiben', en: 'Reasons to stay a little longer' },
  { de: 'Gründe, eine Runde auszugeben', en: 'Reasons to buy a round' },
  { de: 'Gründe, die Bar zu wechseln', en: 'Reasons to move on to another bar' },
  { de: 'Gründe, warum der Abend eskaliert', en: 'Reasons a night gets out of hand' },
  { de: 'Gründe für einen Streit auf einer Party', en: 'Reasons for a fight at a party' },
  { de: 'Gründe, warum jemand auf einer Party weint', en: 'Reasons someone cries at a party' },
  { de: 'Gründe, warum die Polizei zur Party kommt', en: 'Reasons the police show up at a party' },
  { de: 'Dinge, über die sich Nachbarn beschweren', en: 'Things neighbors complain about' },
  { de: 'Dinge, die auf einer Party kaputtgehen', en: 'Things that break at a party' },
  { de: 'Dinge, die eine Party im Freien ruinieren', en: 'Things that ruin an outdoor party' },
  { de: 'Dinge, die bei einer Überraschungsparty schiefgehen', en: 'Things that go wrong at a surprise party' },
  { de: 'Dinge, die auf einer Firmenfeier schiefgehen', en: 'Things that go wrong at an office party' },
  { de: 'Peinliche Partymomente', en: 'Embarrassing party moments' },
  { de: 'Party-Klischees aus Filmen', en: 'Party clichés from movies' },
  { de: 'Partyfilme', en: 'Party movies' },
  { de: 'Kneipen und Bars aus Filmen und Serien', en: 'Bars and pubs from movies and TV' },
  { de: 'Fiktive Figuren, die gern trinken', en: 'Fictional characters who love a drink' },
  { de: 'Prominente, die für ihre Partys bekannt sind', en: 'Celebrities known for partying' },
  { de: 'Events, die man gemeinsam schaut', en: 'Big events to watch with friends' },
  { de: 'Dinge auf einer WM-Party', en: 'Things at a World Cup viewing party' },
  { de: 'Arten, einen Sieg zu feiern', en: 'Ways to celebrate a win' },
  { de: 'Dinge, die man im Club sieht', en: 'Things you see in a club' },
  { de: 'Dinge auf der Toilette im Club', en: 'Things you see in a club bathroom' },
  { de: 'Gründe, nicht in den Club zu kommen', en: 'Reasons to get turned away at the club' },
  { de: 'Berufe im Nachtleben', en: 'Nightlife jobs' },
  { de: 'Dinge, die ein Barkeeper hasst', en: 'Things bartenders hate' },
  { de: 'Tanzbewegungen', en: 'Dance moves' },
  { de: 'Dinge auf einem Rave', en: 'Things at a rave' },
  { de: 'Dinge, die man nach Mitternacht macht', en: 'Things you do after midnight' },
  { de: 'Wege, nach dem Feiern heimzukommen', en: 'Ways to get home after a night out' },
  { de: 'Dinge, die man im Nachtbus sieht', en: 'Things you see on the night bus' },
  { de: 'Dinge, die man auf dem Heimweg macht', en: 'Things you do on the way home from a party' },
  { de: 'Dinge, die Betrunkene sagen', en: 'Things drunk people say' },
  { de: 'Dinge, die Betrunkene tun', en: 'Things drunk people do' },
  { de: 'Wörter für betrunken', en: 'Words for being drunk' },
  { de: 'Geheimnisse, die betrunken herauskommen', en: 'Secrets that come out when drunk' },
  { de: 'Dinge, die man betrunken online kauft', en: 'Things you buy online when drunk' },
  { de: 'Dinge, die man um drei Uhr nachts googelt', en: 'Things you google at 3 a.m.' },
  { de: 'Dinge, die man betrunken verliert', en: 'Things people lose when drunk' },
  { de: 'Dinge, die man nach dem Feiern in den Taschen findet', en: 'Things you find in your pockets after a night out' },
  { de: 'Dinge im Gruppenchat nach der Party', en: 'Things in the group chat after a party' },
  { de: 'Katersymptome', en: 'Hangover symptoms' },
  { de: 'Dinge, die man am Tag nach einer Party macht', en: 'Things you do the day after a party' },
  { de: 'Dinge, die nach einer Party im Kühlschrank übrig sind', en: 'Leftovers in the fridge after a party' },
  { de: 'Dinge, die man nach einer Party aufräumt', en: 'Things you clean up after a party' },
  { de: 'Ausreden, um früher zu gehen', en: 'Excuses to leave a party early' },
  { de: 'Ausreden, um nichts zu trinken', en: 'Excuses for not drinking' },
  { de: 'Ausreden für die Eltern nach einer langen Nacht', en: 'Excuses for your parents after a long night' },
  { de: 'Ausreden für den Chef am Montag', en: 'Excuses for your boss on Monday morning' },
  { de: 'Partyinseln', en: 'Party islands' },
  { de: 'Berühmte Partymeilen', en: 'Famous nightlife streets' },
  { de: 'Dinge in Las Vegas', en: 'Things in Las Vegas' },
  { de: 'Feste auf der ganzen Welt', en: 'Festivals and celebrations around the world' },
  { de: 'Dinge, die man an Karneval sieht', en: 'Things you see at carnival' },
  { de: 'Dinge auf einem Stadtfest', en: 'Things at a street festival' },
  { de: 'Dinge auf einer Après-Ski-Party', en: 'Things at an après-ski party' },
  { de: 'Silvesterbräuche', en: 'New Year’s Eve traditions' },
  { de: 'Glücksbringer an Silvester', en: 'Good luck charms for New Year' },
  { de: 'Vorsätze fürs neue Jahr', en: 'New Year’s resolutions' },
  { de: 'Geburtstagstraditionen', en: 'Birthday traditions' },
  { de: 'Wichtelgeschenke', en: 'Secret Santa gifts' },
  { de: 'Preise bei einer Tombola', en: 'Raffle prizes' },
  { de: 'Spiele auf einer Hochzeit', en: 'Wedding games' },
  { de: 'Aufgaben von Trauzeugen', en: 'Best man and maid of honor duties' },
  { de: 'Dinge auf einem Abschlussball', en: 'Things at a prom' },
  { de: 'Dinge auf einer Babyparty', en: 'Things at a baby shower' },
  { de: 'Dinge auf einer Pyjamaparty', en: 'Things at a sleepover' },
  { de: 'Dinge auf einer Poolparty', en: 'Things at a pool party' },
  { de: 'Dinge auf einer Gartenparty', en: 'Things at a garden party' },
  { de: 'Dinge auf einer Halloween-Party', en: 'Things at a Halloween party' },
  { de: 'Dinge auf einer Party im Stil der 80er', en: 'Things at an 80s party' },
  { de: 'Dinge auf einer Party im Stil der 20er', en: 'Things at a Roaring Twenties party' },
  { de: 'Dinge auf einer Bad-Taste-Party', en: 'Things at a bad taste party' },
  { de: 'Dinge auf einer Hawaii-Party', en: 'Things at a Hawaiian party' },
  { de: 'Aktivitäten für eine Sommerparty', en: 'Summer party activities' },
  { de: 'Dinge am Lagerfeuer', en: 'Things around a campfire' },
  { de: 'Dinge auf dem Weihnachtsmarkt', en: 'Things at a Christmas market' },
  { de: 'Dinge im Partykeller', en: 'Things in a party basement' },
  { de: 'Dinge, die man aus leeren Flaschen machen kann', en: 'Things you can make from empty bottles' },
  { de: 'Dinge, die beim Grillen auf einer Party schiefgehen', en: 'Things that go wrong at a barbecue party' },
  { de: 'Essen auf einer Silvesterparty', en: 'Food at a New Year’s Eve party' },
  { de: 'Dinge, die in einer Kneipe an der Wand hängen', en: 'Things hanging on the walls of a pub' },
  { de: 'Party-Accessoires', en: 'Party accessories' },
  { de: 'Dinge an einer Strandbar', en: 'Things at a beach bar' },
  { de: 'Dinge auf einer Bootsparty', en: 'Things at a boat party' },
  { de: 'Dinge auf einer Einweihungsparty', en: 'Things at a housewarming party' },
  { de: 'Dinge, die auf einer Party verschüttet werden', en: 'Things that get spilled at a party' },
  { de: 'Dinge, die man nachts am Kiosk kauft', en: 'Things you buy at a late-night corner shop' },
  { de: 'Dinge, die man für ein Trinkspiel braucht', en: 'Things you need for a drinking game' },
  { de: 'Dinge in einem Hostel', en: 'Things in a hostel' },
  { de: 'Reiseziele für einen Junggesellenabschied', en: 'Destinations for a bachelor or bachelorette trip' },
];
