import type { HotPotatoSeed } from './types';

export const placesPrompts: HotPotatoSeed[] = [
  { de: 'Länder in Lateinamerika', en: 'Countries in Latin America' },
  { de: 'Länder in Osteuropa', en: 'Countries in Eastern Europe' },
  { de: 'Länder im Nahen Osten', en: 'Countries in the Middle East' },
  { de: 'Länder am Mittelmeer', en: 'Countries on the Mediterranean' },
  { de: 'Länder der Europäischen Union', en: 'Countries in the European Union' },
  { de: 'Länder, in denen man mit Euro bezahlt', en: 'Countries where you pay with euros' },
  { de: 'Länder, in denen man Spanisch spricht', en: 'Countries where people speak Spanish' },
  { de: 'Länder, in denen man Englisch spricht', en: 'Countries where people speak English' },
  { de: 'Länder, in denen man Französisch spricht', en: 'Countries where people speak French' },
  {
    de: 'Länder mit mehr als einer Amtssprache',
    en: 'Countries with more than one official language',
  },
  { de: 'Länder mit einem König oder einer Königin', en: 'Countries with a king or queen' },
  { de: 'Inselstaaten', en: 'Island nations' },
  { de: 'Länder ohne Zugang zum Meer', en: 'Landlocked countries' },
  { de: 'Länder mit Küste', en: 'Countries with a coastline' },
  { de: 'Länder auf der Südhalbkugel', en: 'Countries in the southern hemisphere' },
  { de: 'Länder mit Rot in der Flagge', en: 'Countries with red in their flag' },
  { de: 'Länder mit Sternen in der Flagge', en: 'Countries with stars on their flag' },
  { de: 'Länder, in denen Linksverkehr herrscht', en: 'Countries that drive on the left' },
  { de: 'Länder, die es nicht mehr gibt', en: 'Countries that no longer exist' },
  { de: 'Sehr kleine Länder', en: 'Very small countries' },
  { de: 'Sehr große Länder', en: 'Very large countries' },
  { de: 'Länder, die für ihr Essen bekannt sind', en: 'Countries known for their food' },
  { de: 'Länder, in denen Wein angebaut wird', en: 'Countries that produce wine' },
  { de: 'Länder, in denen man Ski fahren kann', en: 'Countries where you can go skiing' },
  { de: 'Länder mit Wüste', en: 'Countries with a desert' },
  { de: 'Länder mit Regenwald', en: 'Countries with rainforest' },
  { de: 'Länder, die bei Backpackern beliebt sind', en: 'Countries popular with backpackers' },
  { de: 'Starke Fußballnationen', en: 'Strong football nations' },
  {
    de: 'Länder, die schon eine Fußball-WM ausgerichtet haben',
    en: 'Countries that have hosted a World Cup',
  },
  {
    de: 'Länder, in denen jemand aus der Runde schon war',
    en: 'Countries someone in the group has visited',
  },
  { de: 'Hauptstädte in Europa', en: 'Capital cities in Europe' },
  { de: 'Hauptstädte in Asien', en: 'Capital cities in Asia' },
  { de: 'Hauptstädte in Amerika', en: 'Capital cities in the Americas' },
  { de: 'Landeshauptstädte in Deutschland', en: 'State capitals in Germany' },
  { de: 'Deutsche Bundesländer', en: 'German federal states' },
  { de: 'US-Bundesstaaten', en: 'US states' },
  { de: 'Städte in Bayern', en: 'Cities in Bavaria' },
  { de: 'Städte in Nordrhein-Westfalen', en: 'Cities in North Rhine-Westphalia' },
  { de: 'Städte im Ruhrgebiet', en: 'Cities in the Ruhr area' },
  { de: 'Städte in Ostdeutschland', en: 'Cities in eastern Germany' },
  { de: 'Städte in Norddeutschland', en: 'Cities in northern Germany' },
  { de: 'Städte am Rhein', en: 'Cities on the Rhine' },
  { de: 'Städte in Österreich', en: 'Cities in Austria' },
  { de: 'Städte in der Schweiz', en: 'Cities in Switzerland' },
  { de: 'Städte in Italien', en: 'Cities in Italy' },
  { de: 'Städte in Frankreich', en: 'Cities in France' },
  { de: 'Städte in Spanien', en: 'Cities in Spain' },
  { de: 'Städte in Großbritannien', en: 'Cities in the UK' },
  { de: 'Städte in den Niederlanden', en: 'Cities in the Netherlands' },
  { de: 'Städte in Skandinavien', en: 'Cities in Scandinavia' },
  { de: 'Städte in Osteuropa', en: 'Cities in Eastern Europe' },
  { de: 'Städte in der Türkei', en: 'Cities in Turkey' },
  { de: 'Städte in Kalifornien', en: 'Cities in California' },
  { de: 'Städte in Japan', en: 'Cities in Japan' },
  { de: 'Städte in China', en: 'Cities in China' },
  { de: 'Städte in Indien', en: 'Cities in India' },
  { de: 'Städte in Asien', en: 'Cities in Asia' },
  { de: 'Städte in Afrika', en: 'Cities in Africa' },
  { de: 'Städte in Südamerika', en: 'Cities in South America' },
  {
    de: 'Städte mit mehr als einer Million Einwohnern',
    en: 'Cities with more than a million people',
  },
  { de: 'Hafenstädte', en: 'Port cities' },
  { de: 'Universitätsstädte', en: 'University towns' },
  { de: 'Partystädte', en: 'Party cities' },
  { de: 'Städte mit U-Bahn', en: 'Cities with a subway' },
  { de: 'Städte mit berühmten Fußballvereinen', en: 'Cities with famous football clubs' },
  {
    de: 'Städte, in denen schon Olympische Spiele waren',
    en: 'Cities that have hosted the Olympics',
  },
  { de: 'Städte, in denen berühmte Filme spielen', en: 'Cities where famous films are set' },
  {
    de: 'Städte, in denen jemand aus der Runde schon war',
    en: 'Cities someone in the group has visited',
  },
  { de: 'Städte für einen Wochenendtrip', en: 'Cities for a weekend trip' },
  { de: 'Antike Städte', en: 'Ancient cities' },
  { de: 'Orte an der Nord- und Ostsee', en: 'Towns on the North Sea and Baltic coast' },
  { de: 'Urlaubsregionen in Deutschland', en: 'Holiday regions in Germany' },
  { de: 'Regionen in Italien', en: 'Regions of Italy' },
  { de: 'Regionen in Frankreich', en: 'Regions of France' },
  { de: 'Regionen der Welt', en: 'Regions of the world' },
  { de: 'Inseln im Mittelmeer', en: 'Islands in the Mediterranean' },
  { de: 'Deutsche Inseln', en: 'German islands' },
  { de: 'Griechische Inseln', en: 'Greek islands' },
  { de: 'Inseln in der Karibik', en: 'Caribbean islands' },
  { de: 'Halbinseln', en: 'Peninsulas' },
  { de: 'Flüsse in Europa', en: 'Rivers in Europe' },
  { de: 'Flüsse in Deutschland', en: 'Rivers in Germany' },
  { de: 'Seen', en: 'Lakes' },
  { de: 'Meere und Ozeane', en: 'Seas and oceans' },
  { de: 'Gebirge', en: 'Mountain ranges' },
  { de: 'Vulkane', en: 'Volcanoes' },
  { de: 'Wüsten', en: 'Deserts' },
  { de: 'Nationalparks', en: 'National parks' },
  { de: 'Berühmte Strände', en: 'Famous beaches' },
  { de: 'Skigebiete', en: 'Ski resorts' },
  { de: 'Orte im Weltall', en: 'Places in space' },
  { de: 'Sehenswürdigkeiten in Paris', en: 'Sights in Paris' },
  { de: 'Sehenswürdigkeiten in London', en: 'Sights in London' },
  { de: 'Sehenswürdigkeiten in Rom', en: 'Sights in Rome' },
  { de: 'Sehenswürdigkeiten in New York', en: 'Sights in New York' },
  { de: 'Sehenswürdigkeiten in Berlin', en: 'Sights in Berlin' },
  { de: 'Sehenswürdigkeiten in München', en: 'Sights in Munich' },
  { de: 'Sehenswürdigkeiten in Hamburg', en: 'Sights in Hamburg' },
  { de: 'Sehenswürdigkeiten in Wien', en: 'Sights in Vienna' },
  { de: 'Sehenswürdigkeiten in Barcelona', en: 'Sights in Barcelona' },
  { de: 'Sehenswürdigkeiten in Amsterdam', en: 'Sights in Amsterdam' },
  { de: 'Sehenswürdigkeiten in Deutschland', en: 'Sights in Germany' },
  { de: 'Sehenswürdigkeiten in Österreich', en: 'Sights in Austria' },
  { de: 'Sehenswürdigkeiten in der Schweiz', en: 'Sights in Switzerland' },
  { de: 'Sehenswürdigkeiten in Italien', en: 'Sights in Italy' },
  { de: 'Sehenswürdigkeiten in Spanien', en: 'Sights in Spain' },
  { de: 'Sehenswürdigkeiten in den USA', en: 'Sights in the USA' },
  { de: 'Sehenswürdigkeiten in Asien', en: 'Sights in Asia' },
  { de: 'Sehenswürdigkeiten in Ägypten', en: 'Sights in Egypt' },
  { de: 'Berühmte Bauwerke', en: 'Famous buildings' },
  { de: 'Berühmte Brücken', en: 'Famous bridges' },
  { de: 'Berühmte Türme', en: 'Famous towers' },
  { de: 'Berühmte Schlösser und Burgen', en: 'Famous castles and palaces' },
  { de: 'Berühmte Kirchen und Kathedralen', en: 'Famous churches and cathedrals' },
  { de: 'Berühmte Plätze', en: 'Famous squares' },
  { de: 'Berühmte Straßen', en: 'Famous streets' },
  { de: 'Berühmte Museen', en: 'Famous museums' },
  { de: 'Berühmte Stadien', en: 'Famous stadiums' },
  { de: 'Berühmte Konzertorte', en: 'Famous concert venues' },
  { de: 'Berühmte Gefängnisse', en: 'Famous prisons' },
  { de: 'Ruinen und archäologische Stätten', en: 'Ruins and archaeological sites' },
  { de: 'UNESCO-Welterbestätten', en: 'UNESCO World Heritage Sites' },
  { de: 'Freizeitparks', en: 'Theme parks' },
  { de: 'Formel-1-Strecken', en: 'Formula 1 circuits' },
  { de: 'Flughäfen', en: 'Airports' },
  { de: 'Fiktive Orte', en: 'Fictional places' },
  { de: 'Orte aus Harry Potter', en: 'Places from Harry Potter' },
  { de: 'Orte aus der Bibel', en: 'Places in the Bible' },
  { de: 'Orte, die in Songtiteln vorkommen', en: 'Places that appear in song titles' },
  { de: 'Gebäude in einem Dorf', en: 'Buildings in a village' },
  { de: 'Arten von Unterkünften', en: 'Types of accommodation' },
  { de: 'Landschaftsformen', en: 'Types of landscape' },
  { de: 'Arten von Gewässern', en: 'Types of bodies of water' },
  { de: 'Orte in der Natur', en: 'Places in nature' },
  { de: 'Orte in einer Schule', en: 'Places in a school' },
  { de: 'Orte in einem Krankenhaus', en: 'Places in a hospital' },
  { de: 'Orte in einem Hotel', en: 'Places in a hotel' },
  { de: 'Orte in einem Einkaufszentrum', en: 'Places in a shopping mall' },
  { de: 'Orte auf einem Bauernhof', en: 'Places on a farm' },
  { de: 'Orte unter der Erde', en: 'Places underground' },
  { de: 'Orte, an denen man warten muss', en: 'Places where you have to wait' },
  { de: 'Orte, an denen man Schlange steht', en: 'Places where you stand in line' },
  { de: 'Orte, an denen man leise sein muss', en: 'Places where you have to be quiet' },
  { de: 'Orte, an denen es laut ist', en: 'Places that are loud' },
  { de: 'Orte, an denen es kalt ist', en: 'Places where it’s cold' },
  { de: 'Orte, an denen es heiß ist', en: 'Places where it’s hot' },
  { de: 'Orte, an denen man nass wird', en: 'Places where you get wet' },
  { de: 'Orte, an denen man nackt ist', en: 'Places where people are naked' },
  { de: 'Orte, an denen man schlafen kann', en: 'Places where you can sleep' },
  { de: 'Orte, an denen man Geld ausgibt', en: 'Places where you spend money' },
  { de: 'Orte, an denen man Eintritt zahlt', en: 'Places where you pay admission' },
  { de: 'Orte, an denen man Uniform trägt', en: 'Places where people wear uniforms' },
  { de: 'Orte, an denen man Sport treibt', en: 'Places where you do sports' },
  { de: 'Orte, an denen man Tiere sieht', en: 'Places where you see animals' },
  { de: 'Orte, an denen man Musik hört', en: 'Places where you hear music' },
  { de: 'Orte, an denen man essen gehen kann', en: 'Places to eat out' },
  { de: 'Orte zum Feiern', en: 'Places to party' },
  { de: 'Orte für ein erstes Date', en: 'Places for a first date' },
  { de: 'Romantische Orte', en: 'Romantic places' },
  { de: 'Gruselige Orte', en: 'Creepy places' },
  { de: 'Langweilige Orte', en: 'Boring places' },
  { de: 'Orte, an denen man heiraten kann', en: 'Places where you can get married' },
  { de: 'Orte für ein Picknick', en: 'Places for a picnic' },
  { de: 'Orte zum Lernen', en: 'Places to study' },
  { de: 'Orte für einen Kindergeburtstag', en: 'Places for a kid’s birthday party' },
  { de: 'Orte, die man als Kind geliebt hat', en: 'Places you loved as a kid' },
  { de: 'Orte, an denen man neue Leute kennenlernt', en: 'Places where you meet new people' },
  { de: 'Orte, an denen man Promis treffen könnte', en: 'Places where you might meet celebrities' },
  { de: 'Orte, an denen man sich verstecken kann', en: 'Places where you can hide' },
  { de: 'Orte, an denen man sich verlaufen kann', en: 'Places where you can get lost' },
  { de: 'Orte, an denen man Selfies macht', en: 'Places where people take selfies' },
  { de: 'Orte, die rund um die Uhr geöffnet haben', en: 'Places that are open 24/7' },
  { de: 'Orte, an denen man nicht rauchen darf', en: 'Places where you can’t smoke' },
  { de: 'Orte mit schlechtem Handyempfang', en: 'Places with bad phone signal' },
  {
    de: 'Orte, die nichts für Leute mit Höhenangst sind',
    en: 'Places that are bad if you’re afraid of heights',
  },
  { de: 'Orte, an denen man arbeiten kann', en: 'Places where people work' },
  { de: 'Orte, an denen man Souvenirs kauft', en: 'Places where you buy souvenirs' },
  { de: 'Hauptstädte in Afrika', en: 'Capital cities in Africa' },
  { de: 'Hauptstädte, die an einem Fluss liegen', en: 'Capital cities on a river' },
  { de: 'Städte in Kanada und Australien', en: 'Cities in Canada and Australia' },
  { de: 'Städte in Griechenland', en: 'Cities in Greece' },
  { de: 'Städte in Portugal', en: 'Cities in Portugal' },
  { de: 'Städte in Kroatien', en: 'Cities in Croatia' },
  { de: 'Städte in Baden-Württemberg', en: 'Cities in Baden-Württemberg' },
  { de: 'Städte in Hessen', en: 'Cities in Hesse' },
  {
    de: 'Seen in Deutschland, Österreich und der Schweiz',
    en: 'Lakes in Germany, Austria and Switzerland',
  },
  { de: 'Berge in den Alpen', en: 'Mountains in the Alps' },
  { de: 'Länder mit Vulkanen', en: 'Countries with volcanoes' },
  { de: 'Länder, die für Strandurlaub beliebt sind', en: 'Countries popular for beach holidays' },
  { de: 'Länder mit Grün in der Flagge', en: 'Countries with green in their flag' },
  {
    de: 'Länder, die man von Deutschland aus mit dem Zug erreicht',
    en: 'Countries you can reach by train from Germany',
  },
  { de: 'Orte an einem Flughafen', en: 'Places at an airport' },
  { de: 'Orte auf einem Kreuzfahrtschiff', en: 'Places on a cruise ship' },
  { de: 'Bereiche in einem Zoo', en: 'Areas in a zoo' },
  { de: 'Räume in einer Burg oder einem Schloss', en: 'Rooms in a castle' },
  { de: 'Orte in einem Büro', en: 'Places in an office' },
  { de: 'Orte auf einem Festival', en: 'Places at a festival' },
  { de: 'Orte, an denen man Sonnencreme braucht', en: 'Places where you need sunscreen' },
  { de: 'Orte, an denen man den Ausweis zeigen muss', en: 'Places where you have to show ID' },
  { de: 'Orte, an denen man sich schick anzieht', en: 'Places where you dress up' },
];
