import type { HotPotatoSeed } from './types';

export const popculturePrompts: HotPotatoSeed[] = [
  { de: 'Superheldinnen', en: 'Female superheroes' },
  { de: 'Marvel-Filme', en: 'Marvel movies' },
  { de: 'Pokémon-Typen', en: 'Pokémon types' },
  { de: 'Nintendo-Spiele', en: 'Nintendo games' },
  { de: 'Figuren aus Mario Kart', en: 'Mario Kart characters' },
  { de: 'Netflix-Serien', en: 'Netflix series' },
  { de: 'Sitcoms', en: 'Sitcoms' },
  { de: 'Anime-Serien', en: 'Anime series' },
  { de: 'Schauspielerinnen aus Hollywood', en: 'Hollywood actresses' },
  { de: 'Berühmte Webseiten', en: 'Famous websites' },
  { de: 'YouTuber', en: 'YouTubers' },
  { de: 'Influencer', en: 'Influencers' },
  { de: 'Twitch-Streamer', en: 'Twitch streamers' },
  { de: 'Podcasts', en: 'Podcasts' },
  { de: 'Streamingdienste', en: 'Streaming services' },
  { de: 'Funktionen von Social-Media-Apps', en: 'Social media app features' },
  { de: 'Dinge, die man auf Instagram postet', en: 'Things people post on Instagram' },
  { de: 'Dinge, für die Influencer Werbung machen', en: 'Things influencers advertise' },
  { de: 'Berühmte Memes', en: 'Famous memes' },
  { de: 'TikTok-Trends', en: 'TikTok trends' },
  { de: 'Emojis', en: 'Emojis' },
  { de: 'Tech-Gründer', en: 'Famous tech founders' },
  { de: 'Weihnachtsfilme', en: 'Christmas movies' },
  { de: 'Actionfilme', en: 'Action movies' },
  { de: 'Komödien', en: 'Comedy movies' },
  { de: 'Liebesfilme', en: 'Romantic movies' },
  { de: 'Animationsfilme', en: 'Animated movies' },
  { de: 'Science-Fiction-Filme', en: 'Science fiction movies' },
  { de: 'Kriegsfilme', en: 'War movies' },
  { de: 'Sportfilme', en: 'Sports movies' },
  { de: 'Kinderfilme', en: 'Kids’ movies' },
  { de: 'Filme mit Leonardo DiCaprio', en: 'Leonardo DiCaprio movies' },
  { de: 'Filme mit Tom Cruise', en: 'Tom Cruise movies' },
  { de: 'Filme mit Will Smith', en: 'Will Smith movies' },
  { de: 'Filme mit Jim Carrey', en: 'Jim Carrey movies' },
  { de: 'Filme mit Brad Pitt', en: 'Brad Pitt movies' },
  { de: 'Filme mit Johnny Depp', en: 'Johnny Depp movies' },
  { de: 'Filme mit Arnold Schwarzenegger', en: 'Arnold Schwarzenegger movies' },
  { de: 'Filme von Steven Spielberg', en: 'Steven Spielberg movies' },
  { de: 'James-Bond-Filme', en: 'James Bond movies' },
  { de: 'Filme, die einen Oscar gewonnen haben', en: 'Oscar-winning movies' },
  { de: 'Filme aus den 80ern', en: 'Movies from the 80s' },
  { de: 'Filme aus den 90ern', en: 'Movies from the 90s' },
  { de: 'Filme über Zeitreisen', en: 'Movies about time travel' },
  { de: 'Filme, die im Weltraum spielen', en: 'Movies set in space' },
  { de: 'Zombiefilme und Zombieserien', en: 'Zombie movies and shows' },
  { de: 'Filme, die auf Büchern basieren', en: 'Movies based on books' },
  { de: 'Filme mit Dinosauriern', en: 'Movies with dinosaurs' },
  { de: 'Berühmte Filmzitate', en: 'Famous movie quotes' },
  { de: 'Filmgenres', en: 'Movie genres' },
  { de: 'Filmstudios', en: 'Film studios' },
  { de: 'Berühmte Regisseure', en: 'Famous film directors' },
  { de: 'Schauspieler mit Oscar', en: 'Oscar-winning actors' },
  { de: 'Schauspieler, die einen Superhelden gespielt haben', en: 'Actors who played a superhero' },
  { de: 'Schauspieler aus den Harry-Potter-Filmen', en: 'Actors from the Harry Potter movies' },
  { de: 'Ehemalige Kinderstars', en: 'Former child stars' },
  { de: 'Disney-Bösewichte', en: 'Disney villains' },
  { de: 'Disney-Figuren', en: 'Disney characters' },
  { de: 'Prinzessinnen aus Filmen', en: 'Princesses from movies' },
  { de: 'Bösewichte aus Horrorfilmen', en: 'Horror movie villains' },
  { de: 'Mitglieder der Avengers', en: 'Members of the Avengers' },
  { de: 'Batman-Bösewichte', en: 'Batman villains' },
  { de: 'Figuren der X-Men', en: 'X-Men characters' },
  { de: 'Marvel-Figuren', en: 'Marvel characters' },
  { de: 'DC-Figuren', en: 'DC characters' },
  { de: 'Figuren aus Game of Thrones', en: 'Game of Thrones characters' },
  { de: 'Figuren aus Der Herr der Ringe', en: 'Lord of the Rings characters' },
  { de: 'Figuren aus SpongeBob', en: 'SpongeBob characters' },
  { de: 'Figuren aus Toy Story', en: 'Toy Story characters' },
  { de: 'Figuren aus Stranger Things', en: 'Stranger Things characters' },
  { de: 'Figuren aus Star Trek', en: 'Star Trek characters' },
  { de: 'Figuren aus der Sesamstraße', en: 'Sesame Street characters' },
  { de: 'Figuren aus Dragon Ball', en: 'Dragon Ball characters' },
  { de: 'Figuren der Looney Tunes', en: 'Looney Tunes characters' },
  { de: 'Videospielfiguren', en: 'Video game characters' },
  { de: 'Anime-Figuren', en: 'Anime characters' },
  { de: 'Serienfiguren', en: 'TV show characters' },
  { de: 'Lehrer in Hogwarts', en: 'Hogwarts teachers' },
  { de: 'Zaubersprüche aus Harry Potter', en: 'Harry Potter spells' },
  { de: 'Zauberer aus Filmen und Büchern', en: 'Wizards from movies and books' },
  {
    de: 'Vampire und Werwölfe aus Filmen und Serien',
    en: 'Vampires and werewolves from movies and TV',
  },
  { de: 'Piraten aus Filmen und Büchern', en: 'Pirates from movies and books' },
  { de: 'Detektive aus Filmen und Büchern', en: 'Detectives from movies and books' },
  { de: 'Spione und Agenten aus Filmen', en: 'Spies and secret agents from movies' },
  { de: 'Berühmte Hunde aus Filmen und Serien', en: 'Famous dogs from movies and TV' },
  { de: 'Berühmte Katzen aus Filmen und Serien', en: 'Famous cats from movies and TV' },
  { de: 'Tierfiguren aus Zeichentrickfilmen', en: 'Animal characters from cartoons' },
  { de: 'Roboter aus Filmen', en: 'Robots from movies' },
  { de: 'Außerirdische aus Filmen', en: 'Aliens from movies' },
  { de: 'Filmmonster', en: 'Movie monsters' },
  { de: 'Berühmte Filmautos', en: 'Famous movie cars' },
  { de: 'Fiktive Orte aus Filmen und Büchern', en: 'Fictional places from movies and books' },
  { de: 'Fiktive Figuren mit Brille', en: 'Fictional characters with glasses' },
  { de: 'Krimiserien', en: 'Crime series' },
  { de: 'Fantasyserien', en: 'Fantasy series' },
  { de: 'Kinderserien', en: 'Kids’ TV shows' },
  { de: 'Serien über Ärzte und Krankenhäuser', en: 'Medical TV shows' },
  { de: 'Serien über Teenager', en: 'TV shows about teenagers' },
  { de: 'Serien mit mehr als fünf Staffeln', en: 'TV shows with more than five seasons' },
  { de: 'Serien aus den 90ern', en: 'TV shows from the 90s' },
  { de: 'Zeichentrickserien aus den 90ern', en: 'Cartoons from the 90s' },
  { de: 'Reality-Shows', en: 'Reality TV shows' },
  { de: 'Castingshows', en: 'Talent shows' },
  { de: 'Quizshows', en: 'Game shows' },
  { de: 'Fernsehköche', en: 'TV chefs' },
  { de: 'Berühmte Comedians', en: 'Famous comedians' },
  { de: 'Comics und Comicstrips', en: 'Comics and comic strips' },
  { de: 'Mangas', en: 'Manga series' },
  { de: 'Bestseller-Buchreihen', en: 'Bestselling book series' },
  { de: 'Berühmte Autoren', en: 'Famous authors' },
  { de: 'Spielkonsolen', en: 'Game consoles' },
  { de: 'Spielefirmen', en: 'Video game companies' },
  { de: 'Videospielgenres', en: 'Video game genres' },
  { de: 'Handyspiele', en: 'Mobile games' },
  { de: 'Ego-Shooter', en: 'First-person shooters' },
  { de: 'Rennspiele', en: 'Racing games' },
  { de: 'Rollenspiele am Computer oder an der Konsole', en: 'Role-playing video games' },
  { de: 'Horrorspiele', en: 'Horror video games' },
  { de: 'Open-World-Spiele', en: 'Open-world games' },
  { de: 'Kampfspiele', en: 'Fighting games' },
  { de: 'Sportspiele für die Konsole', en: 'Sports video games' },
  { de: 'Spieleklassiker aus der Spielhalle', en: 'Arcade classics' },
  { de: 'Spiele, die man online mit Freunden zockt', en: 'Games you play online with friends' },
  { de: 'Minecraft-Mobs', en: 'Minecraft mobs' },
  { de: 'Spielzeug aus den 90ern', en: 'Toys from the 90s' },
  { de: 'LEGO-Themenwelten', en: 'LEGO themes' },
  { de: 'Promi-Paare', en: 'Celebrity couples' },
  { de: 'Berühmte Duos', en: 'Famous duos' },
  { de: 'Berühmte Geschwister', en: 'Famous siblings' },
  { de: 'Berühmte Models', en: 'Famous models' },
  { de: 'Milliardäre', en: 'Billionaires' },
  { de: 'Mitglieder von Königshäusern', en: 'Members of royal families' },
  { de: 'Promis mit roten Haaren', en: 'Celebrities with red hair' },
  { de: 'Promis mit Glatze', en: 'Bald celebrities' },
  { de: 'Hollywood-Stars über 60', en: 'Hollywood stars over 60' },
  { de: 'Superheldenfilme', en: 'Superhero movies' },
  { de: 'Filme mit Scarlett Johansson', en: 'Scarlett Johansson movies' },
  { de: 'Filme mit Robert De Niro', en: 'Robert De Niro movies' },
  { de: 'Filme mit Meryl Streep', en: 'Meryl Streep movies' },
  { de: 'Filme mit Keanu Reeves', en: 'Keanu Reeves movies' },
  { de: 'Filme mit Adam Sandler', en: 'Adam Sandler movies' },
  { de: 'Filme mit Dwayne Johnson', en: 'Dwayne Johnson movies' },
  { de: 'DreamWorks-Filme', en: 'DreamWorks movies' },
  { de: 'Filme aus den 2000ern', en: 'Movies from the 2000s' },
  { de: 'Kultfilme', en: 'Cult movies' },
  { de: 'Filme, die in New York spielen', en: 'Movies set in New York' },
  { de: 'Katastrophenfilme', en: 'Disaster movies' },
  { de: 'Thriller', en: 'Thrillers' },
  { de: 'Filmbiografien über echte Personen', en: 'Biopics' },
  { de: 'Filme mit Tieren in der Hauptrolle', en: 'Movies starring animals' },
  { de: 'Teenie-Komödien', en: 'Teen comedies' },
  { de: 'Serien von HBO', en: 'HBO shows' },
  { de: 'Serien über Superhelden', en: 'Superhero TV shows' },
  { de: 'Zeichentrickserien für Erwachsene', en: 'Adult animated series' },
  { de: 'Pixar-Figuren', en: 'Pixar characters' },
  { de: 'Figuren aus Shrek', en: 'Shrek characters' },
  { de: 'Figuren aus Spider-Man', en: 'Spider-Man characters' },
  { de: 'Fiktive Firmen aus Filmen und Serien', en: 'Fictional companies from movies and TV' },
  { de: 'Berühmte Raumschiffe aus Filmen und Serien', en: 'Famous spaceships from movies and TV' },
  { de: 'Berühmte Waffen aus Filmen und Spielen', en: 'Famous weapons from movies and games' },
  {
    de: 'Magische Gegenstände aus Filmen und Büchern',
    en: 'Magical objects from movies and books',
  },
  { de: 'Berühmte Filmpaare', en: 'Famous on-screen couples' },
  { de: 'Fiktive Figuren mit Hut', en: 'Fictional characters with hats' },
  { de: 'Fiktive Figuren mit Maske', en: 'Fictional characters with masks' },
  {
    de: 'Grüne Filmfiguren und Zeichentrickfiguren',
    en: 'Green characters from movies and cartoons',
  },
  {
    de: 'Blaue Filmfiguren und Zeichentrickfiguren',
    en: 'Blue characters from movies and cartoons',
  },
  {
    de: 'Berühmte Mäuse und Ratten aus Filmen und Serien',
    en: 'Famous mice and rats from movies and TV',
  },
  { de: 'Berühmte Bären aus Filmen und Serien', en: 'Famous bears from movies and TV' },
  { de: 'Videospiele aus den 90ern', en: 'Video games from the 90s' },
  { de: 'Jump’n’Run-Spiele', en: 'Platform games' },
  { de: 'Strategiespiele', en: 'Strategy games' },
  { de: 'Simulationsspiele', en: 'Simulation games' },
  { de: 'Spielereihen mit vielen Teilen', en: 'Long-running video game series' },
  { de: 'Endgegner aus Videospielen', en: 'Video game bosses' },
  { de: 'Dinge, die man in Minecraft baut', en: 'Things you build in Minecraft' },
  { de: 'PlayStation-Spiele', en: 'PlayStation games' },
  { de: 'Gaming-Zubehör', en: 'Gaming accessories' },
  { de: 'Spielzeugfiguren und Puppen', en: 'Toy figures and dolls' },
  { de: 'Berühmte virale Videos', en: 'Famous viral videos' },
  {
    de: 'Promis mit riesiger Instagram-Fangemeinde',
    en: 'Celebrities with huge Instagram followings',
  },
  { de: 'Dinge, die man auf TikTok sieht', en: 'Things you see on TikTok' },
  { de: 'Arten von YouTube-Videos', en: 'Types of YouTube videos' },
  { de: 'Promis aus den USA', en: 'American celebrities' },
  { de: 'Promis mit Tattoos', en: 'Celebrities with tattoos' },
  { de: 'Berühmte Hollywood-Familien', en: 'Famous Hollywood families' },
  { de: 'Schauspieler, die Bösewichte gespielt haben', en: 'Actors who played villains' },
  { de: 'Britische Schauspieler', en: 'British actors' },
  { de: 'Berühmte Kinderfiguren aus Filmen', en: 'Famous child characters from movies' },
  { de: 'Mütter aus Filmen und Serien', en: 'Famous moms from movies and TV' },
  { de: 'Väter aus Filmen und Serien', en: 'Famous dads from movies and TV' },
  { de: 'Lehrer aus Filmen und Serien', en: 'Teachers from movies and TV' },
  { de: 'Figuren aus Kinderbüchern', en: 'Children’s book characters' },
  { de: 'Bösewichte aus James Bond', en: 'James Bond villains' },
  { de: 'Figuren aus Sitcoms', en: 'Sitcom characters' },
  {
    de: 'Orte aus Der Herr der Ringe und Der Hobbit',
    en: 'Places from The Lord of the Rings and The Hobbit',
  },
  { de: 'Britische Serien', en: 'British TV shows' },
  { de: 'Filme mit einer Zahl im Titel', en: 'Movies with a number in the title' },
  { de: 'Filme mit einem Tier im Titel', en: 'Movies with an animal in the title' },
  { de: 'Filme mit einem Namen im Titel', en: 'Movies with a name in the title' },
  { de: 'Filmtitel mit nur einem Wort', en: 'One-word movie titles' },
];
