import type { HotPotatoSeed } from './types';

export const sexualPrompts: HotPotatoSeed[] = [
  { de: 'Kosenamen für den Partner', en: 'Pet names for a partner' },
  { de: 'Anmachsprüche', en: 'Pickup lines' },
  { de: 'Dinge, die man im Sexshop findet', en: 'Things you find in a sex shop' },
  { de: 'Dating-Apps', en: 'Dating apps' },
  {
    de: 'Dinge, die man beim ersten Date nicht sagen sollte',
    en: 'Things you shouldn’t say on a first date',
  },
  { de: 'Erogene Zonen', en: 'Erogenous zones' },
  { de: 'Sexstellungen', en: 'Sex positions' },
  { de: 'Sexspielzeuge', en: 'Sex toys' },
  { de: 'Orte, an denen man Sex haben kann', en: 'Places where you can have sex' },
  { de: 'Wörter für Brüste', en: 'Words for breasts' },
  { de: 'Umschreibungen für Sex', en: 'Euphemisms for sex' },
  { de: 'Arten von Dessous', en: 'Types of lingerie' },
  { de: 'Dinge in einer Nachttischschublade', en: 'Things in a nightstand drawer' },
  { de: 'Verhütungsmethoden', en: 'Methods of contraception' },
  { de: 'Romantische Filme', en: 'Romantic movies' },
  { de: 'Erotische Filme', en: 'Steamy movies' },
  { de: 'Liebeslieder', en: 'Love songs' },
  { de: 'Songs über Sex', en: 'Songs about sex' },
  { de: 'Sexsymbole aller Zeiten', en: 'Sex symbols of all time' },
  { de: 'Fetische', en: 'Fetishes' },
  { de: 'Rollenspiel-Szenarien', en: 'Role-play scenarios' },
  { de: 'Dinge, die beim Sex schiefgehen können', en: 'Things that can go wrong during sex' },
  { de: 'Ausreden, um ein Date früh zu beenden', en: 'Excuses to end a date early' },
  { de: 'Gründe für eine Trennung', en: 'Reasons for a breakup' },
  { de: 'Red Flags beim Dating', en: 'Dating red flags' },
  { de: 'Green Flags beim Dating', en: 'Dating green flags' },
  { de: 'Fragen für ein erstes Date', en: 'Questions to ask on a first date' },
  { de: 'Aphrodisiaka', en: 'Aphrodisiacs' },
  { de: 'Lebensmittel, die anzüglich aussehen', en: 'Foods that look suggestive' },
  { de: 'Körperstellen, die man küssen kann', en: 'Body parts you can kiss' },
  { de: 'Arten von Küssen', en: 'Types of kisses' },
  { de: 'Dinge, die man beim Flirten macht', en: 'Things people do when flirting' },
  { de: 'Orte, an denen man jemanden kennenlernen kann', en: 'Places to meet someone new' },
  { de: 'Berufe, die als sexy gelten', en: 'Jobs that are considered sexy' },
  { de: 'Dinge, die man nackt macht', en: 'Things you do naked' },
  { de: 'Wörter für Penis', en: 'Words for penis' },
  { de: 'Wörter für Hintern', en: 'Words for butt' },
  { de: 'Kleidungsstücke für Strip-Poker', en: 'Clothing items to lose in strip poker' },
  { de: 'Spiele für Paare', en: 'Games for couples' },
  { de: 'Romantische Reiseziele', en: 'Romantic travel destinations' },
  { de: 'Romantische Gesten', en: 'Romantic gestures' },
  { de: 'Geschenke zum Valentinstag', en: 'Valentine’s Day gifts' },
  { de: 'Peinliche Momente bei einem Date', en: 'Awkward moments on a date' },
  { de: 'Dinge, die man nach dem Sex macht', en: 'Things people do after sex' },
  { de: 'Dinge, die man vor einem Date macht', en: 'Things you do to get ready for a date' },
  { de: 'Berühmte Promi-Paare', en: 'Famous celebrity couples' },
  { de: 'Berühmte Liebespaare aus Filmen und Büchern', en: 'Famous couples from movies and books' },
  { de: 'Arten von Beziehungen', en: 'Types of relationships' },
  { de: 'Lebensmittel fürs Schlafzimmer', en: 'Foods to use in the bedroom' },
  { de: 'Stellen für ein sexy Tattoo', en: 'Sexy places for a tattoo' },
  { de: 'Stellen für ein Piercing', en: 'Places to get a piercing' },
  { de: 'Düfte, die sexy wirken', en: 'Scents that are sexy' },
  { de: 'Zubehör für Fesselspiele', en: 'Bondage accessories' },
  { de: 'Dinge, die man mit verbundenen Augen machen kann', en: 'Things you can do blindfolded' },
  { de: 'Beliebte Safewords', en: 'Popular safewords' },
  { de: 'Serien mit vielen Sexszenen', en: 'TV shows with lots of sex scenes' },
  { de: 'Dating-Shows im Fernsehen', en: 'Dating shows on TV' },
  { de: 'Dinge, die in Dating-Profilen stehen', en: 'Things people write on dating profiles' },
  { de: 'Typische Fotos in Dating-Profilen', en: 'Typical dating profile photos' },
  { de: 'Aktivitäten beim Junggesellenabschied', en: 'Bachelor and bachelorette party activities' },
  { de: 'Dinge, die man im Stripclub sieht', en: 'Things you see in a strip club' },
  { de: 'Sexy Tanzstile', en: 'Sexy dance styles' },
  {
    de: 'Körperteile, die man an anderen attraktiv findet',
    en: 'Body parts people find attractive',
  },
  {
    de: 'Eigenschaften, die einen Partner attraktiv machen',
    en: 'Traits that make a partner attractive',
  },
  { de: 'Dinge, die total abtörnen', en: 'Total turn-offs' },
  { de: 'Dinge, die anmachen', en: 'Turn-ons' },
  { de: 'Arten von Kondomen', en: 'Types of condoms' },
  { de: 'Geschmacksrichtungen für Gleitgel', en: 'Flavors of lube' },
  { de: 'Drinks für ein Date', en: 'Drinks to order on a date' },
  { de: 'Dinge, die ein Date ruinieren', en: 'Things that ruin a date' },
  { de: 'Gründe für Ghosting', en: 'Reasons people ghost someone' },
  { de: 'Ausreden, um keinen Sex zu haben', en: 'Excuses to avoid sex' },
  { de: 'Sexy Kleidungsstücke', en: 'Sexy clothing items' },
  { de: 'Sexy Schuhe', en: 'Sexy shoes' },
  { de: 'Aktivitäten am Valentinstag', en: 'Valentine’s Day activities' },
  { de: 'Dinge, die man im Bett trägt', en: 'Things people wear to bed' },
  { de: 'Arten von Massagen', en: 'Types of massages' },
  { de: 'Dinge, die man bei Kerzenschein macht', en: 'Things to do by candlelight' },
  { de: 'Romantische oder erotische Bücher', en: 'Romantic or erotic books' },
  { de: 'Disney-Paare', en: 'Disney couples' },
  { de: 'Dinge, die man auf einer Hochzeit sieht', en: 'Things you see at a wedding' },
  { de: 'Orte für einen Heiratsantrag', en: 'Places to propose' },
  { de: 'Dinge, die Paare gemeinsam machen', en: 'Things couples do together' },
  { de: 'Dinge, über die Paare streiten', en: 'Things couples fight about' },
  { de: 'Dinge, die man nach einer Trennung macht', en: 'Things people do after a breakup' },
  { de: 'Umschreibungen für Selbstbefriedigung', en: 'Euphemisms for masturbation' },
  { de: 'Musikvideos, die sexy sind', en: 'Sexy music videos' },
  { de: 'Dinge, die vibrieren', en: 'Things that vibrate' },
  { de: 'Dinge, die man lecken kann', en: 'Things you can lick' },
  { de: 'Dinge, die hart werden', en: 'Things that get hard' },
  { de: 'Dinge, die nass werden', en: 'Things that get wet' },
  { de: 'Dinge, die lang und dick sind', en: 'Things that are long and thick' },
  { de: 'Dinge, die man blasen kann', en: 'Things you can blow' },
  { de: 'Dinge, die man reiten kann', en: 'Things you can ride' },
  { de: 'Dinge, die man streicheln kann', en: 'Things you can stroke' },
  { de: 'Dinge, die man auspacken kann', en: 'Things you can unwrap' },
  { de: 'Dinge, die man schlucken kann', en: 'Things you can swallow' },
  { de: 'Dinge, die man in den Mund nimmt', en: 'Things you put in your mouth' },
  { de: 'Dinge, die tropfen', en: 'Things that drip' },
  { de: 'Dinge, die man aufpumpen kann', en: 'Things you can pump up' },
  { de: 'Dinge, die man schütteln kann', en: 'Things you can shake' },
  { de: 'Dinge, die man irgendwo reinstecken kann', en: 'Things you can stick in somewhere' },
  { de: 'Dinge, die man im Dunkeln macht', en: 'Things you do in the dark' },
  { de: 'Dinge, die man heimlich macht', en: 'Things people do in secret' },
  { de: 'Dinge, die man unter der Dusche macht', en: 'Things you do in the shower' },
  { de: 'Dinge, die man im Auto machen kann', en: 'Things you can do in a car' },
  { de: 'Orte, an denen man erwischt werden kann', en: 'Places where you can get caught' },
  {
    de: 'Dinge, die man nach einem One-Night-Stand sucht',
    en: 'Things you look for after a one-night stand',
  },
  { de: 'Sexy Akzente', en: 'Sexy accents' },
  { de: 'Sportarten, bei denen man viel Haut sieht', en: 'Sports where you see a lot of skin' },
  { de: 'Outfits für ein erstes Date', en: 'Outfits for a first date' },
  { de: 'Dinge, die man zu einem Date mitnimmt', en: 'Things you bring on a date' },
  { de: 'Lügen beim Dating', en: 'Lies people tell when dating' },
  { de: 'Komplimente', en: 'Compliments' },
  { de: 'Dinge, die man jemandem ins Ohr flüstert', en: 'Things you whisper in someone’s ear' },
  { de: 'Gründe für Eifersucht', en: 'Reasons for jealousy' },
  { de: 'Partyspiele mit Knutschfaktor', en: 'Party games that involve kissing' },
  { de: 'Aufgaben bei Wahrheit oder Pflicht', en: 'Dares for truth or dare' },
  { de: 'Sexy Halloween-Kostüme', en: 'Sexy Halloween costumes' },
  { de: 'Dinge, die man am FKK-Strand sieht', en: 'Things you see at a nudist beach' },
  { de: 'Gründe, warum jemand Single ist', en: 'Reasons someone is single' },
  { de: 'Date-Ideen für zu Hause', en: 'Date ideas at home' },
  {
    de: 'Berühmte Verführer aus Film und Literatur',
    en: 'Famous seducers from film and literature',
  },
  { de: 'Sexuelle Orientierungen', en: 'Sexual orientations' },
  { de: 'Kitzlige Körperstellen', en: 'Ticklish body parts' },
  { de: 'Dinge, die man im Hotelzimmer macht', en: 'Things you do in a hotel room' },
  { de: 'Dinge, die man beim Sex nie sagen sollte', en: 'Things you should never say during sex' },
  { de: 'Dinge, die Paare teilen', en: 'Things couples share' },
  { de: 'Ausreden fürs Zuspätkommen zum Date', en: 'Excuses for being late to a date' },
  { de: 'Arten, Schluss zu machen', en: 'Ways to break up with someone' },
  { de: 'Sexy Zeichentrickfiguren', en: 'Sexy cartoon characters' },
  { de: 'Sexy Videospielfiguren', en: 'Sexy video game characters' },
  { de: 'Superhelden, die heiß sind', en: 'Hot superheroes' },
  { de: 'Bösewichte, die heiß sind', en: 'Hot villains' },
  { de: 'Dinge, die Gänsehaut machen', en: 'Things that give you goosebumps' },
  { de: 'Anzeichen, dass man verliebt ist', en: 'Signs you’re in love' },
  { de: 'Dinge, die die Eltern nicht finden sollten', en: 'Things your parents shouldn’t find' },
  {
    de: 'Dinge, nach denen man googelt und dann den Verlauf löscht',
    en: 'Things you google and then clear your history',
  },
  { de: 'Fehler beim Küssen', en: 'Kissing mistakes' },
  { de: 'Dinge, die Paare auf Instagram posten', en: 'Things couples post on Instagram' },
  { de: 'Dinge, die man mit Eiswürfeln machen kann', en: 'Things you can do with ice cubes' },
  { de: 'Möbel, auf denen man Sex haben kann', en: 'Furniture you can have sex on' },
  { de: 'Typen, die man auf Dating-Apps trifft', en: 'Types of people on dating apps' },
  { de: 'Dinge, die man vor dem Sex macht', en: 'Things people do before sex' },
  { de: 'Promis über 50, die heiß sind', en: 'Hot celebrities over 50' },
  { de: 'Sportler, die heiß sind', en: 'Hot athletes' },
  { de: 'Musiker, die heiß sind', en: 'Hot musicians' },
  { de: 'Gründe fürs Fremdgehen', en: 'Reasons people cheat' },
  { de: 'Anzeichen, dass jemand fremdgeht', en: 'Signs someone is cheating' },
  { de: 'Ausreden von Fremdgehern', en: 'Excuses cheaters use' },
  { de: 'Pikante Sätze für Ich hab noch nie', en: 'Spicy statements for never have I ever' },
  { de: 'Pikante Fragen für Wahrheit oder Pflicht', en: 'Spicy questions for truth or dare' },
  { de: 'Gründe, nach links zu wischen', en: 'Reasons to swipe left' },
  { de: 'Gründe, nach rechts zu wischen', en: 'Reasons to swipe right' },
  { de: 'Dinge für ein romantisches Wochenende', en: 'Things to pack for a romantic weekend' },
  { de: 'Dinge für ein Picknick-Date', en: 'Things for a picnic date' },
  { de: 'Hobbys, die sexy sind', en: 'Hobbies that are sexy' },
  { de: 'Musikinstrumente, die sexy wirken', en: 'Instruments that look sexy to play' },
  { de: 'Dinge, die man in der Sauna sieht', en: 'Things you see in a sauna' },
  { de: 'Dinge, die zu schnell vorbei sind', en: 'Things that are over too quickly' },
  { de: 'Dinge, die Ausdauer brauchen', en: 'Things that take stamina' },
  { de: 'Dinge, die man am Morgen danach bereut', en: 'Things you regret the morning after' },
  { de: 'Dinge, die man betrunken schreibt', en: 'Things you text when drunk' },
  { de: 'Dinge, die man aufknöpfen oder aufmachen kann', en: 'Things you can unbutton or unzip' },
  { de: 'Dinge, die man mit der Zunge macht', en: 'Things you do with your tongue' },
  { de: 'Dinge, die zu groß sein können', en: 'Things that can be too big' },
  { de: 'Dinge, die zu klein sein können', en: 'Things that can be too small' },
  { de: 'Dinge, die man einölen kann', en: 'Things you can oil up' },
  { de: 'Dinge, die heiß sind', en: 'Things that are hot' },
  { de: 'Dinge, an denen man sich festhalten kann', en: 'Things you can hold on to' },
  { de: 'Dinge, an denen man knabbern kann', en: 'Things you can nibble on' },
  { de: 'Dinge, die man im Liegen macht', en: 'Things you do lying down' },
  { de: 'Dinge, die man auf den Knien macht', en: 'Things you do on your knees' },
  { de: 'Dinge, die man nur zu zweit machen kann', en: 'Things you can only do as a pair' },
  { de: 'Dinge, die quietschen', en: 'Things that squeak' },
  { de: 'Dinge, die spritzen', en: 'Things that squirt' },
  { de: 'Dinge mit Happy End', en: 'Things with a happy ending' },
  { de: 'Anzeichen, dass ein Date gut läuft', en: 'Signs a date is going well' },
  {
    de: 'Dinge, die man nicht auf dem Handy des Partners finden will',
    en: 'Things you don’t want to find on your partner’s phone',
  },
  { de: 'Meilensteine in einer Beziehung', en: 'Relationship milestones' },
  {
    de: 'Dinge, die Paare nach Jahren nicht mehr machen',
    en: 'Things couples stop doing after years',
  },
  { de: 'Fehler beim Kennenlernen der Schwiegereltern', en: 'Mistakes when meeting the in-laws' },
  {
    de: 'Dinge, die man im Bett macht, außer zu schlafen',
    en: 'Things you do in bed besides sleeping',
  },
  { de: 'Berühmte Affären', en: 'Famous affairs' },
  { de: 'Körperstellen, die man rasieren kann', en: 'Body parts you can shave' },
  { de: 'Muskeln, die sexy aussehen', en: 'Muscles that look sexy' },
  { de: 'Frisuren, die sexy sind', en: 'Hairstyles that are sexy' },
  { de: 'Gründe, nackt zu sein', en: 'Reasons to be naked' },
  { de: 'Dinge, die man nackt nicht machen sollte', en: 'Things you shouldn’t do naked' },
  { de: 'Orte zum Nacktbaden', en: 'Places to go skinny-dipping' },
  { de: 'Sexy Uniformen', en: 'Sexy uniforms' },
  { de: 'Dinge, die man auf einer Hochzeitsreise macht', en: 'Things you do on a honeymoon' },
  { de: 'Dinge, die man beim Kuscheln macht', en: 'Things you do while cuddling' },
  { de: 'Dinge, die man im Club zum Flirten macht', en: 'Things you do to flirt in a club' },
  { de: 'Dinge, die man mit Schlagsahne machen kann', en: 'Things you can do with whipped cream' },
  { de: 'Dinge, die man beim Sexting schickt', en: 'Things people send when sexting' },
  { de: 'Ausreden für Knutschflecken', en: 'Excuses for a hickey' },
  { de: 'Ideen für ein Jahrestag-Date', en: 'Anniversary date ideas' },
  { de: 'Dinge, die man einem Ex nie sagen sollte', en: 'Things you should never tell an ex' },
  { de: 'Gründe, zum Ex zurückzugehen', en: 'Reasons people go back to an ex' },
];
