import type { HotPotatoSeed } from './types';

export const sportsPrompts: HotPotatoSeed[] = [
  { de: 'Bundesliga-Vereine', en: 'Bundesliga clubs' },
  { de: 'Fußballvereine aus England', en: 'English football clubs' },
  { de: 'Fußballvereine aus Spanien', en: 'Spanish football clubs' },
  { de: 'Fußballvereine aus Italien', en: 'Italian football clubs' },
  { de: 'Fußballvereine aus Frankreich', en: 'French football clubs' },
  { de: 'Fußballvereine aus den Niederlanden', en: 'Dutch football clubs' },
  { de: 'Fußballvereine aus Südamerika', en: 'South American football clubs' },
  { de: 'Vereine aus der Champions League', en: 'Champions League clubs' },
  { de: 'Fußball-Nationalmannschaften', en: 'National football teams' },
  { de: 'Fußballstadien', en: 'Football stadiums' },
  { de: 'Bekannte Derbys im Fußball', en: 'Famous football derbies' },
  { de: 'Aktuelle Fußballstars', en: 'Current football stars' },
  { de: 'Fußballlegenden', en: 'Football legends' },
  { de: 'Fußballspielerinnen', en: 'Female footballers' },
  { de: 'Fußballtrainer', en: 'Football managers' },
  { de: 'Fußballer, die später Trainer wurden', en: 'Footballers who became managers' },
  { de: 'Torhüter', en: 'Goalkeepers' },
  { de: 'Stürmer', en: 'Strikers' },
  { de: 'Deutsche Nationalspieler', en: 'German national team players' },
  { de: 'Deutsche Weltmeister von 2014', en: 'Germany’s 2014 World Cup winners' },
  { de: 'Ballon-d’Or-Gewinner', en: 'Ballon d’Or winners' },
  { de: 'Spieler des FC Bayern München', en: 'FC Bayern Munich players' },
  { de: 'Spieler von Borussia Dortmund', en: 'Borussia Dortmund players' },
  { de: 'Spieler von Bayer Leverkusen', en: 'Bayer Leverkusen players' },
  { de: 'Spieler des FC Schalke 04', en: 'Schalke 04 players' },
  { de: 'Spieler von Real Madrid', en: 'Real Madrid players' },
  { de: 'Spieler des FC Barcelona', en: 'FC Barcelona players' },
  { de: 'Spieler von Manchester United', en: 'Manchester United players' },
  { de: 'Spieler des FC Liverpool', en: 'Liverpool FC players' },
  { de: 'Spieler von Manchester City', en: 'Manchester City players' },
  { de: 'Spieler des FC Chelsea', en: 'Chelsea players' },
  { de: 'Spieler des FC Arsenal', en: 'Arsenal players' },
  { de: 'Spieler von Paris Saint-Germain', en: 'Paris Saint-Germain players' },
  { de: 'Spieler von Juventus Turin', en: 'Juventus players' },
  { de: 'Spieler des AC Mailand', en: 'AC Milan players' },
  { de: 'Spieler von Inter Mailand', en: 'Inter Milan players' },
  { de: 'Spieler aus der Premier League', en: 'Premier League players' },
  { de: 'Spieler aus der Bundesliga', en: 'Bundesliga players' },
  { de: 'Brasilianische Fußballer', en: 'Brazilian footballers' },
  { de: 'Französische Fußballer', en: 'French footballers' },
  { de: 'Englische Fußballer', en: 'English footballers' },
  { de: 'Argentinische Fußballer', en: 'Argentine footballers' },
  { de: 'Spanische Fußballer', en: 'Spanish footballers' },
  { de: 'Italienische Fußballer', en: 'Italian footballers' },
  { de: 'Portugiesische Fußballer', en: 'Portuguese footballers' },
  { de: 'Niederländische Fußballer', en: 'Dutch footballers' },
  { de: 'Belgische Fußballer', en: 'Belgian footballers' },
  { de: 'Afrikanische Fußballer', en: 'African footballers' },
  { de: 'Fußballer mit der Rückennummer 10', en: 'Footballers who wore the number 10' },
  {
    de: 'Fußballer, die unter nur einem Namen bekannt sind',
    en: 'Footballers known by a single name',
  },
  { de: 'Fußballturniere', en: 'Football tournaments' },
  {
    de: 'Länder, die eine Fußball-WM ausgerichtet haben',
    en: 'Countries that have hosted a World Cup',
  },
  { de: 'Begriffe aus dem Fußball', en: 'Football terms' },
  { de: 'Dinge auf einem Fußballplatz', en: 'Things on a football pitch' },
  { de: 'Dinge, die man im Stadion sieht', en: 'Things you see in a stadium' },
  { de: 'Dinge, die Fans ins Stadion mitbringen', en: 'Things fans bring to the stadium' },
  { de: 'Gründe für eine Spielunterbrechung', en: 'Reasons a match gets stopped' },
  { de: 'Gründe für eine Gelbe Karte', en: 'Reasons for a yellow card' },
  { de: 'Dinge, die ein Schiedsrichter tut', en: 'Things a referee does' },
  {
    de: 'Dinge, die ein Trainer an der Seitenlinie macht',
    en: 'Things a coach does on the sideline',
  },
  { de: 'Arten von Torjubel', en: 'Goal celebrations' },
  { de: 'Snacks beim Fußballschauen', en: 'Snacks for watching football' },
  {
    de: 'Dinge, die man beim Fußballschauen macht',
    en: 'Things people do while watching football',
  },
  { de: 'Dinge, die Sportler in Interviews sagen', en: 'Things athletes say in interviews' },
  { de: 'Dinge, die nach einem Sieg passieren', en: 'Things that happen after a win' },
  { de: 'Ausreden nach einer Niederlage', en: 'Excuses after losing a match' },
  { de: 'Trikotsponsoren', en: 'Shirt sponsors' },
  { de: 'Sportartikelmarken', en: 'Sportswear brands' },
  { de: 'Pokale und Trophäen', en: 'Trophies and cups' },
  { de: 'Positionen in verschiedenen Sportarten', en: 'Positions across different sports' },
  { de: 'Rennsportarten', en: 'Racing sports' },
  { de: 'Sportarten, die man im Park sieht', en: 'Sports you see in the park' },
  { de: 'Neuere olympische Sportarten', en: 'Newer Olympic sports' },
  { de: 'Sportarten, die nicht olympisch sind', en: 'Sports that aren’t in the Olympics' },
  { de: 'Mannschaftssportarten', en: 'Team sports' },
  { de: 'Einzelsportarten', en: 'Individual sports' },
  { de: 'Sportarten, die man zu zweit macht', en: 'Sports for two people' },
  { de: 'Dinge, die Sportler tragen', en: 'Things athletes wear' },
  { de: 'Spitznamen berühmter Sportler', en: 'Nicknames of famous athletes' },
  { de: 'Sportarten, bei denen man Punkte zählt', en: 'Sports where you score points' },
  {
    de: 'Schläge, Tritte und Griffe im Kampfsport',
    en: 'Strikes, kicks and holds in martial arts',
  },
  { de: 'Leichtathletik-Disziplinen', en: 'Track and field events' },
  { de: 'Disziplinen im Skisport', en: 'Skiing disciplines' },
  { de: 'Disziplinen im Radsport', en: 'Cycling disciplines' },
  { de: 'Extremsportarten', en: 'Extreme sports' },
  { de: 'Sportarten mit Schläger', en: 'Sports played with a racket, bat or stick' },
  { de: 'Sportarten ohne Ball', en: 'Sports without a ball' },
  { de: 'Sportarten mit Netz', en: 'Sports with a net' },
  { de: 'Sportarten mit Toren', en: 'Sports with goals' },
  { de: 'Sportarten mit Motoren', en: 'Motorsports' },
  { de: 'Sportarten mit Tieren', en: 'Sports involving animals' },
  { de: 'Sportarten mit Helm', en: 'Sports where you wear a helmet' },
  { de: 'Sportarten mit Handschuhen', en: 'Sports where you wear gloves' },
  { de: 'Sportarten mit Brett', en: 'Board sports' },
  { de: 'Sportarten auf Rädern', en: 'Sports on wheels' },
  { de: 'Sportarten mit Waffen', en: 'Sports with weapons' },
  { de: 'Sportarten in den Bergen', en: 'Mountain sports' },
  { de: 'Sportarten in der Luft', en: 'Air sports' },
  { de: 'Sportarten am Strand', en: 'Beach sports' },
  { de: 'Hallensportarten', en: 'Indoor sports' },
  { de: 'Sportarten, bei denen man springt', en: 'Sports that involve jumping' },
  { de: 'Sportarten, bei denen man wirft', en: 'Sports that involve throwing' },
  { de: 'Dinge, die man im Sport wirft', en: 'Things you throw in sports' },
  { de: 'Sportarten, bei denen man viel rennt', en: 'Sports where you run a lot' },
  { de: 'Sportarten, bei denen man sitzt', en: 'Sports you do sitting down' },
  { de: 'Sportarten, bei denen die Zeit gestoppt wird', en: 'Sports where the clock decides' },
  { de: 'Sportarten, bei denen eine Jury bewertet', en: 'Sports judged by a panel' },
  { de: 'Sportarten aus Asien', en: 'Sports from Asia' },
  { de: 'Sportarten aus Großbritannien', en: 'Sports invented in Britain' },
  { de: 'Sportarten, die in den USA beliebt sind', en: 'Sports popular in the US' },
  { de: 'Nationalsportarten verschiedener Länder', en: 'National sports of different countries' },
  { de: 'Sportarten, in denen Deutschland stark ist', en: 'Sports Germany is good at' },
  { de: 'Sportarten, die man im Fernsehen schaut', en: 'Sports people watch on TV' },
  { de: 'Sportarten für Kinder', en: 'Sports for kids' },
  {
    de: 'Sportarten, die man bis ins hohe Alter machen kann',
    en: 'Sports you can do into old age',
  },
  { de: 'Sportarten, die man im Urlaub ausprobiert', en: 'Sports people try on holiday' },
  { de: 'Sportarten, die du nie ausprobieren würdest', en: 'Sports you would never try' },
  { de: 'Sportarten, die keiner ernst nimmt', en: 'Sports nobody takes seriously' },
  { de: 'Hobbys, die als Sport gelten', en: 'Hobbies that count as a sport' },
  { de: 'Spiele für den Garten', en: 'Games for the garden' },
  { de: 'Kneipensportarten', en: 'Pub and bar games' },
  {
    de: 'Länder, die bei Olympia viele Medaillen holen',
    en: 'Countries that win lots of Olympic medals',
  },
  { de: 'Turnübungen', en: 'Gymnastics moves' },
  { de: 'Yoga-Übungen', en: 'Yoga poses' },
  { de: 'Fitnesskurse', en: 'Fitness classes' },
  { de: 'Begriffe aus dem Schwimmen', en: 'Swimming terms' },
  { de: 'Fitnessgeräte', en: 'Gym equipment' },
  { de: 'Begriffe aus dem Fitnessstudio', en: 'Gym slang' },
  { de: 'Typen von Leuten im Fitnessstudio', en: 'Types of people at the gym' },
  { de: 'Gründe, ins Fitnessstudio zu gehen', en: 'Reasons to go to the gym' },
  { de: 'Ausreden, um keinen Sport zu machen', en: 'Excuses not to work out' },
  { de: 'Dinge, die beim Sport nerven', en: 'Annoying things about doing sports' },
  { de: 'Dinge, die man nach dem Sport macht', en: 'Things you do after a workout' },
  { de: 'Dinge, die Sportler essen oder trinken', en: 'Things athletes eat or drink' },
  { de: 'Muskeln im Körper', en: 'Muscles in the body' },
  { de: 'Sportverletzungen', en: 'Sports injuries' },
  { de: 'Sportgeräte', en: 'Sports equipment' },
  { de: 'Arten von Bällen', en: 'Types of balls' },
  { de: 'Dinge in einer Sporttasche', en: 'Things in a sports bag' },
  { de: 'Dinge in einer Umkleidekabine', en: 'Things in a locker room' },
  { de: 'Dinge in einer Turnhalle', en: 'Things in a sports hall' },
  { de: 'Dinge aus dem Sportunterricht', en: 'Things from PE class' },
  { de: 'Dinge, die man beim Joggen dabeihat', en: 'Things you take on a run' },
  { de: 'Dinge, die man zum Skifahren braucht', en: 'Things you need for skiing' },
  { de: 'Dinge auf einer Skipiste', en: 'Things on a ski slope' },
  { de: 'Wintersportorte', en: 'Ski resorts' },
  { de: 'Dinge, die man beim Wandern dabeihat', en: 'Things you take hiking' },
  { de: 'Dinge, die man ins Schwimmbad mitnimmt', en: 'Things you take to the pool' },
  { de: 'Dinge, die man im Schwimmbad sieht', en: 'Things you see at the swimming pool' },
  { de: 'Dinge auf einem Golfplatz', en: 'Things on a golf course' },
  { de: 'Dinge auf einem Tennisplatz', en: 'Things on a tennis court' },
  { de: 'Dinge an einer Rennstrecke', en: 'Things at a race track' },
  { de: 'Dinge, die man bei Olympia sieht', en: 'Things you see at the Olympics' },
  { de: 'Fahrradteile', en: 'Bike parts' },
  { de: 'Skateboard-Tricks', en: 'Skateboard tricks' },
  { de: 'Begriffe aus dem Tennis', en: 'Tennis terms' },
  { de: 'Begriffe aus dem Basketball', en: 'Basketball terms' },
  { de: 'Begriffe aus dem Golf', en: 'Golf terms' },
  { de: 'Begriffe aus dem Boxen', en: 'Boxing terms' },
  { de: 'Begriffe aus dem Schach', en: 'Chess terms' },
  { de: 'Begriffe aus dem American Football', en: 'American football terms' },
  { de: 'Begriffe aus dem Baseball', en: 'Baseball terms' },
  { de: 'Begriffe aus dem Eishockey', en: 'Ice hockey terms' },
  { de: 'Begriffe aus dem Volleyball', en: 'Volleyball terms' },
  { de: 'Begriffe aus der Formel 1', en: 'Formula 1 terms' },
  { de: 'Begriffe aus dem Radsport', en: 'Cycling terms' },
  { de: 'Begriffe aus dem Wintersport', en: 'Winter sports terms' },
  { de: 'Tennisspieler', en: 'Male tennis players' },
  { de: 'Tennisspielerinnen', en: 'Female tennis players' },
  { de: 'Tennisturniere', en: 'Tennis tournaments' },
  { de: 'Formel-1-Fahrer', en: 'Formula 1 drivers' },
  { de: 'Formel-1-Teams', en: 'Formula 1 teams' },
  { de: 'Formel-1-Rennstrecken', en: 'Formula 1 circuits' },
  { de: 'Rennen und Rennserien im Motorsport', en: 'Motorsport races and series' },
  { de: 'Basketballspieler', en: 'Basketball players' },
  { de: 'NBA-Teams', en: 'NBA teams' },
  { de: 'NFL-Teams', en: 'NFL teams' },
  { de: 'NHL-Teams', en: 'NHL teams' },
  { de: 'MLB-Teams', en: 'MLB teams' },
  { de: 'American-Football-Spieler', en: 'American football players' },
  { de: 'Eishockeyspieler', en: 'Ice hockey players' },
  { de: 'Boxer', en: 'Boxers' },
  { de: 'Wrestler', en: 'Pro wrestlers' },
  { de: 'Golfspieler', en: 'Golfers' },
  { de: 'Berühmte Schwimmer', en: 'Famous swimmers' },
  { de: 'Leichtathleten', en: 'Track and field athletes' },
  { de: 'Wintersportler', en: 'Winter sports athletes' },
  { de: 'Weltrekordhalter im Sport', en: 'Sports world record holders' },
  { de: 'Deutsche Sportler', en: 'German athletes' },
  { de: 'Österreichische Sportler', en: 'Austrian athletes' },
  { de: 'Schweizer Sportler', en: 'Swiss athletes' },
  { de: 'Amerikanische Sportler', en: 'American athletes' },
  { de: 'Berühmte Sportlerinnen', en: 'Famous female athletes' },
  { de: 'Olympiasieger', en: 'Olympic champions' },
  { de: 'Olympische Austragungsorte', en: 'Olympic host cities' },
  { de: 'Große Sportereignisse', en: 'Major sporting events' },
  { de: 'Städte mit einem bekannten Marathon', en: 'Cities with a famous marathon' },
  { de: 'E-Sport-Spiele', en: 'Esports games' },
  { de: 'Sportvideospiele', en: 'Sports video games' },
  { de: 'Dinge, die man bei einem Marathon sieht', en: 'Things you see at a marathon' },
];
