export const chaosTasks: string[] = [
  '{{player}} ist für die nächsten 5 Aufgaben der Fragenmeister: Wer eine Frage dieser Person beantwortet, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 6 Aufgaben der Daumenmeister: Legt diese Person den Daumen auf den Tisch, müssen alle folgen und der Letzte trinkt 2 Schlucke.',
  '{{player}} und {{player}} sind für die nächsten 5 Aufgaben Trinkbuddys: Trinkt einer, trinkt der andere mit.',
  '{{player}} ist für die nächsten 4 Aufgaben der Butler und muss allen nachschenken. Wer sich selbst nachschenkt, trinkt 2 Schlucke.',
  '{{player}} ist für die nächsten 5 Aufgaben das Spiegelbild von {{player}} und macht jede Bewegung nach. Vergisst das Spiegelbild eine Bewegung, trinkt es 1 Schluck.',
  '{{player}} ist für die nächsten 6 Aufgaben der Gesetzgeber und darf eine neue Regel festlegen. Wer sie bricht, trinkt 2 Schlucke.',
  '{{player}} ist für die nächsten 5 Aufgaben der Nasenmeister: Fasst diese Person an die Nase, müssen alle nachziehen und der Letzte trinkt 2 Schlucke.',
  '{{player}} ist für die nächsten 4 Aufgaben der Schiedsrichter und entscheidet bei jedem Streit, wer 2 Schlucke trinkt.',
  '{{player}} ist für die nächsten 5 Aufgaben der Hofnarr: Wer über einen Witz dieser Person nicht lacht, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Zeuge und muss jede neue Aufgabe laut wiederholen. Jede vergessene Wiederholung kostet 2 Schlucke.',
  '{{player}} ist für die nächsten 3 Aufgaben der Vorkoster: Bevor jemand anderes trinkt, nimmt diese Person zuerst 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Glückspilz: Muss diese Person trinken, darf sie 1 Schluck davon an jemanden verschenken.',
  '{{player}} ist für die nächsten 4 Aufgaben der Bodyguard von {{player}} und übernimmt alle Schlucke, die der Schützling trinken müsste.',
  '{{player}} ist für die nächsten 5 Aufgaben der Stimmungsmacher: Nach jeder Aufgabe ruft diese Person "Prost!" und alle trinken 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Nachrichtensprecher und muss jede neue Aufgabe wie in den Abendnachrichten vorlesen. Wer dabei lacht, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 6 Aufgaben der Wortwächter und bestimmt ein verbotenes Wort. Wer es sagt, trinkt 2 Schlucke.',
  '{{player}} ist für die nächsten 5 Aufgaben der Zeremonienmeister und muss jeden Schluck am Tisch mit "Zum Wohl!" ankündigen. Jede verpasste Ansage kostet 1 Schluck.',
  '{{player}} ist für die nächsten 4 Aufgaben ein Geheimagent und darf nur flüstern. Spricht diese Person laut, trinkt sie 2 Schlucke.',
  '{{player}} ist für die nächsten 5 Aufgaben ein Roboter und spricht nur in Robotersprache. Jeder Ausrutscher kostet 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Dirigent: Hebt diese Person die Hand, summen alle, bis sie sie wieder senkt. Wer nicht mitsummt, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 6 Aufgaben Bürgermeister: Wer diese Person nicht mit "Frau Bürgermeisterin" oder "Herr Bürgermeister" anspricht, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Fotograf: Ruft diese Person "Foto!", müssen alle posieren und wer zuletzt erstarrt, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Kellner und muss jede Bitte am Tisch mit einer Verbeugung annehmen. Ohne Verbeugung trinkt diese Person 1 Schluck.',
  '{{player}} ist für die nächsten 4 Aufgaben der Lügendetektor: Nach jeder Antwort am Tisch darf diese Person "Lüge!" rufen und der Beschuldigte trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Glöckner: Klopft diese Person zweimal auf den Tisch, trinken alle 1 Schluck. Das geht höchstens dreimal.',
  '{{player}} ist für die nächsten 5 Aufgaben Sportkommentator und kommentiert jeden Schluck am Tisch. Bleibt ein Schluck unkommentiert, trinkt der Kommentator selbst 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben ein Pirat und muss jeden Satz mit "Arrr" beenden. Jeder vergessene Piratenruf kostet 1 Schluck.',
  '{{player}} ist für die nächsten 6 Aufgaben Hüter der Gläser: Niemand darf sein Glas abstellen, ohne diese Person anzusehen. Wer es vergisst, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Erzähler und fasst nach jeder Aufgabe in einem Satz zusammen, was passiert ist, wie in einer Doku. Jede vergessene Zusammenfassung kostet 1 Schluck.',
  '{{player}} ist für die nächsten 4 Aufgaben Pantomime und darf nur mit Gesten antworten. Jedes gesprochene Wort kostet 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Wetterfrosch und muss vor jedem eigenen Schluck das Wetter von morgen ansagen. Ohne Wetterbericht trinkt diese Person doppelt.',
  '{{player}} ist für die nächsten 5 Aufgaben der Trinkspruchmeister und muss vor jedem eigenen Schluck einen neuen Trinkspruch sagen. Eine Wiederholung kostet 2 Schlucke.',
  '{{player}} ist für die nächsten 5 Aufgaben Höflichkeitsbeauftragter: Wer ohne "bitte" etwas verlangt und dabei erwischt wird, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 6 Aufgaben der Sheriff: Ruft diese Person "Hände hoch!", heben alle die Hände und der Letzte trinkt 2 Schlucke.',
  '{{player}} ist für die nächsten 5 Aufgaben der Lehrer: Wer sprechen will, muss sich melden. Wer einfach reinredet, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Zauberer und darf einmal pro Aufgabe einen Schluck wegzaubern. Der linke Nachbar trinkt ihn stattdessen.',
  '{{player}} ist für die nächsten 4 Aufgaben der DJ und summt nach jeder Aufgabe ein Lied an. Wer es nicht errät, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Papagei von {{player}} und wiederholt jeden Satz des Gegenübers. Für jeden verpassten Satz trinkt der Papagei 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben unsichtbar: Wer mit dieser Person redet oder sie ansieht, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Chef und darf zweimal "Überstunden!" rufen. Dann trinken alle anderen 2 Schlucke.',
  '{{player}} ist für die nächsten 5 Aufgaben der Zahlenwächter: Wer eine Zahl laut ausspricht, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 4 Aufgaben Bademeister: Pfeift diese Person, müssen alle mit den Armen Schwimmbewegungen machen. Der Letzte trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben Opernstar und darf nur singend sprechen. Jeder normal gesprochene Satz kostet 1 Schluck.',
  '{{player}} ist für die nächsten 6 Aufgaben die Majestät am Tisch: Wer trinkt, ohne vorher "Zum Wohl, Majestät" zu sagen, trinkt 1 Schluck extra.',
  '{{player}} darf für die nächsten 5 Aufgaben nur in Fragen sprechen. Jeder Satz ohne Fragezeichen am Ende kostet 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Detektiv und darf einmal jemanden beschuldigen, heimlich nicht getrunken zu haben. Stimmt es, trinkt der Beschuldigte 3 Schlucke, sonst trinkt der Detektiv 2.',
  '{{player}} ist für die nächsten 4 Aufgaben der Hausmeister: Wer etwas auf dem Tisch verschüttet, trinkt 2 Schlucke und muss sich bei dieser Person entschuldigen.',
  '{{player}} ist für die nächsten 5 Aufgaben der Glücksbringer: Wer diese Person vor dem Trinken antippt, muss nur die Hälfte trinken.',
  '{{player}} ist für die nächsten 6 Aufgaben der Steuereintreiber: Jedes Mal, wenn jemand 2 oder mehr Schlucke verteilt, darf diese Person 1 zusätzlichen Schluck verteilen.',
  '{{player}} ist für die nächsten 5 Aufgaben der Übersetzer von {{player}}: Die zweite Person spricht nur Fantasiesprache und der Übersetzer muss alles übersetzen. Wer aufgibt, trinkt 2 Schlucke.',
  '{{player}} ist für die nächsten 5 Aufgaben der Schutzengel und darf einmal einen Schluck von jemandem übernehmen. Wer gerettet wird, bedankt sich laut oder trinkt doppelt.',
  '{{player}} ist für die nächsten 4 Aufgaben der Wächter der Stille: Ruft diese Person "Psst!", herrschen 10 Sekunden Stille. Wer spricht, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Applausmeister: Klatscht diese Person, klatschen alle mit. Wer als Letzter einsteigt, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben Ehrengast: Wer trinkt, muss vorher mit dieser Person anstoßen. Wer es vergisst, trinkt 1 Schluck extra.',
  '{{player}} ist für die nächsten 5 Aufgaben Synchronsprecher von {{player}}: Die zweite Person bewegt nur die Lippen, die erste spricht. Wer aus der Rolle fällt, trinkt 2 Schlucke.',
  '{{player}} ist für die nächsten 5 Aufgaben die Komplimentpolizei: Wer trinkt, muss vorher jemandem ein Kompliment machen. Wer es vergisst, trinkt 1 Schluck extra.',
  '{{player}} ist für die nächsten 6 Aufgaben der Rätselmeister und stellt vor jeder Aufgabe ein kurzes Rätsel. Wer zuerst die Lösung ruft, verteilt 1 Schluck.',
  '{{player}}, {{player}} und {{player}} sind für die nächsten 4 Aufgaben ein Trinkteam: Trinkt einer, trinken alle drei.',
  '{{player}} sucht sich für die nächsten 6 Aufgaben einen Trinkbuddy aus. Trinkt einer von beiden, trinkt der andere mit.',
  '{{player}} und {{player}} sind für die nächsten 5 Aufgaben Rivalen: Trinkt einer der beiden, bekommt der andere 1 Schluck dazu.',
  '{{player}} und {{player}} sind für die nächsten 5 Aufgaben Zwillinge und müssen jede Frage gleichzeitig beantworten. Sind die Antworten verschieden, trinken beide 1 Schluck.',
  '{{player}} und {{player}} sind für die nächsten 4 Aufgaben an den Ellbogen verbunden und dürfen nur gemeinsam trinken. Wer loslässt, trinkt 2 Schlucke.',
  '{{player}} und {{player}} tauschen für die nächsten 5 Aufgaben ihre Namen. Wer jemanden mit dem alten Namen anspricht, trinkt 1 Schluck.',
  '{{player}} und {{player}} tauschen sofort die Plätze und spielen für die nächsten 5 Aufgaben die Rolle des anderen. Wer aus der Rolle fällt, trinkt 2 Schlucke.',
  '{{player}} und {{player}} sind für die nächsten 6 Aufgaben ein altes Ehepaar und reden sich nur mit "Liebling" an. Jedes vergessene "Liebling" kostet 1 Schluck.',
  '{{player}} und {{player}} sind für die nächsten 5 Aufgaben Erzfeinde und dürfen sich nur siezen. Jedes Du kostet 1 Schluck.',
  '{{player}} und {{player}} schauen sich für die nächsten 5 Aufgaben vor jeder Aufgabe 3 Sekunden ernst an. Wer zuerst lacht, trinkt 1 Schluck.',
  '{{player}} trinkt für die nächsten 5 Aufgaben immer dann 1 Schluck, wenn {{player}} lacht.',
  '{{player}} ist für die nächsten 5 Aufgaben mit dem linken Nachbarn verbunden: Trinkt einer, trinkt der andere mit.',
  'Alle sind für die nächsten 3 Aufgaben mit ihrem rechten Nachbarn verbunden: Wer trinkt, nimmt den Nachbarn mit. Die Kette läuft nur einmal um den Tisch.',
  'Für die nächsten 5 Aufgaben ist das Wort "trinken" verboten. Wer es sagt, trinkt 2 Schlucke.',
  'Für die nächsten 6 Aufgaben ist das Wort "ja" verboten. Wer es sagt, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben ist das Wort "nein" verboten. Wer es sagt, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben sind alle Vornamen verboten. Wer jemanden beim Namen nennt, trinkt 2 Schlucke.',
  'Für die nächsten 4 Aufgaben ist das Wort "du" verboten. Wer es sagt, trinkt 1 Schluck.',
  '{{player}} darf für die nächsten 5 Aufgaben das Wort "und" nicht benutzen. Jedes "und" kostet 1 Schluck.',
  'Für die nächsten 5 Aufgaben sind alle Schimpfwörter verboten. Wer flucht, trinkt 2 Schlucke.',
  'Für die nächsten 6 Aufgaben heißt ein Schluck "Blubb". Wer trotzdem "Schluck" sagt, trinkt 1 Blubb.',
  'Für die nächsten 5 Aufgaben darf niemand "okay" sagen. Wer es tut, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben ist das Wort "Handy" verboten. Wer es sagt, trinkt 2 Schlucke.',
  'Für die nächsten 4 Aufgaben darf niemand ein englisches Wort benutzen. Jedes englische Wort kostet 1 Schluck.',
  '{{player}} denkt sich heimlich ein verbotenes Wort aus und verrät es nicht. Wer es in den nächsten 5 Aufgaben sagt, trinkt 2 Schlucke.',
  'Für die nächsten 5 Aufgaben ist das Wort "Prost" verboten. Wer anstößt, sagt "Zum Wohl" oder trinkt 1 Schluck extra.',
  'Für die nächsten 5 Aufgaben sind die Wörter "links" und "rechts" verboten. Wer eins davon sagt, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben darf niemand "äh" oder "ähm" sagen. Jedes Zögern kostet 1 Schluck.',
  'Für die nächsten 4 Aufgaben sind alle Wörter verboten, die mit "S" beginnen. Wer eins sagt, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben ist das Wort "Aufgabe" verboten. Wer es sagt, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben heißt Wasser "Zaubersaft". Wer "Wasser" sagt, trinkt 1 Schluck.',
  'Für die nächsten 6 Aufgaben heißt jedes Glas "Pokal". Wer "Glas" sagt, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben heißt der Tisch "Insel". Wer "Tisch" sagt, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben muss jeder vor dem Trinken "Auf die Königin!" rufen. Wer es vergisst, trinkt 1 Schluck extra.',
  'Für die nächsten 6 Aufgaben muss jeder nach dem Trinken "Ahhh, köstlich!" sagen. Wer es vergisst, trinkt nochmal.',
  'Für die nächsten 4 Aufgaben muss jeder vor dem Trinken laut bis 3 zählen. Wer es vergisst, trinkt doppelt.',
  'Für die nächsten 5 Aufgaben muss jeder seine Sätze mit "meine Damen und Herren" beenden. Wer es vergisst, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben muss jeder vor dem Trinken "Ich bereue nichts!" sagen. Wer es vergisst, trinkt 1 Schluck extra.',
  'Für die nächsten 6 Aufgaben muss jeder vor dem Trinken mit dem Glas einen Kreis in die Luft malen. Wer es vergisst, trinkt 1 Schluck extra.',
  'Für die nächsten 5 Aufgaben muss jeder vor dem Trinken einen Tierlaut machen, den es am Tisch noch nicht gab. Eine Wiederholung kostet 1 Schluck extra.',
  'Für die nächsten 5 Aufgaben muss jeder nach dem Trinken kurz salutieren. Wer es vergisst, trinkt 1 Schluck.',
  'Für die nächsten 4 Aufgaben muss jeder vor dem Trinken einen kurzen Toast auf den linken Nachbarn aussprechen. Wer es vergisst, trinkt doppelt.',
  'Für die nächsten 5 Aufgaben muss jeder vor dem Trinken einmal kurz aufstehen und sich wieder setzen. Wer sitzen bleibt, trinkt 1 Schluck extra.',
  'Für die nächsten 5 Aufgaben muss jeder beim Trinken den kleinen Finger abspreizen. Wer es vergisst, trinkt 1 Schluck extra.',
  'Für die nächsten 6 Aufgaben muss jeder nach dem Trinken "Danke, Glas" flüstern. Wer es vergisst, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben darf nur mit der linken Hand getrunken werden. Wer rechts trinkt, trinkt 2 Schlucke.',
  '{{player}} darf für die nächsten 6 Aufgaben nur mit der rechten Hand trinken, alle anderen nur mit der linken. Jeder Fehler kostet 1 Schluck.',
  '{{player}} und {{player}} reichen sich für die nächsten 3 Aufgaben gegenseitig das Glas und dürfen ihr eigenes nicht anfassen. Wer es doch tut, trinkt 2 Schlucke.',
  'Für die nächsten 5 Aufgaben muss jeder sein Glas mit beiden Händen halten wie einen kostbaren Pokal. Wer einhändig trinkt, trinkt 1 Schluck extra.',
  '{{player}} darf für die nächsten 4 Aufgaben nur mit überkreuzten Armen trinken. Jeder Fehler kostet 1 Schluck.',
  'Für die nächsten 5 Aufgaben muss beim Trinken eine Hand auf dem Kopf liegen. Wer es vergisst, trinkt 1 Schluck extra.',
  '{{player}} darf für die nächsten 4 Aufgaben das eigene Glas nicht anfassen, {{player}} muss es beim Trinken reichen. Wer schummelt, trinkt 2 Schlucke.',
  'Für die nächsten 5 Aufgaben darf niemand mit dem Finger auf jemanden zeigen. Wer es tut, trinkt 2 Schlucke.',
  'Für die nächsten 4 Aufgaben müssen alle Ellbogen vom Tisch bleiben. Wer erwischt wird, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben gilt: Wer sich ins Gesicht fasst, trinkt 1 Schluck.',
  '{{player}} spricht für die nächsten 5 Aufgaben mit französischem Akzent. Jeder Ausrutscher kostet 1 Schluck.',
  'Alle sprechen für die nächsten 4 Aufgaben wie Cowboys aus dem Wilden Westen. Wer normal redet, trinkt 1 Schluck.',
  '{{player}} spricht für die nächsten 5 Aufgaben im Dialekt einer selbst gewählten Region. Fällt diese Person in ihre normale Sprache zurück, trinkt sie 1 Schluck.',
  '{{player}} muss für die nächsten 5 Aufgaben in Reimen sprechen. Für jeden Satz ohne Reim gibt es 1 Schluck.',
  'Für die nächsten 4 Aufgaben sprechen alle in der dritten Person über sich selbst. Wer "ich" sagt, trinkt 1 Schluck.',
  '{{player}} beginnt für die nächsten 5 Aufgaben jeden Satz mit "Es war einmal". Jeder vergessene Märchenanfang kostet 1 Schluck.',
  '{{player}} spricht für die nächsten 5 Aufgaben mit sehr hoher Stimme. Jeder normale Satz kostet 1 Schluck.',
  '{{player}} spricht für die nächsten 4 Aufgaben extrem langsam, als wäre die Batterie leer. Wer darüber lacht, trinkt 1 Schluck.',
  'Alle müssen für die nächsten 5 Aufgaben flüstern. Wer laut spricht, trinkt 1 Schluck.',
  '{{player}} spricht für die nächsten 5 Aufgaben wie ein Werbesprecher im Radio. Jeder normale Satz kostet 1 Schluck.',
  '{{player}} muss für die nächsten 5 Aufgaben jeden Satz mit einem Lachen beenden. Ohne Lachen gibt es 1 Schluck.',
  '{{player}} redet für die nächsten 4 Aufgaben wie ein Navigationsgerät. Jeder normale Satz kostet 1 Schluck.',
  '{{player}} spricht für die nächsten 5 Aufgaben nur in Sätzen mit höchstens 3 Wörtern. Jeder längere Satz kostet 1 Schluck.',
  '{{player}} spricht für die nächsten 4 Aufgaben wie ein überdrehter Gameshow-Moderator. Jeder ruhige Satz kostet 1 Schluck.',
  '{{player}} spricht für die nächsten 5 Aufgaben wie ein Geist und lässt jeden Satz mit "Huuuh" enden. Jeder vergessene Geisterruf kostet 1 Schluck.',
  '{{player}} spricht für die nächsten 5 Aufgaben wie ein Kaiser nur in der Mehrzahl von sich, etwa "Wir wünschen ein Getränk". Jedes "ich" kostet 1 Schluck.',
  '{{player}} spricht für die nächsten 4 Aufgaben wie ein Wikinger und schlägt nach jedem Satz einmal sanft auf den Tisch. Jeder vergessene Schlag kostet 1 Schluck.',
  'Alle rücken sofort einen Platz nach links. Wer zuletzt sitzt, trinkt 2 Schlucke.',
  '{{player}} und {{player}} tauschen sofort die Plätze. Wer länger braucht, trinkt 1 Schluck.',
  'Alle stehen auf und suchen sich einen neuen Platz. Wer zuletzt sitzt oder auf dem alten Platz landet, trinkt 2 Schlucke.',
  '{{player}} darf zwei beliebige Personen die Plätze tauschen lassen. Beide trinken zur Begrüßung am neuen Platz 1 Schluck.',
  'Die zwei jüngsten Personen am Tisch tauschen sofort die Plätze und trinken auf den neuen Platz 1 Schluck.',
  'Die Person mit dem vollsten Glas tauscht den Platz mit der Person mit dem leersten Glas. Beide trinken 1 Schluck.',
  '{{player}} wird zum Kaiser gekrönt und bestimmt für die nächsten 5 Aufgaben nach jeder Aufgabe einen Untertan, der 1 Schluck trinkt.',
  'Alle Regeln sind aufgehoben. Zur Feier trinken alle 1 Schluck.',
  'Alle Rollen sind aufgehoben. Wer bis eben eine Rolle hatte, trinkt zum Abschied 1 Schluck.',
  '{{player}} darf eine laufende Regel aufheben. Gibt es gerade keine Regel, trinkt diese Person 2 Schlucke.',
  'Alle verbotenen Wörter sind wieder erlaubt. Zur Erleichterung ruft jeder sein Lieblingswort und trinkt 1 Schluck.',
  'Alle Trinkbuddys werden getrennt. Wer einen Buddy hatte, trinkt einen Abschiedsschluck.',
  '{{player}} darf eine laufende Regel um 3 Aufgaben verlängern oder sofort beenden und trinkt danach 1 Schluck.',
  'Die zuletzt eingeführte Regel wird verschärft: Jeder Verstoß kostet ab jetzt 2 Schlucke mehr.',
  'Alle laufenden Regeln sind aufgehoben, außer einer. {{player}} entscheidet, welche bleibt, und trinkt dafür 1 Schluck.',
  'Wer gerade eine Rolle hat, gibt sie an den linken Nachbarn weiter. Der neue Rollenträger trinkt 1 Schluck.',
  'Rollentausch: Alle, die gerade eine Rolle haben, tauschen sie untereinander. Gibt es nur eine Rolle, geht sie an {{player}}.',
  '{{player}} darf sich von einer laufenden Regel oder Rolle freikaufen, indem diese Person 3 Schlucke trinkt.',
  'Amnestie: Wer heute schon gegen eine Regel verstoßen hat, darf jetzt 1 Schluck verteilen.',
  'Alle Flüche sind gebrochen. Wer verflucht war, darf 2 Schlucke verteilen.',
  'Fluch: {{player}} vertauscht für die nächsten 5 Aufgaben "ja" und "nein". Jeder Fehler kostet 1 Schluck.',
  'Fluch: {{player}} darf für die nächsten 5 Aufgaben nicht lächeln. Jedes Lächeln kostet 1 Schluck.',
  'Fluch: {{player}} muss für die nächsten 4 Aufgaben bei jedem Lachen am Tisch empört "Wer stört?" rufen. Jedes vergessene Mal kostet 1 Schluck.',
  'Fluch: {{player}} darf für die nächsten 5 Aufgaben keine Fragen beantworten, sondern nur mit Gegenfragen reagieren. Jede echte Antwort kostet 1 Schluck.',
  'Fluch: {{player}} hat für die nächsten 5 Aufgaben alle Namen vergessen und nennt jeden "Kumpel". Jeder genannte Name kostet 1 Schluck.',
  'Fluch: {{player}} muss für die nächsten 4 Aufgaben alles, was am Tisch gesagt wird, mit "Ganz genau!" bestätigen. Jedes vergessene Mal kostet 1 Schluck.',
  'Fluch: {{player}} wird für die nächsten 5 Aufgaben zur Katze und antwortet nur mit "Miau". Jedes echte Wort kostet 1 Schluck.',
  'Fluch: {{player}} hat für die nächsten 5 Aufgaben den Medusablick. Wer von dieser Person angestarrt wird, erstarrt 5 Sekunden oder trinkt 1 Schluck.',
  'Fluch: {{player}} hat für die nächsten 5 Aufgaben Schluckauf und muss nach jedem Satz "hicks" sagen. Jedes vergessene Hicks kostet 1 Schluck.',
  'Fluch: Jedes Mal, wenn {{player}} in den nächsten 5 Aufgaben lacht, trinkt der linke Nachbar 1 Schluck.',
  'Fluch: {{player}} ist für die nächsten 4 Aufgaben ein Vampir und trinkt nur hinter dem angewinkelten Arm wie hinter einem Umhang. Wer es vergisst, trinkt 1 Schluck extra.',
  'Fluch: {{player}} muss für die nächsten 5 Aufgaben jeden Satz mit "Leider" beginnen. Jeder Satz ohne kostet 1 Schluck.',
  'Fluch: {{player}} ist für die nächsten 5 Aufgaben ein Pechmagnet. Jedes Mal, wenn jemand Schlucke verteilt, bekommt diese Person 1 zusätzlich.',
  'Fluch: {{player}} muss für die nächsten 4 Aufgaben über jeden Witz am Tisch übertrieben laut lachen. Jedes ausbleibende Lachen kostet 1 Schluck.',
  'Fluch: {{player}} ist für die nächsten 5 Aufgaben ein Huhn und muss nach jedem Schluck gackern. Jedes vergessene Gackern kostet 1 Schluck.',
  '{{player}} ist für die nächsten 4 Aufgaben der Anführer: Alle machen jede Geste dieser Person nach. Wer es vergisst, trinkt 1 Schluck.',
  '{{player}} verkündet jetzt eine 20 Sekunden lange Eilmeldung über das Getränk in der eigenen Hand. Wer dabei lacht, trinkt 1 Schluck.',
  'Alle machen gleichzeitig ihr bestes Tiergeräusch. Der Tisch bestimmt das schwächste, und wer es gemacht hat, trinkt 2 Schlucke.',
  '{{player}} trinkt den nächsten Schluck in extremer Zeitlupe. Wer währenddessen lacht, trinkt ebenfalls 1 Schluck.',
  '{{player}} hat 10 Sekunden, um 5 Dinge aufzuzählen, die gelb sind. Schafft diese Person es nicht, trinkt sie 2 Schlucke.',
  'Alle zeigen auf Kommando auf die Person, die am ehesten einen Kaktus adoptieren würde. Wer die meisten Finger abbekommt, trinkt 2 Schlucke.',
  '{{player}} spielt einen Fernsehkoch und stellt das eigene Getränk vor. Danach trinken alle einen Probierschluck.',
  'Wer zuletzt die Hände auf den Kopf legt, trinkt 2 Schlucke.',
  'Wer zuletzt "Bananenbrot!" ruft, trinkt 2 Schlucke.',
  '{{player}} erfindet ein neues Wort und erklärt seine Bedeutung. Wer es in den nächsten 5 Aufgaben nicht mindestens einmal benutzt, trinkt 1 Schluck.',
  '{{player}} und {{player}} liefern sich ein Starrduell. Wer zuerst blinzelt oder lacht, trinkt 2 Schlucke.',
  'Alle frieren sofort ein. Wer sich als Erstes bewegt, trinkt 2 Schlucke.',
  '{{player}} macht das Geräusch eines startenden Flugzeugs. Ist der Tisch nicht überzeugt, trinkt diese Person 1 Schluck.',
  '{{player}} hält eine 15 Sekunden lange Wahlkampfrede für das Amt des Tischpräsidenten. Wird die Person gewählt, verteilt sie 3 Schlucke, sonst trinkt sie 2.',
  '{{player}} verkauft {{player}} in 20 Sekunden einen beliebigen Gegenstand vom Tisch. Wird der Gegenstand gekauft, trinkt der Käufer 2 Schlucke, sonst der Verkäufer.',
  'Alle stoßen an und machen dabei ein Geräusch wie ein Delfin. Danach trinken alle 1 Schluck.',
  '{{player}} beschreibt das eigene Getränk wie ein überheblicher Weinkenner. Gibt der Tisch weniger als 5 von 10 Punkten, trinkt diese Person 2 Schlucke.',
  'Wer zuerst einen blauen Gegenstand hochhält, darf 2 Schlucke verteilen.',
  '{{player}} spricht 30 Sekunden lang wie ein Tierfilmer über {{player}}. Wer währenddessen lacht, trinkt 1 Schluck.',
  'Alle heulen auf Kommando wie Wölfe. Der Leiseste trinkt 2 Schlucke.',
  '{{player}} macht vor, wie eine Giraffe trinkt. Danach trinken alle 1 Schluck auf die Giraffe.',
  '{{player}} zählt mit geschlossenen Augen bis 20 und alle anderen müssen absolut still sein. Wer ein Geräusch macht, trinkt 1 Schluck.',
  '{{player}} erklärt in 20 Sekunden, warum Socken gefährlich sind. Ist der Tisch überzeugt, verteilt diese Person 2 Schlucke, sonst trinkt sie 2.',
  'Alle machen gleichzeitig ein Gesicht, als hätten sie in eine Zitrone gebissen. Das überzeugendste Gesicht darf 2 Schlucke verteilen.',
  '{{player}} ist jetzt ein Wackeldackel und nickt bis zur nächsten Aufgabe zu allem. Danach trinkt diese Person 1 Schluck.',
  '{{player}} beginnt einen Satz und reihum fügt jeder ein Wort hinzu. Wer zögert oder den Satz kaputt macht, trinkt 2 Schlucke.',
  '{{player}} summt ein bekanntes Lied. Wer es zuerst errät, verteilt 2 Schlucke. Errät es niemand, trinkt die summende Person 2 Schlucke.',
  'Für die nächsten 5 Aufgaben müssen alle mitlachen, wenn {{player}} lacht. Wer nicht mitlacht, trinkt 1 Schluck.',
  'Für die nächsten 6 Aufgaben gilt: Wer gähnt, trinkt 2 Schlucke.',
  'Für die nächsten 5 Aufgaben gilt: Wer auf sein Handy schaut, trinkt 2 Schlucke.',
  'Für die nächsten 5 Aufgaben gilt: Wer eine Frage stellt, trinkt 1 Schluck.',
  'Für die nächsten 4 Aufgaben gilt: Wer die Beine übereinanderschlägt, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben gilt: Wer laut seufzt, trinkt 1 Schluck.',
  'Für die nächsten 6 Aufgaben gilt: Wer niest, darf 3 Schlucke verteilen.',
  'Für die nächsten 5 Aufgaben gilt: Wer aufsteht, muss beim Hinsetzen "Ich bin zurück!" rufen oder trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben gilt: Wer sein Glas leert, darf eine neue Regel für 3 Aufgaben erfinden.',
  'Für die nächsten 5 Aufgaben gilt: Jedes Mal, wenn jemand "Chaos" sagt, trinken alle 1 Schluck.',
  'Für die nächsten 4 Aufgaben gilt: Wer lacht, muss dabei die Hand vor den Mund halten oder trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben muss jeder nach dem Trinken zweimal mit dem Glas auf den Tisch tippen. Wer es vergisst, trinkt 1 Schluck extra.',
  'Für die nächsten 5 Aufgaben dürfen Gläser nur am Rand des Tisches stehen. Wer sein Glas weiter in die Mitte stellt, trinkt 1 Schluck.',
  'Für die nächsten 6 Aufgaben gilt: Wer eine Aufgabe kommentiert, bevor sie erledigt ist, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben fragt jeder vor dem Trinken den Nachbarn "Darf ich?". Wer es vergisst, trinkt doppelt.',
  'Für die nächsten 5 Aufgaben gilt: Wer ein Getränk erwähnt, das nicht auf dem Tisch steht, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben ist die Mitte des Tisches Lava. Wer sie berührt, trinkt 2 Schlucke.',
  'Für die nächsten 6 Aufgaben gilt: Muss jemand 3 Schlucke oder mehr trinken, klatschen alle anderen. Wer nicht klatscht, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben gilt: Wer "danke" sagt, trinkt sofort 1 Schluck, und wer "bitte" sagt, darf 1 Schluck verteilen.',
  'Für die nächsten 4 Aufgaben nennt jeder vor dem Trinken einen Dinosaurier. Wer einen Dinosaurier doppelt nennt, trinkt 1 Schluck extra.',
  'Für die nächsten 5 Aufgaben gilt: Wer {{player}} unterbricht, trinkt 2 Schlucke.',
  'Für die nächsten 5 Aufgaben gilt: Wer ein Kompliment bekommt, muss sich verbeugen oder trinkt 1 Schluck.',
  'Für die nächsten 6 Aufgaben gilt das Echo-Gesetz: Ruft jemand "Echo!", wiederholen alle das letzte Wort. Wer zu spät ist, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben muss jeder beim Sprechen eine Hand aufs Herz legen. Wer erwischt wird, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben gilt: Wer sich über eine Aufgabe beschwert, trinkt die doppelte Menge.',
  'Für die nächsten 5 Aufgaben darf jeder einmal "Hoch!" rufen. Dann heben alle ihr Glas und der Letzte trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben werden alle Schlucke verdoppelt, die {{player}} verteilt.',
  'Für die nächsten 5 Aufgaben werden alle Schlucke halbiert, die {{player}} trinken muss. Aufgerundet wird trotzdem.',
  'Für die nächsten 4 Aufgaben müssen alle beim Trinken {{player}} in die Augen schauen. Wer wegschaut, trinkt 1 Schluck extra.',
  '{{player}} darf in den nächsten 5 Aufgaben heimlich zwinkern. Wer angezwinkert wird, trinkt 1 Schluck. Wird die zwinkernde Person erwischt, trinkt sie 2.',
  'Für die nächsten 6 Aufgaben heißt jedes Glas Gustav und muss vor dem Trinken begrüßt werden. Wer Gustav nicht begrüßt, trinkt 1 Schluck extra.',
  'Für die nächsten 5 Aufgaben gilt: Wer ein Tier erwähnt, macht es kurz nach oder trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben gilt: Wer {{player}} ein Kompliment macht, darf 1 Schluck verteilen.',
  'Für die nächsten 4 Aufgaben lachen alle nur noch mit "Hohoho" wie der Weihnachtsmann. Wer normal lacht, trinkt 1 Schluck.',
  'Für die nächsten 5 Aufgaben gilt: Wer sein Glas anfasst, ohne zu trinken, muss sofort 1 Schluck trinken.',
  'Für die nächsten 5 Aufgaben gilt: Bei jedem Regelverstoß ruft der ganze Tisch "Chaos!" und der Sünder trinkt 1 Schluck extra.',
  '{{player}} spricht die Vornamen aller am Tisch rückwärts aus. Für jeden Fehler gibt es 1 Schluck.',
  '{{player}} buchstabiert das Wort "Schifffahrt" rückwärts. Schafft diese Person es nicht, trinkt sie 2 Schlucke.',
  '{{player}} sagt 3 Mal schnell "Fischers Fritz fischt frische Fische". Jeder Versprecher kostet 1 Schluck.',
  'Alle singen gemeinsam den Refrain eines Liedes, das {{player}} aussucht. Wer den Text nicht kennt, trinkt 1 Schluck.',
  '{{player}} imitiert einen Staubsauger, bis jemand lacht. Wer zuerst lacht, trinkt 2 Schlucke.',
  'Alle berühren sofort etwas Rotes. Wer zuletzt etwas findet, trinkt 2 Schlucke.',
  '{{player}} hat 15 Sekunden, um 4 Wörter zu nennen, die sich auf "Bier" reimen. Für jedes fehlende Wort gibt es 1 Schluck.',
  'Alle rufen gleichzeitig ihr Lieblingsessen. Wer dasselbe ruft wie jemand anderes, trinkt 1 Schluck.',
  '{{player}} kündigt die nächste Aufgabe mit einem Trommelwirbel auf dem Tisch an und darf dafür 1 Schluck verteilen.',
  '{{player}} und {{player}} spielen Schere, Stein, Papier. Der Verlierer trinkt 2 Schlucke und nennt den Gewinner für die nächsten 3 Aufgaben nur "Champion".',
  'Alle erstarren sofort in der Pose einer Statue. {{player}} kürt die beste Statue, die 2 Schlucke verteilen darf.',
  'Wer als Erstes ein Lied mit einer Farbe im Titel nennt, darf 2 Schlucke verteilen.',
  '{{player}} spricht einen Trinkspruch nur aus Geräuschen, ohne ein echtes Wort. Danach trinken alle 1 Schluck.',
  '{{player}} erfindet einen Tanzschritt, den alle im Sitzen nachmachen. Wer sich weigert, trinkt 2 Schlucke.',
  'Alle täuschen gleichzeitig ein Gähnen vor. Wer dabei wirklich gähnen muss, trinkt 1 Schluck.',
  '{{player}} flüstert {{player}} ein Wort zu, das die zweite Person pantomimisch darstellt. Errät der Tisch es in 30 Sekunden, verteilt der Darsteller 2 Schlucke, sonst trinkt er 2.',
  'Alle trommeln 5 Sekunden auf den Tisch. Wer danach als Letzter aufhört, trinkt 1 Schluck.',
  '{{player}} erzählt die Handlung eines Films in einem Satz so schlecht wie möglich. Wer den Film zuerst errät, verteilt 2 Schlucke.',
  '{{player}} wird kurz zum Dinosaurier und brüllt so laut wie möglich. Wer sich erschreckt, trinkt 1 Schluck.',
  '{{player}} macht einen Wetterbericht für den Tisch. Bei Regen trinken alle 1 Schluck, bei Sonne nur der Moderator.',
  'Alle zeigen gleichzeitig mit dem Daumen nach oben oder unten. Die Minderheit trinkt 2 Schlucke.',
  '{{player}} und {{player}} streiten 20 Sekunden lang nur mit dem Wort "Kartoffel". Der Tisch kürt den Sieger und der Verlierer trinkt 2 Schlucke.',
  '{{player}} versucht 10 Sekunden lang nicht zu blinzeln, während alle Grimassen schneiden. Schafft diese Person es, verteilt sie 3 Schlucke, sonst trinkt sie 2.',
  'Alle nennen reihum ein Wort, das mit "Z" beginnt. Wer zögert oder etwas wiederholt, trinkt 2 Schlucke.',
  '{{player}} lässt das eigene Glas mit verstellter Stimme eine kurze Dankesrede an den Tisch halten. Danach trinken alle 1 Schluck.',
  '{{player}} hat 20 Sekunden, um den Tisch ohne Worte zum Lachen zu bringen. Lacht jemand, trinkt der Lacher 1 Schluck, sonst trinkt der Clown 2 Schlucke.',
  'Die Person mit den meisten Buchstaben im Vornamen trinkt 2 Schlucke und schreibt den Namen danach mit der Nase in die Luft.',
  'Die Person mit dem kürzesten Vornamen muss für die nächsten 5 Aufgaben jede neue Regel laut wiederholen. Jede vergessene Wiederholung kostet 1 Schluck.',
  'Die größte Person am Tisch ist für die nächsten 5 Aufgaben der Leuchtturm: Ruft sie "Nebel!", machen alle "Tuuut". Der Letzte trinkt 1 Schluck.',
  'Die kleinste Person am Tisch darf in den nächsten 5 Aufgaben einmal "Stopp!" rufen und damit eigene Schlucke überspringen.',
  'Wer als Letztes Geburtstag hatte, wird gefeiert: Alle singen kurz ein Ständchen und das Geburtstagskind verteilt 3 Schlucke.',
  'Wer heute am weitesten angereist ist, ist für die nächsten 5 Aufgaben Tourist und kommentiert jede Aufgabe mit "Wie aufregend!". Jeder vergessene Kommentar kostet 1 Schluck.',
  'Wer die meisten Ringe trägt, darf 2 Schlucke verteilen und bekommt in den nächsten 3 Aufgaben keine Schlucke zugeteilt.',
  'Die Person mit dem leersten Glas ist für die nächsten 4 Aufgaben Kapitän: Ruft sie "Alle Mann an Deck!", stehen alle auf. Der Letzte trinkt 1 Schluck.',
  '{{player}} muss für die nächsten 3 Aufgaben ununterbrochen leise vor sich hin murmeln. Jede Pause über 5 Sekunden kostet 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben der Erfinder und denkt sich nach jeder Aufgabe eine Mini-Regel für 1 Aufgabe aus. Fällt dieser Person nichts ein, trinkt sie 2 Schlucke.',
  '{{player}} bekommt einen Joker: Einmal in den nächsten 6 Aufgaben darf diese Person "Joker!" rufen und eigene Schlucke an jemand anderen weitergeben.',
  '{{player}} ist für die nächsten 5 Aufgaben der Störenfried und darf einmal pro Aufgabe ein seltsames Geräusch machen. Wer darauf reagiert, trinkt 1 Schluck.',
  '{{player}} ist für die nächsten 4 Aufgaben Wahrsager und sagt jedem vor dem Trinken die Zukunft voraus. Wer über die Prophezeiung lacht, trinkt 1 Schluck extra.',
  '{{player}} ist für die nächsten 5 Aufgaben Alarmanlage und ruft "Achtung!", sobald jemand sein Glas hebt. Jedes verpasste "Achtung" kostet 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben Hellseher und tippt vor jeder Aufgabe, wer als Nächstes trinkt. Bei jedem Treffer verteilt diese Person 2 Schlucke.',
  '{{player}} ist für die nächsten 6 Aufgaben Glasaufsicht: Wer sein Glas unbeaufsichtigt stehen lässt, bekommt von dieser Person 1 Schluck.',
  '{{player}} ist für die nächsten 5 Aufgaben ein Superheld und ruft vor jedem eigenen Schluck den eigenen Heldennamen. Wer den Namen vergisst, trinkt 1 Schluck extra.',
  '{{player}} und {{player}} sind für die nächsten 5 Aufgaben verfeindete Staaten und reden nur über einen Botschafter, den sie gemeinsam wählen. Wer direkt spricht, trinkt 2 Schlucke.',
  '{{player}} und {{player}} sind für die nächsten 4 Aufgaben Schicksalspartner: Muss einer trinken, entscheidet Schere, Stein, Papier, wer es tatsächlich tut.',
  '{{player}} und {{player}} sind für die nächsten 5 Aufgaben Komplizen und dürfen sich einmal gegenseitig vor einer Trinkaufgabe retten. Der Retter trinkt dann 1 Schluck.',
  '{{player}} und {{player}} müssen für die nächsten 5 Aufgaben die Sätze des anderen beenden. Wer nicht einspringt, trinkt 1 Schluck.',
  '{{player}}, {{player}} und {{player}} sind für die nächsten 5 Aufgaben eine Band und singen bei jedem Schluck gemeinsam "Yeah!". Wer nicht mitsingt, trinkt 1 Schluck.',
  '{{player}} und {{player}} gründen eine Geheimgesellschaft und vereinbaren ein geheimes Handzeichen für die nächsten 5 Aufgaben. Errät es jemand, trinken beide 2 Schlucke.',
  '{{player}} und {{player}} sind für die nächsten 5 Aufgaben Fernsehsender und dürfen nur sprechen, nachdem sie eine Werbepause angekündigt haben. Jeder Verstoß kostet 1 Schluck.',
  'Wer heute schon gegen eine Regel verstoßen hat, gesteht es jetzt und trinkt 1 Schluck. Wer schweigt und verraten wird, trinkt 3.',
  'Chaosrunde: Alle rufen gleichzeitig eine neue Regel. {{player}} entscheidet, welche für die nächsten 5 Aufgaben gilt.',
  'Demokratie: Der Tisch stimmt ab, welche laufende Regel abgeschafft wird. Wer für die siegende Regel gestimmt hat, trinkt 1 Schluck.',
  'Revolution: Alle, die gerade keine Rolle haben, trinken 1 Schluck. Alle, die eine haben, verlieren sie.',
  'Die älteste laufende Regel wird durch ihr Gegenteil ersetzt. {{player}} formuliert das Gegenteil und trinkt dafür 1 Schluck.',
  'Wer als Erstes alle laufenden Regeln aufzählen kann, darf 3 Schlucke verteilen.',
  'Gedächtnistest: {{player}} zählt alle gerade geltenden Regeln auf. Für jede vergessene Regel gibt es 1 Schluck.',
  'Glückssträhne: In den nächsten 3 Aufgaben darf jeder, der trinken muss, einmal "Glück!" rufen und 1 Schluck weniger trinken.',
  'Für die nächsten 5 Aufgaben ruft jeder, der bei einer Aufgabe gemeint ist, dramatisch "Warum immer ich?". Wer es vergisst, trinkt 1 Schluck extra.',
  'Für die nächsten 4 Aufgaben wird jeder Schluck mit geschlossenen Augen getrunken. Wer blinzelt, trinkt 1 Schluck extra.',
  '{{player}} hält eine feierliche Lobrede auf den letzten Schluck im eigenen Glas und trinkt ihn danach.',
  '{{player}} macht 10 Sekunden lang Werbung für Leitungswasser. Überzeugt das den Tisch, trinken alle 1 Schluck Wasser, sonst trinkt der Werbende 2 Schlucke.',
  '{{player}} spielt ein Gespräch zwischen dem eigenen linken und rechten Schuh nach. Gibt es keinen Applaus, trinkt diese Person 2 Schlucke.',
  'Alle tun 10 Sekunden lang so, als säßen sie in einer Achterbahn. Wer am wenigsten Einsatz zeigt, trinkt 2 Schlucke.',
  '{{player}} sagt das Alphabet so schnell wie möglich auf. Dauert es länger als 10 Sekunden, trinkt diese Person 2 Schlucke.',
  '{{player}} nennt 3 Dinge, die man nicht in eine Mikrowelle stecken sollte. Wer etwas Lustigeres findet, darf dieser Person 1 Schluck geben.',
  '{{player}} beschreibt den eigenen Morgen wie einen Actionfilm-Trailer. Danach trinken alle 1 Schluck auf den Helden.',
  'Alle machen gleichzeitig das Geräusch eines Weckers. Wer zuletzt aufhört, trinkt 1 Schluck.',
  '{{player}} erfindet einen Namen für die Gruppe. Für die nächsten 5 Aufgaben ruft jeder ihn vor dem Trinken, sonst gibt es 1 Schluck extra.',
  '{{player}} spielt eine Fliege, die um den Tisch summt, und landet bei einer Person. Diese Person trinkt 2 Schlucke.',
  '{{player}} begrüßt jede Person am Tisch wie einen lange verschollenen Freund. Wer nicht mitspielt, trinkt 1 Schluck.',
  '{{player}} zeigt die Siegerpose für einen Lottogewinn. Gibt der Tisch weniger als 6 von 10 Punkten, trinkt diese Person 2 Schlucke.',
  '{{player}} erklärt {{player}} so überzeugend wie möglich ein Hobby, das es nicht gibt. Glaubt die zweite Person es, trinkt sie 2 Schlucke.',
];
