export const curatedNormalTasks: string[] = [
  "{{player}}, wer von {{player}} und {{player}} wird eher berühmt? Die gewählte Person verteilt 3 Schlucke.",
  "{{player}} und {{player}}, gleicht eure Gläser aus. Wer mehr im Glas hat, trinkt, bis beide gleich voll sind.",
  "{{player}}, trink 3 Schlucke, wenn du Kinder magst.",
  "Abstimmung: Lieber nie wieder Alkohol oder für immer jeden Tag ein Bier? Die Minderheit trinkt 4 Schlucke.",
  "Abstimmung: Wer bringt die flachsten Witze? Die gewählte Person verteilt 5 Schlucke.",
  "{{player}}, trink 2 Schlucke, wenn du Taylor Swift magst.",
  "{{player}}, denk an eine Person, die du heute getroffen hast. Reihum rät jeder einmal, wer gemeint ist. Wer falsch rät, trinkt 1 Schluck.",
  "Alle singen den Refrain von „Love Story“ von Taylor Swift. Wer am schönsten singt, verteilt 5 Schlucke.",
  "Für die nächsten 10 Minuten sind alle liebevoll zueinander. Wer unfreundlich ist, trinkt 2 Schlucke.",
  "{{player}}, trink so viele Schlucke, wie dein Nachname Konsonanten hat.",
  "{{player}}, trink 3 Schlucke, wenn du ein Haustier hast.",
  "Reihum sagt jeder ein Sprichwort. Wem keins mehr einfällt, trinkt 3 Schlucke.",
  "Alle trinken 1 Schluck für jede eingeladene Person, die nicht gekommen ist.",
  "{{player}}, was war das Dümmste, das du je betrunken gemacht hast? Erzähl es oder trink 5 Schlucke.",
  "{{player}}, verteile 3 Schlucke an einen Spieler, der kleiner ist als du.",
  "{{player}}, wer von {{player}} und {{player}} würde sich eher selbst ein Tattoo stechen? Die gewählte Person verteilt 3 Schlucke.",
  "Alle Brillenträger verteilen 3 Schlucke.",
  "{{player}}, schließ die Augen. Die anderen geben dir ein Getränk und du musst erraten, wem es gehört. Liegst du richtig, verteile 5 Schlucke, sonst trink 3.",
  "{{player}}, trink 3 Schlucke, wenn du mit dem Auto gekommen bist.",
  "Abstimmung: Bier oder Schnaps? Die Minderheit trinkt 2 Schlucke.",
  "{{player}}, trink 2 Schlucke.",
  "Abstimmung: Wer hat den besten Musikgeschmack? Die gewählte Person verteilt 5 Schlucke.",
  "{{player}}, verteile 2 Schlucke, wenn du Marvel-Filme nicht magst.",
  "{{player}}, mach einen Handstand oder trink 5 Schlucke.",
  "{{player}}, trink 3 Schlucke, wenn du gerne telefonierst.",
  "{{player}}, trink 2 Schlucke, wenn du noch nie Fallschirmspringen warst.",
  "{{player}}, trink 3 Schlucke, wenn du studierst.",
  "Alle Spielerinnen trinken 3 Schlucke.",
  "{{player}}, wer von {{player}} und {{player}} hat in der Schule öfter geschwänzt? Die gewählte Person trinkt 3 Schlucke.",
  "Alle, die im Sommer Geburtstag haben, trinken 2 Schlucke.",
  "{{player}}, wenn dein Vorname mit T beginnt, trink 3 Schlucke. Sonst verteile sie.",
  "{{player}}, trink 3 Schlucke, wenn du täglich duschst.",
  "{{player}}, trink 2 Schlucke, wenn du diese Woche schon Fahrrad gefahren bist.",
  "{{player}}, trink so viele Schlucke, wie {{player}} Jahre älter oder jünger ist als du, mindestens aber 1.",
  "{{player}}, trink 3 Schlucke, wenn du ein eigenes Bad hast.",
  "Alle, die schon mal von einem Sexbot auf Instagram angeschrieben wurden, trinken 2 Schlucke.",
  "Wer als Letztes die Füße vom Boden hebt, trinkt 3 Schlucke.",
  "Alle, die noch zu Hause wohnen, trinken 2 Schlucke.",
  "Wer als Nächstes Geburtstag hat, verteilt 5 Schlucke. Hat die Person heute Geburtstag, trinken alle anderen 3 Schlucke.",
  "{{player}}, trink 2 Schlucke, wenn du Netflix über den Account von jemand anderem schaust.",
  "{{player}}, nenne 3 Songs von Taylor Swift. Schaffst du es, verteile 2 Schlucke, sonst trink sie selbst.",
  "Alle, die ein eigenes Auto haben, trinken 2 Schlucke.",
  "{{player}}, deine beiden Sitznachbarn trinken 2 Schlucke.",
  "{{player}}, such dir einen Trinkbuddy aus. Bis zum Spielende trinkt er immer mit, wenn du trinkst.",
  "{{player}}, such dir einen Trinkbuddy aus. Bis zum Spielende trinkt ihr immer gemeinsam, egal wer von euch trinken muss.",
  "{{player}}, schütte 1 Schluck deines Getränks in das Glas der Person dir gegenüber.",
  "{{player}}, wer von {{player}} und {{player}} würde sich eher mit dir streiten? Die gewählte Person trinkt 3 Schlucke.",
  "{{player}}, trink 3 Schlucke. Danach trinkt gegen den Uhrzeigersinn jeder 1 Schluck weniger als sein Vorgänger.",
  "Alle trinken so viele Schlucke, wie sie Geschwister haben.",
  "Alle, die heute schon mehr als 2 Stunden auf Social Media waren, trinken 2 Schlucke.",
  "Die jüngste und die älteste Person spielen Schere, Stein, Papier. Wer verliert, trinkt 3 Schlucke.",
  "{{player}}, trink 1 Schluck und wähle jemanden, der 3 Schlucke trinkt. Diese Person wählt dann jemanden, der 2 Schlucke mehr trinkt, oder beendet die Kette.",
  "{{player}}, wer von {{player}} und {{player}} hört bei ernsten Themen besser zu? Die gewählte Person verteilt 3 Schlucke.",
  "{{player}}, mach einen Purzelbaum oder trink 5 Schlucke.",
  "{{player}}, such ein Lied aus. Alle singen es gemeinsam. Wer nicht mitsingt, trinkt 3 Schlucke.",
  "{{player}}, nenne 2 Eigenschaften, die du an der Person rechts von dir magst. Diese Person trinkt glücklich 2 Schlucke.",
  "Macht ein gemeinsames Selfie. Danach trinken alle 1 Schluck.",
  "{{player}}, erzähl einen Witz. Wer lacht, trinkt 2 Schlucke.",
  "{{player}} und {{player}}, macht Armdrücken. Wer verliert, trinkt 3 Schlucke.",
  "{{player}}, erzähl einen Fun Fact über dich. Alle anderen raten, ob er stimmt. Wer falsch liegt, trinkt 3 Schlucke.",
  "{{player}}, verteile 2 Schlucke, wenn du weißt, wo Amerikanisch-Samoa liegt. Sonst trink sie selbst.",
  "{{player}}, summe ein Lied. Wer es zuerst errät, verteilt 3 Schlucke. Errät es niemand, trinkst du 5 Schlucke.",
  "Alle stoßen an und trinken 2 Schlucke.",
];

export const curatedWildTasks: string[] = [
  "{{player}}, stell einer Person deiner Wahl eine Frage. Sie muss ehrlich antworten oder 5 Schlucke trinken.",
  "{{player}}, mach Kniebeugen. Für je 3 Kniebeugen verteilst du 1 Schluck, bei jeder 5. Kniebeuge trinkst du selbst 1 Schluck.",
  "{{player}}, trink 1 Schluck durch eine Socke oder trink 5 Schlucke.",
  "{{player}}, erzähl eine peinliche Geschichte über {{player}} oder trink 5 Schlucke.",
  "Wer als Erstes ein peinliches Partyfoto von sich auf dem Handy zeigt, verteilt 3 Schlucke.",
  "{{player}} und {{player}}, schüttet eure Getränke zusammen und trinkt jeweils die Hälfte.",
  "{{player}}, sag für die nächsten 5 Aufgaben vor jedem Schluck „Ich liebe meine Mutter und meinen Vater“. Vergisst du es, trink 2 Schlucke extra.",
  "{{player}}, lauf gackernd wie ein Huhn einmal um den Tisch oder trink 5 Schlucke.",
  "{{player}}, sing ein Lied vor oder trink 3 Schlucke.",
  "{{player}}, mach 20 saubere Liegestütze oder trink 3 Schlucke und mach 10 Hampelmänner.",
  "{{player}}, trink einen Shot vom schlimmsten Getränk, das gerade auf dem Tisch steht.",
  "{{player}}, roaste die Person rechts von dir in einem Satz. Lacht sie, trinkt sie 2 Schlucke, sonst trinkst du 2.",
  "Der Gastgeber wählt einen Spieler, der einen Shot nach Wahl des Gastgebers trinkt.",
  "Alle, die schon mal ein Klo verstopft haben, trinken 3 Schlucke.",
  "{{player}}, gieß {{player}} einen Schluck deines Getränks direkt in den Mund.",
  "{{player}}, trink die Hälfte deines Glases und gib die andere Hälfte einem Spieler deiner Wahl.",
  "Abstimmung: Lieber ein Date mit deinem Ex oder mit dem Ex deines besten Freundes? Die Minderheit trinkt 5 Schlucke.",
  "{{player}}, wie attraktiv findest du die Person dir gegenüber auf einer Skala von 1 bis 10? Trink so viele Schlucke, wie deine Zahl beträgt.",
  "{{player}}, ex dein Glas.",
  "Alle, die schon mal betrunken in der Schule waren, trinken 4 Schlucke.",
  "Abstimmung: Wer hat den Längeren... äh, die längere Ausdauer beim Trinken, {{player}} oder {{player}}? Wer weniger Stimmen bekommt, trinkt 5 Schlucke.",
];
