export const duellTasks: string[] = [
  '{{player}} gegen {{player}}: Schere, Stein, Papier, Best of 3. Wer verliert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Schere, Stein, Papier, nur eine Runde, alles oder nichts. Wer verliert, trinkt 5 Schlucke.',
  '{{player}} gegen {{player}} gegen {{player}}: Schere, Stein, Papier zu dritt, bis ein Verlierer feststeht. Der trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Schere, Stein, Papier, wer zuerst 5 Runden gewinnt. Der Gewinner verteilt 5 Schlucke.',
  '{{player}} gegen {{player}}: Daumenkrieg, Best of 3. Der Gewinner verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Daumenkrieg mit der linken Hand. Wer verliert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Blinzelduell. Wer zuerst blinzelt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Blinzelduell, und {{player}} darf Grimassen schneiden, um euch abzulenken. Wer zuerst blinzelt, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Armdrücken. Wer verliert, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Armdrücken mit der schwächeren Hand. Der Gewinner verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd hält einer die offene Hand hin und versucht, den Zeigefinger des anderen zu schnappen. Wer nach je 3 Versuchen seltener gefangen hat, trinkt 3 Schlucke.',
  '{{player}} lässt einen Stift fallen, {{player}} und {{player}} versuchen abwechselnd, ihn zu fangen. Wer zuerst danebengreift, trinkt 3 Schlucke.',

  '{{player}} gegen {{player}}: Schaut euch 30 Sekunden lang ernst in die Augen. Wer zuerst lacht, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Erzählt euch abwechselnd einen Flachwitz. Wer zuerst lacht, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Sagt abwechselnd mit todernster Miene das Wort "Wackelpudding". Wer zuerst grinst, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Schneidet abwechselnd eine Grimasse. Wer zuerst lacht, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Macht abwechselnd ein Tiergeräusch, der andere muss ernst bleiben. Wer zuerst lacht, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Singt euch mit Opernstimme gegenseitig ein Kompliment vor. Wer zuerst lacht, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Erzählt euch mit Nachrichtensprecherstimme, was ihr heute gefrühstückt habt. Wer zuerst lacht, trinkt 3 Schlucke.',
  '{{player}} versucht, {{player}} und {{player}} in 30 Sekunden zum Lachen zu bringen, ohne sie zu berühren. Wer von den beiden zuerst lacht, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Starrt euch an und sagt dabei ganz langsam gemeinsam das Alphabet auf. Wer zuerst lacht, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Macht abwechselnd euer bestes Bösewichtlachen. Wer dabei zuerst richtig lachen muss, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Flüstert euch abwechselnd ein erfundenes Geheimnis über Kartoffeln zu. Wer zuerst kichert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Die Runde darf 20 Sekunden lang alles tun, um euch zum Lachen zu bringen, ohne euch anzufassen. Wer zuerst lacht, trinkt 4 Schlucke.',

  '{{player}} gegen {{player}}: Wer länger auf einem Bein steht, verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Auf einem Bein stehen mit geschlossenen Augen. Wer zuerst den zweiten Fuß absetzt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Streckt einen Arm waagerecht nach vorne. Wer ihn zuerst sinken lässt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer einen Löffel länger auf der Nase balanciert, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wandsitzen mit dem Rücken an der Wand. Wer zuerst aufsteht, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Wer in 20 Sekunden mehr Kniebeugen schafft, verteilt 3 Schlucke. {{player}} zählt mit.',
  '{{player}} gegen {{player}}: Wer länger einen Ton summen kann, ohne Luft zu holen, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Dreht gleichzeitig eine Münze auf dem Tisch. Wessen Münze länger kreiselt, der verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer einen Stift länger senkrecht auf einem Finger balanciert, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Schätzt mit geschlossenen Augen 30 Sekunden ab, {{player}} stoppt die Zeit. Wer weiter danebenliegt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer länger auf Zehenspitzen stehen kann, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Setzt euch hin und hebt beide Füße vom Boden. Wer sie zuerst absetzt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer in 15 Sekunden mehr Hampelmänner schafft, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer in 10 Sekunden öfter mit den Fingern schnipst, verteilt 2 Schlucke. {{player}} zählt.',
  '{{player}} gegen {{player}}: Klopft euch mit einer Hand auf den Kopf und reibt mit der anderen den Bauch. Wer zuerst durcheinanderkommt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer die Liegestützposition länger halten kann, verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Schließt die Augen und tippt euch je 3 Mal mit dem Zeigefinger auf die Nasenspitze. Wer öfter danebentippt, trinkt 3 Schlucke.',

  '{{player}} gegen {{player}}: Legt einen Gegenstand zwischen euch. Sobald {{player}} "Jetzt" ruft, greift zu. Wer ihn zuerst hat, verteilt 3 Schlucke.',
  '{{player}} klatscht irgendwann in die Hände. Wer von {{player}} und {{player}} danach zuerst die eigene Nase berührt, verteilt 3 Schlucke.',
  '{{player}} sagt wahllos Wörter. Sobald das Wort "Pizza" fällt, springen {{player}} und {{player}} auf. Wer langsamer ist, trinkt 3 Schlucke.',
  '{{player}} ruft Tiere und Farben durcheinander. {{player}} und {{player}} heben nur bei Farben ihr Glas. Wer zuerst einen Fehler macht, trinkt 3 Schlucke.',
  '{{player}} ruft Körperteile, {{player}} und {{player}} zeigen so schnell wie möglich darauf. Wer zuerst falsch zeigt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: "Kopf, Schulter, Knie und Fuß" in immer schnellerem Tempo. Wer zuerst danebengreift, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer schneller von 30 rückwärts bis 0 zählt, ohne sich zu vertun, verteilt 3 Schlucke.',
  '{{player}} spielt "Simon sagt" mit {{player}} und {{player}}. Wer zuerst einen Befehl ohne "Simon sagt" ausführt, trinkt 3 Schlucke.',
  '{{player}} sagt Zahlen, {{player}} und {{player}} klopfen nur bei geraden Zahlen auf den Tisch. Wer sich zuerst vertut, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Zählt abwechselnd hoch und sagt statt jeder Zahl mit einer 7 oder durch 7 teilbar "Buzz". Wer sich zuerst vertut, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Zählt abwechselnd auf Englisch hoch, immer schneller. Wer zuerst stockt oder sich verzählt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer zuerst das Handy entsperrt und die Taschenlampe angeschaltet hat, verteilt 2 Schlucke.',
  '{{player}} ruft irgendwann "Prost". Wer von {{player}} und {{player}} zuletzt sein Glas hebt, trinkt 2 Schlucke.',

  '{{player}} gegen {{player}}: Nennt abwechselnd Automarken. Wer zögert oder etwas wiederholt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Länder in Europa. Wem keins mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Disney-Figuren nennen. Wer hängen bleibt, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Biermarken. Wer zuerst passen muss, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Obstsorten. Wer zuerst nichts mehr weiß, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Gemüsesorten. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Hauptstädte der Welt. Wer zögert, trinkt 3 Schlucke, der Gewinner verteilt zusätzlich 2.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Fußballvereine. Wer keinen mehr weiß, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, zählt abwechselnd Sportarten auf. Der Gewinner verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Tiere, die mit S anfangen. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Musikinstrumente. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Pokémon nennen. Wem keins mehr einfällt, trinkt 4 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Figuren aus Harry Potter. Wer hängen bleibt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Figuren aus den Simpsons. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Superhelden. Der Gewinner verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Pizzabeläge. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Cocktails. Wem keiner mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Käsesorten. Wer zuerst passen muss, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Berufe. Wer zögert oder wiederholt, trinkt 2 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Hunderassen. Wer keine mehr weiß, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, zählt abwechselnd Brettspiele auf. Der Gewinner verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Serien nennen. Wer zuerst stockt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Süßigkeiten. Wem nichts mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd deutsche Städte. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Gewürze. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Vogelarten. Wer keine mehr weiß, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Fische und Meerestiere. Der Gewinner verteilt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Dinge, die man in einer Küche findet. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Rapper nennen. Wem keiner mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Länder in Afrika. Wer zuerst nicht weiterweiß, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Vornamen, die mit M beginnen. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Getränke ohne Alkohol. Wer hängen bleibt, trinkt 3 Schlucke Alkoholisches.',
  '{{player}} gegen {{player}}: Abwechselnd Dinge, die man am Strand findet. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Videospiele. Der Gewinner verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Märchen nennen. Wem keins mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Eissorten. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Filmtitel, in denen eine Zahl vorkommt. Wer hängen bleibt, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Hauptstädte in Südamerika. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Schauspielerinnen und Schauspieler aus Hollywood. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Gerichte aus Italien. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Wörter für "betrunken". Wem keins mehr einfällt, trinkt 3 Schlucke.',

  '{{player}} gegen {{player}}: Wortkette, jedes Wort beginnt mit dem letzten Buchstaben des vorherigen. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Bildet abwechselnd eine Kette wie Haustür, Türschloss, Schlossgarten. Wer hängen bleibt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: "Ich packe meinen Koffer", ihr wiederholt abwechselnd alles und fügt etwas hinzu. Wer zuerst etwas vergisst, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Reimt abwechselnd auf "Haus". Wer keinen Reim mehr findet, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer in 30 Sekunden mehr Wörter findet, die sich auf "Nacht" reimen, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Wörter, die mit "Bier" anfangen. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Wörter, die auf "ung" enden. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer in 20 Sekunden mehr Wörter mit Q nennt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Bildet je einen Satz, in dem jedes Wort mit B beginnt. Die Runde kürt den besseren, der Verlierer trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Erzählt gemeinsam eine Geschichte, jeder sagt abwechselnd nur ein Wort. Wer zuerst zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Erzählt abwechselnd 30 Sekunden von eurem Lieblingsessen, ohne "äh" oder "ähm" zu sagen. Wer es zuerst sagt, trinkt 3 Schlucke.',
  '{{player}} stellt {{player}} und {{player}} abwechselnd schnelle Fragen. Wer zuerst "Ja" oder "Nein" sagt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Unterhaltet euch nur in Fragen. Wer zuerst etwas sagt, das keine Frage ist, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Führt ein Gespräch, in dem jeder Satz mit dem nächsten Buchstaben des Alphabets beginnt, angefangen bei A. Wer stockt, trinkt 3 Schlucke.',
  '{{player}} nennt Wörter, {{player}} und {{player}} rufen so schnell wie möglich das Gegenteil. Wer zuerst 3 Mal schneller war, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer zuerst ein Wort mit drei gleichen Buchstaben hintereinander nennt, zum Beispiel Schifffahrt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer das längere echte Wort nennt, verteilt 3 Schlucke. Die Runde entscheidet, ob es zählt.',
  '{{player}} flüstert {{player}} und {{player}} je einen Begriff zu. Erklärt ihn der Runde, ohne das Wort zu sagen. Wessen Begriff schneller erraten wird, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Unterhaltet euch 30 Sekunden, ohne das Wort "ich" zu benutzen. Wer es zuerst sagt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Sprecht abwechselnd einen Satz, in dem kein einziges A vorkommt. Wer zuerst eins sagt oder zögert, trinkt 3 Schlucke.',

  '{{player}} gegen {{player}}: Sagt dreimal schnell "Fischers Fritz fischt frische Fische". Wer sich mehr verhaspelt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Sagt dreimal schnell "Blaukraut bleibt Blaukraut und Brautkleid bleibt Brautkleid". Die Runde bestimmt den Verlierer, der trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer "Zwischen zwei Zwetschgenzweigen zwitschern zwei Schwalben" schneller fehlerfrei sagt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Zungenbrecher "Der Cottbuser Postkutscher putzt den Cottbuser Postkutschkasten" dreimal hintereinander. Wer patzt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer "Hinter Hermanns Hannes Haus hängen hundert Hemden raus" schneller schafft, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Sagt "Esel essen Nesseln nicht, Nesseln essen Esel nicht" so schnell ihr könnt. Wer sich verspricht, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer "Am zehnten Zehnten um zehn Uhr zehn zogen zehn zahme Ziegen zehn Zentner Zucker zum Zoo" fehlerfrei sagt, verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Sagt fünfmal schnell "Rhabarberbarbara". Wer sich zuerst verhaspelt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Zungenbrecher "Wenn Fliegen hinter Fliegen fliegen, fliegen Fliegen Fliegen nach". Die Runde kürt den Verlierer, der trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer "Acht alte Ameisen aßen am Abend Ananas" fünfmal schneller fehlerfrei sagt, verteilt 3 Schlucke.',

  '{{player}} gegen {{player}}: Wer das Alphabet schneller rückwärts aufsagt, verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Sagt die Monate rückwärts auf, von Dezember bis Januar. Wer langsamer ist oder patzt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Die Wochentage auf Englisch rückwärts. Wer zuerst fertig ist, verteilt 2 Schlucke.',
  '{{player}} gegen {{player}}: Buchstabiert euren eigenen Vornamen rückwärts, so schnell ihr könnt. Wer langsamer ist, trinkt 2 Schlucke.',
  '{{player}} gegen {{player}}: Wer zuerst "Rhythmus" richtig buchstabiert, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer die 7er-Reihe schneller bis 70 aufsagt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer in 30 Sekunden mehr Bundesländer aufzählt, verteilt 3 Schlucke. Es gibt 16.',
  '{{player}} gegen {{player}}: Wer zuerst alle 8 Planeten in der richtigen Reihenfolge von der Sonne aus nennt, verteilt 4 Schlucke. Die Runde prüft mit.',
  '{{player}} gegen {{player}}: Wer zuerst "Donaudampfschifffahrt" fehlerfrei buchstabiert, verteilt 3 Schlucke.',

  '{{player}} gegen {{player}}: Wer mehr Songs von Helene Fischer nennen kann, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Songs von Queen. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer mehr Lieder von ABBA kennt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Songs von Michael Jackson. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer mehr Songs von Ed Sheeran nennt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Songs von Taylor Swift. Wem keiner mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer mehr Lieder von Die Ärzte kennt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Songs von den Toten Hosen. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer mehr Songs von den Beatles aufzählt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Songs von Rihanna. Wer hängen bleibt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Songs von Rammstein. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} summt ein Lied, {{player}} und {{player}} raten. Wer es zuerst errät, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Singt abwechselnd eine Zeile aus einem Lied, in dessen Titel eine Farbe vorkommt. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Singt abwechselnd eine Zeile aus einem Weihnachtslied. Wem keins mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer mehr Lieder mit "Liebe" oder "Love" im Titel nennt, verteilt 3 Schlucke.',

  '{{player}} gegen {{player}}: Wer zuerst die Hauptstadt von Australien nennt, verteilt 3 Schlucke. {{player}} prüft am Handy nach.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Länder, die an Deutschland grenzen. Wer zuerst passt oder sich irrt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer mehr Landeshauptstädte nennt, verteilt 3 Schlucke. {{player}} prüft am Handy nach.',
  '{{player}} gegen {{player}}: Wer mehr Bundeskanzlerinnen und Bundeskanzler nennt, verteilt 3 Schlucke. {{player}} prüft am Handy nach.',
  '{{player}} sucht im Handy eine Quizfrage heraus und liest sie vor. Wer von {{player}} und {{player}} zuerst richtig antwortet, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Schätzt, wie hoch der Kölner Dom ist. {{player}} schaut im Handy nach, wer weiter danebenliegt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Schätzt, in welchem Jahr das erste iPhone erschienen ist. {{player}} schaut im Handy nach, wer näher dran ist, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Ratet, wie viele Kontakte {{player}} im Handy hat. Die Person schaut nach, wer näher dran ist, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Ratet, wie viele ungelesene Nachrichten {{player}} gerade hat. Die Person schaut nach, wer weiter danebenliegt, trinkt 3 Schlucke.',

  '{{player}} gegen {{player}}: Nennt abwechselnd Schuhmarken. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Kleidungsstücke. Wer zögert oder wiederholt, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Werkzeuge. Wem keins mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Dinosaurier nennen. Wer hängen bleibt, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Insekten. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Baumarten. Wem keine mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Blumen. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Möbelstücke. Wer zuerst nichts mehr weiß, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Wintersportarten. Der Gewinner verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Fahrzeuge, aber keine Automarken. Wer stockt, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Apps auf euren Handys, ohne nachzuschauen. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Nudelsorten. Wer hängen bleibt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Dinge, die rund sind. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Länder in Asien. Wem keins mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Inseln. Wer zuerst passt, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Flüsse. Wer keinen mehr weiß, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd deutsche Bands. Wer zuerst stockt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Brotsorten und Backwaren. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Dinge, die man im Badezimmer findet. Wer hängen bleibt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Filmtitel, in denen ein Tier vorkommt. Wer zuerst passt, trinkt 4 Schlucke.',

  'Stadt, Land, Fluss: {{player}} nennt einen Buchstaben. Wer von {{player}} und {{player}} zuerst eine Stadt, ein Land und einen Fluss damit sagt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Teekesselchen, also Wörter mit zwei Bedeutungen wie Bank oder Schloss. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd englische Wörter, die man im Deutschen ständig benutzt. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Sprichwörter. Wer eins falsch zusammensetzt oder passen muss, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wortkette mit Vornamen, jeder neue Name beginnt mit dem letzten Buchstaben des vorherigen. Wer stockt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wortkette mit Essen und Getränken, jedes Wort beginnt mit dem letzten Buchstaben des vorherigen. Wer hängen bleibt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Wörter, die mit "Sch" anfangen. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd Wörter mit genau 3 Buchstaben. Wer zögert, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Reimt abwechselnd auf "Herz". Wem kein Reim mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt abwechselnd Wörter, in denen "ei" vorkommt. Wer stockt, trinkt 2 Schlucke.',
  '{{player}} gegen {{player}}: Abwechselnd zusammengesetzte Wörter mit "Feuer", wie Feuerwehr. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Beschreibt {{player}} abwechselnd mit einem netten Adjektiv. Wem zuerst keins mehr einfällt, trinkt 3 Schlucke.',
  '{{player}} nennt einen Buchstaben. {{player}} und {{player}} nennen abwechselnd Tiere mit diesem Anfangsbuchstaben. Wer zuerst passt, trinkt 3 Schlucke.',

  '{{player}} gegen {{player}}: Wer schneller ein Selfie macht, auf dem alle am Tisch zu sehen sind, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer zuerst ein Foto von einem Hund auf dem Handy findet, verteilt 2 Schlucke.',
  '{{player}} gegen {{player}}: Wer zuerst 3 runde Dinge im Raum zeigt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Fingerhakeln mit den Zeigefingern. Wer den anderen zu sich herüberzieht, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer länger die Luft anhält, verteilt 3 Schlucke. {{player}} stoppt die Zeit.',
  '{{player}} gegen {{player}}: Legt euch eine Serviette auf den Kopf und nickt 10 Mal. Wem sie zuerst herunterfällt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Baut abwechselnd einen Turm aus Gegenständen vom Tisch. Wer ihn zum Einsturz bringt, trinkt 4 Schlucke.',
  '{{player}} gegen {{player}}: Haltet euer Glas mit ausgestrecktem Arm vor euch. Wer zuerst den Arm sinken lässt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Sagt gleichzeitig das Alphabet auf, einer vorwärts, einer rückwärts. Wer zuerst stockt, trinkt 3 Schlucke.',
  '{{player}} klopft einen Rhythmus auf den Tisch. {{player}} und {{player}} klopfen ihn nach, und er wird jedes Mal länger. Wer zuerst danebenliegt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Schließt die Augen. Nacheinander sagen 3 Leute aus der Runde mit verstellter Stimme "Prost". Wer mehr Stimmen richtig erkennt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Schließt die Augen. Die Runde reicht euch nacheinander 3 Hände. Wer mehr Hände der richtigen Person zuordnet, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer mehr Nachnamen der Leute am Tisch kennt, verteilt 3 Schlucke. Die Runde bestätigt.',
  '{{player}} gegen {{player}}: Wer mehr Lieblingsgetränke der Leute am Tisch richtig nennt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Balanciert einen Bierdeckel auf dem Handrücken, steht auf und setzt euch wieder. Wem er herunterfällt, trinkt 3 Schlucke.',
  '{{player}} ruft Zahlen zwischen 1 und 5. {{player}} und {{player}} klatschen genau so oft. Wer sich zuerst vertut, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Einer macht 20 Sekunden lang Bewegungen vor, der andere spiegelt sie, dann wird getauscht. Wer schlechter gespiegelt hat, trinkt 3 Schlucke. Die Runde entscheidet.',
  '{{player}} gegen {{player}}: Zeichnet mit geschlossenen Augen ein Gesicht auf dem Handy. Die Runde kürt das schlechtere Bild, und wer es gemalt hat, trinkt 3 Schlucke.',

  '{{player}} gegen {{player}}: Imitiert einen Hund, der gerade einen Ball entdeckt. Die Runde stimmt ab, der Verlierer trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Spielt einen Kellner, der jede Bestellung falsch versteht. Wer die Runde mehr zum Lachen bringt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Präsentiert ein Gericht wie in einer Kochshow, nur mit Gegenständen vom Tisch. Die Runde kürt den Sieger, der verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Macht einem Stuhl einen Heiratsantrag. Wer weniger überzeugt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Imitiert abwechselnd einen Promi. Wessen Promi die Runde schneller errät, der verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Imitiert je eine Person aus der Runde, ohne den Namen zu sagen. Wer schneller erraten wird, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Fragt als Touristen in einer erfundenen Sprache nach dem Weg zum Bahnhof. Die Runde stimmt ab, der Verlierer trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Haltet eine kurze Trauerrede auf ein leeres Glas. Wer die Runde mehr rührt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Singt "Alle meine Entchen" als Heavy-Metal-Song. Wer weniger überzeugt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Rappt 4 Zeilen über euer Lieblingsessen. Die Runde kürt den Sieger, der verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Spielt in 15 Sekunden eine Telenovela-Szene, in der jemand den Autoschlüssel verloren hat. Wer dramatischer war, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Macht das Geräusch eines alten Modems beim Einwählen. Die Runde entscheidet, wer echter klingt, der Verlierer trinkt 2 Schlucke.',
  '{{player}} gegen {{player}}: Spielt einen Zauberer, dessen Trick komplett schiefgeht. Wer die Runde mehr zum Lachen bringt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Zeigt, wie ein Baby zum ersten Mal in eine Zitrone beißt. Wer weniger überzeugt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Erklärt in 20 Sekunden, warum ausgerechnet ihr heute Abend einen Pokal verdient. Die Runde stimmt ab, der Verlierer trinkt 3 Schlucke.',

  '{{player}} gegen {{player}}: Schätzt, wie viele Gläser gerade auf dem Tisch stehen, ohne zu zählen. {{player}} zählt nach, wer weiter danebenliegt, trinkt 2 Schlucke.',
  '{{player}} gegen {{player}}: Schätzt, wie viele Schritte es von hier bis zur Tür sind. {{player}} läuft nach, wer weiter danebenliegt, trinkt 3 Schlucke.',
  '{{player}} denkt sich eine Zahl zwischen 1 und 50. Wer von {{player}} und {{player}} näher dran tippt, verteilt 3 Schlucke.',

  '{{player}} gegen {{player}}: Stellt abwechselnd ein Tier pantomimisch dar. Wessen Tier die Runde schneller errät, der verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Stellt je einen Filmtitel pantomimisch dar. Wer zuerst erraten wird, verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Pantomime mit Berufen. Wessen Beruf länger unerraten bleibt, der trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Stellt abwechselnd eine Sportart pantomimisch dar. Wer schneller erraten wird, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Stellt je ein Haushaltsgerät pantomimisch dar. Die Runde stimmt ab, wer überzeugender war, der Verlierer trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Spielt je ein Märchen pantomimisch vor. Wessen Märchen zuerst erraten wird, der verteilt 3 Schlucke.',
  '{{player}} flüstert {{player}} und {{player}} denselben Begriff zu. Beide stellen ihn gleichzeitig pantomimisch dar, wer zuerst erraten wird, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Stellt pantomimisch dar, wie ihr morgens aufsteht. Die Runde stimmt ab, wer lustiger war, und der verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Zeichnet in 30 Sekunden ein Pferd auf dem Handy. Die Runde stimmt ab, wer schlechter gezeichnet hat, und der trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Spielt pantomimisch vor, wie ihr ein Geschenk auspackt, das ihr nicht mögt. Wer überzeugender ist, verteilt 3 Schlucke.',

  '{{player}} gegen {{player}}: Imitiert beide einen Hahn am Morgen. Die Runde stimmt ab, wer schlechter war, und der trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Kommentiert die letzte Minute eines WM-Finales wie ein Fußballreporter. Die Runde kürt den Gewinner, der verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Bewegt euch 10 Sekunden wie ein Roboter. Wer weniger überzeugt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Moderiert den Wetterbericht für morgen. Die Runde stimmt ab, der Verlierer trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Sprecht wie ein Navi den Weg zur Küche. Wer besser klingt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Macht eine Bahnhofsdurchsage für einen verspäteten Zug. Die Runde wählt die bessere, der Gewinner verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Beschreibt wie ein Tierfilmsprecher, was {{player}} gerade tut. Die Runde stimmt ab, wer besser war, der verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Singt eure Einkaufsliste als Schlager. Wer weniger überzeugt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Macht eine Pilotendurchsage vor dem Landeanflug. Die Runde kürt die beste, der Verlierer trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Brüllt wie ein Dinosaurier. Die Runde entscheidet, wer furchteinflößender war, und der verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Imitiert eine Katze, die unbedingt Futter will. Wer schlechter ist, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Lauft wie Models über einen Laufsteg einmal um den Tisch. Die Runde wählt den Sieger, der verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Zeigt euren besten Torjubel in Zeitlupe. Wer weniger überzeugt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Dreht einen 15 Sekunden langen Werbespot für Leitungswasser. Die Runde stimmt ab, der Gewinner verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Kommentiert ein Curlingspiel so spannend wie möglich. Wer weniger spannend war, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Macht das Geräusch eines startenden Motorrads. Die Runde kürt das bessere, der Verlierer trinkt 2 Schlucke.',
  '{{player}} gegen {{player}}: Imitiert einen Seehund. Wer echter klingt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Haltet 15 Sekunden lang eine Rede als Motivationstrainer. Wer die Runde mehr mitreißt, verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Kündigt euch gegenseitig an wie ein Boxkampfsprecher. Die Runde stimmt ab, wer lauter und besser war, der verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Verkauft der Runde in 20 Sekunden einen Kugelschreiber. Wer weniger überzeugt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Erfindet die beste Ausrede, warum ihr zu spät zur Party kommt. Die Runde stimmt ab, der Verlierer trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Erfindet einen Namen für einen neuen Cocktail. Die Runde wählt den besseren, und der Gewinner verteilt 3 Schlucke.',

  'Die Runde stimmt ab: Wer von {{player}} und {{player}} würde eher einen Marathon laufen? Wer mehr Stimmen bekommt, verteilt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} tanzt besser? Der Gewinner verteilt 3 Schlucke, der andere trinkt 2.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} kocht besser? Wer weniger Stimmen hat, trinkt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} hat das bessere Pokerface? Der Gewinner verteilt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} würde länger in einer Zombieapokalypse überleben? Wer verliert, trinkt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} wird eher berühmt? Wer mehr Stimmen bekommt, verteilt 4 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} würde eher eine Quizshow gewinnen? Der Gewinner verteilt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} hat das ansteckendere Lachen? Wer mehr Stimmen hat, verteilt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} kommt schneller aus einem Escape Room? Wer verliert, trinkt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} greift beim Karaoke zuerst zum Mikrofon? Wer mehr Stimmen bekommt, trinkt 2 Schlucke und verteilt 2.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} würde auf einer einsamen Insel länger durchhalten? Der Gewinner verteilt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} findet sich ohne Navi besser zurecht? Wer weniger Stimmen hat, trinkt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} erzählt die besseren Witze? Der Gewinner verteilt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} wäre der bessere Reiseleiter? Wer verliert, trinkt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} ist als Erstes auf der Tanzfläche? Wer mehr Stimmen bekommt, verteilt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} hätte als Superheld die cooleren Kräfte? Wer weniger Stimmen hat, trinkt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} würde eher eine Band gründen? Wer mehr Stimmen bekommt, verteilt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} kann besser ein Geheimnis für sich behalten? Der Gewinner verteilt 4 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} hätte als Bürgermeister die besseren Ideen? Wer verliert, trinkt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} hat den besseren Musikgeschmack? Der Gewinner verteilt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} würde den besseren Geheimagenten abgeben? Wer weniger Stimmen bekommt, trinkt 3 Schlucke.',
  'Die Runde stimmt ab: Wer von {{player}} und {{player}} plant die bessere Party? Der Gewinner verteilt 4 Schlucke.',

  '{{player}} gegen {{player}}: Wer gerade den höheren Akkustand hat, verteilt 2 Schlucke.',
  '{{player}} gegen {{player}}: Vergleicht eure Bildschirmzeit von gestern. Wer mehr hat, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer schneller "Heute ist ein wunderschöner Abend" fehlerfrei ins Handy tippt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer zuerst 5 rote Dinge im Raum zeigt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Sagt die Augenfarbe des anderen, ohne hinzusehen. Wer falsch liegt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer mehr Geburtstage der Leute am Tisch richtig nennt, verteilt 4 Schlucke.',
  '{{player}} gegen {{player}}: Beschreibt euren perfekten Sonntag in genau 5 Wörtern. Die Runde wählt den schöneren, der Gewinner verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer zuerst einen Gegenstand aus der eigenen Tasche zeigt, der mit K anfängt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer zuerst errät, wie viele Finger {{player}} hinter dem Rücken ausstreckt, verteilt 2 Schlucke. Best of 3.',
  '{{player}} gegen {{player}}: Wer schneller 3 Schlucke trinkt und das Glas wieder abstellt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Nennt gleichzeitig eine Zahl zwischen 1 und 10. Wer näher an der Zahl liegt, die {{player}} sich ausgedacht hat, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer sich mehr Gegenstände merkt, die {{player}} langsam aufzählt (10 Stück), verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Schaut euch 10 Sekunden lang den Tisch an, dann schließt ihr die Augen und {{player}} nimmt etwas weg. Wer zuerst sagt, was fehlt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}}: Wer zuerst ein Lied mit einem Tier im Titel singt, verteilt 3 Schlucke.',
  '{{player}} gegen {{player}} gegen {{player}}: Wer am längsten auf einem Bein steht und dabei ein Lied singt, verteilt 4 Schlucke.',
  '{{player}} gegen {{player}} gegen {{player}}: Abwechselnd Länder mit dem Anfangsbuchstaben B. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}} gegen {{player}}: Blinzelduell zu dritt. Wer zuerst blinzelt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}} gegen {{player}}: Nennt abwechselnd Dinge, die grün sind. Wer zuerst passt, trinkt 3 Schlucke.',
  '{{player}} gegen {{player}} gegen {{player}}: Wortkette mit Tieren, jedes neue Tier beginnt mit dem letzten Buchstaben des vorherigen. Wer stockt, trinkt 3 Schlucke.',
];
