export const normalTasks: string[] = [
  // Einzelaufgaben
  '{{player}}, erzähl einen Witz. Lacht mindestens eine Person, verteilst du 3 Schlucke, sonst trinkst du 2.',
  '{{player}}, sag das Alphabet rückwärts bis zum Buchstaben M oder trink 3 Schlucke.',
  '{{player}}, nenne 5 Länder, die mit A anfangen, in 15 Sekunden. Schaffst du es, verteilst du 3 Schlucke, sonst trinkst du 3.',
  '{{player}}, mach 10 Kniebeugen oder trink 3 Schlucke.',
  '{{player}}, sing den Refrain deines Lieblingssongs. Danach verteilst du 2 Schlucke.',
  '{{player}}, imitiere einen Nachrichtensprecher, der das Wetter von morgen ansagt, oder trink 2 Schlucke.',
  '{{player}}, sprich für die nächsten 3 Aufgaben nur noch im Flüsterton. Jedes Mal, wenn du laut wirst, trinkst du 1 Schluck.',
  '{{player}}, mach ein Kompliment an jede Person in der Runde. Danach darfst du 3 Schlucke verteilen.',
  '{{player}}, balanciere 10 Sekunden auf einem Bein mit geschlossenen Augen. Klappt es nicht, trinkst du 2 Schlucke.',
  '{{player}}, zähl in 10 Sekunden 6 Tiere mit vier Beinen auf oder trink 2 Schlucke.',
  '{{player}}, sag einen Zungenbrecher dreimal fehlerfrei: Fischers Fritz fischt frische Fische. Verhaspelst du dich, trinkst du 2 Schlucke.',
  '{{player}}, erzähl in einem Satz, was du heute gegessen hast, aber wie ein Sternekoch. Danach verteilst du 2 Schlucke.',
  '{{player}}, verrate dein peinlichstes Lieblingslied oder trink 3 Schlucke.',
  '{{player}}, beschreibe deinen Morgen nur mit Geräuschen. Wer zuerst errät, was du machst, verteilt 2 Schlucke.',
  '{{player}}, trink 2 Schlucke und such dir dann einen Trinkbuddy aus, der für die nächsten 3 Aufgaben immer mittrinkt, wenn du trinkst.',
  '{{player}}, verteile 4 Schlucke beliebig in der Runde.',
  '{{player}}, trink so viele Schlucke, wie dein Vorname Silben hat.',
  '{{player}}, sprich 1 Minute lang mit einem Akzent deiner Wahl. Rutscht er dir weg, trinkst du 2 Schlucke.',
  '{{player}}, nenne 3 Dinge, die gerade in deiner Hosentasche oder Tasche sind, ohne nachzusehen. Liegst du daneben, trinkst du 2 Schlucke.',
  '{{player}}, mach deine beste Roboterbewegung für 10 Sekunden oder trink 3 Schlucke.',
  '{{player}}, erfinde einen Werbeslogan für das Getränk in deiner Hand. Gefällt er der Runde, verteilst du 3 Schlucke.',
  '{{player}}, rede für die nächsten 3 Aufgaben von dir nur in der dritten Person. Jeder Patzer kostet 1 Schluck.',
  '{{player}}, imitiere ein Tier deiner Wahl. Errät die Runde es in 10 Sekunden, verteilst du 2 Schlucke, sonst trinkst du 2.',
  '{{player}}, wenn du Geschwister hast, verteilst du 2 Schlucke, sonst trinkst du 2.',
  '{{player}}, sag 10 Sekunden lang nur Wörter mit B, ohne zu stocken, oder trink 2 Schlucke.',
  '{{player}}, verrate, welche Serie du zuletzt gesuchtet hast, oder trink 2 Schlucke.',
  '{{player}}, mach einen Hampelmann 10 Mal hintereinander oder trink 3 Schlucke.',
  '{{player}}, halte für 1 Minute eine Hand über dem Kopf. Nimmst du sie runter, trinkst du 3 Schlucke.',
  '{{player}}, sing Alle meine Entchen wie ein Opernstar oder trink 3 Schlucke.',
  '{{player}}, erzähle deine Lieblingsanekdote aus der Schulzeit in 30 Sekunden oder trink 3 Schlucke.',
  '{{player}}, dichte einen Zweizeiler über dein Getränk. Reimt er sich, verteilst du 2 Schlucke.',
  '{{player}}, beschreibe deinen Traumurlaub in drei Wörtern. Danach trinken alle, die mitkommen würden, 1 Schluck.',
  '{{player}}, sag zu jedem Spieler ein Wort, das ihn gut beschreibt. Danach verteilst du 2 Schlucke.',
  '{{player}}, rate die Uhrzeit auf die Minute genau, ohne nachzusehen. Liegst du mehr als 10 Minuten daneben, trinkst du 2 Schlucke.',
  '{{player}}, wenn du schon mal einen Kuchen selbst gebacken hast, verteilst du 2 Schlucke.',
  '{{player}}, erzähl in 20 Sekunden, warum Montag eigentlich der beste Tag der Woche ist. Überzeugst du die Runde, verteilst du 3 Schlucke.',
  '{{player}}, mach 5 Liegestütze oder trink 3 Schlucke.',
  '{{player}}, trink für die nächsten 3 Aufgaben nur mit deiner schwächeren Hand. Erwischt dich jemand, trinkst du 2 Schlucke extra.',
  '{{player}}, imitiere einen Fußballkommentator, der beschreibt, wie jemand sein Glas hebt. Danach verteilst du 2 Schlucke.',
  '{{player}}, nenne deinen absoluten Lieblingsfilm. Alle, die ihn auch lieben, trinken mit dir 1 Schluck.',
  '{{player}}, wenn du schon mal bei einem Konzert in der ersten Reihe standest, verteilst du 3 Schlucke.',
  '{{player}}, wenn du ein Haustier hast, zeig der Runde ein Foto davon und verteile 2 Schlucke. Sonst trinkst du 1.',
  '{{player}}, erzähl, was du mit einer Million Euro als Erstes kaufen würdest. Die Runde stimmt ab, ob es gut ist. Wenn nicht, trinkst du 2 Schlucke.',
  '{{player}}, nenne 4 Pizzabeläge in 5 Sekunden oder trink 2 Schlucke.',
  '{{player}}, dein Glas ist jetzt dein Mikrofon. Halte eine kurze Dankesrede für einen Preis, den du dir ausdenkst. Danach verteilst du 3 Schlucke.',
  '{{player}}, wenn du heute schon Sport gemacht hast, verteilst du 3 Schlucke, sonst trinkst du 1.',
  '{{player}}, lass die Runde ein Wort aussuchen, das du in deinen nächsten Satz einbauen musst. Schaffst du es nicht, trinkst du 2 Schlucke.',
  '{{player}}, halte 20 Sekunden Augenkontakt mit der Person rechts von dir. Wer zuerst lacht, trinkt 2 Schlucke.',
  '{{player}}, wenn du schon mal einen Pokal oder eine Medaille gewonnen hast, verteilst du 3 Schlucke.',

  // Zwei Spieler
  '{{player}} und {{player}}, Schere Stein Papier. Wer verliert, trinkt 2 Schlucke.',
  '{{player}} und {{player}}, Daumenkrieg. Der Verlierer trinkt 3 Schlucke.',
  '{{player}} und {{player}}, Blinzelduell. Wer zuerst blinzelt, trinkt 2 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Automarken. Wer zuerst keine mehr weiß, trinkt 3 Schlucke.',
  '{{player}} und {{player}}, stoßt an und trinkt beide 2 Schlucke.',
  '{{player}} und {{player}}, ihr seid für die nächsten 3 Aufgaben Trinkpartner. Trinkt einer, trinkt der andere mit.',
  '{{player}} und {{player}}, wer zuerst 3 Gemüsesorten mit K nennt, verteilt 2 Schlucke.',
  '{{player}}, imitiere {{player}} so gut du kannst. Lacht die Runde, verteilst du 3 Schlucke.',
  '{{player}} und {{player}}, wer hat die größeren Hände? Haltet sie aneinander. Die kleinere Hand trinkt 2 Schlucke.',
  '{{player}} und {{player}}, nennt gleichzeitig eine Farbe. Sagt ihr dieselbe, verteilt ihr je 3 Schlucke, sonst trinkt ihr je 1.',
  '{{player}}, errate das Lieblingsessen von {{player}}. Liegst du richtig, verteilst du 3 Schlucke, sonst trinkst du 2.',
  '{{player}} und {{player}}, starrt euch an, ohne zu lachen. Wer zuerst lacht, trinkt 3 Schlucke.',
  '{{player}}, gib {{player}} ein ehrliches Kompliment. Danach trinkt ihr beide 1 Schluck.',
  '{{player}} und {{player}}, wer hat heute mehr Schritte gemacht? Schaut nach. Der Faulere trinkt 2 Schlucke.',
  '{{player}}, rate den Geburtsmonat von {{player}}. Falsch geraten heißt 2 Schlucke für dich.',
  '{{player}} und {{player}}, macht gleichzeitig eine Pose. Die Runde wählt die bessere. Der andere trinkt 2 Schlucke.',
  '{{player}}, wie viele Geschwister hat {{player}}? Falsch geraten, trinkst du 2 Schlucke.',
  '{{player}} und {{player}}, nennt abwechselnd Hauptstädte in Europa. Wer zuerst keine mehr weiß, trinkt 3 Schlucke.',
  '{{player}}, beschreibe {{player}} in drei Wörtern. Gefallen sie der beschriebenen Person nicht, trinkst du 2 Schlucke.',
  '{{player}} und {{player}}, macht ein Armdrücken mit kleinen Fingern. Der Verlierer trinkt 2 Schlucke.',
  '{{player}}, du darfst {{player}} eine Frage stellen, die mit Ja oder Nein beantwortet wird. Lautet die Antwort Ja, trinkt die gefragte Person 2 Schlucke.',
  '{{player}}, bestimme, ob {{player}} oder {{player}} die bessere Tanzfigur hat. Die beiden zeigen sie kurz und der Verlierer trinkt 2 Schlucke.',
  '{{player}}, entscheide, wer von {{player}} und {{player}} die beste Stimme zum Vorlesen hat. Diese Person verteilt 3 Schlucke.',

  // Abstimmungen
  'Abstimmung: Wer würde eher beim Film als Erstes einschlafen? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher sein Handy im Kühlschrank vergessen? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher eine Kochshow gewinnen? Diese Person verteilt 3 Schlucke.',
  'Abstimmung: Wer würde eher bei einer Quizshow eine Million gewinnen? Diese Person verteilt 3 Schlucke.',
  'Abstimmung: Wer würde eher zu spät zur eigenen Party kommen? Diese Person trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher eine Zombieapokalypse überleben? Diese Person verteilt 3 Schlucke.',
  'Abstimmung: Wer würde eher ohne Navi im Kreis fahren? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher bei einem Liebesfilm weinen? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher jeden Tag dasselbe Essen essen? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher in einer Castingshow mitmachen? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher 20 Katzen haben? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher seinen eigenen Geburtstag vergessen? Diese Person trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher einen Weltrekord aufstellen? Diese Person verteilt 3 Schlucke.',
  'Abstimmung: Wer hat heute das beste Outfit an? Diese Person verteilt 4 Schlucke.',
  'Abstimmung: Wer lacht am lautesten in der Runde? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher beim Karaoke das Mikro nicht mehr hergeben? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher im Supermarkt den Einkaufszettel vergessen? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher eine Woche lang ohne Handy auskommen? Diese Person verteilt 3 Schlucke.',
  'Abstimmung: Wer ist der beste Gastgeber in der Runde? Diese Person verteilt 3 Schlucke.',
  'Abstimmung: Wer würde eher mit einem Promi ein Selfie ergattern? Diese Person verteilt 2 Schlucke.',
  'Abstimmung: Wer würde eher eine ganze Staffel an einem Tag schauen? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher beim Wandern die falsche Abzweigung nehmen? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer würde eher ein Buch schreiben? Diese Person verteilt 2 Schlucke.',
  'Abstimmung: Wer hat den ansteckendsten Lacher? Diese Person verteilt 3 Schlucke.',
  'Abstimmung: Wer würde eher beim Monopoly schummeln? Diese Person trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher als Erstes auf der Tanzfläche stehen? Diese Person verteilt 2 Schlucke.',
  'Abstimmung: Wer würde eher auf eine Weltreise ohne Plan gehen? Diese Person verteilt 2 Schlucke.',
  'Abstimmung: Wer würde eher seinen Schlüssel suchen, während er ihn in der Hand hält? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer wäre der beste Reiseführer? Diese Person verteilt 3 Schlucke.',
  'Abstimmung: Wer ist der größte Morgenmuffel? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer hat den besten Musikgeschmack in der Runde? Diese Person bestimmt das nächste Lied und verteilt 2 Schlucke.',
  'Abstimmung: Wer würde eher einen Tag lang im Schlafanzug bleiben? Diese Person trinkt 2 Schlucke.',
  'Abstimmung: Wer schreibt die längsten Sprachnachrichten? Diese Person trinkt 3 Schlucke.',
  'Abstimmung: Wer wäre der beste Detektiv? Diese Person verteilt 3 Schlucke.',
  'Abstimmung: Pizza oder Burger? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Strand oder Berge? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Hund oder Katze? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Sommer oder Winter? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Frühaufsteher oder Nachteule? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Süß oder salzig? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Ananas auf Pizza, ja oder nein? Die Minderheit trinkt 3 Schlucke.',
  'Abstimmung: Lieber unsichtbar sein oder fliegen können? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Lieber nie wieder Musik hören oder nie wieder Filme schauen? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Lieber in der Vergangenheit oder in der Zukunft leben? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Lieber jeden Tag Regen oder jeden Tag 35 Grad? Die Minderheit trinkt 2 Schlucke.',
  'Abstimmung: Lieber mit Tieren sprechen oder alle Sprachen der Welt können? Die Minderheit trinkt 2 Schlucke.',

  // Alle, die ...
  'Alle, die schon mal einen Film im Kino verschlafen haben, trinken 2 Schlucke.',
  'Alle, die schon mal ihren Schlüssel verloren haben, trinken 1 Schluck.',
  'Alle, die heute schon mehr als 3 Kaffee getrunken haben, trinken 2 Schlucke.',
  'Alle, die schon mal in einem anderen Land Urlaub gemacht haben, trinken 1 Schluck.',
  'Alle, die ein Instrument spielen können, verteilen 2 Schlucke.',
  'Alle, die schon mal bei einem Konzert waren, trinken 1 Schluck.',
  'Alle, die einen Wecker mit Schlummertaste nutzen, trinken 2 Schlucke.',
  'Alle, die schon mal ein Selfie mit einem Promi gemacht haben, verteilen 3 Schlucke.',
  'Alle, die Brille oder Kontaktlinsen tragen, trinken 1 Schluck.',
  'Alle, die heute schon getanzt haben, verteilen 2 Schlucke.',
  'Alle, die schon mal in einer Achterbahn geschrien haben, trinken 2 Schlucke.',
  'Alle, die ihr Handy gerade in der Hand haben, trinken 2 Schlucke.',
  'Alle, die im Winter Geburtstag haben, trinken 2 Schlucke.',
  'Alle, die im Sommer Geburtstag haben, verteilen 2 Schlucke.',
  'Alle, die mit dem Fahrrad gekommen sind, verteilen 2 Schlucke.',
  'Alle, die schon mal eine ganze Pizza alleine gegessen haben, trinken 2 Schlucke.',
  'Alle, die beim Duschen singen, trinken 2 Schlucke.',
  'Alle, die Harry Potter gelesen haben, trinken 1 Schluck.',
  'Alle, die schon mal einen Marathon oder Halbmarathon gelaufen sind, verteilen 3 Schlucke.',
  'Alle, die schon mal einen Zug verpasst haben, trinken 2 Schlucke.',
  'Alle, die mehr als 1000 ungelesene Mails haben, trinken 2 Schlucke.',
  'Alle, die schon mal bei einem Videoanruf das Mikro vergessen haben, trinken 2 Schlucke.',
  'Alle, die Ananas auf Pizza mögen, trinken 2 Schlucke.',
  'Alle, die schon mal Ski oder Snowboard gefahren sind, trinken 1 Schluck.',
  'Alle, die einen Spitznamen haben, trinken 1 Schluck.',
  'Alle, die heute schon jemanden umarmt haben, verteilen 2 Schlucke.',
  'Alle, die schon mal ein Tier gerettet haben, verteilen 3 Schlucke.',
  'Alle, die schon mal beim Kochen etwas angebrannt haben, trinken 2 Schlucke.',
  'Alle, die einen grünen Daumen haben und Pflanzen am Leben halten, verteilen 2 Schlucke.',
  'Alle, die schon mal in einem Zelt übernachtet haben, trinken 1 Schluck.',
  'Alle, die ein Tattoo haben, trinken 1 Schluck.',
  'Alle, die Einzelkind sind, verteilen 2 Schlucke.',
  'Alle, die das älteste Geschwisterkind sind, trinken 2 Schlucke.',
  'Alle, die mehr als zwei Sprachen sprechen, verteilen 3 Schlucke.',
  'Alle, die schon mal auf einem Pferd geritten sind, trinken 1 Schluck.',
  'Alle, die heute schon ein Nickerchen gemacht haben, trinken 2 Schlucke.',
  'Alle, die schon mal ein Lied falsch mitgesungen haben, ohne es zu merken, trinken 2 Schlucke.',
  'Alle, die heute Schwarz tragen, trinken 1 Schluck.',
  'Alle, die schon mal gewinkt haben, obwohl gar nicht sie gemeint waren, trinken 2 Schlucke.',
  'Alle, die schon mal einen Witz erzählt haben, über den niemand gelacht hat, trinken 2 Schlucke.',
  'Alle, die mehr als 5 Tabs im Browser offen haben, trinken 2 Schlucke.',

  // Mini Spiele
  'Kategorien-Runde: Obstsorten. Reihum nennt jeder eine. Wer zögert oder wiederholt, trinkt 2 Schlucke.',
  'Kategorien-Runde: Fußballvereine. Reihum nennt jeder einen. Wer zuerst passen muss, trinkt 2 Schlucke.',
  'Kategorien-Runde: Disney-Filme. Reihum nennt jeder einen. Wer stockt, trinkt 2 Schlucke.',
  'Kategorien-Runde: Dinge, die man im Badezimmer findet. Wer keine Idee mehr hat, trinkt 2 Schlucke.',
  'Kategorien-Runde: Eissorten. Reihum nennt jeder eine. Wer passt, trinkt 2 Schlucke.',
  'Kategorien-Runde: Sportarten mit Ball. Wer zuerst nichts mehr weiß, trinkt 2 Schlucke.',
  'Kategorien-Runde: Berühmte Sängerinnen. Reihum nennt jeder eine. Wer stockt, trinkt 2 Schlucke.',
  'Kategorien-Runde: Brettspiele. Reihum nennt jeder eines. Wer passt, trinkt 2 Schlucke.',
  'Kategorien-Runde: Superhelden. Reihum nennt jeder einen. Wer stockt, trinkt 2 Schlucke.',
  'Kategorien-Runde: Tiere im Zoo. Wer zuerst passen muss, trinkt 2 Schlucke.',
  'Kategorien-Runde: Simpsons-Figuren. Wer zuerst keine mehr weiß, trinkt 2 Schlucke.',
  'Kategorien-Runde: Dinge, die man an den Strand mitnimmt. Wer stockt, trinkt 2 Schlucke.',
  'Kategorien-Runde: Länder in Afrika. Wer zuerst stockt, trinkt 3 Schlucke.',
  'Kategorien-Runde: Berufe. Reihum nennt jeder einen. Wer zögert, trinkt 2 Schlucke.',
  'Kategorien-Runde: Automarken. Wer zuerst keine mehr kennt, trinkt 2 Schlucke.',
  'Kategorien-Runde: Kinderserien von früher. Wer stockt, trinkt 2 Schlucke.',
  'Reimkette: {{player}} beginnt mit dem Wort Haus. Reihum nennt jeder ein Reimwort. Wer keins mehr findet, trinkt 2 Schlucke.',
  'Reimkette: {{player}} beginnt mit dem Wort Katze. Wer kein Reimwort mehr findet, trinkt 2 Schlucke.',
  'Reimkette: {{player}} beginnt mit dem Wort Bier. Wer stockt, trinkt 2 Schlucke.',
  'Wort-Kette: {{player}} sagt ein Wort, die nächste Person ein Wort, das mit dem letzten Buchstaben beginnt. Wer stockt, trinkt 2 Schlucke.',
  'Wort-Kette mit zusammengesetzten Wörtern: {{player}} beginnt mit Fußball, die nächste Person macht Ballspiel und so weiter. Wer stockt, trinkt 2 Schlucke.',
  'Wasserfall: {{player}} fängt an zu trinken, alle anderen folgen im Uhrzeigersinn. Niemand darf aufhören, bevor die Person vor ihm aufhört.',
  'Kleiner Wasserfall: Alle trinken gleichzeitig los. Wer als Erstes absetzt, trinkt danach noch 1 Schluck.',
  'Schere Stein Papier Turnier: Alle spielen paarweise. Die Verlierer spielen weiter, bis einer übrig ist. Diese Person trinkt 3 Schlucke.',
  'Zählrunde: Zählt reihum bis 30. Statt jeder Zahl mit 7 oder durch 7 teilbar sagt ihr Bier. Wer sich vertut, trinkt 2 Schlucke.',
  'Ich packe meinen Koffer: {{player}} beginnt. Jeder wiederholt alles und fügt einen Gegenstand hinzu. Wer etwas vergisst, trinkt 3 Schlucke.',
  'Stille Post: {{player}} flüstert der linken Person einen Satz ins Ohr. Kommt am Ende etwas anderes an, trinken alle 1 Schluck.',
  'Pantomime: {{player}}, stell einen Film dar. Wer ihn errät, verteilt 2 Schlucke. Errät ihn niemand in 30 Sekunden, trinkst du 2 Schlucke.',
  'Pantomime: {{player}} stellt einen Beruf dar. Wer zuerst richtig rät, verteilt 2 Schlucke.',
  'Pantomime: {{player}} stellt ein Tier dar, ohne Geräusche. Wer zuerst richtig rät, verteilt 2 Schlucke.',
  'Pantomime: {{player}} stellt eine Alltagssituation dar, zum Beispiel Zähneputzen oder Einparken. Wer sie errät, verteilt 2 Schlucke.',
  'Summen: {{player}}, summ ein bekanntes Lied. Wer es zuerst errät, verteilt 3 Schlucke. Errät es niemand, trinkst du 2 Schlucke.',
  'Ich sehe was, was du nicht siehst: {{player}} beginnt. Wer es errät, verteilt 2 Schlucke. Nach 5 falschen Tipps trinken alle 1 Schluck.',
  'Wer bin ich: {{player}} denkt an einen Promi. Die Runde stellt Fragen, die man mit Ja oder Nein beantworten kann. Nach 10 Fragen ohne Lösung trinken alle anderen 2 Schlucke.',
  'Daumen hoch: Wer als Letztes seinen Daumen auf den Tisch legt, trinkt 2 Schlucke.',
  'Nasen-Runde: Wer als Letztes den Finger an die Nase legt, trinkt 2 Schlucke.',
  'Wer als Letztes beide Hände in die Luft streckt, trinkt 2 Schlucke.',
  'Wer als Letztes sein Glas berührt, trinkt 2 Schlucke.',
  'Wer als Letztes Prost ruft, trinkt 2 Schlucke.',
  'Ja-Nein-Verbot: {{player}} stellt jedem eine Frage. Wer mit Ja oder Nein antwortet, trinkt 2 Schlucke.',
  'Buchstabenrunde: Jeder nennt reihum ein Tier mit dem Anfangsbuchstaben seines Vornamens. Wer keins findet, trinkt 2 Schlucke.',
  'Alphabet-Runde: Reihum nennt jeder ein Essen, das mit dem nächsten Buchstaben im Alphabet beginnt. Wer stockt, trinkt 2 Schlucke.',
  'Lach-Verbot: Für 30 Sekunden darf niemand lachen, während {{player}} Grimassen schneidet. Wer lacht, trinkt 2 Schlucke.',
  'Geschichte erzählen: {{player}} beginnt eine Geschichte mit einem Satz. Reihum fügt jeder einen Satz hinzu. Wer stockt, trinkt 2 Schlucke.',
  'Zungenbrecher-Runde: Jeder sagt reihum Blaukraut bleibt Blaukraut und Brautkleid bleibt Brautkleid. Wer sich verhaspelt, trinkt 2 Schlucke.',
  'Hoch oder tief: {{player}} denkt sich eine Zahl von 1 bis 100. Reihum wird geraten. Wer sie trifft, verteilt 5 Schlucke.',
  'Blinzel-Runde: Alle schauen sich gegenseitig an. Wer zuerst blinzelt, trinkt 2 Schlucke.',
  'Hände auf den Tisch: Alle legen die Hände flach hin und heben sie auf Kommando von {{player}}. Wer zu früh hebt, trinkt 2 Schlucke.',
  'Gegensätze: {{player}} sagt reihum ein Wort zu jedem. Die Person nennt sofort das Gegenteil. Wer zögert, trinkt 1 Schluck.',
  'Klatschrhythmus: {{player}} klatscht einen Rhythmus vor. Reihum macht jeder ihn nach. Wer danebenliegt, trinkt 1 Schluck.',
  'Fünf Sekunden: {{player}}, nenne 3 Dinge, die man in einer Küche findet. Schaffst du es nicht, trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Sachen, die fliegen können. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Märchen. Sonst trinkst du 2 Schlucke.',

  // Wissen und Schnelldenken
  '{{player}} sucht im Handy eine Quizfrage heraus und stellt sie {{player}}. Richtig heißt 3 Schlucke verteilen, falsch heißt 2 trinken.',
  'Schnellquiz für alle: {{player}} sucht im Handy eine Quizfrage heraus und liest sie vor. Wer zuerst richtig antwortet, verteilt 3 Schlucke.',
  '{{player}}, wie heißt die Hauptstadt von Kanada? {{player}} prüft am Handy nach. Richtig heißt 3 Schlucke verteilen, falsch heißt 2 trinken.',
  '{{player}}, wie viele Herzen hat ein Oktopus? {{player}} prüft am Handy nach. Richtig heißt 3 Schlucke verteilen, falsch heißt 2 trinken.',
  '{{player}}, in welchem Jahr fiel die Berliner Mauer? {{player}} prüft am Handy nach. Richtig heißt 3 Schlucke verteilen, falsch heißt 2 trinken.',
  '{{player}}, wie heißt der längste Fluss, der komplett durch Deutschland fließt? {{player}} prüft am Handy nach. Richtig heißt 3 Schlucke verteilen, falsch heißt 2 trinken.',
  'Quizfrage an {{player}}: Nenne alle 16 Bundesländer. Die Runde zählt mit. Für jedes fehlende trinkst du 1 Schluck, höchstens 4.',
  'Quizfrage an {{player}}: Zähle die Planeten unseres Sonnensystems auf. Die Runde prüft mit. Fehlt einer, trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Dinge, die man in den Urlaub mitnimmt. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Sportarten ohne Ball. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Dinge, die nach Weihnachten riechen. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Tiere, die im Wasser leben. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Comicfiguren. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Dinge, die man auf einer Hochzeit sieht. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Wörter, die sich auf Hose reimen. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Kartenspiele. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Dinge, die man im Kino kaufen kann. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Berufe, bei denen man eine Uniform trägt. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Gründe, warum Montag doof ist. Sonst trinkst du 2 Schlucke.',
  'Fünf Sekunden: {{player}}, nenne 3 Dinge, die man nie in den Mund nehmen sollte. Sonst trinkst du 2 Schlucke.',
  '{{player}}, buchstabiere deinen Vornamen und Nachnamen rückwärts. Verhaspelst du dich, trinkst du 2 Schlucke.',
  '{{player}}, sag die Monate rückwärts auf, von Dezember bis Januar. Schaffst du es fehlerfrei, verteilst du 2 Schlucke, sonst trinkst du 2.',
  '{{player}}, zähle in 10 Sekunden 5 Farben auf Englisch auf oder trink 2 Schlucke.',
  '{{player}}, nenne zu jedem Buchstaben deines Vornamens ein Tier. Schaffst du es ohne Zögern, verteilst du 3 Schlucke, sonst trinkst du 2.',
  '{{player}}, sag die 3er-Reihe bis 30 so schnell du kannst. Vertust du dich, trinkst du 2 Schlucke.',
  '{{player}}, erkläre in 20 Sekunden, wie man ein Spiegelei brät, ohne die Wörter Ei und Pfanne zu sagen. Rutscht dir eins raus, trinkst du 2 Schlucke.',
  '{{player}}, nenne zu jeder Person in der Runde ein Tier, das zu ihr passt. Danach verteilst du 2 Schlucke.',
  '{{player}}, erfinde in 10 Sekunden einen Namen für eine Band aus dieser Runde. Gefällt er der Runde, verteilst du 2 Schlucke.',
  '{{player}}, nenne 3 Lieder, in deren Titel eine Stadt vorkommt. Schaffst du es nicht, trinkst du 2 Schlucke.',
  '{{player}}, sag in 10 Sekunden 5 Wörter, die mit Z anfangen, oder trink 2 Schlucke.',
  '{{player}}, zähle von 20 rückwärts bis 0 und lass dabei jede ungerade Zahl weg. Vertust du dich, trinkst du 2 Schlucke.',

  // Schätzen und Raten
  '{{player}}, schätze, wie viele Länder es auf der Welt gibt. {{player}} schaut im Handy nach. Liegst du mehr als 10 daneben, trinkst du 2 Schlucke.',
  '{{player}}, schätze, wie hoch der Eiffelturm ist. {{player}} schaut im Handy nach. Liegst du mehr als 50 Meter daneben, trinkst du 2 Schlucke.',
  '{{player}}, schätze, wie viele Knochen ein erwachsener Mensch hat. {{player}} schaut im Handy nach. Liegst du mehr als 30 daneben, trinkst du 2 Schlucke.',
  'Alle schätzen, wie alt {{player}} in Monaten ist. Wer am nächsten dran ist, verteilt 3 Schlucke.',
  'Alle schätzen die Körpergröße von {{player}} in Zentimetern. Wer am weitesten danebenliegt, trinkt 2 Schlucke.',
  'Alle schätzen, wie viele Fotos {{player}} auf dem Handy hat. Dann wird nachgeschaut. Wer am nächsten dran ist, verteilt 3 Schlucke.',
  '{{player}}, rate die Schuhgröße von {{player}}. Liegst du richtig, verteilst du 3 Schlucke, sonst trinkst du 2.',
  '{{player}}, rate, welches Getränk {{player}} am liebsten mag. Falsch geraten heißt 2 Schlucke für dich.',
  '{{player}} denkt an eine Zahl von 1 bis 10. {{player}} hat einen Versuch zu raten. Richtig heißt 3 Schlucke verteilen, falsch heißt 2 trinken.',
  '{{player}}, rate, welche Farbe das Handy von {{player}} hat, ohne hinzuschauen. Falsch geraten heißt 2 Schlucke.',
  'Alle schätzen, wie viele Schritte {{player}} heute gelaufen ist. Wer am weitesten danebenliegt, trinkt 2 Schlucke.',
  '{{player}}, schätze, wie lange du die Luft anhalten kannst, und versuch es dann. Schaffst du es nicht, trinkst du 2 Schlucke.',
  '{{player}}, schätze ohne Uhr, wann 30 Sekunden um sind. Die Runde stoppt mit. Liegst du mehr als 5 Sekunden daneben, trinkst du 2 Schlucke.',

  // Regeln
  'Neue Regel für die nächsten 3 Aufgaben: Niemand darf das Wort trinken sagen. Wer es tut, trinkt 1 Schluck.',
  'Neue Regel für die nächsten 3 Aufgaben: Alle trinken nur mit der linken Hand. Wer es vergisst, trinkt 1 Schluck extra.',
  'Neue Regel für die nächsten 3 Aufgaben: Niemand darf auf sein Handy schauen. Wer es tut, trinkt 2 Schlucke.',
  'Neue Regel für die nächsten 3 Aufgaben: Vor jedem Schluck muss man Prost sagen. Wer es vergisst, trinkt 1 Schluck extra.',
  'Neue Regel für die nächsten 3 Aufgaben: Niemand darf einen Namen sagen. Wer es tut, trinkt 1 Schluck.',
  'Neue Regel für die nächsten 3 Aufgaben: Wer flucht, trinkt 1 Schluck.',
  'Neue Regel für die nächsten 3 Aufgaben: {{player}} ist der König der Runde. Wer den König nicht mit Eure Majestät anspricht, trinkt 1 Schluck.',
  'Neue Regel für die nächsten 3 Aufgaben: Wer lacht, muss vorher die Hand heben. Sonst gibt es 1 Schluck.',
  'Neue Regel für die nächsten 3 Aufgaben: Ja und Nein sind verboten. Jeder Verstoß kostet 1 Schluck.',
  'Neue Regel für die nächsten 3 Aufgaben: {{player}} ist der Daumenmeister. Legt der Daumenmeister heimlich den Daumen auf den Tisch, macht es jeder nach. Der Letzte trinkt 2 Schlucke.',
  'Neue Regel für die nächsten 3 Aufgaben: {{player}} ist der Fragenmeister. Wer eine Frage des Fragenmeisters beantwortet, trinkt 1 Schluck.',
  'Neue Regel für die nächsten 3 Aufgaben: Jeder muss vor dem Trinken an sein Glas klopfen. Wer es vergisst, trinkt 1 Schluck extra.',
  'Neue Regel für die nächsten 3 Aufgaben: Alle reden mit tiefer Stimme. Wer es vergisst, trinkt 1 Schluck.',
  'Neue Regel für die nächsten 3 Aufgaben: {{player}} darf jederzeit Stopp rufen. Wer als Letztes einfriert, trinkt 2 Schlucke.',
  'Neue Regel für die nächsten 3 Aufgaben: Das Wort ich ist verboten. Jeder Verstoß kostet 1 Schluck.',
  'Neue Regel für die nächsten 3 Aufgaben: {{player}} und {{player}} dürfen nur noch miteinander reden. Wer mit jemand anderem spricht, trinkt 1 Schluck.',

  // Ganze Runde
  'Alle stoßen an und trinken 2 Schlucke auf den Abend.',
  'Alle, die gerade ein volleres Glas haben als {{player}}, trinken 2 Schlucke.',
  'Alle zeigen auf die Person, die heute am meisten gelacht hat. Diese Person verteilt 3 Schlucke.',
  'Alle zeigen gleichzeitig auf die Person, die am längsten zum Fertigmachen braucht. Diese Person trinkt 2 Schlucke.',
  'Die Person mit dem längsten Vornamen trinkt 2 Schlucke.',
  'Die Person mit dem kürzesten Vornamen verteilt 2 Schlucke.',
  'Die Person, die als Nächstes Geburtstag hat, verteilt 3 Schlucke.',
  'Die Person, die am weitesten angereist ist, verteilt 3 Schlucke.',
  'Die größte Person in der Runde trinkt 2 Schlucke, die kleinste verteilt 2.',
  'Die Person mit dem wenigsten Akku am Handy trinkt 2 Schlucke.',
  'Die Person mit den meisten Ringen an den Fingern verteilt 2 Schlucke.',
  'Die Person, die zuletzt etwas gegessen hat, trinkt 1 Schluck.',
  'Die jüngste Person in der Runde verteilt 3 Schlucke.',
  'Die älteste Person in der Runde darf eine neue Mini-Regel für die nächsten 3 Aufgaben aufstellen.',
  'Alle tauschen den Platz mit der Person rechts von ihnen. Wer als Letztes sitzt, trinkt 2 Schlucke.',
  'Alle halten ihr Glas hoch. Wer das leerste Glas hat, trinkt 1 Schluck und darf sich nachschenken.',
  'Alle sagen gleichzeitig ihre Lieblingsjahreszeit. Wer allein mit seiner Antwort ist, trinkt 2 Schlucke.',
  'Alle legen ihr Handy in die Mitte. Wer als Letztes fertig ist, trinkt 2 Schlucke.',
  'Toast-Runde: {{player}} hält einen kurzen Trinkspruch. Danach trinken alle 2 Schlucke.',
  'Gruppenfoto in Gedanken: Alle machen gleichzeitig ihre beste Pose. Die Runde wählt die schwächste. Diese Person trinkt 2 Schlucke.',
  'Alle, die gerade die Beine übereinandergeschlagen haben, trinken 1 Schluck.',
  'Alle, die gerade lächeln, dürfen 1 Schluck verteilen.',
  'Jeder nennt sein Lieblingsessen. Wer das gleiche wie jemand anders sagt, trinkt mit dieser Person 1 Schluck.',
  'Jeder zeigt den letzten Song in seiner Musik-App. Die Runde wählt den peinlichsten. Diese Person trinkt 2 Schlucke.',
  'Jeder sagt reihum, wo er gerne wohnen würde. Die Runde wählt die beste Antwort. Diese Person verteilt 3 Schlucke.',
  'Jeder verteilt 1 Schluck an die Person, mit der er heute am meisten geredet hat.',
  'Jeder gibt der Person links von sich 1 Schluck.',
  'Jeder gibt der Person rechts von sich 2 Schlucke.',
];
