export const partyTasks: string[] = [
  'Wasserfall! {{player}} fängt an, alle trinken mit und hören erst auf, wenn die Person links von ihnen aufhört.',
  'Wasserfall rückwärts: {{player}} beginnt, die Runde steigt gegen den Uhrzeigersinn nacheinander ein. Niemand darf absetzen, bevor die Person davor abgesetzt hat.',
  'Mini-Wasserfall: Alle trinken gleichzeitig, und wer zuerst absetzt, trinkt danach noch 2 Schlucke.',
  'Wasserfall mit Musik: Alle trinken, solange {{player}} einen Song summt. Erst wenn das Summen aufhört, darf abgesetzt werden.',
  'Kategorien! {{player}} nennt eine Kategorie, reihum nennt jeder einen Begriff. Wer zögert oder wiederholt, trinkt 2 Schlucke.',
  'Kategorie: Automarken. {{player}} beginnt, reihum geht es weiter. Wer nichts mehr weiß, trinkt 3 Schlucke.',
  'Kategorie: Biersorten und Biermarken. {{player}} startet. Wer hängen bleibt, trinkt 2 Schlucke.',
  'Kategorie: Disney-Filme. {{player}} fängt an. Wer keinen mehr weiß, trinkt 2 Schlucke.',
  'Kategorie: Cocktails. {{player}} beginnt. Wer stockt, trinkt 2 Schlucke.',
  'Kategorie: Fußballvereine. {{player}} startet reihum. Wer passen muss, trinkt 3 Schlucke.',
  'Kategorie: Hauptstädte. {{player}} beginnt. Wer eine falsche oder doppelte nennt, trinkt 2 Schlucke.',
  'Kategorie: Pokémon. {{player}} beginnt. Wer keins mehr weiß, trinkt 2 Schlucke.',
  'Kategorie: Dinge, die man auf einer Party findet. {{player}} startet. Wer hängt, trinkt 2 Schlucke.',
  'Kategorie: Superhelden. {{player}} beginnt. Wer keinen mehr kennt, trinkt 2 Schlucke.',
  'Kategorie: Sänger und Sängerinnen mit nur einem Namen, wie Adele. {{player}} beginnt. Wer nichts weiß, trinkt 3 Schlucke.',
  'Kategorie: Käsesorten. {{player}} beginnt reihum. Wer hängen bleibt, trinkt 2 Schlucke.',
  'Kategorie: Serien auf Netflix. {{player}} startet. Wer keine mehr weiß, trinkt 2 Schlucke.',
  'Kategorie: Wörter, die sich auf "Party" reimen. {{player}} beginnt. Wer nichts findet, trinkt 2 Schlucke.',
  'Kategorie: Schnapssorten. {{player}} startet. Wer keine mehr kennt, trinkt 2 Schlucke.',
  'Kategorie: Harry-Potter-Figuren. {{player}} beginnt. Wer stockt, trinkt 2 Schlucke.',
  'Kategorie: Videospiele. {{player}} beginnt. Wer keins mehr weiß, trinkt 2 Schlucke.',
  'Kategorie: Berühmte Bands. {{player}} startet. Wer passen muss, trinkt 2 Schlucke.',
  'Kategorie: Marvel-Filme. {{player}} beginnt. Wer stockt, trinkt 2 Schlucke.',
  'Kategorie: Tanzstile. {{player}} beginnt. Wer keinen mehr kennt, trinkt 2 Schlucke.',
  'Kategorie: Musikinstrumente. {{player}} startet. Wer hängen bleibt, trinkt 2 Schlucke.',
  'Kategorie: Dinge, die man am Strand macht. {{player}} startet. Wer stockt, trinkt 2 Schlucke.',
  'Ich packe meinen Koffer! {{player}} beginnt, jeder wiederholt alles und fügt etwas hinzu. Wer einen Fehler macht, trinkt 3 Schlucke.',
  'Ich gehe auf eine Party und bringe mit ... {{player}} beginnt, reihum wird ergänzt. Wer etwas vergisst, trinkt 3 Schlucke.',
  'Ich mixe einen Cocktail und tue hinein ... {{player}} beginnt mit der ersten Zutat. Wer die Liste vermasselt, trinkt 3 Schlucke.',
  'Bewegungskette: {{player}} macht eine Geste vor, jeder wiederholt alle bisherigen Gesten und fügt eine hinzu. Wer patzt, trinkt 3 Schlucke.',
  'Geräuschkette: {{player}} macht ein Geräusch, jeder wiederholt alle vorherigen und hängt eins an. Wer sich vertut, trinkt 2 Schlucke.',
  'Ich fahre in den Urlaub nach ... {{player}} nennt ein Ziel, reihum wird die Reiseroute verlängert. Wer ein Ziel vergisst, trinkt 3 Schlucke.',
  'Namenskette: Reihum nennt jeder die Vornamen aller Personen am Tisch im Uhrzeigersinn, so schnell es geht. Wer sich verhaspelt, trinkt 2 Schlucke.',
  'Ich gehe in den Supermarkt und kaufe ... aber alphabetisch. {{player}} beginnt mit A. Wer den Faden verliert, trinkt 3 Schlucke.',
  'Daumen auf den Tisch! Der Letzte, der seinen Daumen auf die Tischkante legt, trinkt 2 Schlucke.',
  'Alle zeigen auf die Decke! Wer als Letztes zeigt, trinkt 2 Schlucke.',
  'Hände hoch! Die letzte Person mit erhobenen Händen trinkt 2 Schlucke.',
  'Alle berühren ihre Nase! Wer als Letztes die Nase berührt, trinkt 2 Schlucke.',
  'Alle stehen auf! Die letzte Person, die steht, trinkt 3 Schlucke.',
  'Alle klatschen 3 Mal! Wer zu spät oder zu oft klatscht, trinkt 2 Schlucke.',
  'Glas hoch! Wer sein Glas als Letztes in die Luft hält, trinkt 2 Schlucke.',
  'Alle rufen "Prost"! Wer als Letztes ruft, trinkt 2 Schlucke.',
  'Alle machen ein Peace-Zeichen! Die letzte Person trinkt 2 Schlucke.',
  'Alle schließen die Augen! Wer als Letztes die Augen zu hat, trinkt 2 Schlucke.',
  'Alle zeigen auf die Person, die am lautesten lacht! Wer die meisten Finger abbekommt, trinkt 2 Schlucke.',
  'Alle greifen nach dem Glas von {{player}}! Wer zuletzt hinlangt, trinkt 2 Schlucke.',
  'Alle legen den Kopf auf den Tisch! Die letzte Person trinkt 3 Schlucke.',
  'Alle salutieren! Wer zuletzt salutiert, trinkt 2 Schlucke.',
  'Alle zeigen mit beiden Daumen nach oben! Wer zu spät ist, trinkt 2 Schlucke.',
  'Alle drehen sich einmal auf dem Stuhl oder im Stehen um sich selbst! Wer zuletzt fertig ist, trinkt 2 Schlucke.',
  'Alle stampfen 2 Mal mit dem Fuß! Wer aus dem Takt fällt, trinkt 2 Schlucke.',
  'Wer als Erstes "Pertolo" ruft, darf 3 Schlucke verteilen.',
  'Wer als Erstes etwas Rotes hochhält, darf 3 Schlucke verteilen.',
  'Wer zuerst auf {{player}} zeigt, darf 2 Schlucke verteilen.',
  'Wer zuerst einen Song mit "Liebe" im Titel nennt, darf 2 Schlucke verteilen.',
  'Wer zuerst etwas Blaues berührt, darf 2 Schlucke verteilen. Die letzte Person trinkt 2 Schlucke.',
  'Wer als Erstes ein Kompliment an {{player}} macht, darf 2 Schlucke verteilen.',
  'Buzz! Reihum wird gezählt. Bei jeder Zahl mit 7 oder durch 7 teilbar sagt man "Buzz". Wer patzt, trinkt 2 Schlucke.',
  'Buzz mit 3: Reihum zählen, bei jeder Zahl mit 3 oder durch 3 teilbar wird geklatscht. {{player}} beginnt. Fehler kosten 2 Schlucke.',
  'Fizz Buzz: Bei durch 3 teilbaren Zahlen "Fizz", bei durch 5 teilbaren "Buzz", bei beiden "Fizz Buzz". {{player}} beginnt. Wer patzt, trinkt 2 Schlucke.',
  'Rückwärts zählen von 30 reihum, {{player}} beginnt. Wer sich verzählt, trinkt 2 Schlucke.',
  'Zählt gemeinsam bis 20, aber ohne Reihenfolge. Sagen 2 Personen gleichzeitig eine Zahl, trinken beide 2 Schlucke und es geht von vorne los.',
  'Zählt reihum auf Englisch bis 30. Wer einen Fehler macht oder zögert, trinkt 2 Schlucke.',
  'Zählt reihum in Zweierschritten bis 50, {{player}} beginnt. Wer patzt, trinkt 2 Schlucke.',
  'Bier statt 4: Reihum zählen, aber jede 4 wird durch "Bier" ersetzt. Wer es vergisst, trinkt 2 Schlucke.',
  'Klatsch-Rhythmus: {{player}} klatscht einen Rhythmus vor, reihum muss jeder ihn nachklatschen. Wer danebenliegt, trinkt 2 Schlucke.',
  'Tisch-Trommeln: Alle trommeln gemeinsam "We Will Rock You" auf den Tisch. Wer aus dem Takt fällt, trinkt 2 Schlucke.',
  'Zip Zap Zop: {{player}} beginnt und schickt "Zip" an jemanden, der "Zap" weitergibt, dann "Zop". Wer sich verspricht, trinkt 2 Schlucke.',
  'Alphabet reihum: Jeder sagt den nächsten Buchstaben, aber rückwärts ab Z. Wer stockt, trinkt 2 Schlucke.',
  'Das Alphabet reihum mit Tieren: A wie Affe, B wie Bär. {{player}} beginnt. Wer hängt, trinkt 2 Schlucke.',
  'Das Alphabet reihum mit Getränken: A wie Aperol, B wie Bier. {{player}} beginnt. Wer stockt, trinkt 2 Schlucke.',
  'Das Alphabet reihum mit Promis: A wie Adele. {{player}} beginnt. Wer keinen weiß, trinkt 2 Schlucke.',
  'Bis 10 zählen, jede Person darf 1 bis 3 Zahlen sagen. Wer die 10 sagen muss, trinkt 3 Schlucke. {{player}} beginnt.',
  'Klatschen statt Zahl: Reihum zählen, aber jede gerade Zahl wird geklatscht statt gesagt. Wer patzt, trinkt 2 Schlucke.',
  'Schnipp und Klatsch: Abwechselnd schnipsen und klatschen, reihum. {{player}} beginnt. Wer aus dem Rhythmus fällt, trinkt 2 Schlucke.',
  'Die Welle! Alle stehen nacheinander kurz auf, 3 Runden lang, immer schneller. Wer zu spät ist, trinkt 2 Schlucke.',
  '{{player}} summt das Intro eines bekannten Songs. Die Runde hat 3 Versuche, sonst trinken alle 1 Schluck.',
  '{{player}} pfeift eine Melodie aus einem Film. Wer sie errät, verteilt 2 Schlucke.',
  '{{player}} singt eine Zeile, {{player}} muss die nächste Zeile singen. Klappt es, trinken alle anderen 1 Schluck.',
  'Alle singen gemeinsam den Refrain von "Atemlos durch die Nacht". Wer nicht mitsingt, trinkt 3 Schlucke.',
  'Alle singen gemeinsam "Country Roads". Wer den Text nicht kennt, trinkt 2 Schlucke.',
  'Alle singen gemeinsam den Refrain von "Bohemian Rhapsody" so dramatisch wie möglich. Die schwächste Performance trinkt 2 Schlucke.',
  'Alle singen gemeinsam "Ein Hoch auf uns" und stoßen beim Refrain an. Danach trinken alle 1 Schluck.',
  'Alle singen gemeinsam "Sweet Caroline" und brüllen das "Bah Bah Bah". Wer nicht laut genug ist, trinkt 2 Schlucke.',
  'Alle singen den Refrain von "Mr. Brightside". Wer als Erstes den Text verliert, trinkt 2 Schlucke.',
  'Alle singen "Layla" mit. Wer den Refrain nicht kennt, trinkt 2 Schlucke.',
  'Alle singen gemeinsam "Wonderwall". Wer falsch einsetzt, trinkt 2 Schlucke.',
  'Alle singen "Dancing Queen" von ABBA. Wer nicht mitmacht, trinkt 3 Schlucke.',
  'Alle singen "99 Luftballons". Wer zuerst den Text nicht mehr weiß, trinkt 2 Schlucke.',
  'Alle singen "Don\'t Stop Believin\'". Die Person mit der schiefsten Stimme darf 2 Schlucke verteilen, weil sie Mut bewiesen hat.',
  'Alle singen "Hey Jude" und halten das "Na na na" so lange wie möglich. Wer zuerst aufhört, trinkt 2 Schlucke.',
  'Alle singen "Ich war noch niemals in New York". Wer den Text nicht kennt, trinkt 2 Schlucke.',
  'Alle singen "Wannabe" von den Spice Girls. Wer beim Rap-Teil aussteigt, trinkt 2 Schlucke.',
  'Alle singen "Livin\' on a Prayer" und gehen beim Refrain eine Oktave höher. Wer sich nicht traut, trinkt 2 Schlucke.',
  'Alle singen "I Will Survive". Die Person, die am überzeugendsten singt, verteilt 3 Schlucke.',
  'Alle singen "Griechischer Wein". Wer nicht mitschunkelt, trinkt 2 Schlucke.',
  'Alle singen gemeinsam "Skandal im Sperrbezirk". Wer den Text verhaut, trinkt 2 Schlucke.',
  'Alle singen "Bella Ciao" und klatschen dazu. Wer aus dem Takt kommt, trinkt 2 Schlucke.',
  'Alle singen "Seven Nation Army" ohne Text, nur die Melodie. Wer lacht, trinkt 2 Schlucke.',
  '{{player}} stimmt einen Song an, und die Runde muss sofort einsteigen. Wer nicht mitsingt, trinkt 2 Schlucke.',
  'Song-Kette: {{player}} nennt einen Song, der nächste nennt einen Song, der mit dem letzten Buchstaben des Titels beginnt. Wer hängt, trinkt 2 Schlucke.',
  'Kategorie: Songs mit einer Farbe im Titel. {{player}} beginnt. Wer keinen weiß, trinkt 2 Schlucke.',
  'Kategorie: Songs mit einer Zahl im Titel. {{player}} startet. Wer stockt, trinkt 2 Schlucke.',
  'Kategorie: Deutsche Schlager. {{player}} beginnt. Wer keinen mehr weiß, trinkt 2 Schlucke.',
  'Kategorie: Songs mit einem Namen im Titel, wie "Billie Jean". {{player}} startet. Wer zögert, trinkt 2 Schlucke.',
  'Kategorie: Songs über Alkohol. {{player}} beginnt. Wer nichts findet, trinkt 3 Schlucke.',
  'Kategorie: Songs aus den 80ern. {{player}} beginnt. Wer stockt, trinkt 2 Schlucke.',
  'Kategorie: Songs aus Disney-Filmen. {{player}} beginnt. Wer zögert, trinkt 2 Schlucke.',
  'Kategorie: Ballermann-Hits. {{player}} startet. Wer passen muss, trinkt 3 Schlucke.',
  '{{player}} singt einen bekannten Song in Opernstimme. Wer ihn zuerst errät, verteilt 2 Schlucke.',
  '{{player}} sagt eine Liedzeile ohne Melodie auf, wie ein Gedicht. Wer den Song errät, verteilt 2 Schlucke.',
  'Lückentext: {{player}} singt eine bekannte Zeile und lässt das letzte Wort weg. Wer es zuerst ergänzt, verteilt 2 Schlucke.',
  'Alle spielen gleichzeitig Luftinstrumente zu einem Song, den {{player}} summt. Wer zuerst aufhört, trinkt 2 Schlucke.',
  'Beatbox-Runde: Reihum macht jeder 5 Sekunden Beatbox. Die Runde wählt den schlechtesten Beat, diese Person trinkt 2 Schlucke.',
  'Karaoke ohne Musik: {{player}} und {{player}} singen gemeinsam einen Refrain ihrer Wahl. Danach trinkt der Rest 1 Schluck aus Respekt.',
  'Wer kennt mehr Songs von Helene Fischer? {{player}} und {{player}} nennen abwechselnd Titel. Alle anderen tippen vorher auf den Sieger. Wer falsch tippt, trinkt 2 Schlucke.',
  'DJ-Runde: {{player}} darf den nächsten Song bestimmen. Wer sich beschwert, trinkt 2 Schlucke.',
  'Musik-Stopp: Wenn die Musik das nächste Mal leiser wird oder ein Song endet, rufen alle "Prost". Wer es verpasst, trinkt 2 Schlucke.',
  'Wer den Interpreten des gerade laufenden Songs zuerst nennt, verteilt 3 Schlucke. Läuft keine Musik, singt {{player}} etwas vor.',
  'Refrain-Duell der Runde: Teilt euch in 2 Teams. Jedes Team singt abwechselnd einen Refrain. Das Team, dem zuerst keiner einfällt, trinkt 2 Schlucke.',
  'Tanzmove! {{player}} macht einen Tanzmove vor, alle müssen ihn nachmachen. Wer sich weigert, trinkt 3 Schlucke.',
  'Alle machen den Macarena-Tanz einmal komplett. Wer patzt, trinkt 2 Schlucke.',
  'Alle machen den Floss für 10 Sekunden. Wer am schlechtesten flosst, trinkt 2 Schlucke.',
  'Alle machen gemeinsam den Ententanz. Wer nicht mitmacht, trinkt 3 Schlucke.',
  'Alle machen den YMCA-Tanz mit den Armen. Wer einen Buchstaben falsch macht, trinkt 2 Schlucke.',
  'Alle tanzen 10 Sekunden im Sitzen. Die Runde wählt den besten Tänzer, der 3 Schlucke verteilt.',
  'Roboter-Tanz: Alle tanzen 10 Sekunden wie Roboter. Wer zuerst lacht, trinkt 2 Schlucke.',
  'Freeze Dance: {{player}} summt, alle tanzen. Wenn das Summen stoppt, müssen alle erstarren. Wer sich bewegt, trinkt 2 Schlucke.',
  'Tanz-Kette: Reihum macht jeder einen Tanzmove, und alle machen ihn sofort nach. Wer nicht mitmacht, trinkt 2 Schlucke.',
  '{{player}} bringt der Runde in 30 Sekunden einen Tanzschritt bei. Wer ihn nicht kann, trinkt 2 Schlucke.',
  'Alle machen den Dab! Wer als Letztes dabbt, trinkt 2 Schlucke.',
  'Alle schunkeln untergehakt 3 Runden lang. Wer aus dem Takt kommt, trinkt 2 Schlucke.',
  'Alle machen 10 Sekunden den Gangnam Style. Wer nicht mitmacht, trinkt 3 Schlucke.',
  'Alle tanzen den Fliegerlied-Tanz: "Und ich flieg, flieg, flieg". Wer nicht mitfliegt, trinkt 2 Schlucke.',
  'Spiegeltanz: {{player}} tanzt, {{player}} muss alles spiegelverkehrt nachmachen. Klappt es, verteilen beide 2 Schlucke.',
  'Polonaise am Tisch: Alle legen die Hände auf die Schultern der Person rechts und schunkeln einmal im Kreis. Wer ausschert, trinkt 2 Schlucke.',
  'Alle machen den "Saturday Night Fever"-Finger. Die beste Pose verteilt 2 Schlucke.',
  'Headbangen! Alle headbangen 5 Sekunden lang zu einem imaginären Riff. Wer zuerst aufhört, trinkt 2 Schlucke.',
  'Alle machen die La Ola-Arme im Sitzen, 3 Runden lang. Wer zu spät ist, trinkt 2 Schlucke.',
  'Prost! Alle stoßen an, schauen sich dabei in die Augen und trinken 2 Schlucke. Wer nicht in die Augen schaut, trinkt noch 1 Schluck.',
  'Alle stoßen mit jeder einzelnen Person am Tisch an. Danach trinken alle 2 Schlucke.',
  '{{player}} hält eine 10 Sekunden lange Rede auf die Runde. Danach stoßen alle an und trinken 2 Schlucke.',
  'Toast auf {{player}}! Alle heben die Gläser, rufen den Namen und trinken 2 Schlucke.',
  'Prost auf Englisch, Spanisch und Italienisch: Cheers, Salud, Cin Cin! Alle trinken nach jedem Wort 1 Schluck.',
  'Alle stoßen an und rufen dabei laut "Zicke zacke, zicke zacke, hoi hoi hoi". Dann trinken alle 2 Schlucke.',
  'Alle trinken 2 Schlucke mit verschränkten Armen beim Nachbarn eingehakt.',
  'Reihum sagt jeder in einer anderen Sprache "Prost". Wer keine neue mehr weiß, trinkt 2 Schlucke.',
  'Alle stoßen an. Das Glas, das als Letztes den Tisch verlässt, gehört zu der Person, die 2 Schlucke extra trinkt.',
  'Alle trinken auf die beste Person der Runde. Jeder zeigt gleichzeitig auf jemanden. Die Person mit den meisten Stimmen verteilt 3 Schlucke.',
  'Trinkspruch-Kette: Reihum sagt jeder einen Satz, worauf getrunken wird. Nach jedem Satz trinken alle 1 Schluck. Eine Runde lang.',
  'Prost im Flüsterton: Alle stoßen ganz leise an. Wer das Glas hörbar klirren lässt, trinkt 2 Schlucke.',
  'Alle stoßen auf den besten Song aller Zeiten an. Wer einen Song nennt, den die Runde schlecht findet, trinkt 1 Schluck extra.',
  'Ein Prost auf die Gastgeber! Alle trinken 2 Schlucke, die Gastgeber verteilen zusätzlich 3 Schlucke.',
  'Ein Prost auf alle, die heute schon getanzt haben! Diese trinken 2 Schlucke.',
  'Alle stoßen an und trinken, ohne die Hände zu benutzen. Wer es nicht schafft, trinkt danach normal 2 Schlucke.',
  'Alle trinken mit der schwachen Hand 2 Schlucke. Wer die falsche Hand nimmt, trinkt noch 2 Schlucke.',
  'Hoch die Tassen! Alle trinken gleichzeitig 3 Schlucke.',
  'Alle stehen auf, stoßen an und setzen sich wieder. Wer sich zuletzt setzt, trinkt 2 Schlucke.',
  'Prost-Rakete: Alle trommeln auf den Tisch, werden immer schneller und rufen dann "Prost". Danach trinken alle 2 Schlucke.',
  'Abstimmung: Wer wird heute als Erstes müde? Auf 3 zeigen alle. Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer ist der beste Tänzer am Tisch? Auf 3 zeigen alle. Der Gewinner verteilt 4 Schlucke.',
  'Abstimmung: Wer würde bei einer Karaoke-Bar als Erstes auf die Bühne gehen? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer hat heute das beste Outfit? Die Person verteilt 3 Schlucke.',
  'Abstimmung: Wer lacht am lautesten? Auf 3 zeigen alle. Wer gewählt wird, trinkt 2 Schlucke.',
  'Abstimmung: Wer wäre der beste DJ? Die meistgewählte Person bestimmt den nächsten Song und verteilt 2 Schlucke.',
  'Abstimmung: Wer bleibt am längsten auf der Party? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer würde in einer Castingshow am weitesten kommen? Der Gewinner verteilt 3 Schlucke.',
  'Abstimmung: Wer hat den schlimmsten Musikgeschmack? Die Person mit den meisten Stimmen trinkt 2 Schlucke und verrät ihren Lieblingssong.',
  'Abstimmung: Wer wäre der beste Partyplaner? Die Person verteilt 3 Schlucke.',
  'Abstimmung: Wer erzählt die besten Geschichten? Die meistgewählte Person verteilt 2 Schlucke.',
  'Abstimmung: Wer ist heute am meisten in Partylaune? Diese Person verteilt 3 Schlucke.',
  'Daumen-Voting: {{player}} nennt einen Song. Alle zeigen gleichzeitig Daumen hoch oder runter. Die Minderheit trinkt 2 Schlucke.',
  'Mehrheit gewinnt: Pizza oder Burger? Auf 3 rufen alle ihre Antwort. Die Minderheit trinkt 2 Schlucke.',
  'Mehrheit gewinnt: Strand oder Berge? Auf 3 zeigen alle nach oben für Berge oder nach unten für Strand. Die Minderheit trinkt 2 Schlucke.',
  'Mehrheit gewinnt: Bier oder Wein? Auf 3 rufen alle. Die Minderheit trinkt 2 Schlucke.',
  'Mehrheit gewinnt: Beatles oder Rolling Stones? Auf 3 rufen alle. Die Minderheit trinkt 2 Schlucke.',
  'Mehrheit gewinnt: Frühaufsteher oder Nachteule? Auf 3 rufen alle. Die Minderheit trinkt 2 Schlucke.',
  'Mehrheit gewinnt: Schlager oder Techno? Auf 3 rufen alle. Die Minderheit trinkt 2 Schlucke.',
  'Gedankenleser: Alle denken an eine Zahl von 1 bis 5 und zeigen sie auf 3 mit den Fingern. Wer dieselbe Zahl wie {{player}} zeigt, verteilt 2 Schlucke.',
  'Synchron-Test: Alle sagen auf 3 gleichzeitig eine Farbe. Wer allein mit seiner Farbe ist, trinkt 2 Schlucke.',
  'Synchron-Test: Alle sagen auf 3 gleichzeitig ein Tier. Haben 2 Personen dasselbe, verteilen sie je 3 Schlucke.',
  'Synchron-Test: Alle nennen auf 3 gleichzeitig ein Getränk. Wer dasselbe wie jemand anderes sagt, stößt mit dieser Person an und trinkt 1 Schluck.',
  'Schere, Stein, Papier mit der ganzen Runde: Alle spielen gleichzeitig. Wer das seltenste Zeichen hat, verteilt 2 Schlucke.',
  'Zwei Teams! {{player}} und {{player}} wählen abwechselnd ihre Teams. Jedes Team nennt abwechselnd Biermarken. Wer zuerst passt, trinkt als Team 2 Schlucke pro Person.',
  'Teamspiel: Teilt euch in 2 Teams. Jedes Team summt abwechselnd einen Song, das andere Team muss raten. Wer 3 Mal falsch rät, trinkt 2 Schlucke pro Person.',
  'Teamspiel: 2 Teams. Welches Team schafft es, zuerst alle Gläser gleichzeitig in die Luft zu halten? Das langsamere Team trinkt 2 Schlucke.',
  'Teamspiel: 2 Teams nennen abwechselnd Länder. Das Team, das zuerst hängt, trinkt 2 Schlucke pro Person.',
  'Teamspiel: 2 Teams. Jedes Team stellt sich in einer Reihe nach Größe auf. Das langsamere Team trinkt 2 Schlucke pro Person.',
  'Teamspiel: 2 Teams. Jedes Team singt 10 Sekunden lang einen Fangesang. Die lautere Mannschaft verteilt 3 Schlucke an das andere Team.',
  'Teamspiel: 2 Teams sortieren sich ohne zu sprechen nach Geburtsmonat. Das langsamere oder falsche Team trinkt 2 Schlucke pro Person.',
  'Teamspiel: 2 Teams. Ein Mitglied pro Team stellt einen Film pantomimisch dar. Das Team, das zuerst richtig rät, verteilt 3 Schlucke.',
  'Teamspiel: 2 Teams. Jedes Team muss in 30 Sekunden so viele Tiere mit B wie möglich nennen. Das Team mit weniger trinkt 2 Schlucke pro Person.',
  'Staffeltrinken: 2 Teams. Nacheinander trinkt jeder im Team 1 Schluck und stellt das Glas ab. Das langsamere Team trinkt noch 2 Schlucke pro Person.',
  'Teamspiel: 2 Teams. Jedes Team erfindet in 30 Sekunden einen Teamnamen und einen Schlachtruf. Die Runde stimmt ab, das Verliererteam trinkt 2 Schlucke.',
  'Teamspiel: Linke Tischhälfte gegen rechte Tischhälfte. Wer kann länger den Ton "Aaaa" halten? Das Verliererteam trinkt 2 Schlucke pro Person.',
  'Teamspiel: 2 Teams. Jedes Team baut in 30 Sekunden den höchsten Turm aus Gegenständen auf dem Tisch. Das kleinere Team trinkt 2 Schlucke pro Person.',
  'Teamspiel: 2 Teams flüstern sich ein Wort durch die Reihe weiter, Stille Post. Kommt das Wort falsch an, trinkt das Team 2 Schlucke pro Person.',
  'Teamspiel: 2 Teams nennen abwechselnd Fußballspieler. Wer nach 5 Sekunden nichts hat, verliert und trinkt 2 Schlucke pro Person.',
  'Teamspiel: 2 Teams. {{player}} sagt einen Begriff, jedes Team zeichnet ihn in 20 Sekunden in die Luft. Die Runde wählt das schlechtere Team, das trinkt 2 Schlucke.',
  'Teamspiel: 2 Teams machen abwechselnd Tiergeräusche. Das Team, dem keins mehr einfällt, trinkt 2 Schlucke pro Person.',
  'Alle, die schon mal auf einem Festival waren, trinken 2 Schlucke und rufen den Namen ihres Lieblingsfestivals.',
  'Wer hat heute schon mitgesungen? Alle, die es getan haben, verteilen 1 Schluck. Alle anderen trinken 1 Schluck.',
  'Alle, die gerade ein Getränk mit Kohlensäure haben, trinken 2 Schlucke.',
  'Alle mit einem leeren Glas füllen auf und trinken direkt 1 Schluck. Alle anderen trinken 2 Schlucke.',
  'Alle, die schon mal in einem Chor oder einer Band waren, verteilen 2 Schlucke.',
  'Alle, die schon mal auf einem Konzert waren, trinken 1 Schluck. Wer auf mehr als 10 war, verteilt 3 Schlucke.',
  'Alle, die schon mal einen Tanzkurs gemacht haben, verteilen 2 Schlucke.',
  'Alle tauschen den Platz mit der Person links von sich. Wer zuletzt sitzt, trinkt 2 Schlucke.',
  'Stille! Alle sind 30 Sekunden komplett still. Wer zuerst etwas sagt oder lacht, trinkt 3 Schlucke.',
  'Lachverbot: {{player}} hat 20 Sekunden, um die Runde zum Lachen zu bringen. Jeder, der lacht, trinkt 2 Schlucke.',
  'Grimassen-Runde: Alle schneiden gleichzeitig ihre beste Grimasse. {{player}} wählt die beste, diese Person verteilt 3 Schlucke.',
  'Pantomime: {{player}} stellt einen Beruf dar. Wer ihn errät, verteilt 2 Schlucke.',
  'Pantomime: {{player}} stellt einen Film dar, ohne zu sprechen. Wer ihn zuerst errät, verteilt 3 Schlucke.',
  'Wer bin ich? {{player}} denkt an eine berühmte Person. Die Runde stellt Ja-Nein-Fragen. Wer sie errät, verteilt 3 Schlucke.',
  'Promi-Imitation: {{player}} imitiert einen Promi. Wer zuerst errät, wer es ist, verteilt 2 Schlucke.',
  'Tierlaute: {{player}} macht ein Tiergeräusch, alle anderen müssen es gleichzeitig nachmachen. Wer nicht mitmacht, trinkt 2 Schlucke.',
  'Wer spricht als Erstes? {{player}} stellt eine Frage an die Runde. Wer zuerst antwortet, verteilt 2 Schlucke, wer zuletzt antwortet, trinkt 2 Schlucke.',
  'Schnellraten: {{player}} beschreibt einen Begriff, ohne ihn zu nennen. Wer ihn zuerst errät, verteilt 2 Schlucke.',
  'Wortassoziation: {{player}} sagt ein Wort, reihum sagt jeder sofort ein passendes Wort. Wer zögert, trinkt 2 Schlucke.',
  'Satzkette: Reihum sagt jeder ein Wort, und es soll eine Geschichte entstehen. Wer den Satz kaputt macht oder zögert, trinkt 2 Schlucke.',
  'Was ist das? {{player}} nennt einen Gegenstand, reihum muss jeder eine verrückte neue Verwendung dafür nennen. Wer nichts weiß, trinkt 2 Schlucke.',
  'Berühmte Filmzitate: Reihum zitiert jeder einen Film. Wer keins mehr weiß, trinkt 2 Schlucke.',
  'Wahr oder falsch: {{player}} erzählt einen Fakt über sich. Alle stimmen ab. Wer falsch liegt, trinkt 2 Schlucke.',
  'Schweigefuchs: Alle machen mit der Hand einen Fuchs. Wer als Letztes seinen Fuchs zeigt, trinkt 2 Schlucke.',
  'Kopf oder Zahl für die ganze Runde: Alle tippen auf Kopf oder Zahl, {{player}} wirft eine Münze. Wer falsch liegt, trinkt 2 Schlucke.',
  'Die Runde erfindet gemeinsam einen Partysong. Reihum sagt jeder eine Zeile. Wer nichts reimt, trinkt 2 Schlucke.',
  'Echo: {{player}} ruft einen Satz, alle anderen müssen ihn im Chor wiederholen. Wer zu spät einsetzt, trinkt 2 Schlucke.',
  'Lautstärke-Check: Alle rufen gleichzeitig "Party". {{player}} entscheidet, wer am leisesten war. Diese Person trinkt 2 Schlucke.',
  'Ja-Nein-Verbot: {{player}} stellt jedem in der Runde schnell eine Frage. Wer mit Ja oder Nein antwortet, trinkt 2 Schlucke.',
  'Wer hat die beste Party-Story? Reihum erzählt jeder einen Satz dazu. Die Runde stimmt ab, die Gewinner-Story verteilt 3 Schlucke.',
  'Gruppenfoto-Pose: Alle machen auf 3 ihre beste Partypose und halten sie 5 Sekunden. Wer zuerst wackelt, trinkt 2 Schlucke.',
  'Der Boden ist Lava! Alle heben die Füße vom Boden. Wer als Letztes die Füße oben hat, trinkt 2 Schlucke.',
  'Wer trägt die meisten Farben? Alle zählen ihre Kleidungsfarben. Die Person mit den meisten verteilt 3 Schlucke.',
  'Alle, die gerade lachen müssen, trinken 1 Schluck. Wer sich zurückhält, aber erwischt wird, trinkt 2.',
  'Party-Ranking: {{player}} nennt 3 Partysongs. Die Runde stimmt ab, welcher der beste ist. Wer für den Verlierer stimmt, trinkt 2 Schlucke.',
  'Der Tisch macht Lärm: Alle trommeln 5 Sekunden so laut sie können. Wer zuerst aufhört, trinkt 2 Schlucke.',
  'Wer kennt den Text? {{player}} nennt einen Song, alle sagen gleichzeitig die erste Zeile auf. Wer es nicht kann, trinkt 2 Schlucke.',
  'Gemeinsames Countdown-Trinken: Alle zählen laut von 10 runter. Bei 0 trinken alle 2 Schlucke.',
  'Wer kann am längsten "Ommm" summen? Alle starten gleichzeitig. Wer zuerst aufhört, trinkt 3 Schlucke.',
  'Der höchste Ton gewinnt: Alle singen gleichzeitig ihren höchsten Ton. {{player}} kürt den Gewinner, der 3 Schlucke verteilt.',
  'Der tiefste Ton gewinnt: Alle brummen gleichzeitig ihren tiefsten Ton. Die tiefste Stimme verteilt 2 Schlucke.',
  'Flaschendrehen light: {{player}} dreht eine Flasche. Die Person, auf die sie zeigt, trinkt 2 Schlucke.',
  'Flaschendrehen: {{player}} dreht eine Flasche. Die Person, auf die sie zeigt, muss einen Song anstimmen, sonst trinkt sie 3 Schlucke.',
  'Wer sitzt am nächsten an der Musikbox? Diese Person verteilt 2 Schlucke und darf lauter machen.',
  'Gruppen-Highfive: Alle klatschen in der Mitte zusammen ab. Wer nicht trifft, trinkt 2 Schlucke.',
  'Highfive-Kette: Reihum gibt jeder der nächsten Person ein Highfive, so schnell wie möglich. Wer die Kette unterbricht, trinkt 2 Schlucke.',
  'Wer kennt die meisten Namen der 7 Zwerge? {{player}} beginnt, reihum wird ergänzt. Wer hängt, trinkt 2 Schlucke.',
  'Nenne die Planeten reihum der Reihe nach. {{player}} beginnt mit Merkur. Wer einen Fehler macht, trinkt 2 Schlucke.',
  'Reihum nennt jeder einen Monat in der richtigen Reihenfolge, aber rückwärts ab Dezember. Wer patzt, trinkt 2 Schlucke.',
  'Zungenbrecher: Reihum sagt jeder "Fischers Fritz fischt frische Fische" 3 Mal schnell. Wer sich verhaspelt, trinkt 2 Schlucke.',
  'Zungenbrecher: Reihum sagt jeder "Blaukraut bleibt Blaukraut und Brautkleid bleibt Brautkleid". Wer stolpert, trinkt 2 Schlucke.',
  'Zungenbrecher: {{player}} und {{player}} sagen gleichzeitig "Zwischen zwei Zwetschgenzweigen zwitschern zwei Schwalben". Wer sich verspricht, trinkt 2 Schlucke.',
  'Alle, deren Name mehr als 5 Buchstaben hat, trinken 2 Schlucke.',
  'Die jüngste Person am Tisch verteilt 3 Schlucke, die älteste trinkt 2 Schlucke.',
  'Die Person mit dem vollsten Glas verteilt 3 Schlucke.',
  'Die größte Person am Tisch und die kleinste stoßen an und trinken je 2 Schlucke.',
  'Wer als Letztes angekommen ist, trinkt 2 Schlucke.',
  'Alle, die heute schon getanzt haben, verteilen 1 Schluck. Wer noch nicht getanzt hat, trinkt 2 und tanzt jetzt 5 Sekunden.',
  '{{player}} wählt einen Partner. Beide müssen gleichzeitig ein Lied anstimmen, ohne sich abzusprechen. Stimmen sie dasselbe an, trinken alle anderen 2 Schlucke.',
  'Schnell-Reim: {{player}} sagt ein Wort, reihum muss jeder ein Reimwort nennen. Wer keins findet, trinkt 2 Schlucke.',
  'Gegenteil-Runde: {{player}} sagt ein Wort, die nächste Person sagt das Gegenteil und ein neues Wort. Wer zögert, trinkt 2 Schlucke.',
  'Emoji-Pantomime: {{player}} macht ein Gesicht wie ein bekanntes Emoji. Wer es zuerst errät, verteilt 2 Schlucke.',
  'Filmtitel-Kette: {{player}} nennt einen Film, der nächste nennt einen Schauspieler daraus, dann einen anderen Film mit ihm. Wer hängt, trinkt 2 Schlucke.',
  'Promi-Kette: {{player}} nennt einen Promi, der nächste einen, dessen Vorname mit dem Anfangsbuchstaben des Nachnamens beginnt. Wer hängt, trinkt 2 Schlucke.',
  'Länder-Kette: Jedes Land muss mit dem letzten Buchstaben des vorherigen beginnen. {{player}} startet. Wer hängt, trinkt 2 Schlucke.',
  'Städte-Kette: Jede Stadt muss mit dem letzten Buchstaben der vorherigen beginnen. {{player}} startet. Wer stockt, trinkt 2 Schlucke.',
  'Wer am schnellsten den Refrain von "Macarena" singen kann, verteilt 3 Schlucke. Alle versuchen es gleichzeitig.',
  'Lieblingssong-Runde: Reihum nennt jeder seinen aktuellen Lieblingssong. Wer einen Song nennt, den niemand sonst kennt, trinkt 2 Schlucke.',
  'Sing-Along-Richter: {{player}} und {{player}} singen gleichzeitig verschiedene Songs. Wer zuerst lacht oder abbricht, trinkt 2 Schlucke.',
  'Kuh-Ruf: Alle muhen gleichzeitig wie eine Kuh. {{player}} kürt die beste Kuh, diese verteilt 2 Schlucke.',
  'Party-Schlachtruf: {{player}} ruft "Wer hat Durst?", alle antworten "Wir!" und trinken 2 Schlucke.',
  'Alle trinken so viele Schlucke, wie {{player}} gerade Finger hochhält. Maximal 4.',
  'Glücksrad: {{player}} zeigt mit geschlossenen Augen im Kreis und stoppt. Die getroffene Person trinkt 2 Schlucke.',
  'Zahlenraten der Runde: Alle schätzen, wie viele Gläser gerade auf dem Tisch stehen. Wer am weitesten danebenliegt, trinkt 2 Schlucke.',
  'Wer hat zuerst Geburtstag im Jahr? Die Runde sortiert sich gedanklich. Die Person mit dem nächsten Geburtstag verteilt 3 Schlucke.',
  'Alle, die heute schon ein Foto gemacht haben, trinken 1 Schluck. Wer heute noch keins gemacht hat, verteilt 1 Schluck.',
  'Werwolf-Moment: Alle heulen gleichzeitig wie ein Wolf. Wer nicht mitheult, trinkt 2 Schlucke.',
  'Fangesang: Alle singen "Oh wie ist das schön" im Stadion-Stil. Wer am leisesten ist, trinkt 2 Schlucke.',
  'Seemannslied: Alle singen "What Shall We Do with the Drunken Sailor" und schunkeln. Wer nicht mitmacht, trinkt 2 Schlucke.',
  'Partyhits-Medley: Reihum singt jeder eine Zeile aus einem anderen Partyhit. Wer keinen mehr weiß, trinkt 2 Schlucke.',
  'Name that Tune: {{player}} klopft den Rhythmus eines Songs auf den Tisch. Wer ihn errät, verteilt 3 Schlucke.',
  'Hit-Jahr: {{player}} nennt einen Song, alle schätzen das Erscheinungsjahr. Wer am weitesten danebenliegt, trinkt 2 Schlucke.',
  'Wer singt das? {{player}} singt einen Refrain an, die Runde nennt den Interpreten. Wer zuerst richtig liegt, verteilt 2 Schlucke.',
  'Englisch auf Deutsch: {{player}} übersetzt einen bekannten Songtitel wörtlich ins Deutsche. Wer das Original errät, verteilt 2 Schlucke.',
  'Instrumenten-Band: Jeder sucht sich ein Luftinstrument aus und alle spielen gemeinsam "Smoke on the Water". Wer zuerst aus der Rolle fällt, trinkt 2 Schlucke.',
  'Zeitlupen-Prost: Alle stoßen in extremer Zeitlupe an. Wer zuerst normal schnell wird, trinkt 2 Schlucke.',
  'Die Person, die zuletzt gelacht hat, trinkt 2 Schlucke.',
  'Wer gerade am lautesten redet, trinkt 2 Schlucke. Auf 3 zeigen alle auf diese Person.',
  'Augen zu und zeigen: Alle schließen die Augen und zeigen auf {{player}}. Wer am weitesten daneben zeigt, trinkt 2 Schlucke.',
  'Wer schafft es, zuerst ein Lied zu nennen, das alle am Tisch kennen? {{player}} prüft. Der Gewinner verteilt 2 Schlucke.',
  'Lieder mit Tieren: Reihum nennt jeder einen Song mit einem Tier im Titel. {{player}} beginnt. Wer hängt, trinkt 2 Schlucke.',
  'Klatsch-Kreis: {{player}} klatscht und schickt das Klatschen nach links. Es soll 3 Runden lang immer schneller werden. Wer den Klatscher verpasst, trinkt 2 Schlucke.',
  'Gemeinsam lachen: Alle lachen 10 Sekunden lang künstlich. Wer zuerst echt lachen muss, verteilt 2 Schlucke.',
  'Schnapp das Wort: {{player}} erzählt eine kurze Geschichte. Jedes Mal, wenn das Wort "und" fällt, klopfen alle auf den Tisch. Wer zu spät klopft, trinkt 2 Schlucke.',
  'Konzert-Feeling: Alle halten ihr Handy-Licht oder ein imaginäres Feuerzeug hoch und schwenken es. Wer zuletzt dabei ist, trinkt 2 Schlucke.',
  'Die Runde singt gemeinsam "Zehn kleine Jägermeister" so weit sie kommt. Wer zuerst den Text verliert, trinkt 2 Schlucke.',
  'Ballermann-Moment: Alle singen gemeinsam "Mallorca, da bin ich daheim" oder einen anderen Malle-Hit. Wer nicht mitsingt, trinkt 2 Schlucke.',
  'Alle stellen sich vor, sie sind auf einem Rave, und tanzen 10 Sekunden mit erhobenen Händen. Wer zuerst aufhört, trinkt 2 Schlucke.',
  'Partyrunde: Jeder nennt reihum den besten Partysong seiner Schulzeit. Wer keinen weiß, trinkt 2 Schlucke.',
  'Pinguin-Parade: Alle watscheln im Sitzen wie Pinguine und machen Pinguingeräusche. Wer zuerst lacht, trinkt 2 Schlucke.',
];
