export const sexualTasks: string[] = [
  'Ich hab noch nie jemanden beim ersten Date geküsst. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie einen Anmachspruch benutzt, der tatsächlich funktioniert hat. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie in einem Club mit einer fremden Person rumgeknutscht. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie jemanden auf einer Dating-App angeschrieben und dann geghostet. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie für eine Lehrkraft geschwärmt. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie ein Date vorzeitig abgebrochen. Wer schon, trinkt 2 Schlucke.',
  'Ich hab mich noch nie im Urlaub Hals über Kopf verliebt. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie eine Nachricht für meinen Crush aus Versehen in den falschen Chat geschickt. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie beim Flaschendrehen vor einem Kuss gekniffen. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie mit jemandem aus dem Freundeskreis meines Ex geflirtet. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie einen Knutschfleck mit einem Schal versteckt. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie das Profil eines Crushs bis ganz nach unten durchgescrollt. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie versehentlich ein uraltes Foto meines Crushs geliked. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie während eines Dates den Namen der Person vergessen. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie zwei Dates am selben Tag gehabt. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie jemanden geküsst, dessen Namen ich nicht kannte. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie betrunken eine Liebeserklärung verschickt. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie eine Beziehung per Textnachricht beendet. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie auf der Rückbank eines Taxis geknutscht. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie einen Kuss unter einem Mistelzweig bekommen. Wer schon, trinkt 1 Schluck.',
  'Ich hab noch nie auf einer Hochzeit mit jemandem geflirtet. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie ein Blind Date gehabt. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie einen Liebesbrief geschrieben. Wer schon, trinkt 1 Schluck.',
  'Ich hab noch nie mit einer Person aus der Arbeit geknutscht. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie so getan, als wäre ich vergeben, um jemanden abzuwimmeln. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie meine Nummer auf eine Serviette geschrieben. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie in der Öffentlichkeit so wild geknutscht, dass sich jemand beschwert hat. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie im Kino mehr geknutscht als den Film geschaut. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie für die Person geschwärmt, mit der eine gute Freundin oder ein guter Freund zusammen war. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie ein Outfit nur getragen, um einer bestimmten Person zu gefallen. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie heimlich für jemanden aus dieser Runde geschwärmt. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie jemanden aus dieser Runde geküsst. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie auf einer Party im Badezimmer geknutscht. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie am Morgen danach auf Zehenspitzen eine fremde Wohnung verlassen. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie ein Date vorher im Internet komplett durchleuchtet. Wer schon, trinkt 1 Schluck.',
  'Ich hab noch nie beim Küssen aus Versehen jemandem auf die Lippe gebissen. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie eine Sprachnachricht an meinen Crush zehnmal neu aufgenommen. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie geflirtet, nur um ein Getränk ausgegeben zu bekommen. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie ein Date mit einer Person gehabt, die mehr als 10 Jahre älter war. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie mit meinem Ex wieder etwas angefangen. Wer schon, trinkt 3 Schlucke.',
  'Ich hab noch nie eine Fernbeziehung geführt. Wer schon, trinkt 1 Schluck.',
  'Ich hab noch nie auf der Tanzfläche absichtlich jemandem schöne Augen gemacht. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie ein Selfie nur für meinen Crush gemacht. Wer schon, trinkt 2 Schlucke.',
  'Ich hab noch nie am Strand geknutscht. Wer schon, trinkt 2 Schlucke.',
  'Alle, die schon mal ein Date über eine Dating-App hatten, trinken 2 Schlucke.',
  'Alle, die schon mal im Regen geküsst wurden, trinken 2 Schlucke.',
  'Alle, die schon mal beim Speed Dating waren, trinken 2 Schlucke.',
  'Alle, die schon mal mit jemandem geknutscht haben, den sie am selben Abend kennengelernt haben, trinken 3 Schlucke.',
  'Alle, die schon mal einen Korb bekommen haben, stoßen an und trinken 1 Schluck.',
  'Alle, die schon mal einen Korb verteilt haben, trinken 2 Schlucke.',
  'Alle, die gerade verliebt sind, trinken 2 Schlucke.',
  'Alle, die gerade Single sind, trinken 2 Schlucke auf die Freiheit.',
  'Alle, die schon mal verlobt oder verheiratet waren, trinken 2 Schlucke.',
  'Alle, die schon mal einen Knutschfleck hatten, trinken 2 Schlucke.',
  'Alle, die schon mal einen Crush online gestalkt haben, trinken 2 Schlucke.',
  'Alle, die schon mal geflirtet haben, um einem Strafzettel zu entgehen, trinken 3 Schlucke.',
  'Alle, die schon mal für ein Date gekocht haben, trinken 1 Schluck.',
  'Alle, die nach einem Date schon mal nie wieder etwas gehört haben, trinken 2 Schlucke.',
  'Alle, die schon mal selbst jemanden geghostet haben, trinken 3 Schlucke.',
  'Alle, die schon mal eine Freundschaft Plus hatten, trinken 3 Schlucke.',
  'Alle, die Liebeskummer schon mal mit Eiscreme und Schnulzen bekämpft haben, trinken 1 Schluck.',
  'Alle, die schon mal einen Heiratsantrag bekommen haben, trinken 2 Schlucke.',
  'Alle, die schon mal auf einem Festival geknutscht haben, trinken 2 Schlucke.',
  'Alle, die schon mal ein Date mit jemandem aus dieser Runde hatten, trinken 3 Schlucke.',
  'Alle, die schon mal mehr als 3 Menschen in einer Woche geküsst haben, trinken 3 Schlucke.',
  'Alle, die schon mal einen Kosenamen benutzt haben, der ihnen heute peinlich ist, trinken 2 Schlucke.',
  'Alle, die schon mal ein Pärchenkostüm getragen haben, trinken 2 Schlucke.',
  'Alle, die beim Küssen manchmal die Augen offen lassen, trinken 2 Schlucke.',
  'Alle, die schon mal ein Date durch Kleckern oder Stolpern ruiniert haben, trinken 2 Schlucke.',
  'Alle, die schon mal einen Pärchenurlaub gemacht haben, trinken 1 Schluck.',
  'Alle, die einem Match schon mal vor lauter Nervosität nicht geantwortet haben, trinken 2 Schlucke.',
  'Alle, die schon mal ein Date hatten, das ganz anders aussah als auf den Fotos, trinken 2 Schlucke.',
  'Alle, die schon mal einen Brautstrauß gefangen haben, trinken 2 Schlucke.',
  'Alle, die schon mal einer fremden Person in einer Bar ein Getränk geschickt haben, trinken 2 Schlucke.',
  'Alle, die schon mal für eine berühmte Person geschwärmt haben, die doppelt so alt war, trinken 1 Schluck.',
  'Alle, die nach einem Liebesfilm schon mal den Ex vermisst haben, trinken 2 Schlucke.',
  'Alle, die schon mal einen Kurs nur wegen einer bestimmten Person belegt haben, trinken 3 Schlucke.',
  'Alle, die schon mal mit jemandem zusammen waren, den die eigenen Eltern nicht mochten, trinken 2 Schlucke.',
  'Alle, die direkt nach einem Date schon mal die beste Freundin oder den besten Freund angerufen haben, trinken 1 Schluck.',
  'Alle, die schon mal einen Flirttipp aus dem Internet ausprobiert haben, trinken 2 Schlucke.',
  'Abstimmung: Wer flirtet am ehesten mit der Bedienung, um einen Shot gratis zu bekommen? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer hat die meisten Dating-Apps auf dem Handy? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer küsst am besten? Die Person mit den meisten Stimmen verteilt 3 Schlucke.',
  'Abstimmung: Wer heiratet am ehesten nach nur 3 Monaten Beziehung? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer schreibt am ehesten um 3 Uhr nachts dem eigenen Crush? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer hat den besten Anmachspruch auf Lager? Die Person mit den meisten Stimmen trägt ihn vor oder trinkt 3 Schlucke.',
  'Abstimmung: Wer wird heute Abend am ehesten noch angeflirtet? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer hat die chaotischste Dating-Vergangenheit? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer ist heimlich am romantischsten? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer verliebt sich am schnellsten? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer hat die meisten Herzen gebrochen? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer flirtet am ehesten, ohne es selbst zu merken? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer landet am ehesten in einer Datingshow im Fernsehen? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer hat das schönste Lächeln in der Runde? Die Person mit den meisten Stimmen verteilt 2 Schlucke.',
  'Abstimmung: Wer verliebt sich am ehesten in eine Urlaubsbekanntschaft? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer wäre das beste Blind Date? Die Person mit den meisten Stimmen verteilt 3 Schlucke.',
  'Abstimmung: Wer plant das romantischste Date? Die Person mit den meisten Stimmen verteilt 2 Schlucke.',
  'Abstimmung: Wer bekommt in einer Bar am ehesten eine Nummer zugesteckt? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer ist am ehesten noch mit dem Ex befreundet? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer redet beim ersten Date am ehesten über den Ex? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer hat die verführerischste Stimme? Die Person mit den meisten Stimmen flüstert der linken Nachbarperson etwas Nettes ins Ohr oder trinkt 3 Schlucke.',
  'Abstimmung: Wer ist am ehesten eifersüchtig? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer hat die besten Flirt-Moves auf der Tanzfläche? Die Person mit den meisten Stimmen zeigt sie 10 Sekunden lang oder trinkt 3 Schlucke.',
  'Abstimmung: Wer schickt die frechsten Nachrichten? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer wird beim Flirten am ehesten rot? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer hätte am ehesten eine heimliche Büroromanze? Die Person mit den meisten Stimmen trinkt 2 Schlucke.',
  'Abstimmung: Wer hat die schönsten Augen in der Runde? Die Person mit den meisten Stimmen verteilt 2 Schlucke.',
  '{{player}}, beantworte ehrlich, wie alt du bei deinem ersten Kuss warst, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, wer aus dieser Runde das beste Date wäre, oder trink 4 Schlucke.',
  '{{player}}, beantworte ehrlich, was dich an einer Person sofort anzieht, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, was das Frechste ist, das du je zu einem Crush gesagt hast, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, wie viele Dates du dieses Jahr schon hattest, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, ob du gerade auf jemanden stehst, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, was dein größter Abturner beim ersten Date ist, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, was dich heimlich total anmacht, jugendfrei bitte, oder trink 4 Schlucke.',
  '{{player}}, beantworte ehrlich, an welchem ungewöhnlichsten Ort du schon geknutscht hast, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, welche berühmte Person dein Freifahrtschein wäre, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, ob du schon mal in eine Person aus dieser Runde verknallt warst, oder trink 4 Schlucke.',
  '{{player}}, beantworte ehrlich, wie lange du nach einem Date wartest, bevor du schreibst, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, was in der letzten Nachricht an deinen Crush stand, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, ob du jemanden schon mal nur wegen eines guten Kusses wiedergetroffen hast, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, was die kitschigste Sache ist, die du je für eine Person gemacht hast, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, was dein schlechtestes Date war und warum, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, ob du beim Flirten eher den ersten Schritt machst oder lieber wartest, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, wann du zuletzt jemanden geküsst hast, oder trink 3 Schlucke.',
  '{{player}}, beschreib ohne Namen die Person, die dir zuletzt Herzklopfen gemacht hat, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, wie viele Menschen du ungefähr schon geküsst hast, oder trink 4 Schlucke.',
  '{{player}}, beantworte ehrlich, was das Peinlichste in deinem Dating-Profil ist oder war, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, welches Kleidungsstück an anderen dich schwach macht, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, ob du schon mal in jemanden verliebt warst, der nichts davon wusste, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, bei welchem Song du sofort in Knutschstimmung kommst, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, was du in einer Beziehung niemals verzeihen würdest, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, ob du ein Date schon mal nur wegen des Essens angenommen hast, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, wie lange deine längste Zeit ohne Kuss war, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, was der romantischste Moment deines Lebens war, oder trink 2 Schlucke.',
  '{{player}}, beantworte ehrlich, welche Eigenschaft deines Ex du heimlich vermisst, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, mit wem aus dieser Runde du am ehesten ein Pärchenkostüm tragen würdest, oder trink 3 Schlucke.',
  '{{player}}, beantworte ehrlich, ob du schon mal jemanden absichtlich eifersüchtig gemacht hast, oder trink 3 Schlucke.',
  '{{player}}, erzähl, wie dich zuletzt jemand angeflirtet hat, oder trink 2 Schlucke.',
  '{{player}}, sag {{player}} deinen besten Anmachspruch oder trink 3 Schlucke.',
  '{{player}}, erfinde einen Anmachspruch mit dem Wort Kartoffel und probier ihn an {{player}} aus, oder trink 3 Schlucke.',
  '{{player}}, sag {{player}} den schlechtesten Anmachspruch, den du kennst. Wer lacht, trinkt 2 Schlucke.',
  '{{player}}, bring {{player}} mit einem Anmachspruch zum Lachen. Klappt es, trinkt die angeflirtete Person 2 Schlucke, sonst trinkst du 2.',
  '{{player}}, flirte {{player}} 15 Sekunden lang nur mit Blicken an. Wer zuerst lacht, trinkt 2 Schlucke.',
  'Reihum sagt jede Person einen Anmachspruch. Die Runde wählt den schlechtesten, und wer ihn gesagt hat, trinkt 3 Schlucke.',
  '{{player}}, sag {{player}} einen Anmachspruch im Stil eines Wetterberichts oder trink 3 Schlucke.',
  '{{player}}, sag {{player}} einen Anmachspruch auf Englisch mit deinem besten Akzent oder trink 2 Schlucke.',
  '{{player}}, denk dir einen Anmachspruch über Mathe aus und sag ihn {{player}}, oder trink 3 Schlucke.',
  '{{player}}, sag {{player}} einen Anmachspruch, als wärst du in einer Seifenoper, oder trink 3 Schlucke.',
  '{{player}}, sag {{player}} einen Anmachspruch in Zeitlupe oder trink 2 Schlucke.',
  '{{player}}, sag der Person links von dir einen Anmachspruch und spiel dabei extrem schüchtern, oder trink 2 Schlucke.',
  '{{player}}, verrate den Anmachspruch, mit dem du selbst schon mal angesprochen wurdest, oder trink 2 Schlucke.',
  '{{player}} sagt einen Anmachspruch in die Runde. Alle, die darauf reinfallen würden, trinken 2 Schlucke.',
  '{{player}}, sag {{player}} einen Anmachspruch in einem Dialekt deiner Wahl oder trink 3 Schlucke.',
  '{{player}}, sag {{player}} einen Anmachspruch, der sich reimt, oder trink 3 Schlucke.',
  '{{player}}, mach {{player}} ein ehrliches Kompliment über das Aussehen oder trink 2 Schlucke.',
  '{{player}}, sag {{player}}, was du an dieser Person am attraktivsten findest, oder trink 3 Schlucke.',
  '{{player}}, mach jeder Person in der Runde ein flirtendes Kompliment oder trink 4 Schlucke.',
  '{{player}}, mach {{player}} ein Kompliment und halte dabei Blickkontakt. Wer zuerst wegschaut, trinkt 2 Schlucke.',
  '{{player}}, beschreib {{player}} in 3 Wörtern, die verführerisch klingen, oder trink 2 Schlucke.',
  '{{player}}, sag {{player}} mit deiner verführerischsten Stimme, was dir an dem Outfit heute gefällt, oder trink 3 Schlucke.',
  '{{player}}, mach {{player}} ein Kompliment über die Stimme oder trink 2 Schlucke.',
  'Reihum macht jede Person der rechten Nachbarperson ein Kompliment. Wer rot wird, trinkt 2 Schlucke.',
  '{{player}}, mach der Person ein Kompliment, die heute für dich am heißesten angezogen ist, oder trink 3 Schlucke.',
  '{{player}}, sag {{player}} 3 Dinge, die dir bei einem Date mit dieser Person gefallen würden, oder trink 3 Schlucke.',
  '{{player}}, zeig pantomimisch, wie du jemanden in einer Bar anflirtest. Gibt die Runde weniger als 5 von 10 Punkten, trinkst du 2 Schlucke.',
  '{{player}}, spiel pantomimisch ein erstes Date nach, das völlig schiefgeht, oder trink 3 Schlucke.',
  '{{player}}, zeig 5 Sekunden lang deinen verführerischsten Blick oder trink 2 Schlucke.',
  '{{player}}, zwinker {{player}} so verführerisch wie möglich zu. Wer lacht, trinkt 2 Schlucke.',
  '{{player}}, zeig deinen besten Flirt-Hüftschwung oder trink 3 Schlucke.',
  '{{player}}, spiel pantomimisch, wie du dich auf der Tanzfläche an deinen Crush heranschleichst, oder trink 2 Schlucke.',
  '{{player}}, stell ohne Worte dar, wie du nach einem Date auf den Abschiedskuss wartest, oder trink 2 Schlucke.',
  '{{player}}, zeig pantomimisch, wie du heimlich zu deinem Crush rüberschaust. Findet die Runde es unglaubwürdig, trinkst du 2 Schlucke.',
  '{{player}}, spiel deinen Lieblingskuss aus einem Film mit einem Kissen nach oder trink 3 Schlucke.',
  '{{player}}, lauf 10 Sekunden lang wie auf einem Laufsteg durch den Raum und gib alles, oder trink 3 Schlucke.',
  '{{player}}, tanz 15 Sekunden lang verführerisch zu einem Lied, das die Runde aussucht, oder trink 3 Schlucke.',
  '{{player}}, beiß dir verführerisch auf die Lippe und schau dabei {{player}} an. Wer zuerst lacht, trinkt 2 Schlucke.',
  '{{player}}, überreiche {{player}} wie in einer Datingshow eine imaginäre Rose oder trink 2 Schlucke.',
  '{{player}}, spiel eine Flirtszene pantomimisch vor. Errät {{player}} nicht, wo sie spielt, trinkt ihr beide 1 Schluck.',
  '{{player}}, gib {{player}} einen Kuss auf die Wange oder trink 3 Schlucke.',
  '{{player}}, gib {{player}} einen Handkuss wie im Mittelalter oder trink 2 Schlucke.',
  '{{player}}, gib der Person mit dem schönsten Lächeln einen Kuss auf die Wange oder trink 3 Schlucke.',
  '{{player}}, wirf {{player}} einen Luftkuss zu. Wird er nicht gefangen, trinkt ihr beide 1 Schluck.',
  '{{player}}, gib {{player}} einen Eskimokuss mit der Nase oder trink 2 Schlucke.',
  '{{player}}, küss deinen eigenen Handrücken so leidenschaftlich wie möglich oder trink 2 Schlucke.',
  '{{player}}, gib {{player}} einen Kuss auf die Stirn oder trink 2 Schlucke.',
  '{{player}} und {{player}}, gebt euch ein Küsschen auf die Wange oder trinkt beide 2 Schlucke.',
  '{{player}}, flüstere {{player}} ein Detail über deinen letzten Kuss ins Ohr oder trink 3 Schlucke.',
  '{{player}}, massier {{player}} 10 Sekunden lang die Schultern oder trink 3 Schlucke.',
  '{{player}}, lass dir von einer Person deiner Wahl 10 Sekunden lang die Schultern massieren, wenn sie mag, oder trink 2 Schlucke.',
  '{{player}}, massier {{player}} 10 Sekunden lang die Hand oder trink 2 Schlucke.',
  '{{player}}, kraul {{player}} 10 Sekunden lang den Nacken oder trink 3 Schlucke.',
  '{{player}}, schreib {{player}} mit dem Finger ein Flirtwort auf den Rücken. Errät die Person es nicht, trinkt sie 1 Schluck. Weigerst du dich, trinkst du 3 Schlucke.',
  '{{player}}, halte für die nächsten 3 Aufgaben Händchen mit {{player}} oder trink 3 Schlucke.',
  '{{player}}, leg 1 Minute lang deinen Kopf auf die Schulter von {{player}} oder trink 3 Schlucke.',
  '{{player}} und {{player}}, tanzt 20 Sekunden lang Engtanz oder trinkt beide 2 Schlucke.',
  '{{player}}, umarm {{player}} 10 Sekunden lang, als hättet ihr euch ewig nicht gesehen, oder trink 3 Schlucke.',
  '{{player}} und {{player}}, schaut euch 20 Sekunden lang tief in die Augen. Wer zuerst lacht oder wegschaut, trinkt 3 Schlucke.',
  '{{player}}, flüstere {{player}} den Titel des Liedes ins Ohr, zu dem du am liebsten mit dieser Person tanzen würdest, oder trink 3 Schlucke.',
  '{{player}}, füttere {{player}} mit einem Snack oder trink 2 Schlucke.',
  '{{player}}, zieh deine Jacke oder eine Socke aus oder trink 3 Schlucke.',
  '{{player}}, tausch mit {{player}} bis zum Ende des Spiels ein Accessoire wie Ring, Uhr oder Kette, oder trink 2 Schlucke.',
  '{{player}} und {{player}} spielen 30 Sekunden lang ein Blind Date, bei dem es sofort funkt. Wer aus der Rolle fällt, trinkt 3 Schlucke.',
  '{{player}} und {{player}} spielen ein Blind Date, bei dem beide extrem nervös sind. Wer zuerst lacht, trinkt 3 Schlucke.',
  '{{player}}, spiel mit {{player}} ein erstes Date in einem Fast-Food-Restaurant nach. Wer zuerst lacht, trinkt 2 Schlucke.',
  '{{player}}, bitte {{player}} wie in einer Datingshow ganz dramatisch um ein zweites Date oder trink 3 Schlucke.',
  '{{player}}, verabschiede dich von {{player}} wie nach einem perfekten ersten Date oder trink 3 Schlucke.',
  '{{player}}, lade {{player}} so geschwollen wie im Mittelalter zu einem Date ein oder trink 2 Schlucke.',
  '{{player}} und {{player}} spielen ein Blind Date, bei dem sich herausstellt, dass beide Vampire sind. Wer zuerst lacht, trinkt 2 Schlucke.',
  '{{player}}, stell dich {{player}} in 30 Sekunden vor wie beim Speed Dating. Sagt die Person kein Match, trinkst du 2 Schlucke.',
  '{{player}}, spiel deinem Date {{player}} vor, wie du die Rechnung übernehmen willst, aber deine Karte abgelehnt wird. Wer zuerst lacht, trinkt 2 Schlucke.',
  '{{player}}, mach {{player}} einen dramatischen Heiratsantrag auf Knien oder trink 3 Schlucke.',
  '{{player}}, mach mit {{player}} Schluss, als wärt ihr in einer Telenovela, oder trink 2 Schlucke.',
  '{{player}} und {{player}} spielen ein Paar, das seit 50 Jahren verheiratet ist und über das erste Date streitet. Wer zuerst lacht, trinkt 2 Schlucke.',
  '{{player}}, verrate, welchen Körperteil du an dir selbst am meisten magst, oder trink 2 Schlucke.',
  '{{player}}, verrate, welchen Körperteil du an anderen zuerst bemerkst, oder trink 2 Schlucke.',
  '{{player}}, sag, welchen Körperteil von {{player}} du am schönsten findest, oder trink 3 Schlucke.',
  '{{player}}, präsentiere deinen schönsten jugendfreien Körperteil mit einer Modelpose oder trink 2 Schlucke.',
  '{{player}}, erzähl deine peinlichste Date-Geschichte oder trink 4 Schlucke.',
  'Reihum erzählt jede Person ihr peinlichstes Date in einem Satz. Die Person mit der schlimmsten Geschichte verteilt 4 Schlucke.',
  '{{player}}, erzähl von dem Moment, in dem du bei einem Date am meisten rot geworden bist, oder trink 3 Schlucke.',
  '{{player}}, erzähl, was beim schlimmsten Kuss deines Lebens schiefging, oder trink 3 Schlucke.',
  '{{player}}, erzähl von einem Date, bei dem du am liebsten heimlich abgehauen wärst, oder trink 3 Schlucke.',
  '{{player}}, verrate die verrückteste Ausrede, mit der du ein Date abgesagt hast, oder trink 3 Schlucke.',
  '{{player}}, erzähl, wie du deinen letzten Crush kennengelernt hast, oder trink 2 Schlucke.',
  '{{player}}, verrate die schrägste Nachricht, die du je auf einer Dating-App bekommen hast, oder trink 3 Schlucke.',
  '{{player}}, erzähl, wann dich zuletzt jemand richtig nervös gemacht hat, oder trink 2 Schlucke.',
  'Wer in der Runde die längste Beziehung hatte, verteilt 3 Schlucke.',
  'Wer zuletzt geküsst wurde, trinkt 2 Schlucke.',
  'Wer zuletzt ein Date hatte, verteilt 2 Schlucke.',
  'Wer am längsten Single ist, verteilt 3 Schlucke.',
  'Alle, die in einer Beziehung sind, stoßen miteinander an und trinken 2 Schlucke.',
  'Wer heute schon geflirtet hat, trinkt 2 Schlucke.',
  'Wer gerade eine Dating-App auf dem Handy hat, trinkt 2 Schlucke.',
  'Wer heute Abend gern noch mit jemandem aus der Runde tanzen würde, trinkt 2 Schlucke.',
  'Wer ein Tattoo an einer Stelle hat, die man gerade nicht sieht, trinkt 2 Schlucke.',
  'Wer heute farblich passende Unterwäsche trägt, trinkt 2 Schlucke.',
  'Wer einen Crush im Handy unter einem Decknamen gespeichert hat, trinkt 3 Schlucke.',
  'Wer glaubt, richtig gut zu küssen, trinkt 2 Schlucke.',
  'Wer schon mal für jemanden aus der Nachbarschaft geschwärmt hat, trinkt 2 Schlucke.',
  'Wer schon mal heimlich ein Foto vom eigenen Date an die Freundesgruppe geschickt hat, trinkt 2 Schlucke.',
  '{{player}}, beende für die nächsten 3 Aufgaben jeden Satz mit dem Wort Schatz. Jedes Vergessen kostet 1 Schluck.',
  '{{player}}, gib {{player}} einen ehrlichen Dating-Tipp oder trink 2 Schlucke.',
  '{{player}}, nenne die Person in der Runde, die am besten riecht, oder trink 3 Schlucke.',
  '{{player}}, stell {{player}} eine freche Frage. Wird sie nicht beantwortet, trinkt die gefragte Person 3 Schlucke.',
  '{{player}}, trag {{player}} 3 Sätze vor, die aus einem kitschigen Liebesroman stammen könnten, oder trink 2 Schlucke.',
  '{{player}}, lies die letzte Nachricht vor, in der du ein Herz verschickt hast, oder trink 3 Schlucke.',
  '{{player}}, zeig der Runde dein letztes Selfie oder trink 3 Schlucke.',
  '{{player}}, zeig der Runde dein Dating-Profil, falls du eins hast, oder trink 3 Schlucke.',
  '{{player}}, beschreib dich in 2 Sätzen wie in einer Kontaktanzeige oder trink 2 Schlucke.',
  '{{player}}, mach deinem Getränk eine verführerische Liebeserklärung und trink danach 2 Schlucke.',
  '{{player}}, verrate deine liebste Stelle für einen Kuss, jugendfrei bitte, oder trink 3 Schlucke.',
  '{{player}}, sag, ob du lieber im Dunkeln oder bei Kerzenlicht knutschst, oder trink 2 Schlucke.',
  '{{player}}, wähle: Kuss im Regen oder Kuss im Riesenrad. Alle, die anders gewählt hätten, trinken 1 Schluck.',
  '{{player}}, beschreib dein perfektes erstes Date in 3 Sätzen oder trink 2 Schlucke.',
  '{{player}}, beschreib den Typ von {{player}} in 3 Wörtern. Liegst du laut der Person daneben, trinkst du 2 Schlucke.',
  '{{player}}, flüstere {{player}} einen frechen Satz ins Ohr. Muss die Person grinsen, trinkt sie 2 Schlucke, sonst trinkst du 2.',
  'Kategorie Orte für ein erstes Date: Reihum nennt jede Person einen. Wer nichts mehr weiß, trinkt 2 Schlucke.',
  'Kategorie Kosenamen: Reihum nennt jede Person einen. Wer keinen mehr weiß, trinkt 2 Schlucke.',
  'Kategorie berühmte Filmpaare: Reihum nennt jede Person eins. Wer keins mehr weiß, trinkt 2 Schlucke.',
  'Kategorie andere Wörter für Küssen: Reihum nennt jede Person eins. Wer keins mehr weiß, trinkt 2 Schlucke.',
  'Kategorie Liebeslieder: Reihum nennt jede Person eins. Wer keins mehr weiß, trinkt 2 Schlucke.',
  'Kategorie Dinge, die auf einem ersten Date schiefgehen können: Reihum nennt jede Person eins. Wer nichts mehr weiß, trinkt 2 Schlucke.',
  '{{player}}, sing {{player}} die erste Zeile eines Liebeslieds vor oder trink 3 Schlucke.',
  '{{player}}, mach {{player}} eine übertriebene Liebeserklärung wie in einem Kitschfilm oder trink 3 Schlucke.',
  '{{player}}, dichte 2 Zeilen über die Lippen von {{player}} oder trink 3 Schlucke.',
  '{{player}}, gib {{player}} einen Kosenamen, der bis zum Ende des Spiels gilt, oder trink 2 Schlucke.',
  '{{player}}, verkupple zwei Personen aus der Runde. Die beiden stoßen an und trinken 2 Schlucke.',
  '{{player}}, wähle ein Trink-Date. Für die nächsten 3 Aufgaben trinkt diese Person immer mit, wenn du trinkst.',
  '{{player}} und {{player}}, sagt gleichzeitig, was euch beim ersten Date wichtiger ist: Humor oder Aussehen. Sagt ihr Unterschiedliches, trinkt ihr beide 2 Schlucke.',
  '{{player}}, frag {{player}} so charmant wie möglich, ob ihr später noch zusammen tanzt, oder trink 2 Schlucke.',
  'Alle, die heute Abend schon jemandem aus der Runde verstohlen hinterhergeschaut haben, trinken 2 Schlucke.',
  '{{player}}, erzähl deinen frechsten Flirterfolg oder trink 3 Schlucke.',
  '{{player}}, verrate den kitschigsten Kosenamen, den du je bekommen hast, oder trink 2 Schlucke.',
  '{{player}}, verrate jugendfrei, was in deinem Nachttisch liegt, oder trink 4 Schlucke.',
  '{{player}}, verrate, welches Parfum an anderen dich schwach macht, oder trink 2 Schlucke.',
  '{{player}}, mach mit einer Person deiner Wahl ein Pärchen-Selfie, wenn sie mitmacht, oder trink 2 Schlucke.',
  'Wer schon mal ein Lied über eine verflossene Liebe in Dauerschleife gehört hat, trinkt 2 Schlucke.',
  'Wer noch eine Karte oder einen Brief von einem alten Crush aufbewahrt, trinkt 2 Schlucke.',
  'Wer schon mal für eine Zeichentrickfigur geschwärmt hat, trinkt 2 Schlucke.',
  'Wer schon mal beim Knutschen von den Eltern erwischt wurde, trinkt 3 Schlucke.',
  'Wer schon mal einen Partner oder eine Partnerin den Eltern vorgestellt hat, trinkt 1 Schluck.',
  'Wer schon mal den Valentinstag allein mit Pizza gefeiert hat, trinkt 1 Schluck.',
  'Wer schon mal ein Date im Museum hatte, trinkt 1 Schluck.',
  'Wer sich bei einem Date schon mal auf die Toilette verzogen hat, um sich per Handy Rat zu holen, trinkt 2 Schlucke.',
  'Wer auf einer Dating-App schon mal mit jemandem aus dem Bekanntenkreis gematcht hat, trinkt 2 Schlucke.',
  'Wer schon mal selbst einen Heiratsantrag gemacht hat, trinkt 2 Schlucke.',
  'Wer beim ersten Date schon mal die Rechnung geteilt hat, trinkt 1 Schluck.',
  'Wer Brillen an anderen sexy findet, trinkt 2 Schlucke.',
  'Wer auf Tattoos bei anderen steht, trinkt 2 Schlucke.',
  'Wer bei Grübchen schwach wird, trinkt 1 Schluck.',
  'Wer heute Abend noch auf einen Kuss hofft, trinkt 2 Schlucke.',
  'Wer eine Schwäche für tiefe Stimmen hat, trinkt 2 Schlucke.',
  'Wer schon mal einem Crush ein Lied gewidmet hat, trinkt 2 Schlucke.',
  'Wer beim Flirten schon mal so abgelenkt war, dass ein Glas umgekippt ist, trinkt 2 Schlucke.',
  'Wer noch einen Pulli von einem Ex oder Crush im Schrank hat, trinkt 2 Schlucke.',
  'Wer ein Gespräch mit dem Crush schon mal vor dem Spiegel geübt hat, trinkt 2 Schlucke.',
  'Wer auf einer Party schon mal den ganzen Abend nur mit einer einzigen Person verbracht hat, trinkt 2 Schlucke.',
  'Abstimmung: Wer hat heute Abend den besten Flirtblick drauf? Die Person mit den meisten Stimmen verteilt 2 Schlucke.',
  '{{player}}, beantworte ehrlich, ob du beim ersten Date lieber zum Abschied küsst oder dir den Kuss fürs zweite aufhebst, oder trink 2 Schlucke.',
];
