export const wahrheitTasks: string[] = [
  'Ich hab noch nie einen Liebesbrief geschrieben. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie so getan, als würde ich jemanden nicht sehen, um nicht grüßen zu müssen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie in der Schule abgeschrieben. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie einen Anruf ignoriert und danach behauptet, ich hätte geschlafen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie für einen Lehrer oder eine Lehrerin geschwärmt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie jemandem zurückgewunken, der gar nicht mich gemeint hat. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie eine Sprachnachricht über 5 Minuten verschickt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie ein Geschenk weiterverschenkt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie unter der Dusche eine ganze Konzertshow aufgeführt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie das Profil meines Ex bis ganz nach unten durchgescrollt. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie aus Versehen ein uraltes Foto von jemandem geliked. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie ein Treffen mit einer komplett erfundenen Ausrede abgesagt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie bei einem Date auf die Uhr geschaut und gehofft, dass es bald vorbei ist. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie jemanden geghostet. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie meinen eigenen Namen gegoogelt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie vor dem Spiegel ein Gespräch geübt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie so getan, als würde ich einen Witz verstehen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie Essen aus dem Kühlschrank meiner Mitbewohner genommen, ohne zu fragen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie eine Serie nur wegen eines Schauspielers weitergeschaut. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie eine Nachricht an die falsche Person geschickt. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie in einem Meeting oder in der Vorlesung geschlafen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie so getan, als hätte ich ein Buch gelesen, das ich nie aufgeschlagen habe. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie in einer Umkleidekabine ein Selfie gemacht. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie mit jemandem geflirtet, nur um etwas umsonst zu bekommen. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie eine Datingapp heruntergeladen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie bei meinem Alter geschummelt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie laut gepupst und es jemand anderem in die Schuhe geschoben. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie meine Hausaufgaben von jemand anderem machen lassen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie einen Chat gescreenshottet, um ihn meinen Freunden zu zeigen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie heimlich ein Gespräch am Nachbartisch belauscht. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie im Kino laut geschnarcht. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie jemanden nur wegen seiner Stimme süß gefunden. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie meinen Schwarm im Internet gestalkt. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie auf einer Party so getan, als würde ich jemanden kennen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie den Abwasch tagelang stehen lassen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie meine Eltern angelogen, wo ich übernachte. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie 2 Dates am selben Tag gehabt. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie den Geburtstag meiner besten Freundin oder meines besten Freundes vergessen. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie Karaoke gesungen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie einen Kurs nur wegen einer bestimmten Person belegt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie eine Nachricht geschrieben und sie ganz schnell wieder gelöscht. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie meinem Ex oder meiner Ex geschrieben, dass ich ihn oder sie vermisse. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie behauptet, mein Akku sei leer, um ein Gespräch zu beenden. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie im Urlaub jemanden geküsst, dessen Namen ich nicht kannte. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie einen gekauften Kuchen als selbst gebacken ausgegeben. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab mich noch nie in jemanden aus dieser Runde verknallt. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie so getan, als würde ich kein Deutsch sprechen, um jemanden loszuwerden. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie eine komplette Staffel an einem Wochenende durchgeschaut. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie im Bett gegessen und die Krümel einfach liegen lassen. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie einen Kollegen oder eine Kollegin heimlich süß gefunden. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie eine Prüfung verschlafen. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie den Namen meines Dates vergessen. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie einem Promi eine Nachricht geschrieben. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie im Restaurant gesagt, dass es super schmeckt, obwohl es furchtbar war. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie ein Lied einer Boyband komplett auswendig gekonnt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie auf einer Party in einer fremden Wohnung übernachtet. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie meinen eigenen Post mit einem Zweitaccount geliked. Wer schon mal, trinkt 3 Schlucke.',
  'Ich hab noch nie geschrieben, dass ich schon unterwegs bin, obwohl ich noch im Bett lag. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab mich noch nie vor dem Einsatz einer verlorenen Wette gedrückt. Wer schon mal, trinkt 2 Schlucke.',
  'Ich hab noch nie über jemanden gelästert, der direkt neben mir stand. Wer schon mal, trinkt 3 Schlucke.',

  'Alle, die schon mal bei einem Liebesfilm geweint haben, trinken 2 Schlucke.',
  'Alle, die heute schon mehr als 3 Stunden am Handy waren, trinken 2 Schlucke.',
  'Alle, die gerade in jemanden verknallt sind, trinken 3 Schlucke.',
  'Alle, die schon mal einen Tippfehler in einer wichtigen Nachricht erst nach dem Senden bemerkt haben, trinken 1 Schluck.',
  'Alle, die ihren Schwarm schon mal angelogen haben, um cooler zu wirken, trinken 2 Schlucke.',
  'Alle, die in der Schule schon mal nachsitzen mussten, trinken 2 Schlucke.',
  'Alle, die schon mal mit einem Ex wieder zusammengekommen sind, trinken 3 Schlucke.',
  'Alle, die schon mal "Sorry, hab das gerade erst gesehen" geschrieben haben, obwohl es nicht stimmte, trinken 2 Schlucke.',
  'Alle, die schon mal eine Ausrede erfunden haben, um nicht zu dieser Runde zu kommen, trinken 3 Schlucke.',
  'Alle, die im Club schon mal einen Korb bekommen haben, trinken 2 Schlucke.',
  'Alle, die sich vor einem Date schon mal einen Notfallanruf von Freunden bestellt haben, trinken 2 Schlucke.',
  'Alle, die schon mal mit jemandem aus dieser Runde geknutscht haben, trinken 3 Schlucke.',
  'Alle, die heimlich eine Lieblingsperson in dieser Runde haben, trinken 2 Schlucke.',
  'Alle, die ein Selfie schon mal mehr als 20 Mal wiederholt haben, trinken 2 Schlucke.',
  'Alle, die schon mal mit "Haha" geantwortet haben, ohne zu lachen, trinken 1 Schluck.',
  'Alle, die bei einem Vorstellungsgespräch schon mal geflunkert haben, trinken 2 Schlucke.',
  'Alle, die schon mal in einen Promi verliebt waren, trinken 2 Schlucke.',
  'Alle, die sich schon mal beim Chef oder bei einer Lehrerin eingeschleimt haben, trinken 2 Schlucke.',
  'Alle, die Liebeskummer schon mal mit einer ganzen Packung Eis bekämpft haben, trinken 2 Schlucke.',
  'Alle, die eine Lehrerin oder einen Lehrer schon mal aus Versehen Mama oder Papa genannt haben, trinken 3 Schlucke.',
  'Alle, die schon mal ein Telefonat vorgetäuscht haben, um niemandem begegnen zu müssen, trinken 2 Schlucke.',
  'Alle, die auf einer Party schon mal ihre Schuhe verloren haben, trinken 2 Schlucke.',
  'Alle, die einen Spitznamen hatten, den sie gehasst haben, trinken 2 Schlucke.',
  'Alle, die in der Öffentlichkeit schon mal gestolpert sind und so getan haben, als wäre nichts, trinken 2 Schlucke.',
  'Alle, die schon mal ein Tagebuch geführt haben, trinken 2 Schlucke.',
  'Alle, die schon mal einen Brief an ihr zukünftiges Ich geschrieben haben, trinken 1 Schluck.',
  'Alle, die auf einer Hochzeit schon mal jemanden angeflirtet haben, trinken 2 Schlucke.',
  'Alle, die schon mal ein Date abgesagt haben, weil die Serie gerade so spannend war, trinken 2 Schlucke.',
  'Alle, die schon mal ihren Vornamen mit dem Nachnamen ihres Schwarms ausprobiert haben, trinken 3 Schlucke.',
  'Alle, die schon mal "Du auch" gesagt haben, obwohl es überhaupt nicht gepasst hat, trinken 2 Schlucke.',
  'Alle, die sich schon mal einen Kuss im Regen gewünscht haben, trinken 1 Schluck.',
  'Alle, die ihre Freunde schon mal für ein Date versetzt haben, trinken 3 Schlucke.',
  'Alle, die schon mal jemanden an der Supermarktkasse süß fanden, trinken 1 Schluck.',
  'Alle, die im Urlaub schon mal einen Sommerflirt hatten, trinken 2 Schlucke.',
  'Alle, die betrunken schon mal jemanden angerufen haben, den sie besser nicht angerufen hätten, trinken 3 Schlucke.',
  'Alle, die schon mal einen Streit komplett per Textnachricht ausgetragen haben, trinken 2 Schlucke.',
  'Alle, die ihre Story schon mal vor einer bestimmten Person verborgen haben, trinken 2 Schlucke.',
  'Alle, die auf einer Party schon mal heimlich die Musik geändert haben, trinken 1 Schluck.',
  'Alle, die zum ersten Date schon mal zu spät gekommen sind, trinken 2 Schlucke.',
  'Alle, die schon mal etwas bestellt und nie ausgepackt haben, trinken 2 Schlucke.',
  'Alle, die in einer Prüfung schon mal einen Spickzettel benutzt haben, trinken 2 Schlucke.',
  'Alle, die sich schon mal nur wegen der Profilbilder in jemanden verguckt haben, trinken 2 Schlucke.',
  'Alle, die in ihrem Zimmer schon mal eine Tanzchoreo geprobt haben, trinken 2 Schlucke.',
  'Alle, die in den letzten 7 Tagen gelogen haben, trinken 2 Schlucke.',
  'Alle, die bei einem Videocall schon mal dachten, die Kamera sei aus, obwohl sie an war, trinken 2 Schlucke.',
  'Alle, die schon mal das Ende eines Films gespoilert haben, trinken 2 Schlucke.',
  'Alle, die ein Kompliment schon mal als Screenshot gespeichert haben, trinken 2 Schlucke.',
  'Alle, die schon mal eine Party verlassen haben, ohne sich zu verabschieden, trinken 2 Schlucke.',
  'Alle, die nach dem Feiern schon mal Essen bestellt haben und sich am nächsten Tag nicht daran erinnert haben, trinken 2 Schlucke.',
  'Alle, die schon mal einen Liebesbrief bekommen haben, trinken 1 Schluck.',
  'Alle, die schon mal per Nachricht Schluss gemacht haben, trinken 3 Schlucke.',
  'Alle, die schon mal heimlich über einen Fehler ihres Chefs gelacht haben, trinken 1 Schluck.',
  'Alle, die eine Sprachnachricht abgehört und nie darauf geantwortet haben, trinken 2 Schlucke.',
  'Alle, die glauben, von allen hier am besten lügen zu können, trinken 2 Schlucke.',
  'Alle, die schon mal ein Kompliment gemacht haben, nur um etwas zu bekommen, trinken 2 Schlucke.',

  '{{player}}, wen in dieser Runde würdest du am ehesten daten? Antworte ehrlich oder trink 4 Schlucke.',
  '{{player}}, was war dein peinlichster Moment in der Schule? Antworte ehrlich oder trink 3 Schlucke.',
  '{{player}}, welche Nachricht auf deinem Handy dürfte hier niemand lesen? Beschreib sie grob oder trink 4 Schlucke.',
  '{{player}}, wer war dein erster Schwarm? Antworte ehrlich oder trink 3 Schlucke.',
  '{{player}}, was ist die größte Lüge, die du deinen Eltern je erzählt hast? Antworte oder trink 4 Schlucke.',
  '{{player}}, welcher Song ist dein heimliches Guilty Pleasure? Antworte oder trink 2 Schlucke.',
  '{{player}}, was war dein schlimmstes Date? Erzähl es oder trink 3 Schlucke.',
  '{{player}}, wen aus der Runde würdest du um 3 Uhr nachts anrufen, damit er oder sie dich abholt? Antworte oder trink 2 Schlucke.',
  '{{player}}, was war dein erster Eindruck von {{player}}? Antworte ehrlich oder trink 3 Schlucke.',
  '{{player}}, welche App auf deinem Handy ist dir am peinlichsten? Antworte oder trink 3 Schlucke.',
  '{{player}}, wie lange hat deine kürzeste Beziehung gedauert? Antworte oder trink 3 Schlucke.',
  '{{player}}, was ist das Peinlichste, das du jemals gegoogelt hast? Antworte oder trink 4 Schlucke.',
  '{{player}}, hast du schon mal jemanden aus dieser Runde heimlich süß gefunden? Antworte ehrlich oder trink 4 Schlucke.',
  '{{player}}, was nervt dich an {{player}} am meisten? Antworte ehrlich oder trink 3 Schlucke.',
  '{{player}}, welche Eigenschaft von {{player}} hättest du gern? Antworte oder trink 2 Schlucke.',
  '{{player}}, was war das Dümmste, das du jemals betrunken gemacht hast? Antworte oder trink 4 Schlucke.',
  '{{player}}, worüber hast du dich schon mal total albern gestritten? Antworte oder trink 2 Schlucke.',
  '{{player}}, welche berühmte Person würdest du sofort daten? Antworte oder trink 2 Schlucke.',
  '{{player}}, worüber hast du zuletzt gelogen? Antworte ehrlich oder trink 3 Schlucke.',
  '{{player}}, was ist deine merkwürdigste Angewohnheit, wenn du allein bist? Antworte oder trink 3 Schlucke.',
  '{{player}}, welcher Kindheitstraum ist dir heute peinlich? Antworte oder trink 2 Schlucke.',
  '{{player}}, welchen Spitznamen hattest du früher, den hier niemand kennt? Antworte oder trink 3 Schlucke.',
  '{{player}}, was war dein peinlichster Moment auf einer Party? Antworte oder trink 3 Schlucke.',
  '{{player}}, wen in der Runde hältst du für die größte Plaudertasche? Antworte oder trink 2 Schlucke.',
  '{{player}}, wem in der Runde würdest du nie ein Geheimnis erzählen? Antworte ehrlich oder trink 4 Schlucke.',
  '{{player}}, was ist der seltsamste Grund, aus dem du jemanden nicht mehr treffen wolltest? Antworte oder trink 3 Schlucke.',
  '{{player}}, was war die kitschigste Sache, die du je für einen Schwarm gemacht hast? Antworte oder trink 3 Schlucke.',
  '{{player}}, welche Serie schaust du heimlich, obwohl du sie peinlich findest? Antworte oder trink 2 Schlucke.',
  '{{player}}, was war dein schlimmster Haarschnitt? Antworte oder trink 2 Schlucke.',
  '{{player}}, wen aus der Runde würdest du mit auf eine einsame Insel nehmen? Antworte oder trink 2 Schlucke.',
  '{{player}}, mit wem in der Runde würdest du niemals in den Urlaub fahren? Antworte ehrlich oder trink 3 Schlucke.',
  '{{player}}, was hast du als Kind geglaubt, das total falsch war? Antworte oder trink 2 Schlucke.',
  '{{player}}, welches Emoji benutzt du viel zu oft? Antworte oder trink 1 Schluck.',
  '{{player}}, welche Lüge über dich selbst erzählst du am häufigsten? Antworte oder trink 3 Schlucke.',
  '{{player}}, wann hast du zuletzt so gelacht, dass du fast nicht mehr konntest? Antworte oder trink 2 Schlucke.',
  '{{player}}, welches Geheimnis über dich kennt niemand in dieser Runde? Verrate es oder trink 5 Schlucke.',
  '{{player}}, was war der schlechteste Anmachspruch, den du je gehört hast? Antworte oder trink 2 Schlucke.',
  '{{player}}, bist du auf einer Party schon mal mit jemandem verschwunden? Antworte ehrlich oder trink 4 Schlucke.',
  '{{player}}, welche Person aus deiner Schulzeit würdest du gern wiedersehen? Antworte oder trink 2 Schlucke.',
  '{{player}}, was ist der unnötigste Spontankauf, den du je gemacht hast? Antworte oder trink 2 Schlucke.',
  '{{player}}, was ist deine größte Red Flag beim Daten? Antworte ehrlich oder trink 3 Schlucke.',
  '{{player}}, welchen Anmachspruch hast du selbst schon mal benutzt? Antworte oder trink 3 Schlucke.',
  '{{player}}, wen in der Runde würdest du am ehesten um Datingtipps bitten? Antworte oder trink 2 Schlucke.',
  '{{player}}, auf wen in der Runde warst du schon mal eifersüchtig? Antworte ehrlich oder trink 4 Schlucke.',
  '{{player}}, was war dein peinlichster Moment mit deinen Eltern? Antworte oder trink 3 Schlucke.',
  '{{player}}, was kannst du überhaupt nicht, behauptest aber gern, dass du es kannst? Antworte oder trink 3 Schlucke.',
  '{{player}}, wie viele Stunden warst du gestern am Handy? Schau nach und sag die Zahl oder trink 3 Schlucke.',
  '{{player}}, welchen Film hast du schon mindestens 10 Mal gesehen? Antworte oder trink 1 Schluck.',
  '{{player}}, welchen Streich hast du in der Schule gespielt, der nie aufgeflogen ist? Antworte oder trink 3 Schlucke.',
  '{{player}}, was hast du auf der Arbeit schon mal verbockt und nie zugegeben? Antworte oder trink 4 Schlucke.',
  '{{player}}, wer in der Runde hat den besten Kleidungsstil? Antworte oder trink 2 Schlucke.',
  '{{player}}, was ist das Kindischste, das du immer noch machst? Antworte oder trink 2 Schlucke.',
  '{{player}}, worauf achtest du bei einem Date als Erstes? Antworte ehrlich oder trink 2 Schlucke.',
  '{{player}}, was hast du deiner besten Freundin oder deinem besten Freund nie erzählt? Antworte oder trink 5 Schlucke.',
  '{{player}}, wessen Story schaust du dir immer sofort an? Antworte oder trink 3 Schlucke.',
  '{{player}}, was war der peinlichste Versprecher deines Lebens? Antworte oder trink 2 Schlucke.',
  '{{player}}, wen in der Runde findest du am lustigsten? Antworte oder trink 1 Schluck.',
  '{{player}}, was ist das Netteste, das du je über {{player}} gedacht, aber nie gesagt hast? Sag es oder trink 3 Schlucke.',
  '{{player}}, was war dein peinlichstes Outfit als Teenager? Antworte oder trink 2 Schlucke.',
  '{{player}}, unter welchem Namen ist dein Schwarm in deinem Handy gespeichert? Antworte oder trink 3 Schlucke.',
  '{{player}}, was ist deine unpopulärste Meinung? Antworte oder trink 2 Schlucke.',
  '{{player}}, welches Gerücht über dich stimmt tatsächlich? Antworte oder trink 4 Schlucke.',
  '{{player}}, mit wem in dieser Runde würdest du für eine Woche das Leben tauschen? Antworte oder trink 2 Schlucke.',
  '{{player}}, wie hast du dich zuletzt vor deinem Schwarm blamiert? Antworte oder trink 4 Schlucke.',
  '{{player}}, wen aus der Runde würdest du als Trauzeugen wählen? Antworte oder trink 2 Schlucke.',
  '{{player}}, wie lange hast du schon mal gebraucht, um auf eine Nachricht zu antworten? Antworte oder trink 2 Schlucke.',
  '{{player}}, was würdest du tun, wenn du einen Tag lang unsichtbar wärst? Antworte ehrlich oder trink 2 Schlucke.',
  '{{player}}, welche Ausrede benutzt du am häufigsten? Antworte oder trink 2 Schlucke.',
  '{{player}}, wer hat dir zuletzt eine Nachricht geschrieben, über die du dich heimlich gefreut hast? Antworte oder trink 3 Schlucke.',
  '{{player}}, über welchen Witz von {{player}} hast du nur aus Höflichkeit gelacht? Antworte oder trink 3 Schlucke.',
  '{{player}}, welches Kompliment hat dich zuletzt so richtig gefreut? Antworte oder trink 1 Schluck.',
  '{{player}}, wann hast du dich zuletzt in jemanden verguckt? Antworte oder trink 3 Schlucke.',
  '{{player}}, lies den obersten Eintrag in deinen Notizen vor oder trink 3 Schlucke.',
  '{{player}}, was war dein peinlichster Moment im Fitnessstudio? Antworte oder trink 2 Schlucke.',
  '{{player}}, wen aus der Runde würdest du bei einem Quiz als Partner wählen? Antworte oder trink 1 Schluck.',
  '{{player}}, auf welche Dummheit aus deiner Vergangenheit bist du heimlich stolz? Antworte oder trink 3 Schlucke.',
  '{{player}}, welches Foto auf deinem Handy ist das peinlichste? Beschreib es oder trink 4 Schlucke.',
  '{{player}}, hast du schon mal jemanden gedatet, nur um eine andere Person eifersüchtig zu machen? Antworte oder trink 4 Schlucke.',
  '{{player}}, was ist das Komischste, das du im Schlaf gesagt oder gemacht hast? Antworte oder trink 2 Schlucke.',
  '{{player}}, was war heute Morgen dein erster Gedanke? Antworte ehrlich oder trink 2 Schlucke.',

  'Abstimmung: Wer schläft am ehesten auf einer Party ein? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer hat am ehesten einen geheimen Schwarm auf der Arbeit? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer hat die meisten ungelesenen Nachrichten? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde am ehesten eine Realityshow gewinnen? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer verliebt sich am schnellsten? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer plaudert am ehesten ein Geheimnis aus? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer kommt immer zu spät? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer würde am ehesten bei einem Date einschlafen? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer hat den schlechtesten Musikgeschmack? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer würde am ehesten heimlich heiraten? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer hat die peinlichsten Fotos auf dem Handy? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde am ehesten mit dem Chef flirten? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer kann am schlechtesten lügen? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer wird am ehesten berühmt? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer schickt am ehesten eine Sprachnachricht von 10 Minuten? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer ist am ehesten heimlich auf einer Datingapp aktiv? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer reißt auf einer Party am ehesten die Musik an sich? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer würde am ehesten im Supermarkt mit Fremden flirten? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer schreibt am ehesten betrunken dem Ex? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde sich am ehesten den Namen des Partners tätowieren lassen? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer bestellt am häufigsten Essen? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer würde in einer Quizshow am ehesten komplett versagen? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer hat die meisten Crushs gleichzeitig? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer hat am ehesten schon mal jemanden aus der Runde gegoogelt? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer vergisst am ehesten, wo das Auto steht? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer hat als Kind am ehesten Klingelstreiche gemacht? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde sich am ehesten ein Selfie mit einem Promi erschleichen? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer redet am meisten über sich selbst? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde am ehesten einen ganzen Tag im Bett verbringen? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer hat für alles eine Ausrede? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer schreit bei einem Horrorfilm am lautesten? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer macht aus allem ein Drama? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde auf einer Hochzeit am ehesten eine peinliche Rede halten? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde am ehesten heimlich das Handy einer anderen Person durchsuchen? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer hat am ehesten eine geheime zweite Identität im Internet? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer würde am ehesten im Urlaub einfach dort bleiben und nicht zurückfliegen? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer flirtet am meisten, ohne es zu merken? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer kommt bei den Eltern der anderen am besten an? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer würde zum Date am ehesten die beste Freundin oder den besten Freund mitbringen? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer schreibt am ehesten heimlich Tagebuch? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer postet am ehesten jeden Jahrestag mit einem langen Text? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer gewinnt am ehesten jeden Streit? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer würde am ehesten eine Liebeserklärung per Sprachnachricht machen? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer ist am ehesten schuld, wenn eine Party eskaliert? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eine Woche ohne Handy am wenigsten durchhalten? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer singt im Auto am lautesten mit? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer würde am ehesten auf einen Fakeaccount reinfallen? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer ist am ehesten noch mit allen früheren Partnern befreundet? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer fotografiert im Restaurant am ehesten das Essen, bevor jemand anfangen darf? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde am ehesten eine eigene Talkshow bekommen? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer gibt beim Karaoke am ehesten das Mikro nicht mehr her? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer stalkt neue Bekanntschaften am ehesten im Internet? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer würde am ehesten einen Tanzwettbewerb gewinnen? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',
  'Abstimmung: Wer ist am ehesten verliebt, ohne es selbst zu wissen? Die Person mit den meisten Stimmen trinkt 3 Schlucke.',
  'Abstimmung: Wer macht beim Flirten am ehesten den ersten Schritt? Wer die meisten Stimmen bekommt, trinkt 2 Schlucke.',

  '{{player}}, wer in der Runde hat das ansteckendste Lachen? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde wäre der anstrengendste Mitbewohner? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde ist heimlich total romantisch? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde braucht morgens am längsten im Bad? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde schickt die meisten Memes? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde hat den seltsamsten Humor? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde wäre der beste Komplize für einen Streich? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde hatte als Kind am meisten Hausarrest? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde tanzt am schlechtesten? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde hat das beste Pokerface? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde sagt Pläne am häufigsten kurzfristig ab? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde kann am besten flirten? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde hat die meisten Selfies auf dem Handy? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde würde in einer Castingshow am weitesten kommen? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde ist heimlich der größte Nerd? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde hat die meisten Geheimnisse? Die Person trinkt 3 Schlucke.',
  '{{player}}, wer in der Runde würde dich am ehesten verpetzen? Die Person trinkt 3 Schlucke.',
  '{{player}}, wer in der Runde wird am schnellsten eifersüchtig? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde sollte öfter mal ehrlich sein? Die Person trinkt 3 Schlucke.',
  '{{player}}, wer in der Runde gibt die schlechtesten Liebestipps? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde würde am ehesten im Schlafanzug auf einer Party auftauchen? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde ist der größte Partylöwe? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde lügt in diesem Spiel am meisten? Die Person trinkt 3 Schlucke.',
  '{{player}}, wer in der Runde hätte den lustigsten Text im Datingprofil? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde wäre der chaotischste Babysitter? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde hat das beste Händchen für Dates? Die Person trinkt 2 Schlucke.',
  '{{player}}, wer in der Runde kennt dich am besten? Ihr trinkt beide 2 Schlucke.',
  '{{player}}, wer in der Runde tippt am langsamsten auf dem Handy? Die Person trinkt 2 Schlucke.',
  '{{player}}, mit wem in der Runde hast du die meisten Insiderwitze? Ihr trinkt beide 2 Schlucke.',
  '{{player}}, wer in der Runde hätte als Promi die meisten Skandale? Die Person trinkt 2 Schlucke.',

  '{{player}} beantwortet 3 Fragen der Runde ehrlich oder trinkt 5 Schlucke.',
  'Hot Seat: {{player}} sitzt 1 Minute auf dem heißen Stuhl und muss jede Frage der Runde beantworten. Jede verweigerte Antwort kostet 2 Schlucke.',
  'Hot Seat: Alle stellen {{player}} reihum eine Frage über die Liebe. Jede ausgelassene Frage kostet 2 Schlucke.',
  '{{player}} muss 2 Fragen von {{player}} ehrlich beantworten oder trinkt 4 Schlucke.',
  'Hot Seat: {{player}} darf auf die nächsten 3 Fragen der Runde nur mit Ja oder Nein antworten. Wird eine Lüge entlarvt, gibt es 3 Schlucke.',
  'Hot Seat: {{player}} beantwortet 3 Fragen zur Schulzeit. Für jede verweigerte Antwort gibt es 2 Schlucke.',
  'Hot Seat: {{player}} beantwortet 3 Fragen zum letzten Date ehrlich oder trinkt 5 Schlucke.',
  '{{player}} und {{player}} stellen sich gegenseitig eine ehrliche Frage. Wer nicht antwortet, trinkt 3 Schlucke.',
  'Hot Seat: {{player}} muss 30 Sekunden lang alle Fragen der Runde ohne Zögern beantworten. Für jedes Zögern gibt es 1 Schluck.',
  'Hot Seat: Die Runde stellt {{player}} 3 Fragen zum eigenen Handy. Jede verweigerte Antwort kostet 2 Schlucke.',
  'Hot Seat: Die Runde einigt sich auf eine einzige Frage an {{player}}. Antworte ehrlich oder trink 5 Schlucke.',
  'Hot Seat: {{player}} bekommt von jeder Person eine Frage zum aktuellen Schwarm. Für jede Ausrede gibt es 2 Schlucke.',
  '{{player}} beantwortet 2 Fragen der Runde über die Arbeit oder die Uni ehrlich oder trinkt 4 Schlucke.',
  'Hot Seat: {{player}} denkt sich eine richtig unangenehme Frage für {{player}} aus. Wer nicht antwortet, trinkt 5 Schlucke.',
  'Hot Seat: {{player}} stellt der Person rechts von sich 3 ehrliche Fragen. Jede Weigerung kostet 2 Schlucke.',
  'Hot Seat: {{player}} beantwortet 3 Fragen über peinliche Kindheitsmomente oder trinkt 4 Schlucke.',
  'Hot Seat: {{player}} sagt jeder Person in der Runde einen ehrlichen Satz über sie. Für jeden ausgelassenen Satz gibt es 2 Schlucke.',
  'Hot Seat: Die Runde stellt {{player}} 3 Fragen, bei denen jedes Mal zwischen 2 Leuten aus der Runde gewählt werden muss. Jede Weigerung kostet 2 Schlucke.',
  'Hot Seat: {{player}} beantwortet 3 Fragen zum ersten Kuss ehrlich oder trinkt 5 Schlucke.',
  'Hot Seat: Jede Person darf {{player}} eine Frage über die Leute in dieser Runde stellen. Jede verweigerte Antwort kostet 2 Schlucke.',
];
