export const wildTasks: string[] = [
  'Abstimmung: Wer würde eher bei einem Casting für eine Realityshow mitmachen? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher auf einer Hochzeit ungefragt eine Rede halten? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher mitten in der Nacht spontan einen Urlaub buchen? Wer die meisten Stimmen bekommt, verteilt 4 Schlucke.',
  'Abstimmung: Wer würde eher beim Karaoke das Mikrofon nicht mehr hergeben? Wer die meisten Stimmen bekommt, trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher einen Promi auf der Straße um ein Selfie anbetteln? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher mit dem DJ diskutieren, weil die Musik schlecht ist? Wer die meisten Stimmen bekommt, trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher beim Flirten über die eigenen Füße stolpern? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher in einer Gruppenarbeit nichts tun und trotzdem präsentieren? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher in einem Horrorfilm als Erstes in den dunklen Keller gehen? Wer die meisten Stimmen bekommt, trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher eine Tanzshow im Fernsehen gewinnen? Wer die meisten Stimmen bekommt, verteilt 5 Schlucke.',
  'Abstimmung: Wer würde eher heimlich die Playlist auf einer Party ändern? Wer die meisten Stimmen bekommt, trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher im Escape Room als Erstes aufgeben? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher eine Sprachnachricht von 10 Minuten verschicken? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher die Hauptrolle in einer kitschigen Seifenoper bekommen? Wer die meisten Stimmen bekommt, verteilt 4 Schlucke.',
  'Abstimmung: Wer würde eher auf der eigenen Geburtstagsparty als Erstes einschlafen? Wer die meisten Stimmen bekommt, trinkt 5 Schlucke.',
  'Abstimmung: Wer würde eher bei einer Quizshow schon die erste Frage verhauen? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher einem Fremden im Zug die ganze Lebensgeschichte erzählen? Wer die meisten Stimmen bekommt, trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher mit einem Sprachassistenten einen Streit anfangen? Wer die meisten Stimmen bekommt, trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher beim Wichteln das schlechteste Geschenk mitbringen? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher ein Musikvideo mit sich selbst als Star drehen? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher heimlich die letzten Pommes vom Teller der anderen klauen? Wer die meisten Stimmen bekommt, trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher beim Monopoly schummeln? Wer die meisten Stimmen bekommt, trinkt 5 Schlucke.',
  'Abstimmung: Wer würde eher in einer Talkshow einen Wutausbruch haben? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher als Influencer berühmt werden? Wer die meisten Stimmen bekommt, verteilt 4 Schlucke.',
  'Abstimmung: Wer würde eher beim Tanzen alle anderen von der Tanzfläche verdrängen? Wer die meisten Stimmen bekommt, trinkt 3 Schlucke.',
  'Abstimmung: Wer würde eher schon beim ersten Date über Hochzeitspläne reden? Wer die meisten Stimmen bekommt, trinkt 5 Schlucke.',
  'Abstimmung: Wer würde eher im Kostüm auf einer Party auftauchen, auf der niemand verkleidet ist? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher eine Woche ohne Handy durchhalten? Wer die wenigsten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher bei einem Konzert auf die Bühne klettern wollen? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher auf einer Party mit der Deko ein Gespräch anfangen? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher bei einer Datingshow mitmachen? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher den Ex auf einer Party zufällig treffen und so tun, als wäre alles super? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher einen Abend lang einen falschen Akzent durchziehen, nur weil es lustig ist? Wer die meisten Stimmen bekommt, verteilt 4 Schlucke.',
  'Abstimmung: Wer würde eher beim Junggesellenabschied die peinlichste Aufgabe übernehmen? Wer die meisten Stimmen bekommt, trinkt 5 Schlucke.',
  'Abstimmung: Wer würde eher in einem Kochduell das Essen anbrennen lassen? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher eine Nachricht an die falsche Person schicken und es erst am nächsten Tag merken? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer hat heute Abend die beste Ausstrahlung? Wer die meisten Stimmen bekommt, verteilt 5 Schlucke.',
  'Abstimmung: Wer wird heute Abend als Erstes müde? Wer die meisten Stimmen bekommt, trinkt 4 Schlucke.',
  'Abstimmung: Wer würde bei einer Zombieapokalypse am längsten überleben? Wer die meisten Stimmen bekommt, verteilt 5 Schlucke.',
  'Abstimmung: Wer hätte das beste Talent für eine Karriere als Schlagersänger? Wer die meisten Stimmen bekommt, singt eine Zeile oder trinkt 4 Schlucke.',
  'Abstimmung: Wer würde eher in einer Bar eine Runde für alle Fremden ausgeben? Wer die meisten Stimmen bekommt, trinkt 3 Schlucke.',
  'Auf drei zeigen alle gleichzeitig auf die Person, die am ehesten einen Flirt mit dem Kellner anfängt. Wer die meisten Finger abbekommt, trinkt 4 Schlucke.',
  'Auf drei zeigen alle gleichzeitig auf die Person mit dem verrücktesten Musikgeschmack. Wer die meisten Finger abbekommt, trinkt 4 Schlucke.',
  'Auf drei zeigen alle gleichzeitig auf die Person, die heute am lautesten ist. Wer die meisten Finger abbekommt, trinkt 4 Schlucke.',
  'Auf drei zeigen alle gleichzeitig auf die Person, die am längsten im Bad braucht. Wer die meisten Finger abbekommt, trinkt 3 Schlucke.',
  'Auf drei zeigen alle gleichzeitig auf die Person, die als Erstes eine verrückte Idee umsetzen würde. Wer die meisten Finger abbekommt, verteilt 4 Schlucke.',
  'Auf drei zeigen alle gleichzeitig auf die Person, die am schlechtesten Geheimnisse für sich behalten kann. Wer die meisten Finger abbekommt, trinkt 5 Schlucke.',
  'Auf drei zeigen alle gleichzeitig auf die Person, die am meisten Dramaqueen ist. Wer die meisten Finger abbekommt, trinkt 4 Schlucke.',
  'Auf drei zeigen alle gleichzeitig auf die Person, mit der man am besten eine Weltreise machen würde. Wer die meisten Finger abbekommt, verteilt 5 Schlucke.',
  'Alle, die schon mal eine Nachricht an die falsche Person geschickt haben, trinken 3 Schlucke.',
  'Alle, die schon mal auf einer Party eingeschlafen sind, trinken 4 Schlucke.',
  'Alle, die schon mal einen Liebesbrief geschrieben haben, trinken 3 Schlucke.',
  'Alle, die schon mal so getan haben, als würden sie jemanden nicht kennen, nur um nicht reden zu müssen, trinken 3 Schlucke.',
  'Alle, die schon mal beim Lügen erwischt wurden, trinken 4 Schlucke.',
  'Alle, die schon mal in einer Bar einen falschen Namen angegeben haben, trinken 4 Schlucke.',
  'Alle, die schon mal das Profil ihres Schwarms bis ganz nach unten durchgescrollt haben, trinken 4 Schlucke.',
  'Alle, die schon mal aus Versehen ein uraltes Foto von jemandem geliked haben, trinken 5 Schlucke.',
  'Alle, die schon mal mit dem oder der Ex wieder zusammengekommen sind, trinken 4 Schlucke.',
  'Alle, die schon mal beim Tanzen hingefallen sind, trinken 3 Schlucke.',
  'Alle, die schon mal ein Geschenk weiterverschenkt haben, trinken 3 Schlucke.',
  'Alle, die schon mal eine Ausrede erfunden haben, um nicht auf eine Party zu müssen, trinken 4 Schlucke.',
  'Alle, die schon mal vor dem Spiegel eine Dankesrede für einen Preis geübt haben, trinken 4 Schlucke.',
  'Alle, die einen Promi-Schwarm haben, für den sie sich ein bisschen schämen, trinken 3 Schlucke und verraten ihn.',
  'Alle, die schon mal ein Date komplett vergessen haben, trinken 5 Schlucke.',
  'Alle, die schon mal jemanden geghostet haben, trinken 4 Schlucke.',
  'Alle, die schon mal geghostet wurden, verteilen 3 Schlucke an jemanden, der es verdient hat.',
  'Alle, die schon mal einen Termin oder eine Prüfung verschlafen haben, trinken 3 Schlucke.',
  'Alle, die einen Spitznamen haben, den sie heimlich hassen, trinken 3 Schlucke.',
  'Alle, die schon mal mit jemandem aus dieser Runde geflirtet haben, trinken 4 Schlucke.',
  'Alle, die schon mal etwas Peinliches in den Familienchat geschickt haben, trinken 4 Schlucke.',
  'Alle, die schon mal so getan haben, als hätten sie ein Buch gelesen, trinken 3 Schlucke.',
  'Alle, die schon mal bei einem Gesellschaftsspiel geschummelt haben, trinken 4 Schlucke.',
  'Alle, deren Akku gerade unter 20 Prozent liegt, trinken 3 Schlucke.',
  'Alle, die Single sind, verteilen 3 Schlucke. Alle, die vergeben sind, trinken 3 Schlucke.',
  'Alle, die schon mal nach ein paar Drinks jemandem ihre Liebe gestanden haben, trinken 4 Schlucke.',
  'Alle, die schon mal auf einem Tisch getanzt haben, trinken 4 Schlucke.',
  'Alle, die schon mal ihre Haare selbst geschnitten und es sofort bereut haben, trinken 3 Schlucke.',
  'Alle, die schon mal einem Promi eine Nachricht geschrieben haben, trinken 4 Schlucke.',
  'Alle, die schon mal aus dem Unterricht geschickt wurden, weil sie nicht aufhören konnten zu lachen, trinken 4 Schlucke.',
  'Alle, die schon mal eine Party gecrasht haben, zu der sie nicht eingeladen waren, trinken 5 Schlucke.',
  'Alle, die schon mal ein Geschenk in letzter Minute an der Tankstelle gekauft haben, trinken 3 Schlucke.',
  'Alle, die schon mal am Morgen danach eine Nachricht vom Vorabend am liebsten gelöscht hätten, trinken 5 Schlucke.',
  'Alle, die schon mal beim ersten Date den Namen der anderen Person vergessen haben, trinken 5 Schlucke.',
  'Alle, die schon mal heimlich in fremden Badezimmerschränken gestöbert haben, trinken 4 Schlucke.',
  'Alle, die schon mal einen Film nur wegen eines Schauspielers geschaut haben, trinken 3 Schlucke.',
  'Alle, die schon mal einen Kuss auf einer Party bereut haben, trinken 4 Schlucke.',
  'Alle, die schon mal in einem Urlaub einen Flirt hatten, trinken 4 Schlucke.',
  'Alle, die schon mal ein Selfie mit einem Promi gemacht haben, verteilen 4 Schlucke.',
  'Alle, die schon mal beim Fernsehen laut mit den Leuten im Bildschirm geredet haben, trinken 3 Schlucke.',
  'Alle, die schon mal ein Outfit nur für ein Foto gekauft und dann zurückgegeben haben, trinken 4 Schlucke.',
  'Alle, die schon mal einen Streit nur wegen eines Gesellschaftsspiels hatten, trinken 4 Schlucke.',
  'Alle, die schon mal auf einem Festival waren, trinken 3 Schlucke. Wer schon mal auf mehr als 5 war, verteilt sie stattdessen.',
  'Alle, die schon mal jemanden geküsst haben, dessen Namen sie nicht kannten, trinken 5 Schlucke.',
  'Alle, die heute schon mehr als 3 Stunden am Handy waren, trinken 3 Schlucke.',
  'Alle, die schon mal bei einer Hochzeit getanzt haben, bis die Schuhe kaputt waren, trinken 3 Schlucke.',
  'Alle, die schon mal eine Wette verloren und den Einsatz nie eingelöst haben, trinken 5 Schlucke.',
  'Alle, die schon mal bei einem Liebesfilm geweint haben, verteilen 3 Schlucke, weil sie Gefühle haben.',
  'Alle, die schon mal mit dem Handy in der Hand ihr Handy gesucht haben, trinken 3 Schlucke.',
  'Alle, die schon mal nachts um 3 Uhr etwas völlig Unnötiges online bestellt haben, trinken 4 Schlucke.',
  'Alle, die schon mal bei einem Konzert in der ersten Reihe standen, verteilen 4 Schlucke.',
  'Alle, die ihre Eltern schon mal mit einer kreativen Ausrede über ihren Abend angelogen haben, trinken 4 Schlucke.',
  'Wer zuletzt die Hand auf den Kopf legt, trinkt 4 Schlucke.',
  'Wer zuletzt aufsteht, trinkt 4 Schlucke.',
  'Wer zuletzt auf {{player}} zeigt, trinkt 3 Schlucke.',
  'Wer zuletzt sein Glas in die Luft hält, trinkt 4 Schlucke.',
  'Wer zuletzt die Arme verschränkt, trinkt 4 Schlucke.',
  'Wer zuletzt "Prost" ruft, trinkt 5 Schlucke.',
  'Wer zuletzt beide Hände flach auf den Tisch legt, trinkt 4 Schlucke.',
  'Wer als Erstes ein Foto von einer Katze auf dem Handy findet, verteilt 4 Schlucke.',
  'Wer als Erstes einen roten Gegenstand hochhält, verteilt 4 Schlucke. Wer als Letztes einen findet, trinkt 3.',
  'Wer als Erstes 5 Disney-Filme aufzählt, verteilt 5 Schlucke.',
  'Für die nächsten 3 Aufgaben darf niemand das Wort "trinken" sagen. Wer es doch tut, trinkt 3 Schlucke.',
  '{{player}}, du bist ab sofort Fragenmeister. Wer dir in den nächsten 3 Aufgaben eine Frage beantwortet, trinkt 3 Schlucke.',
  '{{player}}, du bist jetzt Daumenmeister. Legst du in den nächsten 5 Aufgaben unauffällig den Daumen auf den Tisch, trinkt die Person, die es zuletzt nachmacht, 4 Schlucke.',
  'Für die nächsten 3 Aufgaben trinken alle nur mit der schwachen Hand. Wer es vergisst, trinkt 3 Schlucke extra.',
  '{{player}}, du darfst für die nächsten 3 Aufgaben nur noch flüstern. Jedes laute Wort kostet dich 2 Schlucke.',
  '{{player}} und {{player}} sind für die nächsten 3 Aufgaben Trinkpartner. Trinkt eine Person, trinkt die andere die gleiche Menge mit.',
  'Für die nächsten 4 Aufgaben ist Fluchen verboten. Jedes Schimpfwort kostet 3 Schlucke.',
  '{{player}}, du musst für die nächsten 3 Aufgaben jeden Satz mit "Mylord" beenden. Jeder Fehler kostet 2 Schlucke.',
  'Für die nächsten 3 Aufgaben sind Vornamen verboten. Wer einen Namen sagt, trinkt 3 Schlucke.',
  'Für die nächsten 3 Aufgaben muss jeder vor dem Trinken laut "Auf die Legenden" rufen. Wer es vergisst, trinkt doppelt.',
  '{{player}}, du sprichst für die nächsten 3 Aufgaben mit französischem Akzent. Jeder Ausrutscher kostet 2 Schlucke.',
  '{{player}}, du bist für die nächsten 3 Aufgaben der Butler von {{player}} und musst der Person vor jedem Schluck das Glas reichen. Vergisst du es, trinkst du 3 Schlucke.',
  'Für die nächsten 5 Aufgaben gilt: Wer laut lacht, trinkt 1 Schluck.',
  '{{player}}, du musst für die nächsten 3 Aufgaben alles laut wiederholen, was {{player}} sagt. Jeder vergessene Satz kostet 2 Schlucke.',
  'Für die nächsten 3 Aufgaben ist das Wort "ja" verboten. Wer es sagt, trinkt 3 Schlucke.',
  'Wer in den nächsten 3 Aufgaben sein Handy anfasst, trinkt 4 Schlucke.',
  '{{player}} denkt sich eine neue Regel aus, die für die nächsten 5 Aufgaben gilt. Wer sie bricht, trinkt 3 Schlucke.',
  '{{player}}, du bist für die nächsten 3 Aufgaben König oder Königin. Wer mit dir spricht, ohne dich mit "Majestät" anzureden, trinkt 2 Schlucke.',
  '{{player}}, du darfst in den nächsten 3 Aufgaben nur mit Ja oder Nein antworten. Jedes andere Wort kostet 2 Schlucke.',
  '{{player}} ist für die nächsten 3 Aufgaben der Spiegel von {{player}} und muss jede Bewegung nachmachen. Wer erwischt wird, trinkt 3 Schlucke.',
  'Für die nächsten 3 Aufgaben müssen alle beim Sprechen die Hand heben. Wer ohne Hand redet, trinkt 2 Schlucke.',
  '{{player}}, du sprichst für die nächsten 3 Aufgaben von dir nur in der dritten Person. Jeder Fehler kostet 2 Schlucke.',
  'Für die nächsten 3 Aufgaben muss jeder vor dem Trinken mit dem Glas von {{player}} anstoßen. Wer es vergisst, trinkt 2 Schlucke extra.',
  '{{player}}, du bist für die nächsten 3 Aufgaben der Schatten der Runde: Jedes Mal, wenn jemand trinkt, trinkst du 1 Schluck mit.',
  'Für die nächsten 3 Aufgaben darf niemand auf etwas zeigen. Wer mit dem Finger zeigt, trinkt 3 Schlucke.',
  '{{player}}, du musst für die nächsten 3 Aufgaben bei jeder Antwort einen kleinen Reim einbauen. Ohne Reim trinkst du 2 Schlucke.',
  '{{player}}, du bekommst einen Joker. Du darfst eine beliebige spätere Aufgabe ablehnen, ohne zu trinken.',
  '{{player}}, du darfst die nächste Aufgabe, die dich trifft, an {{player}} weitergeben.',
  '{{player}} ist ab sofort für 3 Aufgaben der Barkeeper. Wer trinkt, muss sich vorher höflich bei der Person bedanken, sonst 2 Schlucke extra.',
  'Für die nächsten 3 Aufgaben müssen alle wie Nachrichtensprecher reden. Wer aus der Rolle fällt, trinkt 3 Schlucke.',
  'Kategorie Automarken: {{player}} beginnt, reihum nennt jeder eine. Wer zögert oder etwas wiederholt, trinkt 4 Schlucke.',
  'Kategorie Fußballvereine: {{player}} beginnt, reihum nennt jeder einen. Wer zögert oder etwas wiederholt, trinkt 4 Schlucke.',
  'Kategorie Cocktails: {{player}} beginnt, reihum nennt jeder einen. Wer zögert oder etwas wiederholt, trinkt 4 Schlucke.',
  'Kategorie Pokémon: {{player}} beginnt, reihum nennt jeder eins. Wer zögert oder etwas wiederholt, trinkt 4 Schlucke.',
  'Anstarr-Duell zwischen {{player}} und {{player}}. Wer zuerst blinzelt oder lacht, trinkt 4 Schlucke.',
  'Schere, Stein, Papier zwischen {{player}} und {{player}}, best of 3. Wer verliert, trinkt 5 Schlucke.',
  'Daumencatchen zwischen {{player}} und {{player}}. Wer verliert, trinkt 4 Schlucke.',
  '{{player}} summt ein Lied. Wer es zuerst errät, verteilt 4 Schlucke. Errät es niemand in 30 Sekunden, trinkt die summende Person 4 Schlucke.',
  'Pantomime: {{player}} stellt einen Film dar. Wer ihn errät, verteilt 3 Schlucke. Errät ihn niemand in 1 Minute, trinkt die darstellende Person 4 Schlucke.',
  'Pantomime: {{player}} spielt einen Beruf vor. Wer ihn errät, verteilt 3 Schlucke. Errät ihn niemand in 1 Minute, trinkt die darstellende Person 4 Schlucke.',
  'Pantomime: {{player}} spielt ein Tier vor, nur {{player}} darf raten. Klappt es in 30 Sekunden nicht, trinken beide 3 Schlucke.',
  'Pantomime: {{player}} stellt eine Sportart dar. Wer sie errät, verteilt 3 Schlucke. Errät sie niemand, trinkt die darstellende Person 3 Schlucke.',
  'Pantomime: {{player}} spielt einen berühmten Promi vor. Wer ihn errät, verteilt 4 Schlucke, sonst trinkt die darstellende Person 4 Schlucke.',
  '{{player}} imitiert eine Person aus der Runde, ohne den Namen zu nennen. Wer zuerst errät, wer gemeint ist, verteilt 3 Schlucke.',
  '{{player}}, imitiere einen bekannten Promi. Wird er erraten, verteilst du 4 Schlucke, sonst trinkst du 4.',
  'Wortkette: {{player}} nennt ein Wort, reihum folgt ein Wort, das mit dem letzten Buchstaben beginnt. Wer stockt, trinkt 4 Schlucke.',
  'Bum-Spiel: Reihum wird gezählt, bei jeder Zahl mit einer 7 oder durch 7 teilbar sagt man "Bum". {{player}} beginnt, wer sich vertut, trinkt 4 Schlucke.',
  '{{player}} denkt sich eine Zahl zwischen 1 und 20 aus. Reihum wird geraten, wer sie trifft, verteilt 5 Schlucke.',
  '{{player}}, nenne in 10 Sekunden 5 Biermarken oder trink 4 Schlucke.',
  '{{player}}, nenne in 10 Sekunden 5 Hauptstädte in Europa oder trink 4 Schlucke.',
  '{{player}}, nenne in 10 Sekunden 5 Harry-Potter-Figuren oder trink 4 Schlucke.',
  '{{player}}, nenne in 10 Sekunden 5 Lieder von Helene Fischer oder trink 5 Schlucke.',
  '{{player}} und {{player}} nennen abwechselnd Hauptstädte. Wer zuerst keine mehr weiß, trinkt 5 Schlucke.',
  '{{player}} und {{player}} nennen abwechselnd Filme mit Leonardo DiCaprio. Wer zuerst keinen mehr weiß, trinkt 4 Schlucke.',
  '{{player}} erzählt 2 Wahrheiten und 1 Lüge über sich. Wer die Lüge findet, verteilt 2 Schlucke, wer danebenliegt, trinkt 2.',
  '{{player}}, sag das Alphabet rückwärts von Z bis P ohne Fehler, oder trink 4 Schlucke.',
  '{{player}}, sag 3 Mal schnell "Fischers Fritz fischt frische Fische" ohne Fehler, oder trink 3 Schlucke.',
  '{{player}}, balanciere einen Bierdeckel 20 Sekunden lang auf dem Kopf, während du einmal um den Tisch gehst. Schaffst du es, verteilst du 4 Schlucke, sonst trinkst du 4.',
  '{{player}}, halte 30 Sekunden die Plank-Position. Schaffst du es, verteilst du 4 Schlucke, sonst trinkst du 4.',
  '{{player}}, mach 15 Hampelmänner, während alle laut mitzählen, oder trink 4 Schlucke.',
  'Ruhe-Challenge: Die ganze Runde ist 30 Sekunden still. Wer zuerst ein Geräusch macht, trinkt 4 Schlucke.',
  'Alle zeigen ihre Bildschirmzeit von gestern. Wer den höchsten Wert hat, trinkt 4 Schlucke, wer den niedrigsten hat, verteilt 4.',
  'Wer am Tisch die meisten ungelesenen Nachrichten hat, trinkt 4 Schlucke.',
  'Wer am Tisch die meisten Fotos in der Galerie hat, trinkt 3 Schlucke. Wer die wenigsten hat, verteilt 3.',
  '{{player}}, lies die letzte Nachricht vor, die du verschickt hast, oder trink 4 Schlucke.',
  '{{player}}, zeig der Runde das fünfte Foto von hinten in deiner Galerie, oder trink 5 Schlucke.',
  '{{player}}, lies deine letzten 3 Suchbegriffe im Browser vor, oder trink 5 Schlucke.',
  '{{player}}, zeig der Runde den peinlichsten Song in deiner Playlist, oder trink 4 Schlucke.',
  '{{player}}, zeig das älteste Foto in deiner Galerie, oder trink 4 Schlucke.',
  '{{player}}, halte eine dramatische Abschiedsrede an dein Glas und trink danach 3 Schlucke.',
  '{{player}}, mach dem Gegenstand, der dir am nächsten liegt, eine leidenschaftliche Liebeserklärung. Lacht jemand, verteilst du 3 Schlucke, sonst trinkst du 3.',
  '{{player}}, kommentiere die nächste Aufgabe wie ein Fußballreporter. Wer dabei lacht, trinkt 2 Schlucke.',
  '{{player}}, sing den Refrain eines Schlagers mit voller Inbrunst, oder trink 4 Schlucke.',
  '{{player}}, tanz 20 Sekunden ohne Musik, als wärst du in einem Musikvideo, oder trink 4 Schlucke.',
  '{{player}}, lauf einmal wie auf dem Laufsteg durch den Raum, oder trink 4 Schlucke.',
  '{{player}}, halte eine Wahlkampfrede von 30 Sekunden, warum du die Krone der Runde verdienst. Klatscht die Mehrheit, verteilst du 5 Schlucke, sonst trinkst du 3.',
  '{{player}}, mach jeder Person in der Runde in 30 Sekunden ein Kompliment, oder trink 4 Schlucke.',
  '{{player}}, sing 10 Sekunden lang wie ein Opernstar, oder trink 4 Schlucke.',
  '{{player}}, erzähl einen Witz. Lacht jemand, verteilst du 4 Schlucke, lacht niemand, trinkst du 4.',
  '{{player}}, sprich bis zu deinem nächsten Schluck wie ein Pirat. Vergisst du es, trinkst du 3 Schlucke extra.',
  '{{player}} und {{player}}, spielt gemeinsam eine berühmte Filmszene nach. Errät die Runde den Film, verteilt ihr beide 3 Schlucke, sonst trinkt ihr 3.',
  '{{player}}, mach dein bestes Tiergeräusch. Die Runde stimmt ab: Überzeugt es nicht, trinkst du 4 Schlucke.',
  '{{player}}, mach einen Werbespot für das Getränk von {{player}}. Will die Mehrheit es danach probieren, verteilst du 4 Schlucke, sonst trinkst du 3.',
  '{{player}}, lass dir von {{player}} mit den Händen eine neue Frisur machen und trag sie bis zur nächsten Aufgabe, oder trink 4 Schlucke.',
  '{{player}} gibt {{player}} einen neuen Spitznamen. Für die nächsten 5 Aufgaben müssen alle ihn benutzen, wer es vergisst, trinkt 2 Schlucke.',
  '{{player}}, setz dir für die nächsten 3 Aufgaben einen Gegenstand vom Tisch als Hut auf den Kopf. Fällt er runter, trinkst du 3 Schlucke.',
  '{{player}}, schreib deinen Namen mit der Hüfte in die Luft, oder trink 4 Schlucke.',
  '{{player}}, mach 10 Hampelmänner und ruf bei jedem "Ich bin ein Star", oder trink 5 Schlucke.',
  '{{player}}, sprich die nächste Minute nur in Fragen. Jede Aussage kostet dich 2 Schlucke.',
  '{{player}}, tanz 30 Sekunden wie ein Roboter, oder trink 4 Schlucke.',
  '{{player}}, du hast 20 Sekunden, um {{player}} zum Lachen zu bringen, ohne die Person zu berühren. Lacht sie, trinkt sie 4 Schlucke, sonst trinkst du 4.',
  '{{player}}, beschreibe deinen Lieblingsfilm in 3 Sätzen, ohne Namen zu nennen. Errät ihn jemand, verteilst du 3 Schlucke, sonst trinkst du 3.',
  '{{player}}, spiel ein Navi und lotse {{player}} mit geschlossenen Augen einmal um den Tisch. Klappt es nicht, trinkt ihr beide 3 Schlucke.',
  '{{player}}, stell dich der Runde in 20 Sekunden vor, als wärst du beim Speeddating. Will dich die Mehrheit wiedersehen, verteilst du 4 Schlucke.',
  '{{player}}, rappe 4 Zeilen über {{player}}, oder trink 5 Schlucke.',
  '{{player}}, sing "Atemlos" mit der Stimme eines Heavy-Metal-Sängers, oder trink 5 Schlucke.',
  '{{player}}, imitiere {{player}} beim Bestellen an der Bar. Lacht die Person, verteilst du 3 Schlucke, sonst trinkst du 3.',
  '{{player}}, halte einen Heiratsantrag an {{player}}, ganz dramatisch und mit Kniefall. Sagt die Person Ja, verteilt ihr beide 3 Schlucke, sonst trinkst du 4.',
  '{{player}}, mach 20 Sekunden lang einen Schlagerstar beim Einzug in die Halle nach, oder trink 4 Schlucke.',
  '{{player}}, stell pantomimisch dar, wie du einen Promi deiner Wahl auf der Straße triffst. Errät die Runde den Promi, verteilst du 4 Schlucke.',
  '{{player}}, verrate deinen peinlichsten Spitznamen von früher, oder trink 4 Schlucke.',
  '{{player}}, erzähle deinen peinlichsten Moment bei einem Date, oder trink 5 Schlucke.',
  '{{player}}, sag, wer in der Runde den fragwürdigsten Musikgeschmack hat. Die Person trinkt 3 Schlucke. Weigerst du dich, trinkst du 5.',
  '{{player}}, beschreibe {{player}} mit 3 ehrlichen, aber netten Worten, oder trink 4 Schlucke.',
  '{{player}}, verrate, welchen Promi du heimlich ziemlich toll findest, oder trink 4 Schlucke.',
  '{{player}}, verrate, wonach du zuletzt gegoogelt hast, oder trink 4 Schlucke.',
  '{{player}}, gib deine schlimmste Modesünde zu, oder trink 3 Schlucke.',
  '{{player}}, lass {{player}} dir eine Frage stellen, die du ehrlich beantworten musst, oder trink 5 Schlucke.',
  '{{player}}, verrate, wen aus der Runde du um 3 Uhr nachts zu Hilfe holen würdest, oder trink 4 Schlucke.',
  '{{player}}, sag, wen aus der Runde du am liebsten als Mitbewohner hättest. Diese Person verteilt 3 Schlucke. Weigerst du dich, trinkst du 4.',
  '{{player}}, verrate deinen schlimmsten Flirtspruch, den du wirklich benutzt hast, oder trink 4 Schlucke.',
  '{{player}}, erzähle, was der verrückteste Grund war, aus dem du je eine Party verlassen hast, oder trink 4 Schlucke.',
  '{{player}}, verrate, welche App du am meisten benutzt und am wenigsten zugeben willst, oder trink 4 Schlucke.',
  '{{player}}, sag, wer in der Runde am wahrscheinlichsten heute noch einen Tanz auf dem Tisch hinlegt. Die Person trinkt 3 Schlucke, du verteilst 2.',
  '{{player}}, erzähle von deinem peinlichsten Schwarm aus der Schulzeit, oder trink 4 Schlucke.',
  '{{player}}, gib zu, welche Serie du heimlich schaust, obwohl sie furchtbar ist, oder trink 3 Schlucke.',
  '{{player}}, verrate, was du als Kind werden wolltest und warum es nicht geklappt hat, oder trink 3 Schlucke.',
  '{{player}}, wähle: Du sprichst die nächsten 3 Aufgaben nur in Reimen, oder du trinkst 5 Schlucke.',
  '{{player}}, wähle: Du singst einen Refrain deiner Wahl, oder du trinkst 4 Schlucke.',
  '{{player}}, wähle: Du tanzt 20 Sekunden zu einem Lied, das {{player}} aussucht, oder du trinkst 5 Schlucke.',
  '{{player}}, wähle: Du verteilst 4 Schlucke an eine Person, oder 1 Schluck an alle anderen.',
  '{{player}}, wähle: Du trinkst 3 Schlucke allein, oder du und {{player}} trinkt jeweils 2.',
  '{{player}}, wähle: Du tauschst für 3 Aufgaben den Platz mit {{player}}, oder du trinkst 4 Schlucke.',
  '{{player}}, wähle: Du verrätst deinen letzten Traum, an den du dich erinnerst, oder du trinkst 4 Schlucke.',
  '{{player}}, wähle: Wahrheit oder 5 Schlucke. Bei Wahrheit darf {{player}} dir eine Frage stellen.',
  '{{player}} verteilt 6 Schlucke beliebig in der Runde.',
  '{{player}} und {{player}} müssen zusammen 7 Schlucke trinken. Wie sie die aufteilen, handeln sie in 10 Sekunden aus, sonst trinkt jeder 5.',
  'Doppelt oder nichts: {{player}} rät die Farbe der Socken von {{player}}. Richtig: 6 Schlucke verteilen. Falsch: 3 Schlucke trinken.',
  '{{player}}, rate das Sternzeichen von {{player}}. Liegst du richtig, verteilst du 5 Schlucke, sonst trinkst du 3.',
  '{{player}}, rate, wie viel Prozent Akku {{player}} gerade hat. Liegst du höchstens 10 daneben, verteilst du 4 Schlucke, sonst trinkst du 4.',
  '{{player}}, schätze, wie viele Kontakte {{player}} im Handy hat. Liegst du höchstens 50 daneben, verteilst du 5 Schlucke, sonst trinkst du 3.',
  '{{player}}, rate, welchen Song {{player}} zuletzt gehört hat. Liegst du richtig, verteilst du 6 Schlucke.',
  'Wasserfall: {{player}} fängt an zu trinken, alle anderen folgen reihum und dürfen erst aufhören, wenn die Person vor ihnen aufhört.',
  'Alle trinken 2 Schlucke. Wer das Glas zuletzt wieder abstellt, trinkt 2 weitere.',
  'Alle stoßen an und trinken 3 Schlucke. Wer dabei jemandem nicht in die Augen schaut, trinkt noch einmal 2.',
  '{{player}}, trink dein Glas auf Ex. Danach darfst du für die nächsten 3 Aufgaben jede Aufgabe ablehnen, die dich trifft.',
  'Großer Einsatz: {{player}} und {{player}} spielen eine Runde Schere, Stein, Papier. Wer verliert, trinkt auf Ex.',
  'Gruppenpakt: Alle trinken gleichzeitig 3 Schlucke, außer {{player}}, die Person darf zuschauen und anfeuern.',
  'Die Person mit dem vollsten Glas trinkt 4 Schlucke.',
  'Die Person mit dem leersten Glas verteilt 4 Schlucke und darf sich nachschenken lassen.',
  'Die Person mit dem nächsten Geburtstag verteilt 5 Schlucke.',
  'Die Person, die heute am weitesten angereist ist, verteilt 5 Schlucke.',
  'Die Person, die am längsten Single ist, verteilt 4 Schlucke.',
  'Die Person, die zuletzt einen Kater hatte, trinkt 3 Schlucke.',
  'Wer heute die auffälligsten Schuhe trägt, verteilt 4 Schlucke. Die Runde entscheidet.',
  '{{player}} und {{player}} tauschen für die nächsten 3 Aufgaben ihre Getränke.',
  '{{player}}, die nächsten 3 Schlucke, die du trinken müsstest, trinkt stattdessen {{player}}.',
  'Duell der Stimmen: {{player}} und {{player}} singen gleichzeitig verschiedene Lieder. Wer zuerst aufhört oder lacht, trinkt 4 Schlucke.',
  'Duell der Komplimente: {{player}} und {{player}} machen sich abwechselnd Komplimente. Wem zuerst nichts mehr einfällt, trinkt 4 Schlucke.',
  'Duell der Grimassen: {{player}} und {{player}} schneiden Grimassen, die Runde stimmt ab. Wer verliert, trinkt 4 Schlucke.',
  '{{player}} und {{player}} versuchen, gleichzeitig dasselbe Wort zu sagen, nachdem {{player}} eine Kategorie genannt hat. Klappt es nicht beim ersten Mal, trinken beide 3 Schlucke.',
  '{{player}} und {{player}} sitzen Rücken an Rücken. {{player}} stellt Fragen wie "Wer ist eher zu spät?", beide zeigen gleichzeitig. Bei jeder Uneinigkeit trinken beide 1 Schluck, 3 Fragen lang.',
  '{{player}} und {{player}} halten sich an den Händen und dürfen 3 Aufgaben lang nicht loslassen. Wer zuerst loslässt, trinkt 4 Schlucke.',
  '{{player}} und {{player}} stellen sich mit geschlossenen Augen auf ein Bein. Wer zuerst wackelt und absetzen muss, trinkt 4 Schlucke.',
  '{{player}} und {{player}} erzählen gleichzeitig ihren Lieblingswitz. Wer die meisten Lacher bekommt, verteilt 4 Schlucke, die andere Person trinkt 3.',
  'Jeder sagt reihum ein Wort, bis ein Satz entsteht. {{player}} beginnt. Wer den Satz unlogisch macht, trinkt 3 Schlucke.',
  'Ich packe meinen Koffer: {{player}} beginnt. Wer etwas vergisst oder die Reihenfolge verdreht, trinkt 4 Schlucke.',
  'Reihum nennt jeder einen Film, in dem Tom Hanks mitspielt. {{player}} beginnt, wer nichts mehr weiß, trinkt 4 Schlucke.',
  'Reihum sagt jeder eine Sache, die er noch nie gemacht hat. Wer es schon gemacht hat, trinkt 2 Schlucke. {{player}} beginnt.',
  'Jeder schätzt, wie viele Schlucke er heute schon getrunken hat. Wer die höchste Zahl nennt, darf 4 Schlucke verteilen.',
  'Alle nennen gleichzeitig auf drei eine Zahl zwischen 1 und 5. Wer die gleiche Zahl wie jemand anderes nennt, trinkt so viele Schlucke.',
  'Alle heben auf drei 0 bis 5 Finger. {{player}} rät vorher die Summe. Richtig: 6 Schlucke verteilen. Falsch: 3 Schlucke trinken.',
  'Alle, die heute schon getanzt haben, verteilen 3 Schlucke. Alle anderen tanzen jetzt 10 Sekunden oder trinken 3.',
  '{{player}}, du wirst für die nächste Aufgabe zum Moderator: Lies sie wie ein Sprecher bei einer Preisverleihung vor. Weigerst du dich, trinkst du 3 Schlucke.',
  '{{player}}, ruf einmal laut "Ich bin die Partylegende des Abends". Die Runde jubelt oder du trinkst 3 Schlucke.',
  '{{player}}, mach einen Toast auf {{player}}, der mindestens 3 Sätze lang ist. Danach trinken alle 2 Schlucke.',
  '{{player}}, gib der Runde einen Trinkspruch, den noch niemand kennt. Gefällt er, trinken alle anderen 2 Schlucke.',
  '{{player}}, erfinde einen Gruß mit Handbewegung. Für die nächsten 3 Aufgaben muss jeder ihn vor dem Trinken machen, sonst 2 Schlucke extra.',
  '{{player}}, spiele einen Werbespot für dich selbst als perfekten Partygast. Überzeugst du die Runde, verteilst du 4 Schlucke.',
  '{{player}}, imitiere, wie {{player}} tanzt. Ist die Person einverstanden, verteilt ihr beide 3 Schlucke.',
  '{{player}}, erzähle eine erfundene Geschichte über {{player}}, als wäre sie wahr. Glaubt die Runde sie, verteilst du 4 Schlucke, sonst trinkst du 3.',
  '{{player}}, lass {{player}} einen Satz aussuchen, den du in der nächsten Aufgabe unauffällig einbauen musst. Merkt es jemand, trinkst du 4 Schlucke.',
  '{{player}}, du darfst bis zur übernächsten Aufgabe nicht lachen. Bringt dich jemand zum Lachen, trinkst du 4 Schlucke und die Person verteilt 2.',
  '{{player}}, du hast 1 Minute, um 3 Leute in der Runde zum Lachen zu bringen. Schaffst du es, verteilst du 6 Schlucke, sonst trinkst du 4.',
  '{{player}}, du stehst für die nächsten 2 Aufgaben. Setzt du dich, trinkst du 3 Schlucke.',
  '{{player}}, erzähle in 30 Sekunden dein ganzes Leben im Stil einer Dokumentation. Schaffst du es nicht, trinkst du 3 Schlucke.',
  '{{player}}, stell dir vor, du bist in einer Kochshow, und koche pantomimisch ein Gericht. Errät die Runde es, verteilst du 3 Schlucke.',
  '{{player}}, mach eine Ansage wie ein Pilot an Bord, inklusive Turbulenzen. Wer lacht, trinkt 2 Schlucke.',
  '{{player}}, verkünde wie ein Hochzeitsplaner, wer aus der Runde zuerst heiratet. Die genannte Person trinkt 3 Schlucke.',
  '{{player}}, sing "Happy Birthday" für {{player}}, obwohl kein Geburtstag ist. Danach verteilt die Person 3 Schlucke.',
  '{{player}}, gib {{player}} 10 Sekunden lang ein ehrliches Lob über das Outfit. Fällt dir nichts ein, trinkst du 4 Schlucke.',
  '{{player}}, wähle eine Person, die mit dir zusammen 20 Sekunden lang eine Boyband-Choreo improvisiert, oder trink 5 Schlucke.',
  '{{player}}, spiel einen Influencer, der das Getränk in deiner Hand in einer Story bewirbt. Danach trinken alle 1 Schluck darauf.',
  '{{player}}, nimm eine dramatische Pose ein und halte sie bis zum Ende der nächsten Aufgabe. Vorher bewegen kostet 4 Schlucke.',
  '{{player}}, mach den Moderator einer Datingshow und verkupple 2 Personen in der Runde. Diese 2 trinken zusammen 3 Schlucke.',
  '{{player}}, stell dir vor, du hast gerade den Oscar gewonnen, und halte deine Dankesrede. Gefällt sie der Runde, verteilst du 5 Schlucke.',
  '{{player}}, zähle in 10 Sekunden 5 Dinge auf, die du an {{player}} magst, oder trink 4 Schlucke.',
  '{{player}}, wähle eine Person aus, die die nächste Aufgabe mit deinem Namen für dich übernimmt. Dafür trinkst du jetzt 3 Schlucke.',
  'Abstimmung: Wer ist der größere Partymensch, {{player}} oder {{player}}? Wer weniger Stimmen bekommt, trinkt 4 Schlucke.',
];
