import type { WavelengthSeed } from './types';

export const abstractSpectrums: WavelengthSeed[] = [
  {
    left: 'Schlechte Superkraft',
    right: 'Gute Superkraft',
    leftEn: 'Bad superpower',
    rightEn: 'Good superpower',
  },
  { left: 'Keine Kunst', right: 'Kunst', leftEn: 'Not art', rightEn: 'Art' },
  { left: 'Unterbewertet', right: 'Überbewertet', leftEn: 'Underrated', rightEn: 'Overrated' },
  { left: 'Vergänglich', right: 'Ewig', leftEn: 'Fleeting', rightEn: 'Eternal' },
  { left: 'Normal', right: 'Seltsam', leftEn: 'Normal', rightEn: 'Weird' },
  {
    left: 'Moralisch falsch',
    right: 'Moralisch richtig',
    leftEn: 'Morally wrong',
    rightEn: 'Morally right',
  },
  { left: 'Sünde', right: 'Tugend', leftEn: 'Sin', rightEn: 'Virtue' },
  { left: 'Zufall', right: 'Schicksal', leftEn: 'Coincidence', rightEn: 'Fate' },
  { left: 'Natürlich', right: 'Künstlich', leftEn: 'Natural', rightEn: 'Artificial' },
  { left: 'Einfach', right: 'Kompliziert', leftEn: 'Simple', rightEn: 'Complicated' },
  { left: 'Unwichtig', right: 'Lebenswichtig', leftEn: 'Trivial', rightEn: 'Vital' },
  { left: 'Real', right: 'Erfunden', leftEn: 'Real', rightEn: 'Made up' },
  { left: 'Vergangenheit', right: 'Zukunft', leftEn: 'Past', rightEn: 'Future' },
  { left: 'Chaos', right: 'Ordnung', leftEn: 'Chaos', rightEn: 'Order' },
  { left: 'Hässlich', right: 'Schön', leftEn: 'Ugly', rightEn: 'Beautiful' },
  {
    left: 'Kopfsache',
    right: 'Herzenssache',
    leftEn: 'Matter of reason',
    rightEn: 'Matter of heart',
  },
  {
    left: 'Leichte Entscheidung',
    right: 'Schwere Entscheidung',
    leftEn: 'Easy decision',
    rightEn: 'Hard decision',
  },
  { left: 'Verzeihlich', right: 'Unverzeihlich', leftEn: 'Forgivable', rightEn: 'Unforgivable' },
  { left: 'Erlaubt', right: 'Verboten', leftEn: 'Allowed', rightEn: 'Forbidden' },
  { left: 'Unmöglich', right: 'Machbar', leftEn: 'Impossible', rightEn: 'Doable' },
  { left: 'Theorie', right: 'Praxis', leftEn: 'Theory', rightEn: 'Practice' },
  { left: 'Glück', right: 'Können', leftEn: 'Luck', rightEn: 'Skill' },
  { left: 'Talent', right: 'Fleiß', leftEn: 'Talent', rightEn: 'Hard work' },
  { left: 'Instinkt', right: 'Erlernt', leftEn: 'Instinct', rightEn: 'Learned' },
  { left: 'Kindisch', right: 'Erwachsen', leftEn: 'Childish', rightEn: 'Grown up' },
  { left: 'Maskulin', right: 'Feminin', leftEn: 'Masculine', rightEn: 'Feminine' },
  { left: 'Lüge', right: 'Wahrheit', leftEn: 'Lie', rightEn: 'Truth' },
  {
    left: 'Notwendiges Übel',
    right: 'Echter Segen',
    leftEn: 'Necessary evil',
    rightEn: 'True blessing',
  },
  { left: 'Rückschritt', right: 'Fortschritt', leftEn: 'Step back', rightEn: 'Progress' },
  { left: 'Kurzfristig', right: 'Langfristig', leftEn: 'Short term', rightEn: 'Long term' },
  { left: 'Dystopie', right: 'Utopie', leftEn: 'Dystopia', rightEn: 'Utopia' },
  { left: 'Hölle', right: 'Himmel', leftEn: 'Hell', rightEn: 'Heaven' },
  { left: 'Albtraum', right: 'Traum', leftEn: 'Nightmare', rightEn: 'Dream' },
  { left: 'Geschmacklos', right: 'Geschmackvoll', leftEn: 'Tasteless', rightEn: 'Tasteful' },
  { left: 'Kitschig', right: 'Stilvoll', leftEn: 'Cheesy', rightEn: 'Stylish' },
  { left: 'Mainstream', right: 'Nische', leftEn: 'Mainstream', rightEn: 'Niche' },
  { left: 'Unbedeutend', right: 'Historisch', leftEn: 'Insignificant', rightEn: 'Historic' },
  { left: 'Unbedenklich', right: 'Bedenklich', leftEn: 'Harmless', rightEn: 'Concerning' },
  { left: 'Erholsam', right: 'Anstrengend', leftEn: 'Restful', rightEn: 'Exhausting' },
  {
    left: 'Zeitverschwendung',
    right: 'Gut investierte Zeit',
    leftEn: 'Waste of time',
    rightEn: 'Time well spent',
  },
  { left: 'Luxus', right: 'Grundbedürfnis', leftEn: 'Luxury', rightEn: 'Basic need' },
  { left: 'Vertraut', right: 'Mysteriös', leftEn: 'Familiar', rightEn: 'Mysterious' },
  { left: 'Sicher', right: 'Riskant', leftEn: 'Safe', rightEn: 'Risky' },
  {
    left: 'Schlechte Erfindung',
    right: 'Gute Erfindung',
    leftEn: 'Bad invention',
    rightEn: 'Great invention',
  },
  { left: 'Schlechte Idee', right: 'Gute Idee', leftEn: 'Bad idea', rightEn: 'Good idea' },
  { left: 'Schlechter Rat', right: 'Guter Rat', leftEn: 'Bad advice', rightEn: 'Good advice' },
  {
    left: 'Schlechte Ausrede',
    right: 'Gute Ausrede',
    leftEn: 'Bad excuse',
    rightEn: 'Good excuse',
  },
  { left: 'Schlechtes Hobby', right: 'Gutes Hobby', leftEn: 'Bad hobby', rightEn: 'Good hobby' },
  { left: 'Schlechtes Haustier', right: 'Gutes Haustier', leftEn: 'Bad pet', rightEn: 'Good pet' },
  {
    left: 'Schlechte Angewohnheit',
    right: 'Gute Angewohnheit',
    leftEn: 'Bad habit',
    rightEn: 'Good habit',
  },
  {
    left: 'Schlechtes Geschenk',
    right: 'Gutes Geschenk',
    leftEn: 'Bad gift',
    rightEn: 'Good gift',
  },
  { left: 'Schlechte Epoche', right: 'Gute Epoche', leftEn: 'Bad era', rightEn: 'Good era' },
  {
    left: 'Schlechte Lebensweisheit',
    right: 'Gute Lebensweisheit',
    leftEn: 'Bad life lesson',
    rightEn: 'Good life lesson',
  },
  {
    left: 'Hässliches Wort',
    right: 'Schönes Wort',
    leftEn: 'Ugly word',
    rightEn: 'Beautiful word',
  },
  { left: 'Schlechter Name', right: 'Guter Name', leftEn: 'Bad name', rightEn: 'Good name' },
  {
    left: 'Schwacher Beweis',
    right: 'Starker Beweis',
    leftEn: 'Weak evidence',
    rightEn: 'Strong evidence',
  },
  { left: 'Machtlos', right: 'Mächtig', leftEn: 'Powerless', rightEn: 'Powerful' },
  {
    left: 'Leicht zu erklären',
    right: 'Unerklärlich',
    leftEn: 'Easy to explain',
    rightEn: 'Inexplicable',
  },
  { left: 'Leise', right: 'Ohrenbetäubend', leftEn: 'Quiet', rightEn: 'Deafening' },
  { left: 'Schlechtes Omen', right: 'Gutes Omen', leftEn: 'Bad omen', rightEn: 'Good omen' },
  { left: 'Leicht', right: 'Schwer', leftEn: 'Light', rightEn: 'Heavy' },
  {
    left: 'Müllreif',
    right: 'Museumsreif',
    leftEn: 'Trash worthy',
    rightEn: 'Museum worthy',
  },
  { left: 'Rund', right: 'Eckig', leftEn: 'Round', rightEn: 'Angular' },
  { left: 'Kleine Sünde', right: 'Todsünde', leftEn: 'Minor sin', rightEn: 'Deadly sin' },
  { left: 'Dunkel', right: 'Hell', leftEn: 'Dark', rightEn: 'Bright' },
  { left: 'Sauber', right: 'Dreckig', leftEn: 'Clean', rightEn: 'Dirty' },
  { left: 'Alt', right: 'Neu', leftEn: 'Old', rightEn: 'New' },
  { left: 'Stillstand', right: 'Bewegung', leftEn: 'Stillness', rightEn: 'Motion' },
  { left: 'Vorhersehbar', right: 'Überraschend', leftEn: 'Predictable', rightEn: 'Surprising' },
  { left: 'Logisch', right: 'Absurd', leftEn: 'Logical', rightEn: 'Absurd' },
  { left: 'Ernst', right: 'Albern', leftEn: 'Serious', rightEn: 'Silly' },
  { left: 'Tragisch', right: 'Komisch', leftEn: 'Tragic', rightEn: 'Comic' },
  { left: 'Traurig', right: 'Glücklich', leftEn: 'Sad', rightEn: 'Happy' },
  { left: 'Beruhigend', right: 'Beängstigend', leftEn: 'Calming', rightEn: 'Scary' },
  { left: 'Ungemütlich', right: 'Gemütlich', leftEn: 'Uncomfortable', rightEn: 'Cozy' },
  { left: 'Unschuldig', right: 'Verdorben', leftEn: 'Innocent', rightEn: 'Depraved' },
  { left: 'Heilig', right: 'Profan', leftEn: 'Sacred', rightEn: 'Profane' },
  { left: 'Spirituell', right: 'Materiell', leftEn: 'Spiritual', rightEn: 'Material' },
  { left: 'Körper', right: 'Geist', leftEn: 'Body', rightEn: 'Mind' },
  { left: 'Individuum', right: 'Gesellschaft', leftEn: 'Individual', rightEn: 'Society' },
  { left: 'Freiheit', right: 'Sicherheit', leftEn: 'Freedom', rightEn: 'Security' },
  { left: 'Tradition', right: 'Innovation', leftEn: 'Tradition', rightEn: 'Innovation' },
  { left: 'Ursache', right: 'Wirkung', leftEn: 'Cause', rightEn: 'Effect' },
  { left: 'Anfang', right: 'Ende', leftEn: 'Beginning', rightEn: 'End' },
  { left: 'Frage', right: 'Antwort', leftEn: 'Question', rightEn: 'Answer' },
  { left: 'Problem', right: 'Lösung', leftEn: 'Problem', rightEn: 'Solution' },
  { left: 'Objektiv', right: 'Subjektiv', leftEn: 'Objective', rightEn: 'Subjective' },
  { left: 'Konkret', right: 'Abstrakt', leftEn: 'Concrete', rightEn: 'Abstract' },
  { left: 'Wissenschaft', right: 'Glaube', leftEn: 'Science', rightEn: 'Faith' },
  { left: 'Fakt', right: 'Meinung', leftEn: 'Fact', rightEn: 'Opinion' },
  {
    left: 'Vergessenswert',
    right: 'Unvergesslich',
    leftEn: 'Forgettable',
    rightEn: 'Unforgettable',
  },
  { left: 'Geheimnis', right: 'Allgemeinwissen', leftEn: 'Secret', rightEn: 'Common knowledge' },
  { left: 'Unverdient', right: 'Verdient', leftEn: 'Undeserved', rightEn: 'Deserved' },
  { left: 'Unfair', right: 'Fair', leftEn: 'Unfair', rightEn: 'Fair' },
  { left: 'Ironisch', right: 'Aufrichtig', leftEn: 'Ironic', rightEn: 'Sincere' },
  { left: 'Bedeutungslos', right: 'Bedeutungsvoll', leftEn: 'Meaningless', rightEn: 'Meaningful' },
  { left: 'Hoffnungslos', right: 'Hoffnungsvoll', leftEn: 'Hopeless', rightEn: 'Hopeful' },
  {
    left: 'Schadet der Welt',
    right: 'Hilft der Welt',
    leftEn: 'Harms the world',
    rightEn: 'Helps the world',
  },
  { left: 'Yin', right: 'Yang', leftEn: 'Yin', rightEn: 'Yang' },
  { left: 'Ordinär', right: 'Elegant', leftEn: 'Vulgar', rightEn: 'Elegant' },
];
