import type { WavelengthSeed } from './types';

export const foodSpectrums: WavelengthSeed[] = [
  { left: 'Ekelhaft', right: 'Lecker', leftEn: 'Disgusting', rightEn: 'Delicious' },
  { left: 'Gesund', right: 'Ungesund', leftEn: 'Healthy', rightEn: 'Unhealthy' },
  { left: 'Frühstück', right: 'Abendessen', leftEn: 'Breakfast', rightEn: 'Dinner' },
  { left: 'Kinderessen', right: 'Erwachsenenessen', leftEn: 'Kids’ food', rightEn: 'Adult food' },
  { left: 'Mild', right: 'Scharf', leftEn: 'Mild', rightEn: 'Spicy' },
  { left: 'Süß', right: 'Salzig', leftEn: 'Sweet', rightEn: 'Salty' },
  { left: 'Süß', right: 'Sauer', leftEn: 'Sweet', rightEn: 'Sour' },
  { left: 'Matschig', right: 'Knusprig', leftEn: 'Soggy', rightEn: 'Crunchy' },
  { left: 'Leichte Kost', right: 'Schwere Kost', leftEn: 'Light meal', rightEn: 'Heavy meal' },
  { left: 'Snack', right: 'Hauptgericht', leftEn: 'Snack', rightEn: 'Main course' },
  { left: 'Vorspeise', right: 'Dessert', leftEn: 'Starter', rightEn: 'Dessert' },
  {
    left: 'Billiges Essen',
    right: 'Teures Essen',
    leftEn: 'Cheap food',
    rightEn: 'Expensive food',
  },
  { left: 'Fast Food', right: 'Sternerestaurant', leftEn: 'Fast food', rightEn: 'Fine dining' },
  {
    left: 'Hausmannskost',
    right: 'Gourmetküche',
    leftEn: 'Home cooking',
    rightEn: 'Gourmet cuisine',
  },
  {
    left: 'Überschätztes Essen',
    right: 'Unterschätztes Essen',
    leftEn: 'Overrated food',
    rightEn: 'Underrated food',
  },
  {
    left: 'Schlechtes Pizzatopping',
    right: 'Bestes Pizzatopping',
    leftEn: 'Bad pizza topping',
    rightEn: 'Best pizza topping',
  },
  { left: 'Besser kalt', right: 'Besser warm', leftEn: 'Better cold', rightEn: 'Better hot' },
  {
    left: 'Schnell gekocht',
    right: 'Stundenlang gekocht',
    leftEn: 'Quick to cook',
    rightEn: 'Takes hours',
  },
  {
    left: 'Leicht zu kochen',
    right: 'Schwer zu kochen',
    leftEn: 'Easy to cook',
    rightEn: 'Hard to cook',
  },
  { left: 'Sommeressen', right: 'Winteressen', leftEn: 'Summer food', rightEn: 'Winter food' },
  {
    left: 'Macht nicht satt',
    right: 'Macht pappsatt',
    leftEn: 'Not filling',
    rightEn: 'Very filling',
  },
  {
    left: 'Fingerfood',
    right: 'Messer und Gabel',
    leftEn: 'Finger food',
    rightEn: 'Knife and fork',
  },
  {
    left: 'Sauber zu essen',
    right: 'Riesige Sauerei',
    leftEn: 'Clean to eat',
    rightEn: 'Total mess',
  },
  { left: 'Vegan', right: 'Fleischlastig', leftEn: 'Vegan', rightEn: 'Meat heavy' },
  { left: 'Typisch deutsch', right: 'Exotisch', leftEn: 'Typically German', rightEn: 'Exotic' },
  { left: 'Alkoholfrei', right: 'Hochprozentig', leftEn: 'Alcohol free', rightEn: 'Hard liquor' },
  {
    left: 'Schlechtes Getränk',
    right: 'Gutes Getränk',
    leftEn: 'Bad drink',
    rightEn: 'Great drink',
  },
  { left: 'Erfrischend', right: 'Wärmend', leftEn: 'Refreshing', rightEn: 'Warming' },
  { left: 'Schlechter Dip', right: 'Bester Dip', leftEn: 'Worst dip', rightEn: 'Best dip' },
  {
    left: 'Schlechte Eissorte',
    right: 'Beste Eissorte',
    leftEn: 'Worst ice cream',
    rightEn: 'Best ice cream',
  },
  {
    left: 'Schlechte Chipssorte',
    right: 'Beste Chipssorte',
    leftEn: 'Worst chips flavor',
    rightEn: 'Best chips flavor',
  },
  {
    left: 'Schlechter Brotaufstrich',
    right: 'Bester Brotaufstrich',
    leftEn: 'Worst spread',
    rightEn: 'Best spread',
  },
  {
    left: 'Schlechte Beilage',
    right: 'Beste Beilage',
    leftEn: 'Worst side dish',
    rightEn: 'Best side dish',
  },
  { left: 'Schlechte Soße', right: 'Beste Soße', leftEn: 'Worst sauce', rightEn: 'Best sauce' },
  {
    left: 'Schlechtes Gemüse',
    right: 'Bestes Gemüse',
    leftEn: 'Worst vegetable',
    rightEn: 'Best vegetable',
  },
  { left: 'Schlechtes Obst', right: 'Bestes Obst', leftEn: 'Worst fruit', rightEn: 'Best fruit' },
  {
    left: 'Schlechtes Frühstück',
    right: 'Perfektes Frühstück',
    leftEn: 'Bad breakfast',
    rightEn: 'Perfect breakfast',
  },
  {
    left: 'Schlechte Süßigkeit',
    right: 'Beste Süßigkeit',
    leftEn: 'Worst candy',
    rightEn: 'Best candy',
  },
  { left: 'Schlechter Kuchen', right: 'Bester Kuchen', leftEn: 'Worst cake', rightEn: 'Best cake' },
  {
    left: 'Alltagsessen',
    right: 'Festtagsessen',
    leftEn: 'Everyday food',
    rightEn: 'Holiday feast',
  },
  {
    left: 'Naturbelassen',
    right: 'Hochverarbeitet',
    leftEn: 'Unprocessed',
    rightEn: 'Ultra processed',
  },
  { left: 'Frisch', right: 'Ewig haltbar', leftEn: 'Fresh', rightEn: 'Keeps forever' },
  { left: 'Stinkt', right: 'Duftet', leftEn: 'Stinks', rightEn: 'Smells great' },
  { left: 'Zum Teilen', right: 'Nur für mich', leftEn: 'For sharing', rightEn: 'All for me' },
  { left: 'Kalorienarm', right: 'Kalorienbombe', leftEn: 'Low calorie', rightEn: 'Calorie bomb' },
  {
    left: 'Unspektakulär',
    right: 'Instagramtauglich',
    leftEn: 'Plain looking',
    rightEn: 'Instagram worthy',
  },
  {
    left: 'Sieht eklig aus',
    right: 'Sieht lecker aus',
    leftEn: 'Looks gross',
    rightEn: 'Looks tasty',
  },
  { left: 'Diätessen', right: 'Seelenfutter', leftEn: 'Diet food', rightEn: 'Comfort food' },
  {
    left: 'Roh essbar',
    right: 'Muss gekocht werden',
    leftEn: 'Fine raw',
    rightEn: 'Must be cooked',
  },
  {
    left: 'Schlecht zum Grillen',
    right: 'Perfekt zum Grillen',
    leftEn: 'Bad for grilling',
    rightEn: 'Perfect for grilling',
  },
  {
    left: 'Schlecht fürs Picknick',
    right: 'Perfekt fürs Picknick',
    leftEn: 'Bad picnic food',
    rightEn: 'Perfect picnic food',
  },
  {
    left: 'Schlechter Kinosnack',
    right: 'Perfekter Kinosnack',
    leftEn: 'Bad movie snack',
    rightEn: 'Perfect movie snack',
  },
  {
    left: 'Schlechter Mitternachtssnack',
    right: 'Perfekter Mitternachtssnack',
    leftEn: 'Bad midnight snack',
    rightEn: 'Perfect midnight snack',
  },
  {
    left: 'Morgens trinken',
    right: 'Abends trinken',
    leftEn: 'Morning drink',
    rightEn: 'Evening drink',
  },
  {
    left: 'Durstlöscher',
    right: 'Genussgetränk',
    leftEn: 'Thirst quencher',
    rightEn: 'Treat drink',
  },
  { left: 'Fade', right: 'Intensiv', leftEn: 'Bland', rightEn: 'Intense' },
  {
    left: 'Zu wenig gewürzt',
    right: 'Überwürzt',
    leftEn: 'Underseasoned',
    rightEn: 'Overseasoned',
  },
  { left: 'Klassiker', right: 'Foodtrend', leftEn: 'Classic dish', rightEn: 'Food trend' },
  {
    left: 'Omas Küche',
    right: 'Hipsterküche',
    leftEn: 'Grandma’s cooking',
    rightEn: 'Hipster food',
  },
  { left: 'Für jeden', right: 'Für Feinschmecker', leftEn: 'For everyone', rightEn: 'For foodies' },
  {
    left: 'Mag jeder',
    right: 'Gewöhnungssache',
    leftEn: 'Crowd pleaser',
    rightEn: 'Acquired taste',
  },
  {
    left: 'Gut zum Liefern',
    right: 'Nur frisch gut',
    leftEn: 'Good for delivery',
    rightEn: 'Only good fresh',
  },
  {
    left: 'Aufgewärmt eklig',
    right: 'Aufgewärmt besser',
    leftEn: 'Gross reheated',
    rightEn: 'Better reheated',
  },
  {
    left: 'Lieber bestellen',
    right: 'Lieber selbst kochen',
    leftEn: 'Better ordered',
    rightEn: 'Better homemade',
  },
  { left: 'Trocken', right: 'Saftig', leftEn: 'Dry', rightEn: 'Juicy' },
  { left: 'Zäh', right: 'Zart', leftEn: 'Tough', rightEn: 'Tender' },
  { left: 'Flüssig', right: 'Fest', leftEn: 'Liquid', rightEn: 'Solid' },
  { left: 'Saisonal', right: 'Ganzjährig', leftEn: 'Seasonal', rightEn: 'Year round' },
  { left: 'Regional', right: 'Importiert', leftEn: 'Local produce', rightEn: 'Imported' },
  { left: 'Zuckerfrei', right: 'Zuckerbombe', leftEn: 'Sugar free', rightEn: 'Sugar bomb' },
  { left: 'Wenig Protein', right: 'Viel Protein', leftEn: 'Low protein', rightEn: 'High protein' },
  {
    left: 'Passt zu Kaffee',
    right: 'Passt zu Wein',
    leftEn: 'Goes with coffee',
    rightEn: 'Goes with wine',
  },
  { left: 'Bauernessen', right: 'Königsessen', leftEn: 'Peasant food', rightEn: 'Royal food' },
  {
    left: 'Leicht auszusprechen',
    right: 'Schwer auszusprechen',
    leftEn: 'Easy to pronounce',
    rightEn: 'Hard to pronounce',
  },
  { left: 'Klingt eklig', right: 'Klingt lecker', leftEn: 'Sounds gross', rightEn: 'Sounds tasty' },
  {
    left: 'Gibt’s überall',
    right: 'Nur im Urlaub',
    leftEn: 'Available everywhere',
    rightEn: 'Only on holiday',
  },
  {
    left: 'Wenige Zutaten',
    right: 'Viele Zutaten',
    leftEn: 'Few ingredients',
    rightEn: 'Many ingredients',
  },
  {
    left: 'Schnell gegessen',
    right: 'Langsam genossen',
    leftEn: 'Wolfed down',
    rightEn: 'Savored slowly',
  },
  { left: 'Normales Essen', right: 'Mutprobe', leftEn: 'Normal food', rightEn: 'A dare' },
  { left: 'Für unterwegs', right: 'Nur am Tisch', leftEn: 'On the go', rightEn: 'Table only' },
  {
    left: 'Krümelt nicht',
    right: 'Krümelt überall',
    leftEn: 'No crumbs',
    rightEn: 'Crumbs everywhere',
  },
  { left: 'Einmal reicht', right: 'Jeden Tag', leftEn: 'Once is enough', rightEn: 'Every day' },
  { left: 'Rustikal', right: 'Edel', leftEn: 'Rustic', rightEn: 'Posh' },
  { left: 'Cremig', right: 'Stückig', leftEn: 'Smooth', rightEn: 'Chunky' },
  { left: 'Macht wach', right: 'Macht müde', leftEn: 'Wakes you up', rightEn: 'Makes you sleepy' },
  { left: 'Mager', right: 'Fettig', leftEn: 'Lean', rightEn: 'Greasy' },
  {
    left: 'Schlechtes Kantinenessen',
    right: 'Gutes Kantinenessen',
    leftEn: 'Bad canteen food',
    rightEn: 'Good canteen food',
  },
  { left: 'Schlechtes Brot', right: 'Bestes Brot', leftEn: 'Worst bread', rightEn: 'Best bread' },
  { left: 'Schlechter Käse', right: 'Bester Käse', leftEn: 'Worst cheese', rightEn: 'Best cheese' },
  {
    left: 'Schlechtes Frühstücksmüsli',
    right: 'Bestes Frühstücksmüsli',
    leftEn: 'Worst cereal',
    rightEn: 'Best cereal',
  },
  {
    left: 'Schlechtes Sandwich',
    right: 'Bestes Sandwich',
    leftEn: 'Worst sandwich',
    rightEn: 'Best sandwich',
  },
  {
    left: 'Schlechtes Heißgetränk',
    right: 'Bestes Heißgetränk',
    leftEn: 'Worst hot drink',
    rightEn: 'Best hot drink',
  },
  { left: 'Schlechte Limo', right: 'Beste Limo', leftEn: 'Worst soda', rightEn: 'Best soda' },
  {
    left: 'Schlechtes Nationalgericht',
    right: 'Bestes Nationalgericht',
    leftEn: 'Worst national dish',
    rightEn: 'Best national dish',
  },
  {
    left: 'Schlechtes Streetfood',
    right: 'Bestes Streetfood',
    leftEn: 'Worst street food',
    rightEn: 'Best street food',
  },
  {
    left: 'Schlechte Pizza',
    right: 'Perfekte Pizza',
    leftEn: 'Bad pizza',
    rightEn: 'Perfect pizza',
  },
  {
    left: 'Krankenhausessen',
    right: 'Hochzeitsbuffet',
    leftEn: 'Hospital food',
    rightEn: 'Wedding buffet',
  },
  {
    left: 'Studentenküche',
    right: 'Luxusküche',
    leftEn: 'Student cooking',
    rightEn: 'Luxury cooking',
  },
  {
    left: 'Kaum Abwasch',
    right: 'Riesiger Abwasch',
    leftEn: 'Few dishes',
    rightEn: 'Mountain of dishes',
  },
  {
    left: 'Schlechtes Kindergericht',
    right: 'Bestes Kindergericht',
    leftEn: 'Worst kids’ meal',
    rightEn: 'Best kids’ meal',
  },
];
