import type { WavelengthSeed } from './types';

export const normalSpectrums: WavelengthSeed[] = [
  { left: 'Kalt', right: 'Heiß', leftEn: 'Cold', rightEn: 'Hot' },
  { left: 'Billig', right: 'Teuer', leftEn: 'Cheap', rightEn: 'Expensive' },
  { left: 'Nutzlos', right: 'Nützlich', leftEn: 'Useless', rightEn: 'Useful' },
  { left: 'Langweilig', right: 'Spannend', leftEn: 'Boring', rightEn: 'Exciting' },
  {
    left: 'Leicht zu lernen',
    right: 'Schwer zu lernen',
    leftEn: 'Easy to learn',
    rightEn: 'Hard to learn',
  },
  { left: 'Klein', right: 'Groß', leftEn: 'Small', rightEn: 'Big' },
  { left: 'Langsam', right: 'Schnell', leftEn: 'Slow', rightEn: 'Fast' },
  { left: 'Weich', right: 'Hart', leftEn: 'Soft', rightEn: 'Hard' },
  { left: 'Selten', right: 'Häufig', leftEn: 'Rare', rightEn: 'Common' },
  { left: 'Trocken', right: 'Nass', leftEn: 'Dry', rightEn: 'Wet' },
  { left: 'Unbequem', right: 'Bequem', leftEn: 'Uncomfortable', rightEn: 'Comfortable' },
  { left: 'Altmodisch', right: 'Modern', leftEn: 'Outdated', rightEn: 'Modern' },
  { left: 'Unpraktisch', right: 'Praktisch', leftEn: 'Impractical', rightEn: 'Practical' },
  { left: 'Laienhaft', right: 'Professionell', leftEn: 'Amateurish', rightEn: 'Professional' },
  { left: 'Städtisch', right: 'Ländlich', leftEn: 'Urban', rightEn: 'Rural' },
  { left: 'Drinnen', right: 'Draußen', leftEn: 'Indoors', rightEn: 'Outdoors' },
  { left: 'Kinderkram', right: 'Erwachsenensache', leftEn: 'Kid stuff', rightEn: 'Adult stuff' },
  { left: 'Gewöhnlich', right: 'Außergewöhnlich', leftEn: 'Ordinary', rightEn: 'Extraordinary' },
  { left: 'Glatt', right: 'Rau', leftEn: 'Smooth', rightEn: 'Rough' },
  { left: 'Stumpf', right: 'Scharf', leftEn: 'Dull', rightEn: 'Sharp' },
  { left: 'Flach', right: 'Tief', leftEn: 'Shallow', rightEn: 'Deep' },
  { left: 'Dünn', right: 'Dick', leftEn: 'Thin', rightEn: 'Thick' },
  { left: 'Kurz', right: 'Lang', leftEn: 'Short', rightEn: 'Long' },
  { left: 'Schmal', right: 'Breit', leftEn: 'Narrow', rightEn: 'Wide' },
  { left: 'Leer', right: 'Voll', leftEn: 'Empty', rightEn: 'Full' },
  { left: 'Entspannt', right: 'Stressig', leftEn: 'Relaxed', rightEn: 'Stressful' },
  { left: 'Uncool', right: 'Cool', leftEn: 'Uncool', rightEn: 'Cool' },
  { left: 'Zerbrechlich', right: 'Robust', leftEn: 'Fragile', rightEn: 'Sturdy' },
  {
    left: 'Harmloses Tier',
    right: 'Gefährliches Tier',
    leftEn: 'Harmless animal',
    rightEn: 'Dangerous animal',
  },
  { left: 'Haustier', right: 'Wildtier', leftEn: 'Pet', rightEn: 'Wild animal' },
  {
    left: 'Niedliches Tier',
    right: 'Ekliges Tier',
    leftEn: 'Cute animal',
    rightEn: 'Gross animal',
  },
  {
    left: 'Schlechter Urlaubsort',
    right: 'Traumurlaubsort',
    leftEn: 'Bad holiday spot',
    rightEn: 'Dream destination',
  },
  {
    left: 'Schlechtes Geschenk',
    right: 'Tolles Geschenk',
    leftEn: 'Bad gift',
    rightEn: 'Great gift',
  },
  {
    left: 'Unterbezahlter Job',
    right: 'Überbezahlter Job',
    leftEn: 'Underpaid job',
    rightEn: 'Overpaid job',
  },
  { left: 'Entspannter Job', right: 'Knochenjob', leftEn: 'Easy job', rightEn: 'Backbreaking job' },
  {
    left: 'Schlechte Erfindung',
    right: 'Geniale Erfindung',
    leftEn: 'Bad invention',
    rightEn: 'Brilliant invention',
  },
  { left: 'Low Tech', right: 'High Tech', leftEn: 'Low tech', rightEn: 'High tech' },
  {
    left: 'Hobby für Alte',
    right: 'Hobby für Junge',
    leftEn: 'Old people hobby',
    rightEn: 'Young people hobby',
  },
  { left: 'Kein Sport', right: 'Echter Sport', leftEn: 'Not a sport', rightEn: 'Real sport' },
  {
    left: 'Schlechtes Wetter',
    right: 'Traumwetter',
    leftEn: 'Bad weather',
    rightEn: 'Perfect weather',
  },
  { left: 'Winterlich', right: 'Sommerlich', leftEn: 'Wintery', rightEn: 'Summery' },
  { left: 'Unordentlich', right: 'Aufgeräumt', leftEn: 'Messy', rightEn: 'Tidy' },
  { left: 'Analog', right: 'Digital', leftEn: 'Analog', rightEn: 'Digital' },
  { left: 'Lässig', right: 'Schick', leftEn: 'Casual', rightEn: 'Fancy' },
  {
    left: 'Schlechter Hundename',
    right: 'Guter Hundename',
    leftEn: 'Bad dog name',
    rightEn: 'Good dog name',
  },
  {
    left: 'Schlechter Babyname',
    right: 'Guter Babyname',
    leftEn: 'Bad baby name',
    rightEn: 'Good baby name',
  },
  {
    left: 'Schlechtes Souvenir',
    right: 'Tolles Souvenir',
    leftEn: 'Bad souvenir',
    rightEn: 'Great souvenir',
  },
  {
    left: 'Überschätzte Stadt',
    right: 'Unterschätzte Stadt',
    leftEn: 'Overrated city',
    rightEn: 'Underrated city',
  },
  {
    left: 'Schönes Geräusch',
    right: 'Furchtbares Geräusch',
    leftEn: 'Lovely sound',
    rightEn: 'Awful sound',
  },
  { left: 'Schlechtes Auto', right: 'Traumauto', leftEn: 'Bad car', rightEn: 'Dream car' },
  {
    left: 'Fehlkauf',
    right: 'Beste Anschaffung',
    leftEn: 'Bad purchase',
    rightEn: 'Best purchase',
  },
  {
    left: 'Kleines Problem',
    right: 'Großes Problem',
    leftEn: 'Small problem',
    rightEn: 'Big problem',
  },
  { left: 'Legal', right: 'Illegal', leftEn: 'Legal', rightEn: 'Illegal' },
  {
    left: 'Schnell erledigt',
    right: 'Dauert ewig',
    leftEn: 'Done quickly',
    rightEn: 'Takes forever',
  },
  { left: 'Für Anfänger', right: 'Für Profis', leftEn: 'For beginners', rightEn: 'For pros' },
  {
    left: 'Sieht billig aus',
    right: 'Sieht teuer aus',
    leftEn: 'Looks cheap',
    rightEn: 'Looks expensive',
  },
  {
    left: 'Umweltschädlich',
    right: 'Umweltfreundlich',
    leftEn: 'Polluting',
    rightEn: 'Eco friendly',
  },
  { left: 'Beruhigend', right: 'Gruselig', leftEn: 'Soothing', rightEn: 'Creepy' },
  { left: 'Unauffällig', right: 'Auffällig', leftEn: 'Subtle', rightEn: 'Flashy' },
  {
    left: 'Schlechter Wochentag',
    right: 'Bester Wochentag',
    leftEn: 'Worst weekday',
    rightEn: 'Best weekday',
  },
  {
    left: 'Nutzloses Schulfach',
    right: 'Wichtiges Schulfach',
    leftEn: 'Useless school subject',
    rightEn: 'Vital school subject',
  },
  {
    left: 'Harmloser Sport',
    right: 'Extremsport',
    leftEn: 'Harmless sport',
    rightEn: 'Extreme sport',
  },
  {
    left: 'Nie wieder',
    right: 'Jederzeit wieder',
    leftEn: 'Never again',
    rightEn: 'Any time again',
  },
  { left: 'Wenig Aufwand', right: 'Viel Aufwand', leftEn: 'Low effort', rightEn: 'High effort' },
  { left: 'Schmerzlos', right: 'Schmerzhaft', leftEn: 'Painless', rightEn: 'Painful' },
  { left: 'Ungiftig', right: 'Tödlich', leftEn: 'Harmless', rightEn: 'Deadly' },
  { left: 'Lokal', right: 'Global', leftEn: 'Local', rightEn: 'Global' },
  {
    left: 'Pflegeleicht',
    right: 'Pflegeintensiv',
    leftEn: 'Low maintenance',
    rightEn: 'High maintenance',
  },
  { left: 'Unwahrscheinlich', right: 'Wahrscheinlich', leftEn: 'Unlikely', rightEn: 'Likely' },
  { left: 'Fake', right: 'Echt', leftEn: 'Fake', rightEn: 'Real' },
  { left: 'Heimisch', right: 'Exotisch', leftEn: 'Familiar', rightEn: 'Exotic' },
  {
    left: 'Lieber kaufen',
    right: 'Lieber mieten',
    leftEn: 'Better to buy',
    rightEn: 'Better to rent',
  },
  {
    left: 'Selbst machen',
    right: 'Machen lassen',
    leftEn: 'Do it yourself',
    rightEn: 'Hire someone',
  },
  {
    left: 'Schlechter Feiertag',
    right: 'Bester Feiertag',
    leftEn: 'Worst holiday',
    rightEn: 'Best holiday',
  },
  {
    left: 'Hässliche Farbe',
    right: 'Schöne Farbe',
    leftEn: 'Ugly color',
    rightEn: 'Beautiful color',
  },
  {
    left: 'Hasst jeder',
    right: 'Liebt jeder',
    leftEn: 'Everyone hates it',
    rightEn: 'Everyone loves it',
  },
  { left: 'Wertlos', right: 'Wertvoll', leftEn: 'Worthless', rightEn: 'Valuable' },
  {
    left: 'Leicht zu zeichnen',
    right: 'Schwer zu zeichnen',
    leftEn: 'Easy to draw',
    rightEn: 'Hard to draw',
  },
  { left: 'Leise', right: 'Laut', leftEn: 'Quiet', rightEn: 'Loud' },
  { left: 'Federleicht', right: 'Tonnenschwer', leftEn: 'Featherlight', rightEn: 'Heavy as lead' },
  { left: 'Rutschig', right: 'Griffig', leftEn: 'Slippery', rightEn: 'Grippy' },
  {
    left: 'Mag kein Kind',
    right: 'Mag jedes Kind',
    leftEn: 'Kids hate it',
    rightEn: 'Kids love it',
  },
  {
    left: 'Schlechter Wohnort',
    right: 'Traumwohnort',
    leftEn: 'Awful town',
    rightEn: 'Dream town',
  },
  {
    left: 'Schlechtes Möbelstück',
    right: 'Bestes Möbelstück',
    leftEn: 'Worst furniture',
    rightEn: 'Best furniture',
  },
  {
    left: 'Unnötiges Gadget',
    right: 'Unverzichtbares Gadget',
    leftEn: 'Pointless gadget',
    rightEn: 'Essential gadget',
  },
  {
    left: 'Schlechte Wohnung',
    right: 'Traumwohnung',
    leftEn: 'Bad apartment',
    rightEn: 'Dream apartment',
  },
  { left: 'Kleinstadt', right: 'Metropole', leftEn: 'Small town', rightEn: 'Metropolis' },
  {
    left: 'Schlechtes Verkehrsmittel',
    right: 'Bestes Verkehrsmittel',
    leftEn: 'Worst transport',
    rightEn: 'Best transport',
  },
  {
    left: 'Hält ewig',
    right: 'Geht sofort kaputt',
    leftEn: 'Lasts forever',
    rightEn: 'Breaks right away',
  },
  { left: 'Platzsparend', right: 'Sperrig', leftEn: 'Compact', rightEn: 'Bulky' },
  { left: 'Riecht schlecht', right: 'Riecht gut', leftEn: 'Smells bad', rightEn: 'Smells good' },
  {
    left: 'Unzerstörbar',
    right: 'Wegwerfartikel',
    leftEn: 'Indestructible',
    rightEn: 'Disposable',
  },
  {
    left: 'Langweilige Aufgabe',
    right: 'Spaßige Aufgabe',
    leftEn: 'Dull chore',
    rightEn: 'Fun chore',
  },
  {
    left: 'Schlechter Ausflug',
    right: 'Perfekter Ausflug',
    leftEn: 'Bad day trip',
    rightEn: 'Perfect day trip',
  },
  {
    left: 'Einfach zu bedienen',
    right: 'Kompliziert zu bedienen',
    leftEn: 'Easy to use',
    rightEn: 'Hard to use',
  },
  { left: 'Morgens', right: 'Nachts', leftEn: 'Morning', rightEn: 'Night' },
  { left: 'Unhandlich', right: 'Handlich', leftEn: 'Clunky', rightEn: 'Handy' },
  {
    left: 'Schlechter Beruf',
    right: 'Bester Beruf',
    leftEn: 'Worst profession',
    rightEn: 'Best profession',
  },
  {
    left: 'Schlechte Jahreszeit',
    right: 'Beste Jahreszeit',
    leftEn: 'Worst season',
    rightEn: 'Best season',
  },
  {
    left: 'Schlechtes Werkzeug',
    right: 'Bestes Werkzeug',
    leftEn: 'Worst tool',
    rightEn: 'Best tool',
  },
];
