import type { WavelengthSeed } from './types';

export const partySpectrums: WavelengthSeed[] = [
  {
    left: 'Schlechter Partysong',
    right: 'Guter Partysong',
    leftEn: 'Bad party song',
    rightEn: 'Good party song',
  },
  { left: 'Nüchtern', right: 'Sturzbetrunken', leftEn: 'Sober', rightEn: 'Wasted' },
  {
    left: 'Peinlicher Tanzmove',
    right: 'Cooler Tanzmove',
    leftEn: 'Embarrassing dance move',
    rightEn: 'Cool dance move',
  },
  {
    left: 'Schlechte Anmache',
    right: 'Gute Anmache',
    leftEn: 'Bad pickup line',
    rightEn: 'Good pickup line',
  },
  { left: 'Schlechter Shot', right: 'Guter Shot', leftEn: 'Bad shot', rightEn: 'Good shot' },
  {
    left: 'Langweilige Party',
    right: 'Legendäre Party',
    leftEn: 'Boring party',
    rightEn: 'Legendary party',
  },
  {
    left: 'Schlechter Cocktail',
    right: 'Guter Cocktail',
    leftEn: 'Bad cocktail',
    rightEn: 'Good cocktail',
  },
  { left: 'Billiges Bier', right: 'Edles Bier', leftEn: 'Cheap beer', rightEn: 'Fancy beer' },
  {
    left: 'Schlechter Gastgeber',
    right: 'Guter Gastgeber',
    leftEn: 'Bad host',
    rightEn: 'Good host',
  },
  {
    left: 'Unterschätzter Drink',
    right: 'Überschätzter Drink',
    leftEn: 'Underrated drink',
    rightEn: 'Overrated drink',
  },
  {
    left: 'Früh nach Hause',
    right: 'Bis Sonnenaufgang',
    leftEn: 'Home early',
    rightEn: 'Until sunrise',
  },
  {
    left: 'Leichter Kater',
    right: 'Heftiger Kater',
    leftEn: 'Mild hangover',
    rightEn: 'Brutal hangover',
  },
  {
    left: 'Lahme Abgangsausrede',
    right: 'Gute Abgangsausrede',
    leftEn: 'Lame exit excuse',
    rightEn: 'Smooth exit excuse',
  },
  { left: 'Schlechter Club', right: 'Guter Club', leftEn: 'Bad club', rightEn: 'Good club' },
  {
    left: 'Langweiliges Trinkspiel',
    right: 'Geniales Trinkspiel',
    leftEn: 'Boring drinking game',
    rightEn: 'Brilliant drinking game',
  },
  {
    left: 'Schlechtes Katerfrühstück',
    right: 'Gutes Katerfrühstück',
    leftEn: 'Bad hangover breakfast',
    rightEn: 'Good hangover breakfast',
  },
  {
    left: 'Peinlicher Karaokesong',
    right: 'Starker Karaokesong',
    leftEn: 'Cringe karaoke song',
    rightEn: 'Great karaoke song',
  },
  {
    left: 'Schlechtes Partyoutfit',
    right: 'Gutes Partyoutfit',
    leftEn: 'Bad party outfit',
    rightEn: 'Good party outfit',
  },
  { left: 'Leichter Einlass', right: 'Harte Tür', leftEn: 'Easy door', rightEn: 'Tough door' },
  {
    left: 'Schlechter Partysnack',
    right: 'Guter Partysnack',
    leftEn: 'Bad party snack',
    rightEn: 'Good party snack',
  },
  {
    left: 'Schlechter Wingman',
    right: 'Guter Wingman',
    leftEn: 'Bad wingman',
    rightEn: 'Good wingman',
  },
  {
    left: 'Rote Flagge',
    right: 'Grüne Flagge',
    leftEn: 'Date red flag',
    rightEn: 'Date green flag',
  },
  {
    left: 'Schlechter Dateort',
    right: 'Guter Dateort',
    leftEn: 'Bad date spot',
    rightEn: 'Good date spot',
  },
  {
    left: 'Schlechtes Datingprofil',
    right: 'Gutes Datingprofil',
    leftEn: 'Bad dating profile',
    rightEn: 'Good dating profile',
  },
  {
    left: 'Schlechtes Profilbild',
    right: 'Gutes Profilbild',
    leftEn: 'Bad profile pic',
    rightEn: 'Good profile pic',
  },
  {
    left: 'Schlechte erste Nachricht',
    right: 'Gute erste Nachricht',
    leftEn: 'Bad opening text',
    rightEn: 'Good opening text',
  },
  {
    left: 'Langweiliger Barkeeper',
    right: 'Legendärer Barkeeper',
    leftEn: 'Boring bartender',
    rightEn: 'Legendary bartender',
  },
  {
    left: 'Schlechter Trinkspruch',
    right: 'Guter Trinkspruch',
    leftEn: 'Bad toast',
    rightEn: 'Good toast',
  },
  { left: 'Unauffälliger Gast', right: 'Partylöwe', leftEn: 'Wallflower', rightEn: 'Party animal' },
  { left: 'Ruhiger Abend', right: 'Wilde Nacht', leftEn: 'Quiet night', rightEn: 'Wild night' },
  {
    left: 'Kleiner Fehltritt',
    right: 'Totaler Absturz',
    leftEn: 'Small slip',
    rightEn: 'Total meltdown',
  },
  {
    left: 'Schlechter Vorglühort',
    right: 'Guter Vorglühort',
    leftEn: 'Bad pregame spot',
    rightEn: 'Good pregame spot',
  },
  {
    left: 'Peinliche Nachricht nachts',
    right: 'Süße Nachricht nachts',
    leftEn: 'Cringe drunk text',
    rightEn: 'Sweet drunk text',
  },
  {
    left: 'Schlechtes Festival',
    right: 'Gutes Festival',
    leftEn: 'Bad festival',
    rightEn: 'Good festival',
  },
  { left: 'Schlechte Bar', right: 'Gute Bar', leftEn: 'Bad bar', rightEn: 'Good bar' },
  {
    left: 'Lahmes Silvester',
    right: 'Episches Silvester',
    leftEn: 'Boring New Year’s',
    rightEn: 'Epic New Year’s',
  },
  {
    left: 'Schlechte Geburtstagsparty',
    right: 'Gute Geburtstagsparty',
    leftEn: 'Bad birthday party',
    rightEn: 'Good birthday party',
  },
  {
    left: 'Schlechter JGA',
    right: 'Guter JGA',
    leftEn: 'Bad bachelor party',
    rightEn: 'Good bachelor party',
  },
  {
    left: 'Schlechte Hochzeitsfeier',
    right: 'Gute Hochzeitsfeier',
    leftEn: 'Bad wedding party',
    rightEn: 'Good wedding party',
  },
  { left: 'Schlechter DJ', right: 'Guter DJ', leftEn: 'Bad DJ', rightEn: 'Good DJ' },
  {
    left: 'Schlechte Afterparty',
    right: 'Gute Afterparty',
    leftEn: 'Bad afterparty',
    rightEn: 'Good afterparty',
  },
  { left: 'Schlechte Mische', right: 'Gute Mische', leftEn: 'Bad mixer', rightEn: 'Good mixer' },
  {
    left: 'Schwacher Drink',
    right: 'Starker Drink',
    leftEn: 'Weak drink',
    rightEn: 'Strong drink',
  },
  {
    left: 'Trauriger Betrunkener',
    right: 'Lustiger Betrunkener',
    leftEn: 'Sad drunk',
    rightEn: 'Fun drunk',
  },
  {
    left: 'Schlechter Tanzpartner',
    right: 'Guter Tanzpartner',
    leftEn: 'Bad dance partner',
    rightEn: 'Good dance partner',
  },
  {
    left: 'Schlechter Partytrend',
    right: 'Guter Partytrend',
    leftEn: 'Bad party trend',
    rightEn: 'Good party trend',
  },
  {
    left: 'Unnötige Partyregel',
    right: 'Wichtige Partyregel',
    leftEn: 'Pointless party rule',
    rightEn: 'Essential party rule',
  },
  { left: 'Schlechter Abgang', right: 'Guter Abgang', leftEn: 'Bad exit', rightEn: 'Smooth exit' },
  {
    left: 'Schlechte Mottoparty',
    right: 'Gute Mottoparty',
    leftEn: 'Bad theme party',
    rightEn: 'Good theme party',
  },
  {
    left: 'Schlechtes Kostüm',
    right: 'Gutes Kostüm',
    leftEn: 'Bad costume',
    rightEn: 'Good costume',
  },
  {
    left: 'Schlechte Location',
    right: 'Gute Location',
    leftEn: 'Bad venue',
    rightEn: 'Good venue',
  },
  {
    left: 'Lahme Absage',
    right: 'Gute Absage',
    leftEn: 'Lame cancellation',
    rightEn: 'Good cancellation',
  },
  {
    left: 'Schlechtes Datethema',
    right: 'Gutes Datethema',
    leftEn: 'Bad date topic',
    rightEn: 'Good date topic',
  },
  {
    left: 'Verzeihliches Ghosting',
    right: 'Unverzeihliches Ghosting',
    leftEn: 'Forgivable ghosting',
    rightEn: 'Unforgivable ghosting',
  },
  {
    left: 'Schlechtes Kompliment',
    right: 'Gutes Kompliment',
    leftEn: 'Bad compliment',
    rightEn: 'Good compliment',
  },
  { left: 'Schlechtes Match', right: 'Gutes Match', leftEn: 'Bad match', rightEn: 'Good match' },
  {
    left: 'Schlechter Kennenlernort',
    right: 'Guter Kennenlernort',
    leftEn: 'Bad meeting spot',
    rightEn: 'Good meeting spot',
  },
  { left: 'Zu anhänglich', right: 'Zu distanziert', leftEn: 'Too clingy', rightEn: 'Too distant' },
  {
    left: 'Schlechter Trennungsgrund',
    right: 'Guter Trennungsgrund',
    leftEn: 'Bad breakup reason',
    rightEn: 'Good breakup reason',
  },
  { left: 'Romantisch', right: 'Kitschig', leftEn: 'Romantic', rightEn: 'Cheesy' },
  {
    left: 'Schlechte Datingapp',
    right: 'Gute Datingapp',
    leftEn: 'Bad dating app',
    rightEn: 'Good dating app',
  },
  { left: 'Netter Ex', right: 'Albtraum Ex', leftEn: 'Nice ex', rightEn: 'Nightmare ex' },
  {
    left: 'Brutaler Korb',
    right: 'Netter Korb',
    leftEn: 'Brutal rejection',
    rightEn: 'Kind rejection',
  },
  {
    left: 'Schlechter Trinkanlass',
    right: 'Guter Trinkanlass',
    leftEn: 'Bad drinking occasion',
    rightEn: 'Good drinking occasion',
  },
  {
    left: 'Kein Kater',
    right: 'Zwei Tage Kater',
    leftEn: 'No hangover',
    rightEn: 'Two day hangover',
  },
  {
    left: 'Schlechte Katerhilfe',
    right: 'Gute Katerhilfe',
    leftEn: 'Bad hangover cure',
    rightEn: 'Good hangover cure',
  },
  {
    left: 'Unauffällig betrunken',
    right: 'Offensichtlich betrunken',
    leftEn: 'Subtly drunk',
    rightEn: 'Obviously drunk',
  },
  {
    left: 'Schlechter Bierpongpartner',
    right: 'Guter Bierpongpartner',
    leftEn: 'Bad pong partner',
    rightEn: 'Good pong partner',
  },
  {
    left: 'Schlechte Tanzfläche',
    right: 'Gute Tanzfläche',
    leftEn: 'Bad dance floor',
    rightEn: 'Good dance floor',
  },
  {
    left: 'Schlechte Heimfahrt',
    right: 'Gute Heimfahrt',
    leftEn: 'Bad ride home',
    rightEn: 'Good ride home',
  },
  {
    left: 'Mieses Trinkgeld',
    right: 'Großzügiges Trinkgeld',
    leftEn: 'Bad tip',
    rightEn: 'Generous tip',
  },
  {
    left: 'Peinliche Barbestellung',
    right: 'Coole Barbestellung',
    leftEn: 'Embarrassing bar order',
    rightEn: 'Cool bar order',
  },
  {
    left: 'Schlimmster Partymoment',
    right: 'Bester Partymoment',
    leftEn: 'Worst party moment',
    rightEn: 'Best party moment',
  },
  { left: 'Kleine Runde', right: 'Riesige Sause', leftEn: 'Small hangout', rightEn: 'Huge bash' },
  { left: 'Schlechter Gast', right: 'Guter Gast', leftEn: 'Bad guest', rightEn: 'Good guest' },
  {
    left: 'Schlechte Partyidee',
    right: 'Gute Partyidee',
    leftEn: 'Bad party idea',
    rightEn: 'Good party idea',
  },
  { left: 'Schlechter Wein', right: 'Guter Wein', leftEn: 'Bad wine', rightEn: 'Good wine' },
  {
    left: 'Schlechter Longdrink',
    right: 'Guter Longdrink',
    leftEn: 'Bad long drink',
    rightEn: 'Good long drink',
  },
  {
    left: 'Billiger Sekt',
    right: 'Echter Champagner',
    leftEn: 'Cheap bubbly',
    rightEn: 'Real champagne',
  },
  {
    left: 'Harmlose Partystory',
    right: 'Legendäre Partystory',
    leftEn: 'Harmless party story',
    rightEn: 'Legendary party story',
  },
  {
    left: 'Viel zu früh',
    right: 'Viel zu spät',
    leftEn: 'Way too early',
    rightEn: 'Way too late',
  },
  {
    left: 'Schlechte Partydeko',
    right: 'Gute Partydeko',
    leftEn: 'Bad party decor',
    rightEn: 'Good party decor',
  },
  {
    left: 'Schlechtes Partyfoto',
    right: 'Gutes Partyfoto',
    leftEn: 'Bad party pic',
    rightEn: 'Good party pic',
  },
  {
    left: 'Peinliche Sprachnachricht',
    right: 'Lustige Sprachnachricht',
    leftEn: 'Cringe voice message',
    rightEn: 'Funny voice message',
  },
  {
    left: 'Schlechte Trinkstrategie',
    right: 'Gute Trinkstrategie',
    leftEn: 'Bad drinking strategy',
    rightEn: 'Good drinking strategy',
  },
  {
    left: 'Schlechte Kneipentour',
    right: 'Gute Kneipentour',
    leftEn: 'Bad pub crawl',
    rightEn: 'Good pub crawl',
  },
  { left: 'Schlechter Drop', right: 'Guter Drop', leftEn: 'Bad drop', rightEn: 'Good drop' },
  {
    left: 'Schlechtes zweites Date',
    right: 'Gutes zweites Date',
    leftEn: 'Bad second date',
    rightEn: 'Good second date',
  },
  {
    left: 'Langsam rangehen',
    right: 'Direkt rangehen',
    leftEn: 'Slow approach',
    rightEn: 'Direct approach',
  },
  {
    left: 'Schüchterner Flirt',
    right: 'Mutiger Flirt',
    leftEn: 'Shy flirting',
    rightEn: 'Bold flirting',
  },
  {
    left: 'Schlechtes Liebesgeständnis',
    right: 'Gutes Liebesgeständnis',
    leftEn: 'Bad love confession',
    rightEn: 'Good love confession',
  },
  {
    left: 'Schlechter Kosename',
    right: 'Guter Kosename',
    leftEn: 'Bad pet name',
    rightEn: 'Good pet name',
  },
  {
    left: 'Kurze Schlange',
    right: 'Endlose Schlange',
    leftEn: 'Short queue',
    rightEn: 'Endless queue',
  },
  {
    left: 'Lahme Polonaise',
    right: 'Epische Polonaise',
    leftEn: 'Lame conga line',
    rightEn: 'Epic conga line',
  },
  {
    left: 'Schlechter Mocktail',
    right: 'Guter Mocktail',
    leftEn: 'Bad mocktail',
    rightEn: 'Good mocktail',
  },
  {
    left: 'Schlechter Smalltalk',
    right: 'Guter Smalltalk',
    leftEn: 'Bad small talk',
    rightEn: 'Good small talk',
  },
  {
    left: 'Schlechtes Doppeldate',
    right: 'Gutes Doppeldate',
    leftEn: 'Bad double date',
    rightEn: 'Good double date',
  },
  {
    left: 'Schlechter Urlaubsflirt',
    right: 'Guter Urlaubsflirt',
    leftEn: 'Bad holiday fling',
    rightEn: 'Good holiday fling',
  },
  {
    left: 'Schlechte Partystadt',
    right: 'Gute Partystadt',
    leftEn: 'Bad party city',
    rightEn: 'Good party city',
  },
  {
    left: 'Schlechte Strandparty',
    right: 'Gute Strandparty',
    leftEn: 'Bad beach party',
    rightEn: 'Good beach party',
  },
];
