import type { WavelengthSeed } from './types';

export const peopleSpectrums: WavelengthSeed[] = [
  { left: 'Faul', right: 'Fleißig', leftEn: 'Lazy', rightEn: 'Hardworking' },
  { left: 'Introvertiert', right: 'Extrovertiert', leftEn: 'Introverted', rightEn: 'Extroverted' },
  { left: 'Bösewicht', right: 'Held', leftEn: 'Villain', rightEn: 'Hero' },
  {
    left: 'Schlechter Lehrer',
    right: 'Guter Lehrer',
    leftEn: 'Bad teacher',
    rightEn: 'Good teacher',
  },
  { left: 'Unsympathisch', right: 'Sympathisch', leftEn: 'Unlikable', rightEn: 'Likable' },
  { left: 'Kleinlich', right: 'Gelassen', leftEn: 'Petty', rightEn: 'Laid-back' },
  { left: 'Schüchtern', right: 'Selbstbewusst', leftEn: 'Shy', rightEn: 'Confident' },
  { left: 'Unehrlich', right: 'Ehrlich', leftEn: 'Dishonest', rightEn: 'Honest' },
  { left: 'Schlechter Chef', right: 'Guter Chef', leftEn: 'Bad boss', rightEn: 'Good boss' },
  { left: 'Mieser Job', right: 'Traumjob', leftEn: 'Lousy job', rightEn: 'Dream job' },
  { left: 'Schlecht bezahlt', right: 'Gut bezahlt', leftEn: 'Underpaid', rightEn: 'Well paid' },
  {
    left: 'Unwichtiger Beruf',
    right: 'Systemrelevant',
    leftEn: 'Unimportant job',
    rightEn: 'Essential job',
  },
  { left: 'Sicherer Job', right: 'Gefährlicher Job', leftEn: 'Safe job', rightEn: 'Dangerous job' },
  { left: 'Schlechter Vater', right: 'Guter Vater', leftEn: 'Bad dad', rightEn: 'Good dad' },
  { left: 'Schlechte Mutter', right: 'Gute Mutter', leftEn: 'Bad mom', rightEn: 'Good mom' },
  {
    left: 'Schlechter Freund',
    right: 'Bester Freund',
    leftEn: 'Bad friend',
    rightEn: 'Best friend',
  },
  { left: 'Unbekannt', right: 'Weltberühmt', leftEn: 'Unknown', rightEn: 'World famous' },
  { left: 'Dumm', right: 'Genial', leftEn: 'Dumb', rightEn: 'Genius' },
  { left: 'Ungeschickt', right: 'Geschickt', leftEn: 'Clumsy', rightEn: 'Handy' },
  { left: 'Pessimist', right: 'Optimist', leftEn: 'Pessimist', rightEn: 'Optimist' },
  { left: 'Geizig', right: 'Großzügig', leftEn: 'Stingy', rightEn: 'Generous' },
  { left: 'Unpünktlich', right: 'Pünktlich', leftEn: 'Always late', rightEn: 'Punctual' },
  { left: 'Unsportlich', right: 'Sportlich', leftEn: 'Unathletic', rightEn: 'Athletic' },
  { left: 'Humorlos', right: 'Lustig', leftEn: 'Humorless', rightEn: 'Funny' },
  { left: 'Unhöflich', right: 'Höflich', leftEn: 'Rude', rightEn: 'Polite' },
  { left: 'Feige', right: 'Mutig', leftEn: 'Cowardly', rightEn: 'Brave' },
  { left: 'Naiv', right: 'Misstrauisch', leftEn: 'Naive', rightEn: 'Suspicious' },
  { left: 'Bodenständig', right: 'Abgehoben', leftEn: 'Down to earth', rightEn: 'Aloof' },
  { left: 'Spießig', right: 'Rebellisch', leftEn: 'Square', rightEn: 'Rebellious' },
  { left: 'Ungepflegt', right: 'Gepflegt', leftEn: 'Scruffy', rightEn: 'Well groomed' },
  {
    left: 'Schlechter Sänger',
    right: 'Guter Sänger',
    leftEn: 'Bad singer',
    rightEn: 'Good singer',
  },
  {
    left: 'Schlechter Schauspieler',
    right: 'Guter Schauspieler',
    leftEn: 'Bad actor',
    rightEn: 'Good actor',
  },
  {
    left: 'Schlechter Politiker',
    right: 'Guter Politiker',
    leftEn: 'Bad politician',
    rightEn: 'Good politician',
  },
  {
    left: 'Mittelmäßiger Sportler',
    right: 'Sportlegende',
    leftEn: 'Average athlete',
    rightEn: 'Sports legend',
  },
  { left: 'Unattraktiv', right: 'Attraktiv', leftEn: 'Unattractive', rightEn: 'Attractive' },
  { left: 'Vergesslich', right: 'Gutes Gedächtnis', leftEn: 'Forgetful', rightEn: 'Great memory' },
  { left: 'Ungeduldig', right: 'Geduldig', leftEn: 'Impatient', rightEn: 'Patient' },
  {
    left: 'Nachtragend',
    right: 'Verzeiht alles',
    leftEn: 'Holds grudges',
    rightEn: 'Forgives everything',
  },
  { left: 'Kopfmensch', right: 'Bauchmensch', leftEn: 'Thinker', rightEn: 'Feeler' },
  { left: 'Kind im Herzen', right: 'Alte Seele', leftEn: 'Kid at heart', rightEn: 'Old soul' },
  { left: 'Stadtmensch', right: 'Landmensch', leftEn: 'City person', rightEn: 'Country person' },
  { left: 'Morgenmensch', right: 'Nachteule', leftEn: 'Morning person', rightEn: 'Night owl' },
  { left: 'Hundemensch', right: 'Katzenmensch', leftEn: 'Dog person', rightEn: 'Cat person' },
  { left: 'Vernünftig', right: 'Verrückt', leftEn: 'Sensible', rightEn: 'Crazy' },
  { left: 'Unbeliebt', right: 'Beliebt', leftEn: 'Unpopular', rightEn: 'Popular' },
  {
    left: 'Schlechter Mitbewohner',
    right: 'Guter Mitbewohner',
    leftEn: 'Bad roommate',
    rightEn: 'Good roommate',
  },
  {
    left: 'Schlechter Verlierer',
    right: 'Guter Verlierer',
    leftEn: 'Sore loser',
    rightEn: 'Good loser',
  },
  { left: 'Schlechter Lügner', right: 'Guter Lügner', leftEn: 'Bad liar', rightEn: 'Good liar' },
  { left: 'Unkreativ', right: 'Kreativ', leftEn: 'Uncreative', rightEn: 'Creative' },
  { left: 'Unzuverlässig', right: 'Zuverlässig', leftEn: 'Unreliable', rightEn: 'Reliable' },
  { left: 'Kühl', right: 'Herzlich', leftEn: 'Distant', rightEn: 'Warmhearted' },
  { left: 'Einzelgänger', right: 'Teamplayer', leftEn: 'Loner', rightEn: 'Team player' },
  { left: 'Mitläufer', right: 'Anführer', leftEn: 'Follower', rightEn: 'Leader' },
  { left: 'Bescheiden', right: 'Arrogant', leftEn: 'Humble', rightEn: 'Arrogant' },
  { left: 'Unauffällig', right: 'Exzentrisch', leftEn: 'Inconspicuous', rightEn: 'Eccentric' },
  { left: 'Sparsam', right: 'Verschwenderisch', leftEn: 'Thrifty', rightEn: 'Spendthrift' },
  { left: 'Ruhig', right: 'Laut', leftEn: 'Calm', rightEn: 'Loud' },
  { left: 'Entspannt', right: 'Gestresst', leftEn: 'Relaxed', rightEn: 'Stressed' },
  { left: 'Harmlos', right: 'Gefährlich', leftEn: 'Harmless', rightEn: 'Dangerous' },
  { left: 'Netter Promi', right: 'Fieser Promi', leftEn: 'Nice celeb', rightEn: 'Mean celeb' },
  {
    left: 'Schlechtes Vorbild',
    right: 'Gutes Vorbild',
    leftEn: 'Bad role model',
    rightEn: 'Good role model',
  },
  {
    left: 'Kurze Karriere',
    right: 'Lange Karriere',
    leftEn: 'Short career',
    rightEn: 'Long career',
  },
  { left: 'Talentfrei', right: 'Hochbegabt', leftEn: 'Untalented', rightEn: 'Gifted' },
  {
    left: 'Schlechter Autofahrer',
    right: 'Guter Autofahrer',
    leftEn: 'Bad driver',
    rightEn: 'Good driver',
  },
  { left: 'Schlechter Koch', right: 'Guter Koch', leftEn: 'Bad cook', rightEn: 'Good cook' },
  {
    left: 'Schlechter Tänzer',
    right: 'Guter Tänzer',
    leftEn: 'Bad dancer',
    rightEn: 'Good dancer',
  },
  {
    left: 'Schlechter Kollege',
    right: 'Guter Kollege',
    leftEn: 'Bad coworker',
    rightEn: 'Good coworker',
  },
  {
    left: 'Schlechter Nachbar',
    right: 'Guter Nachbar',
    leftEn: 'Bad neighbor',
    rightEn: 'Good neighbor',
  },
  { left: 'Schlechter Arzt', right: 'Guter Arzt', leftEn: 'Bad doctor', rightEn: 'Good doctor' },
  {
    left: 'Schlechter Präsident',
    right: 'Guter Präsident',
    leftEn: 'Bad president',
    rightEn: 'Good president',
  },
  { left: 'Unglaubwürdig', right: 'Glaubwürdig', leftEn: 'Untrustworthy', rightEn: 'Trustworthy' },
  {
    left: 'Leicht zu beeindrucken',
    right: 'Schwer zu beeindrucken',
    leftEn: 'Easily impressed',
    rightEn: 'Hard to impress',
  },
  {
    left: 'Schlechter Partner',
    right: 'Traumpartner',
    leftEn: 'Bad partner',
    rightEn: 'Ideal partner',
  },
  { left: 'Nerd', right: 'Cool', leftEn: 'Nerd', rightEn: 'Cool' },
  { left: 'Brav', right: 'Frech', leftEn: 'Well behaved', rightEn: 'Cheeky' },
  { left: 'Unromantisch', right: 'Romantisch', leftEn: 'Unromantic', rightEn: 'Romantic' },
  {
    left: 'Körperlich leichter Job',
    right: 'Körperlich harter Job',
    leftEn: 'Physically easy job',
    rightEn: 'Physically hard job',
  },
  { left: 'Unseriös', right: 'Seriös', leftEn: 'Shady', rightEn: 'Respectable' },
  {
    left: 'Kinder hassen ihn',
    right: 'Kinder lieben ihn',
    leftEn: 'Kids hate them',
    rightEn: 'Kids love them',
  },
  { left: 'Abergläubisch', right: 'Rational', leftEn: 'Superstitious', rightEn: 'Rational' },
  { left: 'Unemotional', right: 'Emotional', leftEn: 'Unemotional', rightEn: 'Emotional' },
  { left: 'Planer', right: 'Spontan', leftEn: 'Planner', rightEn: 'Spontaneous' },
  { left: 'Stubenhocker', right: 'Abenteurer', leftEn: 'Homebody', rightEn: 'Adventurer' },
  { left: 'Altmodisch', right: 'Trendbewusst', leftEn: 'Old fashioned', rightEn: 'Trendy' },
  {
    left: 'Schlechter Influencer',
    right: 'Guter Influencer',
    leftEn: 'Bad influencer',
    rightEn: 'Good influencer',
  },
  { left: 'Eintagsfliege', right: 'Ikone', leftEn: 'One hit wonder', rightEn: 'Icon' },
  { left: 'Peinlich', right: 'Würdevoll', leftEn: 'Embarrassing', rightEn: 'Dignified' },
  { left: 'Sensibel', right: 'Dickes Fell', leftEn: 'Sensitive', rightEn: 'Thick skinned' },
  { left: 'Verschlossen', right: 'Offenes Buch', leftEn: 'Closed off', rightEn: 'Open book' },
  { left: 'Normalo', right: 'Diva', leftEn: 'Regular person', rightEn: 'Diva' },
  {
    left: 'Schlechter Zuhörer',
    right: 'Guter Zuhörer',
    leftEn: 'Bad listener',
    rightEn: 'Good listener',
  },
  { left: 'Pleite', right: 'Steinreich', leftEn: 'Broke', rightEn: 'Filthy rich' },
  {
    left: 'Leicht ersetzbar',
    right: 'Unersetzbar',
    leftEn: 'Easily replaced',
    rightEn: 'Irreplaceable',
  },
  {
    left: 'Unpolitisch',
    right: 'Politisch engagiert',
    leftEn: 'Apolitical',
    rightEn: 'Politically active',
  },
  { left: 'Kein Ehrgeiz', right: 'Ehrgeizig', leftEn: 'No ambition', rightEn: 'Ambitious' },
  {
    left: 'Würde nie betrügen',
    right: 'Würde sofort betrügen',
    leftEn: 'Would never cheat',
    rightEn: 'Would cheat instantly',
  },
  { left: 'Tierhasser', right: 'Tierfreund', leftEn: 'Animal hater', rightEn: 'Animal lover' },
  {
    left: 'Schlechter Superheld',
    right: 'Bester Superheld',
    leftEn: 'Worst superhero',
    rightEn: 'Best superhero',
  },
  {
    left: 'Harmloser Schurke',
    right: 'Furchteinflößender Schurke',
    leftEn: 'Harmless villain',
    rightEn: 'Terrifying villain',
  },
  {
    left: 'Schlechter Trainer',
    right: 'Guter Trainer',
    leftEn: 'Bad coach',
    rightEn: 'Good coach',
  },
];
