import type { WavelengthSeed } from './types';

export const popcultureSpectrums: WavelengthSeed[] = [
  {
    left: 'Unterschätzter Film',
    right: 'Überschätzter Film',
    leftEn: 'Underrated movie',
    rightEn: 'Overrated movie',
  },
  { left: 'Schlechter Song', right: 'Guter Song', leftEn: 'Bad song', rightEn: 'Great song' },
  { left: 'Schlechte Serie', right: 'Gute Serie', leftEn: 'Bad show', rightEn: 'Great show' },
  {
    left: 'Schlechtes Videospiel',
    right: 'Gutes Videospiel',
    leftEn: 'Bad video game',
    rightEn: 'Great video game',
  },
  {
    left: 'Schwacher Bösewicht',
    right: 'Genialer Bösewicht',
    leftEn: 'Weak villain',
    rightEn: 'Great villain',
  },
  { left: 'Langweiliger Held', right: 'Kultheld', leftEn: 'Boring hero', rightEn: 'Iconic hero' },
  {
    left: 'Kinderfilm',
    right: 'Nichts für Kinder',
    leftEn: 'Kids’ movie',
    rightEn: 'Not for kids',
  },
  { left: 'Flop', right: 'Blockbuster', leftEn: 'Flop', rightEn: 'Blockbuster' },
  { left: 'Geheimtipp', right: 'Kennt jeder', leftEn: 'Hidden gem', rightEn: 'Everyone knows it' },
  {
    left: 'Harmloser Horrorfilm',
    right: 'Verstörender Horrorfilm',
    leftEn: 'Tame horror movie',
    rightEn: 'Disturbing horror movie',
  },
  {
    left: 'Feelgood Film',
    right: 'Deprimierender Film',
    leftEn: 'Feel good movie',
    rightEn: 'Depressing movie',
  },
  {
    left: 'Schlechte Fortsetzung',
    right: 'Gute Fortsetzung',
    leftEn: 'Bad sequel',
    rightEn: 'Great sequel',
  },
  {
    left: 'Schlechtes Remake',
    right: 'Gutes Remake',
    leftEn: 'Bad remake',
    rightEn: 'Great remake',
  },
  {
    left: 'Schlechtes Ende',
    right: 'Perfektes Ende',
    leftEn: 'Bad ending',
    rightEn: 'Perfect ending',
  },
  {
    left: 'Kurzer Hype',
    right: 'Zeitloser Klassiker',
    leftEn: 'Short hype',
    rightEn: 'Timeless classic',
  },
  { left: 'Vergessen', right: 'Legendär', leftEn: 'Forgotten', rightEn: 'Legendary' },
  {
    left: 'Kein Ohrwurm',
    right: 'Krasser Ohrwurm',
    leftEn: 'Forgettable tune',
    rightEn: 'Total earworm',
  },
  { left: 'Zum Chillen', right: 'Zum Tanzen', leftEn: 'Chill song', rightEn: 'Dance song' },
  { left: 'Trauriger Song', right: 'Fröhlicher Song', leftEn: 'Sad song', rightEn: 'Happy song' },
  {
    left: 'Schlechter Sänger',
    right: 'Großartiger Sänger',
    leftEn: 'Bad singer',
    rightEn: 'Great singer',
  },
  {
    left: 'Schlechter Schauspieler',
    right: 'Großartiger Schauspieler',
    leftEn: 'Bad actor',
    rightEn: 'Great actor',
  },
  { left: 'Kennt keiner', right: 'Weltstar', leftEn: 'Nobody', rightEn: 'Megastar' },
  { left: 'Skandalfrei', right: 'Skandalnudel', leftEn: 'Scandal free', rightEn: 'Scandal magnet' },
  {
    left: 'Schlechter Rapper',
    right: 'Bester Rapper',
    leftEn: 'Bad rapper',
    rightEn: 'Best rapper',
  },
  { left: 'Schlechte Band', right: 'Beste Band', leftEn: 'Bad band', rightEn: 'Best band' },
  { left: 'Schlechtes Album', right: 'Bestes Album', leftEn: 'Bad album', rightEn: 'Best album' },
  { left: 'Schlechtes Genre', right: 'Bestes Genre', leftEn: 'Worst genre', rightEn: 'Best genre' },
  {
    left: 'Schlechter Disneyfilm',
    right: 'Bester Disneyfilm',
    leftEn: 'Worst Disney movie',
    rightEn: 'Best Disney movie',
  },
  {
    left: 'Schlechter Superheldenfilm',
    right: 'Bester Superheldenfilm',
    leftEn: 'Worst superhero movie',
    rightEn: 'Best superhero movie',
  },
  {
    left: 'Schlechter Weihnachtsfilm',
    right: 'Bester Weihnachtsfilm',
    leftEn: 'Worst Christmas movie',
    rightEn: 'Best Christmas movie',
  },
  {
    left: 'Schlimmster Weihnachtssong',
    right: 'Bester Weihnachtssong',
    leftEn: 'Worst Christmas song',
    rightEn: 'Best Christmas song',
  },
  { left: 'Schlechte Romcom', right: 'Beste Romcom', leftEn: 'Bad romcom', rightEn: 'Best romcom' },
  {
    left: 'Völlig unrealistisch',
    right: 'Sehr realistisch',
    leftEn: 'Totally unrealistic',
    rightEn: 'Very realistic',
  },
  { left: 'Schlecht gealtert', right: 'Gut gealtert', leftEn: 'Aged badly', rightEn: 'Aged well' },
  {
    left: 'Schlechte Buchverfilmung',
    right: 'Gute Buchverfilmung',
    leftEn: 'Bad book adaptation',
    rightEn: 'Great book adaptation',
  },
  {
    left: 'Schlechte Spielverfilmung',
    right: 'Gute Spielverfilmung',
    leftEn: 'Bad game adaptation',
    rightEn: 'Great game adaptation',
  },
  {
    left: 'Eine Folge reicht',
    right: 'Suchtgefahr',
    leftEn: 'One is enough',
    rightEn: 'Binge worthy',
  },
  {
    left: 'Endete zu früh',
    right: 'Lief zu lange',
    leftEn: 'Ended too soon',
    rightEn: 'Ran too long',
  },
  { left: 'Trash TV', right: 'Anspruchsvolles TV', leftEn: 'Trash TV', rightEn: 'Quality TV' },
  {
    left: 'Schlechter Werbespot',
    right: 'Genialer Werbespot',
    leftEn: 'Bad commercial',
    rightEn: 'Brilliant commercial',
  },
  { left: 'Casual Game', right: 'Hardcore Game', leftEn: 'Casual game', rightEn: 'Hardcore game' },
  {
    left: 'Schlechteste Konsole',
    right: 'Beste Konsole',
    leftEn: 'Worst console',
    rightEn: 'Best console',
  },
  { left: 'Pixelgrafik', right: 'Fotorealistisch', leftEn: 'Pixel art', rightEn: 'Photorealistic' },
  {
    left: 'Austauschbare Figur',
    right: 'Ikonische Figur',
    leftEn: 'Forgettable character',
    rightEn: 'Iconic character',
  },
  {
    left: 'Schlechter Zeichentrick',
    right: 'Bester Zeichentrick',
    leftEn: 'Worst cartoon',
    rightEn: 'Best cartoon',
  },
  {
    left: 'Kein Nostalgiefaktor',
    right: 'Pure Nostalgie',
    leftEn: 'No nostalgia',
    rightEn: 'Pure nostalgia',
  },
  { left: 'Typisch 90er', right: 'Typisch heute', leftEn: 'Very 90s', rightEn: 'Very today' },
  {
    left: 'Schlechter Plot Twist',
    right: 'Genialer Plot Twist',
    leftEn: 'Bad plot twist',
    rightEn: 'Brilliant plot twist',
  },
  {
    left: 'Schlechte Filmmusik',
    right: 'Legendärer Soundtrack',
    leftEn: 'Bad soundtrack',
    rightEn: 'Legendary soundtrack',
  },
  {
    left: 'Lahmes Filmzitat',
    right: 'Kultzitat',
    leftEn: 'Lame movie quote',
    rightEn: 'Iconic quote',
  },
  {
    left: 'Schlechtes Cover',
    right: 'Besser als Original',
    leftEn: 'Bad cover',
    rightEn: 'Better than original',
  },
  {
    left: 'One Hit Wonder',
    right: 'Lebende Legende',
    leftEn: 'One hit wonder',
    rightEn: 'Living legend',
  },
  {
    left: 'Leicht mitzusingen',
    right: 'Unmöglich zu singen',
    leftEn: 'Easy to sing',
    rightEn: 'Impossible to sing',
  },
  {
    left: 'Schlechter Songtext',
    right: 'Genialer Songtext',
    leftEn: 'Bad lyrics',
    rightEn: 'Brilliant lyrics',
  },
  {
    left: 'Schlechtes Musikvideo',
    right: 'Ikonisches Musikvideo',
    leftEn: 'Bad music video',
    rightEn: 'Iconic music video',
  },
  {
    left: 'Guilty Pleasure',
    right: 'Stolz drauf',
    leftEn: 'Guilty pleasure',
    rightEn: 'Proud of it',
  },
  { left: 'Cringe', right: 'Kult', leftEn: 'Cringe', rightEn: 'Cult classic' },
  { left: 'Totes Meme', right: 'Zeitloses Meme', leftEn: 'Dead meme', rightEn: 'Timeless meme' },
  { left: 'Schlechteste App', right: 'Beste App', leftEn: 'Worst app', rightEn: 'Best app' },
  {
    left: 'Schlechter Streamingdienst',
    right: 'Bester Streamingdienst',
    leftEn: 'Worst streaming service',
    rightEn: 'Best streaming service',
  },
  { left: 'Absolut böse', right: 'Absolut gut', leftEn: 'Pure evil', rightEn: 'Pure good' },
  {
    left: 'Schlechtes Filmpaar',
    right: 'Traumpaar',
    leftEn: 'Bad screen couple',
    rightEn: 'Dream couple',
  },
  { left: 'Schlechtester Bond', right: 'Bester Bond', leftEn: 'Worst Bond', rightEn: 'Best Bond' },
  { left: 'Komödie', right: 'Drama', leftEn: 'Comedy', rightEn: 'Drama' },
  { left: 'Unlustig', right: 'Urkomisch', leftEn: 'Not funny', rightEn: 'Hilarious' },
  { left: 'Low Budget', right: 'Big Budget', leftEn: 'Low budget', rightEn: 'Big budget' },
  {
    left: 'Schlechte Spezialeffekte',
    right: 'Geniale Spezialeffekte',
    leftEn: 'Bad special effects',
    rightEn: 'Great special effects',
  },
  {
    left: 'Schlechter Filmtitel',
    right: 'Genialer Filmtitel',
    leftEn: 'Bad movie title',
    rightEn: 'Brilliant movie title',
  },
  {
    left: 'Schlechter Bandname',
    right: 'Genialer Bandname',
    leftEn: 'Bad band name',
    rightEn: 'Great band name',
  },
  {
    left: 'Schlechtes Albumcover',
    right: 'Ikonisches Albumcover',
    leftEn: 'Bad album cover',
    rightEn: 'Iconic album cover',
  },
  {
    left: 'Typisch deutsch',
    right: 'Typisch Hollywood',
    leftEn: 'Very German',
    rightEn: 'Very Hollywood',
  },
  { left: 'Nur für Fans', right: 'Für alle', leftEn: 'Fans only', rightEn: 'For everyone' },
  {
    left: 'Unterschätzter Song',
    right: 'Überschätzter Song',
    leftEn: 'Underrated song',
    rightEn: 'Overrated song',
  },
  {
    left: 'Unterschätzte Serie',
    right: 'Überschätzte Serie',
    leftEn: 'Underrated show',
    rightEn: 'Overrated show',
  },
  {
    left: 'Goldene Himbeere',
    right: 'Oscarreif',
    leftEn: 'Razzie worthy',
    rightEn: 'Oscar worthy',
  },
  {
    left: 'Lahmer Endgegner',
    right: 'Legendärer Endgegner',
    leftEn: 'Lame boss fight',
    rightEn: 'Legendary boss fight',
  },
  {
    left: 'Schnell durchgespielt',
    right: 'Endlos spielbar',
    leftEn: 'Quick to finish',
    rightEn: 'Endless replay',
  },
  {
    left: 'Zu Recht vergessen',
    right: 'Zu Unrecht vergessen',
    leftEn: 'Rightly forgotten',
    rightEn: 'Wrongly forgotten',
  },
  {
    left: 'Bitte kein Comeback',
    right: 'Bitte Comeback',
    leftEn: 'Never come back',
    rightEn: 'Bring it back',
  },
  {
    left: 'Schlechtes Spin Off',
    right: 'Gutes Spin Off',
    leftEn: 'Bad spin off',
    rightEn: 'Great spin off',
  },
  { left: 'Langweiliges Buch', right: 'Pageturner', leftEn: 'Boring book', rightEn: 'Page turner' },
  { left: 'Peinlicher Tanz', right: 'Kulttanz', leftEn: 'Cringey dance', rightEn: 'Iconic dance' },
  {
    left: 'Schlechter Sommerhit',
    right: 'Bester Sommerhit',
    leftEn: 'Worst summer hit',
    rightEn: 'Best summer hit',
  },
  {
    left: 'Schlechter ESC Song',
    right: 'Bester ESC Song',
    leftEn: 'Worst Eurovision song',
    rightEn: 'Best Eurovision song',
  },
  {
    left: 'Schlechter Krimi',
    right: 'Bester Krimi',
    leftEn: 'Bad crime show',
    rightEn: 'Great crime show',
  },
  {
    left: 'Besser synchronisiert',
    right: 'Besser im Original',
    leftEn: 'Better dubbed',
    rightEn: 'Better in original',
  },
  {
    left: 'Schlechte Sitcom',
    right: 'Beste Sitcom',
    leftEn: 'Worst sitcom',
    rightEn: 'Best sitcom',
  },
  { left: 'Schlechter Anime', right: 'Bester Anime', leftEn: 'Worst anime', rightEn: 'Best anime' },
  {
    left: 'Schlechte Realityshow',
    right: 'Beste Realityshow',
    leftEn: 'Worst reality show',
    rightEn: 'Best reality show',
  },
  {
    left: 'Schlechte Kindersendung',
    right: 'Beste Kindersendung',
    leftEn: 'Worst kids’ show',
    rightEn: 'Best kids’ show',
  },
  {
    left: 'Schlechter Podcast',
    right: 'Bester Podcast',
    leftEn: 'Worst podcast',
    rightEn: 'Best podcast',
  },
  {
    left: 'Schlechter Comedian',
    right: 'Bester Comedian',
    leftEn: 'Worst comedian',
    rightEn: 'Best comedian',
  },
  {
    left: 'Schlechter Regisseur',
    right: 'Bester Regisseur',
    leftEn: 'Worst director',
    rightEn: 'Best director',
  },
  {
    left: 'Schlechte Filmreihe',
    right: 'Beste Filmreihe',
    leftEn: 'Worst franchise',
    rightEn: 'Best franchise',
  },
  {
    left: 'Schlechtes Handyspiel',
    right: 'Bestes Handyspiel',
    leftEn: 'Worst mobile game',
    rightEn: 'Best mobile game',
  },
  {
    left: 'Schlechtes Konzert',
    right: 'Legendäres Konzert',
    leftEn: 'Bad concert',
    rightEn: 'Legendary concert',
  },
  {
    left: 'Schlechter Liebessong',
    right: 'Bester Liebessong',
    leftEn: 'Worst love song',
    rightEn: 'Best love song',
  },
  {
    left: 'Peinliches Filmkostüm',
    right: 'Ikonisches Filmkostüm',
    leftEn: 'Bad movie costume',
    rightEn: 'Iconic movie costume',
  },
  {
    left: 'Leise Ballade',
    right: 'Stadionhymne',
    leftEn: 'Quiet ballad',
    rightEn: 'Stadium anthem',
  },
  {
    left: 'Schlechte Promiehe',
    right: 'Promi Traumpaar',
    leftEn: 'Bad celeb couple',
    rightEn: 'Celeb power couple',
  },
];
