import type { WavelengthSeed } from './types';

export const sexualSpectrums: WavelengthSeed[] = [
  { left: 'Unsexy', right: 'Sexy', leftEn: 'Unsexy', rightEn: 'Sexy' },
  { left: 'Vanilla', right: 'Kinky', leftEn: 'Vanilla', rightEn: 'Kinky' },
  {
    left: 'Schlechtes erstes Date',
    right: 'Gutes erstes Date',
    leftEn: 'Bad first date',
    rightEn: 'Good first date',
  },
  { left: 'Harmlos', right: 'Versaut', leftEn: 'Harmless', rightEn: 'Dirty' },
  { left: 'Abtörner', right: 'Antörner', leftEn: 'Instant turnoff', rightEn: 'Instant attraction' },
  {
    left: 'Schlechter Küsser',
    right: 'Guter Küsser',
    leftEn: 'Bad kisser',
    rightEn: 'Good kisser',
  },
  {
    left: 'Unsexy Unterwäsche',
    right: 'Sexy Unterwäsche',
    leftEn: 'Unsexy underwear',
    rightEn: 'Sexy underwear',
  },
  {
    left: 'Schlechter Sexort',
    right: 'Heißer Sexort',
    leftEn: 'Bad sex spot',
    rightEn: 'Hot sex spot',
  },
  {
    left: 'Schlechtes Vorspiel',
    right: 'Gutes Vorspiel',
    leftEn: 'Bad foreplay',
    rightEn: 'Good foreplay',
  },
  {
    left: 'Schlechter Dirty Talk',
    right: 'Guter Dirty Talk',
    leftEn: 'Bad dirty talk',
    rightEn: 'Good dirty talk',
  },
  {
    left: 'Schlechte Sexposition',
    right: 'Gute Sexposition',
    leftEn: 'Bad sex position',
    rightEn: 'Good sex position',
  },
  {
    left: 'Schlechtes Sexting',
    right: 'Gutes Sexting',
    leftEn: 'Bad sexting',
    rightEn: 'Good sexting',
  },
  {
    left: 'Peinlicher Sexmoment',
    right: 'Heißer Sexmoment',
    leftEn: 'Awkward sex moment',
    rightEn: 'Hot sex moment',
  },
  {
    left: 'Schlechte Bettgeschichte',
    right: 'Gute Bettgeschichte',
    leftEn: 'Bad hookup',
    rightEn: 'Great hookup',
  },
  {
    left: 'Schlechter Sexsong',
    right: 'Guter Sexsong',
    leftEn: 'Bad sex song',
    rightEn: 'Good sex song',
  },
  {
    left: 'Schlechtes Sexspielzeug',
    right: 'Gutes Sexspielzeug',
    leftEn: 'Bad sex toy',
    rightEn: 'Good sex toy',
  },
  {
    left: 'Lahme Fantasie',
    right: 'Heiße Fantasie',
    leftEn: 'Lame fantasy',
    rightEn: 'Hot fantasy',
  },
  {
    left: 'Schüchtern im Bett',
    right: 'Wild im Bett',
    leftEn: 'Shy in bed',
    rightEn: 'Wild in bed',
  },
  {
    left: 'Langsam und zärtlich',
    right: 'Schnell und wild',
    leftEn: 'Slow and tender',
    rightEn: 'Fast and wild',
  },
  {
    left: 'Unsexy Körperteil',
    right: 'Sexy Körperteil',
    leftEn: 'Unsexy body part',
    rightEn: 'Sexy body part',
  },
  { left: 'Unsexy Beruf', right: 'Sexy Beruf', leftEn: 'Unsexy job', rightEn: 'Sexy job' },
  { left: 'Unsexy Akzent', right: 'Sexy Akzent', leftEn: 'Unsexy accent', rightEn: 'Sexy accent' },
  { left: 'Unsexy Name', right: 'Sexy Name', leftEn: 'Unsexy name', rightEn: 'Sexy name' },
  { left: 'Unsexy Hobby', right: 'Sexy Hobby', leftEn: 'Unsexy hobby', rightEn: 'Sexy hobby' },
  { left: 'Unsexy Outfit', right: 'Sexy Outfit', leftEn: 'Unsexy outfit', rightEn: 'Sexy outfit' },
  { left: 'Unsexy Geruch', right: 'Sexy Geruch', leftEn: 'Unsexy scent', rightEn: 'Sexy scent' },
  {
    left: 'Unsexy Geräusch',
    right: 'Sexy Geräusch',
    leftEn: 'Unsexy sound',
    rightEn: 'Sexy sound',
  },
  {
    left: 'Unsexy Angewohnheit',
    right: 'Sexy Angewohnheit',
    leftEn: 'Unsexy habit',
    rightEn: 'Sexy habit',
  },
  {
    left: 'Unsexy Kostüm',
    right: 'Sexy Kostüm',
    leftEn: 'Unsexy costume',
    rightEn: 'Sexy costume',
  },
  {
    left: 'Unsexy Frisur',
    right: 'Sexy Frisur',
    leftEn: 'Unsexy hairstyle',
    rightEn: 'Sexy hairstyle',
  },
  { left: 'Unsexy Auto', right: 'Sexy Auto', leftEn: 'Unsexy car', rightEn: 'Sexy car' },
  { left: 'Unsexy Wort', right: 'Sexy Wort', leftEn: 'Unsexy word', rightEn: 'Sexy word' },
  {
    left: 'Unsexy Sportart',
    right: 'Sexy Sportart',
    leftEn: 'Unsexy sport',
    rightEn: 'Sexy sport',
  },
  { left: 'Unsexy Tanz', right: 'Sexy Tanz', leftEn: 'Unsexy dance', rightEn: 'Sexy dance' },
  {
    left: 'Harmloser Fetisch',
    right: 'Wilder Fetisch',
    leftEn: 'Mild fetish',
    rightEn: 'Wild fetish',
  },
  { left: 'Keine Chemie', right: 'Pure Chemie', leftEn: 'No chemistry', rightEn: 'Pure chemistry' },
  {
    left: 'Schlechter Sextipp',
    right: 'Guter Sextipp',
    leftEn: 'Bad sex advice',
    rightEn: 'Good sex advice',
  },
  {
    left: 'Schlechtes Safeword',
    right: 'Gutes Safeword',
    leftEn: 'Bad safeword',
    rightEn: 'Good safeword',
  },
  {
    left: 'Schlechtes Rollenspiel',
    right: 'Gutes Rollenspiel',
    leftEn: 'Bad roleplay',
    rightEn: 'Good roleplay',
  },
  {
    left: 'Harmloses Geständnis',
    right: 'Versautes Geständnis',
    leftEn: 'Innocent confession',
    rightEn: 'Dirty confession',
  },
  {
    left: 'Harmloser Flirt',
    right: 'Eindeutiges Angebot',
    leftEn: 'Innocent flirt',
    rightEn: 'Clear proposition',
  },
  {
    left: 'Unsexy Filmszene',
    right: 'Heiße Filmszene',
    leftEn: 'Unsexy movie scene',
    rightEn: 'Steamy movie scene',
  },
  {
    left: 'Unsexy Schlafzimmer',
    right: 'Sexy Schlafzimmer',
    leftEn: 'Unsexy bedroom',
    rightEn: 'Sexy bedroom',
  },
  {
    left: 'Schlechter Morgen danach',
    right: 'Guter Morgen danach',
    leftEn: 'Bad morning after',
    rightEn: 'Good morning after',
  },
  {
    left: 'Walk of Shame',
    right: 'Walk of Fame',
    leftEn: 'Walk of shame',
    rightEn: 'Walk of fame',
  },
  {
    left: 'Schlechter Strip',
    right: 'Guter Strip',
    leftEn: 'Bad striptease',
    rightEn: 'Good striptease',
  },
  {
    left: 'Schlechte Massage',
    right: 'Sinnliche Massage',
    leftEn: 'Bad massage',
    rightEn: 'Sensual massage',
  },
  {
    left: 'Winziger Knutschfleck',
    right: 'Riesiger Knutschfleck',
    leftEn: 'Tiny hickey',
    rightEn: 'Huge hickey',
  },
  {
    left: 'Schüchterner Kuss',
    right: 'Leidenschaftlicher Kuss',
    leftEn: 'Shy kiss',
    rightEn: 'Passionate kiss',
  },
  {
    left: 'Kein Sexappeal',
    right: 'Purer Sexappeal',
    leftEn: 'No sex appeal',
    rightEn: 'Pure sex appeal',
  },
  {
    left: 'Unsexy Reiseziel',
    right: 'Sexy Reiseziel',
    leftEn: 'Unsexy destination',
    rightEn: 'Sexy destination',
  },
  { left: 'Prüde', right: 'Freizügig', leftEn: 'Prudish', rightEn: 'Uninhibited' },
  {
    left: 'Jugendfrei',
    right: 'Nicht jugendfrei',
    leftEn: 'Family friendly',
    rightEn: 'Adults only',
  },
  {
    left: 'Schlechter Quickie',
    right: 'Guter Quickie',
    leftEn: 'Bad quickie',
    rightEn: 'Good quickie',
  },
  {
    left: 'Lahmes Kopfkino',
    right: 'Heißes Kopfkino',
    leftEn: 'Lame daydream',
    rightEn: 'Steamy daydream',
  },
  {
    left: 'Unsexy Kompliment',
    right: 'Sexy Kompliment',
    leftEn: 'Unsexy compliment',
    rightEn: 'Sexy compliment',
  },
  { left: 'Unsexy Uhrzeit', right: 'Sexy Uhrzeit', leftEn: 'Unsexy hour', rightEn: 'Sexy hour' },
  {
    left: 'Unsexy Jahreszeit',
    right: 'Sexy Jahreszeit',
    leftEn: 'Unsexy season',
    rightEn: 'Sexy season',
  },
  {
    left: 'Unsexy Sternzeichen',
    right: 'Sexy Sternzeichen',
    leftEn: 'Unsexy zodiac sign',
    rightEn: 'Sexy zodiac sign',
  },
  { left: 'Unsexy Getränk', right: 'Sexy Getränk', leftEn: 'Unsexy drink', rightEn: 'Sexy drink' },
  {
    left: 'Unsexy Musikgenre',
    right: 'Sexy Musikgenre',
    leftEn: 'Unsexy music genre',
    rightEn: 'Sexy music genre',
  },
  {
    left: 'Unsexy Sprache',
    right: 'Sexy Sprache',
    leftEn: 'Unsexy language',
    rightEn: 'Sexy language',
  },
  { left: 'Unsexy Stoff', right: 'Sexy Stoff', leftEn: 'Unsexy fabric', rightEn: 'Sexy fabric' },
  { left: 'Unsexy Farbe', right: 'Sexy Farbe', leftEn: 'Unsexy color', rightEn: 'Sexy color' },
  {
    left: 'Unsexy Accessoire',
    right: 'Sexy Accessoire',
    leftEn: 'Unsexy accessory',
    rightEn: 'Sexy accessory',
  },
  { left: 'Unsexy Bart', right: 'Sexy Bart', leftEn: 'Unsexy beard', rightEn: 'Sexy beard' },
  { left: 'Unsexy Schuhe', right: 'Sexy Schuhe', leftEn: 'Unsexy shoes', rightEn: 'Sexy shoes' },
  { left: 'Unsexy Tattoo', right: 'Sexy Tattoo', leftEn: 'Unsexy tattoo', rightEn: 'Sexy tattoo' },
  {
    left: 'Unsexy Charakterzug',
    right: 'Sexy Charakterzug',
    leftEn: 'Unsexy trait',
    rightEn: 'Sexy trait',
  },
  {
    left: 'Unsexy Fähigkeit',
    right: 'Sexy Fähigkeit',
    leftEn: 'Unsexy skill',
    rightEn: 'Sexy skill',
  },
  { left: 'Unsexy Frucht', right: 'Sexy Frucht', leftEn: 'Unsexy fruit', rightEn: 'Sexy fruit' },
  {
    left: 'Unsexy Möbelstück',
    right: 'Sexy Möbelstück',
    leftEn: 'Unsexy furniture',
    rightEn: 'Sexy furniture',
  },
  {
    left: 'Unsexy Instrument',
    right: 'Sexy Instrument',
    leftEn: 'Unsexy instrument',
    rightEn: 'Sexy instrument',
  },
  {
    left: 'Langweiliges Sexleben',
    right: 'Aufregendes Sexleben',
    leftEn: 'Boring sex life',
    rightEn: 'Exciting sex life',
  },
  {
    left: 'Einmal im Monat',
    right: 'Dreimal täglich',
    leftEn: 'Once a month',
    rightEn: 'Three times daily',
  },
  {
    left: 'Ganz leise',
    right: 'Nachbarn wecken',
    leftEn: 'Dead quiet',
    rightEn: 'Wake the neighbors',
  },
  { left: 'Licht aus', right: 'Licht an', leftEn: 'Lights off', rightEn: 'Lights on' },
  {
    left: 'Unter der Decke',
    right: 'Auf der Waschmaschine',
    leftEn: 'Under the covers',
    rightEn: 'On the washer',
  },
  {
    left: 'Kuschelsex',
    right: 'Hemmungsloser Sex',
    leftEn: 'Cuddly sex',
    rightEn: 'Uninhibited sex',
  },
  {
    left: 'Kleiner Engel',
    right: 'Kleiner Teufel',
    leftEn: 'Little angel',
    rightEn: 'Little devil',
  },
  {
    left: 'Zahmer Pärchenabend',
    right: 'Wilder Pärchenabend',
    leftEn: 'Tame couples night',
    rightEn: 'Wild couples night',
  },
  {
    left: 'Harmlose Pflicht',
    right: 'Versaute Pflicht',
    leftEn: 'Tame dare',
    rightEn: 'Dirty dare',
  },
  {
    left: 'Harmlose Frage',
    right: 'Versaute Frage',
    leftEn: 'Innocent question',
    rightEn: 'Dirty question',
  },
  { left: 'Harmloser Witz', right: 'Versauter Witz', leftEn: 'Clean joke', rightEn: 'Dirty joke' },
  {
    left: 'Harmlose Zweideutigkeit',
    right: 'Eindeutige Zweideutigkeit',
    leftEn: 'Subtle innuendo',
    rightEn: 'Blatant innuendo',
  },
  {
    left: 'Harmloses Selfie',
    right: 'Freches Selfie',
    leftEn: 'Innocent selfie',
    rightEn: 'Cheeky selfie',
  },
  {
    left: 'Harmloser Suchverlauf',
    right: 'Versauter Suchverlauf',
    leftEn: 'Clean search history',
    rightEn: 'Dirty search history',
  },
  { left: 'Harmloses Lied', right: 'Versautes Lied', leftEn: 'Clean song', rightEn: 'Dirty song' },
  {
    left: 'Harmlose Bettlektüre',
    right: 'Versaute Bettlektüre',
    leftEn: 'Innocent bedtime read',
    rightEn: 'Steamy bedtime read',
  },
  { left: 'Null Lust', right: 'Brennende Lust', leftEn: 'Zero desire', rightEn: 'Burning desire' },
  { left: 'Unsexy Geschenk', right: 'Sexy Geschenk', leftEn: 'Unsexy gift', rightEn: 'Sexy gift' },
  {
    left: 'Unsexy Hotelzimmer',
    right: 'Sexy Hotelzimmer',
    leftEn: 'Unsexy hotel room',
    rightEn: 'Sexy hotel room',
  },
  {
    left: 'Harmloser Sexunfall',
    right: 'Legendärer Sexunfall',
    leftEn: 'Minor sex mishap',
    rightEn: 'Legendary sex mishap',
  },
  {
    left: 'Schnell vorbei',
    right: 'Die ganze Nacht',
    leftEn: 'Over quickly',
    rightEn: 'All night long',
  },
  { left: 'Schlechter Sex', right: 'Bester Sex', leftEn: 'Bad sex', rightEn: 'Best sex ever' },
  { left: 'Unbeholfen', right: 'Verführerisch', leftEn: 'Clumsy', rightEn: 'Seductive' },
  {
    left: 'Schlechter Liebhaber',
    right: 'Guter Liebhaber',
    leftEn: 'Bad lover',
    rightEn: 'Good lover',
  },
  {
    left: 'Harmloser Traum',
    right: 'Versauter Traum',
    leftEn: 'Innocent dream',
    rightEn: 'Dirty dream',
  },
  {
    left: 'Unsexy Begrüßung',
    right: 'Sexy Begrüßung',
    leftEn: 'Unsexy greeting',
    rightEn: 'Sexy greeting',
  },
  {
    left: 'Unsexy Gesprächsthema',
    right: 'Sexy Gesprächsthema',
    leftEn: 'Unsexy topic',
    rightEn: 'Sexy topic',
  },
];
