import type { HeadsUpSeed } from './types';

export const brandsWords: HeadsUpSeed[] = [
  { de: 'IKEA', en: 'IKEA' },
  { de: 'Nutella', en: 'Nutella' },
  { de: 'Instagram', en: 'Instagram' },
  { de: 'PlayStation', en: 'PlayStation' },
  { de: 'Coca-Cola', en: 'Coca-Cola' },
  { de: 'McDonald’s', en: 'McDonald’s' },
  { de: 'Apple', en: 'Apple' },
  { de: 'Google', en: 'Google' },
  { de: 'Amazon', en: 'Amazon' },
  { de: 'Netflix', en: 'Netflix' },
  { de: 'Spotify', en: 'Spotify' },
  { de: 'YouTube', en: 'YouTube' },
  { de: 'TikTok', en: 'TikTok' },
  { de: 'WhatsApp', en: 'WhatsApp' },
  { de: 'Facebook', en: 'Facebook' },
  { de: 'Snapchat', en: 'Snapchat' },
  { de: 'Twitter', en: 'Twitter' },
  { de: 'Microsoft', en: 'Microsoft' },
  { de: 'Samsung', en: 'Samsung' },
  { de: 'Nike', en: 'Nike' },
  { de: 'Adidas', en: 'Adidas' },
  { de: 'Puma', en: 'Puma' },
  { de: 'BMW', en: 'BMW' },
  { de: 'Mercedes-Benz', en: 'Mercedes-Benz' },
  { de: 'Volkswagen', en: 'Volkswagen' },
  { de: 'Audi', en: 'Audi' },
  { de: 'Porsche', en: 'Porsche' },
  { de: 'Ferrari', en: 'Ferrari' },
  { de: 'Tesla', en: 'Tesla' },
  { de: 'Lamborghini', en: 'Lamborghini' },
  { de: 'Lego', en: 'Lego' },
  { de: 'Barbie', en: 'Barbie' },
  { de: 'Haribo', en: 'Haribo' },
  { de: 'Milka', en: 'Milka' },
  { de: 'Überraschungsei', en: 'Kinder Surprise' },
  { de: 'Red Bull', en: 'Red Bull' },
  { de: 'Pepsi', en: 'Pepsi' },
  { de: 'Fanta', en: 'Fanta' },
  { de: 'Sprite', en: 'Sprite' },
  { de: 'Burger King', en: 'Burger King' },
  { de: 'KFC', en: 'KFC' },
  { de: 'Subway', en: 'Subway' },
  { de: 'Starbucks', en: 'Starbucks' },
  { de: 'Pizza Hut', en: 'Pizza Hut' },
  { de: 'Domino’s', en: 'Domino’s' },
  { de: 'Disney', en: 'Disney' },
  { de: 'Pixar', en: 'Pixar' },
  { de: 'Nintendo', en: 'Nintendo' },
  { de: 'Xbox', en: 'Xbox' },
  { de: 'Game Boy', en: 'Game Boy' },
  { de: 'iPhone', en: 'iPhone' },
  { de: 'iPad', en: 'iPad' },
  { de: 'AirPods', en: 'AirPods' },
  { de: 'MacBook', en: 'MacBook' },
  { de: 'Windows', en: 'Windows' },
  { de: 'Excel', en: 'Excel' },
  { de: 'PowerPoint', en: 'PowerPoint' },
  { de: 'Zoom', en: 'Zoom' },
  { de: 'Skype', en: 'Skype' },
  { de: 'Tinder', en: 'Tinder' },
  { de: 'Uber', en: 'Uber' },
  { de: 'Airbnb', en: 'Airbnb' },
  { de: 'eBay', en: 'eBay' },
  { de: 'PayPal', en: 'PayPal' },
  { de: 'Visa', en: 'Visa' },
  { de: 'Mastercard', en: 'Mastercard' },
  { de: 'Zalando', en: 'Zalando' },
  { de: 'H&M', en: 'H&M' },
  { de: 'Zara', en: 'Zara' },
  { de: 'Primark', en: 'Primark' },
  { de: 'Gucci', en: 'Gucci' },
  { de: 'Louis Vuitton', en: 'Louis Vuitton' },
  { de: 'Chanel', en: 'Chanel' },
  { de: 'Prada', en: 'Prada' },
  { de: 'Rolex', en: 'Rolex' },
  { de: 'Ray-Ban', en: 'Ray-Ban' },
  { de: 'Levi’s', en: 'Levi’s' },
  { de: 'Converse', en: 'Converse' },
  { de: 'Vans', en: 'Vans' },
  { de: 'Crocs', en: 'Crocs' },
  { de: 'Birkenstock', en: 'Birkenstock' },
  { de: 'Nivea', en: 'Nivea' },
  { de: 'Playmobil', en: 'Playmobil' },
  { de: 'Volvo', en: 'Volvo' },
  { de: 'Ritter Sport', en: 'Ritter Sport' },
  { de: 'Toblerone', en: 'Toblerone' },
  { de: 'Lindt', en: 'Lindt' },
  { de: 'Ferrero Rocher', en: 'Ferrero Rocher' },
  { de: 'Harley-Davidson', en: 'Harley-Davidson' },
  { de: 'Oreo', en: 'Oreo' },
  { de: 'Pringles', en: 'Pringles' },
  { de: 'Doritos', en: 'Doritos' },
  { de: 'M&M’s', en: 'M&M’s' },
  { de: 'Snickers', en: 'Snickers' },
  { de: 'Twix', en: 'Twix' },
  { de: 'Mars', en: 'Mars' },
  { de: 'KitKat', en: 'KitKat' },
  { de: 'Skittles', en: 'Skittles' },
  { de: 'Mentos', en: 'Mentos' },
  { de: 'Tic Tac', en: 'Tic Tac' },
  { de: 'Chupa Chups', en: 'Chupa Chups' },
  { de: 'Pez', en: 'Pez' },
  { de: 'Ben & Jerry’s', en: 'Ben & Jerry’s' },
  { de: 'Magnum', en: 'Magnum' },
  { de: 'Heinz', en: 'Heinz' },
  { de: 'Maggi', en: 'Maggi' },
  { de: 'Knorr', en: 'Knorr' },
  { de: 'Dr. Oetker', en: 'Dr. Oetker' },
  { de: 'Kellogg’s', en: 'Kellogg’s' },
  { de: 'Nesquik', en: 'Nesquik' },
  { de: 'Nescafé', en: 'Nescafé' },
  { de: 'Capri-Sonne', en: 'Capri-Sun' },
  { de: 'Jägermeister', en: 'Jägermeister' },
  { de: 'Heineken', en: 'Heineken' },
  { de: 'Corona', en: 'Corona' },
  { de: 'Beck’s', en: 'Beck’s' },
  { de: 'Absolut Vodka', en: 'Absolut Vodka' },
  { de: 'Bacardi', en: 'Bacardi' },
  { de: 'Aperol', en: 'Aperol' },
  { de: 'Smirnoff', en: 'Smirnoff' },
  { de: 'Jack Daniel’s', en: 'Jack Daniel’s' },
  { de: 'Lufthansa', en: 'Lufthansa' },
  { de: 'Ryanair', en: 'Ryanair' },
  { de: 'Deutsche Bahn', en: 'Deutsche Bahn' },
  { de: 'DHL', en: 'DHL' },
  { de: 'UPS', en: 'UPS' },
  { de: 'Aldi', en: 'Aldi' },
  { de: 'Lidl', en: 'Lidl' },
  { de: 'Walmart', en: 'Walmart' },
  { de: 'Shell', en: 'Shell' },
  { de: 'Tupperware', en: 'Tupperware' },
  { de: 'Post-it', en: 'Post-it' },
  { de: 'Duracell', en: 'Duracell' },
  { de: 'Gillette', en: 'Gillette' },
  { de: 'Colgate', en: 'Colgate' },
  { de: 'Pampers', en: 'Pampers' },
  { de: 'Swarovski', en: 'Swarovski' },
  { de: 'Tiffany', en: 'Tiffany' },
  { de: 'Victoria’s Secret', en: 'Victoria’s Secret' },
  { de: 'Calvin Klein', en: 'Calvin Klein' },
  { de: 'Tommy Hilfiger', en: 'Tommy Hilfiger' },
  { de: 'Ralph Lauren', en: 'Ralph Lauren' },
  { de: 'The North Face', en: 'The North Face' },
  { de: 'Jack Wolfskin', en: 'Jack Wolfskin' },
  { de: 'Hugo Boss', en: 'Hugo Boss' },
  { de: 'Versace', en: 'Versace' },
  { de: 'Dior', en: 'Dior' },
  { de: 'Hermès', en: 'Hermès' },
  { de: 'Balenciaga', en: 'Balenciaga' },
  { de: 'Supreme', en: 'Supreme' },
  { de: 'New Balance', en: 'New Balance' },
  { de: 'Reebok', en: 'Reebok' },
  { de: 'Under Armour', en: 'Under Armour' },
  { de: 'Fila', en: 'Fila' },
  { de: 'Canon', en: 'Canon' },
  { de: 'Nikon', en: 'Nikon' },
  { de: 'GoPro', en: 'GoPro' },
  { de: 'Sony', en: 'Sony' },
  { de: 'LG', en: 'LG' },
  { de: 'Philips', en: 'Philips' },
  { de: 'Bosch', en: 'Bosch' },
  { de: 'Siemens', en: 'Siemens' },
  { de: 'Miele', en: 'Miele' },
  { de: 'Dyson', en: 'Dyson' },
  { de: 'Thermomix', en: 'Thermomix' },
  { de: 'Nespresso', en: 'Nespresso' },
  { de: 'Huawei', en: 'Huawei' },
  { de: 'Nokia', en: 'Nokia' },
  { de: 'BlackBerry', en: 'BlackBerry' },
  { de: 'Intel', en: 'Intel' },
  { de: 'Nvidia', en: 'Nvidia' },
  { de: 'Fortnite', en: 'Fortnite' },
  { de: 'Minecraft', en: 'Minecraft' },
  { de: 'Pokémon', en: 'Pokémon' },
  { de: 'Super Mario', en: 'Super Mario' },
  { de: 'Tetris', en: 'Tetris' },
  { de: 'Monopoly', en: 'Monopoly' },
  { de: 'Uno', en: 'Uno' },
  { de: 'Jenga', en: 'Jenga' },
  { de: 'Twister', en: 'Twister' },
  { de: 'Zauberwürfel', en: 'Rubik’s Cube' },
  { de: 'Tamagotchi', en: 'Tamagotchi' },
  { de: 'Duolingo', en: 'Duolingo' },
  { de: 'Wikipedia', en: 'Wikipedia' },
  { de: 'ChatGPT', en: 'ChatGPT' },
  { de: 'Telegram', en: 'Telegram' },
  { de: 'LinkedIn', en: 'LinkedIn' },
  { de: 'Pinterest', en: 'Pinterest' },
  { de: 'Reddit', en: 'Reddit' },
  { de: 'Twitch', en: 'Twitch' },
  { de: 'Discord', en: 'Discord' },
  { de: 'Shazam', en: 'Shazam' },
  { de: 'Google Maps', en: 'Google Maps' },
  { de: 'Shein', en: 'Shein' },
  { de: 'Temu', en: 'Temu' },
  { de: 'Fiat', en: 'Fiat' },
  { de: 'Toyota', en: 'Toyota' },
  { de: 'Ford', en: 'Ford' },
  { de: 'Jeep', en: 'Jeep' },
  { de: 'Vespa', en: 'Vespa' },
];
