import type { HeadsUpSeed } from './types';

export const celebritiesWords: HeadsUpSeed[] = [
  { de: 'Brad Pitt', en: 'Brad Pitt' },
  { de: 'Angelina Jolie', en: 'Angelina Jolie' },
  { de: 'Leonardo DiCaprio', en: 'Leonardo DiCaprio' },
  { de: 'Tom Cruise', en: 'Tom Cruise' },
  { de: 'Tom Hanks', en: 'Tom Hanks' },
  { de: 'Johnny Depp', en: 'Johnny Depp' },
  { de: 'Will Smith', en: 'Will Smith' },
  { de: 'Jennifer Aniston', en: 'Jennifer Aniston' },
  { de: 'Scarlett Johansson', en: 'Scarlett Johansson' },
  { de: 'Meryl Streep', en: 'Meryl Streep' },
  { de: 'Julia Roberts', en: 'Julia Roberts' },
  { de: 'Morgan Freeman', en: 'Morgan Freeman' },
  { de: 'Keanu Reeves', en: 'Keanu Reeves' },
  { de: 'Arnold Schwarzenegger', en: 'Arnold Schwarzenegger' },
  { de: 'Sylvester Stallone', en: 'Sylvester Stallone' },
  { de: 'Jackie Chan', en: 'Jackie Chan' },
  { de: 'Dwayne Johnson', en: 'Dwayne Johnson' },
  { de: 'Robert Downey Jr.', en: 'Robert Downey Jr.' },
  { de: 'Margot Robbie', en: 'Margot Robbie' },
  { de: 'Emma Watson', en: 'Emma Watson' },
  { de: 'Daniel Radcliffe', en: 'Daniel Radcliffe' },
  { de: 'Nicole Kidman', en: 'Nicole Kidman' },
  { de: 'Ryan Gosling', en: 'Ryan Gosling' },
  { de: 'Ryan Reynolds', en: 'Ryan Reynolds' },
  { de: 'Zendaya', en: 'Zendaya' },
  { de: 'Timothée Chalamet', en: 'Timothée Chalamet' },
  { de: 'Hugh Jackman', en: 'Hugh Jackman' },
  { de: 'Chris Hemsworth', en: 'Chris Hemsworth' },
  { de: 'George Clooney', en: 'George Clooney' },
  { de: 'Matt Damon', en: 'Matt Damon' },
  { de: 'Denzel Washington', en: 'Denzel Washington' },
  { de: 'Jim Carrey', en: 'Jim Carrey' },
  { de: 'Adam Sandler', en: 'Adam Sandler' },
  { de: 'Charlie Chaplin', en: 'Charlie Chaplin' },
  { de: 'Marilyn Monroe', en: 'Marilyn Monroe' },
  { de: 'Audrey Hepburn', en: 'Audrey Hepburn' },
  { de: 'Bruce Willis', en: 'Bruce Willis' },
  { de: 'Jennifer Lawrence', en: 'Jennifer Lawrence' },
  { de: 'Sandra Bullock', en: 'Sandra Bullock' },
  { de: 'Rowan Atkinson', en: 'Rowan Atkinson' },
  { de: 'Vin Diesel', en: 'Vin Diesel' },
  { de: 'Samuel L. Jackson', en: 'Samuel L. Jackson' },
  { de: 'Harrison Ford', en: 'Harrison Ford' },
  { de: 'Al Pacino', en: 'Al Pacino' },
  { de: 'Pedro Pascal', en: 'Pedro Pascal' },
  { de: 'Tom Holland', en: 'Tom Holland' },
  { de: 'Christoph Waltz', en: 'Christoph Waltz' },
  { de: 'Taylor Swift', en: 'Taylor Swift' },
  { de: 'Beyoncé', en: 'Beyoncé' },
  { de: 'Rihanna', en: 'Rihanna' },
  { de: 'Lady Gaga', en: 'Lady Gaga' },
  { de: 'Madonna', en: 'Madonna' },
  { de: 'Michael Jackson', en: 'Michael Jackson' },
  { de: 'Elvis Presley', en: 'Elvis Presley' },
  { de: 'Freddie Mercury', en: 'Freddie Mercury' },
  { de: 'Ed Sheeran', en: 'Ed Sheeran' },
  { de: 'Justin Bieber', en: 'Justin Bieber' },
  { de: 'Adele', en: 'Adele' },
  { de: 'Eminem', en: 'Eminem' },
  { de: 'Drake', en: 'Drake' },
  { de: 'Billie Eilish', en: 'Billie Eilish' },
  { de: 'Ariana Grande', en: 'Ariana Grande' },
  { de: 'Shakira', en: 'Shakira' },
  { de: 'Britney Spears', en: 'Britney Spears' },
  { de: 'Kanye West', en: 'Kanye West' },
  { de: 'Snoop Dogg', en: 'Snoop Dogg' },
  { de: 'Bruno Mars', en: 'Bruno Mars' },
  { de: 'Elton John', en: 'Elton John' },
  { de: 'Mick Jagger', en: 'Mick Jagger' },
  { de: 'John Lennon', en: 'John Lennon' },
  { de: 'David Bowie', en: 'David Bowie' },
  { de: 'Bob Marley', en: 'Bob Marley' },
  { de: 'Dua Lipa', en: 'Dua Lipa' },
  { de: 'Harry Styles', en: 'Harry Styles' },
  { de: 'Miley Cyrus', en: 'Miley Cyrus' },
  { de: 'Katy Perry', en: 'Katy Perry' },
  { de: 'Jennifer Lopez', en: 'Jennifer Lopez' },
  { de: 'Céline Dion', en: 'Céline Dion' },
  { de: 'Whitney Houston', en: 'Whitney Houston' },
  { de: 'Kurt Cobain', en: 'Kurt Cobain' },
  { de: 'Tina Turner', en: 'Tina Turner' },
  { de: 'Cher', en: 'Cher' },
  { de: 'Dolly Parton', en: 'Dolly Parton' },
  { de: 'Mozart', en: 'Mozart' },
  { de: 'Beethoven', en: 'Beethoven' },
  { de: 'Cristiano Ronaldo', en: 'Cristiano Ronaldo' },
  { de: 'Lionel Messi', en: 'Lionel Messi' },
  { de: 'Neymar', en: 'Neymar' },
  { de: 'Kylian Mbappé', en: 'Kylian Mbappé' },
  { de: 'Usain Bolt', en: 'Usain Bolt' },
  { de: 'Michael Jordan', en: 'Michael Jordan' },
  { de: 'LeBron James', en: 'LeBron James' },
  { de: 'Roger Federer', en: 'Roger Federer' },
  { de: 'Serena Williams', en: 'Serena Williams' },
  { de: 'Rafael Nadal', en: 'Rafael Nadal' },
  { de: 'Muhammad Ali', en: 'Muhammad Ali' },
  { de: 'Mike Tyson', en: 'Mike Tyson' },
  { de: 'Tiger Woods', en: 'Tiger Woods' },
  { de: 'Lewis Hamilton', en: 'Lewis Hamilton' },
  { de: 'Michael Schumacher', en: 'Michael Schumacher' },
  { de: 'Max Verstappen', en: 'Max Verstappen' },
  { de: 'Michael Phelps', en: 'Michael Phelps' },
  { de: 'Zlatan Ibrahimović', en: 'Zlatan Ibrahimović' },
  { de: 'David Beckham', en: 'David Beckham' },
  { de: 'Pelé', en: 'Pelé' },
  { de: 'Diego Maradona', en: 'Diego Maradona' },
  { de: 'Dirk Nowitzki', en: 'Dirk Nowitzki' },
  { de: 'Manuel Neuer', en: 'Manuel Neuer' },
  { de: 'Thomas Müller', en: 'Thomas Müller' },
  { de: 'Franz Beckenbauer', en: 'Franz Beckenbauer' },
  { de: 'Boris Becker', en: 'Boris Becker' },
  { de: 'Steffi Graf', en: 'Steffi Graf' },
  { de: 'Toni Kroos', en: 'Toni Kroos' },
  { de: 'Jürgen Klopp', en: 'Jürgen Klopp' },
  { de: 'Erling Haaland', en: 'Erling Haaland' },
  { de: 'Simone Biles', en: 'Simone Biles' },
  { de: 'Kobe Bryant', en: 'Kobe Bryant' },
  { de: 'Angela Merkel', en: 'Angela Merkel' },
  { de: 'Olaf Scholz', en: 'Olaf Scholz' },
  { de: 'Friedrich Merz', en: 'Friedrich Merz' },
  { de: 'Donald Trump', en: 'Donald Trump' },
  { de: 'Barack Obama', en: 'Barack Obama' },
  { de: 'Michelle Obama', en: 'Michelle Obama' },
  { de: 'Joe Biden', en: 'Joe Biden' },
  { de: 'Emmanuel Macron', en: 'Emmanuel Macron' },
  { de: 'Queen Elizabeth', en: 'Queen Elizabeth' },
  { de: 'Prinz Harry', en: 'Prince Harry' },
  { de: 'Lady Diana', en: 'Lady Diana' },
  { de: 'Kim Jong-un', en: 'Kim Jong-un' },
  { de: 'Nelson Mandela', en: 'Nelson Mandela' },
  { de: 'Mahatma Gandhi', en: 'Mahatma Gandhi' },
  { de: 'Martin Luther King', en: 'Martin Luther King' },
  { de: 'Abraham Lincoln', en: 'Abraham Lincoln' },
  { de: 'John F. Kennedy', en: 'John F. Kennedy' },
  { de: 'Helmut Kohl', en: 'Helmut Kohl' },
  { de: 'Papst Franziskus', en: 'Pope Francis' },
  { de: 'Dalai Lama', en: 'Dalai Lama' },
  { de: 'Winston Churchill', en: 'Winston Churchill' },
  { de: 'Napoleon', en: 'Napoleon' },
  { de: 'Albert Einstein', en: 'Albert Einstein' },
  { de: 'Isaac Newton', en: 'Isaac Newton' },
  { de: 'Leonardo da Vinci', en: 'Leonardo da Vinci' },
  { de: 'Kleopatra', en: 'Cleopatra' },
  { de: 'Julius Cäsar', en: 'Julius Caesar' },
  { de: 'Christoph Kolumbus', en: 'Christopher Columbus' },
  { de: 'Martin Luther', en: 'Martin Luther' },
  { de: 'Karl Marx', en: 'Karl Marx' },
  { de: 'Sigmund Freud', en: 'Sigmund Freud' },
  { de: 'Galileo Galilei', en: 'Galileo Galilei' },
  { de: 'Charles Darwin', en: 'Charles Darwin' },
  { de: 'Marie Curie', en: 'Marie Curie' },
  { de: 'Pablo Picasso', en: 'Pablo Picasso' },
  { de: 'Vincent van Gogh', en: 'Vincent van Gogh' },
  { de: 'Goethe', en: 'Goethe' },
  { de: 'William Shakespeare', en: 'William Shakespeare' },
  { de: 'Anne Frank', en: 'Anne Frank' },
  { de: 'Frida Kahlo', en: 'Frida Kahlo' },
  { de: 'Neil Armstrong', en: 'Neil Armstrong' },
  { de: 'Walt Disney', en: 'Walt Disney' },
  { de: 'Steve Jobs', en: 'Steve Jobs' },
  { de: 'Bill Gates', en: 'Bill Gates' },
  { de: 'Elon Musk', en: 'Elon Musk' },
  { de: 'Mark Zuckerberg', en: 'Mark Zuckerberg' },
  { de: 'Jeff Bezos', en: 'Jeff Bezos' },
  { de: 'Stephen Hawking', en: 'Stephen Hawking' },
  { de: 'Nikola Tesla', en: 'Nikola Tesla' },
  { de: 'Mutter Teresa', en: 'Mother Teresa' },
  { de: 'Alexander der Große', en: 'Alexander the Great' },
  { de: 'Kim Kardashian', en: 'Kim Kardashian' },
  { de: 'Kylie Jenner', en: 'Kylie Jenner' },
  { de: 'MrBeast', en: 'MrBeast' },
  { de: 'Paris Hilton', en: 'Paris Hilton' },
  { de: 'Oprah Winfrey', en: 'Oprah Winfrey' },
  { de: 'Gordon Ramsay', en: 'Gordon Ramsay' },
  { de: 'Heidi Klum', en: 'Heidi Klum' },
  { de: 'Dieter Bohlen', en: 'Dieter Bohlen' },
  { de: 'Thomas Gottschalk', en: 'Thomas Gottschalk' },
  { de: 'Günther Jauch', en: 'Günther Jauch' },
  { de: 'Stefan Raab', en: 'Stefan Raab' },
  { de: 'Jan Böhmermann', en: 'Jan Böhmermann' },
  { de: 'Joko Winterscheidt', en: 'Joko Winterscheidt' },
  { de: 'Helene Fischer', en: 'Helene Fischer' },
  { de: 'Herbert Grönemeyer', en: 'Herbert Grönemeyer' },
  { de: 'Udo Lindenberg', en: 'Udo Lindenberg' },
  { de: 'Nena', en: 'Nena' },
  { de: 'Til Schweiger', en: 'Til Schweiger' },
  { de: 'Matthias Schweighöfer', en: 'Matthias Schweighöfer' },
  { de: 'Bully Herbig', en: 'Bully Herbig' },
  { de: 'Barbara Schöneberger', en: 'Barbara Schöneberger' },
  { de: 'Sarah Connor', en: 'Sarah Connor' },
  { de: 'Mark Forster', en: 'Mark Forster' },
  { de: 'Elyas M’Barek', en: 'Elyas M’Barek' },
  { de: 'Diane Kruger', en: 'Diane Kruger' },
  { de: 'Hape Kerkeling', en: 'Hape Kerkeling' },
  { de: 'Otto Waalkes', en: 'Otto Waalkes' },
  { de: 'Karl Lagerfeld', en: 'Karl Lagerfeld' },
  { de: 'Claudia Schiffer', en: 'Claudia Schiffer' },
  { de: 'Florian Silbereisen', en: 'Florian Silbereisen' },
  { de: 'Sido', en: 'Sido' },
  { de: 'Cro', en: 'Cro' },
];
