import type { HeadsUpSeed } from './types';

export const everydayWords: HeadsUpSeed[] = [
  { de: 'Zahnbürste', en: 'Toothbrush' },
  { de: 'Regenschirm', en: 'Umbrella' },
  { de: 'Staubsaugen', en: 'Vacuuming' },
  { de: 'Kühlschrank', en: 'Fridge' },
  { de: 'Waschmaschine', en: 'Washing machine' },
  { de: 'Bügeleisen', en: 'Iron' },
  { de: 'Wecker', en: 'Alarm clock' },
  { de: 'Kopfkissen', en: 'Pillow' },
  { de: 'Bettdecke', en: 'Duvet' },
  { de: 'Handtuch', en: 'Towel' },
  { de: 'Seife', en: 'Soap' },
  { de: 'Shampoo', en: 'Shampoo' },
  { de: 'Zahnpasta', en: 'Toothpaste' },
  { de: 'Föhn', en: 'Hair dryer' },
  { de: 'Kamm', en: 'Comb' },
  { de: 'Spiegel', en: 'Mirror' },
  { de: 'Toilettenpapier', en: 'Toilet paper' },
  { de: 'Mülleimer', en: 'Trash can' },
  { de: 'Besen', en: 'Broom' },
  { de: 'Schlüssel', en: 'Key' },
  { de: 'Geldbeutel', en: 'Wallet' },
  { de: 'Handy', en: 'Phone' },
  { de: 'Ladekabel', en: 'Charging cable' },
  { de: 'Fernbedienung', en: 'Remote control' },
  { de: 'Fernseher', en: 'TV' },
  { de: 'Sofa', en: 'Couch' },
  { de: 'Lampe', en: 'Lamp' },
  { de: 'Glühbirne', en: 'Light bulb' },
  { de: 'Steckdose', en: 'Power outlet' },
  { de: 'Kerze', en: 'Candle' },
  { de: 'Feuerzeug', en: 'Lighter' },
  { de: 'Streichholz', en: 'Match' },
  { de: 'Kaffeemaschine', en: 'Coffee machine' },
  { de: 'Toaster', en: 'Toaster' },
  { de: 'Wasserkocher', en: 'Kettle' },
  { de: 'Mikrowelle', en: 'Microwave' },
  { de: 'Backofen', en: 'Oven' },
  { de: 'Herd', en: 'Stove' },
  { de: 'Pfanne', en: 'Frying pan' },
  { de: 'Kochtopf', en: 'Pot' },
  { de: 'Schneidebrett', en: 'Cutting board' },
  { de: 'Messer', en: 'Knife' },
  { de: 'Gabel', en: 'Fork' },
  { de: 'Löffel', en: 'Spoon' },
  { de: 'Teller', en: 'Plate' },
  { de: 'Tasse', en: 'Mug' },
  { de: 'Glas', en: 'Glass' },
  { de: 'Flaschenöffner', en: 'Bottle opener' },
  { de: 'Korkenzieher', en: 'Corkscrew' },
  { de: 'Dosenöffner', en: 'Can opener' },
  { de: 'Spülmaschine', en: 'Dishwasher' },
  { de: 'Abwaschen', en: 'Doing the dishes' },
  { de: 'Spülschwamm', en: 'Sponge' },
  { de: 'Geschirrtuch', en: 'Dish towel' },
  { de: 'Wäscheklammer', en: 'Clothespin' },
  { de: 'Wäscheständer', en: 'Drying rack' },
  { de: 'Kleiderbügel', en: 'Coat hanger' },
  { de: 'Kleiderschrank', en: 'Wardrobe' },
  { de: 'Schublade', en: 'Drawer' },
  { de: 'Teppich', en: 'Rug' },
  { de: 'Vorhang', en: 'Curtain' },
  { de: 'Fenster putzen', en: 'Cleaning windows' },
  { de: 'Bett machen', en: 'Making the bed' },
  { de: 'Wäsche aufhängen', en: 'Hanging up laundry' },
  { de: 'Einkaufen', en: 'Grocery shopping' },
  { de: 'Einkaufswagen', en: 'Shopping cart' },
  { de: 'Einkaufsliste', en: 'Shopping list' },
  { de: 'Kassenzettel', en: 'Receipt' },
  { de: 'Pfandflasche', en: 'Returnable bottle' },
  { de: 'Brille', en: 'Glasses' },
  { de: 'Sonnenbrille', en: 'Sunglasses' },
  { de: 'Armbanduhr', en: 'Wristwatch' },
  { de: 'Rucksack', en: 'Backpack' },
  { de: 'Handtasche', en: 'Handbag' },
  { de: 'Koffer', en: 'Suitcase' },
  { de: 'Schnürsenkel', en: 'Shoelace' },
  { de: 'Hausschuhe', en: 'Slippers' },
  { de: 'Socken', en: 'Socks' },
  { de: 'Jacke', en: 'Jacket' },
  { de: 'Mütze', en: 'Beanie' },
  { de: 'Schal', en: 'Scarf' },
  { de: 'Handschuhe', en: 'Gloves' },
  { de: 'Gummistiefel', en: 'Rubber boots' },
  { de: 'Schlafanzug', en: 'Pajamas' },
  { de: 'Bademantel', en: 'Bathrobe' },
  { de: 'Duschen', en: 'Taking a shower' },
  { de: 'Badewanne', en: 'Bathtub' },
  { de: 'Rasieren', en: 'Shaving' },
  { de: 'Nagelknipser', en: 'Nail clippers' },
  { de: 'Pflaster', en: 'Band-Aid' },
  { de: 'Fieberthermometer', en: 'Thermometer' },
  { de: 'Taschentuch', en: 'Tissue' },
  { de: 'Wattestäbchen', en: 'Cotton swab' },
  { de: 'Deo', en: 'Deodorant' },
  { de: 'Parfüm', en: 'Perfume' },
  { de: 'Lippenpflege', en: 'Lip balm' },
  { de: 'Haargummi', en: 'Hair tie' },
  { de: 'Kugelschreiber', en: 'Pen' },
  { de: 'Bleistift', en: 'Pencil' },
  { de: 'Radiergummi', en: 'Eraser' },
  { de: 'Schere', en: 'Scissors' },
  { de: 'Klebeband', en: 'Tape' },
  { de: 'Haftnotiz', en: 'Sticky note' },
  { de: 'Kalender', en: 'Calendar' },
  { de: 'Briefkasten', en: 'Mailbox' },
  { de: 'Briefmarke', en: 'Stamp' },
  { de: 'Paket', en: 'Package' },
  { de: 'Türklingel', en: 'Doorbell' },
  { de: 'Fußmatte', en: 'Doormat' },
  { de: 'Treppe', en: 'Stairs' },
  { de: 'Aufzug', en: 'Elevator' },
  { de: 'Garage', en: 'Garage' },
  { de: 'Fahrrad', en: 'Bicycle' },
  { de: 'Autowaschanlage', en: 'Car wash' },
  { de: 'Tanken', en: 'Getting gas' },
  { de: 'Parkplatz', en: 'Parking spot' },
  { de: 'Busfahren', en: 'Taking the bus' },
  { de: 'Ampel', en: 'Traffic light' },
  { de: 'Zebrastreifen', en: 'Crosswalk' },
  { de: 'Fahrkarte', en: 'Ticket' },
  { de: 'Batterie', en: 'Battery' },
  { de: 'Taschenlampe', en: 'Flashlight' },
  { de: 'Schraubenzieher', en: 'Screwdriver' },
  { de: 'Hammer', en: 'Hammer' },
  { de: 'Bohrmaschine', en: 'Drill' },
  { de: 'Leiter', en: 'Ladder' },
  { de: 'Werkzeugkasten', en: 'Toolbox' },
  { de: 'Gießkanne', en: 'Watering can' },
  { de: 'Rasenmäher', en: 'Lawn mower' },
  { de: 'Blumentopf', en: 'Flower pot' },
  { de: 'Gartenschlauch', en: 'Garden hose' },
  { de: 'Grillen', en: 'Barbecuing' },
  { de: 'Thermoskanne', en: 'Thermos' },
  { de: 'Brotdose', en: 'Lunch box' },
  { de: 'Trinkflasche', en: 'Water bottle' },
  { de: 'Strohhalm', en: 'Straw' },
  { de: 'Serviette', en: 'Napkin' },
  { de: 'Tischdecke', en: 'Tablecloth' },
  { de: 'Salzstreuer', en: 'Salt shaker' },
  { de: 'Pfeffermühle', en: 'Pepper grinder' },
  { de: 'Frühstück', en: 'Breakfast' },
  { de: 'Mittagsschlaf', en: 'Nap' },
  { de: 'Kochen', en: 'Cooking' },
  { de: 'Abendessen', en: 'Dinner' },
  { de: 'Aufräumen', en: 'Tidying up' },
  { de: 'Müll rausbringen', en: 'Taking out the trash' },
  { de: 'Staubwischen', en: 'Dusting' },
  { de: 'Wäschekorb', en: 'Laundry basket' },
  { de: 'Putzlappen', en: 'Cleaning cloth' },
  { de: 'Eimer', en: 'Bucket' },
  { de: 'Wischmopp', en: 'Mop' },
  { de: 'Kehrschaufel', en: 'Dustpan' },
  { de: 'Klobürste', en: 'Toilet brush' },
  { de: 'Waschbecken', en: 'Sink' },
  { de: 'Wasserhahn', en: 'Faucet' },
  { de: 'Heizung', en: 'Heater' },
  { de: 'Ventilator', en: 'Fan' },
  { de: 'Klimaanlage', en: 'Air conditioning' },
  { de: 'Rauchmelder', en: 'Smoke detector' },
  { de: 'Router', en: 'Wi-Fi router' },
  { de: 'Laptop', en: 'Laptop' },
  { de: 'Tastatur', en: 'Keyboard' },
  { de: 'Computermaus', en: 'Computer mouse' },
  { de: 'Kopfhörer', en: 'Headphones' },
  { de: 'Drucker', en: 'Printer' },
  { de: 'Selfie', en: 'Selfie' },
  { de: 'Videoanruf', en: 'Video call' },
  { de: 'Sprachnachricht', en: 'Voice message' },
  { de: 'Passwort', en: 'Password' },
  { de: 'Kreditkarte', en: 'Credit card' },
  { de: 'Geldautomat', en: 'ATM' },
  { de: 'Kleingeld', en: 'Loose change' },
  { de: 'Sparschwein', en: 'Piggy bank' },
  { de: 'Zeitung', en: 'Newspaper' },
  { de: 'Lesezeichen', en: 'Bookmark' },
  { de: 'Puzzle', en: 'Jigsaw puzzle' },
  { de: 'Brettspiel', en: 'Board game' },
  { de: 'Spielkarten', en: 'Playing cards' },
  { de: 'Würfel', en: 'Dice' },
  { de: 'Luftballon', en: 'Balloon' },
  { de: 'Geschenkpapier', en: 'Wrapping paper' },
  { de: 'Geburtstagskuchen', en: 'Birthday cake' },
  { de: 'Fotoalbum', en: 'Photo album' },
  { de: 'Bilderrahmen', en: 'Picture frame' },
  { de: 'Pinnwand', en: 'Bulletin board' },
  { de: 'Joggen', en: 'Jogging' },
  { de: 'Spazierengehen', en: 'Going for a walk' },
  { de: 'Gassi gehen', en: 'Walking the dog' },
  { de: 'Hängematte', en: 'Hammock' },
  { de: 'Sonnencreme', en: 'Sunscreen' },
  { de: 'Picknick', en: 'Picnic' },
  { de: 'Nachttisch', en: 'Nightstand' },
  { de: 'Matratze', en: 'Mattress' },
  { de: 'Schnuller', en: 'Pacifier' },
  { de: 'Kinderwagen', en: 'Stroller' },
  { de: 'Babyphone', en: 'Baby monitor' },
  { de: 'Zahnseide', en: 'Dental floss' },
  { de: 'Nagellack', en: 'Nail polish' },
  { de: 'Sicherheitsnadel', en: 'Safety pin' },
  { de: 'Knopf', en: 'Button' },
];
