import type { HeadsUpSeed } from './types';

export const foodWords: HeadsUpSeed[] = [
  { de: 'Currywurst', en: 'Currywurst' },
  { de: 'Sushi', en: 'Sushi' },
  { de: 'Brezel', en: 'Pretzel' },
  { de: 'Pizza', en: 'Pizza' },
  { de: 'Spaghetti', en: 'Spaghetti' },
  { de: 'Lasagne', en: 'Lasagna' },
  { de: 'Hamburger', en: 'Hamburger' },
  { de: 'Pommes', en: 'Fries' },
  { de: 'Döner', en: 'Doner Kebab' },
  { de: 'Schnitzel', en: 'Schnitzel' },
  { de: 'Bratwurst', en: 'Bratwurst' },
  { de: 'Sauerkraut', en: 'Sauerkraut' },
  { de: 'Kartoffelsalat', en: 'Potato Salad' },
  { de: 'Leberkäse', en: 'Bavarian Meatloaf' },
  { de: 'Weißwurst', en: 'White Sausage' },
  { de: 'Käsespätzle', en: 'Cheese Spätzle' },
  { de: 'Maultaschen', en: 'Maultaschen' },
  { de: 'Rinderroulade', en: 'Beef Roulade' },
  { de: 'Schweinebraten', en: 'Roast Pork' },
  { de: 'Knödel', en: 'Dumplings' },
  { de: 'Eisbein', en: 'Pork Knuckle' },
  { de: 'Frikadelle', en: 'Meat Patty' },
  { de: 'Reibekuchen', en: 'Potato Pancake' },
  { de: 'Rührei', en: 'Scrambled Eggs' },
  { de: 'Spiegelei', en: 'Fried Egg' },
  { de: 'Pfannkuchen', en: 'Pancake' },
  { de: 'Waffel', en: 'Waffle' },
  { de: 'Croissant', en: 'Croissant' },
  { de: 'Brötchen', en: 'Bread Roll' },
  { de: 'Toast', en: 'Toast' },
  { de: 'Müsli', en: 'Muesli' },
  { de: 'Cornflakes', en: 'Cornflakes' },
  { de: 'Haferbrei', en: 'Porridge' },
  { de: 'Joghurt', en: 'Yogurt' },
  { de: 'Honig', en: 'Honey' },
  { de: 'Marmelade', en: 'Jam' },
  { de: 'Nutella', en: 'Nutella' },
  { de: 'Butter', en: 'Butter' },
  { de: 'Käse', en: 'Cheese' },
  { de: 'Salami', en: 'Salami' },
  { de: 'Schinken', en: 'Ham' },
  { de: 'Speck', en: 'Bacon' },
  { de: 'Avocado', en: 'Avocado' },
  { de: 'Tomate', en: 'Tomato' },
  { de: 'Gurke', en: 'Cucumber' },
  { de: 'Karotte', en: 'Carrot' },
  { de: 'Kartoffel', en: 'Potato' },
  { de: 'Zwiebel', en: 'Onion' },
  { de: 'Knoblauch', en: 'Garlic' },
  { de: 'Paprika', en: 'Bell Pepper' },
  { de: 'Brokkoli', en: 'Broccoli' },
  { de: 'Blumenkohl', en: 'Cauliflower' },
  { de: 'Spinat', en: 'Spinach' },
  { de: 'Spargel', en: 'Asparagus' },
  { de: 'Pilz', en: 'Mushroom' },
  { de: 'Mais', en: 'Corn' },
  { de: 'Erbsen', en: 'Peas' },
  { de: 'Kürbis', en: 'Pumpkin' },
  { de: 'Aubergine', en: 'Eggplant' },
  { de: 'Zucchini', en: 'Zucchini' },
  { de: 'Salat', en: 'Salad' },
  { de: 'Radieschen', en: 'Radish' },
  { de: 'Apfel', en: 'Apple' },
  { de: 'Banane', en: 'Banana' },
  { de: 'Erdbeere', en: 'Strawberry' },
  { de: 'Kirsche', en: 'Cherry' },
  { de: 'Wassermelone', en: 'Watermelon' },
  { de: 'Ananas', en: 'Pineapple' },
  { de: 'Zitrone', en: 'Lemon' },
  { de: 'Orange', en: 'Orange' },
  { de: 'Weintrauben', en: 'Grapes' },
  { de: 'Mango', en: 'Mango' },
  { de: 'Kiwi', en: 'Kiwi' },
  { de: 'Pfirsich', en: 'Peach' },
  { de: 'Birne', en: 'Pear' },
  { de: 'Kokosnuss', en: 'Coconut' },
  { de: 'Heidelbeeren', en: 'Blueberries' },
  { de: 'Himbeere', en: 'Raspberry' },
  { de: 'Pflaume', en: 'Plum' },
  { de: 'Granatapfel', en: 'Pomegranate' },
  { de: 'Reis', en: 'Rice' },
  { de: 'Nudeln', en: 'Pasta' },
  { de: 'Brot', en: 'Bread' },
  { de: 'Mehl', en: 'Flour' },
  { de: 'Zucker', en: 'Sugar' },
  { de: 'Salz', en: 'Salt' },
  { de: 'Pfeffer', en: 'Black Pepper' },
  { de: 'Senf', en: 'Mustard' },
  { de: 'Ketchup', en: 'Ketchup' },
  { de: 'Mayonnaise', en: 'Mayonnaise' },
  { de: 'Essig', en: 'Vinegar' },
  { de: 'Olivenöl', en: 'Olive Oil' },
  { de: 'Zimt', en: 'Cinnamon' },
  { de: 'Ingwer', en: 'Ginger' },
  { de: 'Hähnchen', en: 'Chicken' },
  { de: 'Steak', en: 'Steak' },
  { de: 'Lachs', en: 'Salmon' },
  { de: 'Thunfisch', en: 'Tuna' },
  { de: 'Garnelen', en: 'Shrimp' },
  { de: 'Muscheln', en: 'Mussels' },
  { de: 'Tintenfisch', en: 'Squid' },
  { de: 'Fischstäbchen', en: 'Fish Sticks' },
  { de: 'Hummer', en: 'Lobster' },
  { de: 'Tofu', en: 'Tofu' },
  { de: 'Hot Dog', en: 'Hot Dog' },
  { de: 'Tacos', en: 'Tacos' },
  { de: 'Burrito', en: 'Burrito' },
  { de: 'Nachos', en: 'Nachos' },
  { de: 'Paella', en: 'Paella' },
  { de: 'Risotto', en: 'Risotto' },
  { de: 'Ramen', en: 'Ramen' },
  { de: 'Frühlingsrolle', en: 'Spring Roll' },
  { de: 'Gyros', en: 'Gyros' },
  { de: 'Falafel', en: 'Falafel' },
  { de: 'Hummus', en: 'Hummus' },
  { de: 'Couscous', en: 'Couscous' },
  { de: 'Dim Sum', en: 'Dim Sum' },
  { de: 'Pekingente', en: 'Peking Duck' },
  { de: 'Fish and Chips', en: 'Fish and Chips' },
  { de: 'Bagel', en: 'Bagel' },
  { de: 'Sandwich', en: 'Sandwich' },
  { de: 'Wrap', en: 'Wrap' },
  { de: 'Quiche', en: 'Quiche' },
  { de: 'Flammkuchen', en: 'Tarte Flambée' },
  { de: 'Fondue', en: 'Fondue' },
  { de: 'Raclette', en: 'Raclette' },
  { de: 'Gulasch', en: 'Goulash' },
  { de: 'Chili con Carne', en: 'Chili con Carne' },
  { de: 'Tomatensuppe', en: 'Tomato Soup' },
  { de: 'Linseneintopf', en: 'Lentil Stew' },
  { de: 'Kaiserschmarrn', en: 'Kaiserschmarrn' },
  { de: 'Apfelstrudel', en: 'Apple Strudel' },
  { de: 'Schwarzwälder Kirschtorte', en: 'Black Forest Cake' },
  { de: 'Käsekuchen', en: 'Cheesecake' },
  { de: 'Tiramisu', en: 'Tiramisu' },
  { de: 'Pudding', en: 'Pudding' },
  { de: 'Eis', en: 'Ice Cream' },
  { de: 'Schokolade', en: 'Chocolate' },
  { de: 'Muffin', en: 'Muffin' },
  { de: 'Donut', en: 'Donut' },
  { de: 'Brownie', en: 'Brownie' },
  { de: 'Keks', en: 'Cookie' },
  { de: 'Lebkuchen', en: 'Gingerbread' },
  { de: 'Stollen', en: 'Stollen' },
  { de: 'Zuckerwatte', en: 'Cotton Candy' },
  { de: 'Gummibärchen', en: 'Gummy Bears' },
  { de: 'Lakritz', en: 'Licorice' },
  { de: 'Lutscher', en: 'Lollipop' },
  { de: 'Kaugummi', en: 'Chewing Gum' },
  { de: 'Popcorn', en: 'Popcorn' },
  { de: 'Chips', en: 'Potato Chips' },
  { de: 'Erdnüsse', en: 'Peanuts' },
  { de: 'Gebrannte Mandeln', en: 'Candied Almonds' },
  { de: 'Crêpe', en: 'Crêpe' },
  { de: 'Macarons', en: 'Macarons' },
  { de: 'Marshmallow', en: 'Marshmallow' },
  { de: 'Milchshake', en: 'Milkshake' },
  { de: 'Kaffee', en: 'Coffee' },
  { de: 'Tee', en: 'Tea' },
  { de: 'Cappuccino', en: 'Cappuccino' },
  { de: 'Espresso', en: 'Espresso' },
  { de: 'Limonade', en: 'Lemonade' },
  { de: 'Cola', en: 'Cola' },
  { de: 'Smoothie', en: 'Smoothie' },
  { de: 'Mineralwasser', en: 'Sparkling Water' },
  { de: 'Milch', en: 'Milk' },
  { de: 'Bier', en: 'Beer' },
  { de: 'Glühwein', en: 'Mulled Wine' },
  { de: 'Champagner', en: 'Champagne' },
  { de: 'Cocktail', en: 'Cocktail' },
  { de: 'Mojito', en: 'Mojito' },
  { de: 'Aperol Spritz', en: 'Aperol Spritz' },
  { de: 'Gin Tonic', en: 'Gin and Tonic' },
  { de: 'Whisky', en: 'Whiskey' },
  { de: 'Wodka', en: 'Vodka' },
  { de: 'Tequila', en: 'Tequila' },
  { de: 'Radler', en: 'Shandy' },
  { de: 'Energy Drink', en: 'Energy Drink' },
  { de: 'Bubble Tea', en: 'Bubble Tea' },
  { de: 'Milchreis', en: 'Rice Pudding' },
  { de: 'Kartoffelpüree', en: 'Mashed Potatoes' },
  { de: 'Obstsalat', en: 'Fruit Salad' },
  { de: 'Pesto', en: 'Pesto' },
  { de: 'Bolognese', en: 'Bolognese' },
  { de: 'Carbonara', en: 'Carbonara' },
  { de: 'Calzone', en: 'Calzone' },
  { de: 'Ravioli', en: 'Ravioli' },
  { de: 'Gnocchi', en: 'Gnocchi' },
  { de: 'Bruschetta', en: 'Bruschetta' },
  { de: 'Mozzarella', en: 'Mozzarella' },
  { de: 'Parmesan', en: 'Parmesan' },
  { de: 'Zwiebelkuchen', en: 'Onion Tart' },
  { de: 'Sauerbraten', en: 'Sauerbraten' },
  { de: 'Fischbrötchen', en: 'Fish Sandwich' },
  { de: 'Bienenstich', en: 'Bee Sting Cake' },
  { de: 'Tzatziki', en: 'Tzatziki' },
  { de: 'Guacamole', en: 'Guacamole' },
  { de: 'Schlagsahne', en: 'Whipped Cream' },
  { de: 'Sellerie', en: 'Celery' },
  { de: 'Pistazien', en: 'Pistachios' },
];
