import type { HeadsUpSeed } from './types';

export const jobsWords: HeadsUpSeed[] = [
  { de: 'Arzt', en: 'Doctor' },
  { de: 'Zahnärztin', en: 'Dentist' },
  { de: 'Feuerwehrmann', en: 'Firefighter' },
  { de: 'Polizist', en: 'Police officer' },
  { de: 'Lehrerin', en: 'Teacher' },
  { de: 'Bäcker', en: 'Baker' },
  { de: 'Metzger', en: 'Butcher' },
  { de: 'Koch', en: 'Chef' },
  { de: 'Kellner', en: 'Waiter' },
  { de: 'Friseur', en: 'Hairdresser' },
  { de: 'Pilot', en: 'Pilot' },
  { de: 'Flugbegleiterin', en: 'Flight attendant' },
  { de: 'Krankenschwester', en: 'Nurse' },
  { de: 'Tierarzt', en: 'Vet' },
  { de: 'Anwalt', en: 'Lawyer' },
  { de: 'Richter', en: 'Judge' },
  { de: 'Bauarbeiter', en: 'Construction worker' },
  { de: 'Elektriker', en: 'Electrician' },
  { de: 'Klempner', en: 'Plumber' },
  { de: 'Schreiner', en: 'Carpenter' },
  { de: 'Maler', en: 'Painter' },
  { de: 'Dachdecker', en: 'Roofer' },
  { de: 'Mechaniker', en: 'Mechanic' },
  { de: 'Busfahrer', en: 'Bus driver' },
  { de: 'Taxifahrer', en: 'Taxi driver' },
  { de: 'Lkw-Fahrer', en: 'Truck driver' },
  { de: 'Lokführer', en: 'Train driver' },
  { de: 'Postbote', en: 'Mail carrier' },
  { de: 'Bauer', en: 'Farmer' },
  { de: 'Gärtner', en: 'Gardener' },
  { de: 'Fischer', en: 'Fisherman' },
  { de: 'Förster', en: 'Forest ranger' },
  { de: 'Jäger', en: 'Hunter' },
  { de: 'Soldat', en: 'Soldier' },
  { de: 'Astronaut', en: 'Astronaut' },
  { de: 'Wissenschaftler', en: 'Scientist' },
  { de: 'Programmierer', en: 'Programmer' },
  { de: 'Influencer', en: 'Influencer' },
  { de: 'YouTuber', en: 'YouTuber' },
  { de: 'Sänger', en: 'Singer' },
  { de: 'Schauspielerin', en: 'Actress' },
  { de: 'DJ', en: 'DJ' },
  { de: 'Tänzerin', en: 'Dancer' },
  { de: 'Fotograf', en: 'Photographer' },
  { de: 'Journalist', en: 'Journalist' },
  { de: 'Nachrichtensprecher', en: 'News anchor' },
  { de: 'Moderator', en: 'TV host' },
  { de: 'Model', en: 'Model' },
  { de: 'Modedesignerin', en: 'Fashion designer' },
  { de: 'Architekt', en: 'Architect' },
  { de: 'Ingenieur', en: 'Engineer' },
  { de: 'Apotheker', en: 'Pharmacist' },
  { de: 'Psychologe', en: 'Psychologist' },
  { de: 'Chirurg', en: 'Surgeon' },
  { de: 'Hebamme', en: 'Midwife' },
  { de: 'Sanitäter', en: 'Paramedic' },
  { de: 'Bademeister', en: 'Lifeguard' },
  { de: 'Bibliothekarin', en: 'Librarian' },
  { de: 'Kassiererin', en: 'Cashier' },
  { de: 'Verkäufer', en: 'Salesperson' },
  { de: 'Immobilienmakler', en: 'Real estate agent' },
  { de: 'Banker', en: 'Banker' },
  { de: 'Steuerberater', en: 'Tax advisor' },
  { de: 'Buchhalter', en: 'Accountant' },
  { de: 'Sekretärin', en: 'Secretary' },
  { de: 'Hausmeister', en: 'Janitor' },
  { de: 'Putzfrau', en: 'Cleaning lady' },
  { de: 'Müllmann', en: 'Garbage collector' },
  { de: 'Schornsteinfeger', en: 'Chimney sweep' },
  { de: 'Clown', en: 'Clown' },
  { de: 'Zauberer', en: 'Magician' },
  { de: 'Pfarrer', en: 'Priest' },
  { de: 'Nonne', en: 'Nun' },
  { de: 'Papst', en: 'Pope' },
  { de: 'König', en: 'King' },
  { de: 'Bürgermeister', en: 'Mayor' },
  { de: 'Bundeskanzler', en: 'Chancellor' },
  { de: 'Präsident', en: 'President' },
  { de: 'Politiker', en: 'Politician' },
  { de: 'Detektiv', en: 'Detective' },
  { de: 'Spion', en: 'Spy' },
  { de: 'Türsteher', en: 'Bouncer' },
  { de: 'Bodyguard', en: 'Bodyguard' },
  { de: 'Barkeeper', en: 'Bartender' },
  { de: 'Sommelier', en: 'Sommelier' },
  { de: 'Konditor', en: 'Pastry chef' },
  { de: 'Fußballspieler', en: 'Footballer' },
  { de: 'Schiedsrichter', en: 'Referee' },
  { de: 'Trainer', en: 'Coach' },
  { de: 'Tennisspieler', en: 'Tennis player' },
  { de: 'Rennfahrer', en: 'Racing driver' },
  { de: 'Jockey', en: 'Jockey' },
  { de: 'Boxer', en: 'Boxer' },
  { de: 'Kapitän', en: 'Ship captain' },
  { de: 'Matrose', en: 'Sailor' },
  { de: 'Pirat', en: 'Pirate' },
  { de: 'Cowboy', en: 'Cowboy' },
  { de: 'Ritter', en: 'Knight' },
  { de: 'Tätowierer', en: 'Tattoo artist' },
  { de: 'Kosmetikerin', en: 'Beautician' },
  { de: 'Nageldesignerin', en: 'Nail technician' },
  { de: 'Masseur', en: 'Massage therapist' },
  { de: 'Physiotherapeut', en: 'Physiotherapist' },
  { de: 'Optiker', en: 'Optician' },
  { de: 'Augenarzt', en: 'Eye doctor' },
  { de: 'Schneider', en: 'Tailor' },
  { de: 'Schuster', en: 'Shoemaker' },
  { de: 'Goldschmied', en: 'Goldsmith' },
  { de: 'Uhrmacher', en: 'Watchmaker' },
  { de: 'Schmied', en: 'Blacksmith' },
  { de: 'Bildhauer', en: 'Sculptor' },
  { de: 'Künstler', en: 'Artist' },
  { de: 'Schriftsteller', en: 'Writer' },
  { de: 'Dichter', en: 'Poet' },
  { de: 'Komponist', en: 'Composer' },
  { de: 'Dirigent', en: 'Conductor' },
  { de: 'Pianist', en: 'Pianist' },
  { de: 'Schlagzeuger', en: 'Drummer' },
  { de: 'Regisseur', en: 'Film director' },
  { de: 'Kameramann', en: 'Camera operator' },
  { de: 'Stuntman', en: 'Stuntman' },
  { de: 'Synchronsprecher', en: 'Voice actor' },
  { de: 'Comedian', en: 'Comedian' },
  { de: 'Rapper', en: 'Rapper' },
  { de: 'Streamer', en: 'Streamer' },
  { de: 'Profi-Gamer', en: 'Pro gamer' },
  { de: 'Blogger', en: 'Blogger' },
  { de: 'Hacker', en: 'Hacker' },
  { de: 'Webdesigner', en: 'Web designer' },
  { de: 'Erzieherin', en: 'Kindergarten teacher' },
  { de: 'Babysitter', en: 'Babysitter' },
  { de: 'Au-pair', en: 'Au pair' },
  { de: 'Professor', en: 'Professor' },
  { de: 'Hausfrau', en: 'Housewife' },
  { de: 'Butler', en: 'Butler' },
  { de: 'Zimmermädchen', en: 'Housekeeper' },
  { de: 'Rezeptionist', en: 'Receptionist' },
  { de: 'Concierge', en: 'Concierge' },
  { de: 'Reiseleiter', en: 'Tour guide' },
  { de: 'Animateur', en: 'Holiday entertainer' },
  { de: 'Fluglotse', en: 'Air traffic controller' },
  { de: 'Zugbegleiter', en: 'Train conductor' },
  { de: 'Kranführer', en: 'Crane operator' },
  { de: 'Maurer', en: 'Bricklayer' },
  { de: 'Fliesenleger', en: 'Tiler' },
  { de: 'Schlüsseldienst', en: 'Locksmith' },
  { de: 'Imker', en: 'Beekeeper' },
  { de: 'Winzer', en: 'Winemaker' },
  { de: 'Schäfer', en: 'Shepherd' },
  { de: 'Tierpfleger', en: 'Zookeeper' },
  { de: 'Dompteur', en: 'Lion tamer' },
  { de: 'Akrobat', en: 'Acrobat' },
  { de: 'Jongleur', en: 'Juggler' },
  { de: 'Pantomime', en: 'Mime' },
  { de: 'Straßenmusiker', en: 'Street musician' },
  { de: 'Pizzabote', en: 'Pizza delivery driver' },
  { de: 'Fahrlehrer', en: 'Driving instructor' },
  { de: 'Skilehrer', en: 'Ski instructor' },
  { de: 'Bergführer', en: 'Mountain guide' },
  { de: 'Archäologe', en: 'Archaeologist' },
  { de: 'Astronom', en: 'Astronomer' },
  { de: 'Biologe', en: 'Biologist' },
  { de: 'Chemiker', en: 'Chemist' },
  { de: 'Meteorologe', en: 'Meteorologist' },
  { de: 'Erfinder', en: 'Inventor' },
  { de: 'Übersetzer', en: 'Translator' },
  { de: 'Notar', en: 'Notary' },
  { de: 'Staatsanwalt', en: 'Prosecutor' },
  { de: 'Gefängniswärter', en: 'Prison guard' },
  { de: 'Zollbeamter', en: 'Customs officer' },
  { de: 'Bestatter', en: 'Undertaker' },
  { de: 'Totengräber', en: 'Gravedigger' },
  { de: 'Kammerjäger', en: 'Exterminator' },
  { de: 'Personalerin', en: 'HR manager' },
  { de: 'Geschäftsführer', en: 'CEO' },
  { de: 'Unternehmer', en: 'Entrepreneur' },
  { de: 'Versicherungsvertreter', en: 'Insurance agent' },
  { de: 'Callcenter-Agent', en: 'Call center agent' },
  { de: 'Marktschreier', en: 'Market trader' },
  { de: 'Barista', en: 'Barista' },
  { de: 'Floristin', en: 'Florist' },
  { de: 'Klavierstimmer', en: 'Piano tuner' },
  { de: 'Fensterputzer', en: 'Window cleaner' },
  { de: 'Feuerspucker', en: 'Fire breather' },
  { de: 'Wahrsagerin', en: 'Fortune teller' },
  { de: 'Altenpfleger', en: 'Caregiver' },
  { de: 'Logopäde', en: 'Speech therapist' },
  { de: 'Heilpraktiker', en: 'Naturopath' },
  { de: 'Yogalehrerin', en: 'Yoga teacher' },
  { de: 'Hochzeitsplaner', en: 'Wedding planner' },
  { de: 'Mönch', en: 'Monk' },
  { de: 'Zeitungsausträger', en: 'Paperboy' },
  { de: 'Fahrradkurier', en: 'Bike courier' },
  { de: 'Taucher', en: 'Diver' },
  { de: 'Holzfäller', en: 'Lumberjack' },
  { de: 'Bergmann', en: 'Miner' },
  { de: 'Sprengmeister', en: 'Demolition expert' },
  { de: 'Tankwart', en: 'Gas station attendant' },
  { de: 'Abschleppdienst', en: 'Tow truck driver' },
  { de: 'Social-Media-Manager', en: 'Social media manager' },
];
