import type { HeadsUpSeed } from './types';

export const moviesWords: HeadsUpSeed[] = [
  { de: 'Der König der Löwen', en: 'The Lion King' },
  { de: 'Titanic', en: 'Titanic' },
  { de: 'Harry Potter', en: 'Harry Potter' },
  { de: 'Star Wars', en: 'Star Wars' },
  { de: 'Der Herr der Ringe', en: 'The Lord of the Rings' },
  { de: 'Findet Nemo', en: 'Finding Nemo' },
  { de: 'Die Eiskönigin', en: 'Frozen' },
  { de: 'Shrek', en: 'Shrek' },
  { de: 'Toy Story', en: 'Toy Story' },
  { de: 'Jurassic Park', en: 'Jurassic Park' },
  { de: 'Der weiße Hai', en: 'Jaws' },
  { de: 'E.T.', en: 'E.T.' },
  { de: 'Zurück in die Zukunft', en: 'Back to the Future' },
  { de: 'Forrest Gump', en: 'Forrest Gump' },
  { de: 'Der Pate', en: 'The Godfather' },
  { de: 'Matrix', en: 'The Matrix' },
  { de: 'Avatar', en: 'Avatar' },
  { de: 'Fluch der Karibik', en: 'Pirates of the Caribbean' },
  { de: 'Jack Sparrow', en: 'Jack Sparrow' },
  { de: 'Batman', en: 'Batman' },
  { de: 'Spider-Man', en: 'Spider-Man' },
  { de: 'Superman', en: 'Superman' },
  { de: 'Iron Man', en: 'Iron Man' },
  { de: 'Die Avengers', en: 'The Avengers' },
  { de: 'Hulk', en: 'Hulk' },
  { de: 'Captain America', en: 'Captain America' },
  { de: 'Thor', en: 'Thor' },
  { de: 'Wonder Woman', en: 'Wonder Woman' },
  { de: 'Joker', en: 'Joker' },
  { de: 'Black Panther', en: 'Black Panther' },
  { de: 'Deadpool', en: 'Deadpool' },
  { de: 'James Bond', en: 'James Bond' },
  { de: 'Mission: Impossible', en: 'Mission: Impossible' },
  { de: 'Indiana Jones', en: 'Indiana Jones' },
  { de: 'Rocky', en: 'Rocky' },
  { de: 'Rambo', en: 'Rambo' },
  { de: 'Terminator', en: 'Terminator' },
  { de: 'Alien', en: 'Alien' },
  { de: 'Ghostbusters', en: 'Ghostbusters' },
  { de: 'Kevin allein zu Haus', en: 'Home Alone' },
  { de: 'Mary Poppins', en: 'Mary Poppins' },
  { de: 'Pinocchio', en: 'Pinocchio' },
  { de: 'Schneewittchen', en: 'Snow White' },
  { de: 'Aschenputtel', en: 'Cinderella' },
  { de: 'Dornröschen', en: 'Sleeping Beauty' },
  { de: 'Arielle, die Meerjungfrau', en: 'The Little Mermaid' },
  { de: 'Die Schöne und das Biest', en: 'Beauty and the Beast' },
  { de: 'Aladdin', en: 'Aladdin' },
  { de: 'Das Dschungelbuch', en: 'The Jungle Book' },
  { de: 'Bambi', en: 'Bambi' },
  { de: 'Dumbo', en: 'Dumbo' },
  { de: 'Mulan', en: 'Mulan' },
  { de: 'Pocahontas', en: 'Pocahontas' },
  { de: 'Tarzan', en: 'Tarzan' },
  { de: 'Rapunzel', en: 'Tangled' },
  { de: 'Vaiana', en: 'Moana' },
  { de: 'Encanto', en: 'Encanto' },
  { de: 'Coco', en: 'Coco' },
  { de: 'Oben', en: 'Up' },
  { de: 'Alles steht Kopf', en: 'Inside Out' },
  { de: 'Die Monster AG', en: 'Monsters, Inc.' },
  { de: 'Ratatouille', en: 'Ratatouille' },
  { de: 'WALL-E', en: 'WALL-E' },
  { de: 'Cars', en: 'Cars' },
  { de: 'Die Unglaublichen', en: 'The Incredibles' },
  { de: 'Ice Age', en: 'Ice Age' },
  { de: 'Madagascar', en: 'Madagascar' },
  { de: 'Minions', en: 'Minions' },
  { de: 'Kung Fu Panda', en: 'Kung Fu Panda' },
  { de: 'Zoomania', en: 'Zootopia' },
  { de: 'Die Simpsons', en: 'The Simpsons' },
  { de: 'SpongeBob', en: 'SpongeBob' },
  { de: 'Family Guy', en: 'Family Guy' },
  { de: 'South Park', en: 'South Park' },
  { de: 'Futurama', en: 'Futurama' },
  { de: 'Friends', en: 'Friends' },
  { de: 'Game of Thrones', en: 'Game of Thrones' },
  { de: 'Breaking Bad', en: 'Breaking Bad' },
  { de: 'Stranger Things', en: 'Stranger Things' },
  { de: 'The Office', en: 'The Office' },
  { de: 'How I Met Your Mother', en: 'How I Met Your Mother' },
  { de: 'The Big Bang Theory', en: 'The Big Bang Theory' },
  { de: 'Haus des Geldes', en: 'Money Heist' },
  { de: 'Squid Game', en: 'Squid Game' },
  { de: 'Die Sopranos', en: 'The Sopranos' },
  { de: 'Dr. House', en: 'House' },
  { de: 'Grey’s Anatomy', en: 'Grey’s Anatomy' },
  { de: 'Sherlock', en: 'Sherlock' },
  { de: 'Doctor Who', en: 'Doctor Who' },
  { de: 'The Walking Dead', en: 'The Walking Dead' },
  { de: 'Prison Break', en: 'Prison Break' },
  { de: 'Two and a Half Men', en: 'Two and a Half Men' },
  { de: 'Modern Family', en: 'Modern Family' },
  { de: 'The Crown', en: 'The Crown' },
  { de: 'Bridgerton', en: 'Bridgerton' },
  { de: 'Wednesday', en: 'Wednesday' },
  { de: 'Die Addams Family', en: 'The Addams Family' },
  { de: 'Baywatch', en: 'Baywatch' },
  { de: 'Knight Rider', en: 'Knight Rider' },
  { de: 'Akte X', en: 'The X-Files' },
  { de: 'Star Trek', en: 'Star Trek' },
  { de: 'Mr. Bean', en: 'Mr. Bean' },
  { de: 'Pokémon', en: 'Pokémon' },
  { de: 'Die Schlümpfe', en: 'The Smurfs' },
  { de: 'Biene Maja', en: 'Maya the Bee' },
  { de: 'Heidi', en: 'Heidi' },
  { de: 'Pippi Langstrumpf', en: 'Pippi Longstocking' },
  { de: 'Sesamstraße', en: 'Sesame Street' },
  { de: 'Die Muppets', en: 'The Muppets' },
  { de: 'Scooby-Doo', en: 'Scooby-Doo' },
  { de: 'Tom und Jerry', en: 'Tom and Jerry' },
  { de: 'Micky Maus', en: 'Mickey Mouse' },
  { de: 'Donald Duck', en: 'Donald Duck' },
  { de: 'Bugs Bunny', en: 'Bugs Bunny' },
  { de: 'Garfield', en: 'Garfield' },
  { de: 'Paw Patrol', en: 'Paw Patrol' },
  { de: 'Peppa Wutz', en: 'Peppa Pig' },
  { de: 'Der Zauberer von Oz', en: 'The Wizard of Oz' },
  { de: 'Vom Winde verweht', en: 'Gone with the Wind' },
  { de: 'Casablanca', en: 'Casablanca' },
  { de: 'Psycho', en: 'Psycho' },
  { de: 'Der Exorzist', en: 'The Exorcist' },
  { de: 'Es', en: 'It' },
  { de: 'Shining', en: 'The Shining' },
  { de: 'Das Schweigen der Lämmer', en: 'The Silence of the Lambs' },
  { de: 'Pulp Fiction', en: 'Pulp Fiction' },
  { de: 'Kill Bill', en: 'Kill Bill' },
  { de: 'Fight Club', en: 'Fight Club' },
  { de: 'Inception', en: 'Inception' },
  { de: 'Interstellar', en: 'Interstellar' },
  { de: 'Gladiator', en: 'Gladiator' },
  { de: 'Braveheart', en: 'Braveheart' },
  { de: 'Top Gun', en: 'Top Gun' },
  { de: 'Dirty Dancing', en: 'Dirty Dancing' },
  { de: 'Grease', en: 'Grease' },
  { de: 'Pretty Woman', en: 'Pretty Woman' },
  { de: 'Notting Hill', en: 'Notting Hill' },
  { de: 'Mamma Mia!', en: 'Mamma Mia!' },
  { de: 'Barbie', en: 'Barbie' },
  { de: 'Oppenheimer', en: 'Oppenheimer' },
  { de: 'Fast & Furious', en: 'Fast & Furious' },
  { de: 'Transformers', en: 'Transformers' },
  { de: 'Godzilla', en: 'Godzilla' },
  { de: 'King Kong', en: 'King Kong' },
  { de: 'Dracula', en: 'Dracula' },
  { de: 'Frankenstein', en: 'Frankenstein' },
  { de: 'Twilight', en: 'Twilight' },
  { de: 'Die Tribute von Panem', en: 'The Hunger Games' },
  { de: 'Der Hobbit', en: 'The Hobbit' },
  { de: 'Gandalf', en: 'Gandalf' },
  { de: 'Gollum', en: 'Gollum' },
  { de: 'Darth Vader', en: 'Darth Vader' },
  { de: 'Yoda', en: 'Yoda' },
  { de: 'Chewbacca', en: 'Chewbacca' },
  { de: 'Dumbledore', en: 'Dumbledore' },
  { de: 'Voldemort', en: 'Voldemort' },
  { de: 'Hagrid', en: 'Hagrid' },
  { de: 'Willy Wonka', en: 'Willy Wonka' },
  { de: 'Der Grinch', en: 'The Grinch' },
  { de: 'Men in Black', en: 'Men in Black' },
  { de: 'Die Truman Show', en: 'The Truman Show' },
  { de: 'Der Teufel trägt Prada', en: 'The Devil Wears Prada' },
  { de: 'Natürlich blond', en: 'Legally Blonde' },
  { de: 'Mean Girls', en: 'Mean Girls' },
  { de: 'Hangover', en: 'The Hangover' },
  { de: 'Ziemlich beste Freunde', en: 'The Intouchables' },
  { de: 'Das Leben des Brian', en: 'Life of Brian' },
  { de: 'Die Mumie', en: 'The Mummy' },
  { de: 'Jumanji', en: 'Jumanji' },
  { de: 'Nachts im Museum', en: 'Night at the Museum' },
  { de: 'Dune', en: 'Dune' },
  { de: 'Mad Max', en: 'Mad Max' },
  { de: 'Schindlers Liste', en: 'Schindler’s List' },
  { de: 'Der Soldat James Ryan', en: 'Saving Private Ryan' },
  { de: 'Cast Away', en: 'Cast Away' },
  { de: 'The Wolf of Wall Street', en: 'The Wolf of Wall Street' },
  { de: 'Catch Me If You Can', en: 'Catch Me If You Can' },
  { de: 'La La Land', en: 'La La Land' },
  { de: 'Der Prinz aus Zamunda', en: 'Coming to America' },
  { de: 'Ninja Turtles', en: 'Ninja Turtles' },
  { de: 'Power Rangers', en: 'Power Rangers' },
  { de: 'Sailor Moon', en: 'Sailor Moon' },
  { de: 'Dragon Ball', en: 'Dragon Ball' },
  { de: 'One Piece', en: 'One Piece' },
  { de: 'Naruto', en: 'Naruto' },
  { de: 'Asterix und Obelix', en: 'Asterix and Obelix' },
  { de: 'Tim und Struppi', en: 'Tintin' },
  { de: 'Shaun das Schaf', en: 'Shaun the Sheep' },
  { de: 'Winnie Puuh', en: 'Winnie the Pooh' },
  { de: 'Paddington', en: 'Paddington' },
  { de: 'Olaf', en: 'Olaf' },
  { de: 'Buzz Lightyear', en: 'Buzz Lightyear' },
  { de: 'Rick and Morty', en: 'Rick and Morty' },
  { de: 'Peaky Blinders', en: 'Peaky Blinders' },
  { de: 'Dexter', en: 'Dexter' },
  { de: 'Lost', en: 'Lost' },
  { de: 'The Mandalorian', en: 'The Mandalorian' },
  { de: 'Sex and the City', en: 'Sex and the City' },
  { de: 'Gilmore Girls', en: 'Gilmore Girls' },
  { de: 'Scrubs', en: 'Scrubs' },
];
