import type { HeadsUpSeed } from './types';

export const musicWords: HeadsUpSeed[] = [
  { de: 'The Beatles', en: 'The Beatles' },
  { de: 'The Rolling Stones', en: 'The Rolling Stones' },
  { de: 'Queen', en: 'Queen' },
  { de: 'ABBA', en: 'ABBA' },
  { de: 'Michael Jackson', en: 'Michael Jackson' },
  { de: 'Madonna', en: 'Madonna' },
  { de: 'Elvis Presley', en: 'Elvis Presley' },
  { de: 'Taylor Swift', en: 'Taylor Swift' },
  { de: 'Beyoncé', en: 'Beyoncé' },
  { de: 'Rihanna', en: 'Rihanna' },
  { de: 'Ed Sheeran', en: 'Ed Sheeran' },
  { de: 'Adele', en: 'Adele' },
  { de: 'Lady Gaga', en: 'Lady Gaga' },
  { de: 'Eminem', en: 'Eminem' },
  { de: 'Coldplay', en: 'Coldplay' },
  { de: 'Rammstein', en: 'Rammstein' },
  { de: 'Die Toten Hosen', en: 'Die Toten Hosen' },
  { de: 'Die Ärzte', en: 'Die Ärzte' },
  { de: 'Helene Fischer', en: 'Helene Fischer' },
  { de: 'Herbert Grönemeyer', en: 'Herbert Grönemeyer' },
  { de: 'Udo Lindenberg', en: 'Udo Lindenberg' },
  { de: 'Nena', en: 'Nena' },
  { de: 'Mozart', en: 'Mozart' },
  { de: 'Beethoven', en: 'Beethoven' },
  { de: 'Bach', en: 'Bach' },
  { de: 'Chopin', en: 'Chopin' },
  { de: 'Freddie Mercury', en: 'Freddie Mercury' },
  { de: 'David Bowie', en: 'David Bowie' },
  { de: 'Elton John', en: 'Elton John' },
  { de: 'Bob Marley', en: 'Bob Marley' },
  { de: 'Bob Dylan', en: 'Bob Dylan' },
  { de: 'Nirvana', en: 'Nirvana' },
  { de: 'Metallica', en: 'Metallica' },
  { de: 'AC/DC', en: 'AC/DC' },
  { de: 'Pink Floyd', en: 'Pink Floyd' },
  { de: 'Led Zeppelin', en: 'Led Zeppelin' },
  { de: 'U2', en: 'U2' },
  { de: 'Britney Spears', en: 'Britney Spears' },
  { de: 'Justin Bieber', en: 'Justin Bieber' },
  { de: 'Shakira', en: 'Shakira' },
  { de: 'Bruno Mars', en: 'Bruno Mars' },
  { de: 'Billie Eilish', en: 'Billie Eilish' },
  { de: 'Ariana Grande', en: 'Ariana Grande' },
  { de: 'Snoop Dogg', en: 'Snoop Dogg' },
  { de: 'Drake', en: 'Drake' },
  { de: 'Tokio Hotel', en: 'Tokio Hotel' },
  { de: 'Scooter', en: 'Scooter' },
  { de: 'Kraftwerk', en: 'Kraftwerk' },
  { de: 'Peter Maffay', en: 'Peter Maffay' },
  { de: 'DJ Ötzi', en: 'DJ Ötzi' },
  { de: 'Mark Forster', en: 'Mark Forster' },
  { de: 'Cro', en: 'Cro' },
  { de: 'Sido', en: 'Sido' },
  { de: 'Lena Meyer-Landrut', en: 'Lena Meyer-Landrut' },
  { de: 'Modern Talking', en: 'Modern Talking' },
  { de: 'Falco', en: 'Falco' },
  { de: 'Whitney Houston', en: 'Whitney Houston' },
  { de: 'Tina Turner', en: 'Tina Turner' },
  { de: 'Frank Sinatra', en: 'Frank Sinatra' },
  { de: 'Johnny Cash', en: 'Johnny Cash' },
  { de: 'Dolly Parton', en: 'Dolly Parton' },
  { de: 'Cher', en: 'Cher' },
  { de: 'Prince', en: 'Prince' },
  { de: 'Stevie Wonder', en: 'Stevie Wonder' },
  { de: 'Louis Armstrong', en: 'Louis Armstrong' },
  { de: 'Jimi Hendrix', en: 'Jimi Hendrix' },
  { de: 'Kurt Cobain', en: 'Kurt Cobain' },
  { de: 'Mick Jagger', en: 'Mick Jagger' },
  { de: 'John Lennon', en: 'John Lennon' },
  { de: 'Paul McCartney', en: 'Paul McCartney' },
  { de: 'Dua Lipa', en: 'Dua Lipa' },
  { de: 'The Weeknd', en: 'The Weeknd' },
  { de: 'Harry Styles', en: 'Harry Styles' },
  { de: 'One Direction', en: 'One Direction' },
  { de: 'Backstreet Boys', en: 'Backstreet Boys' },
  { de: 'Spice Girls', en: 'Spice Girls' },
  { de: 'Daft Punk', en: 'Daft Punk' },
  { de: 'David Guetta', en: 'David Guetta' },
  { de: 'Avicii', en: 'Avicii' },
  { de: 'Linkin Park', en: 'Linkin Park' },
  { de: 'Green Day', en: 'Green Day' },
  { de: 'Red Hot Chili Peppers', en: 'Red Hot Chili Peppers' },
  { de: 'Bon Jovi', en: 'Bon Jovi' },
  { de: 'Guns N’ Roses', en: 'Guns N’ Roses' },
  { de: 'Robbie Williams', en: 'Robbie Williams' },
  { de: 'Phil Collins', en: 'Phil Collins' },
  { de: 'Sting', en: 'Sting' },
  { de: 'Céline Dion', en: 'Céline Dion' },
  { de: 'Mariah Carey', en: 'Mariah Carey' },
  { de: 'Amy Winehouse', en: 'Amy Winehouse' },
  { de: 'BTS', en: 'BTS' },
  { de: 'Sarah Connor', en: 'Sarah Connor' },
  { de: 'Silbermond', en: 'Silbermond' },
  { de: 'Kylie Minogue', en: 'Kylie Minogue' },
  { de: 'Katy Perry', en: 'Katy Perry' },
  { de: 'Miley Cyrus', en: 'Miley Cyrus' },
  { de: 'Justin Timberlake', en: 'Justin Timberlake' },
  { de: 'Bohemian Rhapsody', en: 'Bohemian Rhapsody' },
  { de: 'Atemlos durch die Nacht', en: 'Atemlos durch die Nacht' },
  { de: '99 Luftballons', en: '99 Red Balloons' },
  { de: 'Thriller', en: 'Thriller' },
  { de: 'Yesterday', en: 'Yesterday' },
  { de: 'Imagine', en: 'Imagine' },
  { de: 'Billie Jean', en: 'Billie Jean' },
  { de: 'Despacito', en: 'Despacito' },
  { de: 'Macarena', en: 'Macarena' },
  { de: 'Gangnam Style', en: 'Gangnam Style' },
  { de: 'Hallelujah', en: 'Hallelujah' },
  { de: 'Wonderwall', en: 'Wonderwall' },
  { de: 'Smells Like Teen Spirit', en: 'Smells Like Teen Spirit' },
  { de: 'Hotel California', en: 'Hotel California' },
  { de: 'Stille Nacht', en: 'Silent Night' },
  { de: 'Zum Geburtstag viel Glück', en: 'Happy Birthday to You' },
  { de: 'Ode an die Freude', en: 'Ode to Joy' },
  { de: 'Für Elise', en: 'Für Elise' },
  { de: 'Dancing Queen', en: 'Dancing Queen' },
  { de: 'Highway to Hell', en: 'Highway to Hell' },
  { de: 'We Will Rock You', en: 'We Will Rock You' },
  { de: 'Shape of You', en: 'Shape of You' },
  { de: 'Last Christmas', en: 'Last Christmas' },
  { de: 'Jingle Bells', en: 'Jingle Bells' },
  { de: 'Livin’ on a Prayer', en: 'Livin’ on a Prayer' },
  { de: 'Purple Rain', en: 'Purple Rain' },
  { de: 'Mamma Mia', en: 'Mamma Mia' },
  { de: 'Wind of Change', en: 'Wind of Change' },
  { de: 'Waterloo', en: 'Waterloo' },
  { de: 'Y.M.C.A.', en: 'Y.M.C.A.' },
  { de: 'Barbie Girl', en: 'Barbie Girl' },
  { de: 'The Final Countdown', en: 'The Final Countdown' },
  { de: 'Eye of the Tiger', en: 'Eye of the Tiger' },
  { de: 'Gitarre', en: 'Guitar' },
  { de: 'E-Gitarre', en: 'Electric guitar' },
  { de: 'Bassgitarre', en: 'Bass guitar' },
  { de: 'Klavier', en: 'Piano' },
  { de: 'Flügel', en: 'Grand piano' },
  { de: 'Schlagzeug', en: 'Drums' },
  { de: 'Geige', en: 'Violin' },
  { de: 'Cello', en: 'Cello' },
  { de: 'Kontrabass', en: 'Double bass' },
  { de: 'Harfe', en: 'Harp' },
  { de: 'Querflöte', en: 'Flute' },
  { de: 'Blockflöte', en: 'Recorder' },
  { de: 'Klarinette', en: 'Clarinet' },
  { de: 'Saxofon', en: 'Saxophone' },
  { de: 'Trompete', en: 'Trumpet' },
  { de: 'Posaune', en: 'Trombone' },
  { de: 'Tuba', en: 'Tuba' },
  { de: 'Mundharmonika', en: 'Harmonica' },
  { de: 'Akkordeon', en: 'Accordion' },
  { de: 'Dudelsack', en: 'Bagpipes' },
  { de: 'Orgel', en: 'Organ' },
  { de: 'Synthesizer', en: 'Synthesizer' },
  { de: 'Ukulele', en: 'Ukulele' },
  { de: 'Banjo', en: 'Banjo' },
  { de: 'Xylophon', en: 'Xylophone' },
  { de: 'Triangel', en: 'Triangle' },
  { de: 'Tamburin', en: 'Tambourine' },
  { de: 'Pauke', en: 'Kettledrum' },
  { de: 'Panflöte', en: 'Pan flute' },
  { de: 'Didgeridoo', en: 'Didgeridoo' },
  { de: 'Rock', en: 'Rock' },
  { de: 'Hip-Hop', en: 'Hip-hop' },
  { de: 'Jazz', en: 'Jazz' },
  { de: 'Blues', en: 'Blues' },
  { de: 'Klassische Musik', en: 'Classical music' },
  { de: 'Schlager', en: 'Schlager' },
  { de: 'Heavy Metal', en: 'Heavy metal' },
  { de: 'Punk', en: 'Punk' },
  { de: 'Reggae', en: 'Reggae' },
  { de: 'Techno', en: 'Techno' },
  { de: 'Country', en: 'Country music' },
  { de: 'Disco', en: 'Disco' },
  { de: 'Oper', en: 'Opera' },
  { de: 'Volksmusik', en: 'Folk music' },
  { de: 'K-Pop', en: 'K-pop' },
  { de: 'Musical', en: 'Musical' },
  { de: 'Konzert', en: 'Concert' },
  { de: 'Musikfestival', en: 'Music festival' },
  { de: 'Chor', en: 'Choir' },
  { de: 'Orchester', en: 'Orchestra' },
  { de: 'Dirigent', en: 'Conductor' },
  { de: 'Notenblatt', en: 'Sheet music' },
  { de: 'Violinschlüssel', en: 'Treble clef' },
  { de: 'Mikrofon', en: 'Microphone' },
  { de: 'Kopfhörer', en: 'Headphones' },
  { de: 'Schallplatte', en: 'Vinyl record' },
  { de: 'Kassette', en: 'Cassette tape' },
  { de: 'Karaoke', en: 'Karaoke' },
  { de: 'DJ', en: 'DJ' },
  { de: 'Ohrwurm', en: 'Earworm' },
  { de: 'Zugabe', en: 'Encore' },
  { de: 'Metronom', en: 'Metronome' },
  { de: 'Boyband', en: 'Boy band' },
  { de: 'Luftgitarre', en: 'Air guitar' },
  { de: 'Crowdsurfing', en: 'Crowd surfing' },
  { de: 'Eurovision Song Contest', en: 'Eurovision Song Contest' },
  { de: 'Nationalhymne', en: 'National anthem' },
  { de: 'Schlaflied', en: 'Lullaby' },
  { de: 'Straßenmusiker', en: 'Busker' },
  { de: 'Headbangen', en: 'Headbanging' },
];
