import type { HeadsUpSeed } from './types';

export const placesWords: HeadsUpSeed[] = [
  { de: 'Deutschland', en: 'Germany' },
  { de: 'Frankreich', en: 'France' },
  { de: 'Italien', en: 'Italy' },
  { de: 'Spanien', en: 'Spain' },
  { de: 'Österreich', en: 'Austria' },
  { de: 'Schweiz', en: 'Switzerland' },
  { de: 'England', en: 'England' },
  { de: 'USA', en: 'USA' },
  { de: 'Kanada', en: 'Canada' },
  { de: 'Mexiko', en: 'Mexico' },
  { de: 'Brasilien', en: 'Brazil' },
  { de: 'Argentinien', en: 'Argentina' },
  { de: 'Japan', en: 'Japan' },
  { de: 'China', en: 'China' },
  { de: 'Indien', en: 'India' },
  { de: 'Australien', en: 'Australia' },
  { de: 'Ägypten', en: 'Egypt' },
  { de: 'Russland', en: 'Russia' },
  { de: 'Griechenland', en: 'Greece' },
  { de: 'Türkei', en: 'Turkey' },
  { de: 'Schweden', en: 'Sweden' },
  { de: 'Norwegen', en: 'Norway' },
  { de: 'Island', en: 'Iceland' },
  { de: 'Irland', en: 'Ireland' },
  { de: 'Niederlande', en: 'Netherlands' },
  { de: 'Portugal', en: 'Portugal' },
  { de: 'Polen', en: 'Poland' },
  { de: 'Thailand', en: 'Thailand' },
  { de: 'Südafrika', en: 'South Africa' },
  { de: 'Neuseeland', en: 'New Zealand' },
  { de: 'Kroatien', en: 'Croatia' },
  { de: 'Jamaika', en: 'Jamaica' },
  { de: 'Kuba', en: 'Cuba' },
  { de: 'Dänemark', en: 'Denmark' },
  { de: 'Marokko', en: 'Morocco' },
  { de: 'Südkorea', en: 'South Korea' },
  { de: 'Vatikan', en: 'Vatican City' },
  { de: 'Mallorca', en: 'Mallorca' },
  { de: 'Hawaii', en: 'Hawaii' },
  { de: 'Malediven', en: 'Maldives' },
  { de: 'Sizilien', en: 'Sicily' },
  { de: 'Bali', en: 'Bali' },
  { de: 'Ibiza', en: 'Ibiza' },
  { de: 'Kreta', en: 'Crete' },
  { de: 'Antarktis', en: 'Antarctica' },
  { de: 'Grönland', en: 'Greenland' },
  { de: 'Bayern', en: 'Bavaria' },
  { de: 'Toskana', en: 'Tuscany' },
  { de: 'Kalifornien', en: 'California' },
  { de: 'Berlin', en: 'Berlin' },
  { de: 'Paris', en: 'Paris' },
  { de: 'London', en: 'London' },
  { de: 'Rom', en: 'Rome' },
  { de: 'Venedig', en: 'Venice' },
  { de: 'New York', en: 'New York' },
  { de: 'Tokio', en: 'Tokyo' },
  { de: 'Hamburg', en: 'Hamburg' },
  { de: 'München', en: 'Munich' },
  { de: 'Köln', en: 'Cologne' },
  { de: 'Wien', en: 'Vienna' },
  { de: 'Amsterdam', en: 'Amsterdam' },
  { de: 'Barcelona', en: 'Barcelona' },
  { de: 'Madrid', en: 'Madrid' },
  { de: 'Prag', en: 'Prague' },
  { de: 'Moskau', en: 'Moscow' },
  { de: 'Dubai', en: 'Dubai' },
  { de: 'Hollywood', en: 'Hollywood' },
  { de: 'Rio de Janeiro', en: 'Rio de Janeiro' },
  { de: 'Sydney', en: 'Sydney' },
  { de: 'Los Angeles', en: 'Los Angeles' },
  { de: 'Las Vegas', en: 'Las Vegas' },
  { de: 'Istanbul', en: 'Istanbul' },
  { de: 'Athen', en: 'Athens' },
  { de: 'Lissabon', en: 'Lisbon' },
  { de: 'Kopenhagen', en: 'Copenhagen' },
  { de: 'Peking', en: 'Beijing' },
  { de: 'Hongkong', en: 'Hong Kong' },
  { de: 'Singapur', en: 'Singapore' },
  { de: 'San Francisco', en: 'San Francisco' },
  { de: 'Miami', en: 'Miami' },
  { de: 'Mailand', en: 'Milan' },
  { de: 'Dublin', en: 'Dublin' },
  { de: 'Zürich', en: 'Zurich' },
  { de: 'Frankfurt', en: 'Frankfurt' },
  { de: 'Kairo', en: 'Cairo' },
  { de: 'Bangkok', en: 'Bangkok' },
  { de: 'Eiffelturm', en: 'Eiffel Tower' },
  { de: 'Kolosseum', en: 'Colosseum' },
  { de: 'Brandenburger Tor', en: 'Brandenburg Gate' },
  { de: 'Freiheitsstatue', en: 'Statue of Liberty' },
  { de: 'Big Ben', en: 'Big Ben' },
  { de: 'Chinesische Mauer', en: 'Great Wall of China' },
  { de: 'Pyramiden von Gizeh', en: 'Pyramids of Giza' },
  { de: 'Schiefer Turm von Pisa', en: 'Leaning Tower of Pisa' },
  { de: 'Taj Mahal', en: 'Taj Mahal' },
  { de: 'Kölner Dom', en: 'Cologne Cathedral' },
  { de: 'Schloss Neuschwanstein', en: 'Neuschwanstein Castle' },
  { de: 'Golden Gate Bridge', en: 'Golden Gate Bridge' },
  { de: 'Weißes Haus', en: 'White House' },
  { de: 'Oper von Sydney', en: 'Sydney Opera House' },
  { de: 'Akropolis', en: 'Acropolis' },
  { de: 'Stonehenge', en: 'Stonehenge' },
  { de: 'Machu Picchu', en: 'Machu Picchu' },
  { de: 'Christusstatue in Rio', en: 'Christ the Redeemer' },
  { de: 'Buckingham Palace', en: 'Buckingham Palace' },
  { de: 'Tower Bridge', en: 'Tower Bridge' },
  { de: 'Empire State Building', en: 'Empire State Building' },
  { de: 'Burj Khalifa', en: 'Burj Khalifa' },
  { de: 'Sagrada Família', en: 'Sagrada Família' },
  { de: 'Petersdom', en: 'St. Peter’s Basilica' },
  { de: 'Kreml', en: 'Kremlin' },
  { de: 'Louvre', en: 'Louvre' },
  { de: 'Notre-Dame', en: 'Notre-Dame' },
  { de: 'Triumphbogen', en: 'Arc de Triomphe' },
  { de: 'Berliner Mauer', en: 'Berlin Wall' },
  { de: 'Reichstag', en: 'Reichstag' },
  { de: 'Hollywood-Schriftzug', en: 'Hollywood Sign' },
  { de: 'Mount Rushmore', en: 'Mount Rushmore' },
  { de: 'Times Square', en: 'Times Square' },
  { de: 'Central Park', en: 'Central Park' },
  { de: 'Alcatraz', en: 'Alcatraz' },
  { de: 'Disneyland', en: 'Disneyland' },
  { de: 'Sphinx', en: 'Sphinx' },
  { de: 'Schloss Versailles', en: 'Palace of Versailles' },
  { de: 'Osterinsel', en: 'Easter Island' },
  { de: 'London Eye', en: 'London Eye' },
  { de: 'Elbphilharmonie', en: 'Elbphilharmonie' },
  { de: 'Berliner Fernsehturm', en: 'Berlin TV Tower' },
  { de: 'Area 51', en: 'Area 51' },
  { de: 'Nordpol', en: 'North Pole' },
  { de: 'Mount Everest', en: 'Mount Everest' },
  { de: 'Niagarafälle', en: 'Niagara Falls' },
  { de: 'Grand Canyon', en: 'Grand Canyon' },
  { de: 'Nil', en: 'Nile' },
  { de: 'Totes Meer', en: 'Dead Sea' },
  { de: 'Great Barrier Reef', en: 'Great Barrier Reef' },
  { de: 'Zugspitze', en: 'Zugspitze' },
  { de: 'Matterhorn', en: 'Matterhorn' },
  { de: 'Vesuv', en: 'Mount Vesuvius' },
  { de: 'Kilimandscharo', en: 'Kilimanjaro' },
  { de: 'Bodensee', en: 'Lake Constance' },
  { de: 'Rhein', en: 'Rhine' },
  { de: 'Ostsee', en: 'Baltic Sea' },
  { de: 'Nordsee', en: 'North Sea' },
  { de: 'Mittelmeer', en: 'Mediterranean Sea' },
  { de: 'Bermudadreieck', en: 'Bermuda Triangle' },
  { de: 'Loch Ness', en: 'Loch Ness' },
  { de: 'Fuji', en: 'Mount Fuji' },
  { de: 'Sahara', en: 'Sahara' },
  { de: 'Alpen', en: 'Alps' },
  { de: 'Schwarzwald', en: 'Black Forest' },
  { de: 'Amazonas', en: 'Amazon' },
  { de: 'Bahnhof', en: 'Train station' },
  { de: 'Flughafen', en: 'Airport' },
  { de: 'Krankenhaus', en: 'Hospital' },
  { de: 'Schule', en: 'School' },
  { de: 'Supermarkt', en: 'Supermarket' },
  { de: 'Kino', en: 'Cinema' },
  { de: 'Bäckerei', en: 'Bakery' },
  { de: 'Apotheke', en: 'Pharmacy' },
  { de: 'Friseursalon', en: 'Hair salon' },
  { de: 'Zahnarztpraxis', en: 'Dentist’s office' },
  { de: 'Bibliothek', en: 'Library' },
  { de: 'Zoo', en: 'Zoo' },
  { de: 'Freizeitpark', en: 'Theme park' },
  { de: 'Schwimmbad', en: 'Swimming pool' },
  { de: 'Fitnessstudio', en: 'Gym' },
  { de: 'Kirche', en: 'Church' },
  { de: 'Friedhof', en: 'Cemetery' },
  { de: 'Gefängnis', en: 'Prison' },
  { de: 'Polizeiwache', en: 'Police station' },
  { de: 'Feuerwache', en: 'Fire station' },
  { de: 'Rathaus', en: 'Town hall' },
  { de: 'Tankstelle', en: 'Gas station' },
  { de: 'Parkhaus', en: 'Parking garage' },
  { de: 'Kneipe', en: 'Pub' },
  { de: 'Disco', en: 'Nightclub' },
  { de: 'Hotel', en: 'Hotel' },
  { de: 'Campingplatz', en: 'Campsite' },
  { de: 'Bauernhof', en: 'Farm' },
  { de: 'Spielplatz', en: 'Playground' },
  { de: 'Fußballstadion', en: 'Football stadium' },
  { de: 'Universität', en: 'University' },
  { de: 'Kindergarten', en: 'Kindergarten' },
  { de: 'Strand', en: 'Beach' },
  { de: 'Sauna', en: 'Sauna' },
  { de: 'Waschsalon', en: 'Laundromat' },
  { de: 'Baumarkt', en: 'Hardware store' },
  { de: 'Autowaschanlage', en: 'Car wash' },
  { de: 'Bushaltestelle', en: 'Bus stop' },
  { de: 'Weihnachtsmarkt', en: 'Christmas market' },
  { de: 'Flohmarkt', en: 'Flea market' },
  { de: 'Zirkus', en: 'Circus' },
  { de: 'Casino', en: 'Casino' },
  { de: 'Leuchtturm', en: 'Lighthouse' },
  { de: 'Skigebiet', en: 'Ski resort' },
  { de: 'Bowlingbahn', en: 'Bowling alley' },
  { de: 'Eisdiele', en: 'Ice cream parlor' },
  { de: 'Dönerbude', en: 'Kebab shop' },
  { de: 'Tattoostudio', en: 'Tattoo parlor' },
];
