import type { HeadsUpSeed } from './types';

export const sexualWords: HeadsUpSeed[] = [
  { de: 'Knutschfleck', en: 'Hickey' },
  { de: 'Zungenkuss', en: 'French kiss' },
  { de: 'Dating-App', en: 'Dating app' },
  { de: 'Handschellen', en: 'Handcuffs' },
  { de: 'Kondom', en: 'Condom' },
  { de: 'Vibrator', en: 'Vibrator' },
  { de: 'Dildo', en: 'Dildo' },
  { de: 'Missionarsstellung', en: 'Missionary position' },
  { de: 'Doggystyle', en: 'Doggy style' },
  { de: 'Reiterstellung', en: 'Cowgirl' },
  { de: 'Neunundsechzig', en: 'Sixty-nine' },
  { de: 'Löffelchenstellung', en: 'Spooning' },
  { de: 'Quickie', en: 'Quickie' },
  { de: 'One-Night-Stand', en: 'One-night stand' },
  { de: 'Freundschaft Plus', en: 'Friends with benefits' },
  { de: 'Walk of Shame', en: 'Walk of shame' },
  { de: 'Morgenlatte', en: 'Morning wood' },
  { de: 'Orgasmus', en: 'Orgasm' },
  { de: 'Vorspiel', en: 'Foreplay' },
  { de: 'Dirty Talk', en: 'Dirty talk' },
  { de: 'Sexting', en: 'Sexting' },
  { de: 'Nacktfoto', en: 'Nude pic' },
  { de: 'Dickpic', en: 'Dick pic' },
  { de: 'Striptease', en: 'Striptease' },
  { de: 'Lapdance', en: 'Lap dance' },
  { de: 'Stripclub', en: 'Strip club' },
  { de: 'Stripper', en: 'Stripper' },
  { de: 'Junggesellenabschied', en: 'Bachelor party' },
  { de: 'Dessous', en: 'Lingerie' },
  { de: 'Strapse', en: 'Suspenders' },
  { de: 'Tanga', en: 'Thong' },
  { de: 'Push-up-BH', en: 'Push-up bra' },
  { de: 'Netzstrumpfhose', en: 'Fishnet tights' },
  { de: 'Latex', en: 'Latex' },
  { de: 'Peitsche', en: 'Whip' },
  { de: 'Augenbinde', en: 'Blindfold' },
  { de: 'Fesselspiele', en: 'Bondage' },
  { de: 'Rollenspiel', en: 'Role play' },
  { de: 'Safeword', en: 'Safe word' },
  { de: 'Fifty Shades of Grey', en: 'Fifty Shades of Grey' },
  { de: 'Gleitgel', en: 'Lube' },
  { de: 'Massageöl', en: 'Massage oil' },
  { de: 'Liebeskugeln', en: 'Love balls' },
  { de: 'Penisring', en: 'Cock ring' },
  { de: 'Sexshop', en: 'Sex shop' },
  { de: 'Sexspielzeug', en: 'Sex toy' },
  { de: 'Liebesschaukel', en: 'Sex swing' },
  { de: 'Pornofilm', en: 'Porn movie' },
  { de: 'Erotikroman', en: 'Erotic novel' },
  { de: 'Playboy', en: 'Playboy' },
  { de: 'OnlyFans', en: 'OnlyFans' },
  { de: 'Pornostar', en: 'Porn star' },
  { de: 'Kamasutra', en: 'Kama Sutra' },
  { de: 'Viagra', en: 'Viagra' },
  { de: 'Pille danach', en: 'Morning-after pill' },
  { de: 'Antibabypille', en: 'Birth control pill' },
  { de: 'Schwangerschaftstest', en: 'Pregnancy test' },
  { de: 'Aphrodisiakum', en: 'Aphrodisiac' },
  { de: 'Austern', en: 'Oysters' },
  { de: 'Erdbeeren mit Sahne', en: 'Strawberries and cream' },
  { de: 'Schlafzimmerblick', en: 'Bedroom eyes' },
  { de: 'Flirten', en: 'Flirting' },
  { de: 'Anmachspruch', en: 'Pickup line' },
  { de: 'Zwinkern', en: 'Winking' },
  { de: 'Erstes Date', en: 'First date' },
  { de: 'Blind Date', en: 'Blind date' },
  { de: 'Speeddating', en: 'Speed dating' },
  { de: 'Tinder', en: 'Tinder' },
  { de: 'Match', en: 'Match' },
  { de: 'Wischen nach rechts', en: 'Swipe right' },
  { de: 'Ghosting', en: 'Ghosting' },
  { de: 'Booty Call', en: 'Booty call' },
  { de: 'Netflix and Chill', en: 'Netflix and chill' },
  { de: 'Noch auf einen Kaffee?', en: 'Coffee at my place?' },
  { de: 'Knutschen', en: 'Making out' },
  { de: 'Fummeln', en: 'Groping' },
  { de: 'Petting', en: 'Petting' },
  { de: 'Rummachen', en: 'Hooking up' },
  { de: 'Kuscheln', en: 'Cuddling' },
  { de: 'Händchenhalten', en: 'Holding hands' },
  { de: 'Nackenkuss', en: 'Neck kiss' },
  { de: 'Ohrläppchen knabbern', en: 'Nibbling an earlobe' },
  { de: 'Bettgeflüster', en: 'Pillow talk' },
  { de: 'Rosenblätter auf dem Bett', en: 'Rose petals on the bed' },
  { de: 'Kerzenlicht', en: 'Candlelight' },
  { de: 'Whirlpool', en: 'Hot tub' },
  { de: 'Wasserbett', en: 'Waterbed' },
  { de: 'Seidenbettwäsche', en: 'Silk sheets' },
  { de: 'Spiegel an der Decke', en: 'Mirror on the ceiling' },
  { de: 'Stundenhotel', en: 'Love hotel' },
  { de: 'Flitterwochen', en: 'Honeymoon' },
  { de: 'Hochzeitsnacht', en: 'Wedding night' },
  { de: 'Sex am Strand', en: 'Sex on the beach' },
  { de: 'Mile High Club', en: 'Mile High Club' },
  { de: 'Sex im Auto', en: 'Car sex' },
  { de: 'Unter der Dusche', en: 'Shower sex' },
  { de: 'Dreier', en: 'Threesome' },
  { de: 'Gruppensex', en: 'Orgy' },
  { de: 'Swingerclub', en: 'Swingers club' },
  { de: 'Offene Beziehung', en: 'Open relationship' },
  { de: 'Polyamorie', en: 'Polyamory' },
  { de: 'Fernbeziehung', en: 'Long-distance relationship' },
  { de: 'Affäre', en: 'Affair' },
  { de: 'Fremdgehen', en: 'Cheating' },
  { de: 'Seitensprung', en: 'Fling' },
  { de: 'Ex-Freund', en: 'Ex-boyfriend' },
  { de: 'Versöhnungssex', en: 'Make-up sex' },
  { de: 'Trennungssex', en: 'Breakup sex' },
  { de: 'Sugar Daddy', en: 'Sugar daddy' },
  { de: 'Toyboy', en: 'Toy boy' },
  { de: 'MILF', en: 'MILF' },
  { de: 'Cougar', en: 'Cougar' },
  { de: 'Casanova', en: 'Casanova' },
  { de: 'Aufreißer', en: 'Player' },
  { de: 'Frauenheld', en: 'Ladies’ man' },
  { de: 'Femme fatale', en: 'Femme fatale' },
  { de: 'Jungfrau', en: 'Virgin' },
  { de: 'Das erste Mal', en: 'The first time' },
  { de: 'Liebesbrief', en: 'Love letter' },
  { de: 'Valentinstag', en: 'Valentine’s Day' },
  { de: 'Schmetterlinge im Bauch', en: 'Butterflies in your stomach' },
  { de: 'Verknallt', en: 'Having a crush' },
  { de: 'Schwarm', en: 'Crush' },
  { de: 'Liebe auf den ersten Blick', en: 'Love at first sight' },
  { de: 'Heiratsantrag', en: 'Marriage proposal' },
  { de: 'Pärchenurlaub', en: 'Couples’ vacation' },
  { de: 'Kopfschmerzen vortäuschen', en: 'Faking a headache' },
  { de: 'Lippenstift am Kragen', en: 'Lipstick on the collar' },
  { de: 'Erektionsprobleme', en: 'Erectile dysfunction' },
  { de: 'Zu früh kommen', en: 'Finishing too early' },
  { de: 'Morgensex', en: 'Morning sex' },
  { de: 'Geschlechtsverkehr', en: 'Intercourse' },
  { de: 'Selbstbefriedigung', en: 'Masturbation' },
  { de: 'Blowjob', en: 'Blowjob' },
  { de: 'Oralsex', en: 'Oral sex' },
  { de: 'Fußfetisch', en: 'Foot fetish' },
  { de: 'Sexpuppe', en: 'Sex doll' },
  { de: 'Domina', en: 'Dominatrix' },
  { de: 'Sklave', en: 'Submissive' },
  { de: 'Po-Klaps', en: 'Spanking' },
  { de: 'Kratzspuren', en: 'Scratch marks' },
  { de: 'Lustmolch', en: 'Horndog' },
  { de: 'Stöhnen', en: 'Moaning' },
  { de: 'Quietschendes Bett', en: 'Squeaky bed' },
  { de: 'Dünne Wände', en: 'Thin walls' },
  { de: 'Bitte nicht stören', en: 'Do not disturb' },
  { de: 'Socke an der Türklinke', en: 'Sock on the doorknob' },
  { de: 'Erwischt werden', en: 'Getting caught' },
  { de: 'Nacktbaden', en: 'Skinny dipping' },
  { de: 'FKK-Strand', en: 'Nude beach' },
  { de: 'Flitzer', en: 'Streaker' },
  { de: 'Oben ohne', en: 'Topless' },
  { de: 'Unterwäsche', en: 'Underwear' },
  { de: 'Boxershorts', en: 'Boxer shorts' },
  { de: 'Ohne Unterwäsche', en: 'Going commando' },
  { de: 'Krankenschwesterkostüm', en: 'Nurse costume' },
  { de: 'Polizistinnenkostüm', en: 'Cop costume' },
  { de: 'Hasenohren', en: 'Bunny ears' },
  { de: 'Feder', en: 'Feather' },
  { de: 'Eiswürfel', en: 'Ice cube' },
  { de: 'Schlagsahne', en: 'Whipped cream' },
  { de: 'Body Shot', en: 'Body shot' },
  { de: 'Flaschendrehen', en: 'Spin the bottle' },
  { de: 'Strip-Poker', en: 'Strip poker' },
  { de: 'Wahrheit oder Pflicht', en: 'Truth or dare' },
  { de: 'Sieben Minuten im Himmel', en: 'Seven minutes in heaven' },
  { de: 'Brüste', en: 'Boobs' },
  { de: 'Hintern', en: 'Butt' },
  { de: 'Sixpack', en: 'Six-pack' },
  { de: 'Waschbrettbauch', en: 'Washboard abs' },
  { de: 'Dekolleté', en: 'Cleavage' },
  { de: 'Brusthaare', en: 'Chest hair' },
  { de: 'Intimrasur', en: 'Bikini wax' },
  { de: 'Brustwarze', en: 'Nipple' },
  { de: 'Nippelpiercing', en: 'Nipple piercing' },
  { de: 'Arschgeweih', en: 'Tramp stamp' },
  { de: 'G-Punkt', en: 'G-spot' },
  { de: 'Erogene Zone', en: 'Erogenous zone' },
  { de: 'Kronjuwelen', en: 'Family jewels' },
  { de: 'Gurke', en: 'Cucumber' },
  { de: 'Aubergine', en: 'Eggplant' },
  { de: 'Pfirsich', en: 'Peach' },
  { de: 'Banane', en: 'Banana' },
  { de: 'Sexy Stimme', en: 'Sexy voice' },
  { de: 'Hüftschwung', en: 'Hip sway' },
  { de: 'Twerken', en: 'Twerking' },
  { de: 'Poledance', en: 'Pole dancing' },
  { de: 'Sexsymbol', en: 'Sex symbol' },
  { de: 'Hugh Hefner', en: 'Hugh Hefner' },
  { de: 'Magic Mike', en: 'Magic Mike' },
  { de: 'Rotlichtviertel', en: 'Red-light district' },
  { de: 'Kondomautomat', en: 'Condom machine' },
  { de: 'Frauenarzt', en: 'Gynecologist' },
  { de: 'Libido', en: 'Libido' },
  { de: 'Sexualkunde', en: 'Sex ed' },
  { de: 'Bienchen und Blümchen', en: 'The birds and the bees' },
  { de: 'Kissenschlacht', en: 'Pillow fight' },
  { de: 'Massage', en: 'Massage' },
  { de: 'Badewanne zu zweit', en: 'Bath for two' },
  { de: 'Liebesnest', en: 'Love nest' },
];
