import type { HeadsUpSeed } from './types';

export const sportsWords: HeadsUpSeed[] = [
  { de: 'Fußball', en: 'Football' },
  { de: 'Basketball', en: 'Basketball' },
  { de: 'Tennis', en: 'Tennis' },
  { de: 'Handball', en: 'Handball' },
  { de: 'Volleyball', en: 'Volleyball' },
  { de: 'Eishockey', en: 'Ice hockey' },
  { de: 'Golf', en: 'Golf' },
  { de: 'Boxen', en: 'Boxing' },
  { de: 'Schwimmen', en: 'Swimming' },
  { de: 'Skifahren', en: 'Skiing' },
  { de: 'Snowboarden', en: 'Snowboarding' },
  { de: 'Reiten', en: 'Horse riding' },
  { de: 'Radfahren', en: 'Cycling' },
  { de: 'Tischtennis', en: 'Table tennis' },
  { de: 'Badminton', en: 'Badminton' },
  { de: 'Rudern', en: 'Rowing' },
  { de: 'Segeln', en: 'Sailing' },
  { de: 'Surfen', en: 'Surfing' },
  { de: 'Klettern', en: 'Climbing' },
  { de: 'Fechten', en: 'Fencing' },
  { de: 'Ringen', en: 'Wrestling' },
  { de: 'Judo', en: 'Judo' },
  { de: 'Karate', en: 'Karate' },
  { de: 'Turnen', en: 'Gymnastics' },
  { de: 'Bogenschießen', en: 'Archery' },
  { de: 'Darts', en: 'Darts' },
  { de: 'Billard', en: 'Pool' },
  { de: 'Bowling', en: 'Bowling' },
  { de: 'Rugby', en: 'Rugby' },
  { de: 'American Football', en: 'American football' },
  { de: 'Baseball', en: 'Baseball' },
  { de: 'Cricket', en: 'Cricket' },
  { de: 'Formel 1', en: 'Formula 1' },
  { de: 'Marathon', en: 'Marathon' },
  { de: 'Triathlon', en: 'Triathlon' },
  { de: 'Skispringen', en: 'Ski jumping' },
  { de: 'Biathlon', en: 'Biathlon' },
  { de: 'Eiskunstlauf', en: 'Figure skating' },
  { de: 'Curling', en: 'Curling' },
  { de: 'Bobfahren', en: 'Bobsleigh' },
  { de: 'Wasserball', en: 'Water polo' },
  { de: 'Hochsprung', en: 'High jump' },
  { de: 'Weitsprung', en: 'Long jump' },
  { de: 'Stabhochsprung', en: 'Pole vault' },
  { de: 'Speerwurf', en: 'Javelin' },
  { de: 'Kugelstoßen', en: 'Shot put' },
  { de: 'Hürdenlauf', en: 'Hurdles' },
  { de: 'Sprint', en: 'Sprint' },
  { de: 'Gewichtheben', en: 'Weightlifting' },
  { de: 'Skateboarden', en: 'Skateboarding' },
  { de: 'Yoga', en: 'Yoga' },
  { de: 'Joggen', en: 'Jogging' },
  { de: 'Wandern', en: 'Hiking' },
  { de: 'Tauchen', en: 'Scuba diving' },
  { de: 'Squash', en: 'Squash' },
  { de: 'Minigolf', en: 'Mini golf' },
  { de: 'Kanufahren', en: 'Canoeing' },
  { de: 'Kitesurfen', en: 'Kitesurfing' },
  { de: 'Fallschirmspringen', en: 'Skydiving' },
  { de: 'Bungeejumping', en: 'Bungee jumping' },
  { de: 'Langlauf', en: 'Cross-country skiing' },
  { de: 'Rodeln', en: 'Sledging' },
  { de: 'Beachvolleyball', en: 'Beach volleyball' },
  { de: 'Kickboxen', en: 'Kickboxing' },
  { de: 'Schach', en: 'Chess' },
  { de: 'Tauziehen', en: 'Tug of war' },
  { de: 'Zehnkampf', en: 'Decathlon' },
  { de: 'Diskuswurf', en: 'Discus' },
  { de: 'Lionel Messi', en: 'Lionel Messi' },
  { de: 'Cristiano Ronaldo', en: 'Cristiano Ronaldo' },
  { de: 'Manuel Neuer', en: 'Manuel Neuer' },
  { de: 'Thomas Müller', en: 'Thomas Müller' },
  { de: 'Franz Beckenbauer', en: 'Franz Beckenbauer' },
  { de: 'Michael Schumacher', en: 'Michael Schumacher' },
  { de: 'Sebastian Vettel', en: 'Sebastian Vettel' },
  { de: 'Lewis Hamilton', en: 'Lewis Hamilton' },
  { de: 'Max Verstappen', en: 'Max Verstappen' },
  { de: 'Boris Becker', en: 'Boris Becker' },
  { de: 'Steffi Graf', en: 'Steffi Graf' },
  { de: 'Roger Federer', en: 'Roger Federer' },
  { de: 'Rafael Nadal', en: 'Rafael Nadal' },
  { de: 'Serena Williams', en: 'Serena Williams' },
  { de: 'Novak Djokovic', en: 'Novak Djokovic' },
  { de: 'Usain Bolt', en: 'Usain Bolt' },
  { de: 'Michael Phelps', en: 'Michael Phelps' },
  { de: 'Dirk Nowitzki', en: 'Dirk Nowitzki' },
  { de: 'LeBron James', en: 'LeBron James' },
  { de: 'Michael Jordan', en: 'Michael Jordan' },
  { de: 'Muhammad Ali', en: 'Muhammad Ali' },
  { de: 'Mike Tyson', en: 'Mike Tyson' },
  { de: 'Wladimir Klitschko', en: 'Wladimir Klitschko' },
  { de: 'Tiger Woods', en: 'Tiger Woods' },
  { de: 'Kylian Mbappé', en: 'Kylian Mbappé' },
  { de: 'Erling Haaland', en: 'Erling Haaland' },
  { de: 'Neymar', en: 'Neymar' },
  { de: 'Zinédine Zidane', en: 'Zinédine Zidane' },
  { de: 'Pelé', en: 'Pelé' },
  { de: 'Diego Maradona', en: 'Diego Maradona' },
  { de: 'Jürgen Klopp', en: 'Jürgen Klopp' },
  { de: 'Toni Kroos', en: 'Toni Kroos' },
  { de: 'Simone Biles', en: 'Simone Biles' },
  { de: 'Alexander Zverev', en: 'Alexander Zverev' },
  { de: 'Jamal Musiala', en: 'Jamal Musiala' },
  { de: 'Harry Kane', en: 'Harry Kane' },
  { de: 'Mario Götze', en: 'Mario Götze' },
  { de: 'Oliver Kahn', en: 'Oliver Kahn' },
  { de: 'Lukas Podolski', en: 'Lukas Podolski' },
  { de: 'Bastian Schweinsteiger', en: 'Bastian Schweinsteiger' },
  { de: 'Miroslav Klose', en: 'Miroslav Klose' },
  { de: 'Tom Brady', en: 'Tom Brady' },
  { de: 'Kobe Bryant', en: 'Kobe Bryant' },
  { de: 'David Beckham', en: 'David Beckham' },
  { de: 'Zlatan Ibrahimović', en: 'Zlatan Ibrahimović' },
  { de: 'Joshua Kimmich', en: 'Joshua Kimmich' },
  { de: 'FC Bayern München', en: 'Bayern Munich' },
  { de: 'Borussia Dortmund', en: 'Borussia Dortmund' },
  { de: 'FC Barcelona', en: 'FC Barcelona' },
  { de: 'Real Madrid', en: 'Real Madrid' },
  { de: 'Manchester United', en: 'Manchester United' },
  { de: 'FC Liverpool', en: 'Liverpool FC' },
  { de: 'Schalke 04', en: 'Schalke 04' },
  { de: 'Juventus Turin', en: 'Juventus' },
  { de: 'Paris Saint-Germain', en: 'Paris Saint-Germain' },
  { de: 'Chicago Bulls', en: 'Chicago Bulls' },
  { de: 'Los Angeles Lakers', en: 'Los Angeles Lakers' },
  { de: 'Hamburger SV', en: 'Hamburger SV' },
  { de: '1. FC Köln', en: 'FC Cologne' },
  { de: 'Werder Bremen', en: 'Werder Bremen' },
  { de: 'Bayer Leverkusen', en: 'Bayer Leverkusen' },
  { de: 'FC Chelsea', en: 'Chelsea FC' },
  { de: 'FC St. Pauli', en: 'FC St. Pauli' },
  { de: 'Manchester City', en: 'Manchester City' },
  { de: 'Nationalmannschaft', en: 'National team' },
  { de: 'Tennisschläger', en: 'Tennis racket' },
  { de: 'Golfschläger', en: 'Golf club' },
  { de: 'Federball', en: 'Shuttlecock' },
  { de: 'Hantel', en: 'Dumbbell' },
  { de: 'Boxhandschuhe', en: 'Boxing gloves' },
  { de: 'Torwarthandschuhe', en: 'Goalkeeper gloves' },
  { de: 'Schlittschuhe', en: 'Ice skates' },
  { de: 'Puck', en: 'Puck' },
  { de: 'Trikot', en: 'Jersey' },
  { de: 'Trillerpfeife', en: 'Whistle' },
  { de: 'Stoppuhr', en: 'Stopwatch' },
  { de: 'Springseil', en: 'Skipping rope' },
  { de: 'Schwimmbrille', en: 'Swimming goggles' },
  { de: 'Surfbrett', en: 'Surfboard' },
  { de: 'Schienbeinschoner', en: 'Shin pads' },
  { de: 'Basketballkorb', en: 'Basketball hoop' },
  { de: 'Gelbe Karte', en: 'Yellow card' },
  { de: 'Rote Karte', en: 'Red card' },
  { de: 'Pokal', en: 'Trophy' },
  { de: 'Medaille', en: 'Medal' },
  { de: 'Siegertreppchen', en: 'Podium' },
  { de: 'Laufband', en: 'Treadmill' },
  { de: 'Baseballschläger', en: 'Baseball bat' },
  { de: 'Trampolin', en: 'Trampoline' },
  { de: 'Sprungbrett', en: 'Diving board' },
  { de: 'Schwebebalken', en: 'Balance beam' },
  { de: 'Elfmeter', en: 'Penalty' },
  { de: 'Abseits', en: 'Offside' },
  { de: 'Eckball', en: 'Corner kick' },
  { de: 'Freistoß', en: 'Free kick' },
  { de: 'Eigentor', en: 'Own goal' },
  { de: 'Hattrick', en: 'Hat-trick' },
  { de: 'Fallrückzieher', en: 'Bicycle kick' },
  { de: 'Kopfball', en: 'Header' },
  { de: 'Torwart', en: 'Goalkeeper' },
  { de: 'Schiedsrichter', en: 'Referee' },
  { de: 'Halbzeit', en: 'Half-time' },
  { de: 'Verlängerung', en: 'Extra time' },
  { de: 'Videobeweis', en: 'VAR' },
  { de: 'Foul', en: 'Foul' },
  { de: 'Doping', en: 'Doping' },
  { de: 'Weltrekord', en: 'World record' },
  { de: 'Olympische Spiele', en: 'Olympic Games' },
  { de: 'Fußball-WM', en: 'World Cup' },
  { de: 'Champions League', en: 'Champions League' },
  { de: 'Bundesliga', en: 'Bundesliga' },
  { de: 'Tour de France', en: 'Tour de France' },
  { de: 'Super Bowl', en: 'Super Bowl' },
  { de: 'Wimbledon', en: 'Wimbledon' },
  { de: 'Olympisches Feuer', en: 'Olympic flame' },
  { de: 'Matchball', en: 'Match point' },
  { de: 'Knockout', en: 'Knockout' },
  { de: 'Slam Dunk', en: 'Slam dunk' },
  { de: 'Touchdown', en: 'Touchdown' },
  { de: 'Boxenstopp', en: 'Pit stop' },
  { de: 'Pole-Position', en: 'Pole position' },
  { de: 'La-Ola-Welle', en: 'Mexican wave' },
  { de: 'Fehlstart', en: 'False start' },
  { de: 'Muskelkater', en: 'Sore muscles' },
  { de: 'Abstieg', en: 'Relegation' },
  { de: 'Maskottchen', en: 'Mascot' },
  { de: 'Stadion', en: 'Stadium' },
  { de: 'Liegestütz', en: 'Push-up' },
  { de: 'Klimmzug', en: 'Pull-up' },
  { de: 'Spagat', en: 'The splits' },
  { de: 'Salto', en: 'Somersault' },
  { de: 'Handstand', en: 'Handstand' },
];
