export const coworkersQuestions: string[] = [
  'Wer würde am ehesten in einem Meeting einschlafen?',
  'Wer von euch hat schon mal vergessen, sich im Videocall stummzuschalten?',
  'Wer hat am wahrscheinlichsten schon mal eine Mail an die falsche Person geschickt?',
  'Wer würde am ehesten die letzte Tasse Kaffee nehmen und keinen neuen kochen?',
  'Wer von euch beantwortet Mails auch noch um Mitternacht?',
  'Wer würde am ehesten im Homeoffice noch im Schlafanzug arbeiten?',
  'Wer hat die meisten ungelesenen Mails im Postfach?',
  'Wer würde am ehesten eine Deadline um fünf Minuten vor knapp schaffen?',
  'Wer von euch hat schon mal so getan, als wäre die Internetverbindung schlecht?',
  'Wer würde am ehesten in fünf Jahren Chefin oder Chef dieser Firma sein?',
  'Wer hat am wahrscheinlichsten schon mal im Meeting heimlich etwas anderes erledigt?',
  'Wer würde am ehesten auf der Weihnachtsfeier als Letztes nach Hause gehen?',
  'Wer von euch hat den chaotischsten Schreibtisch?',
  'Wer würde am ehesten ein Meeting ansetzen, das auch eine Mail hätte sein können?',
  'Wer hat am wahrscheinlichsten schon mal fremdes Essen aus dem Kühlschrank gegessen?',
  'Wer würde am ehesten spontan kündigen und eine Weltreise machen?',
  'Wer von euch schickt die meisten Emojis im Teamchat?',
  'Wer würde am ehesten bei jeder Frage sagen: Lass uns das offline besprechen?',
  'Wer hat am wahrscheinlichsten noch nie die Spülmaschine in der Kaffeeküche ausgeräumt?',
  'Wer würde am ehesten zu jedem Meeting zu spät kommen?',
  'Wer von euch hat die meisten offenen Browser-Tabs?',
  'Wer würde am ehesten heimlich ein Nickerchen im Homeoffice machen?',
  'Wer hat am wahrscheinlichsten schon mal eine Präsentation komplett improvisiert?',
  'Wer würde am ehesten das Büro mit Pflanzen in einen Dschungel verwandeln?',
  'Wer von euch kennt den ganzen Büroklatsch zuerst?',
  'Wer würde am ehesten auf der Firmenfeier die Tanzfläche eröffnen?',
  'Wer hat am wahrscheinlichsten schon mal im Videocall mit Kamera an gegessen?',
  'Wer würde am ehesten eine Excel-Tabelle für die eigene Einkaufsliste anlegen?',
  'Wer von euch sagt am häufigsten: Kurze Frage?',
  'Wer würde am ehesten den Drucker zum Verzweifeln bringen?',
  'Wer hat am wahrscheinlichsten schon mal Urlaub genommen und trotzdem Mails gelesen?',
  'Wer würde am ehesten das Team mit selbstgebackenem Kuchen überraschen?',
  'Wer von euch hat schon mal das Meeting gestartet und den Link nicht verschickt?',
  'Wer würde am ehesten in der Mittagspause einen Powernap halten?',
  'Wer hat am wahrscheinlichsten das peinlichste Profilbild im Teamchat?',
  'Wer würde am ehesten ohne Kaffee keinen einzigen Satz herausbringen?',
  'Wer von euch würde eine Beförderung am lautesten feiern?',
  'Wer würde am ehesten einen Fehler im Code oder Dokument einer anderen Person finden?',
  'Wer hat am wahrscheinlichsten schon mal auf Allen antworten geklickt, obwohl es nicht nötig war?',
  'Wer würde am ehesten ein Buzzword-Bingo im Meeting gewinnen?',
  'Wer von euch hat den längsten Arbeitsweg und beschwert sich am wenigsten?',
  'Wer würde am ehesten die Weihnachtsfeier komplett allein organisieren?',
  'Wer hat am wahrscheinlichsten die meisten Passwörter auf Zetteln notiert?',
  'Wer würde am ehesten im Meeting nicken, ohne zuzuhören?',
  'Wer von euch würde im Lotto gewinnen und trotzdem am Montag zur Arbeit kommen?',
  'Wer würde am ehesten ein Teamevent mit Escape Room vorschlagen?',
  'Wer hat am wahrscheinlichsten schon mal den Status auf Abwesend gestellt, um Ruhe zu haben?',
  'Wer würde am ehesten eine ganze Woche nur Kantinenessen essen?',
  'Wer von euch hat schon mal den Chef oder die Chefin aus Versehen geduzt oder gesiezt?',
  'Wer würde am ehesten eine eigene Firma gründen?',
  'Wer hat am wahrscheinlichsten die meisten Kalendereinträge an einem Tag?',
  'Wer würde am ehesten im Großraumbüro zu laut telefonieren?',
  'Wer von euch bringt am häufigsten Süßigkeiten für alle mit?',
  'Wer würde am ehesten eine Mail mit Anhang schicken und den Anhang vergessen?',
  'Wer hat am wahrscheinlichsten schon mal einen Termin komplett verschlafen?',
  'Wer würde am ehesten Mitarbeiterin oder Mitarbeiter des Monats werden?',
  'Wer von euch würde im Firmen-Fußballturnier am meisten Ehrgeiz zeigen?',
  'Wer würde am ehesten beim Wichteln das seltsamste Geschenk mitbringen?',
  'Wer hat am wahrscheinlichsten schon mal im Büro übernachtet?',
  'Wer würde am ehesten jede Kleinigkeit in einem Ticket dokumentieren?',
  'Wer von euch würde eine Woche ohne Laptop am besten überleben?',
  'Wer würde am ehesten am Freitagnachmittag als Erstes verschwinden?',
  'Wer hat am wahrscheinlichsten den besten Ausrede-Vorrat für Verspätungen?',
  'Wer würde am ehesten die Kaffeemaschine kaputt machen?',
  'Wer von euch würde in einer Bürosoap die Hauptrolle spielen?',
  'Wer würde am ehesten eine Stunde lang über die perfekte Ordnerstruktur diskutieren?',
  'Wer hat am wahrscheinlichsten schon mal eine Sprachnachricht im Arbeitschat verschickt?',
  'Wer würde am ehesten mit dem Fahrrad bei Regen ins Büro kommen?',
  'Wer von euch kennt die Geburtstage aller Kolleginnen und Kollegen auswendig?',
  'Wer würde am ehesten nach der Kündigung trotzdem zur Weihnachtsfeier kommen?',
  'Wer hat am wahrscheinlichsten den aufgeräumtesten Desktop auf dem Rechner?',
  'Wer würde am ehesten ein Meeting mit einem Witz eröffnen, über den niemand lacht?',
  'Wer von euch hat schon mal eine Mail angefangen mit: Wie bereits erwähnt?',
  'Wer würde am ehesten heimlich die Bürotemperatur verstellen?',
  'Wer hat am wahrscheinlichsten schon mal den eigenen Bildschirm geteilt und etwas Peinliches gezeigt?',
  'Wer würde am ehesten das Firmenlogo als Tattoo tragen?',
  'Wer von euch würde beim Teamevent am lautesten Karaoke singen?',
  'Wer würde am ehesten im Aufzug Smalltalk mit dem Vorstand anfangen?',
  'Wer hat am wahrscheinlichsten schon mal in der Mittagspause länger gebraucht als geplant?',
  'Wer würde am ehesten nach dem Feierabend noch schnell eine Sache fertig machen?',
];
