export const coworkersQuestions: string[] = [
  'Wer würde am ehesten in einem Meeting einschlafen?',
  'Wer von euch hat schon mal vergessen, sich im Videocall stummzuschalten?',
  'Wer hat am wahrscheinlichsten schon mal eine Mail an die falsche Person geschickt?',
  'Wer würde am ehesten die letzte Tasse Kaffee nehmen und keinen neuen kochen?',
  'Wer von euch beantwortet Mails auch noch um Mitternacht?',
  'Wer würde am ehesten im Homeoffice noch im Schlafanzug arbeiten?',
  'Wer würde am ehesten eine Deadline um fünf Minuten vor knapp schaffen?',
  'Wer von euch hat schon mal so getan, als wäre die Internetverbindung schlecht?',
  'Wer würde am ehesten in fünf Jahren Chefin oder Chef dieser Firma sein?',
  'Wer hat am wahrscheinlichsten schon mal im Meeting heimlich etwas anderes erledigt?',
  'Wer würde am ehesten auf der Weihnachtsfeier als Letztes nach Hause gehen?',
  'Wer von euch hat den chaotischsten Schreibtisch?',
  'Wer würde am ehesten ein Meeting ansetzen, das auch eine Mail hätte sein können?',
  'Wer würde am ehesten spontan kündigen und eine Weltreise machen?',
  'Wer von euch schickt die meisten Emojis im Teamchat?',
  'Wer würde am ehesten bei jeder Frage sagen: Lass uns das offline besprechen?',
  'Wer hat am wahrscheinlichsten noch nie die Spülmaschine in der Kaffeeküche ausgeräumt?',
  'Wer würde am ehesten zu jedem Meeting zu spät kommen?',
  'Wer von euch hat die meisten offenen Browser-Tabs?',
  'Wer hat am wahrscheinlichsten schon mal eine Präsentation komplett improvisiert?',
  'Wer würde am ehesten das Büro mit Pflanzen in einen Dschungel verwandeln?',
  'Wer von euch kennt den ganzen Büroklatsch zuerst?',
  'Wer würde am ehesten auf der Firmenfeier die Tanzfläche eröffnen?',
  'Wer hat am wahrscheinlichsten schon mal im Videocall mit Kamera an gegessen?',
  'Wer würde am ehesten eine Excel-Tabelle für die eigene Einkaufsliste anlegen?',
  'Wer von euch sagt am häufigsten: Kurze Frage?',
  'Wer hat am wahrscheinlichsten schon mal Urlaub genommen und trotzdem Mails gelesen?',
  'Wer würde am ehesten das Team mit selbstgebackenem Kuchen überraschen?',
  'Wer von euch hat schon mal das Meeting gestartet und den Link nicht verschickt?',
  'Wer hat am wahrscheinlichsten das peinlichste Profilbild im Teamchat?',
  'Wer würde am ehesten ohne Kaffee keinen einzigen Satz herausbringen?',
  'Wer von euch würde eine Beförderung am lautesten feiern?',
  'Wer hat am wahrscheinlichsten schon mal auf Allen antworten geklickt, obwohl es nicht nötig war?',
  'Wer würde am ehesten die Weihnachtsfeier komplett allein organisieren?',
  'Wer hat am wahrscheinlichsten die meisten Passwörter auf Zetteln notiert?',
  'Wer würde am ehesten im Meeting nicken, ohne zuzuhören?',
  'Wer von euch würde im Lotto gewinnen und trotzdem am Montag zur Arbeit kommen?',
  'Wer würde am ehesten ein Teamevent mit Escape Room vorschlagen?',
  'Wer hat am wahrscheinlichsten schon mal den Status auf Abwesend gestellt, um Ruhe zu haben?',
  'Wer würde am ehesten eine ganze Woche nur Kantinenessen essen?',
  'Wer von euch hat schon mal den Chef oder die Chefin aus Versehen geduzt oder gesiezt?',
  'Wer würde am ehesten eine eigene Firma gründen?',
  'Wer würde am ehesten im Großraumbüro zu laut telefonieren?',
  'Wer von euch bringt am häufigsten Süßigkeiten für alle mit?',
  'Wer würde am ehesten eine Mail mit Anhang schicken und den Anhang vergessen?',
  'Wer hat am wahrscheinlichsten schon mal einen Termin komplett verschlafen?',
  'Wer würde am ehesten Mitarbeiterin oder Mitarbeiter des Monats werden?',
  'Wer von euch würde im Firmen-Fußballturnier am meisten Ehrgeiz zeigen?',
  'Wer würde am ehesten beim Wichteln das seltsamste Geschenk mitbringen?',
  'Wer hat am wahrscheinlichsten schon mal im Büro übernachtet?',
  'Wer würde am ehesten jede Kleinigkeit in einem Ticket dokumentieren?',
  'Wer von euch würde eine Woche ohne Laptop am besten überleben?',
  'Wer würde am ehesten am Freitagnachmittag als Erstes verschwinden?',
  'Wer hat am wahrscheinlichsten den besten Ausrede-Vorrat für Verspätungen?',
  'Wer würde am ehesten die Kaffeemaschine kaputt machen?',
  'Wer von euch würde in einer Bürosoap die Hauptrolle spielen?',
  'Wer würde am ehesten eine Stunde lang über die perfekte Ordnerstruktur diskutieren?',
  'Wer hat am wahrscheinlichsten schon mal eine Sprachnachricht im Arbeitschat verschickt?',
  'Wer würde am ehesten mit dem Fahrrad bei Regen ins Büro kommen?',
  'Wer von euch kennt die Geburtstage aller Kolleginnen und Kollegen auswendig?',
  'Wer hat am wahrscheinlichsten den aufgeräumtesten Desktop auf dem Rechner?',
  'Wer würde am ehesten ein Meeting mit einem Witz eröffnen, über den niemand lacht?',
  'Wer von euch hat schon mal eine Mail angefangen mit: Wie bereits erwähnt?',
  'Wer würde am ehesten heimlich die Bürotemperatur verstellen?',
  'Wer hat am wahrscheinlichsten schon mal den eigenen Bildschirm geteilt und etwas Peinliches gezeigt?',
  'Wer würde am ehesten das Firmenlogo als Tattoo tragen?',
  'Wer von euch würde beim Teamevent am lautesten Karaoke singen?',
  'Wer würde am ehesten im Aufzug Smalltalk mit dem Vorstand anfangen?',
  'Wer würde am ehesten nach dem Feierabend noch schnell eine Sache fertig machen?',
  'Wer würde am ehesten eine Agenda mit zwölf Unterpunkten für ein Meeting von zehn Minuten schreiben?',
  'Wer von euch macht in Meetings die schönsten Notizen, die danach niemand liest?',
  'Wer würde am ehesten zu einem Meeting erscheinen, zu dem gar keine Einladung kam?',
  'Wer würde am ehesten das Protokoll schreiben, weil sich sonst niemand meldet?',
  'Wer von euch stellt am Ende jedes Meetings noch eine Frage, wenn alle schon aufstehen?',
  'Wer hat am wahrscheinlichsten schon mal im falschen Meetingraum gewartet?',
  'Wer würde am ehesten bei einem Brainstorming die verrücktesten Ideen einbringen?',
  'Wer von euch sagt im Meeting am häufigsten: Da bin ich ganz bei dir?',
  'Wer würde am ehesten einen Meetingraum für den ganzen Tag blockieren, nur zur Sicherheit?',
  'Wer hat am wahrscheinlichsten schon mal ein Meeting nur wegen der Kekse besucht?',
  'Wer würde am ehesten eine Retrospektive in eine Therapiesitzung verwandeln?',
  'Wer würde am ehesten ein Meeting ansetzen, um das nächste Meeting vorzubereiten?',
  'Wer würde am ehesten im Meeting ein Flipchart vollmalen, das niemand entziffern kann?',
  'Wer von euch hat im Homeoffice den schönsten virtuellen Hintergrund?',
  'Wer hat am wahrscheinlichsten schon mal ein Haustier ins Videomeeting laufen lassen?',
  'Wer von euch hat im Homeoffice schon mal oben Hemd und unten Jogginghose getragen?',
  'Wer würde am ehesten im Homeoffice vergessen, dass heute Bürotag ist?',
  'Wer von euch hat zu Hause das ergonomischste Setup?',
  'Wer hat am wahrscheinlichsten schon mal ein Paket während eines Calls angenommen?',
  'Wer würde am ehesten im Homeoffice drei Tage lang das Haus nicht verlassen?',
  'Wer hat am wahrscheinlichsten schon mal mit einem Filter im Videocall als Kartoffel gesprochen?',
  'Wer würde am ehesten für das Homeoffice einen zweiten Monitor kaufen und dann drei wollen?',
  'Wer von euch arbeitet im Homeoffice am liebsten mit Musik in voller Lautstärke?',
  'Wer würde am ehesten aus dem Café arbeiten und es Homeoffice nennen?',
  'Wer würde am ehesten ein Schild mit Regeln für die Kaffeeküche aufhängen?',
  'Wer hat am wahrscheinlichsten die meisten Tassen im Büro herumstehen?',
  'Wer würde am ehesten eine eigene Siebträgermaschine ins Büro mitbringen?',
  'Wer würde am ehesten in der Kaffeeküche hängen bleiben und eine Stunde quatschen?',
  'Wer von euch hat eine Lieblingstasse, die niemand sonst benutzen darf?',
  'Wer würde am ehesten Essen mit Namen beschriften, bevor es in den Kühlschrank kommt?',
  'Wer hat am wahrscheinlichsten schon mal Fisch in der Büro-Mikrowelle aufgewärmt?',
  'Wer würde am ehesten Tee trinken, nur um anders zu sein als alle anderen?',
  'Wer würde am ehesten in der Kaffeeküche heimlich Kuchenreste vernichten?',
  'Wer würde am ehesten eine Petition für besseren Kaffee starten?',
  'Wer würde am ehesten Hafermilch für das ganze Büro bestellen?',
  'Wer von euch erzählt in der Kaffeeküche die besten Geschichten vom Wochenende?',
  'Wer von euch schreibt die längsten Mails?',
  'Wer würde am ehesten eine Mail mit nur einem Wort beantworten?',
  'Wer hat am wahrscheinlichsten schon mal eine Mail mit Liebe Grüße an die Geschäftsführung geschickt?',
  'Wer würde am ehesten Mails mit drei Ausrufezeichen als dringend markieren?',
  'Wer würde am ehesten Mails ausdrucken, um sie in Ruhe zu lesen?',
  'Wer hat am wahrscheinlichsten schon mal vergessen, die Abwesenheitsnotiz wieder auszuschalten?',
  'Wer würde am ehesten Inbox Zero erreichen und es allen erzählen?',
  'Wer von euch setzt am liebsten die Führungskraft in CC?',
  'Wer würde am ehesten eine Mail fünfmal umschreiben, bevor sie rausgeht?',
  'Wer hat am wahrscheinlichsten eine Mailsignatur mit einem Zitat drin?',
  'Wer würde am ehesten Mails mit Freundliche Grüße und null Freundlichkeit beenden?',
  'Wer von euch hat schon mal eine Mail zurückgerufen und gebetet, dass es klappt?',
  'Wer hat am wahrscheinlichsten schon mal eine Mail im Entwurf vergessen und erst Wochen später gefunden?',
  'Wer würde am ehesten den Newsletter der Firma tatsächlich lesen?',
  'Wer von euch antwortet auf Mails schneller als auf Nachrichten von der Familie?',
  'Wer hat am wahrscheinlichsten schon mal CC und BCC verwechselt?',
  'Wer würde am ehesten auf eine Mail antworten, die schon drei Wochen alt ist?',
  'Wer von euch schreibt im Chat erst Hallo und wartet dann auf eine Antwort, bevor die Frage kommt?',
  'Wer hat am wahrscheinlichsten schon mal eine private Nachricht im falschen Chat gepostet?',
  'Wer würde am ehesten auf jede Nachricht nur mit einem Daumen reagieren?',
  'Wer von euch hat den kreativsten Status im Teamchat?',
  'Wer hat am wahrscheinlichsten schon mal die ganze Firma mit @alle markiert?',
  'Wer würde am ehesten GIFs als Antwort auf ernste Fragen schicken?',
  'Wer von euch tippt am längsten, bevor endlich eine Nachricht kommt?',
  'Wer würde am ehesten Nachrichten als ungelesen markieren und nie wieder ansehen?',
  'Wer von euch schreibt im Chat ausschließlich in Kleinbuchstaben?',
  'Wer hat am wahrscheinlichsten schon mal mit dem falschen Emoji auf eine traurige Nachricht reagiert?',
  'Wer würde am ehesten einen Channel nur für Katzenbilder gründen?',
  'Wer von euch antwortet im Chat schneller als der eigene Schatten?',
  'Wer würde am ehesten alle Benachrichtigungen ausschalten und trotzdem alles mitbekommen?',
  'Wer hat am wahrscheinlichsten schon mal eine Umfrage im Teamchat gestartet, nur um das Mittagessen zu klären?',
  'Wer würde am ehesten Threads ignorieren und alles in den Hauptchannel schreiben?',
  'Wer von euch arbeitet unter Zeitdruck am besten?',
  'Wer würde am ehesten eine Aufgabe drei Wochen vor der Deadline fertig haben?',
  'Wer hat am wahrscheinlichsten schon mal um eine Fristverlängerung gebeten, die gar nicht nötig war?',
  'Wer würde am ehesten sagen, das ist in fünf Minuten erledigt, und dann zwei Tage brauchen?',
  'Wer von euch hat die längste To-do-Liste?',
  'Wer würde am ehesten eine erledigte Aufgabe nachträglich auf die Liste schreiben, nur um sie abzuhaken?',
  'Wer hat am wahrscheinlichsten schon mal eine Aufgabe erledigt, die längst gestrichen war?',
  'Wer würde am ehesten bei Stress anfangen, den Schreibtisch aufzuräumen?',
  'Wer würde am ehesten eine Deadline in den Kalender eintragen und sie dann ignorieren?',
  'Wer hat am wahrscheinlichsten schon mal eine Abgabe um 23:59 Uhr verschickt?',
  'Wer von euch bleibt bei der größten Panik am ruhigsten?',
  'Wer würde am ehesten einen Projektplan mit Farbcodes erstellen?',
  'Wer hat am wahrscheinlichsten schon mal eine Aufgabe einfach elegant weiterdelegiert?',
  'Wer von euch hat das Aufschieben zur Kunstform erhoben?',
  'Wer würde am ehesten am letzten Tag vor dem Urlaub alles auf einmal erledigen?',
  'Wer hat am wahrscheinlichsten schon mal eine Aufgabe übernommen, nur um aus einem Meeting rauszukommen?',
  'Wer würde am ehesten die Führungskraft beim Tischkicker gnadenlos besiegen?',
  'Wer würde am ehesten als Chefin oder Chef den Freitag zum freien Tag erklären?',
  'Wer von euch würde als Chefin oder Chef die meisten Meetings abschaffen?',
  'Wer hat am wahrscheinlichsten schon mal im Jahresgespräch mehr geredet als die Führungskraft?',
  'Wer würde am ehesten eine Gehaltsverhandlung mit selbstgebauten Diagrammen führen?',
  'Wer hat am wahrscheinlichsten schon mal die Führungskraft aus Versehen mit Mama oder Papa angesprochen?',
  'Wer würde am ehesten als Chefin oder Chef eine Rutsche ins Büro bauen lassen?',
  'Wer von euch würde bei einem Rollentausch mit der Führungskraft nach einem Tag aufgeben?',
  'Wer hat am wahrscheinlichsten die beste Antwort auf die Frage nach den eigenen Schwächen?',
  'Wer würde am ehesten als Chefin oder Chef die Kleiderordnung auf Hawaiihemden umstellen?',
  'Wer von euch isst jeden Tag dasselbe Mittagessen?',
  'Wer würde am ehesten um elf Uhr schon fragen, wann es Mittagessen gibt?',
  'Wer hat am wahrscheinlichsten das beste Meal Prep im ganzen Büro?',
  'Wer würde am ehesten die Mittagspause am Schreibtisch verbringen?',
  'Wer von euch kennt jedes Restaurant in der Nähe des Büros?',
  'Wer würde am ehesten eine halbe Stunde über die Wahl des Mittagessens diskutieren?',
  'Wer hat am wahrscheinlichsten schon mal versehentlich das Mittagessen einer anderen Person mitgenommen?',
  'Wer würde am ehesten in der Mittagspause joggen gehen?',
  'Wer würde am ehesten eine Sammelbestellung organisieren und dann das Geld eintreiben?',
  'Wer von euch bringt das außergewöhnlichste Essen mit ins Büro?',
  'Wer würde am ehesten eine Mittagspause mit Spaziergang für das ganze Team einführen?',
  'Wer hat am wahrscheinlichsten schon mal beim Mittagessen über die Arbeit geredet, obwohl alle Pause wollten?',
  'Wer würde am ehesten eine Rangliste der besten Kantinengerichte führen?',
  'Wer von euch hat immer Snacks in der Schreibtischschublade?',
  'Wer würde am ehesten Essen bestellen, nur weil jemand anders gerade Essen hat?',
  'Wer würde am ehesten beim Mittagessen heimlich die Rechnung für alle bezahlen?',
  'Wer von euch hat auf der Weihnachtsfeier das schickste Outfit?',
  'Wer würde am ehesten auf der Firmenfeier eine spontane Rede halten?',
  'Wer hat am wahrscheinlichsten schon mal auf der Firmenfeier den Namen von jemandem vergessen?',
  'Wer würde am ehesten beim Teamevent die Regeln jedes Spiels hinterfragen?',
  'Wer von euch würde beim Firmenlauf als Erstes ins Ziel kommen?',
  'Wer würde am ehesten auf der Sommerfeier den Grill übernehmen?',
  'Wer hat am wahrscheinlichsten die meisten Fotos von der letzten Weihnachtsfeier?',
  'Wer würde am ehesten beim Teamevent im Kletterpark die meiste Angst haben?',
  'Wer von euch würde ein Pubquiz für das Team im Alleingang gewinnen?',
  'Wer hat am wahrscheinlichsten schon mal beim Teamevent das falsche Datum im Kalender gehabt?',
  'Wer würde am ehesten beim Teamevent das Kommando übernehmen, ohne gefragt zu werden?',
  'Wer hat am wahrscheinlichsten schon mal beim Bowling mit dem Team einen Strike gefeiert wie einen Olympiasieg?',
  'Wer würde am ehesten auf der Weihnachtsfeier beim DJ um ein bestimmtes Lied betteln?',
  'Wer von euch würde bei einem Kochkurs mit dem Team am meisten Chaos anrichten?',
  'Wer würde am ehesten den Teamausflug in eine Wanderung über 20 Kilometer verwandeln?',
  'Wer hat am wahrscheinlichsten die beste Geschichte von einer früheren Firmenfeier?',
  'Wer würde am ehesten am Tag nach der Firmenfeier pünktlich und topfit im Büro sitzen?',
  'Wer von euch hat den spannendsten Lebenslauf?',
  'Wer würde am ehesten eine Abschiedsmail schreiben, die alle zum Weinen bringt?',
  'Wer würde am ehesten in zehn Jahren noch genau hier arbeiten?',
  'Wer von euch würde den Job für eine Karriere als Influencer aufgeben?',
  'Wer hat am wahrscheinlichsten den ungewöhnlichsten Nebenjob gehabt?',
  'Wer würde am ehesten nach der Rente trotzdem jeden Tag im Büro vorbeischauen?',
  'Wer von euch würde sich als Erstes für ein Sabbatical entscheiden?',
  'Wer würde am ehesten eine komplett neue Karriere als Bäckerin oder Bäcker starten?',
  'Wer hat am wahrscheinlichsten das beste Vorstellungsgespräch aller Zeiten geführt?',
  'Wer würde am ehesten auf LinkedIn einen inspirierenden Text über einen platten Reifen posten?',
  'Wer von euch hat schon die meisten Weiterbildungen gemacht?',
  'Wer würde am ehesten einen Jobtitel erfinden, den es noch gar nicht gibt?',
  'Wer hat am wahrscheinlichsten schon mal ein Vorstellungsgespräch mit dem falschen Firmennamen begonnen?',
  'Wer würde am ehesten nach dem Abschied ein Buch über die Zeit hier schreiben?',
  'Wer würde am ehesten ein Start-up mit einer Idee aus der Kaffeeküche gründen?',
  'Wer von euch hat die meisten Bonusmeilen gesammelt?',
  'Wer würde am ehesten auf einer Dienstreise den Zug verpassen?',
  'Wer hat am wahrscheinlichsten schon mal eine Reisekostenabrechnung drei Monate zu spät eingereicht?',
  'Wer würde am ehesten auf Dienstreise das Hotelfrühstück komplett ausnutzen?',
  'Wer von euch packt für eine Nacht Dienstreise einen ganzen Koffer?',
  'Wer würde am ehesten auf Dienstreise jede Sehenswürdigkeit mitnehmen?',
  'Wer hat am wahrscheinlichsten schon mal eine Quittung verloren und verzweifelt gesucht?',
  'Wer würde am ehesten im ICE einen Call führen, obwohl ständig der Empfang weg ist?',
  'Wer von euch hat schon mal im falschen Hotel eingecheckt?',
  'Wer würde am ehesten eine Dienstreise in einen Kurzurlaub verlängern?',
  'Wer hat am wahrscheinlichsten schon mal das Ladekabel auf einer Dienstreise vergessen?',
  'Wer würde am ehesten auf einer Messe die meisten Werbegeschenke einsammeln?',
  'Wer von euch kennt jeden Bahnhof in Deutschland von innen?',
  'Wer hat am wahrscheinlichsten schon mal die Zimmerkarte im Hotelzimmer liegen lassen und sich ausgesperrt?',
  'Wer von euch würde nach einem Kundentermin noch die ganze Stadt erkunden?',
  'Wer würde am ehesten im Flugzeug noch schnell eine Präsentation fertig machen?',
  'Wer hat am wahrscheinlichsten schon mal eine Dienstreise wegen eines Bahnstreiks komplett umgeplant?',
  'Wer würde am ehesten von jeder Dienstreise einen Kühlschrankmagneten mitbringen?',
  'Wer von euch hat schon mal einen Papierstau mit roher Gewalt gelöst?',
  'Wer würde am ehesten 50 Seiten drucken und dann merken, dass es die falsche Datei war?',
  'Wer hat am wahrscheinlichsten schon mal auf dem falschen Drucker gedruckt?',
  'Wer würde am ehesten ein IT-Ticket schreiben, das nur aus dem Wort Hilfe besteht?',
  'Wer hat am wahrscheinlichsten schon mal den IT-Support gerufen, und ein Neustart hat alles gelöst?',
  'Wer würde am ehesten das Passwort vergessen, das gerade erst geändert wurde?',
  'Wer von euch hilft allen anderen bei Technikproblemen, ohne in der IT zu arbeiten?',
  'Wer würde am ehesten Updates monatelang auf Später verschieben?',
  'Wer hat am wahrscheinlichsten schon mal Kaffee über die Tastatur gekippt?',
  'Wer würde am ehesten den IT-Support mit Keksen bestechen?',
  'Wer hat am wahrscheinlichsten schon mal auf eine Phishing-Testmail der IT reingeklickt?',
  'Wer würde am ehesten die Tastenkombination für jede Funktion auswendig kennen?',
  'Wer würde am ehesten eine Datei als final_final_wirklich_final speichern?',
  'Wer hat am wahrscheinlichsten schon mal eine wichtige Datei gelöscht und im Papierkorb wiedergefunden?',
  'Wer von euch hat sich am ersten Arbeitstag im Gebäude verlaufen?',
  'Wer würde am ehesten neuen Kolleginnen und Kollegen eine Führung mit Geheimtipps geben?',
  'Wer hat am wahrscheinlichsten bis heute nicht alle Namen aus dem eigenen Onboarding gelernt?',
  'Wer von euch war am ersten Arbeitstag am nervösesten?',
  'Wer hat am wahrscheinlichsten am ersten Tag viel zu schick angezogen im Büro gestanden?',
  'Wer von euch nimmt die wenigsten Urlaubstage und muss den Rest im März noch schnell verbrauchen?',
  'Wer würde am ehesten Brückentage strategisch besser planen als jedes Projekt?',
  'Wer hat am wahrscheinlichsten schon mal aus dem Urlaub eine Postkarte ins Büro geschickt?',
  'Wer würde am ehesten aus dem Urlaub mit Souvenirs für das ganze Team zurückkommen?',
  'Wer würde am ehesten eine Urlaubsübergabe schreiben, die länger ist als ein Roman?',
  'Wer würde am ehesten nach dem Urlaub eine Woche brauchen, um wieder anzukommen?',
  'Wer von euch kommt aus jedem Urlaub mit dem stärksten Sonnenbrand zurück?',
  'Wer hat am wahrscheinlichsten die beste Urlaubsgeschichte im Team?',
  'Wer würde am ehesten am ersten Tag nach dem Urlaub 400 Mails einfach als gelesen markieren?',
  'Wer von euch kennt die meisten Excel-Formeln auswendig?',
  'Wer hat am wahrscheinlichsten schon mal eine Excel-Datei mit einem Klick zerstört?',
  'Wer würde am ehesten jede Zelle in einer anderen Farbe einfärben?',
  'Wer von euch nutzt in Präsentationen die meisten Animationen?',
  'Wer würde am ehesten eine Präsentation mit 60 Folien für zehn Minuten vorbereiten?',
  'Wer würde am ehesten Comic Sans in einer Kundenpräsentation verwenden?',
  'Wer würde am ehesten ein Diagramm zeigen, das niemand versteht, nicht mal die Person selbst?',
  'Wer würde am ehesten Folien mit Memes auflockern?',
  'Wer von euch sagt in Präsentationen am häufigsten: Wie man hier gut sehen kann?',
  'Wer würde am ehesten den Laserpointer nervös über die ganze Leinwand tanzen lassen?',
  'Wer hat am wahrscheinlichsten schon mal den Beamer nicht zum Laufen gebracht?',
  'Wer von euch hat schon mal SVERWEIS erklärt und dabei selbst den Faden verloren?',
  'Wer würde am ehesten eine Präsentation ganz ohne Folien halten?',
  'Wer hat am wahrscheinlichsten schon mal eine Folie mit nur einem riesigen Wort gezeigt?',
  'Wer würde am ehesten bei einer Präsentation die Zeit um das Doppelte überziehen?',
  'Wer von euch trägt im Großraumbüro immer Kopfhörer, damit niemand stört?',
  'Wer würde am ehesten im Großraumbüro laut mit dem eigenen Rechner reden?',
  'Wer würde am ehesten morgens als Erstes im Büro sein und das Licht anmachen?',
  'Wer würde am ehesten beim Desksharing den Platz mit einem Handtuch reservieren?',
  'Wer hat am wahrscheinlichsten schon mal im Büro die Schuhe ausgezogen?',
  'Wer von euch summt bei der Arbeit, ohne es zu merken?',
  'Wer würde am ehesten das Büro für die Weihnachtszeit komplett dekorieren?',
  'Wer hat am wahrscheinlichsten die beste Fahrtechnik auf dem Bürostuhl?',
  'Wer würde am ehesten einen Stehschreibtisch haben und ihn nie hochfahren?',
  'Wer von euch tippt am lautesten auf der Tastatur?',
  'Wer würde am ehesten Post-its auf jeden freien Zentimeter kleben?',
  'Wer würde am ehesten einen Bürohund adoptieren, wenn es erlaubt wäre?',
  'Wer von euch hat schon mal an einer Glastür gezogen, an der man drücken muss?',
  'Wer würde am ehesten im Büro ein Fitnessprogramm für die Pause einführen?',
  'Wer hat am wahrscheinlichsten die größte Sammlung an Kugelschreibern auf dem Tisch?',
  'Wer von euch hat den kreativsten Spitznamen im Team?',
  'Wer würde am ehesten eigene Abkürzungen erfinden und erwarten, dass alle sie kennen?',
  'Wer würde am ehesten Wörter wie Synergie und Mehrwert in jedem Satz verwenden?',
  'Wer hat am wahrscheinlichsten schon mal genickt, obwohl die Abkürzung völlig unbekannt war?',
  'Wer hat am wahrscheinlichsten schon mal auf dem Firmenparkplatz das eigene Auto nicht wiedergefunden?',
  'Wer würde am ehesten einen Teamnamen vorschlagen, der nach Superhelden klingt?',
  'Wer von euch würde bei einer Feueralarmübung als Letztes rausgehen, weil die Mail noch raus muss?',
  'Wer würde am ehesten ein Teamfoto organisieren, bei dem alle das gleiche Shirt tragen?',
  'Wer würde am ehesten eine Playlist für das ganze Team erstellen?',
  'Wer von euch hat den besten Riecher dafür, wann es irgendwo Kuchen gibt?',
  'Wer würde am ehesten Feedback in Form eines Gedichts geben?',
  'Wer hat am wahrscheinlichsten schon mal eine Telefonkonferenz aus dem Supermarkt geführt?',
  'Wer würde am ehesten am letzten Arbeitstag vor Weihnachten das ganze Büro mit Glühwein versorgen?',
];
