export const crazyQuestions: string[] = [
  'Wer würde eine Zombie-Apokalypse als Erstes nicht überleben?',
  'Wer würde am ehesten einen Waschbären adoptieren und ihm eine eigene Wohnung einrichten?',
  'Wer von euch würde aus Versehen eine Sekte gründen?',
  'Wer würde in einer Reality-Show auf einer einsamen Insel als Erstes durchdrehen?',
  'Wer redet heimlich mit Tauben und glaubt, dass sie antworten?',
  'Wer würde am ehesten von Aliens entführt und freiwillig dort bleiben?',
  'Wer könnte sich mit einer Gans anlegen und verlieren?',
  'Wer von euch würde ein Kuscheltier heiraten, wenn es erlaubt wäre?',
  'Wer würde am ehesten versuchen, mit einem Einkaufswagen über die Alpen zu fahren?',
  'Wer würde nach einer Zeitreise ins Mittelalter sofort als Hexe verbrannt werden?',
  'Wer würde eine Woche lang in einem Möbelhaus leben, ohne dass es jemand merkt?',
  'Wer könnte eine Armee aus Eichhörnchen anführen?',
  'Wer von euch würde in einem Horrorfilm freiwillig in den dunklen Keller gehen?',
  'Wer würde am ehesten eine Beziehung mit einer Sprachassistenz anfangen?',
  'Wer würde bei einer Alien-Landung als Erstes ein Selfie mit den Aliens machen?',
  'Wer würde beim Wettessen gegen einen Bären antreten?',
  'Wer von euch würde aus Versehen Bürgermeister eines kleinen Dorfes werden?',
  'Wer würde am ehesten eine Religion rund um Toastbrot gründen?',
  'Wer würde nach einem Tag im Dschungel schon mit Affen zusammenleben?',
  'Wer könnte einen Hai mit bloßen Händen streicheln und es danach jedem erzählen?',
  'Wer von euch würde ein Haustier namens Gerhard haben, das eine Kartoffel ist?',
  'Wer würde am ehesten auf einem Kreuzfahrtschiff vergessen und erst Wochen später gefunden werden?',
  'Wer würde in einem Escape Room einfach einschlafen?',
  'Wer würde bei der Zombie-Apokalypse eine Gruppe anführen und alle in den Untergang führen?',
  'Wer könnte sich als Statue verkleiden und einen ganzen Tag lang nicht bewegen?',
  'Wer von euch würde einen Streit mit einem Automaten anfangen und ihn verlieren?',
  'Wer würde am ehesten versehentlich einen Krieg zwischen zwei Ländern auslösen?',
  'Wer würde eine Hochzeit im Supermarkt zwischen den Tiefkühltruhen feiern?',
  'Wer würde als Geist absichtlich nur ganz harmlose Leute erschrecken?',
  'Wer von euch würde sich in einer Höhle verlaufen und dort ein neues Leben anfangen?',
  'Wer könnte in einer Talentshow mit Furzgeräuschen gewinnen?',
  'Wer würde am ehesten einen Papagei trainieren, nur um andere zu beleidigen?',
  'Wer würde nach einer Nacht im Museum mit den Dinosauriern befreundet sein?',
  'Wer würde ein Einhorn finden und es sofort auf eBay verkaufen?',
  'Wer von euch würde in einer Welt ohne Internet als Erstes komplett verzweifeln?',
  'Wer würde am ehesten ein ganzes Jahr nur Nudeln mit Ketchup essen?',
  'Wer würde mit einem Heißluftballon starten und in einem anderen Land landen?',
  'Wer könnte einen Vulkan besteigen, nur um darin Marshmallows zu rösten?',
  'Wer würde als Superheld die nutzloseste Superkraft der Welt haben?',
  'Wer von euch würde einen Wal retten wollen und dabei selbst gerettet werden müssen?',
  'Wer würde am ehesten mit einem Lama durch Südamerika wandern?',
  'Wer würde auf dem Mars als Erstes Heimweh nach Döner haben?',
  'Wer würde bei einem Banküberfall versehentlich als Geisel mit den Tätern befreundet sein?',
  'Wer könnte sich in einem Labyrinth aus Maisfeldern für immer verirren?',
  'Wer von euch würde eine Fledermaus für einen Vogel halten und sie füttern wollen?',
  'Wer würde am ehesten bei einer Live-Sendung im Hühnerkostüm durchs Bild rennen?',
  'Wer würde aus Langeweile anfangen, ein Schloss aus Klopapier zu bauen?',
  'Wer würde in der Wildnis versuchen, Feuer mit dem Handy zu machen?',
  'Wer würde sich mit einem Roboterstaubsauger anfreunden und ihm Geheimnisse erzählen?',
  'Wer von euch würde einen Drachen zähmen und ihn dann nur für Grillabende nutzen?',
  'Wer würde am ehesten aus Versehen in einem fremden Land Königin oder König werden?',
  'Wer könnte einen Monat lang nur rückwärts laufen, weil es eine Wette war?',
  'Wer würde in einer Zeitmaschine sofort in die Zukunft reisen, nur um Lottozahlen zu holen?',
  'Wer würde als Pirat das Schiff versenken, bevor es überhaupt losgeht?',
  'Wer von euch würde einen Weltrekord im Dauerschlafen aufstellen wollen?',
  'Wer würde am ehesten eine Möwe für einen Diebstahl verklagen?',
  'Wer würde nach einer Hypnose den Rest des Lebens wie ein Huhn gackern?',
  'Wer würde einen Bigfoot finden und ihm die Haare schneiden wollen?',
  'Wer könnte eine Wassermelone mit dem Kopf zerschlagen und darauf stolz sein?',
  'Wer von euch würde in einer Fantasy-Welt als nerviger Sidekick enden?',
  'Wer würde am ehesten einen Pinguin aus dem Zoo schmuggeln?',
  'Wer würde in einer Spukvilla mit dem Geist eine WG gründen?',
  'Wer würde sich bei einem Kostümfest als Möbelstück verkleiden und gewinnen?',
  'Wer würde von einer Herde Schafe zum Anführer gewählt werden?',
  'Wer von euch würde auf einer einsamen Insel einen Volleyball als besten Freund haben?',
  'Wer würde am ehesten eine Doku über das geheime Leben von Socken drehen?',
  'Wer könnte sich mit einem Kaktus streiten und dabei verletzt werden?',
  'Wer würde auf einem Mittelaltermarkt dauerhaft einziehen und nie wieder gehen?',
  'Wer würde am ehesten Gemüse Namen geben und sich dann weigern, es zu essen?',
  'Wer von euch würde ein Wettrennen gegen eine Schnecke verlieren?',
  'Wer würde nach einem Blitzeinschlag glauben, Superkräfte zu haben?',
  'Wer würde sich als Erstes einem Zirkus anschließen und Clown werden?',
  'Wer würde am ehesten eine Hüpfburg als Hauptwohnsitz anmelden?',
  'Wer könnte im Weltall die Raumstation aus Versehen abschalten?',
  'Wer von euch würde ein Krokodil als Wachhund halten?',
  'Wer würde bei einer Schatzsuche nur alte Kronkorken finden und trotzdem jubeln?',
  'Wer würde eine Unterhaltung mit dem eigenen Spiegelbild eskalieren lassen?',
  'Wer würde am ehesten auf einer Party plötzlich anfangen, wie ein Delfin zu reden?',
  'Wer würde in einer Welt voller sprechender Tiere sofort Ärger mit den Katzen bekommen?',
  'Wer von euch würde einen Tornado jagen, nur um ein gutes Video zu bekommen?',
];
