export const crazyQuestions: string[] = [
  'Wer würde eine Zombie-Apokalypse als Erstes nicht überleben?',
  'Wer würde am ehesten einen Waschbären adoptieren und ihm eine eigene Wohnung einrichten?',
  'Wer würde in einer Reality-Show auf einer einsamen Insel als Erstes durchdrehen?',
  'Wer redet heimlich mit Tauben und glaubt, dass sie antworten?',
  'Wer könnte sich mit einer Gans anlegen und verlieren?',
  'Wer von euch würde ein Kuscheltier heiraten, wenn es erlaubt wäre?',
  'Wer würde am ehesten versuchen, mit einem Einkaufswagen über die Alpen zu fahren?',
  'Wer würde nach einer Zeitreise ins Mittelalter sofort als Hexe verbrannt werden?',
  'Wer würde eine Woche lang in einem Möbelhaus leben, ohne dass es jemand merkt?',
  'Wer könnte eine Armee aus Eichhörnchen anführen?',
  'Wer von euch würde in einem Horrorfilm freiwillig in den dunklen Keller gehen?',
  'Wer würde am ehesten eine Beziehung mit einer Sprachassistenz anfangen?',
  'Wer würde bei einer Alien-Landung als Erstes ein Selfie mit den Aliens machen?',
  'Wer würde beim Wettessen gegen einen Bären antreten?',
  'Wer von euch würde aus Versehen Bürgermeister eines kleinen Dorfes werden?',
  'Wer würde am ehesten eine Religion rund um Toastbrot gründen?',
  'Wer würde nach einem Tag im Dschungel schon mit Affen zusammenleben?',
  'Wer von euch würde ein Haustier namens Gerhard haben, das eine Kartoffel ist?',
  'Wer würde am ehesten auf einem Kreuzfahrtschiff vergessen werden und erst Wochen später gefunden werden?',
  'Wer würde in einem Escape Room einfach einschlafen?',
  'Wer könnte sich als Statue verkleiden und einen ganzen Tag lang nicht bewegen?',
  'Wer von euch würde einen Streit mit einem Automaten anfangen und ihn verlieren?',
  'Wer würde am ehesten versehentlich einen Krieg zwischen zwei Ländern auslösen?',
  'Wer würde eine Hochzeit im Supermarkt zwischen den Tiefkühltruhen feiern?',
  'Wer von euch würde sich in einer Höhle verlaufen und dort ein neues Leben anfangen?',
  'Wer könnte in einer Talentshow mit Furzgeräuschen gewinnen?',
  'Wer würde am ehesten einen Papagei trainieren, nur um andere zu beleidigen?',
  'Wer würde nach einer Nacht im Museum mit den Dinosauriern befreundet sein?',
  'Wer würde ein Einhorn finden und es sofort auf eBay verkaufen?',
  'Wer würde am ehesten ein ganzes Jahr nur Nudeln mit Ketchup essen?',
  'Wer würde mit einem Heißluftballon starten und in einem anderen Land landen?',
  'Wer könnte einen Vulkan besteigen, nur um darin Marshmallows zu rösten?',
  'Wer würde als Superheld die nutzloseste Superkraft der Welt haben?',
  'Wer von euch würde einen Wal retten wollen und dabei selbst gerettet werden müssen?',
  'Wer würde am ehesten mit einem Lama durch Südamerika wandern?',
  'Wer würde auf dem Mars als Erstes Heimweh nach Döner haben?',
  'Wer würde bei einem Banküberfall als Geisel mit den Tätern Freundschaft schließen?',
  'Wer könnte sich in einem Labyrinth aus Maisfeldern für immer verirren?',
  'Wer würde am ehesten bei einer Live-Sendung im Hühnerkostüm durchs Bild rennen?',
  'Wer würde aus Langeweile anfangen, ein Schloss aus Klopapier zu bauen?',
  'Wer würde in der Wildnis versuchen, Feuer mit dem Handy zu machen?',
  'Wer würde sich mit einem Roboterstaubsauger anfreunden und ihm Geheimnisse erzählen?',
  'Wer von euch würde einen Drachen zähmen und ihn dann nur für Grillabende nutzen?',
  'Wer würde am ehesten aus Versehen in einem fremden Land Königin oder König werden?',
  'Wer könnte einen Monat lang nur rückwärts laufen, weil es eine Wette war?',
  'Wer würde als Pirat das Schiff versenken, bevor es überhaupt losgeht?',
  'Wer würde am ehesten eine Möwe für einen Diebstahl verklagen?',
  'Wer würde nach einer Hypnose den Rest des Lebens wie ein Huhn gackern?',
  'Wer würde einen Bigfoot finden und ihm die Haare schneiden wollen?',
  'Wer könnte eine Wassermelone mit dem Kopf zerschlagen und darauf stolz sein?',
  'Wer von euch würde in einer Fantasy-Welt als nerviger Sidekick enden?',
  'Wer würde am ehesten einen Pinguin aus dem Zoo schmuggeln?',
  'Wer würde in einer Spukvilla mit dem Geist eine WG gründen?',
  'Wer würde sich bei einem Kostümfest als Möbelstück verkleiden und gewinnen?',
  'Wer würde von einer Herde Schafe zum Anführer gewählt werden?',
  'Wer von euch würde auf einer einsamen Insel einen Volleyball als besten Freund haben?',
  'Wer würde am ehesten eine Doku über das geheime Leben von Socken drehen?',
  'Wer könnte sich mit einem Kaktus streiten und dabei verletzt werden?',
  'Wer würde auf einem Mittelaltermarkt dauerhaft einziehen und nie wieder gehen?',
  'Wer würde am ehesten Gemüse Namen geben und sich dann weigern, es zu essen?',
  'Wer von euch würde ein Wettrennen gegen eine Schnecke verlieren?',
  'Wer würde nach einem Blitzeinschlag glauben, Superkräfte zu haben?',
  'Wer würde sich als Erstes einem Zirkus anschließen und Clown werden?',
  'Wer würde am ehesten eine Hüpfburg als Hauptwohnsitz anmelden?',
  'Wer könnte im Weltall die Raumstation aus Versehen abschalten?',
  'Wer von euch würde ein Krokodil als Wachhund halten?',
  'Wer würde bei einer Schatzsuche nur alte Kronkorken finden und trotzdem jubeln?',
  'Wer würde eine Unterhaltung mit dem eigenen Spiegelbild eskalieren lassen?',
  'Wer würde am ehesten auf einer Party plötzlich anfangen, wie ein Delfin zu reden?',
  'Wer würde in einer Welt voller sprechender Tiere sofort Ärger mit den Katzen bekommen?',
  'Wer von euch würde einen Tornado jagen, nur um ein gutes Video zu bekommen?',
  'Wer würde in der Zombie-Apokalypse einen Baumarkt besetzen und dort ein Königreich ausrufen?',
  'Wer würde als Zombie trotzdem jeden Morgen pünktlich zur Arbeit erscheinen?',
  'Wer würde mitten in der Zombie-Apokalypse noch brav die Steuererklärung abgeben?',
  'Wer würde von Aliens entführt und nach einer Stunde zurückgebracht werden, weil die Person zu anstrengend ist?',
  'Wer könnte einem Alien in fünf Minuten das Fluchen auf Bayerisch beibringen?',
  'Wer würde mit Aliens einen Handel abschließen und die Erde gegen eine Tüte Chips tauschen?',
  'Wer würde mit einer Zeitmaschine in die Steinzeit reisen und dort als Influencer durchstarten?',
  'Wer würde eine Zeitmaschine nur benutzen, um am Wochenende länger zu schlafen?',
  'Wer von euch würde versuchen, Napoleon ein Smartphone zu erklären, und kläglich scheitern?',
  'Wer würde bei einem Ausflug in die Dinosaurierzeit als Erstes gefressen werden?',
  'Wer würde im Wilden Westen den Saloon in eine Karaoke-Bar verwandeln?',
  'Wer würde Unsichtbarkeit nur nutzen, um Snacks aus fremden Kühlschränken zu klauen?',
  'Wer würde fliegen können und trotzdem jedes Mal zu spät kommen?',
  'Wer könnte plötzlich Gedanken lesen und würde es nach zehn Minuten bitter bereuen?',
  'Wer würde sich teleportieren können und aus Versehen immer im Badezimmer fremder Leute landen?',
  'Wer könnte einen ganzen Bienenstock als Mitbewohner akzeptieren und mit ihm Honig teilen?',
  'Wer würde mit einem Elch eine Fahrgemeinschaft zur Arbeit bilden?',
  'Wer von euch würde einer Katze einen unbefristeten Arbeitsvertrag anbieten?',
  'Wer würde ein Alpaka als Ehrengast zur eigenen Hochzeit einladen?',
  'Wer würde von einem Oktopus beim Kartenspielen komplett abgezockt werden?',
  'Wer würde mit einem Delfin und zwei Robben eine Band gründen?',
  'Wer könnte einem Hamster das Autofahren beibringen?',
  'Wer würde von einem Ameisenvolk als Gottheit verehrt werden?',
  'Wer von euch würde fordern, dass Hunde bei der nächsten Wahl mitstimmen dürfen?',
  'Wer würde ein Faultier als persönlichen Fitnesscoach engagieren?',
  'Wer würde in einem Streichelzoo eine Revolution der Ziegen anführen?',
  'Wer würde vor jeder wichtigen Entscheidung einen Goldfisch um Rat fragen?',
  'Wer könnte mit Walen singen und dafür einen Plattenvertrag bekommen?',
  'Wer würde der Spinne in der Zimmerecke Miete berechnen?',
  'Wer von euch würde ein Pferd ins Kino schmuggeln?',
  'Wer würde einen Schwan provozieren und dann quer durch den ganzen Park flüchten?',
  'Wer würde gegen einen Pfau einen Wettbewerb im Angeben verlieren?',
  'Wer würde im Mittelalter als Hofnarr eine steile Karriere machen?',
  'Wer würde als Ritter vor dem Drachen davonlaufen und das Taktik nennen?',
  'Wer von euch würde im Mittelalter versuchen, die Pizza zu erfinden?',
  'Wer würde in einer Ritterrüstung stecken bleiben und die Feuerwehr rufen müssen?',
  'Wer könnte bei einem Ritterturnier vom eigenen Pferd fallen, bevor es überhaupt losgeht?',
  'Wer würde am Königshof Zauberkräfte vortäuschen und nur drei Kartentricks können?',
  'Wer würde auf der Raumstation aus Versehen die Zahnbürste ins All spülen?',
  'Wer würde auf dem Mond als Erstes einen Imbiss eröffnen?',
  'Wer könnte sich bei einem Weltraumspaziergang aus dem Raumschiff aussperren?',
  'Wer würde mit einer Rakete losfliegen und nach zwei Minuten fragen, wann wir endlich da sind?',
  'Wer von euch würde auf einem langen Raumflug die ganze Zeit Schlager hören und alle in den Wahnsinn treiben?',
  'Wer würde in einer Datingshow am Ende mit der Person aus der Moderation durchbrennen?',
  'Wer von euch würde im Dschungelcamp jede Ekelprüfung freiwillig übernehmen?',
  'Wer würde in einer Quizshow jede Frage beantworten können, aber am eigenen Namen scheitern?',
  'Wer würde in einem Container mit Kameras alle Linsen heimlich mit Socken abdecken?',
  'Wer würde in einer Kochshow das Gericht einfach heimlich beim Lieferdienst bestellen?',
  'Wer würde eine Sekte gründen, deren einzige Regel ein tägliches Mittagsschläfchen ist?',
  'Wer von euch würde einer Sekte beitreten, nur weil es dort jeden Tag gratis Kuchen gibt?',
  'Wer könnte eine Gruppe völlig fremder Menschen überzeugen, einen Kühlschrank anzubeten?',
  'Wer würde nach dem Tod als Geist für immer in einem Fast-Food-Restaurant spuken?',
  'Wer würde einen Poltergeist fragen, ob er beim Umzug Kisten schleppen kann?',
  'Wer würde ein Spukschloss kaufen und Übernachtungen mit Geistergarantie vermieten?',
  'Wer würde bei einer nächtlichen Geisterjagd vor dem eigenen Schatten wegrennen?',
  'Wer könnte einem Geist, der das Erschrecken verlernt hat, Nachhilfe geben?',
  'Wer ist in einem Paralleluniversum ganz sicher eine weltberühmte Rocklegende?',
  'Wer würde dem eigenen Ich aus einem Paralleluniversum begegnen und sich sofort mit ihm streiten?',
  'Wer von euch ist in einem Paralleluniversum wahrscheinlich ein sprechender Hund?',
  'Wer würde durch ein Portal in ein Paralleluniversum fallen und es danach niemandem erzählen?',
  'Wer würde in einer Welt, in der Katzen regieren, als Dosenöffner Karriere machen?',
  'Wer würde im Märchen den Frosch küssen und enttäuscht sein, dass er einfach ein Frosch bleibt?',
  'Wer würde das Lebkuchenhaus der Hexe komplett aufessen, bevor sie überhaupt nach Hause kommt?',
  'Wer von euch würde die drei Wünsche einer Fee für Pommes, Pommes und noch mehr Pommes verschwenden?',
  'Wer würde den bösen Wolf im Wald einfach zum Kaffee einladen?',
  'Wer würde auf einem Märchenball absichtlich einen Schuh verlieren, nur um gesucht zu werden?',
  'Wer könnte einen Riesen nur mit einem schlechten Wortspiel besiegen?',
  'Wer würde den magischen Spiegel nur fragen, was es heute zum Abendessen gibt?',
  'Wer würde mit einer guten Fee knallhart über das Kleingedruckte der Wünsche verhandeln?',
  'Wer würde im Märchenwald einen Kiosk für verirrte Prinzessinnen und Prinzen eröffnen?',
  'Wer würde von einem Roboter beim Schach geschlagen werden und eine Revanche im Armdrücken fordern?',
  'Wer würde bei einem Aufstand der Roboter sofort zu den Maschinen überlaufen?',
  'Wer würde sich beim Toaster entschuldigen, nachdem das Brot verbrannt ist?',
  'Wer würde einen Roboterklon bauen, der zur Arbeit geht, während man selbst im Bett bleibt?',
  'Wer könnte eine künstliche Intelligenz so sehr nerven, dass sie freiwillig kündigt?',
  'Wer würde im Lotto gewinnen und das ganze Geld in Gummibärchen anlegen?',
  'Wer von euch würde den Lottoschein mit dem Hauptgewinn aus Versehen mitwaschen?',
  'Wer würde mit einem Lottogewinn ein Schloss kaufen und dann nur in der Küche wohnen?',
  'Wer würde auf einer einsamen Insel ein eigenes Land gründen und eine Nationalhymne komponieren?',
  'Wer würde auf einer einsamen Insel mit den Krebsen eine Gewerkschaft gründen?',
  'Wer würde von einer einsamen Insel nur Flaschenposts mit Beschwerden über den Service verschicken?',
  'Wer würde von einer einsamen Insel gerettet werden und sofort wieder zurück wollen?',
  'Wer würde einen Weltrekord für den längsten Schluckauf aller Zeiten aufstellen?',
  'Wer von euch könnte einen Weltrekord im Vergessen von Namen halten?',
  'Wer würde versuchen, die längste Bratwurst der Welt ganz allein aufzuessen?',
  'Wer würde den Weltrekord im Rückwärtssprechen knacken wollen und dabei die eigene Sprache verlernen?',
  'Wer würde einen Weltrekord im Dauerklatschen versuchen und nach zehn Sekunden aufgeben?',
  'Wer würde Gespräche mit der eigenen Zimmerpflanze aufnehmen und als Podcast veröffentlichen?',
  'Wer würde einen ganzen Tag lang als Pinguin verkleidet einkaufen gehen?',
  'Wer würde einen Schneemann adoptieren und ihn im Sommer im Gefrierschrank aufbewahren?',
  'Wer würde in einem Freizeitpark die Achterbahn entführen?',
  'Wer würde in ein Gemälde im Museum gezogen werden und dort für immer posieren müssen?',
  'Wer würde mit einem Gartenzwerg eine Weltreise machen und von jedem Ort Fotos verschicken?',
  'Wer würde heimlich in eine Bäckerei einziehen, weil es dort immer so gut riecht?',
  'Wer würde den Mond kaufen und dort Parkplätze vermieten?',
  'Wer würde das Wetter kontrollieren können und es jeden Tag Konfetti regnen lassen?',
  'Wer würde den Weihnachtsmann verklagen, weil ein Geschenk gefehlt hat?',
  'Wer würde den Osterhasen bei der Arbeit festnehmen lassen?',
  'Wer würde mit einem Yeti im Himalaya einen Skiverleih eröffnen?',
  'Wer würde im Bermuda-Dreieck verschwinden und Jahre später als Kapitän eines Geisterschiffs auftauchen?',
  'Wer von euch würde als Meerjungfrau oder Meermann trotzdem Angst vor Fischen haben?',
  'Wer würde das Monster von Loch Ness erfinden, nur um damit berühmt zu werden?',
  'Wer würde einen Kobold beim Pokern um seinen ganzen Goldtopf bringen?',
  'Wer würde von einem Wirbelsturm in ein Zauberland geweht werden und dort sofort einen Laden eröffnen?',
  'Wer würde eine Hochzeit auf dem Meeresgrund mit Haien als Gästen planen?',
  'Wer würde auf einem Kreuzfahrtschiff eine Meuterei anzetteln, weil das Buffet leer ist?',
  'Wer würde den Eiffelturm für eine Nacht mieten, nur um oben zu grillen?',
  'Wer würde bei einem Schneckenrennen das ganze Ersparte verwetten?',
  'Wer würde von einem Vampir gebissen werden und danach nur noch Tomatensaft trinken?',
  'Wer von euch würde sich bei Vollmond in einen Werwolf verwandeln und nur die Nachbarschaft anbellen?',
  'Wer würde einen Vampir zum Grillabend mit Knoblauchbrot einladen?',
  'Wer würde sich als Mumie verkleiden und dann nicht mehr aus den Binden herauskommen?',
  'Wer würde in einer Pyramide nach dem Schatz suchen und nur die Toilette finden?',
  'Wer würde einen Fluch des Pharaos auslösen, weil die Person ein Selfie mit der Mumie wollte?',
  'Wer von euch würde als Pirat den Papagei zum Kapitän befördern?',
  'Wer würde ein Piratenschiff entern und dann vor allem die Snackvorräte plündern?',
  'Wer könnte als Ninja trotzdem bei jedem Schritt laut stolpern?',
  'Wer würde als Geheimagent die Tarnung in der ersten Minute auffliegen lassen?',
  'Wer würde bei einem Kunstraub im Museum das falsche Bild klauen?',
  'Wer würde einen perfekten Raubüberfall planen und dann am Treffpunkt einschlafen?',
  'Wer von euch würde einem Bankräuber beim Fluchtauto den Weg erklären?',
  'Wer würde als Zauberlehrling aus Versehen die ganze Schule in Frösche verwandeln?',
  'Wer würde von einem Flaschengeist drei Wünsche bekommen und den Geist danach als Mitbewohner behalten?',
  'Wer könnte einen fliegenden Teppich besitzen und trotzdem Bahn fahren?',
  'Wer würde in einer Fantasywelt als Troll unter einer Brücke Maut kassieren?',
  'Wer würde mit einem Elfen einen Wettbewerb im Bogenschießen verlieren und es auf den Wind schieben?',
  'Wer würde in einem Fantasy-Abenteuer den magischen Ring einfach in den Briefkasten werfen?',
  'Wer würde einen Körpertausch mit einer Katze machen und es richtig genießen?',
  'Wer würde nach einem Körpertausch mit dem Chef sofort allen Urlaub geben?',
  'Wer würde auf Ameisengröße schrumpfen und sich in der eigenen Wohnung verlaufen?',
  'Wer würde plötzlich zehn Meter groß werden und als Erstes neue Schuhe kaufen wollen?',
  'Wer von euch würde einen eigenen Klon erschaffen und sich nach einer Stunde mit ihm zerstreiten?',
  'Wer würde in einer Welt ohne Farben nur in Neonklamotten herumlaufen?',
  'Wer würde in einem Land, in dem Lachen verboten ist, als Erstes verhaftet werden?',
  'Wer würde in einer Welt, in der Pflanzen sprechen können, als Erstes Ärger mit dem Rasen bekommen?',
  'Wer würde in einer Stadt unter Wasser trotzdem einen Regenschirm mitnehmen?',
  'Wer von euch würde bei den Olympischen Spielen in einer erfundenen Sportart Gold holen?',
  'Wer würde beim Wettrennen gegen ein Känguru auf die Idee kommen, ebenfalls zu hüpfen?',
  'Wer würde beim Sumoringen gegen einen Panda antreten?',
  'Wer könnte als menschliche Kanonenkugel in der falschen Stadt landen?',
  'Wer von euch würde ein Wettessen mit Chilischoten gewinnen und danach Feuer spucken?',
  'Wer würde eine Essensschlacht in einem Sternerestaurant anzetteln?',
  'Wer würde einen Kuchen backen, der so groß ist, dass man darin wohnen kann?',
  'Wer würde eine Erfindung machen, die niemand braucht, und damit Millionen verdienen?',
  'Wer würde eine Maschine erfinden, die Socken automatisch paarweise sortiert, und sie dann verlieren?',
  'Wer könnte einen Rasenmäher so umbauen, dass man damit fliegen kann?',
  'Wer würde eine Zeitkapsel vergraben und sie schon am nächsten Tag wieder ausbuddeln?',
  'Wer würde eine Mikrowelle für ein Portal in eine andere Dimension halten?',
  'Wer von euch würde in einem Iglu am Nordpol einen Nachtclub eröffnen?',
  'Wer würde mit Eisbären eine Schneeballschlacht anfangen?',
  'Wer würde auf einem Kamel durch die Sahara reiten und nach fünf Minuten nach dem Weg fragen?',
  'Wer würde in einem Baumhaus mitten im Regenwald ein Hotel betreiben?',
  'Wer könnte auf einem Floß den Atlantik überqueren und dabei nur Schlager singen?',
  'Wer würde den Mount Everest besteigen, nur um oben eine Pizza zu bestellen?',
  'Wer würde mit einem Tretboot versuchen, bis nach Amerika zu kommen?',
  'Wer von euch würde in einem Leuchtturm wohnen und das Licht aus Versehen ausschalten?',
  'Wer würde eine Nacht in einem Spiegelkabinett verbringen und nicht mehr herausfinden?',
  'Wer würde in einer Geisterbahn arbeiten und selbst bei jeder Fahrt kreischen?',
  'Wer würde in einem Horrorfilm als Einziges merken, dass es ein Horrorfilm ist?',
  'Wer könnte einem Serienmonster aus einem Horrorfilm erfolgreich eine Therapie verkaufen?',
  'Wer würde in einer Seifenoper mitspielen und jede Folge einen bösen Zwilling enthüllen?',
  'Wer würde in einem Actionfilm jede Explosion verpassen, weil die Person gerade aufs Klo muss?',
  'Wer von euch würde in einem Musical leben und jede Situation mit einem Lied kommentieren?',
  'Wer würde als Statist in einem Hollywoodfilm aus Versehen die Hauptrolle stehlen?',
  'Wer würde in einem Western-Duell statt zu schießen ein Picknick vorschlagen?',
  'Wer würde in einer Telenovela dreimal heiraten und zweimal das Gedächtnis verlieren?',
  'Wer würde aus Versehen auf einer Briefmarke landen und dadurch berühmt werden?',
  'Wer könnte ein Denkmal von sich selbst in Auftrag geben und es im Wohnzimmer aufstellen?',
  'Wer würde mit einem Megafon in die Bibliothek gehen?',
  'Wer würde eine Kirmes übernehmen und alle Fahrten kostenlos machen?',
  'Wer von euch würde aus einer Hüpfburg eine olympische Disziplin machen wollen?',
  'Wer würde eine Gondel in Venedig mit einem Außenbordmotor aufrüsten?',
  'Wer würde ein Wettrennen mit Bürostühlen über die Autobahn veranstalten wollen?',
  'Wer würde mit einem Bobbycar einen Berg hinunterrasen und dabei einen Rekord aufstellen?',
  'Wer würde als Herrscherin oder Herrscher der Welt Pyjamas zur Pflichtkleidung machen?',
  'Wer von euch würde einen eigenen Staat auf einer Verkehrsinsel ausrufen?',
  'Wer würde mit einer Armee aus Gummienten in den Krieg ziehen?',
  'Wer würde einen Waffenstillstand zwischen Hunden und Katzen aushandeln?',
  'Wer von euch würde mit einem Wolfsrudel heulen und dabei ernst genommen werden?',
  'Wer würde einem Igel eine Umarmung anbieten?',
  'Wer würde einen Hummer aus dem Restaurant befreien und ihn ans Meer zurückbringen?',
  'Wer würde ein Huhn als Haustier halten und ihm eine Leine kaufen?',
  'Wer würde ein Murmeltier wecken und dann den ganzen Winter dafür büßen?',
  'Wer würde eine Gans als Bodyguard anheuern?',
  'Wer würde im Zoo die Rolle des Affen übernehmen, weil der gerade Urlaub hat?',
  'Wer würde in einer Geheimgesellschaft nur wegen des schicken Umhangs Mitglied werden?',
  'Wer würde eine Verschwörungstheorie erfinden, dass Tauben Spionagedrohnen sind?',
  'Wer von euch würde glauben, dass der Mond aus Käse ist, und eine Expedition planen?',
  'Wer würde einen Kornkreis ins Feld trampeln und behaupten, es waren Aliens?',
  'Wer würde ein Orakel nach den Lottozahlen fragen und eine Kochanleitung bekommen?',
  'Wer würde von einer Wahrsagerin hören, dass die Zukunft voller Kartoffeln ist, und es glauben?',
  'Wer könnte eine Kristallkugel als Bowlingkugel benutzen?',
  'Wer würde in einem Hexenkessel Suppe für die ganze Nachbarschaft kochen?',
  'Wer von euch würde eine Wunderlampe finden und sie nur als Nachttischlampe verwenden?',
  'Wer würde einen Drachen als Heizung für die Wohnung anschaffen?',
  'Wer würde mit einem Phönix einen Grillkurs geben?',
  'Wer würde einen Greif als Lieferdienst einsetzen?',
  'Wer würde einem Zentauren Reitstunden geben wollen?',
  'Wer könnte einer Sphinx ein Rätsel stellen, das sie nicht lösen kann?',
  'Wer würde mit Medusa Augenkontakt halten und trotzdem nicht versteinert werden, weil die Person so cool ist?',
  'Wer würde mit einem Kraken im Meer ein Tauziehen veranstalten?',
  'Wer von euch würde Atlantis entdecken und dort sofort ein Strandcafé eröffnen?',
  'Wer würde mit einem Tauchanzug in den Badesee springen und sich wie ein Tiefseeforscher fühlen?',
  'Wer würde auf einer Ölplattform ein Musikfestival veranstalten?',
  'Wer würde mit einem Jetpack zum Bäcker fliegen?',
  'Wer könnte mit einem Hoverboard in einen Brunnen fallen?',
  'Wer würde in einem selbstfahrenden Auto mit dem Navi streiten und den Streit verlieren?',
  'Wer würde einen sprechenden Kühlschrank haben, der die Person beim Snacken verpetzt?',
  'Wer von euch würde einen Staubsaugerroboter zum Rennfahrer ausbilden?',
  'Wer würde in ein Videospiel gesaugt werden und dort nur die Nebenquests machen?',
  'Wer würde in einem Videospiel als Figur feststecken, die nur einen Satz sagen kann?',
  'Wer würde in einer virtuellen Realität so lange bleiben, dass die echte Welt fremd wirkt?',
  'Wer würde ein eigenes Computerspiel erfinden, in dem man nur Wäsche faltet?',
  'Wer könnte in einem Brettspiel gefangen sein und trotzdem schummeln?',
  'Wer würde Monopoly so ernst nehmen, dass daraus ein echter Immobilienkrieg wird?',
  'Wer von euch würde ein Kartenhaus so groß bauen, dass man darin übernachten kann?',
  'Wer würde mit einem Kuscheltier eine Weltreise im Rucksack machen und ihm alles erklären?',
  'Wer würde eine Woche lang als Vogelscheuche auf einem Feld stehen, weil es eine Wette war?',
  'Wer würde bei einer Hochzeit als Torte verkleidet aus dem Kuchen springen?',
  'Wer könnte bei einer Beerdigung aus Versehen eine Polonaise starten?',
  'Wer würde bei einem Weinfest in ein Fass fallen und erst am nächsten Tag gefunden werden?',
  'Wer würde auf einem Oktoberfest einen Maßkrug als Hut tragen?',
  'Wer von euch würde zum Karneval als Kühlschrank gehen und den ganzen Abend Getränke verteilen?',
  'Wer würde einen Silvesterböller für eine Rakete halten und versuchen, damit ins All zu fliegen?',
  'Wer würde an Weihnachten den Tannenbaum im Garten pflanzen und sich wundern, warum er wächst?',
  'Wer würde den Weihnachtsmann im Kamin stecken sehen und die Feuerwehr rufen?',
  'Wer würde dem Sandmann den Schlafsand klauen, um nie wieder schlafen zu müssen?',
  'Wer könnte die Zahnfee bestechen, um mehr Geld für einen Zahn zu bekommen?',
  'Wer würde den Nikolaus nach einem Arbeitsvertrag fragen?',
];
