export const deepQuestions: string[] = [
  'Wer von euch würde nachts um drei sofort kommen, wenn man anruft?',
  'Wem in dieser Runde würdet ihr euer größtes Geheimnis anvertrauen?',
  'Wer ist die loyalste Person hier am Tisch?',
  'Wer zeigt Gefühle am wenigsten, obwohl innen viel passiert?',
  'Wer ist viel mutiger, als man auf den ersten Blick denkt?',
  'Wer hat sich in den letzten Jahren am meisten verändert?',
  'Wer hört am besten zu, wenn es einem schlecht geht?',
  'Wer von euch gibt die ehrlichsten Ratschläge, auch wenn sie unbequem sind?',
  'Bei wem fühlt man sich sofort wohl und angenommen?',
  'Wer denkt am meisten über das Leben nach?',
  'Wer würde am ehesten für eine Freundschaft über den eigenen Schatten springen?',
  'Wer hat das größte Herz in dieser Runde?',
  'Wer kann am besten verzeihen?',
  'Wer von euch merkt als Erstes, wenn es jemandem nicht gut geht?',
  'Wer würde am ehesten einen Traum verfolgen, auch wenn alle dagegen sind?',
  'Wer ist die Person, die immer zu ihrem Wort steht?',
  'Wer versteckt Unsicherheit am besten hinter einem Lächeln?',
  'Wer ist am meisten an sich selbst gewachsen?',
  'Wen würdet ihr bei einem kompletten Neuanfang am liebsten an eurer Seite haben?',
  'Wer behält die eigene Meinung am häufigsten für sich?',
  'Wer ist der ruhige Fels in der Brandung, wenn alles chaotisch wird?',
  'Wer würde ein Geheimnis auch nach zwanzig Jahren noch für sich behalten?',
  'Wer von euch ist strenger mit sich selbst als mit anderen?',
  'Wer bringt andere am ehesten dazu, an sich selbst zu glauben?',
  'Wer hat die beste Intuition für Menschen?',
  'Wer würde sich am ehesten für jemanden einsetzen, der ungerecht behandelt wird?',
  'Wer von euch hat die meisten unausgesprochenen Träume?',
  'Wen würdet ihr nach einem schlechten Tag als Erstes anrufen?',
  'Wer hat euch schon mal mit einer ganz neuen Seite überrascht?',
  'Wer wäre am ehesten bereit, für eine Überzeugung alles zu riskieren?',
  'Wer kann am besten zugeben, einen Fehler gemacht zu haben?',
  'Wer ist im Herzen viel weicher, als die Fassade vermuten lässt?',
  'Wer kümmert sich am meisten um andere und vergisst dabei sich selbst?',
  'Auf wessen Meinung gebt ihr am meisten?',
  'Wer würde am ehesten einen sicheren Job kündigen, um etwas Eigenes zu wagen?',
  'Wer von euch hat die schönste Art, Dankbarkeit zu zeigen?',
  'Wer ist der Grund, warum diese Gruppe so gut zusammenhält?',
  'Wer von euch hat die größte innere Stärke?',
  'Wer ist am ehrlichsten zu sich selbst?',
  'Wer hat in letzter Zeit den mutigsten Schritt gewagt?',
  'Wer würde am ehesten ein Jahr lang allein um die Welt reisen?',
  'Wer findet immer die richtigen Worte in schwierigen Momenten?',
  'Wer von euch wird am meisten unterschätzt?',
  'Wen würdet ihr bei einer wichtigen Lebensentscheidung zuerst um Rat fragen?',
  'Wer macht nach einem Streit am ehesten den ersten Schritt?',
  'Wer hat die meiste Geduld mit anderen Menschen?',
  'Wer von euch hat ein Talent, das viel zu wenig gesehen wird?',
  'Wer würde am ehesten einem fremden Menschen in Not spontan helfen?',
  'Wer ist am meisten man selbst, egal wer gerade zuschaut?',
  'Wer von euch würde für die Menschen hier am weitesten fahren?',
  'Wer schreibt die ehrlichsten und schönsten Nachrichten zum Geburtstag?',
  'Wer ist innerlich am meisten mit sich im Reinen?',
  'Wer würde am ehesten zugeben, gerade Angst zu haben?',
  'Wer ist die Person, die nie jemanden zurücklässt?',
  'Wer denkt nachts am längsten über Gespräche nach?',
  'Wer würde am ehesten eine Freundschaft retten, die schon fast verloren war?',
  'Wer hat euch schon mal etwas beigebracht, das ihr nie vergessen werdet?',
  'Wer von euch kann am besten schweigen, wenn Worte nicht helfen?',
  'Wer zeigt Zuneigung eher durch Taten als durch Worte?',
  'Auf wen kann man sich in einer Krise am meisten verlassen?',
  'Wer würde am ehesten einen Brief an das eigene jüngere Ich schreiben?',
  'Wer hat die stärksten Werte und lebt sie auch?',
  'Wer von euch hat schon die meisten Herausforderungen still gemeistert?',
  'Wer wäre am ehesten bereit, die eigene Meinung nach einem guten Argument zu ändern?',
  'Mit wem kann man stundenlang über wirklich alles reden?',
  'Wer gibt am meisten, ohne etwas zurückzuerwarten?',
  'Wer würde am ehesten zugeben, jemanden zu vermissen?',
  'Wer von euch ist am stolzesten auf die eigenen Wurzeln?',
  'Wer hat das Leben von jemandem hier am meisten positiv beeinflusst?',
  'Wer ist euch über die Jahre am meisten ans Herz gewachsen?',
  'Wer würde am ehesten den Fehler einer befreundeten Person auf sich nehmen?',
  'Wer bleibt auch in schwierigen Zeiten am optimistischsten?',
  'Mit wem aus dieser Runde würdet ihr am liebsten gemeinsam alt werden?',
  'Wem würdet ihr ohne Bedenken eure Kinder für ein Wochenende anvertrauen?',
  'Wer würde in einer Diskussion am ehesten zu euch halten, auch wenn ihr falschliegt?',
  'Wer von euch spricht nie schlecht über Leute, die gerade nicht da sind?',
  'Wer hält Freundschaften auch über große Entfernungen am besten am Leben?',
  'Wer würde am ehesten für euch lügen, um euch zu schützen?',
  'Wer von euch hat am längsten gebraucht, um anderen wirklich zu vertrauen?',
  'Wer würde euch bei einem Umzug helfen, ohne dass ihr fragen müsst?',
  'Wer meldet sich zuverlässig, wenn man länger nichts voneinander gehört hat?',
  'Wer würde bei einem Streit zwischen zwei Leuten aus der Gruppe am fairsten vermitteln?',
  'Wer verteidigt die Gruppe am lautesten, wenn jemand von außen lästert?',
  'Wer würde am ehesten allein auf ein Konzert gehen und es richtig genießen?',
  'Wer traut sich am ehesten, als einzige Stimme in der Gruppe zu widersprechen?',
  'Wer würde am ehesten in ein fremdes Land ziehen, ohne dort jemanden zu kennen?',
  'Wer spricht unangenehme Themen am mutigsten an?',
  'Wer hat den Mut, um Hilfe zu bitten, wenn es nötig ist?',
  'Wer würde am ehesten eine lange Beziehung beenden, weil es sich nicht mehr richtig anfühlt?',
  'Wer hat schon mal eine Entscheidung getroffen, die alle für verrückt hielten, und recht behalten?',
  'Wer von euch wagt sich am ehesten an Dinge, die noch nie jemand in der Familie gemacht hat?',
  'Wer würde am ehesten Geld zurückgeben, das versehentlich zu viel ausgezahlt wurde?',
  'Wer kauft am ehesten bewusst nachhaltig ein, auch wenn es mehr kostet?',
  'Wer würde auf einen gut bezahlten Job verzichten, weil er nicht zu den eigenen Werten passt?',
  'Wer behandelt Menschen im Service am respektvollsten?',
  'Wer würde am ehesten ehrenamtlich arbeiten, wenn Zeit keine Rolle spielt?',
  'Wer von euch hat die klarste Vorstellung davon, was im Leben wirklich zählt?',
  'Wer spendet am ehesten, ohne es jemandem zu erzählen?',
  'Wer von euch würde auch dann ehrlich bleiben, wenn eine Lüge nie auffliegen würde?',
  'Wem ist die Meinung anderer am wenigsten wichtig, solange das eigene Gewissen rein ist?',
  'Wer achtet am meisten darauf, wie die eigenen Entscheidungen andere Menschen betreffen?',
  'Wer von euch weint am ehesten bei einem Film?',
  'Wer spricht am offensten aus, wie viel die Freundschaften hier bedeuten?',
  'Wer umarmt am liebsten und am längsten?',
  'Wer kann am besten in Worte fassen, was andere nur fühlen?',
  'Wer von euch zeigt Freude am ansteckendsten?',
  'Wer braucht nach einem Streit am längsten, um wieder runterzukommen?',
  'Wer schluckt Ärger am ehesten runter, statt ihn anzusprechen?',
  'Wer hat das ehrlichste Gesicht, auf dem man jede Stimmung ablesen kann?',
  'Wer von euch würde am ehesten einen langen Brief statt einer kurzen Nachricht schreiben?',
  'Wer zeigt am offensten, wenn etwas wehgetan hat?',
  'Wer ist am ehesten gerührt von kleinen Gesten?',
  'Wer freut sich am ehrlichsten für den Erfolg anderer?',
  'Wer kocht für andere, wenn Worte nicht mehr reichen?',
  'Wer würde am ehesten zugeben, eifersüchtig zu sein?',
  'Wer würde dem eigenen Ich von vor zehn Jahren am meisten imponieren?',
  'Wer hat eine Gewohnheit abgelegt, auf die alle stolz sein können?',
  'Wer von euch kommt am besten mit großen Veränderungen klar?',
  'Wer hält am längsten an alten Gewohnheiten fest?',
  'Wer von euch erfindet sich am ehesten alle paar Jahre neu?',
  'Wer würde am ehesten ein ganz neues Hobby anfangen und dabei richtig aufblühen?',
  'Wer von euch ist ruhiger geworden, als man es je erwartet hätte?',
  'Wer hat in letzter Zeit am meisten Neues ausprobiert?',
  'Wer von euch tut sich am schwersten damit, Dinge loszulassen?',
  'Wer arbeitet am härtesten für die eigenen Ziele, auch wenn es keiner sieht?',
  'Wer gibt am wenigsten schnell auf?',
  'Wer misst Erfolg am wenigsten an Geld?',
  'Wer hat den größten inneren Antrieb?',
  'Wer feiert die eigenen Erfolge am wenigsten, obwohl es allen Grund dafür gäbe?',
  'Wer von euch zweifelt am meisten an sich, obwohl es keinen Grund dafür gibt?',
  'Wer kann Komplimente am schlechtesten annehmen?',
  'Wer vergleicht sich am häufigsten mit anderen?',
  'Wer würde am ehesten zugeben, sich manchmal fehl am Platz zu fühlen?',
  'Wer denkt vor wichtigen Entscheidungen am längsten hin und her?',
  'Wer hat am meisten Angst, andere zu enttäuschen?',
  'Wer zieht Dinge trotz Angst vorm Scheitern am konsequentesten durch?',
  'Wen würdet ihr bei Liebeskummer als Erstes um Rat fragen?',
  'Wer gibt die besten Ratschläge, hält sich selbst aber nie daran?',
  'Wer hat den weisesten Spruch für jede Lebenslage parat?',
  'Wer hört erst zu und gibt dann einen Rat, statt sofort Lösungen anzubieten?',
  'Wer von euch hat schon mal einen Rat gegeben, der euer Leben verändert hat?',
  'Wer wäre das beste Vorbild für ein jüngeres Familienmitglied?',
  'Wer trifft große Entscheidungen am ehesten aus dem Bauch heraus?',
  'Wer bereut am wenigsten von den eigenen Entscheidungen?',
  'Wer würde am ehesten die eigene Karriere für die Familie zurückstellen?',
  'Wer würde am ehesten ein Sabbatjahr nehmen, um herauszufinden, was wirklich zählt?',
  'Wer lässt das Leben am ehesten einfach passieren?',
  'Wer würde am ehesten ein Kind adoptieren?',
  'Wer hat schon mal eine Abzweigung im Leben genommen, die alles verändert hat?',
  'Wer von euch ruft am regelmäßigsten bei der Familie an?',
  'Wer ist der eigenen Familie am ähnlichsten, auch wenn es ungern zugegeben wird?',
  'Wer von euch hat die engste Bindung zu den Geschwistern?',
  'Wer würde die schönsten Familientraditionen weitergeben?',
  'Wer von euch würde die geduldigsten Eltern abgeben?',
  'Wer erzählt am liebsten Geschichten aus der eigenen Kindheit?',
  'Wer ist in der eigenen Familie das schwarze Schaf mit dem größten Herzen?',
  'Wer hat von den Großeltern die wertvollste Lebensweisheit mitbekommen?',
  'Wer behandelt Freunde am meisten wie Familie?',
  'Wer hat das beste Verhältnis zu den Eltern der anderen hier?',
  'Wer hat die längste Freundschaft in dieser Runde?',
  'Wer bringt am ehesten neue Leute in die Gruppe?',
  'Wer erinnert sich an die meisten Kleinigkeiten, die man mal erzählt hat?',
  'Wer von euch hat schon am meisten für diese Gruppe geopfert?',
  'Wer plant am zuverlässigsten die nächsten gemeinsamen Treffen?',
  'Wer kennt euch so gut, dass Worte manchmal überflüssig sind?',
  'Wer ist die Person, bei der man nie eine Maske tragen muss?',
  'Wer von euch würde eine Freundschaft niemals wegen Geld aufs Spiel setzen?',
  'Wen habt ihr beim ersten Treffen völlig anders eingeschätzt, als die Person wirklich ist?',
  'Wer ist die beste Gesellschaft auf einer langen Autofahrt durch die Nacht?',
  'Wer stellt die besten Nachfragen, wenn man etwas erzählt?',
  'Wer fragt Tage später nach, wie ein wichtiges Gespräch gelaufen ist?',
  'Wer hört auch bei langweiligen Geschichten mit echtem Interesse zu?',
  'Wer hört auch das, was zwischen den Zeilen gesagt wird?',
  'Wer von euch erzählt am wenigsten über sich, weil immer nach den anderen gefragt wird?',
  'Wer kann am schlechtesten lügen?',
  'Wer von euch ist ehrlich, ohne dabei verletzend zu sein?',
  'Wer würde am ehesten eine unangenehme Wahrheit beichten, bevor sie rauskommt?',
  'Wer gibt am ehesten zu, etwas nicht zu wissen?',
  'Wer ist zu ehrlich für das eigene Wohl?',
  'Wer ist auch in der Liebe kompromisslos ehrlich?',
  'Wer erzählt Geschichten genau so, wie sie passiert sind, ohne zu übertreiben?',
  'Wer von euch hängt am meisten an alten Erinnerungsstücken?',
  'Wer würde am ehesten ein Fotoalbum über die gemeinsame Zeit gestalten?',
  'Wer würde am ehesten noch einmal in die Schulzeit zurückwollen?',
  'Wer von euch erinnert sich am genauesten an den ersten gemeinsamen Abend?',
  'Wer bekommt bei alten Liedern am schnellsten Gänsehaut?',
  'Wer vermisst die eigene Kindheit am meisten?',
  'Wer scrollt am häufigsten durch alte Chatverläufe?',
  'Wer von euch wird am ehesten einen Lebenstraum wirklich wahr machen?',
  'Wer hat sich als Kind die verrücktesten Dinge für das Erwachsensein ausgemalt?',
  'Wer hat schon einen Kindheitstraum tatsächlich verwirklicht?',
  'Wer von euch hat eine Liste mit Lebenszielen und arbeitet sie wirklich ab?',
  'Wer würde am ehesten eine weite Reise nur für einen einzigen besonderen Moment machen?',
  'Wer hat den verrücktesten Traum für die Zeit nach dem Berufsleben?',
  'Wer von euch würde am ehesten noch ein Instrument lernen, nur aus Liebe zur Musik?',
  'Wer würde mit einem Lottogewinn am meisten Gutes tun?',
  'Wer von euch kann am besten im Moment leben?',
  'Wer ist am dankbarsten für die kleinen Dinge im Leben?',
  'Wer sollte sich öfter mal eine echte Pause gönnen?',
  'Wer kann am besten Nein sagen, ohne sich schlecht zu fühlen?',
  'Wer schaut am liebevollsten auf die eigene Vergangenheit zurück?',
  'Wer findet am ehesten in der Natur zu sich selbst?',
  'Wer kann am besten genießen, ohne ein schlechtes Gewissen zu haben?',
  'Wer schreibt am ehesten Tagebuch, um die eigenen Gedanken zu ordnen?',
  'Wer lacht am ehesten über sich selbst?',
  'Wer von euch nimmt das Leben am leichtesten, ohne oberflächlich zu sein?',
  'Wer hat die beste Balance zwischen Arbeit und Leben gefunden?',
  'Wer macht anderen am häufigsten einfach so eine Freude?',
  'Wer bringt am ehesten Suppe vorbei, wenn jemand erkältet im Bett liegt?',
  'Wer von euch macht die durchdachtesten Geschenke?',
  'Wer würde für jemanden hier am ehesten eine ganze Nacht wach bleiben, um zu helfen?',
  'Wer zeigt Respekt auch gegenüber Menschen, die ganz anders denken?',
  'Wer von euch ist am offensten für neue Sichtweisen?',
  'Wer würde am ehesten eine Woche das Leben einer völlig anderen Person führen, um sie zu verstehen?',
  'Wer würde am ehesten einen Baum pflanzen, dessen Schatten erst spätere Generationen genießen?',
  'Wer vergisst eine erwiesene Freundlichkeit niemals?',
  'Wer ist am nachtragendsten, auch wenn es kaum jemand merkt?',
  'Wer von euch macht sich die meisten Sorgen um die anderen?',
  'Wer ist die älteste Seele in dieser Runde?',
  'Wer von euch ist am neugierigsten auf das Leben anderer Menschen?',
  'Wer stellt auf Partys die tiefsten Fragen?',
  'Wer hat die interessanteste Sicht auf die Welt?',
  'Wer würde am ehesten ein Jahr in einem Kloster verbringen?',
  'Wer von euch glaubt am meisten an Schicksal?',
  'Wer würde am ehesten eine wichtige Entscheidung dem Zufall überlassen?',
  'Wer ist am ehesten davon überzeugt, dass jeder Mensch sich ändern kann?',
  'Wer hat die klarste Haltung, ohne andere davon überzeugen zu müssen?',
  'Wer würde am ehesten bei einer Demo für eine Herzenssache mitlaufen?',
  'Wer von euch kann am besten allein sein?',
  'Wer fühlt sich in großen Gruppen am wenigsten wohl, kommt aber trotzdem immer mit?',
  'Wer blüht in großen Runden am meisten auf?',
  'Wer kann am besten ein ehrliches Kompliment machen?',
  'Wer von euch hat schon jemandem hier aus einer echten Klemme geholfen?',
  'Wer würde sich am meisten freuen, wenn alle hier zusammen in eine Straße ziehen würden?',
  'Wer würde am ehesten die Rede auf der Hochzeit von jemandem hier halten?',
  'Wem würdet ihr zutrauen, euch in einer wichtigen Situation zu vertreten?',
  'Wer ist die Person, die euch am meisten inspiriert?',
  'Wer von euch lebt das Leben, das andere sich heimlich wünschen?',
  'Wer wäre die beste Wahl als Patin oder Pate eines Kindes?',
  'Wer hat schon sehr früh im Leben Verantwortung für andere übernommen?',
  'Wer übernimmt in Notfällen ganz selbstverständlich das Kommando?',
  'Wer von euch kann sich am besten in andere hineinversetzen?',
  'Wer kämpft am leidenschaftlichsten für eine Idee?',
  'Wer von euch hat die stärkste Meinung und die sanfteste Art, sie zu sagen?',
  'Wer hat schon mal etwas Großes aufgegeben, damit es jemand anderem besser geht?',
  'Wer würde am ehesten den letzten Euro mit euch teilen?',
  'Wer von euch hat sich schon mal für jemanden hier richtig stark gemacht?',
  'Wer ist die Person, die in zwanzig Jahren alle wieder zusammentrommelt?',
  'Wer hätte eine Biografie verdient, die alle lesen sollten?',
  'Wer würde am ehesten ein bestimmtes Jahr noch einmal genau so erleben wollen?',
  'Wer ist am meisten im Frieden mit dem Älterwerden?',
  'Wer würde am ehesten zehn Jahre jünger sein wollen, um alles bewusster zu erleben?',
  'Wer von euch hat die schönste Art, mit Kindern umzugehen?',
  'Wer hat das meiste Mitgefühl für Tiere?',
  'Wer würde am ehesten ein Tier aus dem Tierheim retten?',
  'Wer kann am besten mit älteren Menschen reden?',
  'Wer von euch bleibt in Diskussionen am fairsten?',
  'Wer kann eine Niederlage am würdevollsten hinnehmen?',
  'Wer würde am ehesten auf einen Gewinn verzichten, damit jemand anderes gewinnt?',
  'Wer ist am ehesten bereit, eigene Vorurteile zu hinterfragen?',
  'Wer hat am meisten aus den eigenen Fehlern gelernt?',
  'Wer liest am ehesten Bücher, die das eigene Denken verändern?',
  'Wer lässt sich von einem guten Gespräch am nachhaltigsten verändern?',
  'Wer nimmt sich Kritik am meisten zu Herzen?',
  'Wer kann Kritik am besten annehmen und etwas daraus machen?',
  'Wer ist am ehesten mit wenig glücklich?',
  'Wer würde am ehesten das eigene Lieblingsstück verschenken, weil es jemand anderem mehr bedeutet?',
  'Wer würde am ehesten einen Traumjob in einer fernen Stadt für die Menschen hier ablehnen?',
  'Wer wählt im Zweifel lieber Abenteuer als Sicherheit?',
  'Wer findet an einem neuen Ort am leichtesten Anschluss?',
  'Wer würde am ehesten noch mit siebzig neue Freundschaften schließen?',
  'Für wen ist Zuhause eher ein Mensch als ein Ort?',
  'Wer würde am ehesten ein Coaching machen, nur um sich weiterzuentwickeln?',
  'Wer reflektiert nach einem Streit am ehrlichsten das eigene Verhalten?',
  'Wer von euch entschuldigt sich am aufrichtigsten?',
  'Wer zeigt den eigenen Eltern am meisten Dankbarkeit?',
  'Wer würde den Eltern am ehesten einen Traumurlaub schenken?',
  'Wer erzählt am liebevollsten von der eigenen Familie?',
  'Wer von euch ist mit den eigenen Eltern am ehesten auch befreundet?',
  'Wer würde an Weihnachten am ehesten Menschen einladen, die sonst allein wären?',
  'Wer gibt Fremden am ehesten das Gefühl, willkommen zu sein?',
  'Wer würde auf einer Hochzeit am ehesten mit der einsamsten Person am Tisch reden?',
  'Wer hat seit der Jugend am meisten Selbstvertrauen gewonnen?',
  'Wer redet sich Sorgen am ehesten bei einem langen Spaziergang von der Seele?',
  'Mit wem könnt ihr am besten schweigend einen Sonnenuntergang anschauen?',
  'Wer von euch hat den besten Blick für Schönheit im Alltag?',
  'Wer würde am ehesten eine Nacht unter freiem Himmel verbringen, nur um die Sterne zu sehen?',
  'Wer würde am ehesten bis zum Sonnenaufgang über das Universum philosophieren?',
  'Wer fühlt sich dem Ort der eigenen Kindheit am stärksten verbunden?',
  'Wer bleibt nach einer Trennung am ehesten freundschaftlich verbunden?',
  'Wer liebt am bedingungslosesten?',
  'Wer würde für die große Liebe am meisten aufgeben?',
  'Wer von euch glaubt am festesten an die große Liebe?',
  'Wer wird am ehesten mal eine Liebeserklärung vor Publikum machen?',
  'Wer ist in einer Beziehung am verlässlichsten?',
  'Wer hat euch schon mal mit einer einzigen Nachricht den Tag gerettet?',
  'Wer würde am ehesten einen Abend organisieren, nur um allen hier Danke zu sagen?',
  'Wer übernimmt in der Gruppe am ehesten die Aufgaben, um die sich sonst niemand kümmert?',
  'Wer von euch hat sich die kindliche Begeisterung am besten bewahrt?',
  'Über wen werdet ihr in zwanzig Jahren noch die schönsten Geschichten erzählen?',
];
