export const deepQuestions: string[] = [
  'Wer von euch würde nachts um drei sofort kommen, wenn man anruft?',
  'Wem in dieser Runde würdet ihr euer größtes Geheimnis anvertrauen?',
  'Wer ist die loyalste Person hier am Tisch?',
  'Wer zeigt Gefühle am wenigsten, obwohl innen viel passiert?',
  'Wer ist viel mutiger, als man auf den ersten Blick denkt?',
  'Wer hat sich in den letzten Jahren am meisten verändert?',
  'Wer würde am ehesten alles stehen und liegen lassen, um einem Menschen aus dieser Runde zu helfen?',
  'Wer hört am besten zu, wenn es einem schlecht geht?',
  'Wer von euch gibt die ehrlichsten Ratschläge, auch wenn sie unbequem sind?',
  'Bei wem fühlt man sich sofort wohl und angenommen?',
  'Wer denkt am meisten über das Leben nach?',
  'Wer würde am ehesten für eine Freundschaft über den eigenen Schatten springen?',
  'Wer hat das größte Herz in dieser Runde?',
  'Wer kann am besten verzeihen?',
  'Wer von euch merkt als Erstes, wenn es jemandem nicht gut geht?',
  'Wer würde am ehesten einen Traum verfolgen, auch wenn alle dagegen sind?',
  'Wer ist die Person, die immer zu ihrem Wort steht?',
  'Wer versteckt Unsicherheit am besten hinter einem Lächeln?',
  'Wer ist am meisten an sich selbst gewachsen?',
  'Wen würdet ihr bei einem kompletten Neuanfang am liebsten an eurer Seite haben?',
  'Wer behält die eigene Meinung am häufigsten für sich?',
  'Wer ist der ruhige Fels in der Brandung, wenn alles chaotisch wird?',
  'Wer würde ein Geheimnis auch nach zwanzig Jahren noch für sich behalten?',
  'Wer von euch ist strenger mit sich selbst als mit anderen?',
  'Wer bringt andere am ehesten dazu, an sich selbst zu glauben?',
  'Wer hat die beste Intuition für Menschen?',
  'Wer würde sich am ehesten für jemanden einsetzen, der ungerecht behandelt wird?',
  'Wer von euch hat die meisten unausgesprochenen Träume?',
  'Wen würdet ihr nach einem schlechten Tag als Erstes anrufen?',
  'Wer hat euch schon mal mit einer ganz neuen Seite überrascht?',
  'Wer wäre am ehesten bereit, für eine Überzeugung alles zu riskieren?',
  'Wer kann am besten zugeben, einen Fehler gemacht zu haben?',
  'Wer ist im Herzen viel weicher, als die Fassade vermuten lässt?',
  'Wer von euch wird in zehn Jahren noch genauso für die Gruppe da sein?',
  'Wer kümmert sich am meisten um andere und vergisst dabei sich selbst?',
  'Auf wessen Meinung gebt ihr am meisten?',
  'Wer würde am ehesten einen sicheren Job kündigen, um etwas Eigenes zu wagen?',
  'Wer von euch hat die schönste Art, Dankbarkeit zu zeigen?',
  'Wer trägt am meisten mit sich herum, ohne darüber zu reden?',
  'Wer ist der Grund, warum diese Gruppe so gut zusammenhält?',
  'Wer würde euch am ehesten die Wahrheit sagen, auch wenn sie wehtut?',
  'Wer von euch hat die größte innere Stärke?',
  'Wer ist am ehrlichsten zu sich selbst?',
  'Wer hat in letzter Zeit den mutigsten Schritt gewagt?',
  'Wer würde am ehesten ein Jahr lang allein um die Welt reisen?',
  'Wer findet immer die richtigen Worte in schwierigen Momenten?',
  'Wer von euch wird am meisten unterschätzt?',
  'Wen würdet ihr bei einer wichtigen Lebensentscheidung zuerst um Rat fragen?',
  'Wer macht nach einem Streit am ehesten den ersten Schritt?',
  'Wer hat die meiste Geduld mit anderen Menschen?',
  'Wer von euch hat ein Talent, das viel zu wenig gesehen wird?',
  'Wer würde am ehesten einem fremden Menschen in Not spontan helfen?',
  'Wer ist am meisten man selbst, egal wer gerade zuschaut?',
  'Wer von euch würde für die Menschen hier am weitesten fahren?',
  'Wer schreibt die ehrlichsten und schönsten Nachrichten zum Geburtstag?',
  'Wer ist innerlich am meisten mit sich im Reinen?',
  'Wer würde am ehesten zugeben, gerade Angst zu haben?',
  'Wer von euch hat sich seit dem Kennenlernen am positivsten entwickelt?',
  'Wer ist die Person, die nie jemanden zurücklässt?',
  'Wer denkt nachts am längsten über Gespräche nach?',
  'Wer würde am ehesten eine Freundschaft retten, die schon fast verloren war?',
  'Wer hat euch schon mal etwas beigebracht, das ihr nie vergessen werdet?',
  'Wer von euch kann am besten schweigen, wenn Worte nicht helfen?',
  'Wer zeigt Zuneigung eher durch Taten als durch Worte?',
  'Auf wen kann man sich in einer Krise am meisten verlassen?',
  'Wer würde am ehesten einen Brief an das eigene jüngere Ich schreiben?',
  'Wer hat die stärksten Werte und lebt sie auch?',
  'Wer von euch hat schon die meisten Herausforderungen still gemeistert?',
  'Wer wäre am ehesten bereit, die eigene Meinung nach einem guten Argument zu ändern?',
  'Mit wem kann man stundenlang über wirklich alles reden?',
  'Wer gibt am meisten, ohne etwas zurückzuerwarten?',
  'Wer würde am ehesten zugeben, jemanden zu vermissen?',
  'Wer von euch ist am stolzesten auf die eigenen Wurzeln?',
  'Wer hat das Leben von jemandem hier am meisten positiv beeinflusst?',
  'Wer ist euch über die Jahre am meisten ans Herz gewachsen?',
  'Wer würde am ehesten den Fehler einer befreundeten Person auf sich nehmen?',
  'Wer von euch hat die größten Pläne für die Zukunft?',
  'Wer bleibt auch in schwierigen Zeiten am optimistischsten?',
  'Wem würdet ihr ohne zu zögern euren Schlüssel und euer Handy anvertrauen?',
  'Mit wem aus dieser Runde würdet ihr am liebsten gemeinsam alt werden?',
];
