export const exposedQuestions: string[] = [
  'Wer hat am wahrscheinlichsten schon mal das Instagram-Profil vom Crush bis ins Jahr 2015 durchgescrollt?',
  'Wer von euch hat schon mal aus Versehen ein altes Foto vom Crush geliked?',
  'Wer würde am ehesten einer Ex-Beziehung nachts um drei eine Nachricht schreiben?',
  'Wer ist die Person, die am meisten über ihr Alter, ihre Größe oder ihr Gehalt flunkert?',
  'Wer hat schon mal eine Krankheit vorgetäuscht, um nicht zu einem Treffen zu müssen?',
  'Wer von euch hatte die peinlichste Emo- oder Hipster-Phase?',
  'Wer hat am wahrscheinlichsten noch alte Liebesbriefe oder Chatverläufe gespeichert?',
  'Wer würde am ehesten eine Nachricht über jemanden genau an diese Person schicken?',
  'Wer hat schon mal mit einem Fake-Account jemanden ausspioniert?',
  'Wer von euch hat schon mal im Schlaf etwas sehr Peinliches gesagt?',
  'Wer ist am ehesten in der Schule beim Spicken erwischt worden?',
  'Wer hat schon mal jemandem zugewunken, der gar nicht gemeint war?',
  'Wer hat am wahrscheinlichsten die cringeste Profilbeschreibung auf einer Dating-App?',
  'Wer von euch hat schon mal eine Sprachnachricht abgeschickt, die nie hätte rausgehen dürfen?',
  'Wer ist die Person, die am ehesten noch mit dem Ex befreundet ist, obwohl alle wissen, dass da mehr ist?',
  'Wer hat am wahrscheinlichsten schon mal jemanden geghostet und es bis heute nicht erklärt?',
  'Wer von euch hat schon mal vor dem Spiegel einen Streit oder ein Date geprobt?',
  'Wer hat schon mal einen Post gelöscht, weil er zu wenige Likes bekommen hat?',
  'Wer hat am wahrscheinlichsten in der Pubertät Gedichte über den Schwarm geschrieben?',
  'Wer ist am ehesten mal beim Lästern von der betroffenen Person erwischt worden?',
  'Wer von euch hat schon mal im Unterricht oder Meeting laut gefurzt und es jemand anderem angehängt?',
  'Wer hat schon mal eine komplette Ausrede erfunden, um ein Date abzusagen?',
  'Wer ist die Person, die schon mal heimlich das Handy vom Partner oder der Partnerin durchsucht hat?',
  'Wer würde am ehesten zugeben, einmal in den Freund oder die Freundin eines Kumpels verknallt gewesen zu sein?',
  'Wer von euch hat noch eine peinliche Fanfiction oder ein Tagebuch irgendwo versteckt?',
  'Wer hat am wahrscheinlichsten schon mal beim Bewerbungsgespräch kräftig übertrieben?',
  'Wer hat schon mal im falschen Moment laut losgelacht, zum Beispiel auf einer Beerdigung?',
  'Wer würde am ehesten einen alten Tweet oder Post haben, der heute richtig peinlich wäre?',
  'Wer ist die Person, die beim ersten Date am ehesten etwas richtig Peinliches gemacht hat?',
  'Wer von euch hat schon mal ein Geschenk weiterverschenkt und wurde dabei erwischt?',
  'Wer hat am wahrscheinlichsten mal einen Live-Stream oder ein TikTok gemacht, das niemand sehen sollte?',
  'Wer hat schon mal behauptet, ein Buch gelesen oder einen Film gesehen zu haben, nur um mitreden zu können?',
  'Wer ist am ehesten schon mal im Supermarkt oder Bus vor dem Crush gestolpert?',
  'Wer würde am ehesten den Namen des Crushs mit dem eigenen Nachnamen ausprobieren?',
  'Wer von euch hat schon mal heimlich das Essen von Mitbewohnern gegessen und es abgestritten?',
  'Wer hat schon mal eine Nachricht mit dem falschen Namen an jemanden geschickt?',
  'Wer ist die Person, die nach einer Trennung am ehesten etwas Dramatisches gepostet hat?',
  'Wer würde am ehesten auf einer Hochzeit eine peinliche Rede halten?',
  'Wer von euch hat schon mal einen Lehrer oder eine Lehrerin aus Versehen Mama oder Papa genannt?',
  'Wer hat am wahrscheinlichsten mal einem Ex absichtlich Bilder vom neuen Glück gezeigt?',
  'Wer hat schon mal so getan, als würde er oder sie telefonieren, um niemanden grüßen zu müssen?',
  'Wer von euch hat die peinlichsten Suchanfragen im Browserverlauf?',
  'Wer hat am wahrscheinlichsten schon mal eine Beziehung per Textnachricht beendet?',
  'Wer hat schon mal jemandem eine Liebeserklärung gemacht und eine Abfuhr kassiert?',
  'Wer ist die Person, die am ehesten noch Kleidung vom Ex im Schrank hat?',
  'Wer würde am ehesten heimlich die eigenen Fotos mit Filtern bis zur Unkenntlichkeit bearbeiten?',
  'Wer von euch hat sich schon mal in eine Lehrkraft oder Chefin oder Chef verknallt?',
  'Wer hat am wahrscheinlichsten den Eltern eine wilde Lüge erzählt, die bis heute nicht aufgeflogen ist?',
  'Wer ist am ehesten mit offenem Hosenstall durch die Stadt gelaufen, ohne es zu merken?',
  'Wer würde am ehesten zugeben, sich schon mal selbst eine Nachricht zum Valentinstag geschickt zu haben?',
  'Wer hat am wahrscheinlichsten mal eine peinliche Nachricht in den Familienchat geschickt?',
  'Wer hat schon mal einen Crush aus der Ferne beobachtet und so getan, als wäre es Zufall?',
  'Wer würde am ehesten beim Karaoke den Text komplett vergessen und trotzdem weitersingen?',
  'Wer von euch hat schon mal heimlich geweint, weil eine Serie zu Ende war?',
  'Wer hat am wahrscheinlichsten bei einem Gruppenfoto heimlich alle anderen schlecht aussehen lassen?',
  'Wer hat schon mal eine Freundschaft wegen einer Kleinigkeit beendet, die heute peinlich ist?',
  'Wer ist am ehesten von den Eltern bei etwas erwischt worden, worüber nie wieder gesprochen wurde?',
  'Wer würde am ehesten Geld für Likes oder Follower ausgeben?',
  'Wer hat schon mal jemanden mit einer anderen Person verwechselt und lange Smalltalk gemacht?',
  'Wer ist die Person, die die peinlichste Geschichte hat, die hier noch niemand kennt?',
  'Wer von euch hat in der Schule am wahrscheinlichsten eine Entschuldigung der Eltern selbst unterschrieben?',
  'Wer wurde in der Schulzeit am wahrscheinlichsten mit einem peinlichen Spitznamen gerufen?',
  'Wer hat schon mal eine schlechte Klassenarbeit vor den Eltern versteckt?',
  'Wer hat am wahrscheinlichsten im Sportunterricht eine Ausrede erfunden, um nicht mitmachen zu müssen?',
  'Wer hat schon mal einen Liebesbrief mit "Ja, Nein, Vielleicht" zum Ankreuzen verschickt?',
  'Wer von euch ist am ehesten auf der Klassenfahrt nachts heimlich in ein fremdes Zimmer geschlichen?',
  'Wer hat am wahrscheinlichsten Hausaufgaben abgeschrieben und dabei alle Fehler mitkopiert?',
  'Wer wurde am ehesten beim Briefchenschreiben erwischt, und der Zettel wurde laut vorgelesen?',
  'Wer hatte in der Schule die peinlichste Frisur, die es heute noch auf Fotos gibt?',
  'Wer von euch hatte schon mal einen kompletten Blackout beim Vortrag vor der Klasse?',
  'Wer hat am wahrscheinlichsten eine Lehrkraft nachgemacht und wurde genau dabei erwischt?',
  'Wer würde am ehesten zugeben, sich in der Schule für die eigenen Eltern geschämt zu haben?',
  'Wer von euch hat auf dem Schulfoto die Augen zu, und das Bild hängt noch bei den Eltern?',
  'Wer hat am wahrscheinlichsten einen Eintrag ins Klassenbuch für etwas richtig Dummes kassiert?',
  'Wer von euch hat sich schon mal in der Schule vor allen übergeben?',
  'Wer hat am wahrscheinlichsten nach einer Trennung alle gemeinsamen Fotos zerrissen?',
  'Wer von euch hat schon mal die neue Beziehung vom Ex komplett durchleuchtet?',
  'Wer würde am ehesten beim Ex anrufen und sofort wieder auflegen?',
  'Wer hat schon mal zu einer Party zugesagt, nur weil der Ex auch kommen sollte?',
  'Wer hat am wahrscheinlichsten mal ein Geschenk vom Ex zurückgefordert?',
  'Wer von euch ist schon mal zum Ex zurück, obwohl wirklich alle davon abgeraten haben?',
  'Wer hat in einer Beziehung schon mal den Jahrestag komplett vergessen?',
  'Wer würde am ehesten ein Lied über den Ex schreiben und es auch noch jemandem vorspielen?',
  'Wer von euch ist schon mal absichtlich an der Wohnung vom Ex vorbeigegangen?',
  'Wer hat am wahrscheinlichsten noch ein Passwort, das mit dem Ex zu tun hat?',
  'Wer hat nach einer Trennung schon mal eine drastische Typveränderung gemacht und sie bereut?',
  'Wer hat sich am ehesten schon mal hinter einem Regal versteckt, weil der Ex im Laden war?',
  'Wer von euch hatte schon mal eine Beziehung, von der die Freunde nichts wissen durften?',
  'Wer hat am wahrscheinlichsten Schluss gemacht und kurz danach um ein Comeback gebettelt?',
  'Wer würde am ehesten das Haustier vom Ex mehr vermissen als den Ex selbst?',
  'Wer hat schon mal versehentlich den Namen vom Ex bei der neuen Person gesagt?',
  'Wer hat schon mal eine Beziehung verlängert, nur um an Weihnachten nicht allein zu sein?',
  'Wer von euch hat schon mal aus Versehen eine Story für alle statt für enge Freunde gepostet?',
  'Wer hat am wahrscheinlichsten schon mal fünfzig Selfies gemacht, um eines zu posten?',
  'Wer würde am ehesten die eigenen Posts mit einem Zweitaccount liken?',
  'Wer hat schon mal einen langen wütenden Kommentar unter einen fremden Post geschrieben?',
  'Wer von euch hat am ehesten einen Urlaub online inszeniert, der in Wahrheit furchtbar war?',
  'Wer hat schon mal einen Videocall im ungünstigsten Moment mit Kamera angenommen?',
  'Wer von euch hat schon mal in einem Livestream kommentiert und wurde laut vorgelesen?',
  'Wer hat am wahrscheinlichsten mal einen Kalenderspruch über das Leben gepostet, der heute peinlich ist?',
  'Wer hat schon mal beim Foto den Ort gefälscht, um interessanter zu wirken?',
  'Wer von euch hat schon mal jemanden entfolgt und es heimlich wieder rückgängig gemacht?',
  'Wer hat am wahrscheinlichsten einen Kommentar bei einem Promi hinterlassen, auf den man nicht stolz ist?',
  'Wer würde am ehesten ein trauriges Lied in die Story packen, damit eine bestimmte Person es sieht?',
  'Wer hat schon mal einen Tanztrend nachgemacht, und es ging komplett schief?',
  'Wer von euch hat einen Tippfehler im Post erst nach hundert Likes bemerkt?',
  'Wer hat am wahrscheinlichsten noch einen alten Blog oder Kanal, der nie gefunden werden darf?',
  'Wer hat schon mal eine private Nachricht versehentlich als öffentlichen Kommentar gepostet?',
  'Wer von euch hat schon mal den Weg geändert, nur um dem Crush zufällig zu begegnen?',
  'Wer hat am wahrscheinlichsten eine Stunde an einer Nachricht gefeilt und dann nur "hey" geschickt?',
  'Wer hat schon mal ein Hobby angefangen, nur weil der Crush es auch macht?',
  'Wer hat schon mal absichtlich etwas bei jemandem liegen lassen, um einen Grund zum Wiedersehen zu haben?',
  'Wer ist am ehesten mal beim Anstarren vom Crush gegen eine Laterne gelaufen?',
  'Wer würde am ehesten jede Nachricht vom Crush einer Freundesgruppe zur Analyse schicken?',
  'Wer würde am ehesten einen Kurs nur wegen einer Person belegen, die auch drin sitzt?',
  'Wer hat am wahrscheinlichsten stundenlang den Online-Status vom Crush beobachtet?',
  'Wer hat schon mal einen Crush verschwiegen, weil jemand aus dem Freundeskreis dieselbe Person mochte?',
  'Wer verknallt sich am ehesten in jemanden aus dem Fitnessstudio, ohne je ein Wort gewechselt zu haben?',
  'Wer hat am wahrscheinlichsten vor dem Crush mit einer Fähigkeit angegeben, die gar nicht existiert?',
  'Wer würde am ehesten zugeben, gerade in jemanden verknallt zu sein, von dem niemand hier weiß?',
  'Wer hat am wahrscheinlichsten schon mal gegoogelt, wie man über jemanden hinwegkommt?',
  'Wer würde am ehesten regelmäßig den eigenen Namen googeln?',
  'Wer hat schon mal nach "Wie wirke ich cool" oder etwas ähnlich Verzweifeltem gesucht?',
  'Wer von euch hat die peinlichste Fotogalerie auf dem Handy, die niemand durchscrollen darf?',
  'Wer hat am wahrscheinlichsten die meisten Screenshots von fremden Chats gespeichert?',
  'Wer hat schon mal hektisch den Verlauf gelöscht, weil jemand kurz den Laptop wollte?',
  'Wer hat am wahrscheinlichsten die seltsamsten Namen für Kontakte im Handy gespeichert?',
  'Wer hat sich schon mal die eigene Sprachnachricht angehört und sich in Grund und Boden geschämt?',
  'Wer hatte am ehesten mal peinliche Musik laut im Zug, weil die Kopfhörer nicht verbunden waren?',
  'Wer würde am ehesten die Autokorrektur beschuldigen, obwohl die Nachricht genau so gemeint war?',
  'Wer hatte schon mal einen richtig peinlichen Song auf Platz eins im Musik-Jahresrückblick?',
  'Wer von euch hat beim Bildschirmteilen im Meeting schon mal etwas Peinliches gezeigt?',
  'Wer hat am wahrscheinlichsten schon mal gegoogelt, wie man richtig küsst?',
  'Wer hat schon mal einen Online-Test wie "Welche Prinzessin bin ich?" sehr ernst genommen?',
  'Wer von euch wurde schon mal von den Eltern vor Freunden mit einem Kosenamen gerufen?',
  'Wer hat am wahrscheinlichsten Eltern, die peinliche Kommentare unter Fotos schreiben?',
  'Wer hat den Eltern schon mal erzählt, bei Freunden zu schlafen, und war ganz woanders?',
  'Wer von euch hat schon mal heimlich das Auto der Eltern genommen?',
  'Wer hat am wahrscheinlichsten etwas zu Hause kaputt gemacht und es den Geschwistern angehängt?',
  'Wer hat schon mal von den Eltern ein Aufklärungsgespräch bekommen, das heute noch nachhallt?',
  'Wer würde am ehesten zugeben, die Wäsche immer noch zu den Eltern zu bringen?',
  'Wer hat am wahrscheinlichsten noch ein Kinderzimmer bei den Eltern, das wie mit vierzehn aussieht?',
  'Wer hat schon mal versehentlich eine Lästernachricht über die Eltern an die Eltern geschickt?',
  'Wer von euch hat schon mal ein Familienfest mit einer erfundenen Ausrede geschwänzt?',
  'Wer hat schon mal behauptet, das Studium laufe super, obwohl es überhaupt nicht stimmte?',
  'Wer ist die Person, deren Eltern bei jeder Feier dieselbe peinliche Geschichte erzählen?',
  'Wer hat am wahrscheinlichsten die Großeltern um Geld für etwas angeblich Vernünftiges gebeten?',
  'Wer hat am wahrscheinlichsten behauptet, im Stau zu stehen, obwohl die Person gerade erst aufgestanden war?',
  'Wer von euch hat schon mal einen leeren Akku vorgetäuscht, um ein Gespräch zu beenden?',
  'Wer würde am ehesten behaupten, eine Nachricht nie bekommen zu haben, obwohl sie gelesen wurde?',
  'Wer hat schon mal Verwandte erkranken lassen, um eine Prüfung zu verschieben?',
  'Wer von euch hat behauptet, eine Sprache zu sprechen, und wurde dann direkt darin angesprochen?',
  'Wer hat schon mal behauptet, schon gegessen zu haben, nur um nicht mitkommen zu müssen?',
  'Wer hat am ehesten eine Lüge so weit getrieben, dass sie jahrelang aufrechterhalten werden musste?',
  'Wer würde am ehesten einen Notfall vortäuschen, um von einem schlechten Date wegzukommen?',
  'Wer von euch hat schon mal so getan, als würde man schlafen, um einem Gespräch zu entkommen?',
  'Wer hat am wahrscheinlichsten das Geburtsdatum gefälscht, um irgendwo reinzukommen?',
  'Wer hat schon mal behauptet, eine berühmte Person getroffen zu haben, obwohl es nicht stimmte?',
  'Wer hat am wahrscheinlichsten bei einem Quiz oder Spieleabend heimlich gegoogelt?',
  'Wer würde am ehesten behaupten, ein Gericht selbst gekocht zu haben, obwohl es bestellt war?',
  'Wer trägt am ehesten noch eine Lüge gegenüber jemandem aus dieser Runde mit sich herum?',
  'Wer hat am wahrscheinlichsten ein Haustier als Ausrede benutzt, das gar nicht existiert?',
  'Wer von euch hat schon mal vor vielen Leuten an einer Tür gezogen, auf der "Drücken" stand?',
  'Wer hat am wahrscheinlichsten auf "Guten Appetit" mit "Danke, gleichfalls" geantwortet, obwohl die Person nicht isst?',
  'Wer würde am ehesten auf einer Rolltreppe stolpern, während alle zusehen?',
  'Wer von euch hat schon mal versucht, in ein fremdes Auto einzusteigen?',
  'Wer hat am wahrscheinlichsten ein verpasstes High Five in eine Haarbewegung umgewandelt?',
  'Wer hat schon mal laut mitgesungen und erst später gemerkt, dass alle zuhören?',
  'Wer ist am ehesten mit Klopapier am Schuh von der Toilette zurückgekommen?',
  'Wer von euch hat im Kino schon mal etwas laut kommentiert, und der ganze Saal hat es gehört?',
  'Wer hat am wahrscheinlichsten im Fitnessstudio ein Gerät falsch herum benutzt?',
  'Wer hat schon mal zur Umarmung angesetzt, obwohl die andere Person nur die Hand geben wollte?',
  'Wer von euch saß schon mal im falschen Meeting oder Hörsaal und hat es viel zu spät gemerkt?',
  'Wer würde am ehesten nach einer Präsentation das Mikro anlassen und etwas Peinliches sagen?',
  'Wer hat schon mal an der Kasse gemerkt, dass kein Geld dabei ist, mit langer Schlange dahinter?',
  'Wer hat am ehesten ein Wort jahrelang mit voller Überzeugung falsch benutzt?',
  'Wer von euch hat schon mal die Bedienung im Restaurant versehentlich Schatz genannt?',
  'Wer hat am wahrscheinlichsten in der Umkleide eine Hose kaputt gemacht und musste sie kaufen?',
  'Wer hat beim Lachen schon mal so laut geschnaubt, dass sich alle erschreckt haben?',
  'Wer würde am ehesten zugeben, heimlich Reality-TV in Dauerschleife zu schauen?',
  'Wer hat schon mal den ganzen Tag im Bett verbracht und danach von totaler Produktivität erzählt?',
  'Wer von euch hat schon mal eine ganze Packung Kekse allein gegessen und die Verpackung versteckt?',
  'Wer richtet am wahrscheinlichsten heimlich den Tag nach dem Horoskop aus?',
  'Wer hat schon mal ein unnötiges Paket vor den Mitbewohnern versteckt?',
  'Wer schläft am ehesten heute noch heimlich mit einem Kuscheltier?',
  'Wer würde am ehesten ein Kleidungsstück einmal ausführen und dann zurückschicken?',
  'Wer von euch hat schon mal heimlich im Tagebuch von jemand anderem gelesen?',
  'Wer hat am wahrscheinlichsten ein peinliches Hobby, von dem niemand hier etwas weiß?',
  'Wer von euch spricht am ehesten heimlich in Babysprache mit Pflanzen oder Haustieren?',
  'Wer hat am wahrscheinlichsten mehr Geld für Handyspiele ausgegeben, als zugegeben wird?',
  'Wer würde am ehesten heimlich vom Teller anderer naschen, wenn die kurz weg sind?',
  'Wer hat noch als erwachsener Mensch irgendwo geklingelt und ist weggerannt?',
  'Wer wurde am ehesten schon mal bei lauten Selbstgesprächen erwischt?',
  'Wer von euch hat schon mal einen Bademantel aus dem Hotel mitgehen lassen?',
  'Wer hat schon mal eine Staffel in einer Nacht geschaut und sich am nächsten Tag krankgemeldet?',
  'Wer von euch hatte schon mal ein wichtiges Meeting im Homeoffice mit Pyjamahose?',
  'Wer hat am wahrscheinlichsten im falschen Chat über die Chefin oder den Chef gelästert?',
  'Wer hat schon mal eine komplette Hausarbeit in der letzten Nacht geschrieben?',
  'Wer von euch hat in einer Prüfung absichtlich unleserlich geschrieben, um Punkte zu retten?',
  'Wer hat schon mal im Bewerbungsgespräch den Namen der Firma falsch gesagt?',
  'Wer musste sich am ehesten nach einer Firmenfeier am Montag bei allen entschuldigen?',
  'Wer von euch hat schon mehrmals "Anhang anbei" geschrieben und den Anhang vergessen?',
  'Wer von euch hat eine berufliche Mail schon mal versehentlich mit Herzchen beendet?',
  'Wer hat am wahrscheinlichsten bei der Arbeit auf der Toilette ein Nickerchen gemacht?',
  'Wer würde am ehesten ein Telefonat mit dem Job versehentlich mit "Hab dich lieb" beenden?',
  'Wer hat im Praktikum mal etwas so verbockt, dass es heute noch erzählt wird?',
  'Wer hat in einer Gruppenarbeit nichts gemacht und trotzdem die volle Note bekommen?',
  'Wer von euch hat auf einem Date die Rechnung absichtlich der anderen Person überlassen?',
  'Wer hatte am wahrscheinlichsten ein Date mit jemandem, der auf Fotos komplett anders aussah?',
  'Wer hat auf einem Date schon mal viel zu lange über den Ex gesprochen?',
  'Wer von euch hat auf einer Dating-App schon mal Kollegen oder Verwandte entdeckt?',
  'Wer hatte am wahrscheinlichsten schon mal zwei Dates am selben Abend?',
  'Wer hat schon mal ein Date verlassen, indem man aufs Klo ging und nie wiederkam?',
  'Wer ist am ehesten beim ersten Kuss mit den Zähnen zusammengestoßen?',
  'Wer würde am ehesten Freunde heimlich an den Nebentisch vom Date setzen?',
  'Wer von euch hat auf einem Date schon mal so viel gegessen, dass es peinlich wurde?',
  'Wer hat am wahrscheinlichsten das eigene Dating-Profil von Freunden schreiben lassen?',
  'Wer hat auf einem Date schon mal über den eigenen Beruf gelogen?',
  'Wer von euch hat schon mal jemandem einen Korb gegeben und es danach bereut?',
  'Wer hat am wahrscheinlichsten jemanden gedatet, nur um eine andere Person eifersüchtig zu machen?',
  'Wer hat sich beim Date schon mal zur falschen Person an den Tisch gesetzt?',
  'Wer hat am ehesten ein Blind Date erlebt, das zur legendären Horrorgeschichte wurde?',
  'Wer von euch hat beim Date vor Nervosität schon mal ein volles Glas umgekippt?',
  'Wer schreibt am wahrscheinlichsten seit Monaten mit einem Match, ohne sich je getroffen zu haben?',
  'Wer hatte schon mal ein Date mit jemandem, den eine Person hier vorher gedatet hat?',
  'Wer von euch hat schon mal eine Chatgruppe ohne bestimmte Leute aus dieser Runde gegründet?',
  'Wer hat am wahrscheinlichsten ein Geheimnis von jemandem hier weitererzählt?',
  'Wer würde am ehesten absagen und dann in einer Story auf einer anderen Party auftauchen?',
  'Wer hat schon mal heimlich gehofft, dass ein Treffen mit Freunden ausfällt?',
  'Wer von euch hat einen Gruppenchat stummgeschaltet, ohne dass die anderen davon wissen?',
  'Wer war am wahrscheinlichsten schon mal neidisch auf das Leben von jemandem hier und hat es verschwiegen?',
  'Wer war am ehesten eifersüchtig auf eine neue Freundschaft von jemandem hier?',
  'Wer von euch hat geliehenes Geld nie zurückgezahlt und gehofft, dass es vergessen wird?',
  'Wer hat am wahrscheinlichsten noch ein geliehenes Kleidungsstück und tut so, als wüsste es niemand?',
  'Wer hat schon mal jemandem hier ein Kompliment gemacht, das gar nicht ernst gemeint war?',
  'Wer von euch hat schon mal heimlich über ein Outfit von jemandem hier gelacht?',
  'Wer hat am wahrscheinlichsten ein Treffen nur organisiert, um eine bestimmte Person zu sehen?',
  'Wer hat schon mal ein Last-Minute-Geschenk von der Tankstelle mitgebracht?',
  'Wer hat am ehesten den Geburtstag von jemandem aus dem engsten Freundeskreis komplett vergessen?',
  'Wer hat am wahrscheinlichsten beim Spieleabend geschummelt und es nie zugegeben?',
  'Wer hat schon mal mit den Geschwistern von jemandem hier geflirtet?',
  'Wer hat als Kind am ehesten etwas verschluckt, das definitiv nicht essbar war?',
  'Wer würde am ehesten zugeben, bis ins Teenageralter an den Weihnachtsmann geglaubt zu haben?',
  'Wer hat als Kind schon mal einen Fanbrief an eine Band oder einen Serienstar geschrieben?',
  'Wer von euch hat sich als Kind am ehesten selbst die Haare geschnitten, mit katastrophalem Ergebnis?',
  'Wer hatte am wahrscheinlichsten bis in ein peinliches Alter eine imaginäre Freundschaft?',
  'Wer wollte schon im Kindergarten jemanden heiraten und hat es ganz offiziell verkündet?',
  'Wer ist am ehesten auf einem alten Heimvideo zu sehen, das die Eltern gern bei Feiern zeigen?',
  'Wer kann am ehesten noch die komplette Choreo einer Boyband oder Girlgroup aus den Zweitausendern?',
  'Wer von euch hatte als Teenager das peinlichste Poster über dem Bett hängen?',
  'Wer hat am wahrscheinlichsten eine Band gegründet, die genau einen einzigen Auftritt hatte?',
  'Wer hat als Kind schon mal im Laden etwas Kleines geklaut, zum Beispiel einen Kaugummi?',
  'Wer von euch hatte die peinlichste erste E-Mail-Adresse?',
  'Wer hat am wahrscheinlichsten einen Kettenbrief weitergeleitet, aus Angst vor dem Fluch?',
  'Wer wollte als Teenager älter aussehen, und es ging komplett daneben?',
  'Wer hebt am ehesten noch das erste Handy samt aller alten SMS auf?',
  'Wer hat am wahrscheinlichsten bei einem Talentwettbewerb mitgemacht, der komplett schiefging?',
  'Wer hat schon mal einen Brief an das zukünftige Ich geschrieben, der heute sehr peinlich ist?',
  'Wer hat am wahrscheinlichsten mit Spinat zwischen den Zähnen ein wichtiges Gespräch geführt?',
  'Wer hatte schon mal beim Niesen einen richtig peinlichen Zwischenfall?',
  'Wer von euch hat schon mal mit Gesichtsmaske oder Pickelcreme die Tür für den Paketdienst geöffnet?',
  'Wer hat am wahrscheinlichsten ein T-Shirt den ganzen Tag falsch herum getragen?',
  'Wer hatte schon mal eine Hose, die in der Öffentlichkeit gerissen ist?',
  'Wer ist am ehesten im Zug auf der Schulter einer fremden Person aufgewacht?',
  'Wer wurde am ehesten schon mal beim Sabbern im Schlaf fotografiert?',
  'Wer von euch sah nach einem Selbstbräuner schon mal wochenlang orange aus?',
  'Wer hat am wahrscheinlichsten beim Friseur gesagt, es gefällt, und zu Hause geweint?',
  'Wer hat schon mal einen Markennamen jahrelang selbstbewusst falsch ausgesprochen?',
  'Wer von euch hat schon mal im Schwimmbad ein Teil der Badekleidung verloren?',
  'Wer hat am wahrscheinlichsten eine Kontaktlinse verloren, und das ganze Restaurant hat mitgesucht?',
  'Wer hat am wahrscheinlichsten eine Diät angekündigt und am selben Abend Pizza bestellt?',
  'Wer hat schon mal ein Fitnessstudio-Abo abgeschlossen und war genau einmal dort?',
  'Wer von euch hat schon mal so getan, als könnte man einen Wein fachmännisch beurteilen?',
  'Wer hat schon mal ein Buch nur gekauft, damit es im Regal klug aussieht?',
  'Wer von euch hat schon mal Ahnung von Fußball oder Autos vorgetäuscht und wurde enttarnt?',
  'Wer ist am ehesten mit einem Akzent aus dem Urlaub zurückgekommen, der eine Woche anhielt?',
  'Wer würde am ehesten ein teures Essen posten, das jemand anderes bezahlt hat?',
  'Wer von euch hat schon mal tiefe Entspannung beim Yoga vorgespielt und dabei an Pommes gedacht?',
  'Wer hat am wahrscheinlichsten Sportkleidung, die nur für Fotos getragen wird?',
  'Wer hat schon mal ein fremdes Haustier oder Auto als das eigene ausgegeben?',
  'Wer von euch hat einen Lauf groß angekündigt und dann heimlich nicht teilgenommen?',
  'Wer hat am wahrscheinlichsten eine geschenkte Pflanze eingehen lassen und heimlich eine neue gekauft?',
  'Wer würde am ehesten nach einem einzigen Kochkurs behaupten, Profi zu sein?',
  'Wer hat schon mal vor dem Spiegel eine Dankesrede für einen großen Preis geübt?',
  'Wer postet am ehesten monatelang Urlaubsfotos häppchenweise, damit es nach mehr aussieht?',
  'Wer hat am wahrscheinlichsten ein Kompliment für die Haare angenommen, obwohl es Extensions waren?',
  'Wer hat schon mal ein Instrument gekauft, um damit anzugeben, und es nie gelernt?',
  'Wer würde am ehesten im Laden etwas kaputt machen und es heimlich zurück ins Regal stellen?',
  'Wer ist schon mal beim Schwarzfahren erwischt worden und hat eine wilde Geschichte erzählt?',
  'Wer hat am wahrscheinlichsten einen Schaden an etwas Geliehenem einfach verschwiegen?',
  'Wer hat schon mal einen langen Brief an jemanden geschrieben und ihn nie abgeschickt?',
  'Wer hat am ehesten schon mal bei Gastgebern heimlich in den Badezimmerschrank geschaut?',
  'Wer würde am ehesten zugeben, die Hälfte der Leute hier anfangs nicht gemocht zu haben?',
  'Wer von euch hat schon mal Nachbarn durch die Wand belauscht und mitgeschrieben?',
  'Wer hat schon mal so viel bei einer Wette gesetzt, dass es richtig wehgetan hat?',
  'Wer von euch ist schon mal durch einen fremden Garten abgekürzt und wurde dabei erwischt?',
  'Wer würde am ehesten heimlich eine Fünf-Sterne-Bewertung für das eigene Projekt verfassen?',
  'Wer ist schon mal aus einem richtig peinlichen Grund durch die Fahrprüfung gefallen?',
  'Wer hat schon mal heimlich im Internet nach einer Person aus dieser Runde gesucht?',
  'Wer von euch hat schon mal eine Nachricht sofort für alle gelöscht, aber es war schon zu spät?',
];
