export const exposedQuestions: string[] = [
  'Wer hat am wahrscheinlichsten schon mal das Instagram-Profil vom Crush bis ins Jahr 2015 durchgescrollt?',
  'Wer von euch hat schon mal aus Versehen ein altes Foto vom Crush geliked?',
  'Wer würde am ehesten einer Ex-Beziehung nachts um drei eine Nachricht schreiben?',
  'Wer hat am wahrscheinlichsten noch einen geheimen Ordner mit Fotos vom Ex?',
  'Wer ist die Person, die am meisten über ihr Alter, ihre Größe oder ihr Gehalt flunkert?',
  'Wer hat schon mal eine Krankheit vorgetäuscht, um nicht zu einem Treffen zu müssen?',
  'Wer von euch hatte die peinlichste Emo- oder Hipster-Phase?',
  'Wer hat am wahrscheinlichsten noch alte Liebesbriefe oder Chatverläufe gespeichert?',
  'Wer würde am ehesten eine Nachricht über jemanden genau an diese Person schicken?',
  'Wer hat schon mal mit einem Fake-Account jemanden ausspioniert?',
  'Wer von euch hat schon mal im Schlaf etwas sehr Peinliches gesagt?',
  'Wer hat am wahrscheinlichsten schon mal so getan, als würde er oder sie ein Lied kennen?',
  'Wer ist am ehesten in der Schule beim Spicken erwischt worden?',
  'Wer hat schon mal jemandem zugewunken, der gar nicht gemeint war?',
  'Wer würde am ehesten heimlich den Partner oder die Partnerin von Freunden bewerten?',
  'Wer hat am wahrscheinlichsten die cringeste Profilbeschreibung auf einer Dating-App?',
  'Wer von euch hat schon mal eine Sprachnachricht abgeschickt, die nie hätte rausgehen dürfen?',
  'Wer hat schon mal über ein Geschenk gelogen und behauptet, es sei toll?',
  'Wer ist die Person, die am ehesten noch mit dem Ex befreundet ist, obwohl alle wissen, dass da mehr ist?',
  'Wer hat am wahrscheinlichsten schon mal jemanden geghostet und es bis heute nicht erklärt?',
  'Wer würde am ehesten ein peinliches Kinderfoto als Profilbild verwenden?',
  'Wer von euch hat schon mal vor dem Spiegel einen Streit oder ein Date geprobt?',
  'Wer hat schon mal einen Post gelöscht, weil er zu wenige Likes bekommen hat?',
  'Wer hat am wahrscheinlichsten in der Pubertät Gedichte über den Schwarm geschrieben?',
  'Wer ist am ehesten mal beim Lästern von der betroffenen Person erwischt worden?',
  'Wer würde am ehesten nach einer Trennung die Playlist mit allen traurigen Liedern auf Dauerschleife hören?',
  'Wer von euch hat schon mal im Unterricht oder Meeting laut gefurzt und es jemand anderem angehängt?',
  'Wer hat am wahrscheinlichsten schon mal einen Ex über die Story eines Freundes gestalkt?',
  'Wer hat schon mal eine komplette Ausrede erfunden, um ein Date abzusagen?',
  'Wer ist die Person, die schon mal heimlich das Handy vom Partner oder der Partnerin durchsucht hat?',
  'Wer würde am ehesten zugeben, einmal in den Freund oder die Freundin eines Kumpels verknallt gewesen zu sein?',
  'Wer von euch hat noch eine peinliche Fanfiction oder ein Tagebuch irgendwo versteckt?',
  'Wer hat am wahrscheinlichsten schon mal beim Bewerbungsgespräch kräftig übertrieben?',
  'Wer hat schon mal im falschen Moment laut losgelacht, zum Beispiel auf einer Beerdigung?',
  'Wer ist am ehesten auf Social Media eine ganz andere Person als im echten Leben?',
  'Wer würde am ehesten einen alten Tweet oder Post haben, der heute richtig peinlich wäre?',
  'Wer von euch hat schon mal versehentlich einen Screenshot an die Person geschickt, um die es ging?',
  'Wer hat am wahrscheinlichsten schon mal gelogen, um früher von der Arbeit oder Uni zu gehen?',
  'Wer hat in der Schulzeit am meisten für jemanden geschwärmt, der nichts davon wusste?',
  'Wer ist die Person, die beim ersten Date am ehesten etwas richtig Peinliches gemacht hat?',
  'Wer würde am ehesten heimlich die Nummer vom Ex noch auswendig können?',
  'Wer von euch hat schon mal ein Geschenk weiterverschenkt und wurde dabei erwischt?',
  'Wer hat am wahrscheinlichsten mal einen Live-Stream oder ein TikTok gemacht, das niemand sehen sollte?',
  'Wer hat schon mal behauptet, ein Buch gelesen oder einen Film gesehen zu haben, nur um mitreden zu können?',
  'Wer ist am ehesten schon mal im Supermarkt oder Bus vor dem Crush gestolpert?',
  'Wer würde am ehesten den Namen des Crushs mit dem eigenen Nachnamen ausprobieren?',
  'Wer von euch hat schon mal heimlich das Essen von Mitbewohnern gegessen und es abgestritten?',
  'Wer hat am wahrscheinlichsten noch Kontakt zu einer Person, die eigentlich gesperrt sein sollte?',
  'Wer hat schon mal eine Nachricht mit dem falschen Namen an jemanden geschickt?',
  'Wer ist die Person, die nach einer Trennung am ehesten etwas Dramatisches gepostet hat?',
  'Wer würde am ehesten auf einer Hochzeit eine peinliche Rede halten?',
  'Wer von euch hat schon mal einen Lehrer oder eine Lehrerin aus Versehen Mama oder Papa genannt?',
  'Wer hat am wahrscheinlichsten mal einem Ex absichtlich Bilder vom neuen Glück gezeigt?',
  'Wer hat schon mal so getan, als würde er oder sie telefonieren, um niemanden grüßen zu müssen?',
  'Wer ist am ehesten in einer Gruppe gelandet, in der über die eigene Person gelästert wurde?',
  'Wer würde am ehesten zugeben, schon mal über Freunde in diesem Raum gelogen zu haben?',
  'Wer von euch hat die peinlichsten Suchanfragen im Browserverlauf?',
  'Wer hat am wahrscheinlichsten schon mal eine Beziehung per Textnachricht beendet?',
  'Wer hat schon mal jemandem eine Liebeserklärung gemacht und eine Abfuhr kassiert?',
  'Wer ist die Person, die am ehesten noch Kleidung vom Ex im Schrank hat?',
  'Wer würde am ehesten heimlich die eigenen Fotos mit Filtern bis zur Unkenntlichkeit bearbeiten?',
  'Wer von euch hat sich schon mal in eine Lehrkraft oder Chefin oder Chef verknallt?',
  'Wer hat am wahrscheinlichsten den Eltern eine wilde Lüge erzählt, die bis heute nicht aufgeflogen ist?',
  'Wer hat schon mal einen Account erstellt, nur um zu sehen, wer die Story vom Ex anschaut?',
  'Wer ist am ehesten mit offenem Hosenstall durch die Stadt gelaufen, ohne es zu merken?',
  'Wer würde am ehesten zugeben, sich schon mal selbst eine Nachricht zum Valentinstag geschickt zu haben?',
  'Wer von euch hat schon mal in einem Streit komplett unrecht gehabt und es nie zugegeben?',
  'Wer hat am wahrscheinlichsten mal eine peinliche Nachricht in den Familienchat geschickt?',
  'Wer hat schon mal einen Crush aus der Ferne beobachtet und so getan, als wäre es Zufall?',
  'Wer ist die Person, die am ehesten über die Anzahl der Ex-Beziehungen schwindelt?',
  'Wer würde am ehesten beim Karaoke den Text komplett vergessen und trotzdem weitersingen?',
  'Wer von euch hat schon mal heimlich geweint, weil eine Serie zu Ende war?',
  'Wer hat am wahrscheinlichsten bei einem Gruppenfoto heimlich alle anderen schlecht aussehen lassen?',
  'Wer hat schon mal eine Freundschaft wegen einer Kleinigkeit beendet, die heute peinlich ist?',
  'Wer ist am ehesten von den Eltern bei etwas erwischt worden, worüber nie wieder gesprochen wurde?',
  'Wer würde am ehesten Geld für Likes oder Follower ausgeben?',
  'Wer von euch hat schon mal ein Date wegen eines Kumpels oder einer Freundin abgesagt und gelogen?',
  'Wer hat am wahrscheinlichsten den Ex heimlich bei einem gemeinsamen Freund ausgefragt?',
  'Wer hat schon mal jemanden mit einer anderen Person verwechselt und lange Smalltalk gemacht?',
  'Wer ist die Person, die die peinlichste Geschichte hat, die hier noch niemand kennt?',
];
