export const friendlyQuestions: string[] = [
  'Wer von euch gibt die besten Umarmungen?',
  'Wer ist die Person, die immer hilft, ohne lange zu fragen?',
  'Wer sorgt zuverlässig für gute Laune, sobald er oder sie den Raum betritt?',
  'Wer wäre die beste Person, um zusammen in eine WG zu ziehen?',
  'Wer von euch kann am besten zuhören?',
  'Wer hat das ansteckendste Lachen?',
  'Wer würde am ehesten mitten in der Nacht vorbeikommen, wenn man Hilfe braucht?',
  'Wer ist die Person, bei der man sich sofort wohlfühlt?',
  'Wer macht die besten Komplimente?',
  'Wer von euch hat das größte Herz?',
  'Wer erinnert sich immer an Geburtstage?',
  'Wer würde am ehesten einen Kuchen backen, nur um anderen eine Freude zu machen?',
  'Wer hat den besten Musikgeschmack in dieser Gruppe?',
  'Wer ist die Person, die man bei Liebeskummer als Erstes anrufen würde?',
  'Wer von euch strahlt die meiste Ruhe aus?',
  'Wer gibt die besten Ratschläge?',
  'Wer würde am ehesten ein liebevolles Geschenk selbst basteln?',
  'Wer ist die Person mit dem schönsten Lächeln?',
  'Wer von euch kann andere am besten aufmuntern?',
  'Wer hat immer einen Snack dabei und teilt ihn gern?',
  'Wer ist am loyalsten, wenn es darauf ankommt?',
  'Wer würde am ehesten bei einem Umzug helfen, ohne sich zu beschweren?',
  'Wer von euch hat den besten Humor?',
  'Wer ist die Person, die jede Party besser macht?',
  'Wer kocht so gut, dass man jede Einladung sofort annimmt?',
  'Wer würde den besten Reisepartner abgeben?',
  'Wer von euch ist am ehrlichsten, aber trotzdem immer lieb?',
  'Wer hat die schönste Stimme?',
  'Wer ist die Person, die allen das Gefühl gibt, dazuzugehören?',
  'Wer schreibt die liebsten Nachrichten?',
  'Wer würde am ehesten Fremden spontan helfen?',
  'Wer ist am geduldigsten mit anderen?',
  'Wer wäre die beste Person, um ein Haustier zu hüten?',
  'Wer von euch hat den besten Kleidungsstil?',
  'Wer würde am ehesten eine Überraschungsparty für jemanden organisieren?',
  'Wer von euch bringt andere am schnellsten zum Lachen?',
  'Wer wäre die beste Patentante oder der beste Patenonkel?',
  'Wer ist die Person, auf die man sich immer verlassen kann?',
  'Wer würde am ehesten mit dir eine ganze Nacht durchquatschen?',
  'Wer von euch hat die schönsten Augen?',
  'Wer würde am ehesten Suppe vorbeibringen, wenn es dir schlecht geht?',
  'Wer ist die Person, die nie schlecht über andere redet?',
  'Wer von euch ist am mutigsten?',
  'Wer würde am ehesten eine Playlist extra für dich zusammenstellen?',
  'Wer von euch ist am großzügigsten?',
  'Wer hat sich in den letzten Jahren am meisten positiv entwickelt?',
  'Wer würde am ehesten einen Streit in der Gruppe friedlich schlichten?',
  'Wer ist die Person, die immer an alle denkt?',
  'Wer von euch tanzt am schönsten?',
  'Wer hat die beste Energie am Morgen?',
  'Wer würde am ehesten eine handgeschriebene Karte verschicken?',
  'Wer ist die Person, mit der man am liebsten einen Filmabend macht?',
  'Wer von euch ist am bodenständigsten geblieben?',
  'Wer erzählt die besten Geschichten?',
  'Wer würde am ehesten bei einer Prüfung mitfiebern und danach anrufen?',
  'Wer von euch ist am verständnisvollsten?',
  'Wer würde am ehesten das letzte Stück Pizza abgeben?',
  'Wer ist die Person, die man allen Eltern ohne Sorge vorstellen würde?',
  'Wer würde den besten Lehrer oder die beste Lehrerin abgeben?',
  'Wer von euch hat das beste Gespür dafür, wenn es jemandem nicht gut geht?',
  'Wer würde am ehesten einen Regentag in ein Abenteuer verwandeln?',
  'Wer ist am aufmerksamsten bei kleinen Details?',
  'Wer von euch würde die beste Rede auf einer Hochzeit halten?',
  'Wer ist die Person, ohne die diese Gruppe nicht dieselbe wäre?',
  'Wer würde am ehesten deine Pflanzen gießen, wenn du verreist bist?',
  'Wer von euch würde ohne Zögern die eigene Jacke hergeben, wenn jemand friert?',
  'Wer bietet sofort Hilfe an, wenn jemand schwere Taschen trägt?',
  'Wer würde am ehesten beim Ausfüllen nerviger Formulare helfen?',
  'Wer ist die Person, die beim Aufräumen nach einer Feier als Letztes geht?',
  'Wer sorgt nachts dafür, dass alle sicher nach Hause kommen?',
  'Wer erklärt komplizierte Dinge so, dass man sie wirklich versteht?',
  'Wer würde am ehesten vor einer Prüfung stundenlang Lernstoff abfragen?',
  'Wer von euch repariert am liebsten Dinge für andere?',
  'Wer würde am ehesten einen platten Fahrradreifen flicken, ohne dass man fragen muss?',
  'Wer hat immer ein Pflaster, ein Taschentuch oder ein Ladekabel dabei?',
  'Wer schreibt nach einem Treffen als Erstes, ob alle gut angekommen sind?',
  'Wer würde am ehesten für jemanden einkaufen gehen, der gerade keine Zeit hat?',
  'Wer würde am ehesten den Abwasch übernehmen, obwohl jemand anderes dran wäre?',
  'Wer von euch hat den trockensten, aber liebenswertesten Humor?',
  'Wer kann über sich selbst am herzlichsten lachen?',
  'Wer macht die lustigsten Sprachnachrichten?',
  'Wer findet in jeder peinlichen Situation noch etwas zum Lachen?',
  'Wer von euch hat die besten Insiderwitze erfunden?',
  'Wer kann die witzigsten Imitationen?',
  'Wer schickt die lustigsten Memes in den Gruppenchat?',
  'Wer hat die kreativsten Spitznamen für Dinge und Leute?',
  'Wer von euch hat ein perfektes Timing für lustige Kommentare?',
  'Wer würde das unterhaltsamste Comedyprogramm auf die Bühne bringen?',
  'Wer von euch hat ein Talent, das viel mehr Leute kennen sollten?',
  'Wer hat die schönste Handschrift?',
  'Wer ist am geschicktesten mit den Händen?',
  'Wer von euch hat das beste Gedächtnis für Details aus alten Gesprächen?',
  'Wer macht die schönsten Fotos?',
  'Wer hätte das Zeug, ein eigenes Restaurant zu eröffnen?',
  'Wer ist sportlich so talentiert, dass man nur staunen kann?',
  'Wer von euch lernt neue Sprachen am schnellsten?',
  'Wer würde in einer Quizshow am meisten abräumen?',
  'Wer kann am besten zeichnen?',
  'Wer hat das beste Händchen für Pflanzen?',
  'Wer von euch ist ein heimliches Organisationstalent?',
  'Wer kann am besten mit Kindern umgehen?',
  'Wer könnte jedes Möbelstück ohne Anleitung aufbauen?',
  'Wer schreibt so schön, dass man ein Buch von dieser Person lesen würde?',
  'Wer von euch sieht selbst in Jogginghose noch stylisch aus?',
  'Wer hat die schönsten Haare in der Runde?',
  'Wer hat die am schönsten eingerichtete Wohnung?',
  'Wer trägt Farben, die sonst niemand tragen könnte, und sieht toll darin aus?',
  'Wer von euch hat einen ganz eigenen, unverwechselbaren Stil?',
  'Wer sieht auf Fotos immer gut aus?',
  'Wer hat einen Duft, an den man sich noch lange gern erinnert?',
  'Wer von euch könnte jederzeit als Model durchgehen?',
  'Wer hat die schönsten Schuhe?',
  'Wer dekoriert Tische und Räume so, dass alle staunen?',
  'Wer ist die Person, mit der man auch nach Monaten ohne Kontakt sofort wieder vertraut ist?',
  'Wer von euch hält die Gruppe zusammen?',
  'Wer meldet sich einfach so, nur um zu fragen, wie es einem geht?',
  'Wer würde am ehesten für ein Treffen quer durchs Land reisen?',
  'Wer ist die Person, der man jedes Geheimnis anvertrauen kann?',
  'Wer von euch freut sich am ehrlichsten über den Erfolg anderer?',
  'Wer verteidigt Freunde, auch wenn sie nicht dabei sind?',
  'Wer erinnert sich an Dinge, die man nur einmal nebenbei erwähnt hat?',
  'Wer würde am ehesten ein Fotoalbum mit gemeinsamen Erinnerungen gestalten?',
  'Wer ist der beste Mensch, um gemeinsam alt zu werden?',
  'Wer von euch hat am meisten dazu beigetragen, dass ihr euch alle kennt?',
  'Wer schafft es immer, ein Treffen zu organisieren, wenn alle zu beschäftigt sind?',
  'Wer würde am ehesten zu jedem Auftritt oder Spiel kommen, nur um anzufeuern?',
  'Wer ist die Person, mit der man auch schweigend gern Zeit verbringt?',
  'Wer gibt einem das Gefühl, wirklich gesehen zu werden?',
  'Wer würde dir bei einem Neuanfang in einer fremden Stadt am ehesten beistehen?',
  'Wer von euch verzeiht am schnellsten?',
  'Wer nimmt sich immer Zeit, auch wenn der Kalender voll ist?',
  'Wer würde am ehesten eine neue Tradition für eure Freundschaft ins Leben rufen?',
  'Bei wem fühlt man sich als Gast am meisten willkommen?',
  'Wer hat immer ein Gästebett oder ein Sofa für alle frei?',
  'Wer von euch deckt den schönsten Tisch?',
  'Wer würde am ehesten spontan für zehn Leute kochen?',
  'Bei wem würdet ihr am liebsten Weihnachten feiern?',
  'Wer von euch macht den besten Brunch?',
  'Wer bietet Gästen sofort etwas zu trinken an?',
  'Wer würde am ehesten einen gemütlichen Spieleabend zu Hause ausrichten?',
  'Wer achtet bei Einladungen darauf, dass niemand allein in der Ecke steht?',
  'Wer von euch backt den Geburtstagskuchen, den sich alle wünschen?',
  'Wer würde am ehesten eine Grillfeier im Garten veranstalten und alle einladen?',
  'Wer denkt beim Kochen immer an Allergien und Vorlieben aller Gäste?',
  'Wer macht den besten Kaffee oder Tee?',
  'Wer von euch ist immer pünktlich?',
  'Wer hält Versprechen, egal wie klein sie sind?',
  'Wer gibt geliehene Sachen garantiert zurück, sogar in besserem Zustand?',
  'Wer von euch antwortet am zuverlässigsten auf Nachrichten?',
  'Wer würde am ehesten pünktlich am Flughafen stehen, um dich abzuholen?',
  'Wer behält in stressigen Situationen den Überblick?',
  'Wer ist die Person, die man als Notfallkontakt angeben würde?',
  'Wer kümmert sich darum, dass Geld in der Gruppe fair aufgeteilt wird?',
  'Wer plant Ausflüge so, dass einfach alles klappt?',
  'Wer ist die Person, deren Wort wirklich etwas zählt?',
  'Wer von euch hat die originellsten Geschenkideen?',
  'Wer könnte aus Resten im Kühlschrank ein Festmahl zaubern?',
  'Wer hat die besten Ideen für Kostüme?',
  'Wer würde am ehesten ein eigenes Brettspiel erfinden?',
  'Wer schreibt die schönsten Gedichte oder Glückwunschkarten?',
  'Wer von euch denkt am meisten um die Ecke?',
  'Wer würde am ehesten ein altes Möbelstück in etwas Wunderschönes verwandeln?',
  'Wer findet für jedes Problem eine kreative Lösung?',
  'Wer hat die fantasievollsten Träume, von denen man unbedingt hören möchte?',
  'Wer von euch würde den besten Film drehen?',
  'Wer erfindet die schönsten Geschichten zum Einschlafen?',
  'Wer würde am ehesten einen Song über eure Freundschaft schreiben?',
  'Wer von euch gestaltet die schönsten Einladungen?',
  'Wer von euch hat die herzlichste Begrüßung?',
  'Wer wirkt selbst an schlechten Tagen noch freundlich?',
  'Wer strahlt das meiste Selbstvertrauen aus, ohne arrogant zu sein?',
  'Wer von euch hat den warmherzigsten Blick?',
  'Wer wirkt auf Fremde sofort sympathisch?',
  'Wer hat eine Ausstrahlung, die andere mutiger macht?',
  'Wer von euch hat die schönste Art zu erzählen?',
  'Wer bringt sogar Menschen an der Supermarktkasse zum Lächeln?',
  'Wer von euch strahlt am meisten Lebensfreude aus?',
  'Wer würde als Promi von allen geliebt werden?',
  'Wer wird von Tieren sofort ins Herz geschlossen?',
  'Wer merkt sofort, wenn jemand zu wenig gegessen oder getrunken hat?',
  'Wer von euch würde am ehesten einen Tee kochen, wenn jemand traurig ist?',
  'Wer bringt einen nach einer Party immer bis zur Haustür?',
  'Wer erinnert andere daran, auch mal auf sich selbst zu achten?',
  'Wer fragt nach einem schweren Termin nach, wie es gelaufen ist?',
  'Wer hat immer Kopfschmerztabletten und gute Worte dabei?',
  'Wer würde bei einem Krankenhausbesuch am ehesten die ganze Zeit bleiben?',
  'Wer bemerkt kleine Veränderungen wie eine neue Frisur sofort?',
  'Wer würde jemandem, der sich allein fühlt, sofort Gesellschaft leisten?',
  'Wer von euch nimmt Neue in der Gruppe am herzlichsten auf?',
  'Wer von euch ist am optimistischsten?',
  'Wer bleibt auch im größten Chaos gelassen und freundlich?',
  'Wer gibt nie auf, wenn es schwierig wird?',
  'Wer ist am bescheidensten, obwohl es allen Grund zum Angeben gäbe?',
  'Wer von euch ist am neugierigsten auf andere Menschen?',
  'Wer entschuldigt sich am ehrlichsten, wenn etwas schiefgeht?',
  'Wer ist am offensten für neue Erfahrungen?',
  'Wer von euch ist am dankbarsten für kleine Dinge?',
  'Wer hat den stärksten Gerechtigkeitssinn?',
  'Wer von euch sucht einen Fehler zuerst bei sich selbst?',
  'Wer ist am respektvollsten gegenüber allen Menschen?',
  'Wer bleibt sich selbst immer treu?',
  'Wer ist die Person, die am meisten Dankbarkeit verdient?',
  'Wer setzt sich am ehesten für Schwächere ein?',
  'Wer von euch ist am weltoffensten?',
  'Wer würde am ehesten ein Ehrenamt übernehmen?',
  'Wer sammelt bestimmt am meisten Karmapunkte?',
  'Wer von euch kann Konflikte ansprechen, ohne je verletzend zu werden?',
  'Mit wem würdet ihr am liebsten eine einsame Insel teilen?',
  'Wer wäre die beste Begleitung für einen Roadtrip?',
  'Wer von euch wäre die perfekte Verstärkung im Escape Room?',
  'Wer wäre die beste Person für ein Picknick im Park?',
  'Mit wem würdet ihr am liebsten einen Kochkurs machen?',
  'Wer von euch wäre die beste Person für einen langen Spaziergang am Abend?',
  'Mit wem würdet ihr am liebsten eine Zugreise durch Europa machen?',
  'Wer wäre die beste Begleitung für einen Wellnesstag?',
  'Wer von euch wäre die beste Person, um zusammen ein Festival zu besuchen?',
  'Mit wem würdet ihr eine Schnitzeljagd am ehesten gewinnen?',
  'Wer wäre die beste Person, um gemeinsam Sterne zu beobachten?',
  'Mit wem würdet ihr am liebsten einen Sonntag im Schlafanzug verbringen?',
  'Wer wäre die beste Begleitung für eine Wanderung in den Bergen?',
  'Mit wem würdet ihr am liebsten einen Flohmarkt durchstöbern?',
  'Wer wäre die beste Begleitung auf einer Hochzeit, auf der man niemanden kennt?',
  'Mit wem würdet ihr am liebsten ein Puzzle mit tausend Teilen legen?',
  'Wer wäre die beste Person, um gemeinsam ein neues Hobby auszuprobieren?',
  'Wer von euch hat sich das größte Kompliment des Abends verdient?',
  'Wer wäre in einem Märchen die gute Fee?',
  'Wer ist ein Mensch, den Kinder als Vorbild haben sollten?',
  'Wer verdient endlich mal einen richtig entspannten Urlaub?',
  'Wer von euch hat dieses Jahr am meisten geleistet?',
  'Wer wäre die Hauptfigur in einem Wohlfühlfilm?',
  'Wer würde als Stadtoberhaupt die Stadt am freundlichsten machen?',
  'Wer hätte eine eigene Statue für Herzlichkeit verdient?',
  'Wer wäre die Figur, die in einem Kinderbuch am Ende alle rettet?',
  'Wer verdient eine Auszeichnung für die meiste Geduld mit dieser Gruppe?',
  'Wer wäre als Hund ein besonders kuscheliger Golden Retriever?',
  'Wer wäre als Getränk eine heiße Schokolade an einem kalten Tag?',
  'Wer wäre als Wetter ein sonniger Frühlingstag?',
  'Wer von euch wäre als Song ein Hit für gute Laune?',
  'Wer wäre als Ort eine gemütliche Berghütte?',
  'Wer von euch wäre als Essen das liebste Trostessen der Welt?',
  'Wer wäre als Blume eine Sonnenblume?',
  'Wer bedankt sich immer, auch für Kleinigkeiten?',
  'Wer von euch lässt andere an der Supermarktkasse vor?',
  'Wer grüßt die Nachbarschaft am freundlichsten?',
  'Wer würde am ehesten einer älteren Person über die Straße helfen?',
  'Wer gibt im Restaurant am großzügigsten Trinkgeld?',
  'Wer hält anderen immer die Tür auf?',
  'Wer von euch hebt Müll auf, auch wenn es nicht der eigene ist?',
  'Wer würde am ehesten einem verlorenen Hund helfen, nach Hause zu finden?',
  'Wer würde einen gefundenen Geldbeutel sofort zurückbringen?',
  'Wer von euch macht Fremden am häufigsten Komplimente?',
  'Wer würde am ehesten der Nachbarschaft Kekse vor die Tür stellen?',
  'Wer schickt am häufigsten Fotos, die an schöne gemeinsame Momente erinnern?',
  'Wer von euch ist im Straßenverkehr am geduldigsten?',
  'Wer würde am ehesten einfach so Blumen mitbringen?',
  'Wer würde dich bei einem Marathon an der Strecke anfeuern?',
  'Wer von euch glaubt an Träume, auch wenn sie verrückt klingen?',
  'Wer gibt einem den letzten Schubs, um etwas Neues zu wagen?',
  'Wer würde dein Projekt am ehesten überall weiterempfehlen?',
  'Wer feiert die kleinen Erfolge anderer wie große?',
  'Wer erinnert einen an die eigenen Stärken, wenn man zweifelt?',
  'Wer würde mit dir eine Challenge durchziehen, damit du nicht allein bist?',
  'Wer gibt Feedback, das ehrlich ist und trotzdem gut tut?',
  'Wer nimmt Ängste ernst und macht sie trotzdem kleiner?',
  'Wer bringt neue Menschen in die Gruppe, die perfekt passen?',
  'Wer macht die besten Gruppenfotos, auf denen alle gut aussehen?',
  'Wer sorgt dafür, dass bei Entscheidungen jede Stimme zählt?',
  'Wer würde am ehesten ein eigenes T-Shirt für die Gruppe entwerfen?',
  'Wer von euch hat die schönste Gruppentradition angestoßen?',
  'Wer würde eine Gruppenreise so planen, dass alle glücklich sind?',
  'Wer wäre in einer Beziehung am aufmerksamsten?',
  'Wer würde am ehesten einen Liebesbrief mit der Hand schreiben?',
  'Wer würde das perfekte erste Date planen?',
  'Wer wäre der Lieblingsmensch jedes Kindes auf einem Familienfest?',
  'Wer von euch würde am ehesten ein Tier aus dem Tierheim retten?',
  'Wer würde am ehesten mit Kindern eine Burg aus Decken bauen?',
  'Wer würde am ehesten ein verletztes Vögelchen gesund pflegen?',
  'Wer macht das beste Frühstück der Welt?',
  'Wer von euch hat ein Familienrezept, das alle probieren müssen?',
  'Wer würde am ehesten Pausenbrote für alle schmieren?',
  'Wer teilt das eigene Dessert, ohne zu zögern?',
  'Wer von euch mixt die besten Cocktails oder Mocktails?',
  'Wer hat die schönsten Lebensweisheiten auf Lager?',
  'Wer von euch würde in einem Zombiefilm alle beschützen?',
  'Wer wäre die beste Person, um sich einen Regenschirm zu teilen?',
  'Wer würde dir am ehesten ein Geburtstagslied singen, auch wenn es schief klingt?',
  'Wer hat die besten Buch- und Serientipps?',
  'Wer könnte am ehesten einen grummeligen Menschen zum Lachen bringen?',
  'Wer sieht in jedem Menschen zuerst das Gute?',
  'Wer würde die gemütlichste Morgensendung im Radio moderieren?',
  'Wer würde die schönste Führung durch die eigene Heimatstadt geben?',
  'Wer kann trösten, ohne viele Worte zu brauchen?',
  'Wer hat ein Zuhause, das sich wie Urlaub anfühlt?',
  'Wer von euch hat das schönste Hobby?',
  'Wer würde dir am ehesten ein Buch schenken, das genau zu dir passt?',
  'Wer erzählt am leidenschaftlichsten von den eigenen Lieblingsthemen?',
  'Wer würde einen Fehler von dir nie gegen dich verwenden?',
  'Wer lässt sich mit den kleinsten Dingen am glücklichsten machen?',
  'Wer würde am ehesten eine Sammlung mit Komplimenten für schlechte Tage anlegen?',
  'Wer hat dich zuletzt richtig zum Strahlen gebracht?',
];
