export const friendlyQuestions: string[] = [
  'Wer hat das schönste Lachen in dieser Runde?',
  'Wer von euch gibt die besten Umarmungen?',
  'Wer ist die Person, die immer hilft, ohne lange zu fragen?',
  'Wer sorgt zuverlässig für gute Laune, sobald er oder sie den Raum betritt?',
  'Wer wäre die beste Person, um zusammen in eine WG zu ziehen?',
  'Wer von euch kann am besten zuhören?',
  'Wer hat das ansteckendste Lachen?',
  'Wer würde am ehesten mitten in der Nacht vorbeikommen, wenn man Hilfe braucht?',
  'Wer ist die Person, bei der man sich sofort wohlfühlt?',
  'Wer macht die besten Komplimente?',
  'Wer von euch hat das größte Herz?',
  'Wer erinnert sich immer an Geburtstage?',
  'Wer würde am ehesten einen Kuchen backen, nur um anderen eine Freude zu machen?',
  'Wer hat den besten Musikgeschmack in dieser Gruppe?',
  'Wer ist die Person, die man bei Liebeskummer als Erstes anrufen würde?',
  'Wer von euch strahlt die meiste Ruhe aus?',
  'Wer gibt die besten Ratschläge?',
  'Wer würde am ehesten ein liebevolles Geschenk selbst basteln?',
  'Wer ist die Person mit dem schönsten Lächeln?',
  'Wer von euch kann andere am besten aufmuntern?',
  'Wer hat immer einen Snack dabei und teilt ihn gern?',
  'Wer ist am loyalsten, wenn es darauf ankommt?',
  'Wer würde am ehesten bei einem Umzug helfen, ohne sich zu beschweren?',
  'Wer von euch hat den besten Humor?',
  'Wer ist die Person, die jede Party besser macht?',
  'Wer kocht so gut, dass man jede Einladung sofort annimmt?',
  'Wer würde den besten Reisepartner abgeben?',
  'Wer von euch ist am ehrlichsten, aber trotzdem immer lieb?',
  'Wer hat die schönste Stimme?',
  'Wer ist die Person, die allen das Gefühl gibt, dazuzugehören?',
  'Wer schreibt die liebsten Nachrichten?',
  'Wer würde am ehesten Fremden spontan helfen?',
  'Wer von euch hat die positivste Ausstrahlung?',
  'Wer ist am geduldigsten mit anderen?',
  'Wer wäre die beste Person, um ein Haustier zu hüten?',
  'Wer von euch hat den besten Kleidungsstil?',
  'Wer ist die Person, die man immer um Rat fragen kann?',
  'Wer würde am ehesten eine Überraschungsparty für jemanden organisieren?',
  'Wer hat die kreativsten Ideen?',
  'Wer von euch bringt andere am schnellsten zum Lachen?',
  'Wer wäre die beste Patentante oder der beste Patenonkel?',
  'Wer ist die Person, auf die man sich immer verlassen kann?',
  'Wer würde am ehesten mit dir eine ganze Nacht durchquatschen?',
  'Wer von euch hat die schönsten Augen?',
  'Wer ist am hilfsbereitesten, wenn jemand krank ist?',
  'Wer würde am ehesten Suppe vorbeibringen, wenn es dir schlecht geht?',
  'Wer ist die Person, die nie schlecht über andere redet?',
  'Wer von euch ist am mutigsten?',
  'Wer verbreitet die gemütlichste Stimmung?',
  'Wer würde am ehesten eine Playlist extra für dich zusammenstellen?',
  'Wer ist die Person, deren Umarmungen jeden Tag retten können?',
  'Wer von euch ist am großzügigsten?',
  'Wer hat sich in den letzten Jahren am meisten positiv entwickelt?',
  'Wer würde am ehesten einen Streit in der Gruppe friedlich schlichten?',
  'Wer ist die Person, die immer an alle denkt?',
  'Wer von euch tanzt am schönsten?',
  'Wer hat die beste Energie am Morgen?',
  'Wer würde am ehesten eine handgeschriebene Karte verschicken?',
  'Wer ist die Person, mit der man am liebsten einen Filmabend macht?',
  'Wer von euch ist am bodenständigsten geblieben?',
  'Wer wäre ein großartiges Elternteil?',
  'Wer erzählt die besten Geschichten?',
  'Wer würde am ehesten bei einer Prüfung mitfiebern und danach anrufen?',
  'Wer ist die Person, die einen nie im Stich lässt?',
  'Wer von euch ist am verständnisvollsten?',
  'Wer hat das wärmste Herz in dieser Runde?',
  'Wer würde am ehesten das letzte Stück Pizza abgeben?',
  'Wer ist die Person, die man allen Eltern ohne Sorge vorstellen würde?',
  'Wer von euch ist am motivierendsten?',
  'Wer würde den besten Lehrer oder die beste Lehrerin abgeben?',
  'Wer hat die schönsten Erinnerungen mit dieser Gruppe geschaffen?',
  'Wer ist die Person, die am meisten an andere glaubt?',
  'Wer von euch hat das beste Gespür dafür, wenn es jemandem nicht gut geht?',
  'Wer würde am ehesten einen Regentag in ein Abenteuer verwandeln?',
  'Wer ist am aufmerksamsten bei kleinen Details?',
  'Wer von euch würde die beste Rede auf einer Hochzeit halten?',
  'Wer ist die Person, ohne die diese Gruppe nicht dieselbe wäre?',
  'Wer würde am ehesten deine Pflanzen gießen, wenn du verreist bist?',
  'Wer hat das beste Lachen, wenn er oder sie sich richtig freut?',
  'Wer von euch macht diese Welt ein kleines bisschen schöner?',
];
