export const futureQuestions: string[] = [
  'Wer von euch heiratet als Erstes?',
  'Wer wird eines Tages richtig reich?',
  'Wer landet irgendwann im Fernsehen?',
  'Wer wandert als Erstes ins Ausland aus?',
  'Wer wird am ehesten mit Videos im Internet berühmt?',
  'Wer von euch hat später die meisten Kinder?',
  'Wer leitet irgendwann eine eigene Firma?',
  'Wer lebt mit 50 in einem Wohnwagen und ist glücklich damit?',
  'Wer wird am ehesten 100 Jahre alt?',
  'Wer verliert eines Tages alles Ersparte im Casino?',
  'Wer gewinnt irgendwann im Lotto und erzählt es niemandem?',
  'Wer wohnt mit 40 noch im alten Kinderzimmer bei den Eltern?',
  'Wer zieht als Letztes von zu Hause aus?',
  'Wer geht am ehesten in die Politik?',
  'Wer schreibt eines Tages ein Buch über das eigene Leben?',
  'Wer hat als Erstes Enkelkinder?',
  'Wer kauft sich als Erstes ein Haus?',
  'Wer zieht später aufs Land und hält Hühner?',
  'Wer eröffnet irgendwann eine eigene Bar?',
  'Wer landet am ehesten in einer Reality Show?',
  'Wer wird eines Tages auf der Straße erkannt?',
  'Wer heiratet am ehesten spontan in Las Vegas?',
  'Wessen Haustier hat später mehr Follower als alle hier zusammen?',
  'Wer zieht für die Liebe ans andere Ende der Welt?',
  'Wer arbeitet mit 75 noch, weil Rente zu langweilig ist?',
  'Wer geht als Erstes in Rente?',
  'Wer bereut als Erstes ein Tattoo?',
  'Wer gründet ein Startup, das grandios scheitert?',
  'Wer lebt irgendwann allein auf einer einsamen Insel?',
  'Wer fliegt als Erstes ins Weltall?',
  'Wer schafft es eines Tages ins Buch der Rekorde?',
  'Wer wird irgendwann ins Rathaus gewählt?',
  'Wer hat mit 30 schon drei Hunde?',
  'Wem gehört eines Tages ein eigenes Weingut?',
  'Wer zieht am ehesten in eine Hippie Kommune?',
  'Wer verliert irgendwann alles und fängt komplett neu an?',
  'Wer wird eines Tages vom Blitz getroffen und überlebt?',
  'Wer sitzt in 20 Jahren noch jeden Freitag in derselben Kneipe?',
  'Wer bekommt als Erstes graue Haare?',
  'Wer wird später das peinlichste Elternteil auf jedem Elternabend?',
  'Wer kauft sich in der Midlife Crisis ein knallrotes Cabrio?',
  'Wer wohnt mit 45 noch in einer WG?',
  'Wer sitzt eines Tages im Gefängnis und macht danach einen Podcast darüber?',
  'Wer verdient später sein Geld als Profi beim Pokern?',
  'Wer betreibt mit 60 eine Strandbar in Thailand?',
  'Wer feiert den 50. Geburtstag im Club bis 8 Uhr morgens?',
  'Wer gewinnt irgendwann eine Million bei einer Quizshow?',
  'Wer verschläft die eigene Hochzeit?',
  'Wer tritt am ehesten einer seltsamen Sekte bei?',
  'Wer lebt später vegan und redet über nichts anderes mehr?',
  'Wer lebt eines Tages ohne Handy in einer Hütte im Wald?',
  'Wen verfolgen irgendwann Paparazzi?',
  'Wer bekommt als Erstes einen eigenen Eintrag bei Wikipedia?',
  'Wer hat später ein Haus voller Katzen?',
  'Wer zieht nach Mallorca und eröffnet dort eine Kneipe?',
  'Wer bekommt als Erstes Zwillinge?',
  'Wer wird so reich, dass alle hier um Geld betteln müssen?',
  'Wer bekommt mit 80 noch Strafzettel fürs Rasen?',
  'Wer heiratet am Ende jemanden aus der eigenen Schulklasse?',
  'Wer wird eines Tages Stammgast in der Notaufnahme?',
  'Wer erfindet etwas völlig Sinnloses und wird damit steinreich?',
  'Wer trägt in 20 Jahren noch genau dieselben Klamotten?',
  'Wer zieht in ein Tiny House und bereut es nach einer Woche?',
  'Wer unterrichtet irgendwann an der eigenen alten Schule?',
  'Wer wird durch ein virales Video über Nacht weltbekannt?',
  'Wer verbringt die Rente komplett auf einem Kreuzfahrtschiff?',
  'Wer landet eines Tages auf der Titelseite einer Zeitung?',
  'Wer lernt mit 60 noch Skateboard fahren?',
  'Bei wem feiert später die ganze Familie jedes Jahr Weihnachten?',
  'Wer verwettet irgendwann das eigene Auto?',
  'Wer arbeitet später nur noch im Schlafanzug aus dem Homeoffice?',
  'Wer steht eines Tages als Schlagerstar auf der Bühne?',
  'Wer gründet später eine eigene Religion?',
  'Wer bleibt für immer Single und ist super glücklich damit?',
  'Wer benennt das eigene Kind nach einem Fußballstar?',
  'Wer fängt mit 50 noch ein Studium an?',
  'Wer wohnt irgendwann in einer Villa mit Pool?',
  'Wer sucht eines Tages die große Liebe in einer Datingshow im Fernsehen?',
  'Wer verliert als Erstes den Führerschein?',
  'Wer überrascht beim Klassentreffen in 20 Jahren alle am meisten?',
];
