export const futureQuestions: string[] = [
  'Wer von euch heiratet als Erstes?',
  'Wer landet irgendwann im Fernsehen?',
  'Wer wandert als Erstes ins Ausland aus?',
  'Wer lebt mit 50 in einem Wohnwagen und ist glücklich damit?',
  'Wer wird am ehesten 100 Jahre alt?',
  'Wer verliert eines Tages alles Ersparte im Casino?',
  'Wer gewinnt irgendwann im Lotto und erzählt es niemandem?',
  'Wer wohnt mit 40 noch im alten Kinderzimmer bei den Eltern?',
  'Wer schreibt eines Tages ein Buch über das eigene Leben?',
  'Wer hat als Erstes Enkelkinder?',
  'Wer kauft sich als Erstes ein Haus?',
  'Wer zieht später aufs Land und hält Hühner?',
  'Wer heiratet am ehesten spontan in Las Vegas?',
  'Wessen Haustier hat später mehr Follower als alle hier zusammen?',
  'Wer zieht für die Liebe ans andere Ende der Welt?',
  'Wer arbeitet mit 75 noch, weil Rente zu langweilig ist?',
  'Wer bereut als Erstes ein Tattoo?',
  'Wer fliegt als Erstes ins Weltall?',
  'Wer schafft es eines Tages ins Buch der Rekorde?',
  'Wer hat mit 30 schon drei Hunde?',
  'Wem gehört eines Tages ein eigenes Weingut?',
  'Wer zieht am ehesten in eine Hippiekommune?',
  'Wer sitzt in 20 Jahren noch jeden Freitag in derselben Kneipe?',
  'Wer wird später das peinlichste Elternteil auf jedem Elternabend?',
  'Wer kauft sich in der Midlife Crisis ein knallrotes Cabrio?',
  'Wer wohnt mit 45 noch in einer WG?',
  'Wer sitzt eines Tages im Gefängnis und macht danach einen Podcast darüber?',
  'Wer verdient später sein Geld als Profi beim Pokern?',
  'Wer betreibt mit 60 eine Strandbar in Thailand?',
  'Wer feiert den 50. Geburtstag im Club bis 8 Uhr morgens?',
  'Wer gewinnt irgendwann eine Million bei einer Quizshow?',
  'Wer verschläft die eigene Hochzeit?',
  'Wer tritt am ehesten einer seltsamen Sekte bei?',
  'Wer lebt später vegan und redet über nichts anderes mehr?',
  'Wer lebt eines Tages ohne Handy in einer Hütte im Wald?',
  'Wen verfolgen irgendwann Paparazzi?',
  'Wer bekommt als Erstes einen eigenen Eintrag bei Wikipedia?',
  'Wer hat später ein Haus voller Katzen?',
  'Wer zieht nach Mallorca und eröffnet dort eine Kneipe?',
  'Wer bekommt als Erstes Zwillinge?',
  'Wer wird so reich, dass alle hier um Geld betteln müssen?',
  'Wer bekommt mit 80 noch Strafzettel fürs Rasen?',
  'Wer heiratet am Ende jemanden aus der eigenen Schulklasse?',
  'Wer wird eines Tages Stammgast in der Notaufnahme?',
  'Wer erfindet etwas völlig Sinnloses und wird damit steinreich?',
  'Wer trägt in 20 Jahren noch genau dieselben Klamotten?',
  'Wer zieht in ein Tiny House und bereut es nach einer Woche?',
  'Wer unterrichtet irgendwann an der eigenen alten Schule?',
  'Wer wird durch ein virales Video über Nacht weltbekannt?',
  'Wer verbringt die Rente komplett auf einem Kreuzfahrtschiff?',
  'Wer lernt mit 60 noch Skateboard fahren?',
  'Bei wem feiert später die ganze Familie jedes Jahr Weihnachten?',
  'Wer verwettet irgendwann das eigene Auto?',
  'Wer arbeitet später nur noch im Schlafanzug aus dem Homeoffice?',
  'Wer steht eines Tages als Schlagerstar auf der Bühne?',
  'Wer gründet später eine eigene Religion?',
  'Wer bleibt für immer Single und ist super glücklich damit?',
  'Wer benennt das eigene Kind nach einem Fußballstar?',
  'Wer fängt mit 50 noch ein Studium an?',
  'Wer sucht eines Tages die große Liebe in einer Datingshow im Fernsehen?',
  'Wer verliert als Erstes den Führerschein?',
  'Wer überrascht beim Klassentreffen in 20 Jahren alle am meisten?',
  'Wer heiratet im Laufe des Lebens mehr als dreimal?',
  'Wer macht irgendwann einen Heiratsantrag vor einem ganzen Fußballstadion?',
  'Wer feiert eines Tages eine Hochzeit mit über 500 Gästen?',
  'Wer heiratet heimlich und erzählt es allen erst ein Jahr später?',
  'Wer lernt die große Liebe an der Supermarktkasse kennen?',
  'Wer bekommt beim eigenen Heiratsantrag ein Nein?',
  'Wer von euch feiert irgendwann die goldene Hochzeit?',
  'Wer heiratet am ehesten jemanden, den die ganze Gruppe nicht ausstehen kann?',
  'Wer heiratet in einem Kostüm aus einem Fantasyfilm?',
  'Wer ist am Ende 15 Jahre verlobt, ohne je zu heiraten?',
  'Wen fragen später die meisten Leute, ob er oder sie Trauzeuge sein will?',
  'Wer heiratet unter Wasser mit Taucherbrille?',
  'Wer hält auf der eigenen Hochzeit eine Rede, die eine ganze Stunde dauert?',
  'Wer verkuppelt später die meisten Paare im Freundeskreis?',
  'Wer kommt irgendwann wieder mit der ersten großen Liebe zusammen?',
  'Wer erneuert alle fünf Jahre das Eheversprechen mit großer Feier?',
  'Wer wird später das strengste Elternteil von allen?',
  'Wer wird das entspannteste Elternteil der Welt?',
  'Wer bekommt mit über 45 noch das erste Kind?',
  'Wer hat später so viele Kinder, dass es für eine eigene Fußballmannschaft reicht?',
  'Wer gibt den eigenen Kindern die verrücktesten Namen?',
  'Wer wird später Elternsprecher und organisiert jedes Schulfest?',
  'Wer wird das coolste Großelternteil, mit dem die Enkel am liebsten feiern gehen?',
  'Wer stopft die Enkel später heimlich mit Süßigkeiten voll?',
  'Wer fährt als Elternteil einen riesigen Van mit acht Sitzen?',
  'Wer wird von den eigenen Kindern später im Internet bloßgestellt?',
  'Wer zwingt die eigenen Kinder später, Blockflöte zu lernen?',
  'Wer schreit später am lautesten am Rand vom Kinderfußball?',
  'Wer plant für die eigenen Kinder die aufwendigsten Geburtstagspartys?',
  'Wer wird die Tante oder der Onkel, bei dem die Kinder alles dürfen?',
  'Wer hat am Ende keine eigenen Kinder, aber zwölf Patenkinder?',
  'Wer erzählt den eigenen Kindern später die peinlichsten Geschichten von heute?',
  'Wer ruft später bei jedem Handyproblem die eigenen Kinder an?',
  'Wer wird eines Tages Chef von einem riesigen Konzern?',
  'Wer kündigt irgendwann spontan per Sprachnachricht?',
  'Wer wechselt im Leben am häufigsten den Job?',
  'Wer bleibt 40 Jahre lang in derselben Firma?',
  'Wer arbeitet eines Tages als Barkeeper auf einem Kreuzfahrtschiff?',
  'Wer wird Chef der freiwilligen Feuerwehr im Dorf?',
  'Wer macht später Karriere als Influencer für Rentnerprodukte?',
  'Wer wird eines Tages Sternekoch?',
  'Wer wird Lehrer und bereut es schon am ersten Tag?',
  'Wer verdient von euch als Erstes ein sechsstelliges Gehalt?',
  'Wer arbeitet eines Tages beim Geheimdienst und darf niemandem davon erzählen?',
  'Wer wird Bestatter mit dem schwärzesten Humor?',
  'Wer schmeißt den gut bezahlten Job hin und wird Yogalehrer auf Bali?',
  'Wer wird als Erstes von einem Roboter im Job ersetzt?',
  'Wer wird Weltmeister in einer völlig unbekannten Sportart?',
  'Wer wird Trainer einer Fußballmannschaft in der Kreisliga?',
  'Wer wird irgendwann Schiedsrichter und von allen beschimpft?',
  'Wer forscht eines Tages ein Jahr lang in einer Station in der Antarktis?',
  'Wer arbeitet später als Privatdetektiv?',
  'Wer legt irgendwann als berühmter DJ auf Ibiza auf?',
  'Wer wird Hausmeister und liebt den Job über alles?',
  'Wer bekommt eines Tages einen Nobelpreis?',
  'Wer wird Anwalt und gewinnt danach jeden Streit, auch privat?',
  'Wer wird irgendwann Zirkusdirektor?',
  'Wer moderiert später das Wetter im Fernsehen?',
  'Wer arbeitet eines Tages als Butler für Superreiche?',
  'Wer wird die Chefin oder der Chef, den alle Angestellten hassen?',
  'Wer ist mit 30 Millionär und mit 35 pleite?',
  'Wer macht sich von euch als Erstes selbstständig?',
  'Wer leiht später einer Figur in einem Zeichentrickfilm die Stimme?',
  'Wer kauft irgendwann einen Fußballverein?',
  'Wer wird mit Kryptowährung reich und verliert alles wieder?',
  'Wer erbt eines Tages von einer unbekannten Tante ein Schloss?',
  'Wer hat mit 60 immer noch Schulden beim Dispo?',
  'Wer spendet später ein Vermögen für einen guten Zweck?',
  'Wer kauft sich als Erstes einen Privatjet?',
  'Wer leiht sich später von allen hier Geld und zahlt es nie zurück?',
  'Wer gibt das erste große Gehalt komplett für Sneaker aus?',
  'Wer lebt später sparsam wie ein Mönch, obwohl Millionen auf dem Konto sind?',
  'Wer kauft sich mit 70 einen Lamborghini?',
  'Wer bezahlt später für alle hier eine Reise um die Welt?',
  'Wer bekommt eines Tages einen Oscar?',
  'Wer spielt irgendwann in einem Tatort mit?',
  'Wer moderiert später eine eigene Talkshow?',
  'Wer gewinnt eines Tages eine Castingshow?',
  'Wer singt irgendwann beim Eurovision Song Contest?',
  'Wer zieht eines Tages ins Dschungelcamp ein?',
  'Wer wird als Statist in einem Hollywoodfilm entdeckt?',
  'Wer wird eines Tages das Gesicht einer Werbung für Hämorrhoidensalbe?',
  'Wer bekommt eine eigene Kochsendung im Fernsehen?',
  'Wer wird in einer Doku über seltsame Hobbys gezeigt?',
  'Wer gibt irgendwann in den Nachrichten ein Interview als Augenzeuge?',
  'Wer singt eines Tages in einer Boyband oder Girlgroup?',
  'Wer füllt später ein ganzes Stadion mit einem eigenen Konzert?',
  'Wer steht irgendwann als Wachsfigur bei Madame Tussauds?',
  'Wessen Gesicht ist eines Tages auf einer Briefmarke?',
  'Wer wird der Star einer Seifenoper im Nachmittagsprogramm?',
  'Wer landet in einer Gameshow und fällt vor laufender Kamera ins Wasserbecken?',
  'Wer verdient später Geld mit Videos, in denen nur gegessen wird?',
  'Wer startet einen Podcast, den nur die eigene Mutter hört?',
  'Wer wird ein berühmter Gamer mit Millionen Zuschauern?',
  'Wer gewinnt irgendwann den Deutschen Comedypreis?',
  'Über wessen Leben dreht Netflix eines Tages eine eigene Serie?',
  'Wer sitzt später jeden Sonntagabend in einer politischen Talkshow?',
  'Wer taucht in 30 Jahren in einer Rückblickshow als peinlichster Moment des Jahres auf?',
  'Wer postet mit 70 noch Tanzvideos im Internet?',
  'Wer wird später Influencer für Gartenzwerge?',
  'Wer verliert eines Tages alles wegen eines einzigen Posts?',
  'Wer löscht von euch als Erstes alle sozialen Netzwerke für immer?',
  'Wer startet eine Challenge, die weltweit alle nachmachen?',
  'Wer hat mit 80 einen YouTube Kanal über Strickmuster?',
  'Wer filmt später die eigenen Kinder jeden Tag für einen Familienkanal?',
  'Wer gibt im Internet allen Geldtipps und ist selbst pleite?',
  'Wer streamt die eigene Hochzeit live im Internet?',
  'Wer macht später Werbung für ein Produkt, das er oder sie heimlich hasst?',
  'Wer postet 40 Jahre lang jeden Tag ein Selfie?',
  'Wer bekommt den ersten großen Shitstorm wegen eines Kochrezepts?',
  'Wer wird später der Admin, der alle Gruppenchats der Familie verwaltet?',
  'Wer wandert nach Kanada aus und wird Holzfäller?',
  'Wer reist irgendwann mit dem Motorrad einmal um die Welt?',
  'Wer besucht von euch als Erstes alle Länder der Erde?',
  'Wer lebt später auf einem Hausboot?',
  'Wer wohnt eines Tages in einem alten Leuchtturm?',
  'Wer zieht in eine Großstadt und hält es nur zwei Wochen aus?',
  'Wer zieht nie aus der eigenen Heimatstadt weg?',
  'Wer zieht eines Tages in ein Kloster?',
  'Wer wohnt irgendwann neben einem Promi und klingelt dauernd?',
  'Wer wird der nervige Nachbar, der wegen jeder Hecke die Polizei ruft?',
  'Wer wohnt eines Tages in einem Smart Home, das nur noch macht, was es will?',
  'Wer wandert aus und zieht nach einem Monat heulend wieder zurück?',
  'Wer verpasst später auf Reisen die meisten Flüge?',
  'Wer pilgert irgendwann den ganzen Jakobsweg?',
  'Wer lebt später in Japan und spricht fließend Japanisch?',
  'Wer wohnt irgendwann direkt neben den eigenen Eltern?',
  'Wer zieht später mit allen Freunden in ein großes gemeinsames Haus?',
  'Wer wird Dauercamper mit Vorzelt, Satellitenschüssel und Gartenzaun?',
  'Wer renoviert ein altes Haus und wird nie damit fertig?',
  'Wer zieht in eine Stadt, nur weil dort der Lieblingsverein spielt?',
  'Wer arbeitet später mit dem Laptop von Stränden auf der ganzen Welt?',
  'Wer hat später eine eigene Kegelbahn im Keller?',
  'Wer hat irgendwann ein Ferienhaus in Italien, das alle hier nutzen dürfen?',
  'Wer wird der Rentner, der jeden Tag Baustellen beobachtet?',
  'Wer zockt mit 80 noch die ganze Nacht Computerspiele?',
  'Wer flirtet im Altersheim mit allen auf dem Flur?',
  'Wer springt mit 70 noch mit dem Fallschirm aus einem Flugzeug?',
  'Wer läuft mit 75 noch einen Marathon?',
  'Wer züchtet in der Rente preisgekrönte Riesenkürbisse?',
  'Wer schlägt im Alter alle Leute beim Schach im Park?',
  'Wer sitzt mit 85 jeden Tag mit Fernglas am Fenster?',
  'Wer verbringt die ganze Rente im Golfclub?',
  'Wer wird im Alter Stammgast beim Seniorentanz?',
  'Wer schreibt im Alter wütende Leserbriefe an die Zeitung?',
  'Wer steht mit 90 noch auf Festivals in der ersten Reihe?',
  'Wer fängt im Alter mit Bodybuilding an?',
  'Wer trägt im Alter nur noch beige Kleidung?',
  'Wer lernt in der Rente noch fünf neue Sprachen?',
  'Wer gründet im Altersheim eine Rockband?',
  'Wer wird im Alter Vorsitzender im Kleingartenverein und kontrolliert jede Hecke?',
  'Wer erzählt im Alter jede Geschichte zehnmal?',
  'Wer lässt sich mit 70 ein riesiges Tattoo stechen?',
  'Wer geht schon mit 45 in Frührente?',
  'Wer schreibt mit 90 noch Liebesbriefe?',
  'Wer glaubt im Alter an jede Verschwörungstheorie?',
  'Wer macht in der Rente noch den Führerschein für einen Lastwagen?',
  'Wer hat später ein Pferd im eigenen Garten?',
  'Wer gründet später eine eigene Alpakafarm?',
  'Wer wird Imker mit zehn Bienenvölkern?',
  'Wer gibt dem Haustier später einen Namen wie Günther oder Hildegard?',
  'Wer kauft dem eigenen Hund später einen Kinderwagen?',
  'Wer feiert für die eigene Katze einen Geburtstag mit Gästen?',
  'Wer hat später einen Papagei, der nur Schimpfwörter kann?',
  'Wer gewinnt mit dem eigenen Hund einen Schönheitswettbewerb?',
  'Wer hat später ein Hausschwein, das mit in der Wohnung lebt?',
  'Wer wird Schafhirte in den Alpen?',
  'Wer hält später Ziegen auf dem Balkon?',
  'Wer geht mit dem eigenen Haustier später zum Tierpsychologen?',
  'Wer verkauft später selbstgemachten Käse auf dem Wochenmarkt?',
  'Wer fährt eines Tages stolz mit dem eigenen Traktor durchs Dorf?',
  'Wer fängt mit 40 an, Modelleisenbahnen zu bauen?',
  'Wer wird eines Tages Schützenkönig im Dorf?',
  'Wer läuft eines Tages einen Ultramarathon durch die Wüste?',
  'Wer steht irgendwann auf dem Gipfel des Mount Everest?',
  'Wer singt später jeden Mittwoch im Kirchenchor?',
  'Wer spielt später in einer Coverband auf Dorffesten?',
  'Wer wird süchtig nach Puzzles mit 5000 Teilen?',
  'Wer baut später Schiffe in Flaschen?',
  'Wer wird Weltmeister im Luftgitarrespielen?',
  'Wer wird eines Tages Karnevalsprinz?',
  'Wer verbringt später jedes Wochenende in Ritterrüstung beim Mittelalterverein?',
  'Wer sammelt später Figuren aus Überraschungseiern im Wert eines Autos?',
  'Wer schwimmt eines Tages durch den Ärmelkanal?',
  'Wer kennt später jeden Pilz im Wald beim Namen?',
  'Wer wird der Hobbykoch, der allen ungefragt Tipps gibt?',
  'Wer braut später eigenes Bier im Keller?',
  'Wer wird eines Tages Bundeskanzler?',
  'Wer gründet irgendwann eine eigene Partei?',
  'Wer zieht eines Tages ins Schloss Bellevue ein?',
  'Wer kandidiert für den Bundestag und bekommt genau drei Stimmen?',
  'Wer organisiert später die größte Demo der Stadt?',
  'Wer wird Minister für ein Ministerium, das niemand kennt?',
  'Nach wem wird eines Tages ein Gesetz benannt?',
  'Wer wird im Gemeinderat für die längsten Reden berüchtigt?',
  'Wer kettet sich irgendwann aus Protest an einen Baum?',
  'Wer wird Wahlhelfer und zählt jede Stimme dreimal?',
  'Wer muss eines Tages vor einem Untersuchungsausschuss aussagen?',
  'Wer wird Präsident eines winzigen Landes, das niemand kennt?',
  'Wer erfindet eines Tages ein Gerät, das wirklich die Welt verändert?',
  'Wer gründet ein Startup und verkauft es an Google?',
  'Wer pitcht irgendwann eine Idee bei Die Höhle der Löwen?',
  'Wer erfindet ein neues Getränk, das plötzlich alle trinken?',
  'Wer gründet eine Firma, die Socken im Abo verkauft?',
  'Wer erfindet eine ganz neue Sportart?',
  'Wer erfindet ein Partyspiel, das die ganze Welt spielt?',
  'Wer gründet ein Startup mit 50 Angestellten und keinem einzigen Kunden?',
  'Wer erfindet einen neuen Feiertag, den alle feiern?',
  'Wer entdeckt eines Tages eine neue Tierart?',
  'Wessen Gewürzmischung steht eines Tages in jedem Supermarkt?',
  'Wer organisiert irgendwann ein eigenes Musikfestival?',
  'Wer eröffnet eine ganze Kette von Dönerläden?',
  'Wer eröffnet ein Café, in dem Katzen den Kaffee servieren?',
  'Wer schreibt einen Krimi, in dem alle hier als Verdächtige vorkommen?',
  'Wer wird ein Maler, dessen Bilder erst nach dem Tod etwas wert sind?',
  'Wer schreibt einen Beziehungsratgeber, obwohl es selbst nie klappt?',
  'Wer wird ein bekannter Kinderbuchautor?',
  'Wer dreht irgendwann einen eigenen Kinofilm?',
  'Wer schreibt eines Tages ein eigenes Musical?',
  'Wer schreibt eine Fantasyreihe mit zwölf Bänden und wird nie fertig?',
  'Wer gründet mit 45 noch eine Punkband?',
  'Wer kündigt in der Midlife Crisis alles und segelt um die Welt?',
  'Wer kauft sich in der Midlife Crisis ein Motorrad, das nur in der Garage steht?',
  'Wer lässt sich nach dem Tod einfrieren, um später wieder aufzuwachen?',
  'Wer findet eines Tages einen echten Schatz?',
  'Wer gewinnt eines Tages einen Prozess gegen einen Weltkonzern?',
  'Wer wird durch eine völlig bescheuerte Mutprobe berühmt?',
  'Wer landet eines Tages aus Versehen ohne Pass in einem fremden Land?',
  'Wer hat in zehn Jahren immer noch dasselbe Handy?',
  'Wer wird eines Tages Ehrenbürger der eigenen Stadt?',
  'Wer bekommt von euch als Erstes eine Glatze?',
  'Wer trinkt mit 60 noch Dosenbier im Park mit den alten Freunden?',
  'Wer organisiert in 20 Jahren das große Wiedersehen dieser Gruppe?',
  'Wer ist in 30 Jahren immer noch mit allen hier befreundet?',
  'Wer ruft in zehn Jahren noch nachts um drei an, nur um zu quatschen?',
  'Wer wird irgendwann zum Spießer, der Socken in Sandalen trägt?',
  'Wer wird in zehn Jahren genau wie die eigenen Eltern?',
  'Wer verwechselt im Alter ständig die Namen der Enkel?',
];
