export const interactiveQuestions: string[] = [
  'Wer tanzt am schlechtesten? Zeig uns 10 Sekunden deinen besten Move!',
  'Wer kann am besten Leute nachmachen? Imitiere jemanden aus der Runde, die anderen raten!',
  'Wer hat die lauteste Lache? Lach 5 Sekunden so laut du kannst!',
  'Wer singt am liebsten unter der Dusche? Sing den Refrain deines Lieblingssongs!',
  'Wer macht die besten Komplimente? Mach jeder Person in der Runde ein ehrliches Kompliment!',
  'Wer hat die meisten Selfies auf dem Handy? Zeig der Runde dein letztes Selfie!',
  'Wer schreibt die meisten Nachrichten am Tag? Lies deine letzte gesendete Nachricht laut vor!',
  'Wer wäre die beste Besetzung für Hollywood? Spiel pantomimisch einen Film vor, die anderen raten!',
  'Wer hat das beste Pokerface? Bleib 30 Sekunden ernst, während alle versuchen, dich zum Lachen zu bringen!',
  'Wer könnte am ehesten Stand-up-Comedy machen? Erzähl uns deinen besten Witz!',
  'Wer ist am dramatischsten? Spiel uns eine Sterbeszene wie im Film vor!',
  'Wer hat das schönste Lächeln? Lächle zehn Sekunden lang die Person links von dir an!',
  'Wer kann am besten Tiergeräusche? Mach drei Tiere nach, die anderen raten!',
  'Wer würde bei einer Castingshow mitmachen? Präsentier uns dein verstecktes Talent!',
  'Wer redet am schnellsten? Sag einen Zungenbrecher dreimal hintereinander fehlerfrei!',
  'Wer wäre die beste Moderation für eine Gala? Kündige die nächste Person an, als wäre sie ein Superstar!',
  'Wer hat die beste Singstimme? Sing ein Kinderlied, als stündest du auf einer Opernbühne!',
  'Wer schickt die meisten Sprachnachrichten? Nimm eine Sprachnachricht mit einem Lob an die Runde auf und spiel sie ab!',
  'Wer hat den seltsamsten Emoji-Verlauf? Zeig der Runde deine zuletzt benutzten Emojis!',
  'Wer würde am ehesten einen Tanz-Battle gewinnen? Fordere jemanden zu einem 15-Sekunden-Battle heraus!',
  'Wer ist am schlagfertigsten? Erfinde in 10 Sekunden einen Reim auf die Person rechts von dir!',
  'Wer hat das beste Gedächtnis? Nenne die Getränke aller Personen in der Runde, ohne hinzuschauen!',
  'Wer wäre die beste Stimme für Werbung? Verkauf uns dein Getränk in einem 20-Sekunden-Werbespot!',
  'Wer könnte am ehesten Nachrichten sprechen? Verkünde die Ereignisse dieses Abends als Eilmeldung!',
  'Wer fotografiert am häufigsten sein Essen? Zeig uns dein letztes Essensfoto!',
  'Wer ist am ehrlichsten? Sag der Person gegenüber, was du an ihr am meisten schätzt!',
  'Wer könnte am besten einen Roboter spielen? Bewege dich 30 Sekunden lang wie ein Roboter!',
  'Wer hat das Zeug zum Influencer? Mach ein Selfie mit der Runde und erfinde eine Caption dazu!',
  'Wer kann am besten Akzente? Erzähl uns in einem Akzent deiner Wahl, wie dein Tag war!',
  'Wer würde am ehesten Karaoke singen? Sing die erste Strophe eines Songs, den alle kennen!',
  'Wer kann am besten Luftgitarre spielen? Gib uns ein 15-Sekunden-Solo!',
  'Wer könnte am besten Fußball kommentieren? Kommentiere live, was die Person links von dir gerade tut!',
  'Wer wäre die beste Besetzung fürs Bürgermeisteramt? Halte eine kurze Wahlkampfrede für die Runde!',
  'Wer ist am schlechtesten im Lügen? Erzähl zwei Wahrheiten und eine Lüge, die anderen raten!',
  'Wer verschickt die witzigsten Memes? Zeig uns das letzte Meme, das du verschickt hast!',
  'Wer hat die markanteste Stimme? Lies diese Karte noch einmal wie ein Hörbuch vor!',
  'Wer hat am meisten Zauberkraft? Lass etwas am Tisch verschwinden oder zeig uns einen Trick!',
  'Wer kann am besten flirten? Mach der Person rechts von dir ein charmantes Kompliment!',
  'Wer würde in einem Musical mitspielen? Sing uns vor, was du heute gegessen hast!',
  'Wer hat das beste Gleichgewicht? Stell dich 30 Sekunden auf ein Bein und trink dabei einen Schluck!',
  'Wer kann am besten motivieren? Gib der Runde eine 20-Sekunden-Motivationsrede!',
  'Wer tippt am schnellsten? Tippe in 10 Sekunden einen Satz, den die Runde vorgibt!',
  'Wer kann am besten Grimassen schneiden? Zeig uns deine drei besten Grimassen!',
  'Wer würde am ehesten bei einer Quizshow gewinnen? Beantworte eine Wissensfrage, die die Runde dir stellt!',
  'Wer erzählt die besten Geschichten? Erzähl in 30 Sekunden ein Märchen mit allen aus der Runde als Figuren!',
  'Wer ist am diplomatischsten? Schlichte einen erfundenen Streit zwischen den zwei Personen neben dir!',
  'Wer verliert am schnellsten die Geduld? Bleib 20 Sekunden lang komplett still und regungslos!',
  'Wer hat die lustigsten Kontaktnamen im Handy? Zeig uns deinen kuriosesten Kontaktnamen!',
  'Wer hat am meisten ungelesene Nachrichten? Zeig der Runde die Zahl auf deinem Handy!',
  'Wer telefoniert am liebsten? Ruf eine Person deiner Wahl an und sag ihr, dass du sie magst!',
  'Wer ist am aktivsten in Gruppenchats? Schick ein nettes Kompliment in einen Gruppenchat deiner Wahl!',
  'Wer ist am nostalgischsten? Zeig uns das älteste Foto in deiner Galerie!',
  'Wer kennt die meisten Werbejingles? Sing einen Werbejingle, die anderen raten die Marke!',
  'Wer hat den besten Musikgeschmack für Partys? Spiel uns einen Song vor, der jetzt die Stimmung hebt!',
  'Wer würde am ehesten eine Rede auf einer Hochzeit halten? Halte einen Toast auf die Runde!',
  'Wer hat die beste Körperbeherrschung? Mach den Moonwalk oder versuche es zumindest!',
  'Wer ist am besten in Pantomime? Stell pantomimisch einen Beruf dar, die anderen raten!',
  'Wer schaut die meisten Serien? Spiel eine Szene aus deiner Lieblingsserie nach, die anderen raten!',
  'Wer kann am besten Promis nachmachen? Imitiere einen Promi, bis jemand ihn errät!',
  'Wer ist der größte Fan einer Band? Summe einen Song dieser Band, die anderen raten!',
  'Wer hätte das Zeug zum Rap-Star? Rappe vier Zeilen über die Person links von dir!',
  'Wer kann am besten erklären? Bring der Runde in 30 Sekunden etwas bei, das du richtig gut kannst!',
  'Wer ist am witzigsten ohne Worte? Bring die Runde in 20 Sekunden zum Lachen, ohne zu sprechen!',
  'Wer hat den besten Spürsinn? Rate, wer in der Runde heute am meisten getrunken hat, und begründe es!',
  'Wer ist am mutigsten? Lass die Runde eine harmlose Nachricht formulieren und schick sie an einen Kontakt deiner Wahl!',
  'Wer ist am hilfsbereitesten? Bediene die Person rechts von dir bis zur nächsten Karte wie im Luxushotel!',
  'Wer kann am besten zeichnen? Zeichne mit dem Finger ein Bild in die Luft, die anderen raten!',
  'Wer ist am sportlichsten? Mach 10 Hampelmänner und motiviere die Runde mitzumachen!',
  'Wer könnte am besten einen Bösewicht spielen? Lach wie ein Filmbösewicht und verrate deinen fiesen Plan!',
  'Wer hat den feinsten Geschmack? Beschreibe dein Getränk, als wärst du auf einer Weinprobe!',
  'Wer verrät sich am schnellsten? Schau der Person gegenüber 20 Sekunden in die Augen, ohne zu lachen!',
  'Wer hat den besten Musikgeschmack? Zeig uns deinen zuletzt gehörten Song und verteidige ihn!',
  'Wer ist am neugierigsten? Interviewe die Person links von dir mit drei spontanen Fragen!',
  'Wer würde am ehesten auf einer Bühne auftreten? Verbeuge dich und lass dich 10 Sekunden von der Runde feiern!',
  'Wer hat die kreativste Fantasie? Erfinde ein neues Wort und erkläre, was es bedeutet!',
  'Wer kann am besten mit Kindern? Erklär uns das Internet, als wären wir fünf Jahre alt!',
  'Wer verschläft am häufigsten? Spiel der Runde deinen Weckerton vor!',
  'Wer hat das größte Sprachtalent? Sag einen Satz in so vielen Sprachen wie möglich!',
  'Wer gibt die besten Ratschläge? Gib der Person rechts von dir einen Lebenstipp für die Woche!',
  'Wer hat am meisten Energie? Steh auf und starte mit der ganzen Runde eine La Ola!',
];
