export const interactiveQuestions: string[] = [
  'Wer tanzt am schlechtesten? Zeig uns 10 Sekunden deinen besten Move!',
  'Wer kann am besten Leute nachmachen? Imitiere jemanden aus der Runde, die anderen raten!',
  'Wer hat die lauteste Lache? Lach 5 Sekunden so laut du kannst!',
  'Wer macht die besten Komplimente? Mach jeder Person in der Runde ein ehrliches Kompliment!',
  'Wer wäre die beste Besetzung für Hollywood? Spiel pantomimisch einen Film vor, die anderen raten!',
  'Wer hat das beste Pokerface? Bleib 30 Sekunden ernst, während alle versuchen, dich zum Lachen zu bringen!',
  'Wer könnte am ehesten Stand-up-Comedy machen? Erzähl uns deinen besten Witz!',
  'Wer ist am dramatischsten? Spiel uns eine Sterbeszene wie im Film vor!',
  'Wer hat das schönste Lächeln? Lächle zehn Sekunden lang die Person links von dir an!',
  'Wer kann am besten Tiergeräusche? Mach drei Tiere nach, die anderen raten!',
  'Wer würde bei einer Castingshow mitmachen? Präsentier uns dein verstecktes Talent!',
  'Wer wäre die beste Moderation für eine Gala? Kündige die nächste Person an, als wäre sie ein Superstar!',
  'Wer hat die beste Singstimme? Sing ein Kinderlied, als stündest du auf einer Opernbühne!',
  'Wer hat den seltsamsten Emoji-Verlauf? Zeig der Runde deine zuletzt benutzten Emojis!',
  'Wer würde am ehesten einen Tanz-Battle gewinnen? Fordere jemanden zu einem 15-Sekunden-Battle heraus!',
  'Wer ist am schlagfertigsten? Erfinde in 10 Sekunden einen Reim auf die Person rechts von dir!',
  'Wer hat das beste Gedächtnis? Nenne die Getränke aller Personen in der Runde, ohne hinzuschauen!',
  'Wer wäre die beste Stimme für Werbung? Verkauf uns dein Getränk in einem 20-Sekunden-Werbespot!',
  'Wer könnte am ehesten Nachrichten sprechen? Verkünde die Ereignisse dieses Abends als Eilmeldung!',
  'Wer ist am ehrlichsten? Sag der Person gegenüber, was du an ihr am meisten schätzt!',
  'Wer könnte am besten einen Roboter spielen? Bewege dich 30 Sekunden lang wie ein Roboter!',
  'Wer kann am besten Luftgitarre spielen? Gib uns ein 15-Sekunden-Solo!',
  'Wer könnte am besten Fußball kommentieren? Kommentiere live, was die Person links von dir gerade tut!',
  'Wer wäre die beste Besetzung fürs Bürgermeisteramt? Halte eine kurze Wahlkampfrede für die Runde!',
  'Wer ist am schlechtesten im Lügen? Erzähl zwei Wahrheiten und eine Lüge, die anderen raten!',
  'Wer hat die markanteste Stimme? Lies diese Karte noch einmal wie ein Hörbuch vor!',
  'Wer hat am meisten Zauberkraft? Lass etwas am Tisch verschwinden oder zeig uns einen Trick!',
  'Wer würde in einem Musical mitspielen? Sing uns vor, was du heute gegessen hast!',
  'Wer hat das beste Gleichgewicht? Stell dich 30 Sekunden auf ein Bein und trink dabei einen Schluck!',
  'Wer kann am besten motivieren? Gib der Runde eine 20-Sekunden-Motivationsrede!',
  'Wer kann am besten Grimassen schneiden? Zeig uns deine drei besten Grimassen!',
  'Wer würde am ehesten bei einer Quizshow gewinnen? Beantworte eine Wissensfrage, die die Runde dir stellt!',
  'Wer erzählt die besten Geschichten? Erzähl in 30 Sekunden ein Märchen mit allen aus der Runde als Figuren!',
  'Wer ist am diplomatischsten? Schlichte einen erfundenen Streit zwischen den zwei Personen neben dir!',
  'Wer verliert am schnellsten die Geduld? Bleib 20 Sekunden lang komplett still und regungslos!',
  'Wer kennt die meisten Werbejingles? Sing einen Werbejingle, die anderen raten die Marke!',
  'Wer würde am ehesten eine Rede auf einer Hochzeit halten? Halte einen Toast auf die Runde!',
  'Wer hat die beste Körperbeherrschung? Mach den Moonwalk oder versuche es zumindest!',
  'Wer ist am besten in Pantomime? Stell pantomimisch einen Beruf dar, die anderen raten!',
  'Wer schaut die meisten Serien? Spiel eine Szene aus deiner Lieblingsserie nach, die anderen raten!',
  'Wer kann am besten Promis nachmachen? Imitiere einen Promi, bis jemand ihn errät!',
  'Wer ist der größte Fan einer Band? Summe einen Song dieser Band, die anderen raten!',
  'Wer hätte das Zeug zum Rap-Star? Rappe vier Zeilen über die Person links von dir!',
  'Wer kann am besten erklären? Bring der Runde in 30 Sekunden etwas bei, das du richtig gut kannst!',
  'Wer ist am witzigsten ohne Worte? Bring die Runde in 20 Sekunden zum Lachen, ohne zu sprechen!',
  'Wer hat den besten Spürsinn? Rate, wer in der Runde heute am meisten getrunken hat, und begründe es!',
  'Wer ist am hilfsbereitesten? Bediene die Person rechts von dir bis zur nächsten Karte wie im Luxushotel!',
  'Wer kann am besten zeichnen? Zeichne mit dem Finger ein Bild in die Luft, die anderen raten!',
  'Wer ist am sportlichsten? Mach 10 Hampelmänner und motiviere die Runde mitzumachen!',
  'Wer könnte am besten einen Bösewicht spielen? Lach wie ein Filmbösewicht und verrate deinen fiesen Plan!',
  'Wer hat den feinsten Geschmack? Beschreibe dein Getränk, als wärst du auf einer Weinprobe!',
  'Wer verrät sich am schnellsten? Schau der Person gegenüber 20 Sekunden in die Augen, ohne zu lachen!',
  'Wer hat den besten Musikgeschmack? Zeig uns deinen zuletzt gehörten Song und verteidige ihn!',
  'Wer ist am neugierigsten? Interviewe die Person links von dir mit drei spontanen Fragen!',
  'Wer hat die kreativste Fantasie? Erfinde ein neues Wort und erkläre, was es bedeutet!',
  'Wer kann am besten mit Kindern? Erklär uns das Internet, als wären wir fünf Jahre alt!',
  'Wer verschläft am häufigsten? Spiel der Runde deinen Weckerton vor!',
  'Wer hat das größte Sprachtalent? Sag einen Satz in so vielen Sprachen wie möglich!',
  'Wer gibt die besten Ratschläge? Gib der Person rechts von dir einen Lebenstipp für die Woche!',
  'Wer hat am meisten Energie? Steh auf und starte mit der ganzen Runde eine La Ola!',
  'Wer würde am ehesten in einer Kochshow auftreten? Moderiere 20 Sekunden lang, wie du dein Lieblingsgericht zubereitest!',
  'Wer flucht am kreativsten? Erfinde ein harmloses Schimpfwort und benutze es in einem Satz!',
  'Wer wäre die beste Stimme für eine Naturdoku? Kommentiere die Runde wie eine Herde wilder Tiere!',
  'Wer hat die schönste Handschrift? Schreib mit dem Finger ein Wort auf den Rücken der Person links, sie rät!',
  'Wer ist am ehesten eine Dramaqueen? Beschwere dich 20 Sekunden lang theatralisch über dein Getränk!',
  'Wer würde als Erstes einen Podcast starten? Stell deinen Podcast in 15 Sekunden mit Intro vor!',
  'Wer erinnert sich am besten an Kinderserien? Sing die Titelmelodie einer Kinderserie!',
  'Wer würde am ehesten in einer Seifenoper mitspielen? Mach der Person gegenüber einen dramatischen Heiratsantrag auf Knien!',
  'Wer hat die beste Erzählstimme? Erzähle, wie du heute hergekommen bist, als wäre es ein Abenteuerfilm!',
  'Wer hat den längsten Atem? Sag das Alphabet in einem einzigen Atemzug auf!',
  'Wer ist am schlechtesten in Geografie? Nenne fünf Hauptstädte in 15 Sekunden!',
  'Wer redet am meisten mit den Händen? Erzähle 20 Sekunden lang etwas, während deine Hände unter dem Tisch bleiben!',
  'Wer ist am ehesten ein Morgenmuffel? Spiel uns vor, wie du morgens aufwachst!',
  'Wer ist der größte Feinschmecker? Beschreibe dein Traumessen so, dass allen das Wasser im Mund zusammenläuft!',
  'Wer kann am besten Dialekte? Sag einen Satz in drei verschiedenen deutschen Dialekten!',
  'Wer ist am abergläubischsten? Erzähl uns deinen seltsamsten Aberglauben und führe das Ritual vor!',
  'Wer hat das beste Rhythmusgefühl? Trommle einen Beat auf den Tisch, die anderen raten den Song!',
  'Wer ist am verpeiltesten? Schließ die Augen und beschreibe, was die Person gegenüber anhat!',
  'Wer würde den besten Schlagerstar abgeben? Dichte einen Schlagerrefrain über diesen Abend!',
  'Wer kann am besten verhandeln? Versuche, jemandem in der Runde deinen Schuh zu verkaufen!',
  'Wer ist am ehesten ein Nachtmensch? Gähne so ansteckend, dass jemand mitgähnt!',
  'Wer hat die schrägste Lieblingsserie? Fasse die letzte Folge in drei Sätzen zusammen!',
  'Wer würde am ehesten in einer Talkshow sitzen? Interviewe dich selbst mit zwei verschiedenen Stimmen!',
  'Wer hat das beste Zeitgefühl? Sag, wie spät es ist, ohne auf eine Uhr zu schauen!',
  'Wer ist am ehesten ein Sprachgenie? Sag das Alphabet rückwärts, so weit du kommst!',
  'Wer hat das beste Timing? Stoppe mit geschlossenen Augen genau 10 Sekunden, die Runde misst mit!',
  'Wer kann am besten trösten? Tröste die Person links von dir über ein erfundenes Missgeschick!',
  'Wer wäre die beste Reiseleitung? Führe die Runde wie eine Gruppe Touristen durch diesen Raum!',
  'Wer liebt Kitsch am meisten? Trag ein selbst gedichtetes Liebesgedicht an dein Getränk vor!',
  'Wer würde auf einer einsamen Insel am längsten überleben? Nenne drei Dinge aus diesem Raum, die du mitnimmst, und begründe es!',
  'Wer ist am ordentlichsten? Räum in 15 Sekunden den Tisch so schön wie möglich auf!',
  'Wer hat die höchste Stimme? Sing eine Tonleiter so hoch du kannst!',
  'Wer hat die tiefste Stimme? Sprich wie in einem Filmtrailer und kündige die nächste Karte an!',
  'Wer kann am besten Werbung für sich selbst machen? Bewirb dich in 20 Sekunden für ein freies WG-Zimmer!',
  'Wer hat die besten Ausreden? Erfinde eine absurde Ausrede, warum du heute zu spät gekommen bist!',
  'Wer ist am ehesten ein Bücherwurm? Erzähle den Inhalt deines Lieblingsbuchs in drei Sätzen!',
  'Wer ist am ehrgeizigsten? Fordere jemanden zu Schnick Schnack Schnuck heraus, wer zuerst zwei Siege hat, gewinnt!',
  'Wer hat den schlechtesten Orientierungssinn? Zeig mit geschlossenen Augen in Richtung Norden!',
  'Wer ist am ehesten selbst ein Meme? Stell ein bekanntes Meme nach, die anderen raten!',
  'Wer könnte am besten eine Sportart erfinden? Erkläre und demonstriere eine neue Sportart für den Tisch!',
  'Wer zockt am meisten? Mach die Geräusche eines Videospiels nach, die anderen raten welches!',
  'Wer hat die lustigste Familie? Imitiere ein Familienmitglied bei einem typischen Spruch!',
  'Wer redet am meisten im Schlaf? Spiel uns vor, wie du im Schlaf redest!',
  'Wer ist am großzügigsten? Verleihe jeder Person in der Runde einen imaginären Preis mit Begründung!',
  'Wer ist am romantischsten? Beschreibe dein perfektes erstes Date in 20 Sekunden!',
  'Wer liebt Rätsel am meisten? Stell der Runde ein Rätsel, sie haben 30 Sekunden Zeit!',
  'Wer hat die beste Körperhaltung? Lauf einmal wie auf einem Laufsteg durch den Raum!',
  'Wer googelt am häufigsten Krankheiten? Spiel uns einen dramatischen Arztbesuch wegen eines Schluckaufs vor!',
  'Wer kann sich am besten Zahlen merken? Merk dir eine zehnstellige Zahl, die die Runde vorgibt, und wiederhole sie!',
  'Wer würde am ehesten auswandern? Erkläre in einer erfundenen Sprache, warum du auswanderst!',
  'Wer wäre die beste Besetzung für einen Horrorfilm? Erzähl eine Gruselgeschichte in drei Sätzen mit Flüsterstimme!',
  'Wer ist am fittesten? Halte 20 Sekunden lang die Plank!',
  'Wer kann am besten Stimmen verstellen? Erzähle mit der Stimme einer Zeichentrickfigur, was du morgen vorhast!',
  'Wer ist am meisten Kind geblieben? Erkläre der Runde dein liebstes Pausenhofspiel und spiel es kurz vor!',
  'Wer posiert am liebsten für Fotos? Zeig uns deine drei besten Fotoposen!',
  'Wer kann am besten zuhören? Fasse zusammen, worüber die Runde in den letzten fünf Minuten geredet hat!',
  'Wer ist am ehesten ein Sprachnerd? Nenne in 10 Sekunden fünf Wörter, die sich auf Tisch reimen!',
  'Wer würde am ehesten ein Restaurant eröffnen? Präsentier die Speisekarte deines Restaurants mit drei Gerichten!',
  'Wer kennt sich am besten mit Mode aus? Bewerte die Outfits der Runde wie in einer Modenschau, nur positiv!',
  'Wer kennt die meisten Sprichwörter? Vervollständige drei Sprichwörter, die die Runde anfängt!',
  'Wer niest am lustigsten? Spiel uns ein Niesen in Zeitlupe vor!',
  'Wer wäre die beste Stimme fürs Navi? Lotse die Person rechts von dir mit Ansagen einmal um den Tisch!',
  'Wer sammelt am ehesten seltsame Dinge? Erzähl uns, was du sammelst, und mach Werbung dafür!',
  'Wer hat das weichste Herz? Erzähle die süßeste Tiergeschichte, die du kennst!',
  'Wer ist am schlechtesten im Kopfrechnen? Rechne 17 mal 13 im Kopf, die Runde stoppt die Zeit!',
  'Wer wäre am liebsten eine Katze? Verhalte dich bis zur nächsten Karte wie eine Katze!',
  'Wer hat die besten Partytricks? Zeig uns etwas Ungewöhnliches, das du mit deinen Fingern kannst!',
  'Wer wäre die beste Auktionsleitung? Versteigere ein Glas Wasser so schnell wie möglich an die Runde!',
  'Wer ist am meisten herumgereist? Beschreibe deinen schönsten Reiseort, ohne ihn zu nennen, die anderen raten!',
  'Wer hat den spannendsten Lebenslauf? Fasse dein Leben in fünf Wörtern zusammen!',
  'Wer kocht am liebsten? Bereite pantomimisch ein Gericht zu, die anderen raten, was es wird!',
  'Wer wäre am ehesten eine Superheldenfigur? Erfinde deine Superkraft und zeig, wie du sie einsetzt!',
  'Wer übertreibt am meisten? Erzähle das Langweiligste deines Tages so spannend wie möglich!',
  'Wer kann am besten Fachchinesisch? Erkläre einen Löffel, als wärst du in einer Vorlesung!',
  'Wer trinkt am genussvollsten? Proste jeder Person einzeln mit einem anderen Trinkspruch zu!',
  'Wer würde am ehesten bei einem Flashmob mitmachen? Bring der Runde eine einfache Tanzbewegung bei, alle machen mit!',
  'Wer kann am besten mit Worten malen? Beschreibe einen Gegenstand im Raum, ohne ihn zu nennen, die anderen raten!',
  'Wer ist am schreckhaftesten? Erzähle, wann du dich zuletzt richtig erschreckt hast, und spiel es nach!',
  'Wer hat die ungewöhnlichsten Hobbys? Erkläre dein schrägstes Hobby in 20 Sekunden mit vollem Körpereinsatz!',
  'Wer würde am ehesten einen Oscar gewinnen? Halte deine Dankesrede unter Tränen!',
  'Wer ist am entspanntesten? Leite die Runde durch eine 20 Sekunden lange Meditation!',
  'Wer wäre die beste Hilfe bei Liebeskummer? Gib der Runde einen Tipp gegen Liebeskummer in Reimform!',
  'Wer redet am meisten? Rede 20 Sekunden über Socken, ohne Äh oder Ähm zu sagen!',
  'Wer hat das beste Bauchgefühl? Die Person rechts denkt an eine Zahl von 1 bis 10, du hast drei Versuche!',
  'Wer kennt die meisten Filmzitate? Sag drei berühmte Filmzitate, die anderen raten den Film!',
  'Wer würde am ehesten einen Marathon laufen? Lauf 15 Sekunden auf der Stelle und kommentiere dich selbst!',
  'Wer wäre die beste Moderation einer Spielshow? Stell der Runde eine Schätzfrage, wer am nächsten liegt, gewinnt!',
  'Wer hat die kreativsten Spitznamen auf Lager? Gib jeder Person in der Runde einen neuen Spitznamen!',
  'Wer würde am ehesten mit einem Automaten streiten? Spiel einen Streit mit einem Kaffeeautomaten nach!',
  'Wer singt am lautesten im Auto? Sing den Anfang eines Songs, als würdest du allein im Auto sitzen!',
  'Wer kann am besten Gedichte aufsagen? Trag ein Gedicht aus der Schulzeit vor, so weit du es noch kannst!',
  'Wer ist am ehesten ein Profi bei Spieleabenden? Erkläre die Regeln eines Brettspiels in 20 Sekunden!',
  'Wer würde am ehesten in die Politik gehen? Erkläre, welches Gesetz du als Erstes einführen würdest!',
  'Wer ist am ehesten ein Rätselfan? Denk dir einen Begriff aus, die Runde darf zehn Fragen mit Ja oder Nein stellen!',
  'Wer hat die lustigste Art zu laufen? Lauf einmal um den Tisch wie ein Pinguin!',
  'Wer kann am besten Stimmung machen? Bring die ganze Runde zum gemeinsamen Klatschen im Takt!',
  'Wer hängt am meisten in den Nullerjahren fest? Zeig uns einen Tanz, der damals angesagt war!',
  'Wer hat das beste Augenmaß? Schätze, wie viele Handylängen der Tisch lang ist, und miss dann nach!',
  'Wer hätte das Zeug zum Popstar? Erfinde einen Bandnamen für die Runde und sing einen Refrain dazu!',
  'Wer kann am besten Bewegungen nachahmen? Mach 15 Sekunden lang alle Bewegungen der Person gegenüber spiegelverkehrt nach!',
  'Wer hat die schnellsten Reflexe? Klatsch in die Hände, sobald die Person links unerwartet Jetzt sagt!',
  'Wer versteht Tiere am besten? Übersetze, was ein Hund über diesen Abend denken würde!',
  'Wer kennt die Runde am besten? Nenne den Lieblingssnack jeder Person hier!',
  'Wer wäre im Mittelalter am besten zurechtgekommen? Sprich bis zur nächsten Karte wie im Mittelalter!',
  'Wer schaut am meisten Realityshows? Spiel eine typische Dramaszene aus einer Realityshow nach!',
  'Wer erzählt am liebsten von früher? Erzähle 20 Sekunden lang, wie die Welt früher war, wie eine sehr alte Person!',
  'Wer findet immer einen Grund zu feiern? Erfinde einen Feiertag für heute und erkläre, wie er gefeiert wird!',
  'Wer wäre die beste Besetzung für einen Krimi? Verhöre die Person links von dir zu einem erfundenen Verbrechen!',
  'Wer kann am besten beatboxen? Gib uns 10 Sekunden Beatbox!',
  'Wer pfeift am besten? Pfeif eine Melodie, die anderen raten den Song!',
  'Wer würde in den Alpen am meisten auffallen? Versuch dich 5 Sekunden lang am Jodeln!',
  'Wer erinnert sich am besten an die Schulzeit? Erzähle in drei Sätzen von deinem ersten Schultag!',
  'Wer würde am ehesten in einem Kloster leben? Sprich bis zur nächsten Karte nur flüsternd!',
  'Wer hat die besten Ideen für Geschenke? Sag jeder Person, was du ihr zum Geburtstag schenken würdest!',
  'Wer ist am ehesten Stammgast in einer Kneipe? Bestell dein nächstes Getränk wie in deiner Stammkneipe!',
  'Wer verliert am häufigsten Sachen? Spiel uns vor, wie du verzweifelt deinen Schlüssel suchst!',
  'Wer würde am ehesten in einem Stummfilm glänzen? Spiel 20 Sekunden lang eine Verfolgungsjagd ohne Ton!',
  'Wer hat die ausgefallensten Essgewohnheiten? Beschreibe deine seltsamste Lieblingskombination und verteidige sie!',
  'Wer hängt am meisten am Handy? Schätze deine heutige Bildschirmzeit und schau dann nach!',
  'Wer durchschaut Lügen am schnellsten? Die Person links erzählt etwas, du sagst, ob es stimmt!',
  'Wer träumt am häufigsten tagsüber? Beschreibe deinen perfekten Tag von morgens bis abends!',
  'Wer kann am besten Maschinen nachmachen? Mach die Geräusche einer Kaffeemaschine, einer Waschmaschine und eines Druckers!',
  'Wer hat die ruhigste Hand? Halte dein Getränk 20 Sekunden mit ausgestrecktem Arm, ohne zu wackeln!',
  'Wer wäre die beste Crew im Flugzeug? Mach die Sicherheitsansage für diesen Raum!',
  'Wer kann am besten improvisieren? Die Runde nennt drei Wörter, du baust sie sofort in eine Geschichte ein!',
  'Wer würde einen Buchstabierwettbewerb gewinnen? Buchstabiere ein Wort, das die Runde dir nennt, rückwärts!',
  'Wer hat die meisten Tierfotos? Zeig uns das niedlichste Tierfoto auf deinem Handy!',
  'Wer hört einen Song am häufigsten in Dauerschleife? Spiel uns 10 Sekunden davon vor und erkläre, warum!',
  'Wer bemerkt die kleinsten Details? Die Runde verändert etwas, während du die Augen schließt, finde es!',
  'Wer kann am besten im Takt bleiben? Klatsch einen Rhythmus vor, die Runde muss ihn nachmachen!',
  'Wer ist am wenigsten handysüchtig? Leg dein Handy bis zur nächsten Karte umgedreht in die Tischmitte!',
  'Wer würde am ehesten auf eine Kreuzfahrt gehen? Spiel, dass ihr auf einem Schiff in einen Sturm geratet, und gib Befehle!',
  'Wer hat die meisten Pflanzen? Erzähle von deiner Lieblingspflanze, als wäre sie ein Mensch!',
  'Wer redet am liebsten mit sich selbst? Führe 15 Sekunden lang ein lautes Selbstgespräch!',
  'Wer kennt sich am besten mit Disneyfilmen aus? Sing einen Disneysong, so weit du ihn kannst!',
  'Wer plant am liebsten? Plane in 20 Sekunden den nächsten gemeinsamen Ausflug der Runde!',
  'Wer ist am albernsten? Sag einen ernsten Satz mit möglichst alberner Stimme!',
  'Wer kann am besten Mitleid erregen? Bettle die Runde 15 Sekunden lang um einen Schluck an!',
  'Wer schreibt die besten Liebesbriefe? Diktiere einen kurzen Liebesbrief an die Pizza!',
  'Wer reagiert am heftigsten auf Spoiler? Spiel uns deine Reaktion auf einen riesigen Spoiler vor!',
  'Wer ist am ehesten ein Kuschelmonster? Verteile eine Umarmung an alle, die eine wollen!',
  'Wer kann am besten Fragen ausweichen? Die Runde stellt dir drei Fragen, antworte nur mit Gegenfragen!',
  'Wer hat die seltsamsten Träume? Erzähle deinen schrägsten Traum in 20 Sekunden!',
  'Wer würde eine Zombieapokalypse am längsten überleben? Erkläre deinen Fluchtplan aus diesem Raum!',
  'Wer kann am besten Geheimnisse bewahren? Erzähle ein erfundenes Geheimnis so, dass alle neugierig werden!',
  'Wer bleibt im Stress am ruhigsten? Sag das Alphabet auf, während die Runde laut durcheinander zählt!',
  'Wer nimmt sich am wenigsten ernst? Mach eine Parodie von dir selbst!',
  'Wer kann am besten Gefühle zeigen? Sag Ich habe Hunger in fünf verschiedenen Gefühlslagen!',
  'Wer würde am ehesten einen Foodblog schreiben? Bewerte deinen letzten Snack wie in einem Restaurantführer!',
  'Wer kann am schlechtesten verlieren? Spiel uns einen dramatischen Wutanfall nach einer Niederlage vor!',
  'Wer wäre die beste Sprachlehrkraft? Bring der Runde ein Wort in einer Fremdsprache bei, alle sprechen es nach!',
  'Wer erzählt am liebsten Anekdoten? Erzähle die lustigste Geschichte aus deiner Kindheit!',
  'Wer würde am liebsten ins All fliegen? Spiel 15 Sekunden lang Schwerelosigkeit vor!',
  'Wer behält im Chaos den Überblick? Stell die Runde in 15 Sekunden der Größe nach auf!',
  'Wer hat das meiste Taktgefühl? Dirigiere die Runde, während alle zusammen ein Lied summen!',
  'Wer würde am ehesten ein Selbsthilfebuch schreiben? Nenne den Titel und die drei wichtigsten Regeln daraus!',
  'Wer ist der größte Ruhepol? Sprich 20 Sekunden lang mit ruhiger Radiostimme über deinen Tag!',
  'Wer ist am ehesten eine Plaudertasche? Rede 30 Sekunden ohne Pause, die Runde gibt dir alle 10 Sekunden ein neues Thema!',
  'Wer kann am besten Fehler zugeben? Entschuldige dich übertrieben förmlich bei der Person rechts für etwas Erfundenes!',
  'Wer würde am ehesten auf einem Festival campen? Spiel uns vor, wie du nach drei Festivaltagen aussiehst!',
  'Wer hat die stärksten Meinungen? Halte ein leidenschaftliches Plädoyer für oder gegen Ananas auf Pizza!',
  'Wer kann am besten Regeln erfinden? Führe eine neue Regel ein, die bis zum Ende des Spiels gilt!',
  'Wer wäre die beste Stimme für ein Videospiel? Sprich den Satz Level geschafft in drei verschiedenen Stimmen!',
  'Wer hat die beste Fantasie für Namen? Erfinde einen Namen für den Gruppenchat dieser Runde!',
  'Wer ist am wenigsten wählerisch? Lass dir von der Runde ein seltsames Gericht beschreiben und reagiere begeistert!',
  'Wer ist am besten im Smalltalk? Führe 20 Sekunden Smalltalk über das Wetter mit der Person gegenüber!',
  'Wer würde am ehesten ein Tattoo bereuen? Beschreibe das schlimmste Tattoo, das du dir vorstellen kannst!',
  'Wer kann am besten Mimik lesen? Die Person gegenüber zeigt ein Gefühl ohne Worte, du rätst es!',
  'Wer wäre die beste Zeugin oder der beste Zeuge? Beschreibe die Person rechts, als würde nach deinen Worten ein Phantombild gezeichnet!',
  'Wer würde am ehesten im Lotto gewinnen? Erzähle, was du als Erstes mit einer Million machen würdest!',
  'Wer hat das meiste Selbstvertrauen? Sag drei Dinge, die du an dir richtig gut findest!',
  'Wer ist am ehesten ein Wissenschaftsfan? Erkläre ein Naturphänomen völlig falsch, aber überzeugend!',
  'Wer kann am besten Dinge umbenennen? Gib drei Alltagsgegenständen neue, bessere Namen!',
  'Wer ist am häufigsten in Gedanken woanders? Wiederhole den letzten Satz, den jemand vor dieser Karte gesagt hat!',
  'Wer wäre die beste Besetzung fürs Theater? Spiel den Satz Wo ist mein Schlüssel als Tragödie, Komödie und Krimi!',
  'Wer hat den verrücktesten Familienurlaub erlebt? Erzähle in drei Sätzen davon!',
  'Wer reagiert am schönsten auf Überraschungen? Spiel drei Reaktionen auf ein Geschenk: begeistert, enttäuscht, gerührt!',
  'Wer singt am schiefsten? Sing Alle meine Entchen absichtlich so schief wie möglich!',
  'Wer hat den größten Wortschatz? Nenne fünf Synonyme für betrunken!',
  'Wer würde am ehesten ein Musikinstrument erfinden? Mach 10 Sekunden lang Musik nur mit deinem Körper!',
  'Wer schreibt am liebsten Listen? Nenne die drei besten Momente dieses Abends!',
  'Wer hat die beste Gutenachtstimme? Erzähl der Runde eine Gutenachtgeschichte in vier Sätzen!',
  'Wer liest am ehesten Horoskope? Erstelle für die Person links ein Horoskop für morgen!',
  'Wer würde am ehesten einen Weltrekord aufstellen? Erfinde einen Weltrekord, den du hier sofort aufstellen kannst, und stell ihn auf!',
  'Wer hat die besten Ideen für Filme? Pitche der Runde in 20 Sekunden einen Film über diesen Abend!',
  'Wer ist am ehesten ein Kindskopf? Spiel 10 Sekunden lang ein Kleinkind, das unbedingt ein Eis will!',
  'Wer singt am ehesten beim Wandern? Stimme ein Wanderlied an, die Runde singt mit!',
  'Wer würde in einem Western die Hauptrolle spielen? Zeig uns, wie schnell du dein Handy wie einen Colt ziehst!',
  'Wer schreibt die schönsten Grußkarten? Diktiere eine Geburtstagskarte für die Person rechts von dir!',
  'Wer könnte am besten ein Kinderbuch schreiben? Erfinde in vier Sätzen eine Geschichte über ein Tier mit einem Problem!',
  'Wer erlebt am meisten in Zügen? Erzähle in 20 Sekunden deine verrückteste Zugfahrt!',
  'Wer kann am besten Lieder umdichten? Dichte die erste Zeile eines bekannten Songs auf diesen Abend um!',
  'Wer kann am besten bauchreden? Lass dein Getränk etwas sagen, ohne die Lippen zu bewegen!',
  'Wer würde bei einer Gruselführung als Erstes schreien? Mach den besten Gruselschrei, den du kannst!',
  'Wer schreibt die ehrlichsten Bewertungen? Bewerte diesen Abend mit Sternen und einer kurzen Rezension!',
  'Wer würde am ehesten Unboxing-Videos drehen? Pack pantomimisch ein Geschenk aus und kommentiere es!',
  'Wer klingt am Telefon am überzeugendsten? Spiel einen Anruf beim Kundenservice nach!',
  'Wer wäre die beste Besetzung für ein Märchen? Spiel eine Fee, die jeder Person einen Wunsch erfüllt!',
  'Wer redet am meisten mit Haustieren? Sprich 15 Sekunden mit der Runde wie mit einem Hundewelpen!',
  'Wer verfolgt am meisten die Nachrichten? Erfinde drei gute Schlagzeilen für morgen!',
  'Wer schaut am meisten Filme? Beschreibe einen Film in drei Wörtern, die anderen raten!',
  'Wer würde am ehesten eine eigene Sprache erfinden? Bring der Runde drei Wörter deiner eigenen Sprache bei!',
  'Wer frühstückt am ausgiebigsten? Beschreibe dein perfektes Frühstück mit allen Geräuschen!',
  'Wer würde am ehesten Kunst studieren? Erkläre ein unsichtbares Kunstwerk im Raum wie bei einer Museumsführung!',
  'Wer findet überall Anschluss? Finde in 30 Sekunden drei Gemeinsamkeiten mit der Person links!',
  'Wer wäre die beste Stimme für Bahnansagen? Sag die Verspätung des nächsten Getränks durch!',
  'Wer würde am ehesten bei einem Backwettbewerb mitmachen? Beschreibe die Torte, die du für die Runde backen würdest!',
  'Wer ist am sturköpfigsten? Die Runde versucht 20 Sekunden, dich von etwas Absurdem zu überzeugen, gib nicht nach!',
  'Wer würde am ehesten mit Gegenständen reden? Spiel einen Dialog zwischen deinem Handy und deinem Getränk!',
  'Wer ist am ehesten ein Adrenalinjunkie? Erzähle das Mutigste, was du je gemacht hast!',
  'Wer kann am besten Stimmen erkennen? Schließ die Augen, jemand sagt mit verstellter Stimme Hallo, rate wer!',
  'Wer ist am ehesten von Kleinigkeiten genervt? Spiel uns vor, wie dich nachts ein tropfender Wasserhahn wach hält!',
  'Wer kann am besten applaudieren? Gib der Runde stehende Ovationen und begründe sie!',
  'Wer ist am ehesten ein Sportfan? Stimme einen Fangesang für die Runde an!',
  'Wer würde am ehesten bei einem Poetry Slam auftreten? Trag vier Zeilen über dein Handy vor!',
  'Wer kämpft am meisten mit der Autokorrektur? Tippe einen Satz blind und lies vor, was daraus geworden ist!',
  'Wer mag Sprachspiele am liebsten? Nenne ein Wort, das vorwärts und rückwärts gleich ist!',
  'Wer kennt die meisten Länderflaggen? Beschreibe eine Flagge, die anderen raten das Land!',
  'Wer hat das schnellste Mundwerk? Sag Fischers Fritz fischt frische Fische dreimal schnell hintereinander!',
  'Wer verhaspelt sich am häufigsten? Sag Blaukraut bleibt Blaukraut und Brautkleid bleibt Brautkleid fünfmal schnell!',
  'Wer hat die flinkste Zunge? Sag Zehn zahme Ziegen zogen zehn Zentner Zucker zum Zoo dreimal schnell!',
  'Wer hat den besten englischen Akzent? Bestell dein nächstes Getränk mit britischem Akzent!',
  'Wer klingt am ehesten italienisch? Erzähle mit italienischem Akzent und viel Gestik von deinem Lieblingsessen!',
  'Wer reimt am schnellsten? Reime auf jedes Wort, das die Runde dir 15 Sekunden lang zuruft!',
  'Wer kann am besten Zeugnisse schreiben? Stell der Runde ein mündliches Zeugnis mit Noten für diesen Abend aus!',
  'Wer erinnert sich am besten an erste Begegnungen? Erzähle, wie du jemanden hier kennengelernt hast!',
  'Wer hätte die spannendste Autobiografie? Nenne ihren Titel und fasse das erste Kapitel in zwei Sätzen zusammen!',
  'Wer ist bei Prüfungen am nervösesten? Spiel uns eine mündliche Prüfung über Gummibärchen vor!',
  'Wer erfindet am ehesten etwas Geniales? Präsentiere eine Erfindung, die die Welt nicht braucht!',
  'Wer würde am besten ins Königshaus passen? Winke der Runde 10 Sekunden lang königlich zu!',
  'Wer hat die feierlichste Art? Erhebe die Person rechts mit einer kurzen Rede in den Adelsstand!',
  'Wer wäre die beste Kassenkraft? Scanne pantomimisch alles auf dem Tisch mit Piepgeräusch!',
  'Wer drückt sich am liebsten vor dem Abwasch? Erkläre 20 Sekunden lang, warum Abwaschen gefährlich ist!',
  'Wer würde am ehesten ein Lied über sich selbst schreiben? Sing eine Zeile aus deinem eigenen Titelsong!',
  'Wer kann die Runde noch am ehesten überraschen? Erzähle eine harmlose Sache über dich, die hier noch niemand weiß!',
  'Wer denkt am meisten über sich selbst nach? Sprich eine Grußbotschaft an dein Ich in zehn Jahren!',
  'Wer denkt am meisten an die Zukunft? Sag voraus, was jede Person hier in zehn Jahren macht!',
  'Wer hat die weisesten Sprüche? Formuliere einen Glückskeksspruch für die Person gegenüber!',
  'Wer würde am liebsten durch die Zeit reisen? Sag, in welches Jahr du reist, und spiel eine Szene von dort!',
  'Wer ist der Mittelpunkt jeder Party? Bring die ganze Runde dazu, gleichzeitig Prost zu rufen!',
];
