export const normalQuestions: string[] = [
  'Wer würde am ehesten den eigenen Geburtstag vergessen?',
  'Wer von euch hat die meisten ungelesenen Nachrichten auf dem Handy?',
  'Wer drückt morgens am häufigsten auf Schlummern?',
  'Wer ist am ehesten zu spät, selbst wenn es um die eigene Feier geht?',
  'Wer würde sich in einem Möbelhaus verlaufen?',
  'Wer von euch redet mit Haustieren wie mit Menschen?',
  'Wer hat am wahrscheinlichsten schon mal im Supermarkt den falschen Einkaufswagen mitgenommen?',
  'Wer ist die Person, die im Restaurant am längsten für die Bestellung braucht?',
  'Wer würde am ehesten einen Film nur wegen des Covers anschauen?',
  'Wer von euch hat zu Hause eine Schublade voller Kabel, die niemand mehr braucht?',
  'Wer singt am lautesten im Auto mit?',
  'Wer hat am wahrscheinlichsten schon mal die falsche Person zurückgewunken?',
  'Wer ist am ehesten die Person, die immer Snacks dabeihat?',
  'Wer von euch würde eine Woche ohne Handy am schlechtesten aushalten?',
  'Wer schaut eine Serie am ehesten an einem einzigen Wochenende durch?',
  'Wer hat am wahrscheinlichsten schon mal das Handy gesucht, während es in der Hand lag?',
  'Wer ist am meisten auf den Urlaub vorbereitet, mit Liste und allem?',
  'Wer von euch packt den Koffer erst eine Stunde vor der Abfahrt?',
  'Wer lacht am ehesten über die eigenen Witze, bevor die Pointe kommt?',
  'Wer hat am wahrscheinlichsten mehr als zehn offene Tabs im Browser?',
  'Wer ist die Person, die beim Spieleabend am meisten diskutiert?',
  'Wer von euch kennt die meisten Songtexte auswendig?',
  'Wer würde am ehesten ein Haustier mit einem ungewöhnlichen Namen haben?',
  'Wer schläft am ehesten bei einem Film im Kino ein?',
  'Wer hat am wahrscheinlichsten schon mal die Tür gedrückt, obwohl Ziehen dranstand?',
  'Wer ist am ehesten die Person, die im Gruppenchat nur mit Emojis antwortet?',
  'Wer von euch würde bei einer Talentshow mit dem seltsamsten Talent auftreten?',
  'Wer würde am ehesten einen Zimmerpflanzen-Dschungel zu Hause haben?',
  'Wer verliert am häufigsten Schlüssel, Kopfhörer oder Geldbeutel?',
  'Wer hat am wahrscheinlichsten schon mal mit sich selbst gesprochen und es nicht gemerkt?',
  'Wer von euch fotografiert das Essen, bevor gegessen wird?',
  'Wer erzählt Geschichten am ausführlichsten, auch wenn sie kurz sein könnten?',
  'Wer ist am ehesten die Person, die beim Einparken dreimal ansetzen muss?',
  'Wer von euch hat die verrückteste Sammlung zu Hause?',
  'Wer würde am ehesten mitten in der Nacht Pfannkuchen machen?',
  'Wer hat am wahrscheinlichsten schon mal eine Pflanze vertrocknen lassen, die angeblich unkaputtbar ist?',
  'Wer von euch würde in einem Escape Room als Erstes das Rätsel lösen?',
  'Wer würde am ehesten ein ganzes Wochenende im Schlafanzug verbringen?',
  'Wer tanzt am ehesten, wenn niemand hinschaut?',
  'Wer hat am wahrscheinlichsten schon mal eine Sprachnachricht über fünf Minuten geschickt?',
  'Wer ist am ehesten die Person, die beim Einkaufen den Einkaufszettel vergisst?',
  'Wer würde am ehesten eine Reise spontan am selben Tag buchen?',
  'Wer isst am langsamsten von allen hier?',
  'Wer hat am wahrscheinlichsten schon mal den Namen einer Person direkt nach dem Vorstellen vergessen?',
  'Wer ist die Person, die frische Wäsche am längsten auf dem Stuhl liegen lässt?',
  'Wer räumt am ehesten die Spülmaschine ein, ohne gefragt zu werden?',
  'Wer hat am wahrscheinlichsten schon mal ein Möbelstück falsch zusammengebaut?',
  'Wer ist am ehesten die Person, die im Kino jede Szene kommentiert?',
  'Wer von euch hat den seltsamsten Lieblingssnack?',
  'Wer würde am ehesten ein ganzes Buch an einem Tag lesen?',
  'Wer verschickt am häufigsten lustige Videos in den Gruppenchat?',
  'Wer hat am wahrscheinlichsten schon mal die Socken verkehrt herum angezogen und es erst abends gemerkt?',
  'Wer ist die Person, die immer weiß, wo das nächste gute Café ist?',
  'Wer friert am schnellsten, selbst im Sommer?',
  'Wer ist am ehesten die Person, die im Urlaub die meisten Postkarten schreibt?',
  'Wer von euch hat den kreativsten Handyhintergrund?',
  'Wer läuft beim Telefonieren am ehesten durch die ganze Wohnung?',
  'Wer kauft am ehesten etwas nur, weil es im Angebot ist?',
  'Wer hat am wahrscheinlichsten schon mal ein Lied den ganzen Tag gesummt, ohne es zu merken?',
  'Wer ist die Person, die Geschenke erst am letzten Tag kauft?',
  'Wer würde am ehesten bei einem Flohmarkt mehr kaufen als verkaufen?',
  'Wer hat immer eine Ausrede parat, warum es heute nicht mit dem Sport klappt?',
  'Wer hat am wahrscheinlichsten schon mal den gleichen Film dreimal im Kino gesehen?',
  'Wer ist am ehesten die Person, die bei Gruppenfotos immer die Augen zu hat?',
  'Wer von euch würde einen Wettbewerb im Nichtstun gewinnen?',
  'Wer braucht morgens am längsten im Bad?',
  'Wer von euch trinkt den ersten Kaffee noch vor dem Zähneputzen?',
  'Wer würde am ehesten im Bus den Ausstieg verpassen, weil die Musik zu gut ist?',
  'Wer kontrolliert am häufigsten, ob der Herd wirklich aus ist?',
  'Wer hat am wahrscheinlichsten schon mal Salz statt Zucker in den Kaffee getan?',
  'Wer ist morgens schon gesprächig, wenn alle anderen noch halb schlafen?',
  'Wer von euch braucht am längsten, um sich für ein Outfit zu entscheiden?',
  'Wer zieht am ehesten bei jedem Wetter kurze Hosen an?',
  'Wer hat am wahrscheinlichsten mehr Jacken als Platz an der Garderobe?',
  'Wer würde am ehesten mit Hausschuhen zum Bäcker gehen?',
  'Wer von euch wird am häufigsten ohne Regenschirm vom Regen überrascht?',
  'Wer isst Pizza am ehesten mit Ananas?',
  'Wer von euch würde jedes Gericht nachwürzen, bevor es überhaupt probiert wurde?',
  'Wer bestellt beim Lieferdienst immer genau dasselbe?',
  'Wer würde am ehesten ein Gericht nur wegen des lustigen Namens auf der Karte bestellen?',
  'Wer isst am ehesten die Pommes vom Teller der anderen?',
  'Wer hat am wahrscheinlichsten schon mal vergessen, dass noch Nudeln auf dem Herd stehen?',
  'Wer von euch verträgt am meisten Schärfe?',
  'Wer würde beim Grillen am ehesten die Grillzange nicht mehr hergeben?',
  'Wer von euch hat immer Platz für Nachtisch, egal wie satt?',
  'Wer isst am ehesten Müsli zum Abendessen?',
  'Wer hat am wahrscheinlichsten schon mal etwas Abgelaufenes gegessen und es erst danach gemerkt?',
  'Wer ist die Person, die beim Teilen von Essen immer das letzte Stück nimmt?',
  'Wer von euch backt zur Weihnachtszeit Plätzchen in riesigen Mengen?',
  'Wer würde am ehesten einen Monat lang auf Süßigkeiten verzichten können?',
  'Wer schneidet am ehesten die Rinde vom Brot ab?',
  'Wer würde in einem Buffet-Restaurant die meisten Runden drehen?',
  'Wer isst das Frühstück am ehesten erst zur Mittagszeit?',
  'Wer hat am wahrscheinlichsten schon mal ein Rezept aus einem Video nachgekocht, und es sah ganz anders aus?',
  'Wer bestellt im Café die komplizierteste Kaffeespezialität?',
  'Wer von euch würde am ehesten Schnecken oder Insekten probieren?',
  'Wer ist die Person, die beim Kochen die ganze Küche verwüstet?',
  'Wer trinkt am ehesten kalten Kaffee, weil der warme vergessen wurde?',
  'Wer isst Eis am ehesten auch im tiefsten Winter?',
  'Wer hat am wahrscheinlichsten schon mal den Kühlschrank geöffnet, ohne zu wissen, was gesucht wird?',
  'Wer von euch kann aus einem fast leeren Kühlschrank noch ein Essen zaubern?',
  'Wer würde am ehesten Ketchup auf einfach alles tun?',
  'Wer isst die Schokolade aus dem Adventskalender am ehesten schon vorher auf?',
  'Wer bügelt am ehesten sogar Socken?',
  'Wer schiebt den Abwasch am längsten vor sich her?',
  'Wer würde am ehesten die Wohnung nur dann putzen, wenn Besuch kommt?',
  'Wer hat am wahrscheinlichsten schon mal ein rotes Teil mit der weißen Wäsche gewaschen?',
  'Wer von euch hat einem Saugroboter am ehesten einen Namen gegeben?',
  'Wer hat am wahrscheinlichsten noch Umzugskartons, die nie ausgepackt wurden?',
  'Wer bringt die Pfandflaschen am seltensten weg?',
  'Wer hat die meisten Frischhaltedosen ohne passenden Deckel?',
  'Wer von euch dekoriert die Wohnung zu jeder Jahreszeit um?',
  'Wer würde am ehesten eine kaputte Glühbirne wochenlang nicht austauschen?',
  'Wer ist die Person, die beim Aufräumen einfach alles in einen Schrank stopft?',
  'Wer hat am wahrscheinlichsten schon mal die Waschmaschine angemacht, ohne Waschmittel einzufüllen?',
  'Wer hat das unordentlichste Auto?',
  'Wer wäscht am ehesten erst, wenn wirklich nichts Sauberes mehr im Schrank ist?',
  'Wer hat am wahrscheinlichsten eine Ecke, in der sich die Post seit Wochen stapelt?',
  'Wer hat gerade jetzt den niedrigsten Akkustand auf dem Handy?',
  'Wer würde am ehesten beim Videoanruf vergessen, dass die Kamera an ist?',
  'Wer hat am wahrscheinlichsten noch ein Handy mit gesprungenem Display?',
  'Wer ist die Person, die in der Familie alle technischen Probleme lösen muss?',
  'Wer liest am ehesten die Nutzungsbedingungen tatsächlich durch?',
  'Wer von euch hat noch eine Sammlung alter Handys in der Schublade?',
  'Wer würde am ehesten jedes Problem lösen wollen, indem das Gerät neu gestartet wird?',
  'Wer hat am wahrscheinlichsten schon mal ein Passwort dreimal hintereinander zurückgesetzt?',
  'Wer von euch hat das Handy immer auf lautlos und verpasst deshalb alles?',
  'Wer würde am ehesten mit dem Sprachassistenten diskutieren?',
  'Wer macht am ehesten von allem einen Screenshot?',
  'Wer hat am wahrscheinlichsten schon mal eine Nachricht an die falsche Person geschickt?',
  'Wer ist am ehesten die Person, die neue Technik direkt am Erscheinungstag kauft?',
  'Wer schreibt Nachrichten am ehesten komplett ohne Großbuchstaben?',
  'Wer würde am ehesten das Navi ignorieren und sich dann verfahren?',
  'Wer hat am ehesten für jede Stimmung eine eigene Playlist?',
  'Wer von euch entschuldigt sich am häufigsten, auch wenn es gar nicht nötig ist?',
  'Wer würde am ehesten mitten in einer Diskussion nachgoogeln, um recht zu haben?',
  'Wer kann am schlechtesten ein Geheimnis über ein Geschenk für sich behalten?',
  'Wer ist am ehesten die Person, die alles plant, sogar einen Spaziergang?',
  'Wer hat am wahrscheinlichsten zu allem eine Meinung?',
  'Wer von euch kann sich am schlechtesten entscheiden?',
  'Wer würde am ehesten bei einem traurigen Werbespot weinen?',
  'Wer lacht am lautesten von allen?',
  'Wer sagt am häufigsten den Satz "Hab ich doch gesagt"?',
  'Wer ist am neugierigsten von allen?',
  'Wer hat am wahrscheinlichsten schon mal ein fremdes Gespräch belauscht und sich fast eingemischt?',
  'Wer erschreckt sich am leichtesten?',
  'Wer würde am ehesten eine To-do-Liste schreiben, nur um etwas abhaken zu können?',
  'Wer ist die Person, die einfach nie Nein sagen kann?',
  'Wer hat die meisten Spitznamen?',
  'Wer von euch wäre der beste Detektiv?',
  'Wer verliert beim Spielen am schlechtesten?',
  'Wer redet am ehesten im Schlaf?',
  'Wer würde am ehesten einer fremden Person im Zug die eigene Lebensgeschichte erzählen?',
  'Wer hat am wahrscheinlichsten schon mal eine Wette über etwas völlig Unwichtiges abgeschlossen?',
  'Wer würde am ehesten an einem freien Tag um sechs Uhr morgens schon joggen gehen?',
  'Wer würde am ehesten Horoskope lesen und ernst nehmen?',
  'Wer ist am ehesten die Person, die jedes Gespräch auf das eigene Lieblingsthema lenkt?',
  'Wer niest am lautesten?',
  'Wer gähnt am ansteckendsten?',
  'Wer von euch hat den besten Orientierungssinn?',
  'Wer würde am ehesten bei Mensch ärgere dich nicht schummeln?',
  'Wer ist die Person, die nach einem Film stundenlang darüber reden will?',
  'Wer redet am ehesten über das Wetter, wenn das Gespräch stockt?',
  'Wer würde am ehesten ein neues Hobby anfangen und nach einer Woche wieder aufhören?',
  'Wer hat am wahrscheinlichsten schon mal ein Fitnessstudio-Abo bezahlt, ohne je hinzugehen?',
  'Wer ist die Person, die bei einem Puzzle mit tausend Teilen nicht aufhören kann?',
  'Wer würde an einem Karaoke-Abend am ehesten das Mikrofon nicht mehr hergeben?',
  'Wer strickt oder häkelt am ehesten heimlich?',
  'Wer hat am wahrscheinlichsten schon mal bei einem Volkslauf mitgemacht, nur wegen der Medaille?',
  'Wer von euch spielt am ehesten Videospiele bis tief in die Nacht?',
  'Wer würde ein Museum am ehesten ganz genau, Schild für Schild, anschauen?',
  'Wer ist am ehesten die Person, die bei Gesellschaftsspielen die Regeln vorliest?',
  'Wer hat am wahrscheinlichsten schon mal ein Hörbuch auf doppelter Geschwindigkeit gehört?',
  'Wer von euch würde beim Bowling am ehesten nur in der Rinne landen?',
  'Wer malt am ehesten beim Telefonieren kleine Kritzeleien?',
  'Wer löst am ehesten jeden Tag das Kreuzworträtsel?',
  'Wer schaut am ehesten Dokumentationen über das Weltall oder die Tiefsee?',
  'Wer würde am ehesten im Park gegen Fremde Schach spielen?',
  'Wer ist am ehesten die Person, die beim Minigolf die Regeln sehr genau nimmt?',
  'Wer verbringt am meisten Zeit im Baumarkt?',
  'Wer würde am ehesten einen eigenen Podcast starten?',
  'Wer hat am wahrscheinlichsten schon mal ein Lied hundertmal am Stück in Dauerschleife gehört?',
  'Wer schaut am ehesten Kochvideos, ohne jemals selbst zu kochen?',
  'Wer von euch hat die meisten angefangenen Bücher auf dem Nachttisch?',
  'Wer würde bei einem Kneipenquiz am ehesten alle Sportfragen beantworten?',
  'Wer ist die Person, die beim Schwimmen nie ins kalte Wasser will?',
  'Wer würde beim Schlittschuhlaufen am ehesten nach zwei Metern hinfallen?',
  'Wer würde am ehesten das Ticket oder den Ausweis vor dem Flug vergessen?',
  'Wer von euch nimmt am meisten Gepäck für ein Wochenende mit?',
  'Wer schläft auf Reisen am ehesten sofort im Zug oder Flugzeug ein?',
  'Wer hat am wahrscheinlichsten schon mal den Zug verpasst, weil noch schnell ein Kaffee geholt wurde?',
  'Wer von euch versucht es im Ausland immer in der Landessprache, auch mit nur drei Wörtern?',
  'Wer bringt die kitschigsten Souvenirs aus dem Urlaub mit?',
  'Wer hat am wahrscheinlichsten schon mal am ersten Urlaubstag einen Sonnenbrand bekommen?',
  'Wer ist die Person, die schon drei Stunden vor dem Abflug am Flughafen ist?',
  'Wer würde bei einem Roadtrip am ehesten die Musik bestimmen wollen?',
  'Wer hat am wahrscheinlichsten schon mal ein Hotel in der falschen Stadt gebucht?',
  'Wer würde sich am ehesten in einer fremden Stadt verlaufen und es dann Abenteuer nennen?',
  'Wer ist die Person, die im Auto ständig fragt, wie lange es noch dauert?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Raststätte etwas Wichtiges liegen lassen?',
  'Wer von euch würde am liebsten jedes Jahr am selben Ort Urlaub machen?',
  'Wer bekommt im Urlaub am ehesten schon nach drei Tagen Heimweh?',
  'Wer von euch muss jeden Hund auf der Straße streicheln?',
  'Wer hat am wahrscheinlichsten schon mal beim Bäcker das falsche Brötchen bekommen und es trotzdem genommen?',
  'Wer ist die Person, die bei Telefonaten mit Unbekannten am höflichsten klingt?',
  'Wer würde an der Kasse am ehesten das Kleingeld ganz genau abzählen?',
  'Wer hat am wahrscheinlichsten schon mal ein Paket beim Nachbarn abgeholt und eine Stunde geplaudert?',
  'Wer würde am ehesten in einer Warteschlange mit Fremden Freundschaft schließen?',
  'Wer ist am ehesten die Person, die am Telefon viel zu laut spricht?',
  'Wer von euch ruft lieber an, statt zu schreiben?',
  'Wer hat am wahrscheinlichsten schon mal einen Termin am falschen Tag wahrgenommen?',
  'Wer kauft auf dem Jahrmarkt am ehesten so lange Lose, bis der große Teddy gewonnen ist?',
  'Wer bringt zu jeder Einladung ein selbstgemachtes Mitbringsel mit?',
  'Wer ist die Person, die beim Verabschieden noch eine halbe Stunde an der Tür redet?',
  'Wer wird am häufigsten auf der Straße nach dem Weg gefragt?',
  'Wer hat am wahrscheinlichsten schon mal mit "Gleichfalls" geantwortet, obwohl es gar nicht passte?',
  'Wer holt sich im Kino am ehesten das größte Popcorn und isst es vor dem Film auf?',
  'Wer würde am ehesten eine Beschwerde schreiben, wenn das Essen kalt ankommt?',
  'Wer hat am wahrscheinlichsten schon mal versucht, in ein fremdes Auto einzusteigen, weil es genauso aussah?',
  'Wer verabredet sich am ehesten und sagt dann kurzfristig ab?',
  'Wer würde am ehesten im Laden nach Rabatt fragen?',
  'Wer hat beim Zahnarzt am meisten Angst?',
  'Wer hat am wahrscheinlichsten in diesem Jahr schon einen Brief mit der Hand geschrieben?',
  'Wer von euch hätte am meisten Angst vor einer Spinne im Zimmer?',
  'Wer trägt Insekten am ehesten vorsichtig nach draußen, statt sie zu verscheuchen?',
  'Wer hat am wahrscheinlichsten schon mal ein Tier aus einem Baum oder Teich gerettet?',
  'Wer ist die Person, die beim Spaziergang jede Blume benennen kann?',
  'Wer würde am ehesten bei Gewitter draußen stehen und zuschauen?',
  'Wer wäre am ehesten eine Katze, wenn alle hier Tiere wären?',
  'Wer geht am ehesten bei strömendem Regen spazieren?',
  'Wer würde am ehesten barfuß durch den Wald laufen?',
  'Wer würde am ehesten Sterne beobachten und allen die Sternbilder erklären?',
  'Wer steht am ehesten extra früh auf, um den Sonnenaufgang zu sehen?',
  'Wer von euch schaut Filme am ehesten mit Untertiteln?',
  'Wer verrät am ehesten aus Versehen das Ende eines Films?',
  'Wer würde am ehesten eine Serie zum fünften Mal anschauen?',
  'Wer ist die Person, die sich beim Horrorfilm die Augen zuhält?',
  'Wer von euch braucht am längsten, um einen Film für den Abend auszusuchen?',
  'Wer kennt die meisten Filmzitate?',
  'Wer würde am ehesten eine Reality-Show schauen und es niemandem erzählen?',
  'Wer hat am wahrscheinlichsten schon mal eine Folge übersprungen und es erst später gemerkt?',
  'Wer würde bei einem Konzert am ehesten ganz vorne stehen?',
  'Wer von euch hat den ungewöhnlichsten Musikgeschmack?',
  'Wer kann am besten Stimmen von Zeichentrickfiguren nachmachen?',
  'Wer ist am ehesten die Person, die Weihnachtslieder schon im November hört?',
  'Wer liest am ehesten noch eine gedruckte Zeitung?',
  'Wer wird am ehesten Fan einer kleinen Band, lange bevor sie berühmt ist?',
  'Wer hat am wahrscheinlichsten schon mal einen Film nur halb geschaut, weil das Handy spannender war?',
  'Wer schmückt den Weihnachtsbaum am aufwendigsten?',
  'Wer von euch packt Geschenke am schönsten ein?',
  'Wer würde an Halloween am ehesten das aufwendigste Kostüm tragen?',
  'Wer isst an Ostern die meisten Schokoladenhasen?',
  'Wer hat am wahrscheinlichsten schon mal ein Geschenk weiterverschenkt?',
  'Wer ist die Person, die an Silvester als Erste müde wird?',
  'Wer würde an Fasching am ehesten jedes Jahr dasselbe Kostüm anziehen?',
  'Wer von euch freut sich am meisten auf den ersten Schnee?',
  'Wer würde am ehesten Neujahrsvorsätze aufschreiben und tatsächlich einhalten?',
  'Wer hat am wahrscheinlichsten im Februar noch Weihnachtsdeko hängen?',
  'Wer ist am ehesten die Person, die im Herbst nur noch Kürbisgerichte isst?',
  'Wer war in der Schule am ehesten die Person, die sich ständig gemeldet hat?',
  'Wer von euch hatte als Kind die meisten Kuscheltiere?',
  'Wer hat am wahrscheinlichsten noch die Zeugnisse aus der Grundschule aufbewahrt?',
  'Wer würde heute am ehesten noch auf einem Spielplatz herumklettern?',
  'Wer war als Kind beim Verstecken am ehesten die Person, die nie gefunden wurde?',
  'Wer von euch hat am spätesten Fahrradfahren gelernt?',
  'Wer hat am wahrscheinlichsten schon mal Hausaufgaben im Bus erledigt?',
  'Wer würde am ehesten heute noch das Lieblingsessen aus der Kindheit bestellen?',
  'Wer von euch hat die schlechteste Wurftechnik bei Ballspielen?',
  'Wer schimpft beim Fußball vor dem Fernseher am lautesten mit dem Schiedsrichter?',
  'Wer hat am wahrscheinlichsten schon mal Muskelkater vom Treppensteigen gehabt?',
  'Wer ist die Person, die beim Joggen am meisten redet?',
  'Wer würde am ehesten Tischtennis spielen, bis alle anderen aufgeben?',
  'Wer würde beim Sackhüpfen am ehesten gewinnen?',
  'Wer hat die meisten Notizen mit unwichtigen Gedanken auf dem Handy?',
  'Wer von euch liest am ehesten die Packungsbeilage komplett durch?',
  'Wer schläft am ehesten mit Socken?',
  'Wer würde bei einem Mittagsschlaf am ehesten drei Stunden verschlafen?',
  'Wer hat am wahrscheinlichsten schon mal einen Raum betreten und sofort vergessen, warum?',
  'Wer von euch kann am besten pfeifen?',
  'Wer zählt beim Hochgehen am ehesten die Treppenstufen?',
  'Wer führt am ehesten ein Tagebuch?',
  'Wer hat am wahrscheinlichsten schon mal etwas versteckt und das Versteck selbst vergessen?',
  'Wer von euch kaut am ehesten auf dem Kugelschreiber herum?',
  'Wer knackt am häufigsten mit den Fingern?',
  'Wer würde am ehesten alle Kassenbons sammeln und abheften?',
  'Wer hat am wahrscheinlichsten schon mal ein Paket bestellt und dann vergessen, was drin ist?',
  'Wer probiert in der Eisdiele am ehesten jedes Mal eine neue Sorte?',
  'Wer trägt am ehesten auch bei bewölktem Himmel eine Sonnenbrille?',
  'Wer hat heute die buntesten Socken an?',
  'Wer hat am wahrscheinlichsten schon mal etwas nur wegen der schönen Verpackung gekauft?',
  'Wer würde im Supermarkt am ehesten den ganzen Laden absuchen, statt nach dem Weg zu fragen?',
  'Wer ist die Person, die im Restaurant die Rechnung immer ganz genau aufteilt?',
  'Wer von euch würde am ehesten ein Selfie mit einer bekannten Person machen wollen?',
  'Wer schaut beim Spazierengehen abends am liebsten in beleuchtete Fenster?',
  'Wer redet am ehesten mit dem Fernseher?',
  'Wer von euch würde am ehesten die Türklingel überhören, weil die Musik zu laut läuft?',
  'Wer trinkt am wenigsten Wasser am Tag?',
  'Wer hat am wahrscheinlichsten schon mal mit leerem Magen viel zu viel eingekauft?',
  'Wer ist die Person, die beim Spaziergang ständig stehen bleibt, um etwas zu fotografieren?',
  'Wer von euch würde einen Tag als Tourist in der eigenen Stadt am meisten genießen?',
];
