export const normalQuestions: string[] = [
  'Wer würde am ehesten den eigenen Geburtstag vergessen?',
  'Wer von euch hat die meisten ungelesenen Nachrichten auf dem Handy?',
  'Wer drückt morgens am häufigsten auf Schlummern?',
  'Wer ist am ehesten zu spät, selbst wenn es um die eigene Feier geht?',
  'Wer würde sich in einem Möbelhaus verlaufen?',
  'Wer von euch redet mit Haustieren wie mit Menschen?',
  'Wer hat am wahrscheinlichsten schon mal im Supermarkt den falschen Einkaufswagen mitgenommen?',
  'Wer ist die Person, die im Restaurant am längsten für die Bestellung braucht?',
  'Wer würde am ehesten einen Film nur wegen des Covers anschauen?',
  'Wer von euch hat zu Hause eine Schublade voller Kabel, die niemand mehr braucht?',
  'Wer singt am lautesten im Auto mit?',
  'Wer hat am wahrscheinlichsten schon mal die falsche Person zurückgewunken?',
  'Wer würde bei einem Quiz über Tiere gewinnen?',
  'Wer ist am ehesten die Person, die immer Snacks dabeihat?',
  'Wer von euch würde eine Woche ohne Handy am schlechtesten aushalten?',
  'Wer schaut eine Serie am ehesten an einem einzigen Wochenende durch?',
  'Wer hat am wahrscheinlichsten schon mal das Handy gesucht, während es in der Hand lag?',
  'Wer würde am ehesten bei einer Kochshow mitmachen?',
  'Wer ist am meisten auf den Urlaub vorbereitet, mit Liste und allem?',
  'Wer von euch packt den Koffer erst eine Stunde vor der Abfahrt?',
  'Wer lacht am ehesten über die eigenen Witze, bevor die Pointe kommt?',
  'Wer würde am ehesten eine Woche lang jeden Tag dasselbe essen?',
  'Wer hat am wahrscheinlichsten mehr als zehn offene Tabs im Browser?',
  'Wer ist die Person, die beim Spieleabend am meisten diskutiert?',
  'Wer von euch kennt die meisten Songtexte auswendig?',
  'Wer würde am ehesten ein Haustier mit einem ungewöhnlichen Namen haben?',
  'Wer schläft am ehesten bei einem Film im Kino ein?',
  'Wer hat am wahrscheinlichsten schon mal die Tür gedrückt, obwohl Ziehen dranstand?',
  'Wer ist am ehesten die Person, die im Gruppenchat nur mit Emojis antwortet?',
  'Wer von euch würde bei einer Talentshow mit dem seltsamsten Talent auftreten?',
  'Wer würde am ehesten einen Zimmerpflanzen-Dschungel zu Hause haben?',
  'Wer verliert am häufigsten Schlüssel, Kopfhörer oder Geldbeutel?',
  'Wer hat am wahrscheinlichsten schon mal mit sich selbst gesprochen und es nicht gemerkt?',
  'Wer ist die Person, die im Supermarkt immer an der langsamsten Kasse landet?',
  'Wer von euch fotografiert das Essen, bevor gegessen wird?',
  'Wer würde am ehesten bei einem Gewinnspiel mitmachen und tatsächlich gewinnen?',
  'Wer erzählt Geschichten am ausführlichsten, auch wenn sie kurz sein könnten?',
  'Wer hat am wahrscheinlichsten schon mal in einem Laden laut über ein Produkt gelacht?',
  'Wer ist am ehesten die Person, die beim Einparken dreimal ansetzen muss?',
  'Wer von euch hat die verrückteste Sammlung zu Hause?',
  'Wer würde am ehesten mitten in der Nacht Pfannkuchen machen?',
  'Wer gibt beim Brettspiel am ehesten auf, wenn es schlecht läuft?',
  'Wer hat am wahrscheinlichsten schon mal eine Pflanze vertrocknen lassen, die angeblich unkaputtbar ist?',
  'Wer ist die Person, die beim Wandern immer vorne läuft?',
  'Wer von euch würde in einem Escape Room als Erstes das Rätsel lösen?',
  'Wer würde am ehesten ein ganzes Wochenende im Schlafanzug verbringen?',
  'Wer tanzt am ehesten, wenn niemand hinschaut?',
  'Wer hat am wahrscheinlichsten schon mal eine Sprachnachricht über fünf Minuten geschickt?',
  'Wer ist am ehesten die Person, die beim Einkaufen den Einkaufszettel vergisst?',
  'Wer von euch hat die meisten Fotos auf dem Handy?',
  'Wer würde am ehesten eine Reise spontan am selben Tag buchen?',
  'Wer isst am langsamsten von allen hier?',
  'Wer hat am wahrscheinlichsten schon mal den Namen einer Person direkt nach dem Vorstellen vergessen?',
  'Wer ist die Person, die frische Wäsche am längsten auf dem Stuhl liegen lässt?',
  'Wer von euch würde bei einem Stromausfall als Erstes die Kerzen finden?',
  'Wer würde am ehesten ein Rezept ganz genau nach Anleitung kochen?',
  'Wer räumt am ehesten die Spülmaschine ein, ohne gefragt zu werden?',
  'Wer hat am wahrscheinlichsten schon mal ein Möbelstück falsch zusammengebaut?',
  'Wer ist am ehesten die Person, die im Kino jede Szene kommentiert?',
  'Wer von euch hat den seltsamsten Lieblingssnack?',
  'Wer würde am ehesten ein ganzes Buch an einem Tag lesen?',
  'Wer verschickt am häufigsten lustige Videos in den Gruppenchat?',
  'Wer hat am wahrscheinlichsten schon mal die Socken verkehrt herum angezogen und es erst abends gemerkt?',
  'Wer ist die Person, die immer weiß, wo das nächste gute Café ist?',
  'Wer von euch würde in einer Quizshow beim Telefonjoker angerufen werden?',
  'Wer würde am ehesten aus Versehen einen Kuchen anbrennen lassen?',
  'Wer friert am schnellsten, selbst im Sommer?',
  'Wer hat am wahrscheinlichsten schon mal jemandem auf der Straße zugewunken, der gar nicht gemeint war?',
  'Wer ist am ehesten die Person, die im Urlaub die meisten Postkarten schreibt?',
  'Wer von euch hat den kreativsten Handyhintergrund?',
  'Wer läuft beim Telefonieren am ehesten durch die ganze Wohnung?',
  'Wer kauft am ehesten etwas nur, weil es im Angebot ist?',
  'Wer hat am wahrscheinlichsten schon mal ein Lied den ganzen Tag gesummt, ohne es zu merken?',
  'Wer ist die Person, die Geschenke erst am letzten Tag kauft?',
  'Wer von euch würde am längsten in einem Wartezimmer still sitzen können?',
  'Wer würde am ehesten bei einem Flohmarkt mehr kaufen als verkaufen?',
  'Wer hat immer eine Ausrede parat, warum es heute nicht mit dem Sport klappt?',
  'Wer hat am wahrscheinlichsten schon mal den gleichen Film dreimal im Kino gesehen?',
  'Wer ist am ehesten die Person, die bei Gruppenfotos immer die Augen zu hat?',
  'Wer von euch würde einen Wettbewerb im Nichtstun gewinnen?',
];
