export const partyQuestions: string[] = [
  'Wer würde am ehesten auf einer Party auf dem Sofa einschlafen?',
  'Wer von euch tanzt als Erstes, wenn das Lieblingslied läuft?',
  'Wer hat am wahrscheinlichsten schon mal den Heimweg vergessen?',
  'Wer ist die Person, die beim Vorglühen schon zu viel getrunken hat?',
  'Wer würde am ehesten um 4 Uhr morgens noch Döner holen gehen?',
  'Wer von euch verschwindet auf Partys gern ohne Tschüss zu sagen?',
  'Wer hat am wahrscheinlichsten schon mal das Handy im Club verloren?',
  'Wer würde am ehesten als Letztes die Party verlassen?',
  'Wer von euch übernimmt immer die Musik auf jeder Party?',
  'Wer ist am ehesten die Person, die am nächsten Morgen allen Frühstück macht?',
  'Wer würde am ehesten auf einem Festival das eigene Zelt nicht mehr finden?',
  'Wer von euch hat den schlimmsten Kater nach einer durchfeierten Nacht?',
  'Wer hat am wahrscheinlichsten schon mal auf dem Tisch getanzt?',
  'Wer würde am ehesten an der Türsteherkontrolle scheitern?',
  'Wer von euch bestellt immer noch eine Runde Shots, wenn alle schon gehen wollen?',
  'Wer ist die Person, die auf jeder Party neue Freundschaften schließt?',
  'Wer würde am ehesten auf einer Hausparty die Küche nicht verlassen?',
  'Wer hat am wahrscheinlichsten schon mal im Taxi geschlafen?',
  'Wer von euch kennt bei jedem Partysong den kompletten Text?',
  'Wer würde am ehesten eine spontane Party bei sich zu Hause schmeißen?',
  'Wer ist am ehesten die Person, die beim Bierpong nie verliert?',
  'Wer von euch erzählt betrunken die längsten Geschichten?',
  'Wer würde am ehesten im Urlaub jede Nacht feiern gehen?',
  'Wer hat am wahrscheinlichsten schon mal einen Filmriss gehabt?',
  'Wer von euch schreibt nach einer Party die peinlichsten Nachrichten?',
  'Wer würde am ehesten nach dem Feiern noch schwimmen gehen wollen?',
  'Wer ist die Person, die beim Karaoke das Mikro nicht mehr hergibt?',
  'Wer würde am ehesten sagen: Nur ein Getränk, und dann bis zum Morgen bleiben?',
  'Wer von euch fährt immer nüchtern und sammelt alle wieder ein?',
  'Wer hat am wahrscheinlichsten schon mal die letzte Bahn verpasst?',
  'Wer würde am ehesten mit dem DJ befreundet sein?',
  'Wer von euch hat den besten Tanzstil auf der Tanzfläche?',
  'Wer ist am ehesten die Person, die am Abend vorher sagt: Morgen trinke ich nie wieder?',
  'Wer würde am ehesten ein Trinkspiel erfinden?',
  'Wer hat am wahrscheinlichsten schon mal in fremden Klamotten nach Hause gefunden?',
  'Wer von euch landet nach jeder Party bei jemand anderem auf dem Boden?',
  'Wer würde am ehesten auf dem Festival drei Tage nicht duschen?',
  'Wer ist die Person, die auf jeder Party die besten Fotos macht?',
  'Wer würde am ehesten auf der Party mit Fremden Brüderschaft trinken?',
  'Wer hat am wahrscheinlichsten schon mal eine Geburtstagsparty verschlafen?',
  'Wer von euch plant am liebsten den nächsten Urlaub mit der Clique?',
  'Wer würde am ehesten im Club die Jacke an der Garderobe vergessen?',
  'Wer ist am ehesten die Person, die betrunken plötzlich sehr philosophisch wird?',
  'Wer von euch hat schon die meisten Festivals besucht?',
  'Wer würde am ehesten um Mitternacht noch spontan in eine andere Stadt fahren?',
  'Wer hat am wahrscheinlichsten schon mal einen Drink über jemanden geschüttet?',
  'Wer von euch ist auf Partys immer am lautesten?',
  'Wer würde am ehesten an der Bar eine Runde für alle ausgeben?',
  'Wer ist die Person, die nach zwei Bier schon mit allen tanzt?',
  'Wer würde am ehesten auf der Afterparty noch fit sein?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Party geweint?',
  'Wer von euch verträgt am wenigsten, trinkt aber am meisten?',
  'Wer würde am ehesten im Urlaub einen Kater am Pool auskurieren?',
  'Wer ist am ehesten die Person, die nach dem Club noch Pommes isst?',
  'Wer von euch hat schon mal den Schlüssel auf einer Party verloren?',
  'Wer würde am ehesten eine Mottoparty mit dem aufwendigsten Kostüm besuchen?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Party die Nachbarn verärgert?',
  'Wer von euch erinnert sich am nächsten Morgen an jedes Detail?',
  'Wer würde am ehesten auf einer Hochzeit als Letztes tanzen?',
  'Wer ist die Person, die immer behauptet, heute ruhig zu machen?',
  'Wer würde am ehesten beim Feiern den Sonnenaufgang erleben?',
  'Wer hat am wahrscheinlichsten schon mal auf einem Festival neue Freunde fürs Leben gefunden?',
  'Wer von euch bringt die schlechtesten Getränke zur Party mit?',
  'Wer würde am ehesten in einer Strandbar den ganzen Urlaub verbringen?',
  'Wer ist am ehesten die Person, die beim Vorglühen zu spät kommt?',
  'Wer von euch würde am ehesten auf dem Heimweg anfangen zu singen?',
  'Wer würde am ehesten eine Polonaise starten?',
  'Wer hat am wahrscheinlichsten schon mal eine Party mit Freunden gecrasht?',
  'Wer von euch kümmert sich auf Partys immer um die Betrunkenen?',
  'Wer würde am ehesten im Club stundenlang auf der Toilette quatschen?',
  'Wer ist die Person, die nach dem Feiern noch ein Konterbier braucht?',
  'Wer würde am ehesten auf einem Junggesellenabschied komplett eskalieren?',
  'Wer hat am wahrscheinlichsten schon mal mit der Polizei auf einer Party geredet?',
  'Wer von euch hat die längste Partynacht überhaupt erlebt?',
  'Wer würde am ehesten auf Mallorca am Ballermann landen?',
  'Wer ist am ehesten die Person, die am Sonntag noch nach Rauch und Bier riecht?',
  'Wer von euch würde am ehesten eine Silvesterparty organisieren?',
  'Wer würde am ehesten nach drei Drinks Liebeserklärungen an alle machen?',
  'Wer hat am wahrscheinlichsten schon mal den Flug nach einer Partynacht verpasst?',
  'Wer von euch sagt immer zu und taucht dann doch nicht auf der Party auf?',
];
