export const partyQuestions: string[] = [
  'Wer würde am ehesten auf einer Party auf dem Sofa einschlafen?',
  'Wer von euch tanzt als Erstes, wenn das Lieblingslied läuft?',
  'Wer ist die Person, die beim Vorglühen schon zu viel getrunken hat?',
  'Wer würde am ehesten um 4 Uhr morgens noch Döner holen gehen?',
  'Wer von euch verschwindet auf Partys gern ohne Tschüss zu sagen?',
  'Wer hat am wahrscheinlichsten schon mal das Handy im Club verloren?',
  'Wer würde am ehesten als Letztes die Party verlassen?',
  'Wer von euch übernimmt immer die Musik auf jeder Party?',
  'Wer ist am ehesten die Person, die am nächsten Morgen allen Frühstück macht?',
  'Wer würde am ehesten auf einem Festival das eigene Zelt nicht mehr finden?',
  'Wer von euch hat den schlimmsten Kater nach einer durchfeierten Nacht?',
  'Wer hat am wahrscheinlichsten schon mal auf dem Tisch getanzt?',
  'Wer von euch bestellt immer noch eine Runde Shots, wenn alle schon gehen wollen?',
  'Wer ist die Person, die auf jeder Party neue Freundschaften schließt?',
  'Wer würde am ehesten auf einer Hausparty die Küche nicht verlassen?',
  'Wer hat am wahrscheinlichsten schon mal im Taxi geschlafen?',
  'Wer von euch kennt bei jedem Partysong den kompletten Text?',
  'Wer würde am ehesten eine spontane Party bei sich zu Hause schmeißen?',
  'Wer ist am ehesten die Person, die beim Bierpong nie verliert?',
  'Wer von euch erzählt betrunken die längsten Geschichten?',
  'Wer hat am wahrscheinlichsten schon mal einen Filmriss gehabt?',
  'Wer von euch schreibt nach einer Party die peinlichsten Nachrichten?',
  'Wer ist die Person, die beim Karaoke das Mikro nicht mehr hergibt?',
  'Wer würde am ehesten sagen: Nur ein Getränk, und dann bis zum Morgen bleiben?',
  'Wer von euch fährt immer nüchtern und sammelt alle wieder ein?',
  'Wer hat am wahrscheinlichsten schon mal die letzte Bahn verpasst?',
  'Wer würde am ehesten mit dem DJ befreundet sein?',
  'Wer von euch hat den besten Tanzstil auf der Tanzfläche?',
  'Wer ist am ehesten die Person, die am Morgen danach sagt: Ich trinke nie wieder?',
  'Wer würde am ehesten ein Trinkspiel erfinden?',
  'Wer hat am wahrscheinlichsten schon mal in fremden Klamotten nach Hause gefunden?',
  'Wer von euch landet nach jeder Party bei jemand anderem auf dem Boden?',
  'Wer würde am ehesten auf dem Festival drei Tage nicht duschen?',
  'Wer ist die Person, die auf jeder Party die besten Fotos macht?',
  'Wer würde am ehesten auf der Party mit Fremden Brüderschaft trinken?',
  'Wer hat am wahrscheinlichsten schon mal eine Geburtstagsparty verschlafen?',
  'Wer ist am ehesten die Person, die betrunken plötzlich sehr philosophisch wird?',
  'Wer würde am ehesten um Mitternacht noch spontan in eine andere Stadt fahren?',
  'Wer hat am wahrscheinlichsten schon mal einen Drink über jemanden geschüttet?',
  'Wer würde am ehesten an der Bar eine Runde für alle ausgeben?',
  'Wer ist die Person, die nach zwei Bier schon mit allen tanzt?',
  'Wer würde am ehesten auf der Afterparty noch fit sein?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Party geweint?',
  'Wer von euch verträgt am wenigsten, trinkt aber am meisten?',
  'Wer von euch hat schon mal den Schlüssel auf einer Party verloren?',
  'Wer würde am ehesten eine Mottoparty mit dem aufwendigsten Kostüm besuchen?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Party die Nachbarn verärgert?',
  'Wer von euch erinnert sich am nächsten Morgen an jedes Detail?',
  'Wer würde am ehesten beim Feiern den Sonnenaufgang erleben?',
  'Wer von euch bringt die schlechtesten Getränke zur Party mit?',
  'Wer ist am ehesten die Person, die beim Vorglühen zu spät kommt?',
  'Wer von euch würde am ehesten auf dem Heimweg anfangen zu singen?',
  'Wer würde am ehesten eine Polonaise starten?',
  'Wer hat am wahrscheinlichsten schon mal eine Party mit Freunden gecrasht?',
  'Wer von euch kümmert sich auf Partys immer um die Betrunkenen?',
  'Wer würde am ehesten im Club stundenlang auf der Toilette quatschen?',
  'Wer ist die Person, die nach dem Feiern noch ein Konterbier braucht?',
  'Wer würde am ehesten auf einem Junggesellenabschied komplett eskalieren?',
  'Wer hat am wahrscheinlichsten schon mal mit der Polizei auf einer Party geredet?',
  'Wer von euch hat die längste Partynacht überhaupt erlebt?',
  'Wer würde am ehesten auf Mallorca am Ballermann landen?',
  'Wer ist am ehesten die Person, die am Sonntag noch nach Rauch und Bier riecht?',
  'Wer von euch würde am ehesten eine Silvesterparty organisieren?',
  'Wer würde am ehesten nach drei Drinks Liebeserklärungen an alle machen?',
  'Wer hat am wahrscheinlichsten schon mal den Flug nach einer Partynacht verpasst?',
  'Wer von euch sagt immer zu und taucht dann doch nicht auf der Party auf?',
  'Wer würde am ehesten das Vorglühen so lange ausdehnen, dass es keiner mehr in den Club schafft?',
  'Wer bringt zum Vorglühen am wahrscheinlichsten nur eine Tüte Chips und sonst nichts mit?',
  'Wer von euch mixt beim Vorglühen die abenteuerlichsten Drinks?',
  'Wer hat am wahrscheinlichsten schon mal beim Vorglühen die Nachbarn kennengelernt, weil es zu laut war?',
  'Wer würde am ehesten das Vorglühen einfach in der Bahn fortsetzen?',
  'Wer von euch hat immer einen Flachmann in der Tasche?',
  'Wer kauft am wahrscheinlichsten den billigsten Wein im Späti?',
  'Wer von euch kennt jeden Späti in der Stadt mit Namen?',
  'Wer hat am wahrscheinlichsten schon mal beim Vorglühen etwas Wertvolles zerbrochen?',
  'Wer von euch braucht am längsten im Bad, bevor es losgehen kann?',
  'Wer würde am ehesten dem Türsteher die eigene Lebensgeschichte erzählen?',
  'Wer von euch kommt an jedem Türsteher vorbei, egal wie voll es ist?',
  'Wer würde am ehesten eine Stunde in der Schlange stehen und dann abgewiesen werden?',
  'Wer von euch tanzt im Club am liebsten direkt neben der Box?',
  'Wer würde am ehesten im Club Ohrstöpsel tragen?',
  'Wer hat am wahrscheinlichsten schon mal den Garderobenzettel verloren?',
  'Wer von euch würde am ehesten den ganzen Abend in der Raucherecke verbringen?',
  'Wer hat am wahrscheinlichsten schon mal einen DJ um ein Schlagerlied gebeten?',
  'Wer ist noch auf der Tanzfläche, wenn im Club das Licht angeht?',
  'Wer kennt nach dem Club am wahrscheinlichsten den Weg zur nächsten Afterhour?',
  'Wer hat am wahrscheinlichsten schon mal eine Afterhour bis zum Mittag mitgemacht?',
  'Wer von euch wartet an der Bar eine halbe Stunde und bestellt dann das Falsche?',
  'Wer bezahlt im Club am wahrscheinlichsten zwanzig Euro für einen Longdrink, ohne mit der Wimper zu zucken?',
  'Wer von euch wird an der vollen Bar immer als Erstes bedient?',
  'Wer hat am wahrscheinlichsten schon mal im Club die Gruppe verloren und allein weitergefeiert?',
  'Wer von euch tanzt am längsten am Stück, ohne eine Pause zu machen?',
  'Wer würde am ehesten in Turnschuhen an der Tür abgewiesen werden?',
  'Wer hat am wahrscheinlichsten schon mal im Club die Schuhe ausgezogen?',
  'Wer von euch geht am ehesten allein in einen Club?',
  'Wer würde am ehesten in Berlin vor dem Berghain stehen und hoffen?',
  'Wer hat am wahrscheinlichsten schon mal ein komplettes Festival im Regen durchgefeiert?',
  'Wer von euch nimmt auf ein Festival nur Dosenravioli und Bier mit?',
  'Wer würde am ehesten auf einem Festival alle Bands verpassen, weil auf dem Campingplatz mehr los ist?',
  'Wer hat am wahrscheinlichsten schon mal ein Festivalbändchen wochenlang nicht abgeschnitten?',
  'Wer von euch baut auf dem Festival den besten Pavillon auf?',
  'Wer würde am ehesten auf dem Festival mit dem Nachbarcamp eine Wasserschlacht anfangen?',
  'Wer hat am wahrscheinlichsten schon mal auf einem Festival in einem fremden Zelt aufgewacht?',
  'Wer von euch steht beim Konzert immer ganz vorne in der ersten Reihe?',
  'Wer würde am ehesten auf einem Festival einen Moshpit starten?',
  'Wer hat am wahrscheinlichsten schon mal beim Crowdsurfing einen Schuh verloren?',
  'Wer würde am ehesten einen Bollerwagen voller Bier über den ganzen Campingplatz ziehen?',
  'Wer hat am wahrscheinlichsten schon mal das Festivalticket zu Hause vergessen?',
  'Wer würde am ehesten auf dem Festival Glitzer im Gesicht tragen und ihn Tage später noch finden?',
  'Wer hat am wahrscheinlichsten schon mal ein Festival vorzeitig abgebrochen?',
  'Wer von euch schläft auf dem Festival am wenigsten?',
  'Wer würde am ehesten auf dem Festival ein Megafon dabei haben?',
  'Wer hat am wahrscheinlichsten schon mal das Auto auf dem Festivalparkplatz nicht wiedergefunden?',
  'Wer würde am ehesten direkt nach dem Festival das Ticket fürs nächste Jahr kaufen?',
  'Wer von euch hat das beste Rezept gegen einen Kater?',
  'Wer würde am ehesten einen Katertag komplett im Bett mit Serien verbringen?',
  'Wem von euch sieht man den Kater am nächsten Morgen am wenigsten an?',
  'Wer würde am ehesten verkatert zum Brunch erscheinen und so tun, als wäre alles gut?',
  'Wer hat am wahrscheinlichsten schon mal verkatert eine Prüfung geschrieben?',
  'Wer von euch jammert am lautesten über den Kater?',
  'Wer würde am ehesten am Morgen danach die Handyfotos durchgehen, um den Abend zu rekonstruieren?',
  'Wer von euch ist am Sonntag nach einer Party einfach nicht erreichbar?',
  'Wer hat am wahrscheinlichsten schon mal nach einer Partynacht mit Schrecken auf das Konto geschaut?',
  'Wer würde sich am ehesten am Katertag doch wieder zum Feiern überreden lassen?',
  'Wer von euch hat schon mal verkatert ein Familienessen überstanden?',
  'Wer würde am ehesten bei Kings Cup die gemeinsten Regeln aufstellen?',
  'Wer von euch verliert bei jedem Trinkspiel, egal welches?',
  'Wer hat am wahrscheinlichsten schon mal beim Flunkyball geschummelt?',
  'Wer würde am ehesten die Regeln eines Trinkspiels mitten im Spiel ändern?',
  'Wer von euch ist bei Ich hab noch nie am ehrlichsten?',
  'Wer würde am ehesten ein Trinkspiel so ernst nehmen wie ein WM-Finale?',
  'Wer von euch kann am schnellsten ein Bier exen?',
  'Wer würde am ehesten bei einem Trinkspiel heimlich Wasser trinken?',
  'Wer hat am wahrscheinlichsten schon mal beim Mäxchen geblufft und verloren?',
  'Wer von euch kennt die meisten Trinkspiele auswendig?',
  'Wer würde am ehesten Bierpong mit Wein spielen?',
  'Wer hat am wahrscheinlichsten schon mal ein Trinkspiel vorgeschlagen und war als Erstes raus?',
  'Wer von euch hat bei Trinkspielen das beste Pokerface?',
  'Wer würde am ehesten für Bierpong eine eigene Wurftechnik trainieren?',
  'Wer von euch braucht mindestens drei Drinks, bevor es auf die Karaokebühne geht?',
  'Wer hat am wahrscheinlichsten schon mal beim Karaoke ein Lied auf Japanisch versucht?',
  'Wer würde am ehesten beim Karaoke ein Duett mit einer völlig fremden Person singen?',
  'Wer von euch hat ein festes Karaokelied, das jedes Mal kommt?',
  'Wer singt beim Karaoke am wahrscheinlichsten komplett schief, aber mit voller Überzeugung?',
  'Wer von euch würde beim Karaoke am ehesten eine Choreo einbauen?',
  'Wer hat am wahrscheinlichsten schon mal beim Karaoke Applaus von der ganzen Bar bekommen?',
  'Wer von euch drückt sich beim Karaoke jedes Mal erfolgreich?',
  'Wer würde am ehesten Bohemian Rhapsody komplett allein singen?',
  'Wer würde am ehesten um 5 Uhr morgens an der Tankstelle Würstchen kaufen?',
  'Wer hat am wahrscheinlichsten schon mal nachts im Dönerladen eine Freundschaft fürs Leben geschlossen?',
  'Wer würde am ehesten nach der Party noch Nudeln kochen und dabei einschlafen?',
  'Wer hat am wahrscheinlichsten schon mal den Döner auf dem Heimweg fallen lassen?',
  'Wer würde am ehesten eine Currywurst um 3 Uhr morgens zum Höhepunkt der Nacht erklären?',
  'Wer von euch plündert nach jeder Party den Kühlschrank der Gastgebenden?',
  'Wer würde am ehesten vor der Bäckerei warten, bis um 6 Uhr die ersten Brötchen kommen?',
  'Wer würde am ehesten nach dem Feiern zu Fuß nach Hause gehen, obwohl es eine Stunde dauert?',
  'Wer hat am wahrscheinlichsten schon mal ein Taxi zur falschen Adresse geschickt?',
  'Wer von euch landet nach dem Feiern immer im Nachtbus?',
  'Wer würde am ehesten in der Bahn einschlafen und an der Endstation aufwachen?',
  'Wer würde am ehesten auf dem Heimweg noch eine zweite Party finden?',
  'Wer hat am wahrscheinlichsten schon mal das Fahrrad vor dem Club stehen lassen und vergessen?',
  'Wer würde am ehesten den Taxifahrer zum Mitsingen bringen?',
  'Wer würde am ehesten eine Party in der WG schmeißen, ohne den Mitbewohnern Bescheid zu sagen?',
  'Wer hat am wahrscheinlichsten schon mal eine Party geschmissen, zu der dreimal so viele Leute kamen wie eingeladen?',
  'Wer würde am ehesten auf einer Party die Haustiere mehr beachten als die Gäste?',
  'Wer würde am ehesten auf der eigenen Party alle Gäste zu Untersetzern zwingen?',
  'Wer würde am ehesten auf einer Hausparty die Badewanne mit Eis und Bier füllen?',
  'Wer würde am ehesten zu einer Party einladen und dann selbst zu spät kommen?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Party jemanden kennengelernt, den niemand eingeladen hat?',
  'Wer von euch putzt am Tag nach einer Party am gründlichsten?',
  'Wer würde am ehesten für eine Hausparty das ganze Wohnzimmer zur Tanzfläche umräumen?',
  'Wer findet am wahrscheinlichsten am Morgen nach der eigenen Party noch jemanden schlafend in der Badewanne?',
  'Wer würde am ehesten eine Gartenparty mit Lichterketten und Feuerschale organisieren?',
  'Wer hat am wahrscheinlichsten schon mal beim Aufräumen nach einer Party Dinge gefunden, die niemandem gehören?',
  'Wer von euch würde am ehesten eine Hausparty mit Dresscode und Gästeliste wie im Club machen?',
  'Wer würde am ehesten auf einer Hochzeit eine spontane Rede halten?',
  'Wer von euch fängt auf Hochzeiten am wahrscheinlichsten den Brautstrauß?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Hochzeit beim Sektempfang zu schnell getrunken?',
  'Wer würde am ehesten auf einer Hochzeit die Tanzfläche stürmen, noch bevor das Paar getanzt hat?',
  'Wer von euch weint auf jeder Hochzeit schon bei der Trauung?',
  'Wer würde am ehesten auf einer Hochzeit mit den Großeltern des Paares tanzen?',
  'Wer hat am wahrscheinlichsten schon mal das Hochzeitsbuffet als Erstes gestürmt?',
  'Wer von euch verpasst auf Hochzeiten die Mitternachtssuppe, weil die Tanzfläche wichtiger ist?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Hochzeit heimlich die Tischkarten vertauscht?',
  'Wer von euch organisiert für eine Hochzeit die lustigsten Spiele?',
  'Wer würde am ehesten auf einer Hochzeit die halbe Nacht an der Fotobox verbringen?',
  'Wer hat am wahrscheinlichsten schon mal bei einer Brautentführung mitgemacht?',
  'Wer würde am ehesten auf einer Hochzeit bis zum Frühstück durchfeiern?',
  'Wer würde am ehesten für einen Junggesellenabschied die peinlichsten Shirts drucken lassen?',
  'Wer von euch würde auf einem Junggesellenabschied am ehesten Schnaps aus einem Bauchladen verkaufen?',
  'Wer hat am wahrscheinlichsten schon mal auf einem Junggesellenabschied im Kostüm durch die Innenstadt laufen müssen?',
  'Wer von euch passt auf dem Junggesellenabschied auf, dass die Hauptperson überlebt?',
  'Wer hat am wahrscheinlichsten schon mal auf einem Junggesellenabschied Fremde zum Mitfeiern überredet?',
  'Wer von euch würde einen Junggesellenabschied mit Minutenplan und Exceltabelle organisieren?',
  'Wer würde auf einem Junggesellenabschied am ehesten als Erstes schlappmachen?',
  'Wer würde am ehesten zum Junggesellenabschied ein Lied über die Hauptperson dichten?',
  'Wer würde am ehesten auf dem Oktoberfest auf der Bierbank stehen und mitsingen?',
  'Wer von euch schafft am meisten Maß an einem Wiesntag?',
  'Wer hat am wahrscheinlichsten schon mal auf der Wiesn den Platz im Zelt verloren?',
  'Wer würde am ehesten vom Oktoberfest mit einem Lebkuchenherz nach Hause kommen?',
  'Wer würde am ehesten nach drei Maß noch Kettenkarussell fahren?',
  'Wer hat am wahrscheinlichsten schon mal frühmorgens vor dem Bierzelt angestanden?',
  'Wer von euch kennt jedes Lied, das im Bierzelt läuft?',
  'Wer würde am ehesten auf dem Oktoberfest mit einem Tisch voller Fremder anstoßen?',
  'Wer hat am wahrscheinlichsten schon mal versucht, einen Maßkrug als Andenken mitzunehmen?',
  'Wer würde am ehesten auf dem Volksfest den Autoscooter zum Höhepunkt des Abends erklären?',
  'Wer würde am ehesten an Silvester den Countdown verpassen, weil die Person gerade auf dem Klo ist?',
  'Wer von euch hat an Silvester das meiste Feuerwerk dabei?',
  'Wer hat am wahrscheinlichsten schon mal an Silvester um Mitternacht die Gruppe aus den Augen verloren?',
  'Wer würde an Silvester am ehesten um zehn nach zwölf schon schlafen?',
  'Wer von euch fasst an Silvester die meisten Vorsätze und bricht sie am ersten Januar?',
  'Wer hat am wahrscheinlichsten schon mal Silvester im Club zum doppelten Eintrittspreis gefeiert?',
  'Wer würde am ehesten an Silvester auf drei Partys in einer Nacht gehen?',
  'Wer hat am wahrscheinlichsten schon mal an Silvester den Sekt viel zu früh geöffnet?',
  'Wer kann an Silvester am wahrscheinlichsten Dinner for One komplett mitsprechen?',
  'Wer würde am ehesten im Urlaub Sangria aus dem Eimer trinken?',
  'Wer von euch kennt alle Ballermannhits auswendig?',
  'Wer würde am ehesten im Urlaub eine Bootsparty buchen?',
  'Wer von euch fliegt am liebsten für ein Wochenende zum Feiern ins Ausland?',
  'Wer würde am ehesten im Urlaub nachts vergessen, wie das eigene Hotel heißt?',
  'Wer hat am wahrscheinlichsten schon mal im Urlaub die ganze Nacht am Strand verbracht?',
  'Wer von euch kommt aus dem Partyurlaub erholungsbedürftiger zurück als vorher?',
  'Wer hat am wahrscheinlichsten schon mal im Flieger mit dem Feiern angefangen?',
  'Wer von euch würde im Urlaub den Arschbombenwettbewerb am Pool gewinnen?',
  'Wer hat am wahrscheinlichsten schon mal ein Souvenir gekauft, an das keine Erinnerung mehr da ist?',
  'Wer von euch würde auf Ibiza am ehesten jede Nacht einen anderen Club ausprobieren?',
  'Wer würde am ehesten zum Feiern nach Prag fahren und nichts von der Stadt sehen?',
  'Wer hat am wahrscheinlichsten schon mal im Urlaub bei einer Kneipentour mit Fremden mitgemacht?',
  'Wer stellt im Gruppenurlaub am wahrscheinlichsten den Wecker für alle, obwohl niemand aufstehen will?',
  'Wer würde am ehesten im Ferienhaus den Pool nachts zur Partyzone machen?',
  'Wer würde am ehesten im Skiurlaub mehr Zeit in der Hütte als auf der Piste verbringen?',
  'Wer würde am ehesten in einer Kneipe die ganze Bar zum Mitsingen bringen?',
  'Wer von euch hat eine Stammkneipe, in der alle den eigenen Namen kennen?',
  'Wer bestellt an der Bar am wahrscheinlichsten etwas, das niemand aussprechen kann?',
  'Wer von euch würde am ehesten an einem Dienstag spontan feiern gehen?',
  'Wer von euch trinkt immer das Gleiche, egal wo?',
  'Wer würde am ehesten in der Bar den Nachbartisch zu einer Runde Kicker herausfordern?',
  'Wer hat am wahrscheinlichsten schon mal die Rechnung für alle bekommen, weil der Rest schon weg war?',
  'Wer würde am ehesten in einer Cocktailbar die Karte von vorne bis hinten durchprobieren?',
  'Wer von euch kennt das Barpersonal der halben Stadt persönlich?',
  'Wer würde am ehesten mit einer Gruppe Fremder um die Häuser ziehen?',
  'Wer hat am wahrscheinlichsten schon mal in einer Kneipe beim Dart die Stammgäste herausgefordert?',
  'Wer von euch würde am ehesten eine Weinprobe in ein Gelage verwandeln?',
  'Wer hat am wahrscheinlichsten schon mal an der Bar mit Fremden über das Leben diskutiert, bis zugemacht wurde?',
  'Wer von euch sagt um Mitternacht: Wir gehen jetzt noch woanders hin?',
  'Wer hat am wahrscheinlichsten schon mal eine Bar erst zusammen mit dem Personal verlassen?',
  'Wer von euch würde einen Partyabend am ehesten in der Shishabar ausklingen lassen?',
  'Wer würde am ehesten den Karneval in Köln eine ganze Woche durchfeiern?',
  'Wer von euch kann die meisten Karnevalslieder schunkelnd mitsingen?',
  'Wer hat am wahrscheinlichsten schon mal einen selbst angesetzten Likör auf eine Party mitgebracht?',
  'Wer würde am ehesten eine Bowle machen, die alle umhaut?',
  'Wer von euch hat den seltsamsten Lieblingsshot?',
  'Wer würde am ehesten bei jeder Runde Jägermeister vorschlagen?',
  'Wer hat am wahrscheinlichsten schon mal Tequila ohne Salz und Zitrone runtergekippt?',
  'Wer von euch würde auf einer Party nur alkoholfrei trinken und trotzdem am wildesten feiern?',
  'Wer würde am ehesten einen Cocktailkurs machen und danach alle damit nerven?',
  'Wer hat am wahrscheinlichsten schon mal eine Sektflasche mit einem Säbel geöffnet?',
  'Wer von euch kann eine Bierflasche mit allem außer einem Öffner aufmachen?',
  'Wer würde auf einer Party am ehesten die eigenen Getränke im Kühlschrank mit Namen beschriften?',
  'Wer von euch bringt am ehesten einen Schnaps aus dem Urlaub mit, den niemand trinken will?',
  'Wer würde am ehesten eine Runde Kurze ausgeben, um eine Diskussion zu beenden?',
  'Wer von euch hat schon mal eine Flasche Sekt geschüttelt und alle nass gespritzt?',
  'Wer würde am ehesten auf einer Party plötzlich einen Breakdance versuchen?',
  'Wer von euch spricht nach ein paar Drinks plötzlich fließend Englisch?',
  'Wer hat am wahrscheinlichsten schon mal ein Lied beim DJ gewünscht und es dann verpasst?',
  'Wer würde am ehesten mitten in der Party eine Rede auf die Freundschaft halten?',
  'Wer von euch filmt auf Partys alles für die Story?',
  'Wer würde am ehesten auf einer Party eine Wette verlieren und dafür etwas Verrücktes machen müssen?',
  'Wer würde sich am ehesten auf einer fremden Party benehmen, als wäre es die eigene Wohnung?',
  'Wer von euch fängt auf Partys am ehesten eine Diskussion über Politik an?',
  'Wer hat am wahrscheinlichsten schon mal eine Konfettikanone in einer Wohnung gezündet?',
  'Wer von euch ruft betrunken am ehesten die eigenen Eltern an?',
  'Wer würde am ehesten auf einer Party das Licht ausmachen und die Discokugel anwerfen?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Party einen Tanzwettbewerb gewonnen?',
  'Wer von euch kommt auf jede Party mit einer Begleitung, die niemand kennt?',
  'Wer hat am wahrscheinlichsten schon mal betrunken etwas online bestellt und es am nächsten Tag vergessen?',
  'Wer würde am ehesten auf einer Party den Fernseher anmachen, weil gerade Fußball läuft?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Party mit einer berühmten Person getanzt?',
  'Wer von euch trägt auf Partys eine Sonnenbrille, auch drinnen?',
  'Wer hat am wahrscheinlichsten schon mal ein Partyspiel so ernst genommen, dass Streit entstand?',
  'Wer von euch hat die meisten Partyfotos, auf denen die Augen zu sind?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Party gefeiert, ohne zu wissen, wessen Party das ist?',
  'Wer von euch würde am ehesten eine Schaumparty im Garten veranstalten?',
  'Wer würde am ehesten auf einer Party mit der Gitarre Lagerfeuerlieder spielen?',
  'Wer hat am wahrscheinlichsten schon mal eine Mottoparty ohne Kostüm besucht und es bereut?',
  'Wer von euch verwechselt auf jeder Party mindestens einmal das eigene Glas?',
  'Wer hat am wahrscheinlichsten schon mal eine weite Reise nur für eine einzige Party gemacht?',
  'Wer würde am ehesten den eigenen 30. Geburtstag mit einer riesigen Sause feiern?',
  'Wer hat am wahrscheinlichsten schon mal eine Überraschungsparty aus Versehen verraten?',
  'Wer von euch würde eine kippende Party am ehesten mit Schlagermusik retten?',
  'Wer würde am ehesten heute noch auf einer Abiparty mitfeiern wollen?',
  'Wer von euch hat auf Partys immer ein Ladekabel für alle dabei?',
  'Wer würde am ehesten auf einer Party Leute mit Zaubertricks unterhalten?',
  'Wer von euch tanzt mit geschlossenen Augen und vergisst alles um sich herum?',
  'Wer hat am wahrscheinlichsten schon mal auf einer Party eine Kissenschlacht gestartet?',
  'Wer hat am wahrscheinlichsten schon mal auf dem Heimweg von einer Party einen Igel gerettet?',
  'Wer von euch feiert auf Stadtfesten am längsten?',
  'Wer würde am ehesten auf einem Rave in einer Glitzerhose auftauchen?',
  'Wer würde am ehesten eine Grillparty bis tief in die Nacht ausdehnen?',
  'Wer würde am ehesten im Schlagerzelt Atemlos durch die Nacht mitgrölen?',
];
