export const roastQuestions: string[] = [
  'Wer würde am ehesten eine zehnminütige Sprachnachricht schicken, die auch in einen Satz gepasst hätte?',
  'Wer von euch kommt garantiert zu spät, selbst zur eigenen Geburtstagsfeier?',
  'Wer hat am wahrscheinlichsten schon mal eine Pflanze vertrocknen lassen, die angeblich unkaputtbar war?',
  'Wer ist die Person, die im Restaurant immer am längsten für die Bestellung braucht?',
  'Wer würde am ehesten ein Brettspiel abbrechen, nur weil es gerade schlecht läuft?',
  'Wer von euch antwortet auf Nachrichten erst nach drei Tagen, ist aber ständig online?',
  'Wer hat den fragwürdigsten Musikgeschmack in dieser Runde?',
  'Wer erzählt dieselbe Geschichte zum fünften Mal und merkt es nicht?',
  'Wer würde am ehesten beim Einparken dreimal neu ansetzen und dann trotzdem schief stehen?',
  'Wer von euch hat die meisten ungelesenen Mails im Postfach?',
  'Wer ist am schlechtesten darin, ein Geheimnis für sich zu behalten?',
  'Wer würde am ehesten eine Diskussion unbedingt gewinnen wollen, obwohl die Fakten klar dagegen sprechen?',
  'Wer hat am wahrscheinlichsten schon mal Nudelwasser anbrennen lassen?',
  'Wer von euch sagt "bin gleich da", obwohl noch nicht mal die Schuhe an sind?',
  'Wer ist die Person, die bei jedem Film nach fünf Minuten fragt, wer das nochmal war?',
  'Wer würde am ehesten das Handy ins Klo fallen lassen?',
  'Wer hat die chaotischste Wohnung von allen hier?',
  'Wer von euch leiht sich Sachen aus und gibt sie nie zurück?',
  'Wer würde am ehesten bei einem Quiz voller Überzeugung die falsche Antwort reinrufen?',
  'Wer trägt am wahrscheinlichsten heute noch Klamotten aus der Schulzeit?',
  'Wer ist der größte Besserwisser in dieser Gruppe?',
  'Wer würde am ehesten den Gruppenchat mit Memes zuspammen, die niemand lustig findet?',
  'Wer von euch schreibt die meisten Tippfehler und korrigiert sie nie?',
  'Wer braucht am längsten, um einen Witz zu verstehen?',
  'Wer würde am ehesten im Urlaub den Reisepass vergessen?',
  'Wer kann am schlechtesten kochen und hält sich trotzdem für einen Profi?',
  'Wer von euch hat den peinlichsten Klingelton oder Weckerton?',
  'Wer würde am ehesten bei einer Wanderung nach zehn Minuten fragen, wie weit es noch ist?',
  'Wer hat am wahrscheinlichsten schon mal zurückgewunken, obwohl jemand ganz anderes gemeint war?',
  'Wer redet beim Serienabend am meisten dazwischen?',
  'Wer würde am ehesten die eigene Handynummer nicht auswendig wissen?',
  'Wer von euch hat auf Gruppenfotos immer die Augen zu?',
  'Wer ist die Person, die nie Bargeld dabei hat, wenn es darauf ankommt?',
  'Wer würde am ehesten eine Pflanze, ein Haustier und einen Sauerteig gleichzeitig vernachlässigen?',
  'Wer hat den schlimmsten Orientierungssinn und verläuft sich sogar mit Navi?',
  'Wer von euch kauft Sportkleidung, trägt sie aber nur auf dem Sofa?',
  'Wer würde am ehesten einen Vertrag im Fitnessstudio abschließen und nie hingehen?',
  'Wer hat am wahrscheinlichsten schon mal eine Nachricht an die falsche Person geschickt?',
  'Wer ist am schnellsten beleidigt, wenn man einen kleinen Witz macht?',
  'Wer würde am ehesten beim Tanzen komplett aus dem Takt kommen und es nicht merken?',
  'Wer von euch hat das nervigste Lachen?',
  'Wer würde am ehesten eine Bewertung mit einem Stern schreiben, weil die Pommes kalt waren?',
  'Wer hat die schlechtesten Ausreden, um Pläne abzusagen?',
  'Wer ist die Person, die "ich hab keinen Hunger" sagt und dann von allen Tellern isst?',
  'Wer von euch fängt jedes Jahr ein neues Hobby an und gibt es nach zwei Wochen auf?',
  'Wer würde am ehesten bei Monopoly schummeln?',
  'Wer hat am wahrscheinlichsten schon mal das eigene Auto auf dem Parkplatz nicht wiedergefunden?',
  'Wer schaut beim Essen am meisten aufs Handy?',
  'Wer würde am ehesten eine Präsentation komplett improvisieren und behaupten, das sei Absicht gewesen?',
  'Wer von euch hat die längste Liste an angefangenen Serien, die nie zu Ende geschaut wurden?',
  'Wer ist der schlechteste Verlierer in dieser Runde?',
  'Wer würde am ehesten einen Streit mit einem Sprachassistenten anfangen?',
  'Wer hatte früher den peinlichsten Kleidungsstil, über den alle lieber schweigen?',
  'Wer von euch verschläft am häufigsten, trotz fünf Weckern?',
  'Wer würde am ehesten an der Selbstbedienungskasse bei jedem Artikel scheitern?',
  'Wer hat am wahrscheinlichsten schon mal einen Termin vergessen und es erst am nächsten Tag gemerkt?',
  'Wer ist die Person, die immer "nur kurz" etwas erzählen will und dann eine Stunde redet?',
  'Wer würde am ehesten im Escape Room als Erstes aufgeben?',
  'Wer von euch hat den chaotischsten Rucksack oder die unordentlichste Tasche?',
  'Wer würde am ehesten Pläne absagen, weil die Couch einfach zu gemütlich ist?',
  'Wer hat das schlechteste Gedächtnis für Namen?',
  'Wer ist am geizigsten, wenn es ums Rechnungteilen geht?',
  'Wer von euch hat schon am meisten Geld für etwas völlig Unnötiges ausgegeben?',
  'Wer würde am ehesten ein Selfie mit einer viel zu tiefgründigen Bildunterschrift posten?',
  'Wer hat am wahrscheinlichsten schon mal eine Plastikpflanze gegossen?',
  'Wer gibt die schlechtesten Ratschläge, aber mit der größten Überzeugung?',
  'Wer würde am ehesten mit Einkaufszettel losgehen und trotzdem das Wichtigste vergessen?',
  'Wer von euch meckert im Straßenverkehr am meisten?',
  'Wer ist die Person, die gefühlt jeden Satz mit "eigentlich" anfängt?',
  'Wer würde am ehesten beim Karaoke ein Lied wählen, das viel zu hoch ist?',
  'Wer hat die meisten offenen Tabs im Browser und weiß bei keinem mehr, warum?',
  'Wer von euch tut so, als hätte es das Buch gelesen, obwohl nur der Film geschaut wurde?',
  'Wer würde am ehesten ein Regal aufbauen und am Ende Schrauben übrig haben?',
  'Wer hat am wahrscheinlichsten schon mal laut über einen Witz gelacht, ohne ihn zu verstehen?',
  'Wer ist am schlechtesten darin, ein Geschenk ordentlich zu verpacken?',
  'Wer würde am ehesten Essen zurückgehen lassen, das genau so bestellt wurde?',
  'Wer von euch führt die lautesten Telefonate in der Bahn?',
  'Wer würde am ehesten bei einer peinlichen Stille genau das falsche Thema anschneiden?',
  'Wer googelt heimlich unter dem Tisch und verkauft das dann als Allgemeinwissen?',
  'Wer ist die Person, deren Handyakku immer bei zwei Prozent ist?',
];
