export const roastQuestions: string[] = [
  'Wer würde am ehesten eine zehnminütige Sprachnachricht schicken, die auch in einen Satz gepasst hätte?',
  'Wer von euch kommt garantiert zu spät, selbst zur eigenen Geburtstagsfeier?',
  'Wer hat am wahrscheinlichsten schon mal eine Pflanze vertrocknen lassen, die angeblich unkaputtbar war?',
  'Wer ist die Person, die im Restaurant immer am längsten für die Bestellung braucht?',
  'Wer würde am ehesten ein Brettspiel abbrechen, nur weil es gerade schlecht läuft?',
  'Wer von euch antwortet auf Nachrichten erst nach drei Tagen, ist aber ständig online?',
  'Wer hat den fragwürdigsten Musikgeschmack in dieser Runde?',
  'Wer erzählt dieselbe Geschichte zum fünften Mal und merkt es nicht?',
  'Wer würde am ehesten beim Einparken dreimal neu ansetzen und dann trotzdem schief stehen?',
  'Wer von euch hat die meisten ungelesenen Mails im Postfach?',
  'Wer ist am schlechtesten darin, ein Geheimnis für sich zu behalten?',
  'Wer würde am ehesten eine Diskussion unbedingt gewinnen wollen, obwohl die Fakten klar dagegen sprechen?',
  'Wer hat am wahrscheinlichsten schon mal Nudelwasser anbrennen lassen?',
  'Wer von euch sagt "bin gleich da", obwohl noch nicht mal die Schuhe an sind?',
  'Wer ist die Person, die bei jedem Film nach fünf Minuten fragt, wer das nochmal war?',
  'Wer würde am ehesten das Handy ins Klo fallen lassen?',
  'Wer hat die chaotischste Wohnung von allen hier?',
  'Wer von euch leiht sich Sachen aus und gibt sie nie zurück?',
  'Wer würde am ehesten bei einem Quiz voller Überzeugung die falsche Antwort reinrufen?',
  'Wer trägt am wahrscheinlichsten heute noch Klamotten aus der Schulzeit?',
  'Wer ist der größte Besserwisser in dieser Gruppe?',
  'Wer würde am ehesten den Gruppenchat mit Memes zuspammen, die niemand lustig findet?',
  'Wer von euch schreibt die meisten Tippfehler und korrigiert sie nie?',
  'Wer würde am ehesten im Urlaub den Reisepass vergessen?',
  'Wer kann am schlechtesten kochen und hält sich trotzdem für einen Profi?',
  'Wer von euch hat den peinlichsten Klingelton oder Weckerton?',
  'Wer würde am ehesten bei einer Wanderung nach zehn Minuten fragen, wie weit es noch ist?',
  'Wer hat am wahrscheinlichsten schon mal zurückgewunken, obwohl jemand ganz anderes gemeint war?',
  'Wer redet beim Serienabend am meisten dazwischen?',
  'Wer ist die Person, die nie Bargeld dabei hat, wenn es darauf ankommt?',
  'Wer hat den schlimmsten Orientierungssinn und verläuft sich sogar mit Navi?',
  'Wer von euch kauft Sportkleidung, trägt sie aber nur auf dem Sofa?',
  'Wer würde am ehesten einen Vertrag im Fitnessstudio abschließen und nie hingehen?',
  'Wer spoilert am ehesten das Ende einer Serie und tut dann so, als wäre das keine große Sache?',
  'Wer ist am schnellsten beleidigt, wenn man einen kleinen Witz macht?',
  'Wer würde am ehesten beim Tanzen komplett aus dem Takt kommen und es nicht merken?',
  'Wer von euch hat das nervigste Lachen?',
  'Wer würde am ehesten eine Bewertung mit einem Stern schreiben, weil die Pommes kalt waren?',
  'Wer hat die schlechtesten Ausreden, um Pläne abzusagen?',
  'Wer ist die Person, die "ich hab keinen Hunger" sagt und dann von allen Tellern isst?',
  'Wer von euch fängt jedes Jahr ein neues Hobby an und gibt es nach zwei Wochen auf?',
  'Wer hat am wahrscheinlichsten schon mal das eigene Auto auf dem Parkplatz nicht wiedergefunden?',
  'Wer schaut beim Essen am meisten aufs Handy?',
  'Wer würde am ehesten eine Präsentation komplett improvisieren und behaupten, das sei Absicht gewesen?',
  'Wer von euch hat die längste Liste an angefangenen Serien, die nie zu Ende geschaut wurden?',
  'Wer ist der schlechteste Verlierer in dieser Runde?',
  'Wer würde am ehesten einen Streit mit einem Sprachassistenten anfangen?',
  'Wer von euch verschläft am häufigsten, trotz fünf Weckern?',
  'Wer würde am ehesten an der Selbstbedienungskasse bei jedem Artikel scheitern?',
  'Wer hat am wahrscheinlichsten schon mal einen Termin vergessen und es erst am nächsten Tag gemerkt?',
  'Wer ist die Person, die immer "nur kurz" etwas erzählen will und dann eine Stunde redet?',
  'Wer würde am ehesten im Escape Room als Erstes aufgeben?',
  'Wer von euch hat den chaotischsten Rucksack oder die unordentlichste Tasche?',
  'Wer würde am ehesten Pläne absagen, weil die Couch einfach zu gemütlich ist?',
  'Wer hat das schlechteste Gedächtnis für Namen?',
  'Wer würde am ehesten ein Selfie mit einer viel zu tiefgründigen Bildunterschrift posten?',
  'Wer hat am wahrscheinlichsten schon mal eine Plastikpflanze gegossen?',
  'Wer gibt die schlechtesten Ratschläge, aber mit der größten Überzeugung?',
  'Wer würde am ehesten mit Einkaufszettel losgehen und trotzdem das Wichtigste vergessen?',
  'Wer ist die Person, die gefühlt jeden Satz mit "eigentlich" anfängt?',
  'Wer würde am ehesten beim Karaoke ein Lied wählen, das viel zu hoch ist?',
  'Wer hat die meisten offenen Tabs im Browser und weiß bei keinem mehr, warum?',
  'Wer von euch redet über Bücher mit, obwohl nur der Film geschaut wurde?',
  'Wer würde am ehesten ein Regal aufbauen und am Ende Schrauben übrig haben?',
  'Wer hat am wahrscheinlichsten schon mal laut über einen Witz gelacht, ohne ihn zu verstehen?',
  'Wer ist am schlechtesten darin, ein Geschenk ordentlich zu verpacken?',
  'Wer würde am ehesten Essen zurückgehen lassen, das genau so bestellt wurde?',
  'Wer von euch führt die lautesten Telefonate in der Bahn?',
  'Wer würde am ehesten bei einer peinlichen Stille genau das falsche Thema anschneiden?',
  'Wer googelt heimlich unter dem Tisch und verkauft das dann als Allgemeinwissen?',
  'Wer ist die Person, deren Handyakku immer bei zwei Prozent ist?',
  'Wer würde am ehesten zum Flughafen fahren, wenn das Boarding schon begonnen hat?',
  'Wer würde am ehesten am richtigen Ort auftauchen, nur leider am falschen Tag?',
  'Wer drückt im Aufzug am ehesten fünfmal auf den Knopf, als würde es dadurch schneller gehen?',
  'Wer hat am wahrscheinlichsten schon mal einen Zug verpasst, weil noch schnell ein Kaffee sein musste?',
  'Wer sagt bei Plänen immer "mal schauen" und meint damit eigentlich nein?',
  'Wer von euch erinnert sich an Geburtstage nur dank Social Media?',
  'Wer ist am schlechtesten darin, eine Frist einzuhalten, und hat dafür immer eine Geschichte parat?',
  'Wer braucht morgens am längsten im Bad und gibt dem Wasserdruck die Schuld?',
  'Wer würde am ehesten den eigenen Umzug planen und am Tag davor merken, dass es keine Kartons gibt?',
  'Wer ist die Person, die beim Ausflug noch kurz aufs Klo muss, wenn alle schon an der Tür stehen?',
  'Wer würde am ehesten ein Konzert nur durch den Handybildschirm erleben?',
  'Wer ist die Person, die jedes Essen erst fotografieren muss, bevor jemand anfangen darf?',
  'Wer würde am ehesten ein Passwort vergessen, das erst vor fünf Minuten erstellt wurde?',
  'Wer reagiert auf ernste Nachrichten nur mit einem Daumen hoch?',
  'Wer ist am wahrscheinlichsten schon mal gegen eine Laterne gelaufen, weil das Handy spannender war?',
  'Wer würde am ehesten den Computer ausschalten, indem einfach der Stecker gezogen wird?',
  'Wer von euch fragt bei jedem technischen Problem sofort jemand anderen, statt es selbst zu versuchen?',
  'Wer ist die Person, die jedes Update ewig wegklickt, bis gar nichts mehr geht?',
  'Wer redet im Videocall minutenlang, obwohl das Mikro stumm geschaltet ist?',
  'Wer würde am ehesten das Handy suchen, während damit telefoniert wird?',
  'Wer würde am ehesten Spaghetti mit Ketchup als Gourmetgericht verkaufen?',
  'Wer von euch hat beim Kochen schon öfter den Rauchmelder ausgelöst als alle anderen zusammen?',
  'Wer würde am ehesten Tiefkühlpizza mitsamt Plastikfolie in den Ofen schieben?',
  'Wer hat den Kühlschrank mit den ältesten Lebensmitteln, die schon ein Eigenleben führen?',
  'Wer würde am ehesten im Restaurant immer das Gleiche bestellen, egal wie groß die Karte ist?',
  'Wer von euch beschwert sich über zu scharfes Essen, wenn nur ein Hauch Pfeffer drin ist?',
  'Wer bringt zum Picknick garantiert nur Servietten mit?',
  'Wer von euch isst am lautesten?',
  'Wer hat am wahrscheinlichsten schon mal Zucker mit Salz verwechselt und den Kuchen trotzdem serviert?',
  'Wer von euch sagt "mir egal, wo wir essen" und lehnt dann jeden Vorschlag ab?',
  'Wer lässt Geschirr tagelang einweichen, bis es angeblich von allein sauber wird?',
  'Wer von euch kauft Gemüse, um gesünder zu leben, und wirft es eine Woche später weg?',
  'Wer würde am ehesten eine Metallschüssel in die Mikrowelle stellen und sich über das Feuerwerk wundern?',
  'Wer ist die Person, die beim Grillen alles schwarz werden lässt und das dann Röstaromen nennt?',
  'Wer würde am ehesten Geschenkpapier vorsichtig auspacken, um es nächstes Jahr wiederzuverwenden?',
  'Wer würde am ehesten zwanzig Minuten fahren, um zehn Cent beim Tanken zu sparen?',
  'Wer von euch gibt am wenigsten Trinkgeld und findet trotzdem den Service schlecht?',
  'Wer würde am ehesten die Probierhäppchen im Supermarkt als Mittagessen betrachten?',
  'Wer ist die Person, deren Geschenke verdächtig nach Werbegeschenk aussehen?',
  'Wer hat am wahrscheinlichsten noch Abos laufen, von denen niemand mehr etwas weiß?',
  'Wer würde am ehesten ein Streamingkonto mit fünf Fremden teilen, nur um zwei Euro zu sparen?',
  'Wer von euch kauft Dinge, die niemand braucht, nur weil sie reduziert waren?',
  'Wer würde am ehesten ein Geschenk weiterverschenken und dabei die alte Karte drinlassen?',
  'Wer würde am ehesten Zuckertütchen und Ketchup aus Restaurants mitnehmen?',
  'Wer von euch ist immer genau dann auf Toilette, wenn die Rechnung kommt?',
  'Wer würde am ehesten einen längst abgelaufenen Gutschein einlösen wollen und dann diskutieren?',
  'Wer ist die Person, die beim Gruppengeschenk erst bezahlt, wenn dreimal nachgefragt wurde?',
  'Wer von euch fährt so langsam, dass Radfahrer überholen?',
  'Wer würde am ehesten im Kreisverkehr dreimal im Kreis fahren, weil die Ausfahrt verpasst wurde?',
  'Wer hat am wahrscheinlichsten schon mal den Blinker die ganze Fahrt lang angelassen?',
  'Wer ist die Person, die als Beifahrer ständig mitbremst und kommentiert?',
  'Wer von euch dreht die Karte auf dem Handy so lange, bis niemand mehr weiß, wo Norden ist?',
  'Wer würde am ehesten an der Tankstelle jedes Mal auf der falschen Seite halten?',
  'Wer von euch fährt Rad, als würde die Straße allein gehören?',
  'Wer hat am wahrscheinlichsten schon mal ein Knöllchen bekommen, weil es nur kurz zum Bäcker gehen sollte?',
  'Wer würde am ehesten eine Abkürzung vorschlagen, die eine Stunde länger dauert?',
  'Wer ist die Person, die im Auto die Musik übernimmt und niemand anderen ranlässt?',
  'Wer hupt am häufigsten, auch wenn es überhaupt nichts bringt?',
  'Wer würde am ehesten das Mietauto mit einer Beule zurückgeben und auf unschuldig machen?',
  'Wer von euch nimmt im Bus immer zwei Sitzplätze ein, einen für sich und einen für die Tasche?',
  'Wer würde am ehesten auf der Autobahn die mittlere Spur nie verlassen?',
  'Wer von euch macht aus einem Papierschnitt eine Tragödie in drei Akten?',
  'Wer postet kryptische Statusmeldungen, nur damit alle nachfragen?',
  'Wer von euch verlässt den Raum theatralisch und hofft, dass jemand hinterherkommt?',
  'Wer bekommt bei Hunger schlechtere Laune als ein Kleinkind?',
  'Wer würde am ehesten so laut seufzen, dass alle fragen müssen, was los ist?',
  'Wer ist die Person, bei der jede Geschichte mit "Ihr glaubt nicht, was mir passiert ist" anfängt?',
  'Wer würde am ehesten eine Wespe am Tisch behandeln, als wäre es ein Bär?',
  'Wer von euch übertreibt beim Erzählen so stark, dass am Ende niemand mehr die echte Version kennt?',
  'Wer schreibt nach einem Streit lange Nachrichten mit Absätzen und Zitaten?',
  'Wer würde am ehesten "Ich will nicht darüber reden" sagen und dann eine Stunde darüber reden?',
  'Wer würde am ehesten bei schlechtem WLAN lautstark das Ende der Zivilisation ausrufen?',
  'Wer von euch hat die kreativste Ausrede, warum der Müll noch nicht rausgebracht wurde?',
  'Wer würde am ehesten behaupten, das Handy war auf lautlos, obwohl es direkt daneben lag?',
  'Wer ist die Person, die beim Umzug helfen will, aber erst kommt, wenn alles getragen ist?',
  'Wer würde am ehesten eine Aufgabe absichtlich so schlecht erledigen, dass niemand je wieder fragt?',
  'Wer von euch sagt "ich mach das morgen" und meint damit nächstes Jahr?',
  'Wer liegt am Wochenende am längsten im Bett und nennt das Erholung?',
  'Wer hat am wahrscheinlichsten schon mal einen Stau erfunden, um eine Verspätung zu erklären?',
  'Wer würde am ehesten lieber eine Stunde frieren, als aufzustehen und eine Decke zu holen?',
  'Wer von euch wirft Klamotten auf den Stuhl, bis der Stuhl darunter verschwindet?',
  'Wer würde am ehesten bei Gruppenarbeiten nur den eigenen Namen beisteuern?',
  'Wer ist die Person, die beim Abwasch plötzlich ganz dringend telefonieren muss?',
  'Wer würde am ehesten dieselbe Ausrede so oft benutzen, dass alle sie mitsprechen können?',
  'Wer hat am wahrscheinlichsten noch Kartons vom letzten Umzug, die nie ausgepackt wurden?',
  'Wer würde am ehesten nur dort Staub wischen, wo der Besuch hinschaut?',
  'Wer ist die Person, die ständig "ich bin so beschäftigt" sagt und dann den ganzen Tag Serien schaut?',
  'Wer würde am ehesten die frische Wäsche wochenlang direkt aus dem Wäschekorb tragen?',
  'Wer von euch trägt Socken in Sandalen und verteidigt das als Trend?',
  'Wer würde am ehesten zu einer Hochzeit im Hoodie erscheinen?',
  'Wer hat die meisten Kleidungsstücke mit Etikett im Schrank, die nie getragen wurden?',
  'Wer ist die Person, die jeden Modetrend mitmacht, aber immer zwei Jahre zu spät?',
  'Wer würde am ehesten ein Shirt mit einem peinlichen Spruch voller Stolz tragen?',
  'Wer würde am ehesten drinnen eine Sonnenbrille tragen und das cool finden?',
  'Wer ist die Person, deren Lieblingspulli inzwischen mehr Löcher als Stoff hat?',
  'Wer würde am ehesten im Schlafanzug zum Supermarkt gehen?',
  'Wer würde am ehesten ein Profilbild benutzen, das mindestens zehn Jahre alt ist?',
  'Wer von euch hat zu Hause eine Schublade voller Kabel, zu denen kein Gerät mehr existiert?',
  'Wer hat den schlechtesten Geschmack bei Geschenken und merkt es nicht?',
  'Wer würde am ehesten Deko kaufen, auf der "Live Laugh Love" steht?',
  'Wer von euch trägt immer dieselbe Hose und behauptet, es seien mehrere gleiche?',
  'Wer von euch singt im Auto lauthals mit und kennt trotzdem keinen einzigen Text richtig?',
  'Wer würde am ehesten bei jedem Treffen dieselbe Playlist abspielen?',
  'Wer hört heimlich Schlager und tut so, als wäre es ironisch?',
  'Wer ist die Person, die bei jedem Lied sagt, dass die alte Version besser war?',
  'Wer würde am ehesten den eigenen Jahresrückblick der Musikapp lieber geheim halten?',
  'Wer von euch summt ständig vor sich hin, ohne es zu merken?',
  'Wer würde am ehesten eine Band nur deshalb gut finden, weil sie noch niemand kennt?',
  'Wer pfeift am schiefsten und hört trotzdem nicht auf?',
  'Wer ist die Person, die einen Ohrwurm so lange singt, bis ihn alle anderen auch haben?',
  'Wer würde am ehesten auf ein Konzert gehen und nur das eine bekannte Lied kennen?',
  'Wer würde am ehesten unter der Dusche eine Oper aufführen, die das ganze Haus mithört?',
  'Wer von euch erklärt allen ungefragt, warum ihre Lieblingsmusik eigentlich schlecht ist?',
  'Wer würde am ehesten ein Hobby nur wegen der teuren Ausrüstung anfangen?',
  'Wer hat zu Hause ein Fahrrad, dessen Reifen seit Jahren platt sind?',
  'Wer würde am ehesten nach einer einzigen Yogastunde allen Tipps zur Atmung geben?',
  'Wer von euch fotografiert jeden Sonnenuntergang, als wäre es der letzte?',
  'Wer ist die Person, die nach einer einzigen Doku sofort Fachmensch für das Thema ist?',
  'Wer von euch korrigiert bei jeder Gelegenheit die Grammatik der anderen?',
  'Wer würde am ehesten mitten in einer Geschichte unterbrechen, um eine eigene, bessere zu erzählen?',
  'Wer ist die Person, die jeden Witz so lange erklärt, bis er nicht mehr lustig ist?',
  'Wer würde am ehesten in jeder Diskussion Studien zitieren, die noch nie jemand gesehen hat?',
  'Wer hat zu jedem Thema eine Meinung, auch ohne die geringste Ahnung?',
  'Wer würde am ehesten "Hab ich doch gleich gesagt" sagen, obwohl es nie gesagt wurde?',
  'Wer spricht am liebsten über sich selbst, selbst wenn es gerade um jemand anderen geht?',
  'Wer würde am ehesten die Regeln eines Spiels so lange erklären, bis niemand mehr Lust hat?',
  'Wer ist die Person, die beim Erzählen ständig den Faden verliert und bei etwas völlig anderem landet?',
  'Wer würde am ehesten einem Profi erklären, wie dessen eigener Job richtig geht?',
  'Wer flüstert am lautesten?',
  'Wer von euch benutzt am häufigsten Fremdwörter, deren Bedeutung nicht ganz klar ist?',
  'Wer würde am ehesten in einem Streit mit "Ich sag ja nur" alles noch schlimmer machen?',
  'Wer ist am schlechtesten im Zuhören und fragt danach alles nochmal?',
  'Wer würde am ehesten einen Fun Fact erzählen, der nachweislich falsch ist?',
  'Wer würde am ehesten beim Kreuzworträtsel schummeln und es trotzdem nicht schaffen?',
  'Wer würde am ehesten die Spülmaschine völlig falsch einräumen und es dann ein System nennen?',
  'Wer hat das dreckigste Auto, mit Krümeln aus mehreren Jahren?',
  'Wer würde am ehesten passiv aggressive Zettel in der Küche der WG aufhängen?',
  'Wer von euch hat mehr Duftkerzen als Möbel?',
  'Wer würde am ehesten weiße und bunte Wäsche zusammen waschen, immer wieder?',
  'Wer lässt am längsten die leere Klopapierrolle hängen?',
  'Wer würde am ehesten dem Staubsaugerroboter einen Namen geben und ihn wie ein Haustier behandeln?',
  'Wer von euch stopft alles in den Schrank, damit die Wohnung aufgeräumt aussieht?',
  'Wer würde am ehesten ein Bild aufhängen und dabei fünf Löcher zu viel bohren?',
  'Wer stellt die fast leere Milchpackung am ehesten wieder in den Kühlschrank, statt sie wegzuwerfen?',
  'Wer ist die Person, die den Kühlschrank öffnet, reinstarrt und ihn ohne etwas wieder schließt?',
  'Wer würde am ehesten einen tropfenden Wasserhahn jahrelang ignorieren?',
  'Wer von euch bringt Pfandflaschen erst weg, wenn sie den halben Flur blockieren?',
  'Wer würde am ehesten die Waschmaschine anstellen und die Wäsche drei Tage darin vergessen?',
  'Wer hat das Bett noch nie freiwillig gemacht?',
  'Wer würde am ehesten ein Handtuch so lange benutzen, bis es von allein steht?',
  'Wer von euch dekoriert zu Weihnachten so übertrieben, dass die Nachbarn Sonnenbrillen brauchen?',
  'Wer lässt den Weihnachtsbaum am längsten stehen, bis weit in den Frühling?',
  'Wer ist die Person, die bei jedem Besuch die Schuhe anbehält, egal wie oft gefragt wird?',
  'Wer von euch schreibt in Mails "siehe unten", obwohl unten gar nichts steht?',
  'Wer würde am ehesten in einem Meeting nicken, ohne ein Wort verstanden zu haben?',
  'Wer ist die Person, die jede Mail mit drei Ausrufezeichen beendet?',
  'Wer würde am ehesten aus Versehen auf "Allen antworten" klicken und die ganze Firma anschreiben?',
  'Wer hatte in der Schule die absurdesten Ausreden für vergessene Hausaufgaben?',
  'Wer ist die Person, die im Homeoffice nur oben herum ordentlich angezogen ist?',
  'Wer von euch tut beschäftigt, sobald jemand Wichtiges vorbeikommt?',
  'Wer würde am ehesten bei einer Prüfung voller Überzeugung über das falsche Thema schreiben?',
  'Wer von euch macht aus jeder Kleinigkeit ein Meeting?',
  'Wer würde am ehesten zur Firmenfeier nur wegen des kostenlosen Buffets gehen?',
  'Wer ist die Person, die "teamfähig" im Lebenslauf stehen hat, aber nie ans Telefon geht?',
  'Wer würde am ehesten eine Präsentation mit bunten Effekten und blinkenden Übergängen vollstopfen?',
  'Wer würde am ehesten beim Volleyball dem Ball ausweichen, statt ihn zu spielen?',
  'Wer von euch erfindet beim Kartenspielen spontan neue Regeln, die zufällig immer helfen?',
  'Wer ist die Person, die bei Videospielen grundsätzlich dem Controller die Schuld gibt?',
  'Wer von euch brüllt beim Fußballschauen den Fernseher an, als könnte das Team es hören?',
  'Wer würde am ehesten bei Stadt Land Fluss Wörter erfinden und darauf bestehen, dass es sie gibt?',
  'Wer ist am schlechtesten darin, ein Pokerface zu machen?',
  'Wer von euch zählt beim Würfeln heimlich ein Feld mehr?',
  'Wer würde am ehesten beim Bowling jede Kugel in die Rinne werfen und der Bahn die Schuld geben?',
  'Wer würde am ehesten beim Spieleabend eine halbe Stunde über den eigenen Zug nachdenken?',
  'Wer von euch erzählt noch Jahre später von dem einen Sieg im Tischtennis?',
  'Wer würde am ehesten bei einem Wettrennen schon vor dem Startsignal loslaufen?',
  'Wer hat das schlechteste Ballgefühl und trifft trotzdem immer die Lampe?',
  'Wer von euch kann nicht mal bei Schere, Stein, Papier fair spielen?',
  'Wer würde am ehesten bei Werwolf sofort auffliegen, weil das Grinsen einfach nicht aufhört?',
  'Wer ist die Person, die bei Uno ständig erklärt, dass man das zu Hause ganz anders spielt?',
  'Wer von euch fragt erst, wer noch alles kommt, bevor überhaupt zugesagt wird?',
  'Wer würde am ehesten bei einer Umfrage im Gruppenchat nie abstimmen und sich dann beschweren?',
  'Wer ist die Person, die jede neue Bekanntschaft nach fünf Minuten zur Lieblingsperson erklärt?',
  'Wer würde am ehesten auf einer Hochzeit eine Rede halten, die nur von sich selbst handelt?',
  'Wer von euch verabschiedet sich und steht dann noch eine Stunde im Türrahmen?',
  'Wer würde am ehesten Gäste einladen und noch nicht geduscht sein, wenn es klingelt?',
  'Wer ist die Person, die bei jedem Gruppenfoto noch einmal neu aufnehmen will?',
  'Wer von euch sagt immer "ich bring was mit" und kommt dann mit leeren Händen?',
  'Wer würde am ehesten einen Insider erzählen, den außer der Person selbst niemand versteht?',
  'Wer würde am ehesten Gerüchte aus der Nachbarschaft schneller verbreiten als die Lokalzeitung?',
  'Wer ist am schlechtesten darin, gespielte Freude über ein Geschenk zu zeigen?',
  'Wer würde am ehesten Bekannte im Supermarkt sehen und sich hinter dem Regal verstecken?',
  'Wer von euch kommt beim Smalltalk nie über das Wetter hinaus?',
  'Wer würde am ehesten eine Überraschungsfeier planen und vergessen, die Hauptperson einzuladen?',
  'Wer ist die Person, die beim gemeinsamen Film einschläft und danach wissen will, wie er ausgeht?',
  'Wer von euch packt für ein Wochenende drei Koffer ein?',
  'Wer würde am ehesten im Urlaub nur im Hotel bleiben und trotzdem von der Kultur schwärmen?',
  'Wer ist die Person, die im Ausland einfach lauter Deutsch spricht, damit es alle verstehen?',
  'Wer würde am ehesten um sieben Uhr morgens die Strandliege mit einem Handtuch reservieren?',
  'Wer würde am ehesten im Ausland ausschließlich Schnitzel mit Pommes bestellen?',
  'Wer ist die Person, die nach einer Woche Urlaub mit einem neuen Akzent zurückkommt?',
  'Wer von euch kauft im Urlaub Souvenirs, die zu Hause sofort in der Schublade landen?',
  'Wer würde am ehesten nach einer Nacht im Zelt sofort das nächste Hotel buchen?',
  'Wer hat die schlechtesten Fremdsprachenkenntnisse, redet im Ausland aber am meisten?',
  'Wer würde am ehesten beim Camping vergessen, die Heringe einzupacken?',
  'Wer ist die Person, die im Flugzeug sofort die Schuhe auszieht?',
  'Wer von euch erzählt nach jedem Urlaub wochenlang von nichts anderem mehr?',
  'Wer würde am ehesten im Hotel das Frühstücksbuffet für den ganzen Tag einpacken?',
  'Wer würde am ehesten an einer Tür ziehen, auf der groß "Drücken" steht?',
  'Wer ist die Person, die im Kino am lautesten mit der Tüte raschelt?',
  'Wer schläft bei jeder Autofahrt nach fünf Minuten ein und behauptet danach, die ganze Zeit wach gewesen zu sein?',
  'Wer von euch schnarcht am lautesten und streitet es vehement ab?',
  'Wer würde am ehesten Schlüssel, Handy und Geldbeutel gleichzeitig suchen?',
  'Wer würde am ehesten den Schlüssel innen stecken lassen und sich aussperren?',
  'Wer ist die Person, die bei Horrorfilmen die ganze Zeit wegschaut und trotzdem mitreden will?',
  'Wer von euch verrät das Ende von Filmen, ohne vorher zu fragen?',
  'Wer würde am ehesten mit dem eigenen Haustier ausführlichere Gespräche führen als mit Menschen?',
  'Wer hat am wahrscheinlichsten schon mal ein Paket an die alte Adresse bestellt?',
  'Wer von euch kommt mit zwei vollen Einkaufstüten nach Hause, obwohl nur Milch gefehlt hat?',
  'Wer ist die Person, die beim Spazierengehen so langsam schlendert, dass alle warten müssen?',
  'Wer würde am ehesten an der Kasse erst nach dem Scannen anfangen, das Portemonnaie zu suchen?',
  'Wer von euch macht beim Niesen das dramatischste Geräusch?',
  'Wer würde am ehesten eine Petition starten, weil das Lieblingsprodukt aus dem Sortiment geflogen ist?',
  'Wer hat eine Handschrift, die nicht mal selbst entziffert werden kann?',
  'Wer würde am ehesten vier Stunden im Möbelhaus verbringen und am Ende nur Teelichter kaufen?',
  'Wer ist die Person, die immer die langsamste Schlange erwischt und sich dann lautstark beschwert?',
  'Wer von euch zählt vor jedem Foto laut runter und drückt dann trotzdem zu früh ab?',
  'Wer würde am ehesten eine Stunde mit der Hotline diskutieren, obwohl der Fehler klar bei sich selbst liegt?',
  'Wer von euch ist morgens vor dem ersten Kaffee nicht ansprechbar?',
];
