export const sexualQuestions: string[] = [
  'Wer hatte schon mal ein Date mit zwei Leuten am selben Tag?',
  'Wer würde am ehesten beim ersten Date schon über Hochzeit reden?',
  'Wer von euch hat die meisten Matches auf Tinder?',
  'Wer hat am wahrscheinlichsten schon mal im Bett den falschen Namen gesagt?',
  'Wer würde am ehesten wieder mit dem Ex im Bett landen?',
  'Wer kann sich an den Namen eines One-Night-Stands nicht mehr erinnern?',
  'Wer von euch flirtet am meisten, ohne es selbst zu merken?',
  'Wer würde am ehesten heute Abend jemanden aus dieser Runde küssen?',
  'Wer hat am wahrscheinlichsten schon mal im Auto rumgemacht?',
  'Wer hatte schon mal etwas mit der besten Freundin oder dem besten Freund vom Ex?',
  'Wer würde am ehesten eine offene Beziehung ausprobieren?',
  'Wer schickt am ehesten um drei Uhr nachts ein "Bist du noch wach?"?',
  'Wer von euch hatte schon mal Sex an einem öffentlichen Ort?',
  'Wer würde am ehesten auf einer Hochzeit mit einem Gast für eine Stunde verschwinden?',
  'Wer hat am wahrscheinlichsten schon mal ein Tinder-Date geghostet?',
  'Wer hat beim Küssen schon mal so gelacht, dass die Stimmung komplett weg war?',
  'Wer würde am ehesten im Fitnessstudio flirten, statt zu trainieren?',
  'Wer löscht Tinder am häufigsten und lädt es eine Woche später wieder runter?',
  'Wer hatte früher heimlich einen Crush auf eine Lehrkraft?',
  'Wer würde am ehesten einen Dreier ausprobieren?',
  'Wer von euch ist am ehesten der Typ für Sex beim ersten Date?',
  'Wer hat sich am wahrscheinlichsten schon mal morgens heimlich aus der Wohnung eines Dates geschlichen?',
  'Wer würde am ehesten aus Versehen Nudes an die falsche Person schicken?',
  'Wer hatte schon mal eine Urlaubsromanze, von der niemand wissen durfte?',
  'Wer flirtet am ehesten mit dem Barpersonal, um Getränke umsonst zu bekommen?',
  'Wer würde am ehesten auf einer Party mit zwei verschiedenen Leuten knutschen?',
  'Wer von euch hat die peinlichste Sexgeschichte?',
  'Wer hat am wahrscheinlichsten schon mal beim Sex einen Krampf bekommen?',
  'Wer würde am ehesten ein Date schon beim zweiten Treffen den Eltern vorstellen?',
  'Wer hat schon mal jemanden geküsst, nur um eine andere Person eifersüchtig zu machen?',
  'Wer würde am ehesten mit der ganzen Gruppe in einen Sexshop gehen?',
  'Wer hat die längste Flaute im Bett hinter sich?',
  'Wer hat am wahrscheinlichsten schon mal mit jemandem von der Arbeit rumgemacht?',
  'Wer würde am ehesten eine Beziehung per Sprachnachricht beenden?',
  'Wer bekommt auf Instagram die meisten Flirtnachrichten von Fremden?',
  'Wer hat bei einem Date schon mal einen leeren Akku vorgetäuscht, um früher zu gehen?',
  'Wer stalkt am ehesten nachts noch das Instagram vom Ex?',
  'Wer von euch hat schon mal Handschellen benutzt, und zwar nicht an Fasching?',
  'Wer würde am ehesten offen über einen eigenen Fetisch reden?',
  'Wer hatte am wahrscheinlichsten schon mal ein Sexspielzeug im Handgepäck?',
  'Wer würde am ehesten etwas mit der Person aus der WG anfangen?',
  'Wer hatte schon mal einen Knutschfleck, der sich nicht verstecken ließ?',
  'Wer würde am ehesten bei Love Island mitmachen?',
  'Wer hat am wahrscheinlichsten eine eigene Playlist nur fürs Schlafzimmer?',
  'Wer von euch hat den besten Anmachspruch auf Lager?',
  'Wer würde am ehesten einen Anmachspruch bringen, der komplett nach hinten losgeht?',
  'Wer würde am ehesten einen Sugar Daddy oder eine Sugar Mommy suchen?',
  'Wer hat am wahrscheinlichsten schon mal von jemandem aus dieser Runde geträumt, und zwar nicht jugendfrei?',
  'Wer würde am ehesten im Club in fünf Minuten eine Telefonnummer klarmachen?',
  'Wer hatte schon mal ein Date, das erst am nächsten Morgen vorbei war?',
  'Wer würde am ehesten mitten beim Sexting einschlafen?',
  'Bei wem würden sich die Nachbarn am ehesten über den Lärm im Schlafzimmer beschweren?',
  'Wer hat am wahrscheinlichsten schon mal beim Sex das Bett kaputt gemacht?',
  'Wer würde am ehesten auf einer Dating-App ein zehn Jahre altes Foto benutzen?',
  'Wer hatte schon mal ein Date mit einer Person, die mindestens zehn Jahre älter war?',
  'Wer würde am ehesten in einer Umkleidekabine rummachen?',
  'Wer hat in dieser Stadt die meisten Verflossenen?',
  'Wer würde am ehesten mal aus Neugier in einen Swingerclub gehen?',
  'Wer von euch hat beim Flaschendrehen schon mal mehr gemacht als nur geküsst?',
  'Wer hat am wahrscheinlichsten schon mal zwei Leute gleichzeitig gedatet, ohne dass sie voneinander wussten?',
  'Wer würde am ehesten versuchen, das ganze Kamasutra durchzuprobieren?',
  'Wer hatte schon mal Sex im Zelt auf einem Festival?',
  'Wer würde am ehesten nach einem Date der Gruppe eine Bewertung mit Punkten schicken?',
  'Wer ist am ehesten der Typ für Dirty Talk?',
  'Wer hat beim Flirten am wahrscheinlichsten schon mal den eigenen Namen vergessen?',
  'Wer würde am ehesten Rollenspiele im Schlafzimmer ausprobieren?',
  'Wer hat beim Küssen schon mal aus Versehen zu fest zugebissen?',
  'Wer würde am ehesten mit dem Ex von jemandem aus dem Freundeskreis knutschen?',
  'Wer wurde schon mal von den Eltern beim Rummachen erwischt?',
  'Wer ist am wahrscheinlichsten schon mal mit jemandem im Bett gelandet, nur weil die Person gut kochen konnte?',
  'Wer würde am ehesten nur wegen eines Hundes auf dem Profilbild nach rechts wischen?',
  'Wer von euch hat schon mal in der Sauna geflirtet?',
  'Wer ist am ehesten schon Mitglied im Mile High Club?',
  'Wer hat sich schon mal in einen One-Night-Stand verliebt?',
  'Wer würde am ehesten beim ersten Date die Rechnung bis auf den Cent genau aufteilen?',
  'Wer hat am wahrscheinlichsten schon mal ein Date nur wegen des kostenlosen Essens angenommen?',
  'Wer hat sich schon mal für ein Date einen gespielten Notfallanruf aus dem Freundeskreis bestellt?',
  'Wer würde am ehesten beim ersten Date so lange über den Ex reden, bis es unangenehm wird?',
  'Wer würde am ehesten ein Date unterbrechen, nur um den Spielstand im Fußball zu checken?',
  'Wer hat beim ersten Date am wahrscheinlichsten schon mal Essen auf das Outfit gekleckert?',
  'Wer schreibt am ehesten nach dem Date sofort eine Nachricht, noch bevor die Haustür zu ist?',
  'Wer würde am ehesten mitten auf einem Date einschlafen?',
  'Wer hatte schon mal ein Date, zu dem die andere Person ungefragt eine Begleitung mitgebracht hat?',
  'Wer hatte schon mal ein Date, das in echt ganz anders aussah als auf den Fotos?',
  'Wer würde am ehesten ein Date mit einer Präsentation über sich selbst beeindrucken wollen?',
  'Wer würde nach einem schlechten Date am ehesten trotzdem aus Höflichkeit ein zweites ausmachen?',
  'Wer swipt am ehesten aus Langeweile auf dem Klo?',
  'Wer hat schon mal auf einer Dating-App ein Familienmitglied entdeckt?',
  'Wer würde am ehesten ein Match mit einem selbstgeschriebenen Gedicht anschreiben?',
  'Wer hat schon mal ein Match im Supermarkt erkannt und sich hinter dem Regal versteckt?',
  'Wer hat am wahrscheinlichsten schon mal jemanden aus dieser Runde in einer Dating-App gesehen?',
  'Wer schreibt am ehesten nur "Hey" als erste Nachricht und wundert sich, dass keine Antwort kommt?',
  'Wer schickt am ehesten Screenshots aus Dating-Chats in den Gruppenchat?',
  'Wer hatte schon mal ein App-Date, das sich als Person aus der alten Schulklasse entpuppte?',
  'Wer von euch merkt am wenigsten, wenn jemand flirtet?',
  'Wer hat schon mal im Ausland mit Händen und Füßen geflirtet, weil keine gemeinsame Sprache da war?',
  'Wer würde am ehesten auf einem Elternabend flirten?',
  'Wer flirtet betrunken am peinlichsten?',
  'Wer hat am wahrscheinlichsten schon mal mit dem Paketdienst geflirtet?',
  'Wer von euch hat schon mal über LinkedIn geflirtet?',
  'Wer würde am ehesten einer fremden Person an der Bar einen Drink schicken lassen?',
  'Wer hat schon mal geflirtet, während der eigene Schatz im selben Raum war?',
  'Wer flirtet am ehesten mit einer Person, die eigentlich nur nach dem Weg gefragt hat?',
  'Wer hat am wahrscheinlichsten schon mal im Fahrstuhl eine Nummer bekommen?',
  'Wer küsst am wahrscheinlichsten mit zu viel Zunge?',
  'Wer hatte den peinlichsten ersten Kuss?',
  'Wer würde am ehesten an Silvester um Mitternacht eine fremde Person küssen?',
  'Wer hat sich beim Küssen schon mal mit Zahnspange oder Piercing verhakt?',
  'Wer würde am ehesten im Regen einen filmreifen Kuss inszenieren?',
  'Wer hat am wahrscheinlichsten schon mal mit Knoblauchatem geknutscht?',
  'Wer von euch hat schon mal wegen einer Wette jemanden geküsst?',
  'Wer hat schon mal jemanden geküsst und es noch in derselben Sekunde bereut?',
  'Wer würde am ehesten im Kino die ganze Zeit knutschen, statt den Film zu schauen?',
  'Wer hatte den ersten Kuss am spätesten?',
  'Wer hat am wahrscheinlichsten schon mal ganz oben im Riesenrad geknutscht?',
  'Wer küsst zum Abschied am ehesten auf den Mund, obwohl eine Umarmung gereicht hätte?',
  'Wer würde am ehesten Kussunterricht geben?',
  'Wer hat in einer einzigen Nacht die meisten Leute geküsst?',
  'Wer würde am ehesten bei der Kiss Cam im Stadion voll mitmachen?',
  'Wer hat am wahrscheinlichsten schon mal nach einem One-Night-Stand Frühstück gemacht?',
  'Wer hat schon mal einen One-Night-Stand im Urlaub gehabt?',
  'Wer ist schon mal nach einer Nacht in einer Wohnung aufgewacht und wusste nicht, in welchem Stadtteil?',
  'Wer hat am wahrscheinlichsten schon mal nach einem One-Night-Stand etwas Wichtiges liegen lassen?',
  'Wer hatte schon mal einen Walk of Shame am Sonntagmorgen?',
  'Wer würde nach einem One-Night-Stand am ehesten noch den Abwasch machen?',
  'Wer hat am wahrscheinlichsten schon mal einen One-Night-Stand später im Job wiedergetroffen?',
  'Wer würde am ehesten etwas mit jemandem aus der Nachbarschaft anfangen?',
  'Wer ist am ehesten der Typ für Freundschaft Plus?',
  'Wer hat am wahrscheinlichsten schon mal eine Affäre gehabt, die länger lief als manche Beziehung?',
  'Wer würde eine Freundschaft Plus am ehesten beenden, weil plötzlich Gefühle im Spiel sind?',
  'Wer würde am ehesten schon nach drei Wochen zusammenziehen?',
  'Wer hat am wahrscheinlichsten schon mal heimlich das Handy vom Schatz durchsucht?',
  'Wer von euch ist in einer Beziehung am eifersüchtigsten?',
  'Wer würde am ehesten einen Heiratsantrag vor großem Publikum machen?',
  'Wer hat schon mal Schluss gemacht und am nächsten Tag wieder angerufen?',
  'Wer würde sich am ehesten den Namen vom Schatz tätowieren lassen?',
  'Wer benutzt in Beziehungen die peinlichsten Kosenamen?',
  'Wer hat schon mal einen Streit im Bett beendet statt mit Worten?',
  'Wer ist nach einer Trennung am ehesten sofort in die nächste Beziehung gerutscht?',
  'Wer hat am wahrscheinlichsten noch Geschenke vom Ex im Schrank?',
  'Wer hat schon mal einen Ex zurückerobert?',
  'Wer von euch würde am ehesten jemanden daten, der zwanzig Jahre jünger ist?',
  'Wer verliebt sich am schnellsten?',
  'Wer würde beim ersten Treffen mit den Schwiegereltern am ehesten etwas völlig Unpassendes sagen?',
  'Wer würde am ehesten in Las Vegas spontan heiraten?',
  'Wer sagt am ehesten schon nach einer Woche "Ich liebe dich"?',
  'Wer führt am wahrscheinlichsten eine geheime Liste mit allen bisherigen Bettgeschichten?',
  'Wer würde am ehesten den Ex eines eigenen Geschwisters daten?',
  'Wer würde am ehesten auf einem Junggesellenabschied komplett über die Stränge schlagen?',
  'Wer würde am ehesten behaupten, das sei kein Flirten gewesen, sondern nur Freundlichkeit?',
  'Wer hat eine Promi-Freikarte, die in der Beziehung offiziell abgesprochen ist?',
  'Wer hatte schon mal ein Date mit einer Person, die sich später als vergeben herausstellte?',
  'Wer wird am ehesten eifersüchtig, wenn die eigene Begleitung mit der Bedienung lacht?',
  'Wer würde am ehesten Sex am Strand haben, obwohl danach überall Sand ist?',
  'Wer hatte schon mal Sex im Elternhaus, während die Eltern zuhause waren?',
  'Wer hat am wahrscheinlichsten schon mal beim Sex auf die Uhr geschaut?',
  'Wer hatte schon mal Sex unter der Dusche, der eher eine Rutschpartie war?',
  'Wer würde am ehesten einen Quickie in der Mittagspause einschieben?',
  'Wer hatte am wahrscheinlichsten schon mal Sex im Büro?',
  'Wer hat beim Sex am wahrscheinlichsten schon mal einen Lachanfall bekommen?',
  'Wer schläft nach dem Sex am ehesten sofort ein?',
  'Wer will nach dem Sex am ehesten sofort Pizza bestellen?',
  'Wer hatte schon mal Sex, obwohl der Zug in zehn Minuten abfuhr?',
  'Wer würde am ehesten mit einer neu gelernten Stellung angeben?',
  'Wer ist schon mal nachts zur Tankstelle gefahren, weil keine Kondome im Haus waren?',
  'Wer ist am ehesten der Typ für Morgensex?',
  'Wer würde am ehesten Sex auf der laufenden Waschmaschine ausprobieren?',
  'Wer hat im Bett am wahrscheinlichsten schon mal mehr gequatscht als gemacht?',
  'Wer würde am ehesten nach dem Sex auf der Smartwatch die verbrannten Kalorien checken?',
  'Wer würde am ehesten eigene Namen für Stellungen erfinden?',
  'Wer hatte am wahrscheinlichsten schon mal Sex auf dem Küchentisch?',
  'Wer hatte schon mal einen Muskelkater, der nicht vom Sport kam?',
  'Wer ist am wahrscheinlichsten schon mal beim Sex aus dem Bett gefallen?',
  'Wer hatte schon mal Sex, während das Haustier zugeschaut hat?',
  'Wer hatte am wahrscheinlichsten schon mal Sex mit Socken an?',
  'Wer würde am ehesten ein ganzes Wochenende komplett ohne Klamotten verbringen?',
  'Wer würde am ehesten Urlaub an einem FKK-Strand machen?',
  'Wer ist schon mal nachts nackt baden gegangen?',
  'Wer hat am wahrscheinlichsten Nacktfotos von sich auf dem Handy, die nie verschickt wurden?',
  'Wer wäre beim Strip Poker am ehesten als Erstes nackt?',
  'Wer würde am ehesten einen Striptease für den Schatz einstudieren?',
  'Wer hat am wahrscheinlichsten schon mal einen Lapdance bekommen?',
  'Wer hat die größte Sammlung an Sexspielzeug?',
  'Wer würde am ehesten Sexspielzeug als Wichtelgeschenk mitbringen?',
  'Wer hat am wahrscheinlichsten schon mal ein Sexspielzeug bestellt, das bei den Nachbarn abgegeben wurde?',
  'Wer würde am ehesten eine Augenbinde ins Spiel bringen?',
  'Wer hat die wildeste Fantasie, von der hier noch niemand weiß?',
  'Wer hat am wahrscheinlichsten schon mal unanständig von der Chefin oder vom Chef geträumt?',
  'Wer würde am ehesten im Schlafzimmer eine Uniform tragen?',
  'Wer steht am ehesten auf einen Klaps auf den Hintern?',
  'Wer würde am ehesten Fifty Shades of Grey als Anleitung benutzen?',
  'Wer übertreibt beim Sexting am ehesten mit Auberginen und Pfirsichen?',
  'Wer hat am wahrscheinlichsten schon mal Massageöl über die ganze Bettwäsche gekippt?',
  'Wer würde am ehesten Sprühsahne im Schlafzimmer einsetzen?',
  'Wer würde am ehesten eine Tantra-Massage buchen?',
  'Wer würde am ehesten ein Wochenende in einem Erotikhotel buchen?',
  'Wer steht am ehesten auf Fesselspiele?',
  'Wer würde sich am ehesten einen Spiegel über das Bett hängen?',
  'Wer würde am ehesten ein Spielzeug mit Fernsteuerung per App ausprobieren?',
  'Wer würde im Bett am ehesten das Kommando übernehmen?',
  'Wer lässt sich im Bett am liebsten verführen, statt selbst aktiv zu werden?',
  'Wer würde am ehesten Dessous kaufen, die mehr kosten als ein Wocheneinkauf?',
  'Wer trägt heute am ehesten schon passende Unterwäsche, nur für alle Fälle?',
  'Wer hat am wahrscheinlichsten schon mal Unterwäsche bei jemandem vergessen?',
  'Wer würde am ehesten ein Safeword vorschlagen, das komplett unsexy ist?',
  'Wer schaut am ehesten Erotikfilme angeblich nur wegen der Handlung?',
  'Wer hat am wahrscheinlichsten den peinlichsten Browserverlauf?',
  'Wer wird am ehesten rot, wenn beim Fernsehen mit den Eltern eine Sexszene kommt?',
  'Wer würde am ehesten ein OnlyFans-Konto aufmachen?',
  'Wer würde am ehesten an Halloween ein Kostüm wählen, das fürs Schlafzimmer gedacht ist?',
  'Wer würde am ehesten auf dem Arbeitslaptop sexten?',
  'Wer hat am wahrscheinlichsten schon mal Telefonsex gehabt?',
  'Wer hat am wahrscheinlichsten schon mal beim Sex gepupst?',
  'Wer hat am wahrscheinlichsten schon mal mitten im Vorspiel Hunger bekommen?',
  'Wer wurde schon mal beim Sex von der WG gehört und am nächsten Morgen ausgelacht?',
  'Wer ist am wahrscheinlichsten schon mal an einem BH oder Gürtel verzweifelt?',
  'Wer ist schon mal beim Ausziehen umgekippt, weil die Hose festhing?',
  'Wer hat am wahrscheinlichsten schon mal beim Sex einen Anruf angenommen?',
  'Wer hat schon mal beim Rummachen eine Brille kaputt gemacht?',
  'Wer hatte schon mal einen Kondom-Notfall, über den heute alle lachen?',
  'Wer ist schon mal beim Rummachen auf der Couch eingeschlafen?',
  'Wer wollte am wahrscheinlichsten schon mal verführerisch sein und ist dabei gestolpert?',
  'Wer wurde schon mal von den Nachbarn durchs Fenster gesehen, und zwar in einer eindeutigen Situation?',
  'Wer hat am wahrscheinlichsten schon mal aus Versehen eine sehr eindeutige Sprachnachricht verschickt?',
  'Wer wurde schon mal beim Rummachen von der Polizei angesprochen?',
  'Wer hat beim Sex am wahrscheinlichsten schon mal ein Kompliment gemacht, das völlig falsch rüberkam?',
  'Wer hat im Bett schon mal Geräusche gemacht, für die es heute noch peinlich ist?',
  'Wer hat beim Sex am wahrscheinlichsten schon mal eine Nachricht von Mama auf dem Sperrbildschirm gesehen?',
  'Wer hat die Unterwäsche am ehesten verkehrt herum an und merkt es erst beim Ausziehen?',
  'Wer verliebt sich am ehesten immer wieder in denselben Typ Mensch?',
  'Wer wird bei einer tiefen Stimme am ehesten schwach?',
  'Wer würde am ehesten einer fremden Person wegen ihres Parfüms hinterherlaufen?',
  'Wer hat am wahrscheinlichsten einen heimlichen Crush auf jemanden aus dem Fitnessstudio?',
  'Wer hat die seltsamsten Red Flags beim Dating?',
  'Wer ignoriert am ehesten alle Red Flags, solange die Person gut aussieht?',
  'Wer hat beim Dating am wahrscheinlichsten selbst die meisten Red Flags?',
  'Wer hatte am wahrscheinlichsten schon mal einen Crush auf jemanden in dieser Runde?',
  'Wer aus dieser Runde wäre das beste Date?',
  'Wer aus dieser Runde wäre im Bett am ehesten die größte Überraschung?',
  'Wer in dieser Runde hat die meisten heimlichen Verehrer?',
  'Wer spielt am ehesten Amor für den ganzen Freundeskreis?',
  'Wer hat am wahrscheinlichsten schon mal mit jemandem aus dem Freundeskreis geschlafen und es geheim gehalten?',
  'Wer würde am ehesten heute Abend mit einer völlig fremden Person nach Hause gehen?',
  'Wer kennt die meisten Bettgeschichten der anderen hier?',
  'Wer kann am schlechtesten ein Geheimnis über das Liebesleben anderer für sich behalten?',
  'Wer erzählt am ehesten viel zu viele Details über das eigene Sexleben?',
  'Wer wird beim Thema Sex am ehesten sofort rot?',
  'Wer hat am wahrscheinlichsten das aktivste Liebesleben in dieser Runde?',
  'Wer würde am ehesten ein Buch über das eigene Liebesleben schreiben?',
  'Wer würde am ehesten bei Temptation Island die eigene Beziehung testen?',
  'Wer hört bei Liebeskummer am ehesten tagelang traurige Lieder?',
  'Wer hat am wahrscheinlichsten schon mal betrunken den Ex angerufen?',
  'Wer würde am ehesten einen Crush jahrelang verheimlichen?',
  'Wer hat schon mal einen Korb bekommen, der richtig wehgetan hat?',
  'Wer verteilt Körbe am ehesten auf die charmanteste Art?',
  'Wer hat am wahrscheinlichsten schon mal jemandem eine falsche Nummer gegeben?',
  'Wer würde am ehesten eine Kontaktanzeige in der Zeitung aufgeben?',
  'Wer würde am ehesten auf einer Singleparty mit Ampelarmband auftauchen?',
  'Wer hat am wahrscheinlichsten schon mal auf einem Junggesellenabschied eine fremde Person geküsst?',
  'Wer übertreibt am Valentinstag am ehesten mit Rosen und Kerzen?',
  'Wer würde auf der Hochzeit eines Ex am ehesten mit den Gästen flirten?',
  'Wer hat am wahrscheinlichsten schon mal im Urlaub die Nummer der Reiseleitung bekommen?',
  'Wer würde am ehesten im Skiurlaub mit der Skilehrerin oder dem Skilehrer anbandeln?',
  'Wer würde am ehesten offen sagen, was im Bett gefällt?',
  'Wer spricht am ehesten direkt nach dem Sex über Gefühle?',
  'Wer würde nach dem ersten Mal am ehesten fragen, wie es war?',
  'Wer besteht am ehesten jede Nacht auf Löffelchen?',
  'Wer klaut im Bett am ehesten die ganze Decke?',
  'Wer würde beim ersten Übernachten am ehesten schon die eigene Zahnbürste dalassen?',
  'Wer lässt am ehesten absichtlich etwas beim Date liegen, um einen Grund für ein Wiedersehen zu haben?',
  'Wer hat am wahrscheinlichsten schon mal das Shirt eines Dates behalten?',
  'Wer hat am ehesten immer ein Kondom im Portemonnaie?',
  'Wer hat am wahrscheinlichsten schon mal vor den Eltern ein Kondom fallen lassen?',
  'Wer würde beim Kondomkauf in der Apotheke am ehesten rot werden?',
  'Wer würde ein heißes Date am ehesten in Jogginghose empfangen?',
  'Wer würde auf einer Party am ehesten im Badezimmer rummachen?',
  'Wer hat am wahrscheinlichsten schon mal im Treppenhaus geknutscht?',
  'Wer würde beim Après-Ski am ehesten jemanden abschleppen?',
  'Wer hatte schon mal einen Crush auf ein Elternteil von jemandem aus dem Freundeskreis?',
  'Wer verschickt am ehesten eine Sprachnachricht mit Schlafzimmerstimme?',
  'Wer tippt am ehesten eine Nachricht an den Crush und löscht sie dann doch wieder?',
  'Wer schaut am ehesten zwanzigmal nach, ob der Crush die Story gesehen hat?',
  'Wer hat am wahrscheinlichsten schon mal eine Story nur für eine einzige Person gepostet?',
  'Wer würde am ehesten eine Thirst Trap posten?',
  'Wer hat am wahrscheinlichsten schon mal jemanden blockiert und eine Woche später wieder entblockt?',
  'Wer würde über ein Date am ehesten eine Liste mit Pro und Contra schreiben?',
  'Wer hat am wahrscheinlichsten schon mal eine Beziehung vor dem Freundeskreis geheim gehalten?',
  'Wer hat am ehesten eine Urlaubsbekanntschaft später zuhause besucht?',
  'Wer verlässt eine Party am ehesten ohne Abschied, aber mit Begleitung?',
  'Wer hat das beste Pokerface, wenn es um das eigene Liebesleben geht?',
  'Wer würde bei Wahrheit oder Pflicht am ehesten immer Pflicht wählen, nur um jemanden zu küssen?',
  'Wer müsste bei "Ich hab noch nie" am ehesten am meisten trinken?',
  'Wer würde am ehesten ein Erotik-Kartenspiel zum Spieleabend mitbringen?',
  'Wer speichert Dates am ehesten mit Spitznamen wie "Bar vom Freitag" im Handy?',
  'Wer bietet am ehesten eine Massage an, die nicht nur eine Massage bleibt?',
  'Wer schläft am ehesten nackt?',
  'Wer würde dem Lieferdienst am ehesten aus Versehen in Unterwäsche die Tür öffnen?',
  'Wer hat am wahrscheinlichsten einen Crush auf die Person, die jeden Morgen den Kaffee macht?',
  'Wer würde am ehesten ein Blind Date von den Eltern arrangieren lassen?',
  'Wer kommt am ehesten als Wingman mit und schleppt am Ende selbst jemanden ab?',
];
