export const sexualQuestions: string[] = [
  'Wer hatte schon mal ein Date mit zwei Leuten am selben Tag?',
  'Wer würde am ehesten beim ersten Date schon über Hochzeit reden?',
  'Wer von euch hat die meisten Matches auf Tinder?',
  'Wer hat am wahrscheinlichsten schon mal im Bett den falschen Namen gesagt?',
  'Wer würde am ehesten wieder mit dem Ex im Bett landen?',
  'Wer kann sich an den Namen eines One-Night-Stands nicht mehr erinnern?',
  'Wer von euch flirtet am meisten, ohne es selbst zu merken?',
  'Wer würde am ehesten heute Abend jemanden aus dieser Runde küssen?',
  'Wer hat am wahrscheinlichsten schon mal im Auto rumgemacht?',
  'Wer hatte schon mal etwas mit der besten Freundin oder dem besten Freund vom Ex?',
  'Wer würde am ehesten eine offene Beziehung ausprobieren?',
  'Wer schickt am ehesten um drei Uhr nachts ein "Bist du noch wach?"?',
  'Wer von euch hatte schon mal Sex an einem öffentlichen Ort?',
  'Wer würde am ehesten auf einer Hochzeit mit einem Gast für eine Stunde verschwinden?',
  'Wer hat am wahrscheinlichsten schon mal ein Tinder Date geghostet?',
  'Wer würde am ehesten ein Date nach zehn Minuten abbrechen?',
  'Wer hat beim Küssen schon mal so gelacht, dass die Stimmung komplett weg war?',
  'Wessen Geschmack bei Dates ist hier am fragwürdigsten?',
  'Wer würde am ehesten im Fitnessstudio flirten, statt zu trainieren?',
  'Wer löscht Tinder am häufigsten und lädt es eine Woche später wieder runter?',
  'Wer hatte früher heimlich einen Crush auf eine Lehrkraft?',
  'Wer würde am ehesten einen Dreier ausprobieren?',
  'Wer von euch ist am ehesten der Typ für Sex beim ersten Date?',
  'Wer hat sich am wahrscheinlichsten schon mal morgens heimlich aus der Wohnung eines Dates geschlichen?',
  'Wer würde am ehesten aus Versehen Nudes an die falsche Person schicken?',
  'Wer hatte schon mal eine Urlaubsromanze, von der niemand wissen durfte?',
  'Wer flirtet am ehesten mit dem Barpersonal, um Getränke umsonst zu bekommen?',
  'Wer würde am ehesten auf einer Party mit zwei verschiedenen Leuten knutschen?',
  'Wer von euch hat die peinlichste Sexgeschichte?',
  'Wer hat am wahrscheinlichsten schon mal beim Sex einen Krampf bekommen?',
  'Wer würde am ehesten ein Date schon beim zweiten Treffen den Eltern vorstellen?',
  'Wer hat schon mal jemanden geküsst, nur um eine andere Person eifersüchtig zu machen?',
  'Wer würde am ehesten mit der ganzen Gruppe in einen Sexshop gehen?',
  'Wer hat die längste Flaute im Bett hinter sich?',
  'Wer von euch würde bei einem Blind Date am ehesten durch die Hintertür verschwinden?',
  'Wer hat am wahrscheinlichsten schon mal mit jemandem von der Arbeit rumgemacht?',
  'Wer würde am ehesten eine Beziehung per Sprachnachricht beenden?',
  'Wer bekommt auf Instagram die meisten Flirtnachrichten von Fremden?',
  'Wer hat bei einem Date schon mal einen leeren Akku vorgetäuscht, um früher zu gehen?',
  'Wer würde am ehesten für ein Date in eine andere Stadt fliegen?',
  'Wer stalkt am ehesten nachts noch das Instagram vom Ex?',
  'Wer von euch hat schon mal Handschellen benutzt, und zwar nicht an Fasching?',
  'Wer würde am ehesten offen über einen eigenen Fetisch reden?',
  'Wer hatte am wahrscheinlichsten schon mal ein Sexspielzeug im Handgepäck?',
  'Wer würde am ehesten etwas mit der Person aus der WG anfangen?',
  'Wer hatte schon mal einen Knutschfleck, der sich nicht verstecken ließ?',
  'Wer würde am ehesten bei Love Island mitmachen?',
  'Wer hat am wahrscheinlichsten eine eigene Playlist nur fürs Schlafzimmer?',
  'Wer von euch hat den besten Anmachspruch auf Lager?',
  'Wer würde am ehesten einen Anmachspruch bringen, der komplett nach hinten losgeht?',
  'Wer hat schon mal jemanden auf einer Hochzeit abgeschleppt?',
  'Wer würde am ehesten einen Sugar Daddy oder eine Sugar Mommy suchen?',
  'Wer hat am wahrscheinlichsten schon mal von jemandem aus dieser Runde geträumt, und zwar nicht jugendfrei?',
  'Wer würde am ehesten im Club in fünf Minuten eine Telefonnummer klarmachen?',
  'Wer hatte schon mal ein Date, das erst am nächsten Morgen vorbei war?',
  'Wer würde am ehesten mitten beim Sexting einschlafen?',
  'Bei wem würden sich die Nachbarn am ehesten über den Lärm im Schlafzimmer beschweren?',
  'Wer hat am wahrscheinlichsten schon mal beim Sex das Bett kaputt gemacht?',
  'Wer würde am ehesten auf einer Dating App ein zehn Jahre altes Foto benutzen?',
  'Wer hatte schon mal ein Date mit einer Person, die mindestens zehn Jahre älter war?',
  'Wer würde am ehesten in einer Umkleidekabine rummachen?',
  'Wer hat in dieser Stadt die meisten Verflossenen?',
  'Wer würde am ehesten mal aus Neugier in einen Swingerclub gehen?',
  'Wer von euch hat beim Flaschendrehen schon mal mehr gemacht als nur geküsst?',
  'Wer hat am wahrscheinlichsten schon mal zwei Leute gleichzeitig gedatet, ohne dass sie voneinander wussten?',
  'Wer würde am ehesten versuchen, das ganze Kamasutra durchzuprobieren?',
  'Wer hatte schon mal Sex im Zelt auf einem Festival?',
  'Wer würde am ehesten nach einem Date der Gruppe eine Bewertung mit Punkten schicken?',
  'Wer ist am ehesten der Typ für Dirty Talk?',
  'Wer hat beim Flirten am wahrscheinlichsten schon mal den eigenen Namen vergessen?',
  'Wer würde am ehesten Rollenspiele im Schlafzimmer ausprobieren?',
  'Wer hat beim Küssen schon mal aus Versehen zu fest zugebissen?',
  'Wer würde am ehesten mit dem Ex von jemandem aus dem Freundeskreis knutschen?',
  'Wer wurde schon mal von den Eltern beim Rummachen erwischt?',
  'Wer würde am ehesten schon beim dritten Date Unterwäsche verschenken?',
  'Wer ist am wahrscheinlichsten schon mal mit jemandem im Bett gelandet, nur weil die Person gut kochen konnte?',
  'Wer würde am ehesten nur wegen eines Hundes auf dem Profilbild nach rechts wischen?',
  'Wer von euch hat schon mal in der Sauna geflirtet?',
  'Wer ist am ehesten schon Mitglied im Mile High Club?',
  'Wer hat sich schon mal in einen One-Night-Stand verliebt?',
];
