export const chaosTasksEn: string[] = [
  '{{player}} is the Question Master for the next 5 cards: anyone who answers one of their questions drinks 1 sip.',
  '{{player}} is the Thumb Master for the next 6 cards: when they put a thumb on the table, everyone has to follow and the last one drinks 2 sips.',
  '{{player}} and {{player}} are drinking buddies for the next 5 cards: when one drinks, the other drinks too.',
  '{{player}} is the butler for the next 4 cards and has to top up everyone\'s drinks. Anyone who pours their own drinks 2 sips.',
  '{{player}} is the mirror image of {{player}} for the next 5 cards and copies every move. If the mirror misses a move, it drinks 1 sip.',
  '{{player}} is the lawmaker for the next 6 cards and gets to make a new rule. Anyone who breaks it drinks 2 sips.',
  '{{player}} is the Nose Master for the next 5 cards: when they touch their nose, everyone has to follow and the last one drinks 2 sips.',
  '{{player}} is the referee for the next 4 cards and settles every argument by deciding who drinks 2 sips.',
  '{{player}} is the court jester for the next 5 cards: anyone who doesn\'t laugh at their jokes drinks 1 sip.',
  '{{player}} is the witness for the next 5 cards and has to repeat every new card out loud. Every missed repeat costs 2 sips.',
  '{{player}} is the royal taster for the next 3 cards: before anyone else drinks, they take 1 sip first.',
  '{{player}} is the lucky one for the next 5 cards: whenever they have to drink, they can pass 1 of those sips to someone else.',
  '{{player}} is the bodyguard of {{player}} for the next 4 cards and takes every sip their client would have to drink.',
  '{{player}} is the hype person for the next 5 cards: after every card they shout "Cheers!" and everyone drinks 1 sip.',
  '{{player}} is the news anchor for the next 5 cards and has to read every new card like the evening news. Anyone who laughs drinks 1 sip.',
  '{{player}} is the word guard for the next 6 cards and picks a forbidden word. Anyone who says it drinks 2 sips.',
  '{{player}} is the master of ceremonies for the next 5 cards and has to announce every sip at the table with "Cheers to that!" Every missed announcement costs 1 sip.',
  '{{player}} is a secret agent for the next 4 cards and can only whisper. If they speak out loud, they drink 2 sips.',
  '{{player}} is a robot for the next 5 cards and only speaks in robot voice. Every slip costs 1 sip.',
  '{{player}} is the conductor for the next 5 cards: when they raise a hand, everyone hums until it goes down again. Anyone who doesn\'t hum drinks 1 sip.',
  '{{player}} is the mayor for the next 6 cards: anyone who doesn\'t address them as "Madam Mayor" or "Mr. Mayor" drinks 1 sip.',
  '{{player}} is the photographer for the next 5 cards: when they shout "Photo!", everyone has to strike a pose and the last to freeze drinks 1 sip.',
  '{{player}} is the waiter for the next 5 cards and has to accept every request at the table with a bow. No bow means they drink 1 sip.',
  '{{player}} is the lie detector for the next 4 cards: after any answer at the table they can shout "Lie!" and the accused drinks 1 sip.',
  '{{player}} is the bell ringer for the next 5 cards: when they knock twice on the table, everyone drinks 1 sip. This works 3 times at most.',
  '{{player}} is the sports commentator for the next 5 cards and commentates every sip at the table. If a sip goes uncommented, the commentator drinks 1 sip.',
  '{{player}} is a pirate for the next 5 cards and has to end every sentence with "Arrr". Every forgotten pirate growl costs 1 sip.',
  '{{player}} is the Keeper of the Glasses for the next 6 cards: nobody can put their glass down without looking at them. Anyone who forgets drinks 1 sip.',
  '{{player}} is the narrator for the next 5 cards and sums up what just happened after every card in one sentence, like a documentary. Every forgotten summary costs 1 sip.',
  '{{player}} is a mime for the next 4 cards and can only answer with gestures. Every spoken word costs 1 sip.',
  '{{player}} is the weatherman for the next 5 cards and has to forecast tomorrow\'s weather before each of their own sips. No forecast means they drink double.',
  '{{player}} is the Toast Master for the next 5 cards and has to make a new toast before each of their own sips. A repeat costs 2 sips.',
  '{{player}} is the manners officer for the next 5 cards: anyone caught asking for something without saying "please" drinks 1 sip.',
  '{{player}} is the sheriff for the next 6 cards: when they shout "Hands up!", everyone raises their hands and the last one drinks 2 sips.',
  '{{player}} is the teacher for the next 5 cards: anyone who wants to speak has to raise their hand. Anyone who just blurts out drinks 1 sip.',
  '{{player}} is the wizard for the next 5 cards and can magic away 1 sip per card. The neighbor on their left drinks it instead.',
  '{{player}} is the DJ for the next 4 cards and hums a song after every card. Anyone who can\'t guess it drinks 1 sip.',
  '{{player}} is the parrot of {{player}} for the next 5 cards and repeats every sentence their partner says. For every missed sentence the parrot drinks 1 sip.',
  '{{player}} is invisible for the next 5 cards: anyone who talks to them or looks at them drinks 1 sip.',
  '{{player}} is the boss for the next 5 cards and can shout "Overtime!" twice. Each time, everyone else drinks 2 sips.',
  '{{player}} is the number guard for the next 5 cards: anyone who says a number out loud drinks 1 sip.',
  '{{player}} is the lifeguard for the next 4 cards: when they whistle, everyone has to do swimming strokes with their arms. The last one drinks 1 sip.',
  '{{player}} is an opera star for the next 5 cards and can only speak by singing. Every normally spoken sentence costs 1 sip.',
  '{{player}} is His or Her Majesty of the table for the next 6 cards: anyone who drinks without first saying "Cheers, Your Majesty" drinks 1 extra sip.',
  '{{player}} can only speak in questions for the next 5 cards. Every sentence that doesn\'t end in a question mark costs 1 sip.',
  '{{player}} is the detective for the next 5 cards and can accuse someone once of secretly skipping a drink. If it\'s true, the accused drinks 3 sips, otherwise the detective drinks 2.',
  '{{player}} is the janitor for the next 4 cards: anyone who spills something on the table drinks 2 sips and has to apologize to them.',
  '{{player}} is the lucky charm for the next 5 cards: anyone who taps them before drinking only has to drink half.',
  '{{player}} is the tax collector for the next 6 cards: every time someone gives out 2 or more sips, they get to give out 1 extra sip.',
  '{{player}} is the translator for {{player}} for the next 5 cards: the second player only speaks a made up language and the translator has to translate everything. Whoever gives up drinks 2 sips.',
  '{{player}} is the guardian angel for the next 5 cards and can take over one sip from someone once. The person who gets saved says thank you out loud or drinks double.',
  '{{player}} is the Keeper of Silence for the next 4 cards: when they say "Shhh!", there are 10 seconds of silence. Anyone who talks drinks 1 sip.',
  '{{player}} is the Applause Master for the next 5 cards: when they clap, everyone claps along. The last one to join in drinks 1 sip.',
  '{{player}} is the guest of honor for the next 5 cards: anyone who drinks has to clink glasses with them first. Anyone who forgets drinks 1 extra sip.',
  '{{player}} is the voice actor for {{player}} for the next 5 cards: the second player only moves their lips while the first one speaks. Whoever breaks character drinks 2 sips.',
  '{{player}} is the compliment police for the next 5 cards: anyone who drinks has to compliment someone first. Anyone who forgets drinks 1 extra sip.',
  '{{player}} is the Riddle Master for the next 6 cards and asks a short riddle before every card. Whoever shouts the answer first gives out 1 sip.',
  '{{player}}, {{player}} and {{player}} are a drinking team for the next 4 cards: when one drinks, all three drink.',
  '{{player}} picks a drinking buddy for the next 6 cards. When one of them drinks, the other drinks too.',
  '{{player}} and {{player}} are rivals for the next 5 cards: when one of them drinks, the other gets 1 extra sip.',
  '{{player}} and {{player}} are twins for the next 5 cards and have to answer every question at the same time. If the answers are different, both drink 1 sip.',
  '{{player}} and {{player}} are linked at the elbows for the next 4 cards and can only drink together. Whoever lets go drinks 2 sips.',
  '{{player}} and {{player}} swap names for the next 5 cards. Anyone who uses the old name drinks 1 sip.',
  '{{player}} and {{player}} swap seats right now and play each other for the next 5 cards. Whoever breaks character drinks 2 sips.',
  '{{player}} and {{player}} are an old married couple for the next 6 cards and only call each other "darling". Every forgotten "darling" costs 1 sip.',
  '{{player}} and {{player}} are archenemies for the next 5 cards and can only address each other as "Sir" or "Madam". Every slip costs 1 sip.',
  '{{player}} and {{player}} stare at each other seriously for 3 seconds before every card for the next 5 cards. Whoever laughs first drinks 1 sip.',
  '{{player}} drinks 1 sip every time {{player}} laughs for the next 5 cards.',
  '{{player}} is linked to the neighbor on their left for the next 5 cards: when one drinks, the other drinks too.',
  'Everyone is linked to the neighbor on their right for the next 3 cards: whoever drinks takes their neighbor along. The chain only goes around the table once.',
  'For the next 5 cards the word "drink" is forbidden. Anyone who says it drinks 2 sips.',
  'For the next 6 cards the word "yes" is forbidden. Anyone who says it drinks 1 sip.',
  'For the next 5 cards the word "no" is forbidden. Anyone who says it drinks 1 sip.',
  'For the next 5 cards all first names are forbidden. Anyone who calls someone by name drinks 2 sips.',
  'For the next 4 cards the word "you" is forbidden. Anyone who says it drinks 1 sip.',
  '{{player}} can\'t use the word "and" for the next 5 cards. Every "and" costs 1 sip.',
  'For the next 5 cards all swear words are forbidden. Anyone who curses drinks 2 sips.',
  'For the next 6 cards a sip is called a "blub". Anyone who still says "sip" drinks 1 blub.',
  'For the next 5 cards nobody can say "okay". Anyone who does drinks 1 sip.',
  'For the next 5 cards the word "phone" is forbidden. Anyone who says it drinks 2 sips.',
  'For the next 4 cards nobody can say the word "like". Every "like" costs 1 sip.',
  '{{player}} secretly picks a forbidden word and keeps it to themselves. Anyone who says it in the next 5 cards drinks 2 sips.',
  'For the next 5 cards the word "cheers" is forbidden. Anyone clinking glasses says "bottoms up" or drinks 1 extra sip.',
  'For the next 5 cards the words "left" and "right" are forbidden. Anyone who says one of them drinks 1 sip.',
  'For the next 5 cards nobody can say "uh" or "um". Every hesitation costs 1 sip.',
  'For the next 4 cards all words starting with "S" are forbidden. Anyone who says one drinks 1 sip.',
  'For the next 5 cards the word "card" is forbidden. Anyone who says it drinks 1 sip.',
  'For the next 5 cards water is called "magic juice". Anyone who says "water" drinks 1 sip.',
  'For the next 6 cards every glass is called a "trophy". Anyone who says "glass" drinks 1 sip.',
  'For the next 5 cards the table is called "the island". Anyone who says "table" drinks 1 sip.',
  'For the next 5 cards everyone has to shout "To the Queen!" before drinking. Anyone who forgets drinks 1 extra sip.',
  'For the next 6 cards everyone has to say "Ahhh, delicious!" after drinking. Anyone who forgets drinks again.',
  'For the next 4 cards everyone has to count to 3 out loud before drinking. Anyone who forgets drinks double.',
  'For the next 5 cards everyone has to end their sentences with "ladies and gentlemen". Anyone who forgets drinks 1 sip.',
  'For the next 5 cards everyone has to say "No regrets!" before drinking. Anyone who forgets drinks 1 extra sip.',
  'For the next 6 cards everyone has to draw a circle in the air with their glass before drinking. Anyone who forgets drinks 1 extra sip.',
  'For the next 5 cards everyone has to make an animal sound nobody at the table has made yet before drinking. A repeat costs 1 extra sip.',
  'For the next 5 cards everyone has to give a quick salute after drinking. Anyone who forgets drinks 1 sip.',
  'For the next 4 cards everyone has to make a quick toast to the neighbor on their left before drinking. Anyone who forgets drinks double.',
  'For the next 5 cards everyone has to stand up and sit back down before drinking. Anyone who stays seated drinks 1 extra sip.',
  'For the next 5 cards everyone has to stick out their pinky while drinking. Anyone who forgets drinks 1 extra sip.',
  'For the next 6 cards everyone has to whisper "Thank you, glass" after drinking. Anyone who forgets drinks 1 sip.',
  'For the next 5 cards you can only drink with your left hand. Anyone who drinks with their right drinks 2 sips.',
  '{{player}} can only drink with their right hand for the next 6 cards, everyone else only with their left. Every mistake costs 1 sip.',
  '{{player}} and {{player}} hand each other their glasses for the next 3 cards and can\'t touch their own. Whoever does drinks 2 sips.',
  'For the next 5 cards everyone has to hold their glass with both hands like a precious trophy. Anyone who drinks one handed drinks 1 extra sip.',
  '{{player}} can only drink with crossed arms for the next 4 cards. Every mistake costs 1 sip.',
  'For the next 5 cards everyone has to keep one hand on their head while drinking. Anyone who forgets drinks 1 extra sip.',
  '{{player}} can\'t touch their own glass for the next 4 cards, so {{player}} has to hand it over for every drink. Whoever cheats drinks 2 sips.',
  'For the next 5 cards nobody can point at anyone. Anyone who does drinks 2 sips.',
  'For the next 4 cards all elbows stay off the table. Anyone who gets caught drinks 1 sip.',
  'For the next 5 cards: anyone who touches their face drinks 1 sip.',
  '{{player}} speaks with a French accent for the next 5 cards. Every slip costs 1 sip.',
  'Everyone talks like a Wild West cowboy for the next 4 cards. Anyone who talks normally drinks 1 sip.',
  '{{player}} speaks in an accent of their choice for the next 5 cards. If they slip back into their normal voice, they drink 1 sip.',
  '{{player}} has to speak in rhymes for the next 5 cards. Every sentence that doesn\'t rhyme costs 1 sip.',
  'For the next 4 cards everyone talks about themselves in the third person. Anyone who says "I" drinks 1 sip.',
  '{{player}} starts every sentence with "Once upon a time" for the next 5 cards. Every forgotten fairy tale opener costs 1 sip.',
  '{{player}} speaks in a really high voice for the next 5 cards. Every normal sentence costs 1 sip.',
  '{{player}} speaks extremely slowly for the next 4 cards, like their battery is dying. Anyone who laughs at it drinks 1 sip.',
  'Everyone has to whisper for the next 5 cards. Anyone who speaks out loud drinks 1 sip.',
  '{{player}} talks like a radio ad announcer for the next 5 cards. Every normal sentence costs 1 sip.',
  '{{player}} has to end every sentence with a laugh for the next 5 cards. No laugh means 1 sip.',
  '{{player}} talks like a GPS for the next 4 cards. Every normal sentence costs 1 sip.',
  '{{player}} can only speak in sentences of 3 words or fewer for the next 5 cards. Every longer sentence costs 1 sip.',
  '{{player}} talks like an overexcited game show host for the next 4 cards. Every calm sentence costs 1 sip.',
  '{{player}} talks like a ghost for the next 5 cards and ends every sentence with "Wooooo". Every forgotten ghost wail costs 1 sip.',
  '{{player}} uses the royal "we" for the next 5 cards, like "We desire a drink". Every "I" costs 1 sip.',
  '{{player}} talks like a Viking for the next 4 cards and gently pounds the table once after every sentence. Every forgotten pound costs 1 sip.',
  'Everyone moves one seat to the left right now. The last one seated drinks 2 sips.',
  '{{player}} and {{player}} swap seats right now. Whoever takes longer drinks 1 sip.',
  'Everyone stands up and finds a new seat. The last one seated, or anyone who ends up in their old seat, drinks 2 sips.',
  '{{player}} can make any two players swap seats. Both drink 1 sip to welcome themselves to their new seat.',
  'The two youngest players at the table swap seats right now and drink 1 sip to their new spot.',
  'The player with the fullest glass swaps seats with the player with the emptiest glass. Both drink 1 sip.',
  '{{player}} is crowned emperor and, for the next 5 cards, picks a subject after every card who drinks 1 sip.',
  'All rules are cancelled. To celebrate, everyone drinks 1 sip.',
  'All roles are cancelled. Anyone who had a role until now drinks 1 farewell sip.',
  '{{player}} can cancel one active rule. If there are no rules right now, they drink 2 sips.',
  'All forbidden words are allowed again. To celebrate, everyone shouts their favorite word and drinks 1 sip.',
  'All drinking buddies are split up. Anyone who had a buddy drinks a farewell sip.',
  '{{player}} can extend one active rule by 3 cards or end it right now, and then drinks 1 sip.',
  'The most recent rule gets tougher: from now on every violation costs 2 more sips.',
  'All active rules are cancelled except one. {{player}} decides which one stays and drinks 1 sip for it.',
  'Anyone who currently has a role passes it to the neighbor on their left. The new role holder drinks 1 sip.',
  'Role swap: everyone who currently has a role swaps it with each other. If there\'s only one role, it goes to {{player}}.',
  '{{player}} can buy their way out of one active rule or role by drinking 3 sips.',
  'Amnesty: anyone who has broken a rule tonight can now give out 1 sip.',
  'All curses are broken. Anyone who was cursed can give out 2 sips.',
  'Curse: {{player}} swaps "yes" and "no" for the next 5 cards. Every mistake costs 1 sip.',
  'Curse: {{player}} can\'t smile for the next 5 cards. Every smile costs 1 sip.',
  'Curse: for the next 4 cards {{player}} has to shout "Who dares disturb me?" in outrage whenever anyone at the table laughs. Every time they forget costs 1 sip.',
  'Curse: {{player}} can\'t answer questions for the next 5 cards and can only respond with another question. Every real answer costs 1 sip.',
  'Curse: {{player}} has forgotten everyone\'s name for the next 5 cards and calls everyone "buddy". Every name they say costs 1 sip.',
  'Curse: for the next 4 cards {{player}} has to agree with everything said at the table by saying "Exactly!" Every time they forget costs 1 sip.',
  'Curse: {{player}} turns into a cat for the next 5 cards and can only answer with "Meow". Every real word costs 1 sip.',
  'Curse: {{player}} has the Medusa stare for the next 5 cards. Anyone they stare at freezes for 5 seconds or drinks 1 sip.',
  'Curse: {{player}} has the hiccups for the next 5 cards and has to say "hic" after every sentence. Every forgotten hic costs 1 sip.',
  'Curse: every time {{player}} laughs in the next 5 cards, the neighbor on their left drinks 1 sip.',
  'Curse: {{player}} is a vampire for the next 4 cards and only drinks behind a raised arm, like behind a cape. Forgetting costs 1 extra sip.',
  'Curse: {{player}} has to start every sentence with "Unfortunately" for the next 5 cards. Every sentence without it costs 1 sip.',
  'Curse: {{player}} is a bad luck magnet for the next 5 cards. Every time someone gives out sips, they get 1 extra.',
  'Curse: for the next 4 cards {{player}} has to laugh way too loudly at every joke at the table. Every missing laugh costs 1 sip.',
  'Curse: {{player}} is a chicken for the next 5 cards and has to cluck after every sip. Every forgotten cluck costs 1 sip.',
  '{{player}} is the leader for the next 4 cards: everyone copies every gesture they make. Anyone who forgets drinks 1 sip.',
  '{{player}} now delivers 20 seconds of breaking news about the drink in their hand. Anyone who laughs drinks 1 sip.',
  'Everyone makes their best animal sound at the same time. The table picks the weakest one, and whoever made it drinks 2 sips.',
  '{{player}} takes their next sip in extreme slow motion. Anyone who laughs during it also drinks 1 sip.',
  '{{player}} has 10 seconds to name 5 things that are yellow. If they can\'t, they drink 2 sips.',
  'On the count of 3, everyone points at the person most likely to adopt a cactus. Whoever gets the most fingers drinks 2 sips.',
  '{{player}} plays a TV chef and presents their own drink. Then everyone drinks a tasting sip.',
  'Last one to put their hands on their head drinks 2 sips.',
  'Last one to shout "Banana bread!" drinks 2 sips.',
  '{{player}} invents a new word and explains what it means. Anyone who doesn\'t use it at least once in the next 5 cards drinks 1 sip.',
  '{{player}} and {{player}} have a staring contest. Whoever blinks or laughs first drinks 2 sips.',
  'Everyone freeze right now. The first one to move drinks 2 sips.',
  '{{player}} makes the sound of a plane taking off. If the table isn\'t convinced, they drink 1 sip.',
  '{{player}} gives a 15 second campaign speech to become President of the Table. If they get elected, they give out 3 sips, otherwise they drink 2.',
  '{{player}} has 20 seconds to sell {{player}} any object on the table. If the buyer takes the deal, the buyer drinks 2 sips, otherwise the seller does.',
  'Everyone clinks glasses while making a dolphin noise. Then everyone drinks 1 sip.',
  '{{player}} describes their own drink like a snobby wine critic. If the table rates it below 5 out of 10, they drink 2 sips.',
  'The first one to hold up something blue can give out 2 sips.',
  '{{player}} narrates {{player}} for 30 seconds like a nature documentary. Anyone who laughs during it drinks 1 sip.',
  'On the count of 3, everyone howls like a wolf. The quietest one drinks 2 sips.',
  '{{player}} shows how a giraffe drinks. Then everyone drinks 1 sip to the giraffe.',
  '{{player}} counts to 20 with their eyes closed and everyone else has to stay completely silent. Anyone who makes a sound drinks 1 sip.',
  '{{player}} has 20 seconds to explain why socks are dangerous. If the table is convinced, they give out 2 sips, otherwise they drink 2.',
  'Everyone makes a face like they just bit into a lemon at the same time. The most convincing face can give out 2 sips.',
  '{{player}} is now a bobblehead and nods at everything until the next card. Then they drink 1 sip.',
  '{{player}} starts a sentence and everyone adds one word in turn. Whoever hesitates or breaks the sentence drinks 2 sips.',
  '{{player}} hums a well known song. Whoever guesses it first gives out 2 sips. If nobody guesses it, the hummer drinks 2 sips.',
  'For the next 5 cards everyone has to laugh along whenever {{player}} laughs. Anyone who doesn\'t drinks 1 sip.',
  'For the next 6 cards: anyone who yawns drinks 2 sips.',
  'For the next 5 cards: anyone who looks at their phone drinks 2 sips.',
  'For the next 5 cards: anyone who asks a question drinks 1 sip.',
  'For the next 4 cards: anyone who crosses their legs drinks 1 sip.',
  'For the next 5 cards: anyone who sighs loudly drinks 1 sip.',
  'For the next 6 cards: anyone who sneezes can give out 3 sips.',
  'For the next 5 cards: anyone who stands up has to shout "I\'m back!" when they sit down or drink 1 sip.',
  'For the next 5 cards: anyone who empties their glass can make up a new rule for 3 cards.',
  'For the next 5 cards: every time someone says "chaos", everyone drinks 1 sip.',
  'For the next 4 cards: anyone who laughs has to cover their mouth with their hand or drink 1 sip.',
  'For the next 5 cards everyone has to tap their glass on the table twice after drinking. Anyone who forgets drinks 1 extra sip.',
  'For the next 5 cards glasses can only stand at the edge of the table. Anyone who puts their glass closer to the middle drinks 1 sip.',
  'For the next 6 cards: anyone who comments on a card before it\'s done drinks 1 sip.',
  'For the next 5 cards everyone asks their neighbor "May I?" before drinking. Anyone who forgets drinks double.',
  'For the next 5 cards: anyone who mentions a drink that isn\'t on the table drinks 1 sip.',
  'For the next 5 cards the middle of the table is lava. Anyone who touches it drinks 2 sips.',
  'For the next 6 cards: whenever someone has to drink 3 or more sips, everyone else claps. Anyone who doesn\'t clap drinks 1 sip.',
  'For the next 5 cards: anyone who says "thank you" drinks 1 sip right away, and anyone who says "please" can give out 1 sip.',
  'For the next 4 cards everyone names a dinosaur before drinking. Anyone who names a dinosaur that\'s already been said drinks 1 extra sip.',
  'For the next 5 cards: anyone who interrupts {{player}} drinks 2 sips.',
  'For the next 5 cards: anyone who gets a compliment has to take a bow or drink 1 sip.',
  'For the next 6 cards the Echo Law applies: when someone shouts "Echo!", everyone repeats the last word. Anyone too slow drinks 1 sip.',
  'For the next 5 cards everyone has to keep a hand on their heart while talking. Anyone who gets caught drinks 1 sip.',
  'For the next 5 cards: anyone who complains about a card drinks double.',
  'For the next 5 cards everyone can shout "Raise \'em!" once. Then everyone raises their glass and the last one drinks 1 sip.',
  'For the next 5 cards every sip {{player}} gives out is doubled.',
  'For the next 5 cards every sip {{player}} has to drink is halved. Still rounded up, though.',
  'For the next 4 cards everyone has to look {{player}} in the eye while drinking. Anyone who looks away drinks 1 extra sip.',
  '{{player}} can secretly wink at people during the next 5 cards. Anyone who gets winked at drinks 1 sip. If the winker gets caught, they drink 2.',
  'For the next 6 cards every glass is called Gerald and has to be greeted before drinking. Anyone who doesn\'t greet Gerald drinks 1 extra sip.',
  'For the next 5 cards: anyone who mentions an animal has to imitate it or drink 1 sip.',
  'For the next 5 cards: anyone who gives {{player}} a compliment can give out 1 sip.',
  'For the next 4 cards everyone can only laugh with a "Ho ho ho" like Santa. Anyone who laughs normally drinks 1 sip.',
  'For the next 5 cards: anyone who touches their glass without drinking has to drink 1 sip right away.',
  'For the next 5 cards: with every rule violation the whole table shouts "Chaos!" and the sinner drinks 1 extra sip.',
  '{{player}} says the first names of everyone at the table backwards. Every mistake costs 1 sip.',
  '{{player}} spells the word "Mississippi" backwards. If they can\'t, they drink 2 sips.',
  '{{player}} says "Peter Piper picked a peck of pickled peppers" 3 times fast. Every slip costs 1 sip.',
  'Everyone sings the chorus of a song {{player}} picks. Anyone who doesn\'t know the lyrics drinks 1 sip.',
  '{{player}} imitates a vacuum cleaner until someone laughs. The first one to laugh drinks 2 sips.',
  'Everyone touch something red right now. The last one to find something drinks 2 sips.',
  '{{player}} has 15 seconds to name 4 words that rhyme with "beer". Every missing word costs 1 sip.',
  'Everyone shouts their favorite food at the same time. Anyone who shouts the same thing as someone else drinks 1 sip.',
  '{{player}} announces the next card with a drumroll on the table and gets to give out 1 sip for it.',
  '{{player}} and {{player}} play rock, paper, scissors. The loser drinks 2 sips and has to call the winner "Champion" for the next 3 cards.',
  'Everyone freezes in a statue pose right now. {{player}} picks the best statue, who can give out 2 sips.',
  'The first one to name a song with a color in the title can give out 2 sips.',
  '{{player}} makes a toast using only sounds, no real words. Then everyone drinks 1 sip.',
  '{{player}} invents a dance move that everyone copies while sitting. Anyone who refuses drinks 2 sips.',
  'Everyone fakes a yawn at the same time. Anyone who ends up really yawning drinks 1 sip.',
  '{{player}} whispers a word to {{player}}, who acts it out without speaking. If the table guesses it within 30 seconds, the actor gives out 2 sips, otherwise they drink 2.',
  'Everyone drums on the table for 5 seconds. The last one to stop drinks 1 sip.',
  '{{player}} explains the plot of a movie in one sentence as badly as possible. Whoever guesses the movie first gives out 2 sips.',
  '{{player}} turns into a dinosaur for a moment and roars as loud as they can. Anyone who flinches drinks 1 sip.',
  '{{player}} gives a weather report for the table. If it\'s rain, everyone drinks 1 sip. If it\'s sunshine, only the presenter does.',
  'Everyone shows a thumbs up or thumbs down at the same time. The minority drinks 2 sips.',
  '{{player}} and {{player}} argue for 20 seconds using only the word "potato". The table picks the winner and the loser drinks 2 sips.',
  '{{player}} tries not to blink for 10 seconds while everyone pulls faces. If they make it, they give out 3 sips, otherwise they drink 2.',
  'Going around the table, everyone says a word starting with "Z". Whoever hesitates or repeats a word drinks 2 sips.',
  '{{player}} makes their glass give a short thank you speech to the table in a funny voice. Then everyone drinks 1 sip.',
  '{{player}} has 20 seconds to make the table laugh without words. If someone laughs, the laugher drinks 1 sip, otherwise the clown drinks 2 sips.',
  'The player with the most letters in their first name drinks 2 sips and then writes their name in the air with their nose.',
  'The player with the shortest first name has to repeat every new rule out loud for the next 5 cards. Every forgotten repeat costs 1 sip.',
  'The tallest player at the table is the lighthouse for the next 5 cards: when they shout "Fog!", everyone goes "Toooot". The last one drinks 1 sip.',
  'The shortest player at the table can shout "Stop!" once in the next 5 cards to skip their own sips.',
  'Whoever had the most recent birthday gets celebrated: everyone sings a quick birthday song and the birthday kid gives out 3 sips.',
  'Whoever traveled the farthest to get here is a tourist for the next 5 cards and reacts to every card with "How exciting!" Every forgotten comment costs 1 sip.',
  'Whoever is wearing the most rings can give out 2 sips and can\'t be given any sips for the next 3 cards.',
  'The player with the emptiest glass is captain for the next 4 cards: when they shout "All hands on deck!", everyone stands up. The last one drinks 1 sip.',
  '{{player}} has to mumble quietly to themselves nonstop for the next 3 cards. Every pause longer than 5 seconds costs 1 sip.',
  '{{player}} is the inventor for the next 5 cards and comes up with a mini rule for 1 card after every card. If they can\'t think of one, they drink 2 sips.',
  '{{player}} gets a joker: once in the next 6 cards they can shout "Joker!" and pass their own sips to someone else.',
  '{{player}} is the troublemaker for the next 5 cards and can make one weird noise per card. Anyone who reacts drinks 1 sip.',
  '{{player}} is the fortune teller for the next 4 cards and predicts everyone\'s future before they drink. Anyone who laughs at the prophecy drinks 1 extra sip.',
  '{{player}} is the alarm system for the next 5 cards and shouts "Alert!" as soon as someone raises their glass. Every missed "Alert!" costs 1 sip.',
  '{{player}} is the psychic for the next 5 cards and predicts who drinks next before every card. For every correct guess they give out 2 sips.',
  '{{player}} is the glass inspector for the next 6 cards: anyone who leaves their glass unattended gets 1 sip from them.',
  '{{player}} is a superhero for the next 5 cards and shouts their hero name before each of their own sips. Forgetting the name costs 1 extra sip.',
  '{{player}} and {{player}} are enemy nations for the next 5 cards and only talk through an ambassador they pick together. Whoever talks directly drinks 2 sips.',
  '{{player}} and {{player}} are bound by fate for the next 4 cards: whenever one has to drink, rock, paper, scissors decides who actually does.',
  '{{player}} and {{player}} are partners in crime for the next 5 cards and can each save the other from a drinking card once. The rescuer then drinks 1 sip.',
  '{{player}} and {{player}} have to finish each other\'s sentences for the next 5 cards. Whoever doesn\'t jump in drinks 1 sip.',
  '{{player}}, {{player}} and {{player}} are a band for the next 5 cards and sing "Yeah!" together on every sip. Anyone who doesn\'t sing along drinks 1 sip.',
  '{{player}} and {{player}} form a secret society and agree on a secret hand signal for the next 5 cards. If someone figures it out, both drink 2 sips.',
  '{{player}} and {{player}} are TV channels for the next 5 cards and can only speak after announcing a commercial break. Every violation costs 1 sip.',
  'Anyone who has broken a rule tonight confesses now and drinks 1 sip. Anyone who stays quiet and gets ratted out drinks 3.',
  'Chaos round: everyone shouts a new rule at the same time. {{player}} decides which one applies for the next 5 cards.',
  'Democracy: the table votes on which active rule gets abolished. Anyone who voted for the winning rule drinks 1 sip.',
  'Revolution: everyone who doesn\'t have a role right now drinks 1 sip. Everyone who does loses it.',
  'The oldest active rule gets replaced by its opposite. {{player}} words the opposite and drinks 1 sip for it.',
  'The first one who can list all active rules can give out 3 sips.',
  'Memory test: {{player}} lists all the rules currently in play. Every forgotten rule costs 1 sip.',
  'Lucky streak: in the next 3 cards, anyone who has to drink can shout "Lucky!" once and drink 1 sip less.',
  'For the next 5 cards anyone a card is about has to cry out dramatically "Why always me?" Anyone who forgets drinks 1 extra sip.',
  'For the next 4 cards every sip is taken with eyes closed. Anyone who peeks drinks 1 extra sip.',
  '{{player}} gives a solemn tribute to the last sip in their glass and then drinks it.',
  '{{player}} does a 10 second ad for tap water. If the table is convinced, everyone drinks 1 sip of water, otherwise the advertiser drinks 2 sips.',
  '{{player}} acts out a conversation between their left and right shoe. If there\'s no applause, they drink 2 sips.',
  'Everyone pretends to ride a roller coaster for 10 seconds. Whoever puts in the least effort drinks 2 sips.',
  '{{player}} recites the alphabet as fast as they can. If it takes longer than 10 seconds, they drink 2 sips.',
  '{{player}} names 3 things you should never put in a microwave. Anyone who comes up with something funnier can give them 1 sip.',
  '{{player}} describes their morning like an action movie trailer. Then everyone drinks 1 sip to the hero.',
  'Everyone makes an alarm clock sound at the same time. The last one to stop drinks 1 sip.',
  '{{player}} comes up with a name for the group. For the next 5 cards everyone shouts it before drinking, or drinks 1 extra sip.',
  '{{player}} plays a fly buzzing around the table and lands on someone. That person drinks 2 sips.',
  '{{player}} greets everyone at the table like a long lost friend. Anyone who doesn\'t play along drinks 1 sip.',
  '{{player}} shows their victory pose for winning the lottery. If the table rates it below 6 out of 10, they drink 2 sips.',
  '{{player}} explains a hobby that doesn\'t exist to {{player}} as convincingly as possible. If the second player believes it, they drink 2 sips.',
];
