export const curatedNormalTasksEn: string[] = [
  '{{player}}, who\'s more likely to become famous: {{player}} or {{player}}? The chosen one gives out 3 sips.',
  '{{player}} and {{player}}, even out your glasses. Whoever has more drinks until both are equally full.',
  '{{player}}, drink 3 sips if you like kids.',
  'Vote: Would you rather never drink alcohol again or have a beer every single day forever? The minority drinks 4 sips.',
  'Vote: Who tells the worst jokes? The chosen one gives out 5 sips.',
  '{{player}}, drink 2 sips if you like Taylor Swift.',
  '{{player}}, think of someone you met today. Everyone gets one guess, going around the circle. Wrong guesses drink 1 sip.',
  'Everyone sings the chorus of "Love Story" by Taylor Swift. The best singer gives out 5 sips.',
  'For the next 10 minutes everyone has to be sweet to each other. Anyone who\'s mean drinks 2 sips.',
  '{{player}}, drink as many sips as there are consonants in your last name.',
  '{{player}}, drink 3 sips if you have a pet.',
  'Go around the circle and everyone says a proverb. The first one who can\'t think of one drinks 3 sips.',
  'Everyone drinks 1 sip for every invited person who didn\'t show up.',
  '{{player}}, what\'s the dumbest thing you\'ve ever done drunk? Tell the story or drink 5 sips.',
  '{{player}}, give out 3 sips to a player who\'s shorter than you.',
  '{{player}}, who\'s more likely to give themselves a tattoo: {{player}} or {{player}}? The chosen one gives out 3 sips.',
  'Everyone wearing glasses gives out 3 sips.',
  '{{player}}, close your eyes. The others hand you a drink and you have to guess whose it is. Guess right and give out 5 sips, otherwise drink 3.',
  '{{player}}, drink 3 sips if you came by car.',
  'Vote: Beer or shots? The minority drinks 2 sips.',
  '{{player}}, drink 2 sips.',
  'Vote: Who has the best taste in music? The chosen one gives out 5 sips.',
  '{{player}}, give out 2 sips if you don\'t like Marvel movies.',
  '{{player}}, do a handstand or drink 5 sips.',
  '{{player}}, drink 3 sips if you enjoy talking on the phone.',
  '{{player}}, drink 2 sips if you\'ve never been skydiving.',
  '{{player}}, drink 3 sips if you\'re a student.',
  'All the girls drink 3 sips.',
  '{{player}}, who skipped school more often: {{player}} or {{player}}? The chosen one drinks 3 sips.',
  'Everyone with a summer birthday drinks 2 sips.',
  '{{player}}, if your first name starts with T, drink 3 sips. Otherwise give them out.',
  '{{player}}, drink 3 sips if you shower every day.',
  '{{player}}, drink 2 sips if you\'ve ridden a bike this week.',
  '{{player}}, drink as many sips as the number of years between you and {{player}}, but at least 1.',
  '{{player}}, drink 3 sips if you have your own bathroom.',
  'Everyone who\'s ever been messaged by a sex bot on Instagram drinks 2 sips.',
  'Last one to lift their feet off the floor drinks 3 sips.',
  'Everyone who still lives with their parents drinks 2 sips.',
  'Whoever has the next birthday gives out 5 sips. If it\'s their birthday today, everyone else drinks 3 sips.',
  '{{player}}, drink 2 sips if you watch Netflix on someone else\'s account.',
  '{{player}}, name 3 Taylor Swift songs. If you can, give out 2 sips. If not, drink them yourself.',
  'Everyone who owns a car drinks 2 sips.',
  '{{player}}, the two people sitting next to you drink 2 sips.',
  '{{player}}, pick a drinking buddy. Until the game ends, they drink whenever you drink.',
  '{{player}}, pick a drinking buddy. Until the game ends, you always drink together, no matter which of you has to drink.',
  '{{player}}, pour 1 sip of your drink into the glass of the person across from you.',
  '{{player}}, who\'s more likely to get into a fight with you: {{player}} or {{player}}? The chosen one drinks 3 sips.',
  '{{player}}, drink 3 sips. Then going counterclockwise, everyone drinks 1 sip less than the person before them.',
  'Everyone drinks as many sips as they have siblings.',
  'Everyone who\'s spent more than 2 hours on social media today drinks 2 sips.',
  'The youngest and the oldest player play rock, paper, scissors. The loser drinks 3 sips.',
  '{{player}}, drink 1 sip and pick someone to drink 3. That person then picks someone to drink 2 more, or ends the chain.',
  '{{player}}, who\'s the better listener when things get serious: {{player}} or {{player}}? The chosen one gives out 3 sips.',
  '{{player}}, do a somersault or drink 5 sips.',
  '{{player}}, pick a song. Everyone sings it together. Anyone who doesn\'t sing along drinks 3 sips.',
  '{{player}}, name 2 things you love about the person on your right. That person happily drinks 2 sips.',
  'Take a group selfie. Then everyone drinks 1 sip.',
  '{{player}}, tell a joke. Anyone who laughs drinks 2 sips.',
  '{{player}} and {{player}}, arm wrestle. The loser drinks 3 sips.',
  '{{player}}, share a fun fact about yourself. Everyone else guesses if it\'s true. Wrong guesses drink 3 sips.',
  '{{player}}, give out 2 sips if you know where American Samoa is. Otherwise drink them yourself.',
  '{{player}}, hum a song. Whoever guesses it first gives out 3 sips. If nobody gets it, you drink 5 sips.',
  'Everyone raise your glasses, cheers, and drink 2 sips.',
];

export const curatedWildTasksEn: string[] = [
  '{{player}}, ask anyone you like a question. They have to answer honestly or drink 5 sips.',
  '{{player}}, do squats. For every 3 squats you give out 1 sip, and on every 5th squat you drink 1 sip yourself.',
  '{{player}}, drink 1 sip through a sock or drink 5 sips.',
  '{{player}}, tell an embarrassing story about {{player}} or drink 5 sips.',
  'First person to show an embarrassing party photo of themselves on their phone gives out 3 sips.',
  '{{player}} and {{player}}, mix your drinks together and each drink half.',
  '{{player}}, for the next 5 cards, say "I love my mom and my dad" before every sip. If you forget, drink 2 extra sips.',
  '{{player}}, walk once around the table clucking like a chicken or drink 5 sips.',
  '{{player}}, sing a song for everyone or drink 3 sips.',
  '{{player}}, do 20 proper push-ups or drink 3 sips and do 10 jumping jacks.',
  '{{player}}, take a shot of the worst drink on the table right now.',
  '{{player}}, roast the person on your right in one sentence. If they laugh, they drink 2 sips. If not, you drink 2.',
  'The host picks a player, who takes a shot of the host\'s choice.',
  'Everyone who\'s ever clogged a toilet drinks 3 sips.',
  '{{player}}, pour a sip of your drink straight into {{player}}\'s mouth.',
  '{{player}}, drink half your glass and give the other half to a player of your choice.',
  'Vote: Would you rather go on a date with your ex or with your best friend\'s ex? The minority drinks 5 sips.',
  '{{player}}, how attractive do you find the person across from you on a scale of 1 to 10? Drink that many sips.',
  '{{player}}, down your drink.',
  'Everyone who\'s ever been drunk at school drinks 4 sips.',
  'Vote: Who\'s got the bigger... uh, the bigger drinking stamina, {{player}} or {{player}}? Whoever gets fewer votes drinks 5 sips.',
];
