export const duellTasksEn: string[] = [
  '{{player}} vs. {{player}}: Rock, paper, scissors, best of 3. The loser drinks 3 sips.',
  '{{player}} vs. {{player}}: Rock, paper, scissors, one round only, all or nothing. The loser drinks 5 sips.',
  '{{player}} vs. {{player}} vs. {{player}}: Three-way rock, paper, scissors until there\'s a loser. They drink 4 sips.',
  '{{player}} vs. {{player}}: Rock, paper, scissors, first to win 5 rounds. The winner gives out 5 sips.',
  '{{player}} vs. {{player}}: Thumb war, best of 3. The winner gives out 4 sips.',
  '{{player}} vs. {{player}}: Thumb war with your left hand. The loser drinks 3 sips.',
  '{{player}} vs. {{player}}: Staring contest. Whoever blinks first drinks 3 sips.',
  '{{player}} vs. {{player}}: Staring contest, and {{player}} can pull faces to distract you. Whoever blinks first drinks 4 sips.',
  '{{player}} vs. {{player}}: Arm wrestling. The loser drinks 4 sips.',
  '{{player}} vs. {{player}}: Arm wrestling with your weaker arm. The winner gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns holding out an open palm while the other rests a finger on it, then try to snatch that finger. After 3 tries each, whoever caught fewer drinks 3 sips.',
  '{{player}} drops a pen, and {{player}} and {{player}} take turns trying to catch it. Whoever misses first drinks 3 sips.',

  '{{player}} vs. {{player}}: Look each other dead in the eye for 30 seconds. Whoever laughs first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns telling each other a terrible dad joke. Whoever laughs first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns saying "jiggly pudding" with a dead serious face. Whoever grins first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns pulling a face. Whoever laughs first drinks 4 sips.',
  '{{player}} vs. {{player}}: Take turns making an animal noise while the other keeps a straight face. Whoever laughs first drinks 3 sips.',
  '{{player}} vs. {{player}}: Sing each other a compliment in an opera voice. Whoever laughs first drinks 3 sips.',
  '{{player}} vs. {{player}}: Tell each other what you had for breakfast in a news anchor voice. Whoever laughs first drinks 3 sips.',
  '{{player}} tries to make {{player}} and {{player}} laugh within 30 seconds without touching them. Whichever of the two laughs first drinks 4 sips.',
  '{{player}} vs. {{player}}: Stare at each other and slowly recite the alphabet together. Whoever laughs first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns doing your best evil villain laugh. Whoever cracks up for real first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns whispering a made up secret about potatoes. Whoever giggles first drinks 3 sips.',
  '{{player}} vs. {{player}}: For 20 seconds, the group can do anything to make you laugh, as long as they don\'t touch you. Whoever laughs first drinks 4 sips.',

  '{{player}} vs. {{player}}: Whoever stands on one leg longer gives out 4 sips.',
  '{{player}} vs. {{player}}: Stand on one leg with your eyes closed. Whoever puts their other foot down first drinks 3 sips.',
  '{{player}} vs. {{player}}: Hold one arm straight out in front of you. Whoever lets it drop first drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever balances a spoon on their nose longer gives out 3 sips.',
  '{{player}} vs. {{player}}: Wall sit with your back against the wall. Whoever stands up first drinks 4 sips.',
  '{{player}} vs. {{player}}: Whoever does more squats in 20 seconds gives out 3 sips. {{player}} keeps count.',
  '{{player}} vs. {{player}}: Whoever can hum a note longer without taking a breath gives out 3 sips.',
  '{{player}} vs. {{player}}: Spin a coin on the table at the same time. Whoever\'s coin spins longer gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever balances a pen upright on one finger longer gives out 3 sips.',
  '{{player}} vs. {{player}}: Close your eyes and guess when 30 seconds are up while {{player}} times it. Whoever is further off drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever can stand on tiptoe longer gives out 3 sips.',
  '{{player}} vs. {{player}}: Sit down and lift both feet off the floor. Whoever puts them down first drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever does more jumping jacks in 15 seconds gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever snaps their fingers more times in 10 seconds gives out 2 sips. {{player}} counts.',
  '{{player}} vs. {{player}}: Pat your head with one hand and rub your belly with the other. Whoever messes up first drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever can hold a push up position longer gives out 4 sips.',
  '{{player}} vs. {{player}}: Close your eyes and touch the tip of your nose with your index finger 3 times. Whoever misses more often drinks 3 sips.',

  '{{player}} vs. {{player}}: Put an object between you. As soon as {{player}} shouts "Now", grab it. Whoever gets it first gives out 3 sips.',
  '{{player}} claps at some random moment. Whichever of {{player}} and {{player}} touches their own nose first gives out 3 sips.',
  '{{player}} says random words. As soon as the word "pizza" comes up, {{player}} and {{player}} jump up. Whoever is slower drinks 3 sips.',
  '{{player}} calls out a mix of animals and colors. {{player}} and {{player}} raise their glass only for colors. Whoever makes a mistake first drinks 3 sips.',
  '{{player}} calls out body parts, and {{player}} and {{player}} point to them as fast as they can. Whoever points wrong first drinks 3 sips.',
  '{{player}} vs. {{player}}: "Head, Shoulders, Knees and Toes", faster and faster. Whoever touches the wrong spot first drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever counts down from 30 to 0 faster without slipping up gives out 3 sips.',
  '{{player}} plays "Simon Says" with {{player}} and {{player}}. Whoever follows an order without "Simon says" first drinks 3 sips.',
  '{{player}} calls out numbers, and {{player}} and {{player}} knock on the table only for even numbers. Whoever messes up first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns counting up, and say "Buzz" instead of any number that contains a 7 or is divisible by 7. Whoever messes up first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns counting up in Spanish, faster and faster. Whoever stalls or miscounts first drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever unlocks their phone and turns on the flashlight first gives out 2 sips.',
  '{{player}} shouts "Cheers" at some random moment. Whichever of {{player}} and {{player}} raises their glass last drinks 2 sips.',

  '{{player}} vs. {{player}}: Take turns naming car brands. Whoever hesitates or repeats one drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming countries in Europe. Whoever runs out drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming Disney characters. Whoever gets stuck drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming beer brands. Whoever has to pass first drinks 4 sips.',
  '{{player}} vs. {{player}}: Take turns naming fruits. Whoever draws a blank first drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming vegetables. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming world capitals. Whoever hesitates drinks 3 sips, and the winner also gives out 2.',
  '{{player}} vs. {{player}}: Take turns naming soccer clubs. Whoever runs out drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming sports. The winner gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming animals that start with S. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming musical instruments. Whoever hesitates drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming Pokémon. Whoever runs out drinks 4 sips.',
  '{{player}} and {{player}}, take turns naming Harry Potter characters. Whoever gets stuck drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming Simpsons characters. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming superheroes. The winner gives out 4 sips.',
  '{{player}} vs. {{player}}: Take turns naming pizza toppings. Whoever hesitates drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming cocktails. Whoever runs out drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming types of cheese. Whoever has to pass first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming jobs. Whoever hesitates or repeats one drinks 2 sips.',
  '{{player}} vs. {{player}}: Take turns naming dog breeds. Whoever runs out drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming board games. The winner gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming TV shows. Whoever stalls first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming candy and sweets. Whoever runs out drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming US cities. Whoever hesitates drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming spices. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming birds. Whoever runs out drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming fish and sea creatures. The winner gives out 3 sips.',
  '{{player}} and {{player}}, take turns naming things you\'d find in a kitchen. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming rappers. Whoever runs out drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming countries in Africa. Whoever gets stuck first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming first names that start with M. Whoever hesitates drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming non alcoholic drinks. Whoever gets stuck drinks 3 sips of something alcoholic.',
  '{{player}} vs. {{player}}: Take turns naming things you\'d find on a beach. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming video games. The winner gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming fairy tales. Whoever runs out drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming ice cream flavors. Whoever hesitates drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming movie titles with a number in them. Whoever gets stuck drinks 4 sips.',
  '{{player}} vs. {{player}}: Take turns naming capitals in South America. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming Hollywood actors and actresses. Whoever hesitates drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming Italian dishes. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming words for "drunk". Whoever runs out drinks 3 sips.',

  '{{player}} vs. {{player}}: Word chain, each word starts with the last letter of the one before. Whoever hesitates drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns building a chain like football, ballroom, roommate. Whoever gets stuck drinks 3 sips.',
  '{{player}} vs. {{player}}: "I packed my suitcase", take turns repeating everything so far and adding one item. Whoever forgets something first drinks 4 sips.',
  '{{player}} vs. {{player}}: Take turns rhyming with "house". Whoever can\'t find a rhyme drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever finds more words that rhyme with "night" in 30 seconds gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming words that start with "beer". Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming words that end in "ing". Whoever hesitates drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever names more words with Q in 20 seconds gives out 3 sips.',
  '{{player}} vs. {{player}}: Each of you makes up a sentence where every word starts with B. The group picks the better one, and the loser drinks 3 sips.',
  '{{player}} vs. {{player}}: Tell a story together, one word each at a time. Whoever hesitates first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns talking about your favorite food for 30 seconds without saying "um" or "uh". Whoever says it first drinks 3 sips.',
  '{{player}} fires quick questions at {{player}} and {{player}}, taking turns. Whoever says "yes" or "no" first drinks 3 sips.',
  '{{player}} vs. {{player}}: Talk to each other only in questions. Whoever says something that isn\'t a question first drinks 3 sips.',
  '{{player}} vs. {{player}}: Have a conversation where each sentence starts with the next letter of the alphabet, beginning with A. Whoever stalls drinks 3 sips.',
  '{{player}} calls out words, and {{player}} and {{player}} shout the opposite as fast as they can. Whoever is faster 3 times first gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever first names a word with two double letters back to back, like coffee or bookkeeper, gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever names the longer real word gives out 3 sips. The group decides if it counts.',
  '{{player}} whispers a word to {{player}} and to {{player}}. Explain it to the group without saying it. Whoever\'s word gets guessed faster gives out 3 sips.',
  '{{player}} vs. {{player}}: Chat for 30 seconds without using the word "I". Whoever says it first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns saying a sentence without a single letter E in it. Whoever slips one in or hesitates first drinks 3 sips.',

  '{{player}} vs. {{player}}: Say "She sells seashells by the seashore" 3 times fast. Whoever stumbles more drinks 3 sips.',
  '{{player}} vs. {{player}}: Say "Red lorry, yellow lorry" 3 times fast. The group picks the loser, who drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever says "Peter Piper picked a peck of pickled peppers" faster without a mistake gives out 3 sips.',
  '{{player}} vs. {{player}}: Tongue twister "How much wood would a woodchuck chuck if a woodchuck could chuck wood" 3 times in a row. Whoever slips up drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever gets through "Six slick slim sycamore saplings" faster gives out 3 sips.',
  '{{player}} vs. {{player}}: Say "Fresh fried fish, fish fresh fried, fried fish fresh, fish fried fresh" as fast as you can. Whoever messes up drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever says "The sixth sick sheik\'s sixth sheep\'s sick" without a mistake gives out 4 sips.',
  '{{player}} vs. {{player}}: Say "Irish wristwatch" 5 times fast. Whoever stumbles first drinks 3 sips.',
  '{{player}} vs. {{player}}: Tongue twister "I saw Susie sitting in a shoeshine shop". The group picks the loser, who drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever says "Unique New York" 5 times faster without a mistake gives out 3 sips.',

  '{{player}} vs. {{player}}: Whoever says the alphabet backwards faster gives out 4 sips.',
  '{{player}} vs. {{player}}: Say the months backwards, from December to January. Whoever is slower or slips up drinks 3 sips.',
  '{{player}} vs. {{player}}: Say the days of the week backwards, starting with Sunday. Whoever finishes first gives out 2 sips.',
  '{{player}} vs. {{player}}: Spell your own first name backwards as fast as you can. Whoever is slower drinks 2 sips.',
  '{{player}} vs. {{player}}: Whoever spells "rhythm" correctly first gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever recites the 7 times table up to 70 faster gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever lists more US states in 30 seconds gives out 3 sips. There are 50.',
  '{{player}} vs. {{player}}: Whoever first names all 8 planets in order from the sun gives out 4 sips. The group checks.',
  '{{player}} vs. {{player}}: Whoever spells "onomatopoeia" correctly first gives out 3 sips.',

  '{{player}} vs. {{player}}: Whoever can name more Dolly Parton songs gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming Queen songs. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever knows more ABBA songs gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming Michael Jackson songs. Whoever hesitates drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever names more Ed Sheeran songs gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming Taylor Swift songs. Whoever runs out drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever knows more Coldplay songs gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming AC/DC songs. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever lists more Beatles songs gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming Rihanna songs. Whoever gets stuck drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming Rammstein songs. Whoever hesitates drinks 3 sips.',
  '{{player}} hums a song, and {{player}} and {{player}} guess. Whoever gets it first gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns singing a line from a song with a color in the title. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns singing a line from a Christmas song. Whoever runs out drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever names more songs with "Love" in the title gives out 3 sips.',

  '{{player}} vs. {{player}}: Whoever names the capital of Australia first gives out 3 sips. {{player}} checks on their phone.',
  '{{player}} vs. {{player}}: Take turns naming countries that border Germany. Whoever passes or gets one wrong first drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever names more US state capitals gives out 3 sips. {{player}} checks on their phone.',
  '{{player}} vs. {{player}}: Whoever names more US presidents gives out 3 sips. {{player}} checks on their phone.',
  '{{player}} looks up a trivia question on their phone and reads it out. Whichever of {{player}} and {{player}} answers correctly first gives out 3 sips.',
  '{{player}} vs. {{player}}: Guess how tall the Eiffel Tower is. {{player}} looks it up, and whoever is further off drinks 3 sips.',
  '{{player}} vs. {{player}}: Guess what year the first iPhone came out. {{player}} looks it up, and whoever is closer gives out 3 sips.',
  '{{player}} vs. {{player}}: Guess how many contacts {{player}} has in their phone. They check, and whoever is closer gives out 3 sips.',
  '{{player}} vs. {{player}}: Guess how many unread messages {{player}} has right now. They check, and whoever is further off drinks 3 sips.',

  '{{player}} vs. {{player}}: Take turns naming shoe brands. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming items of clothing. Whoever hesitates or repeats one drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming tools. Whoever runs out drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming dinosaurs. Whoever gets stuck drinks 4 sips.',
  '{{player}} vs. {{player}}: Take turns naming insects. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming types of trees. Whoever runs out drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming flowers. Whoever hesitates drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming pieces of furniture. Whoever draws a blank first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming winter sports. The winner gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming vehicles, but no car brands. Whoever stalls drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming apps on your phone without looking. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming types of pasta. Whoever gets stuck drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming things that are round. Whoever hesitates drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming countries in Asia. Whoever runs out drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming islands. Whoever passes first drinks 4 sips.',
  '{{player}} vs. {{player}}: Take turns naming rivers. Whoever runs out drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming British bands. Whoever stalls first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming types of bread and baked goods. Whoever hesitates drinks 3 sips.',
  '{{player}} and {{player}}, take turns naming things you\'d find in a bathroom. Whoever gets stuck drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming movie titles with an animal in them. Whoever passes first drinks 4 sips.',

  'City, Country, River: {{player}} picks a letter. Whichever of {{player}} and {{player}} first names a city, a country and a river starting with it gives out 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming words with two meanings, like bat or bark. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming words English borrowed from other languages, like kindergarten or croissant. Whoever hesitates drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns saying proverbs. Whoever mixes one up or has to pass drinks 3 sips.',
  '{{player}} vs. {{player}}: Word chain with first names, each new name starts with the last letter of the one before. Whoever stalls drinks 3 sips.',
  '{{player}} vs. {{player}}: Word chain with food and drinks, each word starts with the last letter of the one before. Whoever gets stuck drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming words that start with "sh". Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming words with exactly 3 letters. Whoever hesitates drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns rhyming with "heart". Whoever runs out of rhymes drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns naming words with "oo" in them. Whoever stalls drinks 2 sips.',
  '{{player}} vs. {{player}}: Take turns naming compound words with "fire", like firefighter. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns describing {{player}} with a nice adjective. Whoever runs out first drinks 3 sips.',
  '{{player}} picks a letter. {{player}} and {{player}} take turns naming animals that start with it. Whoever passes first drinks 3 sips.',

  '{{player}} vs. {{player}}: Whoever takes a selfie with everyone at the table in it faster gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever finds a photo of a dog on their phone first gives out 2 sips.',
  '{{player}} vs. {{player}}: Whoever points out 3 round things in the room first gives out 3 sips.',
  '{{player}} vs. {{player}}: Finger tug of war with your index fingers hooked together. Whoever pulls the other over gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever holds their breath longer gives out 3 sips. {{player}} times it.',
  '{{player}} vs. {{player}}: Put a napkin on your head and nod 10 times. Whoever\'s napkin falls off first drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns building a tower out of things on the table. Whoever knocks it over drinks 4 sips.',
  '{{player}} vs. {{player}}: Hold your glass out in front of you at arm\'s length. Whoever lowers their arm first drinks 3 sips.',
  '{{player}} vs. {{player}}: Say the alphabet at the same time, one forwards and one backwards. Whoever stalls first drinks 3 sips.',
  '{{player}} taps a rhythm on the table. {{player}} and {{player}} tap it back, and it gets longer each time. Whoever gets it wrong first drinks 3 sips.',
  '{{player}} vs. {{player}}: Close your eyes. 3 people from the group say "Cheers" one after another in a disguised voice. Whoever recognizes more voices gives out 3 sips.',
  '{{player}} vs. {{player}}: Close your eyes. The group hands you 3 hands, one after another. Whoever matches more hands to the right person gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever knows more last names of the people at the table gives out 3 sips. The group confirms.',
  '{{player}} vs. {{player}}: Whoever correctly names more favorite drinks of the people at the table gives out 3 sips.',
  '{{player}} vs. {{player}}: Balance a coaster on the back of your hand, stand up and sit back down. Whoever drops it drinks 3 sips.',
  '{{player}} calls out numbers from 1 to 5. {{player}} and {{player}} clap exactly that many times. Whoever messes up first drinks 3 sips.',
  '{{player}} vs. {{player}}: One of you does moves for 20 seconds while the other mirrors them, then switch. Whoever mirrored worse drinks 3 sips. The group decides.',
  '{{player}} vs. {{player}}: Draw a face on your phone with your eyes closed. The group picks the worse drawing, and whoever drew it drinks 3 sips.',

  '{{player}} vs. {{player}}: Act like a dog that just spotted a ball. The group votes, and the loser drinks 3 sips.',
  '{{player}} vs. {{player}}: Play a waiter who gets every order wrong. Whoever makes the group laugh more gives out 3 sips.',
  '{{player}} vs. {{player}}: Present a dish like on a cooking show, using only things from the table. The group picks the winner, who gives out 3 sips.',
  '{{player}} vs. {{player}}: Propose to a chair. Whoever is less convincing drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns impersonating a celebrity. Whoever\'s celebrity the group guesses faster gives out 3 sips.',
  '{{player}} vs. {{player}}: Each impersonate someone in the group without saying their name. Whoever gets guessed faster gives out 3 sips.',
  '{{player}} vs. {{player}}: Play tourists asking for directions to the train station in a made up language. The group votes, and the loser drinks 3 sips.',
  '{{player}} vs. {{player}}: Give a short eulogy for an empty glass. Whoever moves the group more gives out 3 sips.',
  '{{player}} vs. {{player}}: Sing "Twinkle, Twinkle, Little Star" as a heavy metal song. Whoever is less convincing drinks 3 sips.',
  '{{player}} vs. {{player}}: Rap 4 lines about your favorite food. The group picks the winner, who gives out 4 sips.',
  '{{player}} vs. {{player}}: Act out a 15 second soap opera scene where someone has lost the car keys. Whoever was more dramatic gives out 3 sips.',
  '{{player}} vs. {{player}}: Make the sound of an old dial up modem connecting. The group decides who sounds more real, and the loser drinks 2 sips.',
  '{{player}} vs. {{player}}: Play a magician whose trick goes completely wrong. Whoever makes the group laugh more gives out 3 sips.',
  '{{player}} vs. {{player}}: Show how a baby bites into a lemon for the first time. Whoever is less convincing drinks 3 sips.',
  '{{player}} vs. {{player}}: Explain in 20 seconds why you of all people deserve a trophy tonight. The group votes, and the loser drinks 3 sips.',

  '{{player}} vs. {{player}}: Guess how many glasses are on the table right now without counting. {{player}} counts, and whoever is further off drinks 2 sips.',
  '{{player}} vs. {{player}}: Guess how many steps it is from here to the door. {{player}} walks it, and whoever is further off drinks 3 sips.',
  '{{player}} thinks of a number between 1 and 50. Whichever of {{player}} and {{player}} guesses closer gives out 3 sips.',

  '{{player}} vs. {{player}}: Take turns acting out an animal. Whoever\'s animal the group guesses faster gives out 3 sips.',
  '{{player}} vs. {{player}}: Each act out a movie title. Whoever gets guessed first gives out 4 sips.',
  '{{player}} vs. {{player}}: Charades with jobs. Whoever\'s job stays unguessed longer drinks 3 sips.',
  '{{player}} vs. {{player}}: Take turns acting out a sport. Whoever gets guessed faster gives out 3 sips.',
  '{{player}} vs. {{player}}: Each act out a household appliance. The group votes on who was more convincing, and the loser drinks 3 sips.',
  '{{player}} vs. {{player}}: Each act out a fairy tale. Whoever\'s fairy tale gets guessed first gives out 3 sips.',
  '{{player}} whispers the same word to {{player}} and {{player}}. Both act it out at the same time, and whoever gets guessed first gives out 3 sips.',
  '{{player}} vs. {{player}}: Act out how you get up in the morning. The group votes on who was funnier, and that person gives out 3 sips.',
  '{{player}} vs. {{player}}: Draw a horse on your phone in 30 seconds. The group votes on whose drawing is worse, and that person drinks 3 sips.',
  '{{player}} vs. {{player}}: Act out unwrapping a present you don\'t like. Whoever is more convincing gives out 3 sips.',

  '{{player}} vs. {{player}}: Both do a rooster in the morning. The group votes on who was worse, and that person drinks 3 sips.',
  '{{player}} vs. {{player}}: Commentate the last minute of a World Cup final like a sports announcer. The group picks the winner, who gives out 4 sips.',
  '{{player}} vs. {{player}}: Move like a robot for 10 seconds. Whoever is less convincing drinks 3 sips.',
  '{{player}} vs. {{player}}: Present tomorrow\'s weather forecast. The group votes, and the loser drinks 3 sips.',
  '{{player}} vs. {{player}}: Give directions to the kitchen like a GPS voice. Whoever sounds better gives out 3 sips.',
  '{{player}} vs. {{player}}: Make a train station announcement for a delayed train. The group picks the better one, and the winner gives out 3 sips.',
  '{{player}} vs. {{player}}: Describe what {{player}} is doing right now like a nature documentary narrator. The group votes on who was better, and that person gives out 3 sips.',
  '{{player}} vs. {{player}}: Sing your shopping list as a country song. Whoever is less convincing drinks 3 sips.',
  '{{player}} vs. {{player}}: Make a pilot announcement before landing. The group picks the best one, and the loser drinks 3 sips.',
  '{{player}} vs. {{player}}: Roar like a dinosaur. The group decides who was scarier, and that person gives out 3 sips.',
  '{{player}} vs. {{player}}: Act like a cat that desperately wants food. Whoever is worse drinks 3 sips.',
  '{{player}} vs. {{player}}: Strut around the table once like models on a runway. The group picks the winner, who gives out 4 sips.',
  '{{player}} vs. {{player}}: Show your best goal celebration in slow motion. Whoever is less convincing drinks 3 sips.',
  '{{player}} vs. {{player}}: Shoot a 15 second commercial for tap water. The group votes, and the winner gives out 3 sips.',
  '{{player}} vs. {{player}}: Commentate a curling match as excitingly as possible. Whoever was less exciting drinks 3 sips.',
  '{{player}} vs. {{player}}: Make the sound of a motorcycle starting up. The group picks the better one, and the loser drinks 2 sips.',
  '{{player}} vs. {{player}}: Do your best seal impression. Whoever sounds more real gives out 3 sips.',
  '{{player}} vs. {{player}}: Give a 15 second speech as a motivational coach. Whoever fires up the group more gives out 4 sips.',
  '{{player}} vs. {{player}}: Announce each other like a boxing ring announcer. The group votes on who was louder and better, and that person gives out 3 sips.',
  '{{player}} vs. {{player}}: Sell the group a pen in 20 seconds. Whoever is less convincing drinks 3 sips.',
  '{{player}} vs. {{player}}: Come up with the best excuse for being late to the party. The group votes, and the loser drinks 3 sips.',
  '{{player}} vs. {{player}}: Come up with a name for a new cocktail. The group picks the better one, and the winner gives out 3 sips.',

  'Group vote: Who\'s more likely to run a marathon, {{player}} or {{player}}? Whoever gets more votes gives out 3 sips.',
  'Group vote: Who\'s the better dancer, {{player}} or {{player}}? The winner gives out 3 sips, and the other drinks 2.',
  'Group vote: Who\'s the better cook, {{player}} or {{player}}? Whoever gets fewer votes drinks 3 sips.',
  'Group vote: Who has the better poker face, {{player}} or {{player}}? The winner gives out 3 sips.',
  'Group vote: Who would survive longer in a zombie apocalypse, {{player}} or {{player}}? The loser drinks 3 sips.',
  'Group vote: Who\'s more likely to become famous, {{player}} or {{player}}? Whoever gets more votes gives out 4 sips.',
  'Group vote: Who\'s more likely to win a game show, {{player}} or {{player}}? The winner gives out 3 sips.',
  'Group vote: Who has the more contagious laugh, {{player}} or {{player}}? Whoever gets more votes gives out 3 sips.',
  'Group vote: Who would get out of an escape room faster, {{player}} or {{player}}? The loser drinks 3 sips.',
  'Group vote: Who grabs the mic first at karaoke, {{player}} or {{player}}? Whoever gets more votes drinks 2 sips and gives out 2.',
  'Group vote: Who would last longer on a desert island, {{player}} or {{player}}? The winner gives out 3 sips.',
  'Group vote: Who\'s better at finding their way without GPS, {{player}} or {{player}}? Whoever gets fewer votes drinks 3 sips.',
  'Group vote: Who tells the better jokes, {{player}} or {{player}}? The winner gives out 3 sips.',
  'Group vote: Who would make the better tour guide, {{player}} or {{player}}? The loser drinks 3 sips.',
  'Group vote: Who\'s first on the dance floor, {{player}} or {{player}}? Whoever gets more votes gives out 3 sips.',
  'Group vote: Who would have the cooler superpowers, {{player}} or {{player}}? Whoever gets fewer votes drinks 3 sips.',
  'Group vote: Who\'s more likely to start a band, {{player}} or {{player}}? Whoever gets more votes gives out 3 sips.',
  'Group vote: Who\'s better at keeping a secret, {{player}} or {{player}}? The winner gives out 4 sips.',
  'Group vote: Who would have the better ideas as mayor, {{player}} or {{player}}? The loser drinks 3 sips.',
  'Group vote: Who has the better taste in music, {{player}} or {{player}}? The winner gives out 3 sips.',
  'Group vote: Who would make the better secret agent, {{player}} or {{player}}? Whoever gets fewer votes drinks 3 sips.',
  'Group vote: Who throws the better party, {{player}} or {{player}}? The winner gives out 4 sips.',

  '{{player}} vs. {{player}}: Whoever has more battery left right now gives out 2 sips.',
  '{{player}} vs. {{player}}: Compare your screen time from yesterday. Whoever has more drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever types "Tonight is an absolutely wonderful evening" into their phone faster without a typo gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever points out 5 red things in the room first gives out 3 sips.',
  '{{player}} vs. {{player}}: Name the other person\'s eye color without looking. Whoever gets it wrong drinks 3 sips.',
  '{{player}} vs. {{player}}: Whoever correctly names more birthdays of the people at the table gives out 4 sips.',
  '{{player}} vs. {{player}}: Describe your perfect Sunday in exactly 5 words. The group picks the nicer one, and the winner gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever first shows something from their own pocket or bag that starts with K gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever first guesses how many fingers {{player}} is holding up behind their back gives out 2 sips. Best of 3.',
  '{{player}} vs. {{player}}: Whoever drinks 3 sips and puts their glass back down faster gives out 3 sips.',
  '{{player}} vs. {{player}}: Both say a number between 1 and 10 at the same time. Whoever is closer to the number {{player}} is thinking of gives out 3 sips.',
  '{{player}} vs. {{player}}: {{player}} slowly lists 10 items. Whoever remembers more of them gives out 3 sips.',
  '{{player}} vs. {{player}}: Look at the table for 10 seconds, then close your eyes while {{player}} takes something away. Whoever says what\'s missing first gives out 3 sips.',
  '{{player}} vs. {{player}}: Whoever first sings a song with an animal in the title gives out 3 sips.',
  '{{player}} vs. {{player}} vs. {{player}}: Whoever stands on one leg longest while singing a song gives out 4 sips.',
  '{{player}} vs. {{player}} vs. {{player}}: Take turns naming countries that start with B. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}} vs. {{player}}: Three-way staring contest. Whoever blinks first drinks 3 sips.',
  '{{player}} vs. {{player}} vs. {{player}}: Take turns naming things that are green. Whoever passes first drinks 3 sips.',
  '{{player}} vs. {{player}} vs. {{player}}: Word chain with animals, each new animal starts with the last letter of the one before. Whoever stalls drinks 3 sips.',
];
