export const normalTasksEn: string[] = [
  // Solo tasks
  '{{player}}, tell a joke. If at least one person laughs, give out 3 sips. Otherwise drink 2.',
  '{{player}}, say the alphabet backwards down to the letter M or drink 3 sips.',
  '{{player}}, name 5 countries starting with A in 15 seconds. If you make it, give out 3 sips. If not, drink 3.',
  '{{player}}, do 10 squats or drink 3 sips.',
  '{{player}}, sing the chorus of your favorite song. Then give out 2 sips.',
  '{{player}}, do your best news anchor reading tomorrow\'s weather forecast or drink 2 sips.',
  '{{player}}, for the next 3 cards you can only whisper. Every time you get loud, drink 1 sip.',
  '{{player}}, give every person here a compliment. Then you get to give out 3 sips.',
  '{{player}}, balance on one leg with your eyes closed for 10 seconds. If you can\'t, drink 2 sips.',
  '{{player}}, name 6 four-legged animals in 10 seconds or drink 2 sips.',
  '{{player}}, say this tongue twister 3 times without a mistake: Peter Piper picked a peck of pickled peppers. Trip over it and drink 2 sips.',
  '{{player}}, describe what you ate today in one sentence, like a Michelin star chef. Then give out 2 sips.',
  '{{player}}, reveal your most embarrassing favorite song or drink 3 sips.',
  '{{player}}, act out your morning using only sounds. Whoever figures out what you\'re doing first gives out 2 sips.',
  '{{player}}, drink 2 sips, then pick a drinking buddy who drinks with you every time you drink for the next 3 cards.',
  '{{player}}, give out 4 sips however you like.',
  '{{player}}, drink as many sips as your first name has syllables.',
  '{{player}}, talk in an accent of your choice for 1 minute. If you slip out of it, drink 2 sips.',
  '{{player}}, name 3 things in your pocket or bag right now without looking. Get one wrong and drink 2 sips.',
  '{{player}}, do your best robot dance for 10 seconds or drink 3 sips.',
  '{{player}}, come up with an ad slogan for the drink in your hand. If the group likes it, give out 3 sips.',
  '{{player}}, for the next 3 cards you can only talk about yourself in the third person. Every slip costs 1 sip.',
  '{{player}}, imitate an animal of your choice. If the group guesses it within 10 seconds, give out 2 sips. Otherwise drink 2.',
  '{{player}}, if you have siblings, give out 2 sips. Otherwise drink 2.',
  '{{player}}, say only words starting with B for 10 seconds without stopping, or drink 2 sips.',
  '{{player}}, reveal the last show you binge-watched or drink 2 sips.',
  '{{player}}, do 10 jumping jacks in a row or drink 3 sips.',
  '{{player}}, hold one hand above your head for 1 minute. If you put it down, drink 3 sips.',
  '{{player}}, sing Twinkle Twinkle Little Star like an opera star or drink 3 sips.',
  '{{player}}, tell your favorite story from your school days in 30 seconds or drink 3 sips.',
  '{{player}}, make up a two-line poem about your drink. If it rhymes, give out 2 sips.',
  '{{player}}, describe your dream vacation in 3 words. Then everyone who\'d come along drinks 1 sip.',
  '{{player}}, say one word to each player that describes them well. Then give out 2 sips.',
  '{{player}}, guess the exact time to the minute without looking. If you\'re more than 10 minutes off, drink 2 sips.',
  '{{player}}, if you\'ve ever baked a cake yourself, give out 2 sips.',
  '{{player}}, you have 20 seconds to explain why Monday is actually the best day of the week. If you convince the group, give out 3 sips.',
  '{{player}}, do 5 push-ups or drink 3 sips.',
  '{{player}}, for the next 3 cards you can only drink with your weaker hand. If someone catches you, drink 2 extra sips.',
  '{{player}}, be a sports commentator calling the play as someone lifts their glass. Then give out 2 sips.',
  '{{player}}, name your all-time favorite movie. Everyone who loves it too drinks 1 sip with you.',
  '{{player}}, if you\'ve ever been in the front row at a concert, give out 3 sips.',
  '{{player}}, if you have a pet, show the group a photo of it and give out 2 sips. Otherwise drink 1.',
  '{{player}}, tell us the first thing you\'d buy with a million dollars. The group votes on whether it\'s a good choice. If not, drink 2 sips.',
  '{{player}}, name 4 pizza toppings in 5 seconds or drink 2 sips.',
  '{{player}}, your glass is now your microphone. Give a short acceptance speech for an award you make up. Then give out 3 sips.',
  '{{player}}, if you\'ve worked out today, give out 3 sips. Otherwise drink 1.',
  '{{player}}, let the group pick a word you have to work into your next sentence. If you can\'t, drink 2 sips.',
  '{{player}}, hold eye contact with the person on your right for 20 seconds. Whoever laughs first drinks 2 sips.',
  '{{player}}, if you\'ve ever won a trophy or a medal, give out 3 sips.',

  // Two players
  '{{player}} and {{player}}, rock, paper, scissors. The loser drinks 2 sips.',
  '{{player}} and {{player}}, thumb war. The loser drinks 3 sips.',
  '{{player}} and {{player}}, staring contest. Whoever blinks first drinks 2 sips.',
  '{{player}} and {{player}}, take turns naming car brands. Whoever runs out first drinks 3 sips.',
  '{{player}} and {{player}}, clink glasses and both drink 2 sips.',
  '{{player}} and {{player}}, you\'re drinking partners for the next 3 cards. When one drinks, the other drinks too.',
  '{{player}} and {{player}}, first to name 3 vegetables starting with C gives out 2 sips.',
  '{{player}}, do your best impression of {{player}}. If the group laughs, give out 3 sips.',
  '{{player}} and {{player}}, who has bigger hands? Hold them up against each other. The smaller hand drinks 2 sips.',
  '{{player}} and {{player}}, both say a color at the same time. If it\'s the same one, you each give out 3 sips. Otherwise you each drink 1.',
  '{{player}}, guess {{player}}\'s favorite food. If you\'re right, give out 3 sips. Otherwise drink 2.',
  '{{player}} and {{player}}, stare at each other without laughing. Whoever laughs first drinks 3 sips.',
  '{{player}}, give {{player}} an honest compliment. Then you both drink 1 sip.',
  '{{player}} and {{player}}, who\'s walked more steps today? Check your phones. The lazier one drinks 2 sips.',
  '{{player}}, guess {{player}}\'s birth month. A wrong guess means 2 sips for you.',
  '{{player}} and {{player}}, strike a pose at the same time. The group picks the better one. The other drinks 2 sips.',
  '{{player}}, how many siblings does {{player}} have? Guess wrong and drink 2 sips.',
  '{{player}} and {{player}}, take turns naming European capitals. Whoever runs out first drinks 3 sips.',
  '{{player}}, describe {{player}} in 3 words. If they don\'t like your words, drink 2 sips.',
  '{{player}} and {{player}}, pinky arm wrestle. The loser drinks 2 sips.',
  '{{player}}, ask {{player}} a yes or no question. If the answer is yes, they drink 2 sips.',
  '{{player}}, decide whether {{player}} or {{player}} has the better dance move. They both show it off quickly and the loser drinks 2 sips.',
  '{{player}}, decide who has the best reading voice: {{player}} or {{player}}. That person gives out 3 sips.',

  // Votes
  'Vote: Who\'s most likely to fall asleep first during a movie? That person drinks 2 sips.',
  'Vote: Who\'s most likely to leave their phone in the fridge? That person drinks 2 sips.',
  'Vote: Who\'s most likely to win a cooking show? That person gives out 3 sips.',
  'Vote: Who\'s most likely to win a million on a game show? That person gives out 3 sips.',
  'Vote: Who\'s most likely to show up late to their own party? That person drinks 3 sips.',
  'Vote: Who\'s most likely to survive a zombie apocalypse? That person gives out 3 sips.',
  'Vote: Who\'s most likely to drive in circles without GPS? That person drinks 2 sips.',
  'Vote: Who\'s most likely to cry at a romantic movie? That person drinks 2 sips.',
  'Vote: Who\'s most likely to eat the same meal every day? That person drinks 2 sips.',
  'Vote: Who\'s most likely to go on a talent show? That person drinks 2 sips.',
  'Vote: Who\'s most likely to end up with 20 cats? That person drinks 2 sips.',
  'Vote: Who\'s most likely to forget their own birthday? That person drinks 3 sips.',
  'Vote: Who\'s most likely to set a world record? That person gives out 3 sips.',
  'Vote: Who has the best outfit on today? That person gives out 4 sips.',
  'Vote: Who has the loudest laugh here? That person drinks 2 sips.',
  'Vote: Who\'s most likely to hog the mic at karaoke? That person drinks 2 sips.',
  'Vote: Who\'s most likely to forget the shopping list at the supermarket? That person drinks 2 sips.',
  'Vote: Who\'s most likely to survive a week without their phone? That person gives out 3 sips.',
  'Vote: Who\'s the best host here? That person gives out 3 sips.',
  'Vote: Who\'s most likely to snag a selfie with a celebrity? That person gives out 2 sips.',
  'Vote: Who\'s most likely to watch a whole season in one day? That person drinks 2 sips.',
  'Vote: Who\'s most likely to take the wrong turn on a hike? That person drinks 2 sips.',
  'Vote: Who\'s most likely to write a book? That person gives out 2 sips.',
  'Vote: Who has the most contagious laugh? That person gives out 3 sips.',
  'Vote: Who\'s most likely to cheat at Monopoly? That person drinks 3 sips.',
  'Vote: Who\'s most likely to be first on the dance floor? That person gives out 2 sips.',
  'Vote: Who\'s most likely to travel the world with no plan? That person gives out 2 sips.',
  'Vote: Who\'s most likely to look for their keys while holding them? That person drinks 2 sips.',
  'Vote: Who would make the best tour guide? That person gives out 3 sips.',
  'Vote: Who\'s the grumpiest in the morning? That person drinks 2 sips.',
  'Vote: Who has the best taste in music here? That person picks the next song and gives out 2 sips.',
  'Vote: Who\'s most likely to stay in pajamas all day? That person drinks 2 sips.',
  'Vote: Who sends the longest voice messages? That person drinks 3 sips.',
  'Vote: Who would make the best detective? That person gives out 3 sips.',
  'Vote: Pizza or burgers? The minority drinks 2 sips.',
  'Vote: Beach or mountains? The minority drinks 2 sips.',
  'Vote: Dogs or cats? The minority drinks 2 sips.',
  'Vote: Summer or winter? The minority drinks 2 sips.',
  'Vote: Early bird or night owl? The minority drinks 2 sips.',
  'Vote: Sweet or salty? The minority drinks 2 sips.',
  'Vote: Pineapple on pizza, yes or no? The minority drinks 3 sips.',
  'Vote: Would you rather be invisible or be able to fly? The minority drinks 2 sips.',
  'Vote: Would you rather never listen to music again or never watch a movie again? The minority drinks 2 sips.',
  'Vote: Would you rather live in the past or in the future? The minority drinks 2 sips.',
  'Vote: Would you rather have rain every day or 35 degrees Celsius every day? The minority drinks 2 sips.',
  'Vote: Would you rather talk to animals or speak every language in the world? The minority drinks 2 sips.',

  // Everyone who ...
  'Everyone who\'s ever fallen asleep in a movie theater drinks 2 sips.',
  'Everyone who\'s ever lost their keys drinks 1 sip.',
  'Everyone who\'s had more than 3 coffees today drinks 2 sips.',
  'Everyone who\'s ever been on vacation abroad drinks 1 sip.',
  'Everyone who can play an instrument gives out 2 sips.',
  'Everyone who\'s ever been to a concert drinks 1 sip.',
  'Everyone who hits the snooze button on their alarm drinks 2 sips.',
  'Everyone who\'s ever taken a selfie with a celebrity gives out 3 sips.',
  'Everyone who wears glasses or contacts drinks 1 sip.',
  'Everyone who\'s already danced today gives out 2 sips.',
  'Everyone who\'s ever screamed on a roller coaster drinks 2 sips.',
  'Everyone holding their phone right now drinks 2 sips.',
  'Everyone with a winter birthday drinks 2 sips.',
  'Everyone with a summer birthday gives out 2 sips.',
  'Everyone who came by bike gives out 2 sips.',
  'Everyone who\'s ever eaten a whole pizza alone drinks 2 sips.',
  'Everyone who sings in the shower drinks 2 sips.',
  'Everyone who\'s read Harry Potter drinks 1 sip.',
  'Everyone who\'s ever run a marathon or half marathon gives out 3 sips.',
  'Everyone who\'s ever missed a train drinks 2 sips.',
  'Everyone with more than 1000 unread emails drinks 2 sips.',
  'Everyone who\'s ever forgotten they were unmuted on a video call drinks 2 sips.',
  'Everyone who likes pineapple on pizza drinks 2 sips.',
  'Everyone who\'s ever been skiing or snowboarding drinks 1 sip.',
  'Everyone who has a nickname drinks 1 sip.',
  'Everyone who\'s hugged someone today gives out 2 sips.',
  'Everyone who\'s ever rescued an animal gives out 3 sips.',
  'Everyone who\'s ever burned something while cooking drinks 2 sips.',
  'Everyone with a green thumb who keeps their plants alive gives out 2 sips.',
  'Everyone who\'s ever slept in a tent drinks 1 sip.',
  'Everyone with a tattoo drinks 1 sip.',
  'Everyone who\'s an only child gives out 2 sips.',
  'Everyone who\'s the oldest sibling drinks 2 sips.',
  'Everyone who speaks more than 2 languages gives out 3 sips.',
  'Everyone who\'s ever ridden a horse drinks 1 sip.',
  'Everyone who\'s taken a nap today drinks 2 sips.',
  'Everyone who\'s ever sung the wrong lyrics to a song without noticing drinks 2 sips.',
  'Everyone wearing black today drinks 1 sip.',
  'Everyone who\'s ever waved back at someone who wasn\'t waving at them drinks 2 sips.',
  'Everyone who\'s ever told a joke nobody laughed at drinks 2 sips.',
  'Everyone with more than 5 browser tabs open drinks 2 sips.',

  // Mini games
  'Categories: Fruits. Go around the circle, everyone names one. Anyone who hesitates or repeats drinks 2 sips.',
  'Categories: Football clubs. Go around the circle, everyone names one. First to pass drinks 2 sips.',
  'Categories: Disney movies. Go around the circle, everyone names one. Whoever gets stuck drinks 2 sips.',
  'Categories: Things you find in a bathroom. Whoever runs out of ideas drinks 2 sips.',
  'Categories: Ice cream flavors. Go around the circle, everyone names one. Whoever passes drinks 2 sips.',
  'Categories: Sports played with a ball. First one stumped drinks 2 sips.',
  'Categories: Famous female singers. Go around the circle, everyone names one. Whoever gets stuck drinks 2 sips.',
  'Categories: Board games. Go around the circle, everyone names one. Whoever passes drinks 2 sips.',
  'Categories: Superheroes. Go around the circle, everyone names one. Whoever gets stuck drinks 2 sips.',
  'Categories: Zoo animals. First to pass drinks 2 sips.',
  'Categories: Simpsons characters. First one who runs out drinks 2 sips.',
  'Categories: Things you take to the beach. Whoever gets stuck drinks 2 sips.',
  'Categories: Countries in Africa. First one stuck drinks 3 sips.',
  'Categories: Jobs. Go around the circle, everyone names one. Anyone who hesitates drinks 2 sips.',
  'Categories: Car brands. First one who runs out drinks 2 sips.',
  'Categories: Kids\' TV shows from back in the day. Whoever gets stuck drinks 2 sips.',
  'Rhyme chain: {{player}} starts with the word house. Going around, everyone says a word that rhymes. Whoever can\'t find one drinks 2 sips.',
  'Rhyme chain: {{player}} starts with the word cat. Whoever can\'t find a rhyme drinks 2 sips.',
  'Rhyme chain: {{player}} starts with the word beer. Whoever gets stuck drinks 2 sips.',
  'Word chain: {{player}} says a word, the next person says a word starting with its last letter. Whoever gets stuck drinks 2 sips.',
  'Compound word chain: {{player}} starts with football, the next person says ballroom, and so on. Whoever gets stuck drinks 2 sips.',
  'Waterfall: {{player}} starts drinking, everyone else follows clockwise. Nobody can stop until the person before them stops.',
  'Mini waterfall: Everyone starts drinking at the same time. First one to put their glass down drinks 1 more sip afterwards.',
  'Rock, paper, scissors tournament: Everyone plays in pairs. The losers keep playing until one is left. That person drinks 3 sips.',
  'Counting round: Count to 30 around the circle. For every number that has a 7 in it or is divisible by 7, say beer instead. Mess up and drink 2 sips.',
  'I\'m going on a picnic: {{player}} starts. Everyone repeats the whole list and adds one item. Forget something and drink 3 sips.',
  'Telephone: {{player}} whispers a sentence into the ear of the person on their left. If something different comes out at the end, everyone drinks 1 sip.',
  'Charades: {{player}}, act out a movie. Whoever guesses it gives out 2 sips. If nobody gets it within 30 seconds, you drink 2 sips.',
  'Charades: {{player}} acts out a job. First to guess right gives out 2 sips.',
  'Charades: {{player}} acts out an animal, no sounds allowed. First to guess right gives out 2 sips.',
  'Charades: {{player}} acts out an everyday situation, like brushing teeth or parallel parking. Whoever guesses it gives out 2 sips.',
  'Humming: {{player}}, hum a well-known song. First to guess it gives out 3 sips. If nobody gets it, you drink 2 sips.',
  'I spy: {{player}} starts. Whoever guesses it gives out 2 sips. After 5 wrong guesses, everyone drinks 1 sip.',
  'Who am I: {{player}} thinks of a celebrity. The group asks yes or no questions. If nobody gets it after 10 questions, everyone else drinks 2 sips.',
  'Thumbs down: Last one to put their thumb on the table drinks 2 sips.',
  'Nose goes: Last one to touch their finger to their nose drinks 2 sips.',
  'Last one to put both hands in the air drinks 2 sips.',
  'Last one to touch their glass drinks 2 sips.',
  'Last one to shout cheers drinks 2 sips.',
  'No yes, no no: {{player}} asks everyone a question. Anyone who answers with yes or no drinks 2 sips.',
  'Letter round: Going around, everyone names an animal that starts with the first letter of their first name. Whoever can\'t think of one drinks 2 sips.',
  'Alphabet round: Going around, everyone names a food that starts with the next letter of the alphabet. Whoever gets stuck drinks 2 sips.',
  'No laughing: For 30 seconds nobody is allowed to laugh while {{player}} pulls faces. Anyone who laughs drinks 2 sips.',
  'Story time: {{player}} starts a story with one sentence. Going around, everyone adds a sentence. Whoever gets stuck drinks 2 sips.',
  'Tongue twister round: Going around, everyone says red lorry, yellow lorry 5 times fast. Trip over it and drink 2 sips.',
  'Higher or lower: {{player}} thinks of a number from 1 to 100. Everyone takes turns guessing. Whoever gets it gives out 5 sips.',
  'Blink round: Everyone looks at each other. First one to blink drinks 2 sips.',
  'Hands on the table: Everyone puts their hands flat down and lifts them on {{player}}\'s command. Lift too early and drink 2 sips.',
  'Opposites: {{player}} goes around saying a word to each person. They have to say the opposite right away. Anyone who hesitates drinks 1 sip.',
  'Clap the beat: {{player}} claps a rhythm. Going around, everyone copies it. Get it wrong and drink 1 sip.',
  '5 seconds: {{player}}, name 3 things you find in a kitchen. If you can\'t, drink 2 sips.',
  '5 seconds: {{player}}, name 3 things that can fly. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 fairy tales. Otherwise drink 2 sips.',

  // Knowledge and quick thinking
  '{{player}} looks up a quiz question on their phone and asks {{player}}. Right means giving out 3 sips, wrong means drinking 2.',
  'Quick quiz for everyone: {{player}} looks up a quiz question on their phone and reads it out. First correct answer gives out 3 sips.',
  '{{player}}, what\'s the capital of Canada? {{player}} checks on their phone. Right means giving out 3 sips, wrong means drinking 2.',
  '{{player}}, how many hearts does an octopus have? {{player}} checks on their phone. Right means giving out 3 sips, wrong means drinking 2.',
  '{{player}}, what year did the Berlin Wall fall? {{player}} checks on their phone. Right means giving out 3 sips, wrong means drinking 2.',
  '{{player}}, what\'s the longest river in the UK? {{player}} checks on their phone. Right means giving out 3 sips, wrong means drinking 2.',
  'Quiz question for {{player}}: Name all 12 zodiac signs. The group keeps count. Drink 1 sip for each one you miss, 4 at most.',
  'Quiz question for {{player}}: List the planets in our solar system. The group checks. Miss one and drink 2 sips.',
  '5 seconds: {{player}}, name 3 things you pack for a vacation. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 sports without a ball. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 things that smell like Christmas. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 animals that live in water. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 cartoon characters. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 things you see at a wedding. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 words that rhyme with nose. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 card games. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 things you can buy at the movies. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 jobs where you wear a uniform. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 reasons Mondays suck. Otherwise drink 2 sips.',
  '5 seconds: {{player}}, name 3 things you should never put in your mouth. Otherwise drink 2 sips.',
  '{{player}}, spell your first and last name backwards. Trip up and drink 2 sips.',
  '{{player}}, say the months backwards, from December to January. Get it right and give out 2 sips. Otherwise drink 2.',
  '{{player}}, name 5 colors in a language other than English in 10 seconds or drink 2 sips.',
  '{{player}}, name an animal for each letter of your first name. Do it without hesitating and give out 3 sips. Otherwise drink 2.',
  '{{player}}, count by 3s up to 30 as fast as you can. Mess up and drink 2 sips.',
  '{{player}}, explain how to fry an egg in 20 seconds without saying egg or pan. If one slips out, drink 2 sips.',
  '{{player}}, pick an animal that suits each person here. Then give out 2 sips.',
  '{{player}}, come up with a band name for this group in 10 seconds. If the group likes it, give out 2 sips.',
  '{{player}}, name 3 songs with a city in the title. If you can\'t, drink 2 sips.',
  '{{player}}, say 5 words starting with Z in 10 seconds or drink 2 sips.',
  '{{player}}, count down from 20 to 0, skipping every odd number. Mess up and drink 2 sips.',

  // Guessing
  '{{player}}, guess how many countries there are in the world. {{player}} looks it up. If you\'re more than 10 off, drink 2 sips.',
  '{{player}}, guess how tall the Eiffel Tower is. {{player}} looks it up. If you\'re more than 50 meters off, drink 2 sips.',
  '{{player}}, guess how many bones an adult human has. {{player}} looks it up. If you\'re more than 30 off, drink 2 sips.',
  'Everyone guesses how old {{player}} is in months. Whoever gets closest gives out 3 sips.',
  'Everyone guesses how tall {{player}} is in centimeters. Whoever is furthest off drinks 2 sips.',
  'Everyone guesses how many photos {{player}} has on their phone. Then check. Whoever gets closest gives out 3 sips.',
  '{{player}}, guess {{player}}\'s shoe size. If you\'re right, give out 3 sips. Otherwise drink 2.',
  '{{player}}, guess {{player}}\'s favorite drink. A wrong guess means 2 sips for you.',
  '{{player}} thinks of a number from 1 to 10. {{player}} gets one guess. Right means giving out 3 sips, wrong means drinking 2.',
  '{{player}}, guess what color {{player}}\'s phone is without looking. A wrong guess means 2 sips.',
  'Everyone guesses how many steps {{player}} has walked today. Whoever is furthest off drinks 2 sips.',
  '{{player}}, guess how long you can hold your breath, then try it. If you don\'t make it, drink 2 sips.',
  '{{player}}, without a clock, call out when 30 seconds are up. The group times you. If you\'re more than 5 seconds off, drink 2 sips.',

  // Rules
  'New rule for the next 3 cards: Nobody can say the word drink. Anyone who does drinks 1 sip.',
  'New rule for the next 3 cards: Everyone drinks with their left hand only. Forget and drink 1 extra sip.',
  'New rule for the next 3 cards: Nobody can look at their phone. Anyone who does drinks 2 sips.',
  'New rule for the next 3 cards: You have to say cheers before every sip. Forget and drink 1 extra sip.',
  'New rule for the next 3 cards: Nobody can say anyone\'s name. Anyone who does drinks 1 sip.',
  'New rule for the next 3 cards: Anyone who swears drinks 1 sip.',
  'New rule for the next 3 cards: {{player}} is the king of the table. Anyone who doesn\'t address the king as Your Majesty drinks 1 sip.',
  'New rule for the next 3 cards: You have to raise your hand before you laugh. Otherwise it\'s 1 sip.',
  'New rule for the next 3 cards: Yes and no are banned. Every slip costs 1 sip.',
  'New rule for the next 3 cards: {{player}} is the thumb master. When the thumb master secretly puts their thumb on the table, everyone copies. The last one drinks 2 sips.',
  'New rule for the next 3 cards: {{player}} is the question master. Anyone who answers a question from the question master drinks 1 sip.',
  'New rule for the next 3 cards: Everyone has to tap their glass before drinking. Forget and drink 1 extra sip.',
  'New rule for the next 3 cards: Everyone talks in a deep voice. Forget and drink 1 sip.',
  'New rule for the next 3 cards: {{player}} can shout freeze at any time. Last one to freeze drinks 2 sips.',
  'New rule for the next 3 cards: The word I is banned. Every slip costs 1 sip.',
  'New rule for the next 3 cards: {{player}} and {{player}} can only talk to each other. If either talks to anyone else, they drink 1 sip.',

  // Whole group
  'Everyone clink glasses and drink 2 sips to tonight.',
  'Everyone whose glass is fuller than {{player}}\'s right now drinks 2 sips.',
  'Everyone point at the person who\'s laughed the most today. That person gives out 3 sips.',
  'Everyone point at the same time at the person who takes the longest to get ready. That person drinks 2 sips.',
  'The person with the longest first name drinks 2 sips.',
  'The person with the shortest first name gives out 2 sips.',
  'Whoever has the next birthday gives out 3 sips.',
  'Whoever traveled the furthest to get here gives out 3 sips.',
  'The tallest person here drinks 2 sips, the shortest gives out 2.',
  'Whoever has the lowest phone battery drinks 2 sips.',
  'Whoever is wearing the most rings gives out 2 sips.',
  'Whoever ate most recently drinks 1 sip.',
  'The youngest person here gives out 3 sips.',
  'The oldest person here gets to make up a new mini rule for the next 3 cards.',
  'Everyone swaps seats with the person on their right. Last one to sit down drinks 2 sips.',
  'Everyone hold up your glass. Whoever has the emptiest glass drinks 1 sip and gets a refill.',
  'Everyone says their favorite season at the same time. Anyone who\'s alone with their answer drinks 2 sips.',
  'Everyone puts their phone in the middle. Last one done drinks 2 sips.',
  'Toast time: {{player}} makes a short toast. Then everyone drinks 2 sips.',
  'Imaginary group photo: Everyone strikes their best pose at the same time. The group picks the weakest. That person drinks 2 sips.',
  'Everyone sitting with their legs crossed right now drinks 1 sip.',
  'Everyone smiling right now gets to give out 1 sip.',
  'Everyone names their favorite food. Anyone who says the same as someone else drinks 1 sip with them.',
  'Everyone shows the last song they played in their music app. The group picks the most embarrassing one. That person drinks 2 sips.',
  'Going around, everyone says where they\'d love to live. The group picks the best answer. That person gives out 3 sips.',
  'Everyone gives 1 sip to the person they\'ve talked to the most today.',
  'Everyone gives 1 sip to the person on their left.',
  'Everyone gives 2 sips to the person on their right.',
];
