export const partyTasksEn: string[] = [
  'Waterfall! {{player}} starts, everyone drinks along and only stops once the person to their left stops.',
  'Reverse waterfall: {{player}} starts, and the group joins in one by one counterclockwise. Nobody can stop before the person before them has stopped.',
  'Mini waterfall: Everyone drinks at the same time, and whoever stops first drinks 2 more sips.',
  'Waterfall with music: Everyone drinks while {{player}} hums a song. You can only stop once the humming stops.',
  'Categories! {{player}} picks a category, and everyone takes turns naming something in it. Hesitate or repeat and you drink 2 sips.',
  'Category: Car brands. {{player}} starts, then it goes around the circle. Whoever runs out drinks 3 sips.',
  'Category: Beer styles and beer brands. {{player}} starts. Whoever gets stuck drinks 2 sips.',
  'Category: Disney movies. {{player}} starts. Whoever can\'t think of one drinks 2 sips.',
  'Category: Cocktails. {{player}} starts. Whoever stalls drinks 2 sips.',
  'Category: Football clubs. {{player}} starts the round. Whoever has to pass drinks 3 sips.',
  'Category: Capital cities. {{player}} starts. Whoever names a wrong one or a repeat drinks 2 sips.',
  'Category: Pokémon. {{player}} starts. Whoever can\'t think of one drinks 2 sips.',
  'Category: Things you find at a party. {{player}} starts. Whoever gets stuck drinks 2 sips.',
  'Category: Superheroes. {{player}} starts. Whoever runs out drinks 2 sips.',
  'Category: Singers known by just one name, like Adele. {{player}} starts. Whoever blanks drinks 3 sips.',
  'Category: Types of cheese. {{player}} starts the round. Whoever gets stuck drinks 2 sips.',
  'Category: Shows on Netflix. {{player}} starts. Whoever runs out drinks 2 sips.',
  'Category: Words that rhyme with "drink". {{player}} starts. Whoever can\'t find one drinks 2 sips.',
  'Category: Types of liquor. {{player}} starts. Whoever runs out drinks 2 sips.',
  'Category: Harry Potter characters. {{player}} starts. Whoever stalls drinks 2 sips.',
  'Category: Video games. {{player}} starts. Whoever can\'t think of one drinks 2 sips.',
  'Category: Famous bands. {{player}} starts. Whoever has to pass drinks 2 sips.',
  'Category: Marvel movies. {{player}} starts. Whoever stalls drinks 2 sips.',
  'Category: Dance styles. {{player}} starts. Whoever runs out drinks 2 sips.',
  'Category: Musical instruments. {{player}} starts. Whoever gets stuck drinks 2 sips.',
  'Category: Things you do at the beach. {{player}} starts. Whoever stalls drinks 2 sips.',
  'I\'m going on a picnic! {{player}} starts, and everyone repeats the whole list and adds one item. Whoever makes a mistake drinks 3 sips.',
  'I\'m going to a party and I\'m bringing... {{player}} starts, and everyone adds to the list in turn. Whoever forgets something drinks 3 sips.',
  'I\'m mixing a cocktail and putting in... {{player}} starts with the first ingredient. Whoever messes up the list drinks 3 sips.',
  'Move chain: {{player}} does a gesture, and everyone repeats all the gestures so far and adds one. Whoever slips up drinks 3 sips.',
  'Sound chain: {{player}} makes a sound, and everyone repeats all the previous ones and adds one. Whoever gets it wrong drinks 2 sips.',
  'I\'m going on vacation to... {{player}} names a destination, and the trip gets longer with every turn. Whoever forgets a stop drinks 3 sips.',
  'Name chain: Taking turns, everyone says the first names of everyone at the table clockwise, as fast as possible. Whoever trips over their words drinks 2 sips.',
  'I went to the supermarket and bought... but in alphabetical order. {{player}} starts with A. Whoever loses track drinks 3 sips.',
  'Thumbs on the table! The last person to put their thumb on the edge of the table drinks 2 sips.',
  'Everyone point at the ceiling! Whoever points last drinks 2 sips.',
  'Hands up! The last person to raise their hands drinks 2 sips.',
  'Everyone touch your nose! Whoever touches their nose last drinks 2 sips.',
  'Everyone stand up! The last person to stand drinks 3 sips.',
  'Everyone clap 3 times! Whoever claps too late or too often drinks 2 sips.',
  'Glasses up! Whoever raises their glass last drinks 2 sips.',
  'Everyone shout "Cheers"! Whoever shouts last drinks 2 sips.',
  'Everyone throw up a peace sign! The last person drinks 2 sips.',
  'Everyone close your eyes! Whoever closes their eyes last drinks 2 sips.',
  'Everyone point at the person with the loudest laugh! Whoever gets the most fingers pointed at them drinks 2 sips.',
  'Everyone grab {{player}}\'s glass! Whoever reaches for it last drinks 2 sips.',
  'Everyone put your head on the table! The last person drinks 3 sips.',
  'Everyone salute! Whoever salutes last drinks 2 sips.',
  'Everyone give two thumbs up! Whoever is too slow drinks 2 sips.',
  'Everyone spin around once, on your chair or standing! Whoever finishes last drinks 2 sips.',
  'Everyone stomp your foot 2 times! Whoever falls out of rhythm drinks 2 sips.',
  'Whoever shouts "Pertolo" first gets to give out 3 sips.',
  'Whoever holds up something red first gets to give out 3 sips.',
  'Whoever points at {{player}} first gets to give out 2 sips.',
  'Whoever first names a song with "Love" in the title gets to give out 2 sips.',
  'Whoever touches something blue first gets to give out 2 sips. The last person drinks 2 sips.',
  'Whoever gives {{player}} a compliment first gets to give out 2 sips.',
  'Buzz! Count around the circle. For every number that contains a 7 or is divisible by 7, say "Buzz" instead. Whoever slips up drinks 2 sips.',
  'Buzz with 3: Count around the circle and clap instead of saying any number that contains a 3 or is divisible by 3. {{player}} starts. Mistakes cost 2 sips.',
  'Fizz Buzz: Say "Fizz" for numbers divisible by 3, "Buzz" for numbers divisible by 5, and "Fizz Buzz" for both. {{player}} starts. Whoever slips up drinks 2 sips.',
  'Count down from 30 around the circle, {{player}} starts. Whoever miscounts drinks 2 sips.',
  'Count to 20 together, but in no set order. If 2 people say a number at the same time, both drink 2 sips and you start over.',
  'Count to 20 in Spanish around the circle. Whoever makes a mistake or hesitates drinks 2 sips.',
  'Count around the circle in steps of 2 up to 50, {{player}} starts. Whoever slips up drinks 2 sips.',
  'Beer for 4: Count around the circle, but every 4 gets replaced with "Beer". Whoever forgets drinks 2 sips.',
  'Clap rhythm: {{player}} claps a rhythm, and everyone has to clap it back in turn. Whoever gets it wrong drinks 2 sips.',
  'Table drums: Everyone drums "We Will Rock You" on the table together. Whoever falls out of rhythm drinks 2 sips.',
  'Zip Zap Zop: {{player}} starts by sending "Zip" to someone, who passes on "Zap", then "Zop". Whoever messes it up drinks 2 sips.',
  'Alphabet around the circle: Everyone says the next letter, but backwards from Z. Whoever stalls drinks 2 sips.',
  'Animal alphabet around the circle: A for Alligator, B for Bear. {{player}} starts. Whoever gets stuck drinks 2 sips.',
  'Drinks alphabet around the circle: A for Aperol, B for Beer. {{player}} starts. Whoever stalls drinks 2 sips.',
  'Celebrity alphabet around the circle: A for Adele. {{player}} starts. Whoever can\'t think of one drinks 2 sips.',
  'Count to 10, and each person can say 1 to 3 numbers. Whoever has to say 10 drinks 3 sips. {{player}} starts.',
  'Clap, don\'t count: Count around the circle, but clap instead of saying every even number. Whoever slips up drinks 2 sips.',
  'Snap and clap: Take turns snapping and clapping around the circle. {{player}} starts. Whoever loses the rhythm drinks 2 sips.',
  'The wave! Everyone stands up briefly one after another, for 3 rounds, faster each time. Whoever is too slow drinks 2 sips.',
  '{{player}} hums the intro of a famous song. The group gets 3 guesses, otherwise everyone drinks 1 sip.',
  '{{player}} whistles a tune from a movie. Whoever guesses it gives out 2 sips.',
  '{{player}} sings a line, and {{player}} has to sing the next one. If they nail it, everyone else drinks 1 sip.',
  'Everyone sings the chorus of "I Gotta Feeling" together. Whoever doesn\'t sing along drinks 3 sips.',
  'Everyone sings "Country Roads" together. Whoever doesn\'t know the words drinks 2 sips.',
  'Everyone sings the chorus of "Bohemian Rhapsody" together, as dramatically as possible. The weakest performance drinks 2 sips.',
  'Everyone sings "We Are the Champions" together and clinks glasses on the chorus. Then everyone drinks 1 sip.',
  'Everyone sings "Sweet Caroline" together and yells the "Bah Bah Bah". Whoever isn\'t loud enough drinks 2 sips.',
  'Everyone sings the chorus of "Mr. Brightside". Whoever loses the words first drinks 2 sips.',
  'Everyone sings along to "Layla" by Eric Clapton. Whoever doesn\'t know the chorus drinks 2 sips.',
  'Everyone sings "Wonderwall" together. Whoever comes in at the wrong time drinks 2 sips.',
  'Everyone sings "Dancing Queen" by ABBA. Whoever doesn\'t join in drinks 3 sips.',
  'Everyone sings "99 Red Balloons". Whoever forgets the words first drinks 2 sips.',
  'Everyone sings "Don\'t Stop Believin\'". The person with the most off-key voice gets to give out 2 sips for being brave.',
  'Everyone sings "Hey Jude" and holds the "Na na na" as long as possible. Whoever stops first drinks 2 sips.',
  'Everyone sings "New York, New York". Whoever doesn\'t know the words drinks 2 sips.',
  'Everyone sings "Wannabe" by the Spice Girls. Whoever drops out during the rap part drinks 2 sips.',
  'Everyone sings "Livin\' on a Prayer" and goes up an octave on the chorus. Whoever chickens out drinks 2 sips.',
  'Everyone sings "I Will Survive". The most convincing singer gives out 3 sips.',
  'Everyone sings "Piano Man" and sways arm in arm. Whoever doesn\'t sway along drinks 2 sips.',
  'Everyone sings "Summer of \'69" together. Whoever botches the words drinks 2 sips.',
  'Everyone sings "Bella Ciao" and claps along. Whoever loses the beat drinks 2 sips.',
  'Everyone sings "Seven Nation Army" with no words, just the melody. Whoever laughs drinks 2 sips.',
  '{{player}} starts singing a song, and the group has to join in right away. Whoever doesn\'t sing along drinks 2 sips.',
  'Song chain: {{player}} names a song, and the next person names a song that starts with the last letter of that title. Whoever gets stuck drinks 2 sips.',
  'Category: Songs with a color in the title. {{player}} starts. Whoever can\'t think of one drinks 2 sips.',
  'Category: Songs with a number in the title. {{player}} starts. Whoever stalls drinks 2 sips.',
  'Category: One-hit wonders. {{player}} starts. Whoever runs out drinks 2 sips.',
  'Category: Songs with a name in the title, like "Billie Jean". {{player}} starts. Whoever hesitates drinks 2 sips.',
  'Category: Songs about alcohol. {{player}} starts. Whoever can\'t find one drinks 3 sips.',
  'Category: Songs from the 80s. {{player}} starts. Whoever stalls drinks 2 sips.',
  'Category: Songs from Disney movies. {{player}} starts. Whoever hesitates drinks 2 sips.',
  'Category: Cheesy party anthems. {{player}} starts. Whoever has to pass drinks 3 sips.',
  '{{player}} sings a famous song in an opera voice. Whoever guesses it first gives out 2 sips.',
  '{{player}} recites a song lyric with no melody, like a poem. Whoever guesses the song gives out 2 sips.',
  'Fill in the blank: {{player}} sings a famous line and leaves out the last word. Whoever fills it in first gives out 2 sips.',
  'Everyone plays air instruments at the same time to a song {{player}} hums. Whoever stops first drinks 2 sips.',
  'Beatbox round: Everyone beatboxes for 5 seconds in turn. The group picks the worst beat, and that person drinks 2 sips.',
  'Karaoke without music: {{player}} and {{player}} sing a chorus of their choice together. Then everyone else drinks 1 sip out of respect.',
  'Who knows more Taylor Swift songs? {{player}} and {{player}} take turns naming titles. Everyone else bets on the winner first. Whoever bets wrong drinks 2 sips.',
  'DJ round: {{player}} picks the next song. Whoever complains drinks 2 sips.',
  'Music stop: The next time the music gets quieter or a song ends, everyone shouts "Cheers". Whoever misses it drinks 2 sips.',
  'Whoever names the artist of the song playing right now first gives out 3 sips. If there\'s no music, {{player}} sings something.',
  'Chorus battle: Split into 2 teams. The teams take turns singing a chorus. The first team that can\'t think of one drinks 2 sips.',
  'Dance move! {{player}} shows a dance move, and everyone has to copy it. Whoever refuses drinks 3 sips.',
  'Everyone does the full Macarena once. Whoever slips up drinks 2 sips.',
  'Everyone does the floss for 10 seconds. The worst flosser drinks 2 sips.',
  'Everyone does the Chicken Dance together. Whoever doesn\'t join in drinks 3 sips.',
  'Everyone does the YMCA with their arms. Whoever gets a letter wrong drinks 2 sips.',
  'Everyone dances in their seat for 10 seconds. The group picks the best dancer, who gives out 3 sips.',
  'Robot dance: Everyone dances like a robot for 10 seconds. Whoever laughs first drinks 2 sips.',
  'Freeze dance: {{player}} hums and everyone dances. When the humming stops, everyone has to freeze. Whoever moves drinks 2 sips.',
  'Dance chain: Everyone takes a turn doing a dance move, and the whole group copies it right away. Whoever doesn\'t join in drinks 2 sips.',
  '{{player}} teaches the group a dance step in 30 seconds. Whoever can\'t do it drinks 2 sips.',
  'Everyone dab! Whoever dabs last drinks 2 sips.',
  'Everyone links arms and sways for 3 rounds. Whoever loses the rhythm drinks 2 sips.',
  'Everyone does Gangnam Style for 10 seconds. Whoever doesn\'t join in drinks 3 sips.',
  'Everyone does the Cha Cha Slide: "Slide to the left, slide to the right". Whoever doesn\'t slide along drinks 2 sips.',
  'Mirror dance: {{player}} dances, and {{player}} has to copy everything as a mirror image. If it works, both give out 2 sips.',
  'Conga at the table: Everyone puts their hands on the shoulders of the person to their right and sways once around the circle. Whoever breaks the line drinks 2 sips.',
  'Everyone strikes the "Saturday Night Fever" finger pose. The best pose gives out 2 sips.',
  'Headbang! Everyone headbangs for 5 seconds to an imaginary riff. Whoever stops first drinks 2 sips.',
  'Everyone does the Mexican wave with their arms while seated, for 3 rounds. Whoever is too slow drinks 2 sips.',
  'Cheers! Everyone clinks glasses while looking each other in the eye and drinks 2 sips. Whoever breaks eye contact drinks 1 more sip.',
  'Everyone clinks glasses with every single person at the table. Then everyone drinks 2 sips.',
  '{{player}} gives a 10 second speech to the group. Then everyone clinks glasses and drinks 2 sips.',
  'A toast to {{player}}! Everyone raises their glass, shouts the name and drinks 2 sips.',
  'Cheers in German, Spanish and Italian: Prost, Salud, Cin Cin! Everyone drinks 1 sip after each word.',
  'Everyone clinks glasses and shouts "Oggy Oggy Oggy, Oi Oi Oi". Then everyone drinks 2 sips.',
  'Everyone drinks 2 sips with their arm linked through their neighbor\'s.',
  'Take turns saying "Cheers" in a different language. Whoever can\'t think of a new one drinks 2 sips.',
  'Everyone clinks glasses. The last glass to leave the table belongs to the person who drinks 2 extra sips.',
  'A toast to the best person here! Everyone points at someone at the same time. The person with the most votes gives out 3 sips.',
  'Toast chain: Everyone takes a turn saying what we\'re drinking to. After each toast, everyone drinks 1 sip. One round only.',
  'Whisper cheers: Everyone clinks glasses very quietly. Whoever makes their glass clink out loud drinks 2 sips.',
  'Everyone toasts to the best song of all time. Whoever names a song the group thinks is bad drinks 1 extra sip.',
  'A toast to the hosts! Everyone drinks 2 sips, and the hosts also give out 3 sips.',
  'A toast to everyone who has already danced tonight! They drink 2 sips.',
  'Everyone clinks glasses and drinks without using their hands. Whoever can\'t manage it drinks 2 sips the normal way afterwards.',
  'Everyone drinks 2 sips with their weak hand. Whoever uses the wrong hand drinks 2 more sips.',
  'Bottoms up! Everyone drinks 3 sips at the same time.',
  'Everyone stands up, clinks glasses and sits back down. Whoever sits down last drinks 2 sips.',
  'Cheers rocket: Everyone drums on the table, faster and faster, then shouts "Cheers". Then everyone drinks 2 sips.',
  'Vote: Who will get tired first tonight? Everyone points on 3. The person with the most votes drinks 3 sips.',
  'Vote: Who is the best dancer at the table? Everyone points on 3. The winner gives out 4 sips.',
  'Vote: Who would be first on stage at a karaoke bar? The person with the most votes drinks 2 sips.',
  'Vote: Who has the best outfit tonight? That person gives out 3 sips.',
  'Vote: Who has the loudest laugh? Everyone points on 3. Whoever gets picked drinks 2 sips.',
  'Vote: Who would make the best DJ? The person with the most votes picks the next song and gives out 2 sips.',
  'Vote: Who will stay at the party the longest? The person with the most votes drinks 2 sips.',
  'Vote: Who would get furthest on a talent show? The winner gives out 3 sips.',
  'Vote: Who has the worst taste in music? The person with the most votes drinks 2 sips and reveals their favorite song.',
  'Vote: Who would be the best party planner? That person gives out 3 sips.',
  'Vote: Who tells the best stories? The person with the most votes gives out 2 sips.',
  'Vote: Who is in the biggest party mood tonight? That person gives out 3 sips.',
  'Thumbs vote: {{player}} names a song. Everyone shows thumbs up or thumbs down at the same time. The minority drinks 2 sips.',
  'Majority wins: Pizza or burgers? Everyone shouts their answer on 3. The minority drinks 2 sips.',
  'Majority wins: Beach or mountains? On 3, everyone points up for mountains or down for beach. The minority drinks 2 sips.',
  'Majority wins: Beer or wine? Everyone shouts on 3. The minority drinks 2 sips.',
  'Majority wins: Beatles or Rolling Stones? Everyone shouts on 3. The minority drinks 2 sips.',
  'Majority wins: Early bird or night owl? Everyone shouts on 3. The minority drinks 2 sips.',
  'Majority wins: Country or techno? Everyone shouts on 3. The minority drinks 2 sips.',
  'Mind reader: Everyone thinks of a number from 1 to 5 and shows it with their fingers on 3. Whoever shows the same number as {{player}} gives out 2 sips.',
  'Sync test: On 3, everyone says a color at the same time. Whoever is alone with their color drinks 2 sips.',
  'Sync test: On 3, everyone says an animal at the same time. If 2 people say the same one, they each give out 3 sips.',
  'Sync test: On 3, everyone names a drink at the same time. Whoever says the same as someone else clinks glasses with them and drinks 1 sip.',
  'Rock, paper, scissors with the whole group: Everyone plays at once. Whoever throws the rarest sign gives out 2 sips.',
  'Two teams! {{player}} and {{player}} take turns picking their teams. The teams take turns naming beer brands. The first team to pass drinks 2 sips per person.',
  'Team game: Split into 2 teams. The teams take turns humming a song while the other team guesses. The team that guesses wrong 3 times drinks 2 sips per person.',
  'Team game: 2 teams. Which team can get all their glasses in the air at the same time first? The slower team drinks 2 sips.',
  'Team game: 2 teams take turns naming countries. The first team to get stuck drinks 2 sips per person.',
  'Team game: 2 teams. Each team lines up in order of height. The slower team drinks 2 sips per person.',
  'Team game: 2 teams. Each team sings a football chant for 10 seconds. The louder team gives out 3 sips to the other team.',
  'Team game: 2 teams line up by birth month without talking. The slower or wrong team drinks 2 sips per person.',
  'Team game: 2 teams. One member per team acts out a movie. The team that guesses it first gives out 3 sips.',
  'Team game: 2 teams. Each team has 30 seconds to name as many animals starting with B as possible. The team with fewer drinks 2 sips per person.',
  'Relay drinking: 2 teams. One after another, everyone on the team drinks 1 sip and puts their glass down. The slower team drinks 2 more sips per person.',
  'Team game: 2 teams. Each team has 30 seconds to come up with a team name and a battle cry. The group votes, and the losing team drinks 2 sips.',
  'Team game: Left side of the table against right side. Who can hold an "Aaaah" longer? The losing team drinks 2 sips per person.',
  'Team game: 2 teams. Each team has 30 seconds to build the tallest tower out of things on the table. The team with the shorter tower drinks 2 sips per person.',
  'Team game: 2 teams play Telephone and whisper a word down the line. If the word comes out wrong, the team drinks 2 sips per person.',
  'Team game: 2 teams take turns naming football players. Whoever has nothing after 5 seconds loses and drinks 2 sips per person.',
  'Team game: 2 teams. {{player}} says a word, and each team draws it in the air in 20 seconds. The group picks the worse team, which drinks 2 sips.',
  'Team game: 2 teams take turns making animal noises. The team that runs out first drinks 2 sips per person.',
  'Everyone who has ever been to a festival drinks 2 sips and shouts the name of their favorite festival.',
  'Who has already sung along tonight? Everyone who has gives out 1 sip. Everyone else drinks 1 sip.',
  'Everyone with a fizzy drink right now drinks 2 sips.',
  'Everyone with an empty glass refills it and drinks 1 sip right away. Everyone else drinks 2 sips.',
  'Everyone who has ever been in a choir or a band gives out 2 sips.',
  'Everyone who has ever been to a concert drinks 1 sip. Whoever has been to more than 10 gives out 3 sips.',
  'Everyone who has ever taken a dance class gives out 2 sips.',
  'Everyone swaps seats with the person to their left. Whoever sits down last drinks 2 sips.',
  'Silence! Everyone stays completely quiet for 30 seconds. Whoever talks or laughs first drinks 3 sips.',
  'No laughing: {{player}} has 20 seconds to make the group laugh. Everyone who laughs drinks 2 sips.',
  'Face-pulling round: Everyone pulls their best funny face at the same time. {{player}} picks the best one, and that person gives out 3 sips.',
  'Charades: {{player}} acts out a job. Whoever guesses it gives out 2 sips.',
  'Charades: {{player}} acts out a movie without talking. Whoever guesses it first gives out 3 sips.',
  'Who am I? {{player}} thinks of a famous person. The group asks yes or no questions. Whoever guesses it gives out 3 sips.',
  'Celebrity impression: {{player}} does an impression of a celebrity. Whoever guesses who it is first gives out 2 sips.',
  'Animal noises: {{player}} makes an animal noise, and everyone else has to copy it at the same time. Whoever doesn\'t join in drinks 2 sips.',
  'Who speaks first? {{player}} asks the group a question. Whoever answers first gives out 2 sips, and whoever answers last drinks 2 sips.',
  'Quick guess: {{player}} describes a word without saying it. Whoever guesses it first gives out 2 sips.',
  'Word association: {{player}} says a word, and everyone takes turns instantly saying a related word. Whoever hesitates drinks 2 sips.',
  'Story chain: Everyone takes turns adding one word to build a story. Whoever breaks the sentence or hesitates drinks 2 sips.',
  'What\'s this for? {{player}} names an object, and everyone takes turns coming up with a crazy new use for it. Whoever has nothing drinks 2 sips.',
  'Famous movie quotes: Everyone takes turns quoting a movie. Whoever runs out drinks 2 sips.',
  'True or false: {{player}} shares a fact about themselves. Everyone votes. Whoever is wrong drinks 2 sips.',
  'Silent fox: Everyone makes a fox with their hand. Whoever shows their fox last drinks 2 sips.',
  'Heads or tails for the whole group: Everyone calls heads or tails, and {{player}} flips a coin. Whoever is wrong drinks 2 sips.',
  'The group writes a party song together. Everyone adds a line in turn. Whoever can\'t rhyme drinks 2 sips.',
  'Echo: {{player}} shouts a sentence, and everyone else has to repeat it in unison. Whoever comes in late drinks 2 sips.',
  'Volume check: Everyone shouts "Party" at the same time. {{player}} decides who was the quietest. That person drinks 2 sips.',
  'No yes, no no: {{player}} fires a quick question at everyone in the group. Whoever answers with yes or no drinks 2 sips.',
  'Who has the best party story? Everyone takes a turn telling it in one sentence. The group votes, and the winning story gives out 3 sips.',
  'Group photo pose: On 3, everyone strikes their best party pose and holds it for 5 seconds. Whoever wobbles first drinks 2 sips.',
  'The floor is lava! Everyone lifts their feet off the floor. Whoever gets their feet up last drinks 2 sips.',
  'Who\'s wearing the most colors? Everyone counts the colors in their outfit. The person with the most gives out 3 sips.',
  'Everyone who has to laugh right now drinks 1 sip. Whoever tries to hold it in but gets caught drinks 2.',
  'Party ranking: {{player}} names 3 party songs. The group votes on the best one. Whoever votes for the loser drinks 2 sips.',
  'Make some noise: Everyone drums on the table as loud as they can for 5 seconds. Whoever stops first drinks 2 sips.',
  'Who knows the words? {{player}} names a song, and everyone recites the first line at the same time. Whoever can\'t drinks 2 sips.',
  'Countdown drinking: Everyone counts down from 10 out loud. At 0, everyone drinks 2 sips.',
  'Who can hum "Ommm" the longest? Everyone starts at the same time. Whoever stops first drinks 3 sips.',
  'Highest note wins: Everyone sings their highest note at the same time. {{player}} crowns the winner, who gives out 3 sips.',
  'Lowest note wins: Everyone hums their lowest note at the same time. The deepest voice gives out 2 sips.',
  'Spin the bottle lite: {{player}} spins a bottle. The person it points to drinks 2 sips.',
  'Spin the bottle: {{player}} spins a bottle. The person it points to has to start a song, or else drink 3 sips.',
  'Who is sitting closest to the speaker? That person gives out 2 sips and gets to turn the music up.',
  'Group high five: Everyone high fives in the middle. Whoever misses drinks 2 sips.',
  'High five chain: Everyone high fives the next person in turn, as fast as possible. Whoever breaks the chain drinks 2 sips.',
  'Who knows the most names of the 7 Dwarfs? {{player}} starts, and everyone adds one in turn. Whoever gets stuck drinks 2 sips.',
  'Name the planets in order around the circle. {{player}} starts with Mercury. Whoever makes a mistake drinks 2 sips.',
  'Everyone takes turns naming a month in order, but backwards from December. Whoever slips up drinks 2 sips.',
  'Tongue twister: Everyone takes a turn saying "She sells seashells by the seashore" 3 times fast. Whoever trips up drinks 2 sips.',
  'Tongue twister: Everyone takes a turn saying "Peter Piper picked a peck of pickled peppers". Whoever stumbles drinks 2 sips.',
  'Tongue twister: {{player}} and {{player}} say "How much wood would a woodchuck chuck if a woodchuck could chuck wood" at the same time. Whoever messes up drinks 2 sips.',
  'Everyone whose name has more than 5 letters drinks 2 sips.',
  'The youngest person at the table gives out 3 sips, and the oldest drinks 2 sips.',
  'The person with the fullest glass gives out 3 sips.',
  'The tallest and the shortest person at the table clink glasses and drink 2 sips each.',
  'Whoever arrived last drinks 2 sips.',
  'Everyone who has already danced tonight gives out 1 sip. Whoever hasn\'t danced yet drinks 2 and dances for 5 seconds now.',
  '{{player}} picks a partner. Both have to start singing a song at the same time without agreeing on one. If they pick the same song, everyone else drinks 2 sips.',
  'Quick rhyme: {{player}} says a word, and everyone takes turns naming a word that rhymes. Whoever can\'t find one drinks 2 sips.',
  'Opposites round: {{player}} says a word, and the next person says the opposite plus a new word. Whoever hesitates drinks 2 sips.',
  'Emoji charades: {{player}} makes a face like a well-known emoji. Whoever guesses it first gives out 2 sips.',
  'Movie chain: {{player}} names a movie, the next person names an actor from it, then the next names another movie with that actor. Whoever gets stuck drinks 2 sips.',
  'Celebrity chain: {{player}} names a celebrity, and the next person names one whose first name starts with the first letter of the previous last name. Whoever gets stuck drinks 2 sips.',
  'Country chain: Each country has to start with the last letter of the one before. {{player}} starts. Whoever gets stuck drinks 2 sips.',
  'City chain: Each city has to start with the last letter of the one before. {{player}} starts. Whoever stalls drinks 2 sips.',
  'Whoever sings the chorus of "Macarena" fastest gives out 3 sips. Everyone tries at the same time.',
  'Favorite song round: Everyone takes turns naming their current favorite song. Whoever names a song nobody else knows drinks 2 sips.',
  'Sing-off: {{player}} and {{player}} sing different songs at the same time. Whoever laughs or stops first drinks 2 sips.',
  'Cow call: Everyone moos like a cow at the same time. {{player}} crowns the best cow, who gives out 2 sips.',
  'Party battle cry: {{player}} shouts "Who\'s thirsty?", everyone answers "We are!" and drinks 2 sips.',
  'Everyone drinks as many sips as {{player}} is holding up fingers right now. 4 max.',
  'Wheel of fortune: {{player}} points around the circle with their eyes closed and stops. The person they land on drinks 2 sips.',
  'Group guess: Everyone estimates how many glasses are on the table right now. Whoever is furthest off drinks 2 sips.',
  'Whose birthday is next? The group works it out in their heads. The person with the next birthday gives out 3 sips.',
  'Everyone who has taken a photo today drinks 1 sip. Whoever hasn\'t taken one yet gives out 1 sip.',
  'Werewolf moment: Everyone howls like a wolf at the same time. Whoever doesn\'t howl along drinks 2 sips.',
  'Stadium chant: Everyone sings "Olé, olé, olé" stadium style. Whoever is the quietest drinks 2 sips.',
  'Sea shanty: Everyone sings "What Shall We Do with the Drunken Sailor" and sways along. Whoever doesn\'t join in drinks 2 sips.',
  'Party hits medley: Everyone takes turns singing a line from a different party hit. Whoever runs out drinks 2 sips.',
  'Name that tune: {{player}} taps the rhythm of a song on the table. Whoever guesses it gives out 3 sips.',
  'Hit year: {{player}} names a song, and everyone guesses the year it came out. Whoever is furthest off drinks 2 sips.',
  'Who sings this? {{player}} sings the start of a chorus, and the group names the artist. Whoever gets it right first gives out 2 sips.',
  'Lost in translation: {{player}} says a famous song title in fancy, overly formal words, like "Remaining Alive" for "Stayin\' Alive". Whoever guesses the original gives out 2 sips.',
  'Air band: Everyone picks an air instrument and the whole group plays "Smoke on the Water". Whoever breaks character first drinks 2 sips.',
  'Slow motion cheers: Everyone clinks glasses in extreme slow motion. Whoever speeds up to normal first drinks 2 sips.',
  'The last person who laughed drinks 2 sips.',
  'Whoever is talking the loudest right now drinks 2 sips. Everyone points at that person on 3.',
  'Eyes closed and point: Everyone closes their eyes and points at {{player}}. Whoever is furthest off drinks 2 sips.',
  'Who can be first to name a song everyone at the table knows? {{player}} checks. The winner gives out 2 sips.',
  'Animal songs: Everyone takes turns naming a song with an animal in the title. {{player}} starts. Whoever gets stuck drinks 2 sips.',
  'Clap circle: {{player}} claps and sends the clap to the left. It should get faster and faster for 3 rounds. Whoever misses the clap drinks 2 sips.',
  'Laugh together: Everyone fake laughs for 10 seconds. Whoever starts laughing for real first gives out 2 sips.',
  'Catch the word: {{player}} tells a short story. Every time the word "and" comes up, everyone taps the table. Whoever taps too late drinks 2 sips.',
  'Concert vibes: Everyone holds up their phone light or an imaginary lighter and waves it. Whoever joins in last drinks 2 sips.',
  'The group sings "99 Bottles of Beer" together as far as they can get. Whoever loses the count first drinks 2 sips.',
  'Holiday anthem moment: Everyone sings "Mambo No. 5" or another cheesy holiday hit together. Whoever doesn\'t sing along drinks 2 sips.',
  'Everyone imagines they\'re at a rave and dances with their hands up for 10 seconds. Whoever stops first drinks 2 sips.',
  'Party round: Everyone takes turns naming the best party song from their school days. Whoever can\'t think of one drinks 2 sips.',
  'Penguin parade: Everyone waddles in their seat like a penguin and makes penguin noises. Whoever laughs first drinks 2 sips.',
];
