export const sexualTasksEn: string[] = [
  'Never have I ever kissed someone on a first date. If you have, drink 2 sips.',
  'Never have I ever used a pickup line that actually worked. If you have, drink 2 sips.',
  'Never have I ever made out with a stranger in a club. If you have, drink 3 sips.',
  'Never have I ever messaged someone on a dating app and then ghosted them. If you have, drink 2 sips.',
  'Never have I ever had a crush on a teacher. If you have, drink 2 sips.',
  'Never have I ever cut a date short. If you have, drink 2 sips.',
  'Never have I ever fallen head over heels on vacation. If you have, drink 2 sips.',
  'Never have I ever sent a message meant for my crush to the wrong chat. If you have, drink 3 sips.',
  'Never have I ever chickened out of a kiss during spin the bottle. If you have, drink 2 sips.',
  'Never have I ever flirted with someone from my ex\'s friend group. If you have, drink 3 sips.',
  'Never have I ever hidden a hickey with a scarf. If you have, drink 2 sips.',
  'Never have I ever scrolled all the way to the bottom of a crush\'s profile. If you have, drink 2 sips.',
  'Never have I ever accidentally liked an ancient photo of my crush. If you have, drink 3 sips.',
  'Never have I ever forgotten my date\'s name in the middle of the date. If you have, drink 3 sips.',
  'Never have I ever had two dates on the same day. If you have, drink 2 sips.',
  'Never have I ever kissed someone whose name I didn\'t know. If you have, drink 3 sips.',
  'Never have I ever sent a drunk love confession. If you have, drink 3 sips.',
  'Never have I ever ended a relationship over text. If you have, drink 2 sips.',
  'Never have I ever made out in the back seat of a taxi. If you have, drink 2 sips.',
  'Never have I ever been kissed under the mistletoe. If you have, drink 1 sip.',
  'Never have I ever flirted with someone at a wedding. If you have, drink 2 sips.',
  'Never have I ever been on a blind date. If you have, drink 2 sips.',
  'Never have I ever written a love letter. If you have, drink 1 sip.',
  'Never have I ever made out with a coworker. If you have, drink 3 sips.',
  'Never have I ever pretended to be taken to get rid of someone. If you have, drink 2 sips.',
  'Never have I ever written my number on a napkin. If you have, drink 2 sips.',
  'Never have I ever made out so wildly in public that someone complained. If you have, drink 3 sips.',
  'Never have I ever made out more than I watched the movie at the cinema. If you have, drink 2 sips.',
  'Never have I ever had a crush on a close friend\'s partner. If you have, drink 3 sips.',
  'Never have I ever worn an outfit just to impress one specific person. If you have, drink 2 sips.',
  'Never have I ever secretly had a crush on someone in this group. If you have, drink 3 sips.',
  'Never have I ever kissed someone in this group. If you have, drink 3 sips.',
  'Never have I ever made out in the bathroom at a party. If you have, drink 3 sips.',
  'Never have I ever tiptoed out of someone\'s place the morning after. If you have, drink 3 sips.',
  'Never have I ever fully researched a date online beforehand. If you have, drink 1 sip.',
  'Never have I ever accidentally bitten someone\'s lip while kissing. If you have, drink 2 sips.',
  'Never have I ever rerecorded a voice message to my crush 10 times. If you have, drink 2 sips.',
  'Never have I ever flirted just to get a free drink. If you have, drink 2 sips.',
  'Never have I ever dated someone more than 10 years older than me. If you have, drink 2 sips.',
  'Never have I ever gotten back together with an ex. If you have, drink 3 sips.',
  'Never have I ever been in a long distance relationship. If you have, drink 1 sip.',
  'Never have I ever deliberately made eyes at someone on the dance floor. If you have, drink 2 sips.',
  'Never have I ever taken a selfie just for my crush. If you have, drink 2 sips.',
  'Never have I ever made out on a beach. If you have, drink 2 sips.',
  'Everyone who has ever been on a date from a dating app drinks 2 sips.',
  'Everyone who has ever been kissed in the rain drinks 2 sips.',
  'Everyone who has ever been speed dating drinks 2 sips.',
  'Everyone who has ever made out with someone they met that same night drinks 3 sips.',
  'Everyone who has ever been turned down clinks glasses and drinks 1 sip.',
  'Everyone who has ever turned someone down drinks 2 sips.',
  'Everyone who is in love right now drinks 2 sips.',
  'Everyone who is single right now drinks 2 sips to freedom.',
  'Everyone who has ever been engaged or married drinks 2 sips.',
  'Everyone who has ever had a hickey drinks 2 sips.',
  'Everyone who has ever stalked a crush online drinks 2 sips.',
  'Everyone who has ever flirted their way out of a ticket drinks 3 sips.',
  'Everyone who has ever cooked for a date drinks 1 sip.',
  'Everyone who has ever never heard back after a date drinks 2 sips.',
  'Everyone who has ever ghosted someone themselves drinks 3 sips.',
  'Everyone who has ever had a friends with benefits situation drinks 3 sips.',
  'Everyone who has ever fought heartbreak with ice cream and sappy movies drinks 1 sip.',
  'Everyone who has ever been proposed to drinks 2 sips.',
  'Everyone who has ever made out at a festival drinks 2 sips.',
  'Everyone who has ever been on a date with someone in this group drinks 3 sips.',
  'Everyone who has ever kissed more than 3 people in one week drinks 3 sips.',
  'Everyone who has ever used a pet name they now find embarrassing drinks 2 sips.',
  'Everyone who has ever worn a couples costume drinks 2 sips.',
  'Everyone who sometimes keeps their eyes open while kissing drinks 2 sips.',
  'Everyone who has ever ruined a date by spilling something or tripping drinks 2 sips.',
  'Everyone who has ever been on a couples vacation drinks 1 sip.',
  'Everyone who has ever been too nervous to reply to a match drinks 2 sips.',
  'Everyone who has ever had a date who looked nothing like their photos drinks 2 sips.',
  'Everyone who has ever caught a bridal bouquet drinks 2 sips.',
  'Everyone who has ever sent a drink to a stranger at a bar drinks 2 sips.',
  'Everyone who has ever had a crush on a celebrity twice their age drinks 1 sip.',
  'Everyone who has ever missed an ex after watching a romantic movie drinks 2 sips.',
  'Everyone who has ever signed up for a class just because of one particular person drinks 3 sips.',
  'Everyone who has ever dated someone their parents didn\'t like drinks 2 sips.',
  'Everyone who has ever called their best friend right after a date drinks 1 sip.',
  'Everyone who has ever tried a flirting tip from the internet drinks 2 sips.',
  'Vote: Who is most likely to flirt with the bartender for a free shot? The person with the most votes drinks 2 sips.',
  'Vote: Who has the most dating apps on their phone? The person with the most votes drinks 3 sips.',
  'Vote: Who is the best kisser? The person with the most votes gives out 3 sips.',
  'Vote: Who is most likely to get married after just 3 months together? The person with the most votes drinks 2 sips.',
  'Vote: Who is most likely to text their crush at 3 a.m.? The person with the most votes drinks 3 sips.',
  'Vote: Who has the best pickup line up their sleeve? The person with the most votes says it out loud or drinks 3 sips.',
  'Vote: Who is most likely to get hit on later tonight? The person with the most votes drinks 2 sips.',
  'Vote: Who has the most chaotic dating history? The person with the most votes drinks 3 sips.',
  'Vote: Who is secretly the most romantic? The person with the most votes drinks 2 sips.',
  'Vote: Who falls in love the fastest? The person with the most votes drinks 2 sips.',
  'Vote: Who has broken the most hearts? The person with the most votes drinks 3 sips.',
  'Vote: Who is most likely to flirt without even noticing? The person with the most votes drinks 2 sips.',
  'Vote: Who is most likely to end up on a TV dating show? The person with the most votes drinks 2 sips.',
  'Vote: Who has the best smile in the group? The person with the most votes gives out 2 sips.',
  'Vote: Who is most likely to fall for a vacation fling? The person with the most votes drinks 2 sips.',
  'Vote: Who would make the best blind date? The person with the most votes gives out 3 sips.',
  'Vote: Who plans the most romantic dates? The person with the most votes gives out 2 sips.',
  'Vote: Who is most likely to get slipped a phone number at a bar? The person with the most votes drinks 2 sips.',
  'Vote: Who is most likely to still be friends with their ex? The person with the most votes drinks 2 sips.',
  'Vote: Who is most likely to talk about their ex on a first date? The person with the most votes drinks 3 sips.',
  'Vote: Who has the most seductive voice? The person with the most votes whispers something sweet into the ear of the person on their left or drinks 3 sips.',
  'Vote: Who is the most jealous? The person with the most votes drinks 2 sips.',
  'Vote: Who has the best flirty dance moves? The person with the most votes shows them off for 10 seconds or drinks 3 sips.',
  'Vote: Who sends the cheekiest texts? The person with the most votes drinks 3 sips.',
  'Vote: Who is most likely to blush while flirting? The person with the most votes drinks 2 sips.',
  'Vote: Who is most likely to have a secret office romance? The person with the most votes drinks 2 sips.',
  'Vote: Who has the most beautiful eyes in the group? The person with the most votes gives out 2 sips.',
  '{{player}}, tell us honestly how old you were at your first kiss, or drink 3 sips.',
  '{{player}}, tell us honestly who in this group would be the best date, or drink 4 sips.',
  '{{player}}, tell us honestly what instantly attracts you to someone, or drink 2 sips.',
  '{{player}}, tell us honestly the cheekiest thing you\'ve ever said to a crush, or drink 3 sips.',
  '{{player}}, tell us honestly how many dates you\'ve been on this year, or drink 3 sips.',
  '{{player}}, tell us honestly whether you\'re into someone right now, or drink 3 sips.',
  '{{player}}, tell us honestly your biggest turnoff on a first date, or drink 2 sips.',
  '{{player}}, tell us honestly what secretly turns you on, keep it PG, or drink 4 sips.',
  '{{player}}, tell us honestly the weirdest place you\'ve ever made out, or drink 3 sips.',
  '{{player}}, tell us honestly which celebrity would be your free pass, or drink 2 sips.',
  '{{player}}, tell us honestly whether you\'ve ever had a crush on someone in this group, or drink 4 sips.',
  '{{player}}, tell us honestly how long you wait after a date before texting, or drink 2 sips.',
  '{{player}}, tell us honestly what your last message to your crush said, or drink 3 sips.',
  '{{player}}, tell us honestly whether you\'ve ever seen someone again just because they were a great kisser, or drink 3 sips.',
  '{{player}}, tell us honestly the cheesiest thing you\'ve ever done for someone, or drink 2 sips.',
  '{{player}}, tell us honestly about your worst date and why it was so bad, or drink 3 sips.',
  '{{player}}, tell us honestly whether you make the first move when flirting or prefer to wait, or drink 2 sips.',
  '{{player}}, tell us honestly when you last kissed someone, or drink 3 sips.',
  '{{player}}, without naming names, describe the last person who made your heart race, or drink 3 sips.',
  '{{player}}, tell us honestly roughly how many people you\'ve kissed, or drink 4 sips.',
  '{{player}}, tell us honestly the most embarrassing thing on your dating profile, past or present, or drink 2 sips.',
  '{{player}}, tell us honestly which piece of clothing on someone else makes you weak, or drink 2 sips.',
  '{{player}}, tell us honestly whether you\'ve ever been in love with someone who never knew, or drink 2 sips.',
  '{{player}}, tell us honestly which song instantly puts you in the mood to make out, or drink 2 sips.',
  '{{player}}, tell us honestly what you would never forgive in a relationship, or drink 2 sips.',
  '{{player}}, tell us honestly whether you\'ve ever said yes to a date just for the food, or drink 3 sips.',
  '{{player}}, tell us honestly the longest you\'ve ever gone without a kiss, or drink 3 sips.',
  '{{player}}, tell us honestly the most romantic moment of your life, or drink 2 sips.',
  '{{player}}, tell us honestly which trait of your ex you secretly miss, or drink 3 sips.',
  '{{player}}, tell us honestly who in this group you\'d most likely wear a couples costume with, or drink 3 sips.',
  '{{player}}, tell us honestly whether you\'ve ever made someone jealous on purpose, or drink 3 sips.',
  '{{player}}, tell us how someone last hit on you, or drink 2 sips.',
  '{{player}}, give {{player}} your best pickup line or drink 3 sips.',
  '{{player}}, come up with a pickup line using the word potato and try it on {{player}}, or drink 3 sips.',
  '{{player}}, tell {{player}} the worst pickup line you know. Whoever laughs drinks 2 sips.',
  '{{player}}, make {{player}} laugh with a pickup line. If it works, the person you flirted with drinks 2 sips, otherwise you drink 2.',
  '{{player}}, flirt with {{player}} for 15 seconds using only your eyes. Whoever laughs first drinks 2 sips.',
  'Going around the circle, everyone says a pickup line. The group picks the worst one, and whoever said it drinks 3 sips.',
  '{{player}}, give {{player}} a pickup line in the style of a weather report or drink 3 sips.',
  '{{player}}, give {{player}} a pickup line in your best French accent or drink 2 sips.',
  '{{player}}, come up with a math pickup line and say it to {{player}}, or drink 3 sips.',
  '{{player}}, give {{player}} a pickup line as if you were in a soap opera, or drink 3 sips.',
  '{{player}}, give {{player}} a pickup line in slow motion or drink 2 sips.',
  '{{player}}, give the person on your left a pickup line while acting extremely shy, or drink 2 sips.',
  '{{player}}, share a pickup line someone once used on you, or drink 2 sips.',
  '{{player}} says a pickup line to the group. Everyone who would fall for it drinks 2 sips.',
  '{{player}}, give {{player}} a pickup line in an accent of your choice or drink 3 sips.',
  '{{player}}, give {{player}} a pickup line that rhymes, or drink 3 sips.',
  '{{player}}, give {{player}} an honest compliment on their looks or drink 2 sips.',
  '{{player}}, tell {{player}} what you find most attractive about them, or drink 3 sips.',
  '{{player}}, give everyone in the group a flirty compliment or drink 4 sips.',
  '{{player}}, give {{player}} a compliment while holding eye contact. Whoever looks away first drinks 2 sips.',
  '{{player}}, describe {{player}} in 3 words that sound seductive, or drink 2 sips.',
  '{{player}}, tell {{player}} in your most seductive voice what you like about their outfit tonight, or drink 3 sips.',
  '{{player}}, compliment {{player}} on their voice or drink 2 sips.',
  'Going around the circle, everyone gives the person on their right a compliment. Whoever blushes drinks 2 sips.',
  '{{player}}, compliment the person you think is dressed the hottest tonight, or drink 3 sips.',
  '{{player}}, tell {{player}} 3 things you would enjoy about a date with them, or drink 3 sips.',
  '{{player}}, act out how you flirt with someone at a bar, no words allowed. If the group rates it below 5 out of 10, you drink 2 sips.',
  '{{player}}, act out a first date that goes completely wrong, no words allowed, or drink 3 sips.',
  '{{player}}, show us your most seductive look for 5 seconds or drink 2 sips.',
  '{{player}}, wink at {{player}} as seductively as you can. Whoever laughs drinks 2 sips.',
  '{{player}}, show us your best flirty hip sway or drink 3 sips.',
  '{{player}}, act out sneaking up on your crush on the dance floor, no words allowed, or drink 2 sips.',
  '{{player}}, show without words how you wait for the goodnight kiss after a date, or drink 2 sips.',
  '{{player}}, act out secretly glancing over at your crush. If the group doesn\'t buy it, you drink 2 sips.',
  '{{player}}, reenact your favorite movie kiss with a pillow or drink 3 sips.',
  '{{player}}, strut across the room like it\'s a runway for 10 seconds and give it everything, or drink 3 sips.',
  '{{player}}, dance seductively for 15 seconds to a song the group picks, or drink 3 sips.',
  '{{player}}, bite your lip seductively while looking at {{player}}. Whoever laughs first drinks 2 sips.',
  '{{player}}, hand {{player}} an imaginary rose like on a dating show or drink 2 sips.',
  '{{player}}, act out a flirting scene without words. If {{player}} can\'t guess where it takes place, you both drink 1 sip.',
  '{{player}}, give {{player}} a kiss on the cheek or drink 3 sips.',
  '{{player}}, kiss {{player}}\'s hand like a medieval knight or drink 2 sips.',
  '{{player}}, give the person with the best smile a kiss on the cheek or drink 3 sips.',
  '{{player}}, blow {{player}} a kiss. If they don\'t catch it, you both drink 1 sip.',
  '{{player}}, rub noses with {{player}} in an Eskimo kiss or drink 2 sips.',
  '{{player}}, kiss the back of your own hand as passionately as you can or drink 2 sips.',
  '{{player}}, give {{player}} a kiss on the forehead or drink 2 sips.',
  '{{player}} and {{player}}, give each other a peck on the cheek or both drink 2 sips.',
  '{{player}}, whisper one detail about your last kiss into {{player}}\'s ear or drink 3 sips.',
  '{{player}}, massage {{player}}\'s shoulders for 10 seconds or drink 3 sips.',
  '{{player}}, get a 10 second shoulder massage from someone of your choice, if they\'re up for it, or drink 2 sips.',
  '{{player}}, massage {{player}}\'s hand for 10 seconds or drink 2 sips.',
  '{{player}}, scratch {{player}}\'s neck for 10 seconds or drink 3 sips.',
  '{{player}}, trace a flirty word on {{player}}\'s back with your finger. If they can\'t guess it, they drink 1 sip. If you refuse, you drink 3 sips.',
  '{{player}}, hold hands with {{player}} for the next 3 cards or drink 3 sips.',
  '{{player}}, rest your head on {{player}}\'s shoulder for 1 minute or drink 3 sips.',
  '{{player}} and {{player}}, slow dance for 20 seconds or both drink 2 sips.',
  '{{player}}, hug {{player}} for 10 seconds like you haven\'t seen each other in years, or drink 3 sips.',
  '{{player}} and {{player}}, gaze deep into each other\'s eyes for 20 seconds. Whoever laughs or looks away first drinks 3 sips.',
  '{{player}}, whisper to {{player}} the title of the song you\'d most like to dance to with them, or drink 3 sips.',
  '{{player}}, feed {{player}} a snack or drink 2 sips.',
  '{{player}}, take off your jacket or one sock or drink 3 sips.',
  '{{player}}, swap an accessory like a ring, watch or necklace with {{player}} until the end of the game, or drink 2 sips.',
  '{{player}} and {{player}} play out a 30 second blind date where the sparks fly instantly. Whoever breaks character drinks 3 sips.',
  '{{player}} and {{player}} play out a blind date where both are extremely nervous. Whoever laughs first drinks 3 sips.',
  '{{player}}, act out a first date at a fast food restaurant with {{player}}. Whoever laughs first drinks 2 sips.',
  '{{player}}, beg {{player}} for a second date as dramatically as on a dating show, or drink 3 sips.',
  '{{player}}, say goodbye to {{player}} as if after a perfect first date, or drink 3 sips.',
  '{{player}}, ask {{player}} out on a date in the most flowery medieval language you can, or drink 2 sips.',
  '{{player}} and {{player}} play out a blind date where it turns out they\'re both vampires. Whoever laughs first drinks 2 sips.',
  '{{player}}, introduce yourself to {{player}} in 30 seconds like at speed dating. If they say no match, you drink 2 sips.',
  '{{player}}, show your date {{player}} how you try to pick up the check but your card gets declined. Whoever laughs first drinks 2 sips.',
  '{{player}}, get down on one knee and give {{player}} a dramatic marriage proposal or drink 3 sips.',
  '{{player}}, break up with {{player}} like you\'re in a telenovela, or drink 2 sips.',
  '{{player}} and {{player}} play a couple married for 50 years arguing about their first date. Whoever laughs first drinks 2 sips.',
  '{{player}}, reveal which body part you like most on yourself, or drink 2 sips.',
  '{{player}}, reveal which body part you notice first on other people, or drink 2 sips.',
  '{{player}}, say which body part of {{player}} you find the most attractive, or drink 3 sips.',
  '{{player}}, show off your best PG body part with a model pose or drink 2 sips.',
  '{{player}}, tell your most embarrassing date story or drink 4 sips.',
  'Going around the circle, everyone sums up their most embarrassing date in one sentence. The person with the worst story gives out 4 sips.',
  '{{player}}, tell us about the moment you blushed the hardest on a date, or drink 3 sips.',
  '{{player}}, tell us what went wrong during the worst kiss of your life, or drink 3 sips.',
  '{{player}}, tell us about a date you wanted to secretly escape from, or drink 3 sips.',
  '{{player}}, reveal the craziest excuse you\'ve used to cancel a date, or drink 3 sips.',
  '{{player}}, tell us how you met your last crush, or drink 2 sips.',
  '{{player}}, share the weirdest message you\'ve ever gotten on a dating app, or drink 3 sips.',
  '{{player}}, tell us when someone last made you really nervous, or drink 2 sips.',
  'Whoever in the group has had the longest relationship gives out 3 sips.',
  'Whoever was kissed most recently drinks 2 sips.',
  'Whoever had a date most recently gives out 2 sips.',
  'Whoever has been single the longest gives out 3 sips.',
  'Everyone in a relationship clinks glasses with each other and drinks 2 sips.',
  'Whoever has already flirted today drinks 2 sips.',
  'Whoever has a dating app on their phone right now drinks 2 sips.',
  'Whoever would like to dance with someone from the group later tonight drinks 2 sips.',
  'Whoever has a tattoo somewhere you can\'t see right now drinks 2 sips.',
  'Whoever is wearing matching underwear today drinks 2 sips.',
  'Whoever has a crush saved in their phone under a code name drinks 3 sips.',
  'Whoever thinks they\'re a really good kisser drinks 2 sips.',
  'Whoever has ever had a crush on a neighbor drinks 2 sips.',
  'Whoever has ever secretly sent a photo of their date to the group chat drinks 2 sips.',
  '{{player}}, end every sentence with the word babe for the next 3 cards. Every slip costs 1 sip.',
  '{{player}}, give {{player}} an honest dating tip or drink 2 sips.',
  '{{player}}, name the person in the group who smells the best, or drink 3 sips.',
  '{{player}}, ask {{player}} a cheeky question. If they don\'t answer, they drink 3 sips.',
  '{{player}}, recite 3 sentences to {{player}} that could come from a cheesy romance novel, or drink 2 sips.',
  '{{player}}, read out the last message where you sent a heart, or drink 3 sips.',
  '{{player}}, show the group your last selfie or drink 3 sips.',
  '{{player}}, show the group your dating profile if you have one, or drink 3 sips.',
  '{{player}}, describe yourself in 2 sentences like a personal ad or drink 2 sips.',
  '{{player}}, make a seductive declaration of love to your drink, then drink 2 sips.',
  '{{player}}, reveal your favorite place to be kissed, keep it PG, or drink 3 sips.',
  '{{player}}, say whether you\'d rather make out in the dark or by candlelight, or drink 2 sips.',
  '{{player}}, choose: a kiss in the rain or a kiss on a Ferris wheel. Everyone who would have picked the other drinks 1 sip.',
  '{{player}}, describe your perfect first date in 3 sentences or drink 2 sips.',
  '{{player}}, describe {{player}}\'s type in 3 words. If they say you\'re wrong, you drink 2 sips.',
  '{{player}}, whisper a cheeky line into {{player}}\'s ear. If they grin, they drink 2 sips, otherwise you drink 2.',
  'Category, first date spots: Going around the circle, everyone names one. Whoever runs out of ideas drinks 2 sips.',
  'Category, pet names: Going around the circle, everyone names one. Whoever runs out of ideas drinks 2 sips.',
  'Category, famous movie couples: Going around the circle, everyone names one. Whoever runs out of ideas drinks 2 sips.',
  'Category, other words for kissing: Going around the circle, everyone names one. Whoever runs out of ideas drinks 2 sips.',
  'Category, love songs: Going around the circle, everyone names one. Whoever runs out of ideas drinks 2 sips.',
  'Category, things that can go wrong on a first date: Going around the circle, everyone names one. Whoever runs out of ideas drinks 2 sips.',
  '{{player}}, sing the first line of a love song to {{player}} or drink 3 sips.',
  '{{player}}, make an over the top declaration of love to {{player}} like in a cheesy movie, or drink 3 sips.',
  '{{player}}, write a 2 line poem about {{player}}\'s lips or drink 3 sips.',
  '{{player}}, give {{player}} a pet name that sticks until the end of the game, or drink 2 sips.',
  '{{player}}, play matchmaker for two people in the group. Those two clink glasses and drink 2 sips.',
  '{{player}}, pick a drinking date. For the next 3 cards, that person drinks whenever you do.',
  '{{player}} and {{player}}, say at the same time what matters more to you on a first date: humor or looks. If your answers differ, you both drink 2 sips.',
  '{{player}}, ask {{player}} as charmingly as you can whether you\'ll dance together later, or drink 2 sips.',
  'Everyone who has already sneaked a glance at someone in the group tonight drinks 2 sips.',
  '{{player}}, tell us about your cheekiest flirting win or drink 3 sips.',
  '{{player}}, reveal the cheesiest pet name you\'ve ever been given, or drink 2 sips.',
  '{{player}}, reveal what\'s in your nightstand, keep it PG, or drink 4 sips.',
  '{{player}}, reveal which perfume or cologne on other people makes you weak, or drink 2 sips.',
  '{{player}}, take a couples selfie with someone of your choice, if they\'re up for it, or drink 2 sips.',
  'Whoever has ever played a song about a lost love on repeat drinks 2 sips.',
  'Whoever still keeps a card or letter from an old crush drinks 2 sips.',
  'Whoever has ever had a crush on a cartoon character drinks 2 sips.',
  'Whoever has ever been caught making out by their parents drinks 3 sips.',
  'Whoever has ever introduced a partner to their parents drinks 1 sip.',
  'Whoever has ever spent Valentine\'s Day alone with a pizza drinks 1 sip.',
  'Whoever has ever had a date at a museum drinks 1 sip.',
  'Whoever has ever escaped to the bathroom during a date to get advice by phone drinks 2 sips.',
  'Whoever has ever matched with someone they know on a dating app drinks 2 sips.',
  'Whoever has ever proposed to someone drinks 2 sips.',
  'Whoever has ever split the bill on a first date drinks 1 sip.',
  'Whoever finds glasses on other people sexy drinks 2 sips.',
  'Whoever is into tattoos on other people drinks 2 sips.',
  'Whoever goes weak for dimples drinks 1 sip.',
  'Whoever is still hoping for a kiss tonight drinks 2 sips.',
  'Whoever has a soft spot for deep voices drinks 2 sips.',
  'Whoever has ever dedicated a song to a crush drinks 2 sips.',
  'Whoever has ever been so distracted while flirting that they knocked over a glass drinks 2 sips.',
  'Whoever still has a sweater from an ex or crush in their closet drinks 2 sips.',
  'Whoever has ever practiced a conversation with their crush in front of the mirror drinks 2 sips.',
  'Whoever has ever spent an entire party with just one person drinks 2 sips.',
  'Vote: Who has the best flirty look going on tonight? The person with the most votes gives out 2 sips.',
  '{{player}}, tell us honestly whether you prefer a goodnight kiss on the first date or saving it for the second, or drink 2 sips.',
];
