export const wahrheitTasksEn: string[] = [
  'Never have I ever written a love letter. If you have, drink 2 sips.',
  'Never have I ever pretended not to see someone so I wouldn\'t have to say hi. If you have, drink 2 sips.',
  'Never have I ever copied someone\'s work at school. If you have, drink 2 sips.',
  'Never have I ever ignored a call and then claimed I was asleep. If you have, drink 2 sips.',
  'Never have I ever had a crush on a teacher. If you have, drink 2 sips.',
  'Never have I ever waved back at someone who wasn\'t waving at me. If you have, drink 2 sips.',
  'Never have I ever sent a voice message longer than 5 minutes. If you have, drink 2 sips.',
  'Never have I ever regifted a present. If you have, drink 2 sips.',
  'Never have I ever performed a full concert in the shower. If you have, drink 2 sips.',
  'Never have I ever scrolled all the way to the bottom of my ex\'s profile. If you have, drink 3 sips.',
  'Never have I ever accidentally liked an ancient photo of someone. If you have, drink 3 sips.',
  'Never have I ever bailed on plans with a completely made up excuse. If you have, drink 2 sips.',
  'Never have I ever checked the time on a date, hoping it would be over soon. If you have, drink 2 sips.',
  'Never have I ever ghosted someone. If you have, drink 3 sips.',
  'Never have I ever googled my own name. If you have, drink 2 sips.',
  'Never have I ever rehearsed a conversation in front of the mirror. If you have, drink 2 sips.',
  'Never have I ever pretended to get a joke. If you have, drink 2 sips.',
  'Never have I ever eaten my roommate\'s food without asking. If you have, drink 2 sips.',
  'Never have I ever kept watching a show just because of one actor. If you have, drink 2 sips.',
  'Never have I ever sent a message to the wrong person. If you have, drink 3 sips.',
  'Never have I ever fallen asleep in a meeting or a lecture. If you have, drink 2 sips.',
  'Never have I ever pretended to have read a book I never even opened. If you have, drink 2 sips.',
  'Never have I ever taken a selfie in a fitting room. If you have, drink 2 sips.',
  'Never have I ever flirted with someone just to get something for free. If you have, drink 3 sips.',
  'Never have I ever downloaded a dating app. If you have, drink 2 sips.',
  'Never have I ever lied about my age. If you have, drink 2 sips.',
  'Never have I ever farted loudly and blamed it on someone else. If you have, drink 3 sips.',
  'Never have I ever had someone else do my homework. If you have, drink 2 sips.',
  'Never have I ever screenshotted a chat to show my friends. If you have, drink 2 sips.',
  'Never have I ever secretly eavesdropped on the next table. If you have, drink 2 sips.',
  'Never have I ever snored loudly in a movie theater. If you have, drink 2 sips.',
  'Never have I ever found someone cute just because of their voice. If you have, drink 2 sips.',
  'Never have I ever stalked my crush online. If you have, drink 3 sips.',
  'Never have I ever pretended to know someone at a party. If you have, drink 2 sips.',
  'Never have I ever left the dishes sitting for days. If you have, drink 2 sips.',
  'Never have I ever lied to my parents about where I was spending the night. If you have, drink 3 sips.',
  'Never have I ever had 2 dates on the same day. If you have, drink 3 sips.',
  'Never have I ever forgotten my best friend\'s birthday. If you have, drink 3 sips.',
  'Never have I ever sung karaoke. If you have, drink 2 sips.',
  'Never have I ever signed up for a class just because of one particular person. If you have, drink 2 sips.',
  'Never have I ever typed a message and deleted it super fast. If you have, drink 2 sips.',
  'Never have I ever texted my ex that I miss them. If you have, drink 3 sips.',
  'Never have I ever claimed my battery was dying to end a conversation. If you have, drink 2 sips.',
  'Never have I ever kissed someone on vacation without knowing their name. If you have, drink 3 sips.',
  'Never have I ever passed off a store bought cake as homemade. If you have, drink 2 sips.',
  'Never have I ever had a crush on someone in this group. If you have, drink 3 sips.',
  'Never have I ever pretended not to speak English to get rid of someone. If you have, drink 2 sips.',
  'Never have I ever binged an entire season in one weekend. If you have, drink 2 sips.',
  'Never have I ever eaten in bed and just left the crumbs there. If you have, drink 2 sips.',
  'Never have I ever secretly thought a coworker was cute. If you have, drink 2 sips.',
  'Never have I ever slept through an exam. If you have, drink 3 sips.',
  'Never have I ever forgotten my date\'s name. If you have, drink 3 sips.',
  'Never have I ever sent a message to a celebrity. If you have, drink 2 sips.',
  'Never have I ever told a restaurant the food was great when it was awful. If you have, drink 2 sips.',
  'Never have I ever known an entire boy band song by heart. If you have, drink 2 sips.',
  'Never have I ever crashed at a stranger\'s place after a party. If you have, drink 3 sips.',
  'Never have I ever liked my own post from a second account. If you have, drink 3 sips.',
  'Never have I ever texted "on my way" while still lying in bed. If you have, drink 2 sips.',
  'Never have I ever weaseled out of paying up on a lost bet. If you have, drink 2 sips.',
  'Never have I ever talked trash about someone who was standing right next to me. If you have, drink 3 sips.',

  'Everyone who has ever cried at a romantic movie, drink 2 sips.',
  'Everyone who has spent more than 3 hours on their phone today, drink 2 sips.',
  'Everyone who has a crush on someone right now, drink 3 sips.',
  'Everyone who has ever spotted a typo in an important message only after hitting send, drink 1 sip.',
  'Everyone who has ever lied to their crush to seem cooler, drink 2 sips.',
  'Everyone who has ever had detention at school, drink 2 sips.',
  'Everyone who has ever gotten back together with an ex, drink 3 sips.',
  'Everyone who has ever written "Sorry, just saw this" when it wasn\'t true, drink 2 sips.',
  'Everyone who has ever made up an excuse to skip hanging out with this group, drink 3 sips.',
  'Everyone who has ever been turned down at a club, drink 2 sips.',
  'Everyone who has ever arranged an emergency call from a friend before a date, drink 2 sips.',
  'Everyone who has ever made out with someone in this group, drink 3 sips.',
  'Everyone who secretly has a favorite person in this group, drink 2 sips.',
  'Everyone who has ever retaken a selfie more than 20 times, drink 2 sips.',
  'Everyone who has ever replied "Haha" without actually laughing, drink 1 sip.',
  'Everyone who has ever fibbed in a job interview, drink 2 sips.',
  'Everyone who has ever been in love with a celebrity, drink 2 sips.',
  'Everyone who has ever sucked up to a boss or a teacher, drink 2 sips.',
  'Everyone who has ever fought heartbreak with an entire tub of ice cream, drink 2 sips.',
  'Everyone who has ever accidentally called a teacher Mom or Dad, drink 3 sips.',
  'Everyone who has ever faked a phone call to avoid running into someone, drink 2 sips.',
  'Everyone who has ever lost their shoes at a party, drink 2 sips.',
  'Everyone who had a nickname they hated, drink 2 sips.',
  'Everyone who has ever tripped in public and acted like nothing happened, drink 2 sips.',
  'Everyone who has ever kept a diary, drink 2 sips.',
  'Everyone who has ever written a letter to their future self, drink 1 sip.',
  'Everyone who has ever hit on someone at a wedding, drink 2 sips.',
  'Everyone who has ever canceled a date because the show they were watching was too good, drink 2 sips.',
  'Everyone who has ever tried out their first name with their crush\'s last name, drink 3 sips.',
  'Everyone who has ever said "You too" when it made absolutely no sense, drink 2 sips.',
  'Everyone who has ever wished for a kiss in the rain, drink 1 sip.',
  'Everyone who has ever ditched their friends for a date, drink 3 sips.',
  'Everyone who has ever found someone at the supermarket checkout cute, drink 1 sip.',
  'Everyone who has ever had a summer fling on vacation, drink 2 sips.',
  'Everyone who has ever drunk dialed someone they really shouldn\'t have, drink 3 sips.',
  'Everyone who has ever had an entire fight over text, drink 2 sips.',
  'Everyone who has ever hidden their story from one specific person, drink 2 sips.',
  'Everyone who has ever secretly changed the music at a party, drink 1 sip.',
  'Everyone who has ever been late to a first date, drink 2 sips.',
  'Everyone who has ever ordered something and never unpacked it, drink 2 sips.',
  'Everyone who has ever used a cheat sheet in an exam, drink 2 sips.',
  'Everyone who has ever fallen for someone just because of their profile pictures, drink 2 sips.',
  'Everyone who has ever practiced a dance routine in their bedroom, drink 2 sips.',
  'Everyone who has lied in the last 7 days, drink 2 sips.',
  'Everyone who has ever thought their camera was off on a video call when it was on, drink 2 sips.',
  'Everyone who has ever spoiled the ending of a movie, drink 2 sips.',
  'Everyone who has ever screenshotted a compliment to keep it, drink 2 sips.',
  'Everyone who has ever left a party without saying goodbye, drink 2 sips.',
  'Everyone who has ever ordered food after a night out and had no memory of it the next day, drink 2 sips.',
  'Everyone who has ever received a love letter, drink 1 sip.',
  'Everyone who has ever broken up with someone over text, drink 3 sips.',
  'Everyone who has ever secretly laughed at their boss\'s mistake, drink 1 sip.',
  'Everyone who has listened to a voice message and never replied, drink 2 sips.',
  'Everyone who thinks they\'re the best liar here, drink 2 sips.',
  'Everyone who has ever given a compliment just to get something, drink 2 sips.',

  '{{player}}, who in this group would you most likely date? Answer honestly or drink 4 sips.',
  '{{player}}, what was your most embarrassing moment at school? Answer honestly or drink 3 sips.',
  '{{player}}, which message on your phone should nobody here ever read? Describe it roughly or drink 4 sips.',
  '{{player}}, who was your first crush? Answer honestly or drink 3 sips.',
  '{{player}}, what\'s the biggest lie you ever told your parents? Answer or drink 4 sips.',
  '{{player}}, what song is your secret guilty pleasure? Answer or drink 2 sips.',
  '{{player}}, what was your worst date ever? Tell the story or drink 3 sips.',
  '{{player}}, who in this group would you call at 3 a.m. to come pick you up? Answer or drink 2 sips.',
  '{{player}}, what was your first impression of {{player}}? Answer honestly or drink 3 sips.',
  '{{player}}, which app on your phone are you most embarrassed about? Answer or drink 3 sips.',
  '{{player}}, how long did your shortest relationship last? Answer or drink 3 sips.',
  '{{player}}, what\'s the most embarrassing thing you\'ve ever googled? Answer or drink 4 sips.',
  '{{player}}, have you ever secretly thought someone in this group was cute? Answer honestly or drink 4 sips.',
  '{{player}}, what annoys you most about {{player}}? Answer honestly or drink 3 sips.',
  '{{player}}, which of {{player}}\'s qualities would you love to have? Answer or drink 2 sips.',
  '{{player}}, what\'s the dumbest thing you\'ve ever done drunk? Answer or drink 4 sips.',
  '{{player}}, what\'s the silliest thing you\'ve ever argued about? Answer or drink 2 sips.',
  '{{player}}, which celebrity would you date in a heartbeat? Answer or drink 2 sips.',
  '{{player}}, what was the last thing you lied about? Answer honestly or drink 3 sips.',
  '{{player}}, what\'s your weirdest habit when you\'re alone? Answer or drink 3 sips.',
  '{{player}}, which childhood dream embarrasses you now? Answer or drink 2 sips.',
  '{{player}}, what old nickname did you have that nobody here knows about? Answer or drink 3 sips.',
  '{{player}}, what was your most embarrassing moment at a party? Answer or drink 3 sips.',
  '{{player}}, who in this group do you think is the biggest blabbermouth? Answer or drink 2 sips.',
  '{{player}}, who in this group would you never tell a secret to? Answer honestly or drink 4 sips.',
  '{{player}}, what\'s the weirdest reason you ever stopped seeing someone? Answer or drink 3 sips.',
  '{{player}}, what\'s the cheesiest thing you\'ve ever done for a crush? Answer or drink 3 sips.',
  '{{player}}, which show do you secretly watch even though you think it\'s embarrassing? Answer or drink 2 sips.',
  '{{player}}, what was your worst haircut ever? Answer or drink 2 sips.',
  '{{player}}, who in this group would you take to a desert island? Answer or drink 2 sips.',
  '{{player}}, who in this group would you never go on vacation with? Answer honestly or drink 3 sips.',
  '{{player}}, what did you believe as a kid that was totally wrong? Answer or drink 2 sips.',
  '{{player}}, which emoji do you use way too much? Answer or drink 1 sip.',
  '{{player}}, what lie about yourself do you tell most often? Answer or drink 3 sips.',
  '{{player}}, when was the last time you laughed so hard you could barely breathe? Answer or drink 2 sips.',
  '{{player}}, what secret about you does nobody in this group know? Spill it or drink 5 sips.',
  '{{player}}, what\'s the worst pickup line you\'ve ever heard? Answer or drink 2 sips.',
  '{{player}}, have you ever disappeared with someone at a party? Answer honestly or drink 4 sips.',
  '{{player}}, who from your school days would you love to see again? Answer or drink 2 sips.',
  '{{player}}, what\'s the most pointless impulse buy you\'ve ever made? Answer or drink 2 sips.',
  '{{player}}, what\'s your biggest red flag when dating? Answer honestly or drink 3 sips.',
  '{{player}}, what pickup line have you actually used yourself? Answer or drink 3 sips.',
  '{{player}}, who in this group would you most likely ask for dating advice? Answer or drink 2 sips.',
  '{{player}}, who in this group have you ever been jealous of? Answer honestly or drink 4 sips.',
  '{{player}}, what was your most embarrassing moment with your parents? Answer or drink 3 sips.',
  '{{player}}, what are you terrible at but love to claim you\'re good at? Answer or drink 3 sips.',
  '{{player}}, how many hours were you on your phone yesterday? Check and say the number or drink 3 sips.',
  '{{player}}, which movie have you seen at least 10 times? Answer or drink 1 sip.',
  '{{player}}, what prank did you pull at school that you never got caught for? Answer or drink 3 sips.',
  '{{player}}, what have you messed up at work and never admitted? Answer or drink 4 sips.',
  '{{player}}, who in this group has the best sense of style? Answer or drink 2 sips.',
  '{{player}}, what\'s the most childish thing you still do? Answer or drink 2 sips.',
  '{{player}}, what\'s the first thing you notice on a date? Answer honestly or drink 2 sips.',
  '{{player}}, what have you never told your best friend? Answer or drink 5 sips.',
  '{{player}}, whose story do you always watch right away? Answer or drink 3 sips.',
  '{{player}}, what was the most embarrassing slip of the tongue of your life? Answer or drink 2 sips.',
  '{{player}}, who in this group do you think is the funniest? Answer or drink 1 sip.',
  '{{player}}, what\'s the nicest thing you\'ve ever thought about {{player}} but never said? Say it or drink 3 sips.',
  '{{player}}, what was your most embarrassing outfit as a teenager? Answer or drink 2 sips.',
  '{{player}}, what name is your crush saved under in your phone? Answer or drink 3 sips.',
  '{{player}}, what\'s your most unpopular opinion? Answer or drink 2 sips.',
  '{{player}}, which rumor about you is actually true? Answer or drink 4 sips.',
  '{{player}}, who in this group would you swap lives with for a week? Answer or drink 2 sips.',
  '{{player}}, how did you last embarrass yourself in front of your crush? Answer or drink 4 sips.',
  '{{player}}, who in this group would you pick as your best man or maid of honor? Answer or drink 2 sips.',
  '{{player}}, what\'s the longest you\'ve ever taken to reply to a message? Answer or drink 2 sips.',
  '{{player}}, what would you do if you were invisible for a day? Answer honestly or drink 2 sips.',
  '{{player}}, what excuse do you use most often? Answer or drink 2 sips.',
  '{{player}}, who last sent you a message that secretly made your day? Answer or drink 3 sips.',
  '{{player}}, which of {{player}}\'s jokes did you only laugh at to be polite? Answer or drink 3 sips.',
  '{{player}}, what compliment made you really happy recently? Answer or drink 1 sip.',
  '{{player}}, when did you last fall for someone? Answer or drink 3 sips.',
  '{{player}}, read out the top entry in your notes app or drink 3 sips.',
  '{{player}}, what was your most embarrassing moment at the gym? Answer or drink 2 sips.',
  '{{player}}, who in this group would you pick as your quiz partner? Answer or drink 1 sip.',
  '{{player}}, what dumb thing from your past are you secretly proud of? Answer or drink 3 sips.',
  '{{player}}, what\'s the most embarrassing photo on your phone? Describe it or drink 4 sips.',
  '{{player}}, have you ever dated someone just to make someone else jealous? Answer or drink 4 sips.',
  '{{player}}, what\'s the weirdest thing you\'ve said or done in your sleep? Answer or drink 2 sips.',
  '{{player}}, what was your first thought this morning? Answer honestly or drink 2 sips.',

  'Vote: Who\'s most likely to fall asleep at a party? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to have a secret crush at work? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who has the most unread messages? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to win a reality show? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who falls in love the fastest? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to spill a secret? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s always late? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to fall asleep on a date? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who has the worst taste in music? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to secretly get married? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who has the most embarrassing photos on their phone? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to flirt with the boss? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s the worst liar? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to become famous? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to send a 10 minute voice message? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to be secretly active on a dating app? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to hijack the music at a party? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to flirt with strangers at the supermarket? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to drunk text their ex? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to get their partner\'s name tattooed? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who orders takeout the most? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to totally bomb on a quiz show? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who has the most crushes at the same time? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to have already googled someone in this group? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to forget where they parked the car? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to have played ding dong ditch as a kid? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to sneak a selfie with a celebrity? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who talks about themselves the most? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to spend an entire day in bed? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who has an excuse for everything? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who screams the loudest during a horror movie? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who turns everything into a drama? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to give an embarrassing speech at a wedding? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to secretly go through someone else\'s phone? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to have a secret second identity online? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to just stay on vacation and never fly home? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who flirts the most without realizing it? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s the biggest hit with everyone\'s parents? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to bring their best friend along on a date? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to secretly keep a diary? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to post a long caption for every anniversary? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to win every argument? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to confess their love in a voice message? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to be the reason a party gets out of hand? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who would struggle most to last a week without their phone? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who sings along the loudest in the car? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to fall for a fake account? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to still be friends with all their exes? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to photograph the food at a restaurant before anyone is allowed to eat? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to get their own talk show? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to hog the mic at karaoke? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to stalk new acquaintances online? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to win a dance competition? Whoever gets the most votes drinks 2 sips.',
  'Vote: Who\'s most likely to be in love without even knowing it? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who\'s most likely to make the first move when flirting? Whoever gets the most votes drinks 2 sips.',

  '{{player}}, who in this group has the most contagious laugh? That person drinks 2 sips.',
  '{{player}}, who in this group would be the most exhausting roommate? That person drinks 2 sips.',
  '{{player}}, who in this group is secretly a total romantic? That person drinks 2 sips.',
  '{{player}}, who in this group takes the longest in the bathroom in the morning? That person drinks 2 sips.',
  '{{player}}, who in this group sends the most memes? That person drinks 2 sips.',
  '{{player}}, who in this group has the weirdest sense of humor? That person drinks 2 sips.',
  '{{player}}, who in this group would be the best partner in crime for a prank? That person drinks 2 sips.',
  '{{player}}, who in this group got grounded the most as a kid? That person drinks 2 sips.',
  '{{player}}, who in this group is the worst dancer? That person drinks 2 sips.',
  '{{player}}, who in this group has the best poker face? That person drinks 2 sips.',
  '{{player}}, who in this group cancels plans last minute the most? That person drinks 2 sips.',
  '{{player}}, who in this group is the best flirt? That person drinks 2 sips.',
  '{{player}}, who in this group has the most selfies on their phone? That person drinks 2 sips.',
  '{{player}}, who in this group would make it furthest on a talent show? That person drinks 2 sips.',
  '{{player}}, who in this group is secretly the biggest nerd? That person drinks 2 sips.',
  '{{player}}, who in this group has the most secrets? That person drinks 3 sips.',
  '{{player}}, who in this group would be most likely to rat you out? That person drinks 3 sips.',
  '{{player}}, who in this group gets jealous the fastest? That person drinks 2 sips.',
  '{{player}}, who in this group should be honest more often? That person drinks 3 sips.',
  '{{player}}, who in this group gives the worst love advice? That person drinks 2 sips.',
  '{{player}}, who in this group would most likely show up to a party in pajamas? That person drinks 2 sips.',
  '{{player}}, who in this group is the biggest party animal? That person drinks 2 sips.',
  '{{player}}, who in this group lies the most in this game? That person drinks 3 sips.',
  '{{player}}, who in this group would have the funniest dating profile bio? That person drinks 2 sips.',
  '{{player}}, who in this group would be the most chaotic babysitter? That person drinks 2 sips.',
  '{{player}}, who in this group has the best luck with dates? That person drinks 2 sips.',
  '{{player}}, who in this group knows you best? You both drink 2 sips.',
  '{{player}}, who in this group types the slowest on their phone? That person drinks 2 sips.',
  '{{player}}, who in this group do you share the most inside jokes with? You both drink 2 sips.',
  '{{player}}, who in this group would have the most scandals as a celebrity? That person drinks 2 sips.',

  '{{player}} answers 3 questions from the group honestly or drinks 5 sips.',
  'Hot Seat: {{player}} sits in the hot seat for 1 minute and has to answer every question from the group. Every refused answer costs 2 sips.',
  'Hot Seat: Everyone takes turns asking {{player}} a question about love. Every skipped question costs 2 sips.',
  '{{player}} has to answer 2 questions from {{player}} honestly or drink 4 sips.',
  'Hot Seat: {{player}} can only answer the group\'s next 3 questions with yes or no. If a lie gets exposed, that\'s 3 sips.',
  'Hot Seat: {{player}} answers 3 questions about their school days. Every refused answer costs 2 sips.',
  'Hot Seat: {{player}} answers 3 questions about their last date honestly or drinks 5 sips.',
  '{{player}} and {{player}} each ask the other one honest question. Whoever doesn\'t answer drinks 3 sips.',
  'Hot Seat: {{player}} has to answer every question from the group for 30 seconds without hesitating. Every hesitation costs 1 sip.',
  'Hot Seat: The group asks {{player}} 3 questions about their phone. Every refused answer costs 2 sips.',
  'Hot Seat: The group agrees on one single question for {{player}}. Answer honestly or drink 5 sips.',
  'Hot Seat: Everyone asks {{player}} one question about their current crush. Every excuse costs 2 sips.',
  '{{player}} answers 2 questions from the group about work or school honestly or drinks 4 sips.',
  'Hot Seat: {{player}} comes up with a really awkward question for {{player}}. Whoever doesn\'t answer drinks 5 sips.',
  'Hot Seat: {{player}} asks the person to their right 3 honest questions. Every refusal costs 2 sips.',
  'Hot Seat: {{player}} answers 3 questions about embarrassing childhood moments or drinks 4 sips.',
  'Hot Seat: {{player}} tells everyone in the group one honest sentence about them. Every skipped sentence costs 2 sips.',
  'Hot Seat: The group asks {{player}} 3 questions, each time choosing between 2 people in the group. Every refusal costs 2 sips.',
  'Hot Seat: {{player}} answers 3 questions about their first kiss honestly or drinks 5 sips.',
  'Hot Seat: Everyone gets to ask {{player}} one question about the people in this group. Every refused answer costs 2 sips.',
];
