export const wildTasksEn: string[] = [
  'Vote: Who would be most likely to audition for a reality show? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to give an uninvited speech at a wedding? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to book a spontaneous vacation in the middle of the night? Whoever gets the most votes gives out 4 sips.',
  'Vote: Who would be most likely to refuse to give up the mic at karaoke? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who would be most likely to beg a celebrity for a selfie on the street? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to argue with the DJ about the bad music? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who would be most likely to trip over their own feet while flirting? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to do nothing on a group project and still present it? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be the first to walk into the dark basement in a horror movie? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who would be most likely to win a TV dance competition? Whoever gets the most votes gives out 5 sips.',
  'Vote: Who would be most likely to secretly change the playlist at a party? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who would be the first to give up in an escape room? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to send a 10 minute voice message? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to land the lead role in a cheesy soap opera? Whoever gets the most votes gives out 4 sips.',
  'Vote: Who would be the first to fall asleep at their own birthday party? Whoever gets the most votes drinks 5 sips.',
  'Vote: Who would be most likely to blow the very first question on a quiz show? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to tell a stranger on the train their whole life story? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who would be most likely to start a fight with a voice assistant? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who would be most likely to bring the worst gift to Secret Santa? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to shoot a music video starring themselves? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to sneak the last fries off someone else\'s plate? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who would be most likely to cheat at Monopoly? Whoever gets the most votes drinks 5 sips.',
  'Vote: Who would be most likely to have a meltdown on a talk show? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to become a famous influencer? Whoever gets the most votes gives out 4 sips.',
  'Vote: Who would be most likely to push everyone else off the dance floor? Whoever gets the most votes drinks 3 sips.',
  'Vote: Who would be most likely to talk about wedding plans on a first date? Whoever gets the most votes drinks 5 sips.',
  'Vote: Who would be most likely to show up in costume to a party where nobody else dressed up? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to survive a week without their phone? Whoever gets the fewest votes drinks 4 sips.',
  'Vote: Who would be most likely to try climbing on stage at a concert? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to start a conversation with the decorations at a party? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to go on a dating show? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to run into their ex at a party and pretend everything is amazing? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to keep up a fake accent for a whole night just for laughs? Whoever gets the most votes gives out 4 sips.',
  'Vote: Who would be most likely to take on the most embarrassing dare at a bachelor or bachelorette party? Whoever gets the most votes drinks 5 sips.',
  'Vote: Who would be most likely to burn the food in a cooking competition? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would be most likely to text the wrong person and only notice the next day? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who has the best vibe tonight? Whoever gets the most votes gives out 5 sips.',
  'Vote: Who will be the first to get tired tonight? Whoever gets the most votes drinks 4 sips.',
  'Vote: Who would survive the longest in a zombie apocalypse? Whoever gets the most votes gives out 5 sips.',
  'Vote: Who has the most talent for a career as a cheesy pop star? Whoever gets the most votes sings a line or drinks 4 sips.',
  'Vote: Who would be most likely to buy a round for a bar full of strangers? Whoever gets the most votes drinks 3 sips.',
  'On 3, everyone points at the person most likely to flirt with the waiter. Whoever gets the most fingers drinks 4 sips.',
  'On 3, everyone points at the person with the craziest taste in music. Whoever gets the most fingers drinks 4 sips.',
  'On 3, everyone points at the loudest person tonight. Whoever gets the most fingers drinks 4 sips.',
  'On 3, everyone points at the person who takes the longest in the bathroom. Whoever gets the most fingers drinks 3 sips.',
  'On 3, everyone points at the person who would be first to act on a crazy idea. Whoever gets the most fingers gives out 4 sips.',
  'On 3, everyone points at the person who is worst at keeping secrets. Whoever gets the most fingers drinks 5 sips.',
  'On 3, everyone points at the biggest drama queen. Whoever gets the most fingers drinks 4 sips.',
  'On 3, everyone points at the person they\'d most like to travel the world with. Whoever gets the most fingers gives out 5 sips.',
  'Everyone who has ever texted the wrong person drinks 3 sips.',
  'Everyone who has ever fallen asleep at a party drinks 4 sips.',
  'Everyone who has ever written a love letter drinks 3 sips.',
  'Everyone who has ever pretended not to know someone just to avoid talking to them drinks 3 sips.',
  'Everyone who has ever been caught lying drinks 4 sips.',
  'Everyone who has ever given a fake name at a bar drinks 4 sips.',
  'Everyone who has ever scrolled all the way to the bottom of their crush\'s profile drinks 4 sips.',
  'Everyone who has ever accidentally liked someone\'s ancient photo drinks 5 sips.',
  'Everyone who has ever gotten back together with an ex drinks 4 sips.',
  'Everyone who has ever fallen over while dancing drinks 3 sips.',
  'Everyone who has ever regifted a present drinks 3 sips.',
  'Everyone who has ever made up an excuse to skip a party drinks 4 sips.',
  'Everyone who has ever practiced an award acceptance speech in the mirror drinks 4 sips.',
  'Everyone with a celebrity crush they\'re a little embarrassed about drinks 3 sips and reveals who it is.',
  'Everyone who has ever completely forgotten about a date drinks 5 sips.',
  'Everyone who has ever ghosted someone drinks 4 sips.',
  'Everyone who has ever been ghosted gives out 3 sips to someone who deserves it.',
  'Everyone who has ever slept through an appointment or an exam drinks 3 sips.',
  'Everyone who has a nickname they secretly hate drinks 3 sips.',
  'Everyone who has ever flirted with someone in this group drinks 4 sips.',
  'Everyone who has ever sent something embarrassing to the family group chat drinks 4 sips.',
  'Everyone who has ever pretended to have read a book drinks 3 sips.',
  'Everyone who has ever cheated at a board game drinks 4 sips.',
  'Everyone whose phone battery is below 20 percent right now drinks 3 sips.',
  'Everyone who is single gives out 3 sips. Everyone who is taken drinks 3 sips.',
  'Everyone who has ever confessed their love to someone after a few drinks drinks 4 sips.',
  'Everyone who has ever danced on a table drinks 4 sips.',
  'Everyone who has ever cut their own hair and instantly regretted it drinks 3 sips.',
  'Everyone who has ever messaged a celebrity drinks 4 sips.',
  'Everyone who has ever been sent out of class for not being able to stop laughing drinks 4 sips.',
  'Everyone who has ever crashed a party they weren\'t invited to drinks 5 sips.',
  'Everyone who has ever bought a last minute gift at a gas station drinks 3 sips.',
  'Everyone who has ever woken up wishing they could delete a text from the night before drinks 5 sips.',
  'Everyone who has ever forgotten the other person\'s name on a first date drinks 5 sips.',
  'Everyone who has ever secretly snooped through someone else\'s bathroom cabinet drinks 4 sips.',
  'Everyone who has ever watched a movie just because of one actor drinks 3 sips.',
  'Everyone who has ever regretted a kiss at a party drinks 4 sips.',
  'Everyone who has ever had a vacation fling drinks 4 sips.',
  'Everyone who has ever taken a selfie with a celebrity gives out 4 sips.',
  'Everyone who has ever talked out loud to the people on the TV drinks 3 sips.',
  'Everyone who has ever bought an outfit just for a photo and then returned it drinks 4 sips.',
  'Everyone who has ever had a fight over a board game drinks 4 sips.',
  'Everyone who has ever been to a festival drinks 3 sips. If you\'ve been to more than 5, give them out instead.',
  'Everyone who has ever kissed someone without knowing their name drinks 5 sips.',
  'Everyone who has already spent more than 3 hours on their phone today drinks 3 sips.',
  'Everyone who has ever danced at a wedding until their shoes broke drinks 3 sips.',
  'Everyone who has ever lost a bet and never paid up drinks 5 sips.',
  'Everyone who has ever cried at a romance movie gives out 3 sips, because feelings are valid.',
  'Everyone who has ever looked for their phone while holding it drinks 3 sips.',
  'Everyone who has ever ordered something totally pointless online at 3 a.m. drinks 4 sips.',
  'Everyone who has ever stood in the front row at a concert gives out 4 sips.',
  'Everyone who has ever lied to their parents about their night with a creative excuse drinks 4 sips.',
  'Last person to put their hand on their head drinks 4 sips.',
  'Last person to stand up drinks 4 sips.',
  'Last person to point at {{player}} drinks 3 sips.',
  'Last person to raise their glass in the air drinks 4 sips.',
  'Last person to cross their arms drinks 4 sips.',
  'Last person to shout "Cheers" drinks 5 sips.',
  'Last person to put both hands flat on the table drinks 4 sips.',
  'First person to find a cat photo on their phone gives out 4 sips.',
  'First person to hold up something red gives out 4 sips. Last person to find something drinks 3.',
  'First person to name 5 Disney movies gives out 5 sips.',
  'For the next 3 cards, nobody can say the word "drink". Anyone who does drinks 3 sips.',
  '{{player}}, you are now the Question Master. Anyone who answers one of your questions in the next 3 cards drinks 3 sips.',
  '{{player}}, you are now the Thumb Master. If you quietly put your thumb on the table during the next 5 cards, the last person to copy you drinks 4 sips.',
  'For the next 3 cards, everyone drinks only with their weak hand. Forget and you drink 3 extra sips.',
  '{{player}}, you can only whisper for the next 3 cards. Every loud word costs you 2 sips.',
  '{{player}} and {{player}} are drinking buddies for the next 3 cards. Whenever one drinks, the other drinks the same amount.',
  'For the next 4 cards, swearing is banned. Every swear word costs 3 sips.',
  '{{player}}, for the next 3 cards you must end every sentence with "my lord". Every slip costs 2 sips.',
  'For the next 3 cards, first names are banned. Anyone who says a name drinks 3 sips.',
  'For the next 3 cards, everyone has to shout "To the legends" before drinking. Forget and you drink double.',
  '{{player}}, speak with a French accent for the next 3 cards. Every slip costs 2 sips.',
  '{{player}}, you are {{player}}\'s butler for the next 3 cards and must hand them their glass before every sip. Forget and you drink 3 sips.',
  'For the next 5 cards: anyone who laughs out loud drinks 1 sip.',
  '{{player}}, for the next 3 cards you have to repeat out loud everything {{player}} says. Every missed sentence costs 2 sips.',
  'For the next 3 cards, the word "yes" is banned. Anyone who says it drinks 3 sips.',
  'Anyone who touches their phone during the next 3 cards drinks 4 sips.',
  '{{player}} makes up a new rule for the next 5 cards. Anyone who breaks it drinks 3 sips.',
  '{{player}}, you are King or Queen for the next 3 cards. Anyone who talks to you without calling you "Your Majesty" drinks 2 sips.',
  '{{player}}, for the next 3 cards you can only answer with yes or no. Every other word costs 2 sips.',
  '{{player}} is {{player}}\'s mirror for the next 3 cards and has to copy every move. Whoever gets caught drinks 3 sips.',
  'For the next 3 cards, everyone has to raise their hand before speaking. Anyone who talks without raising it drinks 2 sips.',
  '{{player}}, for the next 3 cards you can only refer to yourself in the third person. Every slip costs 2 sips.',
  'For the next 3 cards, everyone has to clink glasses with {{player}} before drinking. Forget and you drink 2 extra sips.',
  '{{player}}, you are the group\'s shadow for the next 3 cards: every time someone drinks, you drink 1 sip too.',
  'For the next 3 cards, nobody can point at anything. Anyone who points drinks 3 sips.',
  '{{player}}, for the next 3 cards every answer you give needs a little rhyme. No rhyme and you drink 2 sips.',
  '{{player}}, you get a joker. You can turn down any later card without drinking.',
  '{{player}}, you can pass the next card that hits you on to {{player}}.',
  '{{player}} is the bartender for the next 3 cards. Anyone who drinks has to politely thank them first, or drink 2 extra sips.',
  'For the next 3 cards, everyone has to talk like a news anchor. Anyone who breaks character drinks 3 sips.',
  'Category car brands: {{player}} starts, then everyone names one in turn. Whoever hesitates or repeats one drinks 4 sips.',
  'Category football clubs: {{player}} starts, then everyone names one in turn. Whoever hesitates or repeats one drinks 4 sips.',
  'Category cocktails: {{player}} starts, then everyone names one in turn. Whoever hesitates or repeats one drinks 4 sips.',
  'Category Pokémon: {{player}} starts, then everyone names one in turn. Whoever hesitates or repeats one drinks 4 sips.',
  'Staring contest between {{player}} and {{player}}. Whoever blinks or laughs first drinks 4 sips.',
  'Rock, paper, scissors between {{player}} and {{player}}, best of 3. The loser drinks 5 sips.',
  'Thumb war between {{player}} and {{player}}. The loser drinks 4 sips.',
  '{{player}} hums a song. Whoever guesses it first gives out 4 sips. If nobody gets it in 30 seconds, the hummer drinks 4 sips.',
  'Charades: {{player}} acts out a movie. Whoever guesses it gives out 3 sips. If nobody gets it in 1 minute, the actor drinks 4 sips.',
  'Charades: {{player}} acts out a job. Whoever guesses it gives out 3 sips. If nobody gets it in 1 minute, the actor drinks 4 sips.',
  'Charades: {{player}} acts out an animal, and only {{player}} can guess. If it doesn\'t work in 30 seconds, both drink 3 sips.',
  'Charades: {{player}} acts out a sport. Whoever guesses it gives out 3 sips. If nobody gets it, the actor drinks 3 sips.',
  'Charades: {{player}} acts out a famous celebrity. Whoever guesses it gives out 4 sips, otherwise the actor drinks 4 sips.',
  '{{player}} impersonates someone in the group without saying their name. Whoever guesses who it is first gives out 3 sips.',
  '{{player}}, impersonate a famous celebrity. If someone guesses who it is, you give out 4 sips, otherwise you drink 4.',
  'Word chain: {{player}} says a word, then everyone in turn says a word starting with the last letter of the previous one. Whoever stalls drinks 4 sips.',
  'Buzz: Count around the circle, and say "Buzz" for every number that contains a 7 or is divisible by 7. {{player}} starts, and whoever messes up drinks 4 sips.',
  '{{player}} thinks of a number between 1 and 20. Everyone takes turns guessing, and whoever gets it gives out 5 sips.',
  '{{player}}, name 5 beer brands in 10 seconds or drink 4 sips.',
  '{{player}}, name 5 European capitals in 10 seconds or drink 4 sips.',
  '{{player}}, name 5 Harry Potter characters in 10 seconds or drink 4 sips.',
  '{{player}}, name 5 Taylor Swift songs in 10 seconds or drink 5 sips.',
  '{{player}} and {{player}} take turns naming capital cities. Whoever runs out first drinks 5 sips.',
  '{{player}} and {{player}} take turns naming Leonardo DiCaprio movies. Whoever runs out first drinks 4 sips.',
  '{{player}} tells 2 truths and 1 lie about themselves. Whoever spots the lie gives out 2 sips, whoever guesses wrong drinks 2.',
  '{{player}}, say the alphabet backwards from Z to P without a mistake, or drink 4 sips.',
  '{{player}}, say "She sells seashells by the seashore" 3 times fast without a mistake, or drink 3 sips.',
  '{{player}}, balance a coaster on your head for 20 seconds while walking once around the table. Pull it off and you give out 4 sips, otherwise you drink 4.',
  '{{player}}, hold a plank for 30 seconds. Pull it off and you give out 4 sips, otherwise you drink 4.',
  '{{player}}, do 15 jumping jacks while everyone counts out loud, or drink 4 sips.',
  'Silence challenge: the whole group stays quiet for 30 seconds. Whoever makes the first sound drinks 4 sips.',
  'Everyone shows their screen time from yesterday. Highest number drinks 4 sips, lowest gives out 4.',
  'Whoever at the table has the most unread messages drinks 4 sips.',
  'Whoever at the table has the most photos in their gallery drinks 3 sips. Whoever has the fewest gives out 3.',
  '{{player}}, read out the last message you sent, or drink 4 sips.',
  '{{player}}, show the group the fifth most recent photo in your gallery, or drink 5 sips.',
  '{{player}}, read out your last 3 browser searches, or drink 5 sips.',
  '{{player}}, show the group the most embarrassing song on your playlist, or drink 4 sips.',
  '{{player}}, show the oldest photo in your gallery, or drink 4 sips.',
  '{{player}}, give a dramatic farewell speech to your glass, then drink 3 sips.',
  '{{player}}, make a passionate declaration of love to the object closest to you. If anyone laughs, you give out 3 sips, otherwise you drink 3.',
  '{{player}}, commentate the next card like a sports commentator. Anyone who laughs drinks 2 sips.',
  '{{player}}, sing the chorus of a cheesy pop song with full passion, or drink 4 sips.',
  '{{player}}, dance for 20 seconds without music like you\'re in a music video, or drink 4 sips.',
  '{{player}}, strut once across the room like it\'s a catwalk, or drink 4 sips.',
  '{{player}}, give a 30 second campaign speech on why you deserve to be crowned ruler of the group. If most people clap, you give out 5 sips, otherwise you drink 3.',
  '{{player}}, give everyone in the group a compliment within 30 seconds, or drink 4 sips.',
  '{{player}}, sing like an opera star for 10 seconds, or drink 4 sips.',
  '{{player}}, tell a joke. If anyone laughs, you give out 4 sips. If nobody laughs, you drink 4.',
  '{{player}}, talk like a pirate until your next sip. Forget and you drink 3 extra sips.',
  '{{player}} and {{player}}, act out a famous movie scene together. If the group guesses the movie, you both give out 3 sips, otherwise you both drink 3.',
  '{{player}}, do your best animal noise. The group votes, and if it isn\'t convincing, you drink 4 sips.',
  '{{player}}, make a commercial for {{player}}\'s drink. If most people want to try it afterwards, you give out 4 sips, otherwise you drink 3.',
  '{{player}}, let {{player}} give you a new hairstyle with their hands and keep it until the next card, or drink 4 sips.',
  '{{player}} gives {{player}} a new nickname. For the next 5 cards everyone has to use it, and anyone who forgets drinks 2 sips.',
  '{{player}}, put an object from the table on your head as a hat for the next 3 cards. If it falls off, you drink 3 sips.',
  '{{player}}, write your name in the air with your hips, or drink 4 sips.',
  '{{player}}, do 10 jumping jacks and shout "I\'m a star" with each one, or drink 5 sips.',
  '{{player}}, for the next minute you can only speak in questions. Every statement costs you 2 sips.',
  '{{player}}, dance like a robot for 30 seconds, or drink 4 sips.',
  '{{player}}, you have 20 seconds to make {{player}} laugh without touching them. If they laugh, they drink 4 sips, otherwise you drink 4.',
  '{{player}}, describe your favorite movie in 3 sentences without saying any names. If someone guesses it, you give out 3 sips, otherwise you drink 3.',
  '{{player}}, play a GPS and guide {{player}} once around the table with their eyes closed. If it doesn\'t work, you both drink 3 sips.',
  '{{player}}, introduce yourself to the group in 20 seconds like you\'re speed dating. If most people want to see you again, you give out 4 sips.',
  '{{player}}, rap 4 lines about {{player}}, or drink 5 sips.',
  '{{player}}, sing "Baby" by Justin Bieber in a heavy metal voice, or drink 5 sips.',
  '{{player}}, impersonate {{player}} ordering at the bar. If they laugh, you give out 3 sips, otherwise you drink 3.',
  '{{player}}, propose to {{player}}, totally dramatic and down on one knee. If they say yes, you both give out 3 sips, otherwise you drink 4.',
  '{{player}}, spend 20 seconds acting out a pop star making their grand entrance into a stadium, or drink 4 sips.',
  '{{player}}, act out bumping into a celebrity of your choice on the street. If the group guesses who it is, you give out 4 sips.',
  '{{player}}, reveal your most embarrassing childhood nickname, or drink 4 sips.',
  '{{player}}, tell us your most embarrassing moment on a date, or drink 5 sips.',
  '{{player}}, say who in the group has the most questionable taste in music. That person drinks 3 sips. Refuse and you drink 5.',
  '{{player}}, describe {{player}} in 3 honest but nice words, or drink 4 sips.',
  '{{player}}, reveal which celebrity you secretly think is pretty great, or drink 4 sips.',
  '{{player}}, reveal the last thing you googled, or drink 4 sips.',
  '{{player}}, confess your worst fashion crime, or drink 3 sips.',
  '{{player}}, let {{player}} ask you a question you have to answer honestly, or drink 5 sips.',
  '{{player}}, reveal who in the group you\'d call for help at 3 a.m., or drink 4 sips.',
  '{{player}}, say who in the group you\'d most like as a roommate. That person gives out 3 sips. Refuse and you drink 4.',
  '{{player}}, reveal the worst pickup line you\'ve actually used, or drink 4 sips.',
  '{{player}}, tell us the craziest reason you\'ve ever left a party, or drink 4 sips.',
  '{{player}}, reveal the app you use the most and least want to admit to, or drink 4 sips.',
  '{{player}}, say who in the group is most likely to dance on a table tonight. That person drinks 3 sips, and you give out 2.',
  '{{player}}, tell us about your most embarrassing school crush, or drink 4 sips.',
  '{{player}}, admit which show you secretly watch even though it\'s terrible, or drink 3 sips.',
  '{{player}}, reveal what you wanted to be as a kid and why it didn\'t work out, or drink 3 sips.',
  '{{player}}, choose: speak only in rhymes for the next 3 cards, or drink 5 sips.',
  '{{player}}, choose: sing a chorus of your choice, or drink 4 sips.',
  '{{player}}, choose: dance for 20 seconds to a song {{player}} picks, or drink 5 sips.',
  '{{player}}, choose: give out 4 sips to one person, or 1 sip to everyone else.',
  '{{player}}, choose: drink 3 sips alone, or you and {{player}} drink 2 each.',
  '{{player}}, choose: swap seats with {{player}} for 3 cards, or drink 4 sips.',
  '{{player}}, choose: tell us the last dream you remember, or drink 4 sips.',
  '{{player}}, choose: truth or 5 sips. If you pick truth, {{player}} gets to ask you a question.',
  '{{player}} gives out 6 sips however they like.',
  '{{player}} and {{player}} have to drink 7 sips together. They have 10 seconds to agree on how to split them, or each drinks 5.',
  'Double or nothing: {{player}} guesses the color of {{player}}\'s socks. Right: give out 6 sips. Wrong: drink 3 sips.',
  '{{player}}, guess {{player}}\'s star sign. If you\'re right, you give out 5 sips, otherwise you drink 3.',
  '{{player}}, guess {{player}}\'s battery percentage. If you\'re within 10, you give out 4 sips, otherwise you drink 4.',
  '{{player}}, guess how many contacts {{player}} has in their phone. If you\'re within 50, you give out 5 sips, otherwise you drink 3.',
  '{{player}}, guess the last song {{player}} listened to. If you\'re right, you give out 6 sips.',
  'Waterfall: {{player}} starts drinking, everyone else follows in turn and can only stop once the person before them stops.',
  'Everyone drinks 2 sips. Last person to put their glass down drinks 2 more.',
  'Everyone clinks glasses and drinks 3 sips. Anyone who doesn\'t make eye contact while clinking drinks 2 more.',
  '{{player}}, down your drink. After that you can turn down any card that hits you for the next 3 cards.',
  'High stakes: {{player}} and {{player}} play one round of rock, paper, scissors. The loser downs their drink.',
  'Group pact: Everyone drinks 3 sips at the same time, except {{player}}, who gets to watch and cheer.',
  'The person with the fullest glass drinks 4 sips.',
  'The person with the emptiest glass gives out 4 sips and gets a refill.',
  'The person with the next birthday gives out 5 sips.',
  'The person who traveled the farthest to be here today gives out 5 sips.',
  'The person who has been single the longest gives out 4 sips.',
  'The person who had the most recent hangover drinks 3 sips.',
  'Whoever is wearing the flashiest shoes today gives out 4 sips. The group decides.',
  '{{player}} and {{player}} swap drinks for the next 3 cards.',
  '{{player}}, the next 3 sips you would have to drink go to {{player}} instead.',
  'Battle of the voices: {{player}} and {{player}} sing different songs at the same time. Whoever stops or laughs first drinks 4 sips.',
  'Battle of compliments: {{player}} and {{player}} take turns complimenting each other. Whoever runs out first drinks 4 sips.',
  'Battle of the faces: {{player}} and {{player}} pull faces and the group votes. The loser drinks 4 sips.',
  '{{player}} and {{player}} try to say the same word at the same time after {{player}} names a category. If it doesn\'t work on the first try, both drink 3 sips.',
  '{{player}} and {{player}} sit back to back. {{player}} asks questions like "Who\'s more likely to be late?" and both point at the same time. For 3 questions, both drink 1 sip every time they disagree.',
  '{{player}} and {{player}} hold hands and can\'t let go for 3 cards. Whoever lets go first drinks 4 sips.',
  '{{player}} and {{player}} stand on one leg with their eyes closed. Whoever wobbles and has to put their foot down first drinks 4 sips.',
  '{{player}} and {{player}} tell their favorite joke at the same time. Whoever gets the most laughs gives out 4 sips, the other drinks 3.',
  'Everyone takes turns saying one word until it forms a sentence. {{player}} starts. Whoever makes the sentence stop making sense drinks 3 sips.',
  'I\'m going on a picnic: {{player}} starts. Whoever forgets something or mixes up the order drinks 4 sips.',
  'Everyone takes turns naming a movie with Tom Hanks in it. {{player}} starts, and whoever runs out drinks 4 sips.',
  'Never have I ever: everyone takes turns saying something they\'ve never done. Anyone who has done it drinks 2 sips. {{player}} starts.',
  'Everyone guesses how many sips they\'ve had today. Whoever says the highest number gets to give out 4 sips.',
  'On 3, everyone says a number between 1 and 5 at the same time. Anyone who says the same number as someone else drinks that many sips.',
  'On 3, everyone holds up 0 to 5 fingers. {{player}} guesses the total beforehand. Right: give out 6 sips. Wrong: drink 3 sips.',
  'Everyone who has already danced today gives out 3 sips. Everyone else dances for 10 seconds now or drinks 3.',
  '{{player}}, you\'re the host for the next card: read it out like an awards show announcer. Refuse and you drink 3 sips.',
  '{{player}}, shout "I am the party legend of the night" once, loud. The group cheers or you drink 3 sips.',
  '{{player}}, give a toast to {{player}} that is at least 3 sentences long. Then everyone drinks 2 sips.',
  '{{player}}, give the group a toast nobody has heard before. If they like it, everyone else drinks 2 sips.',
  '{{player}}, invent a salute with a hand gesture. For the next 3 cards everyone has to do it before drinking, or drink 2 extra sips.',
  '{{player}}, act out a commercial for yourself as the perfect party guest. If you convince the group, you give out 4 sips.',
  '{{player}}, impersonate how {{player}} dances. If they approve, you both give out 3 sips.',
  '{{player}}, tell a made up story about {{player}} as if it were true. If the group believes it, you give out 4 sips, otherwise you drink 3.',
  '{{player}}, let {{player}} pick a sentence you have to sneak into the next card. If anyone notices, you drink 4 sips.',
  '{{player}}, you can\'t laugh until the card after next. If someone makes you laugh, you drink 4 sips and they give out 2.',
  '{{player}}, you have 1 minute to make 3 people in the group laugh. Pull it off and you give out 6 sips, otherwise you drink 4.',
  '{{player}}, you stay standing for the next 2 cards. If you sit down, you drink 3 sips.',
  '{{player}}, tell your whole life story in 30 seconds in the style of a documentary. If you don\'t make it, you drink 3 sips.',
  '{{player}}, imagine you\'re on a cooking show and mime cooking a dish. If the group guesses it, you give out 3 sips.',
  '{{player}}, make an announcement like an airline pilot, turbulence included. Anyone who laughs drinks 2 sips.',
  '{{player}}, announce like a wedding planner who in the group will get married first. That person drinks 3 sips.',
  '{{player}}, sing "Happy Birthday" to {{player}}, even though it isn\'t their birthday. Then they give out 3 sips.',
  '{{player}}, give {{player}} 10 seconds of honest praise about their outfit. If you can\'t think of anything, you drink 4 sips.',
  '{{player}}, pick someone to improvise a 20 second boy band routine with you, or drink 5 sips.',
  '{{player}}, play an influencer promoting the drink in your hand on their story. Then everyone drinks 1 sip to it.',
  '{{player}}, strike a dramatic pose and hold it until the end of the next card. Moving early costs 4 sips.',
  '{{player}}, play the host of a dating show and match up 2 people in the group. Those 2 drink 3 sips together.',
  '{{player}}, imagine you just won an Oscar and give your acceptance speech. If the group likes it, you give out 5 sips.',
  '{{player}}, list 5 things you like about {{player}} in 10 seconds, or drink 4 sips.',
  '{{player}}, pick someone to take the next card with your name on it for you. In return, you drink 3 sips now.',
  'Vote: Who is the bigger party animal, {{player}} or {{player}}? Whoever gets fewer votes drinks 4 sips.',
];
