export const coworkersQuestionsEn: string[] = [
  'Who is most likely to fall asleep in a meeting?',
  'Which of you has forgotten to mute themselves on a video call?',
  'Who has most likely sent an email to the wrong person?',
  'Who is most likely to take the last cup of coffee and not make a new pot?',
  'Which of you answers emails even at midnight?',
  'Who is most likely to work from home in their pajamas?',
  'Who is most likely to hit a deadline with five minutes to spare?',
  'Which of you has pretended to have a bad internet connection?',
  'Who is most likely to be running this company in five years?',
  'Who has most likely secretly worked on something else during a meeting?',
  'Who is most likely to be the last one to leave the holiday party?',
  'Which of you has the messiest desk?',
  'Who is most likely to schedule a meeting that could have been an email?',
  'Who is most likely to quit on a whim and travel the world?',
  'Which of you sends the most emojis in the team chat?',
  "Who is most likely to answer every question with: Let's take this offline?",
  'Who has most likely never emptied the dishwasher in the office kitchen?',
  'Who is most likely to be late to every meeting?',
  'Which of you has the most browser tabs open?',
  'Who has most likely improvised an entire presentation?',
  'Who is most likely to turn the office into a jungle of plants?',
  'Which of you always hears the office gossip first?',
  'Who is most likely to open the dance floor at the company party?',
  'Who has most likely eaten on a video call with the camera on?',
  'Who is most likely to make a spreadsheet for their grocery list?',
  'Which of you says "quick question" the most?',
  'Who has most likely taken vacation and still checked their emails?',
  'Who is most likely to surprise the team with a homemade cake?',
  'Which of you has started a meeting and forgotten to send the link?',
  'Who most likely has the most embarrassing profile picture in the team chat?',
  'Who is most likely unable to form a single sentence without coffee?',
  'Which of you would celebrate a promotion the loudest?',
  'Who has most likely hit Reply All when there was no need?',
  'Who is most likely to organize the entire holiday party alone?',
  'Who most likely has the most passwords written on sticky notes?',
  'Who is most likely to nod along in a meeting without listening?',
  'Which of you would win the lottery and still show up to work on Monday?',
  'Who is most likely to suggest an escape room as a team event?',
  'Who has most likely set their status to Away just to get some peace?',
  'Who is most likely to eat nothing but cafeteria food for a whole week?',
  'Which of you has accidentally been way too casual or way too formal with the boss?',
  'Who is most likely to start their own company?',
  'Who is most likely to talk way too loudly on the phone in the open office?',
  'Which of you most often brings sweets for everyone?',
  'Who is most likely to send an email about an attachment and forget the attachment?',
  'Who has most likely slept through a meeting entirely?',
  'Who is most likely to become employee of the month?',
  'Which of you would be the most competitive at the company soccer tournament?',
  'Who is most likely to bring the weirdest gift to Secret Santa?',
  'Who has most likely spent the night at the office?',
  'Who is most likely to document every little thing in a ticket?',
  'Which of you would best survive a week without a laptop?',
  'Who is most likely to be the first to disappear on Friday afternoon?',
  'Who most likely has the best stock of excuses for being late?',
  'Who is most likely to break the coffee machine?',
  'Which of you would star in an office soap opera?',
  'Who is most likely to spend an hour debating the perfect folder structure?',
  'Who has most likely sent a voice message in the work chat?',
  'Who is most likely to bike to the office in the pouring rain?',
  "Which of you knows every coworker's birthday by heart?",
  'Who most likely has the tidiest computer desktop?',
  'Who is most likely to open a meeting with a joke nobody laughs at?',
  'Which of you has started an email with "As previously mentioned"?',
  'Who is most likely to secretly change the office thermostat?',
  'Who has most likely shared their screen and shown something embarrassing?',
  'Who is most likely to get the company logo tattooed?',
  'Which of you would sing karaoke the loudest at a team event?',
  'Who is most likely to start small talk with the CEO in the elevator?',
  'Who is most likely to quickly finish one more thing after clocking out?',
  'Who is most likely to write a twelve-point agenda for a ten-minute meeting?',
  'Which of you takes the prettiest meeting notes that nobody ever reads?',
  'Who is most likely to show up to a meeting they were never invited to?',
  'Who is most likely to take the minutes because nobody else volunteers?',
  'Which of you always asks one more question at the end of a meeting when everyone is getting up?',
  'Who has most likely waited in the wrong meeting room?',
  'Who is most likely to pitch the craziest ideas in a brainstorm?',
  'Which of you says "I\'m totally with you on that" the most in meetings?',
  'Who is most likely to book a meeting room for the whole day, just in case?',
  'Who has most likely attended a meeting just for the cookies?',
  'Who is most likely to turn a retrospective into a therapy session?',
  'Who is most likely to schedule a meeting to prepare for the next meeting?',
  'Who is most likely to fill a flipchart in a meeting with something nobody can decipher?',
  'Which of you has the best virtual background when working from home?',
  'Who has most likely had a pet wander into a video meeting?',
  'Which of you has worn a dress shirt on top and sweatpants below while working from home?',
  "Who is most likely to forget it's an office day while working from home?",
  'Which of you has the most ergonomic setup at home?',
  'Who has most likely accepted a package delivery during a call?',
  'Who is most likely to not leave the house for three days while working from home?',
  'Who has most likely talked on a video call as a potato because of a filter?',
  'Who is most likely to buy a second monitor for working from home and then want a third?',
  'Which of you loves working from home with music at full volume?',
  'Who is most likely to work from a café and call it working from home?',
  'Who is most likely to put up a sign with rules for the office kitchen?',
  'Who most likely has the most mugs lying around the office?',
  'Who is most likely to bring their own espresso machine to the office?',
  'Who is most likely to get stuck chatting in the office kitchen for an hour?',
  'Which of you has a favorite mug that nobody else is allowed to use?',
  'Who is most likely to label their food before putting it in the fridge?',
  'Who has most likely reheated fish in the office microwave?',
  'Who is most likely to drink tea just to be different from everyone else?',
  'Who is most likely to secretly finish off the leftover cake in the office kitchen?',
  'Who is most likely to start a petition for better coffee?',
  'Who is most likely to order oat milk for the whole office?',
  'Which of you tells the best weekend stories in the office kitchen?',
  'Which of you writes the longest emails?',
  'Who is most likely to reply to an email with just one word?',
  'Who has most likely ended an email to upper management with "Lots of love"?',
  'Who is most likely to mark emails as urgent with three exclamation points?',
  'Who is most likely to print out emails to read them in peace?',
  'Who has most likely forgotten to turn off their out-of-office reply?',
  'Who is most likely to reach inbox zero and tell everyone about it?',
  'Which of you loves to CC the boss?',
  'Who is most likely to rewrite an email five times before sending it?',
  'Who most likely has an inspirational quote in their email signature?',
  'Who is most likely to end emails with "Kind regards" and zero kindness?',
  'Which of you has recalled an email and prayed it would work?',
  'Who has most likely forgotten an email in drafts and only found it weeks later?',
  'Who is most likely to actually read the company newsletter?',
  'Which of you replies to emails faster than to messages from family?',
  'Who has most likely mixed up CC and BCC?',
  'Who is most likely to reply to an email that is already three weeks old?',
  'Which of you writes "Hi" in the chat and waits for a reply before asking the actual question?',
  'Who has most likely posted a private message in the wrong chat?',
  'Who is most likely to react to every message with just a thumbs-up?',
  'Which of you has the most creative status in the team chat?',
  'Who has most likely tagged the entire company with @everyone?',
  'Who is most likely to answer serious questions with GIFs?',
  'Which of you is typing the longest before a message finally shows up?',
  'Who is most likely to mark messages as unread and never look at them again?',
  'Which of you writes exclusively in lowercase in the chat?',
  'Who has most likely reacted to a sad message with the wrong emoji?',
  'Who is most likely to create a channel just for cat pictures?',
  'Which of you replies in the chat faster than their own shadow?',
  'Who is most likely to turn off all notifications and still catch everything?',
  'Who has most likely started a poll in the team chat just to decide on lunch?',
  'Who is most likely to ignore threads and post everything in the main channel?',
  'Which of you works best under pressure?',
  'Who is most likely to finish a task three weeks before the deadline?',
  'Who has most likely asked for a deadline extension that was not even needed?',
  'Who is most likely to say "This will take five minutes" and then need two days?',
  'Which of you has the longest to-do list?',
  'Who is most likely to add a finished task to their list just to check it off?',
  'Who has most likely completed a task that had been canceled long ago?',
  'Who is most likely to start tidying their desk when stressed?',
  'Who is most likely to put a deadline in their calendar and then ignore it?',
  'Who has most likely submitted something at 11:59 p.m.?',
  'Which of you stays the calmest when everyone else is panicking?',
  'Who is most likely to make a color-coded project plan?',
  'Who has most likely elegantly delegated a task to someone else?',
  'Which of you has turned procrastination into an art form?',
  'Who is most likely to get everything done on the last day before vacation?',
  'Who has most likely volunteered for a task just to get out of a meeting?',
  'Who is most likely to ruthlessly beat the boss at foosball?',
  'Who is most likely to declare Fridays a day off if they were the boss?',
  'Which of you would cut the most meetings if they were the boss?',
  'Who has most likely talked more than their manager in their annual review?',
  'Who is most likely to bring homemade charts to a salary negotiation?',
  'Who has most likely accidentally called their boss Mom or Dad?',
  'Who is most likely to have a slide installed in the office if they were the boss?',
  'Which of you would give up after one day if they swapped roles with the boss?',
  'Who most likely has the best answer when asked about their weaknesses?',
  'Who is most likely to make Hawaiian shirts the dress code if they were the boss?',
  'Which of you eats the same lunch every day?',
  'Who is most likely to start asking about lunch at 11 a.m.?',
  'Who most likely has the best meal prep in the whole office?',
  'Who is most likely to spend their lunch break at their desk?',
  'Which of you knows every restaurant near the office?',
  'Who is most likely to spend half an hour debating where to get lunch?',
  "Who has most likely accidentally taken someone else's lunch?",
  'Who is most likely to go for a run during their lunch break?',
  'Who is most likely to organize a group order and then chase everyone for the money?',
  'Which of you brings the most unusual food to the office?',
  'Who is most likely to introduce lunchtime walks for the whole team?',
  'Who has most likely talked about work during lunch when everyone wanted a break?',
  'Who is most likely to keep a ranking of the best cafeteria dishes?',
  'Which of you always has snacks in their desk drawer?',
  'Who is most likely to order food just because someone else is eating?',
  'Who is most likely to secretly pay the bill for everyone at lunch?',
  'Which of you has the fanciest outfit at the holiday party?',
  'Who is most likely to give a spontaneous speech at the company party?',
  "Who has most likely forgotten someone's name at the company party?",
  'Who is most likely to question the rules of every game at a team event?',
  'Which of you would cross the finish line first at a company fun run?',
  'Who is most likely to take over the grill at the summer party?',
  'Who most likely has the most photos from the last holiday party?',
  'Who would be the most scared on a team outing to a ropes course?',
  'Which of you would win a team pub quiz all on their own?',
  'Who has most likely had the wrong date in their calendar for a team event?',
  'Who is most likely to take charge at a team event without being asked?',
  'Who has most likely celebrated a strike at team bowling like an Olympic gold?',
  'Who is most likely to beg the DJ for a specific song at the holiday party?',
  'Which of you would cause the most chaos at a team cooking class?',
  'Who is most likely to turn the team outing into a 20 km hike?',
  'Who most likely has the best story from a past company party?',
  'Who is most likely to be at the office on time and fresh the day after the company party?',
  'Which of you has the most interesting resume?',
  'Who is most likely to write a farewell email that makes everyone cry?',
  'Who is most likely to still be working right here in ten years?',
  'Which of you would quit their job to become an influencer?',
  'Who most likely has had the most unusual side job?',
  'Who is most likely to keep dropping by the office every day after retiring?',
  'Which of you would be the first to take a sabbatical?',
  'Who is most likely to start a whole new career as a baker?',
  'Who most likely had the best job interview of all time?',
  'Who is most likely to post an inspirational LinkedIn story about a flat tire?',
  'Which of you has done the most training courses?',
  'Who is most likely to invent a job title that does not exist yet?',
  'Who has most likely started a job interview using the wrong company name?',
  'Who is most likely to write a book about their time here after leaving?',
  'Who is most likely to found a startup based on an idea from the office kitchen?',
  'Which of you has collected the most frequent-flyer miles?',
  'Who is most likely to miss the train on a business trip?',
  'Who has most likely submitted an expense report three months late?',
  'Who is most likely to make the most of the hotel breakfast on a business trip?',
  'Which of you packs a full suitcase for a one-night business trip?',
  'Who is most likely to see every sight in town on a business trip?',
  'Who has most likely lost a receipt and searched for it in despair?',
  'Who is most likely to take a call on the train even though the signal keeps dropping?',
  'Which of you has checked into the wrong hotel?',
  'Who is most likely to stretch a business trip into a mini vacation?',
  'Who has most likely forgotten their charger on a business trip?',
  'Who is most likely to collect the most freebies at a trade show?',
  'Which of you has seen the inside of every train station in the country?',
  'Who has most likely left their key card in the hotel room and locked themselves out?',
  'Which of you would explore the whole city after a client meeting?',
  'Who is most likely to finish a presentation on the plane at the last minute?',
  'Who has most likely had to replan an entire business trip because of a train strike?',
  'Who is most likely to bring back a fridge magnet from every business trip?',
  'Which of you has fixed a paper jam with brute force?',
  'Who is most likely to print 50 pages and then realize it was the wrong file?',
  'Who has most likely printed to the wrong printer?',
  'Who is most likely to file an IT ticket that just says "Help"?',
  'Who has most likely called IT support only for a restart to fix everything?',
  'Who is most likely to forget the password they just changed?',
  'Which of you helps everyone with tech problems without even working in IT?',
  'Who is most likely to click "Later" on updates for months?',
  'Who has most likely spilled coffee on their keyboard?',
  'Who is most likely to bribe IT support with cookies?',
  'Who has most likely fallen for a phishing test email from IT?',
  'Who is most likely to know the keyboard shortcut for every function?',
  'Who is most likely to save a file as final_final_really_final?',
  'Who has most likely deleted an important file and found it again in the trash?',
  'Which of you got lost in the building on their first day?',
  'Who is most likely to give new coworkers a tour full of insider tips?',
  'Who has most likely still not learned all the names from their onboarding?',
  'Which of you was the most nervous on the first day at work?',
  'Who most likely showed up way overdressed on their first day?',
  'Which of you takes the fewest vacation days and has to use up the rest in a rush at year-end?',
  'Who is most likely to plan long weekends more strategically than any project?',
  'Who has most likely sent a postcard to the office from vacation?',
  'Who is most likely to come back from vacation with souvenirs for the whole team?',
  'Who is most likely to write a vacation handover longer than a novel?',
  'Who is most likely to need a week to get back into the swing of things after vacation?',
  'Which of you comes back from every vacation with the worst sunburn?',
  'Who most likely has the best vacation story on the team?',
  'Who is most likely to mark 400 emails as read on their first day back from vacation?',
  'Which of you knows the most Excel formulas by heart?',
  'Who has most likely destroyed an Excel file with a single click?',
  'Who is most likely to color every cell a different color?',
  'Which of you uses the most animations in presentations?',
  'Who is most likely to prepare 60 slides for a ten-minute presentation?',
  'Who is most likely to use Comic Sans in a client presentation?',
  'Who is most likely to show a chart nobody understands, not even themselves?',
  'Who is most likely to liven up slides with memes?',
  'Which of you says "As you can clearly see here" the most in presentations?',
  'Who is most likely to make the laser pointer dance nervously across the whole screen?',
  'Who has most likely failed to get the projector working?',
  'Which of you has explained VLOOKUP and lost track halfway through?',
  'Who is most likely to give a presentation with no slides at all?',
  'Who has most likely shown a slide with just one huge word on it?',
  'Who is most likely to run twice as long as planned in a presentation?',
  'Which of you always wears headphones in the open office so nobody bothers them?',
  'Who is most likely to talk out loud to their computer in the open office?',
  'Who is most likely to be first in the office in the morning and turn on the lights?',
  'Who is most likely to reserve a hot desk with a towel?',
  'Who has most likely taken their shoes off at the office?',
  'Which of you hums while working without noticing?',
  'Who is most likely to fully decorate the office for the holidays?',
  'Who most likely has the best office chair racing skills?',
  'Who is most likely to have a standing desk and never raise it?',
  'Which of you types the loudest on the keyboard?',
  'Who is most likely to stick Post-its on every free inch?',
  'Who is most likely to adopt an office dog if it were allowed?',
  'Which of you has pulled on a glass door that says push?',
  'Who is most likely to introduce a workout routine for office breaks?',
  'Who most likely has the biggest collection of pens on their desk?',
  'Which of you has the most creative nickname on the team?',
  'Who is most likely to invent their own abbreviations and expect everyone to know them?',
  'Who is most likely to use words like synergy and added value in every sentence?',
  'Who has most likely nodded along without having any idea what the abbreviation meant?',
  'Who has most likely been unable to find their own car in the company parking lot?',
  'Who is most likely to suggest a team name that sounds like a superhero squad?',
  'Which of you would be the last one out during a fire drill because an email still has to go out?',
  'Who is most likely to organize a team photo where everyone wears the same shirt?',
  'Who is most likely to create a playlist for the whole team?',
  'Which of you has the best nose for when cake shows up somewhere?',
  'Who is most likely to give feedback in the form of a poem?',
  'Who has most likely taken a conference call from the supermarket?',
  'Who is most likely to serve the whole office mulled wine on the last workday before Christmas?',
];
