export const crazyQuestionsEn: string[] = [
  'Who would be the first to die in a zombie apocalypse?',
  'Who is most likely to adopt a raccoon and set up an apartment just for it?',
  'Who would be the first to lose it on a desert island reality show?',
  'Who secretly talks to pigeons and believes they answer back?',
  'Who would pick a fight with a goose and lose?',
  'Which of you would marry a stuffed animal if it were legal?',
  'Who is most likely to try crossing the Alps in a shopping cart?',
  'Who would time-travel to the Middle Ages and get burned as a witch right away?',
  'Who could live in a furniture store for a week without anyone noticing?',
  'Who could lead an army of squirrels?',
  'Which of you would volunteer to go into the dark basement in a horror movie?',
  'Who is most likely to start a relationship with a voice assistant?',
  'Who would be the first to take a selfie with aliens when they land?',
  'Who would enter an eating contest against a bear?',
  'Which of you would accidentally become mayor of a small village?',
  'Who is most likely to start a religion centered around toast?',
  'Who would be living with monkeys after just one day in the jungle?',
  'Which of you would have a pet potato named Gerald?',
  'Who is most likely to get left behind on a cruise ship and only be found weeks later?',
  'Who would just fall asleep in an escape room?',
  'Who could dress up as a statue and not move for an entire day?',
  'Which of you would start a fight with a vending machine and lose?',
  'Who is most likely to accidentally start a war between two countries?',
  'Who would throw a wedding in the frozen food aisle of a supermarket?',
  'Which of you would get lost in a cave and start a new life down there?',
  'Who could win a talent show doing fart noises?',
  'Who is most likely to train a parrot just to insult people?',
  'Who would be best friends with the dinosaurs after a night at the museum?',
  'Who would find a unicorn and immediately sell it on eBay?',
  'Who is most likely to eat nothing but pasta with ketchup for a whole year?',
  'Who would take off in a hot-air balloon and land in a different country?',
  'Who would climb a volcano just to roast marshmallows in it?',
  'Who would be a superhero with the most useless superpower in the world?',
  'Which of you would try to save a whale and end up needing to be rescued?',
  'Who is most likely to hike across South America with a llama?',
  'Who would be the first to get homesick for kebab on Mars?',
  'Who would be taken hostage in a bank robbery and become friends with the robbers?',
  'Who could get lost in a corn maze forever?',
  'Who is most likely to run through a live TV broadcast in a chicken costume?',
  'Who would get bored and start building a castle out of toilet paper?',
  'Who would try to start a fire with their phone in the wilderness?',
  'Who would befriend a robot vacuum and tell it their secrets?',
  'Which of you would tame a dragon and only use it for barbecues?',
  'Who is most likely to accidentally become king or queen of a foreign country?',
  'Who would walk only backwards for a month because of a bet?',
  'Who would be a pirate who sinks the ship before it even sets sail?',
  'Who is most likely to sue a seagull for theft?',
  'Who would get hypnotized and cluck like a chicken for the rest of their life?',
  'Who would find Bigfoot and want to give it a haircut?',
  'Who would smash a watermelon with their head and be proud of it?',
  'Which of you would end up as the annoying sidekick in a fantasy world?',
  'Who is most likely to smuggle a penguin out of the zoo?',
  'Who would move in with the ghost in a haunted mansion as roommates?',
  'Who would dress up as a piece of furniture at a costume party and win?',
  'Who would get elected leader by a flock of sheep?',
  'Which of you would make a volleyball their best friend on a desert island?',
  'Who is most likely to make a documentary about the secret life of socks?',
  'Who could get into an argument with a cactus and get hurt?',
  'Who would move into a medieval fair permanently and never leave?',
  'Who is most likely to name their vegetables and then refuse to eat them?',
  'Which of you would lose a race against a snail?',
  'Who would get struck by lightning and think they have superpowers?',
  'Who would be the first to run off and join the circus as a clown?',
  'Who is most likely to register a bouncy castle as their permanent address?',
  'Who could accidentally switch off the space station?',
  'Which of you would keep a crocodile as a guard dog?',
  'Who would find nothing but old bottle caps on a treasure hunt and still cheer?',
  'Who would let a conversation with their own reflection escalate?',
  'Who is most likely to suddenly start talking like a dolphin at a party?',
  'Who would instantly get into trouble with the cats in a world of talking animals?',
  'Which of you would chase a tornado just to get a good video?',
  'Who would take over a hardware store in the zombie apocalypse and declare it a kingdom?',
  'Who would still show up to work on time every morning as a zombie?',
  'Who would still file their taxes on time in the middle of the zombie apocalypse?',
  'Who would get abducted by aliens and returned after an hour for being too exhausting?',
  'Who could teach an alien to swear in German in five minutes?',
  'Who would make a deal with aliens and trade Earth for a bag of chips?',
  'Who would take a time machine to the Stone Age and blow up as an influencer there?',
  'Who would use a time machine just to sleep in longer on weekends?',
  'Which of you would try to explain a smartphone to Napoleon and fail miserably?',
  'Who would be the first one eaten on a trip back to the age of the dinosaurs?',
  'Who would turn the saloon in the Wild West into a karaoke bar?',
  "Who would use invisibility just to steal snacks from other people's fridges?",
  'Who would be able to fly and still be late every single time?',
  'Who could suddenly read minds and bitterly regret it after ten minutes?',
  "Who would be able to teleport and keep accidentally landing in strangers' bathrooms?",
  'Who would accept an entire beehive as roommates and share honey with them?',
  'Who would carpool to work with a moose?',
  'Which of you would offer a cat a permanent employment contract?',
  'Who would invite an alpaca as the guest of honor at their wedding?',
  'Who would get completely hustled by an octopus at cards?',
  'Who would start a band with a dolphin and two seals?',
  'Who could teach a hamster how to drive?',
  'Who would be worshipped as a god by an ant colony?',
  'Which of you would demand that dogs get to vote in the next election?',
  'Who would hire a sloth as their personal trainer?',
  'Who would lead a goat revolution at a petting zoo?',
  'Who would ask a goldfish for advice before every big decision?',
  'Who could sing with whales and land a record deal for it?',
  'Who would charge the spider in the corner of the room rent?',
  'Which of you would sneak a horse into a movie theater?',
  'Who would provoke a swan and then flee across the entire park?',
  'Who would lose a showing-off contest against a peacock?',
  'Who would have a stellar career as a court jester in the Middle Ages?',
  'Who would be a knight who runs away from the dragon and calls it strategy?',
  'Which of you would try to invent pizza in the Middle Ages?',
  'Who would get stuck in a suit of armor and have to call the fire department?',
  'Who could fall off their own horse at a jousting tournament before it even starts?',
  'Who would fake magic powers at the royal court and only know three card tricks?',
  'Who would accidentally flush their toothbrush into space on the space station?',
  'Who would be the first to open a snack bar on the moon?',
  'Who could lock themselves out of the spaceship during a spacewalk?',
  'Who would launch in a rocket and ask "are we there yet?" after two minutes?',
  'Which of you would play cheesy pop songs nonstop on a long space flight and drive everyone insane?',
  'Who would run off with the host at the end of a dating show?',
  'Which of you would volunteer for every gross challenge in a jungle reality show?',
  'Who could answer every question on a quiz show but get stuck on their own name?',
  'Who would secretly cover every camera lens with socks in the Big Brother house?',
  'Who would secretly order the dish from a delivery app on a cooking show?',
  'Who would start a cult whose only rule is a daily afternoon nap?',
  'Which of you would join a cult just because there is free cake every day?',
  'Who could convince a group of total strangers to worship a fridge?',
  'Who would spend eternity haunting a fast-food restaurant as a ghost?',
  'Who would ask a poltergeist to help carry boxes when they move?',
  'Who would buy a haunted castle and rent out rooms with a guaranteed ghost sighting?',
  'Who would run away from their own shadow on a midnight ghost hunt?',
  'Who could give lessons to a ghost who forgot how to be scary?',
  'Who is definitely a world-famous rock legend in a parallel universe?',
  'Who would meet their parallel-universe self and immediately start arguing?',
  'Which of you is probably a talking dog in a parallel universe?',
  'Who would fall through a portal into a parallel universe and never tell anyone?',
  'Who would build a career as a can opener in a world ruled by cats?',
  'Who would kiss the frog in a fairy tale and be disappointed when it just stays a frog?',
  "Who would eat the witch's entire gingerbread house before she even gets home?",
  "Which of you would waste a fairy's three wishes on fries, fries and more fries?",
  'Who would just invite the big bad wolf in the woods over for coffee?',
  'Who would lose a shoe at a fairy-tale ball on purpose just to be searched for?',
  'Who could defeat a giant with nothing but a bad pun?',
  "Who would only ask the magic mirror what's for dinner tonight?",
  'Who would negotiate hard with a fairy godmother over the fine print of their wishes?',
  'Who would open a kiosk in the enchanted forest for lost princes and princesses?',
  'Who would lose to a robot at chess and demand a rematch at arm wrestling?',
  'Who would switch sides to the machines the moment the robot uprising starts?',
  'Who would apologize to the toaster after burning the toast?',
  'Who would build a robot clone to go to work while they stay in bed?',
  'Who could annoy an AI so much that it quits on its own?',
  'Who would win the lottery and invest all the money in gummy bears?',
  'Which of you would accidentally put the winning lottery ticket through the wash?',
  'Who would win the lottery, buy a castle and then only live in the kitchen?',
  'Who would found their own country on a desert island and compose a national anthem?',
  'Who would start a labor union with the crabs on a desert island?',
  'Who would send messages in bottles from a desert island complaining about the service?',
  'Who would get rescued from a desert island and immediately want to go back?',
  'Who would set the world record for the longest hiccup attack of all time?',
  'Which of you could hold the world record for forgetting names?',
  "Who would try to eat the world's longest bratwurst all by themselves?",
  'Who would try to break the world record for talking backwards and forget their own language?',
  'Who would attempt a world record in nonstop clapping and give up after ten seconds?',
  'Who would record conversations with their houseplant and release them as a podcast?',
  'Who would go grocery shopping dressed as a penguin for an entire day?',
  'Who would adopt a snowman and keep it in the freezer over the summer?',
  'Who would hijack the roller coaster at an amusement park?',
  'Who would get sucked into a painting at a museum and have to pose there forever?',
  'Who would take a garden gnome on a trip around the world and send photos from every stop?',
  'Who would secretly move into a bakery because it always smells so good?',
  'Who would buy the moon and rent out parking spaces on it?',
  'Who would control the weather and make it rain confetti every day?',
  'Who would sue Santa Claus over a missing present?',
  'Who would have the Easter Bunny arrested on the job?',
  'Who would open a ski rental shop in the Himalayas with a yeti?',
  'Who would vanish in the Bermuda Triangle and show up years later as captain of a ghost ship?',
  'Which of you would be a mermaid or merman and still be scared of fish?',
  'Who would invent the Loch Ness Monster just to get famous?',
  "Who would win a leprechaun's entire pot of gold at poker?",
  'Who would get blown into a magical land by a tornado and immediately open a shop there?',
  'Who would plan a wedding on the ocean floor with sharks as guests?',
  'Who would start a mutiny on a cruise ship because the buffet ran out?',
  'Who would rent the Eiffel Tower for a night just to barbecue on top?',
  'Who would bet their entire life savings on a snail race?',
  'Who would get bitten by a vampire and from then on drink nothing but tomato juice?',
  'Which of you would turn into a werewolf at the full moon and only bark at the neighbors?',
  'Who would invite a vampire to a barbecue with garlic bread?',
  'Who would dress up as a mummy and then not be able to get out of the bandages?',
  'Who would search a pyramid for treasure and only find the toilet?',
  "Who would set off a pharaoh's curse because they wanted a selfie with the mummy?",
  'Which of you would be a pirate who promotes the parrot to captain?',
  'Who would board a pirate ship and mainly loot the snack supplies?',
  'Who would be a ninja and still trip loudly with every step?',
  'Who would be a secret agent whose cover gets blown in the first minute?',
  'Who would pull off an art heist at a museum and steal the wrong painting?',
  'Who would plan the perfect heist and then fall asleep at the meeting point?',
  'Which of you would give a bank robber directions to the getaway car?',
  "Who would be a wizard's apprentice who accidentally turns the whole school into frogs?",
  'Who would get three wishes from a genie and then keep the genie as a roommate?',
  'Who could own a flying carpet and still take the train?',
  'Who would be a troll in a fantasy world collecting tolls under a bridge?',
  'Who would lose an archery contest to an elf and blame it on the wind?',
  'Who would just drop the magic ring in a mailbox on a fantasy quest?',
  'Who would swap bodies with a cat and totally love it?',
  'Who would swap bodies with the boss and immediately give everyone vacation?',
  'Who would shrink to the size of an ant and get lost in their own home?',
  'Who would suddenly grow thirty feet tall and want to buy new shoes first?',
  'Which of you would create a clone and fall out with it within an hour?',
  'Who would walk around in neon clothes in a world without color?',
  'Who would be the first one arrested in a country where laughing is illegal?',
  'Who would be the first to get into trouble with the lawn in a world where plants can talk?',
  'Who would still bring an umbrella to a city under the sea?',
  'Which of you would win Olympic gold in a made-up sport?',
  'Who would race a kangaroo and decide to start hopping too?',
  'Who would take on a panda in a sumo wrestling match?',
  'Who could get shot out of a cannon and land in the wrong city?',
  'Which of you would win a chili pepper eating contest and then breathe fire?',
  'Who would start a food fight in a Michelin-star restaurant?',
  'Who would bake a cake so big you could live in it?',
  'Who would invent something nobody needs and make millions with it?',
  'Who would invent a machine that pairs socks automatically and then lose it?',
  'Who could modify a lawn mower so that it can fly?',
  'Who would bury a time capsule and dig it back up the very next day?',
  'Who would mistake a microwave for a portal to another dimension?',
  'Which of you would open a nightclub in an igloo at the North Pole?',
  'Who would start a snowball fight with polar bears?',
  'Who would ride a camel through the Sahara and ask for directions after five minutes?',
  'Who would run a hotel in a treehouse in the middle of the rainforest?',
  'Who could cross the Atlantic on a raft while singing nothing but cheesy pop songs?',
  'Who would climb Mount Everest just to order a pizza at the top?',
  'Who would try to make it all the way to America in a pedal boat?',
  'Which of you would live in a lighthouse and accidentally switch off the light?',
  'Who would spend a night in a hall of mirrors and never find their way out?',
  'Who would work on a ghost train ride and scream on every single trip?',
  'Who would be the only one in a horror movie to realize it is a horror movie?',
  'Who could successfully sell therapy to a slasher movie monster?',
  'Who would star in a soap opera and reveal an evil twin in every episode?',
  'Who would miss every explosion in an action movie because they had to pee?',
  'Which of you would live in a musical and comment on every situation with a song?',
  'Who would be an extra in a Hollywood movie and accidentally steal the lead role?',
  'Who would suggest a picnic instead of shooting in a Wild West duel?',
  'Who would get married three times and lose their memory twice in a telenovela?',
  'Who would accidentally end up on a postage stamp and become famous for it?',
  'Who could commission a statue of themselves and put it in the living room?',
  'Who would walk into a library with a megaphone?',
  'Who would take over a funfair and make all the rides free?',
  'Which of you would want to turn bouncy castle jumping into an Olympic sport?',
  'Who would upgrade a gondola in Venice with an outboard motor?',
  'Who would want to organize an office chair race on the highway?',
  'Who would race down a mountain on a toddler ride-on car and set a record?',
  'Who would make pajamas mandatory if they ruled the world?',
  'Which of you would declare their own country on a traffic island?',
  'Who would go to war with an army of rubber ducks?',
  'Who would negotiate a ceasefire between dogs and cats?',
  'Which of you would howl with a wolf pack and actually be taken seriously?',
  'Who would offer a hedgehog a hug?',
  'Who would free a lobster from a restaurant and take it back to the sea?',
  'Who would keep a chicken as a pet and buy it a leash?',
  'Who would wake up a groundhog and then pay for it all winter long?',
  'Who would hire a goose as a bodyguard?',
  "Who would fill in for the monkey at the zoo while it's on vacation?",
  'Who would join a secret society just for the fancy cloak?',
  'Who would invent a conspiracy theory that pigeons are spy drones?',
  'Which of you would believe the moon is made of cheese and plan an expedition?',
  'Who would stomp a crop circle into a field and claim it was aliens?',
  'Who would ask an oracle for the lottery numbers and get a recipe instead?',
  'Who would hear from a fortune teller that their future is full of potatoes and believe it?',
  'Who could use a crystal ball as a bowling ball?',
  "Who would cook soup for the whole neighborhood in a witch's cauldron?",
  'Which of you would find a magic lamp and only use it as a bedside lamp?',
  'Who would get a dragon to heat their apartment?',
  'Who would teach a barbecue class with a phoenix?',
  'Who would use a griffin as a delivery service?',
  'Who would want to give riding lessons to a centaur?',
  "Who could give a sphinx a riddle it can't solve?",
  'Who would hold eye contact with Medusa and not turn to stone because they are just that cool?',
  'Who would challenge a kraken to a tug-of-war in the ocean?',
  'Which of you would discover Atlantis and immediately open a beach cafe there?',
  'Who would jump into the local lake in a diving suit and feel like a deep-sea explorer?',
  'Who would throw a music festival on an oil rig?',
  'Who would fly to the bakery with a jetpack?',
  'Who could fall into a fountain on a hoverboard?',
  'Who would argue with the GPS in a self-driving car and lose the argument?',
  'Who would have a talking fridge that rats them out for snacking?',
  'Which of you would train a robot vacuum to be a race car driver?',
  'Who would get sucked into a video game and only do the side quests?',
  'Who would get stuck in a video game as a character who can only say one line?',
  'Who would stay in virtual reality so long that the real world feels strange?',
  'Who would invent a video game where all you do is fold laundry?',
  'Who could be trapped inside a board game and still cheat?',
  'Who would take Monopoly so seriously that it turns into a real estate war?',
  'Which of you would build a house of cards big enough to sleep in?',
  'Who would take a stuffed animal around the world in their backpack and explain everything to it?',
  'Who would stand in a field as a scarecrow for a whole week because of a bet?',
  'Who would dress up as a cake and jump out of the cake at a wedding?',
  'Who could accidentally start a conga line at a funeral?',
  'Who would fall into a barrel at a wine festival and only be found the next day?',
  'Who would wear a beer stein as a hat at Oktoberfest?',
  'Which of you would go to a costume party as a fridge and hand out drinks all night?',
  "Who would mistake a firecracker for a rocket and try to fly to space on New Year's Eve?",
  'Who would plant the Christmas tree in the garden and wonder why it keeps growing?',
  'Who would see Santa stuck in the chimney and call the fire department?',
  "Who would steal the Sandman's sand so they never have to sleep again?",
  'Who could bribe the Tooth Fairy to get more money for a tooth?',
  'Who would ask Saint Nicholas for an employment contract?',
];
