export const deepQuestionsEn: string[] = [
  'Which of you would show up right away if someone called at 3 a.m.?',
  'Who here would you trust with your biggest secret?',
  'Who is the most loyal person at this table?',
  'Who shows their feelings the least, even though a lot is going on inside?',
  'Who is much braver than they seem at first glance?',
  'Who has changed the most in the last few years?',
  "Who listens best when you're having a hard time?",
  'Which of you gives the most honest advice, even when it hurts to hear?',
  'Who makes you feel instantly comfortable and accepted?',
  'Who thinks about life the most?',
  'Who would be most likely to swallow their pride to save a friendship?',
  'Who has the biggest heart in this group?',
  'Who is best at forgiving?',
  "Which of you is the first to notice when someone isn't doing well?",
  'Who would be most likely to chase a dream even if everyone was against it?',
  'Who is the person who always keeps their word?',
  'Who is best at hiding insecurity behind a smile?',
  'Who has grown the most as a person?',
  'Who would you most want by your side if you had to start over completely?',
  'Who keeps their opinion to themselves most often?',
  'Who is the calm rock in the storm when everything gets chaotic?',
  'Who would still keep a secret after twenty years?',
  'Which of you is harder on themselves than on others?',
  'Who is best at getting others to believe in themselves?',
  'Who has the best intuition about people?',
  'Who would be most likely to stand up for someone who is being treated unfairly?',
  'Which of you has the most unspoken dreams?',
  'Who would you call first after a bad day?',
  'Who has surprised you with a completely new side of themselves?',
  'Who would be most willing to risk everything for something they believe in?',
  'Who is best at admitting they made a mistake?',
  'Who is much softer at heart than their tough exterior suggests?',
  'Who takes care of others the most and forgets about themselves?',
  'Whose opinion do you value the most?',
  'Who would be most likely to quit a safe job to start something of their own?',
  'Which of you has the most beautiful way of showing gratitude?',
  'Who is the reason this group sticks together so well?',
  'Which of you has the greatest inner strength?',
  'Who is the most honest with themselves?',
  'Who has taken the bravest step recently?',
  'Who would be most likely to travel the world alone for a year?',
  'Who always finds the right words in difficult moments?',
  'Which of you is the most underrated?',
  'Who would you ask for advice first when facing a big life decision?',
  'Who is most likely to make the first move after a fight?',
  'Who has the most patience with other people?',
  'Which of you has a talent that gets way too little recognition?',
  'Who would be most likely to spontaneously help a stranger in need?',
  'Who is the most themselves, no matter who is watching?',
  'Which of you would travel the farthest for the people here?',
  'Who writes the most honest and beautiful birthday messages?',
  'Who is most at peace with themselves?',
  "Who would be most likely to admit they're scared right now?",
  'Who is the person who never leaves anyone behind?',
  'Who lies awake the longest replaying conversations at night?',
  'Who would be most likely to save a friendship that was almost lost?',
  "Who has taught you something you'll never forget?",
  "Which of you is best at staying quiet when words won't help?",
  'Who shows affection through actions rather than words?',
  'Who can you count on the most in a crisis?',
  'Who would be most likely to write a letter to their younger self?',
  'Who has the strongest values and actually lives by them?',
  'Which of you has quietly overcome the most challenges?',
  'Who would be most willing to change their mind after hearing a good argument?',
  'Who could you talk to for hours about absolutely anything?',
  'Who gives the most without expecting anything in return?',
  'Who would be most likely to admit they miss someone?',
  'Which of you is the proudest of their roots?',
  "Who has had the biggest positive impact on someone's life here?",
  'Who has grown closest to your heart over the years?',
  "Who would be most likely to take the blame for a friend's mistake?",
  'Who stays the most optimistic even in hard times?',
  'Who in this group would you most like to grow old with?',
  'Who would you trust with your kids for a weekend without a second thought?',
  "Who would be most likely to back you up in an argument, even if you're wrong?",
  "Which of you never talks badly about people who aren't around?",
  'Who is best at keeping friendships alive over long distances?',
  'Who would be most likely to lie for you to protect you?',
  'Which of you took the longest to truly trust others?',
  'Who would help you move without you even having to ask?',
  "Who reliably reaches out when you haven't heard from each other in a while?",
  'Who would be the fairest mediator in a fight between two people in this group?',
  'Who defends the group the loudest when an outsider talks trash?',
  'Who would be most likely to go to a concert alone and totally enjoy it?',
  'Who is most likely to dare to be the only voice in the group that disagrees?',
  'Who would be most likely to move to a foreign country without knowing anyone there?',
  'Who is the bravest about bringing up uncomfortable topics?',
  "Who has the courage to ask for help when it's needed?",
  "Who would be most likely to end a long relationship because it just doesn't feel right anymore?",
  'Who made a decision everyone thought was crazy and turned out to be right?',
  'Which of you is most likely to try things no one in their family has ever done?',
  'Who would be most likely to give back money they were overpaid by mistake?',
  'Who is most likely to shop sustainably on purpose, even if it costs more?',
  "Who would turn down a well-paid job because it doesn't match their values?",
  'Who treats service staff with the most respect?',
  "Who would be most likely to volunteer if time weren't an issue?",
  'Which of you has the clearest idea of what really matters in life?',
  'Who is most likely to donate without telling anyone?',
  'Which of you would stay honest even if a lie would never be found out?',
  'Who cares least about what others think, as long as their conscience is clear?',
  'Who pays the most attention to how their decisions affect other people?',
  'Which of you is most likely to cry during a movie?',
  'Who is the most open about how much the friendships here mean to them?',
  'Who loves giving the most and the longest hugs?',
  'Who is best at putting into words what others can only feel?',
  'Which of you has the most contagious joy?',
  'Who takes the longest to calm down after a fight?',
  'Who is most likely to swallow their anger instead of speaking up?',
  'Who has the most honest face, where you can read every mood?',
  'Which of you would be most likely to write a long letter instead of a short text?',
  'Who is the most open about it when something has hurt them?',
  'Who is most likely to be moved by small gestures?',
  "Who is the most genuinely happy about other people's success?",
  "Who cooks for others when words aren't enough?",
  "Who would be most likely to admit they're jealous?",
  'Who would impress their self from ten years ago the most?',
  'Who has dropped a habit that everyone can be proud of?',
  'Which of you handles big changes the best?',
  'Who holds on to old habits the longest?',
  'Which of you is most likely to reinvent themselves every few years?',
  'Who would be most likely to pick up a brand-new hobby and really blossom?',
  'Which of you has become calmer than anyone ever expected?',
  'Who has tried the most new things lately?',
  'Which of you has the hardest time letting things go?',
  'Who works the hardest for their goals, even when nobody sees it?',
  'Who is the last to give up?',
  'Who measures success the least by money?',
  'Who has the strongest inner drive?',
  'Who celebrates their own successes the least, even though they have every reason to?',
  "Which of you doubts themselves the most, even though there's no reason to?",
  'Who is the worst at accepting compliments?',
  'Who compares themselves to others most often?',
  'Who would be most likely to admit they sometimes feel out of place?',
  'Who goes back and forth the longest before making important decisions?',
  'Who is the most afraid of disappointing others?',
  'Who follows through the most, despite being afraid of failing?',
  'Who would you ask for advice first when dealing with heartbreak?',
  'Who gives the best advice but never follows it themselves?',
  'Who has a wise saying ready for every situation in life?',
  'Who listens first and then gives advice, instead of jumping straight to solutions?',
  'Which of you has given advice that changed your life?',
  'Who would be the best role model for a younger family member?',
  'Who is most likely to make big decisions based on gut feeling?',
  'Who regrets the fewest of their own decisions?',
  'Who would be most likely to put their career on hold for their family?',
  'Who would be most likely to take a gap year to figure out what really matters?',
  'Who is most likely to just let life happen?',
  'Who would be most likely to adopt a child?',
  'Who has taken a turn in life that changed everything?',
  'Which of you calls their family most regularly?',
  "Who is the most like their own family, even if they don't like to admit it?",
  'Which of you has the closest bond with their siblings?',
  'Who would pass on the most beautiful family traditions?',
  'Which of you would make the most patient parent?',
  'Who loves telling stories from their childhood the most?',
  'Who is the black sheep of their family with the biggest heart?',
  'Who got the most valuable life lesson from their grandparents?',
  'Who treats friends the most like family?',
  "Who has the best relationship with everyone else's parents?",
  'Who has the longest friendship in this group?',
  'Who is most likely to bring new people into the group?',
  'Who remembers the most little things you once told them?',
  'Which of you has sacrificed the most for this group?',
  'Who most reliably plans the next time everyone gets together?',
  'Who knows you so well that words are sometimes unnecessary?',
  'Who is the person you never have to wear a mask around?',
  'Which of you would never put a friendship at risk over money?',
  'Who did you completely misjudge when you first met them?',
  'Who is the best company on a long drive through the night?',
  'Who asks the best follow-up questions when you tell them something?',
  'Who checks in days later to ask how an important conversation went?',
  'Who listens with real interest even to boring stories?',
  'Who also hears what is said between the lines?',
  'Which of you shares the least about themselves because they always ask about others?',
  'Who is the worst liar?',
  'Which of you is honest without being hurtful?',
  'Who would be most likely to confess an uncomfortable truth before it comes out?',
  "Who is most likely to admit they don't know something?",
  'Who is too honest for their own good?',
  'Who is uncompromisingly honest in love too?',
  'Who tells stories exactly as they happened, without exaggerating?',
  'Which of you is most attached to old keepsakes?',
  'Who would be most likely to make a photo album of the time you all spent together?',
  'Who would be most likely to want to go back to their school days?',
  'Which of you remembers your first night together the most clearly?',
  'Who gets goosebumps the fastest from old songs?',
  'Who misses their childhood the most?',
  'Who scrolls through old chat histories most often?',
  'Which of you is most likely to actually make a lifelong dream come true?',
  'Who imagined the wildest things about being a grown-up as a kid?',
  'Who has actually made a childhood dream come true?',
  'Which of you has a bucket list and is really checking things off?',
  'Who would be most likely to take a long trip just for one special moment?',
  'Who has the wildest dream for life after retirement?',
  'Which of you would be most likely to learn an instrument just for the love of music?',
  'Who would do the most good with a lottery win?',
  'Which of you is best at living in the moment?',
  'Who is the most grateful for the little things in life?',
  'Who should treat themselves to a real break more often?',
  'Who is best at saying no without feeling bad?',
  'Who looks back on their past the most fondly?',
  'Who is most likely to find themselves in nature?',
  'Who is best at enjoying things without feeling guilty?',
  'Who is most likely to keep a journal to sort out their thoughts?',
  'Who is most likely to laugh at themselves?',
  'Which of you takes life the most lightly without being shallow?',
  'Who has found the best work-life balance?',
  'Who most often does something nice for others just because?',
  'Who is most likely to drop off soup when someone is sick in bed?',
  'Which of you gives the most thoughtful gifts?',
  'Who would be most likely to stay up all night to help someone here?',
  'Who shows respect even to people who think completely differently?',
  'Which of you is the most open to new perspectives?',
  "Who would be most likely to live someone else's life for a week just to understand them?",
  'Who would be most likely to plant a tree whose shade only future generations will enjoy?',
  'Who never forgets a kindness someone showed them?',
  'Who holds the biggest grudges, even if hardly anyone notices?',
  'Which of you worries the most about the others?',
  'Who is the oldest soul in this group?',
  "Which of you is the most curious about other people's lives?",
  'Who asks the deepest questions at parties?',
  'Who has the most interesting view of the world?',
  'Who would be most likely to spend a year in a monastery?',
  'Which of you believes in fate the most?',
  'Who would be most likely to leave an important decision up to chance?',
  'Who is most convinced that every person can change?',
  'Who has the clearest stance without needing to convince others of it?',
  'Who would be most likely to join a protest for a cause close to their heart?',
  'Which of you is best at being alone?',
  'Who feels least comfortable in big groups but always comes along anyway?',
  'Who comes alive the most in big groups?',
  'Who is best at giving an honest compliment?',
  'Which of you has helped someone here out of a real jam?',
  'Who would be the happiest if everyone here moved onto the same street?',
  "Who would be most likely to give the speech at someone's wedding here?",
  'Who would you trust to represent you in an important situation?',
  'Who is the person who inspires you the most?',
  'Which of you lives the life others secretly wish they had?',
  'Who would be the best choice as godparent to a child?',
  'Who took on responsibility for others very early in life?',
  'Who naturally takes charge in an emergency?',
  "Which of you is best at putting themselves in other people's shoes?",
  'Who fights the most passionately for an idea?',
  'Which of you has the strongest opinions and the gentlest way of sharing them?',
  'Who has given up something big so someone else could be better off?',
  'Who would be most likely to share their last dollar with you?',
  'Which of you has really gone to bat for someone here?',
  'Who is the person who will round everyone up again in twenty years?',
  'Who deserves a biography that everyone should read?',
  'Who would be most likely to want to relive a certain year exactly as it was?',
  'Who is the most at peace with getting older?',
  'Who would be most likely to want to be ten years younger to experience everything more consciously?',
  'Which of you has the most wonderful way with kids?',
  'Who has the most compassion for animals?',
  'Who would be most likely to rescue an animal from a shelter?',
  'Who is best at talking with older people?',
  'Which of you stays the fairest in discussions?',
  'Who can accept a loss with the most dignity?',
  'Who would be most likely to give up a win so someone else could win?',
  'Who is most willing to question their own prejudices?',
  'Who has learned the most from their own mistakes?',
  'Who is most likely to read books that change the way they think?',
  'Who is most deeply changed by a good conversation?',
  'Who takes criticism to heart the most?',
  'Who is best at taking criticism and making something good out of it?',
  'Who is most likely to be happy with very little?',
  'Who would be most likely to give away their favorite thing because it means more to someone else?',
  'Who would be most likely to turn down a dream job in a faraway city for the people here?',
  'Who would rather choose adventure over security when in doubt?',
  'Who finds it easiest to make connections in a new place?',
  'Who would be most likely to still be making new friends at seventy?',
  'For whom is home more of a person than a place?',
  'Who would be most likely to get a coach just to keep growing as a person?',
  'Who reflects most honestly on their own behavior after a fight?',
  'Which of you apologizes the most sincerely?',
  'Who shows the most gratitude to their parents?',
  'Who would be most likely to gift their parents a dream vacation?',
  'Who talks about their family the most lovingly?',
  'Which of you is most likely to also be friends with their parents?',
  'Who would be most likely to invite people over for Christmas who would otherwise be alone?',
  'Who is best at making strangers feel welcome?',
  'Who would be most likely to talk to the loneliest person at the table at a wedding?',
  'Who has gained the most self-confidence since they were a teenager?',
  'Who is most likely to talk through their worries on a long walk?',
  'Who could you best watch a sunset with in silence?',
  'Which of you has the best eye for beauty in everyday life?',
  'Who would be most likely to spend a night under the open sky just to see the stars?',
  'Who would be most likely to philosophize about the universe until sunrise?',
  'Who feels the most connected to the place where they grew up?',
  'Who is most likely to stay friends after a breakup?',
  'Who loves the most unconditionally?',
  'Who would give up the most for the love of their life?',
  'Which of you believes most firmly in true love?',
  'Who is most likely to make a declaration of love in front of an audience someday?',
  'Who is the most reliable partner in a relationship?',
  'Who has saved your day with just a single message?',
  'Who would be most likely to organize an evening just to say thank you to everyone here?',
  'Who is most likely to take on the tasks in the group that nobody else handles?',
  'Which of you has best kept their childlike enthusiasm?',
  'Who will you all still be telling the best stories about in twenty years?',
];
