export const exposedQuestionsEn: string[] = [
  "Who has most likely scrolled through their crush's Instagram all the way back to 2015?",
  'Which of you has ever accidentally liked an old photo of their crush?',
  'Who would most likely text an ex at three in the morning?',
  'Who is most likely to fib about their age, height or salary?',
  'Who has ever faked being sick to get out of plans?',
  'Which of you had the most embarrassing emo or hipster phase?',
  'Who most likely still has old love letters or chat histories saved?',
  'Who would most likely send a message about someone to that exact person?',
  'Who has ever used a fake account to spy on someone?',
  'Which of you has ever said something really embarrassing in their sleep?',
  'Who most likely got caught cheating on a test at school?',
  'Who has ever waved back at someone who was actually waving at someone else?',
  'Who most likely has the cringiest bio on a dating app?',
  'Which of you has ever sent a voice message that should never have gone out?',
  "Who is most likely still friends with their ex, even though everyone knows there's more to it?",
  "Who has most likely ghosted someone and still hasn't explained why?",
  'Which of you has ever rehearsed an argument or a date in front of the mirror?',
  "Who has ever deleted a post because it didn't get enough likes?",
  'Who most likely wrote poems about their crush as a teenager?',
  'Who most likely got caught talking trash by the very person they were talking about?',
  'Which of you has ever farted loudly in class or a meeting and blamed someone else?',
  'Who has ever made up a whole excuse to cancel a date?',
  "Who has ever secretly gone through their partner's phone?",
  "Who would most likely admit to once having a crush on a friend's partner?",
  'Which of you still has embarrassing fanfiction or a diary hidden somewhere?',
  'Who has most likely seriously exaggerated in a job interview?',
  'Who has ever burst out laughing at the worst moment, like at a funeral?',
  'Who most likely has an old tweet or post that would be seriously embarrassing today?',
  'Who most likely did something really embarrassing on a first date?',
  'Which of you has ever regifted a present and gotten caught?',
  'Who has most likely done a livestream or TikTok that nobody was ever supposed to see?',
  'Who has ever claimed to have read a book or seen a movie just to join the conversation?',
  'Who most likely tripped in front of their crush at the supermarket or on the bus?',
  "Who would most likely write their first name with their crush's last name to see how it looks?",
  "Which of you has ever secretly eaten a roommate's food and denied it?",
  'Who has ever sent someone a message using the wrong name?',
  'Who most likely posted something dramatic after a breakup?',
  'Who would most likely give an embarrassing speech at a wedding?',
  'Which of you has ever accidentally called a teacher "Mom" or "Dad"?',
  'Who has most likely flaunted their new relationship in front of an ex on purpose?',
  'Who has ever pretended to be on the phone to avoid saying hi to someone?',
  'Which of you has the most embarrassing searches in their browser history?',
  'Who has most likely ended a relationship over text?',
  'Who has ever confessed their love to someone and gotten rejected?',
  "Who most likely still has an ex's clothes in their closet?",
  "Who would most likely secretly edit their photos with filters until they're unrecognizable?",
  'Which of you has ever had a crush on a teacher or a boss?',
  "Who most likely told their parents a wild lie that still hasn't come out?",
  'Who most likely walked around town with their fly open without noticing?',
  "Who would most likely admit to having sent themselves a Valentine's Day message?",
  'Who most likely sent an embarrassing message to the family group chat?',
  'Who has ever watched a crush from a distance and pretended it was a coincidence?',
  'Who would most likely totally forget the lyrics at karaoke and keep singing anyway?',
  'Which of you has ever secretly cried because a TV show ended?',
  'Who most likely secretly made everyone else look bad in a group photo?',
  "Who has ever ended a friendship over something tiny that's embarrassing now?",
  'Who most likely got caught by their parents doing something that was never spoken of again?',
  'Who would most likely pay for likes or followers?',
  'Who has ever mistaken someone for someone else and made small talk for way too long?',
  'Who has the most embarrassing story that nobody here knows yet?',
  "Which of you most likely forged a parent's signature on a school excuse note?",
  'Who most likely had an embarrassing nickname at school?',
  'Who has ever hidden a bad test grade from their parents?',
  'Who most likely made up an excuse to get out of gym class?',
  'Who has ever sent a love note with "Yes, No, Maybe" boxes to tick?',
  "Which of you most likely snuck into someone else's room at night on a school trip?",
  "Who most likely copied someone's homework, mistakes and all?",
  'Who most likely got caught passing notes and had the note read out loud?',
  'Who had the most embarrassing hairstyle at school that still lives on in photos?',
  'Which of you has ever completely blanked during a presentation in front of the class?',
  'Who most likely imitated a teacher and got caught right in the act?',
  'Who would most likely admit to being embarrassed by their parents at school?',
  "Which of you has their eyes closed in a school photo that still hangs at their parents' place?",
  'Who most likely got detention for something really stupid?',
  'Which of you has ever thrown up in front of everyone at school?',
  'Who most likely tore up all the couple photos after a breakup?',
  "Which of you has ever done a full background check on their ex's new partner?",
  'Who would most likely call an ex and hang up immediately?',
  'Who has ever said yes to a party just because their ex was supposed to be there?',
  'Who has most likely asked an ex to give back a gift?',
  'Which of you has ever gone back to an ex even though literally everyone said not to?',
  'Who has ever completely forgotten an anniversary in a relationship?',
  'Who would most likely write a song about their ex and actually play it for someone?',
  "Which of you has ever walked past their ex's place on purpose?",
  'Who most likely still has a password that has something to do with an ex?',
  'Who has ever had a drastic makeover after a breakup and regretted it?',
  'Who most likely hid behind a shelf because their ex was in the store?',
  "Which of you has ever had a relationship their friends weren't allowed to know about?",
  'Who most likely broke up with someone and begged to get back together soon after?',
  "Who would most likely miss their ex's pet more than the ex?",
  "Who has ever accidentally said their ex's name to a new partner?",
  'Who has ever dragged out a relationship just to avoid being alone at Christmas?',
  'Which of you has ever accidentally posted a story to everyone instead of close friends?',
  'Who has most likely taken fifty selfies just to post one?',
  'Who would most likely like their own posts from a second account?',
  "Who has ever written a long angry comment under a stranger's post?",
  'Which of you most likely staged a vacation online that was actually awful?',
  'Who has ever answered a video call with the camera on at the worst possible moment?',
  'Which of you has ever commented on a livestream and had it read out loud?',
  "Who most likely posted a cheesy inspirational quote about life that's embarrassing now?",
  'Who has ever faked the location on a photo to seem more interesting?',
  'Which of you has ever unfollowed someone and then secretly followed them again?',
  "Who most likely left a comment on a celebrity's post they're not proud of?",
  'Who would most likely put a sad song in their story so a certain person sees it?',
  'Who has ever tried a dance trend that went completely wrong?',
  'Which of you only noticed a typo in their post after a hundred likes?',
  'Who most likely still has an old blog or channel that must never be found?',
  'Who has ever accidentally posted a private message as a public comment?',
  'Which of you has ever changed their route just to "accidentally" run into their crush?',
  'Who has most likely spent an hour perfecting a message and then just sent "hey"?',
  'Who has ever started a hobby just because their crush does it?',
  "Who has ever left something at someone's place on purpose to have a reason to see them again?",
  'Who most likely walked into a lamppost while staring at their crush?',
  'Who would most likely send every message from their crush to the group chat for analysis?',
  'Who would most likely sign up for a class just because a certain person is in it?',
  "Who has most likely spent hours watching their crush's online status?",
  'Who has ever kept a crush secret because a friend liked the same person?',
  'Who is most likely to fall for someone at the gym without ever exchanging a word?',
  "Who has most likely bragged to their crush about a skill they don't actually have?",
  'Who would most likely admit to having a crush right now on someone nobody here knows about?',
  'Who has most likely googled how to get over someone?',
  'Who would most likely google their own name on a regular basis?',
  'Who has ever searched "how to seem cool" or something equally desperate?',
  'Which of you has the most embarrassing photo gallery that nobody is allowed to scroll through?',
  "Who most likely has the most screenshots of other people's chats saved?",
  'Who has ever frantically cleared their browser history because someone wanted to borrow their laptop?',
  'Who most likely has the weirdest contact names saved in their phone?',
  'Who has ever listened back to their own voice message and wanted to sink into the ground?',
  "Who most likely played embarrassing music out loud on a train because their headphones weren't connected?",
  'Who would most likely blame autocorrect even though they meant exactly what they wrote?',
  'Who has ever had a seriously embarrassing song as their number one in their year-end music recap?',
  'Which of you has ever shown something embarrassing while sharing their screen in a meeting?',
  'Who has most likely googled how to kiss properly?',
  'Who has ever taken an online quiz like "Which princess am I?" way too seriously?',
  'Which of you has ever been called a pet name by their parents in front of friends?',
  'Who most likely has parents who leave embarrassing comments under their photos?',
  "Who has ever told their parents they were sleeping at a friend's place and been somewhere else entirely?",
  "Which of you has ever secretly taken their parents' car?",
  'Who most likely broke something at home and blamed a sibling?',
  'Who once got a "birds and the bees" talk from their parents that still haunts them?',
  'Who would most likely admit to still bringing their laundry to their parents?',
  "Who most likely still has a childhood bedroom at their parents' place that looks like they're fourteen?",
  'Who has ever accidentally sent a message complaining about their parents to their parents?',
  'Which of you has ever skipped a family event with a made-up excuse?',
  "Who has ever claimed college was going great when it absolutely wasn't?",
  'Whose parents tell the same embarrassing story at every family party?',
  'Who most likely asked their grandparents for money for something supposedly sensible?',
  'Who most likely claimed to be stuck in traffic when they had just gotten out of bed?',
  'Which of you has ever faked a dead battery to end a conversation?',
  'Who would most likely claim they never got a message even though they read it?',
  'Who has ever made up a sick relative to postpone an exam?',
  'Which of you claimed to speak a language and then got spoken to in it right away?',
  'Who has ever claimed they already ate just to get out of going along?',
  'Who most likely took a lie so far that they had to keep it up for years?',
  'Who would most likely fake an emergency to escape a bad date?',
  'Which of you has ever pretended to be asleep to get out of a conversation?',
  'Who most likely faked their birth date to get in somewhere?',
  'Who has ever claimed to have met a celebrity when they never did?',
  'Who most likely secretly googled answers at a quiz or game night?',
  'Who would most likely claim they cooked a meal themselves when it was actually takeout?',
  'Who is most likely still carrying around a lie they told someone in this group?',
  "Who most likely used a pet that doesn't exist as an excuse?",
  'Which of you has ever pulled on a door that said "Push" in front of lots of people?',
  'Who most likely answered "Enjoy your meal" with "You too" when the other person was not even eating?',
  'Who would most likely trip on an escalator while everyone is watching?',
  "Which of you has ever tried to get into a stranger's car?",
  'Who has most likely turned a missed high five into a hair fix?',
  'Who has ever sung along loudly and only later realized everyone could hear?',
  'Who most likely came back from the bathroom with toilet paper stuck to their shoe?',
  'Which of you has ever commented loudly in a movie theater so the whole room heard?',
  'Who most likely used a machine at the gym the wrong way around?',
  'Who has ever gone in for a hug when the other person only wanted a handshake?',
  'Which of you has ever sat in the wrong meeting or lecture and noticed way too late?',
  'Who would most likely leave their mic on after a presentation and say something embarrassing?',
  'Who has ever realized at the checkout that they had no money, with a long line behind them?',
  'Who most likely used a word wrong for years with total confidence?',
  'Which of you has ever accidentally called a waiter "babe"?',
  'Who most likely ripped a pair of pants in the fitting room and had to buy them?',
  'Who has ever snorted so loudly while laughing that everyone jumped?',
  'Who would most likely admit to secretly binge-watching reality TV nonstop?',
  'Who has ever spent the whole day in bed and then talked about how productive they were?',
  'Which of you has ever eaten a whole pack of cookies alone and hidden the wrapper?',
  'Who most likely secretly plans their day around their horoscope?',
  'Who has ever hidden an unnecessary package from their roommates?',
  'Who most likely still secretly sleeps with a stuffed animal?',
  'Who would most likely wear a piece of clothing once and then return it?',
  "Which of you has ever secretly read someone else's diary?",
  'Who most likely has an embarrassing hobby that nobody here knows about?',
  'Which of you most likely secretly uses baby talk with plants or pets?',
  'Who has most likely spent more money on mobile games than they would admit?',
  "Who would most likely sneak food off other people's plates when they step away?",
  'Who has played ding-dong ditch as an adult?',
  'Who most likely got caught talking loudly to themselves?',
  'Which of you has ever walked off with a hotel bathrobe?',
  'Who has ever binged a whole season in one night and called in sick the next day?',
  'Which of you has ever had an important work call from home in pajama pants?',
  'Who most likely trash-talked their boss in the wrong chat?',
  'Who has ever written an entire term paper the night before it was due?',
  'Which of you has written illegibly on purpose in an exam to save points?',
  'Who has ever said the wrong company name in a job interview?',
  'Who most likely had to apologize to everyone on Monday after the office party?',
  'Which of you has written "please find attached" more than once and forgotten the attachment?',
  'Which of you has ever accidentally ended a work email with a heart?',
  'Who has most likely taken a nap in the bathroom at work?',
  'Who would most likely accidentally end a work call with "Love you"?',
  'Who once messed up so badly during an internship that people still talk about it?',
  'Who did nothing in a group project and still got full marks?',
  'Which of you has ever deliberately let the other person pay the bill on a date?',
  'Who has most likely had a date with someone who looked completely different from their photos?',
  'Who has ever talked way too long about their ex on a date?',
  'Which of you has ever found a coworker or relative on a dating app?',
  'Who most likely has had two dates on the same night?',
  'Who has ever left a date by going to the bathroom and never coming back?',
  'Who most likely bumped teeth during their first kiss?',
  'Who would most likely have friends secretly sit at the next table during a date?',
  'Which of you has ever eaten so much on a date that it got embarrassing?',
  'Who most likely had friends write their dating profile?',
  'Who has ever lied about their job on a date?',
  'Which of you has ever turned someone down and regretted it afterward?',
  'Who has most likely dated someone just to make someone else jealous?',
  'Who has ever sat down with the wrong person thinking they were their date?',
  'Who most likely had a blind date that turned into a legendary horror story?',
  'Which of you has ever knocked over a full glass on a date out of nerves?',
  'Who most likely has been texting a match for months without ever meeting up?',
  'Who has ever dated someone that a person here dated before?',
  'Which of you has ever started a group chat that leaves out certain people in this group?',
  'Who most likely passed on a secret from someone here?',
  'Who would most likely cancel and then show up in a story from a different party?',
  'Who has ever secretly hoped plans with friends would fall through?',
  'Which of you has muted a group chat without the others knowing?',
  'Who has most likely been jealous of the life of someone here and kept quiet about it?',
  'Who most likely got jealous of a new friendship someone here made?',
  'Which of you never paid back borrowed money and hoped it would be forgotten?',
  'Who most likely still has a borrowed piece of clothing and pretends nobody knows?',
  "Who has ever given someone here a compliment they didn't mean at all?",
  'Which of you has ever secretly laughed at an outfit someone here was wearing?',
  'Who most likely organized a hangout just to see one specific person?',
  'Who has ever brought a last-minute gift from a gas station?',
  "Who most likely completely forgot a close friend's birthday?",
  'Who most likely cheated at game night and never admitted it?',
  'Who has ever flirted with the sibling of someone here?',
  'Who most likely swallowed something as a kid that was definitely not edible?',
  'Who would most likely admit to believing in Santa until their teens?',
  'Who wrote fan mail to a band or TV star as a kid?',
  'Which of you most likely cut their own hair as a kid with disastrous results?',
  'Who most likely had an imaginary friend until an embarrassing age?',
  'Who wanted to marry someone back in kindergarten and announced it officially?',
  'Who most likely stars in an old home video their parents love to show at parties?',
  'Who can most likely still do the full choreography of a 2000s boy band or girl group?',
  'Which of you had the most embarrassing poster above their bed as a teenager?',
  'Who most likely started a band that played exactly one show?',
  'Who has ever stolen something small from a store as a kid, like a piece of gum?',
  'Which of you had the most embarrassing first email address?',
  'Who most likely forwarded a chain letter out of fear of the curse?',
  'Who tried to look older as a teenager, and it went totally wrong?',
  'Who most likely still keeps their first phone with all the old texts?',
  'Who most likely entered a talent show that went completely wrong?',
  "Who has ever written a letter to their future self that's super embarrassing now?",
  'Who most likely had an important conversation with spinach stuck in their teeth?',
  'Who has ever had a seriously embarrassing accident while sneezing?',
  'Which of you has ever opened the door for a delivery driver wearing a face mask or zit cream?',
  'Who most likely wore a T-shirt inside out all day?',
  'Who has ever had their pants rip in public?',
  "Who most likely woke up on a stranger's shoulder on a train?",
  'Who most likely got photographed drooling in their sleep?',
  'Which of you has ever looked orange for weeks after using self-tanner?',
  'Who most likely told the hairdresser they loved it and then cried at home?',
  'Who has ever confidently mispronounced a brand name for years?',
  'Which of you has ever lost part of their swimsuit at the pool?',
  'Who most likely lost a contact lens and had the whole restaurant searching for it?',
  'Who most likely announced a diet and ordered pizza that same night?',
  'Who has ever signed up for a gym membership and gone exactly once?',
  'Which of you has ever pretended to be a wine expert?',
  'Who has ever bought a book just so it looks smart on the shelf?',
  'Which of you has ever pretended to know about sports or cars and got exposed?',
  'Who most likely came back from vacation with an accent that lasted a week?',
  'Who would most likely post a fancy meal that someone else paid for?',
  'Which of you has ever faked deep relaxation in yoga while thinking about fries?',
  'Who most likely owns workout clothes that only get worn for photos?',
  "Who has ever passed off someone else's pet or car as their own?",
  'Which of you has hyped up a race and then secretly skipped it?',
  'Who most likely let a gifted plant die and secretly bought a new one?',
  'Who would most likely claim to be a pro after a single cooking class?',
  'Who has ever practiced an acceptance speech for a major award in front of the mirror?',
  'Who most likely posts vacation photos bit by bit for months so it looks like more?',
  'Who has most likely accepted a compliment on their hair even though it was extensions?',
  'Who has ever bought an instrument to show off and never learned to play it?',
  'Who would most likely break something in a store and secretly put it back on the shelf?',
  'Who has ever been caught without a ticket on public transport and told a wild story?',
  'Who most likely kept quiet about damaging something they borrowed?',
  'Who has ever written a long letter to someone and never sent it?',
  "Who most likely snooped in the host's bathroom cabinet?",
  'Who would most likely admit to not liking half the people here at first?',
  'Which of you has ever eavesdropped on the neighbors through the wall and taken notes?',
  'Who has ever bet so much that it really hurt?',
  "Which of you has ever taken a shortcut through a stranger's yard and gotten caught?",
  'Who would most likely secretly write a five-star review of their own project?',
  'Who has ever failed their driving test for a really embarrassing reason?',
  'Who has ever secretly looked up someone in this group online?',
  'Which of you has ever hit "delete for everyone" on a message, but it was already too late?',
];
