export const friendlyQuestionsEn: string[] = [
  'Who gives the best hugs?',
  'Who always helps out without needing to be asked twice?',
  'Who instantly lifts the mood as soon as they walk into a room?',
  'Who would be the best roommate?',
  'Who is the best listener?',
  'Who has the most contagious laugh?',
  'Who would show up in the middle of the night if you needed help?',
  'Who makes everyone feel instantly at ease?',
  'Who gives the best compliments?',
  'Who has the biggest heart?',
  'Who always remembers birthdays?',
  'Who is most likely to bake a cake just to make someone happy?',
  'Who has the best taste in music in this group?',
  'Who would you call first after a breakup?',
  'Who radiates the most calm?',
  'Who gives the best advice?',
  'Who is most likely to handmake a thoughtful gift?',
  'Who has the most beautiful smile?',
  'Who is best at cheering others up?',
  'Who always has a snack on them and happily shares it?',
  'Who is the most loyal when it really counts?',
  'Who would help you move without complaining once?',
  'Who has the best sense of humor?',
  'Who makes every party better?',
  "Who cooks so well that you'd accept any dinner invite instantly?",
  'Who would make the best travel buddy?',
  'Who is the most honest but still always kind?',
  'Who has the most beautiful voice?',
  'Who makes everyone feel like they belong?',
  'Who sends the sweetest messages?',
  'Who is most likely to spontaneously help a stranger?',
  'Who is the most patient with others?',
  'Who would be the best pet sitter?',
  'Who has the best sense of style?',
  'Who is most likely to throw a surprise party for someone?',
  'Who can make others laugh the fastest?',
  'Who would make the best godparent?',
  'Who can you always count on?',
  'Who is most likely to stay up all night talking with you?',
  'Who has the most beautiful eyes?',
  "Who is most likely to bring you soup when you're sick?",
  'Who never talks badly about others?',
  'Who is the bravest?',
  'Who is most likely to make a playlist just for you?',
  'Who is the most generous?',
  'Who has grown the most in a positive way over the past few years?',
  'Who is most likely to peacefully settle an argument in the group?',
  'Who always thinks of everyone?',
  'Who is the most beautiful dancer?',
  'Who has the best morning energy?',
  'Who is most likely to send a handwritten card?',
  'Who is your favorite person for a movie night?',
  'Who has stayed the most down-to-earth?',
  'Who tells the best stories?',
  'Who is most likely to root for you during an exam and call right after?',
  'Who is the most understanding?',
  'Who is most likely to give up the last slice of pizza?',
  "Who could you introduce to anyone's parents without worrying?",
  'Who would make the best teacher?',
  "Who can always tell when someone isn't feeling okay?",
  'Who is most likely to turn a rainy day into an adventure?',
  'Who pays the most attention to little details?',
  'Who would give the best wedding speech?',
  'Who would this group not be the same without?',
  "Who is most likely to water your plants while you're away?",
  'Who would give up their own jacket without hesitation if someone is cold?',
  'Who immediately offers to help when someone is carrying heavy bags?',
  'Who is most likely to help with annoying paperwork?',
  "Who is the last to leave when it's time to clean up after a party?",
  'Who makes sure everyone gets home safe at night?',
  'Who explains complicated things so you actually understand them?',
  'Who is most likely to quiz you for hours before an exam?',
  'Who loves fixing things for other people the most?',
  'Who is most likely to fix a flat bike tire without being asked?',
  'Who always has a bandage, a tissue, or a charger on them?',
  'Who is the first to text after hanging out to check everyone got home okay?',
  'Who is most likely to go grocery shopping for someone who has no time?',
  "Who is most likely to do the dishes even when it's someone else's turn?",
  'Who has the driest but most lovable sense of humor?',
  'Who is best at laughing at themselves?',
  'Who sends the funniest voice messages?',
  'Who can find something to laugh about in every awkward situation?',
  'Who came up with the best inside jokes?',
  'Who does the funniest impressions?',
  'Who sends the funniest memes to the group chat?',
  'Who comes up with the most creative nicknames for things and people?',
  'Who has perfect timing for funny comments?',
  'Who would put on the most entertaining comedy show?',
  'Who has a talent that way more people should know about?',
  'Who has the nicest handwriting?',
  'Who is the most skilled with their hands?',
  'Who has the best memory for details from old conversations?',
  'Who takes the most beautiful photos?',
  'Who has what it takes to open their own restaurant?',
  'Who is so talented at sports that you can only stand in awe?',
  'Who learns new languages the fastest?',
  'Who would win big on a quiz show?',
  'Who is the best at drawing?',
  'Who has the greenest thumb?',
  'Who is secretly an organizational genius?',
  'Who is the best with kids?',
  'Who could assemble any piece of furniture without instructions?',
  'Who writes so beautifully that you would read a book by them?',
  'Who still looks stylish even in sweatpants?',
  'Who has the most beautiful hair here?',
  'Who has the most beautifully decorated home?',
  'Who wears colors nobody else could pull off and looks amazing in them?',
  'Who has a truly unique style of their own?',
  'Who always looks good in photos?',
  'Who has a scent you fondly remember long afterward?',
  'Who could pass as a model any day?',
  'Who has the nicest shoes?',
  'Who decorates tables and rooms so well that everyone is amazed?',
  'Who feels instantly familiar again even after months without talking?',
  'Who holds the group together?',
  "Who reaches out just to ask how you're doing?",
  'Who is most likely to travel across the country just to meet up?',
  'Who could you trust with any secret?',
  "Who is the most genuinely happy about other people's success?",
  "Who defends their friends even when they aren't around?",
  'Who remembers things you only mentioned once in passing?',
  'Who is most likely to make a photo album of shared memories?',
  'Who is the best person to grow old with?',
  'Who did the most to bring all of you together?',
  'Who always manages to organize a meetup when everyone is too busy?',
  'Who would show up to every performance or game just to cheer?',
  'Who is great to spend time with even in silence?',
  'Who makes you feel truly seen?',
  'Who would most likely stand by you if you started over in a new city?',
  'Who forgives the fastest?',
  'Who always makes time, even when their calendar is full?',
  'Who is most likely to start a new tradition for your friendship?',
  'At whose place do you feel most welcome as a guest?',
  'Who always has a spare bed or couch for anyone?',
  'Who sets the most beautiful table?',
  'Who would most likely cook for ten people on short notice?',
  'Whose home would you most like to spend Christmas at?',
  'Who makes the best brunch?',
  'Who immediately offers guests something to drink?',
  'Who is most likely to host a cozy game night at home?',
  'Who makes sure nobody is standing alone in a corner at a get-together?',
  'Who bakes the birthday cake everyone wishes for?',
  'Who is most likely to throw a backyard barbecue and invite everyone?',
  "Who always keeps every guest's allergies and preferences in mind when cooking?",
  'Who makes the best coffee or tea?',
  'Who is always on time?',
  'Who keeps their promises, no matter how small?',
  'Who always returns borrowed things, even in better condition?',
  'Who replies to messages most reliably?',
  'Who would be at the airport on time to pick you up?',
  'Who keeps a clear head in stressful situations?',
  'Who would you list as your emergency contact?',
  'Who makes sure money gets split fairly in the group?',
  'Who plans trips so that everything just works out?',
  'Whose word really means something?',
  'Who has the most original gift ideas?',
  'Who could whip up a feast from fridge leftovers?',
  'Who has the best costume ideas?',
  'Who is most likely to invent their own board game?',
  'Who writes the most beautiful poems or birthday cards?',
  'Who thinks the most outside the box?',
  'Who is most likely to turn an old piece of furniture into something beautiful?',
  'Who finds a creative solution for every problem?',
  'Who has the most imaginative dreams that you just have to hear about?',
  'Who would make the best movie?',
  'Who makes up the best bedtime stories?',
  'Who is most likely to write a song about your friendship?',
  'Who designs the most beautiful invitations?',
  'Who has the warmest greeting?',
  'Who still comes across as friendly even on bad days?',
  'Who radiates the most confidence without being arrogant?',
  'Who has the warmest eyes?',
  'Who do strangers instantly like?',
  'Who has a presence that makes others braver?',
  'Who has the most captivating way of telling a story?',
  'Who can even make the cashier at the supermarket smile?',
  'Who radiates the most joy for life?',
  'Who would be universally loved as a celebrity?',
  'Who do animals instantly fall in love with?',
  "Who notices right away when someone hasn't eaten or drunk enough?",
  'Who is most likely to make tea when someone is sad?',
  'Who always walks you to your front door after a party?',
  'Who reminds others to take care of themselves too?',
  'Who checks in after a tough appointment to ask how it went?',
  'Who always has painkillers and kind words on hand?',
  'Who would most likely stay the whole time during a hospital visit?',
  'Who instantly notices small changes like a new haircut?',
  'Who would immediately keep someone company if they felt lonely?',
  'Who welcomes newcomers to the group most warmly?',
  'Who is the most optimistic?',
  'Who stays calm and friendly even in total chaos?',
  'Who never gives up when things get tough?',
  'Who is the most humble despite having every reason to show off?',
  'Who is the most curious about other people?',
  'Who apologizes most sincerely when something goes wrong?',
  'Who is the most open to new experiences?',
  'Who is the most grateful for the little things?',
  'Who has the strongest sense of justice?',
  'Who is the first to look for the fault in themselves?',
  'Who is the most respectful toward everyone?',
  'Who always stays true to themselves?',
  'Who deserves the most gratitude?',
  'Who is most likely to stand up for the underdog?',
  'Who is the most open to other cultures?',
  'Who is most likely to volunteer?',
  'Who has surely collected the most karma points?',
  'Who can address conflicts without ever being hurtful?',
  'Who would you most like to be stranded on a desert island with?',
  'Who would be the best road trip companion?',
  'Who would be the perfect teammate in an escape room?',
  'Who would be the best person for a picnic in the park?',
  'Who would you most like to take a cooking class with?',
  'Who would be the best person for a long evening walk?',
  'Who would you most like to take a train trip across Europe with?',
  'Who would be the best company for a spa day?',
  'Who would be the best person to go to a festival with?',
  'Who would you most likely win a scavenger hunt with?',
  'Who would be the best person to go stargazing with?',
  'Who would you most like to spend a lazy Sunday in pajamas with?',
  'Who would be the best company for a hike in the mountains?',
  'Who would you most like to browse a flea market with?',
  "Who would be the best plus-one at a wedding where you don't know anyone?",
  'Who would you most like to do a 1,000-piece puzzle with?',
  'Who would be the best person to try a new hobby with?',
  'Who has earned the biggest compliment of the night?',
  'Who would be the good fairy in a fairy tale?',
  'Who is someone kids should look up to?',
  'Who finally deserves a truly relaxing vacation?',
  'Who has achieved the most this year?',
  'Who would be the main character in a heartwarming movie?',
  'Who would make their city the friendliest place as mayor?',
  'Who deserves their own statue for kindness?',
  "Who would be the character in a children's book who saves everyone in the end?",
  'Who deserves an award for the most patience with this group?',
  'Who would be an extra cuddly golden retriever if they were a dog?',
  'Who would be a hot chocolate on a cold day if they were a drink?',
  'Who would be a sunny spring day if they were the weather?',
  'Who would be an upbeat hit if they were a song?',
  'Who would be a cozy mountain cabin if they were a place?',
  "Who would be the world's favorite comfort food if they were a dish?",
  'Who would be a sunflower if they were a flower?',
  'Who always says thank you, even for little things?',
  'Who lets others go ahead of them in line at the supermarket?',
  'Who greets the neighbors most warmly?',
  'Who is most likely to help an elderly person cross the street?',
  'Who tips the most generously at restaurants?',
  'Who always holds the door for others?',
  "Who picks up trash even when it isn't theirs?",
  'Who is most likely to help a lost dog find its way home?',
  'Who would return a found wallet right away?',
  'Who compliments strangers most often?',
  "Who is most likely to leave cookies on the neighbors' doorsteps?",
  'Who most often sends photos that bring back great shared memories?',
  'Who is the most patient in traffic?',
  'Who is most likely to bring flowers just because?',
  'Who would cheer you on from the sidelines of a marathon?',
  'Who believes in dreams, even when they sound crazy?',
  'Who gives you the final push to try something new?',
  'Who is most likely to recommend your project to everyone they know?',
  "Who celebrates other people's small wins like big ones?",
  'Who reminds you of your strengths when you doubt yourself?',
  "Who would do a challenge with you so you're not alone?",
  "Who gives feedback that's honest but still feels good?",
  'Who takes your fears seriously and still makes them feel smaller?',
  'Who brings new people into the group who fit in perfectly?',
  'Who takes the best group photos where everyone looks good?',
  'Who makes sure every voice counts when making decisions?',
  'Who is most likely to design matching shirts for the group?',
  'Who started the most beautiful group tradition?',
  'Who would plan a group trip that makes everyone happy?',
  'Who would be the most attentive partner in a relationship?',
  'Who is most likely to handwrite a love letter?',
  'Who would plan the perfect first date?',
  "Who would be every kid's favorite person at a family gathering?",
  'Who is most likely to adopt a pet from a shelter?',
  'Who is most likely to build a blanket fort with kids?',
  'Who is most likely to nurse an injured little bird back to health?',
  'Who makes the best breakfast in the world?',
  'Who has a family recipe everyone needs to try?',
  'Who is most likely to pack lunches for everyone?',
  'Who shares their dessert without hesitation?',
  'Who mixes the best cocktails or mocktails?',
  'Who always has the best life wisdom up their sleeve?',
  'Who would protect everyone in a zombie movie?',
  'Who would be the best person to share an umbrella with?',
  'Who is most likely to sing you happy birthday, even off-key?',
  'Who has the best book and TV show recommendations?',
  'Who could most likely make a grumpy person laugh?',
  'Who always sees the good in everyone first?',
  'Who would host the coziest morning radio show?',
  'Who would give the best tour of their hometown?',
  'Who can comfort you without needing many words?',
  'Whose home feels like a vacation?',
  'Who has the coolest hobby?',
  'Who is most likely to give you a book that suits you perfectly?',
  'Who talks most passionately about their favorite topics?',
  'Who would never use your mistakes against you?',
  'Who can be made happiest by the smallest things?',
  'Who is most likely to put together a collection of compliments for bad days?',
  'Who most recently made you truly light up?',
];
