export const futureQuestionsEn: string[] = [
  'Who will be the first to get married?',
  'Who will end up on TV someday?',
  'Who will be the first to move abroad for good?',
  'Who will live in a camper van at 50 and love every minute of it?',
  'Who is most likely to live to 100?',
  'Who will one day blow all their savings at a casino?',
  'Who will win the lottery someday and tell absolutely no one?',
  "Who will still be living in their childhood bedroom at their parents' place at 40?",
  'Who will one day write a book about their own life?',
  'Who will be the first to have grandkids?',
  'Who will be the first to buy a house?',
  'Who will move to the countryside later and keep chickens?',
  'Who is most likely to get married on a whim in Las Vegas?',
  'Whose pet will one day have more followers than everyone here combined?',
  'Who will move to the other side of the world for love?',
  'Who will still be working at 75 because retirement is too boring?',
  'Who will be the first to regret a tattoo?',
  'Who will be the first to go to space?',
  'Who will make it into the Guinness World Records one day?',
  'Who will already have three dogs at 30?',
  'Who will own their own vineyard one day?',
  'Who is most likely to move into a hippie commune?',
  'Who will still be sitting in the same bar every Friday in 20 years?',
  'Who will be the most embarrassing parent at every school meeting?',
  'Who will buy a bright red convertible during their midlife crisis?',
  'Who will still be living with roommates at 45?',
  'Who will end up in prison one day and start a podcast about it afterwards?',
  'Who will make a living as a professional poker player?',
  'Who will be running a beach bar in Thailand at 60?',
  'Who will celebrate their 50th birthday partying in a club until 8 a.m.?',
  'Who will win a million on a game show someday?',
  'Who will oversleep and miss their own wedding?',
  'Who is most likely to join a weird cult?',
  'Who will go vegan and never talk about anything else again?',
  'Who will one day live in a cabin in the woods without a phone?',
  'Who will be chased by paparazzi someday?',
  'Who will be the first to get their own Wikipedia page?',
  'Who will end up with a house full of cats?',
  'Who will move to Mallorca and open a bar there?',
  'Who will be the first to have twins?',
  'Who will get so rich that everyone here has to beg them for money?',
  'Who will still be getting speeding tickets at 80?',
  'Who will end up marrying someone from their old school class?',
  'Who will one day become a regular at the emergency room?',
  'Who will invent something completely pointless and get filthy rich from it?',
  'Who will still be wearing the exact same clothes in 20 years?',
  'Who will move into a tiny house and regret it after a week?',
  'Who will end up teaching at their old school?',
  'Who will go viral overnight and become world-famous?',
  'Who will spend their entire retirement on a cruise ship?',
  'Who will learn to skateboard at 60?',
  'Whose place will the whole family go to for Christmas every year?',
  'Who will bet their own car someday and lose it?',
  'Who will end up working from home in pajamas only?',
  'Who will one day be on stage as a cheesy pop star?',
  'Who will start their own religion someday?',
  'Who will stay single forever and be super happy about it?',
  'Who will name their kid after a soccer star?',
  'Who will go back to college at 50?',
  'Who will one day look for true love on a TV dating show?',
  "Who will be the first to lose their driver's license?",
  'Who will surprise everyone the most at the 20-year reunion?',
  'Who will get married more than three times in their life?',
  'Who will propose in front of an entire soccer stadium someday?',
  'Who will one day have a wedding with over 500 guests?',
  'Who will get married in secret and only tell everyone a year later?',
  'Who will meet the love of their life in the checkout line at the supermarket?',
  'Who will get a no when they propose?',
  'Who here will celebrate their golden wedding anniversary someday?',
  "Who is most likely to marry someone the whole group can't stand?",
  'Who will get married dressed as a character from a fantasy movie?',
  'Who will end up engaged for 15 years without ever getting married?',
  'Who will get asked to be best man or maid of honor the most?',
  'Who will get married underwater wearing a diving mask?',
  'Who will give an hour-long speech at their own wedding?',
  'Who will set up the most couples in the friend group?',
  'Who will get back together with their first love someday?',
  'Who will renew their wedding vows every five years with a huge party?',
  'Who will be the strictest parent of all?',
  'Who will be the most chilled-out parent in the world?',
  'Who will have their first kid after 45?',
  'Who will have so many kids they could field their own soccer team?',
  'Who will give their kids the craziest names?',
  "Who will become head of the parents' association and organize every school event?",
  'Who will be the coolest grandparent that the grandkids love to party with?',
  'Who will secretly stuff their grandkids full of candy?',
  'Who will drive a giant eight-seater minivan as a parent?',
  'Who will get exposed on the internet by their own kids someday?',
  'Who will force their kids to learn the recorder?',
  "Who will be the loudest parent yelling on the sidelines at kids' soccer games?",
  'Who will throw the most over-the-top birthday parties for their kids?',
  'Who will be the aunt or uncle who lets the kids do anything?',
  'Who will end up with no kids of their own but twelve godchildren?',
  'Who will tell their future kids the most embarrassing stories from back in the day?',
  'Who will call their kids for help with every phone problem?',
  'Who will one day run a giant corporation?',
  'Who will quit their job on a whim with a voice message someday?',
  'Who will change jobs the most times in their life?',
  'Who will stay at the same company for 40 years?',
  'Who will one day work as a bartender on a cruise ship?',
  'Who will become chief of the village volunteer fire department?',
  'Who will build a career as an influencer for retiree products?',
  'Who will one day become a Michelin-star chef?',
  'Who will become a teacher and regret it on day one?',
  'Who here will be the first to earn a six-figure salary?',
  'Who will one day work for the secret service and not be allowed to tell anyone?',
  'Who will become the undertaker with the darkest sense of humor?',
  'Who will ditch a well-paid job to become a yoga teacher in Bali?',
  'Who will be the first to be replaced by a robot at work?',
  'Who will become world champion in a completely unknown sport?',
  'Who will end up coaching a local amateur soccer team?',
  'Who will become a referee someday and get yelled at by everyone?',
  'Who will one day spend a year doing research at a station in Antarctica?',
  'Who will work as a private detective someday?',
  'Who will end up as a famous DJ playing sets in Ibiza?',
  'Who will become a janitor and absolutely love the job?',
  'Who will win a Nobel Prize one day?',
  'Who will become a lawyer and then win every argument, even at home?',
  'Who will become a circus ringmaster someday?',
  'Who will end up presenting the weather on TV?',
  'Who will one day work as a butler for the super rich?',
  'Who will become the boss that all the employees hate?',
  'Who will be a millionaire at 30 and broke at 35?',
  'Who here will be the first to start their own business?',
  'Who will voice a character in an animated movie someday?',
  'Who will buy a soccer club someday?',
  'Who will get rich with crypto and then lose it all again?',
  'Who will one day inherit a castle from an aunt they never knew?',
  'Who will still be in overdraft at 60?',
  'Who will donate a fortune to a good cause someday?',
  'Who will be the first to buy a private jet?',
  'Who will borrow money from everyone here and never pay it back?',
  'Who will blow their first big paycheck entirely on sneakers?',
  'Who will live as frugally as a monk despite having millions in the bank?',
  'Who will buy a Lamborghini at 70?',
  'Who will pay for a trip around the world for everyone here someday?',
  'Who will win an Oscar one day?',
  'Who will guest-star in a big TV crime drama someday?',
  'Who will host their own talk show someday?',
  'Who will win a talent show on TV one day?',
  'Who will sing at the Eurovision Song Contest someday?',
  'Who will one day go on a celebrity jungle reality show?',
  'Who will get discovered as an extra in a Hollywood movie?',
  'Who will one day be the face of a hemorrhoid cream commercial?',
  'Who will get their own cooking show on TV?',
  'Who will be featured in a documentary about weird hobbies?',
  'Who will be interviewed on the news as an eyewitness someday?',
  'Who will one day sing in a boy band or girl group?',
  'Who will sell out an entire stadium with their own concert someday?',
  'Who will end up as a wax figure at Madame Tussauds?',
  'Whose face will be on a postage stamp one day?',
  'Who will become the star of a daytime soap opera?',
  'Who will end up on a game show and fall into the water pool on live TV?',
  'Who will make money from videos where they just eat food?',
  'Who will start a podcast that only their mom listens to?',
  'Who will become a famous gamer with millions of viewers?',
  'Who will win a big national comedy award someday?',
  'Whose life will Netflix turn into a series one day?',
  'Who will be a regular guest on a political talk show every Sunday night?',
  'Who will show up in a TV throwback show in 30 years as the most embarrassing moment of the year?',
  'Who will still be posting dance videos online at 70?',
  'Who will become an influencer for garden gnomes?',
  'Who will one day lose everything because of a single post?',
  'Who here will be the first to delete all their social media for good?',
  'Who will start a challenge that the whole world copies?',
  'Who will have a YouTube channel about knitting patterns at 80?',
  'Who will film their kids every day for a family channel?',
  'Who will give everyone money tips online while being broke themselves?',
  'Who will livestream their own wedding?',
  'Who will advertise a product they secretly hate?',
  'Who will post a selfie every single day for 40 years?',
  'Who will get their first big online backlash over a recipe?',
  'Who will become the admin running every family group chat?',
  'Who will move to Canada and become a lumberjack?',
  'Who will ride a motorcycle around the world someday?',
  'Who here will be the first to visit every country on Earth?',
  'Who will end up living on a houseboat?',
  'Who will one day live in an old lighthouse?',
  'Who will move to a big city and only last two weeks?',
  'Who will never move away from their hometown?',
  'Who will one day join a monastery or convent?',
  'Who will end up living next to a celebrity and constantly ringing their doorbell?',
  'Who will become the annoying neighbor who calls the cops over every hedge?',
  'Who will one day live in a smart home that just does whatever it wants?',
  'Who will move abroad and come back crying after a month?',
  'Who will miss the most flights when traveling?',
  'Who will walk the entire Camino de Santiago someday?',
  'Who will end up living in Japan and speaking fluent Japanese?',
  'Who will end up living right next door to their parents?',
  'Who will move into a big shared house with all their friends?',
  'Who will become a permanent camper with an awning, a satellite dish and a garden fence?',
  'Who will renovate an old house and never finish it?',
  'Who will move to a city just because their favorite team plays there?',
  'Who will work on their laptop from beaches all over the world?',
  'Who will have their own bowling alley in the basement?',
  'Who will own a vacation home in Italy that everyone here gets to use?',
  'Who will become the retiree who watches construction sites every day?',
  'Who will still be gaming all night long at 80?',
  'Who will flirt with everyone on their floor at the retirement home?',
  'Who will still be skydiving out of planes at 70?',
  'Who will still be running marathons at 75?',
  'Who will grow prize-winning giant pumpkins in retirement?',
  'Who will beat everyone at chess in the park in their old age?',
  'Who will sit at the window with binoculars every day at 85?',
  'Who will spend their whole retirement at the golf club?',
  'Who will become a regular at senior dance nights?',
  'Who will write angry letters to the editor in their old age?',
  'Who will still be in the front row at festivals at 90?',
  'Who will take up bodybuilding in their old age?',
  'Who will wear nothing but beige in their old age?',
  'Who will learn five new languages in retirement?',
  'Who will start a rock band at the retirement home?',
  'Who will become head of the community garden club in old age and inspect every hedge?',
  'Who will tell every story ten times in their old age?',
  'Who will get a huge tattoo at 70?',
  'Who will retire early at 45?',
  'Who will still be writing love letters at 90?',
  'Who will believe every conspiracy theory in their old age?',
  "Who will get a truck driver's license in retirement?",
  'Who will have a horse in their own backyard someday?',
  'Who will start their own alpaca farm?',
  'Who will become a beekeeper with ten hives?',
  'Who will give their pet a human name like Gary or Barbara?',
  'Who will buy a baby stroller for their dog?',
  'Who will throw a birthday party with guests for their cat?',
  'Who will have a parrot that only knows swear words?',
  'Who will win a beauty contest with their dog?',
  'Who will have a pet pig living with them in the apartment?',
  'Who will become a shepherd in the Alps?',
  'Who will keep goats on their balcony?',
  'Who will take their pet to an animal therapist?',
  'Who will sell homemade cheese at the farmers market?',
  'Who will one day proudly drive their own tractor through the village?',
  'Who will start building model railroads at 40?',
  'Who will one day be crowned champion at the village shooting festival?',
  'Who will one day run an ultramarathon through the desert?',
  'Who will stand on the summit of Mount Everest someday?',
  'Who will sing in the church choir every Wednesday?',
  'Who will play in a cover band at village festivals?',
  'Who will get addicted to 5,000-piece jigsaw puzzles?',
  'Who will end up building ships in bottles?',
  'Who will become air guitar world champion?',
  'Who will one day be crowned carnival king or queen?',
  'Who will spend every weekend in a suit of armor at medieval reenactments?',
  'Who will collect Kinder Surprise toys worth as much as a car?',
  'Who will one day swim across the English Channel?',
  'Who will know every mushroom in the forest by name?',
  'Who will become the home cook who gives everyone unsolicited advice?',
  'Who will brew their own beer in the basement?',
  'Who will lead the country one day?',
  'Who will found their own political party someday?',
  'Who will one day move into the presidential palace?',
  'Who will run for parliament and get exactly three votes?',
  'Who will organize the biggest protest in town?',
  'Who will become minister of a department nobody has ever heard of?',
  'Who will have a law named after them one day?',
  'Who will become notorious on the city council for the longest speeches?',
  'Who will chain themselves to a tree in protest someday?',
  'Who will become a poll worker and count every vote three times?',
  'Who will one day have to testify before an official inquiry?',
  'Who will become president of a tiny country nobody has heard of?',
  'Who will one day invent a gadget that actually changes the world?',
  'Who will found a startup and sell it to Google?',
  'Who will pitch an idea on Shark Tank someday?',
  'Who will invent a new drink that suddenly everyone is drinking?',
  'Who will start a sock subscription company?',
  'Who will invent a whole new sport?',
  'Who will invent a party game that the whole world plays?',
  'Who will found a startup with 50 employees and not a single customer?',
  'Who will invent a new holiday that everyone celebrates?',
  'Who will one day discover a new species of animal?',
  'Whose spice blend will be in every supermarket one day?',
  'Who will organize their own music festival someday?',
  'Who will open a whole chain of kebab shops?',
  'Who will open a café where cats serve the coffee?',
  'Who will write a crime novel where everyone here is a suspect?',
  'Who will become a painter whose work is only worth anything after they die?',
  'Who will write a relationship advice book despite never making it work themselves?',
  "Who will become a well-known children's book author?",
  'Who will make their own movie for the big screen someday?',
  'Who will one day write their own musical?',
  'Who will write a twelve-book fantasy series and never finish it?',
  'Who will start a punk band at 45?',
  'Who will quit everything in a midlife crisis and sail around the world?',
  'Who will buy a motorcycle in their midlife crisis that never leaves the garage?',
  'Who will have themselves frozen after death to wake up again later?',
  'Who will one day find a real treasure?',
  'Who will one day win a lawsuit against a global corporation?',
  'Who will get famous for a totally ridiculous dare?',
  'Who will one day accidentally end up in a foreign country without a passport?',
  'Who will still have the same phone in ten years?',
  'Who will one day be made an honorary citizen of their hometown?',
  'Who here will be the first to go bald?',
  'Who will still be drinking canned beer in the park with old friends at 60?',
  'Who will organize the big reunion of this group in 20 years?',
  'Who will still be friends with everyone here in 30 years?',
  'Who will still be calling at 3 a.m. in ten years just to chat?',
  'Who will eventually turn into a square who wears socks with sandals?',
  'Who will turn into their parents in ten years?',
  "Who will keep mixing up their grandkids' names in old age?",
];
