export const interactiveQuestionsEn: string[] = [
  'Who dances the worst? Show us your best move for 10 seconds!',
  'Who does the best impressions? Imitate someone in the group, everyone else guesses who!',
  'Who has the loudest laugh? Laugh as loud as you can for 5 seconds!',
  'Who gives the best compliments? Give everyone in the group an honest compliment!',
  'Who would be the perfect Hollywood casting? Act out a movie without words, the others guess!',
  'Who has the best poker face? Stay serious for 30 seconds while everyone tries to make you laugh!',
  'Who could most likely do stand-up comedy? Tell us your best joke!',
  'Who is the most dramatic? Act out a death scene like in the movies!',
  'Who has the nicest smile? Smile at the person on your left for ten seconds!',
  'Who does the best animal sounds? Imitate three animals, the others guess!',
  'Who would go on a talent show? Show us your hidden talent!',
  'Who would make the best gala host? Announce the next person as if they were a superstar!',
  'Who has the best singing voice? Sing a nursery rhyme as if you were on an opera stage!',
  'Who has the weirdest emoji history? Show the group your most recently used emojis!',
  'Who would most likely win a dance battle? Challenge someone to a 15-second battle!',
  'Who is the quickest-witted? Come up with a rhyme about the person on your right in 10 seconds!',
  "Who has the best memory? Name everyone's drink in the group without looking!",
  'Who would be the best voice for commercials? Sell us your drink in a 20-second ad!',
  "Who could most likely read the news? Announce tonight's events as breaking news!",
  'Who is the most honest? Tell the person across from you what you appreciate most about them!',
  'Who could best play a robot? Move like a robot for 30 seconds!',
  'Who plays the best air guitar? Give us a 15-second solo!',
  'Who would make the best sports commentator? Commentate live on what the person on your left is doing!',
  'Who would make the best mayor? Give the group a short campaign speech!',
  'Who is the worst liar? Tell two truths and a lie, the others guess!',
  'Who has the most distinctive voice? Read this card again like an audiobook!',
  'Who has the most magic powers? Make something on the table disappear or show us a trick!',
  'Who would star in a musical? Sing us what you ate today!',
  'Who has the best balance? Stand on one leg for 30 seconds and take a sip while you do!',
  'Who is the best motivator? Give the group a 20-second pep talk!',
  'Who pulls the best faces? Show us your three best funny faces!',
  'Who would most likely win a quiz show? Answer a trivia question the group asks you!',
  'Who tells the best stories? Tell a 30-second fairy tale starring everyone in the group!',
  'Who is the most diplomatic? Settle a made-up fight between the two people next to you!',
  'Who loses patience the fastest? Stay completely silent and still for 20 seconds!',
  'Who knows the most ad jingles? Sing an ad jingle, the others guess the brand!',
  'Who would most likely give a wedding speech? Raise a toast to the group!',
  'Who has the best body control? Do the moonwalk, or at least try!',
  'Who is best at charades? Act out a job without words, the others guess!',
  'Who watches the most TV shows? Act out a scene from your favorite show, the others guess!',
  'Who does the best celebrity impressions? Imitate a celebrity until someone guesses who!',
  'Who is the biggest fan of a band? Hum a song by that band, the others guess!',
  'Who has what it takes to be a rap star? Rap four lines about the person on your left!',
  "Who is best at explaining things? Teach the group something you're really good at in 30 seconds!",
  'Who is funniest without words? Make the group laugh in 20 seconds without speaking!',
  'Who has the best instincts? Guess who in the group has had the most to drink tonight and explain why!',
  'Who is the most helpful? Wait on the person to your right like at a luxury hotel until the next card!',
  'Who is best at drawing? Draw a picture in the air with your finger, the others guess!',
  'Who is the most athletic? Do 10 jumping jacks and get the group to join in!',
  'Who could best play a villain? Laugh like a movie villain and reveal your evil plan!',
  'Who has the most refined taste? Describe your drink as if you were at a wine tasting!',
  'Who gives themselves away the fastest? Look the person across from you in the eye for 20 seconds without laughing!',
  'Who has the best taste in music? Show us the last song you listened to and defend it!',
  'Who is the most curious? Interview the person on your left with three spontaneous questions!',
  'Who has the most creative imagination? Invent a new word and explain what it means!',
  "Who is best with kids? Explain the internet to us like we're five years old!",
  'Who oversleeps the most? Play your alarm sound for the group!',
  'Who has the biggest talent for languages? Say one sentence in as many languages as you can!',
  'Who gives the best advice? Give the person on your right a life tip for the week!',
  'Who has the most energy? Stand up and start a Mexican wave with the whole group!',
  'Who would most likely host a cooking show? Present how you make your favorite dish for 20 seconds!',
  'Who swears most creatively? Invent a harmless swear word and use it in a sentence!',
  'Who would be the best nature documentary narrator? Narrate the group like a herd of wild animals!',
  'Who has the nicest handwriting? Write a word with your finger on the back of the person to your left, they guess!',
  'Who is most likely a drama queen? Complain theatrically about your drink for 20 seconds!',
  'Who would be the first to start a podcast? Present your podcast with an intro in 15 seconds!',
  "Who remembers kids' shows best? Sing the theme song of a kids' TV show!",
  'Who would most likely star in a soap opera? Get down on one knee and make a dramatic proposal to the person across from you!',
  'Who has the best narrator voice? Tell us how you got here today as if it were an adventure movie!',
  'Who has the most breath? Say the whole alphabet in a single breath!',
  'Who is the worst at geography? Name five capital cities in 15 seconds!',
  'Who talks with their hands the most? Tell us something for 20 seconds while keeping your hands under the table!',
  'Who is most likely not a morning person? Act out how you wake up in the morning!',
  "Who is the biggest foodie? Describe your dream meal so everyone's mouth starts watering!",
  'Who does the best accents? Say one sentence in three different English accents!',
  'Who is the most superstitious? Tell us your weirdest superstition and perform the ritual!',
  'Who has the best sense of rhythm? Drum a beat on the table, the others guess the song!',
  'Who is the most scatterbrained? Close your eyes and describe what the person across from you is wearing!',
  'Who would make the best cheesy pop star? Make up a cheesy chorus about tonight!',
  'Who is the best negotiator? Try to sell your shoe to someone in the group!',
  'Who is most likely a night owl? Yawn so contagiously that someone yawns along!',
  'Who has the strangest favorite show? Sum up the last episode in three sentences!',
  'Who would most likely be a talk show guest? Interview yourself using two different voices!',
  'Who has the best sense of time? Say what time it is without looking at a clock!',
  'Who is most likely a language genius? Say the alphabet backwards as far as you can!',
  'Who has the best timing? With your eyes closed, count exactly 10 seconds while the group times you!',
  'Who is best at comforting others? Comfort the person on your left about a made-up mishap!',
  'Who would make the best tour guide? Lead the group through this room like a bunch of tourists!',
  'Who loves cheesy romance the most? Recite a love poem you wrote yourself to your drink!',
  "Who would survive longest on a desert island? Name three things from this room you'd take and explain why!",
  'Who is the tidiest? Make the table look as neat as possible in 15 seconds!',
  'Who has the highest voice? Sing a scale as high as you can!',
  'Who has the deepest voice? Talk like a movie trailer voice and announce the next card!',
  'Who is best at selling themselves? Pitch yourself for a spare room in a shared apartment in 20 seconds!',
  'Who has the best excuses? Invent an absurd excuse for why you were late today!',
  'Who is most likely a bookworm? Tell us the plot of your favorite book in three sentences!',
  'Who is the most competitive? Challenge someone to rock-paper-scissors, first to two wins takes it!',
  'Who has the worst sense of direction? Point north with your eyes closed!',
  'Who is most likely a meme themselves? Recreate a famous meme, the others guess!',
  'Who could best invent a sport? Explain and demonstrate a brand-new sport for the table!',
  'Who games the most? Imitate the sounds of a video game, the others guess which one!',
  'Who has the funniest family? Imitate a family member saying their signature line!',
  'Who talks the most in their sleep? Show us how you talk in your sleep!',
  'Who is the most generous? Give everyone in the group an imaginary award and explain why!',
  'Who is the most romantic? Describe your perfect first date in 20 seconds!',
  'Who loves riddles the most? Give the group a riddle, they have 30 seconds to solve it!',
  'Who has the best posture? Walk across the room once like on a catwalk!',
  "Who googles diseases the most? Act out a dramatic doctor's visit over the hiccups!",
  'Who is best at remembering numbers? Memorize a ten-digit number the group gives you and repeat it!',
  'Who would most likely move abroad? Explain in a made-up language why you are moving abroad!',
  'Who would be perfect for a horror movie? Tell a three-sentence scary story in a whisper!',
  'Who is the fittest? Hold a plank for 20 seconds!',
  'Who is best at disguising their voice? Tell us your plans for tomorrow in a cartoon character voice!',
  'Who is the biggest kid at heart? Explain your favorite playground game to the group and act it out briefly!',
  'Who loves posing for photos the most? Show us your three best photo poses!',
  'Who is the best listener? Sum up what the group talked about in the last five minutes!',
  'Who is most likely a word nerd? Name five words that rhyme with table in 10 seconds!',
  "Who would most likely open a restaurant? Present your restaurant's menu with three dishes!",
  'Who knows the most about fashion? Rate the outfits in the group like a fashion show judge, positive comments only!',
  'Who knows the most sayings? Finish three sayings that the group starts!',
  'Who has the funniest sneeze? Show us a sneeze in slow motion!',
  'Who would be the best GPS voice? Guide the person on your right once around the table with directions!',
  'Who most likely collects weird things? Tell us what you collect and make a pitch for it!',
  'Who has the softest heart? Tell the cutest animal story you know!',
  'Who is worst at mental math? Work out 17 times 13 in your head while the group times you!',
  'Who would most like to be a cat? Act like a cat until the next card!',
  'Who has the best party tricks? Show us something unusual you can do with your fingers!',
  'Who would be the best auctioneer? Auction off a glass of water to the group as fast as you can!',
  'Who has traveled the most? Describe your favorite travel destination without naming it, the others guess!',
  'Who has the most exciting life story? Sum up your life in five words!',
  'Who loves cooking the most? Mime cooking a dish, the others guess what it is!',
  'Who would most likely be a superhero? Invent your superpower and show how you use it!',
  'Who exaggerates the most? Tell us the most boring part of your day as excitingly as possible!',
  'Who is best at technical jargon? Explain a spoon as if you were giving a university lecture!',
  'Who enjoys their drinks the most? Toast each person individually with a different toast!',
  'Who would most likely join a flash mob? Teach the group a simple dance move, everyone joins in!',
  'Who is best at painting with words? Describe an object in the room without naming it, the others guess!',
  'Who startles the easiest? Tell us when you last got really scared and act it out!',
  'Who has the most unusual hobbies? Explain your weirdest hobby in 20 seconds using your whole body!',
  'Who would most likely win an Oscar? Give your acceptance speech in tears!',
  'Who is the most relaxed? Lead the group through a 20-second meditation!',
  'Who would be the best help with heartbreak? Give the group a tip against heartbreak in rhyme!',
  'Who talks the most? Talk about socks for 20 seconds without saying um or uh!',
  'Who has the best gut feeling? The person on your right thinks of a number from 1 to 10, you get three guesses!',
  'Who knows the most movie quotes? Say three famous movie quotes, the others guess the film!',
  'Who would most likely run a marathon? Run in place for 15 seconds and commentate on yourself!',
  'Who would make the best game show host? Ask the group an estimation question, the closest answer wins!',
  'Who has the most creative nicknames up their sleeve? Give everyone in the group a new nickname!',
  'Who would most likely argue with a vending machine? Act out a fight with a coffee machine!',
  'Who sings the loudest in the car? Sing the start of a song as if you were alone in your car!',
  'Who is best at reciting poems? Recite a poem from your school days, as much as you still remember!',
  'Who is most likely a game night pro? Explain the rules of a board game in 20 seconds!',
  'Who would most likely go into politics? Explain which law you would pass first!',
  'Who is most likely a puzzle fan? Think of a word, the group gets ten yes-or-no questions to guess it!',
  'Who has the funniest walk? Walk around the table once like a penguin!',
  'Who is best at hyping up a crowd? Get the whole group clapping together in rhythm!',
  'Who is most stuck in the 2000s? Show us a dance that was popular back then!',
  'Who has the best eye for distances? Guess how many phone lengths long the table is, then measure!',
  'Who has what it takes to be a pop star? Invent a band name for the group and sing a chorus for it!',
  'Who is best at copying movements? Mirror every move of the person across from you for 15 seconds!',
  'Who has the fastest reflexes? Clap your hands as soon as the person on your left unexpectedly says now!',
  'Who understands animals best? Translate what a dog would think about tonight!',
  'Who knows the group best? Name the favorite snack of every person here!',
  'Who would have done best in the Middle Ages? Talk like someone from medieval times until the next card!',
  'Who watches the most reality TV? Act out a typical drama scene from a reality show!',
  'Who loves talking about the old days? Talk for 20 seconds about how the world used to be, like a very old person!',
  'Who always finds a reason to celebrate? Invent a holiday for today and explain how it is celebrated!',
  'Who would be perfect for a crime show? Interrogate the person on your left about a made-up crime!',
  'Who is the best beatboxer? Give us 10 seconds of beatbox!',
  'Who whistles best? Whistle a melody, the others guess the song!',
  'Who would stand out most in the Alps? Try yodeling for 5 seconds!',
  'Who remembers school days best? Tell us about your first day of school in three sentences!',
  'Who would most likely live in a monastery? Only whisper until the next card!',
  'Who has the best gift ideas? Tell each person what you would give them for their birthday!',
  "Who is most likely a regular at a bar? Order your next drink like you're at your local spot!",
  'Who loses things most often? Act out desperately searching for your keys!',
  'Who would shine most in a silent film? Act out a 20-second chase scene without any sound!',
  'Who has the most unusual eating habits? Describe your weirdest favorite food combo and defend it!',
  'Who is most glued to their phone? Guess your screen time for today, then check!',
  "Who sees through lies the fastest? The person on your left tells you something, you say if it's true!",
  'Who daydreams the most? Describe your perfect day from morning to night!',
  'Who does the best machine impressions? Make the sounds of a coffee machine, a washing machine and a printer!',
  "Who has the steadiest hand? Hold your drink at arm's length for 20 seconds without wobbling!",
  'Who would make the best flight crew? Give the safety announcement for this room!',
  'Who is best at improvising? The group names three words, you work them into a story right away!',
  'Who would win a spelling bee? Spell a word the group gives you backwards!',
  'Who has the most animal photos? Show us the cutest animal photo on your phone!',
  'Who puts one song on repeat the most? Play us 10 seconds of it and explain why!',
  'Who notices the smallest details? The group changes something while your eyes are closed, find it!',
  'Who keeps the beat best? Clap a rhythm, the group has to copy it!',
  'Who is the least addicted to their phone? Put your phone face down in the middle of the table until the next card!',
  'Who would most likely go on a cruise? Pretend the group is on a ship caught in a storm and give orders!',
  'Who has the most plants? Talk about your favorite plant as if it were a person!',
  'Who loves talking to themselves the most? Have a loud conversation with yourself for 15 seconds!',
  'Who knows the most about Disney movies? Sing a Disney song as far as you know it!',
  "Who loves planning the most? Plan the group's next outing in 20 seconds!",
  'Who is the silliest? Say a serious sentence in the silliest voice you can!',
  'Who is best at getting sympathy? Beg the group for a sip for 15 seconds!',
  'Who writes the best love letters? Dictate a short love letter to pizza!',
  'Who reacts worst to spoilers? Show us your reaction to a huge spoiler!',
  'Who is most likely a cuddle monster? Hand out a hug to everyone who wants one!',
  'Who is best at dodging questions? The group asks you three questions, answer only with questions!',
  'Who has the weirdest dreams? Tell us your strangest dream in 20 seconds!',
  'Who would survive a zombie apocalypse the longest? Explain your escape plan from this room!',
  'Who is best at keeping secrets? Tell a made-up secret in a way that makes everyone curious!',
  'Who stays calmest under stress? Say the alphabet while the group counts out loud over each other!',
  'Who takes themselves the least seriously? Do a parody of yourself!',
  "Who is best at showing emotions? Say I'm hungry in five different moods!",
  'Who would most likely write a food blog? Review your last snack like a restaurant critic!',
  'Who is the sorest loser? Act out a dramatic tantrum after losing a game!',
  'Who would be the best language teacher? Teach the group a word in a foreign language, everyone repeats it!',
  'Who loves telling anecdotes the most? Tell the funniest story from your childhood!',
  'Who would most like to fly to space? Act out zero gravity for 15 seconds!',
  'Who keeps track of things in chaos? Line the group up by height in 15 seconds!',
  'Who has the best feel for the beat? Conduct the group while everyone hums a song together!',
  'Who would most likely write a self-help book? Name the title and its three most important rules!',
  'Who is the calmest person here? Talk about your day for 20 seconds in a soothing radio voice!',
  'Who is most likely a chatterbox? Talk for 30 seconds nonstop, the group gives you a new topic every 10 seconds!',
  'Who is best at admitting mistakes? Apologize with exaggerated formality to the person on your right for something made up!',
  'Who would most likely camp at a festival? Show us how you look after three days at a festival!',
  'Who has the strongest opinions? Make a passionate case for or against pineapple on pizza!',
  'Who is best at making up rules? Introduce a new rule that applies until the end of the game!',
  'Who would be the best voice for a video game? Say the line Level complete in three different voices!',
  "Who is most creative with names? Come up with a name for this group's group chat!",
  'Who is the least picky eater? Let the group describe a weird dish to you and react with excitement!',
  'Who is best at small talk? Make 20 seconds of small talk about the weather with the person across from you!',
  'Who would most likely regret a tattoo? Describe the worst tattoo you can imagine!',
  'Who is best at reading facial expressions? The person across from you shows an emotion without words, you guess it!',
  'Who would make the best witness? Describe the person on your right as if a police sketch artist were drawing from your words!',
  'Who would most likely win the lottery? Tell us the first thing you would do with a million!',
  'Who has the most self-confidence? Name three things you really like about yourself!',
  'Who is most likely a science fan? Explain a natural phenomenon completely wrong but convincingly!',
  'Who is best at renaming things? Give three everyday objects new, better names!',
  'Who is most often lost in thought? Repeat the last sentence someone said before this card!',
  'Who would be perfect for the stage? Perform the line Where are my keys as a tragedy, a comedy and a crime drama!',
  'Who had the craziest family vacation? Tell us about it in three sentences!',
  'Who reacts best to surprises? Act out three reactions to a gift: thrilled, disappointed, touched!',
  'Who sings the most off-key? Sing Twinkle Twinkle Little Star as off-key as you can on purpose!',
  'Who has the biggest vocabulary? Name five synonyms for drunk!',
  'Who would most likely invent a musical instrument? Make music for 10 seconds using only your body!',
  'Who loves making lists the most? Name the three best moments of tonight!',
  'Who has the best bedtime voice? Tell the group a bedtime story in four sentences!',
  'Who most likely reads horoscopes? Give the person on your left their horoscope for tomorrow!',
  'Who would most likely set a world record? Invent a world record you can set right here and set it!',
  'Who has the best movie ideas? Pitch the group a movie about tonight in 20 seconds!',
  'Who is the biggest kid? Act like a toddler who desperately wants ice cream for 10 seconds!',
  'Who most likely sings while hiking? Start singing a campfire song, the group joins in!',
  'Who would play the lead in a Western? Show us how fast you can draw your phone like a revolver!',
  'Who writes the nicest greeting cards? Dictate a birthday card for the person on your right!',
  "Who could best write a children's book? Make up a four-sentence story about an animal with a problem!",
  'Who has the most adventures on trains? Tell us about your craziest train ride in 20 seconds!',
  'Who is best at rewriting songs? Rewrite the first line of a famous song so it is about tonight!',
  'Who is the best ventriloquist? Make your drink say something without moving your lips!',
  'Who would scream first on a ghost tour? Do the best horror movie scream you can!',
  'Who writes the most honest reviews? Rate tonight with stars and a short review!',
  'Who would most likely film unboxing videos? Mime unboxing a present and commentate as you go!',
  'Who sounds most convincing on the phone? Act out a call to customer service!',
  'Who would be perfect for a fairy tale? Play a fairy who grants each person a wish!',
  'Who talks to pets the most? Talk to the group for 15 seconds the way you would talk to a puppy!',
  'Who follows the news the most? Make up three positive headlines for tomorrow!',
  'Who watches the most movies? Describe a movie in three words, the others guess!',
  'Who would most likely invent their own language? Teach the group three words of your own language!',
  'Who has the biggest breakfasts? Describe your perfect breakfast with all the sound effects!',
  'Who would most likely study art? Explain an invisible artwork in the room like a museum guide!',
  'Who fits in anywhere? Find three things in common with the person on your left in 30 seconds!',
  'Who would be the best voice for train announcements? Announce the delay of the next drink!',
  'Who would most likely enter a baking competition? Describe the cake you would bake for the group!',
  "Who is the most stubborn? The group tries to convince you of something absurd for 20 seconds, don't give in!",
  'Who would most likely talk to objects? Act out a dialogue between your phone and your drink!',
  "Who is most likely an adrenaline junkie? Tell us the bravest thing you've ever done!",
  'Who is best at recognizing voices? Close your eyes, someone says hello in a disguised voice, guess who!',
  'Who gets annoyed by little things the most? Act out a dripping tap keeping you awake at night!',
  'Who gives the best applause? Give the group a standing ovation and explain why!',
  'Who is most likely a sports fan? Start a fan chant for the group!',
  'Who would most likely perform at a poetry slam? Recite four lines about your phone!',
  'Who struggles most with autocorrect? Type a sentence without looking and read out what it turned into!',
  'Who loves word games the most? Name a word that reads the same forwards and backwards!',
  'Who knows the most country flags? Describe a flag, the others guess the country!',
  'Who has the fastest mouth? Say Peter Piper picked a peck of pickled peppers three times fast!',
  'Who trips over their words the most? Say Red lorry, yellow lorry five times fast!',
  'Who has the quickest tongue? Say She sells seashells by the seashore three times fast!',
  'Who does the best British accent? Order your next drink in a posh British accent!',
  'Who sounds the most Italian? Tell us about your favorite food in an Italian accent with lots of hand gestures!',
  'Who rhymes the fastest? Rhyme with every word the group shouts at you for 15 seconds!',
  'Who would write the best report cards? Give the group a spoken report card with grades for tonight!',
  'Who remembers first meetings best? Tell us how you met someone here!',
  'Who would have the most exciting autobiography? Name its title and sum up the first chapter in two sentences!',
  'Who gets the most nervous before exams? Act out an oral exam about gummy bears!',
  "Who is most likely to invent something genius? Present an invention the world doesn't need!",
  'Who would fit best into the royal family? Give the group a royal wave for 10 seconds!',
  'Who has the most ceremonial manner? Knight the person on your right with a short speech!',
  'Who would make the best cashier? Mime scanning everything on the table with beep sounds!',
  'Who loves dodging the dishes the most? Explain for 20 seconds why washing dishes is dangerous!',
  'Who would most likely write a song about themselves? Sing a line from your own theme song!',
  'Who could still surprise the group? Share a harmless fact about yourself that nobody here knows yet!',
  'Who reflects on themselves the most? Record a message to yourself ten years from now!',
  'Who thinks about the future the most? Predict what each person here will be doing in ten years!',
  'Who has the wisest sayings? Come up with a fortune cookie message for the person across from you!',
  "Who would most like to time-travel? Say which year you're traveling to and act out a scene from there!",
  'Who is the life of every party? Get the whole group to shout cheers at the same time!',
];
