export const normalQuestionsEn: string[] = [
  'Who is most likely to forget their own birthday?',
  'Which of you has the most unread messages on their phone?',
  'Who hits snooze most often in the morning?',
  'Who is most likely to show up late, even to their own party?',
  'Who would get lost in IKEA?',
  'Which of you talks to pets like they are people?',
  'Who is most likely to have walked off with the wrong shopping cart at the supermarket?',
  'Who takes the longest to order at a restaurant?',
  'Who is most likely to watch a movie just because of the poster?',
  'Which of you has a drawer at home full of cables nobody needs anymore?',
  'Who sings along the loudest in the car?',
  'Who is most likely to have waved back at someone who was waving at someone else?',
  'Who is always the one with snacks on them?',
  'Which of you would struggle the most with a week without a phone?',
  'Who is most likely to binge an entire series in one weekend?',
  'Who is most likely to have searched for their phone while holding it?',
  'Who is the most prepared for vacation, with a packing list and everything?',
  'Which of you packs their suitcase an hour before leaving?',
  'Who is most likely to laugh at their own joke before the punchline?',
  'Who is most likely to have more than ten browser tabs open?',
  'Who argues the most during game night?',
  'Which of you knows the most song lyrics by heart?',
  'Who is most likely to give a pet a really unusual name?',
  'Who is most likely to fall asleep at the movies?',
  'Who is most likely to have pushed a door that clearly said pull?',
  'Who is most likely to reply in the group chat with nothing but emojis?',
  'Which of you would show up to a talent show with the weirdest talent?',
  'Who is most likely to have a houseplant jungle at home?',
  'Who loses their keys, headphones or wallet most often?',
  'Who is most likely to have talked to themselves without noticing?',
  'Which of you takes a photo of the food before anyone eats?',
  'Who tells the longest version of a story that could have been short?',
  'Who is most likely to need three tries to park the car?',
  'Which of you has the strangest collection at home?',
  'Who is most likely to make pancakes in the middle of the night?',
  'Who is most likely to have killed a plant that is supposedly impossible to kill?',
  'Which of you would be first to solve the puzzle in an escape room?',
  'Who is most likely to spend an entire weekend in their pajamas?',
  'Who is most likely to dance when nobody is watching?',
  'Who is most likely to have sent a voice message longer than five minutes?',
  'Who is most likely to forget the shopping list when going shopping?',
  'Who is most likely to book a trip on the same day they leave?',
  'Who is the slowest eater here?',
  "Who is most likely to forget someone's name right after being introduced?",
  'Who leaves clean laundry on the chair the longest?',
  'Who is most likely to load the dishwasher without being asked?',
  'Who is most likely to have assembled a piece of furniture wrong?',
  'Who is most likely to comment on every scene in the movie theater?',
  'Which of you has the weirdest favorite snack?',
  'Who is most likely to read an entire book in one day?',
  'Who sends the most funny videos to the group chat?',
  'Who is most likely to have worn their socks inside out all day without noticing?',
  'Who always knows where the nearest good coffee shop is?',
  'Who gets cold the fastest, even in summer?',
  'Who is most likely to send the most postcards on vacation?',
  'Which of you has the most creative phone wallpaper?',
  'Who is most likely to pace around the whole apartment while on the phone?',
  'Who is most likely to buy something just because it is on sale?',
  'Who is most likely to have hummed the same song all day without realizing?',
  'Who always buys gifts on the very last day?',
  'Who is most likely to buy more than they sell at a flea market?',
  'Who always has an excuse ready for skipping the gym today?',
  'Who is most likely to have seen the same movie three times in theaters?',
  'Who always has their eyes closed in group photos?',
  'Which of you would win a competition in doing nothing?',
  'Who takes the longest in the bathroom in the morning?',
  'Which of you drinks their first coffee before brushing their teeth?',
  'Who is most likely to miss their bus stop because the music is too good?',
  'Who checks most often whether the stove is really off?',
  'Who is most likely to have put salt instead of sugar in their coffee?',
  'Who is already chatty in the morning while everyone else is half-asleep?',
  'Which of you takes the longest to decide on an outfit?',
  'Who is most likely to wear shorts in any weather?',
  'Who is most likely to own more jackets than their coat rack can hold?',
  'Who is most likely to go to the bakery in their slippers?',
  'Which of you gets caught in the rain without an umbrella most often?',
  'Who is most likely to order pizza with pineapple?',
  'Which of you would season every dish before even tasting it?',
  'Who always orders the exact same thing from delivery?',
  'Who is most likely to order a dish just because of its funny name on the menu?',
  "Who is most likely to steal fries off other people's plates?",
  'Who is most likely to have forgotten there was pasta on the stove?',
  'Which of you can handle the spiciest food?',
  'Who would refuse to give up the tongs at a barbecue?',
  'Which of you always has room for dessert, no matter how full?',
  'Who is most likely to eat cereal for dinner?',
  'Who is most likely to have eaten something expired and only noticed afterward?',
  'Who always takes the last piece when sharing food?',
  'Which of you bakes huge batches of cookies at Christmas?',
  'Who could most likely go a whole month without sweets?',
  'Who is most likely to cut the crusts off their bread?',
  'Who would go back for the most rounds at an all-you-can-eat buffet?',
  'Who is most likely to eat breakfast at lunchtime?',
  'Who is most likely to have cooked a recipe from a video that looked nothing like the original?',
  'Who orders the most complicated coffee drink at a café?',
  'Which of you is most likely to try snails or insects?',
  'Who turns the whole kitchen into a disaster zone when cooking?',
  'Who is most likely to drink cold coffee because they forgot the hot one?',
  'Who is most likely to eat ice cream even in the dead of winter?',
  'Who is most likely to have opened the fridge without knowing what they were looking for?',
  'Which of you can make a meal out of an almost empty fridge?',
  'Who is most likely to put ketchup on literally everything?',
  'Who is most likely to eat all the advent calendar chocolates ahead of time?',
  'Who is most likely to iron even their socks?',
  'Who puts off doing the dishes the longest?',
  'Who is most likely to only clean their place when guests are coming?',
  'Who is most likely to have washed something red with the whites?',
  'Which of you is most likely to have named their robot vacuum?',
  'Who is most likely to still have moving boxes that were never unpacked?',
  'Who takes the longest to return their empty bottles?',
  'Who has the most food containers without matching lids?',
  'Which of you redecorates their home for every season?',
  'Who is most likely to leave a burned-out light bulb for weeks?',
  'Who tidies up by shoving everything into one closet?',
  'Who is most likely to have run the washing machine without any detergent?',
  'Who has the messiest car?',
  'Who is most likely to only do laundry when there is truly nothing clean left?',
  'Who is most likely to have a corner where the mail has been piling up for weeks?',
  'Who has the lowest phone battery right now?',
  'Who is most likely to forget their camera is on during a video call?',
  'Who is most likely to still be using a phone with a cracked screen?',
  'Who is the person in their family who has to fix every tech problem?',
  'Who is most likely to actually read the terms and conditions?',
  'Which of you has a collection of old phones in a drawer?',
  'Who is most likely to try to fix every problem by restarting the device?',
  'Who is most likely to have reset the same password three times in a row?',
  'Which of you always has their phone on silent and misses everything?',
  'Who is most likely to argue with a voice assistant?',
  'Who is most likely to screenshot everything?',
  'Who is most likely to have sent a message to the wrong person?',
  'Who is most likely to buy new tech on release day?',
  'Who is most likely to text without ever using capital letters?',
  'Who is most likely to ignore the GPS and then get lost?',
  'Who is most likely to have a playlist for every mood?',
  "Which of you apologizes the most, even when it's not necessary?",
  'Who is most likely to google something mid-argument just to be right?',
  'Who is worst at keeping a gift a secret?',
  'Who is most likely to plan everything, even a walk?',
  'Who is most likely to have an opinion on everything?',
  'Which of you is the most indecisive?',
  'Who is most likely to cry at a sad commercial?',
  'Who has the loudest laugh of everyone here?',
  'Who says "I told you so" the most?',
  'Who is the most curious person here?',
  'Who is most likely to have eavesdropped on strangers and almost joined the conversation?',
  'Who gets startled the most easily?',
  'Who is most likely to write a to-do list just to have something to check off?',
  'Who is the person who simply can never say no?',
  'Who has the most nicknames?',
  'Which of you would make the best detective?',
  'Who is the sorest loser at games?',
  'Who is most likely to talk in their sleep?',
  'Who is most likely to tell a stranger on a train their whole life story?',
  'Who is most likely to have made a bet about something completely pointless?',
  'Who is most likely to go jogging at six in the morning on a day off?',
  'Who is most likely to read horoscopes and take them seriously?',
  'Who is most likely to steer every conversation toward their favorite topic?',
  'Who has the loudest sneeze?',
  'Who has the most contagious yawn?',
  'Which of you has the best sense of direction?',
  'Who is most likely to cheat at a board game like Ludo?',
  'Who wants to talk about a movie for hours after watching it?',
  'Who is most likely to bring up the weather when the conversation dies?',
  'Who is most likely to start a new hobby and quit after a week?',
  'Who is most likely to have paid for a gym membership without ever going?',
  "Who can't stop once they start a thousand-piece puzzle?",
  'Who would hog the mic at karaoke night?',
  'Who is most likely to secretly knit or crochet?',
  'Who is most likely to have signed up for a fun run just for the medal?',
  'Which of you is most likely to play video games late into the night?',
  'Who is most likely to read every single sign in a museum?',
  'Who is most likely to read the rules out loud at board game night?',
  'Who is most likely to have listened to an audiobook at double speed?',
  'Which of you is most likely to bowl nothing but gutter balls?',
  'Who is most likely to doodle while on the phone?',
  'Who is most likely to do the crossword every single day?',
  'Who is most likely to watch documentaries about outer space or the deep sea?',
  'Who is most likely to play chess against strangers in the park?',
  'Who takes the rules of mini golf way too seriously?',
  'Who spends the most time at the hardware store?',
  'Who is most likely to start their own podcast?',
  'Who is most likely to have played one song on repeat a hundred times in a row?',
  'Who is most likely to watch cooking videos without ever cooking?',
  'Which of you has the most half-read books on their nightstand?',
  'Who would answer all the sports questions at a pub quiz?',
  'Who never wants to get into cold water when swimming?',
  'Who would fall over after two meters on the ice rink?',
  'Who is most likely to forget their ticket or passport before a flight?',
  'Which of you packs the most luggage for a weekend trip?',
  'Who is most likely to fall asleep the moment the train or plane starts moving?',
  'Who is most likely to have missed a train because they grabbed a quick coffee?',
  'Which of you always tries the local language abroad, even with only three words?',
  'Who brings back the cheesiest souvenirs from vacation?',
  'Who is most likely to have gotten sunburned on the first day of vacation?',
  'Who is at the airport three hours before their flight?',
  'Who would most want to control the music on a road trip?',
  'Who is most likely to have booked a hotel in the wrong city?',
  'Who is most likely to get lost in a new city and call it an adventure?',
  'Who keeps asking "Are we there yet?" on car rides?',
  'Who is most likely to have left something important behind at a highway rest stop?',
  'Which of you would happily vacation in the same place every year?',
  'Who is most likely to get homesick just three days into a vacation?',
  'Which of you has to pet every dog on the street?',
  'Who is most likely to have been handed the wrong order at the bakery and taken it anyway?',
  'Who sounds the most polite on the phone with strangers?',
  'Who is most likely to count out exact change at the checkout?',
  'Who is most likely to have picked up a package from a neighbor and chatted for an hour?',
  'Who is most likely to make friends with strangers while waiting in line?',
  'Who is most likely to talk way too loudly on the phone?',
  'Which of you would rather call than text?',
  'Who is most likely to have shown up to an appointment on the wrong day?',
  'Who is most likely to keep playing carnival games until they win the giant teddy bear?',
  'Who brings a homemade gift to every invitation?',
  'Who keeps talking at the door for another half hour when saying goodbye?',
  'Who gets asked for directions on the street most often?',
  'Who is most likely to have said "You too!" when it made absolutely no sense?',
  'Who is most likely to buy the biggest popcorn at the movies and finish it before the film starts?',
  'Who is most likely to file a complaint when the food arrives cold?',
  "Who is most likely to have tried to get into a stranger's car because it looked exactly the same?",
  'Who is most likely to make plans and then cancel at the last minute?',
  'Who is most likely to ask for a discount in a store?',
  'Who is the most scared of the dentist?',
  'Who is most likely to have written a letter by hand this year?',
  'Which of you would be most scared of a spider in the room?',
  'Who is most likely to carefully carry bugs outside instead of shooing them away?',
  'Who is most likely to have rescued an animal from a tree or a pond?',
  'Who can name every flower on a walk?',
  'Who is most likely to stand outside and watch a thunderstorm?',
  'If everyone here were an animal, who would be the cat?',
  'Who is most likely to go for a walk in pouring rain?',
  'Who is most likely to walk barefoot through the forest?',
  'Who is most likely to stargaze and explain all the constellations to everyone?',
  'Who is most likely to get up extra early to watch the sunrise?',
  'Which of you is most likely to watch movies with subtitles?',
  'Who is most likely to accidentally spoil the ending of a movie?',
  'Who is most likely to rewatch a series for the fifth time?',
  'Who covers their eyes during horror movies?',
  'Which of you takes the longest to pick a movie for movie night?',
  'Who knows the most movie quotes?',
  'Who is most likely to watch reality TV and never tell anyone?',
  'Who is most likely to have skipped an episode and only noticed later?',
  'Who is most likely to be right at the front at a concert?',
  'Which of you has the most unusual taste in music?',
  'Who does the best cartoon character voices?',
  'Who is most likely to start listening to Christmas music in November?',
  'Who is most likely to still read a printed newspaper?',
  'Who is most likely to become a fan of a small band long before they get famous?',
  'Who is most likely to have half-watched a movie because their phone was more interesting?',
  'Who decorates the Christmas tree the most elaborately?',
  'Which of you wraps presents the most beautifully?',
  'Who is most likely to wear the most elaborate Halloween costume?',
  'Who eats the most chocolate bunnies at Easter?',
  'Who is most likely to have regifted a present?',
  "Who is the first to get tired on New Year's Eve?",
  'Who is most likely to wear the same costume to Carnival every year?',
  'Which of you gets the most excited about the first snow?',
  "Who is most likely to write down New Year's resolutions and actually keep them?",
  'Who is most likely to still have Christmas decorations up in February?',
  'Who is most likely to eat nothing but pumpkin dishes all fall?',
  'Who was most likely the kid who always raised their hand in class?',
  'Which of you had the most stuffed animals as a kid?',
  'Who is most likely to still have their elementary school report cards?',
  'Who is most likely to still climb around on a playground today?',
  'Who was most likely never found when playing hide-and-seek as a kid?',
  'Which of you learned to ride a bike the latest?',
  'Who is most likely to have done their homework on the bus?',
  'Who is most likely to still order their favorite childhood meal today?',
  'Which of you has the worst throwing technique in ball games?',
  'Who yells at the referee the loudest when watching soccer on TV?',
  'Who is most likely to have gotten sore muscles from climbing stairs?',
  'Who talks the most while jogging?',
  'Who is most likely to keep playing ping-pong until everyone else gives up?',
  'Who would most likely win a sack race?',
  'Who has the most notes full of random thoughts on their phone?',
  'Which of you is most likely to read the entire medicine leaflet?',
  'Who is most likely to sleep with socks on?',
  'Who is most likely to turn a quick nap into three hours of sleep?',
  'Who is most likely to have walked into a room and instantly forgotten why?',
  'Which of you can whistle the best?',
  'Who is most likely to count the steps while walking up the stairs?',
  'Who is most likely to keep a diary?',
  'Who is most likely to have hidden something and then forgotten the hiding spot?',
  'Which of you is most likely to chew on their pen?',
  'Who cracks their knuckles most often?',
  'Who is most likely to collect and file every single receipt?',
  "Who is most likely to have ordered a package and forgotten what's inside?",
  'Who is most likely to try a new flavor every time at the ice cream shop?',
  'Who is most likely to wear sunglasses even when it is cloudy?',
  'Who is wearing the most colorful socks today?',
  'Who is most likely to have bought something just because of the pretty packaging?',
  'Who is most likely to search the entire supermarket instead of asking for help?',
  'Who always splits the restaurant bill down to the last cent?',
  'Which of you would most want a selfie with a celebrity?',
  'Who loves peeking into lit windows on evening walks?',
  'Who is most likely to talk to the TV?',
  'Which of you is most likely to miss the doorbell because the music is too loud?',
  'Who drinks the least water in a day?',
  'Who is most likely to have bought way too much food while shopping hungry?',
  'Who keeps stopping on walks to take photos of things?',
  'Which of you would enjoy a day as a tourist in their own city the most?',
];
