export const partyQuestionsEn: string[] = [
  'Who is most likely to fall asleep on the couch at a party?',
  'Which of you is the first to dance when their favorite song comes on?',
  'Who is the one who has already had too much to drink at the pregame?',
  'Who is most likely to go get a kebab at 4 a.m.?',
  'Which of you likes to vanish from parties without saying goodbye?',
  'Who is most likely to have lost their phone in a club?',
  'Who is most likely to be the last one to leave the party?',
  'Which of you always takes over the music at every party?',
  'Who is most likely to make breakfast for everyone the next morning?',
  'Who is most likely to lose track of their own tent at a festival?',
  'Which of you has the worst hangover after an all-nighter?',
  'Who is most likely to have danced on a table?',
  'Which of you always orders one more round of shots when everyone wants to leave?',
  'Who is the person who makes new friends at every party?',
  'Who is most likely to never leave the kitchen at a house party?',
  'Who is most likely to have fallen asleep in a taxi?',
  'Which of you knows every word to every party song?',
  'Who is most likely to throw a spontaneous party at their place?',
  'Who is most likely to never lose at beer pong?',
  'Which of you tells the longest stories when drunk?',
  'Who is most likely to have blacked out?',
  'Which of you sends the most embarrassing texts after a party?',
  'Who is the one who refuses to give up the mic at karaoke?',
  'Who is most likely to say "just one drink" and then stay until morning?',
  'Which of you always stays sober to drive and picks everyone up?',
  'Who is most likely to have missed the last train home?',
  'Who is most likely to become friends with the DJ?',
  'Which of you has the best moves on the dance floor?',
  'Who is most likely to swear off drinking forever the morning after?',
  'Who is most likely to invent a drinking game?',
  "Who is most likely to have made it home in someone else's clothes?",
  "Which of you ends up sleeping on someone else's floor after every party?",
  'Who is most likely to go three days without showering at a festival?',
  'Who is the one who takes the best photos at every party?',
  'Who is most likely to link arms and toast to eternal friendship with strangers at a party?',
  'Who is most likely to have slept through a birthday party?',
  'Who is most likely to suddenly get very philosophical when drunk?',
  'Who is most likely to spontaneously drive to another city at midnight?',
  'Who is most likely to have spilled a drink on someone?',
  'Who is most likely to buy a round for everyone at the bar?',
  'Who is the one who dances with everyone after just two beers?',
  'Who is most likely to still be going strong at the afterparty?',
  'Who is most likely to have cried at a party?',
  'Which of you is the biggest lightweight but drinks the most?',
  'Which of you has lost their keys at a party?',
  'Who is most likely to show up to a theme party in the most elaborate costume?',
  'Who is most likely to have annoyed the neighbors with a party?',
  'Which of you remembers every detail the next morning?',
  'Who is most likely to party until sunrise?',
  'Which of you brings the worst drinks to a party?',
  'Who is most likely to show up late to the pregame?',
  'Which of you is most likely to start singing on the way home?',
  'Who is most likely to start a conga line?',
  'Who is most likely to have crashed a party with friends?',
  'Which of you always looks after the drunk people at parties?',
  'Who is most likely to chat for hours in the club bathroom?',
  'Who is the one who needs a hair of the dog after a night out?',
  'Who is most likely to go completely wild at a bachelor or bachelorette party?',
  'Who is most likely to have talked to the police at a party?',
  'Which of you has had the longest party night ever?',
  'Who is most likely to end up on a boozy beach party holiday in Mallorca?',
  'Who is most likely to still smell like smoke and beer on Sunday?',
  "Which of you is most likely to organize a New Year's Eve party?",
  'Who is most likely to declare their love to everyone after three drinks?',
  'Who is most likely to have missed a flight after a night out?',
  'Which of you always says yes and then never shows up to the party?',
  'Who is most likely to drag out the pregame so long that nobody makes it to the club?',
  'Who is most likely to bring nothing but a bag of chips to the pregame?',
  'Which of you mixes the wildest drinks at the pregame?',
  'Who is most likely to have met the neighbors at a pregame because it got too loud?',
  'Who is most likely to just keep the pregame going on the train?',
  'Which of you always has a flask in their pocket?',
  'Who is most likely to buy the cheapest wine at the corner store?',
  'Which of you knows every corner store in town by name?',
  'Who is most likely to have broken something valuable during a pregame?',
  'Which of you takes the longest in the bathroom before heading out?',
  'Who is most likely to tell the bouncer their whole life story?',
  'Which of you gets past every bouncer, no matter how packed it is?',
  'Who is most likely to wait in line for an hour and then get turned away?',
  'Which of you loves dancing right next to the speaker in a club?',
  'Who is most likely to wear earplugs in a club?',
  'Who is most likely to have lost their coat check ticket?',
  'Which of you is most likely to spend the whole night in the smoking area?',
  'Who is most likely to have asked a club DJ for a cheesy old pop song?',
  'Who is still on the dance floor when the club lights come on?',
  'Who is most likely to know the way to the next afterparty when the club closes?',
  'Who is most likely to have stayed at an afterparty until noon?',
  'Which of you waits at the bar for half an hour and then orders the wrong thing?',
  'Who is most likely to pay twenty bucks for a mixed drink at a club without blinking?',
  'Which of you always gets served first at a crowded bar?',
  'Who is most likely to have lost the group in a club and kept partying alone?',
  'Which of you can dance the longest without taking a break?',
  'Who is most likely to get turned away at the door for wearing sneakers?',
  'Who is most likely to have taken their shoes off in a club?',
  'Which of you is most likely to go to a club alone?',
  'Who is most likely to stand in line at Berghain in Berlin and hope for the best?',
  'Who is most likely to have partied through an entire festival in the rain?',
  'Which of you brings nothing but canned ravioli and beer to a festival?',
  'Who is most likely to miss every band at a festival because the campsite is more fun?',
  'Who is most likely to have kept a festival wristband on for weeks?',
  'Which of you sets up the best gazebo at a festival?',
  'Who is most likely to start a water fight with the neighboring camp at a festival?',
  "Who is most likely to have woken up in a stranger's tent at a festival?",
  'Which of you always stands in the front row at concerts?',
  'Who is most likely to start a mosh pit at a festival?',
  'Who is most likely to have lost a shoe while crowd-surfing?',
  'Who is most likely to pull a wagon full of beer across the whole campsite?',
  'Who is most likely to have left their festival ticket at home?',
  'Who is most likely to wear glitter at a festival and still find it days later?',
  'Who is most likely to have left a festival early?',
  'Which of you sleeps the least at a festival?',
  'Who is most likely to bring a megaphone to a festival?',
  'Who is most likely to have lost their car in the festival parking lot?',
  "Who is most likely to buy next year's ticket right after the festival?",
  'Which of you has the best hangover cure?',
  'Who is most likely to spend an entire hangover day in bed watching TV shows?',
  'Which of you hides a hangover best the next morning?',
  'Who is most likely to show up hungover to brunch and pretend everything is fine?',
  'Who is most likely to have taken an exam hungover?',
  'Which of you complains the loudest about their hangover?',
  'Who is most likely to scroll through their phone photos the morning after to piece the night together?',
  'Which of you is simply unreachable on the Sunday after a party?',
  'Who is most likely to have checked their bank account in horror after a night out?',
  'Who is most likely to get talked into partying again on hangover day?',
  'Which of you has survived a family dinner while hungover?',
  'Who is most likely to make up the meanest rules in Kings Cup?',
  'Which of you loses every drinking game, no matter which one?',
  'Who is most likely to have cheated at an outdoor drinking game?',
  'Who is most likely to change the rules of a drinking game halfway through?',
  'Which of you is the most honest at Never Have I Ever?',
  'Who is most likely to take a drinking game as seriously as a World Cup final?',
  'Which of you can chug a beer the fastest?',
  'Who is most likely to secretly drink water during a drinking game?',
  "Who is most likely to have bluffed at Liar's Dice and lost?",
  'Which of you knows the most drinking games by heart?',
  'Who is most likely to play beer pong with wine?',
  'Who is most likely to have suggested a drinking game and been the first one out?',
  'Which of you has the best poker face in drinking games?',
  'Who is most likely to practice their own throwing technique for beer pong?',
  'Which of you needs at least three drinks before getting on the karaoke stage?',
  'Who is most likely to have tried a karaoke song in Japanese?',
  'Who is most likely to sing a karaoke duet with a complete stranger?',
  'Which of you has a go-to karaoke song they sing every single time?',
  'Who is most likely to sing totally out of tune at karaoke but with full confidence?',
  'Which of you is most likely to add choreography to a karaoke song?',
  'Who is most likely to have gotten applause from the whole bar at karaoke?',
  'Which of you always manages to get out of karaoke?',
  'Who is most likely to sing all of Bohemian Rhapsody alone?',
  'Who is most likely to buy hot dogs at a gas station at 5 a.m.?',
  'Who is most likely to have made a lifelong friend at a kebab shop in the middle of the night?',
  'Who is most likely to cook pasta after a party and fall asleep while it boils?',
  'Who is most likely to have dropped their kebab on the way home?',
  'Who is most likely to declare a greasy 3 a.m. snack the highlight of the night?',
  "Which of you raids the host's fridge after every party?",
  'Who is most likely to wait outside the bakery until the first fresh bread comes out at 6 a.m.?',
  'Who is most likely to walk home after a night out even though it takes an hour?',
  'Who is most likely to have sent a taxi to the wrong address?',
  'Which of you always ends up on the night bus after partying?',
  'Who is most likely to fall asleep on the train and wake up at the last stop?',
  'Who is most likely to find a second party on the way home?',
  'Who is most likely to have left their bike outside a club and forgotten about it?',
  'Who is most likely to get the taxi driver to sing along?',
  'Who is most likely to throw a party at their shared flat without telling their roommates?',
  'Who is most likely to have thrown a party where three times as many people showed up as were invited?',
  'Who is most likely to pay more attention to the pets than the guests at a party?',
  'Who is most likely to force all their guests to use coasters at their own party?',
  'Who is most likely to fill the bathtub with ice and beer at a house party?',
  'Who is most likely to invite people to a party and then show up late themselves?',
  'Who is most likely to have met someone at a party that nobody had invited?',
  'Which of you cleans the most thoroughly the day after a party?',
  'Who is most likely to turn their whole living room into a dance floor for a house party?',
  'Who is most likely to find someone still asleep in the bathtub the morning after their own party?',
  'Who is most likely to throw a garden party with string lights and a fire pit?',
  'Who is most likely to have found things nobody owns while cleaning up after a party?',
  'Which of you is most likely to throw a house party with a dress code and guest list like a club?',
  'Who is most likely to give a spontaneous speech at a wedding?',
  'Which of you is most likely to catch the bouquet at a wedding?',
  'Who is most likely to have drunk too fast at a wedding champagne reception?',
  'Who is most likely to storm the dance floor at a wedding before the couple has even had their first dance?',
  'Which of you cries at every wedding as soon as the ceremony starts?',
  "Who is most likely to dance with the couple's grandparents at a wedding?",
  'Who is most likely to have been first in line at the wedding buffet?',
  'Which of you misses the midnight snack at weddings because the dance floor is more important?',
  'Who is most likely to have secretly swapped the place cards at a wedding?',
  'Which of you organizes the funniest games for a wedding?',
  'Who is most likely to spend half the night at the photo booth at a wedding?',
  'Who is most likely to have joined in a prank kidnapping of the bride at a wedding?',
  'Who is most likely to party at a wedding until breakfast?',
  'Who is most likely to have the most embarrassing shirts printed for a bachelor or bachelorette party?',
  'Which of you is most likely to sell shots from a tray at a bachelor or bachelorette party?',
  'Who is most likely to have had to walk through downtown in a costume at a bachelor or bachelorette party?',
  'Which of you makes sure the guest of honor survives the bachelor or bachelorette party?',
  'Who is most likely to have talked strangers into joining a bachelor or bachelorette party?',
  'Which of you would plan a bachelor or bachelorette party with a schedule down to the minute and a spreadsheet?',
  'Who is most likely to be the first to tap out at a bachelor or bachelorette party?',
  'Who is most likely to write a song about the guest of honor for a bachelor or bachelorette party?',
  'Who is most likely to stand on the beer bench at Oktoberfest and sing along?',
  'Which of you can drink the most liters of beer in one day at Oktoberfest?',
  'Who is most likely to have lost their seat in the tent at Oktoberfest?',
  'Who is most likely to come home from Oktoberfest with a gingerbread heart?',
  'Who is most likely to still ride the swing carousel after three liters of beer?',
  'Who is most likely to have queued outside a beer tent first thing in the morning?',
  'Which of you knows every song played in the beer tent?',
  'Who is most likely to clink glasses with a table full of strangers at Oktoberfest?',
  'Who is most likely to have tried to take a beer stein home as a souvenir?',
  'Who is most likely to call the bumper cars the highlight of a night at the fair?',
  "Who is most likely to miss the New Year's countdown because they're in the bathroom?",
  "Which of you brings the most fireworks on New Year's Eve?",
  "Who is most likely to have lost the group at midnight on New Year's Eve?",
  "Who is most likely to be asleep by ten past midnight on New Year's Eve?",
  "Which of you makes the most resolutions on New Year's Eve and breaks them on January 1st?",
  "Who is most likely to have paid double entry at a club on New Year's Eve?",
  "Who is most likely to go to three parties in one night on New Year's Eve?",
  "Who is most likely to have popped the champagne way too early on New Year's Eve?",
  'Who is most likely to know every line of a classic holiday movie by heart?',
  'Who is most likely to drink sangria out of a bucket on vacation?',
  'Which of you knows every cheesy holiday party anthem by heart?',
  'Who is most likely to book a boat party on vacation?',
  'Which of you loves flying abroad for a weekend just to party?',
  'Who is most likely to forget the name of their hotel at night on vacation?',
  'Who is most likely to have spent a whole night on the beach on vacation?',
  'Which of you comes back from a party vacation needing more rest than before?',
  'Who is most likely to have started partying on the plane?',
  'Which of you would win the cannonball contest at the pool on vacation?',
  'Who is most likely to have bought a souvenir they have no memory of buying?',
  'Which of you is most likely to try a different club every night in Ibiza?',
  'Who is most likely to go partying in Prague and see nothing of the city?',
  'Who is most likely to have joined a pub crawl with strangers on vacation?',
  'Who is most likely to set an alarm for everyone on a group trip even though nobody wants to get up?',
  'Who is most likely to turn the vacation rental pool into a party zone at night?',
  'Who is most likely to spend more time in the ski lodge than on the slopes?',
  'Who is most likely to get the whole bar singing along at a pub?',
  'Which of you has a local bar where everyone knows their name?',
  'Who is most likely to order something at the bar that nobody can pronounce?',
  'Which of you is most likely to go out partying on a random Tuesday?',
  'Which of you always drinks the same thing, no matter where?',
  'Who is most likely to challenge the next table to a game of foosball at a bar?',
  'Who is most likely to have been stuck with the bill for everyone because the rest had already left?',
  'Who is most likely to work through an entire cocktail menu from top to bottom?',
  'Which of you personally knows the bar staff of half the city?',
  'Who is most likely to go bar hopping with a group of strangers?',
  'Who is most likely to have challenged the regulars to a game of darts at a pub?',
  'Which of you is most likely to turn a wine tasting into a drinking binge?',
  'Who is most likely to have discussed the meaning of life with strangers at a bar until closing time?',
  'Which of you always wants to move on to another place at midnight?',
  'Who is most likely to have left a bar together with the staff?',
  'Which of you is most likely to end a night out at a hookah lounge?',
  'Who is most likely to party through an entire week of Carnival in Cologne?',
  'Which of you can sing along to the most Carnival songs while swaying arm in arm?',
  'Who is most likely to have brought homemade liqueur to a party?',
  'Who is most likely to make a punch that knocks everyone out?',
  'Which of you has the weirdest favorite shot?',
  'Who is most likely to suggest Jägermeister for every round?',
  'Who is most likely to have knocked back tequila without salt and lime?',
  'Which of you would stay sober at a party and still party the hardest?',
  'Who is most likely to take a cocktail class and then annoy everyone about it?',
  'Who is most likely to have opened a bottle of champagne with a saber?',
  'Which of you can open a beer bottle with anything except a bottle opener?',
  'Who is most likely to label their own drinks in the fridge at a party?',
  'Which of you is most likely to bring back a liquor from vacation that nobody wants to drink?',
  'Who is most likely to buy a round of shots just to end an argument?',
  'Which of you has shaken a bottle of champagne and sprayed everyone?',
  'Who is most likely to suddenly try breakdancing at a party?',
  'Which of you suddenly speaks a foreign language fluently after a few drinks?',
  'Who is most likely to have requested a song from the DJ and then missed it?',
  'Who is most likely to give a speech about friendship in the middle of a party?',
  'Which of you films everything at parties for their story?',
  'Who is most likely to lose a bet at a party and have to do something crazy?',
  "Who is most likely to act like it's their own place at a stranger's party?",
  'Which of you is most likely to start a political debate at a party?',
  'Who is most likely to have set off a confetti cannon inside an apartment?',
  'Which of you is most likely to call their parents when drunk?',
  'Who is most likely to turn off the lights and fire up the disco ball at a party?',
  'Who is most likely to have won a dance contest at a party?',
  'Which of you shows up to every party with a plus-one nobody knows?',
  'Who is most likely to have ordered something online while drunk and forgotten about it the next day?',
  'Who is most likely to turn on the TV at a party because the game is on?',
  'Who is most likely to have danced with a celebrity at a party?',
  'Which of you wears sunglasses at parties, even indoors?',
  'Who is most likely to have taken a party game so seriously that it caused a fight?',
  'Which of you has the most party photos with their eyes closed?',
  'Who is most likely to have partied all night without knowing whose party it was?',
  'Which of you is most likely to throw a foam party in the backyard?',
  'Who is most likely to break out a guitar and play campfire songs at a party?',
  'Who is most likely to have shown up to a theme party without a costume and regretted it?',
  'Which of you mixes up their glass at least once at every party?',
  'Who is most likely to have traveled a long way just for a single party?',
  'Who is most likely to celebrate their 30th birthday with a huge bash?',
  'Who is most likely to have accidentally spoiled a surprise party?',
  'Which of you is most likely to save a dying party with cheesy party hits?',
  'Who is most likely to still want to party at a high school graduation party today?',
  'Which of you always has a phone charger for everyone at parties?',
  'Who is most likely to entertain people at a party with magic tricks?',
  'Which of you dances with their eyes closed and forgets everything around them?',
  'Who is most likely to have started a pillow fight at a party?',
  'Who is most likely to have rescued a hedgehog on the way home from a party?',
  'Which of you parties the longest at street festivals?',
  'Who is most likely to show up to a rave in glitter pants?',
  'Who is most likely to drag out a barbecue until late at night?',
  'Who is most likely to belt out cheesy party anthems at the top of their lungs in a beer tent?',
];
