export const roastQuestionsEn: string[] = [
  'Who is most likely to send a ten-minute voice message that could have been one sentence?',
  'Which of you is guaranteed to be late, even to your own birthday party?',
  'Who has most likely killed a plant that was supposed to be impossible to kill?',
  'Who always takes the longest to order at a restaurant?',
  'Who is most likely to quit a board game just because they are losing?',
  'Which of you takes three days to reply to messages but is always online?',
  'Who has the most questionable taste in music in this group?',
  'Who tells the same story for the fifth time without noticing?',
  'Who is most likely to try parking three times and still end up crooked?',
  'Which of you has the most unread emails in their inbox?',
  'Who is the worst at keeping a secret?',
  'Who is most likely to insist on winning an argument even when the facts are clearly against them?',
  'Who has most likely managed to burn pasta water?',
  'Which of you says "almost there" when they haven\'t even put their shoes on yet?',
  'Who asks five minutes into every movie who that person was again?',
  'Who is most likely to drop their phone in the toilet?',
  'Who has the messiest home of everyone here?',
  'Which of you borrows things and never gives them back?',
  'Who is most likely to shout out the wrong answer at a quiz with total confidence?',
  'Who is most likely still wearing clothes from their school days?',
  'Who is the biggest know-it-all in this group?',
  'Who is most likely to spam the group chat with memes nobody finds funny?',
  'Which of you makes the most typos and never fixes them?',
  'Who is most likely to forget their passport when going on vacation?',
  'Who is the worst cook but still thinks they are a pro?',
  'Which of you has the most embarrassing ringtone or alarm sound?',
  'Who is most likely to ask how much further it is ten minutes into a hike?',
  'Who has most likely waved back at someone who was actually waving at someone else?',
  'Who talks the most during a TV show night?',
  'Who never has cash on them when it actually matters?',
  'Who has the worst sense of direction and gets lost even with GPS?',
  'Which of you buys workout clothes but only wears them on the couch?',
  'Who is most likely to sign up for a gym membership and never go?',
  "Who is most likely to spoil the ending of a show and act like it's no big deal?",
  'Who gets offended the fastest at a little joke?',
  'Who is most likely to dance completely off beat without noticing?',
  'Which of you has the most annoying laugh?',
  'Who is most likely to leave a one-star review because the fries were cold?',
  'Who has the worst excuses for canceling plans?',
  'Who says "I\'m not hungry" and then eats off everyone\'s plate?',
  'Which of you starts a new hobby every year and gives up after two weeks?',
  'Who has most likely lost their own car in a parking lot?',
  'Who looks at their phone the most during meals?',
  'Who is most likely to completely wing a presentation and claim it was on purpose?',
  'Which of you has the longest list of shows they started and never finished?',
  'Who is the sorest loser in this group?',
  'Who is most likely to get into an argument with a voice assistant?',
  'Which of you oversleeps the most, despite having five alarms?',
  'Who is most likely to struggle with every single item at the self-checkout?',
  'Who has most likely forgotten an appointment and only realized it the next day?',
  'Who always wants to tell you something "real quick" and then talks for an hour?',
  'Who is most likely to be the first to give up in an escape room?',
  'Which of you has the most chaotic backpack or the messiest bag?',
  'Who is most likely to cancel plans because the couch is just too comfy?',
  'Who has the worst memory for names?',
  'Who is most likely to post a selfie with a way too deep caption?',
  'Who has most likely watered a plastic plant?',
  'Who gives the worst advice with the most confidence?',
  'Who is most likely to go shopping with a list and still forget the most important thing?',
  'Who seems to start every single sentence with "actually"?',
  'Who is most likely to pick a karaoke song that is way too high for them?',
  'Who has the most open browser tabs and no idea why any of them are open?',
  'Which of you joins in on book discussions after only watching the movie?',
  'Who is most likely to build a shelf and have screws left over at the end?',
  "Who has most likely laughed out loud at a joke they didn't get?",
  'Who is the worst at wrapping a present neatly?',
  'Who is most likely to send back food that came exactly as they ordered it?',
  'Which of you has the loudest phone calls on the train?',
  'Who is most likely to bring up exactly the wrong topic during an awkward silence?',
  'Who secretly googles under the table and passes it off as general knowledge?',
  'Whose phone battery is always at two percent?',
  'Who is most likely to leave for the airport when boarding has already started?',
  'Who is most likely to show up at the right place, just on the wrong day?',
  'Who is most likely to press the elevator button five times as if that makes it faster?',
  'Who has most likely missed a train because they just had to grab a coffee first?',
  'Who always says "we\'ll see" about plans when they really mean no?',
  'Which of you only remembers birthdays thanks to social media?',
  'Who is the worst at meeting deadlines but always has a story ready?',
  'Who takes the longest in the bathroom in the morning and blames the water pressure?',
  'Who is most likely to plan their move and realize the day before that they have no boxes?',
  'Who always needs to use the bathroom right when everyone is already at the door?',
  'Who is most likely to experience a whole concert through their phone screen?',
  'Who has to photograph every meal before anyone is allowed to start eating?',
  'Who is most likely to forget a password they created five minutes ago?',
  'Who replies to serious messages with nothing but a thumbs-up?',
  'Who has most likely walked into a lamppost because their phone was more interesting?',
  'Who is most likely to shut down a computer by just pulling the plug?',
  'Which of you asks someone else for help with every tech problem instead of trying first?',
  'Who keeps postponing every update until nothing works anymore?',
  'Who talks for minutes on a video call while still muted?',
  "Who is most likely to look for their phone while they're on a call with it?",
  'Who is most likely to serve spaghetti with ketchup as a gourmet dish?',
  'Which of you has set off the smoke alarm while cooking more than everyone else combined?',
  'Who is most likely to put a frozen pizza in the oven with the plastic still on?',
  'Who has a fridge full of food so old it has developed a life of its own?',
  'Who is most likely to order the same thing every time, no matter how big the menu is?',
  'Which of you complains that food is too spicy when there is barely a hint of pepper?',
  'Who is guaranteed to bring only napkins to a picnic?',
  'Which of you is the loudest eater?',
  'Who has most likely mixed up sugar and salt and served the cake anyway?',
  'Which of you says "I don\'t care where we eat" and then shoots down every suggestion?',
  'Who leaves dishes soaking for days until they supposedly clean themselves?',
  'Which of you buys vegetables to eat healthier and throws them out a week later?',
  'Who is most likely to put a metal bowl in the microwave and be surprised by the fireworks?',
  'Who burns everything on the grill and calls it "smoky flavor"?',
  'Who is most likely to unwrap gifts carefully to reuse the wrapping paper next year?',
  'Who is most likely to drive twenty minutes to save ten cents on gas?',
  'Which of you tips the least and still complains about the service?',
  'Who is most likely to treat the free samples at the supermarket as lunch?',
  'Whose gifts look suspiciously like free promotional giveaways?',
  'Who most likely still has subscriptions running that nobody remembers?',
  'Who is most likely to share a streaming account with five strangers just to save two bucks?',
  'Which of you buys things nobody needs just because they were on sale?',
  'Who is most likely to regift a present and leave the old card inside?',
  'Who is most likely to take sugar packets and ketchup home from restaurants?',
  'Which of you always happens to be in the bathroom right when the check arrives?',
  'Who is most likely to try to use a long-expired coupon and then argue about it?',
  'Who only pays their share of a group gift after being asked three times?',
  'Which of you drives so slowly that cyclists overtake them?',
  'Who is most likely to go around a roundabout three times because they missed the exit?',
  'Who has most likely left the turn signal on for an entire drive?',
  'Who is the passenger who keeps hitting an imaginary brake and commenting on everything?',
  'Which of you rotates the map on their phone until nobody knows where north is anymore?',
  'Who is most likely to pull up on the wrong side of the gas pump every single time?',
  'Which of you rides a bike like they own the whole road?',
  'Who has most likely gotten a parking ticket while "just running in for a second"?',
  'Who is most likely to suggest a shortcut that takes an hour longer?',
  'Who takes over the music in the car and lets nobody else touch it?',
  "Who honks the most, even when it doesn't help at all?",
  'Who is most likely to return a rental car with a dent and play innocent?',
  'Which of you always takes up two seats on the bus, one for them and one for their bag?',
  'Who is most likely to never leave the middle lane on the highway?',
  'Which of you turns a paper cut into a tragedy in three acts?',
  'Who posts cryptic status updates just so everyone will ask what happened?',
  'Which of you storms out of the room dramatically, hoping someone will follow?',
  'Who gets crankier than a toddler when they are hungry?',
  "Who is most likely to sigh so loudly that everyone has to ask what's wrong?",
  'Who starts every story with "You won\'t believe what happened to me"?',
  'Who is most likely to treat a wasp at the table like it is a bear?',
  'Which of you exaggerates stories so much that nobody knows the real version anymore?',
  'Who writes long messages with paragraphs and quotes after an argument?',
  'Who is most likely to say "I don\'t want to talk about it" and then talk about it for an hour?',
  'Who is most likely to loudly declare the end of civilization when the Wi-Fi is slow?',
  "Which of you has the most creative excuse for why the trash hasn't been taken out yet?",
  'Who is most likely to claim their phone was on silent when it was right next to them?',
  'Who offers to help with a move but only shows up once everything has been carried?',
  'Who is most likely to do a task so badly on purpose that nobody ever asks them again?',
  'Which of you says "I\'ll do it tomorrow" and means next year?',
  'Who stays in bed the longest on weekends and calls it recovery?',
  'Who has most likely made up a traffic jam to explain being late?',
  'Who is most likely to freeze for an hour rather than get up and grab a blanket?',
  'Which of you piles clothes on a chair until the chair disappears underneath?',
  'Who is most likely to contribute nothing to a group project but their name?',
  'Who suddenly has an urgent phone call the moment it is time to do the dishes?',
  'Who is most likely to use the same excuse so often that everyone can say it along with them?',
  'Who most likely still has boxes from their last move that were never unpacked?',
  'Who is most likely to only dust where guests will actually look?',
  'Who always says "I\'m so busy" and then binge-watches shows all day?',
  'Who is most likely to wear clean laundry straight out of the basket for weeks?',
  'Which of you wears socks with sandals and defends it as a trend?',
  'Who is most likely to show up to a wedding in a hoodie?',
  'Who has the most clothes in their closet with the tags still on?',
  'Who follows every fashion trend, just always two years too late?',
  'Who is most likely to proudly wear a shirt with an embarrassing slogan on it?',
  'Who is most likely to wear sunglasses indoors and think it looks cool?',
  'Whose favorite sweater now has more holes than fabric?',
  'Who is most likely to go to the supermarket in their pajamas?',
  'Who is most likely to use a profile picture that is at least ten years old?',
  'Which of you has a drawer full of cables for devices that no longer exist?',
  "Who has the worst taste in gifts and doesn't even realize it?",
  'Who is most likely to buy home decor that says "Live Laugh Love"?',
  'Which of you always wears the same pants and claims they own several identical pairs?',
  'Which of you sings along loudly in the car without knowing a single lyric correctly?',
  'Who is most likely to play the same playlist at every get-together?',
  'Who secretly listens to cheesy pop music and pretends it is ironic?',
  'Who says the original version was better about every song?',
  'Who is most likely to keep their yearly music app recap a secret?',
  'Which of you constantly hums without noticing?',
  'Who is most likely to like a band only because nobody has heard of them yet?',
  'Who whistles the most out of tune and still never stops?',
  'Who sings a catchy song until everyone else has it stuck in their head too?',
  'Who is most likely to go to a concert and only know the one famous song?',
  'Who is most likely to perform an opera in the shower that the whole building can hear?',
  'Which of you tells everyone, unasked, why their favorite music is actually bad?',
  'Who is most likely to start a hobby just for the expensive gear?',
  'Who has a bike at home whose tires have been flat for years?',
  'Who is most likely to give everyone breathing tips after a single yoga class?',
  "Which of you photographs every sunset like it's the last one ever?",
  'Who becomes an expert on a topic after watching a single documentary?',
  "Which of you corrects everyone else's grammar at every opportunity?",
  'Who is most likely to interrupt a story to tell their own, better one?',
  "Who explains every joke until it isn't funny anymore?",
  'Who is most likely to cite studies in every argument that nobody has ever seen?',
  'Who has an opinion on every topic, even without the slightest clue?',
  'Who is most likely to say "I told you so" when they never said it?',
  "Who loves talking about themselves most, even when it's someone else's moment?",
  'Who is most likely to explain the rules of a game for so long that nobody wants to play anymore?',
  'Who keeps losing the thread while telling a story and ends up somewhere completely different?',
  'Who is most likely to explain to a professional how to do their own job?',
  'Who whispers the loudest?',
  'Which of you uses fancy words the most without quite knowing what they mean?',
  'Who is most likely to make an argument worse with "I\'m just saying"?',
  'Who is the worst listener and then asks for everything to be repeated?',
  'Who is most likely to share a fun fact that is provably wrong?',
  'Who is most likely to cheat at a crossword and still not finish it?',
  'Who is most likely to load the dishwasher completely wrong and call it a system?',
  'Who has the dirtiest car, with crumbs from several years?',
  'Who is most likely to leave passive-aggressive notes in a shared kitchen?',
  'Which of you owns more scented candles than furniture?',
  'Who is most likely to wash whites and colors together, over and over again?',
  'Who leaves the empty toilet paper roll hanging the longest?',
  'Who is most likely to name their robot vacuum and treat it like a pet?',
  'Which of you shoves everything into the closet so the place looks tidy?',
  'Who is most likely to hang a picture and drill five holes too many?',
  'Who is most likely to put an almost empty milk carton back in the fridge instead of tossing it?',
  'Who opens the fridge, stares into it, and closes it again without taking anything?',
  'Who is most likely to ignore a dripping faucet for years?',
  'Which of you only returns empty bottles once they block half the hallway?',
  'Who is most likely to start the washing machine and forget the laundry in it for three days?',
  'Who has never voluntarily made their bed?',
  'Who is most likely to use a towel until it can stand up on its own?',
  'Which of you decorates so much for Christmas that the neighbors need sunglasses?',
  'Who keeps the Christmas tree up the longest, well into spring?',
  'Who keeps their shoes on at every visit, no matter how often they are asked?',
  'Which of you writes "see below" in emails when there is nothing below?',
  'Who is most likely to nod along in a meeting without understanding a single word?',
  'Who ends every email with three exclamation marks?',
  'Who is most likely to accidentally hit "Reply all" and email the whole company?',
  'Who had the most ridiculous excuses for forgotten homework back in school?',
  'Who only dresses properly from the waist up when working from home?',
  'Which of you pretends to be busy as soon as someone important walks by?',
  'Who is most likely to confidently write an entire exam about the wrong topic?',
  'Which of you turns every little thing into a meeting?',
  'Who is most likely to go to the company party just for the free buffet?',
  'Who lists "team player" on their resume but never answers the phone?',
  'Who is most likely to stuff a presentation full of colorful effects and flashy transitions?',
  'Who is most likely to dodge the ball in volleyball instead of playing it?',
  'Which of you makes up new rules during card games that always happen to help them?',
  'Who always blames the controller when playing video games?',
  'Which of you yells at the TV during a game as if the team could hear them?',
  'Who is most likely to make up words in a word game and insist they are real?',
  'Who is the worst at keeping a poker face?',
  'Which of you secretly counts one extra space when rolling the dice?',
  'Who is most likely to throw every bowling ball in the gutter and blame the lane?',
  'Who is most likely to spend half an hour thinking about their move at game night?',
  'Which of you still talks about that one ping-pong win years later?',
  'Who is most likely to start running before the starting signal in a race?',
  'Who has the worst ball skills but somehow always hits the lamp?',
  "Which of you can't even play rock, paper, scissors fairly?",
  "Who is most likely to get caught right away in Werewolf because they can't stop grinning?",
  'Who keeps explaining during Uno that they play it completely differently at home?',
  'Which of you asks who else is coming before even saying yes?',
  'Who is most likely to never vote in a group chat poll and then complain?',
  'Who declares every new acquaintance their favorite person after five minutes?',
  'Who is most likely to give a wedding speech that is all about themselves?',
  'Which of you says goodbye and then stands in the doorway for another hour?',
  'Who is most likely to invite guests over and still not be showered when the doorbell rings?',
  'Who wants to retake every group photo one more time?',
  'Which of you always says "I\'ll bring something" and then shows up empty-handed?',
  'Who is most likely to tell an inside joke that nobody but them understands?',
  'Who is most likely to spread neighborhood gossip faster than the local paper?',
  'Who is the worst at faking excitement about a gift?',
  'Who is most likely to spot someone they know at the supermarket and hide behind a shelf?',
  'Which of you never gets past the weather when making small talk?',
  'Who is most likely to plan a surprise party and forget to invite the guest of honor?',
  'Who falls asleep during movie night and then wants to know how it ended?',
  'Which of you packs three suitcases for a weekend trip?',
  'Who is most likely to stay in the hotel all vacation and still rave about the culture?',
  'Who just speaks their own language louder abroad so everyone will understand?',
  'Who is most likely to reserve a beach chair with a towel at seven in the morning?',
  'Who is most likely to order only burgers and fries when traveling abroad?',
  'Who comes back from a one-week vacation with a brand-new accent?',
  'Which of you buys souvenirs on vacation that end up in a drawer the moment they get home?',
  'Who is most likely to book the nearest hotel after one night in a tent?',
  'Who has the worst foreign-language skills but talks the most when abroad?',
  'Who is most likely to forget the tent pegs when going camping?',
  'Who takes off their shoes the moment they sit down on a plane?',
  'Which of you talks about nothing else for weeks after every vacation?',
  'Who is most likely to pack up the hotel breakfast buffet for the whole day?',
  'Who is most likely to pull on a door that clearly says "Push"?',
  'Who rustles their snack bag the loudest at the movies?',
  'Who falls asleep five minutes into every car ride and then claims they were awake the whole time?',
  'Which of you snores the loudest and denies it the hardest?',
  'Who is most likely to be searching for their keys, phone, and wallet all at once?',
  'Who is most likely to leave the keys inside and lock themselves out?',
  'Who looks away during the whole horror movie and still wants to join the discussion?',
  'Which of you gives away the ending of movies without asking first?',
  'Who is most likely to have longer conversations with their pet than with people?',
  'Who has most likely ordered a package to their old address?',
  'Which of you comes home with two full grocery bags when only milk was needed?',
  'Who strolls so slowly on walks that everyone has to wait for them?',
  'Who is most likely to start looking for their wallet only after everything has been scanned?',
  'Which of you makes the most dramatic noise when sneezing?',
  'Who is most likely to start a petition because their favorite product got discontinued?',
  "Whose handwriting is so bad that even they can't read it?",
  'Who is most likely to spend four hours at IKEA and only buy tea lights?',
  'Who always picks the slowest line and then complains about it loudly?',
  'Which of you counts down out loud before every photo and still takes it too early?',
  'Who is most likely to argue with a hotline for an hour when the mistake is clearly their own?',
  'Which of you is impossible to talk to in the morning before their first coffee?',
];
