export const sexualQuestionsEn: string[] = [
  'Who has been on dates with two different people on the same day?',
  'Who is most likely to bring up marriage on a first date?',
  'Who here has the most matches on Tinder?',
  'Who is most likely to have said the wrong name in bed?',
  'Who is most likely to end up in bed with their ex again?',
  'Who has forgotten the name of a one-night stand?',
  'Who here flirts the most without even noticing?',
  'Who is most likely to kiss someone from this group tonight?',
  'Who is most likely to have made out in a car?',
  "Who has hooked up with their ex's best friend?",
  'Who is most likely to try an open relationship?',
  'Who is most likely to send a "You up?" text at 3 a.m.?',
  'Who here has had sex in a public place?',
  'Who is most likely to disappear with a guest for an hour at a wedding?',
  'Who is most likely to have ghosted a Tinder date?',
  'Who has laughed so hard while kissing that it completely killed the mood?',
  'Who is most likely to flirt at the gym instead of working out?',
  'Who deletes Tinder most often, only to download it again a week later?',
  'Who secretly had a crush on a teacher back in school?',
  'Who is most likely to try a threesome?',
  'Who here is most likely to sleep with someone on the first date?',
  "Who is most likely to have snuck out of a date's place in the morning?",
  'Who is most likely to accidentally send nudes to the wrong person?',
  'Who has had a vacation fling that nobody was allowed to know about?',
  'Who is most likely to flirt with the bartender to get free drinks?',
  'Who is most likely to make out with two different people at the same party?',
  'Who here has the most embarrassing sex story?',
  'Who is most likely to have gotten a cramp during sex?',
  'Who is most likely to introduce a date to their parents by the second meeting?',
  'Who has kissed someone just to make someone else jealous?',
  'Who is most likely to go to a sex shop with the whole group?',
  'Who has gone through the longest dry spell in bed?',
  'Who is most likely to have made out with a coworker?',
  'Who is most likely to break up with someone via voice message?',
  'Who gets the most flirty DMs from strangers on Instagram?',
  'Who has faked a dead phone battery to leave a date early?',
  "Who is most likely to stalk their ex's Instagram late at night?",
  'Who here has used handcuffs, and not for a Halloween costume?',
  'Who is most likely to talk openly about their own fetish?',
  'Who is most likely to have had a sex toy in their carry-on?',
  'Who is most likely to hook up with their roommate?',
  'Who has had a hickey that was impossible to hide?',
  'Who is most likely to go on Love Island?',
  'Who is most likely to have a playlist just for the bedroom?',
  'Who here has the best pickup line ready to go?',
  'Who is most likely to use a pickup line that totally backfires?',
  'Who is most likely to look for a sugar daddy or sugar mommy?',
  'Who is most likely to have had a not-so-PG dream about someone in this group?',
  'Who is most likely to get a phone number at the club within five minutes?',
  "Who has had a date that didn't end until the next morning?",
  'Who is most likely to fall asleep in the middle of sexting?',
  'Whose neighbors are most likely to complain about the noise from the bedroom?',
  'Who is most likely to have broken a bed during sex?',
  'Who is most likely to use a ten-year-old photo on a dating app?',
  'Who has been on a date with someone at least ten years older?',
  'Who is most likely to make out in a fitting room?',
  'Who has the most exes in this city?',
  'Who is most likely to check out a swingers club just out of curiosity?',
  'Who here has done more than just kiss during spin the bottle?',
  'Who is most likely to have dated two people at once without either of them knowing?',
  'Who is most likely to try to work through the entire Kama Sutra?',
  'Who has had sex in a tent at a festival?',
  'Who is most likely to send the group a rating out of ten after a date?',
  'Who is most likely to be into dirty talk?',
  'Who is most likely to have forgotten their own name while flirting?',
  'Who is most likely to try role-play in the bedroom?',
  'Who has accidentally bitten too hard while kissing?',
  "Who is most likely to make out with a friend's ex?",
  'Who has been caught making out by their parents?',
  'Who is most likely to have slept with someone just because they were a great cook?',
  'Who is most likely to swipe right just because of a dog in the profile pic?',
  'Who here has flirted in a sauna?',
  'Who is most likely to already be a member of the Mile High Club?',
  'Who has fallen in love with a one-night stand?',
  'Who is most likely to split the bill down to the cent on a first date?',
  'Who is most likely to have accepted a date just for the free food?',
  'Who has arranged a fake emergency call from a friend to escape a date?',
  'Who is most likely to talk about their ex on a first date until it gets awkward?',
  'Who is most likely to interrupt a date just to check the game score?',
  'Who is most likely to have spilled food on their outfit on a first date?',
  'Who is most likely to text right after a date, before the front door even closes?',
  'Who is most likely to fall asleep in the middle of a date?',
  'Who has been on a date where the other person brought someone along uninvited?',
  'Who has had a date who looked totally different in real life than in their photos?',
  'Who is most likely to try to impress a date with a presentation about themselves?',
  'Who is most likely to agree to a second date out of politeness after a bad first one?',
  'Who is most likely to swipe out of boredom on the toilet?',
  'Who has come across a family member on a dating app?',
  'Who is most likely to message a match with a self-written poem?',
  'Who has spotted a match at the supermarket and hidden behind a shelf?',
  'Who is most likely to have seen someone from this group on a dating app?',
  'Who is most likely to open with just "Hey" and then wonder why nobody replies?',
  'Who is most likely to send screenshots of dating chats to the group chat?',
  'Who has had an app date who turned out to be an old classmate?',
  'Who here is the worst at noticing when someone is flirting?',
  'Who has flirted abroad using only hand gestures because there was no common language?',
  'Who is most likely to flirt at a parent-teacher meeting?',
  'Who is the most embarrassing drunk flirt?',
  'Who is most likely to have flirted with a delivery driver?',
  'Who here has flirted on LinkedIn?',
  'Who is most likely to send a drink to a stranger at the bar?',
  'Who has flirted with someone while their partner was in the same room?',
  'Who is most likely to flirt with someone who just asked for directions?',
  "Who is most likely to have gotten someone's number in an elevator?",
  'Who is most likely to kiss with way too much tongue?',
  'Who had the most embarrassing first kiss?',
  "Who is most likely to kiss a stranger at midnight on New Year's Eve?",
  'Who has gotten tangled up with braces or a piercing while kissing?',
  'Who is most likely to stage a movie-worthy kiss in the rain?',
  'Who is most likely to have made out with garlic breath?',
  'Who here has kissed someone because of a bet?',
  'Who has kissed someone and regretted it that very second?',
  'Who is most likely to make out through the whole movie at the cinema instead of watching it?',
  'Who had their first kiss the latest?',
  'Who is most likely to have made out at the top of a Ferris wheel?',
  'Who is most likely to kiss on the lips when saying goodbye, even though a hug would have done?',
  'Who is most likely to give kissing lessons?',
  'Who has kissed the most people in a single night?',
  'Who is most likely to go all in on the kiss cam at a stadium?',
  'Who is most likely to have made breakfast after a one-night stand?',
  'Who has had a one-night stand on vacation?',
  "Who has woken up at someone's place without knowing what part of town they were in?",
  'Who is most likely to have left something important behind after a one-night stand?',
  'Who has done the walk of shame on a Sunday morning?',
  'Who is most likely to do the dishes after a one-night stand?',
  'Who is most likely to have run into a one-night stand at work later on?',
  'Who is most likely to hook up with a neighbor?',
  'Who is most likely to be the friends-with-benefits type?',
  'Who is most likely to have had an affair that lasted longer than some relationships?',
  'Who is most likely to end a friends-with-benefits thing because feelings got involved?',
  'Who is most likely to move in together after just three weeks?',
  "Who is most likely to have secretly gone through their partner's phone?",
  'Who here is the most jealous in a relationship?',
  'Who is most likely to propose in front of a huge crowd?',
  'Who has broken up with someone and called them again the next day?',
  "Who is most likely to get their partner's name tattooed?",
  'Who uses the most embarrassing pet names in relationships?',
  'Who has ended a fight in bed instead of with words?',
  'Who is most likely to jump straight into the next relationship after a breakup?',
  'Who is most likely to still have gifts from their ex in the closet?',
  'Who has won back an ex?',
  'Who here is most likely to date someone twenty years younger?',
  'Who falls in love the fastest?',
  'Who is most likely to say something totally inappropriate when meeting the in-laws for the first time?',
  'Who is most likely to get spontaneously married in Las Vegas?',
  'Who is most likely to say "I love you" after just one week?',
  'Who is most likely to keep a secret list of all their past hookups?',
  "Who is most likely to date their sibling's ex?",
  'Who is most likely to go completely wild at a bachelor or bachelorette party?',
  "Who is most likely to claim it wasn't flirting, just being friendly?",
  'Who has a celebrity free pass officially agreed on in their relationship?',
  'Who has been on a date with someone who turned out to be taken?',
  'Who is most likely to get jealous when their date laughs with the server?',
  'Who is most likely to have sex on the beach, even with sand everywhere afterwards?',
  "Who has had sex at their parents' place while the parents were home?",
  'Who is most likely to have checked the time during sex?',
  'Who has had shower sex that turned into more of a slip-and-slide?',
  'Who is most likely to squeeze in a quickie on their lunch break?',
  'Who is most likely to have had sex at the office?',
  'Who is most likely to have had a laughing fit during sex?',
  'Who is most likely to fall asleep right after sex?',
  'Who is most likely to want to order pizza right after sex?',
  'Who has had sex even though their train was leaving in ten minutes?',
  'Who is most likely to show off about a newly learned position?',
  'Who has driven to a gas station in the middle of the night because there were no condoms at home?',
  'Who is most likely to be into morning sex?',
  'Who is most likely to try sex on a running washing machine?',
  'Who is most likely to have talked more than actually done anything in bed?',
  'Who is most likely to check their smartwatch for calories burned after sex?',
  'Who is most likely to make up their own names for positions?',
  'Who is most likely to have had sex on the kitchen table?',
  "Who has had sore muscles that didn't come from working out?",
  'Who is most likely to have fallen out of bed during sex?',
  'Who has had sex while their pet was watching?',
  'Who is most likely to have had sex with their socks on?',
  'Who is most likely to spend an entire weekend without any clothes on?',
  'Who is most likely to vacation at a nude beach?',
  'Who has gone skinny-dipping at night?',
  'Who is most likely to have nudes on their phone that were never sent?',
  'Who would be the first one naked at strip poker?',
  'Who is most likely to rehearse a striptease for their partner?',
  'Who is most likely to have gotten a lap dance?',
  'Who has the biggest collection of sex toys?',
  'Who is most likely to bring a sex toy as a Secret Santa gift?',
  'Who is most likely to have ordered a sex toy that got delivered to the neighbors?',
  'Who is most likely to bring a blindfold into play?',
  'Who has the wildest fantasy that nobody here knows about yet?',
  'Who is most likely to have had a naughty dream about their boss?',
  'Who is most likely to wear a uniform in the bedroom?',
  'Who is most likely to enjoy a slap on the butt?',
  'Who is most likely to use Fifty Shades of Grey as a manual?',
  'Who is most likely to overdo the eggplants and peaches when sexting?',
  'Who is most likely to have spilled massage oil all over the sheets?',
  'Who is most likely to bring whipped cream into the bedroom?',
  'Who is most likely to book a tantric massage?',
  'Who is most likely to book a weekend at an erotic hotel?',
  'Who is most likely to be into bondage?',
  'Who is most likely to hang a mirror over their bed?',
  'Who is most likely to try an app-controlled toy?',
  'Who is most likely to take charge in bed?',
  'Who would rather be seduced in bed than make the first move?',
  'Who is most likely to buy lingerie that costs more than a week of groceries?',
  'Who is most likely to be wearing matching underwear today, just in case?',
  "Who is most likely to have left their underwear at someone's place?",
  'Who is most likely to suggest a totally unsexy safe word?',
  'Who is most likely to watch adult films "just for the plot"?',
  'Who is most likely to have the most embarrassing browser history?',
  'Who is most likely to turn red when a sex scene comes on while watching TV with their parents?',
  'Who is most likely to start an OnlyFans account?',
  'Who is most likely to pick a Halloween costume that really belongs in the bedroom?',
  'Who is most likely to sext on their work laptop?',
  'Who is most likely to have had phone sex?',
  'Who is most likely to have farted during sex?',
  'Who is most likely to have gotten hungry in the middle of foreplay?',
  'Who has been overheard having sex by their roommates and got laughed at the next morning?',
  'Who is most likely to have struggled hopelessly with a bra or a belt?',
  'Who has fallen over while undressing because their pants got stuck?',
  'Who is most likely to have answered a phone call during sex?',
  'Who has broken a pair of glasses while making out?',
  'Who has had a condom emergency that everyone laughs about today?',
  'Who has fallen asleep while making out on the couch?',
  'Who is most likely to have tried to be seductive and tripped instead?',
  'Who has been seen through the window by the neighbors in a compromising situation?',
  'Who is most likely to have accidentally sent a very suggestive voice message?',
  'Who has been approached by the police while making out?',
  'Who is most likely to have given a compliment during sex that came out totally wrong?',
  'Who has made noises in bed that still embarrass them today?',
  'Who is most likely to have seen a text from their mom on the lock screen during sex?',
  'Who is most likely to wear their underwear inside out and only notice while undressing?',
  'Who is most likely to keep falling for the same type of person?',
  'Who is most likely to go weak at the knees for a deep voice?',
  'Who is most likely to follow a stranger because of their perfume?',
  'Who is most likely to have a secret crush on someone at the gym?',
  'Who has the weirdest red flags when it comes to dating?',
  'Who is most likely to ignore every red flag as long as the person is hot?',
  'Who is most likely to have the most red flags when dating?',
  'Who is most likely to have had a crush on someone in this group?',
  'Who in this group would make the best date?',
  'Who in this group would be the biggest surprise in bed?',
  'Who in this group has the most secret admirers?',
  'Who is most likely to play Cupid for the whole friend group?',
  'Who is most likely to have slept with someone from the friend group and kept it secret?',
  'Who is most likely to go home with a complete stranger tonight?',
  "Who knows the most about everyone else's hookups here?",
  "Who is worst at keeping secrets about other people's love lives?",
  'Who is most likely to share way too many details about their own sex life?',
  'Who is most likely to blush the moment sex comes up?',
  'Who is most likely to have the most active love life in this group?',
  'Who is most likely to write a book about their love life?',
  'Who is most likely to test their relationship on Temptation Island?',
  'Who is most likely to listen to sad songs for days after a heartbreak?',
  'Who is most likely to have drunk-called their ex?',
  'Who is most likely to hide a crush for years?',
  'Who has been turned down in a way that really hurt?',
  'Who is most likely to turn people down in the most charming way?',
  'Who is most likely to have given someone a fake number?',
  'Who is most likely to place a personal ad in the newspaper?',
  'Who is most likely to show up at a singles party wearing a traffic light wristband?',
  'Who is most likely to have kissed a stranger at a bachelor or bachelorette party?',
  "Who is most likely to go overboard with roses and candles on Valentine's Day?",
  "Who is most likely to flirt with the guests at an ex's wedding?",
  "Who is most likely to have gotten the tour guide's number on vacation?",
  'Who is most likely to hook up with their ski instructor on a ski trip?',
  'Who is most likely to say openly what they like in bed?',
  'Who is most likely to talk about feelings right after sex?',
  'Who is most likely to ask "How was it?" after the first time?',
  'Who is most likely to insist on spooning every night?',
  'Who is most likely to steal all the covers in bed?',
  'Who is most likely to leave their toothbrush behind after the first sleepover?',
  'Who is most likely to leave something behind on purpose after a date to have a reason to meet again?',
  "Who is most likely to have kept a date's shirt?",
  'Who is most likely to always carry a condom in their wallet?',
  'Who is most likely to have dropped a condom in front of their parents?',
  'Who is most likely to blush while buying condoms at the pharmacy?',
  'Who is most likely to greet a hot date in sweatpants?',
  'Who is most likely to make out in the bathroom at a party?',
  'Who is most likely to have made out in a stairwell?',
  'Who is most likely to pick someone up at après-ski?',
  "Who has had a crush on a friend's parent?",
  'Who is most likely to send a voice message in their bedroom voice?',
  'Who is most likely to type out a message to their crush and then delete it?',
  'Who is most likely to check twenty times whether their crush has seen their story?',
  'Who is most likely to have posted a story for just one person?',
  'Who is most likely to post a thirst trap?',
  'Who is most likely to have blocked someone and unblocked them a week later?',
  'Who is most likely to write a pro-and-con list about a date?',
  'Who is most likely to have kept a relationship secret from their friends?',
  'Who is most likely to have visited a vacation fling back home later?',
  'Who is most likely to leave a party without saying goodbye, but not alone?',
  'Who has the best poker face when it comes to their love life?',
  'Who is most likely to always pick dare in Truth or Dare just to kiss someone?',
  'Who would have to drink the most in Never Have I Ever?',
  'Who is most likely to bring a naughty card game to game night?',
  'Who is most likely to save dates in their phone under nicknames like "Bar Friday"?',
  'Who is most likely to offer a massage that turns into more than just a massage?',
  'Who is most likely to sleep naked?',
  'Who is most likely to accidentally open the door for a delivery driver in their underwear?',
  'Who is most likely to have a crush on the person who makes the coffee every morning?',
  'Who is most likely to let their parents set them up on a blind date?',
  'Who is most likely to tag along as a wingman and end up going home with someone themselves?',
];
